### ISSUE TITLE
AD groups in trusted domain not available

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1000]
> All of our servers are in different, trusted domain [SERVERDOMAIN]. This includes our Octopus server.

> Our users are able to successfully login with userdomain\user without any problems. However, I cannot leverage the new AD Groups feature for teams for groups inside of that trusted domain USERDOMAIN. I cannot search or pick those groups. Is there any work around?

Source: http://help.octopusdeploy.com/discussions/problems/21797

**Comment by PaulStovell** [comment]
Will be fixed by https://github.com/OctopusDeploy/Issues/issues/1737
