### ISSUE TITLE
SSH deployments

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#1002]
Provide a Tentacle-like experience for deploying to agentless machines (generally running Linux) using SSH.

Ideally this would be as automatic and hands-off as possible, so that when machines are added and removed in cloud deployments we have a solid, friction-free process.

**Comment by zentron** [comment]
Testing
* API Tests currently hit a set of dedicated micro machine targets. Using Cygwin as a ssh host requires setting up local machine user accounts which is not ideal for development and the setup script starts to become a little heavy.
* Calamri is the only project that requires actual unit testing to be performed on the linux machine and a set of dedicated servers has been provisioned with TC build agents for this purpose.

**Comment by zentron** [comment]
Details about the paths utilized on the linux machine can be found at http://docs.octopusdeploy.com/display/IN/SSH+endpoint+footprint
