### ISSUE TITLE
 Variables: Import/export as CSV (Octopus-Tools)

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1045]
It's not fun to deal with lots of variables. See [this discussion](http://help.octopusdeploy.com/discussions/suggestions/24-variable-management-and-release-cleanup) for example.

Instead of building an all-singing, all-dancing, bulk variable editor, let's just provide the ability to export variables to CSV, edit them, and import them again. Then people can use Excel or Vim or whatever they like. 

Comment from @jamescrowley
This would be nice, especially as you can't even seem to copy + paste the entire table from the web interface at the moment?

Comment from @barbrawalton
Any update on this one? I, too, have a ton of variables, and it's really hard to manage them with the existing interface.

**Comment by worldspawn** [comment]
I got 91 variables to enter for two different environments. This is so horrible!! Theres no import feature but you've closed this issue, why?
