### ISSUE TITLE
octo.exe - how to send custom variables?

### ISSUE THREAD

**Issue by dotnetwise** [OctopusDeploy/Issues#1149]
`octo.exe --set-myvarname=123` 
How to send custom parameters / variables to a new deployment via `octo.exe`?

I can see there is `-v` or `--variable=key:value` but there are no real examples of how to use it

**Comment by mivano** [comment]
Found this thread while trying to find out how these variables work and I noticed that this does not work when the variable is defined in a library. Is that correct? When I place the same variable in my project it works fine, but the variable inside a referenced library is not picked up. 

It is also not picked up when I use a create-release, use the --deploy option and pass in a variable. Does not matter if defined inside project variables or as a library variable, it will not pick up the value I pass in. 

Is this intended behaviour?

These variables are all prompted variables btw.

**Comment by dazinator** [comment]
From using Octopus Deploy Command Line Tool, version 2.6.3.59, 
I think this command may actually be wanting the variable's label value.. not name.

When i changed the variable's label to match the variable name, then `octo deploy-release -v myvariablename:123` worked. When i had the label set to something else then  `octo deploy-release -v myvariablename:123' failed - and octo.exe printed the variable's label value to the log when it complained that it needed a value for the prompted variable - not the variable name.

**Comment by dazinator** [comment]
@dotnetwise would this suggested feature help with this: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/8864836-custom-release-properties-like-team-city-build-id
