### ISSUE TITLE
start process in background but don't wait

### ISSUE THREAD

**Issue by dotnetwise** [OctopusDeploy/Issues#1154]
In previous versions we could do 

``` batch
start /b node job....
```

That would mark the build  with `success` before the actual `job` would finish.

However in the last version of `octopus` (`2.5`) this doesn't happen anymore. The octopus tentacle waits and waits until the `job` will exit.

How can we avoid that?

**Comment by dotnetwise** [comment]
@PaulStovell hello??

**Comment by ccamburn** [comment]
@dotnetwise 

For what it's worth, I haven't tested this in regards to success in the current deployment, but I used this to run a script that shuts down the tentacle, performs some tasks, and restarts it. This might allow your deployment to end and continue in the background.

$argument = "-executionpolicy bypass $PathToScript"

start-process powershell -NoNewWindow -RedirectStandardOutput $OutFile -RedirectStandardError $OutError -argument "-executionpolicy bypass $Script"
