### ISSUE TITLE
Windows Service - small time window between service stop and process exit

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#1167]
It seems that there's a small delay between a service stopping and its process unloading, thus the "Purge files" option of "Custom installation directory" may fail even on a graceful service shutdown (#601).

We can either sleep, retry, or monitor the service process itself at various points in the deployment to mitigate this.

Ideally we'd identify and track the service's PID during the pre-deployment service stop phase.

**Comment by PaulStovell** [comment]
Fixed in 3.0.2!
