### ISSUE TITLE
Special Characters in passwords causing issues

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1172]
I have a password that ends in # and it fails. I have a template that I'll soon be contributing to the library to Uninstall a TopShelf and another Install it. The abbreviated code for the install looks like this:

`$svc = Get-ChildItem –Path "$svcDir/*.exe"`
`$commandArgs = @('install', "-username:$username", @"-password:$password")`
`& $svc $commandArgs`

If I run that from PowerShell directly it works fine but in my step template it fails. When I write the command out to the host Octopus drops the # character to a new line:

```
16:06:52 Info | Using username $username with password $password
16:06:52 Info | Executing: & 'VE.VMF.OfflineMachineMonitor.exe' install -username:MyServiceAcct -password:mypassword123
16:06:52 Info | #
```

Second example

I was just trying to set up a Windows Service deploy running as a Custom user (and password), and got an error that the service couldn't be started.

When I went to the machine that this was on and tried starting the service again, it failed with "Login failed."
I manually updated the service Login information (updating the password only), hit OK, hit start and the service started.
So I copied and pasted the password back into Octo and ran through the process again and again got the failure. Tried pasting that same password into the login on the service and again the service started.

Did several variations of this, trying variables, trying entering it directly, all with no luck.
Finally tried switching around the password. The two characters that I've seen that seem to cause issues in the password are the hashtag (#) and double quote ("). If I updated the password by removing those (in AD and in Octo), the deploy works.

Source: http://help.octopusdeploy.com/discussions/problems/24111

**Comment by vanessalove** [comment]
Way to replicate this issue:

We’ve since regenerated all our service passwords to be alphanumeric to avoid this problem, so I can’t give you an actual password, but simply enough, make one that has a # in the middle of it.

What we were trying to do, same as the original poster, was to set the username/password for a windows service to run under. The powershell script to do this is this:

$plogsvc = gwmi win32_service -filter "name='$servicename'" $plogsvc.change($null,$null,$null,$null,$null,$null,"$username","$password")

$servicename, $username, and $password were constructed out of variables, resulting in values like: $servicename = “AOC PLog Queue Service XYZ” $username = “XYZDemoAppUser” $password “abcd#1234”

The script would run with no problems, the username/password seemingly set for the service. But the service would not start (a later project step), reporting a problem with the credentials. If we were to then manually enter the password on the server for the windows service, it would be able to start up correctly.
------------------------
Apologies for not responding sooner, but much like Mike Jacobs, I have long since regenerated the passwords, and I hadn't planned on replying until I had a chance to validate whether it was fixed. However as I noted in the original note, the two culprits I saw were the pound sign (#) and double quotes (").

I was doing this with a service account like Mike said, but I wasn't using custom powershell. I was using a variable (sensitive option checked) to fill it in on the deploy step with the Windows Service: Startup configure option checked.

(see original source)

**Comment by vanessalove** [comment]
@damianmac what version was this in its not referenced on the milestone?
Could it include a fix for > char?

**Comment by vanessalove** [comment]
@damianmac what version was this in its not referenced on the milestone?
Could it include a fix for > char?

**Comment by gap736uk** [comment]
Just to flag other characters that cause issues that I've just hit: `%` and `@` - basically seems to be issues with such characters in URL strings used to get to the Git Repo when attempting to deploy stuff.

**Comment by slandsaw** [comment]
Experiencing the same kind of issue in Octo 3.17.2. [Guidance ](https://octopus.com/docs/deployment-process/variables/sensitive-variables#Sensitivevariables-HowOctopushandlesyoursensitivevariables) seems to suggest avoidance of special characters. This is a bummer because some folks have no control over what a password will be for a service account for example.

**Comment by js0505** [comment]
using 2018-2-6 still has same issue. I have found that using ` causes a problem in the cmd. I have found a way to manually set it by running cmd /S /C however I cannot seem to find a way to have Octopus run like that.

**Comment by JBYeti** [comment]
We are using version 3.17.4 and are experiencing the issue with special characters (our current one has an occurrence of each of the following symbols: +[?#).  I found if I move the script from the package we import into Octopus to putting the contents of the PowerShell script directly into the deployment process step then the issue does not occur.  We can also run the PowerShell script from the command line on the server and it works there as well.
