### ISSUE TITLE
Environment variable viewing permissions w/ multiple environments scoped

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1178]
A variable assigned to an accessible environments is hidden if also assigned an inaccessible environment 
If Variable A is declared in Environment 1 and 2. User 1 has access to Environment 1 but not Environment 2. User 1 can not see Variable A at all. 
Screenshot 'with access to both env.png' shows the set of variables available when team has access to both environments, where as 'with access to only one env.png' show the result of removing environment 'AT Prod' from the team.

Source: http://help.octopusdeploy.com/discussions/problems/24082

**Comment by DamianMac** [comment]
After further discussion we've decided to leave this behavior as is. Users shouldn't be able to see variables which are scoped across environments they don't have permissions to view. A workaround is to create a new role and team with the correct variable view permissions.
