### ISSUE TITLE
Binding UI breaks when variable filtering used in variables or bound variables

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1193]
Using #{Environment | ToLower} as a bound variable inside the hostname of IIS bindings breaks the UI 

Source: http://help.octopusdeploy.com/discussions/problems/24512

**Comment by AlexRetzlaff** [comment]
Thanks guys!

**Comment by DmitryLobanov** [comment]
Not fixed :( We have hit it on 2.6.0 just today. What are we doing wrong?

**Comment by vanessalove** [comment]
I can confirm that when you use a bound variable, it does not work in the bindings. I get a powershell error because the variable never expands.

**Comment by drusellers** [comment]
I have experienced this issue as well. Watching. :)

**Comment by PaulStovell** [comment]
Using these filters should now work in 3.0. Need to test whether the |'s cause the before script to fail though.

**Comment by drusellers** [comment]
yay

**Comment by Damovisa** [comment]
Tested on 3.0 and this now works correctly.
