### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1222]
1. Make it possible to register multiple authentication providers
2. Add support for LDAP authentication

This should allow us to support teams with multiple AD servers, as well as companies that use OpenLDAP.

LDAP support will need plenty of configuration options to match this:

https://confluence.atlassian.com/display/CROWD011/2.2.2.1+Microsoft+Active+Directory
https://confluence.atlassian.com/display/CROWD011/2.2.2.3+OpenLDAP
http://confluence.jetbrains.com/display/TCD8/Typical+LDAP+Configurations

**Comment by michaelschnyder** [comment]
I really like this feature!

I would be nice if we could register an JWT Issuing Provider. I don't think that you should integrate with tall these various OAuth-Providers directly. As long as Octopus could understand a SAML/JWT based tokens (which basically every OWIN-based app can), this would be great. The integration of IdP should be done in an ACS (have a look at ThinkTectures ones: https://github.com/IdentityServer/Thinktecture.IdentityServer3)

**Comment by Stevenpuddephatt** [comment]
Hi,  is there any expected release for the ability to point to a different AD server?

Regards,
Steven

**Comment by PaulStovell** [comment]
Will be fixed when we do this: https://github.com/OctopusDeploy/Issues/issues/1737
