### ISSUE TITLE
Incorrect spelling of variable IgnoreConfigTranformationErrors

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1225]
Typo in `Octopus.Action.Package.IgnoreConfigTranformationErrors` word transformation missing s.
Can we add another with correct spelling and make both work. Customers are typing it with correct spelling and it is not working.

Source: http://help.octopusdeploy.com/discussions/problems/23038

**Comment by Damovisa** [comment]
As variables are now just in a string->string dictionary, it'll be hard to alias in any meaningful way.

We could either create a duplicate in this case and check both, or just correct and deprecate the old spelling for 3.0?

If we use a duplicate, it might be worthwhile overloading the `GetFlag` method in `Octostache.VariableDictionary` to accept a param array of aliases so the calling code is a little cleaner.

**Comment by PaulStovell** [comment]
We can fix the typo, then map the old name to the new one like this:

```
MisspelledVariable = #{CorrectltySpelledVariable}
```

**Comment by Damovisa** [comment]
Actually (thanks to @mjrichardson for the solution), we can just "correct" the variable at the server when creating the manifest and send the correctly-spelled one to Calamari. Calamari won't need to know about the misspelled one then.
