### ISSUE TITLE
Add Octopus.Machine.Hostname variable

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1228]
Currently we only expose Id, Name, and Roles. This is to expose Hostname as a variable in Octopus. 
This should only be for listening tentacles.
Source: http://help.octopusdeploy.com/discussions/problems/24053

**Comment by twirls** [comment]
Is this implemented?

**Comment by alfhenrik** [comment]
Hi @twirls,

Yes, this has been implemented. 

You can access the machine name like this `$OctopusParameters["Octopus.Machine.Hostname"]` **but** it is only available on `listening` Tentacles.

Thank you,
Henrik

**Comment by rbonestell** [comment]
I'm looking to include the deployment target hostnames in a notification with powershell in a step template, right now I'm using `$OctopusParameters['Octopus.Deployment.Machines']` but that returns machine IDs within Octopus (E.g. `Machines-5,Machines-6`). Is there an equivalent OctopusParameter which would provide the hostnames for the machines to which the release was deployed? (E.g. `TESTWEBSRV01, TESTWEBSRV02`)

**Comment by dopsy** [comment]
@rbonestell 

For such tasks where it requires to go more deeper to get something that by default Octopus doesn;'t provide, you have to use octoposh powershell module or Octopus.Client.dll by initiating connection to Octopus REST API. One of the examples - https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/REST/PowerShell/Targets/GetMachinesInCurrentEnvironmentOfSpecificRole.ps1 

So you have few options:

Using same parameter - $OctopusParameters['Octopus.Deployment.Machines'] to get the machine-id's of servers to which you are deploying your release to. Assign it to variable $b for example. 

$b = "$OctopusParameters['Octopus.Deployment.Machines']" 

Then, using octoposh module(https://github.com/Dalmirog/OctoPosh), do something like this:

```
$APIKey = 'API-*************'
$null = Set-OctopusConnectionInfo -URL 'http://******' -APIKey $APIKey
$header = @{
  'X-Octopus-ApiKey' = "$APIKey"
} 

$b = "$OctopusParameters['Octopus.Deployment.Machines']" 
$a = Get-OctopusMachine

foreach ($id in $b)
{
   #You will get table with all information about machine
    $c = $a | where ID -EQ $id

   #Now we extract just the Name(hostname)
    $c.Name
}
```

You can also achieve the same using octopus.client.dll file. **This way is much faster:**

```
Add-Type -Path 'C:\Octopus.Client.dll'

$URL = 'http://*****'
$APIKey = 'API-**********'

$connection = new-object Octopus.Client.OctopusServerEndpoint "$($URL)","$($APIKey)"
$repository = new-object Octopus.Client.OctopusRepository $endpoint 
$b = "$OctopusParameters['Octopus.Deployment.Machines']" 
$a = $repository.machines.FindAll()

foreach ($id in $b)
{
    $c = $a | where ID -EQ $id
    $c.Name
}
```

**Comment by clottman** [comment]
Why is this only for listening tentacles? It would be really helpful for polling tentacles, too.
