### ISSUE TITLE
Allow Octopack to not publish packages as artifacts to keep them out of TC feed

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1229]
Octopack currently when embedded in TC publishes the packages as artifacts so they show in the TeamCity feed. We need a variable to stop this behaviour.

Source: http://help.octopusdeploy.com/discussions/problems/25199

**Comment by PaulStovell** [comment]
Going to close this now in favour of Steven's suggested workaround. If we get more time hopefully we can revisit.

**Comment by dazinator** [comment]
Can we revisit this one yet?
