### ISSUE TITLE
Project setting screen - release versioning not showing properly saved in UI

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1245]
When you go into a projects settings and select " Use the version number from an included NuGet package" and save it, when you go back to the project settings screen it is showing as the default and not the saved value. 

Source: http://help.octopusdeploy.com/discussions/problems/25561

**Comment by developerxnz** [comment]
We are running Octopus Deploy 2.6.5.1010 and this issue still seems to be active? Can anyone else confirm this?

**Comment by michaelnoonan** [comment]
Hi @developerxnz. Thanks for getting in touch! The best way to get help with this kind of thing is via https://octopus.com/support. Hope that helps! Mike
