### ISSUE TITLE
Retention policy is unusable on live environments

### ISSUE THREAD

**Issue by dotnetwise** [OctopusDeploy/Issues#1246]
As per issue https://github.com/OctopusDeploy/Issues/issues/841 

If you apply ANY retention policy, you can only apply to a `project group` level, and not `per environment` level.
![image](https://cloud.githubusercontent.com/assets/485535/4612067/b1da17e8-52c2-11e4-9a00-f0e003d9e4d3.png)

Hence you cannot specify to apply a different policy on `LIVE` / `Production` environments.
That means, after e.g. in my case 5 releases, the releases will be deleted from LIVE.

Octopus Team, that is a show stopper! :bomb:  
We have had this stupid problem where we've lost older code/deployments on live and wasted hours to restore them.

We have tweaked the `postDepoly.ps1` script to rename the folder after the deployment by adding a zombie background script that would rename it after the actual deployment completes and then update the websites and services to the new path accordingly.

However this is a NO GO, for us.
We DO FEAR that any future releases of octopus can _accidentally_ delete the releases.

Besides the way that it does the actual drop of the "old releases" is really bad. 
e.g. Instead of deleting the folder itself, it goes inside and deletes its content.

This is dumb. For example: 
If we renamed the folder and created a symbolic link with the original name, instead of deleting the symbolic link it  deletes the content from it and then the symbolic link itself.

I am sorry for the upset language above, but just think of what we've been through because of this.
And is still not resolved after so many releases!

**Comment by dotnetwise** [comment]
so is it fixed?

**Comment by vanessalove** [comment]
@dotnetwise Lifecycles now define the retention policies behavior. Which means you can set it per environment. - As Paul mentioned in his previous comment.
