### ISSUE TITLE
TeamCity cannot create a release when package uses scoped variable

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1249]
Hi

We are using Teamcity to produce two NuGet packages for our website. Once is a build using the Debug build configuration and one is built using the Release configuration. This is because we deploy the ProjectName.Debug package to our Dev environment and the ProjectName.Live package to the Live/Production servers.

So we have the following build artefacts:

ProjectName.Debug-1.0.1.nupkg
ProjectName.Live-1.0.1.nupkg
We then are using the TeamCity step "Create Release" to run Octopus which has a "Process Step" of "Deploy NuGetPackage" which have configured using the following in the NuGet Package ID field:

ProjectName.#{Octopus.Environment.Name}

We are getting an error message in the TeamCity build log of "The version number for step 'ProjectName' cannot be automatically resolved because the feed or package ID is dynamic".

This issue on GitHub seems to indicate that this is possible https://github.com/OctopusDeploy/Issues/issues/671 but it does not work for us.

Any ideas?
We are essentially trying to deploy the Debug package to our Dev environment and the Release package to the Live environment.

Source: http://help.octopusdeploy.com/discussions/problems/25709

**Comment by Tho77** [comment]
Is there any update on this issue?
Without being able to use a variable in the Nuget Package ID field, I can work around it by following these steps in this exact order:
- build Debug Teamcity build
- run Octopus Debug Release
- build Live Teamcity build (overwrites Teamcity Nuget packages with Live version)
- run Octopus Live Release

Problem is I actually have more environments in between, and if I mistakenly do one step out of order, my Octopus Live Release can end up pulling my Debug Teamcity Nuget packages from the feed.

**Comment by Tho77** [comment]
Went through the code and found that PackageVersionResolver.cs was not picking up the version number, even though Teamcity was passing in the --version parameter.
Once I passed in --packageversion with the exact same build number, the Octopus release worked.

So now I can use the system.OctoPackAppendToPackageId in my Teamcity OctoPack build and it will follow through to the Octopus release creation.
