### ISSUE TITLE
Tasks get stuck in Waiting state.

### ISSUE THREAD

**Issue by RenEvo** [OctopusDeploy/Issues#1253]
We have a manual intervention step as the first step that will prompt once the packages have been uploaded to our servers. This allows us to "pre-stage" the binaries before doing the rolling installs on the actual services.

After it is in the "Waiting" state. Going into the task in the "Waiting" state, assigning the intervention to yourself, and aborting instead of proceed will keep it in the "Waiting" state indefinitely, instead of an "Aborted" or "Canceled" state.

![image](https://cloud.githubusercontent.com/assets/1626559/4666926/0328eda8-5558-11e4-8d75-45120f89d7d0.png)

*image scrubbed of internal names/users.

**Comment by DamianMac** [comment]
This will be fixed in 3.0, we've totally changed a lot of the underlying architecture for this.
