### ISSUE TITLE
Support database deployment steps

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#126]
Create a convention for deploying database changes, using DbUp, and a special step type for it. 

Users will be told to create a NuGet package containing the scripts they want to execute. The scripts will need to be numbered sequentially, for example:

```
Script0001-Create user table.sql
Script0002-Split fullname into first and last.sql
Script0003-Create order table.sql
```

The convention will then execute a special build of DbUp over the directory after extracting it. 

The step definition will allow you to specify:
- Connection string (referencing any variables, e.g., server name, password)
- Name of the versions table
- (Maybe) Whether to create a backup of the database first

This isn't going to work for 100% of the database deployments out there, but it will probably do fine for 80% of them.

**Comment by dazinator** [comment]
what happened.. :(
