### ISSUE TITLE
[All] pages within Octopus crash when left open for extended periods - potential memory leak

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1265]
Several pages (not just dashboard) often crash in both Chrome and Firefox when left idle for extended periods. Almost always when I come into the office in the morning an Octopus page has crashed in a browser tab.

The octopus dashboard is up on the screens of many users in our company; executives in addition to engineers. In their eyes, Octopus (the service we rely on to deploy our software) crashes daily.

Im aware its just a js client leak and is not indicative of the server's stability, but you can see how its important the crash is addressed.

Source: http://help.octopusdeploy.com/discussions/problems/26008

**Comment by PaulStovell** [comment]
Going to close this, we weren't able to get to the bottom of it, but we now do occasional full-page refreshes so this should be less of an issue.

**Comment by drewfreyling** [comment]
FYI this still happens.
