### ISSUE TITLE
Project with custom feed expression cannot be imported using octo.exe

### ISSUE THREAD

**Issue by ptugarin** [OctopusDeploy/Issues#1270]
I have a project which contains an environment variable in custom feed expression, and when the project is exported using octo.exe, the NuGetFeeds section contains a null feed.
"NuGetFeeds": [
    {
      "Id": null,
      "Name": null
    }

This project cannot be imported using octo.exe feature because I get a "NuGet does not exist" error

Octopus tentacle version: .2.5.10.39
Octopus server version: 2.5.11.614

**Comment by PaulStovell** [comment]
The new import/export tool coming in Octopus 3.0 fixes this
