### ISSUE TITLE
Variables in variable sets scoped to roles missing after 2.5.10 upgrade

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1276]
We have an issue sometimes where a variable doesn't come through in the release, the variable exists (in a variable group) and it should be there. To get round the issue, we duplicated the variable and recreated the release.

We're having a problem that sounds similar. It started after we upgraded to version 2.5.10 of the Octopus server. I reviewed all the variables that are missing from the releases, and it appears that any variables that are scoped to a role instead of an environment are missing.

UPDATE: I did a test to see if any of the other scope types (machine, step) had the same problem. All of our variables come from a shared library variable set instead of in the project itself, so I added a few test variables and saved the variable set. I then recreated the project release, and all the new test variables as well as all of the old variables that had been missing are now showing up. It looks like something got out of sync during the 2.5.10 upgrade, but saving a new version of the library variable set cleared it up.

2 user reports
Source: http://help.octopusdeploy.com/discussions/problems/25986

**Comment by aaronasmith** [comment]
I had this issue after importing a project and a release but with variables scoped to a step.  I'm going through removing/readding the steps and saving the variables and then updating the variables for the release.  This seems to be fixing the problem for now.

**Comment by PaulStovell** [comment]
This issue was down to some Raven indexes being out of date and then data being missing because of the indexes - in the latest 2.6 we now wait for non-stale results before making the snapshots, so this is fixed.
