### ISSUE TITLE
Update Azure to use newer cmdlets

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1385]
We are deploying a cloud service comprising of worker and web roles to Azure using Octopus. Our custom DeployToAzure.ps1 Powershell script uses newer Azure cmdlets such as New-AzureSchedulerJobCollection (see http://msdn.microsoft.com/en-us/library/azure/dn759640.aspx) which are not supported with the Azure module packaged up with the Octopus Tentacle.

Source: http://help.octopusdeploy.com/discussions/problems/27695

**Comment by vanessalove** [comment]
Second ticket: http://help.octopusdeploy.com/discussions/problems/29367

**Comment by richardp-au** [comment]
Do you have a timeline for this? I need it urgently because I can now no longer deploy via Octopus. I had to remove the load balancer config from the .csdef file to allow Octopus to deploy it again for test environments. This means I now need to customise the .csdef and rebuild manually to deploy a version with the load balancer config in it.

The workaround mentioned in #1444 doesn't seem to work, as detailed in that issue.

**Comment by quezlatch** [comment]
Is there a way to work around this, while it is being fixed? we had previously been able to modify the BootstrapDeployToAzure.ps1, but this no longer works. we cannot deploy until there is some sort of resolution to this

**Comment by DamianMac** [comment]
@richardp-au @quezlatch 
What path did you modify the bootstrap powershell file in ? If you've done a tentacle upgrade lately you'd need to find the newer file. It should be somewhere like drive:\Octopus\Applications\.SQ-yoursquid\Octopus.Tentacle\2.6.?\Scripts\

We need to upgrade our powershell dependencies but I'm hoping there's a shorter term workaround for you.

**Comment by quezlatch** [comment]
@DamianMac i couldn't find the script at the time so i made the following modification to my deploy script, as per #1444

**Comment by richardp-au** [comment]
@DamianMac Is this in version 2.6.4.951? It wasn't mentioned in the release notes but it is marked as Done.

**Comment by DamianMac** [comment]
@richardp-au sorry no it's not. 
Unfortunately Microsoft got a bit trigger happy with nuget dependencies for azure SDK, updating this small thing means pulling in half of nuget.org so we've closed it off for the 2.* branch and will re-look at it in 3

**Comment by richardp-au** [comment]
@DamianMac That's going to cause us problems then.

Could you please details exactly how to get the workaround going and which files need changing? I'm happy to modify PS scripts for now while we wait for version 3 but last time I tried it, I couldn't get it to work.

**Comment by graemechristie** [comment]
Isn't the Azure functionality in Octo completely broken without this fix. Rather than just not having access to newer functionality, I get 

```
Get-AzureDeployment : "An exception occurred when calling the 
Error    17:50:01
ServiceManagement API. HTTP Status Code: 400. Service Management Error Code: 
Error    17:50:01
MissingOrIncorrectVersionHeader. Message: The x-ms-version header value 
Error    17:50:01
'2012-12-01' is not one of the supported version headers'.
```

Which afaik is due to the bundled azure powershells tools no longer being supported. Surely you can't close this without a fix in Octopus V2 ... ?
