### ISSUE TITLE
Pre-Release packages listed as latest package

### ISSUE THREAD

**Issue by ccamburn** [OctopusDeploy/Issues#1397]
The help window for the "Latest" column when creating a release shows: 
"The most recent, non-pre-release package that we could find in the NuGet feed."

However, if the highest number package available is a pre-release package, then it shows the pre-release as the latest. 

Also, when clicking the search button, it defaults to having pre-release as checked, which I feel it should be defaulted as unchecked. (Though this isn't technically part of the bug, just a preference. I feel you should have to opt-in for a pre-release, essentially, instead of having to opt-out.)

If I uncheck the box and filter, it correctly does not show the latest package if it is a pre-release.

**Comment by PaulStovell** [comment]
We'll fix this properly when we add better branching support, after 3.0 ships
