### ISSUE TITLE
Add logging of how many files were copied to custom install directory

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1400]
Had a once off support issue where a postdeploy.ps1 was not moved to the custom installation directory and then did not run. Unsure why or how this happened, need to add some logging to show how many files were moved.

**Comment by PaulStovell** [comment]
Pretty sure we do this in 3.0 (calamari) now - please confirm

**Comment by Damovisa** [comment]
Calamari will put the following in the Verbose log:

    Extracting package to: C:\Octopus\Applications\release\Dev\Acme.Web\3.2.3_1
    Extracted 6 files
