### ISSUE TITLE
Release new version of octo.exe

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1404]
https://github.com/OctopusDeploy/Issues/issues/1239
Can we get this checked and released please

**Comment by alfhenrik** [comment]
New release has been created and released.

**Comment by nelsona** [comment]
Where can I get a copy of this new octo.exe release?

**Comment by alfhenrik** [comment]
It's up on chocolatey.org
`choco install octopustools -Version 2.6.1.46`
