### ISSUE TITLE
Config option to turn off config transforms logging

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1405]
On very large releases the extraneous logging for config transforms can make deployment logs way too long and not give instant feedback on a deployment:
When we looked at what was being outputted we found that every transform has several lines of output in the verbose logs, not including warnings. Is there anyway to suppress this or at least put those logs into the unbuffered output type.

Source: http://help.octopusdeploy.com/discussions/problems/28348

**Comment by bigbam505** [comment]
So recently I added some metrics into Datadog and have the following graph for a release which shows just how many log messages are being queued up.

![Graph](https://dl.dropbox.com/s/tahdxxgs3urwctz/Metric_Explorer__Datadog_2015-01-08_16-26-56.jpg?dl=0) 

Each time section is around 30 minutes.  The climb portion of the graph is about 20 minutes and the fall is an hour.  This means that logs can be delayed up to an hour+

**Comment by bigbam505** [comment]
Any word on when this will be added?

**Comment by PaulStovell** [comment]
Let's make this a special variable in 3.0

**Comment by Damovisa** [comment]
New variable will be `Octopus.Action.Package.SuppressConfigTransformationLogging`.
Warnings and errors will still be logged, however. We still want to know when it fails! :)
