### ISSUE TITLE
Auto installer for Tentacle broken if appdir non-standard path

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1407]
We have mixed results when upgrading tentacles. This happened on windows 2012R2 and 2012. The latest upgrade it happened for was 2.6.0.778. These are the only non-standard configuration values: install was on a different drive (D:\) and the application directory is D:\Application too.

& : The term '.\Tentacle.exe' is not recognized as the name of a cmdlet, 
Error 19:39:36 function, script file, or operable program. Check the spelling of the name, or 
Error 19:39:36 if a path was included, verify that the path is correct and try again. 
Error 19:39:36 At D:\Application\.SQ-SABO2-623964D3\Octopus.Tentacle\2.6.0.778\Deploy.ps1:10 
Error 19:39:36 char:3 
Error 19:39:36 + & .\Tentacle.exe service --reconfigure --instance "$instanceName" --console 
Error 19:39:36 
+ ~~~~~~~~~~~~~~ 
Error 19:39:36 + CategoryInfo : ObjectNotFound: (.\Tentacle.exe:String) [], Pare 
Error 19:39:36 ntContainsErrorRecordException 
Error 19:39:36 + FullyQualifiedErrorId : CommandNotFoundException 
Reconfiguring the Octopus Tentacle Windows Service to use path: C:\\Tentacle.exe 
Tentacle instance: Tentacle

Note: works when MSI is used.
Source: http://help.octopusdeploy.com/discussions/problems/28499

**Comment by PaulStovell** [comment]
Fixed in 3.0 due to Tentacle architecture changes
