### ISSUE TITLE
With the release on the 19th for Octopack

### ISSUE THREAD

**Issue by mapeterson42** [OctopusDeploy/Issues#1408]
We are now seeing the following when trying to install the latest version.  If we use the previous version, no error:

"The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd' has invalid child element 'developmentDependency' in namespace 'http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd'. List of possible elements expected: 'releaseNotes, frameworkAssemblies, tags, summary, language, description, copyright, dependencies, references' in namespace 'http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd'."

**Comment by ashujosh007** [comment]
Hey Damian why you closed this issue, did you find a solution for this? If yes please share.
