### ISSUE TITLE
Show machine display names when deploying instead of machine ids

### ISSUE THREAD

**Issue by jsallis** [OctopusDeploy/Issues#1409]
After installing version 2.6.0.778, a message is now displayed to report what machines are being deployed to:

```
Deploying to machines: machines-33,machines-1
```

It would be more helpful to show the display name of the machine instead of the machine id.

**Comment by ccamburn** [comment]
+1, though I think the machine id can be useful. Perhaps:

Deploying to machines: MachineName (machines-33), MachineNum2 (machines-1)

The machine id is useful if you want to use the REST API, but useless otherwise.
