### ISSUE TITLE
Constructor error for guided failure 2.6

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1410]
Unable to find a constructor to use for type System.DelegateSerializationHolder+DelegateEntry. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Octopus.Platform.Deployment.Guidance.Guided.PendingGuidance[0].Item.ActivityIdTracker.Delegate', line 1, position 12560.

In diagnostics after 2.6 upgrade
Source: https://octopusdeploy.uservoice.com/admin/tickets/2472

**Comment by DamianMac** [comment]
Closed. Duplicate of #1430
