### ISSUE TITLE
Tentacle won't start listening on the port 10933

### ISSUE THREAD

**Issue by shcherbachev** [OctopusDeploy/Issues#1411]
I am trying to configure a tentacle to run on my Windows 2012 server. The wizard runs just fine, however the tentacle won't listen at port 10933 after startup. I tried to open http://localhost:10933 - got connection refused. Same with netstat - no port listening.

Here is what I have in tentacle logs:

>2014-12-23 14:58:25.3796   INFO  Waiting for service to start. Current status: Running
>2014-12-23 14:58:25.7703   WARN  Configured to listen to server {"Thumbprint":"DBE032116DB1F69C5816299941EF963FC72FA57A","CommunicationStyle":0,"Address":null,"Squid":null}, but no SQUID is configured for it; skipping.
>2014-12-23 14:58:25.8483   INFO  TCP server distribution service disabled

Am i missing anything?

**Comment by PaulStovell** [comment]
It looks like this happened because the machine was originally set up in polling mode (`-nolisten` was passed), and then when it was reinstalled in listening mode the flag wasn't unset. Let's fix this in the product.
