### ISSUE TITLE
Granular permission for blocking deployments - for discussion

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1412]
Should we have granular permissions for ability to block deployments - ie if a dev breaks a deployment and needs to make sure testers don't proceed with deploying it - shoudl they have to contact an admin to perform this for them?

Source: http://help.octopusdeploy.com/discussions/problems/28696

**Comment by PaulStovell** [comment]
No, I don't think we should build so much into software to solve organisational issues.
