### ISSUE TITLE
Icon not updating properly for parallel deployment steps on task summary window

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1416]
Tested on: 2.6.0.778

Step status Icon is not updating properly for parallel nuget deployment steps on task summary window.

1) Create and deploy with at least 2 nuget package deploy steps running in parallel.
2) Check the Task summary tab. The icons for the deployment steps are in grey, even though the steps ran successfully.

Related support ticket: http://help.octopusdeploy.com/discussions/problems/28944

**Comment by PaulStovell** [comment]
Fixed in latest 2.6 (we made a bunch of parallelism fixes)
