### ISSUE TITLE
Allow Octopus to use LDAP over SSL

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1417]
http://stackoverflow.com/questions/10850860/how-do-i-validate-active-directory-creds-over-ldap-ssl

http://help.octopusdeploy.com/discussions/questions/3901

**Comment by adilmehmoodbutt** [comment]
How can i  migrate Gitlab accounts from standard accounts to ldap users along with work history.

**Comment by PaulStovell** [comment]
Will be closed when we do: https://github.com/OctopusDeploy/Issues/issues/1737
