### ISSUE TITLE
Show HTML error in install wizard

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1418]
When the tentacle install wizard is set to check the Octopus credentials, if it hits a proxy and HTML is returned, it gives a JSON reader error. We should be able to display the HTML that is returned to help the customer determine the blocker.

Source: http://help.octopusdeploy.com/discussions/problems/29161%7C*Error

**Comment by PaulStovell** [comment]
Release Note: Improve helpfulness of errors when REST API client encounters a proxy server error.
