### ISSUE TITLE
Provide an option for any machine variables

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1419]
For variables defined in steps, you need to define the machine name to retrieve the variable in subsequent steps. We need an option for machine.any for cases where they know its going to be the same variable or its a single machine. It will make any scripting or email templates work across multiple environments.

Source: http://help.octopusdeploy.com/discussions/problems/28692

**Comment by plindelauf** [comment]
+1

**Comment by PaulStovell** [comment]
Fixed in 3.0!

**Comment by PaulStovell** [comment]
Here's how the new behaviour works - suppose there's a machine called `Web01` that sets an output variable `Foo`. We'll set the following variables: 

 - `Octopus.Action[Website].Output.Foo` with no scope (**new**)
 - `Octopus.Action[Website].Output.Foo` scoped to machine
 - `Octopus.Action[Website].Output[Web01].Foo` with no scope

So if you want "any", just use `Octopus.Action[Website].Output.Foo` and you'll get any value. 

If you used that variable from Web01, you'd get the Web01 value. If you used it from Web02, you'd get the Web02 value if it had set one. But, if you use it from an email step (which is not machine specific), or Web03 (which may not have a value defined), you'll get either the Web01 or Web02 value. Which one you get is not deterministic.
