### ISSUE TITLE
Import/export bug in 2.6 - missing lifecycle

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1421]
attempted an export and import of another project from Production into our 2.6 Development instance. We again ran into the following error:
"Error from Octopus server (HTTP 400): There was a problem with your request. - The project must be assigned to a lifecycle."

Source: http://help.octopusdeploy.com/discussions/problems/28157

**Comment by kamalim** [comment]
Hello,

Any idea when this bug is going to be fixed.I really want to use the octo exe tool for our server migration
