### ISSUE TITLE
Team Editor w/ restricted Envs deletes Envs from other teams

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1424]
If you have a team editor who has restricted environments, if they view and save a team with other or all environments, it deletes the teams that the editor themselves cannot view/edit. There needs to be something to handle this - either ability to see the environments in this case or they are greyed out, viewable and still save.

Source: https://octopusdeploy.uservoice.com/admin/tickets/2485

**Comment by PaulStovell** [comment]
Editing teams assumes some level of administrative ability - there are too many situations where assigning that role but denying environments just wouldn't work. Going to close this one as we don't have a good solution for it.
