### ISSUE TITLE
Link to Interruption in Configuration > Audit points to 'not found' url

### ISSUE THREAD

**Issue by ashmatthew** [OctopusDeploy/Issues#1425]
Octopus Deploy 2.6.0.778
Configuration > Audit page
I've added a manual intervention step to my production deployment. After performing a production deployment and I view at the audit page under configuration, I see the step listed, but if I hover over the interruption link (not the show/hide details link) it points to /app#/not-found rather than the actual interruption. It does appear to have a title attribute on the link that displays 'interruptions-X', but I'm not sure if that is supposed to translate to a link or not.

**Comment by robpearson** [comment]
Release Note: Interruption no longer link to a non-existant view
