### ISSUE TITLE
Permissions changed for Library -> Packages page - 2.6 bug

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1433]
Currently you need AdministerSystem to view the library -> packages page. This means that giving someone builtinfeeddownload is fairly useless unless they can also view that page.

Source: http://help.octopusdeploy.com/discussions/problems/26965-problem-with-the-permission-builtinfeeddownload

**Comment by mapeterson42** [comment]
Actually it's a bit "worse" than that.  Giving someone AdministerSystem grants them the permission to do the same thing as what I understand builtinfeeddownload is supposed to do.  So there is currently no point in giving them the builtinfeeddownload permission.  AdministerSystem does not appear to give them the ability to upload a new version or any version though (builtinfeedadminister) so there is that.

**Comment by JCapriotti** [comment]
This seems to have changed after we installed Octopus 2.6. Seems like a bug...

**Comment by vanessalove** [comment]
another: http://help.octopusdeploy.com/discussions/problems/29299

**Comment by yooakim** [comment]
@vanessalove do you have any updates on when we can expect this to be fixed? At this time we have a server which we can not use fully. So either we need to downgrade the server or else we would like a fix.

Can a server be downgraded without issues to the previous version without Lifecycles?

**Comment by yooakim** [comment]
Can anyone tell me if it is possible to downgrade the Octopus Server from 2.6 without losing data? 

I need to work aorund this permission issue.

**Comment by vanessalove** [comment]
@yooakim @mapeterson42 @JCapriotti This is live and available as part of 2.6.1
You will need admin permissions to see the retention policy details on the package page, otherwise it is hidden.
