### ISSUE TITLE
Support exclude files in OctoPack via nuspec

### ISSUE THREAD

**Issue by eddiegroves** [OctopusDeploy/Issues#1434]
It would be great if OctoPack supported excluding files as per the [NuSpec reference](http://docs.nuget.org/docs/reference/nuspec-reference#Specifying_Files_to_Include_in_the_Package)

My scenario:
* Include compiled sass -> css files via `<files>`, these files are not included in the csproj.
* Use `OctoPackEnforceAddingFiles` to automatically grab everything else.

Now I'd like to exclude with wildcards the 100+ sass files I don't need packaged. Setting Content to None isn't a long term solution since developers will forget as new files are added and moved around.

**Comment by alluran** [comment]
Hey @eddiegroves, we meet again!

Chuck this in your pre/postbuild for a short-term fix https://github.com/alluran/ProjectSync

**Comment by eddiegroves** [comment]
Hi @alluran! Thanks for the tip, I'll check it out :+1:

**Comment by PaulStovell** [comment]
I think it would be best to just use the nuspec completely (and use * wildcards to save repetition) and not rely on the Octopus conventions too.
