### ISSUE TITLE
Update and revise configuration transformation documentation

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1436]

**Comment by PaulStovell** [comment]
No idea what this means

**Comment by vanessalove** [comment]
its a documentation task for configuration transformations - get a ticket a week sometimes because the documentation isnt clear - reopening

**Comment by vanessalove** [comment]
main support issues asked about continually:

1. theres nothing about how to use additional transforms feature (including things like we recursively search directories, and both files need to be in the same directory, target needs to exist)
2. people get the content type confused with the content type needed to just include files in nuget packages and do it in the wrong order for config files
3. needs a section on how to do variable replacements outside of appsettings and connection strings

**Comment by vanessalove** [comment]
http://docs.octopusdeploy.com/display/OD/Configuration+files+v2
for review

added the "Replacing variables outside appSettings and connectionStrings" and "Additional Configuration Transforms" sections with a few tips
