### ISSUE TITLE
SemVer support

### ISSUE THREAD

**Issue by JakeGinnivan** [OctopusDeploy/Issues#1446]
Currently there is an issue I see a lot of people hitting when trying to use Semantic Versioning (semver.org).

When using SemVer you will produce packages with the same SemVer for each commit with only the build metadata changing. For example.

1.0.0+1
1.0.0+2
1.0.0+3

You then create a release for 1.0.0+3, this will create a tag in your VCS as 1.0.0 and then you can deploy that release to different environments. From the point you tag your VCS you are working on `1.0.1` at a minimum, maybe `1.1.0` if there are new features being added.

The issue is that NuGet and Octopus Deploy do not treat build metadata as significant. This is fine being a consumer of the released package but causes problems for the release process.

The current solution is to promote the build metadata to the 4th part of the version meaning `1.0.0+3` becomes `1.0.0.3`. For pre-release tags this is `1.0.1-beta.1+5` becomes `1.0.1-beta.5`.

Any ideas how this issue should be addressed. https://github.com/ParticularLabs/GitVersion has quite a few Octopus Deploy users and this question comes up quite a bit

**Comment by JakeGinnivan** [comment]
http://octopusdeploy.uservoice.com/forums/170787-general/suggestions/5411483-support-semver-2-0-build-metadata-in-the-release-v is a uservoice with this issue.

**Comment by vanessalove** [comment]
Hi @JakeGinnivan - if you check this thread: https://github.com/OctopusDeploy/Issues/issues/1168
The NuGet semver library does not allow for it yet, so we cannot update octopus until a time that it does. It is also a reason we have the UserVoice so please comment and vote there.

**Comment by DamianMac** [comment]
Sorry Jake, not on our roadmap at the moment

**Comment by JakeGinnivan** [comment]
If you are interested. Here is our doco for v3 of GitVersion for Octopus Deploy users.

https://github.com/ParticularLabs/GitVersion/tree/release/3.0.0#octopus-deployci-build-nuget-packages

Hopefully it might help a few of your users.
