### ISSUE TITLE
Filenames with square brackets not deployed to server

### ISSUE THREAD

**Issue by ajakuszyk** [OctopusDeploy/Issues#1447]
I am using Octopus Deploy 2.6.0.778. I have a NuGet package which, among others, have the following files in the IMG directory:

\img\key-fund[blue].png 
\img\key-fund[red].png

Note the square brackets in the filename. 
When I deploy my packages, all the files except those 2 are deployed. 

To pack those I am using NuGet 3.0.0 – I compiled it from the sources and I can see that files are inside packaged file - they are visible both in NuGet package Explorer and when opened as a zip file.
Note that when NuGet 2.8.2 is used then files are not visible afterwards in NuGet package Explorer (although you can see them if you rename the file extension to zip).

**Comment by ajakuszyk** [comment]
For all those who encounter this issue - I've managed to create a workaround by creating a script module with Expand-FilesWithBrackets function, which I then use in pre-deployment scripts.

### Octopus bug fix - extract files and directories with square brackets in name/path ###

Set-StrictMode -Version Latest

Add-Type -AssemblyName System.IO.Compression.FileSystem

function Expand-FilesWithBrackets
{    
    [CmdletBinding()]
    Param
    (
        [ValidateNotNullOrEmpty()]
        [String]$TargetDir = (Get-Location).Path
    )
    
    $packageFilePath = $OctopusParameters['Octopus.Tentacle.CurrentDeployment.PackageFilePath']    
    $zipArchive = [System.IO.Compression.ZipFile]::OpenRead($packageFilePath)
    foreach ($zipEntry in $zipArchive.Entries)
    {
        # ignore NuGet related files
        @('[Content_Types].xml', '_rels/' ,'package/') | ForEach {
            if ($zipEntry.FullName.StartsWith($_)) { continue }
        }
    
        # ignore files without brackets in name
        if ($zipEntry.FullName -notlike '*`[*' -and 
            $zipEntry.FullName -notlike '*`]*') { continue }
        
        $extractDir = $TargetDir
        $zipEntryDir = Split-Path -LiteralPath $zipEntry.FullName
        if ($zipEntryDir)
        {   
            $extractDir += '\' + $zipEntryDir
            if (-not (Test-Path -LiteralPath $extractDir))
            {
                # Create extract directory if not exists
                New-Item $extractDir -ItemType Container | Out-Null
            }
        }
    
        $extractPath = '{0}\{1}' -f $extractDir, $zipEntry.Name
        Write-Host "Extracting $extractPath"
        [IO.Compression.ZipFileExtensions]::ExtractToFile($zipEntry, $extractPath, $true)
    }
}

**Comment by PaulStovell** [comment]
Thanks, I think this will be fixed when we upgrade to NuGet 3.0

**Comment by OliverRC** [comment]
Any idea when we can expect this fix to be live?
