### ISSUE TITLE
Deployment Audit filtering not working correctly

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1448]
Hello, 
We have just noticed what we think might be an issue in 2.6.0.778. When we access the audit screen and filter by environment, deployments to that environment don't show up. If we look at deployments done prior to our 2.6 upgrade they show up.

https://octopusdeploy.uservoice.com/admin/tickets/2853/?q=assignee%3A%22none%22+status%3Aopen&order=desc

**Comment by sl33kr** [comment]
Hi,
Is there any ETA on a fix for this?

**Comment by PaulStovell** [comment]
This will be fixed in 3.0 (due very soon)
