### ISSUE TITLE
Octopus Team city plugin creates two releases when the create release build step is used

### ISSUE THREAD

**Issue by tommyhawk520** [OctopusDeploy/Issues#1449]
i have a build set up with team city 9.0.1 and octopus deploy 2.6.0.778. before a recent upgrade to these versions the build was working fine but now the create release step from the octopus deploy plugin creates two releases in octopus deploy.

**Comment by vanessalove** [comment]
Hi @tommyhawk520 could you please either email support@octopusdeploy.com or use our support forum http://help.octopusdeploy.com/discussions for this issue. Also when you do, please provide your Team City build log.
