### ISSUE TITLE
Deployments hanging 2.6

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1450]
Multiple sources of deployments hanging since 2.6 changes. Many tickets, many deployment logs.

Sources:

http://help.octopusdeploy.com/discussions/problems/29272
http://help.octopusdeploy.com/discussions/problems/29293
http://help.octopusdeploy.com/discussions/problems/29494
http://help.octopusdeploy.com/discussions/problems/29401
https://octopusdeploy.uservoice.com/admin/tickets/2685

**Comment by vanessalove** [comment]
http://help.octopusdeploy.com/discussions/problems/29494

**Comment by RatStrydom** [comment]
Hi all.

We deployed using 2.6.1 last night and unfortunately it wasn't any better than before.

Regards,
Johann

**Comment by DamianMac** [comment]
Thanks @RatStrydom 
We've had a few reports of the same, we're deep in stack dumps this week to try to track it down. We'll open another issue for the 2.6.2 release

**Comment by vanessalove** [comment]
Deployments hanging issue that was part of a race condition has been resolved and is stable as of 2.6.5. If you are still seeing hanging the source has been confirmed as TCP offloading causing network traffic to disappear so Tentacles are losing messages to send back to Octopus Server. Adjusting your TCP Offloading will resolve the issue.

**Comment by vermeeca** [comment]
Hello!

I'm currently seeing this issue with 2.6.5.

The issue, for me, seems limited to a couple tentacle machines.  These tentacles are VMWare Virtual Machines, running Windows Server 2008 R2.  The Octopus Server is Windows Server 2012 R2.

I tried adjusting the TCP Offloading setting (using the process described [Here](http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1009517)) on one of the Tentacle machines, to no avail.  Should I be adjusting that setting on the Octopus server as well?
