### ISSUE TITLE
IIS Authentication Mode name labels

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1451]
When using a custom binding for the IIS Authentication modes, the Mode name labels are no longer displayed making it harder to determine which mode is what.

See the below UV for screenshot of the issue.
https://octopusdeploy.uservoice.com/admin/tickets/2836/?q=assignee%3Ame+status%3Aopen&order=desc

**Comment by shaynevanasperen** [comment]
Can we get an update and ETA on this please?

**Comment by PaulStovell** [comment]
It will ship as part of 3.0, we'll fix it as we make a few other UI changes in this area.
