### ISSUE TITLE
Guided Failure - Ignore Skips Remaining Steps for a Machine in a Rolling Deployment

### ISSUE THREAD

**Issue by caseymarcallen** [OctopusDeploy/Issues#1452]
If I have a rolling deployment (step 1) with 3 child steps in it (1.1, 1.2, 1.3) if step 1.2 fails and I choose to ignore the failure then step 1.3 will not be executed.

A scenario where this is an issue is if I have steps like:

1. Rolling deployment across Web Servers

1.1 Take Out of Load Balancer

1.2 Deploy Package

1.3 Powershell script to just cleanup some random files

1.4 Check site is up and running OK

1.5 Put back in Load Balancer

if 1.3 fails and I choose to ignore the failure because it's not critical to the success of the deployment then I am expecting 1.4 & 1.5 will continue to be run, however steps 1.4 and 1.5 will be skipped altogether.

**Comment by PaulStovell** [comment]
This is fixed in 3.0 - guidance operates on a per-action basis now.
