### ISSUE TITLE
2.6 Lifecycle retention policies displaying messages incorrectly

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1456]
If you set the overall policy for a lifecycle to keep all, then set phase 1 to keep for 3 days, set phase 2 to keep all, when you release to phase 2 it says it is going to use phase 1 settings even though at the top it states phase 2 is keep forever. Unknown if this is just bad messaging or also broken for the deletion. ive explained about the intention of the inheritance from previous phases, however if you override it should still use the override settings?

Source: http://help.octopusdeploy.com/discussions/problems/29591
![2015-01-30_08_58_31-apply_retention_policies_-_octopus_deploy](https://cloud.githubusercontent.com/assets/7697660/5971742/1ea542b4-a898-11e4-87f7-aed3d151409b.png)

**Comment by vanessalove** [comment]
I had a thought about this ticket while writing the doco. If the deployment has moved into a phase where its only set to keep for 1 day, then while its in that phase, regardless of others, deploying to those environments will only keep for 1 day. Until it reaches a phase 2 deployment then it will always keep forever .. so these messages might be correct

**Comment by Damovisa** [comment]
Reopened for investigation. Incorrect retention policies have been reported in 3.0.

**Comment by vanessalove** [comment]
Closing again, original issue fixed and milestone linked to release.
Create a new issue if it exists in 3.0
