### ISSUE TITLE
When creating nuget packages using octopack the package gets a bit large 

### ISSUE THREAD

**Issue by wallymathieu** [OctopusDeploy/Issues#1457]
When I create packages using Octopack I noticed that the dependencies does not get added as dependencies but as files to the nuget package. This might cause some trouble when building very frequently and with many nuget references (size of nuget stream).

Perhaps a solution is to have an option to avoid adding the Dll present in the packages folder to the output nuget package (but ensure that the dependencies get added as dependencies)?

**Comment by DamianMac** [comment]
We use the nuget package as the unit of deployment so this one isn't going to change
