### ISSUE TITLE
Blocking deployments documentation

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1470]

**Comment by DamianMac** [comment]
@Dalmirog are you going to do this? Or should I close ?

**Comment by Dalmirog** [comment]
@DamianMac Will do it!

**Comment by Dalmirog** [comment]
http://docs.octopusdeploy.com/display/OD/Blocking+Deployments

**Comment by vanessalove** [comment]
moved to trello https://trello.com/c/c0qBZdl0
