### ISSUE TITLE
Setting parallel deployment step as first step does not run step when deploying

### ISSUE THREAD

**Issue by Rafvb** [OctopusDeploy/Issues#1471]
When you set a step (that is not the first step) to 'run in parallel with the previous step' (start trigger) and reorder the steps so it becomes the first step, the step is not excecuted when deploying.
It's not possible to edit the start trigger for a the first step, so you have to reorder again, change the start trigger to 'Wait for ...' and then move it back to the front.

I'm using version 2.6.1.796.

**Comment by Gilligan128** [comment]
This has been recorded and fixed in version 2.6.2 on Issue #1406
