### ISSUE TITLE
Octopack: Detect Web Application from Content Files as well

### ISSUE THREAD

**Issue by vermeeca** [OctopusDeploy/Issues#1472]
I suggest modifying Octopack so that it detects that an application is a web application if there is a Web.Config in the Content files as well as if a Web.Config is physically present in the folder.

For reference, the current IsWebApplication method in CreateOctopackPackage.cs:

```CSharp
private bool IsWebApplication()
{
    return fileSystem.FileExists("web.config");
}
```

I'm trying to package up some web apps that include Web.Config as a linked item, and Octopack is incorrectly identifying them as Console applications.

Opening this issue for discussion.  If it seems like a reasonable enhancement, I'm happy to cook up a pull request.

**Comment by PaulStovell** [comment]
Yes please!
