### ISSUE TITLE
populate isSkipped when determined to be skipped

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1479]
action.isSkipped is only populated when a step is skipped by the user when configuring the deployment. It is not populated when the deployment determines to skip the step ie during these scenarios:

13:14:53   Verbose  |   Step "send me an email!" runs on failure and no failures have been encountered; skipping.
13:14:53   Verbose  |   Step "test" runs on failure and no failures have been encountered; skipping.

Feel this needs a bit of discussion

**Comment by Damovisa** [comment]
Submitted as a PR
