### ISSUE TITLE
Have $OctopusParameters['Octopus.Release.Previous.Number'] be environment-aware

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1496]
Currently the variable **$OctopusParameters['Octopus.Release.Previous.Number']** gets the previous release created. Scenario:

Dev - Has release 3.0.0
Stage - Has  3.0.0
Prod - Has 1.0.0

If we promote Stage's release to Prod, during Prod's deployment the value of this variable will be 2.0.0 instead of 1.0.0 which is the actual previous release number deployed to the current environment (prod).

**Comment by shaneray** [comment]
Thank you very much!

https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/7132620-previous-deploy-variable-for-environment

**Comment by Damovisa** [comment]
I'll add a new variable rather than change the behaviour of the existing one. This should avoid any breaking changes.
