### ISSUE TITLE
OctoPack version bug

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1498]
Today I hit an interesting limitation in OctoPack when I tried to create a package with a WiX installer inside. Even though I provided `OctoPackPackageVersion` through the parameter in the build definition it still failed with the following error.

**As it turns out GetAssemblyVersionInfo is called in any case even if the parameter is provided**. Looks like a bug to me but there may be a reason why this is so. Anyway, I added an extra condition there to ensure this task is called only when `OctoPackPackageVersion` is not defined.

![unnamed](https://cloud.githubusercontent.com/assets/47085/6408082/f87ad0ec-be98-11e4-95f5-769a1c5ea370.png)

**Comment by draugr** [comment]
Is this bug fixed as of now? This bug, and the not-avoidable case that the getassemblyversion prioritizes the InformativeSemVer makes it hard to use together with gitversiontasks.
