### ISSUE TITLE
OctoPackNuGetPushProperties duplicating -Properties when calling nuget.exe

### ISSUE THREAD

**Issue by maxxxxxxxim** [OctopusDeploy/Issues#1499]
When setting OctoPackNuGetPushProperties (e.g. OctoPackNuGetPushProperties=foo=somevalue), the octopack output contains duplicate -Properties value when constructing the command line to call nuget.exe.

In this case the nuspec file contains $suffix$ in the package id tag.

`(OctoPack target) ->  MSBUILD : OctoPack error OCTONUGET: Invalid option value: '-Properties suffix=stable'  MSBUILD : OctoPack error OCT-1676060969: There was an error calling NuGet. Please see the output above for more details. Command line: 'C:\Source\packages\OctoPack.2.0.26\targets\NuGet.exe' pack "C:\Source\Sample.Web\obj\octopacking\Sample.Web.nuspec"  -NoPackageAnalysis -BasePath "C:\Source\Sample.Web" -OutputDirectory "C:\Source\Sample.Web\obj\octopacked" -Version 1.0.0.0 -Properties suffix=stable -Properties suffix=stable`

**Comment by PaulStovell** [comment]
Was sure we fixed this
