### ISSUE TITLE
"No Action Taken" for steps when skipping the first step in a set parallel steps

### ISSUE THREAD

**Issue by lachok** [OctopusDeploy/Issues#1500]
We have a set of 7 steps which I recently changed to run in parallel. The first 6 steps deploy to the same machine. Today I wanted to run just the 7th step so I skipped the first 6. The 7th step appeared as "No Action Taken" as in [here](http://help.octopusdeploy.com/discussions/suggestions/757-add-a-third-status-to-completed-deploy-steps-no-action-taken). The logs on the Tentacle did not show any communication regarding the 7th step. Any steps after the 7th which are not executed in parallel ran successfully. After changing just the 7th step to not run in parallel and creating a new release it ran successfully.

**Comment by vanessalove** [comment]
Hi @lachok This was fixed in 2.6.2 https://github.com/OctopusDeploy/Issues/issues/1406

**Comment by lachok** [comment]
Thanks @vanessalove Probably should've checked that we are running the latest version.
