### ISSUE TITLE
Variables - need a way to make them "versionable"

### ISSUE THREAD

**Issue by dotnetwise** [OctopusDeploy/Issues#1501]
At the moment, running one build after the other is just fine.

However if in one week time, I would like to run an older build, from an older branch, I can't!

Because in the meanwhile the variables were simply updated to the latest version, so they would fail an older build.

Hence, we need a way for `octo.exe` to specify what version of the variables we target.

e.g. run build no.1 in teamcity and then deploy it with `octo.exe -version 1` 
Then update your variables, do more builds etc.
Later run again the same code from the same old branc as build no.1 was and target again `octo.exe -version 1` so the same old variables are being used.

Of course, you also need a way to "edit" older variables e.g. in a dropdown on the variables page

**Comment by PaulStovell** [comment]
Thanks, we'll solve this as part of branching support (you'll be able to scope variables on a branch by branch basis), as well as in a future version when we'll make it easier to view/diff variables. Right now there's too much to change to make this work before 3.0.

**Comment by dotnetwise** [comment]
So why closing it? Add labels 3.0 then, right?
