### ISSUE TITLE
Octo.exe create-project Lifecycle support

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1503]
**Octo.exe V 2.6.1.52**

When using **create-project** the user gets the error message: 
```
Error from Octopus server (HTTP 400): There was a problem with your request.
- The project must be assigned to a lifecycle
```

The Octo.exe POST message to /api/projects is passing down *LifecycleID* as null.
```
{
  "VariableSetId": null,
  "DeploymentProcessId": null,
  "IncludedLibraryVariableSetIds": [],
  "DefaultToSkipIfAlreadyInstalled": false,
  "VersioningStrategy": null,
  "ReleaseCreationStrategy": null,
  "Name": "SomeProject",
  "Slug": null,
  "Description": null,
  "IsDisabled": false,
  "ProjectGroupId": "ProjectGroups-329",
  "LifecycleId": null,
  "AutoCreateRelease": false,
  "Links": {}
}
```

**Comment by Modulus** [comment]
is this fixed? It is currently not possible to create projects with octo.exe....

**Comment by alfhenrik** [comment]
This was fixed in `2.6.3.59`.

Commit https://github.com/OctopusDeploy/Octopus-Tools/commit/5e2a6551f058433e0ed5ede75e76fa3475f8e734 on 5 Feb 2015.

**Comment by alfhenrik** [comment]
Sorry, I made a mistake when looking through the source code, this has not been fixed.

My apologies.

**Comment by PaulStovell** [comment]
Given that Octo.exe can create projects but not add any steps, and given projects without steps are somewhat useless, is there any use case for this command? I think it might be time to obsolete it.

**Comment by PaulStovell** [comment]
Unless people use it to clone stuff

**Comment by tothegills** [comment]
Release note: A Lifecycle can be specified when creating a project with `Octo.exe`
