### ISSUE TITLE
Hanging deployments redux

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1505]

**Comment by PaulStovell** [comment]
Hanging appears to be resolved, the issue is now down to cancellation causing the task queue to stall.

**Comment by bova80** [comment]
When do you expect the next version with the hanging issue resolution out?  This one is really hurting us.

**Comment by vanessalove** [comment]
http://help.octopusdeploy.com/discussions/problems/29272 & http://help.octopusdeploy.com/discussions/problems/30988-deployments-still-hanging-with-latest-version both have provided the logs we asked for

**Comment by vanessalove** [comment]
asked for one more here: http://help.octopusdeploy.com/discussions/problems/29401-seeing-queuedhanging-tasks-fairly-frequently

**Comment by vanessalove** [comment]
HuBoard Noob - didnt mean to close
