### ISSUE TITLE
Octo.exe should print the username of the user it authenticated as

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1506]
Sometimes users use the wrong API key with Octo.exe, and can't find projects or environments because the user they are running as doesn't have permission to see them.

1. After connecting, print the username we connected as
2. When we can't find a project/environment/etc., in the error message, suggest it might possibly be a permissions issue

**Comment by IanMercer** [comment]
Here's what the output looks like:

```
Authenticated as: No priviledges <> (a service account)
...
Could not find a project named 'Azure Service'; either it does not exist or you lack permissions to view it.
Exit code: -1
```

If the user has an email it's in the <>.
