### ISSUE TITLE
Out of Order of Steps When Deploying to Multiple Environments

### ISSUE THREAD

**Issue by caseymarcallen** [OctopusDeploy/Issues#1508]
If selecting multiple environments in the "Deploy To..." selection list, the preview of steps shows some steps out of order.

Note that the out of order steps only apply to one environment. In this case the steps are child steps that relate to taking a site in and out of a load balancer that only apply to the production environment. These Load balancer steps are not applicable to the test environment.

See step 2.1 in screenshot:

![image](https://cloud.githubusercontent.com/assets/951165/6522292/43d0bf40-c41e-11e4-85a8-976b3971b436.png)

**Comment by PaulStovell** [comment]
This was fixed as part of https://github.com/OctopusDeploy/Issues/issues/1378 quite some time ago - I just checked the latest version and it appears to sort correctly.
