### ISSUE TITLE
Adding AD groups to the "Everyone" team

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1509]
Currently it is not possible to delete users from the "Everyone" group, which is how we expect it to work. It is also possible to add AD groups to "Everyone" which , following the "everyone" team's logic, you cannot delete afterwards.

What is the purpose then of being able to add AD groups to "everyone"? 

(Ticket submitted after talking about it with Paul)

**Comment by jkonecki** [comment]
I believe one should be able to delete the group. If the group name has a mistake or the group is removed from AD a lot of error will be polluting Server Logs in Diagnostics.

The workaround is to remove the group directly from the RavenDB:
1. Start Octopus Manager
2. Click on _Browse RavenDB_ in _Storage_ section
3. Open Teams / teams-everyone document
4. Delete your group from ``ExternalSecurityGroups`` array.

**Comment by PaulStovell** [comment]
Shouldn't be able to add groups to Everyone

**Comment by PaulStovell** [comment]
Fixed in 3.0.6 - you can no longer add to everyone group
