### ISSUE TITLE
Random "Completed Successful" Error

### ISSUE THREAD

**Issue by RenEvo** [OctopusDeploy/Issues#1520]
When creating or viewing a release, this message occassionally shows up and the package information is not populated.

![image](https://cloud.githubusercontent.com/assets/1626559/6782170/a18b3b24-d12f-11e4-8b84-a210f3c6c128.png)

It is extremely confusing as to what is actually broken.

**Comment by RenEvo** [comment]
Restarting the server seems to clear this issue, but as the server is running, this becomes increasingly worse.

Also to be clear, this is an external NuGet feed, not the internal one.

**Comment by vanessalove** [comment]
@RenEvo We have a task for this one - and have found the issue. 
https://github.com/OctopusDeploy/Issues/issues/1071

Closing this for duplication
