### ISSUE TITLE
Package using variable, should be set for all deployments of a release

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1521]
A customer is using a variable in its package that is matched to a variable used in the release. When the release is created the variable for the package is correct. Ie 1.0.1-branch1 corresponding package mypackage-branch11.0.1. Then this is released through from Dev -> QA. A new dev is built with branch two and a release created" 1.0.2-branch2 corresponding package mypackage-branch21.0.2.

When release 1.0.1-branch1 is finally released to prod, it uses the package mypackage-branch21.0.1 - branch2 has been used because its what the variable is. Should the package names not persist for the entire release ?

Source: http://help.octopusdeploy.com/discussions/problems/31745

**Comment by PaulStovell** [comment]
Dup of #1529
