### ISSUE TITLE
Library Package download links all link to latest

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1522]
When you go into a package and view all of the versions, the download icon only ever links to the latest . When you click through to details the link is correct. But not on the main page.

![library-package-download](https://cloud.githubusercontent.com/assets/7697660/6795780/d1675e06-d231-11e4-9547-b01976cf5b86.PNG)

**Comment by bjorgvino** [comment]
Any updates on when this will be fixed?

**Comment by PaulStovell** [comment]
We'll fix it just after 3.0 ships at the latest.

**Comment by vanessalove** [comment]
fixed in 3.0
