### ISSUE TITLE
Not using variable snapshot for package name list on release page

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1529]
If a release is created using a variable for the package name, and then you navigate to the release page to see the list of packages used, you'll see the package just fine. If you change the value of that variable and navigate back to the same release page, the package name will change to the new variable value, instead of using the variable snapshot value

![capture](https://cloud.githubusercontent.com/assets/6180562/6867875/ece9f9b0-d464-11e4-9cd8-015a77078da8.JPG)

Source: http://help.octopusdeploy.com/discussions/problems/32078

**Comment by tothegills** [comment]
Need to pass the release when getting deployment process template and use release snapshotted variables instead of project variables

**Comment by tothegills** [comment]
Release note: Variable snapshots will be used when resolving packages for an existing release
