### ISSUE TITLE
Nuget 3.0 (VS2015 CTP6) doesn't install Octopack properly

### ISSUE THREAD

**Issue by georgiosd** [OctopusDeploy/Issues#1530]
I was having an issue where Octopack was enabled during TeamCity build but wasn't running.

Took me ages but found that when installing the Octopack nuget through VS2015, the csproj is not changed to include Octopack targets, hence the problem.

**Comment by zentron** [comment]
@georgiosd,
 Could you please confirm with the latest release of VS2015 that octopack is being correctly installed to your csproj project.
While we have not yet confirmed the place of octopack for builds of vnext xproj projects, I have tested installing it against a csproj file and the targets do look to be correctly added.

Hopefully this is just one of those temporary problems that comes with playing with the bleeding edge. :)

Keep your eyes out for a post where we take a look at the best practices for working with dnx + OD.
Thanks for letting us know about this problem, I look forward to hearing back if this is now sorted.
Rob

**Comment by georgiosd** [comment]
Indeed, this seems to be the case! All good in RTM. Thanks for the followup and I'm already subscribed to the Octopus blog for the DNX news!
