### ISSUE TITLE
Script console timeout

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1531]
The script console times out after 5 minutes even if the task itself is still running on the Tentacle. To fix for 3.0

Source: https://octopusdeploy.uservoice.com/admin/tickets/3773
Example: https://demo.octopusdeploy.com/app#/tasks/ServerTasks-62546

**Comment by PaulStovell** [comment]
I have a feeling these timeouts aren't implemented at all in 3.0 - need to investigate

**Comment by PaulStovell** [comment]
This only matters for Script Console, and since people can click cancel or invoke it by API I think we can just remove the setting.
