### ISSUE TITLE
Documentation for managing team roles and creating custom

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1545]
we have no page that goes into specifics for changing the roles of users / teams

**Comment by vanessalove** [comment]
Add a red ! note on the page about the following:
when we add new roles with releases we do not add the permissions to existing roles as we do not want to grant permissions to people who should not have them, so they need to be added manually to the roles that exist

**Comment by Dalmirog** [comment]
Reminder to add link to the new doc at the bottom of the parent doc http://docs.octopusdeploy.com/display/OD/Key+Concepts

**Comment by Dalmirog** [comment]
The document is ready for review on http://docs.octopusdeploy.com/display/OD/User+Roles

**Comment by PaulStovell** [comment]
Published for 3.0
