### ISSUE TITLE
Investigate Tentacle clustering

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1547]
Work out how much effort is required to make Tentacle cluster aware. If it's not a massive amount of work, do it for 3.0. 

http://help.octopusdeploy.com/discussions/questions/4434

**Comment by PaulStovell** [comment]
Unlikely to get time to do this in the next 3 months so I'm going to close this for now.

**Comment by kreuzerkrieg** [comment]
Ok, it is July 2016
Any progress?

**Comment by lonevvolf** [comment]
I left this:
http://help.octopusdeploy.com/discussions/questions/7149-revisiting-windows-clusters-please

It simply seems that they do not have this as a very high priority.  I encourage you to post about this on their forums if you need it!  Show them that there is a real need!

**Comment by kreuzerkrieg** [comment]
actually, it is doable with power shell. not most convenient and I guess not the most "right" way to do stuff but it worked for me

**Comment by lonevvolf** [comment]
Indeed, this is how we solved it, but it is far from ideal.  Especially when a service can be deployed to different environments which may or may not have clustering in use.

**Comment by kreuzerkrieg** [comment]
exactly the problem I have, gotta create different deployment steps attached to different environments, not the most convenient way
