### ISSUE TITLE
Web Deploy step fails with 'ERROR_USER_UNAUTHORIZED' error

### ISSUE THREAD

**Issue by richiej84** [OctopusDeploy/Issues#1548]
When deploying a website using the Web Deploy (MSDeploy) step, it will fail with a 'ERROR_USER_UNAUTHORIZED' error if you have a variable name 'Password' in you variable set. The 'Password' variable is used to replace an app setting in the website but looks to be conflicting with the web deploy script and overriding the password used when publishing. I can't see anything about 'Password' being a system/protected variable name?? 

Here is the exact error message:

Exception calling "SyncTo" with "4" argument(s): "Connected to the remote
computer ("sitename.scm.azurewebsites.net") using the Web Management
Service, but could not authorize. Make sure that you are using the correct
user name and password, that the site you are connecting to exists, and that
the credentials represent a user who has permissions to access the site.
Learn more at:
http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_USER_UNAUTHORIZED."
At C:\Windows\system32\config\systemprofile\AppData\Local\Tentacle\Temp\bf4003e
6-3926-4b65-9a4c-2b7bb216f430.ps1:93 char:1
+ $deploymentObject.SyncTo("contentPath", $websiteName, $destBaseOptions,
$syncOpt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
+ CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE
xception
+ FullyQualifiedErrorId : DeploymentDetailedException
Publishing Website

**Comment by PaulStovell** [comment]
Fixed in 3.0 - we're adding native Azure website support
