### ISSUE TITLE
Option to ignore package (OctoPack)

### ISSUE THREAD

**Issue by AndrewSav** [OctopusDeploy/Issues#1551]
I have added OctoPack from NuGet to my solution.
When I'm running the solution build with the following keys:
/p:RunOctoPack=true /p:OctoPackPublishPackageToHttp=...

I'm getting the following build error:

> EXEC : The remote server returned an error : (400) Bad Request.. [myproject.vbproj]
  project\packages\OctoPack.3.0.42\tools\OctoPack.targets(105,5): error MSB3073: The command ""project\packages\OctoPack.3.0.42\tools\NuGet.exe" push "myptoject.nupkg" API-KEY -s server " exited with code 1.

This happens because my code has not changed, and the assembly version stayed the same after the build. So when OctoPack tries to push the package to the OctopusDeploy server the package is already there and the build fails.

There should be an option so that this situation for a single package does not ruin the whole solution build. A warning seems more appropriate, but the best would be an ability to configure it so that if the package already exists it's ignored.

Also the error message is cryptic. Bad Request does not give a user any hint as to why this has failed, this can certainly be improved too.

You do have the option /ignoreexisting on Octo.exe for releases, could you please add it one for packages also to octopack?

**Comment by AndrewSav** [comment]
Related: http://help.octopusdeploy.com/discussions/problems/22283-upgraded-to-octopus-deploy-249167-now-getting-400-bad-request-on-nuget-push

**Comment by PaulStovell** [comment]
We use NuGet.exe to push the package - unfortunately it doesn't show the details of the bad request error, and it doesn't have an option to ignore existing. Unfortunately there's not much we can do about this issue.

**Comment by AndrewSav** [comment]
You sure can. Nuget provides public API that you can call instead of using nuget.exe. This API returns appropriate error message that you can handle. You can easily see the message in Fiddler.
