### ISSUE TITLE
Variable Octopus.Deployment.ErrorDetail isnt holding error messages

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1553]
After a Powershell step failure, the variable `$OctopusParameters['Octopus.Deployment.ErrorDetail']`doesn't seem to be populated with any values. [According to the documentation](http://docs.octopusdeploy.com/display/OD/System+variables) it should hold the exception. This was only tested with Powershell Steps so far, so further investigation for other kinds of errors might be needed.

Version: 2.6.4.951

Reported by: http://help.octopusdeploy.com/discussions/questions/4553

**Comment by ccamburn** [comment]
I can confirm that powershell steps running as Pre-, Post-, and Deploy.ps1 steps within a package will also not return an ErrorDetail. 

In addition, I ran a deployment on a machine that lacked disk space (less than 500MB), and received the appropriate error in the log. However, when sending an email and using #{Octopus.Deployment.ErrorDetail}, it was null. My guess is the ErrorDetail as a whole isn't working, more than just in ps1 scripts.

**Comment by PaulStovell** [comment]
Need to confirm this works in 3.0

**Comment by Damovisa** [comment]
Confirmed this works in 3.0.
Note that if the powershell script catches an exception and handles it manually, that Octopus property won't be set. It will only be set if the script actually fails.

If you want to make your own exception details available for future steps, I'd recommend Output variables :)

**Comment by MattPOlson** [comment]
If we catch the exception in PowerShell like this, there isn't any way to populate the variable {Octopus.Deployment.ErrorDetail} with the error detail?

try{
      Execute some code here
} 
catch
 {
         $message = "error "
         Write-Host $message
         Write-Host $_.Exception.ToString()
         exit 10003
}

**Comment by Damovisa** [comment]
Hi @MattPOlson,

The short answer is you wouldn't want to, because we would write over the top of it anyway. If your script returns a non-zero exit code, that gets interpreted as an error, and we populate the `Octopus.Deployment.ErrorDetail` with that fact.

Is there a reason you want to use this specific variable rather than your own?

Damo

**Comment by MattPOlson** [comment]
I wanted to use that variable because it's easy to access. From what I understand if I want to access a variable that was defined by another step I have to use the step name like this. $name = $OctopusParameters["Octopus.Action[StepA].Output.SomeVariable"]. If I don't know what step set that variable I can't get to it. When PowerShell returns a non-zero exit code what does that variable get populated with?

**Comment by Damovisa** [comment]
Hi @MattPOlson,

That's correct. You will have to know the step name if you set output variables.

However, if you set an output variable, but then fail the step (by returning a non-zero exit code or throwing an exception), the output variable won't actually be set. This is a known issue and you can track its progress at https://github.com/OctopusDeploy/Issues/issues/1589.

I was slightly off with my previous response regarding the ErrorDetail contents:
Based on a quick test, when PowerShell returns a non-zero exit code (or throws an exception), `Octopus.Deployment.ErrorDetail` doesn't have anything in it, but `Octopus.Deployment.Error` has something fairly generic like `'Operation: Running step "StepName" on "Environment 1" failed with error: One or more items in the current operation failed.'`.

There will obviously be much more detail in the log, but I understand that's not terribly useful when you're sending the email.

We've kept the behaviour with failures fairly simple. It could be useful to be able to add more specific information about the failure to an email, but for the moment we assume that `Octopus.Deployment.Error` is enough to give you a rough idea of the problem and you'll log in to read through the logs for more detail.

Thanks,
Damo
