### ISSUE TITLE
Weird permissions on script console.

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1557]
User is on a team with the "System Administrator" role and limited to just 1 environment. When he goes to the script console:

1 - When selecting individual machines, the user can see machines from all the environments.

2 - When the user tries to run a scrip on a machine, it gets an error saying 
`Missing permission: TaskCreate`

**Comment by PaulStovell** [comment]
We'll make script console its own permission

**Comment by PaulStovell** [comment]
Going to close this - it could always become a UV suggestion. Script console is designed for admins, we'll reconsider another day.
