### ISSUE TITLE
Filter variables list by value not working

### ISSUE THREAD

**Issue by pascalmartin** [OctopusDeploy/Issues#1560]
When we use filter variables by value is not working ?
version Octopus Deploy 2.6.5.1010

![image](https://cloud.githubusercontent.com/assets/1377165/7160886/ec44f0ce-e359-11e4-9c3e-9265d3cf57e1.png)

![image](https://cloud.githubusercontent.com/assets/1377165/7160910/05ec64c6-e35a-11e4-91be-59f11e80d4ab.png)

**Comment by gobeiil** [comment]
I have the same issue

**Comment by enarciso** [comment]
+1, I can confirm this as well.

Version: Octopus Deploy 2.6.4.951 

Thanks

**Comment by PaulStovell** [comment]
Fixed in 3.0
