### ISSUE TITLE
Promotion doesn't retain selected options of previous deployment

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1563]
I noticed that clicking the promote button no longer remembers the selections you made, after your latest update. i.e. If I have a release and I uncheck a couple of deployment steps, it used to be that using the promote button would remember that. But after the latest updated, I now have to click "advanced" every time and redo my step selections. I really liked the one click promote functionality that used to be around.

**Comment by PaulStovell** [comment]
This is on purpose now, as we normally show that page collapsed to keep it simple
