### ISSUE TITLE
Library variable sets behaving badly

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1569]
If you don't have scope permissions for variables inside a variable set, you cant see any of the variables you get a message like: You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: VariableView
So you do not see what you have permissions to see or even part of the Set, you just see an error message.

It should work like project variable view.

Source: http://help.octopusdeploy.com/discussions/problems/32738

**Comment by vanessalove** [comment]
This is working as expect - user was limited to projects and thus could not see this global feature. It is by design. You should not be able to edit global variables in use by another project if you have no idea what the impact could be.

**Comment by SeanKilleen** [comment]
FYI, I also recently ran into this issue on a client site where I was doing some consulting; they had to make their global list of projects available to me, even though I was only maintaining 2 projects within Octopus.

For users looking to vote for this to be addressed, the UserVoice location is: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6986441-permission-attributes-for-variable-sets-library-v
