### ISSUE TITLE
Investigate why #{else} isn't working as part of file substitution

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1583]
see ticket: http://help.octopusdeploy.com/discussions/questions/4704

**Comment by jamesweakley** [comment]
Could it be (at least partially) because the TemplateParser doesn't include 'else' as a ConditionalToken?

https://github.com/OctopusDeploy/Octostache/blob/master/source/Octostache/Templates/TemplateParser.cs#L86

**Comment by mjrichardson** [comment]
Octostache doesn't support `else` statements.  Like Mustache (the inspiration for Octostache), it is designed to be a very simple logic-less language.
