### ISSUE TITLE
InstallationDirectoryPath variable not available on further steps after deployment failure

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1589]
If the deployment step fails, the variable `#{Octopus.Action[StepName].Output.Package.InstallationDirectoryPath}` is not available on further steps. 

Some users might need to take actions on that directory depending on the outcome of the deployment step, so it would be really useful to have the variable available.

**Comment by PaulStovell** [comment]
This *may* work in 3.0 already, need to check.

**Comment by PaulStovell** [comment]
I just checked - this works fine in 3.0. 

![2015-08-31 14_39_25-deploy octofx release 3 0 940-beta2 to development - octopus deploy](https://cloud.githubusercontent.com/assets/47085/9572173/2a946b4c-4fee-11e5-9496-aec645ed23eb.png)
