### ISSUE TITLE
Automatic deploy not working when release reaches a lifecycle phase

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1591]
Once the release gets created and it reaches a phase with an environment set to be automatically deployed, the deployment doesn't start.
![capture](https://cloud.githubusercontent.com/assets/6180562/7501014/b1c5d27e-f407-11e4-93c0-db0df8086c6b.JPG)

- No logs on the server side.
- Restarting server doesnt seem to fix this.

Tested on:
2.6.5.1010 - Not working
2.6.3.886 - Working OK. Deployments are triggered as expected.

**Comment by PaulStovell** [comment]
There will be a reason behind this, sometimes prompted variables and things get in the way. Need better logging.
