### ISSUE TITLE
Add support for targeting subdirectories in the configuration transform feature's additional transforms

### ISSUE THREAD

**Issue by nathan-alden** [OctopusDeploy/Issues#1592]
Referencing this issue: https://github.com/OctopusDeploy/Issues/issues/1238

The real problem here isn't just the lack of meaningful logging by Octopus Deploy, it's that the additional transform feature doesn't appear to support a subdirectory syntax for the target. It appears that the target must live in the root of the NuGet package for it to be transformed. This is limiting the usefulness of the additional transforms capability.

Humbly requesting this to work as several folks have expected:

    content\Web.Custom.config => content\Web.config

**Comment by vanessalove** [comment]
@nathan-alden Octopus iterates through directories. If those files are in content it will find them. As long as the web.custom.config is in the same directory as web.config this will work if you remove the content\ part of your definition.

**Comment by nathan-alden** [comment]
That appeared to work. Thank you! It would be helpful if the additional transforms capability were documented here: http://docs.octopusdeploy.com/display/OD/Configuration+files

**Comment by vanessalove** [comment]
@nathan-alden yeah it's on the list to update that page

**Comment by nkomp18** [comment]
As of May 2016, I couldn't get this very simple scenario to work.
I have custom config in a folder:

`config\section1.config`

And the appropriately named config with the transformation:

`config\section1.<Environment.Name>.config`

But octopus won't touch it. I've also tried adding this in the additional transforms section, although I shouldn't have to, it should just work automatically. 

`*.#{Octopus.Environment.Name}.config => *.config`

Is this a new bug with Octopus 3.3.1.2?
