### ISSUE TITLE
Investigate Content Type when caching API requests

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1593]
When enabling caching with HttpClient to interact with your service all requests that are cached are failing to be parsed as JSON due to their Content-Type being text/plain instead of applicaiton/json. I think this is because octopus deploy is setting Content-Type to text/plain in the 304 responses and the cache is being updated to reflect that (or something). In Fiddler I am able to set a rule to modify the requests for our octopus server that removes the Content-Type header for 304 responses and things work fine.

Repro: https://gist.github.com/aarondandy/ee11865494c4b1ea5004
Source: http://help.octopusdeploy.com/discussions/problems/33608

**Comment by DamianMac** [comment]
We're likely going to rebuild the http API piece in the near future.
