### ISSUE TITLE
PackagePrerelease in Octo.exe not working as expected

### ISSUE THREAD

**Issue by vermeeca** [OctopusDeploy/Issues#1595]
I'm trying to use the 'prerelease' portion the Nuget Package version of my Octopus deployment packages to indicate which branch the package was built from.  For example, I'm wanting to use it to differentiate our CI builds (e.g. MyApp, version 1.0.20150512.1-Dev) from our builds out of our release branch (e.g. MyApp, version 1.0.20150512.2-Release).

I'm trying to use Octo.exe's '--packagePreRelease' option in order to create a release of my application using packages from a specific branch.  However, Octo.exe doesn't seem to find my packages when using this option.

The issue seems to be with the way it's using the package search API.  When --packagePreRelease is specified, octo.exe makes an API call like the following:

    http://myoctopusserver/api/feeds/feeds-builtin/packages/?packageId=MyApp&partialMatch=true

Which brings back data like the following

```javascript
[
  {
    "Id": "packages-MyApp-1.0.20150511.4-Dev",
    "NuGetPackageId": "MyApp",
    "Title": null,
    "Summary": null,
    "NuGetFeedId": null,
    "Version": "1.0.20150511.4-Dev2",
    "Description": "The MyApp deployment package, built on 5/11/2015",
    "Published": "Monday, May 11, 2015 10:12 PM",
    "ReleaseNotes": null,
    "PackageSizeBytes": null,
    "Links": {
      "Self": "/api/feeds/feeds-builtin/packages?packageId=MyApp&partialMatch=False&includeMultipleVersions=False&take=1"
    }
  },
  {
    "Id": "packages-MyApp.Dev-Camber-1.0.20150508.1",
    "NuGetPackageId": "MyApp.Dev-Camber",
    "Title": null,
    "Summary": null,
    "NuGetFeedId": null,
    "Version": "1.0.20150508.1",
    "Description": "The MyApp deployment package, built on 5/8/2015",
    "Published": "Friday, May 8, 2015 9:17 AM",
    "ReleaseNotes": null,
    "PackageSizeBytes": null,
    "Links": {
      "Self": "/api/feeds/feeds-builtin/packages?packageId=MyApp.Dev-Camber&partialMatch=False&includeMultipleVersions=False&take=1"
    }
  },
  {
    "Id": "packages-MyApp-1.0.20150507.13",
    "NuGetPackageId": "MyApp",
    "Title": null,
    "Summary": null,
    "NuGetFeedId": null,
    "Version": "1.0.20150507.13",
    "Description": "The MyApp deployment package, built on 5/7/2015",
    "Published": "Thursday, May 7, 2015 10:14 PM",
    "ReleaseNotes": null,
    "PackageSizeBytes": null,
    "Links": {
      "Self": "/api/feeds/feeds-builtin/packages?packageId=MyApp&partialMatch=False&includeMultipleVersions=False&take=1"
    }
  }
]
```

This API call seems to be trying to find packages where the [OctoPackAppendToPackageId](https://github.com/OctopusDeploy/OctoPack) feature is being used to put the branch name onto the package instead.

If I change octo.exe to issue an API call like the following instead:

    http://myoctopusserver/api/feeds/feeds-builtin/packages/?packageId=MyApp

It then gets back multiple versions of that package from the API, and can filter them own to the prerelease versions as expected.

**Comment by PaulStovell** [comment]
Closing this as it will be solved by branching support.
