### ISSUE TITLE
AD users from child domain don't get rights when their AD group added to a Team

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1601]
We have a North American domain (eg: COMPANY.COM) and a child domain for our European offices (EUROPE.COMPANY.COM). We have an AD group called RELEASE MANAGEMENT and our European team members are part of this group.

I've created a team on Octopus Server called "Release Management" and added the AD group RELEASE MANAGEMENT to it. The North American folks can get in no issues, but the European team folks who are part of the AD group do not flow through, I have to add them explicitly to the Octopus team.

Source: http://help.octopusdeploy.com/discussions/problems/33583-windows-users-from-child-domain-dont-get-rights-when-their-ad-group-added-to-a-team

Possibly related to #1000 ?

**Comment by PaulStovell** [comment]
Will be fixed by: https://github.com/OctopusDeploy/Issues/issues/1737
