### ISSUE TITLE
"Promote to [environment]" button is visible when already deploying to that environment

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1602]
source: http://help.octopusdeploy.com/discussions/questions/4763

This might be confusing for some users, leading them to start another deployment to the same environment. 

![capture](https://cloud.githubusercontent.com/assets/6180562/7661153/a8b1127c-fb26-11e4-8a69-f83a7dbdee5f.JPG)

Perhaps the button could be greyed with the text "Deploying to [environment]". If the user really wants to start a deployment of that same release while another one is taking place(which shouldn't happen too often), he should click on "Deploy to"

Totally open for discusion

**Comment by PaulStovell** [comment]
Don't think this is enough of an issue to change it (not clear what the fix would be and how we'd implement it)
