### ISSUE TITLE
[3.0] Script steps not showing up in task log while running

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1603]
When running a deployment with a custom step template (and PowerShell script step), the tag log doesn't display the progress of the step, it does display it on the task summary tab though.

![image](https://cloud.githubusercontent.com/assets/1035315/7668566/a1886a4c-fc82-11e4-9b62-aad66413b36c.png)

![image](https://cloud.githubusercontent.com/assets/1035315/7668567/b4892cf8-fc82-11e4-9fd4-f5a01cc3a809.png)

![image](https://cloud.githubusercontent.com/assets/1035315/7668568/c572f7c4-fc82-11e4-9693-90fe3b8fcff3.png)

**Comment by PaulStovell** [comment]
The bug here is the item appears as Pending
