### ISSUE TITLE
Auto release creation not skipping steps that have a role that doesn't apply to the deployment

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1605]
The deployment succeeded though, so not a major issue. More an aestethic (and cause for confusion perhaps?) thing.

![image](https://cloud.githubusercontent.com/assets/1035315/7696304/15f0b228-fe3f-11e4-9267-32f422a2e461.png)

![image](https://cloud.githubusercontent.com/assets/1035315/7696311/23054abe-fe3f-11e4-9451-3361d9546bbb.png)

![image](https://cloud.githubusercontent.com/assets/1035315/7696295/0a4d9e86-fe3f-11e4-921a-c47347d06c6d.png)

**Comment by PaulStovell** [comment]
Just tried this, while I agree the current behavior is a little confusing, I think it's more obvious as you read the deployment log. If we wanted to fix this, we'd have to decide at the start of a deployment to skip a step if it targeted roles that we don't have machines in. When we do some more "cloud" support in the future, we might actually need this, so for now I think we can leave it and we'll figure it out in the future if it becomes a real problem.
