### ISSUE TITLE
MSI installer in quiet mode doesnt start the service after upgrading tentacle

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1606]
Scenario: Server with 3 tentacle instances, only 1 of them is started

**MSI Installer in normal mode**
I run the installer to update the tentacle. During the process, the Tentacle service that was started is stopped as expected. When the installation finished, only that service is started again. 

**MSI installer in quiet mode (from cmd line)**
I run the installer to update the tentacle using the quiet mode. During the process, the Tentacle service that was started is stopped as expected. When the installation finished, the service doesn't get started again.

There's an inconsistency between the 2 installing methods. Should we assume that the service that was started, should be started again after the install?

**Comment by PaulStovell** [comment]
Closing this because there's a pretty easy workaround (`Tentacle.exe service --start`), and since Tentacle updates will be much less frequent.
