### ISSUE TITLE
For 3.0 make the footer renewal link only show for minor/major changes

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1607]
Currently as soon as your maintenance date expires and a new release is created the footer of octopus server states you need to renew to upgrade. But this is only correct for major/minor releases and not patches. Customers are feeling they need to renew for bug fixes and its bringing confusion/extra tickets.
*important at 3.0 release as people will expire during patch releases before 3.1

Source: http://help.octopusdeploy.com/discussions/questions/4824

**Comment by michaelnoonan** [comment]
To do this properly it looks like we'd benefit from Octofront: https://github.com/OctopusDeploy/Octofront/issues/53
