### ISSUE TITLE
Incorrect dashboard statuses

### ISSUE THREAD

**Issue by dazinator** [OctopusDeploy/Issues#1608]
1. Deploy a release to an environment
2. Look at the dashboard - you'll see the progress bar indicating a deployment is in progress.
3. Deploy another release to the same environment (while the existing release is still deploying)
4. Look at the dashboard - you'll see it change to "queued" as the status.
5. Cancel the release that you created - i.e the one that's currently waiting.
6. Look at the dashboard - you'll see it says "Cancelled" - even though there is a deployment in progress.

Correct behaviour: At step 6, it should show you the progress bar of the current ongoing deployment. 

Deployments that were cancelled whilst in a queued state (i.e not actually initiated) arguably shouldn't show on the dashboard as cancelled - instead it should show current deployment for that environment.

**Comment by PaulStovell** [comment]
I think the query would need to use the Started column to know if the deployment was initiated. The logic would be: Exclude tasks which are Cancelling or Cancelled if Started is null.

**Comment by tothegills** [comment]
Release note: Do not show deployments that have been cancelled before they start on the dashboard
