### ISSUE TITLE
TeamCity plugin has a misleading help text

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1613]
In the **Deploy Release** & **Promote Release **step, the **Project** field help text suggests a release can be created using that step, which is not correct.

![tcdeployrelease](https://cloud.githubusercontent.com/assets/6180562/7863028/4424dcb2-0530-11e5-856f-0a9b2d6e5bf1.JPG)

**Comment by tothegills** [comment]
Release note: Fixed misleading help text in Octopus TeamCity plugin
