### ISSUE TITLE
Tentacle auto-updater (2.6->3.0)

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1616]
We have a migration tool for 2.6 -> 3.0 for the data, but nothing planned yet for Tentacle. 

We need a solution that automatically updates Tentacle 2.6 to 3.0. It should do so by:

 - Stopping any running Tentacle.exe processes (running in command line mode or Windows Service mode)
 - Uninstalling the old MSI
 - Installing the new MSI
 - Starting the Tentacle processes

It needs to log any problems in a place that's easy to find, and have some smarts around recovery if something goes wrong. 

The tool that does all this should be:

 - Usable from the command line - places with big environments might script it themselves
 - Usable from an Octopus project or script console script (i.e., we need to make it easy to distribute)
 - Usable from within Octopus 3.0 itself, in case we need to do a Tentacle upgrade

Making it a self-contained exe, wrapped in a NuGet package, might be a good approach.

**Comment by Damovisa** [comment]
We'll also need a parameter to pass in a new 3.0 IP/URL for polling tentacles to hit.
See also #1676.
