### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1617]
We want to allow people to access data about their deployments for reporting purposes. 

Someday we might decide to add lots of reports inside of Octopus, but for now, the easiest thing to do is to expose the data in a way that Excel can consume, and let people make their own reports (or maybe provide some templates/documentation). 

Simplest thing that can possibly work:

 - Table for DeploymentHistory
 - API responder that serves the history as XML, which Excel can then import
 - Documentation/video showing them how -- no need to build any Octopus UI around it just yet

I had a go at doing it in 2.6: https://github.com/OctopusDeploy/OctopusDeploy/pull/150. There's even a video here:

http://www.screencast.com/t/RAtCpdu37P9

Why a DeploymentHistory table? Because retention policies. The 2.6 version I did reported directly off the documents, but retention policies would make it useless for any historical reporting since they delete old data anyway. 

DeploymentHistory table would be somewhat denormalized (in case projects/environments/releases are ever deleted) -- it shouldn't require any joins to query:

 - DeploymentId (PK)
 - DeploymentName
 - ProjectId
 - ProjectName
 - ProjectSlug
 - EnvironmentId
 - EnvironmentName
 - ReleaseId
 - ReleaseVersion
 - TaskId
 - State
 - Created
 - Queued
 - Completed
 - DurationSeconds
 - DeployedBy

Data should be added to this table only when a deployment completes (in `DeploymentTaskController`) or is timed out (i.e., server restarts). 

Data should only be removed from the table when a project is deleted, or an environment is deleted. If releases are renamed, too bad. If projects or environments are renamed, the table should be updated. Otherwise it shouldn't change (e.g., if a user is renamed, who cares).

**Comment by IanMercer** [comment]
Why remove history when a project / environment is deleted? Wouldn't reporting be 'forever' (or at least until it falls off the end of whatever limit is set on retention for reports)?

**Comment by IanMercer** [comment]
Synergy between this and the event-bus for webhooks? Could the reporter just hang off the event bus and collect everything (or a selection) from it? Or event-bus --> event-store --> reporting.

**Comment by PaulStovell** [comment]
Synergy - yes. Need to think about whether it makes sense for deployments to appear in this table until they are 'complete'/'timed out' however - queued tasks shouldn't appear here.

**Comment by PaulStovell** [comment]
Happy to reconsider deletion for project/environments. People could always delete entries manually if they want to. Let's leave them for now and leave it to the customer to delete.

**Comment by vanessalove** [comment]
+1 for allowing customer to delete if they want, but this is a nice history for reporting that has been requested

**Comment by bigbam505** [comment]
Something else that might be worth considering is being able to configure octo to push deployment metrics to a different database or an external service.  This is most likely longer term but we currently import our history into a postgres database for the current day every night so we can run reports across our deployments with a BA tool tableau and create fun graphs like number of deployment failures per day ![Deployment Failures](https://dl.dropbox.com/s/ttgkinpkka874ro/Deployment_Metrics_Deployment_Failures_-_Tableau_Server_2015-06-02_23-03-45.jpg?dl=0)

**Comment by michaelnoonan** [comment]
Release Note: Added reporting capability as per http://docs.octopusdeploy.com/display/OD/Reporting
