### ISSUE TITLE
Offline deployments - set InstallationDirectoryPath

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1618]
http://community.octopusdeploy.com/t/th-installationdirectorypath-variable-is-missing/55/1

**Comment by mjrichardson** [comment]
Output variables are currently not supported by offline-deploys.  This will require some thought as to how that would work.

**Comment by PaulStovell** [comment]
If you want this feature, please vote on UserVoice instead: http://octopusdeploy.uservoice.com/forums/170787-general/suggestions/9196032-output-variables-for-offline-drops
