### ISSUE TITLE
IIS Bindings Do Not Support IPV6

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1620]
In the configuration of a deployment step within Octopus, for the IIS bindings of a site, colons seem to give Octopus Deploy some issues. See attachments: for before and after I save with an IPV6. This is sort of a bug on multiple levels but more importantly it makes it impossible to listen to a loopback IP which is default for localhost on recent versions of Windows.

Source: http://help.octopusdeploy.com/discussions/problems/34608

**Comment by kibbled** [comment]
Any update on this bug?  The only decent work around I've found is to bind to 127.0.0.1 which requires modifying the localhost on the target machine to use IPV4 which can have consequences for other applications.  Additionally, using variables for the IPV6 loopback does not work either.

**Comment by PaulStovell** [comment]
Will be fixed when we do: https://github.com/OctopusDeploy/Issues/issues/1738
