### ISSUE TITLE
Package acquisition not getting cleaned up with a deploy fails

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1623]
System does the disk write to package cache on the server, when a deployment fails system continues writing those files, i guess until there done. If they are 1GB packages it keeps running for quite a while after the deployment has failed.  Had a strange case where the package acquisition failed, system finished writing files then octopus.server starting using 100% cpu and crashed.

**Comment by tothegills** [comment]
Also can not stop OctopusDeploy service until the packages have finished downloading.

**Comment by PaulStovell** [comment]
Deployment failed is handled by one of the threads in the deployment throwing an exception, and then the parent thread rethrowing. However other child threads can still be 'running':

 - Thread A  <--- rethrows and fails deployment
    - Thread A1  <--- throws
    - Thread A2  <--- keeps running

We could try to abort the threads but in that could leave us in a corrupt state. Maybe there's some way we can signal threads that the deployment has failed and they can periodically re-check. 

Changing the way we do package acquisition might make this less of an issue.

**Comment by PaulStovell** [comment]
Going to close this as we seem to be doing a better job with package acquisition
