### ISSUE TITLE
 EXEC : The remote server returned an error : (400) Bad Request

### ISSUE THREAD

**Issue by ALSEDLAH** [OctopusDeploy/Issues#1624]
Hi there, 

When I try to push nuget package to Octopus server by octopack. I got  this error because the package  already exists. It's there any way to overcome this error. I saw in the source code if the exit code doesn  not equal 0, it throws an exception, I'm using Jenkins and as you know Jenkins every exit error not 0, it marks the build as failure.   

thanks

**Comment by vanessalove** [comment]
Hi Alsedlah,

Sorry but, we are unable to change this error as it is internal to NuGet.

Vanessa
