### ISSUE TITLE
Warning doesn't show up on release when a library variable is updated

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1626]
If a variable is updated on a project, and you try to deploy a release that was created prior to the change, the following message shows up:

![uploads/3cbe2776-2380-43e1-a8e4-5e4039cdd937/Screen Shot 2015-04-17 at 10.06.28 am.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3cbe2776-2380-43e1-a8e4-5e4039cdd937%2FScreen+Shot+2015-04-17+at+10.06.28+am.png)

The same does not happen when updating a library set variable, and the old value is used during the deployment without notifying the user that he has to refresh the set on his project.

**Comment by tothegills** [comment]
Release note: Display a warning when deploying a release and relevant library variables have changed
