### ISSUE TITLE
Deploy is set as success with warning when triggered from Octo.exe

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1627]
When a step is skipped because it doesn't apply to the current deployment triggered from the UI, the deployment gets marked as successful with a green icon and the following messages show up on the log indicating that the steps were skipped.

![viaui](https://cloud.githubusercontent.com/assets/6180562/8094118/5e344b90-0f9b-11e5-89df-5759233a7e8a.JPG)

When the same deployment is triggered from Octo.exe, the steps are also skipped, and the deployment is marked as successful, but with a warning icon below and the following messages on the task summary 

![viaoctoexe](https://cloud.githubusercontent.com/assets/6180562/8094218/01a34150-0f9c-11e5-9a6d-e4e2ba81e8f6.JPG)
*(these messages dont show up on the task summary if the deployment was triggered from the UI)*

Opening the discussion to see if both deployments should be marked the same way (either with or without the warning icon) or if this difference between UI-deployments and Octo.exe works as expected

Source: http://help.octopusdeploy.com/discussions/problems/34751

**Comment by Dalmirog** [comment]
My 2 cents:

When the user triggers the build from the UI, he sees a message warning him about the skipped steps before clicking on **Deploy now**. So the user is actively agreeing to continue with the deployment despite of that. Hence the build is marked as successful, without the warning.

When triggering the build from Octo.exe, the might not be aware that know those steps will be skipped, so it makes sense that the build is marked as successful with a warning.

That said, i also understand that it might bother to see builds with a warning on the dashboard when the build was actually succesful

**Comment by MattPOlson** [comment]
I think a good option would be to allow a parameter to be passed into Octo.exe to suppress warnings.

**Comment by robpearson** [comment]
Failed to reproduce this using Octopus 3.1.x and then I found that it’s actually an Octopus 2.6.5 issue.  We are only doing bugs fixes for Octopus 3 therefore this will not be fixed and the issue will be closed.

I’d recommend upgrading to Octopus 3 to take advantage of this bug fix as well as numerous other enhancements and features.
