### ISSUE TITLE
Unhelpful exception for invalid SSH endpoints

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1633]
I'll just leave this one here...

![image](https://cloud.githubusercontent.com/assets/1187840/8101066/cb611a02-1056-11e5-950c-aaf4d09c570e.png)

**Comment by zentron** [comment]
by the sounds of this error message its a valid DNS error. So far unable to reproduce locally. 
I would prefer to leave this open for a bit until it can be reproduced so we can handle catch the specific exception rather than a catch all as this might actually mean something to some people.

**Comment by IanMercer** [comment]
The best approach would be to implement the `MustBeAValidHost` method already lined up for this purpose in the FluentValidation branch so no exception is ever thrown. The method needs to handle all permutations of valid DNS names. IPv6 too?

**Comment by zentron** [comment]
I'm not sure we want to just hide valid network exceptions behind a generic message. This particular failure is a message that comes from DNS a exception.
So long as they don't log in raygun as unhanded exceptions then it makes sense to pass the value on to the user.
