### ISSUE TITLE
Different UPN causes new user creation

### ISSUE THREAD

**Issue by clain23** [OctopusDeploy/Issues#1635]
After changing UPN for AD user it appears as new OctopusDeploy user.

You should probably not use UPN for identification, or somehow merge users.

![](http://d.pr/i/196NX/3ivbioiN+)

**Comment by PaulStovell** [comment]
Let's review this - I don't even know why we used UPNs in the first place, SSID or something else would have been a better choice.

**Comment by DamianMac** [comment]
Closing this. We'll solve a lot of auth issues in the future probably with some claims based system.
