### ISSUE TITLE
Need to flush server thumbprint cache after 2.6 import

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1638]
If you restore a 2.6 backup, you can't connect to upgraded tentacles without a restart because the server has its initial thumbprint in cache.

After a restore we either need to flush the cache, restart the service (not a good idea) or inform the use they need to restart.

**Comment by zentron** [comment]
The plan here is to restart the service after migration completes (obviously not in preview mode). This seems like it would be a fair step to take considering they are in the process of drastically changing the backing data of the server and any number of things could in theory be in an inconsistent state. 

The user will be made aware of this fact during in the wizard.

**Comment by DamianMac** [comment]
You'd want to make sure you only imported if the key changed. We're going to see users running the migrator to import project configs on a regular basis and we'd not want to restart for everything.

**Comment by zentron** [comment]
As this exists only in the management tool and consists of two separate commands, one to migrate one to restart, any users who script the process can skip the restart and all will be right in the world :earth_asia: 
Fix exists in OctopusDeploy@ec0c4f26566983abdacbdb41792faa3afe4f578c

**Comment by zentron** [comment]
available in release 3.0.0.1580
