### ISSUE TITLE
Azure Web App not available in select-list 

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1639]
Azure Web App created in the Management Portal is not appearing in the select-list on the create-target view. 
As described in http://community.octopusdeploy.com/t/azure-integration-in-octopus-deploy-3-0-an-overview/73/5

**Comment by mjrichardson** [comment]
Could you perform the following steps? : 

- Run the Windows Powershell ISE
- Execute `Load-Module "C:\Octopus\Calamari\3.0.1.322\AzurePowershell\Azure.psd1"` (Note: the version number in that path may need to be tweaked to what is actually installed)
- Visit `https://manage.windowsazure.com/publishsettings/index?client=powershell` in your browser, and a publish-settings file should be downloaded. **Note:** This creates a certificate in the Management Portal, and it's details are included in the downloaded file. This file should be deleted (and perhaps the certificate removed from the portal) once you are done with these steps.
- Execute `Import-AzurePublishSettingsFile -PublishSettingsFile "[path to the downloaded publish settings]"` in the Powershell ISE (I think the subscription in the publish-settings file should be selected for use, but to be sure you can run `Select-AzureSubscription -SubscriptionName "[name of subscription included in publish-settings file]"`
- Execute `Get-AzureWebsite`

Is your Web App returned?

**Comment by yooakim** [comment]
I\m trying these steps in a brand new Octopus 3.x server. But there is no Azure.psd1 file in any Calamari folder. There is a `Calamari.nupkg` file in the `C:\Program Files\Octopus Deploy\Octopus` folder.
I've looked on all local disks:
```
Get-ChildItem c:\,d:\,o:\ -Filter Azure.psd1 -Recurse -Force -ErrorAction SilentlyContinue
```
Should this be installed as part of the setup? Does the [Microsoft Azure cmdlets](https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/) need to be in the server Before adding a Azure Deployment target?

**Comment by yooakim** [comment]
You can close this issue. We have several Azure Enterprise Accounts with many subscriptions in each and I had (my misstake) uploaded the management certificate to the wrong subscription.

A small thing that could make this easier is if the Web Space field simply said (None found) or such. Then one would understand that the call to Azure to list webspaces worked but no data came back.

**Comment by mjrichardson** [comment]
Thanks for the update.
