### ISSUE TITLE
Choose Azure Cloud Service config file before PreDeploy scripts are run

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1640]
As suggested in http://community.octopusdeploy.com/t/azure-integration-in-octopus-deploy-3-0-an-overview/73/13

**Comment by edwinf** [comment]
Since Calamari is open source, if it would be helpful I can do a PR for this.

**Comment by michaelnoonan** [comment]
Hi @edwinf, thanks for offering to contribute especially since you can test your specific use case. Submit the PR and keep me in the loop.

**Comment by michaelnoonan** [comment]
Hi @edwinf, I've started work on making `ChooseCloudServiceConfigurationFileConvention` a new Convention that runs after `ExtractAzureCloudServicePackageConvention` and passes the result through the rest of the Convention pipeline.

Check out https://github.com/OctopusDeploy/Calamari/pull/28
