### ISSUE TITLE
Calamari to create working directory under 'C:\Octopus\' rather than temp

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1643]
As suggested in http://community.octopusdeploy.com/t/temp-file-location/197

**Comment by zentron** [comment]
Current thoughts around this are:
- [ ] Pass through `ApplicationDirectoryPath` variable from server based on a new `Work` directory to live in server path, similar to tentacles.
- [ ] Leave cleanup of this directory for the server after the step has completed.

**Comment by zentron** [comment]
Commit @226dd3d7849b96de244337ab0d7d5917f02e6694 is contained in release v3.0.0.1630. Includes a change to Calamari requiring update to v3.0.1.340

**Comment by mjrichardson** [comment]
This should also resolve http://community.octopusdeploy.com/t/bug-pathtoolongexception-on-cloud-service-deployment/239
