### ISSUE TITLE
Projects Drop down shows only one project group and one project

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1651]
_From @IanMercer on June 16, 2015 1:8_

I have two project groups and two projects in each but the Menu bar drop-down only shows the first group and the second project in it (which was the first of each that I ever created).

Now, I have edited the dashboard to show only one project and the projects menu appears to be using that selection and not 'all projects'. So maybe this is by design, but it's confusing.

_Copied from original issue: OctopusDeploy/PrivateIssues#83_

**Comment by PaulStovell** [comment]
It's by design - not going to change for 3.0, will try to pick it up in usability testing in future.
