### ISSUE TITLE
Active Directory error logging

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1653]
From a customer

"This was tracked down to principal.GetAuthorizationGroups() on line 136 of the Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership class.

This call always fails in our environment. At first I thought it was a permissions issue but had a domain admin try on my local so I could see it and it failed with the same exception. I’ve found some documentation on potentially why it fails (hotfix from MS), but nothing concrete, and nothing we’d probably try since this is the only application that seems to run into the issue (to be fair, it’s probably the only one that logs it). You’re fallback code in the catch block reads group memberships just fine so we don’t have any “real” issues, just a spammy error in the logs."

**Comment by PaulStovell** [comment]
Will be fixed by: https://github.com/OctopusDeploy/Issues/issues/1737
