### ISSUE TITLE
Calamari update logic change

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1660]
- [ ] Change health checks to no longer use Calamari, but they will check if the latest Calamari is there
- [ ] Machine document to get a HasLatestCalamari, set from health check
- [ ] Environments page will make machines without latest Calamari yellow, and show a green Update button (per environment) - this will just run a script that ensures Calamari is there
- [ ] When deploying to an environment with out of date Calamaris, they will be automatically upgraded. An info message on the deployment page will notify the user that this will happen.

**Comment by vanessalove** [comment]
So this was a discussion in the office that does not appear to have been documented.
The outcome was the automatic update of calamari was nice, but it should be optional per environment if it auto updates (so large environments or production can be upgraded when is best for the customer).

A now problem is SSH does not upgrade calamari on healthcheck just gives a warning - so this would mean ANY environment with SSH would have to be 'opted in' and update pushed.
This needs thinking about or SSH should behave like the other endpoints and update calamari at healthcheck ?

**Comment by IanMercer** [comment]
Rather than "Machine document to get a HasLatestCalamari, set from health check" should it instead store the actual Calamari version so "hasLatestCalamari" can be calculated as new versions become available.

**Comment by alfhenrik** [comment]
Release notes: Allow updating outdated Calamari versions from the `Environments` page
