### ISSUE TITLE
Configuring a new instance to point at an existing database throws a CryptographicException

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1661]
From http://community.octopusdeploy.com/t/exception-when-installing-new-octopus-3-rel-6-server/249 and http://community.octopusdeploy.com/t/automated-server-install-howto/191/4

On a new install, a new master key gets created which means encrypted values can no longer be decrypted.

**Comment by mjrichardson** [comment]
Connects to OctopusDeploy/Issues#1645
