### ISSUE TITLE
Unable to delete step template that was used in a deployment

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1662]
http://community.octopusdeploy.com/t/bug-step-templates-bugs-usage-deleting/260

Bug #1 - Unable To Delete Step Template

A step template that was used in a deployment can not be deleted, even if it is no longer a part of the release process.

Bug #2 - Usage shows incorrect usages

A step template's "Usage" tab shows all usages of all step templates. (See below screenshot)

Bug #3 - Out of date Label is displayed on incorrect step template usages

When incorrect step templates are listed (from Bug #2 above), they all show as Out of date. (See below screenshot)

**Comment by zentron** [comment]
Fixed in 3.0.1.2071
see: https://github.com/OctopusDeploy/Issues/issues/1723
