### ISSUE TITLE
Log file naming clashes with new installs

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1665]
A log file from an old (perhaps testing) install will get merged in with a newer task (from fresh DB) when they have the same ID. Perhaps a differing naming convention for logs is needed to avoid clashes.

**Comment by PaulStovell** [comment]
Task logs start with the task Id (e.g., ServerTasks-17). We will add a property to the ServerTask doc with a random token and include that in the file name.

**Comment by PaulStovell** [comment]
Decided not to do anything about this

**Comment by PaulStovell** [comment]
Re-opening this since it happened to one customer and will likely happen again.

**Comment by PaulStovell** [comment]
Fixed - we now append a random string to the end of each file, which will ensure they are unique
