### ISSUE TITLE
Cancelling a nuget deployment task hangs and this causes further nuget deployment tasks to hang

### ISSUE THREAD

**Issue by uldissturms** [OctopusDeploy/Issues#1669]
Task never leaves cancelling state and all other deployment tasks wait in a queue - even for deployments to other tentacles. It works again after restarting server service and rescheduling all pending tasks. There is no error logging when this happens. There is no reproducible scenario - this happens from time to time - has happend twice in the last two weeks. There was one task that was able to deploy while the other task was hanging - one that did not have a nuget step. Any help or directions would be most helpful.

**Comment by vanessalove** [comment]
fixed in 3.0 https://github.com/OctopusDeploy/Issues/issues/1431
