### ISSUE TITLE
Nested variables value get encoded when being replaced in config files

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1675]
Var1 = #{Var2}
Var2 = P&ssword

When trying to use Var1 with the **Configuration Variables** feature, the value set on the config file ends up being "P&amp;ssword"

Var2 does not get encoded if used directly, instead of being nested inside Var1. This seems to break only when its nested.

Source: http://help.octopusdeploy.com/discussions/questions/4970

![variables](https://cloud.githubusercontent.com/assets/6180562/8316294/5f03bac0-19cc-11e5-8afb-b14e7b68a8bd.JPG)

![webconfig](https://cloud.githubusercontent.com/assets/6180562/8316322/90a54eea-19cc-11e5-875b-baee1db77e96.jpg)

**Comment by PaulStovell** [comment]
`P&amp;ssword` is the correct value that should go to the config.
