### ISSUE TITLE
Windows Service scripts do not wait until existing service stopped

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1677]
The Windows Service deployment scripts `AfterDeploy.ps1` and `BeforePostDeploy.ps1` both use the `Stop-Service` [ PowerShell command](https://technet.microsoft.com/en-us/library/hh849790.aspx?f=255&MSPPError=-2147217396) to stop any existing service. 
This command however does not wait until the service has stopped before continuing. If the shutdown process takes a longer than normal then the deployment may fail  due to locked resources.
Users have reported that occasionally this requires executing the deployment a second time, at which point their existing service has terminated from the initial attempt and the deployment completes successfully.

These scripts should be updated to check the state of the service with some mechanism to confirm it is no longer running, e.g:

>do { Start-Sleep -Milliseconds 200}
until ((Get-Service $service).status -eq 'Stopped')

Source: http://help.octopusdeploy.com/discussions/problems/35378

**Comment by mjrichardson** [comment]
I think I covered this with https://github.com/OctopusDeploy/Issues/issues/1704
