### ISSUE TITLE
Octopack - support Xamarin projects for apk's etc.

### ISSUE THREAD

**Issue by dazinator** [OctopusDeploy/Issues#1678]
I have written an xamarin android project. When this builds it outputs an apk file.
If i try to add Octopack to this type of project - I can't. Is there a way this can be supported?

**Comment by PaulStovell** [comment]
I don't believe so and it's not something we'll be able to add support for any time soon - might be best to open this as a suggestion on octopusdeploy.uservoice.com. Thanks!
