### ISSUE TITLE
SSH error message isn't quite right

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1682]
This is an SSH endpoint which has never successfully connected because it doesn't support sftp.

`There was a problem with your request.`

`One or more machines in the selected environment are running outdated versions of the Tentacle agent, and they must be upgraded before deployment can proceed. The following machines need to be upgraded: ...`

It's not "running an outdated Tentacle Agent": it's not running anything.

**Comment by PaulStovell** [comment]
Health check fails and gives it version 0.0.0 - it should leave it null

**Comment by PaulStovell** [comment]
Thanks for getting in touch. You've raised a valid issue, but unfortunately we don't think we will have time to fix this in the near future due to other priorities. We've decided to close it for now. For more information, please see this page:
http://octopusdeploy.com/roadmap/why-was-this-closed
