### ISSUE TITLE
Package acquisition crashes server

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1686]
Our current package acquisition strategy means all packages are downloaded to the server in parallel and uploaded to every tentacle as they finish downloading.  When there are a lot of packages the server can be simultaneously uploading and downloading hundreds/thousands of packages which kills CPU, leads to SQL timeouts and eventually crashes the server.

**Comment by PaulStovell** [comment]
Time cap this to 1 day. 

Check if we can quickly and simply calculate if we are over 80% saturation on disk, CPU, memory or bandwidth, and if so, don't add any new tasks (ParallelWorkOrder). 

If this isn't easily doable, just cap max parallelism to 10. 

Also let's fix underlying causes of semaphores being released (octodiff), log writer cache misses, and set SQL timeouts to a bigger value.

**Comment by PaulStovell** [comment]
For the log writer cache misses, I think `ServerLogStorage.Append` or the cache that it uses needs a `lock`. At the moment two threads could try to append at the same time, both miss the cache, and then two appenders would be created. When the appender is created it calls `EnsureWriter` which opens a file stream.
