### ISSUE TITLE
Octopack - Allow Version to be provided by .nuspec file

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1688]
Refer to http://help.octopusdeploy.com/discussions/problems/35368-using-nuget-versioning-with-build-number

The principle of least surprise would mean we should do things similarly to NuGet.exe:
1. Command Line Argument
2. .nuspec file
3. Assembly Version

In the meantime the Command Line Argument can be used to work around this issue.

**Comment by PaulStovell** [comment]
Closing since there's a workaround
