### ISSUE TITLE
Task log output from delta being cut off

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1689]
Sometimes log output from deltas is being cut off. The log will show delta 0% instead of 100%. To reproduce, run a deployment with delta on Tentacle Army.

**Comment by tothegills** [comment]
eg:

17:17:14   Info     |             Applying delta: 0%
17:17:14   Info     |             Applying delta: 10%
17:17:14   Info     |             Applying delta: 20%
17:17:14   Info     |             Applying delta: 30%
17:17:14   Info     |             Applying delta: 50%

**Comment by PaulStovell** [comment]
Log output lines from a process run with SilentProcessRunner are handled by separate threads which may not always have the correct log context.

**Comment by mjrichardson** [comment]
This is an issue with how OctoDiff reports progress.  It is not exactly wrong, just a little confusing.
