### ISSUE TITLE
Investigate what the 4 second delay on tentacles is

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1690]
There is a 4 second delay in logs during a deployment when the server says it is issuing a command (eg. run script) and then the Tentacle actually executing that command.  This is causing delays for deployments that run a large number of scripts.  See http://community.octopusdeploy.com/t/time-taken-for-release-200-plus-increase-in-timings/304/15 for more info

**Comment by niallduggan** [comment]
Hey guys, 

Just checking when this will be available? Not going to upgrade from the current version till then.. 

Regards, 

N.

**Comment by clain23** [comment]
It really hurts cause we have 20 steps.

**Comment by niallduggan** [comment]
Why was this closed? Its still an issue...

**Comment by mjrichardson** [comment]
@niallduggan It was auto-closed because a commit addressing this issue was included in the latest release.
We would be most interested to hear your feedback on whether script run-time is improved by this release (3.0.4).  
If it is still a problem, we will re-open this issue or raise a new one.
