### ISSUE TITLE
Add uninstall for Chocolatey package of Tentacle

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1692]
Fairly self explanatory - see source: http://help.octopusdeploy.com/discussions/problems/26062

**Comment by PaulStovell** [comment]
Not something we'll get around to in the next few iterations so I'm going to move this to UserVoice: http://octopusdeploy.uservoice.com/forums/170787-general/suggestions/8906689-add-uninstall-for-chocolatey-package-of-tentacle
