### ISSUE TITLE
Cannot add HTTP(s) binding using variable with : in the name

### ISSUE THREAD

**Issue by pauldambra** [OctopusDeploy/Issues#1694]
our naming format for variables is areaOfSystem:Thing so in this instance api:BaseUrl

When setting this as the url for an http or https binding it appears to work. Then deployment fails with:

```
Error    01:27:53
foreach-object : Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid Boolean."
Error    01:27:53
At C:\Octopus\Applications\.SQ-MAGNUM-1DC5779F\Octopus.Tentacle\2.6.4.951\Scripts\Octopus.Features.IISWebSite_BeforePos
Error    01:27:53
tDeploy.ps1:86 char:29
Error    01:27:53
+ $bindingString.Split("|") | foreach-object {
Error    01:27:53
+                             ~~~~~~~~~~~~~~~~
Error    01:27:53
    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
Error    01:27:53
    + FullyQualifiedErrorId : FormatException,Microsoft.PowerShell.Commands.ForEachObjectCommand
Info    01:27:53
WARNING: Could not find ssh-agent
Fatal    01:27:53
PowerShell script returned a non-zero exit code: 1
Tentacle version 2.6.4.951
```
and on viewing the process the variable name is truncated at the colon. These variables work elsewhere in our octopus setup just not the http binding.

Setting the variable
<img width="712" alt="screen shot 2015-07-05 at 10 23 42" src="https://cloud.githubusercontent.com/assets/984817/8511100/6acb02c2-2300-11e5-9d54-a45d2d3228d2.png">

Process screen before saving
<img width="250" alt="screen shot 2015-07-05 at 10 23 51" src="https://cloud.githubusercontent.com/assets/984817/8511101/6acd39f2-2300-11e5-881c-43782c94397f.png">

Process screen after saving and reloading the page
<img width="190" alt="screen shot 2015-07-05 at 10 24 05" src="https://cloud.githubusercontent.com/assets/984817/8511102/6ace4072-2300-11e5-96ae-59ca90115f64.png">

**Comment by PaulStovell** [comment]
Unfortunately not much we can do about this right now - we'll be refactoring this area soon and so this issue should go away. We use ":" internally as a separator for IIS bindings.
