### ISSUE TITLE
Better logging and feedback on retention policies Tentacle side

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1702]
Currently the retention policies have some logging when run on a project deployment, but there are so many factors as to why some packages are not deleted.

It's two fold, it will allow customers to understand why some packages are not deleted, and it will allow us to troubleshoot if the retention policies are not working as intended

(One of many) Source: http://help.octopusdeploy.com/discussions/problems/30954

**Comment by PaulStovell** [comment]
Dup of #1572
