### ISSUE TITLE
Variable substitution issue on SSH deploy to linux

### ISSUE THREAD

**Issue by RyanMelenaNoesis** [OctopusDeploy/Issues#1706]
On an SSH deploy to a linux server (Octopus Deploy 3.x) the substitution target file entries don't seem to work when they include a path delimiter.

During the variable substitution task Octopus raises a warning: No files were found that match the substitution target pattern '<target file entry>'.

The Octopus field hint list the examples: "Notes.txt, Config\\\*.json" of which the former seems to work but not the latter.  In troubleshooting this issue I tried using the linux standard forward-slash instead of the windows standard back-slash (eg "Config/*.json") but that caused the deployment to fail with a System.IO.FileNotFoundException.

**Comment by PaulStovell** [comment]
Let's decide on this this week.

**Comment by RyanMelenaNoesis** [comment]
Just wanted to make sure you noticed there is a corresponding pull request https://github.com/OctopusDeploy/Calamari/pull/32 @zentron

**Comment by zentron** [comment]
Requesting some unit tests on the PR

**Comment by RyanMelenaNoesis** [comment]
Added a unit test for relative path variable substitution.

**Comment by zentron** [comment]
Release Notes: Workaround for Mono `FileNotFoundException` when calling `Directory.EnumerateFiles` with relative path
