### ISSUE TITLE
OCTO.EXE Compatable with Octopus 3.0 ?

### ISSUE THREAD

**Issue by rkibbe** [OctopusDeploy/Issues#1713]
I am trying to run create-release to my new Octopus 3.0 server with Octo.exe: Octopus Deploy Command Line Tool, version 2.6.3.59. 

I know the URL and API keys are good. I was wondering if there was a compatabilty issue ?

I keep getting this error: 
c:\Program Files (x86)\Jenkins\jobs\Enterprise_JobFeeds.CI\workspace\JobFeeds.Me
ssages>"C:\Octopus\Octo.exe" list-projects --server http://dcooctobetaXXXX/nuget/p
ackages --apiKey API-XXXXXXXX
Octopus Deploy Command Line Tool, version 2.6.3.59

Handshaking with Octopus server: http://dcooctobeta01/nuget/packages
Error from Octopus server (HTTP 404): The resource you requested was not found.
Exit code: -7

I tried something innocuous as list-projects as you can see I still get the error.

**Comment by vanessalove** [comment]
@rkibbe 

Hi, 
Your URL shows you are pointing to the nuget/packages URL and not your Octopus URL. Please try again with the correct URL. nuget/packages is reserved for nuget push and moving your packages into the Octopus Repository.

Vanessa

**Comment by rkibbe** [comment]
Thankyou....that worked. As with many technical issues you fight with for hours it ends up being something really stupid on your part.....this was no exception.
