### ISSUE TITLE
Schema in Migration scripts is inconsisent

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1719]
Some migration scripts refer to tables without schema names, some include them. This can cause issues when the user creating the tables or updating them has a different default schema. Best practice is for all names to include the schema.

e.g.
    `... FROM dbo.[Account] ...`
vs. 
    `... ALTER TABLE [UserRole] ...`

**Comment by PaulStovell** [comment]
Going to close this as YAGNI. We do not support using any schema that isn't `dbo.`, or mixing our database with other data. Our scripts being inconsistent will probably catch it, and if it does ever come to support then we can do the work to try and detect and guard against it.
