### ISSUE TITLE
Broken z-index for variables pop-up window for bindings

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1721]
At the current state its not possible to interact with the pop-up window at all.

![variableszindex](https://cloud.githubusercontent.com/assets/6180562/8787294/b2a6300c-2f09-11e5-8466-05d65695ce81.JPG)

Octopus Version: 3.0.1.2063
Browser tested: Chrome
source: https://octopusdeploy.uservoice.com/admin/tickets/5459

**Comment by zentron** [comment]
also referenced in 
http://help.octopusdeploy.com/discussions/problems/36180-issues-with-insert-variables-pop-up-in-edit-iis-binding-form
