### ISSUE TITLE
API links inaccurate with 3.0

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1724]
The [`/api/serverstatus`](https://demo.octopusdeploy.com/api/serverstatus) URL returns links that do not apply in 3.0.
See [http://help.octopusdeploy.com/discussions/problems/36175](http://help.octopusdeploy.com/discussions/problems/36175) for initial report.

We should do a runthrough of each endpoint to ensure they're accurate.

**Comment by PaulStovell** [comment]
Removed the obsolete links, couldn't spot anything else that was obsolete.
