### ISSUE TITLE
Missing space in variable after 3.0 upgrade/migration

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1725]
Project variable had a space ie #{SSL thumbprint} but after the migration and upgrade it would not work but it would if the space was removed, customer had to remake the var again.

Source: http://help.octopusdeploy.com/discussions/problems/36182

Please investigate where the space might have gone .. during migration or something else.

**Comment by zentron** [comment]
Tested 2.6 -> 3.0 Migration and space looks to have been preserved no problem. Task outputs the variable correctly so looking for more info from user to continue.
![screenshot 1](https://cloud.githubusercontent.com/assets/1830666/8840702/47dc2918-3128-11e5-96ff-dcd1d407e995.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/1830666/8840703/47dd4dde-3128-11e5-8471-9b2b00dfb384.png)
