### ISSUE TITLE
Migrator: Option to limit import of historical data (releases, deployments, events, server tasks, server task logs)

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1732]
People need a way to reduce the number of Events being imported from 2.6 backups. Some way to either skip them all or to skip older ones during migration would be very helpful.

**Comment by IanMercer** [comment]
More customers are asking for this. Very large Octopus setups need a way to prune history.

**Comment by bigbam505** [comment]
By history do you mean audit events?  I have an issue which @vanessalove has been helping me with.  One thing I also noticed is that the task logs take up a large amount of time. We have nearly 90 gb of servers tasks (I assume they don't get cleaned up ever) and our time spent restoring was very high.  One thing that would be nice is having the ability to just ignore these server tasks / release data with an option maybe.  Just throwing some ideas in here.

**Comment by IanMercer** [comment]
Now looking at expanding this to mean all history: Releases, Deployments, Events, ServerTasks, ServerTask logs. Current plan is an extra parameter `maxage` specifying a limit on how many days of historical data to import.

**Comment by bigbam505** [comment]
as long as that helps bring down the import time considerably for large data sets that sounds like it could fix the issue

**Comment by bigbam505** [comment]
Any idea when this will be released?  Not trying rush just trying to get an estimate on when I can try to restore from backup and test octo 3.0 with our current infrastructure.

**Comment by IanMercer** [comment]
It's in testing now. Task logs are importing much faster too. Probably in tomorrow's release.

**Comment by bigbam505** [comment]
Awesome thanks so much !

**Comment by IanMercer** [comment]
Release note: Migrator now has a maxage=<days> command line option to set limits on history import. (Note: Not available from GUI)
