### ISSUE TITLE
Increase ServerTask.Description length to MAX

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1733]
The `ServerTask.Description` for Deployments is built by: `"Deploy " + project.Name + " release " + release.Version + " to " + environment.Name` which can get long. This column is not indexed so there's no downside to increasing the length to MAX.

We previously increased the database column in https://github.com/OctopusDeploy/OctopusDeploy/commit/fcd09b3c3f91e198d655acd98799b54cf742da3a, but missed the `DocumentMap<ServerTask>`.

**Comment by nathan-alden** [comment]
Thanks for the timely fix, guys. :+1:

**Comment by michaelnoonan** [comment]
My pleasure @nathan-alden. I really hope you enjoy Octopus 3.
