### ISSUE TITLE
OctopusBypassDeploymentMutex is not available in 3.0

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1736]
The `OctopusBypassDeploymentMutex` was removed to let everything run in parallel in Calamari, however this is causing issues for people who rely on being able to use shared resources safely.

Original email:
> I'm seeing parallel deployments on the same tentacle clashing on 3.0.0.1666. I've set OctopusBypassDeploymentMutex to explicitly be False, but still seeing it happening. and the two deploys are fighting over resources. Known issue fixed in RTW, or bug?

**Comment by zentron** [comment]
According to user-supplied logs the latest failure looks to be due to multiple parallel steps deploying to the same location.
