### ISSUE TITLE
Pluggable authentication support

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1737]
Make it easy for people to write plugins for authentication provides. Possible scenarios might be: 

 - Federated identity
 - Making it work with a really complex AD setup

Would fix: https://github.com/OctopusDeploy/Issues/issues/1000

**Comment by PaulStovell** [comment]
Closing this and will re-open when the backlog gets smaller and it comes up again.

**Comment by vgilbertsson** [comment]
Paul I believe in you. :) Please open this issue again. This is a real showstopper!

**Comment by gregjhogan** [comment]
Please implement!

I would like to see federated authentication support (such as SAML/OAuth) where claims of a specific format automatically map you to a team.

For example, a claim of OctoTeam-[TeamName] automatically gives you the permissions/roles for that team when logging in.  This allows you to completely (and easily) manage permissions outside octopus by mapping claims based on a prefix (e.g. OctoTeam-*).  If your IDP supports MFA, hopefully you would get that for free, too.

This may not work well with how API keys currently work, but I wish the API keys were more loosely tied to a user.  It is important to know that I created one or more API keys, but I don't want it to represent me ... I want it to represent a set of permissions (often not all of my permissions).

**Comment by fruffin** [comment]
+1 for this
SAML or OAuth would make it a lot easier to manage permissions, and especially cut off access if/when people leave the business

**Comment by vanessalove** [comment]
@gregjhogan I was just reading through this thread, for your comment about API keys - do you know about service accounts? They are accounts that cannot login to the UI but can have API keys and permissions. They are recommended for automation and are not tied to other users accounts so may mean less maintenance of permissions. http://docs.octopus.com/display/OD/Service+Accounts

**Comment by gregjhogan** [comment]
@vanessalove thanks for the followup.  I did not know about service accounts at the time, but we have since discovered them and use them for our build server.  These work great, thanks!

**Comment by asbjornu** [comment]
It has [come up again](http://help.octopusdeploy.com/discussions/questions/7885-change-domain-controller). :smile:

**Comment by JasonDonnelly** [comment]
This is a +3 for me.  With-out it I am unable to delegate granting user access to Octopus, via Active Directory group membership, to my service desk and thus can never take a vacation !!

Please, have a little heart and implement this sooner rather than later.  I need a vacation.

**Comment by slewis74** [comment]
This is being implemented in #2593
