### ISSUE TITLE
IIS feature: improve how settings are serialized

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1738]
Currently we use ":" to separate out the parts of IIS bindings in the IIS feature. This causes a few problems 

 - Variables that use a ":" in their name break it
 - IPv6 IP addresses break it

Make sure this change is backwards compatible

**Comment by michaelnoonan** [comment]
Source: http://help.octopusdeploy.com/discussions/problems/34608

**Comment by michaelnoonan** [comment]
Source: http://help.octopusdeploy.com/discussions/questions/5795-recommendation-for-mitigating-no-ipv6-support

**Comment by zentron** [comment]
Release Note: IISBindings now support IPv6 addresses
