### ISSUE TITLE
Dashboard is not updated once deployment finishes

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1740]
The icon keeps [spinning](http://38.media.tumblr.com/5ee6ded7952e91dec2c0398e7d699561/tumblr_ncee5eqGdm1tdkigpo4_400.gif) even though the deployment has finished. In the background, calls to `/api/progression/[Project-ID]` are being made and they inform that the deployment has finished.

The icon is updated properly after a manual refresh

![spining_deployment](https://cloud.githubusercontent.com/assets/6180562/8832875/cf6e15a0-3081-11e5-871c-8057c3aa2318.JPG)
----------
----------
![spining_overview](https://cloud.githubusercontent.com/assets/6180562/8832877/d1ca238e-3081-11e5-8290-423ded9e6c05.JPG)

**Comment by michaelnoonan** [comment]
Fixed in 3.0.5
