### ISSUE TITLE
Migrator from 2.6->3.0 does not import license key or SMTP configuration

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1746]
Have seen a couple of reports of the license key not being imported. If people haven't saved their license key somewhere (or whoever got the email has since left) they'll have to contact support to get their key. Let's try to fix this.

**Comment by vanessalove** [comment]
I've had quite a few reports of this - mostly from people who  don't have access to their license keys easily.  So its obviously happening for everyone. I added a warning note in the in place upgrades for people to copy down their license keys - but it would be great (and help with support) to get this one done for monday

**Comment by michaelnoonan** [comment]
I created other Issues to track these separately.
License: https://github.com/OctopusDeploy/Issues/issues/1778
SMTP: https://github.com/OctopusDeploy/Issues/issues/1779
