### ISSUE TITLE
Rendering issues in IE11

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1748]
https://twitter.com/paulstovell/status/623772650540699648

**Comment by PaulStovell** [comment]
This all seems to work fine for me (IE11 on Windows Server 2012). I suspect the Intranet zone and quirks mode might be having an effect, or maybe someone else fixed it already.

**Comment by DamianMac** [comment]
Looks like it's all good! https://twitter.com/philliphaydon/status/624582607817191424
