### ISSUE TITLE
Updating variables in a release is not working

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1749]
The following error is logged in the browser console when clicking the `Update Variables` button:

![image](https://cloud.githubusercontent.com/assets/1035315/8843094/1506ebbc-3147-11e5-860b-d15c2e835c94.png)

**Comment by michaelnoonan** [comment]
I've been able to reproduce this.

**Comment by zentron** [comment]
Item has since been fixed in earlier build.
