### ISSUE TITLE
Configuration transforms not working with files that have spaces

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1757]
Configuration transforms won't be applied when the source file name has spaces in it.
For example, `Web.Environment A.config => web.config` does not apply transforms from `Web.Environment A.config`.

**Comment by zentron** [comment]
This bug appears to only occur if the files are manually added to the nuget "zip".
Sounds to be related to a difference in how nuget deals with with white space vs normal zipping tools.
If the files are added to the nuget package via octopack or nuget directly using the pack command, then the files are correctly embedded and the transformation works fine.

Related issue from SO:
http://stackoverflow.com/questions/19810844/nuget-encodes-the-blank-spaces-in-names-of-files
