### ISSUE TITLE
Allow XML header in release notes file uploaded by Octo.exe

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1760]
The [XML declaration line](https://xmlwriter.net/xml_guide/xml_declaration.shtml) at the top of an XML file doesn't seem to be handled. i.e.:

    <?xml version="1.0" encoding="UTF-8"?> 

Reported in http://help.octopusdeploy.com/discussions/problems/29304

**Comment by PaulStovell** [comment]
These release notes are put into a .nuspec file, so I'd be surprised if it worked. What happens in NuGet Package Explorer?

**Comment by Damovisa** [comment]
Tested on 3.0 and `Octo.exe` adds XML release notes as expected. It's rendered as XML so doesn't look great, but it works.

Note that this isn't adding to the nuspec file, it's adding via the `octo.exe` commandline argument.

![image](https://cloud.githubusercontent.com/assets/1887732/8900250/69c49662-3481-11e5-81ae-3573939b874c.png)
