### ISSUE TITLE
Generic upgrade how to page

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1766]
Getting a few questions on how to upgrade new 3.0 versions AFTER the 3.0 upgrade.
Customers are just wary cus its all different.

Having a best practice isnt a bad idea anyway - ie put into maint mode, make sure deployments arent running (it will kill them) etc run the installer

how tentacles will be upgraded, how calamari is updated.

**Comment by zentron** [comment]
Documentation for upgrading 3.x is now available at
http://docs.octopusdeploy.com/display/OD/Upgrading+from+Octopus+3.x
