### ISSUE TITLE
Long project names without spaces are not handled well in the UI

### ISSUE THREAD

**Issue by nathan-alden** [OctopusDeploy/Issues#1767]
This has been a long-standing niggle of mine. There are some places in the UI where long project names without spaces are not handled well. I usually name my projects after their NuGet packages, so I see this a lot.

![image](https://cloud.githubusercontent.com/assets/1189759/8880492/d5166fa6-31fe-11e5-8c8b-9e8719a6ca96.png)

The dashboard's project column is also quite useless, as all I see is `MyCompany.MyPro...` for every entry.

**Comment by PaulStovell** [comment]
Thanks, this is fixed in 3.0.10

**Comment by michaelnoonan** [comment]
Release Note: Improved the display of long Project names that don't have spaces
