### ISSUE TITLE
Long release versions cannot be seen properly from the dashboard

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1768]
Hovering the mouse over doesn't show the full name either. This will be a problem for almost any version with a branch name on it.

![longreleaseversion](https://cloud.githubusercontent.com/assets/6180562/8882349/9eab9176-321c-11e5-84be-df5c9dad6a75.JPG)

Octopus Version: 3.0.5.2124
Source: http://help.octopusdeploy.com/discussions/problems/36308

**Comment by nathan-alden** [comment]
This issue appears in several places. In 2.6, it looked like they force-wrapped long lines, so that even lines without spaces were wrapped; now, they ellipsified the text--without tooltips, I might add--such that, at least for my install, much of the content on some screens is ambiguous.

**Comment by PaulStovell** [comment]
Fixed in 3.0.10 - we'll force some words to split up if needed.

**Comment by michaelnoonan** [comment]
Release Note: Improved the display of long release versions on the Dashboard
