### ISSUE TITLE
Reports of Hydra installs that needed manual reinstall

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1769]
I've had a report of a hydra install that had tentacles not updating their service paths.

Source: https://secure.helpscout.net/conversation/106903689/305/

Can we at minimum update the Hydra package to include the MSI with the fix so it doesnt happen to more customers with larger installations who havent upgraded yet

And is there an option to use Hydra in 3.0 yet to help the customers this has effected?

**Comment by Damovisa** [comment]
Documentation has been updated to point to the newer Hydra MSI.
We'll do this manually for the time being, with an aim to automate an updated link from the Octopus downloads page.
