### ISSUE TITLE
When you delete a user who is part of a team the ID remains in the team 

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1770]
When you delete a user it doesnt remove their userID from the team list, and thus when you go to the team after you cant bring up the page, it stays as the spinny icon - reported by customer, replciated by me.

Source: https://secure.helpscout.net/conversation/107200071/349/

**Comment by PaulStovell** [comment]
Originally reported as just a bug with teams and users, it actually affects all relationships where we want to remove an item from a list (in this case, a team has a list of users).

**Comment by PaulStovell** [comment]
Fixed in 3.0.6
