### ISSUE TITLE
Proxy configuration is not used by Calamari

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1774]
It appears as though the process of performing Azure tasks is not using the proxy settings that the user configures. This might make sense since although we set the `WebRequest.DefaultWebProxy` in `ProxyInitializer`, I'm not sure if these values are being consumed in either the 3rd party Azure libraries, powershell scripts or calamari.
This issue needs further testing and investigation.

**souce:** http://help.octopusdeploy.com/discussions/problems/36299

**Comment by PaulStovell** [comment]
I expect this is less to do with Azure and more just PowerShell/Calamari in general.

**Comment by PaulStovell** [comment]
Octopus Server and Tentacle both set environment variables for proxy configuration. These are then loaded by ScriptCS and PowerShell scripts, as well as Calamari itself. This way any attempts it makes to use external services should use the correct proxy.

**Comment by zentron** [comment]
User reports proxy not working as expected
http://help.octopusdeploy.com/discussions/problems/36299

**Comment by zentron** [comment]
Ticket reopened at #1874
