### ISSUE TITLE
Package auto-increment pattern ignores correct build numbers

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1776]
**Background**
Assume I have an existing package, `1.2.2` and I create a release via some mechanism (in this example octopack) using the provided package number `1.2.i`.
The generated new release will be `1.2.3`
Issued again then the release will correctly be `1.2.4`.

If however I then request a new release, bumping the major number (`2.0.i`) the generated version is `2.0.5`. This is because it looks like it just uses the build component of the latest generated build regardless of the build number components in the provided pattern. There actually were no `2.0.0`-`2.0.4`

If I also then decide I need to build a release back from the previous major, passing in again `1.2.i` It will then generate a build number `1.2.6` (next revision increment from last build of 2.0.5).
Since 2.0.5 > 1.2.6, now no matter how many times I try to create a release using `1.2.i` it will always return `1.2.6`, meaning only the first time succeeds and all other times will fail saying that it has already been used.

**Proposed Solution**
* The auto-increment logic used during release creation needs to take into consideration the version number components of the provided version before deciding what the next incremented number needs to be. 
* This will also require a little more smarts around the DB retrieval of previous versions to ensure the appropriate build numbers are returned and _not_ just the chronologically latest releases.
* Bumping a major/monor/revision for the first time will require the increment to start again at 0.

**Source**
http://help.octopusdeploy.com/discussions/questions/5177-auto-increment-release-number

**Comment by arex1337** [comment]
Our Enterprise is also negatively affected by this bug

**Comment by michaelnoonan** [comment]
Release Note: Improved the Release version auto-increment logic
