### ISSUE TITLE
Health check should use Environment properties rather than WMI to get machine host name

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1777]
Health check currently uses WMI to get the machine host name. This appears to cause problems on older combinations of PowerShell/Windows with an "Invalid query" error. 

We're switching this to use `[Environment]::MachineName` instead of WMI. 

Source: https://secure.helpscout.net/conversation/107591942/364/

**Comment by PaulStovell** [comment]
Fixed in 3.0.6
