### ISSUE TITLE
Web UI does not allow a project to be deleted when that project contains errors

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1784]
The DELETE button is present on a tab that you cannot get to when there is an error in the project.

Specifically, if, say the deployment process is missing the user gets an error message like `The resource 'deploymentprocess-Projects-13' was not found.` and then there is nothing they can do from the UI to delete it.

The Migrator allows import of 2.6 backups even when errors are present so that customers can recover their other projects but they need a way to be able to delete 'bad' projects.

This is an Angular/WebUI issue.

**Comment by Damovisa** [comment]
Can the project be deleted via octo.exe or the API?
If so, I'd argue that's a reasonable workaround - particularly if deleting is their only option.

**Comment by vanessalove** [comment]
While I guess something like that could be done, we have had complaints that they lost all their variables and other steps with no way to view them - no one likes the path back to 2.6 to fix it for 3.0.

is there anything else that can be done? placeholder for the error process?

**Comment by Damovisa** [comment]
As a once-off workaround,  I think it would be better to add the missing record to the database, sans steps. That at least should allow the user to see the process.
We'd just have to be careful not to leave the data in an unknown state (although it is already) - if there's a chance of that, a delete is safer.

**Comment by IanMercer** [comment]
Today's release allows deprecated actions to still be imported so users are unlikely to see this issue again unless a project is corrupted somehow by perhaps changing data in SQL directly.

**Comment by maartenba** [comment]
Vanessa sent me a workaround to add an empty steps list using SQL - that worked.

**Comment by zentron** [comment]
Now that we have a workaround for this (manually tweaking the SQL) and the projects should no longer  import with faulty data this will likely occur, as Ian noted, when the underlying data is corrupted or validation changes. For this reason I will de-prioritize the ticket.

**Comment by vanessalove** [comment]
@zentron its not just one customer with one project - the more I think about it the more SQL isn't really going to work - its still a priority

**Comment by PaulStovell** [comment]
Migrator will no longer import projects into a broken state, so fixed in 3.0.8
