### ISSUE TITLE
sc.exe config failed with exit code: 1639

### ISSUE THREAD

**Issue by mvp1108** [OctopusDeploy/Issues#1787]
when trying to deploy a windows service, the command is logged as:

sc.exe config MemDataCollectionService binPath= "\"C:\Program Files\JCI\MEMDataCollector\MemDataCollector.exe\"" DisplayName= "MemDataCollectionService" depend= / start= auto obj= NT Authority\Network 

but it fails with the error:

sc.exe config failed with exit code: 1639
Error    11:02:28
At C:\Program Files\JCI\MEMDataCollector\Octopus.Features.WindowsService_Before
Error    11:02:28
PostDeploy.ps1:112 char:3
Error    11:02:28
+         throw "sc.exe config failed with exit code: $LastExitCode"
Error    11:02:28
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error    11:02:28
    + CategoryInfo          : OperationStopped: (sc.exe config f...exit code:  
Error    11:02:28
   1639:String) [], RuntimeException
Error    11:02:28
    + FullyQualifiedErrorId : sc.exe config failed with exit code: 1639
Error    11:02:28
Error    11:02:28
Script 'C:\Program Files\JCI\MEMDataCollector\Octopus.Features.WindowsService_BeforePostDeploy.ps1' returned non-zero exit code: 1
Error    11:02:28
Running rollback conventions...
Error    11:02:28
Script 'C:\Program Files\JCI\MEMDataCollector\Octopus.Features.WindowsService_BeforePostDeploy.ps1' returned non-zero exit code: 1
Error    11:02:28
The remote script failed with exit code 1

I have seen this error in an earlier issue on this site, since closed, but we are using the 3.x version of Octopus Deploy and the original bug was logged against 2.6 and fixed in 2.7.

**Comment by michaelnoonan** [comment]
Hi Marc,

Thanks for getting in touch with us! Error code `1639` means `Invalid command line argument` and it would appear that we're not correctly quoting the `NT Authority\Network` for the `obj` argument in this case.

https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Scripts/Octopus.Features.WindowsService_BeforePostDeploy.ps1#L69

We'll get on to fixing this as soon as practical. In the meantime you could use another account or [use your own Calamari](https://github.com/OctopusDeploy/Calamari)!

Hope that helps!
Mike
