### ISSUE TITLE
Dropdown control for the Step Template parameter always presents the first value instead of the actual value

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1788]
Reproduce on: 3.0.6.2140

We use IIS AppPool - Create custom step from https://library.octopusdeploy.com/#!/step-template/actiontemplate-i.... Please take a look the two issues presented below.

1). While the edition of the UI params of the IIS AppPool - Create step in the Process tab we change Managed Runtime Version drop down from CLR 1.1 to CLR 4.0 and press Save. But after saving we see that the control still presents old unchanged value (CLR 1.1 - it's first value in the drop down). But if we changed view to the 'Custom Expression' we will see that actual value has been really changed. So, the issue is related only to the presentation of the displayed text, not real value.

Attached image is related to this issue.

2). Also if we click Reset for the Custom Expression view the value will be changed to the CLR 4.0 (the last item in the drop down), even if the previous actual value was CLR 2.0.

We have the same issues for any other drop downs in the Chrome 44.0.2403.107 and IE 11 both.

Could you please check these potential defects?

Thank you.

![octopus_bug](https://cloud.githubusercontent.com/assets/6180562/8916777/20765cc2-3484-11e5-99c9-87b8186892d3.png)

Source: http://help.octopusdeploy.com/discussions/problems/3647

**Comment by zentron** [comment]
1) Fix for the binding not working should be out in next release.
2) The default value for this parameter in the script template is `v4.0` so working as expected. Possible confusion due to issue 1 above?
![image](https://cloud.githubusercontent.com/assets/1830666/8922693/aad9a1d0-3529-11e5-9649-7fdbe3bd2eae.png)
