### ISSUE TITLE
"The passwords do not match" when creating a new user

### ISSUE THREAD

**Issue by maartenba** [OctopusDeploy/Issues#1795]
When creating a new user and entering matching passwords, I get a warning saying "The passwords do not match". In other words: can't create a new user.

**Comment by vanessalove** [comment]
Hi Maarten,

This is a bug we have NEVER been able to track down - are you using FF ?
We have had it only reported a handful of times.

We have found *everytime* it was firefox and we think its to do with its password manager or an addon password manager or some kind of 'data filling' addon.
It never happens for us with just FF.

Can you confirm anything about that?

Vanessa

**Comment by maartenba** [comment]
Using the brand new Edge browser in Windows 10.

**Comment by PaulStovell** [comment]
We'll check this when we do a general pass for Edge compatibility in the near future.
