### ISSUE TITLE
The variable Octopus.Release.Number is no longer working

### ISSUE THREAD

**Issue by Jason-Black** [OctopusDeploy/Issues#1798]
I reference the following two system variables in a string used in an email that we send announcing production releases:

#{Octopus.Project.Name}
#{Octopus.Release.Number}

The former is being replaced by the name of the project being deployed, but the latter no longer shows a release number, and is not being processed at all.

Example:

Pending Deployment of #{Octopus.Project.Name} release #{Octopus.Release.Number} to Production

is being translated to:

Pending Deployment of TheProject release #{Octopus.Release.Number} to Production

It looks like this broke in the upgrade to 3.0.x.

**Comment by tothegills** [comment]
Hi Jason,

What version of Octopus is this happening on? I am able to send emails with #{Octopus.Release.Number} substituted in Octopus Server 3.0.1+.

**Comment by Jason-Black** [comment]
We're currently running 3.0.5.2124. To make sure we're testing the same thing, here's the full workflow which involves a variable set:

1) We have a variable set that has a variable defined as:

Pending Deployment of #{Octopus.Project.Name} release #{Octopus.Release.Number} to Production

2) A 'Send Email' step is at the beginning of all deployments, running only when we deploy to production. The above variable from the variable set is used in the subject line of the email step.

3) We receive the email with the project name filled in but not the release number.

**Comment by tothegills** [comment]
Unable to reproduce in 3.0.5 on my end, Jason has it working in 3.0.7.
