### ISSUE TITLE
new_octopusartefact fails on OSX

### ISSUE THREAD

**Issue by graemechristie** [OctopusDeploy/Issues#1800]
new_octopusartefact fails when run in bash on OSX with the message:

```
stat: illegal option -- c
09:44:49Error
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```

stat on OSX (and presumably BSD) takes different arguments from it's Linux equivalent.

OSX is a pretty important target for us, as it is mandatory for the deploy of all of our iOS assets. We cannot technically or legally use Windows or linux targets for this.

#### Screenshot of octopus log message from the task 

![image](https://cloud.githubusercontent.com/assets/1361894/8948499/7c4d9856-35da-11e5-9e2d-f26d77e86226.png)

#### The command from the executing step template
```
echo "Adding Octopus Artefact $baseName"
new_octopusartifact "$artefactDir/$baseName"
```

#### Software version of  the OSX host

```
$ uname -a
Darwin mac148094.internal.bunnings.com.au 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109

```

**Comment by robpearson** [comment]
Release Note: SSH Targets now support creating artifacts on Mac OSX.
