### ISSUE TITLE
Convert Azure targets into steps

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1803]
As per http://octopusdeploy.com/blog/azure-changes

**Comment by Nepomuceno** [comment]
This it is just wrong change the whole concept I want to be able to move my infrastructure. if I have few machines and few websites creating conditional steps will be messy

**Comment by michaelnoonan** [comment]
Release Note: Created specific Azure Step Types as per http://octopusdeploy.com/blog/azure-changes
