### ISSUE TITLE
Unable to pass install path to custom powershell script

### ISSUE THREAD

**Issue by lee5i3** [OctopusDeploy/Issues#1805]
In my powershell script "step template"

I have a parameter named "WebOutputPath" that I pass in the install path of the deployment step to so I can have my step template encrypt my connection string file etc

I am passing in an Octopus Variable "#{Octopus.Action[Deploy Website].Output.Package.InstallationDirectoryPath}"

Deploy Website is the name of my deployment step
This is step contains the powershell script as a child step (since its deployed to multiple environments on the same machine)

When i run the offline package on the server I am getting an error "gc : An object at the specified path #{Octopus.Action[Deploy Website].Output.Package.InstallationDirectoryPath}\web.config does not exist................. and so on"

How can I pass the variable across? This works fine on online deployments

**Comment by jrestall** [comment]
Looks like a duplicate of #1618. According to the tag, the Octopus Team are currently working on this :)

**Comment by lee5i3** [comment]
Thanks for the heads up, did not see that bug report

**Comment by PaulStovell** [comment]
Yep, output variables not supported in offline drops currently.
