### ISSUE TITLE
Dashboard API can now return a failed deployment as previous

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1807]
Calling the dashboard API has changed:

    api/dashboard/dynamic?environments=Environments-1&projects=projects-1&includePrevious=true

In `2.6`, this call returned the current deployment, and the last *successful* deployment
In `3.0`, the call returns the current deployment, and the last deployment *regardless of its state*

Reported in: [http://help.octopusdeploy.com/discussions/questions/5190](http://help.octopusdeploy.com/discussions/questions/5190)

**Comment by PaulStovell** [comment]
Could also be related to: http://help.octopusdeploy.com/discussions/problems/29787

**Comment by zentron** [comment]
Release Note: Dashboard API only returns previous items that did not have any warnings or errors.
