### ISSUE TITLE
Changing a Windows Service account back to Local System doesn't take effect

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1808]
Affects Octopus `3.0.7`.

If I create a Windows Service and configure it to run as `Network Service`, the Windows Service is deployed perfectly.

If I then go and change the deployment step to configure the Windows Service to run as `Local System` and deploy a new release, the Windows Service is left running as `Network Service`.

From what I can tell by looking at Calamari (https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Scripts/Octopus.Features.WindowsService_BeforePostDeploy.ps1#L65), the script will ignore configuring the `obj=` argument if there is no account specified, and I assume the Octopus Server doesn't send an Account since `Local System` is the default???

**Comment by zentron** [comment]
Release Note: Correctly set `Local System` as executing user of windows service to ensure it can be applied if the service was previously run under a different account
