### ISSUE TITLE
Upgrade message is incorrectly telling the user to renew their license

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1812]
The upgrade message on the UI is telling the user they need to renew their license to upgrade, however the maintenance date and version they're eligible for suggest otherwise.

See https://secure.helpscout.net/conversation/108582581/478/ for details

**Comment by Damovisa** [comment]
![image](https://cloud.githubusercontent.com/assets/1887732/8983811/94162afc-3710-11e5-8a27-d1ff295ae0f4.png)

**Comment by Jason-Black** [comment]
I was following this bug in the now-closed issue here: https://github.com/OctopusDeploy/Issues/issues/1789

However I too alo still see this message in 3.0.7.

**Comment by tothegills** [comment]
Fixed in OctopusDeploy/Issues#1836
