### ISSUE TITLE
Variable Substitution is ignoring original encoding and when encoding is specified in version  3.0.6.2140

### ISSUE THREAD

**Issue by cgibbons** [OctopusDeploy/Issues#1814]
When trying to perform variable substitution on a file, the resulting file is always encoded as UTF-8 w/o BOM (as seen in notepad++), and the application will not read the file.  The template is encoded as UTF-16LE.  It doesn't matter if I leave the encoding blank (determine encoding based on template) or specify utf-16, it always encodes it as UTF8.  I've created a workaround step that is just a powershell script to re encode the file after substitution and the file encoding is correct and the application will run.  I'm including both the template and the transformed file as part of this issue.

https://www.dropbox.com/s/wxw6t7r5xoaex4u/AppLauncher.PreSub.ini?dl=0
https://www.dropbox.com/s/czur01lh0rd54x6/AppLauncher.PostSub.ini?dl=0

**Comment by zentron** [comment]
Fix has been included in 
Calamari: 3.0.1.382
pushed to
OD: 3.0.10.2263

**Comment by michaelnoonan** [comment]
Release Note: Text Encoding of Variable Substitution files are now preserved after transformation
