### ISSUE TITLE
Make release bullhorn more robust 

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1816]
Test data got into master, then it was fixed, but then the db caches it, so making some changes to make this more robust

**Comment by tothegills** [comment]
we could check `MaximumAvailableVersion <= MaximumAvailableVersionCoveredByLicense` instead of `==` in the UI

**Comment by tothegills** [comment]
When we are building the `UpgradeAvailability`, we should remove any `OctopusReleaseHistory` that is `>` what Octofront gives us?

michaelnoonan [10:14 AM]
That way we would ignore any accidentally added `OctopusReleaseHistory` that is newer than what Octofront is telling us.

**Comment by PaulStovell** [comment]
Could we overwrite whatever is in UpgradeAvailability that isn't in Octofront? That way Octofront is always the source of truth and we can always go back and fix it.

**Comment by michaelnoonan** [comment]
I've added a test which I think makes sense:
```
This test prevents us from accidentally committing the OctopusReleaseHistory for a future release into the wrong branch - yes, it has happened a couple of times and breaks upgrade notices.  We shouldn't release 3.0.8.0 with 3.1 recorded in the OctopusReleaseHistoryProvider which will break upgrade notices. Either find out why 3.1 was added to the OctopusReleaseHistoryProvider and remove, or increase the version of this assembly appropriately.
  Expected: <empty>
  But was:  < <3.1: Released Tuesday, 14 July 2015> >```
