### ISSUE TITLE
Don't automatically create AD users if it puts them over their license limit

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1819]
If the license limits a customer to, say, 20 users, and user 21 attempts to sign in, instead of creating an account, reject them with an error saying it would exceed the license count and to talk to their administrator.

**Comment by PaulStovell** [comment]
Done in 3.0.10

![2015-08-04 13_52_38-sign in - octopus deploy](https://cloud.githubusercontent.com/assets/47085/9052869/29d8a50e-3ab0-11e5-871b-56872a624f32.png)

**Comment by PaulStovell** [comment]
Error message reads: 

> Unfortunately this Octopus server license is limited to a specific number of users, and adding a user account for you would put the server beyond this limit. Please contact your Octopus administrator to either disable some users, or increase the license limit.

**Comment by michaelnoonan** [comment]
Release Note: Now prevents creating an AD user if this would exceed the licensed number of Users
