### ISSUE TITLE
Upgrade to .NET 4.5

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1820]
As per: http://octopusdeploy.com/blog/octopus-3.1-will-be-.net-4.5

 - [x] Install VS 2015 on our build servers (maybe time for new build servers?) so we can use C# 6-isms
 - [ ] Upgrade Octostache
 - [x] Upgrade Halibut
 - [ ] Upgrade Calamari
 - [x] Upgrade Octopus and Tentacle

**Comment by jeetgohil814** [comment]
do you have any idea how soon 3.1 could be released? Definitely ready for these enhancements with Azure

**Comment by PaulStovell** [comment]
Hopefully next week, if not the week after.

**Comment by michaelnoonan** [comment]
Closing as duplicate.

**Comment by michaelnoonan** [comment]
Duplicate of Octopus/Issues#1942

**Comment by michaelnoonan** [comment]
Duplicate of Octopus/Issues#1943

**Comment by michaelnoonan** [comment]
Duplicate of Octopus/Issues#1884
