### ISSUE TITLE
Scheduler breaks if scheduled to deploy one month away

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1822]
Octopus Version: 3.0.8.2251

![schedule_right](https://cloud.githubusercontent.com/assets/6180562/9017978/f47e1ce2-37b0-11e5-8b8e-d8fae359f4d4.JPG)
![schedule_right2](https://cloud.githubusercontent.com/assets/6180562/9017981/f6184550-37b0-11e5-8734-057495d50343.JPG)
![schedule_wrong](https://cloud.githubusercontent.com/assets/6180562/9017982/f759a1a2-37b0-11e5-9700-cb617aa91e24.JPG)

**Comment by Zhaph** [comment]
Looks like you've fixed some of the issues I was seeing in 3.0.5, because I'm unable to successfully set change the date to next month by typing. I'll get our Sys Admin to upgrade on Monday and see how we go.

**Comment by Dalmirog** [comment]
This is working fine now in Chrome and Firefox, but not for Internet Explorer -> #2014 .

**Comment by zentron** [comment]
This bug no longer exists as it looks to be fixed in https://github.com/OctopusDeploy/Issues/issues/2014
