### ISSUE TITLE
Hydra runs old Tentacle after update

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1824]
Hydra starts the old Tentacle service if the new Tentacle has been installed to a different path than the old Tentacle (if old Tentacle has been auto-updated).

**Comment by Damovisa** [comment]
Now:
 - The old `Tentacle.exe` will be used to uninstall the service
 - The  new `Tentacle.exe` will be used to reinstall the service

**Comment by michaelnoonan** [comment]
Release Note:  Hydra now configures the Tentacle Windows Service to use the new version
