### ISSUE TITLE
Process UI says rolling deployment for parallel deployments

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1826]
If a step is configured as a parallel deployment, the UI in the process still says "Rolling deployment".

**Comment by Damovisa** [comment]
![image](https://cloud.githubusercontent.com/assets/1887732/9029458/1817381e-39d7-11e5-823a-0897011dac57.png)
![image](https://cloud.githubusercontent.com/assets/1887732/9029459/1b6876e0-39d7-11e5-9d58-040823d1d542.png)

**Comment by PaulStovell** [comment]
Fixed in 3.0.10

**Comment by michaelnoonan** [comment]
Release Note: The Process Tab UI now correctly indicates Parallel and Rolling deployments
