### ISSUE TITLE
Server crash will leave unfinished tasks

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1827]
If a server instance bounces, it should pick up any unfinished tasks and fail them. However, in a High Availability (or failure) scenario, that server may never exist again, meaning the tasks are never failed.

We need a cleanup scenario in the case of a dead server instance.

We should also potentially look at the `OctopusServerNode` table to clean up dead server instances.

**Comment by PaulStovell** [comment]
A solution might be:

- A scheduled task that runs every 30 minutes
- Checks which nodes have been unheard of for some time (say a couple of hours)
- Marks any Running/Cancelling/Waiting tasks assigned to those nodes as Timed Out

**Comment by PaulStovell** [comment]
#1843 will fix it
