### ISSUE TITLE
Task name line wrapping hides deployment date on task summary

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1828]
> In 3.0, the task name wraps with less characters than in 2.6. Only two lines are shown on the task summary so now we can no longer see the date/time of deployment. Can the task name be given more room?

in 2.6
![image](https://cloud.githubusercontent.com/assets/1830666/9030740/3c59ee84-39ea-11e5-8abc-2fa378c71067.png)

in 3.0
![image](https://cloud.githubusercontent.com/assets/1830666/9030743/447f4f8c-39ea-11e5-9809-161fff3ee47b.png)

Source: http://community.octopusdeploy.com/t/task-name-on-the-tasks-window-word-wrap-more-aggressively-than-in-2-6-cut-off-deploy-date-time/437

Confirm that this stays fixed with any work that comes out of related ticket https://github.com/OctopusDeploy/Issues/issues/1768

**Comment by PaulStovell** [comment]
Fixed in 3.0.10

**Comment by michaelnoonan** [comment]
Release Note: Long Task names no longer obscure the deployment date/time.
