### ISSUE TITLE
History is blank in Task Summary for 3.0 deployments

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1829]
It appears as though only imported history is showing up on the task summary pages and no new entries. Release history currently appears to be working fine.

>I'm not seeing anything being written to the History section of the Task Summary. These are deployments done in 3.0 after a migration from 2.6. Looks like the history from 2.6 was migrated.

In 2.6
![image](https://cloud.githubusercontent.com/assets/1830666/9030912/e8d4777c-39ec-11e5-87de-57460d78d6df.png)

in 3.0
![image](https://cloud.githubusercontent.com/assets/1830666/9030917/efc03d3c-39ec-11e5-9a94-cc51f95a7feb.png)

Source: http://community.octopusdeploy.com/t/history-is-blank-in-task-summary-for-3-0-deployments/438/1

**Comment by PaulStovell** [comment]
Fixed in 3.0.10

**Comment by michaelnoonan** [comment]
Release Note: History in Task Summary page now shows 3.0 Tasks, not just 2.6 Tasks.
