### ISSUE TITLE
Paging through task history while deployment is running will force reload of 1st page

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1830]
From a task details page, you can page through that task's environment deployment history.

![image](https://cloud.githubusercontent.com/assets/1830666/9030993/4996a9b2-39ee-11e5-932c-0c87d6e7c9e3.png)

If you try to load the second page of information, it will revert back to the first if an ajax refresh (i.e. as occurs while viewing an active deployment).

In addition if there are many entries in this list, altough it only initially shows 3 entries, clicking a page button will return the, presumably default page size, of 30 

Source: http://community.octopusdeploy.com/t/three-minor-ui-issues/423

**Comment by PaulStovell** [comment]
This may be fixed as part of a PR I just sent, but I really can't see this one being worth fixing anyway.
