### ISSUE TITLE
Scheduled deployments broken

### ISSUE THREAD

**Issue by nicolasguenther** [OctopusDeploy/Issues#1832]
I tried to setup a scheduled deployment in Octopus 3.0.9. When using the current date as the deployment date everything works fine and i can see the hint (e.g. "The deployment will start in approximately 12 minutes")
![capture1](https://cloud.githubusercontent.com/assets/1576825/9040012/8ee0fd0e-39ff-11e5-8236-d6bb5aab1d13.JPG)
But when i enter another date (wasn't there a datepicker in Octopus 2?) the hint is gone. In this state, when i cklick the "Deploy Release" button, the deployment starts instantly. This behavior is harmful in certain situations.
![capture2](https://cloud.githubusercontent.com/assets/1576825/9040016/91aeb4c2-39ff-11e5-89ad-55e372b9dd1d.JPG)

**Comment by droyad** [comment]
Work around: put a space between the 2nd '-' and the number. Then remove it.
ie: change it to "2015-08- 04" then back to "2015-08-04"

**Comment by zentron** [comment]
The date picker has now been updated and will be available in the `3.0.14` release in the next few days.
