### ISSUE TITLE
Update server command line with configuration for in-built repository location

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1837]
Need an ability to update the in-built repository location from the command line to stop db updates.

**Comment by vanessalove** [comment]
Shane this is necessary for HA so assigning to you ;)

**Comment by tothegills** [comment]
Might as well be able to set the artifacts and logs paths too

**Comment by tothegills** [comment]
Release note: Added a command to set file paths for NuGet repository, artifacts and task logs.
