### ISSUE TITLE
Issue with package re-indexing after changing built-in repo directory

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1839]
*Feel free to change the title of this issue to something more technical and meaningful. The overall problem seems to be a lack of reindexing*

Octopus version: 3.0.10

Setup - 2 packages on *C:\Octopus\Packages* (1.0.0 and 2.0.0)

1) Change the built-in repository path as [shown on the docs](http://docs.octopusdeploy.com/display/OD/Package+repositories) to *D:\Packages*.
2) Only migrate the package 1.0.0. 
3) Restart the Octopus Server. 
4) On the Web UI, under **Packages** you'll see both packages. Octopus will let you download 2.0.0 which will be a corrupt package of 0kb.

**Comment by tothegills** [comment]
Release Note: Remove missing NuGet packages from the built-in package repository on re-index
