### ISSUE TITLE
Cluster node management page

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1843]

**Comment by tothegills** [comment]
[ ] List of tasks per node
[ ] Ability to drain tasks from a node
[ ] Somewhere for load balancers to ping to check if the server is draining (remove from load balancer)
[ ] Should be able to remove a node from the cluster through API?

**Comment by tothegills** [comment]
Release note: Added configuration section for managing Octopus Server High Availability nodes
