### ISSUE TITLE
Promote buttons are available even if the user doesn't have permission

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1844]
On both the project Overview and the specific Release page, a user can be presented with a `Promote To` button for an environment they can't promote to.

Clicking the button gives a page with an empty error message.

### Permissions
![image](https://cloud.githubusercontent.com/assets/1887732/9078756/0b36e7a6-3b86-11e5-842f-dacb259b80e5.png)
Note: User also has the `Project viewer` role with no environment/project restrictions.

### Deploy Buttons
![image](https://cloud.githubusercontent.com/assets/1887732/9078747/ec04e112-3b85-11e5-9ca1-c3e172f6d035.png)
![image](https://cloud.githubusercontent.com/assets/1887732/9078814/8ccd59ee-3b86-11e5-91c4-1cbbd00d9309.png)

### Error Screen
![image](https://cloud.githubusercontent.com/assets/1887732/9078774/37966baa-3b86-11e5-8006-ef6b52e48887.png)

### Javascript Error
    TypeError: Cannot read property 'Links' of undefined
    at Octopus.Client.Repository.Releases.Octopus.Client.Util.extend.getDeploymentPreview (octopus.min.js:111)
    at octopus.min.js:115
    at Function._.map._.collect (octopus.min.js:76)
    at Scope.$scope.refreshPreview (octopus.min.js:115)
    at octopus.min.js:115
    at processQueue (octopus.min.js:19)
    at octopus.min.js:19
    at Scope.$get.Scope.$eval (octopus.min.js:19)
    at Scope.$get.Scope.$digest (octopus.min.js:19)
    at Scope.$get.Scope.$apply (octopus.min.js:19)```

**Comment by vanessalove** [comment]
Hey @damovisa duplicate: https://github.com/OctopusDeploy/Issues/issues/1519
