### ISSUE TITLE
Focus issue on variable set page

### ISSUE THREAD

**Issue by Jason-Black** [OctopusDeploy/Issues#1846]
When copying and pasting variables and their values from one set to another (using two browser windows), I noticed that the text box activation is inconsistent. Sometimes selecting the next blank 'Name' cell does not allow me to enter text until I have clicked elsewhere and then back. I haven't determined the exact pattern that causes the focus event to not fire yet. This is slowing down the process of migrating groups of variables from a project to a variable set.

Edit: If there is any content in the cell being selected, the focus event fires properly. This issue only occurs with empty cells, such as when adding new entries to the variable set.

**Comment by vanessalove** [comment]
We will be making some changes to variable management within the next few feature releases that should mean this issue isn't as annoying. It may still exist after, if so we will reopen at the time.
