### ISSUE TITLE
Octo.exe create-release --IgnoreExisting and --Deployto args don't work toghether

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1847]
If the release already exists, the `--ignoreexisting` argument keeps going (as expected), but it doesnt deploy the release to the environment set by `--deployto`.

Source http://help.octopusdeploy.com/discussions/problems/36970

**Comment by vanessalove** [comment]
There is a work around for this the customer was happy with by splitting up create-release and deploy-release and also splitting the vars. They were happy and closed the original issue.
