### ISSUE TITLE
Integrated Windows authentication improvements

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1848]
Two improvements to make: 

https://gist.github.com/PaulStovell/eb5b1d17a3c678660515

**Comment by bzbetty** [comment]
Any reason users still need to click the "sign in with microsoft windows domain account" if it's the only option?

**Comment by ebicbecker** [comment]
I second the question from @bzbetty .  If I have my octopus server configured for just AD, I still have two clicks before I am logged in.
