### ISSUE TITLE
Optionally exclude files from the App_Data folder for Azure WebApp deployments

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1852]
We've had several reports from people deploying WebApps having issues with the `App_Data` folder:
https://secure.helpscout.net/conversation/110235445/629/
http://community.octopusdeploy.com/t/azure-web-app-target-removes-app-data/358
http://community.octopusdeploy.com/t/deploying-webapps-with-webjobs/311/4
http://help.octopusdeploy.com/discussions/questions/5253-azure-web-app-multiple-packages

Some people will use `App_Data` to persist data, and by deleting App_Data they will be losing data.
Some people will use WebJobs which deployed into the `App_Data\jobs` folder - if a WebJob is running the deployment will fail due to file locks.

Visual Studio's Publish Web provides some common options including:
- Delete all existing files prior to publish
- Exclude files from the App_Data folder

![image](https://cloud.githubusercontent.com/assets/1627582/9101841/26866e60-3c2f-11e5-8745-2c491538fdaa.png)

Perhaps we should offer a similar set of common options and provide the right arguments when we invoke WebDeploy?

**Comment by markalanevans** [comment]
+1 Experiencing this.

**Comment by MarkWaldronOCHIT** [comment]
Nice to see you are working on this.

**Comment by mjrichardson** [comment]
I have added two new variables: `Octopus.Action.Azure.RemoveAdditionalFiles` and `Octopus.Action.Azure.PreserveAppData`.
These will be implemented in Calamari in the next release.  So anyone using 3.0.x will be able to set them.
The Azure Web App step in 3.1 will provide fields for them in the UI.

**Comment by mjrichardson** [comment]
Release Note: Provide 'Remove additional files' and 'Preserve App_Data' options when deploying Azure Web Apps.

**Comment by markalanevans** [comment]
Awesome!

We will look for the release and test it out.

Thanks so much Michael 

-Mark

**Comment by markalanevans** [comment]
@michaelnoonan Ive updated to the latest version, and i no longer get errors, but i'm not seeing my webjobs deployed.

However all that i have done is created the web jobs project and then in the main website project, i have added this line:

```
 "WebJobs": [
    {
      "filePath": "../ScheduledJobRandomRoaster/ScheduledJobRandomRoaster.csproj"
    }

  ]
```

To the webjobs-list.json file.

Is there any official docs on how to deploy webjobs via OctopusDeploy?

I might try this, but just wondering if there is an official way to deploy WebJobs that are separate projects that need to be deployed to the same Website?

**Comment by michaelnoonan** [comment]
Hi Mark,

What Octopus Deploy supports out of the box from 3.0 is the most common
scenario where people are deploying Web Sites with connected Web Jobs. In
this scenario the Web Site and connected Web Jobs are deployed at the same
time. From what I've understood so far you are trying to deploy your Web
Site(s) and Web Job(s) on independent cadences, which is something we don't
have out of the box support for (yet) because it gets complicated quite
quickly trying to cater for every scenario.

What I would suggest is for you to take a good read through the Azure
documentation on Web Jobs because Tom Dykstra sheds light on how Visual
Studio and the Azure Portal deploy your Web Jobs on your behalf, and you
could simply emulate that with Octopus using the Azure Web Site target (or
Step Type in Octopus 3.1).

https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-deploy-webjobs/
https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/

The key points to note are:
- The `webjobs-list.json` file is created by Visual Studio and (from what I
understand) used by the Visual Studio Publishing wizard, Octopus doesn't
interpret this file
- The Web Jobs should be deployed into the appropriate folder under
`App_Data` depdending on whether they are Continuous or Scheduled
- When deploying Scheduled Web Jobs, the Visual Studio Publishing Wizard
will create an Azure Scheduler Job to invoke the Web Job - you'd need to
emulate this

One recommendation I can make is to use the Visual Studio publishing wizard
to get your Web Site(s) and Web Job(s) deployed, configured and working,
and then use Octopus Deploy to automate the upgrade process for the Web
Site and Web Jobs by simply leveraging Web Deploy (which is the underlying
technology we use to implement the Azure Web Site support in Octopus).

Hope that helps!
Mike

**Comment by michaelnoonan** [comment]
I also just found there is some useful information from David Ebbo on Project Kudu which is the engine behind git deploys to Azure Web Apps and specifically deals with Web Jobs: https://github.com/projectkudu/kudu/wiki/Web-jobs

There's some interesting titbits I didn't know about like the `settings.job` JSON file, and how the actual Web Job execution runs, the working directory for the files, and even a graceful shutdown feature.

**Comment by michaelnoonan** [comment]
@MarkWaldronOCHIT @markalanevans I've updated our documentation with more details on deploying Web Apps and Web Jobs. I'd be interested in your feedback: http://docs.octopusdeploy.com/display/OD/Azure+Web+Apps

**Comment by markalanevans** [comment]
I'm going to read through this in detail when I get to work, but on our first attempt we are actually trying to do the exact scenario u say you built for. Website with connected web jobs deployed at the same time. Are there docs for that?

**Comment by michaelnoonan** [comment]
Hi @markalanevans. Yes, check out the new docs page and let me know how it goes. :)
