### ISSUE TITLE
Octopus.AzureContext.ps1 and azure_certificate.pfx should not be deployed to the Azure WebApp

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1856]
These temporary files whilst required for orchestrating the deployment to Azure should not be deployed to the Azure WebApp.

http://help.octopusdeploy.com/discussions/problems/36887-deploy-to-azure-website-target-also-deploys-tentacle-files

**Comment by zentron** [comment]
Fixed in Calamari: `3.0.1.416`
OD `3.0.14.2389`
Release Note: Temporary certificate generated for Azure script execution is removed and not pushed up to server
