### ISSUE TITLE
Migrator: Can't import deployments created in 1.6

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1858]
Deployments created in 1.6 will have a few fields that are null compared to deployments created in 2.0+. These fields cause the importer to skip the documents on the assumption they are orphans. 

Release Note: Migrator now supports importing deployments that originated in Octopus 1.6

**Comment by PaulStovell** [comment]
If you previously attempted the import, make sure to drop the database/delete the Octopus instance and go through the import process again, otherwise the deployments will be imported but you won't be able to view them because they'll link to the wrong items.

**Comment by michaelnoonan** [comment]
Release Note: Migrator now supports importing deployments that originated in Octopus 1.6
