### ISSUE TITLE
Calamari hashes all packages to determine if a previous package exists

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1859]
http://help.octopusdeploy.com/discussions/problems/36944

We tell Calamari to find previous versions of a package, when there are only 3, it takes a few seconds, when there are many it takes 9 minutes between starting to find them and finding them.

In the code, we go through all packages, calculate hashes on them, sort them by their semver, and *then* we take 5 of them. This could mean hashing hundreds and thousands of packages. 

https://github.com/OctopusDeploy/Calamari/blob/7b623b24e743683dcd0acd49884a330671cbb6a7/source/Calamari/Integration/FileSystem/PackageStore.cs#L109

We'll fix this to sort first, then hash only the 5 candidates we're interested in.

**Comment by zentron** [comment]
Release Note: Calamari updated to filter matching packages by version before generating hash from contents to increase performance.
