### ISSUE TITLE
Custom expression box dissapears after adding a variable in bindings window

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1861]
Once a custom expression is set with a variable and the binding is saved, the field disappears, forcing the user to reset the expression. Happens with all the fields in the binding window.

We should have this just like in 2.6

3.0
![binding3 0](https://cloud.githubusercontent.com/assets/6180562/9116902/3dbe82b2-3c3d-11e5-85b2-511e08d04c48.JPG)

2.6
![binding2 6](https://cloud.githubusercontent.com/assets/6180562/9116904/40f8197a-3c3d-11e5-9660-b287cf400bfc.JPG)

Octopus Version: 3.0.10

**Comment by zentron** [comment]
Release Note: Bound text field shows correctly if loaded value appears to be bound
