### ISSUE TITLE
XML transforms verbiage is incorrect

### ISSUE THREAD

**Issue by godefroi** [OctopusDeploy/Issues#1863]
Under the "Configuration transforms" feature, the verbiage under the textbox for XML transforms is incorrect:

> Octopus can run configuration transformation files. By default Octopus looks for *.Release.config and *..config.

I assume that Octopus actually looks for *.Debug.config and not *..config.

**Comment by zentron** [comment]
@godefroi you are right that there is a typo there, however it doesn't look for `*.Debug.config` but actually `*.<environment>.config` (in addition to `*.Release.config`) by default

**Comment by zentron** [comment]
Release Note: Help text escaped correctly describing transformation defaults
