### ISSUE TITLE
View release page shouldn't wait for packages

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1864]
If the NuGet feeds takes minutes to respond, the view release page doesn't display anything. Let's load these separately so that the rest of the page is useful.

Perhaps if the requests to get package information are taking a while, we can also re-submit the request.

**Comment by zentron** [comment]
Might separate loading the History events as well so that they can interact with the page while its loading

**Comment by octoreleasebot-staging** [comment]
Release note: Package feed details load independently of release details to make release page responsive sooner

**Comment by zentron** [comment]
@PaulStovell, I think separating these requests out a little are enough to make the page more responsive without dealing with timeouts or transient failures for just this specific case
