### ISSUE TITLE
Project Overview page usability issues on very large projects

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1865]
_We have one particular project that is large and is deployed into multiple environments, at different times (ie different versions). Thus we end up with a matrix on the Project Page that is 20 rows by 21 columns. The UI problem is that the horizontal scroll bar is hidden, unless you vertically scroll to the bottom of the page. This means that, in order to scroll right and left when at the top of the page, you have to drop to the bottom, scroll horizontally by some guessed distance (because the headers are hidden) and scroll back up. Then repeat, if your guess was wrong. As a workaround, I can zoom out with the mousewheel, scroll in X and Y directions, and zoom back in._

[Source](http://community.octopusdeploy.com/t/scroll-bars-on-very-large-project-page/442)

**Comment by PashCracken** [comment]
Additional reference information about our project to help you scale this correctly. Our project matrix is 35 columns(environments) and 38 rows(releases)

**Comment by DamianMac** [comment]
This will be addressed with the work we do for 3.3
