### ISSUE TITLE
Split Calamari Azure functionality into separate package

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1873]
Azure support (in particular the Azure PowerShell DLL's) add a significant amount of size to the Calamari package.
The worst part is, this extra luggage needs to be pushed to all Tentacles (and other target types), but is only ever used locally on the Octopus Deploy server (all Azure integration happens from the server in 3.0+).

To address this, Azure integration is being split into an Calamari.Azure package, which won't be pushed to remote targets.

**Comment by michaelnoonan** [comment]
Release Note: Reduced the size of Calamari by splitting the Azure functionality into a separate `Calamari.Azure` package
