### ISSUE TITLE
Issues using Azure deployment through Proxy

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1874]
After #1774 it looks as though the original user who brought this bug to our attention is still having problems.

>Hi Paul
I’ve now testet Azure-deploy using proxy and it doesn’t seem to work.
I’ve upgraded Octoups to 3.0.9 today with no luck as well
I then have to turn back to NAT in our firewall again
Med venlig hilsen

Source: http://help.octopusdeploy.com/discussions/problems/36299

**Comment by michaelnoonan** [comment]
We have tried to reproduce this several times without success. We have however fixed several small issues related to configuring Proxy credentials in Octopus Server and Tentacle (which both propagate credentials for Calamari to use depending on where Calamari is running). It would be worth testing again with Octopus 3.2.3.

Firstly you'll need to reconfigure the Proxy configuration for Octopus Server.

Relates to OctopusDeploy/Issues#1774 and OctopusDeploy/Issues#2130

https://octopus.com/company/roadmap/why-was-this-closed
