### ISSUE TITLE
Square Brackets in Step Name break Output variables

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1882]
This seems to only break when the square brackets are in the middle of the step name:

- [Step Name] . Works ok
- [Step] Name . Does not work

Octopus Version: 3.0.12

**Comment by michaelnoonan** [comment]
Release Note: Prevent saving Steps with `[` or `]` in the name which would otherwise cause Output Variables to stop working for that Step.

**Comment by ErikxNilsson** [comment]
After the 3.2.3 release, if you have two steps with brackets in them, it is impossible to fix either of the steps as octopus validates both step names when you click save, even the one you are not currently editing.

The only way to get around this now is to delete all but one step with brackets in the name and edit that. Could you please hotfix this as we can not edit the process in any of our ~30 projects right now.

**Comment by ErikxNilsson** [comment]
An update:
I managed to fix one project deployment setting directly in the database, so its just a question of the validation in the GUI being overly restrictive.

**Comment by michaelnoonan** [comment]
Hi @ErikxNilsson, you're right, that's less than desirable. I'm glad your found a workaround in the meantime. I'll investigate a more permissive solution that will:
1. Prevent you from creating new Steps with `[` or `]` in the names.
2. Allow you to save existing Steps with a warning about the consequences.

That's made difficult since we actually save the entire process as a single document - meaning it will need to be more of a client-side validation which doesn't make me super excited.

Since you've gone through the process do you have other ideas?

**Comment by ErikxNilsson** [comment]
Ah, I was suspecting that was the reason.
 
I suppose one way could be to add a "danger there be dragons here!!!!"-advanced view (somewhere in the admin part of the GUI) in where you could edit the json document directly?

You could also add a param when you post the save request which step is currently being edited, and only perform name validation on that when saving, though this feels more like a hack-y workaround for this specific issue.

**Comment by michaelnoonan** [comment]
@ErikxNilsson I've done a bunch of investigating this issue, and I've updated #2166 with our thoughts. I think if we fix the fundamental problem we should keep the stricter validation in place. In the meantime if people run into the same issue we will help them manually fix the deployment process.

I think in the end it will be really nice to be able to PATCH the deployment process for a number of reasons.

Thanks for working with me on this one.

**Comment by ErikxNilsson** [comment]
For you who end up here with the same problem, the Octopus team have decided not to fix this. To fix this error, you must edit the SQL database directly. Below is the way I fixed my server:
Obviously, you should take a backup of your database first.

The way to do this is to open the table "DeploymentProcess" in your Octopus database, and edit each row with an ID like so: 'deploymentprocess-Projects-11'.I think you can ignore the snapshots and the ones that end in a bunch of random letters after the number (11 in this case).

Anyways, edit the row, and find the name of your step in the JSON field. Simply remove the brackets (or replace them with something valid, I used parenthesis), and you should be able to edit your project again. For me it showed the new name instantly on the web portal. 

Also, if you have a step that references an earlier step, the reference is by name, and will also have to be changed to the same name as what you changed that step to, but this you can do from the web interface as it is not part of the overall validation when saving the process.
