### ISSUE TITLE
Delete key in Filter text boxes can delete rows in table

### ISSUE THREAD

**Issue by gregjhogan** [OctopusDeploy/Issues#1883]
For example, if I open a variable set (Library -> Variable Sets -> (select a variable set)) then click the filter icon and type in a variable name filter, change the value of one of the displayed variables, then click back into the variable name filter and hit the delete key, it deletes the variable that I just edited.  It seems like the row doesn't properly lose focus when you click into one of the filter input fields.

Web browser: Chrome 44.0.2403.130 on OSX
Octopus Server: 2.65.1010

**Comment by Dalmirog** [comment]
Another source: http://help.octopusdeploy.com/discussions/problems/39008

**Comment by robpearson** [comment]
Release Note: Variable editor doesn't delete rows if the delete key is pressed while filtering.
