### ISSUE TITLE
Automate Tentacle upgrades and move to 4.5

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1884]
So far we haven't changed Tentacles since 3.0 shipped, so there hasn't been a reason to automate Tentacle upgrades. 

If we want to upgrade Tentacles to .NET 4.5, that does mean a Tentacle change, so we'd need to automate their upgrade. 

To do this, we need to:

- [x] Upgrade Halibut to 4.5, and enable speaking TLS 1.0, 1.1 and 1.2
- [x] Bring back the old Tentacle upgrade UI
- [x] Add a task controller which pushes the new Tentacle and orchestrates the upgrade from Octopus server side
- [x] Package the Tentacle MSI as part of our build into Octopus MSI
- [x] Tell Tentacle to install the MSI
- [x] Wait some time, then poll until we get a successful acknowledgement with the new version number, or give up if say 30 minutes goes by and the server never comes back
- [x] Figure out a decent way to test it all locally

For step 5, we might be able to take some inspiration from Hydra. Hydra uses a scheduled task, so I'm not sure we need that, but we do however need some way to kick off a process that will:

- [x]  Wait while Tentacle finishes the current step
- [x]  Gracefully shut down running Tentacle instances
- [x]  Install the new MSI
- [x]  Start Tentacle instances

Keeping in mind:

 - A single machine may have multiple Tentacle instances running, all of which need to be updated together since they use the same MSI-installed executable
 - The upgrader may end up running in parallel on each machine, since users may have the same machine in the same environments

**Comment by michaelnoonan** [comment]
Release Note: Tentacle Upgrades are now automated
