### ISSUE TITLE
Step template default value doesn't like non-alpha numeric characters

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1885]
When making a dropdown in a step template, the "Default Value" does not show in the project/Process/Step/ view unless the default value and the values in the dropdown both only contain alpha/numeric characters (no dashes, underscore, spaces, etc). This is problematic for values that require spaces or otherwise parsed values.

See http://help.octopusdeploy.com/discussions/problems/37493

**Comment by alfhenrik** [comment]
Closed as part of https://github.com/OctopusDeploy/Issues/issues/2095
