### ISSUE TITLE
Release notes display on Release page is unformatted

### ISSUE THREAD

**Issue by godefroi** [OctopusDeploy/Issues#1886]
Plain text release notes are jumbled (line breaks removed, whitespace collapsed) on the Release page (/projects/foo/releases/releasever). They should probably be in a block with white-space: pre or white-space: pre-wrap.

If some people use HTML release notes, then some simple detection mechanism might be in order.

**Comment by vanessalove** [comment]
Our release notes are markup. We sanitize a lot of HTML and this can stop some HTML from showing correctly (especially if it is badly formatted). This is not something we will change.
