### ISSUE TITLE
"Deployment Complete with Warnings" icon is not very obvious

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1888]
With the 3.0 release, the icon for a deployment that completed with warnings or errors has changed to a green checkmark with a small exclamation point. We recently had a failed deployment with this icon and it took us a little while to realize that it had failed because of the misleading icon.

See http://help.octopusdeploy.com/discussions/problems/37435

**Comment by vanessalove** [comment]
Please reconsider this. Further comments about 'hard to distinguish' deployments with warnings from successful deployments.  Marked for triage for group discussion.

**Comment by PaulStovell** [comment]
Discussed this. Decision is:

 - A project setting on how to treat warnings in the dashboard: "Yellow" or "Green"
 - Ability to suppress a specific warning by defining rules like "if it matches this pattern, ignore the warning"

**Comment by vanessalove** [comment]
Information relayed to customer:

```I am about to use more words than necessary so the tl;r; is we will do something about this, but probably not until 3.4 or 3.5.

When it was changed to the green icon with the warning, we had a decrease in support requests. The reason being that customers were more interested in how to suppress warnings and have a green dashboard than actually getting rid of warnings or they had warnings they couldn't get rid of. But now we also agree that if you don't usually have warnings you want to know right away.

So our solution is going to be:

add a project variable for 'keep my warnings green' or 'no i want yellow warnings' for icons
for each warning in your logs, you have the ability to 'mark as ignore this warning' so you could suppress warnings from external tools that you cannot control but you know the deployment is fine. It also means if you get a new warning it will go yellow again
so based on both of those, it makes it a large extension and not something we can update quickly.```

**Comment by vanessalove** [comment]
related: https://github.com/OctopusDeploy/Issues/issues/2380

**Comment by PaulStovell** [comment]
Going to close this - #2380 will cover it
