### ISSUE TITLE
Create `Octopus.Release.CurrentForEnvironment` variables

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1891]
You are deploying release `1.8.6` to `Prod`.  You previously deployed the same release to `Prod` (ie. `1.8.6` is currently deployed to `Prod`).  
`Octopus.Release.PreviousForEnvironment.Number` is currently being set to `1.8.5`.
`Octopus.Release.CurrentForEnvironment.Number` would be set to `1.8.6`.

See http://help.octopusdeploy.com/discussions/problems/37321-issue-with-system-variables-octopus-deploy-3

**Comment by PaulStovell** [comment]
I'm not convinced this is worth solving, there are other ways to solve the kinds of problems that this variable might help to solve, and calculating it is hard. I'd vote to wont-fix.

**Comment by zentron** [comment]
Release Note: Include `Octopus.Release.CurrentForEnvironment` to deployment variables based on the release of the already provided `Octopus.Deployment.PreviousSuccessful`
