### ISSUE TITLE
Add Octopus Server variable to ignore configuration variable replacement errors

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#1897]
Need to add a new variable to ignore NuGet package step configuration variable replacement errors.  This is needed because warnings are now treated as errors and some customers have non-xml config files in their packages.  

Source:
http://help.octopusdeploy.com/discussions/problems/37176-replace-settings-in-some-config-files-with-variables-defined-in-octopus
http://help.octopusdeploy.com/discussions/problems/37369-config-transformation-ignore-error-variable-not-working

**Comment by tothegills** [comment]
Release note: Added the variable Octopus.Action.Package.IgnoreVariableReplacementErrors to treat variable replacement errors as warnings

**Comment by hammett** [comment]
Hi all,
I actually would prefer not the globally disable errors as they may be legitimate. Is there a PS script we can use as part of calamari to transform/process only a fixed list of config files?

Thanks

**Comment by storos** [comment]
Hello, i got same problem and in my project variables i put   key is Octopus.Action.Package.IgnoreVariableReplacementErrors
and value is true
but it gives same error, should i do different ?

**Comment by benjoyce** [comment]
Hey, if it helps, I had this issue and checked all my files for additional chars at the start of the file and saw nothing.  Tried the IgnoreVariableReplacementErrors flag - no joy.  Same error.  Fixed it by marking all the config transform files in the solution with "Build Action" as "Content".  Worked after that.
