### ISSUE TITLE
UI Issue for tasks list in Octo 3.0.13

### ISSUE THREAD

**Issue by bigbam505** [OctopusDeploy/Issues#1898]
It looks like the z index might be off for the task type select box, did not see for the others but this is a fresh install so I have no data really.

![Z-Index is off](https://dl.dropbox.com/s/zpczo4nxmalsqlz/Tasks_-_Octopus_Deploy_2015-08-13_16-21-59.jpg?dl=0)
(its hard to see but the task view cuts off the select box when there is at least one task and the selector is longer than the task list)

Not a major issue as you can still scroll it in view to select options but just wanted to bring it to someones attention

**Comment by robpearson** [comment]
Release Note: Task type filter is not cut off by other page elements.
