### ISSUE TITLE
Option to disable delta compression

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1900]
See http://help.octopusdeploy.com/discussions/problems/37485-uploading-using-delta-fails-every-time

**Comment by tothegills** [comment]
Consider variable to turn off delta computations

**Comment by PaulStovell** [comment]
For reasons we can't seem to figure out, for a small group of people delta compression doesn't always work. Let's make a special variable that users can set to disable delta compression.

**Comment by tothegills** [comment]
Release note: Added the variable `Octopus.Acquire.DeltaCompressionEnabled` to toggle delta compression when sending packages

**Comment by Dalmirog** [comment]
User to notify when released: http://help.octopusdeploy.com/discussions/problems/38500

**Comment by tothegills** [comment]
Have let Mike know.

**Comment by tothegills** [comment]
Create the variable `Octopus.Acquire.DeltaCompressionEnabled` in a project and set the value to `false` to turn off delta compression
