### ISSUE TITLE
Upgrade to TLS 1.2

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1902]
Octopus was built on .NET 4.0, which only allowed up to TLS 1.0 support. 

We're moving to .NET 4.5, which means we can now speak TLS 1.2. 

When establishing a connection, Octopus and Tentacle will negotiate for the best protocol out of: 

 - TLS 1.0
 - TLS 1.1
 - TLS 1.2

We still specify TLS 1.0 so that new versions of Octopus can talk to old Tentacles that are still running TLS 1.0. 

You can however tell Windows to disable TLS 1.0 or 1.1 (or any other protocol) by configuring SChannel, which overrides the settings Octopus/Tentacle use. Here's a free tool to configure it: 

https://www.nartac.com/Products/IISCrypto

![2015-08-14 11_57_19-iis crypto - 1 6 build 7](https://cloud.githubusercontent.com/assets/47085/9265817/da9579ee-427b-11e5-8c59-69320c74ce09.png)

So if you want to be TLS 1.2 only, the process would be:

 - Upgrade Octopus
 - Upgrade Tentacles
 - Use that tool/modify the registry to disable TLS 1.0 and 1.1

**Comment by michaelnoonan** [comment]
Release Note: Octopus Server and Tentacle now support TLS 1.2 which requires .NET 4.5
