### ISSUE TITLE
Changing a project's lifecycle but then cancelling the change, doesn't cancel it

### ISSUE THREAD

**Issue by richiej84** [OctopusDeploy/Issues#1903]
- Go to a project's Process page
- Click *Choose a different lifecycle*
- In the popup, select a different lifecycle
- Click Cancel rather than Apply

The lifecycle still changes to the one selected, even though it wasn't applied.

**Comment by mjrichardson** [comment]
Release note:Cancelling the lifecycle-select dialog no longer persists changes.
