### ISSUE TITLE
Tooltip release notes when hovering over item on Dashboard or Project Overview pages

### ISSUE THREAD

**Issue by richiej84** [OctopusDeploy/Issues#1904]
When hovering over an item in either the Dashboard of a Project Overview page, it would be really nice to see a summary of what changes were in the release - this would probably just be the release notes.

**Comment by vanessalove** [comment]
Feel free to add to UserVoice (https://octopusdeploy.uservoice.com/) when you have suggestions about changes to features in Octopus.
