### ISSUE TITLE
ASP.NET 5 Strategy

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1905]
A user reported some issues (which he managed to workaround) while packing and deploying an ASP.NET 5 webapp to Azure using Octopack and Octopus. It might be worth reviewing our strategy for these kind of deployments.

The user provided very useful data:
http://help.octopusdeploy.com/discussions/questions/5333

**Comment by PaulStovell** [comment]
We'll address this next year closer to vNext being released

**Comment by StrangeWill** [comment]
@PaulStovell Roadmap is to see ASP.NET 5 ready for 1.0 in Q1 and we're almost at the end of January, when can we expect to hear from Octopus on this?

https://github.com/aspnet/Home/wiki/Roadmap
