### ISSUE TITLE
Investigate using FileShare.Read when opening packages

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1907]
Currently we open packages without specifying the `FileShare` mode. The default is none which means that if another process (i.e. anti-virus scanner) has already opened the file the call to `Package.Open` will fail. We have had reports of deployments failing because of this, specifically in `Tentacle.Commands.ExtractCommand`.

If instead we did `using (var package = Package.Open(packageFile, FileMode.Open, FileAccess.Read, FileShare.Read))` the call might succeed despite AV software.

**Comment by Damovisa** [comment]
See https://secure.helpscout.net/conversation/111327562/752/ for example report

**Comment by alfhenrik** [comment]
Release note: Open packages with FileShare.Read to reduce conflicts between anti-virus scanner and Tentacle
