### ISSUE TITLE
Azure feature to allow for virtual directories with 3.1 changes

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1914]
As discussed with Michael adding virtual directory support would be a great small addition to the Azure 3.1 changes to get more customers off the web deploy template.

Source: http://help.octopusdeploy.com/discussions/questions/4981

**Comment by mjrichardson** [comment]
Release note: Allow setting physical path when deploying Azure Web Apps.

**Comment by lance-h** [comment]
I don't believe this feature allows for deploying to virtual directories which are not a child of wwwroot. For example, my virtual directory is physically a sibling of wwwroot, but visibly a child.

E.g. in Azure the virtual directory name is "virtual", physically located at D:\home\sites\virtual
