### ISSUE TITLE
Health Check fails when Drive has <= 1 KB free space

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1916]
If a drive has <= 1KB free space the health check fails

![image](https://cloud.githubusercontent.com/assets/1830666/9302668/beedeabc-451b-11e5-901c-37b5243a0eb6.png)

![image](https://cloud.githubusercontent.com/assets/1830666/9302659/af147eee-451b-11e5-8cb7-1ca890ba9884.png)

**Comment by zentron** [comment]
Release Note: Allow health check to return drive information where free space < 1KB

**Comment by michaelnoonan** [comment]
Also here http://community.octopusdeploy.com/t/health-check-fails-when-a-drive-is-full/465
