### ISSUE TITLE
Octopack support for projects targeting .NET 4.6

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1918]
Octopack doesn't support projects targeting .NET 4.6 but this will start to become more common since the release of .NET 4.6 and Visual Studio 2015. It would be good to have support for .NET 4.6 out of the box.

Source: https://secure.helpscout.net/conversation/113021096/909/

**Comment by cannehag** [comment]
Any status on this issue?

**Comment by michaelnoonan** [comment]
I'm going to close this for now. The original reporter found a simple workaround:
> I got this fixed and working locally. Just had to change the framework in the project properties. It works after that.

https://octopus.com/company/roadmap/why-was-this-closed
