### ISSUE TITLE
Tentacle DeregisterMachineCommand doesn't work in 3.0

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1920]
The Tentacle DeregisterMachineCommand relied on SQUID to uniquely identify the Tentacle but SQUID is not supported in 3.0. We need to find another way to identify the Tentacle so it can be deregistered correctly.

There is no simple work around available.

Source: http://help.octopusdeploy.com/discussions/problems/37767-the-tentacle-matches-more-than-one-machine-on-the-server

**Comment by PaulStovell** [comment]
It should now be based on the subscription (URI for polling Tentacles). For listening Tentacles I don't think we can do much.

**Comment by michaelnoonan** [comment]
Aren't the Tentacle Certificate Thumbprint's unique per-instance? What if we added a first-class query for `GetMachineByThumbprint()` and used that?

**Comment by tothegills** [comment]
Release note: Re-implemented Tentacle deregister-from command.
