### ISSUE TITLE
Error during PowerShell script leaves Tentacle hanging

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1929]
A PowerShell script executing SQL which caused an error, resulted in the Tentacle hanging.  The Tentacle service is then unable to restart, as a process is still holding the port.

As reported in http://help.octopusdeploy.com/discussions/problems/37847-tentacle-hanging-and-then-cannot-restart

**Comment by zentron** [comment]
Update from User

> re: the SQL, this was really a red herring. the SQL script simply ran much longer than expected and I had assuming it was hanging.
> believing that it had hung, I got onto the server and stopped the tentacle, after which it would not restart properly due to the port still being in use.
