### ISSUE TITLE
Autocomplete doesnt work with user with Cyrillic characters

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1934]
Octopus version: 3.0.18

**AD user setup**

![ad_account](https://cloud.githubusercontent.com/assets/6180562/9430563/6282a8e8-49d1-11e5-9317-b544cc2de5d0.JPG)
![ad_general](https://cloud.githubusercontent.com/assets/6180562/9430564/66461546-49d1-11e5-9cf7-7e6d3968df65.JPG)

**Trying to find the user in Octopus**

![od_allusers](https://cloud.githubusercontent.com/assets/6180562/9430589/2625e242-49d2-11e5-94c9-a7a7485de191.JPG)

![od_autocomplete](https://cloud.githubusercontent.com/assets/6180562/9430595/426e538a-49d2-11e5-8be4-e86ca129c9b4.JPG)

source: http://help.octopusdeploy.com/discussions/problems/37785

**Comment by zentron** [comment]
Release Note: User auto complete uses `Username` _or_ `Displayname` during search. Search now also uses Unicode character folding.
