### ISSUE TITLE
Relax license enforcement

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1937]
Say a customer has a license key that entitles them to:

 - 20 projects
 - 20 machines
 - 20 user

And their current Octopus server has:

 - 1 project
 - 20 machines
 - 4 users

At the moment when they add their 21st machine, they'll be prevented from deploying (they can still use the app, they just can't create releases or deploy them). Even though they have plenty of capacity left in the other dimensions. 

Instead, we're going to make license enforcement more relaxed: 

Since they are allowed 20/20/20 of each item, let's consider them as being allowed to have up to 60 "things" in total. When deciding whether they are within the limit, let's add everything together. So this would be a valid combination: 

 - 30 projects
 - 29 machines
 - 1 user (60 things in total)

In addition, when they get to within 5 "things" remaining (e.g., 55 "things" in this case) a warning will appear that they may soon go beyond their license limits. 

(Some grandfathered license keys have "unlimited" in some settings, e.g., 20 projects, 20 machines, but unlimited users. In that case, treat any unlimited portions as the MAX() of all limited values).

**Comment by vanessalove** [comment]
There are shuffled license limits .. need to be accounted for also - such as:

<License Signature="qG8+K1PB2nkysvjEWeCnuu3EgqJvRpHrKVjTmgZ6Pdjvskx6DmZh9BWScrtOYZ/30PUackQVtxfuu6faLq0ftw==">
  <LicensedTo>Aditro</LicensedTo>
  <LicenseKey>56545-13543-18427-21477</LicenseKey>
  <Version>2.0</Version>
  <ValidFrom>2015-04-28</ValidFrom>
  <MaintenanceExpires>2016-04-28</MaintenanceExpires>
  <ProjectLimit>30</ProjectLimit>
  <MachineLimit>30</MachineLimit>
  <UserLimit>120</UserLimit>
</License>

Their total is still only 180 for Team.

**Comment by CRuppert** [comment]
Can you guys please document this WAY more clearly on the main site? Getting Purchasing to come to  github to read a ticket is awful. Similarly, it's not clear at all that this is the way things works. Including Users in the "things" count is... to be honest, really, really, crappy.
