### ISSUE TITLE
Substitute variables #{each} loop doesn't work with nested variables

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1939]
Octopus Version: 3.0.19

Substitute variables #{each} loop doesn't work with nested variables

Variables:

| Name | Value|
| ------------- | ----------- |
| MyVariable[1]      | #{phrase} 1|
| MyVariable[2] | #{phrase} 2|
| phrase | This is variable: |

Web.config
```
	#{each variable in MyVariable}
	<Node ="#{variable}"/>
	#{/each}
```
Final result on Web.config
```
<Node ="#{phrase} 1"/>
<Node ="#{phrase} 2"/>
```

Expected
```
<Node ="This is variable: 1"/>
<Node ="This is variable: 2"/>
```

Source: https://secure.helpscout.net/conversation/113158873/926/

**Comment by michaelnoonan** [comment]
Fixed by OctopusDeploy/Issues#2060
