### ISSUE TITLE
Create 2.6 build with increased timeout for RavenDB index

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1944]
I'm creating this ticket by @PaulStovell 's request. The goal would be to create a 2.6 build that has an increased timeout for the RavenDB indexing (current I believe is 20min) for the users that are having issues importing from [prior 2.6] to [2.6] to then jump to [3.0]

source: https://secure.helpscout.net/conversation/112847737/895/

**Comment by vanessalove** [comment]
another customer now having this issue with their 2.6 server

new source: https://secure.helpscout.net/conversation/114804416/1088/

**Comment by PaulStovell** [comment]
Special builds here: 

32-bit: https://download.octopusdeploy.com/octopus/Octopus.2.6.5.2503.msi
64-bit: https://download.octopusdeploy.com/octopus/Octopus.2.6.5.2503-x64.msi
