### ISSUE TITLE
Calamari - Ignore config transform errors

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1946]
This ticket has an example XML file:

http://help.octopusdeploy.com/discussions/problems/38070

The error is valid I believe, but our variable to treat errors as warnings doesn't seem to work to let the customer suppress it.

**Comment by tothegills** [comment]
Release note: Configuration transform errors are treated as warnings when Octopus.Action.Package.IgnoreConfigTransformationErrors is set to true
