### ISSUE TITLE
When updating a Step Template - update across all Projects

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1947]
I want to use template-all model, where all projects consists only of step templates, to provide central management of deployment process. But when i modify step template, I need to manually go into every project and into step and click "update".

I think it would be better to use TeamCity model, where template can only be inherited and not changed inside project, or cloned from template if changes needed. Or provide the ability to one-click update all steps that uses the template (even better ask for it after click on Save button).

I'm going to end up with 30+ projects, all using the exact same setup consisting entirely of imported Step Templates. A "Project Template" feature would be hugely helpful; failing that, I need some way of auto-refreshing all imported steps.

uservoice suggestion: http://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6072178-when-updating-a-step-template-update-across-all

**Comment by vanessalove** [comment]
putting a hold on this - its available via octopygmy - so I will add a comment to the UV and see if its enough (as its chrome only, should we be concerned about those not able to use chrome?)

**Comment by clain23** [comment]
X-posting here too:

It is not available via octopygmy - plugin description says it is only planned.

**Comment by vanessalove** [comment]
@clain23 It's in dev: https://twitter.com/davidroberts63/status/638408138689875968

**Comment by clain23** [comment]
Plugin works fine, but I am still think it must be a part of the product.

**Comment by michaelnoonan** [comment]
I'm going to close this for now. The suggestion is already logged in UserVoice and we will get to it at some point. We are also considering better support for version controlling Step Templates/Script Modules etc that may make this feature less useful.

https://octopus.com/company/roadmap/why-was-this-closed
