### ISSUE TITLE
Migrator fails if previously-used library variable set has been deleted

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1948]
Issue reported here: https://secure.helpscout.net/conversation/111841581/809/

**Comment by Damovisa** [comment]
The error isn't causing a crash, however it's not writing out the snapshot variable file because the parent is missing.

**Comment by tothegills** [comment]
I don't think this is a bug. If you try to view variables for a release that refers to a missing library variable set you can't because the library variable set is missing.  I think the migrator is correctly not exporting variable snapshots whose parent is a missing library variable set.
