### ISSUE TITLE
Multiple concurrent Tentacles accessing the same semaphore occasionally throw exception

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1952]
User with multiple Tentacles running on the same server reports occastionally seeing
> System.UnauthorizedAccessException: Access to the port is denied.
when the retention policy runs.

Considering we don't explicitly set any `SemaphoreSecurity` settings to deny access it seems unlikely that these settings are relevant.

Reading [MSDN Article](https://msdn.microsoft.com/en-us/library/system.threading.semaphore%28v=vs.80%29.aspx?f=255&MSPPError=-2147217396) indicates the problem may be due to a missing Kernal Object Namespace prefix assigned to the name of the semaphore. The `Global\` prefix should be assigned to all the Seamaphore usages to try avoid this exception

Source: http://help.octopusdeploy.com/discussions/problems/38113

**Comment by zentron** [comment]
Release Note: Calamari semaphores should now be more globally accessible by prepending the `Global\` name prefix

**Comment by rendicott** [comment]
This is still an issue for us running 3.3.1
