### ISSUE TITLE
Windows Service password can be seen in clear text on the deployment log

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1955]
Original post: If a user creates an offline package to deploy a windows service with a custom user and password, the password is stored in clear text in the variables file.

Edit: The password can be seen in the deployment log in clear text and not just in offline packages.
```
[Octopus.Action[deploy].WindowsService.CustomAccountPassword] = 'MichaelRocks123'
```

Octopus version: 3.0.20

**Comment by vanessalove** [comment]
@Dalmirog where is the source for this? was it from a ticket?

**Comment by Dalmirog** [comment]
Source: https://secure.helpscout.net/conversation/115602688/1159/

@vanessalove

**Comment by michaelnoonan** [comment]
Release Note: Windows Service and IIS App Pool Custom Account Passwords are now treated correctly as Sensitive values by default.
