### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1957]
As per: https://octopusdeploy.com/blog/rfc-branching

 - [ ] Under project settings, create a page to define branches as per the RFC
 - [ ] On create release page, add a drop down to choose the branch, and filter packages accordingly
 - [ ] For project variables, add the ability to scope by branch
 - [ ] For project steps, add the ability to restrict the step by branches
 - [ ] On branch settings page, add a checkbox to control whether the branches are individual rows in the dashboard or not
 - [ ] On the release list page, add a drop down to filter by branches

**Comment by tothegills** [comment]
Should be able to scope lifecycles to a branch? Have a default lifecycle and optionally lifecycles for each branch.

**Comment by mjrichardson** [comment]
I think that makes sense. I've added a task to the Trello board.

**Comment by mjrichardson** [comment]
release note:Channels feature.
'Channels' is the name we've given to the set of features discussed in our [branching RFC](https://octopusdeploy.com/blog/rfc-branching).
See our [Release 3.2 blog post](https://octopus.com/blog/octopus-deploy-3.2) for more information.
