### ISSUE TITLE
Calamari does not exit when powershell script returns

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1959]
If you spawn processes from within a Powershell script, Calamari will wait until those processes have finished even though the Powershell script returns.

**Comment by tothegills** [comment]
Example:
```
Write-Host "Running Script..."

$exePath = "C:\Temp\main.bat"

$processs = Start-Process $exePath -PassThru -NoNewWindow
Exit 0
```
main.bat
```
@echo OFF
START ping -t localhost
START ping -t google.com
ECHO Batch file is done!
EXIT /B 0
```

**Comment by tothegills** [comment]
https://secure.helpscout.net/conversation/115305474/1133/

**Comment by PaulStovell** [comment]
This is because `-NoNewWindow` is passed. `ping` is a console app - if it can't create a new window, where would the output go? So for console apps `-NoNewWindow` assumes it needs to wait for the process to exit. Removing that flag makes PowerShell return immediately.

**Comment by phoewass** [comment]
Actually, in some cases, we do not have control over the underlying deployment process, puppet for example. Furthermore, Calamari should have the same behavior as running the script manually.
