### ISSUE TITLE
Some Calamari Delete/Copy operations appear to be failing silently

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1960]
When using a Custom Installation Directory and Purging it as part of the deployment, the deployment appears to succeed but the files are not actually deployed. Loading the Verbose logs reveals:
1. The Purge operation succeeded immediately
2. The copy operation retried each file for 1 minute before moving on to the next file, but the files weren't actually copied, and there is no log of any error.

The log file attached to the source help ticket is the best source for information.

Source: http://help.octopusdeploy.com/discussions/problems/38341-octopus-deploy-not-deploying-files

Most likely candidate is http://blogs.msdn.com/b/dotnet/archive/2015/07/28/ryujit-bug-advisory-in-the-net-framework-4-6.aspx

One consideration would be to disable RyuJIT: https://github.com/Microsoft/dotnet/blob/master/docs/testing-with-ryujit.md#disable-ryujit

Alternatively we could `[MethodImplAttribute(MethodImplOptions.NoOptimization)]` the offending methods.

Otherwise we need our Customers to update .NET 4.6 to mitigate this issue.

**Comment by michaelnoonan** [comment]
Another source: https://secure.helpscout.net/conversation/113958495/1018/

**Comment by michaelnoonan** [comment]
Another source: http://help.octopusdeploy.com/discussions/problems/37931-problem-deploying-contents-of-nuget-package-after-upgrade

**Comment by mjrichardson** [comment]
I have done the following:
- Corrected retry logic so exception eventually gets thrown.
- Improved logging when retrying (so exception message is included).
- Attempt to ensure deletion of directory occurs before we proceed to re-create the directory.

**Comment by mjrichardson** [comment]
release note:  Improved handling for missing `bin` directory issue when copying to custom installation directory.
