### ISSUE TITLE
Teams can't be deleted if they were ever set as auth for manual steps

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1961]
If a team was set as auth for a manual intervention step, then the team can no longer be deleted even if:

- the manual intervention step is no longer part of the (current) deployment process.
- the release where the intervention step was used was deleted.
- the release where the step was used has been deployed through all the phases of the lifecycle.

Octopus version: 3.0.20
Source (for 2.5): http://help.octopusdeploy.com/discussions/questions/5492

**Comment by alfhenrik** [comment]
Release note: Team can now be deleted if they once was responsible for a manual step but they are no longer responsible
