### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1963]

**Comment by jrote1** [comment]
Is there any idea when this will be started?

**Comment by alfhenrik** [comment]
This is the next feature on our list and it will be released in 3.3

**Comment by zentron** [comment]
The first early access release of `3.4` which includes some progress on multi tenancy has been made available
https://octopus.com/blog/octopus-deploy-3.4-eap
http://docs.octopusdeploy.com/display/ODEAP/What+is+the+EAP

Following on from our and [RFC](https://octopus.com/blog/rfc-multitenancy-take-two) this release contains the ability to add tag sets with tags, and tenants. Tags provide a easy way to group together tenants in a manner that suits you, for use in various parts of the system.

For users interested in the progress of the multi tenancy feature we would advise downloading and trying out the `3.4.0-alpha001` build we have made available so get an idea of what direction it is headed. 

The earlier we hear feedback the easier (and more likely) it will be that we will be able to incorporate it into the design.

#### Configuring Tenants ####
![image](https://cloud.githubusercontent.com/assets/1830666/14006122/b8637dfa-f1b5-11e5-9b43-e141e39277de.png)


#### Configuring Tag Sets####
![image](https://cloud.githubusercontent.com/assets/1830666/14006125/be1a39e6-f1b5-11e5-8e5b-ebffd5c19a64.png)

**Comment by alfhenrik** [comment]
### EAP build 2
_This feature will be included in version `3.4.0-alpha0002`_

#### Adding variable templates to a project
![projectvariabletemplates_endtoend](https://cloud.githubusercontent.com/assets/1035315/14010464/1d7d9b78-f1e1-11e5-81c0-bb5ec723b9ed.gif)

**Comment by robpearson** [comment]
Tenant - Project Variables WIP ... nearing completion.

![screencapture-localhost-9005-octopus-dev-html-1460281577266](https://cloud.githubusercontent.com/assets/216245/14414274/d454d262-ffd3-11e5-831b-9ca4c3909fac.png)

**Comment by zentron** [comment]
## Updated Deployment Screen ##
![deploy](https://cloud.githubusercontent.com/assets/1830666/14844615/f408f582-0c9b-11e6-9dc5-d85df6f1e7cc.gif)
To allow for selecting multiple tenants during deployment, this screen has been changed to allow the user to deploy to specific tenants, or to all tenants with specific tags. In both of these cases tenant deployments will only take place if that tenant is configured with an environment mapping for that project.

**Comment by jrote1** [comment]
Will it be possible to run steps when a client is added/removed?

**Comment by zentron** [comment]
Hi @jrote1, if you mean will you be able to perform a deployment of an existing release when a new tenant is added, then the answer is yes. You will be able to link (and unlink) projects to tenants at any time and the releases can be deployed based on the available tenants _at the time of deployment_ as opposed to some snapshot from when the release took place. 

We are pleased to say that we expect to have a beta release of `3.4` out in the next few days! I will update this issue when that occurs so that you can be notified as soon as it is available.

**Comment by jrote1** [comment]
@zentron thanks for your reply. I was more wondering if there can be specific steps that will be run only when a tenant is added/removed. 

Sounds good am looking forward to it.

**Comment by MaikiGirardi** [comment]
I just tested the 3.4 version and i just wonder if it's planned on your product backlog a schedule deployment to a tenant. It's very useful and necessary for my on-premise customers when using the management console.

**Comment by michaelnoonan** [comment]
Release Note: You can now manage tenants and tenanted deployments with Octopus Deploy

**Comment by alfhenrik** [comment]
@MaikiGirardi you can schedule a deployment to a Tenant just like you can with *normal* deployments, you do this by clicking the `Advanced` link (next to the `Deploy now` button) on the deployment screen and selecting `Later` in the `When` section.

**Comment by MaikiGirardi** [comment]
@alfhenrik thanks for your reply, one more question about that. My customers have a need to do a recurrence update, that is, every monday, wednesday and friday at 21:00 to automatically deploy their releases on their environments. There are any plan to make this improvement?

**Comment by jrote1** [comment]
Does the ability to run steps only when a tenant is added/removed exist?

**Comment by alfhenrik** [comment]
@MaikiGirardi We have a [UserVoice ticket](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6599104-recurring-scheduled-deployments) for this exact scenario.

**Comment by MaikiGirardi** [comment]
@alfhenrik thanks for your help!

**Comment by michaelnoonan** [comment]
Release Note: Multi-tenant deployments
