### ISSUE TITLE
Release "Promote To Env" button requires permission to all environments

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#1964]
Release "Promote To Environment" button requires permission to all environments rather than just the next environment in a lifecycle.

Source:
https://secure.helpscout.net/conversation/116638233/1219

NOTE: Issue provides detail of custom team and role specific to projects and environments.

**Comment by zentron** [comment]
Deuplicate: https://github.com/OctopusDeploy/Issues/issues/2098
