### ISSUE TITLE
OctoPack NuGet crashes when installing in F# projects

### ISSUE THREAD

**Issue by caioproiete** [OctopusDeploy/Issues#1966]
When installing OctoPack in F# projects, we get an error message:

```
PM> install-package Octopack
Installing 'OctoPack 3.0.43'.
Successfully installed 'OctoPack 3.0.43'.
Adding 'OctoPack 3.0.43' to FSharpConsoleAppRemove.
Successfully added 'OctoPack 3.0.43' to FSharpConsoleAppRemove.
Cannot find an overload for "Save" and the argument count: "0".At C:\PricingEngine\packages\OctoPack.3.0.43\tools\Install.ps1:37 char:5
+     $project.Save()
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

This happens because F# projects use [OAProject](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/Automation/OAProject.cs) which doesn't implement a method `Save` with no arguments. To get the same behavior, we have to call the `Save` method that receives the project name, pass an empty string to it.

ps: I did read the [guidelines for contributing](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md), and I'm about to send a PR to fix this, so seemed like creating an issue would be the right thing in this case - let me know if it is not.

**Comment by caioproiete** [comment]
@DamianMac Hi Damian, are you going to merge the PR?

**Comment by DamianMac** [comment]
Hi @caioproiete 
We're going to look at it (we have a few OctoPack PRs we need to look at soon). Closed the issue because of this https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md

Damian
