### ISSUE TITLE
UI memory leak

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1968]
As reported in http://help.octopusdeploy.com/discussions/problems/38455-dom-nodes-leaking-in-octopus-user-interface-causing-chrome-to-crash

**Comment by mpasari** [comment]
Was wondering if there is any progress and what is the timeline for a fix?

**Comment by jkonecki** [comment]
Hi @DamianMac , could you please explain why the issue won't be fixed? I believe it's still a problem for some users

**Comment by DamianMac** [comment]
Hi Jakub

It is a problem for some users, but not very many, not predictably, not easily debug gable, and one with a simple workaround (restart the browser every few days). 

The engineering cost to track down and fix this (if possible at all) is time and effort we'd rather spend adding features. 

Our thoughts in more details are here https://octopus.com/company/roadmap/why-was-this-closed

Damian
