### ISSUE TITLE
Step Template variable output is not available from subsequent script step

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#1970]
Project uses a step template that defines a variable NuGetPackageID.  If the deployment has an subsequent script step that tries to access the output variable from the previous step, it's not available.  Customer reported this worked in 2.x but it doesn't working 3.0.x.  

This following line worked in Octopus 2.x:
$OctopusParameters["Octopus.Step[$id].Package.NuGetPackageID"]

The following line but it doesn't work in Octopus 3.0.x w/ the following line.
$OctopusParameters["Octopus.Action[$id].Package.NuGetPackageID"]

**Workaround** is to set an output variable in the step template and then use it in any additional script steps.

Source:
https://secure.helpscout.net/conversation/116749988/1230/

**Comment by zentron** [comment]
Release Note: Variables with values derived from other step scoped values and are accessible via indexing with step name will be persisted across to subsequent steps.
