### ISSUE TITLE
Should not be able to create/deploy release if no environments

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1973]
http://help.octopusdeploy.com/discussions/problems/38497

We currently throw an error - instead we should handle it gracefully. 

(Test cases: no environments at all, and no environments assigned to the current lifecycle)

**Comment by jtdunlop** [comment]
In the case of a pure Azure Web Site deployment where no environments seem to make sense, does it make sense to not be able to create/deploy a release in all cases?

**Comment by robpearson** [comment]
Duplicate of OctopusDeploy/Issues#2085
