### ISSUE TITLE
Choosing a variable from the dropdown in a script step doesn't save unless you type again

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1974]
http://help.octopusdeploy.com/discussions/problems/38582

If choosing a variable from the dropdown is the last thing you do, the background contents of the script input aren't updated. When you save the task, it doesn't save the added variable.

**Comment by Damovisa** [comment]
![script-bug-1974](https://cloud.githubusercontent.com/assets/1887732/9709495/b6b42cb2-556f-11e5-904a-2ab0fea5b7e8.gif)

**Comment by Dalmirog** [comment]
Current workaround for this while we fix the issue:

1) Add some code to your step:

```
write-output
```

2) Add a variable using the list. Your code should look like this now:
```
write-output $MyVariable
```

3) Add an extra character at the end of your code, like a "."(dot) : 
```
write-output $MyVariable.
```

4) Delete the dot and save the step

**Comment by zentron** [comment]
Release Note: Inserting a variable into script as the last action before saving will persist the changes correctly

**Comment by mwoffenden** [comment]
The powershell pre-deployment script editor is flaky (I've noticed this for quite some time.)

OD VERSION: 3.2.14

The only SAVE process that reliably works is:

1) Make change to PS script in the OD script editor (pre deployment script window)
2) Copy it to the clipboard
3) Delete all code from the OD script editor
4) Hit SAVE
5) Paste code back into the OD script editor
6) Hit SAVE again

So I hope the OD team can look at the editor again.

**Comment by zentron** [comment]
@mwoffenden when you say its flaky, what particular scenario is failing for you? Please provide the failing repro steps and we can look at fixing it up.
