### ISSUE TITLE
Improve reliability of Octopus->Tentacle communications

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#1977]
As reported here: http://help.octopusdeploy.com/discussions/problems/38449
communications between Octopus server and Tentacles are less robust in 3.0 than in previously in 2.6.

**Comment by robpearson** [comment]
We've had additiona reports of transient network issues affecting deployments.  

Source:
https://secure.helpscout.net/conversation/126966912/2052/
http://help.octopusdeploy.com/discussions/problems/38666
http://help.octopusdeploy.com/discussions/problems/40046

**Comment by Tazer** [comment]
Would be awesome with some progress in this one. Holding us back from using octopus for a client.

**Comment by mjrichardson** [comment]
A few customers are currently trialing tweaked configuration settings, as per http://help.octopusdeploy.com/discussions/problems/38449 to see if this alleviates their specific issues.

**Comment by tothegills** [comment]
Would be nice if custom connection settings persisted on Server and Tentacle.  Also provide better defaults.

**Comment by mjrichardson** [comment]
New ticket created for preserving Halibut settings:
https://github.com/OctopusDeploy/Issues/issues/2212

**Comment by MJRichardson** [comment]
Halibut default timeouts have been modified, and a change was made to handle the scenario of all pooled connections being bad.  

These changes will be available in the next release (3.2.14).

We'll review whether these changes help customers with unreliable Tentacle connections.

I'm closing this issue for now.

**Comment by MJRichardson** [comment]
Release note:Updated default Tentacle connection timeouts.
Handling for the scenario where all pooled connections for a Tentacle are bad.
