### ISSUE TITLE
Pushing to built-in repo: allow users to ignore if package exists

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1978]
Some build processes don't always increment the package version if the package hasn't actually changed. At the moment, if they use `nuget.exe push` to push a package, it will fail with a 400 error because the package with that version already exists. 

It can be hard to change the build process to handle this, so as a solution, let's make it possible to specify a behaviour when pushing to the repository. Maybe this can be done with a query string:

      // 400 already exists
      nuget.exe push Mypackage.1.0.0.nupkg -source http:///..../nuget/package              

      // 200 OK:
      nuget.exe push Mypackage.1.0.0.nupkg -source http:///..../nuget/package?exists=ignore

**Comment by PaulStovell** [comment]
Also look at if we can:

Before returning a 400 error when they use the normal URL, log or show an info tip in Octopus UI to tell them the workaround

**Comment by PaulStovell** [comment]
Also consider how MyGet does it: 

http://docs.myget.org/docs/reference/faq

You enabled any of the following package settings for your feed. Verify the package settings for the feed you are pushing to.
Forbid overwriting of existing packages? - this will forbid overwriting packages that already exist on your feed (same package id and version)
Forbid packages which are non-compliant with Semantic Version? - this will forbid uploading packages that are not compliant with Semantic Versioning. E.g. a package version like 2.0.234.255 will not be supported.
MyGet will return a detailed error when pushing packages with a full description of the issue. If your NuGet client is not showing this error, use the -verbosity Detailed switch.

**Comment by PaulStovell** [comment]
And when this does happen, use the 409 conflict status code that MyGet uses, not 400

**Comment by GlenBoonzaier** [comment]
This issue can easily be reproduced by "retry build" in Visual Studio.

One concern that I foresee is how Octopus will react.  If I have a project that triggers a release based on the particular package not being updated, will the release not trigger now?  Different cases will require different reactions.

Perhaps let the user set the reaction by parameter in the build configuration. ( /p:exists=ignore )
Suggested options for exist:
 - ignore (will do nothing, no errors, will not trigger release for this package)
 - warn (will show warning in Octopus and on build log, will not trigger release for this package)
 - fail (default, build will fail as it currently does)
 - increment (this will append an incremental integer to the current version in the OctoPack library,
example: 2.5.235.235_1, 2.5.235.235_2, 2.5.235.235_3, etc... this would trigger the a release for this package)

**Comment by PaulStovell** [comment]
As of 3.2.4 you'll be able to use:

```
NuGet.exe push YourPackage.1.0.0.nupkg -ApiKey ... -Source http://your-octopus/nuget/packages?replace=true
```

**Comment by PaulStovell** [comment]
Added a documentation page: http://docs.octopusdeploy.com/display/OD/Push+a+NuGet+package+that+already+exists

**Comment by software-programmer** [comment]
I've upgraded from 3.2.0 => 3.2.6 to test this functionality and I'm seeing it fail with a 500 error

![image](https://cloud.githubusercontent.com/assets/5966776/11446426/9afe893c-952e-11e5-9f17-518980d7eec6.png)

**Comment by software-programmer** [comment]
It would be nice to return a message informing that the user doesn't have the correct permissions if they don't have "BuiltInFeedAdminister", otherwise you just receive a 500 error

![image](https://cloud.githubusercontent.com/assets/5966776/11446513/c8190f9a-952f-11e5-9e5e-31e69a3edd3d.png)

**Comment by michaelnoonan** [comment]
We've added this as a separate issue: https://github.com/OctopusDeploy/Issues/issues/2204
