### ISSUE TITLE
File encoding being set to UTF-8 BOM despite encoding option being set

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1979]
For variable transforms, the file encoding is being forced to UTF-8 BOM and seems to be ignoring the option to use template encoding.
See:
https://secure.helpscout.net/conversation/118999769/1448/

**Comment by tothegills** [comment]
This is a dupe of https://github.com/OctopusDeploy/Issues/issues/1814

**Comment by tothegills** [comment]
This is happening post 3.0.10 (when a fix was made)

**Comment by Dalmirog** [comment]
Possibly related https://secure.helpscout.net/conversation/120274077/1571/ ?

**Comment by DamianMac** [comment]
https://octopus.com/company/roadmap/why-was-this-closed

**Comment by TrentScholl** [comment]
Since it seems this won't be fixed.. If anyone comes across this, the work around is to add a step to your projects deployment processes with the following bash script to remove the BOM

sed -i '1 s/^\xef\xbb\xbf//' /path/to/deployment/*.conf

**Comment by paddie** [comment]
@DamianMac the link you provided doesn't give us any insight into why this was closed. We are running into this issue now, quite a few years later though...

**Comment by DamianMac** [comment]
Sorry @paddie maybe report it to support @ octopus (I don't work there anymore).
But if three people hit it in 3 and a half years it might not be the highest priority :)

**Comment by paddie** [comment]
Ha, I will @DamianMac :)

Yeah, we're also not sure exactly why it started happening now and the one team that's been hit by it (out of 15 other ones with around 300 projects), and we're also just performing a workaround so we don't have to wait for a fix.

Have a good day!

**Comment by droyad** [comment]
@paddie Does #4613 sound like the problem? If not, contact [support](https://octopus.com/support) with the details, including sample files and your configuration.
