### ISSUE TITLE
Changing Window Service and/or IIS App Pool password from value to Custom Expression fails to save the Custom Expression

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1984]
After setting a custom expression for the Service password, the change doesnt seem to be saved and it keeps using the previous password (as long as that password was typed manually)

1) Set password to "SomePassword" and save the step.
2) Create release and deploy.
3) Set password to a custom expression using an Octopus variable (sensitive or not).
4) Create release, Deploy and check the variables. The password is still "SomePassword" (can be seen because of #1955)
5) Check the custom expression field -> It is empty.

Octopus Version: 3.0.20
Source: https://secure.helpscout.net/conversation/119207264/1469/

**Comment by Dalmirog** [comment]
I'm checking this one again. I think I might have made a mistake and the bug is something else. Testing right now.

**Comment by michaelnoonan** [comment]
Another source but for IIS App Pool: http://help.octopusdeploy.com/discussions/problems/38745-iis-app-pool-password-cant-be-changed-to-a-variable-after-being-saved-as-a-static-value

**Comment by michaelnoonan** [comment]
Release Note: Custom Expressions now save correctly for Windows Service and IIS App Pool Custom Account Password values.
