### ISSUE TITLE
Configuration setting for Azure PowerShell module path

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#1985]
Provide a configuration setting to allow Azure PowerShell module to be loaded from installed location, rather than the version packaged with Calamari.

Currently, the Azure Resource Manager module is *not* packaged with Calamari, so this will allow people to use ARM.  It will also allow them to use a later version than the one packaged with Calamari.

**Comment by michaelnoonan** [comment]
Release note: Provide a configuration setting to allow Azure PowerShell module to be loaded from installed location, rather than the version packaged with Calamari.
