### ISSUE TITLE
SSH deployments should stream command output to control server as soon as it becomes available

### ISSUE THREAD

**Issue by marcind** [OctopusDeploy/Issues#1987]
We are using SSH deployment targets (octopus 3.0.21 at the moment) as drivers of some ansible config management scripts. The ansible command (`ansible-playbook` in this case) prints out progress information to stdout as work progresses, however it looks like Calamari does not send the output until the command completes.

This means we don't get visibility into the progress of long-running ansible playbooks until the whole thing is done, at which point all the output lines are dumped out back to Octopus.

It would make for a more responsive experience to be able to see the output as it's being generated by the target machine.

**Comment by marcind** [comment]
Is this closed because the issue has been resolved? I don't see any commit reference.
Would appreciate a comment on whether you are planning to resolve this or not. Thanks

**Comment by DamianMac** [comment]
Hi @marcind 

I closed it because of this https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
We were trying to do some planning yesterday so cleared out some issues.

Damian
