### ISSUE TITLE
Variables don't get saved properly while filtering

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1999]
1) Open project variables. 
2) Create a variable with the name "str1"
3) Open variable filter and filter by something that would make "str1" not show up. Like "test1"
4) With the filter for "test1" still on, create a variable that would show up with that filter, like "test11"
5) Save the changes.

Variable "str1" wasn't added to the variable set. Only variable shown by the current filter.

Octopus Version: 2.0.24
Source: http://help.octopusdeploy.com/discussions/problems/39016

**Comment by robpearson** [comment]
Release Note: Variable Editor saves changes when filters are applied.
