### ISSUE TITLE
Redirect to Login when UI gets 401 ("You must be logged in to...") from Ajax request

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2000]
This was originally implemented in #1621, but regressed with the UI redesign.

`serverstatus` is one place we could do this...
![image](https://cloud.githubusercontent.com/assets/1627582/9921534/e5c140da-5d21-11e5-96b3-fe3731be70a3.png)

Otherwise there might be a way to tap in to the `octopus.client.js` to redirect globally?

**Comment by zentron** [comment]
Release Note: UI Redirects to login if any AJAX request comes back with 401
