### ISSUE TITLE
Implement Sparseboard for Project overview page

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2003]
Per @PaulStovell request: Bring back the "Sparseboard" to hide environments where nothing was released from the Project overview page. The goal of this is to help users with slow loading times (and eventual crashes) on that particular page.

**Comment by Dalmirog** [comment]
Source: https://secure.helpscout.net/conversation/120721920/1610/

**Comment by PaulStovell** [comment]
We show a "ReleaseMatrix" on the dashboard and project overview. Environments are columns, and Projects or Releases are rows. 

Some teams have a very "sparsely populated" configuration - imagine 30 environments used by the project, but a given release only goes to one or two of those environments. So there are a lot of empty columns. 

"Sparseboard" means making the ReleaseMatrix smarter by automatically collapsing columns that have nothing to show in them. It would only come into effect when there are more than 10 environments.

**Comment by robpearson** [comment]
Release Note: Added Support for Release Matrix Sparseboard
