### ISSUE TITLE
User is able to name a project "All" which breaks API call

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2004]
If a user names a Project "All", then Octopus will try to get that Project's information using the URL  `/api/projects/all` ,which will return all the projects of the instance, causing the error seen on the screenshot

![all](https://cloud.githubusercontent.com/assets/6180562/9940680/a94310c2-5d47-11e5-8c70-7402b982df8b.png)

Source: http://help.octopusdeploy.com/discussions/problems/39035
Octopus version: 3.0.24

**Comment by luuksommers** [comment]
Is there a way I can delete the 'All' project?

**Comment by Dalmirog** [comment]
@luuksommers yup that's the recommended workaround. Glad to hear you were able to solve it.

**Comment by tothegills** [comment]
Release note: Prevent projects from being named 'all'
