### ISSUE TITLE
Remove dependency for PS4.0 for 3.1 features

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2005]
source: http://help.octopusdeploy.com/discussions/problems/39049-bootstrappostdeployps1-error-method-invocation-failed-because-systemsecuritycryptographyaescryptoserviceprovider-doesnt-contain-a-method-named-dispose

**Comment by mjrichardson** [comment]
release note:Resolved issue with PowerShell 2.0 and sensitive-variables
