### ISSUE TITLE
"must be at least one machine to deploy to in the environment" reported in valid scenario

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#2006]
As reported in: http://help.octopusdeploy.com/discussions/problems/39067

When deploying to an environment with no machines (e.g. for Azure deployment) and the deployment process contains machine-based steps that will not be run (due to environment specifications) deployment is failing with "There must be at least one machine to deploy to in the environment."

**Comment by mjrichardson** [comment]
release note:Resolved issue causing invalid "must be at least one machine to deploy to in the environment" error

**Comment by vanessalove** [comment]
release note: Fixed issue with Azure process allowing a deployment with no machines targeted
