### ISSUE TITLE
HA: "Add to cluster" wizard doesn't let you choose service account

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2007]
The "Getting started" wizard has a tab that lets you choose a service account. That tab is missing when you launch the "add this instance to a HA cluster" wizard instead. 

This is a problem because you have to manually change the service to run as the service account. Since clusters require a shared database and shared storage, it's quite unlikely that this will work with Local System.

**Comment by tothegills** [comment]
Release note: Allow service account selection when setting up a High Availability node
