### ISSUE TITLE
OD 3.1.0 - Create an API key, click off the dialog, lose the key

### ISSUE THREAD

**Issue by bendetat** [OctopusDeploy/Issues#2011]
1. Start generating an API key
2. Enter the name
3. Generate
4. Click off the modal (not the Close button or the cross, just on the modal overlay)

What happens:

- the modal disappears
- the key doesn't seem to have been added until reloading the page

What I expected:

- since this is a one-off screen (you can't get an already generated key) you shouldn't be able to close the modal without clicking the close button
- the screen should update to show the new key, so I don't keep adding new keys without knowing it did in fact add the key

Loving 3.1 so far ;-)

**Comment by mjrichardson** [comment]
Release note:Resolved UI issue with API key being lost when clicking off the dialog
