### ISSUE TITLE
Update installer to clear node table when not adding to a cluster

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2013]
We had a customer who took a backup of the DB to another server, installed it, then installed OD3.
This created a new instance in the nodes table. This then locked them out of their server.

If you are using the installer and not adding to a node, it should assume that its the only node connecting to the db and clear that table.
We also need to check the behavior when importing - how does the node table work?

**Comment by tothegills** [comment]
Release note: Prevent multiple Octopus installations from unintentionally exceeding license limits
