### ISSUE TITLE
Scheduled deployments start immediately using Internet Explorer

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2014]
Step by step action when I get to the “Deploy Release” screen:

- I select radio button on “Later”
- I place my cursor on the date field (which has todays date on it)
- I then delete the date and change it to tomorrows date e.g 2015-09-17 change to 2015-09-18

NOTE: “The Deployment will start in approximate…” information disappears and does not re-appear. I have to start the release again to get it back

- When I click on the Deploy release then the release happens immediately

Octopus version: 3.1.1
Source: http://help.octopusdeploy.com/discussions/questions/5614

**Comment by Dalmirog** [comment]
Calendar doesn't even let you pick a date from IE, so current workaround is to use another browser until this gets fixed.

**Comment by DamianMac** [comment]
This works fine for me in IE 11

**Comment by alfhenrik** [comment]
Release Note: Manually entering schedule date now correctly schedules a deployment in IE11
