### ISSUE TITLE
Dropdown list fields default to custom expression in step templates

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2015]
Step templates with dropdown lists show the following behavior:

1) Once you open the step from the deployment process, the fields that are supposed to be dropdown lists show up with the "custom expression" checkbox checked.

2) If you un-check the box (so the dropdown comes back again) and select a new value, it will go back to showing up as a "custom expression". If you do this a 2nd time, then it will stay as a dropdown as expected.

Used this step template for testing: https://library.octopusdeploy.com/#!/step-template/actiontemplate-iis-apppool-create

Octopus version: 3.1.1
Source: http://help.octopusdeploy.com/discussions/problems/39188

**Comment by Dalmirog** [comment]
Not a bad idea to fix along with #1885

**Comment by alfhenrik** [comment]
Closed as part of https://github.com/OctopusDeploy/Issues/issues/2095
