### ISSUE TITLE
"Add" button missing when adding roles to a team using Internet Explorer

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2016]
When attempting to add a role to a newly created team, the save button in the popup window does not appear/is not visible while using Internet Explorer. Sometimes, it does appear, but often it does not. It seems rather finicky when the add button actually appears. When trying with a Chrome as the browser, the add button does appear without issue.

Octopus Version: 3.1.1
IE: 11
Source: http://help.octopusdeploy.com/discussions/problems/39222

**Comment by Dalmirog** [comment]
User claims the button shows up sometimes, but in my case it was missing 20/20 times.

**Comment by DamianMac** [comment]
I can't repro this at all

**Comment by Dalmirog** [comment]
I can still reproduce this consistently

![addrole](https://cloud.githubusercontent.com/assets/6180562/10199930/d6937774-6779-11e5-8c95-ccb42e22751a.JPG)

![aboutinternetexplorer](https://cloud.githubusercontent.com/assets/6180562/10199965/063ad97c-677a-11e5-8945-eefa2579762b.JPG)

**Comment by alfhenrik** [comment]
Release Note: `Add` button is now shown once a role is selected.
