### ISSUE TITLE
Deleting a release is not audited

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2019]
Deleting a release (for example through Octopus.Client or octo.exe) is not being audited.

See http://help.octopusdeploy.com/discussions/questions/5652

**Comment by tothegills** [comment]
Release note: Deletions are now audited and will be displayed in the audit trail

**Comment by vanessalove** [comment]
Release note: Deletions from octo.exe or client now audited and will be displayed in the audit trail
