### ISSUE TITLE
Check validation on adding polling machines - must require Uri

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2020]
Customer added a polling tentacle without a Uri and octopus server service was unable to start as a consequence - validation needed to make sure cannot accept this as null data. 

https://secure.helpscout.net/conversation/122641373/1767/

**Comment by michaelnoonan** [comment]
Release Note: Now prevents creating a `Machine` with no `Uri` via the API and prevents server from crashing on startup if there are invalid `Machines`
