### ISSUE TITLE
Migrations are timing out in 3.1

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2021]
Had a customer whose `Add DeployedBy id column` migration took 24 minutes so the transaction timed out and the migration happened again and again.

See: http://help.octopusdeploy.com/discussions/problems/39220-upgrade-to-31-sql-issue-killing-octopus-deploy-service

**Comment by michaelnoonan** [comment]
Another source: http://help.octopusdeploy.com/discussions/problems/39422-octopus-server-3024-311-database-upgrade-failed

**Comment by michaelnoonan** [comment]
Release Note: Allow the database upgrade script that added the `DeployedBy` column to be run multiple times as a workaround for some customers. Also increased the database operation timeout to the maximum to allow more time for these scripts to succeed.
