### ISSUE TITLE
Typo in "Dependencies" field

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2022]
![uibug](https://cloud.githubusercontent.com/assets/6180562/10053716/fe221640-6203-11e5-9ccb-21f2721f46fb.png)

Appartenly a [common typo](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=seperate) included in #1 :) (ctrl +f "seperate")

**Comment by michaelnoonan** [comment]
Only found the one occurrence.

**Comment by michaelnoonan** [comment]
Release Note: Fixed a typo in the Windows Service feature page
