### ISSUE TITLE
Recursive / nested variables with parenthesis on the name not working

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2025]
Given the following variables

| Name | value|
| ------------- | ----------- |
| (variable with parenthesis) | MyValue |
| MyVariable | #{(variable with parenthesis)} |

During the deployment the value of `MyVariable` is `$OctopusParameters['(variable with p)']` instead of `MyValue`. Printing `$OctopusParameters['(variable with p)']` alone does return `MyValue` as expected, which leads me to believe that variables with parenthesis are supported, but they just not work when they are nested.

Setting the value of `MyVariable` to `$OctopusParameters['(variable with p)']` also returns the variable name instead of `MyValue`

**Comment by mjrichardson** [comment]
Release note:Support for parentheses in variable names
