### ISSUE TITLE
Deleting a Project is not audited

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2026]
Octopus version: 3.1.1

Tested in 2.6 and audit task shows up in this version.
![deleteproject](https://cloud.githubusercontent.com/assets/6180562/10081198/1bb17aea-62ca-11e5-8314-36e9c6ddde72.JPG)

**Comment by vanessalove** [comment]
@Dalmirog - how did you delete the project - can you be a bit more specific please so we can replicate.
Also was it attached to a ticket.

We just closed an issue about octo.exe and client deletes not being audited. so need to know if this is related or not.

**Comment by alfhenrik** [comment]
Fairly certain this was fixed in 3.1.3 - [#2019](https://github.com/OctopusDeploy/Issues/issues/2019)

**Comment by Dalmirog** [comment]
My mistake here - I was checking the "tasks" page instead of "Audit". Deleting from UI shows up in "Audit" as expected.

Sorry for the dumb mistake :(. This one can be closed
