### ISSUE TITLE
Deployments hanging with "Another process is currently building XYZ.nupkg.octosig" in Octopus 3.1

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2029]
Customer has reported hanging deployments. See the sources for more detailed logs and reproduction steps.

Example Task Log:
```
                    |         Running: Building delta for MyWebSite1.3.4
08:36:34   Info     |           Using package C:\Octopus\Packages\MyWebSite\MyWebSite.1.3.4.nupkg with hash b31b296dcc71f0ca889c8069a238b91f0254b29e for creating delta
08:36:34   Verbose  |           Another process is currently building C:\Octopus\OctopusServer\PackageCache\MyWebSite.1.3.4.nupkg.octosig
```

Source: http://help.octopusdeploy.com/discussions/problems/37931-problem-deploying-contents-of-nuget-package-after-upgrade#comment_38017196
Source: https://secure.helpscout.net/conversation/124267028/1843/

**Comment by michaelnoonan** [comment]
I had an epiphany and it turns out using the new Variable `Octopus.Acquire.DeltaCompressionEnabled` to skip Delta Compression was a good workaround for the problem. I've removed the `priority` label because the Customer is back up and running.

**Comment by tynor88** [comment]
I have the same error in 3.1!

**Comment by alfhenrik** [comment]
@tynor88 could you try and use the workaround above in the meantime until we can get a fix out for the hanging deployments?

**Comment by tynor88** [comment]
@alfhenrik that solves it, but with 100+ projects it's alot of time i have to spend to enable this on all.

Can you propose a way, i can enable it on all projects - perhaps with an sql script?

**Comment by alfhenrik** [comment]
I'll write up a PS script you can run through the Script Console, I'll get it to you sometime tomorrow.

**Comment by tynor88** [comment]
Sounds great, i appreciate that :)

**Comment by alfhenrik** [comment]
Hey @tynor88, 

I've created a couple of [scripts](https://gist.github.com/alfhenrik/c9f42161d730cb32daf6), one PowerShell and one LINQPad/C# script (if you use LINQPad, be sure to add the `Octopus.Client` NuGet package to the query), *pick your poison* :v:

You won't be able to run the script through Octopus but you can run it on your server or workstation as long as you have an API key that gives you access to your Octopus instance.

Hope that helps!

Thanks,
Henrik

**Comment by tynor88** [comment]
@alfhenrik Thanks, i applied the VariableSet on all my projects! Hope the bug will be fixed soon though :+1:

**Comment by tothegills** [comment]
Hi @tynor88,

Would it be possible to check your Octopus database to see if the table `dbo.Mutex` exists?

Thanks,
Shane

**Comment by tynor88** [comment]
![image](https://cloud.githubusercontent.com/assets/2877439/10186611/aefde9e6-6752-11e5-88f8-5a3fec1bda54.png)

Seems like it has been created with a wrong schema. Hmm. That might be an issue?

**Comment by tynor88** [comment]
I think this issue relates to what my [colleague reported a few months back](http://help.octopusdeploy.com/discussions/problems/36168-installing-301-on-an-existing-empty-database-fails) and also [me a few days back](http://help.octopusdeploy.com/discussions/problems/39499-upgrading-tentacles-from-30-to-31-fails-if-the-tentacle-is-not-running-as-local-system-account). It happends when the server (or tentacles) are running as a custom domain user. In our case app_Octopus.

I have ran these 3 SQL commands, and this seem to have fixed the problem:
```
ALTER SCHEMA dbo TRANSFER [NEAS\app_Octopus].[DeploymentHistory];
ALTER SCHEMA dbo TRANSFER [NEAS\app_Octopus].[Mutex];
ALTER SCHEMA dbo TRANSFER [NEAS\app_Octopus].[UpdateDeploymentHistory];
```

**Comment by tothegills** [comment]
Release note: Database migrations will be applied to the correct schema
