### ISSUE TITLE
Migrating Azure Cloud Service Step from Octopus 2.6 to 3.1.1 fails with "Please select an Account or provide a variable expression for the Account ID to use."

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2031]
The validation we added to ensure users don't create invalid Azure Steps via the User Interface/API appears to be too strict for the migrator.

We should consider fabricating an `Account` per `AzureStep.SubscriptionId` or somehow relax this rule for migration. We have pre-deployment validation that fails a deployment early if an `Account` is not selected or is missing.

Source: http://help.octopusdeploy.com/discussions/problems/39458-failed-to-migrate-from-26-to-311

**Comment by alfhenrik** [comment]
Release note: Don't enforce that AccountId exists on cloud service step when migrating from 2.6
