### ISSUE TITLE
Config Transform not working if Transform and Config are in different directories

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2032]
It was working in 2.6 and it seems to no longer be working in 3.1.1.

Deployment logs for 2.6 and 3.1.1 with attempts to transform
```
[subdir]\[transform file] => [config file]
```

https://gist.github.com/Dalmirog/a5673ba39fce2dc25f66

**Comment by Dalmirog** [comment]
User reported it was working in `3.0.16` and it stopped working in `3.1.1`. Then he rollbacked to `3.0.24` and it wasnt working either.

http://help.octopusdeploy.com/discussions/problems/39329

**Comment by alfhenrik** [comment]
Release note: Bring back support for config transform files in subfolders

**Comment by nkomp18** [comment]
As of May 2016, I couldn't get this very simple scenario to work.
I have custom config in a folder:

config\section1.config

And the appropriately named config with the transformation:

config\section1.<Environment.Name>.config

But octopus won't touch it. I've also tried adding this in the additional transforms section, although I shouldn't have to, it should just work automatically.

*.#{Octopus.Environment.Name}.config => *.config

Is this a new bug with Octopus 3.3.1.2?
