### ISSUE TITLE
Cannot select C# or Bash Script options

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2033]
Cannot select C# or Bash script option on Script steps or Package Steps with custom deployment scripts.  Radio buttons are selected but the selection doesn't take effect.

![screenshot 2015-09-27 21 50 53](https://cloud.githubusercontent.com/assets/216245/10122601/27bdfd6e-6562-11e5-8728-d40c2b6e4055.png)

Tested using Chrome, Safari and Internet Explorer 11.

Source:
https://secure.helpscout.net/conversation/124460498/1859/

**Comment by Dalmirog** [comment]
Another report: http://help.octopusdeploy.com/discussions/problems/39577

**Comment by alfhenrik** [comment]
Release note: Selecting script syntax now selects the syntax you chose

**Comment by RichiCoder1** [comment]
A+ release note :D
