### ISSUE TITLE
"LastModifiedOn" and "LastModifiedBy" properties of Machine resources return null values

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2039]
JSON of machine in 3.1.1
```
{
  "Id": "Machines-1",
  "Name": "Machine1",
  "Thumbprint": "Thumb",
  "Uri": "https://localhost:10933/",
  "IsDisabled": false,
  "EnvironmentIds": [
    "Environments-1"
  ],
  "Roles": [
    "Console",
    "webserver"
  ],
  "Status": "NeedsUpgrade",
  "StatusSummary": "This machine is running an old version of Tentacle (3.1.1).",
  "Endpoint": {
    "CommunicationStyle": "TentaclePassive",
    "Uri": "https://localhost:10933/",
    "Thumbprint": "thumb",
    "Id": null,
    "LastModifiedOn": null,
    "LastModifiedBy": null,
    "Links": {}
  },
  "Links": {
    "Self": "/api/machines/Machines-1",
    "Connection": "/api/machines/Machines-1/connection"
  }
}
```

JSON of machine in 2.6
```
{
  "Id": "machines-1",
  "Name": "localhost",
  "Thumbprint": "thumb",
  "Uri": "https://localhost:10933/",
  "IsDisabled": false,
  "EnvironmentIds": [
    "Environments-1"
  ],
  "Roles": [
    "webserver"
  ],
  "Squid": "SQ-WIN-JPML1JBQ9KE-93B05637",
  "CommunicationStyle": "TentaclePassive",
  "Status": "Online",
  "StatusSummary": "Octopus was able to successfully establish a connection with this machine on Tuesday, September 29, 2015 10:21 AM",
  "LastModifiedOn": "2015-09-02T19:19:42.420+00:00",
  "LastModifiedBy": "dalmiro.granias",
  "Links": {
    "Self": "/api/machines/machines-1",
    "Connection": "/api/machines/machines-1/connection"
  }
}
```

Octopus version: 3.1.1
Source: http://help.octopusdeploy.com/discussions/questions/5714

**Comment by bjewell52** [comment]
Hey Vanessa, how come this won't be fixed?

**Comment by MarcoJ-CID** [comment]
Hi @all.

bjewell52 said:
>Hey Vanessa, how come this won't be fixed?

Is it possible to check easy the last change date of an environment or a machine like by the API. The usage of SQL Table "Events" is not available in our use case.

**Comment by droyad** [comment]
We no longer store this information directly on an entity. Rather we store it in the Audit records (`Events`). You can retrieve these via the api, for example:

`http://localhost/api/Events?regardingAny=Channels-2,Channels-3&from=2016-08-12T00:42Z`

This will get any events that match any of the listed channels from the specified time. Check out `http://localhost/api` to see the other arguments. `regarding` will match events where all the listed resources are linked.
