### ISSUE TITLE
Octopack fails to create a nuget file with bin folder when changing output directory

### ISSUE THREAD

**Issue by dariogriffo** [OctopusDeploy/Issues#2041]
Setting -OutputDirectory in Nuget arguments fails to add the bin folder of my web application.
Relevant lines of the diagnose log is below

The project doesn't have a nuspec file as stated here in the log:

    OctoPack: A NuSpec file named 'TestProject.WebUI.nuspec' was not found in the project root, so the file will be generated automatically. However, you should consider creating your own NuSpec file so that you can customize the description properly. (TaskId:5)
    OctoPack: Packaging an ASP.NET web application (Web.config detected) (TaskId:5)
    OctoPack: Add content files (TaskId:5)

Then the build of the package:

C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe /p:OctoPackNuGetArguments=-OutputDirectory "C:\Workspace\TestProject\octopacked" /t:OctoPack /verbosity:diag TestProject.WebUI\TestProject.WebUI.vbproj

    C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe /p:OctoPackNuGetArguments=-OutputDirectory "C:\Workspace\TestProject\octopacked" /t:OctoPack /verbosity:diag TestProject.WebUI\TestProject.WebUI.vbproj

    OctoPack: Added file: Views\Site.Master (TaskId:5)
    OctoPack: Add binary files to the bin folder (TaskId:5)
    OctoPack: NuGet.exe path: C:\Workspace\TestProject\packages\OctoPack.3.0.43\tools\NuGet.exe (TaskId:5)
    OctoPack: Running NuGet.exe with command line arguments: pack "C:\Workspace\TestProject\TestProject.WebUI\obj\octopacking\TestProject.WebUI.nuspec"  -NoPackageAnalysis -BasePath "C:\Workspace\TestProject\TestProject.WebUI" -OutputDirectory "C:\Workspace\TestProject\TestProject.WebUI\obj\octopacked" -Version 0.0.7 -OutputDirectory "C:\Workspace\TestProject\octopacked" (TaskId:5)
    OctoPack: Attempting to build package from 'TestProject.WebUI.nuspec'. (TaskId:5)
    OctoPack: Successfully created package 'C:\Workspace\TestProject\octopacked\TestProject.WebUI.0.0.7.nupkg'. (TaskId:5)
    OctoPack: Packages have been copied to: C:\Workspace\TestProject\TestProject.WebUI\bin\ (TaskId:5)
    OctoPack: OctoPack successful (TaskId:5)

We don't want to create nuspec files in order to speed up the development, and all the variables are set with Jenkins (version, Id, etc)

**Comment by DamianMac** [comment]
https://octopus.com/company/roadmap/why-was-this-closed
