### ISSUE TITLE
AzureProfile.json getting locked when deploying to azure apps in parallel

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2054]
```
13:03:57   Error    |     Set-AzureSubscription : The process cannot access the file
13:03:57   Error    |     'C:\Windows\system32\config\systemprofile\AppData\Roaming\Windows Azure
13:03:57   Error    |     Powershell\AzureProfile.json' because it is being used by another process.
13:03:57   Error    |     At C:\Octopus\Work\20151006200210-48\DeployToAzure.ps1:29 char:2
13:03:57   Error    |     +     Set-AzureSubscription -SubscriptionName $OctopusAzureSubscriptionName
13:03:57   Error    |     -CurrentS ...
13:03:57   Error    |     +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:03:57   Error    |     ~~~~~~
13:03:57   Error    |     + CategoryInfo          : NotSpecified: (:) [Set-AzureSubscription], IOExc
13:03:57   Error    |     eption
13:03:57   Error    |     + FullyQualifiedErrorId : System.IO.IOException,Microsoft.WindowsAzure.Com
13:03:57   Error    |     mands.Profile.SetAzureSubscriptionCommand
```
Octopus version: 3.1.3
Source: http://help.octopusdeploy.com/discussions/problems/40018

**Comment by alfhenrik** [comment]
Release note: Use local Azure profile to avoid file locking when running Azure steps in parallel

**Comment by HakanL** [comment]
This has only happen 2 or 3 times, out of maybe 30-40 deployments so far, so it's not very easy to reproduce. But my guess is that a file is opened with read/write instead of read-only (like File.OpenRead for example). But if you're using a local file then that may solve it too. This was an issue in 2.x as well btw.

**Comment by HakanL** [comment]
I've been running with this for a while now and haven't seen any of these issues again, so I think we can say for sure it's fixed and verified.

**Comment by alfhenrik** [comment]
@HakanL great to hear that you haven't had any further issues with this file being locked!

And thanks for letting us know.
