### ISSUE TITLE
Base-64 error when license entered into 3.x

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2056]
See ticket for license (im not putting it here), replicated in 3.2beta.
big errors on screen. have to assume at some point we have had all those characters in the signature 

if wrong then move to octofront to make sure that doesnt happen again.
source: http://help.octopusdeploy.com/discussions/problems/40117-license-not-recognized-illegal-character-error

**Comment by zentron** [comment]
The only thing i can think is that based on the Licence key he provided there is a `-\n` in what he pasted. Since `-` is an invalid base64 character and its followed by a line break I'd say he cut+paste it incorrectly.
Until we hear about this coming from someone else Id say this is closed.
