### ISSUE TITLE
Cannot find type AesCryptoServiceProvider in WindowsService_AfterPreDeploy.ps1

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2058]
Octopus 3.1.3

Reported to fail intermittently and succeed on further deployments.

Source: http://help.octopusdeploy.com/discussions/problems/40073-random-error-on-deployment

**Comment by zentron** [comment]
Fixed with Calamari build #3.1.1-ci.27 (30 Oct 15 00:54)
