### ISSUE TITLE
Release retention policy fails if there are too many releases

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2059]
Currently if there's lots of releases, the following error might be encountered.

`The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.`

Related to OctopusDeploy/Issues#1935

Source: http://help.octopusdeploy.com/discussions/problems/40307

**Comment by michaelnoonan** [comment]
Source: http://help.octopusdeploy.com/discussions/problems/41125-retention-policy-issue-on-server-315

**Comment by bigbam505** [comment]
Any ETA on when this will be fixed?  I assume this isn't too high priority because worst case just releases won't be cleaned up but a general idea of when it will be looked at would be nice.  Thanks!

**Comment by zentron** [comment]
Release Note: When performing server side retention policy, the deployment information is loaded in batches to avoid hitting `SQL Max 2100 parameters` exception.
