### ISSUE TITLE
Recursive variable substitution when iterating not working

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#2060]
As reported here: http://help.octopusdeploy.com/discussions/problems/40194

**Comment by michaelnoonan** [comment]
Fixes OctopusDeploy/Issues#1939

**Comment by mjrichardson** [comment]
Release  note:Recursive variable substitution during #{each... re-implemented. This worked in 2.x, but had been broken in 3.x.

**Comment by osudude** [comment]
Upgraded to Octopus 3.1.5 today.  Refreshed variables for our release where we noticed the substitution issue.  Re-deployed.  The variables did not recursively substitute for some reason.

**Comment by osudude** [comment]
Any idea when 3.1.6 will be released? 

thanks
