### ISSUE TITLE
Excel reporting fails when using AD authentication

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#2061]
Excel will prompt for username/password even when the API key is passed.

See https://secure.helpscout.net/conversation/129632273/2293/

**Comment by zentron** [comment]
This does not seem to be occurring for me so not yet sure if this is a bug or not

**Comment by PaulStovell** [comment]
It might be that they use a proxy server?

**Comment by zentron** [comment]
Unable to repro, have so far been unable to receive more information.
