### ISSUE TITLE
Do not enforce 500Mb disk space requirement when running a PowerShell script

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2062]
Customer using PS script to clean up after failed steps, but can't due to disk space requirement.

We should discuss if this requirement should be enforced when running a PS script.
Source: http://help.octopusdeploy.com/discussions/problems/40340

**Comment by bigbam505** [comment]
I looked into contributing but don't have nearly enough time right now!  Thanks for opening this.  (Just wanted to comment so I get email alerts :smile: )

**Comment by DamianMac** [comment]
https://octopus.com/company/roadmap/why-was-this-closed
