### ISSUE TITLE
Deployments queue on the same environments even when OctopusBypassDeploymentMutex is True

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#2064]
Confirmed this was working correctly in 2.6. If the OctopusBypassDeploymentMutex variable was set to True on multiple projects, those projects could be deployed in parallel to the same environments.
This is no longer the case in 3.1.2.

See https://secure.helpscout.net/conversation/129756457/2307/ for details.

May also be related to OctopusDeploy/Issues#1950

**Comment by PaulStovell** [comment]
The user was hitting the task cap - not a bug
