### ISSUE TITLE
OctoPack includes .dbproj extension in package name

### ISSUE THREAD

**Issue by RMSEddy** [OctopusDeploy/Issues#2066]
When building under TeamCity (and possibly other cases) when the target of the build is a .sqlproj file rather than a .sln file, OctoPack does not remove the .sqlproj extension when generating the filename of the .nuspec file (and consequently the .nupkg file).

Version Info:
- OctoPack: 3.0.43
- TeamCity: 9.1.3
- TeamCity Octopus Plugin: 2.6.3.37

Input filename: My.Test.Database.sqlproj
Expected filenames: My.Test.Database.nuspec -> My.Test.Database.1.0.0.5.nupkg
Actual filenames: My.Test.Database.sqlproj.nuspec -> My.Test.Database.sqlproj.1.0.0.5.nupkg

**Comment by DamianMac** [comment]
OctoPack doesn't really offer support for those project types at the moment
https://octopus.com/company/roadmap/why-was-this-closed
