### ISSUE TITLE
Deployments API endpoint no longer lets you filter on task state

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#2072]
Providing a taskState querystring has no effect when using the /api/deployments endpoint.

See  https://secure.helpscout.net/conversation/130055083/2333/ for bug report.

Change is apparent here:
https://github.com/OctopusDeploy/OctopusDeploy/commit/b2b500f8a6fcda44944d57f4c1a40e9a28306637#diff-c542776157a939a48d5c8bfcec7135d5L41

**Comment by PaulStovell** [comment]
If there isn't an easy way to do this (i.e., without joining/making that query slower) then I'd vote to drop it. The tasks API supports filtering by deployment tasks and task state.

**Comment by tothegills** [comment]
Release note: Re-implement ability to filter deployments by task state
