### ISSUE TITLE
URL of external feeds does not take advantage of the field's lenght

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2074]
It seems to be limited to 40-something characters. We could definitely show more characters, and maybe a tooltip if the full path is way too long.

![octopus-deploy-external-feeds-url](https://cloud.githubusercontent.com/assets/6180562/10492453/94cf37ce-7282-11e5-8a6d-3fdbec0069ab.png)

Source: http://help.octopusdeploy.com/discussions/problems/40459
Octopus version: 3.1.3

**Comment by DamianMac** [comment]
https://octopus.com/company/roadmap/why-was-this-closed
