### ISSUE TITLE
Azure PowerShell profile is not updated when Azure Account is changed

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2076]
**Steps to reproduce**
1. Create a new Azure Account called "CachedThumbprint" letting the certificate be automatically generated - BUT don't upload the Management Certificate to Azure
2. Create a Project with a single Azure PowerShell step that does something like `Get-AzureWebsite`
3. Create and deploy a Release which should fail saying it can't connect or authenticate with Azure
4. Edit the Azure Account and make it generated a new certificate
5. Reload the Azure Account to make sure you've got the link to the new certificate with a different Thumbprint to before
6. Upload the new Certificate to the Azure Portal
7. Add an Azure Web App step to your Project, select the "CachedThumbprint" Account and make sure it can happily list the Web Apps in the Subscription - this proves the Management Certificate is correctly uploaded
8. Remove the Web App Step - it isn't needed
9. Try to run the deployment again (with just the Azure PowerShell step)

I'd expect this to succeed but it appears to use  cached Thumbprint and picks the wrong certificate.

**Workaround**
To fix this situation, simply change the Name of the Azure Account and re-run the deployment. This inserts a new record into the cached profile and the deployment should work, picking the second Certificate correctly.

**Comment by michaelnoonan** [comment]
Could be related to OctopusDeploy/Issues#2054

**Comment by alfhenrik** [comment]
Release note: Use local Azure profile to prevent using a cached Azure profile that may be invalid
