### ISSUE TITLE
JS error promoting to an environment in the UI

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#2080]
Reported here: http://help.octopusdeploy.com/discussions/problems/40338

If the request for all available machines takes longer than the other API requests, we get an error. The list of specific machines relies on this collection which hasn't been populated yet.

See the deployment create controller in the portal JS - lines 98 and 230.

**Comment by Damovisa** [comment]
See Dropbox for video of the issue: `Octopus Deploy Shared\Customers\Issues\Issue_2080`

**Comment by bigbam505** [comment]
Sorry for spam commenting so I get emails for the issue.  Also here is the timeline view from our troubleshooting:

![Timeline](https://dl.dropbox.com/s/ekfebx1xbbvaqpd/octo_issue.jpg?dl=0)

**Comment by zentron** [comment]
Release Note: Bugfix for JS script error caused by race condition on deployment page
