### ISSUE TITLE
Unable to change Application Pool password in the Step Template

### ISSUE THREAD

**Issue by ajakuszyk** [OctopusDeploy/Issues#2082]
In Octopus 3.1.3 I created a step template based on 'Deploy NuGet Package' preset.
I've enabled 'IIS web site and application pool' feature and set 'Application Pool identity' to 'Custom User'
I've specified #{Custom.Password} as a password for the application pool.
After I saved the template, I wanted to change the password in the template to be some other variable - e.g. #{MyNewCustomPassword.Variable} but when I change it and press 'Save' - the changes to the Application Pool custom password are not saved - I can still see the old password value #{Custom.Password} when trying to export it, and when trying to use it in the project the old password is used.

**Comment by zentron** [comment]
HI thanks for logging this issue.
Luckily I have literally just fixed this issue as part of another ticket (https://github.com/OctopusDeploy/Issues/issues/2092) this afternoon. It should go out in the next `3.2.` release so keep an eye out.
