### ISSUE TITLE
Retention policy should explicitly block deletion of directories corresponding to skipped deployments

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2083]
Consider the following scenario
1. Deploys `1.1.0` (fails) which creates folder `C:\1.1.0`
2. `C:\1.1.0` is manually deleted (or via script?) due to space limitation (though this does not affect deployment manifest)
3. Deploys `1.1.0` again. Now because `C:\1.1.0` no longer exists on the filesystem, rater than creating `C:\1.1.0_1` it just creates `C:\1.1.0`
4. Retention policy runs, sees the failed deployment to clean up and then goes along to _remove its corresponding directory at `C:\1.1.0` despite it now also being the same directory as a skipped/valid deployment directory_.

When the retention policy runs on the Tentacle, it should ensure that the list of resources being removed does not match any of those referenced by deployments that should be persisted.

source: http://help.octopusdeploy.com/discussions/problems/40536

**Comment by bigbam505** [comment]
Thanks this could be very problematic, for :raising_hand   Thanks!

**Comment by bigbam505** [comment]
Any idea when this will be looked at.  Know 3.2 is on the verge but was hoping this would be included in an update before 3.2 was released.

**Comment by zentron** [comment]
Release Note:  Retention policy will retain directory of removed deployments if it is the same directory as a retained deployment.

**Comment by bigbam505** [comment]
Thanks!
