### ISSUE TITLE
Calamari: Updating appSettings and connectionStrings should say the name of the file it fails on

### ISSUE THREAD

**Issue by yetanotherchris** [OctopusDeploy/Issues#2086]
If you enable "Update appSettings and connectionStrings" in a step, and have an invalid XML config file, the output only shows the previous file it succeeded on, but not the file that breaks.

Could the error handling show the current file it was processing when it failed?

For example, this is what currently displays when `D:\Octopus\Applications\FooApp\App_Config\Foo.config` fails:

		No matching setting or connection string names were found in: D:\Octopus\Applications\FooApp\App_Config\WebDAV.config
		No matching setting or connection string names were found in: D:\Octopus\Applications\FooApp\App_Config\Web1.config
		No matching setting or connection string names were found in: D:\Octopus\Applications\FooApp\App_Config\Web2.config
		System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
		at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
		at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()

**Comment by michaelnoonan** [comment]
This would be really good to have, and should be a simple fix.

**Comment by tothegills** [comment]
I think the path of the failed file was added in https://github.com/OctopusDeploy/Calamari/commit/c0fae6003038ab2a5a30d61b237eee47486673a6

**Comment by tothegills** [comment]
In latest Octopus:
```
Exception while replacing configuration-variables in: C:\Octopus\Applications\Branch\BadConfig\2015.8.31.121211_3\Bad.QA.mvl.config
20:37:03Error
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
```
