### ISSUE TITLE
Warning on creation of key for Mutex database table

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#2087]
There's a warning raised by the "0020 - Create mutex table.sql" script regarding index key lengths.

"Warning! The maximum key length is 900 bytes. The index 'PK_Mutex_Id' has maximum length of 1000 bytes. For some combination of large values, the insert/update operation will fail."

We should handle this better.

See: http://help.octopusdeploy.com/discussions/problems/40624

**Comment by tothegills** [comment]
This affects `RelationalMutex` and could cause problems when doing file operations such as computing deltas when the signature file name is too long to fit in the column.

**Comment by tothegills** [comment]
Release note: Fixed warning when creating database mutex table
