### ISSUE TITLE
Wrong text is displayed when deleting script modules

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2088]
![1](https://cloud.githubusercontent.com/assets/6180562/10619428/03f051f6-774c-11e5-9840-d4c82d6539e9.png)

**Comment by tothegills** [comment]
A script module is a library variable set. I think changing the wording is not worth the hassle.

**Comment by Dalmirog** [comment]
It is a Library Variable Set on the background, yes. But its not too much of a hassle if its a one-liner. Plus it'll improve consistency.

**Comment by michaelnoonan** [comment]
Ah, I added one-liner without looking deeper, but I could imagine this could easily confuse someone.

@tothegills, how about we just make the wording more generic? They already know what they're trying to delete.

`This is included in the following projects: XYZ`

**Comment by michaelnoonan** [comment]
Release Note: Now showing a more informative message when attempting to delete a Script Module that is used by one or more Projects.
