### ISSUE TITLE
Custom expression is not visible on the UI on the App Pool password field after saving the step

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2092]
After saving the step and checking it back again the custom expression is not visible on the UI, but it seems to be present functionality-wise as the App Pool password is set correctly.

1) Before saving
![image001](https://cloud.githubusercontent.com/assets/6180562/10644196/b44528ae-77fd-11e5-846e-d3858ffdf711.png)

2) After saving
![image002](https://cloud.githubusercontent.com/assets/6180562/10644206/c0c0d33a-77fd-11e5-85d4-74d97f579d7f.png)

Related to #1984 , but this issue is only about UI.

Octopus version: 3.1.14

**Comment by zentron** [comment]
Release Note: IIS App Pool Password shown in UI if custom expression is used

**Comment by Dalmirog** [comment]
![apppoolpassword](https://cloud.githubusercontent.com/assets/6180562/13159999/bc5e5aa4-d673-11e5-8eff-c45b0d92ee1f.gif)
*Sorry for the speed. Tool only allowed me to record 20secs*

Separate issue or am I not understanding how this is supposed to work?
