### ISSUE TITLE
Azure web app slots support

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2094]
Per conversation with @PaulStovell 

Creating this ticket to investigate how we can add support for azure web app slots just like we have for azure services. 

The current way to use them are either using `Switch-AzureWebsiteSlot` or a custom expression with the name of the webapp in the format `<web-app-name>(<deployment-slot-name>)`. It'll be good to have some sort of dropdown list or maybe a dedicated step for this.

**Comment by MJRichardson** [comment]
This is a nice idea, and we may well revisit it, but as it doesn't add anything that isn't currently possible, closing for now due to low priority.

Slots currently show as separate sites (in Azure slots *are* actually sites), and as mentioned above, can be swapped using custom PowerShell.
