### ISSUE TITLE
Overlapping display names on Environments page

### ISSUE THREAD

**Issue by nathan-alden** [OctopusDeploy/Issues#2096]
The display names on the Environments page can overlap one another because they neither wrap nor clip. This happens when the display names are a long string without spaces--say, a domain name.

![image](https://cloud.githubusercontent.com/assets/1189759/10711279/a068247c-7a3b-11e5-91d8-a7355a8efe8e.png)

**Comment by DamianMac** [comment]
https://octopus.com/company/roadmap/why-was-this-closed
