### ISSUE TITLE
Cannot find type "System.Security.Cryptography.AesCryptoServiceProvider"

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2097]
We've seen a few instances of Customers reporting PowerShells scripts failing to load `System.Security.Cryptography.AesCryptoServiceProvider` which is in `System.Core.dll`.

A couple of recommendations:

1. Add `Add-Type -AssemblyName System.Core` and see what happens with these customers.
2. Make sure the [Bootstrap.ps1](https://github.com/OctopusDeploy/Calamari/blob/94e883c84e8605a7b032492e23e813e369811733/source/Calamari/Integration/Scripting/WindowsPowerShell/Bootstrap.ps1) script fails if the type cannot be loaded. We should move `$ErrorActionPreference = 'Stop'` to before the `{{VariableDeclarations}}`

Related to https://github.com/OctopusDeploy/Issues/issues/2058

Source: http://help.octopusdeploy.com/discussions/problems/41173-deploy-nuget-package-goes-wrong-today

Source: http://help.octopusdeploy.com/discussions/problems/40907-power-shell-errors-iiswebsite_beforepostdeployps1-after-upgrading-from-26-to-314

**Comment by zentron** [comment]
Have created a branch with these changes
https://github.com/OctopusDeploy/Calamari/compare/bugfix-missingaes?expand=1
and have sent link to user to test

**Comment by michaelnoonan** [comment]
Release Note: Now loading `AesCryptoServiceProvider` more reliably in PowerShell scripts to decrypt sensitive variables.
