### ISSUE TITLE
User can not Promote to Environment when team is scoped to environments

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2098]
A user who has been given `DeploymentCreate` permissions and has been scoped to environments (even if all environments) can not view the `Promote to Environment` button on the release page.

See http://help.octopusdeploy.com/discussions/problems/41219

**Comment by tothegills** [comment]
Also UI jankyness: http://help.octopusdeploy.com/discussions/problems/41287

**Comment by alfhenrik** [comment]
Release note: Users can now Promote to Environment when their team is scoped to environments

**Comment by burck1** [comment]
You guys are awesome! Only a week turnover!
