### ISSUE TITLE
OctopusTools NuGet package cannot be installed when using NuGet 3.0 or higher

### ISSUE THREAD

**Issue by shaynevanasperen** [OctopusDeploy/Issues#2100]
Due to NuGet 3.0 having dropped support for solution level packages, it is now impossible to install the OctopusTools package into a solution. It has to be installed into a specific project, which is impossible because it doesn't contain any files in the `lib` folder. A simple workaround for this exists, which is to place a dummy file into the `lib` folder, which results in the package becoming a project level package and thus compatible with NuGet 3.0 or higher. When making this change, it is also important to mark the package as a development dependency by adding `<developmentDependency>true</developmentDependency>` into the metadata section of the nuspec file. This will ensure that the package reference does not automatically become transitive, in case the consuming project gets packaged as a NuGet package.

**Comment by michaelnoonan** [comment]
Source: http://help.octopusdeploy.com/discussions/problems/41345-octopustools-nuget-package-cannot-be-installed-when-using-nuget-30-or-higher

**Comment by michaelnoonan** [comment]
Release Note: Updated OctopusTools (`octo.exe`) so it can be added to a project using NuGet 3 - shout out to @shaynevanasperen for the contribution.

**Comment by michaelnoonan** [comment]
Hey @shaynevanasperen. I noticed the nuget package we're building is putting `octo.exe` into the root, instead of the `\tools` folder. I think moving this into the `tools` folder makes good sense because:

- It's a tool ;)
- You could run `octo.exe` from the Package Manager Console directly (it gets added to the `$env:PATH` of the PowerShell session)
- We don't need the `DUMMY.txt` file hack any more.

I'm looking to make it a minor version bump to `3.3.0` so `Update-Package -Safe` will be safe, since the path will change and break scripts that depended on it.

Got any thoughts?

**Comment by shaynevanasperen** [comment]
That should work fine. And I agree with your reasoning. I didn't know that adding files to the `\tools` folder also worked, but now I do ;-). I'm a little unclear though on whether or not the major version number should be incremented instead, as according to [Semantic Versioning](http://semver.org/), if you make a breaking change it should increment the major version number. But since this change is not breaking the actual executable file itself, you could argue that it is not a breaking change. It's a little bit murky to be honest, so I'll leave that decision up to you.

**Comment by michaelnoonan** [comment]
Yeah, I agree. I didn't like that people would interpret a major version bump as an API version incompatibility - so I've gone with leveraging the tooling through the `-Safe` parameter instead. I think it's a reasonable compromise given the practical considerations.

Again, thanks for your input!
