### ISSUE TITLE
Log when we find octostache syntax that can't be resolved with variable substitution

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#2105]
If there's an error when doing variable replacement or some octostache syntax that can't be resolved, it appears we fail silently. We should log that we couldn't replace the variable appropriately - albeit not aggressively (info or verbose).

See: http://help.octopusdeploy.com/discussions/problems/40632

**Comment by crmckenzie** [comment]
Looking at the code for Octostache, the if block in TemplateParser line 201 knows if the parsing attempt was successful or not. It does not appear however that Octostache has a means of communicating this information to Calamari otherwise I'd just submit a PR.

The result of `Template.End().TryParse(template)` provides excellent direction as to what's wrong with the template file.

Given a sample file:
```
var1: #{variables.value1}
var2: #{variables.value2
var3: #{variables.value3}
```

The parsing attempt returns:
```
{Parsing failure: unexpected '#'; expected end of input (Line 2, Column 7); recently consumed: e1}
var2: }
    Expectations: {string[1]}
    Message: "unexpected '#'"
    Remainder: {Line 2, Column 7}
    Value: '((Sprache.Result<Octostache.Templates.TemplateToken[]>)(Template.End().TryParse(template))).Value' threw an exception of type 'System.InvalidOperationException'
    WasSuccessful: false
```

This information in the log would have directed me toward the problem.

I suggest an enhancement like this:

```csharp
        public static bool TryParseTemplate(string template, out Template result, out string error)
        {
            var cached = Cache.Get(template) as Template;
            if (cached == null)
            {
                var tokens = Template.End().TryParse(template);
                if (tokens.WasSuccessful)
                {
                    result = new Template(tokens.Value);
                    error = null;
                    cached = new Template(Template.End().Parse(template));
                    Cache.Set(template, cached, new CacheItemPolicy() { SlidingExpiration = TimeSpan.FromMinutes(10) });
                    return true;
                }
                else
                {
                    LoggingFramework.Log(template.ParsingFailureMessage);
                }
                result = null;
                error = tokens.ToString();
                return false;
            }

            error = null;
            result = cached;
            return true;
        }
```

**Comment by crmckenzie** [comment]
As a followup, it looks like Calamari has it's own logging framework. Perhaps the solution here is to extract it into its own library and share it between the Calamari & Octostache.

**Comment by zentron** [comment]
Release Note: Log when variable substitution fails in custom scripts or file substitution during deployment.
