### ISSUE TITLE
Consider retrying the final DeploymentPlan persistence step

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2109]
A deployment can completely succeed, but a SQL Timeout in `DeploymentPlanService.Persist()` leaves the deployment in a failed state that cannot be rectified by the user.

It would make sense if the `DeploymentPlanService.Persist()` and `DeploymentPlanService.Cleanup()` methods were retried since they would be idempotent.

Source: http://help.octopusdeploy.com/discussions/problems/41421-error-while-executing-sql-command-timeout-expired

**Comment by zentron** [comment]
Release Note: DeploymentPlan persistence steps will now retry with the same process as existing SQL selects
