### ISSUE TITLE
Wrong link in Calamari upgrade message

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2111]
![upgradecalamari](https://cloud.githubusercontent.com/assets/6180562/10884022/76e6af72-8154-11e5-94cd-c9d27c3b15b5.jpg)

Points to `http://[OctopusDeploy]/environments` but should be `http://[OctopusDeploy]/app#/environments`

**Comment by alfhenrik** [comment]
Fixed in https://github.com/OctopusDeploy/OctopusDeploy/commit/881258745dc3c07c64ab6cf91608ceba99a4f7ca

**Comment by alfhenrik** [comment]
Release note: Link to environments page in out-dated Calamari message on deployment creation page is now correct.
