### ISSUE TITLE
Octopus incorrectly claims Calamari is not up to date in Tentacles

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2114]
Octopus Version: 3.2.0

The following message still shows up even though all Tentacles have been upgraded to latest Calamari from the Environments page.

![calamari](https://cloud.githubusercontent.com/assets/6180562/10949200/78fd6342-8310-11e5-90d4-63cba70b613d.JPG)

Tentacle is running latest version of Calamari (verified on the machine), so this seems to be only an issue with how we are checking this information in this particular page.

![healthcheck](https://cloud.githubusercontent.com/assets/6180562/10950460/80b87594-8316-11e5-8eb7-39a5906a48a1.JPG)

Source: http://help.octopusdeploy.com/discussions/problems/41703

**Comment by PaulStovell** [comment]
This will be fixed next release.
