### ISSUE TITLE
Upgrading 32-bit Tentacle from 32-bit Server installs 64-bit Tentacle

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2117]
Replicated locally, running Windows Server 2012 R2 x64 with version 3.1.7 x86 Server/Tentacle. Upgraded server to 3.2.0 x86 and ran Tentacle upgrade which installed x64 Tentacle

Source: https://secure.helpscout.net/conversation/136315708/2854/

**Comment by praniga** [comment]
Hi Hendrik

Thanks for fixing this, so what version has this fix. We are on 3.1.4 and next download will be a 64bit one as our servers are 64bit.

Thanks
Praveen Raniga
Test Environment Specialist | Central Technology Services | Technology & Innovation | ASB
09 414 8273 direct | 90273 extension | praveen.raniga@asb.co.nz<mailto:praveen.raniga@asb.co.nz> | asb.co.nz
[Email signature - bank that backs the All Blacks]

**Comment by alfhenrik** [comment]
Hi @praniga,

This will be released as part of 3.2.4 which we're planning on pushing out today.

Thank you and kind regards,
Henrik

**Comment by alfhenrik** [comment]
Release note: Prevent installing 32-bit Tentacle on 64-bit OS and update Windows Service executable path to prevent issues when upgrading 32-bit Tentacles on 64-bit OSs
