### ISSUE TITLE
Inserting a variable using the `Variable Selector` in scripts don't persist

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2118]
Reproduced in `3.2.0` and `3.1.4`, so it's not a bug introduced as part `3.2.0`.

![scriptvariableselector](https://github-cloud.s3.amazonaws.com/assets%2F1035315%2F10957425%2Feefc80e2-83af-11e5-8343-b798c857b8da.gif)

Source: https://secure.helpscout.net/conversation/136112400/2832/

**Comment by Dalmirog** [comment]
#1974 Duplicate?
