### ISSUE TITLE
Octo.exe PathTooLongException

### ISSUE THREAD

**Issue by georgiosd** [OctopusDeploy/Issues#2119]
Please see https://github.com/mono/nuget/pull/5

**Comment by zentron** [comment]
Updated `Octo.exe` to refer back to official `Nuget.Core` library. Available in `3.2.2` release

**Comment by georgiosd** [comment]
Hi @zentron - does that fix the `PathTooLongException`? Not clear.

**Comment by zentron** [comment]
@georgiosd  as noted around the interwebs this is a limitation inside NuGet and not octopack itself.
There are some noted workarounds for getting windows to deal with these sorts of scenarios.
http://stackoverflow.com/questions/13318364/how-to-deploy-node-js-application-with-deep-node-modules-structure-on-windows
http://help.octopusdeploy.com/discussions/problems/2667-deployment-error-the-specified-path-file-name-or-both-are-too-long
Hopefully using the flatter structure of npm 3 will help alleviate these issues somewhat.
I noticed that you added this issue to NuGet themselves
https://github.com/NuGet/Home/issues/1685
I have changed the project reference to the official `Nuget.Core` repo so perhaps if they make a fix on their side we will be able to update and get this fix as soon as its available. In the meantime I'm afraid there is not quick fix that we can make in this case.

**Comment by georgiosd** [comment]
Hi Rob, I have posted a fix as a pull request to the original Mono.Nuget.Core that you were referencing. I am sure you can apply to the v3 tree too if you so wish. 

I did resolve the issues by packing that built tar.gz but my OCD made me very unhappy. Up to you to follow up with the Nuget team or close...

**Comment by zentron** [comment]
Unfortunately @georgiosd  the tar.gz is our current recommended way to get around this problem until it is fixed by the NuGet team.
