### ISSUE TITLE
Bootstrap.Octopus.Features.WindowsService_BeforePostDeploy.ps1 script fails if script is in a folder that contains '$'

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2124]
We're dot-sourcing the target script file with `"` which causes PS to attempt to evaluate part of the path as a PS variable.

We should look at changing the dot-sourcing to use `'` instead so PS doesn't do any variable expansion.

Other bootstrap scripts may be affected as well.

Source: http://help.octopusdeploy.com/discussions/problems/41947

**Comment by michaelnoonan** [comment]
Release Note: Fixed an issue in Calamari that prevented using a `CustomInstallationDirectory` with `$` in the path.
