### ISSUE TITLE
Add tooltip for Tentacle style after it was configured

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2127]
A couple of users have asked `Why can't I modify the 'style' dropdown on the Tentacle to change its communication style?`, which leads to the explanation that they have to create a new instance.

![tentacle](https://cloud.githubusercontent.com/assets/6180562/11041422/7d41c6bc-86f0-11e5-9f31-108c30fc6433.JPG)

Along with the :no_entry_sign: icon, we could add a tooltip saying something like `"This value cannot be modified once the Tentacle was added. To change communication styles, delete this Tentacle and then create a new one with the desired communication style"`.

**Comment by michaelnoonan** [comment]
Release Note: Added reason why the Machine Communication Style cannot be updated after the Machine has been added.
