### ISSUE TITLE
Error when saving project that has ARC enabled

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2128]
When trying to add a variable set or changing project settings, the following error occurs:

```
{
  "ErrorMessage": "There was a problem with your request.",
  "Errors": [
    "A channel ID must be provided to enable automatic release creation."
  ]
}
```
The projects were created in 3.0 and went through the normal upgrade path to 3.2.

Work-around: disable ARC, modify and save project, re-enable ARC.

Source: http://help.octopusdeploy.com/discussions/problems/41801

**Comment by zentron** [comment]
Another Source: http://help.octopusdeploy.com/discussions/problems/42000

**Comment by robpearson** [comment]
Release Note: Projects with automatic release creation (ARC) enabled that do not make use of channels can now be saved successfully.
