### ISSUE TITLE
Changing from IE Proxy with credentials to without credentials does not appear to save

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2130]
If I have proxy credentials saved in the octopus service manager
![image](https://cloud.githubusercontent.com/assets/1830666/11051075/a45a24ea-8797-11e5-8bc4-d5e781459507.png)
And then I change to just `Use the proxy server configured in IE` (without credentials), it appears to save. Logs indeed show

> Use IE proxy: True

as opposed to 

>Use IE proxy: True
Proxy username: Blah
Proxy password set

when providing credentials, however it seems that since the username\password details aren't cleared the proxy details appear to still think it should use credentials.

Source: http://help.octopusdeploy.com/discussions/problems/42010

**Comment by michaelnoonan** [comment]
Release Note: Proxy configuration for Octopus Server and Tentacle now clears the username/password appropriately when selecting `Do not use a proxy` or `Use the proxy server configured in Internet Explorer`.
