### ISSUE TITLE
Once user tries to save variables with Unauthorised scoping, they must refresh the page to save again

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2131]
If a user only has `Environment Viewer` role for a specific environment, then tries to create a variable scoped to that environment they get the `You do not have permission...` error as expected.

If however they then proceed to delete that variable and add another, unscoped variable, the error does not go away. The user must refresh the page to be able to save again.

Source: http://help.octopusdeploy.com/discussions/problems/42010

**Comment by robpearson** [comment]
Release Note: Variable Editor saves new items correctly after deleting unsaved changes.
