### ISSUE TITLE
Task log when deploying Azure Web App lists all targets in environment

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2132]
When deploying an Azure Web App, the task log shows all targets in that environment including those that aren't even azure targets.
![image](https://cloud.githubusercontent.com/assets/1830666/11051456/28d2fd5c-879b-11e5-85fc-ffabd4944ab7.png)

**Comment by mjrichardson** [comment]
The "Server packages" block is always empty. But at least non-applicable targets are no longer displayed.
