### ISSUE TITLE
Tentacle.exe register-with fails to register polling Tentacle

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2134]
```
-------------------------------------------------------------------------------
Full error details are available in the log files.
At: C:\Path\To\Octopus\Logs
===============================================================================
The service listening on https://localhost:10943/ does not appear to be an Octopus server. The response was: 
```

Source: http://help.octopusdeploy.com/discussions/problems/41808

**Comment by alfhenrik** [comment]
In [`RegisterMachineCommand.cs#L149`](https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Tentacle/Commands/RegisterMachineCommand.cs#L149)

```
try
{
    using (var resp = req.GetResponse())
    using (var rs = resp.GetResponseStream())
    using (var reader = new StreamReader(rs))
    {
        var content = reader.ReadToEnd();
        throw new Exception("The service listening on " + serverAddress + " does not appear to be an Octopus server. The response was: " + content); // <-- This causes the register-with command to fail
    }
}
```

**Comment by Nepomuceno** [comment]
This is actually stoping me to deploy any new machine and this version just FUCKED my whole environment. THX guys!!

**Comment by alfhenrik** [comment]
There is a workaround for this issue until we get a fix released, install Tentacle version [3.1.7](https://octopus.com/downloads/3.1.7) and the `register-with` command will work fine.

**Comment by crcasadonte** [comment]
This is also creating potential major issues for us. Its strange to me that registering a polling tentacle was not part of QA before the tentacle was pushed to production.

**Comment by alfhenrik** [comment]
Yes, we made a mistake in the latest release and this bug snuck through our safety net and for that we are sorry.

We are making this bug a priority to get a fix out as soon as possible and will be adding additional tests to ensure this does not happen again.

Our sincere apologies for the inconvenience caused by this bug!

**Comment by alfhenrik** [comment]
Release note: `Tentacle.exe register-with` handshake request no longer throws an exception if we successfully connect to Octopus

**Comment by crcasadonte** [comment]
Awesome thanks!
