### ISSUE TITLE
Show calamari version in health check

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2136]
There's no intuitive way to get the Tentacle's Calamari version from the Web portal and the Health check just says "you have the latest". We are already getting the version number to resolve if the user has the latest version, so we could also show it on the health check:

![calamari](https://cloud.githubusercontent.com/assets/6180562/11063211/ceb85cc4-8793-11e5-88bb-63334229b5cb.JPG)

Would have come in handy when troubleshooting #2114

**Comment by Dalmirog** [comment]
`There's no intuitive way to get the Tentacle's Calamari version from the Web portal` that's half wrong, you can get this info from a deployment log. But we are showing the Tentacle version on the Health Check and also getting the Calamari number. It feels right to show it there as well :)

**Comment by zentron** [comment]
It might be nice if we could also show this information on the machine connectivity page where it currently just displays when the last health check took place
