### ISSUE TITLE
Warn if non-printable characters entered in variables

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#2140]
Often non-printable characters are inadvertently copied into variable values or names.
A specific regular culprit is the left-to-right mark that is inadvertently copied with certificate thumbprints.
Although determining which characters are non-printable is not an exact science, for an initial stab, we will show a warning when saving a variable where the name or value contains a character that is a member of the following unicode category categories:

- Control (excluding carriage-return and line-feed characters, as we already display a mark for these)
- Format
- LineSeparator
- ParagraphSeparator

**Comment by egorpavlikhin** [comment]
This is annoying when you are working with JSON configs. Every other variable comes with a lengthy warning. Please add an option to disable this check.
