### ISSUE TITLE
Deleting an environment does not remove ID from step scoped to it.

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2141]
If there was a step scoped to an Environment (i.e `Environments-40`), after deleting the Environment, the scope to it can no longer be seen on the step on the Web UI, but the Environment ID is still on the scope of the step in the deployment process JSON.

Since from the UI the step seems scoped to no Environments, the expected behavoir is that the step will be executed when deploying to any environment. But this doesn't happen, as the step will only execute when deploying to the environment with ID `Environments-40`, which no longer exists.

```
"Actions": [
        {
          "Id": "f3d799aa-91aa-4308-a2dd-08654dda7ff0",
          "Name": "OnlyInDev2",
          "ActionType": "Octopus.Script",
          "Environments": [
            "Environments-40"
          ],
          "Channels": [],
          "Properties": {
            "Octopus.Action.Script.Syntax": "PowerShell",
            "Octopus.Action.Script.ScriptBody": "\"Hi from dev2\""
          },
          "SensitiveProperties": {}
        }
```

**Comment by michaelnoonan** [comment]
There are two problems here:
1. We should be removing the Environment from Steps/Actions, and then removing the Step/Action if it was ONLY scoped to the deleted Environment. This wasn't working. FIXED
2. Due to this bug we're going to have corrupted data - we'll auto-heal this whenever the Deployment Process is saved. FIXED

**Comment by michaelnoonan** [comment]
Release Note: When deleting an Environment or Channel they will be correctly removed from the `Limited to Environments` and `Limited to Channels` of relevant Steps in Deployment Processes.
