### ISSUE TITLE
Exporting Tentacle cert without a default (or specified instance) fails

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#2143]
http://docs.octopusdeploy.com/display/OD/Export+and+import+Tentacle+certificates+without+a+profile

This won't work without a default or specific instance.

See http://help.octopusdeploy.com/discussions/problems/42144

**Comment by robpearson** [comment]
Release Note: Allowed Tentacle certificate export to file to work without an instance specified.

**Comment by bigbam505** [comment]
Thanks! That was a fast turn around :smiley:
