### ISSUE TITLE
When upgrading Tentacles via the Environments tab, polling-tentacles hang

### ISSUE THREAD

**Issue by mjrichardson** [OctopusDeploy/Issues#2145]
As reported here: http://help.octopusdeploy.com/discussions/problems/42129-upgrading-polling-tentacles-works-but-task-fails
and here: http://help.octopusdeploy.com/discussions/problems/42072-tentacle-upgrade-hangs

**Comment by alfhenrik** [comment]
Release note: Upgrading polling Tentacles from UI no longer hangs the upgrade task.
