### ISSUE TITLE
Backwards incompatable bug introduced in 3.2.3 surrounding IIS deployment of certificates

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2151]
If the user upgrades to `3.2.3` and performs an IIS deployment with certificates for the first time using a deployment plan generated in a previous version, the new binding format causes an error to be thrown.

Temporary quick work around is to go to the project step and edit the binding information to force it to save with the new format.

**Comment by michaelnoonan** [comment]
Release Note: Fixed a backwards-compatibility bug affecting IIS HTTPS bindings and their Certificates.
