### ISSUE TITLE
Configuration Transforms Convention fails on transform definition using '*' and '.config' extension

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2154]
`*.foo.config => *.config` fails.
`*.foo.xml => *.xml` works.

Source: http://help.octopusdeploy.com/discussions/problems/42385

**Comment by tothegills** [comment]
Finding it hard to reproduce, the config definitions work fine for me.
Added some tests to Calamari and fixed a minor bug but would not result in the reported failure.

**Comment by tothegills** [comment]
Fixed by OctopusDeploy/Issues#2211
