### ISSUE TITLE
Artifacts not being imported from 2.6 to 3.x

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2157]
See https://secure.helpscout.net/conversation/138815780/3067/?folderId=571723

**Comment by tothegills** [comment]
Release note: Artifacts are correctly imported from 2.6 backups

**Comment by dcbyers** [comment]
I do not have access to helpscout.  Can you provide information on which artifacts were failing to import correctly from 2.6 and what would be the symptoms?  I migrated from 2.6 this past weekend and want to understand where this one might be affecting me.
