### ISSUE TITLE
Deleting a Release doesn't cascade to DeploymentProcess/VariableSet snapshots

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2159]
When we delete a `Release` (manual or retention) we should considerately cascade delete `DeploymentProcess` and `VariableSet` snapshots.

NOTE: `DeploymentProcess` and `VariableSet` snapshots are re-used/shared between Releases, so we'd need to be careful.

We should also consider cleaning up orphaned snapshots because of the negative flow-on effects of leaving these documents lying around.

Source: http://help.octopusdeploy.com/discussions/problems/41444-user-has-builtinfeedpush-but-octopus-says-it-doesnt

**Comment by zentron** [comment]
Release Note: Deleting a release now removes any linked variable or deployment process snapshots so long as they aren't shared by another release
