### ISSUE TITLE
Large deployments with lots of logging can stall

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#2162]
Deployments with lots of steps and custom logging can stall or take a long time to finish.

https://secure.helpscout.net/conversation/139853620/3135/?folderId=563339

**Comment by DamianMac** [comment]
Also https://secure.helpscout.net/conversation/138737313/3058/?folderId=557082

**Comment by michaelnoonan** [comment]
I've had ~5 customers who had left the variable debug logging turned on which was the cause of their large logs, and the 1-2 minute delay between steps.

**Comment by tothegills** [comment]
Release note: Eliminated performance impact of reading and writing large task log files
