### ISSUE TITLE
Failure in one node of a parallel deployment throws a confusing exception

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#2163]
See this ticket http://help.octopusdeploy.com/discussions/problems/42101-intermittent-deploy-failures-are-increasing

The deployment had a custom PowerShell script which was failing on one node, fails the deployment, but the users see an exception about Autofac lifetime scopes (the deployment had died and context was torn down but other nodes were returning messages).

**Comment by zentron** [comment]
User has indicated this is no longer a problem
