### ISSUE TITLE
 Octopus Tentacle for CoreCLR and Windows10 IoT

### ISSUE THREAD

**Issue by grahamehorner** [OctopusDeploy/Issues#2164]
Please consider creating an implementation of the Octopus Tentacle for CoreCLR and/or Windows10 IoT

**Comment by michaelnoonan** [comment]
Hi @graemehorner, thanks for the suggestion! I've [moved this to UserVoice](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/10783866-port-octopus-to-net-core) which is the most appropriate place. We use our backlog to keep a track of work we've committed to doing in the next two months.

https://octopus.com/company/roadmap/why-was-this-closed
