### ISSUE TITLE
Cannot fix one invalid Step if there is another invalid Step in the DeplomentProcess

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2166]
If you end up in a situation where there are 2+ invalid steps in a process, you can't fix the process through the UI, and instead have to call the API directly with the JSON, or fix the database.

Actual scenario: We recently started preventing `[` and `]` from being used in Step Names to prevent Output Variables from silently failing. However there are lots of Steps in the wild with these now-invalid characters and you cannot update the Deployment Process because the other invalid steps will fail the validation as a whole.

A longer-term solution for this is to implement a `PATCH` operation for `DeploymentProcess` something like:
```
PATCH /deploymentprocesses/12345
[
{
  "op": "replace",
  "path": "/steps/a9d469de-0051-41a3-9292-415044e45516",
  "value": {
    "Id": "a9d469de-0051-41a3-9292-415044e45516",
    "Name": "Pause for approval",
      "Condition": "Success",
      "StartTrigger": "StartAfterPrevious",
      "RequiresPackagesToBeAcquired": false,
      "Actions": [
        {
          "Id": "9ab82857-5cdf-4875-ae9b-c8c9887f6c69",
          "Name": "Pause for approval",
          "ActionType": "Octopus.Manual",
          "Environments": [
            "Environments-2"
          ],
          "Channels": [],
          "Properties": {
            "Octopus.Action.Manual.Instructions": "Do you approve this deployment?"
          }
        }
      ],
      "Properties": {}
    }
  }
}
]
```

This would allow the Step editor to save just the one Step into the Deployment Process without being affected by other parts of the document.

Relates to OctopusDeploy/Issues#1882

**Comment by ErikxNilsson** [comment]
Looks like it will fix our problem, thanks.

**Comment by zentron** [comment]
The work for this ticket seems overkill for fixing something that shouldn't (in future) exist in the first place. In consideration with other work that is pending this ticket has been de-prioritized.
The recommended work around at the moment is as mentioned in the linked ticket is to manually update the step name in SQL to remove the `[` and `]` invalid characters.

https://octopus.com/company/roadmap/why-was-this-closed

**Comment by perosb** [comment]
Can you please provide a proper fix for this?
You cannot expect people manually updating sql database when you change things.

**Comment by zentron** [comment]
@perosb, after some discussion we agree that it probably is better to put something in to make it backwards compatible with existing data that users may have. 
This may be by using the `PATCH` approach suggested above or by allowing existing steps to have this character but blocking new steps.
This ticket will go back onto our backlog to be prioritized as necessary.

**Comment by tothegills** [comment]
Don't do as a database upgrade script as we can't be sure the effects changing step and action names will have on the rest of the deployment process.

**Comment by zentron** [comment]
As part of https://github.com/OctopusDeploy/Issues/issues/2206 I will be looking at adding `PATCH` support. Once this is available this ticket can be readdressed using the `PATCH` approach outlined above

**Comment by MJRichardson** [comment]
It seems the simplest fix here is to only validate *new* step names, and let existing steps pass the new validation.

I'm moving this back into ready, as it is nasty and has no nice work-around.

**Comment by zentron** [comment]
Release Note: Change step rule to only check for `[]` characters if the step is new or the name has changed.
