### ISSUE TITLE
Account Settings - missing length validation

### ISSUE THREAD

**Issue by dazinator** [OctopusDeploy/Issues#2179]
I went to add a new account:

![image](https://cloud.githubusercontent.com/assets/3176632/11371237/619ce2b8-92bf-11e5-9276-c116ed53ed6b.png)

When clicking save:

![image](https://cloud.githubusercontent.com/assets/3176632/11371209/4551a742-92bf-11e5-8de0-94f56a4133fd.png)

I originally thought it was the description field that I had entered too much within, but it turns out it was the Name field, as shortening it resolved the issue. 

Would improve usability if validation could be added to the UI fields so the user knows they have entered too much text.

**Comment by zentron** [comment]
Release Note: Extend the `Account` and `Feed` table `Id` columns to allow for the fact that they are made by combining the type with the `Name`.
