### ISSUE TITLE
Knowledge base / FAQ pages

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2181]
As part of the support embetterment project to reduce the amount of tickets regarding known issues and frequently asked questions.

**Comment by alfhenrik** [comment]
New pages in the Octopus Deploy KB space in Confluence
- [Common Problems](http://docs.octopusdeploy.com/display/ODKB/Common+Problems)
- [Known Issues](http://docs.octopusdeploy.com/display/ODKB/Known+Issues)

These are living documents and needs to be updated when new known issues are found or a new common problem emerges

**Comment by antonvk** [comment]
Awesome! hopefully this will be kept up todate so we can check for know issues/common problems prior releases into production
