### ISSUE TITLE
Login cookie does not distinguish full domain path 

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2182]
Reported by avanade while running through test scenarios.
When logged into one instance octopus1.domain.com then a second octopus1.domain.com/test
The second login will logout the first.
Same browser. Needs to work for full domain if possible to allow for multiple instances.

Cannot confirm if it was 2.5.13, 2.6 or 3.1.7 - also have not tried to replicate.

**Comment by vanessalove** [comment]
worth noting with the new model we are pushing them towards this change will help with successful adoption as some team members are in multiple teams.

**Comment by tothegills** [comment]
Release note: Support logging in to multiple Octopus Server instances at the same time
