### ISSUE TITLE
Script step embedded in a NuGet package

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2189]
When creating a script step in Octopus, you can paste a script into a big textarea. We're going to extend this to support choosing a NuGet package that will contain the script, and entering the name of the script within the package to invoke. This step will be able to run on the Octopus server, as well as on Tentacles/SSH machines/etc. 

This would support scenarios like:

 - Deploy a database migration - the migration scripts can be in a package, with a PowerShell script that calls them
 - Deploy a reporting services project from the Octopus server
 - Deploy an Azure RM template
 - Deploy an AWS CloudFormation template
 - Regular PowerShell/ScriptCS steps that need additional files to operate

It would be similar to the standard NuGet package step, but bypasses all the conventions and "installation" of the package. We simply extract, execute the entry point script, then delete the folder.

**Comment by matt-richardson** [comment]
This sounds very interesting. You could potentially also extend this to step templates, so that these can be stored in source control, packaged and published to Octopus.
