### ISSUE TITLE
function Invoke-Health isn`t work in windows boxes with NFS share mounted from Linux Boxes Servers

### ISSUE THREAD

**Issue by alexandresavicki** [OctopusDeploy/Issues#2190]
@e are struggling to setup the new Octopus Agent 3.0 because the script in the function Invoke-HealthCheck is not working properly when it calls this command:

Get-WmiObject win32_logicaldisk | ? { ($_.DriveType -eq 3) -and ($_.FreeSpace -ne $null)} | % {

if($_.FreeSpace -lt $freeDiskSpaceThreshold) {

Write-Warning $("Drive {0} on {1} only has {2} available" -f $_.DeviceID, $hostName, $(Get-FileSizeString $_.FreeSpace))

} else {

Write-Host $("Drive {0} has {1} available" -f $_.DeviceID, $(Get-FileSizeString $_.FreeSpace))

}

}

We have a Windows Box using a NFS Share from a Linux Box, so as we know, we have to do some tricks to enable Windows to allow write in a share NFS Share from Linux:

There is a article explaining this trick:

http://www.ibmconnections.org/wordpress/index.php/2013/02/configure-windows-nfs-client-with-write-permissions/

I think the Class from WMI about disk files doesn`t work when we mount this nfs share, do you think that is there a way which we can fix this issue.

Thanks.

**Comment by zentron** [comment]
@alexandresavicki  this should go out in the next release. In future we prefer all issues to go through support first rather than creating a new GH issue.
In any case, thanks for the heads up with this issue.

**Comment by tothegills** [comment]
Release note: Health check fall back for machines that have mapped NFS drives
