### ISSUE TITLE
Pushing a package to Octopus root URL returns false successful message

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2194]
Only seems to happen with root URL. It would be good if we could return an error to the nuget call.

![nugetpush](https://cloud.githubusercontent.com/assets/6180562/11459268/6dc02ff0-96b1-11e5-85cc-9bbb10d57302.jpg)

**Comment by zentron** [comment]
Release Note: Only accept HTTP verb `GET` requests to static `/app` route. Other methods will return `405 - Method Not Allowed`
