### ISSUE TITLE
Support -name parameter for new_octopusartefact on ssh targets

### ISSUE THREAD

**Issue by graemechristie** [OctopusDeploy/Issues#2198]
When using new-octopusartefact on ssh targets, the artefact is added with the full path as path of the filename. e.g.

![image](https://cloud.githubusercontent.com/assets/1361894/11491756/d07b2176-981f-11e5-8124-e435cfd33f23.png)

cd-ing into the folder and then adding the artefact without a path, does not work as octopus cannot locate the file to scp it to the server if the filename is not an absolute path (or presumably relative path from the working directory).

As it stands, if a user tries to download an artefact file, the file name is the full path, with slashes converted to hyphens. This is not ideal for us. We build IOS IPA's with octopus, and often have various users and devs collect IPA's from the octo portal and distribute them. The filename is a pretty integral part of allowing users to identify the environment and configuration of the IPA. Having the extra noise in the filename is not ideal, and renaming every artefact on download is also not ideal.

Support for the -Name parameter, as per the powershell functionality would be ideal for us.

I tried using --name and -name parameters to this command but they seemed to be interpreted as an artefact path. I am assuming the name parameter is not currently supported for new_octopusartefact on ssh targets. Additionally, I was not able to find any documentation for the ssh targets, other than some blog posts around the Octopus 3.0 release.

**Comment by graemechristie** [comment]
Note that I have also tried copying the artefacts to the working directory for the step, and then using `new_octopusartefact(filename.ipa)` or `new_octopusartefact(./filename.ipa)`. Both result in "Collecting filename.ipa as an artefact .... No such file" messages.

**Comment by zentron** [comment]
While the name parameter was getting passed from the bash script, it appears to have not been used when stored in the artifact store. I have put in a fix for this which should go out in the next `3.2.11` release.

Thanks for the heads up on the missing documentation. I have extended http://docs.octopusdeploy.com/display/OD/Artifacts to also include a mention of the bash format for this command.

Once the new release is available in the next few days give it a go and let us know if you encounter any further issues around artifacts & ssh.

**Comment by michaelnoonan** [comment]
ReleaseNote: Now supports `-name` parameter for `new_octopusartefact` on ssh targets
