### ISSUE TITLE
EnableMSDeployAppOffline support for Azure Web Apps

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2201]
It would be nice if we could support this feature out of the box: https://msdn.microsoft.com/en-us/library/ee942158.aspx#app_offline

Source: http://help.octopusdeploy.com/discussions/questions/6608

**Comment by zentron** [comment]
I'm not 100% certain but I don't think that is _is_ possible to add out of the box support for this in the azure deployment. More investigation is required.
