### ISSUE TITLE
Offline deployment fails if binding IP adress is empty

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2203]
Given the following binding config
![binding](https://cloud.githubusercontent.com/assets/6180562/11510164/07fc5446-9841-11e5-95c6-87561172d56e.JPG)

Deploying to a listening Tentacle creates a binding for *:83
![binding2](https://cloud.githubusercontent.com/assets/6180562/11510225/6876c018-9841-11e5-9682-67a630f1e906.JPG)

From an Offline deployment, it returns an object reference exception, forcing the user to manually put "*" on the IP field of the deployment step to fix the issue.

**Comment by tothegills** [comment]
Relates to OctopusDeploy/Issues#2221
