### ISSUE TITLE
Adding new variable to project with limited permissions to scopes deletes variables not in scope

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2206]
Repro:

- Create a new project
- Add two variables, VarDev & VarProd, scoped to dev and prod environments respectively
- As a DEV user, view the variables-- as expected we only see the VarDev variable
- As a DEV user, try to add VarNew variable-- as expected we get permission denied
- As an ADMIN user, grant the DEV user permissions to edit variables
- As a DEV user, try to save new variables again-- as expected we are now allowed.

Expected result: VarDev, VarProd, and VarNew variables should be present.

Actual result: VarDev and VarNew are present, while VarProd has been "deleted"

Source: http://help.octopusdeploy.com/discussions/problems/42649

**Comment by robpearson** [comment]
Failed to reproduce initially but the customer has provided more detail.  I'd suggest trying again.

**Comment by zentron** [comment]
https://github.com/OctopusDeploy/OctopusDeploy/commit/1d3ebafbae2be2dcf3f3fd2ad482cec342464963
If the user's available environments changes while they are editing the variable set they will be prompted to reload the page. This is the same existing mechanism that is used currently if someone else has changed the variable set while the user makes changes.

**Comment by zentron** [comment]
Release Note: Updating project variables while the user's environment permissions have changed forces user to reload. This blocks a bug causing variables to be removed.
