### ISSUE TITLE
InstallationDirectoryPath variable of a previous step is not available in Offline steps

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2208]
The variable `[Octopus.Action[previous step name].Output.Package.InstallationDirectoryPath]` is not available in offline deployments in subsequent steps. 

If a step needs to know the installation path of a previous NuGet deploy step, the only current workaround is to use the "Custom install dir" feature and use the variable `Octopus.Action[previous step name].Package.CustomInstallationDirectory`.

A user found this error when trying to use the [SQL Deploy - Dacpack step template](https://library.octopusdeploy.com/#!/step-template/actiontemplate-sql-deploy-dacpac) which relies on the `InstallDirectoryPath` variable of a previous step:

```
# Get arguments
$dacpacPackageStepName = Validate-Argument 'DACPAC Package Step Name' $OctopusParameters['DacpacPackageStepName']
[...]

# Set .NET CurrentDirectory to package installation path
$installDirPathKey = 'Octopus.Action[{0}].Output.Package.InstallationDirectoryPath' -f $dacpacPackageStepName
$installDirPath = $OctopusParameters[$installDirPathKey]
```

This variable is available as expected in regular non-offline deployments.

**Comment by vanessalove** [comment]
This is known. You cannot pass variables between steps in offline deployments. It is still undecided if this will be supported

**Comment by michaelnoonan** [comment]
Adding to what @vanessalove said, there is also a User Voice suggestion: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/9196032-output-variables-for-offline-drops
