### ISSUE TITLE
OctoPack: Web project with linked web.config file not being treated as a web application (potential solution attached)

### ISSUE THREAD

**Issue by danjham** [OctopusDeploy/Issues#2210]
Looking at CreateOctoPackPackage.cs it determines if a project is a web project by the existence of a web.config file.

I have a situation where we have a web.config file that is included in the project by a link

csproj file snippet:
&lt;Content Include="..\..\Global\Cirrus.Web\Web.config"&gt;
      &lt;Link&gt;Web.config&lt;//Link&gt;
    &lt;/Content&gt;

CreateOctoPackPackage class snippet:
private bool IsWebApplication()
    {
      return this.fileSystem.FileExists("web.config");
    }

I suggest this should look in the ContentFiles collection for a web.config file.

Here is the implementation I have working on my local build

 private bool IsWebApplication()
        {
            return this.ContentFiles.Any(f => Path.GetFileName(f.ItemSpec).EndsWith("web.config", StringComparison.OrdinalIgnoreCase));
        }

I have attached the updated CreateOctoPackPackage.cs file

Thanks
Dan.

**Comment by robpearson** [comment]
Actioned in the following PR. 
https://github.com/OctopusDeploy/OctoPack/pull/75
