### ISSUE TITLE
Preserve Halibut configuration settings between upgrades

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2212]
When upgrading Octopus server, `Octopus.Server.exe.config` is overwritten, and any Halibut settings are lost.

e.g. 
`<add key="Halibut.TcpClientPooledConnectionTimeout" value="00:00:00"/>`

It would be much nicer to preserve these.

**Comment by PaulStovell** [comment]
Preserving is hard, is this just related to the few changes we got people to make to test some bandwidth issues? Could we just make those settings the default?

**Comment by zentron** [comment]
I'm with Paul on this one. Considering some new configs might be added and some might be removed between releases, it could be overly complex to preserve user-added sections. Are there some optimal defaults that you would suggest it should be?

**Comment by tothegills** [comment]
Refer to OctopusDeploy/Issues#1977 for more info and values that have been tried

**Comment by zentron** [comment]
Updating Halibut itself with new defaults
