### ISSUE TITLE
If you have an environment scoped to a team - deploying to select machines is broken

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2215]
Suspect that with this change: https://github.com/OctopusDeploy/Issues/issues/2010 if you have a team with an environment scoped you cannot then select a specific set of machines to deploy to.

Source: https://secure.helpscout.net/conversation/144090055/3407/?folderId=557083

**Comment by vanessalove** [comment]
Was def working in 3.1.4

**Comment by robpearson** [comment]
Release Note: Members of teams restricted to specific environments can deploy to specific machines within those environments
