### ISSUE TITLE
Octopus.Step.Status.Error is too generic

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2216]
The variable `Octopus.Step.Status.Error` seems to be "One or more child activities failed." when a step or child action fails.  Consequently `Octopus.Deployment.Error` is the same.

It would be nice to know at the least the error code so subsequent steps could take action depending on the outcome.

**Comment by tothegills** [comment]
See: http://help.octopusdeploy.com/discussions/problems/43141

**Comment by zentron** [comment]
Release Note: Add individual step failure errors if multiple child steps exist within an action
