### ISSUE TITLE
Variables pop-up window almost always shows up off screen

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2222]
Octopus version: 3.2.9

The behavior is a bit erratic. It would be good if it could always show up 100% on the screen and aligned to the right.

Customer's screen (firefox)
![od_1](https://cloud.githubusercontent.com/assets/6180562/11697587/fd5014de-9e98-11e5-8bd9-f98fc39d73b4.png)

My screen (chrome)
![variablepopup](https://cloud.githubusercontent.com/assets/6180562/11697580/f40b4ea2-9e98-11e5-8331-b72e18b4c6c5.JPG)

**Comment by alfhenrik** [comment]
Release note: Fix positioning of variables pop-up so it doesn't extend outside the page width
