### ISSUE TITLE
Can't add variables from pop-up window on Powershell Script steps

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2225]
**Open variables Pop-up -> Select a variable -> It doesn't get added to the script editor**

I could only reproduce this on the Powershell Script steps. Other steps like Azure Powershell script, Custom Scripts in nuget package and at least other 5 random fields with the Variables pop-up are working as expected.

Noticed it on `3.2.9`. Couldn't repro in demo server which is running `3.2.6`.

**Comment by robpearson** [comment]
Release Note: Script Editor Variables Popup can insert variables again
