### ISSUE TITLE
Task that fails while being paused results in serialization error

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2226]
#### Repro Steps: ####
*  Create task with 2 steps.
* One step contains script step that is to execute against an offline tentacle (or anything that will cause it to fail)
* Another step is a manual intervention step
* Run both steps in parallel

![image](https://cloud.githubusercontent.com/assets/1830666/11734221/c2244e98-a000-11e5-877d-23e9241ce2e4.png)

When the manual intervention step completes first, it flags the task as paused and stores the step state in the DB. When the other step eventually fails, it then also stores the `ActivityTaskFailedException` in the step state in the DB.
This class has no default constructor so when the record is attempted to be read again out of the DB, an unhandled exception is thrown that bubbles out the the UI

![image](https://cloud.githubusercontent.com/assets/1830666/11734282/6d91131a-a001-11e5-95f4-4f469513a8a1.png)

![image](https://cloud.githubusercontent.com/assets/1830666/11734301/b3a6bdfa-a001-11e5-9126-ffff4d881850.png)

**Comment by robpearson** [comment]
Release Note: Deployments with parallel steps including one that fails and one manual intervention now execute without problems.
