### ISSUE TITLE
Username/Password variables of Application Pools persist after user changed Identity type

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2229]
Octopus Version: 3.2.10

1) Using "IIS web site and application pool" feature, configure the step to create an App Pool using a custom user/pass as Identity and save the step. Do not deploy.

2) Open the step again and change the Identity to something different. Save the step and deploy

3) During the deployment the variables `Octopus.Action.IISWebSite.ApplicationPoolUsername` and `Octopus.Action.IISWebSite.ApplicationPoolPassword` are still available. The expected behavior would be that after the user saved the step using a different Identity type, the user/pass variables are not longer available.

**Comment by zentron** [comment]
Release Note: IIS app pool credentials are cleared if the selected identity is not a custom user.
