### ISSUE TITLE
Automatic Release not created when package with older version is pushed to the repository

### ISSUE THREAD

**Issue by ajakuszyk** [OctopusDeploy/Issues#2232]
I have 2 projects which use the same Deploy NuGet package Step Template.
Both projects have 'Automatic Release Creation' - [x] Create a release when a package is pushed to the built-in NuGet repository option enabled.
When I push new version of NuGet package (e.g. 6.1.892.0) then release is automatically created.
If then I push package with lower version (e.g. 6.0.893.0, not existing in NuGet repository before) then the release is not created.

Audit log details (from newest to oldest):
- Package Sql.Server.Configuration version 6.0.893.0 was pushed to the builtin feed
- Package Sql.Server.Configuration version 6.1.892.0 was pushed to the builtin feed
- SqlServer.Configuration UK release 6.1.892.0 was automatically created because package Sql.Server.Configuration was pushed to the builtin feed
- SqlServer.Configuration DE release 6.1.892.0 was automatically created because package Sql.Server.Configuration was pushed to the builtin feed

**Comment by vanessalove** [comment]
This behavior is by design. We only create releases for latest versions.

**Comment by ajakuszyk** [comment]
This is a bit misleading - nothing in the UI says that package version have to be higher that the ones already existing in repository.
In this instance, the 'lower version' means that the package came from the different branch (6.0) - so 6.0 package is actually newer than 6.1, therefore 6.0 is 'the latest' build.
Would it be possible to have an option to override the 'design' behaviour?
