### ISSUE TITLE
Transformation doesn't work if config file is in a different subdir than the transform file

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2236]
The following `Additional transforms` expression doesn't work:

```
Web.Base.config => config\octopus\Web.Config
Web.Dev.config => config\octopus\Web.Config
```

The only way that a transform with the config file on a subdir can work, is if both transform and config file are on the same dir and the following is set as `Additional Transforms` expression

```
Web.Base.config => Web.Config
Web.Dev.config => Web.Config
```

Per #2032 we allow to have the transform on a subdir and the config file someplace else(*). It's logic that we also allow the config file to be on a different sudbir than the transform.

(*) because of this issue, "someplace else" can only be the package root at the moment.

**Comment by tothegills** [comment]
Release note: Allow config transforms when the target file is in a relative path: `Web.Base.config => config\Web.Config`
