### ISSUE TITLE
SSH endpoint health check error (OpenBSD)

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2241]
```
13:23:22   Verbose  |     Disposing SSH connection...
13:23:22   Fatal    |     Name cannot begin with the ''' character, hexadecimal value 0x27. Line 1, position 2.
13:23:22   Verbose  |     Name cannot begin with the ''' character, hexadecimal value 0x27. Line 1, position 2.
                    |     System.Xml.XmlException: Name cannot begin with the ''' character, hexadecimal value 0x27. Line 1, position 2.
```

further info in ticket with possible improvement suggested
Source: http://help.octopusdeploy.com/discussions/problems/43513

**Comment by zentron** [comment]
Tested on FreeBSD (available on AWS) and found small issue with execution script however not this particular bug. Will download OpenBSD to try replicate this issue

**Comment by zentron** [comment]
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/commit/2991f38257bac9835364abc81d3bdd20d8704bb5
