### ISSUE TITLE
Deployment using ssh is extremely slow

### ISSUE THREAD

**Issue by alvillain** [OctopusDeploy/Issues#2245]
Hello,

I'm using Octopus Deploy v. 3.2.11 and deploying very lightweight nuget package (12.6 KB) to Ubuntu machine.
The deployment process takes about 16 minutes. Deploy log is attached.
During deployment I see 100% of CPU usage by mono process.

<img width="585" alt="screen shot 2015-12-17 at 16 58 45" src="https://cloud.githubusercontent.com/assets/9715781/11872246/62b63fcc-a4e5-11e5-9ea8-99af41992892.png">

[ServerTasks-598.log.txt](https://github.com/OctopusDeploy/Issues/files/65500/ServerTasks-598.log.txt)

I'm quite sure, I don't have a network issue. 
I cannot believe that deploying such a small package can take 16 min. Any ideas why is it so slow?

**Comment by vanessalove** [comment]
This is a mono+Nuget bug. Please send this through to our support channels.
https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
