### ISSUE TITLE
Audit page, create lifecycle - link is bad

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2247]
On the audit page an event for creating a lifecycle doesn't link to the correct place, goes to not found. Replicated on demo.

Source: http://help.octopusdeploy.com/discussions/problems/43528

**Comment by alfhenrik** [comment]
Known issue: due to the way script modules are implemented (as a special library variable set), the audit events for those will go to the underlying library variable set.

**Comment by alfhenrik** [comment]
Release Note: Link to document in audit events for lifecycles, library variable sets and step templates are now correctly created.
