### ISSUE TITLE
Error in offline package with sensitive variables

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2253]
Error executing an offline package.  Workaround exists.  

Source: http://help.octopusdeploy.com/discussions/problems/43511

**Comment by MJRichardson** [comment]
I was unable to replicate this.  The sensitive variables mechanisms worked as they should when using a sensitive-field on a step template.
It may have been previously resolved.  Closing.

**Comment by expertcoding** [comment]
I think this bug still exists in 3.3.0 release of Octopus. 

Add a single quote in the "release notes" box when creating the release and the json becomes malformed for offline deployments.

**Comment by vanessalove** [comment]
Hi @expertcoding This issue was around sensitive variables such as passwords and masked fields.
Could you submit a ticket through our support channels with an example (screenshots and project process and output) of what you are seeing so if required we can raise another issue here.
Thanks!
