### ISSUE TITLE
Failed child step shows up in green

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2255]
![greenchildstep](https://cloud.githubusercontent.com/assets/6180562/11968161/01d575b8-a8e8-11e5-8041-53e6706372db.jpg)

**Comment by zentron** [comment]
Just to clarify: It looks to only result in this if the failure is a child step, not when it is a step on its own.

Script example
```
Write-Error "OH NO!"
exit 1
```

**Comment by michaelnoonan** [comment]
Release Note: Child steps now display their status correctly when they have failed or have a warning.
