### ISSUE TITLE
To be able to order Projects/Project Groups

### ISSUE THREAD

**Issue by mvalipour** [OctopusDeploy/Issues#2259]
At the moment there is no way to define order for projects or project groups.

This would be handy for all sorts of reasons but most significantly on the dashboard

**Comment by vishnukiranreddy** [comment]
Nice to have feature as sorting is really required

**Comment by vanessalove** [comment]
UserVoice is where suggestions need to go.
https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
