### ISSUE TITLE
CustomInstallationDirectory variable from another step is not evaluating correctly

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2261]
Source: http://help.octopusdeploy.com/discussions/problems/43629-weird-case-with-parameters

When running the `Deploy-RDL Files` step the value for 
`Octopus.Action[Get RDL Files].Package.CustomInstallationDirectory` is getting the wrong value even though the steps are running on the same machine.

`15:36:05   Verbose  |         [Octopus.Action[Get RDL Files].Package.CustomInstallationDirectory] = 'D:\DeployRunner\YYYYY\XXXXXX\RDL'`

But was expected to be `E:\DeployRunner\YYYYY\XXXXXX\RDL`

Interestingly the base components that create this variable look correct:

```
15:36:05   Verbose  |         [Project-Location] = 'E:\WebApps\YYYYY\XXXXXX'
15:36:05   Verbose  |         [Environment-Location] = 'E:\WebApps\YYYYY'
15:36:05   Verbose  |         [Deploy-Location] = 'E:\DeployRunner\YYYYY\XXXXXX'
15:36:05   Verbose  |         [Deploy-Tools-Location] = 'E:\Deploy-Tools\V1\'
15:36:05   Verbose  |         [Deploy-Drive] = 'E'
15:36:05   Verbose  |         [Log-Location] = 'E:\DeployRunner\YYYYY\XXXXXX\Logs\Deployments-20304'
```

**Comment by bigbam505** [comment]
Thanks for adding this @michaelnoonan just wanted to comment to get email updates.  If you need any more information let me know.

**Comment by zentron** [comment]
Release Note: Fixed bug where un-scoped variables were being used during when action variables were being evaluated for 'committing' for use in subsequent actions.

**Comment by zentron** [comment]
Related Tickets
http://help.octopusdeploy.com/discussions/problems/43570-issue-with-resolving-variable-value
http://help.octopusdeploy.com/discussions/questions/6860-using-the-custominstallationdirectory-from-one-step-in-a-another-step
