### ISSUE TITLE
Prevent naming variables with special characters

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2262]
User reported that variables with `<>` on the name used to work in `2.6` for replacement and transformations. This no longer works in 3.x. It might be best to prevent users from being able to use such characters for variable naming.

Source: https://secure.helpscout.net/conversation/155026337/3959/?folderId=557077

**Comment by Dalmirog** [comment]
Conversation in slack: https://octopusdeploy.slack.com/archives/support-discussion/p1451438309000002

**Comment by vanessalove** [comment]
It isn't going to fix this problem that the user reported. they will still be able to migrate into 3.x and then will still have the same if not worse errors when they need to update the variable names. As it is, if they do create a variable name with those characters it does break the deployment so they will know very fast. Just feels like this doesnt solve anything especially what was reported unless we catch it in migration.

**Comment by vanessalove** [comment]
Decided to close this issue.
