### ISSUE TITLE
Failed Tentacle Upgrade is shown as successfully completed

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2266]
Issue to investigate and confirm behaviour.  Tentacle Upgrades from the Octopus Portal "Environments" page can fail however the task is reported as successful.  

![2016-01-04_15-26-20](https://cloud.githubusercontent.com/assets/216245/12083925/8d3cf860-b2f7-11e5-9bc0-8685a9a0a74b.png)

Steps to reproduce:
- Installed Octopus 3.1.2 Server and Tentacle on the same server.
- Update Octopus Environments to add "Dev" environment and local Tentacle.
- Configured Tentacle service to use custom account.  Not an administrator.  Granted logon as a service permission.
- Upgrade Tentacles via Environments page.  Upgrade Task suceeds but process fails with an exception as per the screenshot. 

Source: http://help.octopusdeploy.com/discussions/problems/43534

Note: I didn't receive the exact same error message as the customer as it all depends on the permission the custom user is given.  I successfully upgraded after adding the custom user to the local admin group.  I created a task in Trello to document the permissions required for Tentacle Upgrades.

**Comment by michaelnoonan** [comment]
Release Note: Tentacle upgrade process now displays and handles errors and warnings correctly.
