### ISSUE TITLE
dbo.LibraryVariableSet VariableSetId  length not long enough for our naming convention

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2267]
When you export then import a library variable set, you can get a new ID that is too long for the current size of the column. This needs to be increased. Investigation of other tables and columns with similar naming conventions should be checked.

Source: https://secure.helpscout.net/conversation/156314653/3999/?folderId=557083

**Comment by MJRichardson** [comment]
Release note:Resolved bug with VariableSetId columns not being long enough for migrated data.
