### ISSUE TITLE
Azure Active Directory autentication/authorization for the Octopus Deploy web app

### ISSUE THREAD

**Issue by maartenba** [OctopusDeploy/Issues#2274]
Consider this a feature request for Azure Active Directory autentication/authorization for the Octopus Deploy web app.

Wishlist:
* Be able to configure Azure Active Directory as an authentication mechanism - this would allow single sign-on as well as a user store that is outside of OctopusDeploy.
* Be able to assign Azure AD groups to teams - this would make it easy to let a specific AD group in as "developers" in Octopus.
** Caveat: for organizations with many groups, Azure AD graph API has to be used for capturing the user's groups. This would be very much needed as our org has lots of security groups per user.

**Comment by alfhenrik** [comment]
Hi @maartenba thanks for you suggestion, we have this [UserVoice ticket](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6923861-azure-active-directory-integration) to integrate with Azure AD. You can go there and put some votes in for it and if/when it gets enough customer support we'll take it into consideration.

Thanks!
