### ISSUE TITLE
Octoexe import returns errorcode 0 when import not successful

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2280]
ticket really has all the details so being lazy

Source: http://help.octopusdeploy.com/discussions/problems/43769

**Comment by robpearson** [comment]
Release Note: `octo.exe` Imports with validation errors now return a non-zero exit code.

**Comment by robpearson** [comment]
Release Note: `octo.exe` imports with validation errors now return a non-zero exit code.
