### ISSUE TITLE
Migrator to have a history only import option

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2281]
We have a growing number of cases of the migrator not being able to import the history due to the time it takes, or having not imported data due to its rules and logic. Usually by the time the customer has informed us of this, or realized they are missing data, they have used 3.x for too long to risk changing primary data like projects, variables etc. 

It would be great if we could have a flag for the migrator to only import history that doesn't exist. So projects, releases etc that do not exist within the 3.x instance would be created but if they do exist then they would be skipped instead of overwriting.

I have a bunch of sources for why this is relevant, but they aren't super specific to creating this. I have asked for a couple of databases so we could test their specific cases.

**Comment by vanessalove** [comment]
This would also help for customers who have large histories but need a 3.x instance up and running, or they just dont have the power/memory/resources/infrastructure to do a full import at once.  They could then import the history in workable chunks.

**Comment by vanessalove** [comment]
couple of customers to notify:
http://help.octopusdeploy.com/discussions/problems/43735
http://help.octopusdeploy.com/discussions/problems/43661

**Comment by zentron** [comment]
Also Covers Issue in: https://github.com/OctopusDeploy/Issues/issues/2283

**Comment by zentron** [comment]
so new migrator arguments... something along the lines of
`Octopus.Migrator.exe migrator --nologs --file ...`: imports without touching the raw server log entries
and
`Octopus.Migrator.exe migrator --onlylogs --file ...`: imports only the raw server log entries

When importing, it will first need to also load all the server task document objects to cross reference with the database stored entries to ascertain what the new taskIds are that the logs need to save as.

At the moment these arguments will be exposed just through the command line.

**Comment by zentron** [comment]
Release Note: Provide `--nologs` and `--onlylogs` option for migrator process to seperate loading raw task logs from main server data for increased performance
