### ISSUE TITLE
Migrator converts logfiles already converted

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2283]
When you do partial imports using the max age flag, it imports the history correctly, but it also appears to keep converting the same serverlogs that it previously converted, so even if you do a sequential set of maxage increments, the import time starts to get exponentially larger.

--maxage 80
```
     Release......................................2797
     ServerTask...................................3358
     Task log.....................................3365
     TaskLog file.................................5899
     TaskLog line.................................5489743
```

--maxage 135
```
     Release......................................4288
     ServerTask...................................3973
     Task log.....................................3973
     TaskLog file.................................9861
     TaskLog line.................................9135099
```

it doesnt make sense that the tasklog file increases in such a high number unless we are converting those already converted.

Source: http://help.octopusdeploy.com/discussions/problems/43685-migrating-to-3x-very-slow

It would help those doing incremental imports.

**Comment by zentron** [comment]
Performance Problem will be addressed by https://github.com/OctopusDeploy/Issues/issues/2281
