### ISSUE TITLE
Octopus.Machine.Name is erroneously populated by the target server's "Display name"

### ISSUE THREAD

**Issue by jeffreypalermo** [OctopusDeploy/Issues#2284]
When using Octopus.Machine.Name, one would expect that to be a network-reachable name, such as the tentacle DNS name.  But it seems to be populated with the server's Display Name, which is hardly ever a network-reachable name.  Is this by design?  If so, then the label on the configuration screen should not be "Display name".  It should be "Server Address" so that it is clear.

**Comment by vanessalove** [comment]
Please consult our support channels for support and feedback.
https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
