### ISSUE TITLE
Upgrading to 3.2.14 caused IIS binding enabled to render incorrectly and lose value in UI

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2294]
The source ticket has the details. But roughly after upgrading to 3.2.14 the enabled binding was showing a checkbox, and once expanded it shows a value of false but not of the variable that had previously been set there.

Source: https://secure.helpscout.net/conversation/160367310/4245/?folderId=557083

**Comment by michaelnoonan** [comment]
We are releasing improvements to the Sensitive Property bindings in Octopus 3.3.0 which should address this issue.
