### ISSUE TITLE
In product notification for specific versions

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2297]
With the issue we had in 3.2.14 - discussed with Paul:
Idea that for a version, we can put a comment in Octofront such as a notification that a build was pulled and link to the fix and reasons etc on a docs page. That in product because we know their version and get the next available from Octofront we can give them the warning near the upgrade bullhorn. A way to reach out to customers in this situation so they do not have to reach out to us after the fact.

**Comment by droyad** [comment]
This is being tracked elsewhere
