### ISSUE TITLE
Allow new upgrade tentacle button to post request

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2299]
The new upgrade button that was added in previous release was not actually creating the upgrade task.
Appears to be due to an incorrect null check.

**Comment by zentron** [comment]
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/commit/7c49cb2a7c7affcd9d0a318bfc94fb09a535e3f7

**Comment by vanessalove** [comment]
Release Note:Fixed issue with new Tentacle upgrade button on connectivity page
