### ISSUE TITLE
Add new variable `Octopus.Action.Package.InstallationDirectoryPath` as replacement for `Package.InstallationDirectoryPath`

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2300]
Most of our variables are prefixed with `Octopus.X` especially when there is a corresponding output variable like `Octopus.Action[StepName].Output.Package.InstallationDirectoryPath`

To make things more obvious, consistent, and discoverable for users, add a new variable for  `Octopus.Action.Package.InstallationDirectoryPath` set in all the same places as the `Package.InstallationDirectoryPath` variable.

Mark `Package.InstallationDirectoryPath` as obsolete but keep it around for backwards compatibility. Consider if its possible to log as warning if any obsolete special variable such as this is used.

**Comment by droyad** [comment]
I don't think it's possible to log a deprecation warning in some cases, ie when used in scripts.

Added the property and it is populated along with the other two similar properties:
![image](https://cloud.githubusercontent.com/assets/1687639/14452541/abf38e26-00d2-11e6-84c0-9fa743f43241.png)

**Comment by droyad** [comment]
In Calimari 3.3.8

**Comment by droyad** [comment]
To clarify, the only change is the addition of the `Octopus.Action.Package.InstallationDirectoryPath` variable, existing variable will continue to work.
