### ISSUE TITLE
delete release Teamcity plugin

### ISSUE THREAD

**Issue by mcintyre321** [OctopusDeploy/Issues#2301]
How can I delete a release with the teamcity plugin? It would be great if there was an octo.exe buuild step that let you choose exactly what command you want to run.

**Comment by vanessalove** [comment]
Please consult our support channels for support and feedback.
https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
