### ISSUE TITLE
Provide property on action variable to reference the parent step name

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2302]
A user is attempting to write information for an action, based on the state of its parent step. 
e.g.

```
#{each action in Octopus.Action}
  #{if Octopus.Step[action.StepName].Status != "Skipped"}
```

in the case above the `action.StepName` can then be used to get access to the parent Step status. We currently have `Number` property which, with some string manipulation can get access to the step details, however this requires slightly more complex combined PS & Octostache code which is a little dirty.

Source: http://help.octopusdeploy.com/discussions/questions/7044

**Comment by markryd** [comment]
When released this will need
```
#{each action in Octopus.Action}
  #{if Octopus.Step[#{action.StepName}].Status.Code != "Skipped"}
```
to work, since we need to eval `action.StepName` rather than use it directly, and the value is in `Status.Code` not just `Status`.

**Comment by markryd** [comment]
Release Note: You can now use a variable as the index on an array variable with `#{FirstVariable[#{SecondVariable}]}` and if statements can compare to another variable with `#{if FirstVariable == SecondVariable}` or to a string with #{if FirstVariable == "StringValue"}
