### ISSUE TITLE
Variable evaluated and stored during post-step process has problems with output variables on unscoped user variables

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2303]
It looks as though if a user variable is set to an output variable with multiple machines, then during the post step variable persisting, the wrong value may get set in the wrong machine scope.
Source: http://help.octopusdeploy.com/discussions/problems/43318-problem-with-set-octopusvariable

**Comment by Dalmirog** [comment]
I wasn't able to reproduce this with 3-4 targets. User claims it works well in his dev environment with ~20 targets, but not in prod with 100+

**Comment by zentron** [comment]
Release Note: Fix bug when user provided variables that are made up of output variables are accessed in later steps.
