### ISSUE TITLE
"Invalid date" message on Task Summary screen during Manual Intervention

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2309]
Version - 3.2.19

Deployment process - A few steps, then a manual intervention.

![invaliddate](https://cloud.githubusercontent.com/assets/6180562/12462960/e31719fa-bf9f-11e5-94f8-fc3e2ebc5c29.png)

**Comment by vanessalove** [comment]
Source: https://secure.helpscout.net/conversation/162858083/4386/?folderId=557082

**Comment by vanessalove** [comment]
possibly related to a change made recently https://github.com/OctopusDeploy/Issues/issues/2244

**Comment by tothegills** [comment]
Having problems reproducing, think it could be cache.  Have seen similar before and a hard refresh fixed it.  Would also explain why he no longer has the problem.

**Comment by Dalmirog** [comment]
Checked the initial deployment where I was able to repro this and It looks ok now. Tried to reproduce it again on a brand new project with no luck.

Does seem like a cache thing.
