### ISSUE TITLE
Investigate workarounds for WMF 5.0 and Windows PowerShell

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2310]
Octopus and Tentacle run as Windows Services and rely on calling PowerShell.exe. When Microsoft made WMF 5, they seem to have broken this from working. We raised a bug but never heard back from them before they RTM'd it:

https://connect.microsoft.com/PowerShell/Feedback/Details/1348733

Since they have shipped it, we're going to need to find a workaround. 

Discussion: 
http://help.octopusdeploy.com/discussions/problems/34939

**Comment by PaulStovell** [comment]
From @MJRichardson:

> I think I tested the RTM of WMF 5 before christmas, and found that it worked.  We will need to re-test to be sure.  Also, seems MS have pulled the RTM!: http://blogs.msdn.com/b/powershell/archive/2015/12/23/windows-management-framework-wmf-5-0-currently-removed-from-download-center.aspx

**Comment by MJRichardson** [comment]
I have tested with the Production Preview of WMF 5.0, and the problem seems to no longer occur.

The WMF 5.0 RTM has been retracted by Microsoft.  We will re-check once it is finally released.

**Comment by Dalmirog** [comment]
Apparently MS has released an RTM a few months ago: https://www.microsoft.com/en-us/download/details.aspx?id=50395

Should we give this another try? I've tested deploying OctoFX to a 2012 server running the WMF version of the link above and it worked on my end.
