### ISSUE TITLE
API returns sensitive values for deployment process fields

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2313]
In a deployment process, some fields can be passwords. Examples:

 - The password for a custom Windows Service account in the Windows Service feature
 - The password for a custom IIS application domain
 - Password fields in step templates

When these values are stored in the Octopus Server, they are supposed to be treated as sensitive values. That means they should never be able to be "read" from the Octopus server. 

It appears that this is no longer the case - after saving a deployment step with a password, a GET request will still return the password in plain text:

```
      "Actions": [
        {
          "Id": "f4d0b6d6-1113-48e0-99b8-9c5ed1ceac74",
          "Name": "A",
          "ActionType": "Octopus.TentaclePackage",
          "Environments": [],
          "Channels": [],
          "Properties": {
            "Octopus.Action.EnabledFeatures": "Octopus.Features.WindowsService",
            "Octopus.Action.Package.AutomaticallyRunConfigurationTransformationFiles": "False",
            "Octopus.Action.Package.AutomaticallyUpdateAppSettingsAndConnectionStrings": "False",
            "Octopus.Action.Package.DownloadOnTentacle": "False",
            "Octopus.Action.Package.NuGetFeedId": "feeds-builtin",
            "Octopus.Action.WindowsService.CreateOrUpdateService": "True",
            "Octopus.Action.WindowsService.ServiceAccount": "_CUSTOM",
            "Octopus.Action.WindowsService.StartMode": "auto",
            "Octopus.Action.WindowsService.CustomAccountName": "saasa",
            "Octopus.Action.WindowsService.Arguments": "a",
            "Octopus.Action.WindowsService.ExecutablePath": "a",
            "Octopus.Action.WindowsService.ServiceName": "a",
            "Octopus.Action.WindowsService.DisplayName": "a",
            "Octopus.Action.WindowsService.Description": "a",
            "Octopus.Action.Package.NuGetPackageId": "aaaa"
          },
          "SensitiveProperties": {
            "Octopus.Action.WindowsService.CustomAccountPassword": "mypassword"
          }
        }
```

We go through a lot of effort to split sensitive and non-sensitive values into the dictionaries above, and then we go and print it out anyway. 

Fix: Make sure we never let the API render these sensitive values, and make sure we have integration test coverage for each of the examples above. 

Notes: 

 * The bug only affects the fields in a deployment process, not variables defined on the Variables tab. I checked, these values are still never returned.

Source: http://help.octopusdeploy.com/discussions/problems/44040

**Comment by vanessalove** [comment]
find out what version this started in so we can be clear in our release notes when it was available

**Comment by PaulStovell** [comment]
The bug was introduced in 3.0.20+ and 3.2+. It was introduced when attempting to fix this:

https://github.com/OctopusDeploy/OctopusDeploy/commit/a5828d291d10627e8a0cfbce3a1c834b8f7f083c

It was missed because although we have test coverage for sensitive variables, we didn't have it for deployment process steps. 

We'll fix it very soon and will include test coverage.

**Comment by zentron** [comment]
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/commit/a331886fa9477fe23e81656673de53477e4cfcc8

Reverted original change and added API test

**Comment by zentron** [comment]
Release Note: Prevent sensitive variables for deployment process returning from API call
