### ISSUE TITLE
Support non-nuget packages in External Feeds that are Local paths.

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2314]
For the `3.3-beta` release we plan to only support the extended packaging formats through the built-in feed.

Support should be extended to allow for external feeds with local paths to return non-nuget packages. Currently this is implemented using the NuGet `LocalPackageRepository` which would be better replaced then extended.

**Comment by michaelnoonan** [comment]
We're going to close this for now and monitor demand with this UserVoice suggestion: TBD
