### ISSUE TITLE
Octo.exe pack hanging on Node/Express/React Application

### ISSUE THREAD

**Issue by crathermel** [OctopusDeploy/Issues#2315]
Should we be using octopus deploy for node/express/react applications?  We are trying to package our contents via octo.exe pack command line and the command just "hangs" for a long time and 
<img width="1263" alt="screen shot 2016-01-22 at 11 15 47 am" src="https://cloud.githubusercontent.com/assets/1151374/12517730/fd32a29a-c0f9-11e5-9415-cd41f0346bb6.png">

<img width="1052" alt="screen shot 2016-01-22 at 11 19 54 am" src="https://cloud.githubusercontent.com/assets/1151374/12517751/18b35b18-c0fa-11e5-929c-020971fc0cf0.png">

**Comment by PaulStovell** [comment]
In 3.3 we're releasing support for deploying Node apps using .zip/.tar.gz files instead of NuGet packages - so you won't need to create a .nupkg (they struggle with the many nested node_modules).

**Comment by crathermel** [comment]
Thanks for the update @PaulStovell
