### ISSUE TITLE
Step variables to keep machine scope when on the machine

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2322]
Since introducing OctoStache we don't scope step variables to machine any longer.

If you call `Octopus.Action[Deploy and Test].Output.Package.InstallationDirectoryPath` from a subsequent step on the same machine it may or may not return the correct variable when you do not define the machine name.

Can we investigate if this is possible, and if possible can we implement it. 

It reportedly consistently worked in 2.6.

Source: http://help.octopusdeploy.com/discussions/problems/43866

**Comment by jmezach** [comment]
Any update on this issue? We've had a look at using the machine scope variable instead, but this requires us to make some adjustments to some of the PowerShell scripts we're currently using so its a bit more work than we anticipated. If a more permanent solution is in the works we'd rather not go through that now.

**Comment by MJRichardson** [comment]
I've tested this and it now works.  I believe it was resolved by the fix for https://github.com/OctopusDeploy/Issues/issues/2303 though I'm not certain.  If so, it will work from release 3.2.21 on.
