### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2325]
Add a flag to disable or set allowed origins just like for CORS

**Comment by michaelnoonan** [comment]
This will break TFS vNext/TFS Online/VSTS Core 1.0 portal (which IFRAMES Octopus Portal)

**Comment by michaelnoonan** [comment]
This is causing PCI compliance scanners to fail Octopus as a bad actor.

**Comment by zentron** [comment]
Adding support for [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) along with the `ALLOW-FROM` property to provide single acceptable uri. Caveat is that if this is used then Chrome wont respect the `X-Frame-Options` header at all.

Also this is apparently being deprecated in support of [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives)

As PCI compliance checks will require this header we will add regardless and rely on users setting the appropriate `ALLOW-FROM` property (if at all) to suit their environment at their own risk.

**Comment by zentron** [comment]
Release Note: Provide `X-Frame-Options` HTTP header to `DENY` by default. Settings are configurable on Server.
