### ISSUE TITLE
Octo.exe import broken due to environment check change

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2327]
A change that was made to check if your environment user scopes were changed now breaks the import of projects using octo.exe

Source: https://secure.helpscout.net/conversation/164146525/4469/?folderId=557077

**Comment by vanessalove** [comment]
henrik found where and why

**Comment by vanessalove** [comment]
so the logic on the check for environment scope changing is totally not working.
I did some testing and these are my results:

I can only import to the new server if my environment set EXACTLY matches the environments scoped to variables. If there is no environment scoping its fine.
If i have more than the required environments in the target server it gives this error...

to which i have to ask the following: why does it think my environments have changed as an ADMIN USER API with no environment scoping, over the small logged in session that is an import?

shouldnt the fix that caused it check specifically if i even have environmental scoping and that it has changed - i just dont understand the logic? nothing has changed in that time, i am an admin user and dont have environment scoping on any of my permissions

the worst part is you cant even disable an environment to get the data in, you have to delete the extra environments or remove the scoping from the orgin server variables to export then add them back .. so dangerous.

**Comment by zentron** [comment]
Release Note: Only test for permission changes to environments used in an existing variable set scope when that variable set is updated.
