### ISSUE TITLE
Rename $key variable in Calamari bootstrap script

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2329]
We have users that use the variable name `$key` in their scripts and since 3.0 this will no longer work as we use a variable named `$key` in the bootstrap script used by Calamari.

Suggest this variable be renamed to something like `$OctopusKey` instead to minimise the chance of clashing with customers scripts.

Source: http://help.octopusdeploy.com/discussions/problems/44152

**Comment by vanessalove** [comment]
could we look at changing all small keyword named vars with octopus at the front ? or too much too hard? Just in this context

**Comment by alfhenrik** [comment]
Another occurrence: http://help.octopusdeploy.com/discussions/problems/45558

**Comment by DmitryLobanov** [comment]
We have the same issue. Luckily, we own the code. But it took several hours to figure out what's wrong.

**Comment by markryd** [comment]
Release Notes: No longer use $key as a variable name in bootstrap scripts so we don't clash with customer scripts.
