### ISSUE TITLE
Support for creating Octopus Deploy-compatible NuGet packages in non .NET projects.

### ISSUE THREAD

**Issue by BrandonClapp** [OctopusDeploy/Issues#2331]
We use OctoPack for packaging many of our .NET projects to be used with Octopus Deploy. We have been experimenting with using Node for some of our projects, but are not sure how to go about creating a .nupkg for these projects in order to continue using octopus for these projects.

Does octopus deploy use a standard nuget package or is there a specific structure to creating this package that octopus needs to consume?

It would be great if there was an npm package (i.e. "gulp-octopack") in order for preparing our application for consumption in octopus.

Is there a better way to go about using Octopus with non .NET projects?

**Comment by vanessalove** [comment]
Sorry GitHub is for our working items, not support or questions. If you could please use our support channels.

https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed

**Comment by BrandonClapp** [comment]
For whoever else is looking for the answer to this, rather than creating a special account on the forum, the short answer is no.

**Comment by vanessalove** [comment]
The short answer is yes. We have a beta for our 3.3 coming out today that resolves this, blog post also coming today with details. Having these issues closed in GitHub does not help others find answers nor allow us to support you with more detailed responses, they get lost in our Queue and clog up our working items board.

**Comment by BrandonClapp** [comment]
Thank you for your kindest support.
