### ISSUE TITLE
User / password fields dissapear when using custom expression for App Pool Identity

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2333]
This wasn't a problem before #2229 because the username / password variables persisted regardless of the identity method set.

With "SpecificUser" on the identity custom expression field
![withuser](https://cloud.githubusercontent.com/assets/6180562/12683125/1e2e072c-c696-11e5-8b3f-449f3ce636cc.JPG)

With a variable on it
![withoutuser](https://cloud.githubusercontent.com/assets/6180562/12683126/200eb7da-c696-11e5-95b3-b8802a61207f.JPG)

Source: http://help.octopusdeploy.com/discussions/questions/4481 (latest comments)
Version: 3.1.19

**Comment by michaelnoonan** [comment]
Related to #2264

**Comment by MJRichardson** [comment]
Resolved in Octopus Deploy 3.3.0.
