### ISSUE TITLE
Variable expression not persisted for sensitive-value in step template

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2336]
Steps to reproduce (from http://help.octopusdeploy.com/discussions/problems/43836-bug-in-octopus-deploy ):

1- Go to Step Templates in Octopus
2- Add step template
3- Choose Run a script
4- Add a parameter called test
5- Set the control type of the parameter to Sensitive/password box
6- Click Apply
7- Go to the Step tab
8- Enter this PowerShell: Write-Host $test
9- Save the Step Template
10- Create a new project
11- Create a variable called 'var' and give it a value. Save it.
12- Add the step template you just created to the Process
13- Set the 'test' field to a value manually
14- Save the step template and 'Create release'. The value you put in the sensitive box should be printed if you inspect the Task log for that step
15- Now edit the Process and change the test field in the step to  use a custom variable expression , and use the variable you created (i.e. '#{var}') instead of the manually entered value in the sensitive field
16- Save the step and 'Create release'. The old manually entered value will be printed instead of the substituted variable value

**Comment by michaelnoonan** [comment]
Release Note: Variable expressions are now correctly persisted for sensitive fields in step templates.
