### ISSUE TITLE
Set-OctopusVariable in Package step custom script HTML encodes UTF8 values

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2340]
Steps to replicate:
- Create a project
- Add a variable with a UTF8 value in it, e.g. `£`
- Enable printing evaluated variables
- Add a package step to your process
 - Enable the custom scripts feature
 - Add `Set-OctopusVariable -name "utf8output" -value "#{UTF8Value}"` to any of the script editors
- Add a Run script step with some dummy script in it, so you can see the output variables of your package step
- Create a release and deploy it, view the raw log and the output value will be `A£`

**Comment by MJRichardson** [comment]
I was unable to replicate.  I believe this may have been squashed by https://github.com/OctopusDeploy/Calamari/commit/f98cf9741e37430f1e9fab18af3288d678a6d28b
Closing.
