### ISSUE TITLE
Authentication fails if request contains another cookie with specific "bad" format

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2343]
As seen in the screenshot below, we have added a cookioe `MyCookie` with a value of `{XXS,DSD}`
![image](https://cloud.githubusercontent.com/assets/1830666/12800009/fdac96a8-cb1d-11e5-816d-329bad9ac7bf.png)
Nancy appears to have problems parsing the cookie data and so the octopus Auth token is also lost

![image](https://cloud.githubusercontent.com/assets/1830666/12800088/59e4f55a-cb1e-11e5-8852-b2064895642b.png)

This results in a 401 for the user
Source: http://help.octopusdeploy.com/discussions/problems/35799

**Comment by wes-novack** [comment]
Thank you @zentron!

**Comment by michaelnoonan** [comment]
Hi all. I've investigated this right down into the BCL. Octopus uses Nancy with Self-Host - which depends on `System.Net.HttpListener`. When a HTTP request is dispatched, Nancy trusts the Headers collection that is parsed by `HttpListener` - and it treats `;` and `,` equivalently as *separator* characters.

In this case the cookie from the other subdomain looks like this:
`psSubscription={"endOrConvertDateUtc":"2016-11-26T00:00:00","sku":"IND-Y-PLUS","isTrial":false,"handle":"ee972618-1912-4100-bd84-cda4c339e0d3"};` which contains raw JSON, and a handful of `,` characters, and this is causing the Octopus Authentication Cookie to be parsed incorrectly by `HttpListener`.

We can't make any sensible change to Octopus, nor Nancy, nor `System.Net.HttpListener` to cater for this situation.

We'd recommend encoding the `psSubscription` cookie value as Base64 encoded text, which is what we do with our cookies to avoid this confusion. This is also the recommendation of [RFC 6265](http://tools.ietf.org/html/rfc6265#section-4.1) - and `HttpListener` is well within its rights (and recommendation) to start using `,` as a separator character.

I'm sorry if that's not the answer you were looking for, but I can't recommend making any change to Octopus to cater for this scenario.

Hope that helps!
Mike

**Comment by wes-novack** [comment]
Thanks folks!

**Comment by kwilson803** [comment]
I'm currently running Octopus 3.4.10 and having this issue but I see the bug was closed as "WONTFIX". Are there any plans to actually correct this?
![octopuscapture](https://cloud.githubusercontent.com/assets/22158974/19087769/4f3ee95c-8a41-11e6-9fee-cb3ec53f380c.PNG)

**Comment by wes-novack** [comment]
In our case, we stopped issuing the cookie (from another app on the same domain that we are hosting Octopus) that was causing the problem. You can either get your cookie updated or move your Octopus website to another domain to solve this particular problem.

**Comment by zentron** [comment]
Hi @kwilson83. As @wes-novack stated above (and along with the rest of the ticket details) the problem is with the other cookie on the same domain and there is nothing Octopus can or should be able to do to fix. You will need to either fix your other website, or move the octopus server to another domain.
If however this is a different issue then with more information perhaps we can see if there is a fix specific to your problem.
