### ISSUE TITLE
Handle packages with no file extension in 3.3.0-beta

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2344]
When a package is being extracted the 3.3.0 release now uses file extension to determine the file type. A user has encountered a scenario where the file has no extension (but is still apparently a NuGet file) and the deployment fails because it cannot determine what extractor to use.

We should default to using the NuGet extractor if no other format can be determined since this will be by far  the most common scenario.

Source: https://secure.helpscout.net/conversation/167615527/4728/

**Comment by zentron** [comment]
Release Note: Record built-in packages as being `.nupkg` files when upgraded to 3.3

**Comment by michaelnoonan** [comment]
Sorry, I made a mistake and this commit didn't make the `3.3.0-beta.2` release, but it will be in the `3.3.0-beta.3` and `3.3.0` releases.
