### ISSUE TITLE
Json config feature is case sensitive, resulting in dupe entries

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2346]
When using the JSON config feature it will not detect a variable with the same name but different casing, resulting in duplicate variables.  This will prevent the config file from loading in ASP.
It may be worth failing the convention if there is a case mismatch.

**Comment by tothegills** [comment]
To reproduce:
Create an app with an `appsettings.config` file that contains a variable.  Create a deploy step and include the json feature.  Set up a variable in the project that has a variable the same as in the `appsettings.config` file but with different case.  Deploy.

```
{
   "foo": "bar",
   "Foo": "bar
}
```

**Comment by alfhenrik** [comment]
This one is covered in the release notes by https://github.com/OctopusDeploy/Issues/issues/2364
