### ISSUE TITLE
Can we markdown the package release note to match the release release notes

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2347]
Package release notes aren't shown in markdown, but I think it should be consistent with the release release notes.

Currently looks Rubbish, needs to look Awesome.
Source: http://help.octopusdeploy.com/discussions/problems/44329-octopus-deploy-package-release-notes-look-rubbish

**Comment by MJRichardson** [comment]
Release note:Allow Markdown formatting for NuGet package release-notes
