### ISSUE TITLE
Object reference not set to an instance of an object on push

### ISSUE THREAD

**Issue by kfrancis** [OctopusDeploy/Issues#2349]
Hi,

I'm seeing this issue suddenly when building on VSO:

> OctoPack: Successfully created package 'C:\a\1\s\Source\CabMD.Web\obj\octopacked\cabmd.web.1.5.5878.27239.nupkg'.
         OctoPack: Copy file: C:\a\1\s\Source\CabMD.Web\obj\octopacked\cabmd.web.1.5.5878.27239.nupkg
         OctoPack: OctoPack successful
         Publish to repository: https://www.myget.org/F/mysecurefeedidhere/api/v2
         "C:\a\1\s\packages\OctoPack.3.0.53\tools\NuGet.exe" push "C:\a\1\s\Source\CabMD.Web\obj\octopacked\cabmd.web.1.5.5878.27239.nupkg" <apikey> -s https://www.myget.org/F/mysecurefeedidhere/api/v2 
         Pushing cabmd.web 1.5.5878.27239 to 'https://www.myget.org/F/mysecurefeedidhere/api/v2'...
         Please provide credentials for: https://www.myget.org/F/mysecurefeedidhere/api/v2
         Object reference not set to an instance of an object.
         UserName: Password: 
packages\OctoPack.3.0.53\tools\OctoPack.targets(107,5): Error MSB3073: The command ""C:\a\1\s\packages\OctoPack.3.0.53\tools\NuGet.exe" push "C:\a\1\s\Source\CabMD.Web\obj\octopacked\cabmd.web.1.5.5878.27239.nupkg" <apikey> -s https://www.myget.org/F/mysecurefeedidhere/api/v2 " exited with code 1.
     5>C:\a\1\s\packages\OctoPack.3.0.53\tools\OctoPack.targets(107,5): error MSB3073: The command ""C:\a\1\s\packages\OctoPack.3.0.53\tools\NuGet.exe" push "C:\a\1\s\Source\CabMD.Web\obj\octopacked\cabmd.web.1.5.5878.27239.nupkg" <apikey> -s https://www.myget.org/F/mysecurefeedidhere/api/v2 " exited with code 1. [C:\a\1\s\Source\CabMD.Web\CabMD.Web.vbproj]

The solution has the following build params: 

> /p:RunOctoPack=true /p:OctoPackPublishPackageToHttp=https://www.myget.org/F/mysecurefeedidhere/api/v2 /p:OctoPackPublishApiKey=<apikey> /p:GenerateProjectSpecificOutputFolder=true

The version of octopack (v3.0.53) seems to use NuGet.exe 2.8.3.

**Comment by vanessalove** [comment]
Sorry GitHub is for our working items, not support or questions. If you could please use our support channels.

https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
