### ISSUE TITLE
Octopus Audit page filter times out

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2352]
Octopus Audit page filters can time out.  This is happening on demo.octopusdeploy.com.

Steps to reproduce: 
- Navigate to the Audit events page
- Select OctoFX Trading Website from the project list.

![2016-02-05_11-45-02](https://cloud.githubusercontent.com/assets/216245/12835703/3fc21a28-cbfe-11e5-8fdd-a7df3622c195.png)

The resulting error is below.

![2016-02-05_11-10-01](https://cloud.githubusercontent.com/assets/216245/12835699/346b0a04-cbfe-11e5-9ea9-43adf58b747e.png)

**Comment by droyad** [comment]
This no longer seems to be a problem.
