### ISSUE TITLE
Migrator: No Overwrite option

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2353]
Source from https://github.com/OctopusDeploy/Issues/issues/2338

(I've rewritten this Issue after I lost it to a waffle.io bug)

We would like to make it easier for people to do increasing windows of history import so it's not such a big pill to swallow.

Consider:
1. Import data
2. Import history 30 days
3. Import history 60 days
4. Import history 120 days
5. etc

But it would be important to make sure we don't overwrite any data as that window expands.

**Comment by zentron** [comment]
Release Note: Provide `--nooverwrite` parameter for `migration` task to skip existing documents.
