### ISSUE TITLE
Package installation paths with International letters (UTF8 chars) are invalid in subsequent steps

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2366]
Steps to reproduce:
- Create Environment or Deployment Target w/ Ø in the name.
- Create a Project with a package step (any package) and a script step.
- If you use `Octopus.Action[Package Step Name].Output.Package.InstallationDirectoryPath` in a custom script in the package step, the path is valid (see powershell snippet below).  
  **Sample output**: `C:\OctopusDev\Applications\DWebApp01\NØrway\SimpleWebApp\1.0.4.0`
- If you use `Octopus.Action[Package Step Name].Output.Package.InstallationDirectoryPath` in a subsequent script step, the path is not valid.  The character is replaced with a `?` and it's not longer a valid path.  
  **Sample output**: `C:\OctopusDev\Applications\DWebApp01\N?rway\SimpleWebApp\1.0.4.0`

```
$tmpPath = $OctopusParameters['Octopus.Action[App].Output.Package.InstallationDirectoryPath']
$isDir = (Get-Item $tmpPath) -is [System.IO.DirectoryInfo]
Write-Host "Install: $tmpPath ($isDir)"
```

Sounds related to #2340

**Comment by michaelnoonan** [comment]
Could be related to https://github.com/OctopusDeploy/Issues/issues/2340

**Comment by markryd** [comment]
Unable to reproduce. Presumably fixed while tackling another UTF8 issue.
