### ISSUE TITLE
Octo.exe push package

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2378]
It would be really nice to offer `octo.exe push` using the new package push API in Octopus 3.3. `octo.exe` would then have `pack`, `push`, and `deploy`.

The alternatives are not pretty, see the attached tickets.

Alternative: https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/Octopus.Client/LINQPad/Push%20Package%20to%20Built-In%20Repository.linq

Source: http://help.octopusdeploy.com/discussions/problems/44548

**Comment by PaulStovell** [comment]
I agree, this would be really nice.

**Comment by PaulStovell** [comment]
Rolling this up into a larger issue: #2411
