### ISSUE TITLE
OctoPack internal nuget v3?

### ISSUE THREAD

**Issue by henkmeulekamp** [OctopusDeploy/Issues#2379]
Is there a reason that the NuGet.exe inside the octopack is not >= v3?

We are running into an issue with version of octo nuget packages. We are trying to use SemVer 2.0.0 feature as outlined in:
http://blog.nuget.org/20140924/supporting-semver-2.0.0.html

We are looking at this format: 2.0.0-beta.2
NuGet 3.0 will understand these new dot-separated identifiers and properly sort them.

The nuget.exe inside the octopack nuget package is still v2, and throws the following error when using the version with dot after the beta label.
```
error OCTONUGET: '4.6.6-beta.15' is not a valid version string. 
error OCTONUGET: Parameter name: version 
```

Thanks,

**Comment by vanessalove** [comment]
Sorry GitHub is for our working items only.
https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
