### ISSUE TITLE
Ability to override a task status

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2380]
If a deployment fails for an unimportant reason - e.g., app was deployed, but an email step failed - the only solution is for customers to re-deploy. 

Let's give them the ability to override the status. They could mark a successful task as failed, failed as success, cancelled as success, etc. 

When they override the status, make them provide a reason, and include it in an audit event so that people can see why they overrode it.

**Comment by vanessalove** [comment]
related: https://github.com/OctopusDeploy/Issues/issues/1888

**Comment by ccamburn** [comment]
Until such a time as this is allowed through the API / UI, is there a way we can edit this directly in the database to show success?

**Comment by vanessalove** [comment]
@ccamburn we would not recommend doing any form of data manipulation directly in the database, sorry

**Comment by vanessalove** [comment]
From #1888 which was a slightly different issue but has a proposed solution

Information relayed to customer:

I am about to use more words than necessary so the tl;r; is we will do something about this, but probably not until 3.4 or 3.5.

When it was changed to the green icon with the warning, we had a decrease in support requests. The reason being that customers were more interested in how to suppress warnings and have a green dashboard than actually getting rid of warnings or they had warnings they couldn't get rid of. But now we also agree that if you don't usually have warnings you want to know right away.

So our solution is going to be:

add a project variable for 'keep my warnings green' or 'no i want yellow warnings' for icons
for each warning in your logs, you have the ability to 'mark as ignore this warning' so you could suppress warnings from external tools that you cannot control but you know the deployment is fine. It also means if you get a new warning it will go yellow again
so based on both of those, it makes it a large extension and not something we can update quickly.

**Comment by thebigmoosey** [comment]
Release Note: Added ability to override a task status

**Comment by tothegills** [comment]
Created https://github.com/OctopusDeploy/Issues/issues/3462 to address handling warnings in logs.
