### ISSUE TITLE
Change IIS script to use ​Get-WebAppPoolState​ to avoid process hang

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2385]
Octopus Deploy user has hit upon an issue described in http://forums.iis.net/p/1222296/2101359.aspx whereby an app pool that has its `IdleTimeout action` set to `Suspend` will hang for 2 minutes when accessed via the PS cmdlet  `Get-Item $appPoolPath` as part of our IIS script.

As suggested in the same forum post, the `Get-WebAppPoolState` cmdlet still executes fine and given our usage in the IIS script we may be able to replace `Get-Item` with `Get-WebAppPoolState`.

Investigate if the swap can take place and if so, confirm availability for PowerShell 2+

Source: https://secure.helpscout.net/conversation/172854600/5070/

**Comment by markryd** [comment]
Release Note: Avoid a PowerShell bug that can cause deployment pauses when an app pool is set to suspend
