### ISSUE TITLE
Have message on task page if the task is queued due to the task cap on node

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2386]
Currently with 3.x and nodes we have a hidden cap of 5 tasks run at a time by default. If not using HA no reason to ever check this page and change it. Seems to be working okay as we haven't had more than 1 confused customer at this point - however it makes the task Qed but doesnt tell you why - if it mentioned on the task page [this has been Qed due to having 5 max concurrent tasks running. To increase this limit go to node page] etc would mean that when it is hit, customers would just go there and update it without confused support issues. (see below source).

Source: http://help.octopusdeploy.com/discussions/problems/44551

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Have message on task page if the task is queued due to the task cap on node](https://trello.com/c/hxPIj5v3/27-have-message-on-task-page-if-the-task-is-queued-due-to-the-task-cap-on-node)

**Comment by tothegills** [comment]
Also indicate when a task is waiting on Tentacle upgrade.

**Comment by vanessalove** [comment]
this is what it looks like when a task is queued due to an existing release: (very obvious on what its waiting on and customers know what this is like)
<img width="1259" alt="task-cap-queued-due-to-deployment" src="https://user-images.githubusercontent.com/7697660/28505471-a6e1e79c-7067-11e7-8ace-bc92285928e4.png">

this is what it looks like when its due to task cap: (?!?! why is it queued ??!?!)
<img width="1141" alt="task-cap-queued-due-to-cap" src="https://user-images.githubusercontent.com/7697660/28505478-b8bcf6a0-7067-11e7-8a71-b04938129251.png">
<img width="1132" alt="task-cap-queued-due-to-cap-task-list" src="https://user-images.githubusercontent.com/7697660/28505482-bd192e58-7067-11e7-8086-e9e847d70aae.png">

**Comment by vanessalove** [comment]
My thought was that for the second image, a message between the task summary header and the task progress it puts a message stating its queued due to task cap

**Comment by michaelnoonan** [comment]
We've done some work to make it easier to understand why a task hasn't started yet, and to fix some bugs which caused misinformation (see #3723).

I can think of a few cases where we could show a banner at the top of the tasks page, explaining why new tasks may not be starting:

1. All the nodes in the Octopus Server cluster are busy running tasks and have reached their task cap (new tasks won't start) - this issue
2. One or more of the nodes are in drain mode, possibly preparing for server maintenance.
3. The entire task queue has been paused (see #3703)

**Comment by michaelnoonan** [comment]
We have done further work around this issue over the last several months.

We show more informative messages on the task page describing when a task will execute.

![image](https://user-images.githubusercontent.com/1627582/54092936-dca2c900-43dd-11e9-89dd-0a43163eac40.png)

We show tasks blocking the current task from starting.

![image](https://user-images.githubusercontent.com/1627582/54092956-09ef7700-43de-11e9-8aca-2780e0280062.png)

We show a system-wide banner when something is preventing the Octopus Server cluster from processing tasks.

![image](https://user-images.githubusercontent.com/1627582/54092988-5a66d480-43de-11e9-9446-434bbf110618.png)

I believe this caters for all the known cases, including when a server cluster is too busy to start new tasks. 

If you find this issue and think there is more we can do to make the situation clearer, please comment on this issue while it remains unlocked, or reach out to support@octopus.com. :)

**Comment by michaelnoonan** [comment]
Server Cluster Health Status added in https://github.com/OctopusDeploy/OctopusDeploy/pull/3204
`2018.9.15`
