### ISSUE TITLE
Removing last machine with role scoped to variable causes unexpected UX display 

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2387]
### Problem

Assume that I have just 1 machine with the role `MyRandomRole`, and some other machine with a different role.
![image](https://cloud.githubusercontent.com/assets/1830666/13241871/e0c73d96-da3a-11e5-8275-030a42f432ca.png)

I then set up my variables such that one variable is scoped to _just_ `MyRandomRole` and another variable is scoped to _both_ `MyRandomRole` and some other `tentacle` role.
![image](https://cloud.githubusercontent.com/assets/1830666/13241845/b5c08f76-da3a-11e5-86bc-f8e3e83ad947.png)
`Connection` will now be null by default, but have a value for machines with `MyRandomRole`

I then proceed to delete this machine
![image](https://cloud.githubusercontent.com/assets/1830666/13241898/2176d504-da3b-11e5-8402-8b5656c86fc4.png)

**My Variables now no longer show the scopes for `MyRandomRole`**
![image](https://cloud.githubusercontent.com/assets/1830666/13241908/3afca35a-da3b-11e5-8384-e9b4f75399f4.png)
Notice the `,` character where the 2 roles were once shown. This appears to be because the UI hides roles if there are no machines currently with it. Note the values are correctly still in the database.
![image](https://cloud.githubusercontent.com/assets/1830666/13241945/9138d3c4-da3b-11e5-9a50-b5537932af00.png)
### What's the matter?

Behaviourally everything is correct. The variables scopes should _not_ be removed and variables with just these scopes should also _not_ be removed. This is to allow for these roles to be applied to other (new or existing) machines at a later date. Roles to not get removed from the system with the deletion of their respective machines.

With this UI set up however, it could be very easy for users to be confused about which variables will be applied since it now appears at though `Connection` has a global value, when it actually doesn't (during deployment it knows role scoping is still applicable). 
The users may then adjust this "fake global" value to get their required values, which would be ineffectual at best, and damaging at worst.

Source: http://help.octopusdeploy.com/discussions/problems/44560-scoped-variable-becomes-global-when-machine-removed

**Comment by thebigmoosey** [comment]
Another report of this: http://help.octopusdeploy.com/discussions/problems/49639

**Comment by droyad** [comment]
With 4.0, it now looks like this:

![image](https://user-images.githubusercontent.com/1687639/34596328-7d4124bc-f22a-11e7-9bc7-d88125be9727.png)

Not ideal, I have no way of knowing what the role value is, but perhaps enough to close this issue  @zentron @thebigmoosey ?

**Comment by thebigmoosey** [comment]
@droyad Just curious, does the "missing resource" chip give you any additional context on mouseover?

**Comment by droyad** [comment]
@thebigmoosey It does indeed:
![image](https://user-images.githubusercontent.com/1687639/34601205-a10771b4-f246-11e7-9eeb-838493fd24f0.png)

And what do you know, when I go an edit it, I can see it and remove it

![image](https://user-images.githubusercontent.com/1687639/34601247-cd91624e-f246-11e7-8fe3-e728ef3e8437.png)

This is the opposite experience to the tenants page, see #2989
