### ISSUE TITLE
Offline deployment step variable json files contain all variables

### ISSUE THREAD

**Issue by roryprimrose** [OctopusDeploy/Issues#2388]
When playing with offline deployment functionality, I noticed that the variable json files for each deployment step contain a snapshot of all the variables for the project that target that deployment context. This creates a large amount of white noise should anyone want to edit those variable files.

It would be great if Octopus Deploy would only include the variables in the step json file that are used by the step. Finding a variable used by a single step in order to change its value will then be much easier and less error prone. As is, the risk is that someone will update the correct variable but for the wrong step.

**Comment by jrestall** [comment]
+1 Although we do our best to get the variables correct before a production deployment, sometimes URLs or accounts need to change unexpectedly and having to update 20+ variable files is a real pain late at night.

I'd love it if this was simplified with ideally a single variables file.

**Comment by vanessalove** [comment]
Sorry GitHub is for our working items, and everything created goes through a process. If you could please use our support channels so we can ask questions and triage the matter. Thank you.

https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
