### ISSUE TITLE
Backspace and Tab function unexpectedly for Environments field of Step Details

### ISSUE THREAD

**Issue by kkalitowski** [OctopusDeploy/Issues#2394]
Pressing the keyboard's backspace button when the cursor is in the Environments field should remove an environment. This works properly when setting up a machine in the Environments view / Deployment Target settings screen.

It does not work for the Environments field in a Step Details screen. On the Step Details screen the first backspace takes the cursor out of the field and the second backspace sends the browser back to the previous page.

The Tab key has an issue in this field too. In the Deployment Target screen if you begin typing the name of an environment I would expect Tab to complete the partially typed name and leave the cursor in the field. It does complete the name, but moves to the next field.  On the Step Details screen it also completes the name, but instead of going to the next field the browser jumps to the top of the page.

These behaviors were experienced in version 3.3 Beta 2 using Chrome 48.

**Comment by vanessalove** [comment]
Sorry GitHub is for our working items, and everything created goes through a process. If you could please use our support channels so we can ask questions and triage the matter. Thank you.

https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md
https://octopus.com/company/roadmap/why-was-this-closed
