### ISSUE TITLE
Script behaviour inconsistent between script step and deployment script

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2396]
Scripts in a script step appear to have some behavioural differences to scripts run in deployment scripts.

Consider the following script
```
$doesnt = Get-Date –displayhint time
Write-Output "Doesnt Work"
Write-Output $doesnt

Write-Output --------------------

$works = Get-Date -displayhint time
Write-Output "Works"
Write-Output $works
```

the `-` in the first and second command are actually different characters.

Note the end result by using this same script in two different conditions.

![image](https://cloud.githubusercontent.com/assets/1830666/13338935/b6b79194-dc70-11e5-8ebb-a1b80f6d42dc.png)

We should make sure the scripts work consistently regardless of how\where they are being executed. 

Source: http://octopus-deploy.tenderapp.com/discussions/problems/44546-seeing-output-in-script-console-but-not-in-deploy-log

**Comment by MJRichardson** [comment]
Release note:Configured scripts in package steps now support Unicode characters.
