### ISSUE TITLE
Add brief example of script in subfolder for Script file name field.

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2400]
![scriptfilenameexamples](https://cloud.githubusercontent.com/assets/6180562/13406008/09ef66ca-df00-11e5-8419-54f4150a869b.jpg)

*E.g. MyScript.ps1, Scripts\MyScript.ps1*

It has been asked already: http://help.octopusdeploy.com/discussions/questions/7372

**Comment by MJRichardson** [comment]
Release note:Added example of relative path for script file location in package to on-screen documentation.
