### ISSUE TITLE
Warning we will deprecate Azure Targets in 3.4

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2401]
- [ ] Blog post explaining we will deprecate Azure Targets in 3.4
- [ ] Dismissable warning on Environments page if using an Azure Targets
- [ ] More specific warning on new Deployment Target page
- [ ] Warning message when deploying to an Azure target

**Comment by michaelnoonan** [comment]
We want to make sure there's a good answer for Regions in Azure without Azure Deployment Targets before doing this.

**Comment by vanessalove** [comment]
Updated decision on what to do:
[ ] documentation on how to move from Azure targets
[ ] log warning in the deployment when using Azure targets

**Comment by vanessalove** [comment]
Also logged in the trello - but this is for the warning release notes
