### ISSUE TITLE
Updating Calamari on multiple SSH endpoints fails due to file lock

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2402]
![image](https://cloud.githubusercontent.com/assets/1830666/13413724/8b85dda2-df98-11e5-86b6-b45228db4df6.png)

Source: http://help.octopusdeploy.com/discussions/problems/44699

**Comment by michaelnoonan** [comment]
Release Note: Fixed an issue that was preventing Calamari from updating on multiple SSH endpoints due to a file lock
