### ISSUE TITLE
Octopus API not honoring permissions on Machines.

### ISSUE THREAD

**Issue by Excommunicated** [OctopusDeploy/Issues#2406]
Scenario,
I have a Team that has a single role of Project Deployer. That team is also scoped to a single project and a single environment. When I Query the API as a member of that team, I see only the Projects (/api/projects) and the environments (/api/environments) that I should see. But when I query Machines (/api/machines) I see all machines. I would have thought that this list would be filtered to the machines that are in environments that I have access to, rather than all machines?

**Comment by michaelnoonan** [comment]
Hi @Excommunicated, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong!
