### ISSUE TITLE
OctopusRepository "repository" properties need to be exposed by the interface

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2408]
Customers using the Octopus Client nuget package were unable to create Channels using `IOctopusRepository` because the Channels repository is not exposed by the interface (but it _is_ exposed by the implementation).

Upon investigation, various other repositories are also missing from the interface, so these will need to be added.

Recommend writing a unit test to make sure the number of repositories exposed by the implementation are also exposed by the interface (Eg. do some reflection between the properties that end in the word “Repository” and make sure the counts match between interface and implementation to stop this from getting out of sync again).

...and can we please alphabetise these properties in both the interface and implementation classes :)

Source: [https://secure.helpscout.net/conversation/177088498/5323/?folderId=801354](url)

**Comment by tothegills** [comment]
Relates to https://github.com/OctopusDeploy/Issues/issues/2391

**Comment by alfhenrik** [comment]
Will be fixed as part of #2391
