### ISSUE TITLE
Octo.exe fails to import/export a project's channel information

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2410]
When running an export/import of a Project that has Channels using Octo.exe, the Project's Channel information disappears.

A quick look at Octo.exe's `ProjectImporter.cs` and `ProjectExporter.cs` make me believe Channels have not yet been included in the import/export process in Octo.exe and need to be added.

Source: https://secure.helpscout.net/conversation/177178653/5327/?folderId=801354

**Comment by alfhenrik** [comment]
Fixed in https://github.com/OctopusDeploy/Octo.exe/commit/cf97bf34ef1778968be059018d3400c1ede2b60f

**Comment by alfhenrik** [comment]
Release note: `Octo.exe` Import and export project channels
