### ISSUE TITLE
Octo.exe and TeamCity plugin support for pushing packages

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2411]
We're making some improvements to Octo.exe and the TeamCity plugin to support the future direction of ASP.NET 5/Core 1. The new .NET is all about command line, and "publishing" is finally a first class citizen for all application types (web, console, service, etc.). This makes OctoPack, which had a lot of smarts around what made sense to include in a package, somewhat obsolete. 

What's missing is:

 - An easy way to turn a published output folder into a zip
 - An easy way to push it to an Octopus server

The changes we are making are:

1. `Octo.exe push`, which will push packages (.nupkg, .zip, etc.) to the built-in Octopus repository
2. TeamCity plugin support for the above, which will also support artifact path-style patterns
3. `Octo.exe pack` improvements to allow creating a simple Zip (currently it is `.nupkg` only)

**Comment by PaulStovell** [comment]
Here's what the new TeamCity build runner looks like for pushing a package. The wildcards make it possible to create packages directly from a folder:

![2016-03-03_23-47-00](https://cloud.githubusercontent.com/assets/47085/13512832/d29c9152-e1e8-11e5-9835-3c4d681fa937.png)

**Test criteria**:

 - [ ] Simple patterns like `Foo.zip`
 - [ ] Wildcarded patterns like `dir/**/*.zip`
 - [ ] Transform patterns like `dir/**/* => foo.zip`
 - [ ] Attaching the generated packages as artifacts in TeamCity (on or off)
 - [ ] Using the 'force overwrite' option on/off

**Comment by PaulStovell** [comment]
Here's the command syntax for `Octo.exe push`:

```
Octopus Deploy Command Line Tool, version 3.3.8-ci.11+Branch.master.Sha.f56de1d580f834ac7e38ddcad7af330cd58ce2c5

Usage: Octo push [<options>]

Where [<options>] is any of:

Package pushing:

      --package=VALUE        Package file to push. Specify multiple packages
                             by specifying this argument multiple times:
                             --package package1 --package package2
      --replace-existing     If the package already exists in the repository,
                             the default behavior is to reject the new
                             package being pushed. You can pass this flag to
                             overwrite the existing package.

Common options:

      --server=VALUE         The base URL for your Octopus server - e.g.,
                             http://your-octopus/
      --apiKey=VALUE         Your API key. Get this from the user profile
                             page.
      --user=VALUE           [Optional] Username to use when authenticating
                             with the server.
      --pass=VALUE           [Optional] Password to use when authenticating
                             with the server.
      --configFile=VALUE     [Optional] Text file of default values, with one
                             'key = value' per line.
      --debug                [Optional] Enable debug logging
      --ignoreSslErrors      [Optional] Set this flag if your Octopus server
                             uses HTTPS but the certificate is not trusted on
                             this machine. Any certificate errors will be
                             ignored. WARNING: this option may create a
                             security vulnerability.
      --enableServiceMessages
                             [Optional] Enable TeamCity or Team Foundation
                             Build service messages when logging.


Or use Octo help <command> for more details.
```

**Comment by PaulStovell** [comment]
Command help for `Octo.exe pack` now:

![image](https://cloud.githubusercontent.com/assets/47085/13519247/82b480b2-e221-11e5-84aa-b530b51d7f7c.png)

**Comment by PaulStovell** [comment]
OK, for this to ship, we need to:

1. Tag and release `Octopus.Client` 3.3.3 to NuGet. It contains the fix for uploading large packages. 
2. Pull the new `Octopus.Client` into `Octo.exe`, tag and build it
3. Pull the new `Octo.exe` into the TeamCity plugin

Currently the TeamCity plugin contains a locally built version of `Octo.exe`.

**Comment by PaulStovell** [comment]
Relevant commits: 

TeamCity plugin changes: https://github.com/OctopusDeploy/Octopus-TeamCity/commit/7100ece536db18da79cb8b955299d245d9fd75c2
Octo.exe push: https://github.com/OctopusDeploy/Octo.exe/commit/f56de1d580f834ac7e38ddcad7af330cd58ce2c5
Octo.exe pack: https://github.com/OctopusDeploy/Octo.exe/commit/97ad0a522585a1b92921a6c09ef919cd4c6c02d8

**Comment by alfhenrik** [comment]
Release note: Add `push` command to `Octo.exe` and a `push package` TeamCity plugin build runner

**Comment by Stockholmsnovis** [comment]
Is it possible to user the TeamCity plugin to ONLY create a .zip package and NOT publish the package to any feed? Why you might ask? Well, OctoPack and octo.exe does a good job of "packaging" a .NET web site and we would like to user this packaging functionality to create an On-Premise-inatallable version of our web site. Yes, I am aware of offline deployment targets, but that doesnt cut it in our case.
