### ISSUE TITLE
Octopus crashes when Windows updates are installed

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2413]
Octopus running on Windows 2012 crashes when the updates KB3123479, KB3109853, and KB3081320 are installed.  One of the updates is SHA1 deprecation.

Regenerating the Octopus-Tentacle certificate does not help.

See http://help.octopusdeploy.com/discussions/problems/44707

**Comment by droyad** [comment]
As per the linked discussion, enabling the “CNG Key Isolation” windows service resolved the issue.
