### ISSUE TITLE
Accepting an Invitation requires refreshing the browser for team(s) to take effect

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2416]
1. Create invitation to Octopus Administrators
2. Navigate to the invitation link using an InPrivate session
3. Fill out the invitation details and save
4. The Octopus UI displays like I'm a guest
I could get the correct UI displayed by:
  a. Refreshing the page (F5 in the browser)
  b. Sign Out/Sign In

I confirmed the correct data is saved to the DB when accepting an invitation, it appears to be more of a UI bug. Does this sound right to you, or have I missed something in my reproduction?

Source: http://help.octopusdeploy.com/discussions/problems/44771-permissions-are-not-assigned-via-the-invite-user-link

**Comment by vanessalove** [comment]
Decided to close this issue as a refresh or logging in and out again seems like a valid easy workaround.
