### ISSUE TITLE
Variable substitution behaves differently between inline and package scripts

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2421]
Octostache variable substitution does not appear to be working from scripts inside a package.

We wrote a basic script to test a variable that contained the text “HiThereAndHello":
```
Write-Host "Get to da choppa!"

$markConnectionString = $OctopusParameters["MarkConnectionString"];
Write-Host "1 (OctopusParameters). $($markConnectionString)"

$markConnectionString2 = "#{MarkConnectionString}";
Write-Host "2 (Octostache syntax). $($markConnectionString2)"

Write-Host “Finished”
```
When run inline, this works as expected, but when run from inside a package, the substitution does not occur.
![variable-sub-octostache](https://cloud.githubusercontent.com/assets/819605/13592591/4ce9d3a8-e53f-11e5-8a9f-f32ec2425474.jpg)

Possibly related to [#2396](https://github.com/OctopusDeploy/Issues/issues/2396)

Source: http://help.octopusdeploy.com/discussions/questions/7436

**Comment by michaelnoonan** [comment]
Release Note: When using script steps that source the script from a package, variable substitution is now automatically performed, behaving the same as inline scripts
