### ISSUE TITLE
Upgrade to WebDeploy 3.6

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2422]
WebDeploy 3.6 is no longer beta, and brings a few notable benefits, particularly:
- proxy support
- checksum error fixes
- ASP.NET Core support

Only problem is, there is no NuGet package for it, so we might have to bundle it ourselves.

https://azure.microsoft.com/en-us/blog/web-deploy-3-6-beta-released

**Comment by michaelnoonan** [comment]
Source: https://octopus.com/blog/aspnet-core-build-and-deploy#comment-2572944050

**Comment by zentron** [comment]
From User Request: 
> One issue I am having is deploying an .Net Core Web Application to Azure Web Apps. The current web app deploy step doesn't appear to allow deploying above the site/wwwroot folder, which is problematic because it appears that .Net core needs to be deployed to /site/.

https://github.com/OctopusDeploy/Issues/issues/2443#issuecomment-199801896

**Comment by mstum** [comment]
Hi, just checking if there was an update to this, of if there's an alternate way for us to deploy to Azure through Octopus (e.g., PowerShell scripting?)

**Comment by michaelnoonan** [comment]
Hi @mstum. The ASP.NET team have pushed `Microsoft.Web.Deployment.3.6.0` to nuget.org now, so we're unblocked and can progress this issue.

Depending on what you're blocker is, you have a few options:
1. Wait for us to finish this enhancement
2. For certain uses of ASP.NET Core, use one of the workarounds described here: http://help.octopusdeploy.com/discussions/problems/44863-deploying-file-to-azure-web-app-site-folder
3. Build your own custom Calamari updating to WebDeploy 3.6 and adding any custom arguments to https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari.Azure/Deployment/Conventions/AzureWebAppConvention.cs

**Comment by gmokbel** [comment]
FWIW, I forked, upgraded the nuget package and set it up on a test instance of Octopus.

Azure Deployments are now working from behind the corporate proxy, thanks @michaelnoonan . 
Looking forward to an official release.

**Comment by mstum** [comment]
Is there a chance to have this part of the 3.4 release? (Not sure how far out the ASP.net Core 1.0 milestone is). We're currently looking at scripting using Msdeploy directly (instead of a custom calamari which makes upgrading hard) but would love to see official support.

Alternatively, is there a plan to have a "Set Calamari per project/process step" option? That would be a powerful, but also complicated feature for edge cases, not sure if that's worth it.

Thanks!

**Comment by vanessalove** [comment]
@mstum aiming for the 3.4 release. The only reason we want to ship it then is so it gets the most amount of testing rather than in one of our patch releases.
