### ISSUE TITLE
Long target name overlay

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2425]
We seem to break lines just fine if the name has a space or a hyphen. If it doesn't or uses dots as separators (IP scenarios) the name just goes on an overlays with the next target.

We couldn't decide on the expected logic for this on the support call, so might be worth bringing it to the hive mind when someone grabs it.

![3 2 19](https://cloud.githubusercontent.com/assets/6180562/13703862/88a9b7fc-e777-11e5-9c59-be7373da6143.JPG)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Long target name overlay](https://trello.com/c/O0KKnz71/24-long-target-name-overlay)

**Comment by pawelpabich** [comment]
@Dalmirog I'm planning to re-use what @jess-ross did for release numbers. Would that be ok? 
![image](https://cloud.githubusercontent.com/assets/347637/22194150/41659284-e18c-11e6-8251-6bd5445b3651.png)

**Comment by pawelpabich** [comment]
Cool

![image](https://cloud.githubusercontent.com/assets/347637/22235794/5dd321e0-e24d-11e6-9017-e45d525aec45.png)

**Comment by pawelpabich** [comment]
Release Note: Long target names don't overlap each other anymore.
