### ISSUE TITLE
Upgrade NuGet libraries to 3.0

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2428]
To fit in with 3.4 is possible otherwise 3.5 - would need to know that it is stable.
Want to allow for SemVer 2.0 support amongst other things.

This is a bit of a placeholder issue but will one day moved from 'blocked' to 'ready'

**Comment by ccamburn** [comment]
Hi Vanessa,

Does this change to 3.0 libraries mean that #1071 will then be fixed? (I know it's not an Octopus issue, but rather a nuget 2.X issue, hence why I ask)

**Comment by vanessalove** [comment]
@ccamburn yes that is the hope and intention

**Comment by johnbowker** [comment]
:+1: for this to happen as soon as possible.

**Comment by antonvk** [comment]
Hi,

any update on when this will be released?
