### ISSUE TITLE
Polling Tentacle registration API calls should use appropriate TLS version

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2429]
As reported in: http://help.octopusdeploy.com/discussions/problems/44884

**Comment by MJRichardson** [comment]
Release note:Tentacle Manager now supports all TLS versions

**Comment by MJRichardson** [comment]
Re-opening, as the change should be made for Tentacle.exe as well as Tentacle.Manager.exe,

**Comment by vanessalove** [comment]
created new issue: https://github.com/OctopusDeploy/Issues/issues/2483
cant reopen already released, need to keep track of release notes and milestone.
