### ISSUE TITLE
Switching a script step from "script in package" to "inline script" still attempts to download the package

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2438]
- Create a script step
- Source the script from a package
- Switch to source the script inline
- Running a deployment with this script will still attempt to acquire the package even though it is an inline script now.

Related to OctopusDeploy/Issues#2431

**Comment by droyad** [comment]
Problem only occurs when "Run on Deployment target" is chosen in the step definition

**Comment by droyad** [comment]
Changes made to the Script and Azure Script steps

- UI clears out fields (properties) that are hidden (ie not valid) when the script source is changed
- API validates that these properties are not present
- Upgrader removed invalid properties from existing data

To test, before checking out the branch, setup a project with a script and Azure script step. Fill out both the inline and package properties and save. Note that when you view the steps, and switch the script source, the field values are retained. After checking out the branch and running, this should no longer be the case and the steps that where just created are fixed up.

**Comment by droyad** [comment]
UI behaviour Before:
![before](https://cloud.githubusercontent.com/assets/1687639/14442767/dd61e2c2-007e-11e6-925c-fc97bda22830.gif)

UI behaviour after:
![after](https://cloud.githubusercontent.com/assets/1687639/14442788/f7a43766-007e-11e6-8b5d-311cf31507aa.gif)
