### ISSUE TITLE
ARC fails to find latest package version in NuGet Package step template

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2442]
NuGet Package Id is not properly evaluated in ARC when using a NuGet Package step template.

Step template:
![image](https://cloud.githubusercontent.com/assets/1035315/13936606/92e81556-f00a-11e5-952d-abff0059f11e.png)

Step template parameters:
![image](https://cloud.githubusercontent.com/assets/1035315/13936610/991ac400-f00a-11e5-9b19-51da03c8cab7.png)

Deployment process:
![image](https://cloud.githubusercontent.com/assets/1035315/13936618/a7b71f0e-f00a-11e5-9395-cfd3cce9248e.png)

Octopus Server log:
![image](https://cloud.githubusercontent.com/assets/1035315/13936633/c2d511ba-f00a-11e5-8d32-faff09de0c30.png)

Manually creating release:
![image](https://cloud.githubusercontent.com/assets/1035315/13936659/df41c5dc-f00a-11e5-84ed-2ffbe33cbae4.png)

Source: https://secure.helpscout.net/conversation/182396642/5693/?folderId=571728

**Comment by vanessalove** [comment]
There are a couple of similar issues around step templates as nuget package IDs.
1. they are not shown correctly in the process page https://github.com/OctopusDeploy/Issues/issues/2193
2. they are not cleaned up with retention policies
^no issue yet I was going to discuss, but it seems very related 

could all 3 be done at once?

**Comment by tothegills** [comment]
Release note: Automatic release creation works for step template package steps
