### ISSUE TITLE
Add support for "No Managed code" for App Pool .NET CLR

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2443]
Sources:

```
https://secure.helpscout.net/conversation/173908237/5132
https://secure.helpscout.net/conversation/148028737/3641
http://help.octopusdeploy.com/discussions/beta-testing-feedback/38
https://twitter.com/StrangeWill/status/711020495286706177
http://help.octopusdeploy.com/discussions/problems/44939
```

PS snippet that does this: https://gist.github.com/Dalmirog/bd5b518147c310ec2a22

Uservoice sugestion: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/12522726-ability-to-set-application-pool-clr-to-no-managed

**Comment by PaulStovell** [comment]
Can we get a double check on this too:
https://octopus.com/blog/aspnet-core-build-and-deploy#comment-2572944050

May need to change the step type to allow a different path to be specified.

**Comment by droyad** [comment]
Added in commit https://github.com/OctopusDeploy/OctopusDeploy/commit/26f13e43901020e8f2b64f24f15b026ea6b75da7
