### ISSUE TITLE
Elastic and Transient Environments

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2445]
Elastic environment and transient machine support (enabled via machine policies) to control certain aspects of a machine's lifecycle.

**Comment by thebigmoosey** [comment]
The first early access release of 3.4 which includes some progress on elastic environments has been made available:
https://octopus.com/blog/octopus-deploy-3.4-eap
http://docs.octopusdeploy.com/display/ODEAP/What+is+the+EAP

Following on from our [RFC](https://octopus.com/blog/rfc-cloud-and-infrastructure-automation-support), this release introduces the concept of a machine policy, which allows you to control certain aspects of a machine's lifecycle.

For users interested in the progress of the elastic environments feature, we would advise downloading and trying out the 3.4.0-alpha001 build we have made available to get an idea of what direction this is headed.

**Comment by thebigmoosey** [comment]
After some great community feedback from the EAP release, we’re starting to make some movements on the auto-deployment feature of elastic environments (as well as more options to help customise health checks). We quickly realised that customers would need a way to opt-in or opt-out of certain behaviour (skipping offline machines for example), otherwise this would risk ending up as an “all or nothing” feature. So now we’re investigating the concept of allowing “machine policy overrides per project”.

The direction we’re heading can be seen from the attached mockups (see below). The points of interest are the changes around “machine connectivity” and the way of opting _out_ of auto-deploy and opting _in_ for skipping offline machines. The mockups also explain our reasoning and the integration point with projects (notably a new _Connectivity_ screen where users can override certain policy behaviour).

If you have any thoughts, concerns or suggestions, please drop us a line via the [discussion forums](http://help.octopusdeploy.com/discussions/beta-testing-feedback). And as always, “have nice day”.

## Machine policies list screen:
![machine policies list](https://cloud.githubusercontent.com/assets/819605/14445353/b58559e4-008f-11e6-8444-107d4c372c58.png)

## Machine policy screen:
![machine policy screen](https://cloud.githubusercontent.com/assets/819605/14445354/b7a9a81a-008f-11e6-8497-ff678648aa98.png)

## Machine screen (selection of policy):
![machine screen](https://cloud.githubusercontent.com/assets/819605/14445357/bdc05ad2-008f-11e6-8f47-6c844aa46a9f.png)

## Project connectivity screen (overrides for policy):
![project connectivity screen](https://cloud.githubusercontent.com/assets/819605/14445358/bff52152-008f-11e6-9bfd-19e8fb0df3a1.png)

**Comment by michaelnoonan** [comment]
Release Note: You can now manage elastic and transient environments more easily with Octopus Deploy
