### ISSUE TITLE
SSH deployments are currently limited to executing sequentially

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2446]
It's a known limitation of SSH deployment's that they can't execute in parallel to multiple servers.  This causes tasks to be executed one at at time and display busy messages.  

Source: 
http://help.octopusdeploy.com/discussions/problems/45063

**Comment by zentron** [comment]
This feature has been added but uses the target fingerprint as a discriminator to still block tasks that take place on the same endpoint. Its not a perfect solution but should allow for most use cases.

**Comment by zentron** [comment]
Release Notes: Allow parallel SSH tasks to take place on targets with different fingerprints.
