### ISSUE TITLE
Deploying a release already deployed to an Environment should skip Lifecycle validation

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2449]
Imagine a lifecycle like:

`Dev -> Test -> Production`

Let's say Production already had 3.4.3 deployed into it:

`Dev (3.4.3) -> Test (3.4.3) -> Production (3.4.3)`

Then you added Pre-Production with nothing deployed:

`Dev (3.4.3) -> Test (3.4.3) -> Pre-Production (nil) -> Production (3.4.3)`

When trying to deploy 3.4.3 onto a new machine in Production (think AWS Auto Scale Group) - we will currently block the deployment because of the Lifecycle constraint.

Instead of blocking the deployment, we should recognise that 3.4.3 is already in Production, and we should allow the deployment onto the new machine without considering Lifecycle at all.

In pseudo-code:

bool IsValidDeployment(environment, release, lifecycle) {
  if (release already deployed to environment) return true;
  // Now do normal lifecycle checks
}

Source: http://help.octopusdeploy.com/discussions/problems/45165-adding-environment-broke-my-prod-warninginformational

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploying a release already deployed to an Environment should skip Lifecycle validation](https://trello.com/c/7P5yWJ6U/456-deploying-a-release-already-deployed-to-an-environment-should-skip-lifecycle-validation)

**Comment by zentron** [comment]
If we have 
`Dev` -> `Stg` -> `Prod`
and deploy to
`Dev` + `Stg` 
Then add a `Pre-Stg` phase, this fix will allow `Stg` to still deploy. 

This will mean that `Prod` should also still be able to continue, even though it hasn't had a deployment, but because its immediately dependant phase has been completed.

**Comment by zentron** [comment]
Release Note: Deploying a release to an already deployed to an Environment skips Lifecycle validation
