### ISSUE TITLE
Octopus.Client does not surface option to include release notes when getting packages from internal repository

### ISSUE THREAD

**Issue by campearce** [OctopusDeploy/Issues#2450]
Latest version of Octopus.Client as of this report.
Version: 3.3.4

By default listing packages from the built-in internal repository does not include the release notes.
The client does not surface the option in either the `BuiltInPackageRepository.LatestPackages` or the `BuiltInPackageRepository.ListPackages` call to include the release notes in the response.

Looking at the call the UI makes to get packages with the release notes in there, it is including a query string parameters `includeNotes=true` to make the API return these.

I can call the API manually to get this information back from the client, but would be nicer if this was surfaced as an option in those calls.

**Comment by vanessalove** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
