### ISSUE TITLE
Allow Web Deployment into the /site folder

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2454]
https://octopus.com/blog/aspnet-core-build-and-deploy#comment-2572944050

One issue I am having is deploying an .Net Core Web Application to Azure Web Apps. The current web app deploy step doesn't appear to allow deploying above the site/wwwroot folder, which is problematic because it appears that .Net core needs to be deployed to /site/.

**Comment by droyad** [comment]
Would be fixed by #2422

**Comment by bjcull** [comment]
Is there any doco on how to achieve this? I'm on 3.4.0-beta1 but majorly stuck with how to alter calimari to get things working.
