### ISSUE TITLE
Add argument to Octo.exe or Project definition to pick up only release packages by default

### ISSUE THREAD

**Issue by fruffin** [OctopusDeploy/Issues#2456]
At the moment Octo.exe and the Octopus UI include pre-release packages by default.
It would be good if there was a way to turn that off so that only release packages are picked up in case a release is created (by Octo.exe or the UI) without specifying the package version number.

This is a problem for us when we try to automatically deploy the latest version of our application to our staging environment (which should have only release packages)

Another alternative would be to be able to pass "Latest" or "LatestStable" as the version name.

**Comment by vanessalove** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
