### ISSUE TITLE
Allow executing SSH scripts directly without going through uploading & mono

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2458]
Currently, running SSH scripts involves uploading scripts, variables and calamari via SFTP scripts. These then need to be wrapped and bootstrapped within Calamari on the remote target which, on POSIX machines require also installing mono. This whole process can take minutes under a slow connection, and every new update to the server potentially requires a new version of Calamari to be sent across the wire before a script can be run.
![image](https://cloud.githubusercontent.com/assets/1830666/14480439/69a40380-016c-11e6-9604-a020a0cf77ab.png)

For users who just want to run a script, without the bells and whistles offered by Calamari, this is all unnecessary overhead. 
Instead a new feature has been developed (in a branch) which can execute the scripts the user provides directly over the open SSH connection without transferring any files.
![image](https://cloud.githubusercontent.com/assets/1830666/14480444/76e4d0d8-016c-11e6-8932-de3925637056.png)
## The Flip Side
- The shell will execute under whatever the default shell for that logged in user and not necessarily bash. Standard scripts currently require wrapping in another script file so that it can be explicitly called via `/bin/bash`. This is to ensure our bootstrapping logic works against the bash syntax
- As result of the above point, the user will loose the ability to use some of the helper functions like`get_octopusvariable` or `set_outputvariable`. They can however set output variables by explictly writing the command strings (`##octopus[setVariable`) to the output. 
- Since no SFTP connection takes place (and the helper method doesn't exist) it currently doesn't support artifacts. Perhaps we still attempt to try connect and retrieve if a user goes to the effort of writing the `##octopus[createArtifact` command?
- Some features of the current script step are unsupported, i.e. script from package. 
### Further Decisions

**How should we expose this to the UI?**
Currently this is just done for dev purposes based on the presence of a variable however this potentially should be a new step of its own `Naked Scripts` since there are many options in the current step that are no longer relevant and it probably already has enough toggles and switches. 
My only concern is adding another (very specific) step type to the list for users to select. If/When we have this UI a little more broken down it would be a much more obvious decision.
We also need to make it clear to the user that its _not necessarily_ bash, even if we use the bash syntax highlighting.

**How (if at all) does this affect health checks?**
Health checks to SSH targets currently check for presence of mono, bash etc. Can users disable/change these checks if they only intend on using this naked scripting?

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Naked SSH](https://trello.com/c/MOqLTzWl/3-naked-ssh)

**Comment by zentron** [comment]
![image](https://cloud.githubusercontent.com/assets/1830666/23001405/d0d4138a-f430-11e6-9308-c89e1447b3f6.png)
New options in Machine Policy to only perform connection test (skips dependency tests)

**Comment by droyad** [comment]
Resolved with the release of Raw Scripting
