### ISSUE TITLE
Allow editing window size for step when set to "Run in parallel..."

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2461]
Once you set a step to "Run in parallel" you can only edit the window size for the first step. This causes confusion as users might think that the setting is inherited to the subsequent steps when they really aren't.

To change the window size, you have to change the start trigger, edit the window size, change the start trigger back again and then save the step.

We should allow editing the window size for steps that are set to "Run in parallel..."

Source: http://help.octopusdeploy.com/discussions/problems/45495

**Comment by MJRichardson** [comment]
Release note:Allow editing of window size for subsequent parallel steps
