### ISSUE TITLE
Pushing a package with NuGet 3.4 causes a 500 error

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2464]
If the `push` command is used with NuGet `3.4` against the built in nuget feed, nuget will report `Response status code does not indicate success: 500 (Internal Server Error).` and the Octopus logs will show `System.ArgumentException: Illegal characters in path`.

This is due to a change in the `Content-Disposition` header to include a `filename*` property in addition to the `filename` property.

**Comment by markryd** [comment]
We use Nancy's parsing of the header to get the filename. See https://github.com/NancyFx/Nancy/blob/master/src/Nancy/HttpMultipartBoundary.cs

Looks like there regex is looking for double quoted values, which aren't there anymore.
