### ISSUE TITLE
Object reference not set to an instance of an object whilst "Acquiring Package" from internal feed during NuGet push ?replace=true

### ISSUE THREAD

**Issue by megakid** [OctopusDeploy/Issues#2469]
During a package deployment, I had another process that was pushing the same packages to the internet nuget feed using the ?replace=true.  Ideally I want a ?ignoreexisting=true but had to settle for replacing the packages when pushing them using nuget.exe.

The issues that occur are:

1. During the `nuget.exe push ...?replace=true` we get a server 500 error:

    20-Apr-2016 10:49:14	  Pushing MyService 2.15.0.3245 to 'http://octopus-server/nuget/packages?replace=true'...
    20-Apr-2016 10:49:16	  Failed to process request. 'Internal Server Error'. 
    20-Apr-2016 10:49:16	EXEC : The remote server returned an error : (500) Internal Server Error.. [E:\Bamboo59\xml-data\build-dir\1\build\Bamboo.build]
    20-Apr-2016 10:49:16	E:\Bamboo59\xml-data\build-dir\1\build\Bamboo.build(73,2): error MSB3073: The command "E:\Bamboo59\xml-data\build-dir\1\build\..\src\.nuget\NuGet.exe push E:\Bamboo59\xml-data\build-dir\1\octopacks\MyService.2.15.0.3245.nupkg -ApiKey API-MYKEY -Source http://octopus-server/nuget/packages?replace=true" exited with code 1.
    20-Apr-2016 10:49:16	Done Building Project "E:\Bamboo59\xml-data\build-dir\1\build\Bamboo.build" (CreateOctopusServiceReleases target(s)) -- FAILED.

2. During the deployment `Acquire Packages` we get an `Object reference not set to an instance of an object` exception.  When I try to reattempt the deployment, it fails complaining that the package is now missing from the internal server.  I assume this is a result of the nuget push leaving the package version in a dodgy state (e.g. missing).

I understand that this is probably not great practise - to replace a package version whilst simultaneously deploying it - as stated, I would much rather the nuget.exe to be able to return successful if the version already exists - e.g. idempotence (as you can do in `octo.exe` when creating releases using the `--ignoreexisting` flag).

I believe this could be a bug as it is currently handled very ungracefully

**Comment by vanessalove** [comment]
Hi @megakid, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
