### ISSUE TITLE
Azure steps sync entire work folder to destination path in Azure

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2470]
Including `Bootstrap.ps1`, `Variables.json` and `Variables.secret`

Source: https://secure.helpscout.net/conversation/193358112/6479/?folderId=557082

**Comment by Dalmirog** [comment]
@alfhenrik is there a difference between this and #2424 ?

**Comment by alfhenrik** [comment]
Duplicate of #2424
