### ISSUE TITLE
VSTS extension 'Create Release' task failing on latest version of agent

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2471]
As reported in: http://help.octopusdeploy.com/discussions/problems/45595

It seems Microsoft has renamed the VSTS PowerShell cmdlets: https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Commands.md

**Comment by rzulkoski** [comment]
I'm just running into this issue now as well. Has this been addressed somewhere else or why did it move to closed?

**Comment by rzulkoski** [comment]
Nevermind, installing Windows Updates on our build server running Windows Server 2012 R2 resolved the issue.
