### ISSUE TITLE
Change domain controller

### ISSUE THREAD

**Issue by asbjornu** [OctopusDeploy/Issues#2477]
In the [documentation for Active Directory authentication](http://docs.octopusdeploy.com/display/OD/Active+Directory+authentication), it doesn't look like it's possible to change **which** domain controller Octopus should use for authentication. It seems like it defaults to the domain controller the server is a member of, and that's it. We have several domain controllers and would like the server to belong to another domain than the one users authenticate with. Is this at all possible?

**Comment by vanessalove** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

**Comment by asbjornu** [comment]
@vanessalove Thanks, I've created [a new discussion for this in the support forums](http://help.octopusdeploy.com/discussions/questions/7885-change-domain-controller).
