### ISSUE TITLE
Failed checking for updates

### ISSUE THREAD

**Issue by asbjornu** [OctopusDeploy/Issues#2478]
We have repeated entries in the diagnostics log of Octopus Deploy, stating:

```c#
Failed checking for updates
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.CheckForUpdates() in Y:\work\refs\tags\3.3.4\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 105
```

Which URL and port number does Octopus Deploy use to check for updates? Requests to `https://octopusdeploy.com/` from the server works, but I assume the update check API endpoint is hosted somewhere else? Where?

**Comment by vanessalove** [comment]
Hi @asbjornu, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

**Comment by asbjornu** [comment]
@vanessalove Thanks, I've created [a new discussion for this in the support forums](http://help.octopusdeploy.com/discussions/questions/7887-failed-checking-for-updates).

**Comment by vanessalove** [comment]
@asbjornu thanks for understanding!
