### ISSUE TITLE
Installating a tentacle to a different folder silently deletes other tentacle service/folder

### ISSUE THREAD

**Issue by serbrech** [OctopusDeploy/Issues#2482]
I had a tentacle for octopus 2.x running. we are moving our stuff to octopus 3.
I installed a tentacle v3 on a server that had already a tentacle for v2.
I thought that if it listens to a different port and has different folder, no problem.

I went through the setup, made sure to select another installation path, and press install.
all went fine and the tentacle 3 UI opened.  
But it also **silently** uninstalled the tentacle v2 service, and remove its files...
It's fine to have constraints, not to be able to run them simultaneously. but please dont delete anything without telling me. I would prefer if you failed and warned me.

### Repro : 

Install tentacle v2 to `C:\Program Files\Octopus Deploy 2\`
Install tentacle v3 to `C:\Program Files\Octopus Deploy 3\`

`C:\Program Files\Octopus Deploy 2\` is gone.

Pretty sure the version doesn't matter there, but it was still unexpected.

**Comment by vanessalove** [comment]
Hi @serbrech I do have some questions about this. Could you please email me about this to support at octopus dot com. We don't use GitHub for conversation and investigation. Feel free to link this ticket. My main question is was it via the MSI or Hydra?
Vanessa

(Next message is our generic why was this closed)

**Comment by vanessalove** [comment]
The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

**Comment by serbrech** [comment]
Ising the MSI. I'll send an email :)
