### ISSUE TITLE
Dashboard > Configure UX issues with long project names

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2486]
The _Dashboard > Configure_ page has some fairly annoying UX issues when you add lots of projects/groups with long (40 char+) project names. It becomes very difficult to scroll up and down the lists without accidentally selecting projects. Eg. You can try to click the scrollbar (or the scroll arrows) and accidentally end up selecting projects, which voids the scroll behaviour at times.

Confirmed on Windows Chrome v50.0+.

Suggest looking for updated Angular controls to assist with this situation.

Also, consider readability of long project names as part of the solution, as the small lists becomes difficult to read longer project names as there's no mouseover/hover title.

<img width="858" alt="screen shot 2016-05-03 at 4 08 33 pm" src="https://cloud.githubusercontent.com/assets/819605/14975937/5d68deb8-114a-11e6-9a96-a4b36e82f3e4.png">

Source: http://help.octopusdeploy.com/discussions/problems/45725

**Comment by bharder** [comment]
For those who haven't discovered it yet, re-sizing the width of the window makes it pretty usable:
![issue](https://cloud.githubusercontent.com/assets/239891/15158177/38489384-16b4-11e6-940c-edde801daa7d.png)

**Comment by vanessalove** [comment]
A new issue was created #2569 and is part of 3.3.21 release
