### ISSUE TITLE
Investigation: Some snapshots not frozen breaking upgrade

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2488]
A customer was having issues upgrading from 3.3.4 and we discovered some deployment snapshots (with _-snapshot-_ in the name) that were _not_ frozen as being the cause of the issue. All snapshots should be frozen, so this was causing the upgrade to fail.

Could we please investigate all places where snapshots are created / frozen to see if there's any obvious edge case that will cause this for other customers in the future?

Source: http://help.octopusdeploy.com/discussions/problems/45692

**Comment by PaulStovell** [comment]
Going to close since this was opened over 6 months ago and hasn't come up since (or at least this issue hasn't been updated since).
