### ISSUE TITLE
Automatically select the best channel when creating releases with Octo.exe

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2494]
`octo.exe create-release` should automatically select the best channel for the project using the channel version rules (for Octopus.Server >= 3.2). This will ease the burden of writing custom PowerShell in build servers that are automatically pushing releases to Octopus.

Source: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/10920663-let-octo-exe-auto-select-the-right-channel-when-cr
PR: https://github.com/OctopusDeploy/Octo.exe/pull/73
PR: https://github.com/OctopusDeploy/Octo.exe/pull/75

**Comment by michaelnoonan** [comment]
Release Note: `octo.exe create-release` command extended to automatically select the best channel for the release, or fail with details on how to create it successfully

**Comment by ErikAGriffin** [comment]
@michaelnoonan sorry for the ignorance, but does this only apply to when one is directly calling `octo.exe create-release`?  Currently we create releases by using `octo.exe push` and having Octopus automatically create a release when a new package is detected, but it appears this Automatic Release Creation is not picking up on our channel rules

**Comment by michaelnoonan** [comment]
HI @ErikAGriffin - I'm sorry I missed your question. This applies any time you create a release using the octo.exe tooling. `octo.exe push` can create a release for you, so the same logic applies!

**Comment by ErikAGriffin** [comment]
Hi @michaelnoonan, no worries. Can you elaborate on how `octo.exe push` may create a release? Is there a particular flag or configuration to add in order to make it work?

**Comment by michaelnoonan** [comment]
Hi @ErikAGriffin. I've made a boo boo - I was thinking about how `octo.exe create-release` can also deploy that release as part of the same command. :)

`octo.exe push` _can_ create a release for you as a byproduct by using [Automatic Release Creation](https://octopus.com/docs/deploying-applications/automatic-release-creation). The problem is that ARC doesn't support the logic to automatically detect the best channel based on the package version. I think this suggestion will turn into that kind of feature. https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/10776963-automatic-release-creation-to-multiple-channels

My recommendation though would be to move away from ARC which is based on a package being pushed to the Octopus Built-In Repository, and instead:

1. Push package(s) to Built-In Repo
2. Use octo.exe (or one of the build tool extensions) to create the release choosing the right channel automatically
3. Use octo.exe to deploy the release

Hope that helps!
Mike
