### ISSUE TITLE
Not able to update Calamari to updated version on Linux target

### ISSUE THREAD

**Issue by BhandariSatish** [OctopusDeploy/Issues#2497]
Hi,

We have recently upgraded Octopus Deploy from versoin 3.1.2 to 3.3.10.

One of our Linux target (the only traget so far) is failing while trying to upgrade. None of the releases are working as an after-effect. 

![calamari_issue_linux](https://cloud.githubusercontent.com/assets/4094451/15154155/2198a2d0-16d4-11e6-90cc-354203aecf20.JPG)

**Comment by vanessalove** [comment]
Hi @BhandariSatish, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
