### ISSUE TITLE
Tentacle upgrade can break deployments

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2498]
Currently the Tentacle upgrade system does not seem to check if a deployment is running and can cause a deployment in progress to fail when the Tentacle restarts.
Can we block the upgrader if a deployment is in progress, and also queue deployments until it is completed?

Source: http://help.octopusdeploy.com/discussions/problems/45813

**Comment by alfhenrik** [comment]
Release note: Queue a Tentacle upgrade task if there are currently deployments running on the Tentacle
