### ISSUE TITLE
Change wording when skipping package step

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2499]
The "Skip packages that are already installed" feature in a project is worded in such a way that there is an assumption that just the package is not unpacked but all of the features inside the package step are still run - when they are not. 

Current text "Skip packages that are already installed"
Description: "Octopus can check whether the same version of an included package has already been installed on the deployment target and skip further deployment of the package. By default, Octopus will always re-install every included package."

I think the UI could be reworded and a bit of warning text beneath.
Suggested Change: "Skip package steps that are already installed"
With description text: "Octopus can check whether the same version of an included package has already been installed on the deployment target and skip that package step from running. By default, Octopus will always re-install every included package. The entire step is skipped not just the unpack stage."

Source: http://help.octopusdeploy.com/discussions/problems/6118
(Sending Jess a ping RE this)

**Comment by vanessalove** [comment]
Suggestion from Jess is that we make the fact it skips the whole step front and center so:


​*Skip step if package is already installed*​
The entire step will be skipped if Octopus detects the same package version already installed on the deployment target. By default, Octopus will always re-install every included package.

**Comment by vanessalove** [comment]
FINAL TWEAK (words are hard!)

Skip any package step that is already installed
All features of a package step will be skipped if Octopus detects the same package version already installed on the deployment target. By default, Octopus will always re-install every included package.

**Comment by matt-richardson** [comment]
Release Note: Clarify help text for skipping previously deployed packages
