### ISSUE TITLE
Allow TeamCity Plugin to use variable for the API key

### ISSUE THREAD

**Issue by motowilliams** [OctopusDeploy/Issues#2501]
This is to enable using a TeamCity variable at the build configuration or project root level.

**Comment by matt-richardson** [comment]
@motowilliams - you already can - the ux is just pretty poor.

If you enter the variable into a different field, and then copy and paste it into the apikey field, it works. 

We are using this approach with a single variable at root level used across a hundred odd projects.

**Comment by vanessalove** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
