### ISSUE TITLE
The "Configuration" link in the breadcrumb that is displayed for the Configuration page redirects to the Library page instead of the Configuration page.

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#2504]
The "Configuration" link in the breadcrumb that is displayed for the Configuration page redirects to the Library page instead of the Configuration page.

Steps to reproduce:

1) Open the Octopus Deploy home page
2) Click "Configuration" in the top menu
3) Click the "Configuration" link in the breadcrumb

Octopus redirects to the Library page instead of the Configuration page

Tested in 3.0.11 and 3.3.12 (demo.octopusdeploy.com)

**Comment by markryd** [comment]
Reported in https://secure.helpscout.net/conversation/201589643/7070/?folderId=870334

**Comment by tothegills** [comment]
Release note: The breadcrumb link on Configuration pages now redirects to the correct page
