### ISSUE TITLE
Improve error message around badly formatted zip/tar packages

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2516]
Currently if the user pushes a zip/tar package with a bad format like `MyPackage123.zip`, we return this error message

```
[17:46:34][Octopus Deploy] - The uploaded file isn't in a supported package format.
```

We could do a better job at explaining whats wrong, and even provide a link to our documentation which already explains how the package should look like.

Octopus Version: `3.3.11`
Source: http://help.octopusdeploy.com/discussions/problems/45940

**Comment by robpearson** [comment]
Release Note: Improved error messages for incorrectly named packages
