### ISSUE TITLE
SemVer 2.0

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2517]
Support [SemVer 2.0](http://semver.org/spec/v2.0.0.html) for release versions and packages.

**Comment by vanessalove** [comment]
Why'd the handle leak get linked here? We have a task for Nuget 3.0 https://github.com/OctopusDeploy/Issues/issues/2428 which is the fix.

**Comment by michaelnoonan** [comment]
I made a comment on #1071 that linked this issue to #2428. Sorry if that's confusing. #2428 is the best link for the handle leak.

**Comment by vanessalove** [comment]
Release Note: Support SemVer 2.0
