### ISSUE TITLE
Client takes 30 even when Take=999999

### ISSUE THREAD

**Issue by phillijw** [OctopusDeploy/Issues#2519]
The Octopus.Client will only take 30 since ItemsPerPage is set to 30, even if Take=999999 or some high number. This might be a bug in both the api and the client. Unfortunately I can't find a public project for the client otherwise I would just fix it myself.

`/api/deployments?take=999999`

```
{
    ItemType: "Deployment",
    IsStale: false,
    TotalResults: 33110,
    ItemsPerPage: 30,
    Items: [
        ...all of the items I originally asked for, not just 30 as stated in ItemsPerPage...
        ...but the client still seems to only grab the first 30, probably due to ItemsPerPage=30...
```

**Comment by Dalmirog** [comment]
Hi @phillijw , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
