### ISSUE TITLE
When creating a release NuGetFeedId is resolved incorrectly if scoped to a Channel along with other specifications

### ISSUE THREAD

**Issue by wiruzman** [OctopusDeploy/Issues#2522]
When scoping for Channel along with Target/Role/Enviroment/Step it is falling back to Octopus Builtin feed. It is working when only Channel is scoped.

It is described here: http://help.octopusdeploy.com/discussions/problems/45955-variables-in-package-feed-not-working

This is a crucial bug when working with local machines with local nuget feeds. We are working on a very large project with this bug stopping us and release date is not far.

A part of the problem is solved here [in this bug](https://github.com/OctopusDeploy/Issues/issues/2412)

@michaelnoonan will be the person to correct this :)

**Comment by Dalmirog** [comment]
Hi @wiruzman - I'm closing this issue as we'll continue the conversation in this link: http://help.octopusdeploy.com/discussions/problems/45955-variables-in-package-feed-not-working

In the future please do not duplicate issue reports in different systems, and also do not create issues here. We use do not use this channel for bug reports from customers, but for bugs that we've been able to reproduce and that we'll fix for sure.
