### ISSUE TITLE
Investigate (and fix) issue with multiple instances on polling machines not working in HA

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2523]
It appears that when you have multiple instances on a polling tentacle in HA the thumbprints get confused and give errors. Need to figure out why

Source: https://secure.helpscout.net/conversation/195052001/6586/?folderId=557083

**Comment by markryd** [comment]
Release Note: Fixed HA Servers not trusting newly added polling tentacles
