### ISSUE TITLE
Unable to push package to octopus nuget repository from teamcity.

### ISSUE THREAD

**Issue by maxkornev** [OctopusDeploy/Issues#2525]
Hi
I use octopus plugin for teamcity and try to push nuget package to octopus repository using OctopusDeploy: Push packages step. My octopus version 3.3.14 and teamcity plugin version 3.3.6+1.
When i specify package path as my project path like 

>Source\SelfHost\bin\Debug => package.zip

i get an error

> [Octopus Deploy] Running command:   octo.exe push --server http://192.168.201.209:7080/ --apikey SECRET --package C:\BuildAgent2\temp\buildTmp\ZipPreprocessor7860801240111109765\package.zip
> [13:26:45][Octopus Deploy] Pushing packages to Octopus server
> [13:26:45][Octopus Deploy] Octopus Deploy Command Line Tool, version 3.3.16+Branch.master.Sha.47e0e502fcd994db2415887dc3bf8b3f248962a7
> [13:26:45][Octopus Deploy] 
> [13:26:45][Octopus Deploy] Handshaking with Octopus server: http://192.168.201.209:7080/
> [13:26:45][Octopus Deploy] Handshake successful. Octopus version: 3.3.14; API version: 3.0.0
> [13:26:45][Octopus Deploy] Authenticated as: maxim.kornev <> 
> [13:26:45][Octopus Deploy] Pushing package: C:\BuildAgent2\temp\buildTmp\ZipPreprocessor7860801240111109765\package.zip...
> [13:26:57][Octopus Deploy] Error from Octopus server (HTTP 400): There was a problem with your request.
> [13:26:57][Octopus Deploy] 
> [13:26:57][Octopus Deploy]  - The uploaded file isn't in a supported package format.
> [13:26:57][Octopus Deploy] 
> [13:26:57][Octopus Deploy] Exit code: -7
> [13:26:57][Octopus Deploy] Octo.exe exit code: -7

What am i doing wrong and how should i specify Package path field ?

**Comment by vanessalove** [comment]
Hi @maxkornev , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
