### ISSUE TITLE
Can not run C# script on tentacle with FIPS enabled

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2538]
http://help.octopusdeploy.com/discussions/problems/46028

I replicated this on my Server 2012r2 using the provided code in a script step, my tentacle Server 2012r2 had FIPS Cryptography enabled. (Works fine without FIPS)

class Program 
{ 
static void Main(string[] args) 
{ 
int i=1; 
i++; 
} 
}

Script failed with:
ERROR: Script compilation failed: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms..

**Comment by alfhenrik** [comment]
Running ScriptCS ​**v0.16.1**​ on Server 2012 R2 with FIPS works fine, `Octopus.Dependencies.ScriptCS` (that `Calamari` uses) is at ​**v0.13.3**

Running ScriptCS **v0.13.3** on Server 2012 R2 with FIPS fails, so I'd say we need to update the ScriptCS version in `Octopus.Dependencies.ScriptCS`

```
C:\temp> scriptcs -version
               _       _
 ___  ___ _ __(_)_ __ | |__ ___ ___
/ __|/ __| '__| | '_ \| __// __/ __
\__ \ (__| |  | | |_) | |_| (__\__
|___/\___|_|  |_| .__/ \__\\___|___
                |_| Version: 0.13.3
C:\temp> scriptcs .\Test.csx
ERROR: Script compilation failed: This implementation is not part of the Windows Platform FIPS validated cryptographic a
lgorithms..
```
```
C:\Temp> scriptcs -version
               _       _
 ___  ___ _ __(_)_ __ | |__ ___ ___
/ __|/ __| '__| | '_ \| __// __/ __|
\__ \ (__| |  | | |_) | |_| (__\__ \
|___/\___|_|  |_| .__/ \__\\___|___/
                |_| Version: 0.16.1

C:\Temp> scriptcs .\Test.csx
Hello World from ScriptCS on FIPS
```
`Test.csx`
```
Console.WriteLine("Hello World from ScriptCS on FIPS”);
```

**Comment by pawelpabich** [comment]
Release Note: ScriptCS scripts work now on Win 2012 R2 when FIPS is enabled. ScriptSC has been updated to version 0.16.1 which works only on Mono >= 4.0.
