### ISSUE TITLE
Do not strip out all .nuspec files when packaging

### ISSUE THREAD

**Issue by JakeGinnivan** [OctopusDeploy/Issues#2539]
I am packaging an electron installer, which has a nuspec template in node_modules somewhere. It gets excluded so I cannot build my electron installer.

More details are at https://github.com/electron/windows-installer/issues/100

I have raised an issue in both projects but it would be great if octo.exe did not strip out all nuget files and instead included the fix from https://github.com/NuGet/Home/issues/439

**Comment by vanessalove** [comment]
Hi @JakeGinnivan , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
Feel free to reopen this inside the octo.exe repository or submit a PR over there.
