### ISSUE TITLE
Create VS Web Publish Task Destination File Functionality for XML Transformations

### ISSUE THREAD

**Issue by acgentry** [OctopusDeploy/Issues#2540]
The transformations functionality could use one improvement and that is to allow for piping the results of the transformation to a new destination file.

Currently our procedure is to not check in the web.config or app.config and to have those files built within the project using an app.base.config and app.[environment].config using the following VS feature of destination:

`<Target Name="BeforeBuild">
    <TransformXml Source="App.BASE.config" Transform="App.$(Configuration).config" Destination="App.config" />`

What we could really use is the same functionality in the XML transformations in Octopus, I envision extending the current syntax to allow for this final output:

Syntax:
`Transform.<environment>.config => Target.config => Destination.config`
For example:
`app.UAT.config => app.BASE.config => app.exe.config`

Thanks in advance!

**Comment by vanessalove** [comment]
Hi @acgentry , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
