### ISSUE TITLE
Allow the use of F# script (.fsx) in place of Powershell/ScriptCS

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2549]
Related to https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/10799772-allow-the-use-of-f-script-fsx-in-place-of-powe

**Comment by pawelpabich** [comment]
Hat tip to @jorgef for his help with making the API F# friendly.

**Comment by michaelnoonan** [comment]
Release Note: You can now write custom scripts using F# (`.fsx`)

**Comment by pawelpabich** [comment]
Release notes: Allow the use of F# script (.fsx) in place of Powershell/ScriptCS
