### ISSUE TITLE
Make OctoPack or OD aware of App.{Environment}.config transformation files

### ISSUE THREAD

**Issue by adriaanp** [OctopusDeploy/Issues#2550]
Using slowcheetah with our projects we have transform files like App.{Environment}.config. 

It would have been awesome if OctoPack could rename these transform files to what OD expects. Or if OD can identify app.{Environment}.config and apply these transformations.

**Comment by ccamburn** [comment]
@adriaanp The OD team doesn't monitor GitHub for things like this. I'm sure @vanessalove will be along to direct you to the support forums. They're great about getting back to you (and directing you to uservoice votes if there is one) on the support forums.

I'm chiming in to let you know this is already possible. Just put this into the config transforms section:

`app.#{Octopus.Environment.Name}.config => app.config`

That should run the transforms that you want.

**Comment by adriaanp** [comment]
@ccamburn I know about that option, we feel that we don't want to do that, we are trying to keep everything in build scripts and in source control. Currently we have tasks for copying/renaming these files to the expected file name.

**Comment by droyad** [comment]
Discussion taken to support forum http://help.octopusdeploy.com/discussions/questions/8318-make-octopack-or-od-aware-of-appenvironmentconfig
