### ISSUE TITLE
Additional Transforms After Default Transforms

### ISSUE THREAD

**Issue by acgentry** [OctopusDeploy/Issues#2558]
Hi,

The additional transforms happens before the default transforms, this seems counter intuitive and actually limits the functionality of your workflow.  

Assume I am a user who uses the standard transforms in a VS solution and I also include deployment transforms in my solution that the release engineer can use variables to fine tune the configs.

With the current order any default transforms would supersede/overwrite the additional transforms.

Can we change this order?

acg

**Comment by Dalmirog** [comment]
Hi @acgentry , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
