### ISSUE TITLE
Confirm installer/s work for Server 2016

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2561]
Even though it's in preview confirm the installers work for Server 2016 - see Pauls slack comment about removing 4.0 as dependency in slack chat (below):

Slack: https://octopusdeploy.slack.com/archives/team-octopusdeploy/p1466643059000511
Source: https://twitter.com/IrisClasson/status/745718182271393793

There will be an extended Trello task about Server 2016 compatibility, this is just for those on the preview.

**Comment by droyad** [comment]
OD, Tentacle and a script deployment install and work on Server 2016 Technical Preview 5. No extra installation/frameworks needed.

**Comment by droyad** [comment]
OD, Tentacle and a script deployment install and work on Server 2016 Technical Preview 5. No extra installation/frameworks needed.
