### ISSUE TITLE
Registering a Tentacle via the command line does not cope with MachineResource changes

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2565]
Registering a Tentacle via `Tentacle.exe register-with` will fail if there has been a change to `MachineResource` or a new deployment target type has been added.

**Comment by vanessalove** [comment]
probably need to make this two issues so it can go into 3.4.0 and 3.0.29 milestones for release notes

**Comment by vanessalove** [comment]
Release note: Update to Tentacle registration to account for new MachineResources changes
