### ISSUE TITLE
Run migrator multiple times with the overwrite flag + channels data throws Unique Key exceptions

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2579]
One thing worth noting that I found during the testing of [#2570](https://github.com/OctopusDeploy/Issues/issues/2570) is:

Our migrator can't seem to handle importing multiple times with the overwrite flag set when you have channels.

This has to do with a unique key constraint on the `Channel` table. Basically the `ChannelImporter.cs` class has a override for the `GetKeyForDestination` method which uses `id` as the key and this causes duplicate channels to end up in the ImportContext's IdentityMap, which then causes the unique key constraint to fire, which throws the exception and kills the migration.

This will not be an easy one to solve (I attempted to catch UniqueConstraintViolationExceptions, but the identity map is still borked with duplicate items because of the ChannelImporter, so it doesn't solve the problem - instead you end up with bad data in your instance and screens explode with exceptions). We'll most likely need to override the `GetKeyForSource` and `GetKeyForDestination` methods for channels to be a combination of project + name (the columns that make up the unique key constraint in SQL) so the identity map doesn't end up with duplicate channels...

...and I can't see anyway of doing that with the `GetKeyForSource` method (because its ProjectId is still mapped to the original ProjectId from the source, which won't match the destination = :boom:).
## Current Workaround

If you need to get around this for now for migrations, you can delete data manually from your Channel table and then re-import (after making sure you've got a DB backup obviously).

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Run migrator multiple times with the overwrite flag + channels data throws Unique Key exceptions](https://trello.com/c/bx8jwnzH/729-run-migrator-multiple-times-with-the-overwrite-flag-channels-data-throws-unique-key-exceptions)
