### ISSUE TITLE
Improve database selection/creation step in installation wizard

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2584]
Currently we have a field called "Database" where users can either look for existing databases (by clicking on the dropdown) or just type the name of the new DB then want to create. This 2nd option is not so clear and we've had a few users asking "Do I have to manually create a DB and then search it from the dropdown?".

We could improve this experience by letting them choose between a new db and an existing one, and then show the appropriate field as shown on the mock example below:

![newdatabase](https://cloud.githubusercontent.com/assets/6180562/16623115/06cf6f30-4373-11e6-9627-01f2a3aa4400.jpg)

![existingdatabase](https://cloud.githubusercontent.com/assets/6180562/16623119/0aad5dce-4373-11e6-99bb-a502bc81aeaa.jpg)

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve database selection/creation step in installation wizard](https://trello.com/c/NII00ksq/40-improve-database-selection-creation-step-in-installation-wizard)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve database selection/creation step in installation wizard](https://trello.com/c/780MeerV/747-improve-database-selection-creation-step-in-installation-wizard)

**Comment by droyad** [comment]
This no longer seems as urgent with the new UX
