### ISSUE TITLE
API keys stop working

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2586]
We've had a few reports of API keys that stop working all of a sudden.

Current workaround is to create a new API key.

Would be good to investigate and see why this could happen.

Source: http://help.octopusdeploy.com/discussions/problems/40210

**Comment by senthilrajav** [comment]
Thanks Henrik! Looking forward for the resolution.

**Comment by jonathandgrubb** [comment]
Much appreciated!!!

**Comment by droyad** [comment]
If anyone encounters this again, please contact us via our support channels. Please keep the API key and do not revoke it.
