### ISSUE TITLE
Allow pattern for variable substitution to be supplied in a cross-platform way

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2588]
Current if you need to specify a nested path for variable substitution, you can _either_ specify it so it will work on Windows (i.e. with `\`) _or_ so it will work on *nix (i.e. with `/`).  

Lets make `/` should work on either.

**Comment by pawelpabich** [comment]
@droyad feels like it belongs to execution, doesn't it?
