### ISSUE TITLE
System Integrity Check error when re-creating view

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2596]
For customers upgrading from 3.3.8 to 3.3.22, they're receiving a _System integrity check_ error regarding the schema. Everything in my instance was working, but I was able to reproduce by simply dropping and re-creating the `DeploymentSummary` view. As soon as I did this I received the same error:

>
Unexpected item: VIEW dbo.DeploymentSummary.Version nvarchar(200/0/0) 0
Missing item: VIEW dbo.DeploymentSummary.Version nvarchar(400/0/0) 0

The behaviour I'm seeing is that views in SQL do not have dynamic column lengths (once you've created the view, their column widths are stored, even if the table the view is querying changes state), so perhaps we should refresh our views every release to help avoid this sort of mis-match? That or suggest removing column length checking from views in the schema-checker.

### Longer example to help reproduce:
In our deployment scripts, the Release table starts out with a `Version` column of 200 nvarchar.

Then ​_Script0006 - DeploymentSummary.sql_​ gets run, creating a DeploymentSummary view, where the Release table's Version column is currently 200 nvarchar. So the DeploymentSummary view has a Version column of length 200.

Then ​_Script0008 - Lengthen Ids.sql_​ gets run, altering the length of the Release.Version column to instead be 100 nvarchar.

However, the DeploymentSummary view is still setup with a Version column of 200 nvarchar (this view stores the column length at the time the view was created).

If I install 3.3.8, then upgrade to 3.3.22, the schema check runs fine (so this should be ok / not happening for customers).

The only way I could reproduce was by tinkering with the DB directly and re-creating the DeploymentSummary view (because then the view re-calculates its Version column to correctly be nvarchar 100, which will not match our schema = :boom:)

so I do see it an a bug in Octopus, because our views are potentially out of date as our tables change state between versions

and i learned that views, once created, store the length of columns … which I didn’t realise was a thing :/

Source: https://secure.helpscout.net/conversation/227202432/0/

**Comment by vanessalove** [comment]
Another case: http://help.octopusdeploy.com/discussions/beta-testing-feedback/131

**Comment by markryd** [comment]
Release Note: Refresh views to fix schema integrity check failing for some customers
