### ISSUE TITLE
Step template import needs validation of properties

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2598]
Two issues here:
### Issue 1: Type validation

When importing JSON for step templates, we do not validate the properties dictionary. Users can easily mis-type boolean properties (or have inconsistent casing) which can then cause UI issues for anyone using the template.

Suggest adding validation on import for all known data types in step templates.
### Issue 2: Boolean case from PowerShell

If you're operating our client API via PowerShell and pass it custom objects (PSCustomObject) and serialise to JSON using ConvertTo-JSON, it converts booleans with the first letter capitalized, which then breaks our UI since our HTML controls are expecting lowercase boolean:

```
<control-group label="Run on">
<label class="radio"><input type="radio" ng-model='action.Properties["Octopus.Action.RunOnServer"]' value="false" /> Deployment target</label>
<label class="radio"><input type="radio" ng-model='action.Properties["Octopus.Action.RunOnServer"]' value="true" /> Octopus Server</label>
</control-group>
```

Suggest adding conversions for these boolean properties to make them lowercase, so these don't fail the UI.

Source: http://help.octopusdeploy.com/discussions/problems/46605

**Comment by zentron** [comment]
Have heard of no further reports of this issue since originally logged in 2016. Closing unless there are further concerns.
