### ISSUE TITLE
Bug converting template type from SingleLineText to Sensitive

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2600]
1. Define a tenant template variable as single line and set it.
2. Later, change to to be control type of the variable to be sensitive/password.
3. Go to the project variables for a tenant and click the reset button for that variable. The variable initially shows as a multiline box.
4. Clicked reset but was unable to enter any new value
5. Saving empty ignored change. - User reported seeing exception at this point but this part didn't repro

Source: http://help.octopusdeploy.com/discussions/beta-testing-feedback/120

![unabletochangetypetosensitive](https://cloud.githubusercontent.com/assets/1830666/17006261/c1a9b332-4f22-11e6-8301-59aac1811a6d.gif)

**Comment by zentron** [comment]
Error from user
![image](https://cloud.githubusercontent.com/assets/1830666/17041539/0425a5fa-4fea-11e6-93a8-59739e17b0ad.png)

**Comment by tothegills** [comment]
Release note: When variable templates are converted from sensitive to insensitive and vice versa, any variables based on the templates will also be converted
