### ISSUE TITLE
Bug - Unable to remove environment scope from project variable

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2601]
![cannot changescope](https://cloud.githubusercontent.com/assets/1830666/17006654/b1529a6e-4f25-11e6-83bd-b1114e5119e8.gif)

Source: http://help.octopusdeploy.com/discussions/problems/46650

**Comment by thebigmoosey** [comment]
Release Note: Fixes to the variable "scope" selector so it detects differences correctly
