### ISSUE TITLE
Variable Sets - Editing: Pressing return creates a new record then goes to the 2nd line

### ISSUE THREAD

**Issue by brianbv** [OctopusDeploy/Issues#2603]
In Octopus 3.3.10, I created a new empty variable set.

I double clicked to edit the first item.  After adding a 3rd item, pressing enter will successfully add a new item, but the 2nd field in the grid is always focused instead of the first column of the one that was just added.

**Comment by vanessalove** [comment]
Hi @biranbv, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
