### ISSUE TITLE
Adding required Prompted variables should not return an error if other, scoped variables exist that provide a value

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2605]
### Step 1.

Create a required scoped variable with no default value, and then another variable with the same name but with a value and scoped to an environment (that we will then deploy to)
![image](https://cloud.githubusercontent.com/assets/1830666/17047288/9f4d3996-501f-11e6-9bf8-cb1fe9a3f8a9.png)
### Step 2.

Create a release and go to deploy that release to that scoped environment. Leave the prompted variable empty since we will expect that the variable _with_ the value will be used at deployment time.
![image](https://cloud.githubusercontent.com/assets/1830666/17047288/9f4d3996-501f-11e6-9bf8-cb1fe9a3f8a9.png)
### Step 3.

Oh No! 
![image](https://cloud.githubusercontent.com/assets/1830666/17047453/9eb65308-5021-11e6-99a5-123021edfb5b.png)
### Expected

Given the fact that its not immediately obvious if the prompted variable will have a value until _after_ we select an environment (and potentially machines etc provide values for the scoped variable), its not such a problem if we continue to show the prompt textarea.

What **should** happen though, is that when the deployment is being created, it evaluates the variables and only if after evaluation it finds that the prompted value would be empty (and is required), then return the error.

**Comment by droyad** [comment]
Plan to improve this in variable unification feature
