### ISSUE TITLE
Investigate healthcheck CPU overloading for many machines with (HA specific)

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2607]
We have had a case of health checks causing an overload of the CPU and process, not being able to be cancelled, queuing deployments and not forcing a fail over from the primary node.

While we will look at fixing the underlying issue - how should Octopus behave in this situation and what can be done with health checks to stop this from occurring

Source: https://secure.helpscout.net/conversation/230942602/8662/?folderId=557083

**Comment by MJRichardson** [comment]
This issue couldn't be replicated, and hasn't been reported again.
