### ISSUE TITLE
Support ConnectionKeepAlive for SSH client

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2608]
If the upload process takes an inordinate amount of time to complete, the SSH connection may be closed by the server. 
Once the transfer is complete the deployment step will then attempt to use the, now closed, SSH connection to extract the package which will result in a connection failure.

The SSH client should provide a KeepAlive interval to ensure that it keeps "pinging" the server to ensure that the server doesn't close the connection. This feature will essentially mimic the `ServerAliveInterval` property used during typical SSH client connections.
Either that or check for the connection state before performing a command to ensure it is still connected and attempt a reconnect if required.

Source: http://help.octopusdeploy.com/discussions/problems/46712

**Comment by lonevvolf** [comment]
Any update on this?  To be honest, this seems more like a bug than an enhancement.  It is currently a roadblock for us on a current project with large files.

**Comment by zentron** [comment]
Release Note: Set KeepAliveInterval to 30 sec on SSH connections to keep connection to server open during long uploads.
