### ISSUE TITLE
Ensure variables that are dates do not change format when deserialized from the database

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2610]
When you put in a variable with a date with a certain format
![image](https://cloud.githubusercontent.com/assets/1830666/17128331/435ca116-534f-11e6-9cbc-0fe48f57a63e.png)

hitting save and reloading the page shows that it has deserialized in a different format
![image](https://cloud.githubusercontent.com/assets/1830666/17128345/5d4dfed0-534f-11e6-8202-c6aedc21dca4.png)

even though the database shows that it is still stored in the originally provided value
![image](https://cloud.githubusercontent.com/assets/1830666/17128390/abd129a6-534f-11e6-94d3-78979fcf7ac0.png)

It turns out that this is because the default `JSonSerializerSettings` has `DateParseHandling=DateTime` which means that even though its being deserialized onto a string property (on `VariableDeclaration.Name`) the serializer first turns it into a DateTime object, then turns _that_ into a string. As part of this process the format then changes from the originally provided value.

We cant\shouldn't necessarily set the `DateParseHandling=None` on the root\default JsonSerializerSettings class so instead directly target the `VariableDeclaration` serialization via a couple line change to the `VariableConverter.cs` class;

``` C#
var variableJson = (JObject)JToken.ReadFrom(reader);
JsonSerializerSettings settings = new JsonSerializerSettings {DateParseHandling = DateParseHandling.None};
var variable = JsonConvert.DeserializeObject<VariableDeclaration>(variableJson.ToString(), settings);
```

As part of this process however, we will loose the functionality\behavior that was formatting dates for values that _we_ had provided in special variables, like `Octopus.Deployment.Created`. Some users may had been relying on this behavior however if, as part of this ticket, we ensure that we store all our dates in a standard format it should be low risk due to:
- This bug exists only with data at rest, since its only during the deserialization phase that it occurs and typically our provided variables are supplied and utilized directly at the time of deployment without going through db first.
- Even if our dates change format, it is hoped that scripts are making us of it via something like `DateTime.Parse(#{SpecialVariable.Date})` and so long as we store it in a standard ISO format they shouldn't even notice the change.

Source: http://help.octopusdeploy.com/discussions/problems/46646-automatic-date-formatting
Related: https://github.com/OctopusDeploy/Issues/issues/2218

**Comment by Dalmirog** [comment]
Another more recent source: http://help.octopusdeploy.com/discussions/problems/47645

Ping @MJRichardson about his work on Variable Types to reach @vanessalove , @pawelpabich or myself about our discussion on how Variable Types might solve/helpwith this formatting issue.

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure variables that are dates do not change format when deserialized from the database](https://trello.com/c/qNg3dNQ5/25-ensure-variables-that-are-dates-do-not-change-format-when-deserialized-from-the-database)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure variables that are dates do not change format when deserialized from the database](https://trello.com/c/qNg3dNQ5/25-ensure-variables-that-are-dates-do-not-change-format-when-deserialized-from-the-database)

**Comment by zentron** [comment]
A work around for this is now available resulting from changes introduced in Octostache in the [3.5.](https://octopus.com/blog/octostache-json-formatting) release of Octopus Deploy. 

## Formatting Dates ##
[Filters](http://docs.octopusdeploy.com/display/OD/Variable+Substitution+Syntax#VariableSubstitutionSyntax-Filters) have been provided in the variable replacement syntax to allow for converting dates to another format.

Given a variable that is serialised by json.net as:
![image](https://cloud.githubusercontent.com/assets/1830666/21629266/7cd81194-d272-11e6-9054-292e21e33c98.png)

You can provide in your script a formatting function like
![image](https://cloud.githubusercontent.com/assets/1830666/21629378/5e35364e-d273-11e6-8004-c8d534071b35.png)

which will result in the output
![image](https://cloud.githubusercontent.com/assets/1830666/21629393/75ba482c-d273-11e6-823f-fb5e6d5030e7.png)
