### ISSUE TITLE
Add a variable for current script path when running script from package

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2612]
Octopus extracts the package contents on a temp dir to execute a "script in package". It would be handy to have a variable that holds that full dir in case it needs to be references in any of the scripts.

Currently `$PsScriptRoot` works perfectly, but from a DAWOPS perspective it would look nicer to have our own variable.

**Comment by tothegills** [comment]
Currently can use `$OctopusParameters['OctopusOriginalPackageDirectoryPath']`

**Comment by tothegills** [comment]
Thinking of implementing something like `Octopus.Action.Script.WorkingDirectoryPath`.  Do you think this should be an output variable or only accessible from the script step?

**Comment by tothegills** [comment]
Decided to leave this as the variable `OctopusOriginalPackageDirectoryPath` as it is appropriate for such a temporary path.
