### ISSUE TITLE
Allow "importing" certificates from the certificate store

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2616]
We currently allow Tentacle to use a certificate imported from a PFX file.  In some cases a certificate exists in the Windows Certificate Store but it can not be exported.

Allow the use of store certificates for Tentacle (and Server?).

Also provide good messaging and guidance around the risks of using the certificate store and the problems that may happen when changing users.

**Comment by tgillitzer** [comment]
To answer the "and Server?" question, my request would be yes.   Code should be very similar.

We have quite a bit of experience doing this ourselves.   There are a few major gotcha's.   The two main ones we've seen are permissions on the certificate private key and a missing private key.

Permissions: Generally "SYSTEM" has access to the certificate private keys stored in the certificate store.   If you run as a different user, something will need to grant read permissions to the private key to that user.

Missing private key: There isn't much you can do to work around this and the errors that are generated when it happens aren't the most intuitive, unfortunately.

Also, keep in mind, there are multiple certificate stores (My, Root, Trusted, etc) in multiple locations (SYSTEM, User, Service).

If I can help in anyway, including providing example code to consume from the certificate store, please let me know.

Thanks
