### ISSUE TITLE
Reduce delay between steps for deployments with many steps/machines

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2617]
We recently removed a significant bottleneck between steps, which was impacting customers with projects containing many steps and/or machines (https://github.com/OctopusDeploy/Issues/issues/2546).

But there is still a significant delay:
http://help.octopusdeploy.com/discussions/problems/44558
http://help.octopusdeploy.com/discussions/problems/45981-slow-deployments

Further investigation is required.

**Comment by droyad** [comment]
#3321 Seems to have fixed up this problem to a large extent.  I propose closing this issue.

**Comment by michaelnoonan** [comment]
I agree. With the number of positive reports from customers in https://github.com/OctopusDeploy/Issues/issues/3311
