### ISSUE TITLE
Add UI to delete Octopus nodes

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2619]
We get people who accidentally add nodes for a variety of reasons and need to delete them via the API or database.  Would be much simpler if there was a delete button on the nodes page.

**Comment by cpredasportingindex** [comment]
Hey tothegills , are you talking about tentacles or nodes in a cluster ?

Cheers bud ! 

C

**Comment by vanessalove** [comment]
HI @cpredasportingindex this will be for nodes in a HA cluster.

**Comment by tothegills** [comment]
Release note: Added delete button to server nodes UI
