### ISSUE TITLE
When I "Try Again" the deployment ignores environment filter target machines.

### ISSUE THREAD

**Issue by Ashtonian** [OctopusDeploy/Issues#2625]
If I click Try Again on a failed release it seems to ignore the advance feature "apply to a specific subset of targets". This isn't really obvious and kind of dangerous as a result.

**Comment by Dalmirog** [comment]
Hi @Ashtonian , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
