### ISSUE TITLE
Cannot bind a variable to window size field

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2626]
Version: `3.3.24`

We are not saving the value to the deployment process, so it doesn't seem to be just an UI thing 

![windowsize](https://cloud.githubusercontent.com/assets/6180562/17501561/53a4c560-5e23-11e6-85f4-36e94d7debab.gif)

**Comment by Dalmirog** [comment]
Also if you delete the `int` on the box, the whole "window size" section just dissappears, making it a bit annoying to put a variable on it.

**Comment by markryd** [comment]
This works fine if you type the binding into the box manually.

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot bind a variable to window size field](https://trello.com/c/S4cswzYm/27-cannot-bind-a-variable-to-window-size-field)

**Comment by pawelpabich** [comment]
Release Note: Rolling deployments can have now window size bound to a variable
