### ISSUE TITLE
Fix release notes on the `release package version search` page

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2631]
Release notes in the release package version search page are not displaying any markdown.

Source: http://help.octopusdeploy.com/discussions/problems/46908

To find it:
Create Release > Packages > Specific > Search (brings up modal) > tick release notes > hit 'refresh'

If release notes exist they will render without markdown.

![image](https://cloud.githubusercontent.com/assets/119096/22636246/8258e026-ec85-11e6-806a-d7a474047c18.png)

**Comment by NickJosevski** [comment]
Nuget Package Release Notes do not support markdown. The Release Notes feature on an Octopus Release does support markdown.

This would be an enhancement, if this is still desired please raise on [UserVoice](https://octopusdeploy.uservoice.com/).

**Comment by thashepherd** [comment]
Is https://help.octopusdeploy.com/discussions/questions/9098 (NuGet 3 API no longer returns release notes) still a blocker here? I'd love to get release notes back.

**Comment by NickJosevski** [comment]
The release notes that are part of the page, will render as markdown on the search page, it's operational on the old portal, and the V4 portal.

![image](https://user-images.githubusercontent.com/119096/30997347-95403e44-a50a-11e7-8920-7426fb4c9066.png)

**Comment by droyad** [comment]
Release notes in packages issue: #2834

**Comment by NickJosevski** [comment]
Shipped in 3.17.13
