### ISSUE TITLE
Trying to automate tentacle intaller, but running into troubles 

### ISSUE THREAD

**Issue by cpredasportingindex** [OctopusDeploy/Issues#2635]
The code bellow is from the official page but when i'm customise it for my needs i'm allways gettting bellow ( i'm using powershell v5, windows 10 machine ) .

Tentacle.exe : The term 'Tentacle.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.

cd "C:\Program Files\Octopus Deploy\Tentacle"
 
 
Tentacle.exe create-instance --instance "Tentacle" --config "C:\Octopus\Tentacle.config" --console
Tentacle.exe new-certificate --instance "Tentacle" --if-blank --console
Tentacle.exe configure --instance "Tentacle" --reset-trust --console
Tentacle.exe configure --instance "Tentacle" --home "C:\Octopus" --app "C:\Octopus\Applications" --port "10933" --console
Tentacle.exe configure --instance "Tentacle" --trust "YOUR_OCTOPUS_THUMBPRINT" --console
"netsh" advfirewall firewall add rule "name=Octopus Deploy Tentacle" dir=in action=allow protocol=TCP localport=10933
Tentacle.exe register-with --instance "Tentacle" --server "http://YOUR_OCTOPUS" --apiKey="API-YOUR_API_KEY" --role "web-server" --environment "Staging" --comms-style TentaclePassive --console
Tentacle.exe service --instance "Tentacle" --install --start --console

**Comment by matt-richardson** [comment]
Hi @cpredasportingindex, thanks for getting in touch with us. 

We don't actively monitor this backlog for new issues as per our contributing guide. I see you have also raised a support request - I will answer both of your questions there.

[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
