### ISSUE TITLE
Inconcistency with checkbox "Wait for packages to be downloaded before running"

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2636]
Octopus version: `3.3.27`
# Setup

This was tested with a 5 step deployment process that consists of:

1) Step template step that prints a message 1
2) Regular script step that prints a message 1
3) Package deploy step
4) Step template step that prints a message 2
5) Regular script step that prints a message 2

![deploymentprocess](https://cloud.githubusercontent.com/assets/6180562/17782455/ec78cbc4-6549-11e6-8c59-cf905e6fde60.jpg)

Step template code:

```
{
  "Id": "ActionTemplates-101",
  "Name": "Print Messages",
  "Description": "script",
  "ActionType": "Octopus.Script",
  "Version": 5,
  "Properties": {
    "Octopus.Action.Script.Syntax": "PowerShell",
    "Octopus.Action.Script.ScriptSource": "Inline",
    "Octopus.Action.Script.ScriptBody": "Write-output $Message",
    "Octopus.Action.Script.ScriptFileName": null,
    "Octopus.Action.Package.NuGetFeedId": null,
    "Octopus.Action.Package.NuGetPackageId": null
  },
  "Parameters": [
    {
      "Name": "Message",
      "Label": "Message",
      "HelpText": "Message to print on screen",
      "DefaultValue": "DEFAULT",
      "DisplaySettings": {
        "Octopus.ControlType": "SingleLineText"
      }
    }
  ],
  "$Meta": {
    "ExportedAt": "2016-08-18T16:45:24.199Z",
    "OctopusVersion": "3.3.27",
    "Type": "ActionTemplate"
  }
}
```
# Findings
- "Regular Script step 1" has the option "Wait for packages to be downloaded before running", but after checking it, saving and re-opening the step, the box is not marked. The functionality does get saved in the deployment process, and the packages get downloaded before the step. So this only seems to be a UI thing. This doesn't happen for "Step Template 1" (the box is there and stays checked after saving the step)
- "Regular Script step 2" has the option "Wait for packages to be downloaded before running" even though it comes before the Package deploy step. Marking it and saving it doesn't affect the deployment process at all. Unless I'm not understanding something, the box shouldn't appear at all in that case?

Source: http://help.octopusdeploy.com/discussions/questions/8923

**Comment by droyad** [comment]
In the new UI, the checkbox only appears if the script step comes before a package step. It also now retains the checked state.

**Comment by droyad** [comment]
Release Note: The `Wait for packages to be downloaded` option only appears for steps ordered before a package step, and the checkbox now retains it's value
