### ISSUE TITLE
Issue with tasks completing for Tentacles that share thumbprints

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2637]
We have a couple of reports that has been confirmed by @tothegills where a task is being marked as completed when it is being deployed to multiple Tentacles that share a thumbprint.

Sources: https://secure.helpscout.net/conversation/237677961/9003/?folderId=557083
https://secure.helpscout.net/conversation/238348740/9046/?folderId=557083

TBC ASAP - preferably also as a patch for 3.3 if 3.4 is released so those not ready to upgrade to 3.4 have a fix.

**Comment by vanessalove** [comment]
Workaround is to change the thumbprint on effected Tentacles - messy and manual.
Could effect every customer that automates Tentacle installation.

**Comment by vanessalove** [comment]
Please check one of the sources for some extra information about the thumbprints not being a duplicate for a specific issue they were having.

**Comment by vanessalove** [comment]
Second customer came back confirming no duplicate thumbprint ..

**Comment by tothegills** [comment]
For the first support ticket, Octopus attempts to finish running tasks when requested to shut down.  Logs are not returned but the task actually did finish successfully. Try running sleep script step and package deploy step after.  Shut down the server during the script sleep and the package will be deployed (tho not reflected in the task log).

**Comment by vanessalove** [comment]
second ticket also not related - tentacle is shutting down partly through the deployment. this comes down to messaging and logging. possibly not even related to thumbprints?

I did remove the priority of the issue.

**Comment by droyad** [comment]
No more reports of this
