### ISSUE TITLE
Improve message when running step on Octopus Server on behalf of targets

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#2638]
When running a child step on the Octopus Server on behalf of deployment targets, the messaging on the UI is not as clear as it could be.

![image](https://cloud.githubusercontent.com/assets/373389/17842731/4a38bb62-6869-11e6-92ee-3d0b0d9c178c.png)

When the child steps only run on the Octopus Server, variables such as `$OctopusParameters['Octopus.Machine.Name']` are not available.
When there is at least one sibling step that runs on the deployment targets as well, the variable is available to all child steps.

The message `When running a script step on the Octopus Server on behalf of deployment targets variables in the scope of each deployment target are available to the script` can be interpreted to mean 'custom variables added that are specifically scoped to the target are available' or 'all variables that you get when running on the target are available'. (The first interpretation is the correct one.)

We should improve the UI to help avoid misunderstandings here.

Source: http://help.octopusdeploy.com/discussions/problems/47089

**Comment by tothegills** [comment]
I think this is fixed by: https://github.com/OctopusDeploy/Issues/issues/2751

All variables that you get when running on the target machine are supposed to be available when running on the server on behalf of a target machine.

**Comment by matt-richardson** [comment]
This issue was based on a misunderstanding:

> The message When running a script step on the Octopus Server on behalf of deployment targets variables in the scope of each deployment target are available to the script can be interpreted to mean 'custom variables added that are specifically scoped to the target are available' or 'all variables that you get when running on the target are available'. (The first interpretation is the correct one.)

The second interpretation is actually the correct one.

As @tothegills has mentioned, this is now fixed.
