### ISSUE TITLE
Incorrect description of "Physical Path" property of "Deploy an Azure Web App" step

### ISSUE THREAD

**Issue by DavidKDeutsch** [OctopusDeploy/Issues#2640]
When creating a "Deploy an Azure Web App" step, the description for "Physical Path" says:

> Physical path relative to site root. e.g. 'foo' will deploy to 'site\wwwroot\foo'.
Leave blank to deploy to root.

In reality, this field determines the **virtual** path, not the physical one. For example, if I have a virtual path /foo mapped to "site\wwwroot\bar", specifying "foo" will deploy to "site\wwwroot\bar". If instead I have the root virtual directory ("/") mapped to "site\wwwroot\bar," specifying "foo" will deploy to "site\wwwroot\bar\foo".

I have no problem with this behavior, but the name of the field (along with the description of it) should probably be changed to reflect this behavior.

BTW, this is with version 3.3.2.

**Comment by Dalmirog** [comment]
Hi @DavidKDeutsch , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
