### ISSUE TITLE
SSH accounts don't import

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#2645]
Octopus Server: 3.3.22

When performing an import where SSH accounts exist (\exportedFiles\Accounts\SSHAccount.JSON), the Accounts folder doesn't get created on server. I have replicated it - I created an account, exported, verified its existence in the exported files, deleted the SSH account on server, imported, and it doesn't show as imported.

Source: http://help.octopusdeploy.com/discussions/problems/46868

**Comment by tothegills** [comment]
No accounts are imported

**Comment by tothegills** [comment]
Release note: Accounts are now imported when using the Octopus migrator
