### ISSUE TITLE
The Dashboard is slow with a large number of projects or environments

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2646]
When the combination of projects and environment gets into the high 100's, performance starts becoming pretty bad. There are several levels contributing to this:
- The Dashboard view is slow due to how it scans the ServerTask table
- All the data is serialised to the client, the only filtering being done in server memory is the "Configure Dashboard" options. The text search and top X filter is done client side
- The Previous Successful dashboard data is only used internal
- The Dashboard view is also used by other code paths (eg create release)

**Comment by praniga** [comment]
Hi

Just checking to see if any progress has been made to fix\improve this issue or an ETA.

Thanks
Praveen

**Comment by michaelnoonan** [comment]
I'm going to close this particular issue since we are going to focus all of the effort in fixing the dashboard performance problems in this issue: https://github.com/OctopusDeploy/Issues/issues/2850
