### ISSUE TITLE
Project page descriptions cut off

### ISSUE THREAD

**Issue by CumpsD** [OctopusDeploy/Issues#2651]
I tend to add a little info to my projects with links to where I can find the source and the buildserver. However, it seems the project page cuts these off.

![image](https://cloud.githubusercontent.com/assets/1201644/17948976/94f49536-6a53-11e6-9172-af9277203b30.png)

Is there a way to make these bigger somehow, or auto adjust?

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
