### ISSUE TITLE
Cannot edit SSH keypair under Accounts

### ISSUE THREAD

**Issue by CumpsD** [OctopusDeploy/Issues#2653]
After I have added an SSH account, when I click it to edit, I get the following page:

![image](https://cloud.githubusercontent.com/assets/1201644/17950697/25e1f2ce-6a5d-11e6-95f0-d0c37392d4d1.png)

Just some yellow empty alert, nothing extra

**Comment by michaelnoonan** [comment]
Hi there! Thanks for the report - I think we've fixed this as part of https://github.com/OctopusDeploy/Issues/issues/2660.

The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
