### ISSUE TITLE
Handle trailing backslashes for Octo.exe pack OutFolder and BasePath parameters 

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2663]
`OutFolder` and `BasePath` parameters of `Octo.exe pack` do not support trailing `\` . We (#team-awesome) have the feeling that we'll get plenty of tickets for this one, so it might be better to just handle it gracefully on our end.

Octo.exe version: Latest

Source: http://help.octopusdeploy.com/discussions/problems/47161

**Comment by jkonecki** [comment]
Has been bitten by this bug today. Should be an easy fix, shouldn't it? ;-)

**Comment by markryd** [comment]
When we build the call to Octo.exe in TFS/VSTS we end up with `--outfolder="c:\firstpath\" --basepath="c:\secondpath\"` and the shell interprets `\"` as a literal escaped `"` in the middle of the outfolder argument. Octo.exe is fine, we need to update our TFS extension to either strip the trailing `\` or double it (so we have `--outfolder="c:\firstpath\\"`).
