### ISSUE TITLE
Tenanted deployments - preview current version

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2667]
To keep tenanted deployments consistent with un-tenanted deployments (UI), when deploying to one or more tenants, it's not possible to see which release version is currently deployed to the selected tenants before hitting the "Deploy now" button. We should add a preview next to each tenant's name on this deployment screen.

![whichversion](https://cloud.githubusercontent.com/assets/819605/17991793/3724af8a-6b85-11e6-8f50-46bc11fc532e.png)

Source: http://help.octopusdeploy.com/discussions/questions/9010

There's also some confusion about untenanted/tenanted "current version preview" - we should fix this also:

Discussion: https://octopusdeploy.slack.com/archives/feature-discussion/p1477345844000002

Source: https://twitter.com/IrisClasson/status/790545072022491136

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tenanted deployments - preview current version](https://trello.com/c/jFlObV1D/674-tenanted-deployments-preview-current-version)

**Comment by rifaterdemsahin** [comment]
That is very good

**Comment by MJRichardson** [comment]
This has been implemented in 4.0.

**Comment by MJRichardson** [comment]
Release note: Deploy release page now displays the version previously deployed for each selected environment and tenant.
