### ISSUE TITLE
Provide a better error message for octo.exe push when the server doesn't support that feature

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2671]
We should use hypermedia links to detect when the target server doesn't support the Package Push api and write a better error message including the minimum version that supports the API, and alternative solutions.

Source: http://help.octopusdeploy.com/discussions/questions/8986
Source: https://octopusdeploy.slack.com/archives/team-fire-and-motion/p1472433325000019

**Comment by michaelnoonan** [comment]
Looks like this might be a red herring.

`octo.exe push` uses the `BuiltInRepositoryRepository`: https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octo/Commands/PushCommand.cs#L37

Which uses the `PackageUpload` hypermedia link: https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs#L27

Both Octopus 2.6.x and 3.x have that endpoint and hypermedia link available: 

![image](https://cloud.githubusercontent.com/assets/1627582/23287430/16663366-fa89-11e6-9674-a30eda97845a.png)

The `octo.exe push` command was only introduced in `3.3.8`: https://github.com/OctopusDeploy/OctopusClients/commit/f56de1d580f834ac7e38ddcad7af330cd58ce2c5

I think this issue can be closed.

**Comment by NickJosevski** [comment]
Running the push command against the 2.6 instance was also succesful:

```
> .\Octo.exe push --package .\NestedFilesPackage.2017.2.10.130650.nupkg --server https://2.6.test --apiKey API-XXX
Octopus Deploy Command Line Tool, version 4.6.1

Handshaking with Octopus server: https://deploy.octopushq.com
Handshake successful. Octopus version: 2.6.4.951; API version: 3.0.0
Authenticated as: Nick Josevski <null>
Pushing package: C:\temp\OctopusTools.4.6.1\np\NestedFilesPackage.2017.2.10.130650.nupkg...
Push successful
```
