### ISSUE TITLE
If logo artifacts are deleted, project logos should degrade gracefully

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2678]
If you add a logo to a project, then delete or move artifacts from the server (where the logo file is stored), the project dashboard shows broken images. We should degrade more gracefully in these cases and detect whether the file is available.

This should be extended to all uses of artifacts, not just project logos.

Source: http://help.octopusdeploy.com/discussions/problems/47206

**Comment by pawelpabich** [comment]
We prefer the current behaviour where we indicate that some data is missing so the real problem can be fixed. If a logo is missing we return 404 and the app does not crash.
