### ISSUE TITLE
Variables missing from binding auto-complete list

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2684]
When [adding a new script step to the process in the Channels Sample](https://demo.octopusdeploy.com/app#/projects/channels-sample/process/step/new/Octopus.Script) I would have expected to see all available project and library variables as well as the action variables. However I can only see some of the project variables, and none of the library variables.

Project Variables:

![image](https://cloud.githubusercontent.com/assets/1627582/18078119/24ba90b2-6ecd-11e6-9bcb-e0c348b5bc2c.png)

All Variables:

![image](https://cloud.githubusercontent.com/assets/1627582/18078136/482e51f0-6ecd-11e6-97d1-d3f3ea6c126a.png)

Auto complete:

![image](https://cloud.githubusercontent.com/assets/1627582/18078109/1063352e-6ecd-11e6-9c58-d5c86ecf1049.png)

Source: http://help.octopusdeploy.com/discussions/problems/47248

## Potential solution
We generally like the idea of what you see is what you get (think dashboards and auto-deploy) - what if we actually queried the `AllVariables` for unique names, and added system variables?

**Comment by michaelnoonan** [comment]
Another potential reference indicating the variables only appear if they are in the global scope.

Source: http://help.octopusdeploy.com/discussions/problems/47302

**Comment by michaelnoonan** [comment]
Another source: http://help.octopusdeploy.com/discussions/problems/47340

**Comment by michaelnoonan** [comment]
Another source: http://help.octopusdeploy.com/discussions/problems/47442

**Comment by mud5150** [comment]
I also just noticed this issue today. We're on 3.4.6. Any headway on getting this resolved?

**Comment by kwilson803** [comment]
3.4.5 here. Just noticed this issue as well. Will have to try downgrading if this isn't resolved soon.

**Comment by tothegills** [comment]
Release note: Restore missing variables in binding auto-complete list

**Comment by kwilson803** [comment]
Installed 3.4.9. Issue got worse. Now the ONLY variables that show up are Octopus system variables. No custom defined variables show up in the list. This is ridiculous. Attempt to downgrade to 3.3 in progress.
![capture1](https://cloud.githubusercontent.com/assets/22158974/18548121/3920dcec-7b15-11e6-8ee6-ad144e4152c8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/22158974/18548127/3bd099c8-7b15-11e6-9686-469ba8d265a0.PNG)

**Comment by tothegills** [comment]
Hi @kwilson803,

I'm really sorry the "fix" made things worse and that we have let you down.

The API call that populates the variables was incorrect and I wrongly assumed that the API results were working as we have a suite of tests to exercise the API.  In my haste I didn't check.

Today I'm going re-write the tests to ensure that we are getting the correct results from the API and this mistake never happens again. I know we have shaken your confidence in us but hope we can rebuild that trust by shipping releases that improve, instead of break, the features you rely on.
