### ISSUE TITLE
Allow users to configure what version revisions to be notified about

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2688]
This way we can keep releasing new `PATCH` versions without worrying about being too noisy in the UI for customers that only want to know when new `MAJOR.MINOR` versions are available.

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow users to configure what version revisions to be notified about](https://trello.com/c/ekNv3kap/14-allow-users-to-configure-what-version-revisions-to-be-notified-about)
