### ISSUE TITLE
Deploying an ARM Template from a package fails due to missing variables

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#2693]
When deploying an ARM Template as a script within a package, when we go to deploy it, there are a heap of variables missing (`Octopus.Action.Azure.ResourceGroupDeploymentMode` for one) and this causes the deployment to fail. If you run the same code as a source script everything works as expected.

Source: http://help.octopusdeploy.com/discussions/problems/47084

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploying an ARM Template from a package fails due to missing variables](https://trello.com/c/K5Yqghcn/33-deploying-an-arm-template-from-a-package-fails-due-to-missing-variables)

**Comment by johnsimons** [comment]
I cannot reproduce this in v 2019.1
