### ISSUE TITLE
Conflicting variables crashes Octopus process

### ISSUE THREAD

**Issue by matthewcanty** [OctopusDeploy/Issues#2694]
I was playing with variables and had the following settings in place which were causing the Octopus process to stop.

![image](https://cloud.githubusercontent.com/assets/2089581/18135116/a87f12ee-6f98-11e6-8088-9e68f9db1bd4.png)

![image](https://cloud.githubusercontent.com/assets/2089581/18135198/fb679cf6-6f98-11e6-9a37-9c005583a609.png)

I can't find any logs indicating any issues except event viewer notification that the process has stopped.

**Comment by KennethBates** [comment]
Hi Matthew, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
