### ISSUE TITLE
Environment delete does not cascade to Project Triggers nor Tenants

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2695]
1. Create a Tenant
2. Connect them to a Project and some Environments
3. Delete one of the environments
4. The deleted Environment is still referenced by the Tenant->Project/Environment connections.
5. You end up with "ghost" entries requiring variables etc.

When an Environment is deleted we should also delete the TenantVariables related to that Environment.

The same behaviour occurs if you add Environments to a Project Trigger, and then delete the Environments.

It would be good to investigate the effect of deleting Roles and see what happens with Project Triggers.

Source: http://help.octopusdeploy.com/discussions/problems/47270-bug-ghost-environments-when-editing-tenant-project-variables

**Comment by tothegills** [comment]
Release note: Cascade environment deletion to tenant connections, tenant variables and triggers
