### ISSUE TITLE
Improve Add Step functionality

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2698]
As Octopus is growing we will be providing more and more built-in step templates. Add to that a dozen or so custom templates and our current Add Step screen does't make it easy to find what you are looking for. There is also no easy way of adding [community step templates](http://library.octopus.com/) to Octopus.  Taking all of that into account we have decided that we need to simplify the use and the management of step templates. 

At the moment, the following high level ideas are on our radar:
- [x] Update the add step page to show built-in step templates (e.g  [Deploy an IIS Web Site](http://docs.octopusdeploy.com/display/OD/IIS+Websites+and+Application+Pools)), [community step templates](http://library.octopus.com/) and custom step templates as well as make it easy to find what the user is looking for:
- [x] Automatically pull the latest step templates from community library and make their installation and subsequent updates easy to do
- [x] Provide logos for community library templates
- [x] Make built-in step templates much more prominent
- [x] Add ability to run script step templates directly from the library
- [x] Add ability to install/update community step templates without reviewing their details
- [x] Add ability to view the details of a community step template before it gets installed
- [x] Add ability to install and update community step templates from Step Template Library page
- [x] Link existing custom step templates to community templates if such a link can be safely established
- [x] Add ability to provide custom logo for custom step templates
- [x] Categorise templates in the community library

Other things to do:

- [x] Regression testing
- [x] Docs 
- [x] Blog 

Not Done

- [ ] Add ability to update a single action or all projects to the latest version of a step template

**Comment by pawelpabich** [comment]
**New Add Step screen**

![image](https://cloud.githubusercontent.com/assets/347637/19547977/de517908-96de-11e6-918d-cd4b6759ef2e.png)

**Comment by pawelpabich** [comment]
**Logos for community library**

![image](https://cloud.githubusercontent.com/assets/347637/19548212/82de45ae-96e0-11e6-83de-00f0b5de2ba6.png)

**Comment by ccamburn** [comment]
Any chance of allowing custom logos for server-level step templates? As a company that has a large number of step templates, sometimes scrolling down the list can be confusing. Custom logos would go a long way toward making that screen nicer.

**Comment by fernandobeltranjsc** [comment]
we have diferent step templates owned by diferent departments, add a custom logo for each step-template would be fine, and add category for each one BBDD | IIS | FileSystem....

**Comment by pawelpabich** [comment]
Hi @ccamburn and @fernandobeltranjsc,

Thank you for your feedback and sorry for the delay but we were not sure whether we can squeeze in custom logos. The good news is that we managed to do that :).

![image](https://cloud.githubusercontent.com/assets/347637/20371908/9855c482-acb3-11e6-9a1a-cfc7caeed0fa.png)

**Comment by pawelpabich** [comment]
We've also categorised the templates in the community library and used this information to provide a high level summary of what's in it.

![image](https://cloud.githubusercontent.com/assets/347637/20372002/03d65262-acb4-11e6-9ea7-97af8402d31d.png)

**Comment by ccamburn** [comment]
@pawelpabich No problem on the delay, looks perfect! I look forward to using it.

**Comment by Fernando-Beltran** [comment]
@pawelpabich looks good!  Thanks.

**Comment by wes-novack** [comment]
+++++ to ` Add ability to update a single action or all projects to the latest version of a step template`

When is this feature expected to be released?

**Comment by BlairPaine** [comment]
@pawelpabich when a new step is added to the process screen, is it possible to allow the user to enter a description to describe what that step does.  For example, my step may be to run a PowerShell script.  I want the user to see a description explaining what that PowerShell script step will do rather than just the step name.  For example:

![](http://i.imgur.com/kF1oVw5.png)

I can see in one of your screenshots above there is the possibility to add a description for a library item but not at the actual step level on the process screen.

Rather than hard coding in some text I may just provide a link to documentation explaining that step i.e. in Confluence.

Cheers,
Blair.

**Comment by pawelpabich** [comment]
Release Note: Improved step template management and enabled direct integration with the Community Library

**Comment by wes-novack** [comment]
@pawelpabich disappointed to see that this didn't make it:

`Add ability to update a single action or all projects to the latest version of a step template`

Will there be a new Issue / enhancement opened up for that?

**Comment by pawelpabich** [comment]
Hi @BlairPaine,

Thanks for feedback. We are about to release 3.7 so it won't included in this release but feel free to add it our [User Voice site](octopusdeploy.uservoice.com) as an idea.

**Comment by pawelpabich** [comment]
We have **not** released the ability to update all actions in all projects to the latest version of a step template because the feature was not ready. More details can be found here: https://octofront.com/content/blog/octopus-deploy-3.7-effortless-step-templates

**Comment by wes-novack** [comment]
@pawelpabich that appears to be private. I cannot access the page.

**Comment by diggler001** [comment]
@wes-novack think he meant this:  https://octopus.com/blog/octopus-deploy-3.7-effortless-step-templates

**Comment by pawelpabich** [comment]
thanks @wes-novack. It's fixed now.

**Comment by pawelpabich** [comment]
@wes-novack I know how you feel but [this problem](https://github.com/OctopusDeploy/Issues/issues/2954) is serious enough that decided to wait until we have a solution that works. And yes, we will be starting working on it soon.

**Comment by robpearson** [comment]
@wes-novack I have created a new issue #2985 which covers updating step template in a project's deployment process.  This is my next priority. 👍
