### ISSUE TITLE
4 part version number change from 3.0.71 to 3.4.x

### ISSUE THREAD

**Issue by slaneyrw** [OctopusDeploy/Issues#2703]
v 3.4.x appears to be dropping the 4th part from the generated nupkg if it's 0.
This makes it hard to generate a template build process if the name of the generated nupkg is not consistent.

If there a build config switch that canrevert this behaviour ?

Here are the relevant log output lines

Version 3.0.71

OctoPack:
  OctoPack: Get version info from assembly: TheProject.dll
  Using package version: 1.0.3.0
  OctoPack: Written files: 123
  OctoPack: Copy file: TheProject.nuspec
  OctoPack: Files will not be added because the NuSpec file already contains a <files /> section with one or more elements and option OctoPackEnforceAddingFiles was not specified.
  OctoPack: Attempting to build package from 'TheProject.nuspec'.
  OctoPack: Successfully created package 'TheProject.1.0.3.0.nupkg'.
  OctoPack: Copy file: TheProject.1.0.3.0.nupkg
  OctoPack: OctoPack successful

Version 3.4.1

OctoPack:
  OctoPack: Get version info from assembly: TheProject.dll
  Using package version: 1.0.3.0
  OctoPack: Written files: 123
  OctoPack: Copy file: TheProject.nuspec
  OctoPack: Files will not be added because the NuSpec file already contains a <files /> section with one or more elements and option OctoPackEnforceAddingFiles was not specified.
  OctoPack: Attempting to build package from 'TheProject.nuspec'.
  OctoPack: Setting version to 1.0.3
  OctoPack: Successfully created package 'TheProject.1.0.3.nupkg'.
  OctoPack: Copy file: TheProject.1.0.3.nupkg
  OctoPack: OctoPack successful

**Comment by software-programmer** [comment]
I agree - it broke a number of our templated build configurations in TeamCity

[OctoPack - PR 80](https://github.com/OctopusDeploy/OctoPack/pull/80)

**Comment by KennethBates** [comment]
Hi slaneyrw, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
