### ISSUE TITLE
Can't delete nuget packages, "The resources was not found on this server"

### ISSUE THREAD

**Issue by bigbearzhu** [OctopusDeploy/Issues#2706]
We saw this error when trying to delete Nuget packages from Octopus internal Nuget repository. All packages show correctly, but when I click on Delete button, it shows "The resources was not found on this server" error. The server version is 3.4.0
![image](https://cloud.githubusercontent.com/assets/1924924/18190717/10ba6604-7108-11e6-880f-b7641d02f4f4.png)

**Comment by KennethBates** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
