### ISSUE TITLE
Multiple "No Managed Code" 

### ISSUE THREAD

**Issue by dharmbhav** [OctopusDeploy/Issues#2711]
Hi, 

We are using Octopus 3.4.2 currently. I have successfully configured a .NET 1.0 Core project. In a step to create the AppPool, I am setting the Managed Runtime Version to "No Managed Code" as below:
![image](https://cloud.githubusercontent.com/assets/14266744/18237624/39c2ccc8-7377-11e6-8d82-aba34ed111ee.png)

This works fine for the first time, but on second release onwards, it creates a second option in Application Pool setting as below. Obviously this causes the application to fail (though the release succeeds). If I then manually change the .NET framework version to the first "No Managed Code" option in the dropdown, the app starts working again.

![image](https://cloud.githubusercontent.com/assets/14266744/18237594/dd31f9a2-7376-11e6-8b4f-4487f46980e4.png)

Thanks in advance

**Comment by KennethBates** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
