### ISSUE TITLE
Incorrect Azure subscription ID being written to logs

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2714]
When authenticating with an Azure Service Principal, the following lines are used ( from [AzureContext.ps1](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari.Azure/Scripts/AzureContext.ps1) in Calamari):

```
Login-AzureRmAccount -Credential $creds -TenantId $OctopusAzureADTenantId -ServicePrincipal
Set-AzureRmContext -SubscriptionId $OctopusAzureSubscriptionId -TenantId $OctopusAzureADTenantId  

```

Because no subscription is specified for the `Login-AzureRmAccount` cmdlet, the default subscription is used.  This can result in confusing log messages, where a different subscription ID is shown.  

Functionality-wise, there is no issue, as the following lines sets the context to the correct subscription ID. 

As reported here: https://secure.helpscout.net/conversation/246148033/9463/?folderId=557080

The `Login-AzureRmAccount` cmdlet accepts a SubscriptionId parameter; we should supply it and then there should be no need for `Set-AzureRmContext`.

**Comment by alfhenrik** [comment]
Release note: Correct Azure subscription shown in task log when multiple subscriptions exist
