### ISSUE TITLE
Health Check Step checks too many targets and should be more selective

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2723]
The Health Check Step tests all machines in the target environment instead of being more selective.

The Health Check Step should only test machines included in the deployment, unless the `Include new deployment targets in the deployment` option is selected, in which case it should test all the machines in the environment having any role defined in the Step so they can be considered for inclusion.

**Comment by jmcdade11** [comment]
I got burned by this logic yesterday.  Is there a way to implement this myself in the meantime / is this fix being implemented soon?

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Health Check Step checks too many targets and should be more selective](https://trello.com/c/v9n7IrXS/32-health-check-step-checks-too-many-targets-and-should-be-more-selective)

**Comment by alfhenrik** [comment]
This issue has been resolved as part of https://github.com/OctopusDeploy/Issues/issues/2724, if you are still experiencing these issues, please let us know and we will investigate further.
