### ISSUE TITLE
Library variable set count can be wrong

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#2726]
In some cases the variable set count in the tab header in the project variable library can be incorrect.
See https://demo.octopusdeploy.com/app#/projects/octofx-rate-service/variables/library

The count is from `Project.IncludedLibraryVariableSetIds`. This seems to work correctly currently, perhaps this wasn't cleaned up correctly in the past?

First reported http://help.octopusdeploy.com/discussions/questions/9102

**Comment by matt-richardson** [comment]
One is a variable, one is a script module

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Library variable set count can be wrong](https://trello.com/c/l9Xi90e6/28-library-variable-set-count-can-be-wrong)

**Comment by zentron** [comment]
Release Note: Fix for incorrect library variable set count on project variables tab
