### ISSUE TITLE
Channel versioning rules not applying correctly when having multiple package steps

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2727]
**Setup**
- 1 Channel called `Dev Channel` with rule `[4.0,9.0]` and tag `dev`. Set this one as the default.
- 1 Channel called `Demo Channel` with rule `[4.0,9.0]` and tag `demo`. Do not set as default.
- 1 Package deploy step using package `TicketmasterSystems.Venuemaster` scoped to channel `Dev Channel`. 
- 1 Package deploy step using package `TicketmasterSystems.Venuemaster` scoped to channel `Demo Channel`. 

When you create a release the default channel `Dev Channel` is set, along with the correct step scoped to it and the package with the pre-release tag `Dev`. Now when you change the channel from the dropdown, the steps change as expected, but the package with the `Dev` tag stays, instead of changing to the `Demo` one. This error persists when the release is created and deployed, so its not just a UI thing.

![channelrule](https://cloud.githubusercontent.com/assets/6180562/18356965/6501bb56-75c5-11e6-935c-a15d6f3b73be.gif)

**Source**: https://secure.helpscout.net/conversation/248169978/9555 (private link)
**Octopus version**: 3.4.5

**Comment by droyad** [comment]
This now works (4.1), probably fixed in 4.0:

![channel](https://user-images.githubusercontent.com/1687639/34596712-bfb43458-f22d-11e7-9890-6a9da9cc55be.gif)
