### ISSUE TITLE
Make it easier to deploy to all tenants in an environment

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2729]
When deploying to tenants, I would like an easier way to "Deploy to all tenants that do not already have the release in the selected environment"

In Octopus 3.4.0 you need to deploy to tenants by name, or by tag, but I often find I want to deploy to all tenants in an environment that don't yet have successful deployments of the project.

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it easier to deploy to all tenants in an environment](https://trello.com/c/QkHGk5cV/744-make-it-easier-to-deploy-to-all-tenants-in-an-environment)

**Comment by MJRichardson** [comment]
This been implemented in Octopus 4.0 via a 'Deploy All' button on the project dashboard:

![deploy-all-tenants](https://user-images.githubusercontent.com/113759/32709759-a9728dda-c87e-11e7-8680-69947089d17c.png)

And a 'Add All Applicable Tenants' action when selecting tenants on the deploy-release page:

![all-applicable-tenants](https://user-images.githubusercontent.com/113759/32709776-d689c72a-c87e-11e7-9ed4-cedb4a59b933.png)

**Comment by MJRichardson** [comment]
Release note: It is now easy to create deployments for all tenants which do not currently have the selected version deployed to the selected environment.
