### ISSUE TITLE
Summary -vs- Editor views for Tenant Filters to avoid "wall'o'tags" effect

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2739]
https://octopusdeploy.slack.com/archives/shipping-3-4-0/p1470970212000795

Matt Richardson [12:50 PM]  
just testing out 3.4, and got to the ‘new step’ screen, scrolled down and saw

![image](https://cloud.githubusercontent.com/assets/1627582/18369916/29796d48-766c-11e6-8a44-d4f57eb08f6e.png)

my first reaction was “wow thats scary"

[12:50]  
is it worth collapsing down until its needed?

Michael Noonan [12:52 PM]  
You got slapped in the :eyes: with a wall’o’tags :slightly_smiling_face:

[12:54]  
`Tenants: Any Tenants - _change filter_` type thing, and clicking the link/button could expand. (edited)

Matt Richardson [12:54 PM]  
yeah (edited)

Michael Noonan [12:55 PM]  
And we’d auto-expand it if there was any filtering defined? Or would you prefer/expect a “summary” rolling up the selected tags?

**Comment by michaelnoonan** [comment]
Let's test this in Octopus 4.0 and see how it looks afterwards.

**Comment by droyad** [comment]
@matt-richardson Do you think the new UI covers this? https://frontend-refactor.octopushq.com/app#/projects/a-test-project/process/step/728be193-9173-40c3-b678-d851d14ec70b

**Comment by matt-richardson** [comment]
Yeah, this can be closed - it collapses down well now.

**Comment by droyad** [comment]
Release Note: Collapsed the tenant tag filter section by default to declutter the UI
