### ISSUE TITLE
Ctrl+F hotkey stops working when cursor is on script editor box

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2741]
Steps to repro:

1) On a script step, put the cursor on the editor to add some code and then try to open the browser text search by hitting `Ctrl+F`. The search box doesn't show up.

2) Click someplace else to take the cursor out of the editor and hit `Ctrl + F`. The box shows up as expected.

This doesn't seem to happen with other global browser hotkeys such as `CTRL+T`,`CTRL+N` or `CTRL+R`

Source: http://help.octopusdeploy.com/discussions/problems/47461
Octopus: `3.4.6`

**Comment by droyad** [comment]
Release Note: `Ctrl-F` will now open the browser search function while editing a script
