### ISSUE TITLE
support for subdirectories in the configuration transform

### ISSUE THREAD

**Issue by karlstefan** [OctopusDeploy/Issues#2753]
This is an old issue that to me isn´t fixed. 

I do not want 10 config files and their transform-files laying in my soloution root. I dont even want the config files laying there and the transform-files in a subdirectory. 

Those two scenarios above is working I belive.

My folder structure is like this: 

\Configuration\black.Config
\Configuration\Test\black.Test.Config
\Configuration\Stage\black.Stage.Config
\Configuration\Production\black.Production.Config

So all the config files is in the Configuration root. They are later copied down to the website root. But that is the last deployment step.

I would like this to work.
---------------------------------
Additional transforms: (Variable Environment is Test, Stage, Production)

Configuration\\#{Environment}\black.#{Environment}.config =>  Configuration\black.config

Or

Configuration\\#{Environment}\\\*.#{Environment}.config =>  Configuration\\\*.config
(to get all at the same time)

Not even this is working

#{OctopusOriginalPackageDirectoryPath}\Configuration\#{Environment}\black.#{Environment}.config =>  #{OctopusOriginalPackageDirectoryPath}\Configuration\black.config

And the above row has the exact filepaths into the tentacle deployment folders.

Can you add to honor the path specified? Relatively to the root.

Or maybe relatively to the Transform-file like

black.#{Environment}.config =>  ..\black.config

Edit:
I read this in a different thread
"Octopus iterates through directories so defining the path doesn't work."

It feels like its not entirely true. It doesnt match the files together like it sounds at it should. 

Then  
black.#{Environment}.config =>  black.config
would work, despite the files laying in different directories. But it doesnt

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
