### ISSUE TITLE
SpecialVariables.Tentacle.Agent.ProgramDirectoryPath might not work in PowerShell 2

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2756]
I downgraded Power Shell on one of our VMs to Power Shell v2 and the following test is now failing. This tests works on versions of Power Shell.

http://build.octopushq.com/viewLog.html?buildId=49429&buildTypeId=OctopusDeploy_Testing_TestWindows2008r1sp2&tab=buildLog#_focus=9157

**Comment by markryd** [comment]
Couldn't repro, closing and we'll re-open if a customer reports.
