### ISSUE TITLE
Allow pasting of a list to roles style fields with auto complete

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2765]
This would be mostly helpful on the Script Console page.

Sometimes you have a predetermined list of roles or machines and just want to paste the list into the field, selecting them one at a time can take a lot of time for larger lists.

Source: http://help.octopusdeploy.com/discussions/questions/9141

**Comment by NickJosevski** [comment]
This would be neat for any input that's multi select in v4, bonus points, if you paste in name or ids or a mix, and it finds them.

Would need to handle the case nicely where it doesn't find match, silently skipping it may be confusing, could leverage the missing resource style item.

**Comment by droyad** [comment]
Do as part of #4313
