### ISSUE TITLE
Deadlocking Issue after cancelling a deployment where same package is deployed in multiple steps

### ISSUE THREAD

**Issue by EolAncalimon** [OctopusDeploy/Issues#2769]
We seem to have noticed that when you cancel a multi tenant deployment that deploys the same package  in multiple steps. Any deployment that follows seems to deadlock, all the tenants report that another task is currently uploading the package, and never ends unless cancelled, even server restarts don't seem to fix the issue, it does resolve itself after a certain period of time.

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
