### ISSUE TITLE
Support a special step to acess deployment packages without unpacking them

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2770]
There are often deployment scenarios where a user wants to take their packages application, and either push it manually elsewhere or upload to some service. 
This proposed step would involves selecting a package in the UI, but at deployment time it would simply be made available via populating variables that link to the uploaded package's location.
This could hopefully be a straightforward _tweak_ of the current deployment step, and could involve populating the already available `Octopus.Tentacle.CurrentDeployment.PackageFilePath` special variable, just minus any unpacking conventions.

**Comment by PaulStovell** [comment]
Some scenarios I can think of, that I'd like to make sure anything we build can support:

 - Package is a ZIP file. You just want to push the whole .zip to Amazon S3. 
 - Package is a NuGet file. You want to push the whole .nupkg to NuGet.org
 - Package is a DacPac. You want to run it without extracting anything.

**Comment by zentron** [comment]
One of the key scenarios we wanted to support for this step was for "Naked scripting" where the package is uploaded for SSH execution (i.e. no calamari)
![image](https://cloud.githubusercontent.com/assets/1830666/21597212/7b474b8c-d192-11e6-98b7-25c349ede1b6.png)
Output Variables Include
```
Octopus.Action[Transfer AcmeWeb].Output.Octopus.Action.Package.DirectoryPath
Octopus.Action[Transfer AcmeWeb].Output.Octopus.Action.Package.FileName
Octopus.Action[Transfer AcmeWeb].Output.Octopus.Action.Package.FilePath
```
Although I think all the 3 things you listed could be done now with a secondary script step:

- Given the 1st class AWS support we are trying to provide that could be a nice addition.
- The NuGet feels like it might be a whole step of its own. What would it mean to run that deployment linked to a role or target? It feels like its a slightly different shape.
- This one might make sense to also be handled with a second script step (maybe just one in the library)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Package Transfer Step](https://trello.com/c/CStCe3Nz/19-package-transfer-step)

**Comment by zentron** [comment]
Have moved the acquisition options off this step and non-calamari (for naked ssh scripting) will use the project variable `OctopusUseNakedScript` that is currently used for naked scripts until a more cohesive UX can be provided.

**Comment by zentron** [comment]
Resolved By: https://github.com/OctopusDeploy/OctopusDeploy/commit/fbe9a9bcac2a786f766eac4e362a7f0491824007

**Comment by zentron** [comment]
Documentation: http://docs.octopusdeploy.com/display/OD/Transfer+Package
