### ISSUE TITLE
Provide Tentacle AMIs with each release

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2771]
Provide Tentacle AMIs to AWS marketplace with each release to give AWS users are starting point when they are building their own AMIs.  Saves installing Tentacle every time.

The work @matt-richardson has been doing makes this easy.

**Comment by PaulStovell** [comment]
Before embarking on this I'd like to consider if there are other ways to achieve the goal that won't create another "alternative" way to do something. 

For example, I know AWS lets you inject PowerShell when the machine is provisioned, and perhaps might also allow PowerShell Remoting to connect directly to machines. 

If users in Octopus could add an AWS subscription (like they do for Azure), they could set up rules like:

> When EC2 instances are provisioned with the label pattern "Web*", automatically install Tentacle and assign them to the Web role in Octopus."

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide Tentacle AMIs with each release](https://trello.com/c/O6gKPXAT/29-provide-tentacle-amis-with-each-release)

**Comment by tothegills** [comment]
Keep in mind that when auto-scaling speed is important.  Often providing a script/remoting/dsc is much slower than using a pre-baked AMI.

**Comment by matt-richardson** [comment]
I'm not sure an AMI with a Tentacle on it is the right starting point. There are too many other bits of software that would usually be required to make an Octopus provided AMI the starting point.
 
For this scenario, I'd probably recommend people look at [Packer](packer.io) to take the most appropriate base image and add the required software (including Tentacle) and then create a custom AMI.

Maybe a good solution to this is a blog post showing how to install Tentacle via Packer?
