### ISSUE TITLE
Tenanted project with multiple channels dashboard improvements

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2772]
With untenanted projects that have multiple channels, each channel is separated out into its own table to reduce noise and make it easier to clarify what stage a given release is at.

![image](https://cloud.githubusercontent.com/assets/1830666/18621388/f0731ec0-7e65-11e6-92c5-e51da3cbc646.png)

Although it doesn't make as much sense to split out the tables by channel when tenants exist (since in tenanted projects the Y-axis is tenants and _not_ releases), when you select a specific release from the drop down you should have enough information to filter out those environments that aren't available to that relevant channel.
![image](https://cloud.githubusercontent.com/assets/1830666/18621443/e81f644e-7e66-11e6-9cbb-d756690d9453.png)

It is worth noting that the default, unfiltered tenanted project overview page will still need to consist of a table with _all_ environments since it covers _all_ channels available.

**Comment by cjuroz** [comment]
With untenanted projects with multiple channels it's easy to see in which channel each release belong to. This capability is lost with tenanted projects. 

It would be quite useful to add channel info to multi-channel tenanted projects overview table (maybe using channel tag next to version) 
![image](https://cloud.githubusercontent.com/assets/10542942/21036063/4e18fcfc-bdfe-11e6-8ef7-b4ffce68bf5d.png)
Also, when release filter is applied it should show somewhere the channel that release belong to. Filtering only environments is good but sometimes not enough to figure out which channel has been used.

**Comment by michaelnoonan** [comment]
Things I'd like to see us check for in Octopus 4.0:

- [ ] It's easy to "know" which Channel a release belongs to when you've selected a specific release
- [ ] When selecting a specific release, only the valid environments for the release's channel are shown
- [ ] Have we addressed the concern raised by @cjuroz ?

**Comment by zentron** [comment]
Channel chips added to overview
![image](https://user-images.githubusercontent.com/1830666/31437262-ffa96fc8-aec7-11e7-83f9-016628375d6f.png)

**Comment by zentron** [comment]
@cjuroz , we are actually just about to start the process of opening up our new 4.0 build for public feedback. We'd love to get your input on the new design to see if they help provide better clarity to your deployment status. 
https://twitter.com/OctopusDeploy/status/918039069040324608

**Comment by cjuroz** [comment]
Hi @zentron, thanks for your offering, definitively I would like to test and look how 4.0 is looking. I already registered to have access to it. However, I am on business trip these days but when I am back to office I will dig into 4.0.

**Comment by zentron** [comment]
Added channel chip to the release drop down as well. This will go out shortly as part of 4.0

**Comment by michaelnoonan** [comment]
Release Note: We have improved the Project Overview when the Project uses multi-tenancy and multiple channels
