### ISSUE TITLE
UI - "Verifying account" gets lost above tenant tags

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2773]
When you "save and test" an account, the tick box gets lost above tenant tags so it's not obvious that anything has actually happened:

![image](https://cloud.githubusercontent.com/assets/171197/18656500/e93e2012-7f34-11e6-9713-688b3f2b2949.png)

**Comment by NickJosevski** [comment]
`Save and Test` will display results in a modal dialog in v4.

![untitled_clipping_101117_112302_am](https://user-images.githubusercontent.com/119096/31417995-8d1bf008-ae76-11e7-87d5-37eb59c92398.jpg)

**Comment by NickJosevski** [comment]
Release Note: Saving and testing of azure accounts shows result more clearly
