### ISSUE TITLE
Variable vanishes when step descoped and deleted

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2779]
Pretty easy to replicate:

1. create a step in any project (I used a script step)
2. create a variable and scope it to that step - save
3. remove the scope from the variable - save
4. delete the step that was the scope
.. variable is gone..

Source: http://help.octopusdeploy.com/discussions/problems/47686

**Comment by tothegills** [comment]
Release note: Prevent variable that had ever been scoped to steps and then the scope removed from being deleted when the deployment process is saved
