### ISSUE TITLE
Correct inconsistencies with permissions regarding script console

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2780]
There are some inconsistencies with permissions surrounding the script console. Using an account with System administrator role but not Octopus Administrator team, you are able to run the script but not see the Task log or Script body. 

Can we make the script console feature work for the role and not the team?

To replicate this issue:
1. I created a user, then created a team with only the System Administrator role (unscoped) that the user was a member of.
2. Run script from new account using the script console on all environments.

This issue seems intermittent and I'm not 100% sure to to replicate it every time.

To workaround the issue once it happens, I used Control+Shift+r on chrome to refresh the page while ignoring cache.

![scriptconsoleissue](https://cloud.githubusercontent.com/assets/18252832/18820930/0a3d98c4-83e5-11e6-92b0-db08caaedb08.png)

Source: http://help.octopusdeploy.com/discussions/questions/9181

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Correct inconsistencies with permissions regarding script console](https://trello.com/c/0OcAJl8R/31-correct-inconsistencies-with-permissions-regarding-script-console)

**Comment by alfhenrik** [comment]
We've been unable to replicate the issue, and we've not had any further reports about the issue from customers so we will close this issue for now and if we get more reports of it we'll re-open the issue and re-asses it then
