### ISSUE TITLE
Octo.exe doesn't include files that have square brackets in their names.

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2783]
This looks like a regression in 3.4 because Octo.exe  3.3.18 doesn't have this problem. Based on: https://secure.helpscout.net/conversation/255210814/9971/?folderId=909879

**3.4.2 - broken**

![image](https://cloud.githubusercontent.com/assets/347637/18858580/4f7f0398-84b0-11e6-80ee-847f72fd413f.png)

**3.3.18 - works fine**

![image](https://cloud.githubusercontent.com/assets/347637/18858568/43ecc7ea-84b0-11e6-902c-3f1920fd3054.png)

Command:

`.\Octo.exe pack --id="SqlFilesConsoleApplication7" --format=NuPkg --version=2.12.1.19-dev --outFolder="C:\Users\Pawel\Documents\visual studio 2015\Projects\SqlFilesConsoleApplication7\SqlFilesConsoleApplication7\bin\Debug" --basePath="C:\Users\Pawel\Documents\visual studio 2015\Projects\SqlFilesConsoleApplication7\SqlFilesConsoleApplication7\bin\Debug" --author="" --title="" --description="" --overwrite=True --include="*"`

**Comment by michaelnoonan** [comment]
Interestingly if I open the `.nupkg` file with 7zip the file is actually part of the package contents... I wonder if it's related to the move from NuGet v2 to NuGet v3?

![image](https://cloud.githubusercontent.com/assets/1627582/19994884/27615f9e-a29e-11e6-970b-58c992dfe99b.png)

I'm going to investigate this one further.

**Comment by michaelnoonan** [comment]
After investigating and writing an end to end test that:
1. Creates some sample files
2. Packs them as nupkg
3. Extracts the package
4. Confirms the hash of the contents

This test passes, so it would appear the Package Explorer is potentially the problem here?

Here are the resulting contents of the folders from the test:

```
C:\Users\Michael\AppData\Local\Temp\6fd47b2fe23f4ab9a0d80ef9840de1d3>tree /f /a
Folder PATH listing for volume BOOTCAMP
Volume serial number is 98F2-B9EE
C:.
+---extracted
|       Test.txt
|       Test[squarebrackets].txt
|
+---input
|       Test.txt
|       Test[squarebrackets].txt
|
\---output
        TestPackage.2016.02.01.09.nupkg
```

![image](https://cloud.githubusercontent.com/assets/1627582/19996173/6bc643c4-a2a9-11e6-931f-2a3783a87bf7.png)

**Comment by michaelnoonan** [comment]
A final test: I created the same package using `nuget.exe` `3.4.4` with the same results. I'm going to close this issue, it looks like a problem with NuGet itself.

![image](https://cloud.githubusercontent.com/assets/1627582/20043145/6aec0da4-a4d3-11e6-80c0-4167b270ce0d.png)

![image](https://cloud.githubusercontent.com/assets/1627582/20043150/77cc7432-a4d3-11e6-94c8-550571f599eb.png)

![image](https://cloud.githubusercontent.com/assets/1627582/20043155/8766b75e-a4d3-11e6-8779-9b9e81dcdc46.png)
