### ISSUE TITLE
Streamline editing of tenanted project variables via .NET Client

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2786]
At the moment this operation requires quite a bit of code. Context: http://help.octopusdeploy.com/discussions/questions/9275-how-to-update-tenant-variables-via-octopusclient

**Comment by shem2u** [comment]
It may be worth starting with the REST API.  I used Fiddler to capture the request/response as I groped around for a way to edit the variables and I noticed the collection of variables returned did not include any of those required by a project template but not currently set (i.e. no values).  This was a big part of why the client requires so much code; namely finding the Id values for all the variables that haven't been set.  The second part is having to use the Id values - which are code generated and not the names your users would know.  

I suggest using project variable names as the keys in your api and including any empty pairs.  You could/should still consider hiding some of the navigation cruft of your api in the client.  Right now it doesn't do a whole lot more than create an object representation of the Json returned from a GET ~/api/tenants/{id}/variables.  When someone is going to edit those variables you can be fairly certain they'll know the project/environment so . . .

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Streamline editing of tenanted project variables via .NET Client](https://trello.com/c/k4er8ipU/742-streamline-editing-of-tenanted-project-variables-via-net-client)

**Comment by droyad** [comment]
This will be considered as part of variable unification #4390
