### ISSUE TITLE
Dashboard drop down box for large amount of projects is not in alphabetical order

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2787]
The drop down box you see when you have a large amount of projects on the dashboard is not currently in alphabetical order.

Source: https://secure.helpscout.net/conversation/254231150/0/

**Comment by michaelnoonan** [comment]
I think this has already been fixed? https://github.com/OctopusDeploy/Issues/issues/2743

Feel free to reopen if I'm wrong.
