### ISSUE TITLE
Project Overview error - Sequence contains no matching element

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2790]
The progression API returns a `System.InvalidOperationException: Sequence contains no matching element` exception in some cases:

http://help.octopusdeploy.com/discussions/problems/46424-project-overview-throws-an-exception (v3.2.7)
http://help.octopusdeploy.com/discussions/problems/47292-systeminvalidoperationexception-sequence-contains-no-matching-element (v3.4.1)
http://help.octopusdeploy.com/discussions/problems/47762 (after upgrade from v3.3.0 to v3.4.11)

**Comment by droyad** [comment]
Detect:
```SELECT * 
FROM Release
	INNER JOIN Channel on Release.ChannelId = Channel.Id
WHERE Release.ProjectId <> Channel.ProjectId
```

Fix releases by setting their channels to the default for a project:
```
UPDATE Release SET ChannelID = (SELECT Id FROM Channel s WHERE s.JSON like '%IsDefault":true%' AND s.ProjectId = Release.ProjectId)
FROM Release
	INNER JOIN Channel on Release.ChannelId = Channel.Id
WHERE Release.ProjectId <> Channel.ProjectId
```

It should also be possible to fix these via the UI by editing the channel on the affected releases

**Comment by Dalmirog** [comment]
Another report:

https://secure.helpscout.net/conversation/258173924/0/

**Comment by droyad** [comment]
Also prevents the cloning of the projects

**Comment by thebigmoosey** [comment]
Another report:
https://secure.helpscout.net/conversation/259279652/10183/?folderId=801354

**Comment by droyad** [comment]
I think I've found the problem (or at least one cause). When importing using `octo.exe`, we do not map the `ChannelId` contained in the project's `ReleaseCreationStrategy`. This is then used when auto-creating releases.

**Comment by droyad** [comment]
To fix the data, open the `Trigger` tab of the project, unselect `Automatic Release Creation`, save and then re-enable it.

**Comment by droyad** [comment]
- [ ] Validate `Project.ReleaseCreationStrategy.ChannelId` (and `.ActionId`) when saving a project
- [ ] Fix up existing Releases that have the wrong channel
- [ ] Fix up projects with the wrong channel
- [ ] Add data integrity check where we can't fix up (eg more than one channel)

**Comment by tothegills** [comment]
Release note: Ensure release are created in a channel that belongs to the project the release is created for

**Comment by droyad** [comment]
Fix for `Octo.exe` is in version `3.5.4`
