### ISSUE TITLE
Lifecycles phases are unlocked for all tenants

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2792]
When a deployment is made to a tenant, every other tenant can then progress to the next phase of the lifecycle.  Each tenant should be required to progress through all phases of the lifecycle.

![image](https://cloud.githubusercontent.com/assets/171197/18979996/3ae83aca-8713-11e6-9d71-c7641c665d5a.png)

**Comment by alfhenrik** [comment]
Release note: Ensure a release goes through the correct lifecycle phases for a Tenant, even if the release has progressed past a phase for another Tenant
