### ISSUE TITLE
Viewing script steps considers changes and requires a save

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2801]
When viewing a script step as part of a project process it is immediately marking the step as having changes and requiring to be saved when leaving the step. So far this has only been reported from 3.4+

Happening on demo: https://demo.octopusdeploy.com/app#/projects/octofx-trading-website/process/step/2a6bf866-0d1f-4096-aba7-d132b00f72c9

Source: https://secure.helpscout.net/conversation/256725111/10046/?folderId=557083

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Viewing script steps considers changes and requires a save](https://trello.com/c/HzjxkyCs/32-viewing-script-steps-considers-changes-and-requires-a-save)

**Comment by zentron** [comment]
Release Note: Bugfix causing deployment step to think changes need to be saved after initial page load.
