### ISSUE TITLE
Variableset edit permissions - bug fix and overhaul

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2804]
Currently if you have all the Variableset permissions you cannot edit the variables without variableedit also. If you have variableedit scoped to any project you cannot edit the variablesets variables at all.

The bug is variableedit scoped to projects stopping your ability to edit any of the variableset variables as you cannot scope any variable set variables to projects!

However (the overhaul part) a few of us believe it should be apart from the variable permissions and if you have variableset permissions this is enough. It doesn't make a heap of sense that you need both libaryvariablesetedit and variableedit  to edit libraryset variables. Also the case of needing variabledit for variablesets means you suddenly open up project variables when you might not have wanted to.

Feel free to discuss with Vanessa. 

A couple of sources: (reported in both 3.4 and 3.2)
https://secure.helpscout.net/conversation/233515780/8785/?folderId=557083
https://secure.helpscout.net/conversation/253276535/9841/?folderId=567272

**Comment by vanessalove** [comment]
May require some testing around what it is currently doing as I have only seen the permissions exports and screenshots from users and not extensively tested this myself. :D

**Comment by danielfischeroctopus** [comment]
Another Source: http://help.octopusdeploy.com/discussions/problems/48507-permissions-for-changing-variable-set

**Comment by thebigmoosey** [comment]
Release Note: Allow editing of library variable set variables when the user has LibraryVariableSetEdit permissions (previously needed VariableEdit permissions also)
