### ISSUE TITLE
Migrator import MaxLength failures

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2806]
If you try to migrate a LibraryVariableSet that references a VariableSet with an id of greater than 50 characters (eg. `$variablesets-libraryvariablesets-legacy-snapshot1`), then the migrator fails hard when it tries to import with the error:

"An attempt was made to store 51 characters in the LibraryVariableSet.VariableSetId column, which only allows 50 characters."

<img width="1001" alt="screen shot 2016-10-05 at 9 51 42 am" src="https://cloud.githubusercontent.com/assets/819605/19096740/27b4a79a-8ae2-11e6-9acb-86c6be4e56d5.png">

To be clear, this is not a schema problem. The database has 150 characters assigned to these columns. This is a code problem with migrator using a default value of 50, instead of realising the schema actually has 150 chars. Our `VariableSetMap` correctly has the MaxLengthOverride set to 150 to match the schema, so something about migrator is not honouring this value.

Eg.
```
    public class VariableSetMap : DocumentMap<VariableSet>
    {
        public const int MaxLengthOverride = 150;
```

As part of this solution, please make sure any other models that have IDs > 50 are also fixed if necessary.

**Comment by alfhenrik** [comment]
Release note: Migrator can now import library variable sets with an `Id` longer than 50 characters
