### ISSUE TITLE
Revisit Nuget 3.4 behavior about removing leading and trailing 0 in version numbers.

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2809]
# Background

Refer to source ticket for description of the issue: http://help.octopusdeploy.com/discussions/problems/47256#comment_40659155

Consensus during support call was that we'll do something about this as it will potentially break many CI scenarios.

# How we want to behave with packages and versions

1. We should endeavour to be consistent across our own ecosystem. We work with NuGet and our own built-in repository. Soon we'll work with Docker registries, and eventually NPM, Maven, GitHub releases, etc, all which will have their own standards. We either force people into a "lowest common denominator" of all feeds approach, or we use `string` which enables people to use the feeds as they are intended.
2. We should stick to WYSIWYG wherever possible - if someone asks for a version `2016.06.02` that's what they should get. Otherwise we will make life difficult for scripts in build servers etc.
3. If people use our tools for their build-deploy pipeline, it should just work.
4. If people decide to use their own tooling (like `nuget.exe pack`) they will have to deal with the inconsistencies.
5. When thinking about our built-in repository, we should consider `2016.02.04` as a collision with `2016.2.4` and `2016.2.04` etc just like NuGet do now. This will reduce the chance of ambiguous package references and problems with ordering.
6. We want to sort according to [SemVer 2.0](http://semver.org) so that `1.10.0 > 1.9.0`

# How we'll implement this

We need to consider this from several different angles within the Octopus ecosystem:

1. **How we create packages (using our own tooling)** - WYSIWYG - we don’t do any normalising - there shouldn't be any surprises when pushing a package or referring to it by filename.
2. **How we store and index packages in our own package feed and how we deal with collision detection** - We will store the package and version as-is, but use the normalised version for collision detection.
  a. If there's a possibility of existing duplicates we should come up with a strategy to fix it.
3. **How we interact with package feeds (many and varied, including our own)** - We just ask the feed for a package with the version string we stored in the release, and accept what the feed tells us.

# Plan of action

- [x] `octo.exe pack --format zip` works as described
- [x] `octo.exe pack --format nupkg` works as described (yes, the filename is maintained, but the package metadata is normalized as you would expect with a NuGet package)
- [x] `OctoPack` works as described here for NuGet packages
- [x] Doc page describing how we want to handle versioning

# Design conversations (internal - sorry!)

Initial slack conversation [can be found on this private link](https://octopusdeploy.slack.com/archives/feature-discussion/p1472684872000002). This was also discussed by Mark, Rob W and Vanessa on 06/10 during support call.

And a follow up conversation about the feature discussion [can be found on this private link](https://octopusdeploy.slack.com/archives/feature-discussion/p1478227279000126).

**Comment by droyad** [comment]
The NuGet team have purposefully changed this behaviour (https://github.com/OctopusDeploy/Issues/issues/2813). The solution to this would most likely involve  copying and modifying the NuGet library.

**Comment by whitezel** [comment]
Personally I don't care which way it goes, but there needs to be a decision and notification so that we can choose to change our use one way or the other.

**Comment by vanessalove** [comment]
appears to be effecting package acquisition now on the Tentacle side .. 
http://help.octopusdeploy.com/discussions/problems/47736
escalating

**Comment by pawelpabich** [comment]
This might be related: http://help.octopusdeploy.com/discussions/problems/47736

**Comment by pawelpabich** [comment]
Would this also be related ? https://github.com/OctopusDeploy/Issues/issues/2867

**Comment by michaelnoonan** [comment]
I don't think so @pawelpabich - I think that will be a different problem based on the example you've given.

**Comment by michaelnoonan** [comment]
Wrote a doc page describing the ins and outs of versioning in Octopus Deploy: http://docs.octopusdeploy.com/display/OD/Versioning+in+Octopus+Deploy

**Comment by JustinChristensen** [comment]
@michaelnoonan It's related in the sense that Octopus isn't currently (as of 3.4) comparing numeric pre-release tags numerically for SemVer v2.

From [Semver v2 docs](http://semver.org/):

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: **identifiers consisting of only digits are compared numerically** and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers.

**Comment by michaelnoonan** [comment]
Hi @JustinChristensen - looks like @tothegills is going to be working on this soon over in #2867. This issue was meant to be more focused on how we handle version number normalisation/truncation.

Hope that helps!
Mike
