### ISSUE TITLE
ARC UI only displays if a package is in your deployment process

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2810]
To avoid confusion, we should show a different message about ARC when there's no package available in your deployment process (instead of showing nothing). It's confusing for a lot of users who are looking for the feature (and they can't find it because they removed a package step).

If we had a message like: "To enable ARC, please add a package to your deployment process" or something like that, it would help.

**Comment by rokeno** [comment]
I have had the exact same problem: I went to the Triggers page and unchecked the Create an automatic release and pressed Save. Once i did that, the whole right menu of ARC disappeared and i cannot bring it back.
My problem is that i **have** a deployment package from an external repository.

**Comment by thebigmoosey** [comment]
Release Note: Improved UI messaging around Automatic Release Creation
