### ISSUE TITLE
Mask sensitive variables when performing offline deployments

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2812]
In some situations (eg AWS CodeDeploy) the console output from offline deployments is persisted. The output can contain sensitive variables. Use the same masking technique we use on the server to hide those variables from the logs.

**Comment by droyad** [comment]
This may become less of an issue due to [release promotions](https://octopus.com/blog/roadmap-2017)

**Comment by MJRichardson** [comment]
As @droyad mentioned, [Remote Release Promotions](https://octopus.com/blog/remote-release-promotions-rfc) will hopefully supercede offline deployments in many scenarios.

Given that, we can't justify this change.
