### ISSUE TITLE
Add Tenant Icons to machines in environment view

### ISSUE THREAD

**Issue by graemechristie** [OctopusDeploy/Issues#2814]
We are using Tenants in our Octo setup.

From the environment screen we can see which labels are assigned to a machine, but not which tenant.

In our case, a machine can be shared by multiple tenants.

Due to the fact that adding mutiple labels against machines restricts the targeted tentants to those that have all labels for the machine (rather than any label for a machine), we can't use labels for targeting deployment hosts. We need to add all Tenants individually - which is fine, however it is difficult to tell which tenants are assigned to a machine from the environments screen.

To alleviate this issue, I have developed a tampermonkey script that shows a tenants logo as a 25x25 icon on the environment screen. It has turned out to be an effective use of real estate and makes it very easy to visually identify tenants.

I thought I would suggest that this should be an option in the default interface. Here is an example screenshot from our environment.

![image](https://cloud.githubusercontent.com/assets/1361894/19180171/254b474c-8c96-11e6-8a58-9d0f6e3463c3.png)

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to do this is add a suggestion to our UserVoice site: https://octopusdeploy.uservoice.com

We have had a few suggestions like this, but nothing official - so tracking some votes would give us an indication how strongly people feel about it.

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
