### ISSUE TITLE
Support tables and other formatting in markdown

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2819]
By default the current markdown-html converter isn't configured to parse tables, nor other formatting like strikethrough. We could enable this easily enough, and upgrade the `showdown` library to the latest version fixing bugs along the way.

Source: http://help.octopusdeploy.com/discussions/problems/47995-markdown-structure-in-release-notes

**Comment by alfhenrik** [comment]
Release note: Add support for tables and strikethrough where Markdown can be used
