### ISSUE TITLE
No package for the action $GUID on the server was acquired

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2820]
These sources are for two different scenarios where customers were using the roles feature for Azure steps, but not for Cloud Regions. In the first source, I held a support call and confirmed the problem was due to the role having a real machine/tentacle. This meant the package was acquired on the target, and prevented the Octopus Server from acquiring the package.

For the step types which are always executed on the Octopus Server, we should make certain the Octopus Server gets the package, and not the target. Similarly we should check for Azure Targets in the roles because any steps targeting those will be run on the Octopus Server.

**Steps to reproduce**

1. Create a project with a single Azure PowerShell Step which runs a script from a Package
2. Target the Step to a role which has just one real Tentacle in it
3. When deploying the project, the Package will be acquired on the Tentacle, and not on the Octopus Server, and the deployment will fail.

Source: http://help.octopusdeploy.com/discussions/problems/47942-no-package-for-the-action-guid-on-the-server-was-acquired
Source: http://help.octopusdeploy.com/discussions/problems/47952-activity-xxx-on-yyy-failed-with-error-no-package-for-the-action-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-on-the-server-was-acquired

**Comment by mdaquel** [comment]
Upgraded our server to version 3.4.12 and now experiencing this issue on one of our project. Any update?

**Comment by tothegills** [comment]
Another report: http://help.octopusdeploy.com/discussions/problems/48054

**Comment by alfhenrik** [comment]
Release note: Ensure package is downloaded on the Octopus server for steps that use a package and executes on the server.
