### ISSUE TITLE
The connection is broken and recovery is not possible

### ISSUE THREAD

**Issue by BatsIhor** [OctopusDeploy/Issues#2827]
Hi, 
I have .NET Framework 4.6.1 and Octopus 3.4.4 
Just recently we started to have the this issue, in "Run an Azure PowerShell Script"

The step failed: Activity Swap Environment Slots on the Octopus Server failed with error 'The connection is broken and recovery is not possible. The connection is marked by the server as unrecoverable. No attempt was made to restore the connection.'.
Could you please help me with that?

Thank you 
Ihor

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
