### ISSUE TITLE
Errors in custom health checks cause Tentacle upgrade box to be displayed

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2829]
Custom health check policy that uses 'write-error' to fail the health check (I want the machine to be considered "unhealthy") I get the Tentacle out of date message on the environments page.

![image](https://cloud.githubusercontent.com/assets/171197/19335923/5ccba320-914a-11e6-93df-66844d5a666b.png)

The health check shows the Tentacle is up to date:

![image](https://cloud.githubusercontent.com/assets/171197/19335936/83669f76-914a-11e6-9af5-fe2e7c8e99b8.png)

**Comment by thebigmoosey** [comment]
Tested and LGTM
