### ISSUE TITLE
Support for NPM and Bower feeds

### ISSUE THREAD

**Issue by ramondeklein** [OctopusDeploy/Issues#2832]
It would be great if Octopus would also support external NPM and Bower feeds instead of NuGet or the internal Octopus feed.

**Background**
Octopus does a great job when deploying Windows software based on NuGet packages. As described in #2183 the NuGet package format isn't always suitable. Octopus now supports to store arbitrary archives in the internal Octopus feed. Although this might be useful in some cases, you don't want Octopus to become a package repository. Octopus can also fetch from TeamCity, but TeamCity is also limited to a NuGet only feed and should be responsible to build software, not to host it.

I think that neither TeamCity nor Octopus should be used as package repositories for large scale applications. There are numerous good alternatives (like [MyGet](http://www.myget.org/) or [ProGet](http://inedo.com/proget)) that are specialized in hosting package repositories.

Octopus can connect to such a repository for NuGet packages, but this is rather limited. Creating NuGet packages on non-Windows platforms in cumbersome, but it's very easy to create a Bower or NPM package. If Octopus could fetch from NPM or Bower feeds, then these packages could be consumed in much more natural way.

Both package systems use a similar versioning scheme as NuGet and also supply meta information that is needed by Octopus for discovery of packages and their versions. Then you could use the following paradigm that uses proper separation of concerns:

- TeamCity: Builds software
- Octopus: Deploy software
- Proget: Store artifacts

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to do this is add a suggestion to our UserVoice site: https://octopusdeploy.uservoice.com

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
