### ISSUE TITLE
Add number padding for date version created by octo.exe pack

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2838]
When no version number is given and octo.exe creates the version number based on a date timestamp, the numbers need to be padded to account for alphanumeric version ordering.

ie 2006.9.24 should be lower than 2006.10.3

Source: https://secure.helpscout.net/conversation/259903157/10231/?folderId=845288

**Comment by alfhenrik** [comment]
Due to NuGet 3.4 normalising versions (any part) that start with `0`s this ticket is blocked until https://github.com/OctopusDeploy/Issues/issues/2809 has been resolved.

**Comment by vanessalove** [comment]
This is a red herring - numeric ordering is applied to version numbers, alphanumeric is only applied to tags. The customer was using an incorrect feed for the project in question. We should not pad these numbers.
