### ISSUE TITLE
Deployed version highlighting not correct for channels on project dashboard

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2841]
When you have multiple channels on the project dashboard the currently deployed highlighting for each environment does not appear to be channel specific. It works with only one channel, but when a second is added and has releases the highlighting seems to spread over all channels, where the intention and expectation is that it would be per channel to know the last version on each environment.
Working without a channel:
![fading1](https://cloud.githubusercontent.com/assets/7697660/19463934/7549a862-953b-11e6-87c9-671139dd1c97.png)
With channel not working as expected:
![fadingwchannel](https://cloud.githubusercontent.com/assets/7697660/19463928/6eda05d0-953b-11e6-8e03-c6388c4375bf.png)

Sources: 
http://help.octopusdeploy.com/discussions/problems/47987
http://help.octopusdeploy.com/discussions/problems/47598
http://help.octopusdeploy.com/discussions/problems/52808

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deployed version highlighting not correct for channels on project dashboard](https://trello.com/c/na0B4EQ0/33-deployed-version-highlighting-not-correct-for-channels-on-project-dashboard)

**Comment by zentron** [comment]
According to discussions the correct rules should be that each set of releases for each channel are evaluated indipendantly. The ✅  shading  should show darkest _**for each environment**_ in _**each channel**_ for the _**latest deployment**_.

I.e. If two releases for two different channels have taken place _to the same environment_ then both should have the darker shading.

There appears to be a bug in the SQL that does not factor in Channels, and some code in the server-side which attempts to make up for this fact with its own logic (which is incorrect). As this query is used elsewhere i'll need to make sure this does not have any knock on effects.

**Comment by zentron** [comment]
Will be resolved by adding extra project flag https://github.com/OctopusDeploy/Issues/issues/3343

**Comment by zentron** [comment]
### Current behaviour ###
![image](https://cloud.githubusercontent.com/assets/1830666/24488522/c1802720-155a-11e7-9578-2a7d6b500dd7.png)

### Setting new project-level flag ###
![image](https://cloud.githubusercontent.com/assets/1830666/24488513/b5e61a00-155a-11e7-83bf-364d5f048bb6.png)

### New dashboard ###
![image](https://cloud.githubusercontent.com/assets/1830666/24488533/c5cd334a-155a-11e7-970f-e25d7201cf27.png)

**Comment by zentron** [comment]
Release Note: New flag on project to support concurrent active channel deployments
