### ISSUE TITLE
Create a Support bot to close tickets in Tender that have not had a response in >3 months

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2842]
Currently the number of tickets being hijacked are enough to cause problems. It is effecting the support we give, as it ends up buried in someones Q who isn't on support and goes unanswered if time isnt spent managing the assigned Q (time could better be spent!).

Majority we need more information or logs or to mark private anyway - if we closed any inactive after 3 month tickets with a message saying please create a new one this wouldn't happen.

Notice:
This issue has been closed due to inactivity. Please create a new thread if you believe you have the same issue or require further assistance or the issue as reoccurred. Note that if you are starting a new thread and we asked for specific logs or details they will need to be provided. Feel free to link to this issue as background if it is relevant. If you are the creator of the thread and believe it should not be closed let us know via our support email.

**Things Support bot should do:**
- [ ] Close tickets that have not had a response from the customer in >3 months
- [ ] Be able to query about your ticket queue
- [ ] Be able to query about unassigned/pending tickets

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a Support bot to close tickets in Tender that have not had a response in >3 months](https://trello.com/c/dzg8T5aD/13-create-a-support-bot-to-close-tickets-in-tender-that-have-not-had-a-response-in-3-months)

**Comment by alexrolleyoctopus** [comment]
No longer required as Tender has been replaced with Discourse.
