### ISSUE TITLE
Release dropdown not updating with new releases on the project overview

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2843]
This is when Tenant deployments is enabled

Source: http://help.octopusdeploy.com/discussions/problems/48248

> I have the multi-tenant feature turned on. I am in the project overview page. The bug shows up in the "Show current releases" at the top right. When you click this textbox, the list of current releases is supposed to show up. It does... But that list is not automatically updated. So if I leave my browser on the overview page and it has releases A and B in the drop-down then let's say a release C and D were created. The drop-down never shows C and D unless I refresh the page or navigate away and navigate back to the page. This is only a minor inconvenience but I figured with all the work yall did getting everything to show on the browser as it happens that you might like to know about this one.

**Comment by michaelnoonan** [comment]
Let's confirm this works as expected before shipping Octopus 4.0

**Comment by droyad** [comment]
This filter now queries the API when a release number is typed, so it will get the latest

**Comment by droyad** [comment]
Release Note: The project overview version filter now allows filtering of releases created after the page was loaded
