### ISSUE TITLE
0 matching tenants when specifying both the tenant and their associated tenant group for a release

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2844]
GIF of issue in source ticket (also replicated locally).

Source: http://help.octopusdeploy.com/discussions/problems/48237

**Comment by michaelnoonan** [comment]
Let's make sure this works as expected before we release Octopus 4.0

**Comment by MJRichardson** [comment]
Verified working in 4.0

**Comment by MJRichardson** [comment]
Release note: Resolved issue where selecting both the tenant and a matching tenant-tag resulted in a mis-match.
