### ISSUE TITLE
Bring back ScopeSpecification.IsApplicableTo in Octopus.Client

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#2845]
This method was moved from the public API in `3.4.0` but we have customers that are using it so we should look at bringing it (or something similar) back for them to use.

Source: http://help.octopusdeploy.com/discussions/questions/9053

**Comment by tlycken** [comment]
Is there any update on this? I've still not dared to upgrade my NuGet references, because I worry this will keep breaking my code.

**Comment by tlycken** [comment]
@alfhenrik *bump* would love to at least get a status update on this. `v4.3.1` is out, but it still doesn't seem to have this re-added...

**Comment by alfhenrik** [comment]
@tlycken unfortunately I don't have any status update on this issue. 

Sorry for the inconvenience caused.

Best regards,
Henrik

**Comment by tothegills** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bring back ScopeSpecification.IsApplicableTo in Octopus.Client #2845](https://trello.com/c/Zzl2JB79/55-bring-back-scopespecification-isapplicableto-in-octopus-client-2845)

**Comment by tothegills** [comment]
The logic that used to be `ScopeSpecification` has moved to `ScopeScenario`. The methods are: `Excludes` instead of `IsExcludedBy` and `AppliesTo` instead of `IsApplicableTo`.

**Comment by tothegills** [comment]
`ScopeScenario` is not exposed in the client 🤦‍♂️

**Comment by tlycken** [comment]
For my particular use case, it would be good enough if the client exposed a way to, given a specific scope (i.e. project, environment, service etc), get the value of a variable. I don't need all the information that `ScopeSpecification` provides - I just need to determine what the value of a particular variable should be given a set of circumstances.
