### ISSUE TITLE
Add ordering preference to SemVer tags

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2847]
Currently in the SemVer spec tag ordering is kept as 'undefined' however there is a bit of an expectation for Octopus to have a defined ordering within the tag.

Spoke to Michael RE this who also agreed we could be better than flat alpha-numeric on the tag as a whole.

Source: http://help.octopusdeploy.com/discussions/problems/48174

**Comment by MJRichardson** [comment]
This is consistent with the [SemVer spec](http://semver.org/spec/v2.0.0.html), which specifies 

> Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85

This issue is perhaps more that when multiple release version have the same precedence, the release should probably be ordered by creation date?

**Comment by droyad** [comment]
Since this is consistent with SemVer, and we recommend not relying on metadata to differentiate releases. A release should have a unique version number (ignoring metadata) as this is in the spirit of SemVer.
