### ISSUE TITLE
Script Step Template Runner

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2851]
Octopus already has a "Script Console" which allows administrators to run arbitrary PowerShell across machines. It would be great if they could choose a step template to run instead, and provide parameters. 

This feature helps a few stories:
- Testing step templates: as a step template author, it would be great to be able to test small changes to my step template without the usual dance of updating projects and re-creating releases. 
- Making reusable script console scripts. E.g., something like "restart a windows service" could be scripted once and used many times whenever needed.

**Comment by PaulStovell** [comment]
Primary UI flow:

1. User goes to Library -> Step Templates
1. Next to each template is a "test" button
1. It takes them to the Script Console page with their template selected, ready to enter parameters and choose machines to run it on. 

Alternative UI flow:

1. They can go to Tasks -> Script Console and choose a template

Limitations:

 - Only works for Script-type step templates

**Comment by PaulStovell** [comment]
Checklist

- [ ] "Run" button on Library -> Step Templates -> Edit to go to Script Console with the step template selected
- [ ] Drop down on Script Console to choose a step template (for alternate UI flow)
- [ ] When a Step Template is selected, dynamically load the UI for the parameters
- [ ]

**Comment by PaulStovell** [comment]
Step templates now have a "Run" button. We'll eventually move this to the list page (@pawelpabich), for now I've just put it here. If you click it without saving your changes first, you'll be prompted to save them.

![01-run](https://cloud.githubusercontent.com/assets/47085/19606214/3935b17e-9804-11e6-8ba1-1c33a56e6236.png)

You're taken to a page where you can enter values for any parameters in the template:

![02-run-page](https://cloud.githubusercontent.com/assets/47085/19606232/52d5ce52-9804-11e6-9f76-71e9604522de.png)

Clicking "run now" executes the task as you would expect:

![03-ran](https://cloud.githubusercontent.com/assets/47085/19606247/65f2ec7c-9804-11e6-94b5-edd6b9a40b16.png)

A "Template parameters" tab tells you more about exactly what we ran - including the version number of the template, the parameters used, and the script body itself. This is useful if you are trying different variations of the template and need to revert back. 

![04-params](https://cloud.githubusercontent.com/assets/47085/19606371/17f55982-9805-11e6-9c0e-d6499fac175f.png)

Clicking "Modify and re-run" takes you back to the run page, with your previous settings selected, except for sensitive values:

![2016-10-22 02_58_58-run step template - octopus deploy](https://cloud.githubusercontent.com/assets/47085/19606401/43ecfbd0-9805-11e6-9911-e47ba2a3c01b.png)

**Comment by zentron** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/1830666/21599827/7b9434c0-d1be-11e6-87d9-2fcc5c54cb57.png)
Added in `3.7.0`
