### ISSUE TITLE
Using string interpolation with Serilog can cause IndexOutOfRangeException

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#2853]
Some of the client libraries are using string interpolation in calls to Serilog.  The single string value passed to Serilog is then interpreted by it as a messageFormat, and if that contains certains data values it can cause the above exception.

In analysing a log from a server where this has happened, the logged string contained the substring "{,@}", which caused the exception.

The string interpolation should be removed from the Octopus Client's Serilog calls.

This has impacted the TeamCity plug, and possibly the VSTS plugin.

**Comment by slewis74** [comment]
Source https://secure.helpscout.net/conversation/266756203/10610/?folderId=557082

**Comment by droyad** [comment]
Fixed, will be in the TeamCity Agent 4.0 release

**Comment by michaelnoonan** [comment]
This won't affect VSTS at all and if there is a problem we will open a new bug.
