### ISSUE TITLE
Publish Tentacle VM Extension to Azure Marketplace

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2859]
We previously had a [Tentacle Virtual Machine extension](https://azure.microsoft.com/en-us/blog/octopus-on-azure/) available in Azure.  It was published by Microsoft; they recently changed the way VM extensions are written, and removed our extension.  

We need to publish a new one, following [this guide](https://github.com/Azure/azure-marketplace/wiki/Getting-Started-with-Virtual-Machine-Extensions).  We have apparently been approved for publishing.

As reported in this [support thread](http://help.octopusdeploy.com/discussions/problems/46081).
- [x] Add warning to docs explaining the missing extension
- [ ] Fix it!
- [ ] Update docs accordingly for the new extension
- [ ] Remove the warning from the docs

**Comment by michaelnoonan** [comment]
Relates to #2818

**Comment by mapeterson42** [comment]
FYI, the "this guide" link returns a 404.

**Comment by mapeterson42** [comment]
I see Paul updated this 4 days ago, does that mean this may get fixed in the first half of the year?

**Comment by matt-richardson** [comment]
We are working on it right now. Unfortunately, its nowhere near as simple as it should be.... 

That "this guide" link goes to a private Microsoft repo - you have to have permissions to see it.

**Comment by BlairPaine** [comment]
Hi,

Any further news/updates on this issue please?

I found some unsupported docs at https://github.com/Azure/portaldocs

Cheers,
Blair.

**Comment by matt-richardson** [comment]
Hi @BlairPaine 

Its still in progress, but we are very close. 

Turns out that
> its nowhere near as simple as it should be...

was an understatement. 

Hopefully we should have some good news for you in the next few weeks.

Cheers,
Matt

**Comment by BlairPaine** [comment]
Hi @matt-richardson 

Thank-you for the update. If you're close enough and need someone to test it out please let me know. I'd be happy to help out and provide some feedback.

Cheers,
Blair.

**Comment by matt-richardson** [comment]
Thanks for the offer, @BlairPaine. Can you ping me via our [support email](https://octopus.com/support) and we can chat about it?

**Comment by johnsimons** [comment]
@matt-richardson is this done?
We seem to have 2 tentacles published?
https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=octopus&page=1

**Comment by johnsimons** [comment]
Fixed naming issue - https://github.com/OctopusDeploy/OctopusAzure/pull/1
