### ISSUE TITLE
Auto-deploy deployment process simulator

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2866]
Based on #2865.

We generally like to make things What You See Is What You Get - and this is especially important when it comes to auto-deploy which will likely happen when you are trying to get some hard earned sleep!

We could offer a service that lets you choose the "scope" for a deployment and see a summary of the resulting process that will be executed.

We could make it so you can choose some sample Machines from existing Machines related to the Project: "Show me what would happen if another machine just like this one triggered an auto-deploy right now"

**Extension Idea**: Something like this might actually make sense in the Deployment Process designer area. It would be nice if you could choose a Channel/Environment/TenantTag, etc, and see the resulting process, or even work on the Process where new steps are automatically scoped to the selected Channel/Environment/TenantTag.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto-deploy deployment process simulator](https://trello.com/c/oVH14rXo/27-auto-deploy-deployment-process-simulator)

**Comment by pawelpabich** [comment]
Reconsider once v4 with new UI is released.

**Comment by droyad** [comment]
This is quite a big piece of work and it's unlikely to bubble to the top in the near future.
