### ISSUE TITLE
Retention policy fails, and then hits serialisation exception

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#2870]
08:38:20 Fatal | ISerializable type 'Octopus.Shared.Tasks.ActionFailedException' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present. Path '', line 1, position 1798.

Originally reported at http://help.octopusdeploy.com/discussions/problems/48485

**Comment by pawelpabich** [comment]
This is the same problem as what we've fixed here: https://github.com/OctopusDeploy/Issues/issues/2226

**Comment by pawelpabich** [comment]
Release Note: Failed deployments with Manual Intervention and/or Guided Failure mode don't break Retention policy anymore
