### ISSUE TITLE
Xml Configuration transforms unclear

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#2871]
The Xml Configuration Transforms feature appears to imply that you need to check the `Automatically run configuration transformation files` checkbox to get additional transforms to work, however, this is not the case. Also, it is unclear what order transforms will be executed in.

![image](https://cloud.githubusercontent.com/assets/373389/19841867/213eb99e-9f66-11e6-8c8e-a53b89727007.png)

We should look to resolve this confusion, either by:
- Update the wording to make it clearer that you dont need to check the box to have additional transforms executed, or
- Change the UI to allow the user to specify exactly what transforms are applied, and in what order.

**Comment by matt-richardson** [comment]
Related to #2758

**Comment by droyad** [comment]
New UI makes the function of this checkbox clearer:
![image](https://user-images.githubusercontent.com/1687639/31332630-7357c964-ad2a-11e7-834e-1b59d42b5c44.png)

**Comment by droyad** [comment]
Release Note: Clarified in the UI what the `Run default XML transforms` checkbox does
