### ISSUE TITLE
Provide Docker Compose feature integrated as a first-class step

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2875]
- [ ] Bind service images to Octopus package selection
- [ ] Allow providing dependencies in seperate package? E.g. Build files etc.
- [ ] Allow providing docker-compose.yaml file as package
- [ ]  Support scaling of services
- [ ] Pass enough information to output variables so further commands could be run manually in later steps if desired
- [ ] Support [multiple compose files](http://docs.master.dockerproject.org/compose/extends/#different-environments)?

**Comment by zentron** [comment]
so toying around with how a compose step might look. Whats thoughts on this approach?

When you run a compose file, it creates all the networks/containers/volumes and groups them together. you can provide a project name so that you can then issue other `docker-compose` commands to scale/stop/rebuild etc.
Im thinking that by default the name should be scoped to the project/environment, so that you can have 1 per environment, but leave it unscoped to release, so that potentially when you have a new release, with a new version of some container. it can re-run `docker-compose up`, causing the changed container to be recreated but leaving the others.  (allowing for passing through `--force-recreate` command to recreate all)

The key here is that you could only ever have one "compose project” active at any one time (per environment).
This is slightly different with normal package extraction where the contents are namespaced via the filesystem. but i think it makes more sense in this case

**Comment by RehanSaeed** [comment]
Consider adding support for [Distributed Application Bundles](https://blog.docker.com/2016/06/docker-app-bundle/) as this seems like the equivalent of a NuGet package for Docker. The only problem is that it's experimental at this stage. Does anyone have any ideas when it will be released if ever?

**Comment by herecydev** [comment]
I believe it's out of experimental in `1.13`. There's definitely a lot of backing from docker, unfortunately there's just a lot of fundamental problems they still need to solve (i.e. how do you bind/mount volumes when it may not exist across all machines). I would say not to worry too much about implementing it yet, as for real-world scenarios it's basically unusable at the moment. Would be better once all of the pieces are together.

**Comment by RehanSaeed** [comment]
1.13/1.14 is when it will be solidified apparently https://github.com/docker/docker/issues/26876

**Comment by herecydev** [comment]
Yep, which is fine and promising news but that could be years away at this point. I certainly don't think they have a similar release cadence to Octopus, so I wouldn't hold out for this feature, especially when compose is well-established.

**Comment by zentron** [comment]
Thanks for the feedback @RehanSaeed. As stated in the RFC, we will probably put DAB on the back burner until we have better support for existing Docker orchestration options.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide Docker Compose feature integrated as a first-class step](https://trello.com/c/YFEuhP24/25-provide-docker-compose-feature-integrated-as-a-first-class-step)

**Comment by herecydev** [comment]
Any update on this? Excluding DAB, even simple compose support would be invaluable for supporting the basics of Docker from within Octopus.

**Comment by zentron** [comment]
Hi @herecydev so far this task has not yet been put at the top of the list unfortunately. So far the usage of the existing Docker steps, while admittedly basic docker engine steps, has been fairly low and so the Docker integration has become less of a priority. For the sake of future development what are your thoughts on how we should approach this feature when we do take it on?

**Comment by herecydev** [comment]
It's not entirely surprising, it's still opt-in so not immediately accessible to everyone and the docker support is very simplified at the moment. You've added the docker run with some of the simple settings (ports, volumes, restart policies) which is great, but it's comparable to the "tech sales demo" where the minimum works but you're always going to need more.

Docker run/stop paved the way for things like compose/swarm but you can't use it for building the entire platform. What you've listed [here](https://octopus.com/blog/docker-compose-naming) feels like the correct way of approaching it. You want the `docker-compose.yml` to be either in source control or managed by octopus but essentially octopus to be issuing the `docker compose up`. The variables are a neat way of leveraging the "octopus way" but would be nice to also support [compose's built in method](https://docs.docker.com/compose/compose-file/#variable-substitution) using `.env` perhaps on the target.

I disagree with building from octopus, the deployment tool should be focused on orchestrating your services to different environments and not building. You still want to be able to run a `docker compose up` and expect it resolve the images.

Other than that, I feel like you've addressed the majority of issues you'll probably face. After all docker compose is doing the heavy lifting for the containers and octopus just needs to plumb in the variables and naming schemes.

**Comment by RehanSaeed** [comment]
@herecydev Has provided a great answer. I only want to add that Octopus could add support for Docker Secrets using it's variables.

**Comment by herecydev** [comment]
A little revision... I would like to see `.env` support but having this living on the target is error prone for rollback. Would be better to store in octopus (or at least provide the option).

**Comment by RehanSaeed** [comment]
It's been some time since this was raised and a lot has changed, so here is an update since I'm currently trying to use Octopus to deploy a docker stack (as opposed to docker compose).

I'd like a way to deploy my docker-stack.yml file on my Swarm created using 'Docker for AWS'. I can't use the .NET Core version of Calamari because 'Docker for AWS' uses Moby Linux (based on Alpine Linux) which is not a supported OS by .NET Core. I can install Mono but the EC2 instances can be blown away at any time and replaced by new instances because 'Docker for AWS' uses AWS Auto Scaling Groups to increase/decrease the number of nodes in the Docker Swarm and also deal with bad nodes by simply replacing them.

I've also thought about running an SSH command from my Octopus server but that's Windows so I'm not sure that would work???

I raised [this](https://github.com/docker/for-aws/issues/96) GitHub issue where they suggest creating a Calamari Docker container which can run docker commands.

What are my options? I can see no straightforward route to deploying my docker stack using Octopus Deploy.

**Comment by matt-richardson** [comment]
@RehanSaeed - I've replied over on https://help.octopusdeploy.com/discussions/questions/12443-docker-swarm-step-template#comment_43319048.

**Comment by zentron** [comment]
As DockerCompose has waned in popularity as mechanism to orchestrate containers in production, we have decided to focus our efforts on proving support for tools such as kubernetes instead. 

With the support added for package references in scripts, docker compose steps can be easily added into existing deployments https://octopus.com/blog/docker-compose
