### ISSUE TITLE
Deploy and PreDeploy scripts not executed when using SSH targets

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#2876]
When deploying a tar.gz based package to an SSH target the script identified by the step gets executed but PreDeploy.sh and Deploy.sh do not.

Source http://help.octopusdeploy.com/discussions/problems/48450-linux-deploy-using-ssh-endpoint-succeeds-but-does-not-run-the-predeploysh-and-deploysh-scripts

**Comment by slewis74** [comment]
Also tested with a NuGet package and behaviour was the same

**Comment by slewis74** [comment]
This could come down to the step type that's being used.  If you use "Deploy Script", it only executes the specific script you identify.  If you use "Deploy a package" it executes PreDeploy and Deploy.  Confirmed this works in 3.5.

**Comment by vanessalove** [comment]
Deploy script with a package is not the same as our package step. If you want to run the conventions it should be under the deploy a package step. We have an ordering for that purpose. If it is changed to a package step it will work. Closing this out. Can be made into a UserVoice suggestion to determine need for this or what scenario it is valid for.
