### ISSUE TITLE
10 Retries on a deploy will ignore the error and skip to the next step

### ISSUE THREAD

**Issue by bpBogdan** [OctopusDeploy/Issues#2882]
[ BUG ]
We are using Octopus 3.4.12 and see that if a deploy fails and you retry it for 10 times, the failing step will be ignored and it will skip to the next step. Can this issue be fixed with an update or a configuration change?
In order to reproduce it you only need to create a project and a step that throws an error. This way it will fail. Then retry it 10 times by using the "assign to me" option and "Retry". After "Retry attempt #10" it will go directly to the next step (if exists), or directly pass the deploy, if is the last step

**Comment by vanessalove** [comment]
Hi @bpBogdan, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
