### ISSUE TITLE
Cannot extract zip file: Memory stream is not expandable

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2883]
As reported here: http://help.octopusdeploy.com/discussions/problems/48593

Ticket above includes zip file.  I was able to replicate the issue.

In this case the customer has indicated the zip was created by [grunt-octo](https://github.com/OctopusDeploy/grunt-octo).

Appears similar to http://help.octopusdeploy.com/discussions/problems/44405-exception-unzipping-files

**Comment by alfhenrik** [comment]
Fixed as part of https://github.com/OctopusDeploy/Issues/issues/2888 which was released in `3.5.2`
