### ISSUE TITLE
WebSite and AppPool fields values are retained after IIS feature is disabled

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2886]
*all this happens in the regular "Package Deploy step" and not in the new "IIS" step*

1) Enable the IIS feature in your package step.
2) Fill in Website Name, Pool, Add a non-port-80 binding and change the authentication method to "Anonymous".
3) Deploy your website successfully.
4) Disable the IIS feature and save the step.
5) Re enable the IIS feature and save the step. If you notice the Website and AppPool names are still there, but the rest of the site config its not. If a deployment takes place right now it could seriously mess up the site config.

The user that reported this wanted to disable the IIS feature for a moment and just deploy the package contents.

The expected behavior would be that if the user disables the feature and saves the step, all the feature-related fields get cleared, including Website and Pool name.

Source: https://secure.helpscout.net/mailbox/bb1d62383a582dd4/571746/ (private link)
Octopus: `3.4.15`

**Comment by matt-richardson** [comment]
On the add/remove features dialog, if the user de-selects a feature, show a warning message advising that all settings related to this feature will be removed.

See https://secure.helpscout.net/conversation/272028841/10861/?folderId=557082 (private link)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebSite and AppPool fields values are retained after IIS feature is disabled](https://trello.com/c/8AMfZCG6/36-website-and-apppool-fields-values-are-retained-after-iis-feature-is-disabled)

**Comment by zentron** [comment]
Release Note: Deployment features have their settings cleared when they are disabled
