### ISSUE TITLE
Full permissions required to C:\Octopus when starting Octopus 3.5.0

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2890]
When starting Octopus `3.5.0` permissions are required to `C:\Octopus`. This appears to be a change from before where we would write into the user's appdata folder until we had created the Octopus Home folder.

We should change this so it honours our configuration as described here: http://docs.octopusdeploy.com/display/OD/Permissions+required+for+the+Octopus+windows+service

Source: http://help.octopusdeploy.com/discussions/problems/48635

**Comment by thebigmoosey** [comment]
Release Note: Improved how we were accessing the HomeDirectory when starting Octopus
