### ISSUE TITLE
GoogleApps authentication not working with reverse proxy

### ISSUE THREAD

**Issue by kamlim1k** [OctopusDeploy/Issues#2902]
Have Octopus deploy setup on http://localhost:8080 behind nginx reverse proxy. 
When trying to login using google apps authentication get redirected to http://[machine_name]:8080/api/users/authenticate/GoogleApps... instead of actual domain name

**Comment by matt-richardson** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support.

Please include a copy of your nginx config when you email us - that will help us get to the bottom of it quicker.

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
