### ISSUE TITLE
Add patch releases to RSS

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2912]
Currently the ways to figure out we released a patch are:

- Checking the bullhorn icon on the top right. This one wont work if the Octopus server doesn't have internet access, which is not an uncommon thing.

- Following us in Twitter. Not very useful if social media is blocked at the company.

We already have [an RSS in place](https://octopus.com/feed?releasesonly=true), but it only shows `major` and `minor` releases. We need to extend this to `patches` which are really our 🍞 and :butter:

Related internal conversation: https://octopusdeploy.slack.com/archives/team-octopusdeploy/p1478873578002633

Source: http://help.octopusdeploy.com/discussions/questions/9685

**Comment by Dalmirog** [comment]
A quick blogpost retweeted by our account would help spreading the word about this enhancement.

**Comment by StephenShamakian** [comment]
Any update? I see v3.6 was released today.
