### ISSUE TITLE
Add ability to retrieve node name user is logged in to

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2915]
Currently (outside of packet trace) there is no way to determine which node you are logged in to for a HA setup. Adding something simple like /api/node that returns the node name would give admins the ability to ask users which node they are in to trace issues.

This has also been asked for in /api/ping so adding it here too would be beneficial.

Source: https://secure.helpscout.net/conversation/273056566/10932/?folderId=557083
See Shane or Vanessa for more info if required

**Comment by matt-richardson** [comment]
Have to be careful, as different requests may go to different servers.
In the past, I've done this by returning a response header which would be visible in the browser dev tools.

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ability to retrieve node name user is logged in to](https://trello.com/c/uI0ZfZKr/32-add-ability-to-retrieve-node-name-user-is-logged-in-to)

**Comment by droyad** [comment]
Release Note: Added a `Octopus-Node` HTTP header that shows which server served the request
