### ISSUE TITLE
2.6 > 3.5 upgrade = external feeds broken

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2918]
When upgrading from 2.6 to 3.5, any external feeds you have become broken with a serialisation error. The only way to fix it is to add the type property to the JSON via a SQL update statement.

Steps to reproduce:
- Install a 2.6 instance (I created a 2.6.4 instance)
- Create an external NuGet feed (I created a feed to NuGet API v2 @ https://www.nuget.org/api/v2/)
- Upgrade your 2.6 instance to 3.5
- When you login to 3.5, check your configuration > feeds screens and they break with the following error:

<img width="2458" alt="screen shot 2016-11-14 at 4 22 56 pm" src="https://cloud.githubusercontent.com/assets/819605/20256859/c07daae8-aa91-11e6-9c3a-0a6c9ee48439.png">

The only way I could find to fix this was to inject the type property into the JSON to match the build-in feed (as reported by the customer).

Source: https://secure.helpscout.net/conversation/276162154/11114/?folderId=801354

**Comment by thebigmoosey** [comment]
We have another report of this overnight: http://help.octopusdeploy.com/discussions/problems/48889

**Comment by zentron** [comment]
Fixed in: https://github.com/OctopusDeploy/OctopusDeploy/commit/839cc80d4241de5be61b2a639017a9e4991aa99a
Looks like the migrator was not auto-assigning the feed type to `FeedType.NuGet` and when loading from the database, threw an exception trying to deserialize into the `FeedResource` abstract type.

**Comment by thebigmoosey** [comment]
Release Note: Fixed issue where feeds were not falling back to the default NuGet type when imported using migrator
