### ISSUE TITLE
Allow finer control over config transforms

### ISSUE THREAD

**Issue by peter-dolkens** [OctopusDeploy/Issues#292]
When trying to keep projects compatible with multiple different processes / systems, sometimes it's necessary to keep some transforms around that you don't necessarily want run by convention on deploy.

It would be great if there was an option, when turning on config transforms, to disable the convention options, and only run an explicit transform (I believe the explicit transform is possible, but the convention part is not)

**Comment by andreas-runnhagen** [comment]
@PaulStovell It would be great if this would be added to the documentation at http://docs.octopusdeploy.com/display/OD/Configuration+files with some examples of expressions you can use. 

This page was the only reference i could find regarding this type of configuration.

It would also be great with some better Task logging when you resolve "Additional transforms". If a path is misspelled or something it is just silently skipped. A bit of Info/Verbose logging to give a hint that a path has been skipped would be great.
