### ISSUE TITLE
Add to Slack notification release notes

### ISSUE THREAD

**Issue by sergiorykov** [OctopusDeploy/Issues#2921]
Slack notification about deployment will become more informative with release notes. :)

**Comment by Dalmirog** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support.

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

-------

We also accept PRs for library step templates such as that one :). Perhaps you can attempt to add this enhancement yourself? It definitely sounds like a solid idea

https://github.com/OctopusDeploy/Library/blob/master/step-templates/slack-notify-deployment.json
