### ISSUE TITLE
Octo.exe List-LatestDeployments returns all deployments and not just the latest

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2922]
Octopus Server: `3.5.1`
Octopus Tools: `4.0.4`

![listlatestdeployments](https://cloud.githubusercontent.com/assets/6180562/20359445/a623d112-ac0e-11e6-8cf3-fd18cf641b35.jpg)

Also the deployments don't say to which Project they belong to, making it really confusing when you run this command for multiple projects. Channel info would be great too.

**Comment by tothegills** [comment]
See https://github.com/OctopusDeploy/OctopusClients/issues/101
