### ISSUE TITLE
Improve awareness and docs about usage of variables to define feeds

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2923]
We all have answered this one in support at least once. Its time to get ride of it (hopefully) for good :)

- [x] Improve documentation explaining the usage of a variable to define feeds and the need for a dummy unscoped feed. 9/10 times users attempt to use this with channels, so having the doc example around that feature would be great.

- [x] Whenever someone clicks on the "custom bindings" button for the *package feed* field, show them a link or something that leads to the above doc.

Source: http://help.octopusdeploy.com/search?q=variable+feed&recommend=1&t=d (yes its a search)

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve external feed binding docs and add a link to octopus](https://trello.com/c/0dScRhMq/495-improve-external-feed-binding-docs-and-add-a-link-to-octopus)

**Comment by danielfischeroctopus** [comment]
Documentation for this:
https://octopus.com/docs/deploying-applications/deploying-packages/dynamically-selecting-packages

**Comment by danielfischeroctopus** [comment]
New issue for second part of this issue: https://github.com/OctopusDeploy/Issues/issues/3479

**Comment by johnsimons** [comment]
Both actions seem to be done
