### ISSUE TITLE
Tentacle package cache cleanup for files not in deployment journal

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2932]
Currently we have a server side setting to delete from the `/files/` cache - but this is not applied on the Tentacle. The Tentacle relies on the deployment journal and retention policy to clean up the package cache. If the files are not found in the deployment journal (for whatever reason, 2.6 upgrade, previous bugs etc) we should clean them up when the retention policy runs.

One customer has retention set to keep 1 release, but has files in there since May (now November) and those files are not in the deployment journal. (seen on a call but also see source).

Source: http://help.octopusdeploy.com/discussions/problems/47551-retention-policy-inconcistency

**Comment by droyad** [comment]
Consider doing as part of #4223
