### ISSUE TITLE
UI responsiveness updates to packages on release page

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2936]
When the release screen is loaded with many packages, it can take some time for all the packages to load and respond with the notes from the server. This is typically because the server itself will need to call out to the remote repository to retrieve the notes. The problem is that although these notes aren't necessarily crucial to the screen (the notes section otherwise just says loading) by taking up TCP connection to the web server before the _important_ requests are made (like progression etc), the browser has to wait until the all the feed information comes back before fully loading.
There are a few fixes we can put in here to make it more responsive.

- [x] Currently the feed for each package is loaded before loading the package details, this is unnecessary if multiple packages use the same feed. We should ideally pre-process the package list and only perform 1 request per different feed before loading the relevant packages.
- [x]  Look at delaying the loading of feed information until _after_ the more important requests are made.

Reference https://secure.helpscout.net/conversation/278255942/11206

**Comment by michaelnoonan** [comment]
Release Note: Improved responsiveness of the packages on the Releases page
