### ISSUE TITLE
Extend Tentacle retention policy logs

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2937]
Currently during server retention we get a lot of verbose logging around what is going on with retention policies. On the Tentacle it would be nice to see what retention policy is being applied (how many to keep, how many days etc) and maybe why packages were skipped and not deleted.
This is all during a deployment - but we have a few things that we arent able to trace from a support perspective.

**Comment by droyad** [comment]
Currently we are logging which packages and directories are being removed.

I am adding which packages and directories are being kept. The retention policy is in the title of the section.

The directories are not  scanned for files and a choice made to keep or delete them. Rather the log of previous releases is scanned for releases that should be retained. Then the packages and directories are deleted based on the remaining log items, except if they are part of a retained release.

**Comment by droyad** [comment]
##New output

Policy set to **Keep 3 releases**
```
15:30:08   Info     |         Keeping this deployment and the previous 3 successful deployments
15:30:08   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.1.0 and C:\Octopus\Files\File.1.1.0.zip-2dd3c637-711d-4b7a-9e39-20f99e792b50 as it is the most recent successful release
15:30:08   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.0.0 and C:\Octopus\Files\File.1.0.0.zip-a5c2c172-93b6-44b3-80d0-eb465560383b as it is the 2nd most recent successful release
15:30:08   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.0.0_4 and C:\Octopus\Files\File.1.0.0.zip-a5c2c172-93b6-44b3-80d0-eb465560383b as it is the 3rd most recent successful release
15:30:08   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.0.0_3 and C:\Octopus\Files\File.1.0.0.zip-a5c2c172-93b6-44b3-80d0-eb465560383b as it is the 4th most recent successful release
15:30:08   Info     |         Removing directory 'C:\Octopus\Applications\Local\File\1.0.0_2'
```

Policy set to **Keep for 3 day**
```
15:42:09   Info     |         Keeping deployments from the last 3 days
15:42:09   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.1.0 and C:\Octopus\Files\File.1.1.0.zip-f016d26f-fd95-447f-965a-3f2b25c0240b as it was installed 1 days and 0 hours ago
15:42:09   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.2.0 and C:\Octopus\Files\File.1.2.0.zip-c5c4d1d4-349f-4beb-8b53-59b2c358a4bc as it was installed 0 days and 0 hours ago
15:42:09   Info     |         Removing directory 'C:\Octopus\Applications\Local\File\1.0.0'
15:42:09   Info     |         Removing package file 'C:\Octopus\Files\File.1.0.0.zip-6a4cbf12-5eac-42f6-aa95-c16b902f4026'
```

**Comment by vanessalove** [comment]
This is great! Just to confirm, if you add a second step that uses the same package as step 1, will it duplicate messages? 

ie:
15:30:08   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.0.0_4 and C:\Octopus\Files\File.1.0.0.zip-a5c2c172-93b6-44b3-80d0-eb465560383b as it is the 3rd most recent successful release
15:30:08   Verbose  |         Keeping C:\Octopus\Applications\Local\File\1.0.0_3 and C:\Octopus\Files\File.1.0.0.zip-a5c2c172-93b6-44b3-80d0-eb465560383b as it is the 3rd most recent successful release

**Comment by droyad** [comment]
The retention is run for each step. So if you have steps `Foo` and `Bar`, you get two sections each going through their respective deployments:

```
Applying retention policy using 3 Items to set Environments-1/Projects-1/Step-Foo/Machines-1/<default>
Applying retention policy using 3 Items to set Environments-1/Projects-1/Step-Bar/Machines-1/<default>
```

**Comment by droyad** [comment]
If you have two deployments, (one step) either with the same release version or different, you will get two messages with the same package path, but different install paths as per your example.

**Comment by vanessalove** [comment]
Ah of course. Perfect. This will make the logs so much easier to read for this.

**Comment by droyad** [comment]
Release Note: The releases that are kept are now output to the log during tentacle retention
