### ISSUE TITLE
Better handling of /Users/SignIn endpoint and Basic Authentication with multiple auth providers

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2948]
We applied a short-term fix for a bug this caused: https://github.com/OctopusDeploy/Issues/issues/2974

[Private discussion](https://octopusdeploy.slack.com/archives/team-fire-and-motion/p1479945436000251)

We need to provide better backwards compatibility for the `/users/signin` permalink-style route for handling basic authentication.

Proposed solution to keep this endpoint always available if basic/AD auth is enabled:

1. We will re-enable the `/api/users/signin` route which will be used by all auth providers which support “Basic Authentication” (username/password credentials)
2. The handler of that route will try the enabled auth providers in a precedence order (u/p then AD)
3. Remove the smarts that were added to client(s) for Basic Authentication - just use the well-know route from hypermedia

This will get us to a point of 100% backwards and forwards compatibility, but with the slight behavioural change that you can have both U/P and AD providers enabled.

### Test cases
- [ ] Can register polling Tentacle using older Tentacle Manager
- [ ] Can use older Octopus.Client SDK to sign in using U/P
- [ ] :allthethings: still work :crazy:

**Comment by droyad** [comment]
It looks like the endpoint is also not available if Forms Auth is disabled for the AD Provider

**Comment by droyad** [comment]
A work around for registering a tentacle is to use an API key from the command line.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better handling of /Users/SignIn endpoint and Basic Authentication with multiple auth providers](https://trello.com/c/UD4c8jHA/21-better-handling-of-users-signin-endpoint-and-basic-authentication-with-multiple-auth-providers)

**Comment by slewis74** [comment]
Release Note: single login API endpoint has been re-instated, for backward compatibility with registering Polling Tentacles
