### ISSUE TITLE
Variable edit permissions overhaul

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2951]
Currently if you have all the `Variableset*` permissions you cannot edit the variables without `VariableEdit` also. If you have `VariableEdit` scoped to any project you cannot edit the `Variableset` variables at all.

A few of us believe it should be apart from the `Variable*` permissions and if you have `Variableset*` permissions this is enough. It doesn't make a heap of sense that you need both `LibaryVariablesetEdit` and `VariableEdit` to edit `LibraryVariableset` variables. 

Also the case of needing `VariableEdit` for `LibraryVariablesets` means you suddenly open up `Project` variables when you might not have wanted to.

Initial discussions have been around renaming the `Variable*` permissions to `ProjectVariable*` so that permissions can be assigned on a more granular level.

This is the second part of https://github.com/OctopusDeploy/Issues/issues/2804

**Comment by thebigmoosey** [comment]
This has been closed as part of #2804
