### ISSUE TITLE
Make the upgrade process of deployment actions more transparent

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2953]
When there is a new version of a template we don't show existing properties because the old version of the template is not available anymore.  

![image](https://cloud.githubusercontent.com/assets/347637/20617085/7e7da95a-b332-11e6-81fb-3e590f09348a.png)

This means that there is no way for users to know whether the upgrade actually worked. They can't compare before and after values.

This has been mentioned a few times:
http://help.octopusdeploy.com/discussions/problems/47388-step-template-update-clears-all-input-data
http://help.octopusdeploy.com/discussions/problems/48857-step-template-update-doesnt-copy-data-over
http://help.octopusdeploy.com/discussions/problems/49244

Idea:

Preserve all versions of a given template that are in use. When a customer performs an upgrade show them both versions side by side so they can verify that everything is ok.

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make the upgrade process of deployment actions more transparent](https://trello.com/c/8cQYZ7Ym/35-make-the-upgrade-process-of-deployment-actions-more-transparent)

**Comment by pawelpabich** [comment]
Release Note: Step properties are displayed now when the step is not using the latest version of a step template
