### ISSUE TITLE
Property value gets reset to parameter default value when it's set to no value 

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2954]
Property with no value (e.g. empty) gets reset to parameter default value when its action is upgraded to a new version of the underlying template. 

It looks like we do send the empty data to the server, e.g `{EmptyProperty: ""}` but then we don't persist it.  When we need to upgrade an action we don't have the old version of the template so the merge process analyses the actual data and provides default value because `EmptyProperty` is not present.

It looks like to make this process reliable we would need to start comparing the templates as suggested here: #2953.

We could also start persisting empty properties but that would be a breaking change and not sure what would it break.

Started by: http://help.octopusdeploy.com/discussions/problems/49244-updating-custom-step-templates

**Comment by davidroberts63** [comment]
Interesting, I wonder if that problem occurs in Bluefin. I'll give that a look tomorrow.

**Comment by jmounce** [comment]
To get a version of this out faster, forget about making it 'smart' to auto-update and 'compatible' to guarantee things won't break, and make it a manual "OK" button for us to force the update out to all dependent processes, please.
The risk would be ours, the process designer. If things break after we manually push it, our fault. 
Most of the time, we are making a small, compatible, self-contained change. (like handling a fault better) and the inputs don't change.
You are holding up our productivity by guaranteeing this to be intelligent and safe.
I really don't care about that. Sometimes the User IS the intelligence and safety is well-know.

Make it an option to manually push it out with a BIG warning.

**Comment by pawelpabich** [comment]
Release Note: Empty property value doesn't get reset to default parameter value when a step template change is applied to an existing step
