### ISSUE TITLE
Duplicate error messages for the 'Step name' field

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#2966]
When configuring a step and either putting in a duplicate step name or leaving the step name field empty, causes duplicate errors appear. 

Both error messages could just refer to 'Step name' and remove the 'Action name' and 'Name' messages.

<img width="1084" alt="error message - name in use" src="https://cloud.githubusercontent.com/assets/17240784/20738601/1218be68-b700-11e6-932d-5bc173245758.png">
<img width="809" alt="error message - step name empty" src="https://cloud.githubusercontent.com/assets/17240784/20738608/21617ec8-b700-11e6-9ec9-7c1947f5e32f.png">

**Comment by droyad** [comment]
At the moment the validation for steps and actions is different. We would need to combine the validation of these.

**Comment by NickJosevski** [comment]
Low impact, may be confusing, but not going to fix.
