### ISSUE TITLE
Tasks sometimes get stuck in the "Cancelling" state

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2971]
When a task is canceled it sometimes get stuck in the "Cancelling" state and never becomes "Canceled".

See logs here: http://help.octopusdeploy.com/discussions/problems/48031

**Comment by droyad** [comment]
We have worked on cancellation in other issues, and no reports of this issue this month. Closing for now.

**Comment by nshenoy** [comment]
I'm seeing this issue repeatedly on my Octopus Server. We have 111 tentacles. It hangs at 99% complete and cancellations seem to get stuck and not actually cancel. My server is running version 3.13.9. Where can I send my task log file for analysis?

**Comment by matt-richardson** [comment]
@nshenoy, can you please get in touch via one of our [support channels](https://octopus.com/support)? That way we'll be able to look into it for you.
