### ISSUE TITLE
Tenant tag sets page doesn't display images when Octopus is hosted in a virtual directory

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2973]
The path doesn't include the virtual directory.  

Idea: move the image path to a less file.  This worked in all other cases. It did not work in this one because the image has some bootstrap responsive styles applied to it.

![image](https://cloud.githubusercontent.com/assets/347637/20824829/5f1accae-b8ab-11e6-83e7-517031fa068a.png)

**Comment by MJRichardson** [comment]
We should verify this is fixed in 4.0

**Comment by zentron** [comment]
Onboarding looks fine now
![image](https://user-images.githubusercontent.com/1830666/32637654-d44e8baa-c606-11e7-924b-0d2ff510599e.png)

**Comment by michaelnoonan** [comment]
Release Note: We fixed a problem where the introduction to Tenant Tag Sets wasn't displayed properly when hosting the Octopus Server in a virtual directory
