### ISSUE TITLE
Release number consistency on the main & project dashboards

### ISSUE THREAD

**Issue by nael-fattah** [OctopusDeploy/Issues#2978]
Release numbers on our dashboards were not consistently showing. Some long release numbers were wrapping and some were being cut off with ellipses. 

Jess found the problem in the CSS and will make it consistently use ellipses with the full release number in the title.

Source: http://help.octopusdeploy.com/discussions/problems/49581

**Comment by jess-ross** [comment]
Release note: Fixed ellipsis css and added tool tip for viewing longer names
