### ISSUE TITLE
Tenant tag spacing issue

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#2981]
Tenant tags have larger spacing since 3.7 release.

<img width="370" alt="screen shot 2016-12-07 at 10 06 08 am" src="https://cloud.githubusercontent.com/assets/17240784/20949411/d8d7d516-bc64-11e6-9d34-ff37aecb1da5.png">

Source: http://help.octopusdeploy.com/discussions/problems/49626-tenant-tag-spacing-tenants-page-v371

**Comment by pawelpabich** [comment]
Release Note: Tenant tags are now spaced correctly on the Tenants page
