### ISSUE TITLE
Improve updating step templates (actions) in project deployment processes

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2985]
Building upon #2698, we're working to improve the process to update step templates (actions) within a project's deployment process.  The key change to enable this is to capture the history of step templates as they're changed so we can safely compare two version and update them.  i.e. If we can systematically determine if a parameter has been added, deleted or changed between version, we can provide a great update experience.  

- [x] Add ability to safely update a single step (action) within a project
- [x] Add ability to safely update all projects steps (actions) to the latest version of a step template
- [x] Allow for manual update when automatic update is not possible
- [x] Docs
- [ ] Update https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6072178-when-updating-a-step-template-update-across-all

* Note 1: This work was started as a part of Octopus `3.7` but we found a few edge cases that could potentially break existing deployments so it wasn't included.
* Note 2: I mention steps and actions.  Each deployment process consists of a series of steps, where each step can have one or more actions.  Generally, this mapping is one to one unless you have a rolling deployment with child steps.  See [Step and Actions](http://docs.octopus.com/display/OD/Deployment+Processes#DeploymentProcesses-Stepsandactions) for more information. 

Problems reported by users:
https://github.com/OctopusDeploy/Issues/issues/2954
http://help.octopusdeploy.com/discussions/questions/10716
https://secure.helpscout.net/conversation/292575838/11843/?folderId=557077
https://github.com/OctopusDeploy/Issues/issues/2953
http://help.octopusdeploy.com/discussions/problems/47388-step-template-update-clears-all-input-data
http://help.octopusdeploy.com/discussions/problems/49244

**Comment by pawelpabich** [comment]
Another, possibly related problem https://secure.helpscout.net/conversation/292575838/11843/?folderId=557077

**Comment by jess-ross** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve updating step templates (actions) in project deployment processes](https://trello.com/c/T5OgU16J/40-improve-updating-step-templates-actions-in-project-deployment-processes)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update step templates across all projects (561 votes)](https://trello.com/c/1PApWHUZ/14-update-step-templates-across-all-projects-561-votes)

**Comment by jmounce** [comment]
To get a version of this out faster, forget about making it 'smart' to auto-update and 'compatible' to guarantee things won't break, and make it a manual "OK" button for us to force the update out to all dependent processes, please.
The risk would be ours, the process designer. If things break after we manually push it, our fault. 
Most of the time, we are making a small, compatible, self-contained change. (like handling a fault better) and the inputs don't change.
You are holding up our productivity by guaranteeing this to be intelligent and safe.
I really don't care about that. Sometimes the User IS the intelligence and safety is well-known.

Make it an option to manually push it out with a BIG warning.

**Comment by pawelpabich** [comment]
Quick update re how the feature is progressing:

**Usage screen**

![image](https://cloud.githubusercontent.com/assets/347637/23982545/d9d846c4-0a59-11e7-94d1-1ab144051fe6.png)

**Merge conflict detected**

![image](https://cloud.githubusercontent.com/assets/347637/23982572/ecf203c6-0a59-11e7-88de-908be59c373d.png)

**Manual merge**

![image](https://cloud.githubusercontent.com/assets/347637/23982576/fb377c0e-0a59-11e7-883d-a75e5104a1aa.png)

**Comment by eakoning** [comment]
Looking good! ;-)

**Comment by pawelpabich** [comment]
Release Note: Step template update can be applied to all steps in all projects
