### ISSUE TITLE
Package ID with polish character breaks built-in repository

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2994]
Pushing a package with the Polish character `ł` on the ID breaks the repository with the following error message:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: character
```

The only workaround to get it back to a functional state is to manually remove the package from the Octopus Server, ~and then delete the DB entry on the `NugetPackage` table.~ (you do not need to touch the database. After you delete the package from the Octopus Server and then restart the Octopus service, It'll re-index the packages and that entry will go away on its own. Thanks @vanessalove for pointing that out!)

Worth discussing which characters should we support on the ID to avoid having a log a bug on a case to case basis.

Octopus Version: `3.7.3`
Source: https://secure.helpscout.net/conversation/288796655/11660/?folderId=557077

**Comment by vanessalove** [comment]
Delete from the filesystem and restart the service to make it re-index from the directory is a much SAFER workaround

**Comment by latusekpiotr** [comment]
We were actually working under time pressure and did not know restarting the service will trigger the re-index. We tried removing the package from the file system but when it did not help, we just went ahead and updated the entry in the DB (did not delete it though).

In our case, the error was originating from an API and the logs showed these two URLs were being accessed when the error appeared:
`http://MyOctopusServer/api/packages/raw?replace=True`
`http://MyOctopusServer/api/packages?latest=true`

I also tested Octopus will throw an error when accessing either of these URLs:
`http://MyOctopusServer/api/packages?nuGetPackageId=Paweł`
`http://MyOctopusServer/api/packages?nuGetPackageId=Pawe%C5%82`  (%C5%82 is the code for "ł")

**Comment by vanessalove** [comment]
@latusekpiotr I completely understand the time pressure and not knowing. This was more for future reference or anyone coming into this thread (and a reminder to @Dalmirog who was assisting you). From our point of view editing directly in the database and making changes can void support so we should never recommend it nor suggest it. It should be emergencies only and when there is no other option at all. In this case on service start we index the package directory for changes made directly on the file system.

**Comment by latusekpiotr** [comment]
@vanessalove Understood!

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Package ID with polish character breaks built-in repository #2994](https://trello.com/c/FwEiarrC/20-package-id-with-polish-character-breaks-built-in-repository-2994)
