### ISSUE TITLE
Project group security is missing the ability to clone projects

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#2995]
If your team is scoped to a project group, you no longer have the ability to clone projects.

Eg. This user is assigned to "rage" project group. No Clone button is available in the right menu.
<img width="1624" alt="screen shot 2016-12-09 at 10 12 03 am" src="https://cloud.githubusercontent.com/assets/819605/21032926/b27c52e4-bdf8-11e6-9fcc-2ee4432c52ae.png">

If I go to my project group and create a new project, I don't see any other menu except the overview either:
<img width="1448" alt="screen shot 2016-12-09 at 10 59 32 am" src="https://cloud.githubusercontent.com/assets/819605/21033751/99fc7586-bdfe-11e6-8cdf-70b04a52ced5.png">

It seems ok if I logout and log back in, but that's not an ideal.

As part of this review, we should check anywhere else where this new Project Group scoping may have broken the UI.

**Comment by Dalmirog** [comment]
Related report from another user: http://help.octopusdeploy.com/discussions/problems/16555

**Comment by tothegills** [comment]
Release note: Allow teams with project group permissions to clone projects in those project groups
