### ISSUE TITLE
Improve performance of release page when project has large number of steps with package variables

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2998]
Performance of the `/api/deploymentprocesses/{id}/template` endpoint degrades where there are many package steps in project.

For example, the customer below has 100+ package steps, and that endpoint is taking >30 seconds to respond.

My initial investigation indicates the prime culprit may be variable-evaluation inside a loop.  

As reported in: https://secure.helpscout.net/conversation/287373184/11580/?folderId=571733

**Comment by markryd** [comment]
Release Note: Improved the performance of the release page when the project has a large number of package steps

**Comment by markryd** [comment]
Had to revert previous fix.

**Comment by tothegills** [comment]
Also reported here: http://help.octopusdeploy.com/discussions/problems/54302-slow-load-times-on-release-page

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve performance of release page when project has large number of package steps](https://trello.com/c/l8qgw7du/739-improve-performance-of-release-page-when-project-has-large-number-of-package-steps)

**Comment by jess-ross** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve performance of release page when project has large number of package steps](https://trello.com/c/VCR036a1/17-improve-performance-of-release-page-when-project-has-large-number-of-package-steps)

**Comment by droyad** [comment]
Reproduced with a project with no variables and 100 steps that had a variable package name:
```
var project = repository.Projects.FindByName("Test");
var process = repository.DeploymentProcesses.Get(project.DeploymentProcessId);

process.ClearSteps();
for(int x = 0; x < 100; x++)
{
	var step = process.AddOrUpdateStep("Step" + x);
	step.TargetingRoles("Tentacle");
	var action = step.AddOrUpdatePackageAction("Step" + x, new PackageResource
	{
		FeedId = "Feeds-42",
		PackageId = "#{Var" + x + "}"
		
	});
}

repository.DeploymentProcesses.Modify(process);
```

Takes 10 seconds (30ish under profiling). 

Profiler shows this: 
![image](https://user-images.githubusercontent.com/1687639/57276190-2826da00-70e4-11e9-8700-914658c0e5a7.png)

Without looking into it, it's not clear why it needs to call `TryParseIdentifierPath` 132,500 times.

Trace is attached (dotTrace)
[Trace.zip](https://github.com/OctopusDeploy/Issues/files/3151063/Trace.zip)

**Comment by mudra-octopus** [comment]
The customer here has 120 packages, slow in multiple areas (create a release and following page). There are some logs and a gif uploaded here: https://secure.helpscout.net/conversation/1075916169/56890/

**Comment by mudra-octopus** [comment]
Another instance: https://help.octopus.com/t/release-page-slow/24676

**Comment by MarkSiedle** [comment]
Another instance, with some useful stats to help us isolate the issue in this customer's particular case: https://secure.helpscout.net/conversation/1092158332/57731/

**Comment by KennethBates** [comment]
Another report: https://help.octopus.com/t/25-second-response-to-select-a-release/25658 (private link)

**Comment by KennethBates** [comment]
Another report: https://help.octopus.com/t/release-page-slow/24676

**Comment by capqwerty** [comment]
Is there any light at the end of the tunnel or are we on our own?

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.0 |
| 2020.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.0 |
| 2020.2+ | _all releases_ |
| 2021.3 | 2021.3.7782 |

**Comment by andrew-at-octopus** [comment]
The changes we hope will address the poor performance for many variables in processes with many steps have been added to 2021.3.7782 (not the earlier versions - sorry).   Please let us know if this is still an issue for you, as there may still be more situations to accommodate.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.0 |
| 2020.2+ | _all releases_ |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.0 |
| 2020.2+ | _all releases_ |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.0 |
| 2020.2+ | _all releases_ |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
