### ISSUE TITLE
Include feature highlights in upgrade notification

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#30]
_Issue by **[nblumhardt](https://github.com/nblumhardt)** from Wednesday Oct 09, 2013 at 00:55 GMT_
_Originally opened as https://github.com/OctopusDeploy/OctopusDeploy/issues/52_

---

https://gist.github.com/PaulStovell/6894349

The portal UI will have a "news"-style footer area that, on the latest version, will grab articles from the Octopus feed (blog?)

When an upgrade is available, the footer will contain information about the features in the upgrade, specific to the area(s) of the app being used.

I.e. viewing the Projects page, in the footer of an outdated version you might see:

"New in Octopus 2.0 - project pulse!"

Hyperlinked to docs or a blog post. You can imagine on the footer of the Variables page you might see:

"New in Octopus 2.0 - multi-select variable editing!"
"... - secure variables!"
"... - integrated XML config transformations!"

**Comment by jess-ross** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tenant counter not visible](https://trello.com/c/Fd3ReEra/37-tenant-counter-not-visible)
