### ISSUE TITLE
Previous Step Name dropdown in step templates doesn't show values

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3009]
Was able to reproduce this in a brand new template created in `3.7.5`.

![previousstepnamebug](https://cloud.githubusercontent.com/assets/6180562/21151822/b0cabf56-c142-11e6-9d14-5ac3bca40573.gif)

Template used in GIF: [previousstepnametemplate.txt](https://github.com/OctopusDeploy/Issues/files/649660/previousstepnametemplate.txt)

Octopus: `3.7.5`
Source (2 users): http://help.octopusdeploy.com/discussions/problems/49770-problem-with-the-step-template-parameter-type-a-previous-deployment-step-name

**Comment by Dalmirog** [comment]
More reports:
- http://help.octopusdeploy.com/discussions/questions/10131-how-to-set-dacpac-package-step-name-parameter-for-sql-deploy-dacpac-step

**Comment by pawelpabich** [comment]
Release Note: Previous step name dropdown shows values

**Comment by konste** [comment]
Спасибо! :-)
