### ISSUE TITLE
Last line in script editor is cut off

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3010]
Depending on the browser window size the last line can be hidden 50%-20%.

![lastline](https://cloud.githubusercontent.com/assets/6180562/21155554/50a2135e-c151-11e6-9351-32656758aec2.jpg)

Tested in Chrome for windows.
Octopus: `3.7.5`
Source: http://help.octopusdeploy.com/discussions/problems/49840

**Comment by pawelpabich** [comment]
Fix in v4

**Comment by droyad** [comment]
Release Note: The script editor now always scrolls to the bottom
