### ISSUE TITLE
Disabled steps are not reflected in the deployment preview

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3020]
From https://github.com/OctopusDeploy/OctopusDeploy/pull/638#issuecomment-266600726

I've disabled a step:

![image](https://cloud.githubusercontent.com/assets/1627582/21122948/3ae98680-c121-11e6-9028-6974018ae18b.png)

But it doesn't appear anywhere in the deployment preview, but I wonder if it should?

![image](https://cloud.githubusercontent.com/assets/1627582/21122942/2f8b28c0-c121-11e6-91f2-49280d517684.png)

If I'm surprised a step is missing, I'd need to go back to the process and realise it's disabled.

I'm not sure it's worth changing as part of this PR because of the bugs I can see this change would introduce, but it does feel like the UX could be improved.

**Comment by NickJosevski** [comment]
Disabled steps are will now be reflected in the deployment preview.
