### ISSUE TITLE
Improve test scenarios for health check step

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3021]
It's not clear what the consequences of specifying "included" or "excluded" machines has on health check steps.

It's not clear what machines will result when running multiple health check steps across different roles. eg Health check web-server followed by health check app-server.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve test scenarios for health check step](https://trello.com/c/aTfJgNWb/17-improve-test-scenarios-for-health-check-step)
