### ISSUE TITLE
Cannot run configure with commands that require the DB before the MasterKey is established and the database is initialised

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3023]
Trying to enable something like Azure AD is failing even though Octopus is working, the MasterKey is established, and the Database is working great!

It turns out the problem is that the code tries to access the `master` database to see if the Octopus database exists yet. In certain circumstances the user account in the Connection String doesn't have access to the `master` database, and the query fails silently causing this false-positive.

Source: https://secure.helpscout.net/conversation/293179373/11880/?folderId=571731
Source: https://secure.helpscout.net/conversation/292859608/11860/?folderId=571731

**Comment by slewis74** [comment]
Release Note: Octopus Server's configure command no longer needs access to the master database to determine if the Octopus Database has been initialized
