### ISSUE TITLE
Octo.exe list-latestdeployments behavior is inconsistent when using --project or --environment

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3024]
Lets say you have 2 deployments for `ProjectA` and 2 for `ProjectB`. 

If you run `List-latestDeployments` without the `--project` parameter, you'll get both deployments from each project. If you specify a project with that param though, you'll only get 1 deployment for that project. I would expect to get the same result as without the parameter, just filtered by that single project.

Octo.exe: `4.4.0`
Source: http://help.octopusdeploy.com/discussions/problems/48959#comment_41500629

**Comment by Dalmirog** [comment]
@zentron suggested we return a default number of deployments (say 5) and provide a switch to specify how many you want (eg --top 1). I'm fine with that approach.

**Comment by NickJosevski** [comment]
To avoid breaking more people who now have taken a dependency on the new behavior which makes use of dashboard API calls to mirror the dashboard behavior.

A more ideal outcome will be a new action `list-release` which will take `--project="P" --environment="E" --number="N"`

**Comment by NickJosevski** [comment]
Release Note: Octo.exe now has list-deployments which also can take a tenant to filter on
