### ISSUE TITLE
Tentacles using an old thumbprint can connect until the server is restarted

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3032]
1. Configure a polling tentacle
2. Run a health check
 => it will succeed
3. Change the certificate thumbprint on the machine edit screen to something random (but leave the Tentacle with the existing thumbprint
4. Run a healthcheck again
 => It succeeds, but it should fail, as the certificate thumbprint doesn’t match...

**Comment by matt-richardson** [comment]
Notes:
* Removal needs to be threadsafe
* Removal needs to disconnect any live threads

**Comment by droyad** [comment]
We don't see this as a problem. Authentication is done when the connection is established.

**Comment by droyad** [comment]
1. Configure a polling tentacle
2. Run a health check
3. Edit the thumbprint in the Web UI
4. Restart the tentacle
5. Expect it to not allow reconnection, however it does.

Existing connections should not be dropped though
