### ISSUE TITLE
Investigate long package transfers to polling Tentacles

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3034]
We have a few cases where transfering large packages to polling Tentacles reaches our internal timeouts. You can work around this by modifying the timeouts to large values (1+ hour).

Delta compression also seems to have an effect or be effected by this.

At the very minimum timeouts need to be increased, but best option would be to know its a package transfer and not enforce any timeouts or somehow keep the connection alive.

Source: https://secure.helpscout.net/conversation/291734884/11796/?folderId=557083

Possibly may need to split this into to cases/fixes as delta compression may be a secondary issue as the customer had to leave it disabled.

**Comment by vanessalove** [comment]
Workaround (Set to 2 hours, pick a time that will be sufficient for the file transfer to occur)

1. Stop the Octopus Server service
2. Find the Octopus.Server.exe.config (where your program files are stored not the instance files)
3. add the following to the appSettings:
Add:
```
<add key="Halibut.PollingRequestMaximumMessageProcessingTimeout" value="02:00:00"/>
<add key="Halibut.PollingRequestQueueTimeout" value="02:00:00"/>
```
4. start the Octopus Server service

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate long package transfers to polling Tentacles #3034](https://trello.com/c/RBqZkMn3/10-investigate-long-package-transfers-to-polling-tentacles-3034)

**Comment by droyad** [comment]
Note that the `PollingRequestMaximumMessageProcessingTimeout` value is the time the server waits for a polling tentacle to connect and pick up a message. Therefore healthchecks and deployments would wait that long before failing due to a machine not being available.

**Comment by droyad** [comment]
Related to #2521

**Comment by droyad** [comment]
In Halibut we could detect that a connection for that mailbox is currently in the transferring state and not trigger the timeout.

**Comment by droyad** [comment]
As an alternative, we could get the tentacle to open extra connections when a long transfer occurs.

**Comment by Moozhe** [comment]
Actually, `PollingRequestQueueTimeout` is what defines how long Octopus waits for the polling tentacle to check in on a health check before timing out.  This is also what causes the Acquire Packages step to time out.

In my case I've run into this issue while transferring a 20MB package from one Azure VM running Octopus Server, to another Azure VM running my tentacle, in the same Azure datacenter.  Typically the "transferring packages" step for a specific tentacle only takes about 7 seconds.  But sometimes it times out after 2 minutes.

Is there not a way to fix this by having the polling tentacle check in periodically on a separate thread while downloading?  I've noticed that the tentacle doesn't throw any errors locally, and it does successfully download the file to the packages folder.  As long as it keeps checking in periodically while it performs its downloading/processing it should keep waiting.

**Comment by tothegills** [comment]
See https://secure.helpscout.net/conversation/678531728

**Comment by droyad** [comment]
#5204 Allows the configuration of Polling timeouts via the Machine Policy

**Comment by zentron** [comment]
No further action on this item unless customer requests arise with specific situations to reassess
