### ISSUE TITLE
Script step run as Source Code always sets "Wait for packages to be downloaded" to false

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3037]
When you have a script step that is set to run from source code and you check the `Wait for packages to be downloaded before running` check box it saves correctly but when you go back into the step the check box is unchecked again (but the value in the database is `true`) so if you make any other the value in the database will be reset to `false`.

![scriptsteprequirespackagestobeacquireduibug](https://cloud.githubusercontent.com/assets/1035315/21511486/552769a4-cced-11e6-8bac-ac4cd6025596.gif)

[This](https://github.com/OctopusDeploy/OctopusDeploy/blob/master/portal/app/areas/projects/actions/Octopus.Script.js#L49) is the code that is causing the conflict in the UI.

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Script step run as Source Code always sets "Wait for packages to be downloaded" to false](https://trello.com/c/fXUB0uHH/38-script-step-run-as-source-code-always-sets-wait-for-packages-to-be-downloaded-to-false)
