### ISSUE TITLE
Everyone team not allowing changes due to member change restriction

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3047]
Currently the Everyone team is not allowing changes to roles, scoping or really anything and is displaying the following message: 
![everyone-team-error](https://cloud.githubusercontent.com/assets/7697660/21631239/b7261be0-d284-11e6-943c-23dc6102063b.png)

While we do not allow changes to the users in that team, you should be able to edit what that user can see and do as per our documentation:
` The Everyone team always contains all users, but you can assign different roles to members of this Team (for example, you might allow everyone to view all projects and environments, but not edit anything). Out of the box, Everyone members can do nothing. `

Source: https://secure.helpscout.net/conversation/296358952/12043/?folderId=557083

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Everyone team not allowing changes due to member change restriction](https://trello.com/c/oMFsizwQ/26-everyone-team-not-allowing-changes-due-to-member-change-restriction)

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Everyone team not allowing changes due to member change restriction](https://trello.com/c/WyxuUk1H/30-everyone-team-not-allowing-changes-due-to-member-change-restriction)

**Comment by MJRichardson** [comment]
This seems to work as expected in Octopus 3.11.x.

Closing.

**Comment by vanessalove** [comment]
Another report - Also replicatable (totally a word) on demo.

Source: https://secure.helpscout.net/conversation/347966997/14756/?folderId=557083

**Comment by matt-richardson** [comment]
Release Note: Fix issue with modifying the everyone team when user had been deleted
