### ISSUE TITLE
Selecting Release on multi-tenant dashboard not updating page

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3048]
As reported in http://help.octopusdeploy.com/discussions/problems/50365

Henrik replicated this in the demo environment, but was unable to replicate it locally.  
Rob Erez mentioned a previous issue with release information not refreshing when selected, that was also unable to repro'd locally.  Perhaps a timing issue on visible when the server is not running locally??

**Comment by MJRichardson** [comment]
Also raised by http://help.octopusdeploy.com/discussions/problems/50440

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selecting Release on multi-tenant dashboard not updating page](https://trello.com/c/w6wV5H0M/42-selecting-release-on-multi-tenant-dashboard-not-updating-page)

**Comment by michaelnoonan** [comment]
Another report: http://help.octopusdeploy.com/discussions/problems/51000-multi-tenant-deployment-small-issue

**Comment by MJRichardson** [comment]
Release note:Selecting release on multi-tenant project dashboard will now update the dashboard
