### ISSUE TITLE
Counts for diagnostic and performance issues

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3050]
To diagnose and replicate performance issues, it would be helpful to have counts on the diagnostics page or via the diagnostics page that would provide numbers of things in Octopus so we can build instances that match these numbers and to replicate performance problems.

If we could have a page off diagnostics that lists counts for things such as: projects, variables, packages, variable sets, environments, machines, Lifecycles, tenants, roles, deployment processes/steps, step templates, external feeds.

if the page will take a while to grab data it should have a warning and it should also be exportable as a file or JSON for when we require it.

While in this area and performing this task, it would be good if we could also show the used license counts for the license limits on < enterprise licenses (this was @MJRichardson scope creep)

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Counts for diagnostic and performance issues](https://trello.com/c/ggkdZ0xM/29-counts-for-diagnostic-and-performance-issues)

**Comment by droyad** [comment]
We should add this to the System Report

**Comment by droyad** [comment]
This doesn't seem as useful anymore after recent changes
