### ISSUE TITLE
User with EventView for project cannot see deployment process change audit records

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3055]
As reported here: http://help.octopusdeploy.com/discussions/problems/50376

In the `ListEventsResponder` we do this:

```
var rule = new ScopedPermissionRequiredRule(typeof(Event), Permission.EventView);
...
rule.Customize(query) ...
```

This modifies the query to append SQL Where clauses which restrict Events to those with appropriate values for `ProjectId` and `EnvironmentId`.  The `DeploymentProcessModified` event does _have_ values for `EnvironmentId`, and so is being excluded.

This is tricky, as there are some cases where absence of a value for a scope means permission should be denied.  In this case, it seems it should be granted.

Two possible options:
- Permissions declare how null values should be handled (i.e. granted or denied)
- Perhaps Event View is the only exception to the rule, and should have it's own Rule class, similar to Accounts.

Related Slack conversation: https://octopusdeploy.slack.com/archives/help-me/p1483930666000058

**Comment by SeijiSuenaga** [comment]
This bug affects variable and tenant changes as well.

A user assigned to a team that is scoped only to specific projects and/or project groups is able to see variable/tenant changes in the audit log.  Adding an environment or tenant to the team's scopes causes all variable/tenant changes to disappear from the audit log.

Has there been any progress on this issue since January?

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User with EventView for project cannot see deployment process change audit records](https://trello.com/c/9x47NuNy/721-user-with-eventview-for-project-cannot-see-deployment-process-change-audit-records)

**Comment by NickJosevski** [comment]
Release Notes: Fix for inconsistencies in EventView permission calculations.
