### ISSUE TITLE
Update Deployment Process screen to provide better UX for managing steps & features

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3065]
Managing the deployment process with multiple steps and multiple features enabled is becoming a bit unwieldy.
Some design changes have been proposed to make this process a bit smoother for the user
[UX_Deployment_Process_Configuration_03.pdf](https://github.com/OctopusDeploy/Issues/files/700280/UX_Deployment_Process_Configuration_03.pdf)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Making the deployment process progressive](https://trello.com/c/9xJ5a3Fe/44-making-the-deployment-process-progressive)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deployment process progressive edit - Phase 1: Combine list of steps and edit onto one screen](https://trello.com/c/Mjuw4ATe/64-deployment-process-progressive-edit-phase-1-combine-list-of-steps-and-edit-onto-one-screen)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deployment process progressive edit - Phase 2: Split step edit into components rather than one long list](https://trello.com/c/J3sgNY2P/65-deployment-process-progressive-edit-phase-2-split-step-edit-into-components-rather-than-one-long-list)

**Comment by johnsimons** [comment]
Mostly implemented as part of v4
