### ISSUE TITLE
Broken scoped permissions for library variable sets

### ISSUE THREAD

**Issue by nael-fattah** [OctopusDeploy/Issues#3074]
Teams can see/edit variables inside the library variable sets that are outside their scope.
You are unable to see the scope, you can however see the variable and its values. You can then edit them.

Customer has great steps on replicating this, source: https://secure.helpscout.net/conversation/304625348/12423/?folderId=845288

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customize time between attempts when downloading packages from external feeds](https://trello.com/c/6XgYCYSe/57-customize-time-between-attempts-when-downloading-packages-from-external-feeds)

**Comment by alfhenrik** [comment]
Release note: Do not show variables in library variable sets that are scoped to environments for which a user is not authorized
