### ISSUE TITLE
Package uploaded with a - before the version cannot be accessed again

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3076]
When you upload a package named `Test-1.0.0.zip` though the web UI
- It shows up as version `Test-1` and version `0.0`
- The next page shows that the package can't be found
- It can't be deleted
- The details can't be viewed

**Comment by alfhenrik** [comment]
Same as https://github.com/OctopusDeploy/Issues/issues/3042

**Comment by droyad** [comment]
Closing as dupe
