### ISSUE TITLE
Environment selection on parent step causes JavaScript error

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3077]
Looks like a recent change ([#3053](https://github.com/OctopusDeploy/Issues/issues/3053)) have broken parent steps in rolling deployments, JavaScript error in developer console which causes the configuration of window size not to show. 

Also exhibited on our [demo](https://demo.octopus.com/app#/projects/octofx-trading-website/process/step/66da7067-1f0c-45bb-ae68-699a7e75ac7d) site.

Source: http://help.octopusdeploy.com/discussions/problems/50667

**Comment by vanessalove** [comment]
another report: http://help.octopusdeploy.com/discussions/problems/50681-cannot-change-role-on-process-step-if-the-step-contains-child-steps

**Comment by alfhenrik** [comment]
And another report: http://help.octopusdeploy.com/discussions/problems/50685-parent-step-role-cannot-be-changed

**Comment by zentron** [comment]
Release Note: Fix Javascript issue breaking the rolling deployment step page.

**Comment by davestephens** [comment]
Thanks for picking this up so quickly following my report!
