### ISSUE TITLE
Package transfer is not stopped when task is cancelled

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3078]
Related to https://github.com/OctopusDeploy/Issues/issues/3061

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Package transfer is not stopped when task is cancelled #3078](https://trello.com/c/oSbcwqhM/157-package-transfer-is-not-stopped-when-task-is-cancelled-3078)

**Comment by zentron** [comment]
This appears to even occur during Calamari update process.
As seen in screenshot below, calamari was still being pushed across when the `Cancel` was invoked. Not only does calamari continue to upload but it looks like once it hit 100% it started all over again.

![image](https://cloud.githubusercontent.com/assets/1830666/25110565/61fa3a16-2428-11e7-8c4b-3d57685e7b84.png)

**Comment by droyad** [comment]
Halibut does not current support cancellation of message sending. We would either need to modify Halibut, or terminate the connection, which may not clean up on the Tentacle correctly.

**Comment by zentron** [comment]
Unlikely to action given existing priorities
