### ISSUE TITLE
Deleting project group does not update teams

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3087]
If you delete a project group, it does not update the team to remove the reference to the project group. This causes an error when you try and edit the team as the referenced project group no longer exists.

Issue #3086 was logged to make this deleted project group visible (belt and braces approach), but we subsequently need to update the project group delete logic to remove from the teams.

Need to take into consideration what happens when the last project group is removed from a team - as this would increase the permissions of the members of that team.
 
* ~Do we delete the team? (I'm thinking this'd probably be a bad idea.)~
* ~Do we prevent project group removal if its the last project group assigned to a team?~
* Do we prevent project group removal completely if a project group is assigned to a team?

**Edit:** _Deleting an environment is blocked if it is referenced by a team. It doesn't update teams at all - it just blocks. We should probably follow the same approach._

**Edit:** _Deleting a project is also blocked in the same way if it is referenced by a team. We definitely should follow the same approach._

**Comment by zentron** [comment]
![image](https://cloud.githubusercontent.com/assets/1830666/23534121/70c3ed30-0001-11e7-9288-dbe5bfbb27fc.png)

**Comment by zentron** [comment]
Release Note: Prevent project groups from being removed if linked to a team to avoid permission creep.
