### ISSUE TITLE
Whitespace in variable expressions changes the result

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3089]
eg `#{unless action.IsSkipped }` will always evaluate to false. Original report: http://help.octopusdeploy.com/discussions/problems/50568-isskipped-not-working

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Whitespace in variable expressions changes the result #3089](https://trello.com/c/k0142yZL/172-whitespace-in-variable-expressions-changes-the-result-3089)

**Comment by markryd** [comment]
Release Note: Correctly evaluate `#{if Variable}` substitutions if there is whitespace between the variable and the closing brace
