### ISSUE TITLE
File upload functionality is not working in IE9

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3092]
The upload functionality is broken across the whole app in IE9.

![image](https://cloud.githubusercontent.com/assets/347637/22188462/1d2dc560-e161-11e6-8644-539ba09dc867.png)

The interesting fact is that it has been in that state at least for **a year** (tested in `3.2.19` and `3.8.1`) and nobody has reported it. This begs a question whether we still want to officially support IE9.  

We don't seem to have any stats re how many people use IE9 to manage their Octopus servers. The only thing we have is the usage on our public website which might or might not be relevant.

![image](https://cloud.githubusercontent.com/assets/347637/22188527/d183689e-e161-11e6-8c4a-cebd5321a64a.png)

Thoughts?

**Comment by jess-ross** [comment]
When released Bootstrap 4 will only support IE10+. If we choose to upgrade, that would be another reason to not support IE9.

**Comment by michaelnoonan** [comment]
As a side note, we noticed we cannot add a custom header using the `angularFileUploader` in IE8-9 which makes some security scenarios difficult to work with. Another vote for IE10+.

**Comment by pawelpabich** [comment]
Fix in v4 by dropping IE9 and IE10 support

**Comment by droyad** [comment]
No longer relevant
