### ISSUE TITLE
Add configuration for octopus.server.exe to modify the database connection string

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3100]
Currently if  you want to change the database connection string you have to modify the config file directly. As majority of the configurations in this file are able to be modified via the octopus.server.exe configure command it would be nice to have the ability to modify the connection string via that method also.

As an addition checking for any remaining configs that are not able to be changed via command line would be valuable to also add.

Source: https://secure.helpscout.net/conversation/309087670/12679/?folderId=557083

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add configuration for octopus.server.exe to modify the database connection string](https://trello.com/c/85LehcBU/191-add-configuration-for-octopus-server-exe-to-modify-the-database-connection-string)

**Comment by tothegills** [comment]
The command is:

`.\Octopus.Server.exe configure --storageConnectionString ""MyConnectionString"`
