### ISSUE TITLE
Project overview should honor lifecycle environment order, not environment sort order

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3103]
Source: http://help.octopusdeploy.com/discussions/problems/50852

**Comment by alfhenrik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lifecycle order not honoured by Dashboard](https://trello.com/c/cmFagSnU/127-lifecycle-order-not-honoured-by-dashboard)

**Comment by droyad** [comment]
@alfhenrik Does this just apply to the phase ordering, or to environments within a phase. Eg, I have (in order) `Local` and `Other`. If I create a lifecycle with one phase, adding those in reverse order, I can get:
![image](https://user-images.githubusercontent.com/1687639/31335211-e915a09a-ad34-11e7-8aa0-b81e9864b5ca.png)

Should the dashboard respect that order? There is no way to easily re-order the environments within a phase (short of removing and re-adding).

**Comment by alfhenrik** [comment]
This applies to environments within phases as well, e.g. the order of the environments on the project overview should mirror that of the environment list (top to bottom) on the lifecycle.

**Comment by droyad** [comment]
Release Note: Sorted environments on the dashboard by phase order then by order within phase

**Comment by nimblejoe** [comment]
Has this been in included into the product?  We have upgraded to version 4.1.0 and I'm not seeing this functionality there.  The order of the environments seems to take precedence over the order specified in the Lifecycle.  It seems more intuitive the have the Lifecycle take precedence or offer a switch on the Lifecycle that would allow you to specify which one takes precedence.

**Comment by droyad** [comment]
@nimblejoe Yes it has, and I just checked it on my dev instance and it does respect that ordering. Could you please send us a screenshot of the lifecycle and the dashboard showing the problem? If you want to keep it private, do it via https://octopus.com/support
