### ISSUE TITLE
Non-fatal JS Error occasionally appears in console logs

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3107]
When navigating through the site, pages that use react occasionally log the following error into the logs. This does not kill the app, but could cause users some unnecessary concern.
![image](https://cloud.githubusercontent.com/assets/1830666/22354384/dc41bc60-e470-11e6-9dc6-cb1fa23833e4.png)

**Comment by pawelpabich** [comment]
Fix in v4

**Comment by pawelpabich** [comment]
Fixed by using only React

**Comment by michaelnoonan** [comment]
Release Note: We fixed some noisy JavaScript errors which were appearing in the browser logs
