### ISSUE TITLE
Disabling a step causes variable scopings to be removed

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#3114]
To reproduce:

1. Create a project with two steps
2. Add a variable
3. Scope the variable to both steps 
4. Disable one of the steps
5. Check the variables - the scoping will disappear for the step that was disabled. This can be confirmed in the audit history.

**Comment by pawelpabich** [comment]
UI before fix:

![image](https://cloud.githubusercontent.com/assets/347637/22413593/ff6d92fe-e704-11e6-85ca-27e0dcac5a5f.png)

UI after fix:

![image](https://cloud.githubusercontent.com/assets/347637/22413642/59327f7a-e705-11e6-9564-4938750c3d1f.png)

**Comment by pawelpabich** [comment]
Release Note: Variables can be scoped now to disabled steps
