### ISSUE TITLE
Sensitive variables when length greater than 47 chars can not be decrypted on SSH targets

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3122]
To reproduce:

- create a script step that runs "echo $(get_octopusvariable "app_key")"
- create a sensitive prompted variable called app_key
- release/deploy providing app_key a value < 48 characters - success!
- deploy providing app_key a value >= 48 characters:
![image](https://cloud.githubusercontent.com/assets/171197/22497605/a063dd90-e89e-11e6-8f44-31002c3c6c73.png)

See http://help.octopusdeploy.com/discussions/problems/50958

**Comment by droyad** [comment]
Reproduced on Ubuntu 14.04.5. Works on 16.10.

**Comment by droyad** [comment]
Release Note: Linux machines with older versions of openssl now support long sensitive variables
