### ISSUE TITLE
Support long paths on Win10 and Server 2016

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3129]
Windows 10/Server 2016 introduced improvements in long path support.

Documentation: https://octopus.com/docs/how-to/long-paths

Todo:
- [x] Support in Calamari (#3129)
- [ ] Support in C# scripts
- [ ] Support in F# scripts
- [x] Support in Server
- [ ] Support in Tentacle
- [x] Check #2532 is now resolved for Win10/Server2016
- [x] Documentation
- [ ] Migrator

#2532 (Retention policy failing on long path structures) is related

**Comment by thebigmoosey** [comment]
fyi I created this little test package to test long path support for an [OctoPack PR](https://github.com/OctopusDeploy/OctoPack/pull/93). We can re-use it here to test long-path support in our various systems if needed ... (GitHub didn't support .nupkg files, so I compressed the package contents as a zip instead)

[MyLongPackage.1.0.0.zip](https://github.com/OctopusDeploy/Issues/files/1069992/MyLongPackage.1.0.0.zip)

**Comment by robcwaldron** [comment]
Hey guys, any chance there's an update on this? We've been blocked from deploying a large Sitecore codebase for a while now through Octopus due to this constraint.

**Comment by droyad** [comment]
@robcwaldron Nothing new yet, however the solution seems straight forward. I'll have a another look at it.

I'll link your support request for our reference: https://help.octopusdeploy.com/discussions/problems/68020-octopus-419-long-file-path#comment_45119611 (private link)

**Comment by droyad** [comment]
The latest Octopus `2018.5.3` and Tentacle `3.21.0` have added support for long file names. See https://octopus.com/docs/deploying-applications/custom-scripts/long-paths for limitations

We are limited to 255 characters for the working directory when starting a process, eg when running pre/post install scripts and scripts from a package.

**Comment by droyad** [comment]
This hasn't come up again this year, so I think we've resolved this
