### ISSUE TITLE
Additional Transforms Feature

### ISSUE THREAD

**Issue by BlueWombat** [OctopusDeploy/Issues#3134]
Hi.

When I'm attempting to use said feature, with line listed below, I get some very strange behavior.
It's attempting to transform my Web.config which is at the root of my package, no problem there. However, the entire task fails because I have another Web.config file nested i a sub-directory, which to my understanding whouldn't be affected by the config I've provided.

Config line:
#{InstallDir}\Web.Support136135.config => Web.config

Log entry:
The XML configuration file D:\Octopus\Applications\Integration\Web.Config.Integration.Master\1.0.0-integration0000124\sitecore\admin\Web.config failed with transformation file D:\web\Website_1.0.0-integration0000124\Web.Support136135.config

Hope you can be of assistance.

Thanks in advance,
Mikkel Petersen.

**Comment by Dalmirog** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support.

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

---

We also accept PRs for library step templates such as that one :). Perhaps you can attempt to add this enhancement yourself? It definitely sounds like a solid idea

https://github.com/OctopusDeploy/Library/blob/master/step-templates/slack-notify-deployment.json

**Comment by BlueWombat** [comment]
Well, did you even read the contents?

It's a bug report in an existing deploy feature, not a feature request..

Den 3. feb. 2017 7.07 PM skrev "Dalmiro" <notifications@github.com>:
