### ISSUE TITLE
Can not clone or disable project due to invalid channel reference.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3137]
Project is referencing a channel that does not exist. This is causing Octopus to error when trying to disable or clone the project.

(Source: https://secure.helpscout.net/conversation/314389775/13021/?folderId=845288)
(Related: https://github.com/OctopusDeploy/Issues/issues/2484)

We need to:
* fix up any existing data Is this possible? If not, then we need to detect this situation and show a warning to the user that they need to fix it.
* fix up channel delete so that it blocks if the channel is used by Automatic Release Creation

**Comment by danielfischeroctopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can not clone or disable project due to broken data reference.](https://trello.com/c/rNsXQBAA/181-can-not-clone-or-disable-project-due-to-broken-data-reference)

**Comment by zentron** [comment]
Release Note: Fixed bug preventing project cloning when channel missing on auto release creation strategy.
