### ISSUE TITLE
Successful authentication request against Google Apps or AD redirects to logout page. 

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3144]
When I tried to login using Google Apps  or AD

![image](https://cloud.githubusercontent.com/assets/347637/22678247/7033be9c-ed44-11e6-85ab-d97871d5739f.png)

I was redirected to 

![image](https://cloud.githubusercontent.com/assets/347637/22678252/78d001dc-ed44-11e6-9821-2ecfc0778951.png)

**Comment by zentron** [comment]
Release Note: Correctly redirect 3rd party login to dashboard after logging out and back in again.
