### ISSUE TITLE
Improve upgrade experience when database changes are required

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3147]
We've been thinking on this for some time now. Some of our customers experienced problems when upgrading HA clusters, not realising database upgrades were still running on one node, and started the upgrade on another node which resulting in errors.

# Suggested solution

1. The Octopus Server Manager is always loaded post-upgrading-executable-files. Show a dialog in the Octopus Manager indicating:
  a. Database changes are required.
  b. Information on backup and restore.
  c. Link to the release notes from-to versions like [this](https://octopus.com/downloads/compare?from=3.7.6&to=3.8.7). (How would we do this? Introduce a release history file on disk?)
  d. Provide a button to execute the database upgrade and show progress in the form of a log window (like other scripts)
  e. Help people out when an error occurs.

Source: https://secure.helpscout.net/conversation/305177983?folderId=571731

**Comment by matt-richardson** [comment]
We'll need to consider how to handle this in quiet/unattended install mode as well.

**Comment by jdkang** [comment]
Even a simple `gc "C:\Octopus\Logs\OctopusServer.txt" -Wait -Tail 10` (obviously you'd have to not hard code the path) was enough to make it A LOT more clear for us what was going on.

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve upgrade experience when database changes are required](https://trello.com/c/bNehwny2/454-improve-upgrade-experience-when-database-changes-are-required)
