### ISSUE TITLE
Make release names wrap on the dashboard

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#3162]
Issue: http://help.octopusdeploy.com/discussions/problems/51136

**Why**
Some of our users display the dashboard on a screen in the office and the change in 3.7.8 to truncate the release names is causing issues. A tool tip was included in the change but this doesn't work when a user doesn't have access to the screen. 

**Solution**
Make the release names wrap and at the same time make sure the machine names wrap.

**Comment by jess-ross** [comment]
Release note: Fix to make long release names wrap on the dashboard.

**Comment by MattJeanes** [comment]
Running 3.10.10. Currently the words wrap mid-word, e.g:

```
My Cool Test Servi
ce
```

And it looks a bit weird, perhaps it could wrap on words where possible? E.g

```
My Cool Test
Service
```
