### ISSUE TITLE
De-registering tentacle from server that doesn't know about it leaves reference to config in file

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3163]
Steps to reproduce:
1) register a tentacle with a server
2) delete the tentacle from the server side
3) attempt to de-register - you'll see an error `Error: No machine matching this Tentacle's thumbprint was found.`
4) check `Tentacle.config` -> server is still listed

It should remove the server reference from the config file.

**Comment by NickJosevski** [comment]
Suggestion decision path from @matt-richardson:

```
1) check if thumbprint matches the server
2) call delete
3) if server says “no idea who you are” but thumbprint matches, delete from config
4) if server says “no idea who you are” but thumbprint doesn’t match, don't delete
5) if server says “deleted”, delete from config
```

**Comment by NickJosevski** [comment]
Release Note: Fix for de-register tentacle command, tentacle configuration now updates
