### ISSUE TITLE
Provide a first-class way to delete untenanted deployments when changing Project to tenanted-only mode

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3169]
We generally consider the "mixed mode" of untenanted/tenanted deployments as a bridge from one model to the other. One missing piece here is that we don't provide a first-class way to clean up the untenanted deployments when changing to `Tenanted deployments only` mode. The result is that the untenanted deployments never get superseded, meaning they stay on the dashboard forever, and retention policies can do nothing about cleaning them up.

# Suggested Solution

When the Project's `multi-tenant deployment mode` changes to `Tenanted deployments only` we could prompt the user to see if they want us to delete all of the untenanted deployment history for that project. If not, we leave the history alone. If yes, we delete all the deployment history and related documents via cascade rules.

# Workaround

Until we add this enhancement you can safely use C# (or PowerShell) script like this one to achieve the same result:

```
void Main()
{
	string octopusUrl = "http://localhost:8065";
	string apiKey = "API-XXXXXXXXXXXXXXXXXXXXXXXXXXX";
	string projectName = "myprojectname";

	var octopusServer = new OctopusServerEndpoint(octopusUrl, apiKey);
	var repo = new OctopusRepository(octopusServer);

	var project = repo.Projects.FindByName(projectName);
	if (project == null)
		throw new Exception($"There is no project called {projectName}");
	
	var releases = repo.Projects.GetAllReleases(project);
	
	var environments = repo.Environments.GetAll();

	var deletedCount = 0;
	repo.Deployments.Paginate(
		new[] { project.Id },
		environments.Select(env => env.Id).ToArray(),
		(page) =>
		{
			var untenantedDeployments = page.Items.Where(d => string.IsNullOrWhiteSpace(d.TenantId));
			foreach (var untenantedDeployment in untenantedDeployments)
			{
				deletedCount++;
				var url = untenantedDeployment.Link("self");
				Console.WriteLine($"Deleting {url} [{untenantedDeployment.Name} {releases.SingleOrDefault(r => r.Id == untenantedDeployment.ReleaseId)?.Version}]");
				repo.Client.Delete(url);
			}
			return true;
		});

	Console.WriteLine($"Found and deleted {deletedCount} untenanted deployments for {project.Name}");
}
```

The easiest way to do this immediately is to use [LINQPad](https://www.linqpad.net) with [this shared script](http://share.linqpad.net/c2rm5v.linq). Alternatively you can copy that code into a small C# program and reference the [Octopus.Client](https://www.nuget.org/packages/Octopus.Client/) NuGet Library.

**Note you will need to replace the `myprojectname` with the real project name.**

# Original Source

http://help.octopusdeploy.com/discussions/questions/10782
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/16980910-hide-the-un-tenanted-release-goup

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide a first-class way to delete untenanted deployments when changing Project to tenanted-only mode](https://trello.com/c/wjPmmFNr/738-provide-a-first-class-way-to-delete-untenanted-deployments-when-changing-project-to-tenanted-only-mode)

**Comment by MJRichardson** [comment]
This could possibly be addressed simply by retention-policy.
Once a project has been marked as tenanted-only, all untenanted releases could be removed at the next retention-policy run.

**Comment by droyad** [comment]
Allow the deletion of depoyments via the UI

**Comment by sanistaal-bbc** [comment]
This helped me to get rid of my untenanted deployments. Thanks!

**Comment by bwinchester** [comment]
Any update on this? 
We moved to tenanted deployments to simplify tenant variables and manage what products tenants have. Great. But we have this cluttered environments columns on each project dashboard now with legacy releases.

**Comment by droyad** [comment]
No progress on this @bwinchester, however the above script is a good workaround.

**Comment by octokhor** [comment]
Most customers interviewed on tenants have either found a way to get around this or got into tenants from the very beginning. This idea also exists as part of tenants research so closing down this particular ticket to avoid populating the FnM backlog too much
