### ISSUE TITLE
Images are not resizing n tenants overview page

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#3170]
Source: http://help.octopusdeploy.com/discussions/problems/51203-tenants-and-project-image-resize-ie-vs-chrome?mail_type=queue

There is an issue with project and tenant logo images not auto resizing in IE11, 10 & 9. 

<img width="1075" alt="screen shot 2017-02-14 at 1 14 19 pm" src="https://cloud.githubusercontent.com/assets/17240784/22913620/a3def2b6-f2b7-11e6-8754-87b25e8b77f8.png">

This is what it should look like...
<img width="790" alt="screen shot 2017-02-14 at 2 13 28 pm" src="https://cloud.githubusercontent.com/assets/17240784/22914986/d641bd62-f2bf-11e6-80d6-c743a6ed39d5.png">

Images resize fine on the project overview page, tenants page and the dashboard. Issue seems to be isolated just on a tenants overview page.

**Comment by droyad** [comment]
Release Note: Tenant logos now size correctly in Internet Explorer
