### ISSUE TITLE
Add switch to Octo.exe pack so it lists the files it adds to the package just like Octopack

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3171]
Subject pretty much says it all. The switch could be called `--verbose` (Powershell standard) or `--ListFiles`.

- I don't think the switch should be `true` by default, but that's totally up for discussion in our team channel.
- Should it be added as a checkbox on the VSTS and TeamCity extensions, or should we let users add it manually as an extra argument? My vote goes for checkbox because I feel this is a troubleshooting feature that we want users to quickly discover by themselves, hopefully without logging a ticket first with the usual "Octopus didn't deploy file [x]".

Make sure to update the `Octo.exe help pack` output in our docs once the switch gets added: https://octopus.com/docs/packaging-applications/nuget-packages/using-octo.exe

Sort of source: http://help.octopusdeploy.com/discussions/questions/10802

**Comment by Damovisa** [comment]
Updated VSTS extension to include checkbox: https://github.com/OctopusDeploy/OctoTFS/commit/5e4b702d7f6181b4d8ac25df8923ad4a75c11635

**Comment by NickJosevski** [comment]
Release Note: octo.exe pack command has verbose logging support showing files added, can also be selected in VSTS extension
