### ISSUE TITLE
2.6 Migration to run upgrade scripts post data commit

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3173]
Currently when doing a 2.6 > 3 migration you install the 3 db (including running the db scripts) then you import your data. Many scripts clean or update data so it starts in a bad state.

This task is to determine what data clean/modify scripts need to be run post migration on the data.

source: https://secure.helpscout.net/conversation/314076862/13004/?folderId=557083

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2.6 Migration to run upgrade scripts post data commit](https://trello.com/c/Pyuex8K5/128-2-6-migration-to-run-upgrade-scripts-post-data-commit)

**Comment by NickJosevski** [comment]
Closing

If you need help migrating from 2.6 to 3. please contact [Octopus Support](https://octopus.com/support)
