### ISSUE TITLE
Add ability to specify run condition as on `Success/Failure condition` and `Variable condition`

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#3187]
A couple of options: make Run condition: Variable separate from Run condition: Success/Failure/Always; or create new entries SuccessAndVariable, FailureAndVariable.

Source: http://help.octopusdeploy.com/discussions/problems/51360

**Comment by ccamburn** [comment]
As a workaround for anyone who needs it, until this gets added, the following will work:

To run only on success and variable truthiness:

`#{unless Octopus.Deployment.Error}#{PromptedVariable}#{/unless}`

To run only on failure and variable truthiness:

`#{if Octopus.Deployment.Error}#{PromptedVariable}#{/unless}`

**Comment by zentron** [comment]
Closing ticket unless raised again by customer
