### ISSUE TITLE
Radio buttons are not in view on small screen for create release page

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#3192]
Source: https://secure.helpscout.net/conversation/315741257/13068/?folderId=557082

When creating a release on a small screen the radio buttons for "When" are not visible to the user. I could only recreate it so that the buttons were not in line which could be the issue and is a matter of applying the "radio" class to a div rather than to the label. 

**Recreated**
<img width="330" alt="screen shot 2017-02-17 at 1 11 31 pm" src="https://cloud.githubusercontent.com/assets/17240784/23051335/fe11ba6c-f513-11e6-8bc9-d9a13f015887.png">

**Users**
![image](https://cloud.githubusercontent.com/assets/17240784/23051498/32aabf0c-f515-11e6-8e0e-48997705a84a.png)

**Comment by alfhenrik** [comment]
Release note: Align radio buttons on deploy release page so that they are visible on smaller screens
