### ISSUE TITLE
Active project tab overlays script editor in fullscreen mode

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3195]
Steps to reproduce:
1. Go to a project
2. Add the step to Run a Script
3. Click to go fullscreen in the code editor

Source: http://help.octopusdeploy.com/discussions/problems/51434

**Comment by brunorubin** [comment]
Hi @alfhenrik. Thanks for opening this issue. 
Do you have any ETA on when it will be released?

cheers.

**Comment by danielfischeroctopus** [comment]
Another Source: https://secure.helpscout.net/conversation/337677713/14211/?folderId=845288

**Comment by pawelpabich** [comment]
Duplicate: https://github.com/OctopusDeploy/Issues/issues/3381
