### ISSUE TITLE
Variable Run Condition should ideally be evaluated on a machine level to allow for machine scoped variables

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3206]
Given the following step that produces an output variable
![image](https://cloud.githubusercontent.com/assets/1830666/23241259/ccc8f980-f9bd-11e6-88bb-16bf0bc6dd19.png)

A subsequent step with the run condition:

![image](https://cloud.githubusercontent.com/assets/1830666/23241284/fb2d5794-f9bd-11e6-9151-e64581d60d10.png)

Fails to evaluate since the code to determine the condition occurs before machine evaluation (DeploymentPlan.cs#90). Ideally this logic should take place _at the machine level_ so that users can include machine specific variables that may be relevant to the running of those steps on those machines, seperate to the evaluation that takes place for other machines.

Source: https://secure.helpscout.net/conversation/323552838?folderId=557077

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Run condition Variable](https://trello.com/c/x2gduEk4/268-run-condition-variable)

**Comment by ccamburn** [comment]
Would this then mean that you could have a step that runs on a role that includes X machines, each of which has custom output variables from a previous step, and the new step would run on SOME of the machines (not necessarily all) based on the output variables?

If so, that would basically allow for a (somewhat convoluted) solution to running a step on one machine from a pool of machines. 
http://help.octopusdeploy.com/discussions/questions/10686-run-step-once-from-a-pool-of-tentacles

**Comment by zentron** [comment]
I suppose technically you are right, It might work though the point Paul makes in the original thread still stands that it might not end up being the best allocation of resources.  That being said if its "convoluted" enough (to use a term that is probably quite apt 😄 ) then perhaps only users who fully understand its repercussions will do such a thing.

Good point though, it will be interesting to see what else this provides once its enabled.

**Comment by KennethBates** [comment]
Another source: https://help.octopus.com/t/variable-run-condition-scoped-for-target-machine/19213

**Comment by patricknolan** [comment]
Thanks @KennethBates .

@ccamburn link about posted by Kenneth provides a real-world scenario for this. It's actually critical for us and I'm surprised it works how it currently does.

Unfortunately, I'm going to have to work out an interim solution for this. Hopefully this issue will be fixed soon!

**Comment by KennethBates** [comment]
Another source: https://secure.helpscout.net/conversation/647440423/31408?folderId=954335 (private link)

**Comment by TomPeters** [comment]
Hi @ceilingfish,

>Are roles considered machine level data, or is this a different issue?

From the point of view of variable scoping, you could describe roles as being considered machine level data. So yes, I believe that this is the same issue.

**Comment by syeadon** [comment]
Hi, I just wanted to point out why this would be useful and it may help others. I needed to execute sql against the primary machine in a sql availability group, I wanted to use the community "execute sql" step. All the sql machines in the availability group are part of a  "sql" target. The problem with this is that all the code i have written will execute against all the machines in that role. What I wanted to do was write a custom step that retrieved the availability group's primary machine name and output it as a variable. Later I could use the run condition to decide whether this code would run on this machine or not (some times the sql may need to run on both machines). Presently this is not possible. I have had to not use the community step and instead write a custom step that accepts sql and performs the machine  name validation each time. Its not a huge problem but my code is bloated with validation code.

**Comment by KennethBates** [comment]
Another request for this: https://secure.helpscout.net/conversation/915293865/47836?folderId=954335 (private link)

**Comment by KennethBates** [comment]
Another request (private link) https://secure.helpscout.net/conversation/925837745/48494?folderId=954335

**Comment by MarkSiedle** [comment]
Release Note: Adding variable run conditions for child steps
