### ISSUE TITLE
Step preview on the advanced deployment view can be incorrect for tenanted deployments

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3217]
Relates to: https://github.com/OctopusDeploy/Issues/issues/3178

# Issue description from customer

This morning I wanted to deploy a single step from our tenanted project as part of my deployment to a tenant. The step was marked to **only run for tenants with a specific tag**, but I forgot that when deploying. The tenant I was deploying to should have had the tenant tag that makes the step run, **but it did not**.

When I deployed, I expected the single step I had marked to run, **but it did not**.

I realized after a second attempt that it was because the tenant was missing the tenant tag that was required for the step to run.

# Suggested solution

It would be helpful if the advanced deployment options would also give an indication of whether the step is expected to run based on the options for restricting a step to certain environments/tenant tags, and if not, why.

Source: https://secure.helpscout.net/conversation/319167840?folderId=571731

**Comment by MJRichardson** [comment]
Let's verify this works as expected in 4.0 before it ships.

**Comment by droyad** [comment]
The deployment steps are shown correctly per tenant. However there is no explanation of why a step wouldn't run. Should we consider this done?

**Comment by droyad** [comment]
@michaelnoonan @matt-richardson ⬆️

**Comment by michaelnoonan** [comment]
Yes, this is fixed in 4.0 alpha.

**Comment by droyad** [comment]
Release Note: Deployment preview now shows which steps will run on a per-tenant basis
