### ISSUE TITLE
Include steps duration time in Task Log

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3221]
Source: http://help.octopusdeploy.com/discussions/questions/10933

3 votes for straight github instead of Uservoice: https://octopusdeploy.slack.com/archives/team-execution/p1487869907000005

Showing it in the Task Summary would be a great plus

**Comment by Dalmirog** [comment]
An output variable with each step's duration could be useful for post-deployment notifications: http://help.octopusdeploy.com/discussions/questions/11047

**Comment by NickJosevski** [comment]
Task summary looked quite noisy, it will be on the header sections of the 'Task Log' page, as it runs you can see it ticking up, and it will report a final time.

The API now delivers `Duration` for tasks when returned as `ActivityLogTreeNode`s this can be used if needed.

**Comment by NickJosevski** [comment]
Release Note: Task logs will show duration of tasks as they run, and total run time when finished
