### ISSUE TITLE
DSC cTentacleAgent $TentacleHomeDirectory doesn't accept whitespace chars

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3226]
> If you use 'c:\give me white\spaces please' the MSI install part till stall forever.
>
>Also in that context there seem to be no error handling of msi installs that fail to start because of bad parameters.

Source: https://github.com/OctopusDeploy/OctopusDSC/issues/43

**Comment by matt-richardson** [comment]
Closing as duplicate of https://github.com/OctopusDeploy/OctopusDSC/issues/43
