### ISSUE TITLE
Project Overview screen skips releases greater with than 2 deployments passed.

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3229]
Due to the way we use the `dbo.Dashboard` view only the "current" and "previous" release for each environment in a project is returned for the project overview screen. This means that if you have deployed `Release 1` to prod, then `Release 2, 3 & 4` to `Dev` only release 1 3 & 4 would show up on the overview screen with `Release 2` mysteriously missing.

![image](https://cloud.githubusercontent.com/assets/1830666/23386212/e74b9d9e-fda0-11e6-8f62-30d45bc9c259.png)
![image](https://cloud.githubusercontent.com/assets/1830666/23386220/f0306566-fda0-11e6-9f98-0074696aa493.png)
![image](https://cloud.githubusercontent.com/assets/1830666/23386227/fa216746-fda0-11e6-99c4-7356ef38bc0e.png)

While this may be good for performance reasons, and ultimately not incorrect in showing which release is in which environment, it does raise the possibility of confusing users as to what happened to a previous release.

Source: http://help.octopusdeploy.com/discussions/problems/51666

**Comment by StevenWolfe** [comment]
This caused me a little confusion this morning...

In my case I had two releases that had previously gone to our Production environment.  I created two new releases that were scheduled for the future, but was confused to see only 1x of the newly scheduled releases and 1x of the old completed releases.

At a minimum it would be nice to be sure that new or pending releases take priority over old stuff in the query.  And/or possibly a hint somewhere that Overview is truncated.

Thanks!

**Comment by thebigmoosey** [comment]
Other reports:
- https://help.octopus.com/t/add-view-more-button-to-project-overview-table/21185
- https://secure.helpscout.net/conversation/653078966?folderId=557077

**Comment by zentron** [comment]
Ticket referenced on larger dashboard ticket
