### ISSUE TITLE
Skip All with disabled steps result in an error

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3233]
When selecting `Skip All` when creating a deployments for a project that has disabled steps, the disabled steps are also marked as `skipped`. When the deployment is submitted an error occurs `Could not find an action matching <guid>` as the deployment does not expect that step to come through.

The work around is to disable each step individually instead of using the `Skip All` short cut.

**Comment by droyad** [comment]
See https://github.com/OctopusDeploy/OctopusDeploy/issues/858 (internal link)

**Comment by NickJosevski** [comment]
Release Note: Fixed skipped step issue, was just logging entries being delayed.
