### ISSUE TITLE
Api Key and other dialogs do not close when session times out

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3240]
I left my api key dialog open in a background tab, and when I came back the next day, my session had timed out but the dialog was still visible.

![image](https://cloud.githubusercontent.com/assets/373389/23489346/e8d69474-ff45-11e6-8e8f-6cab04168f50.png)

I believe that this also happens on other dialogs - eg the "delete environment' dialog.

(and before you ask, yes, that api key has been revoked)

**Comment by zentron** [comment]
Release Note: Modals dismissed if url route changes or user logs out
