### ISSUE TITLE
Import all certificates in chain

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3257]
Currently if an uploaded certificate contains a chain of certificates, only the leaf certificate will be installed.

When importing a PFX file using the Windows Certificate Manager, it imports all certificates in the chain, place the CA certificates in the appropriate stores (Intermediate CA or Root CA).

We should do similar.  i.e. determine the certificate chain and install the certificates into the appropriate stores (if not already present).

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import all certificates in chain](https://trello.com/c/oPceg8zn/208-import-all-certificates-in-chain)

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Certificate chains](https://trello.com/c/WIB1w5Uh/21-certificate-chains)

**Comment by MJRichardson** [comment]
Merged into 3.12.0

**Comment by MJRichardson** [comment]
Release note: Support for PFX files containing a certificate-chain when uploading certificates
