### ISSUE TITLE
Permissions required to access script modules should be stated on the edit User Roles page

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3268]
Currently there is nowhere inside Octopus to see the permissions required for the Scrip Modules feature.

The below screenshot shows what is currently displayed.
![libvar](https://cloud.githubusercontent.com/assets/18252832/23694063/7beed5d2-0423-11e7-938b-f192157cf979.JPG)

Below is what is required for the Script Modules feature:

To see the Script modules menu requires the VariableView permission.
To create a new Script module requires the LibraryVariableSetCreate permission.
To view an existing Script module requires the LibraryVariableSetView, VariableView and VariableViewUnscoped permissions.
To edit an existing Script module requires the LibraryVariableSetEdit permission.

They should be stated inside Octopus, on the page where you edit User Roles.

**Comment by NickJosevski** [comment]
Closed: Merging with https://github.com/OctopusDeploy/Issues/issues/3931 to form a single UX focused roles/permissions feature request.
