### ISSUE TITLE
Import Certificate gives error if Private-Key Exportable set and no private-key is present

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3270]
If the 'Private-Key Exportable' field is checked on the Import Certificate step, and the certificate being imported does not contain a private-key, an error is thrown:

```
There was an error importing the certificate into the store
​Certificate does not have a private-key
```

As reported by: https://secure.helpscout.net/conversation/330939849?folderId=557077

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import Certificate gives error if Private-Key Exportable set and no private-key is present](https://trello.com/c/DJhE7bJj/216-import-certificate-gives-error-if-private-key-exportable-set-and-no-private-key-is-present)

**Comment by pawelpabich** [comment]
Hmmm @MJRichardson isn't this actually a good thing?  The user wanted X and the the action can not be performed so I would say we should provide feedback which is what we do here.

**Comment by MJRichardson** [comment]
@pawelpabich Yeah, I think you may be right.  You could easily argue failing silently would be worse.
Let's close.

**Comment by MJRichardson** [comment]
I suppose the only exception to this is perhaps when using creating a step-template.  But you could always expose that as a parameter.
