### ISSUE TITLE
Reordering a step with a run condition will still evaluate if its removed due to being the first step.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3288]
You can reorder a step with a run condition to be run first, it will hide the run condition option but still evaluate.

Step to replicate are as below:

Create two steps.
Set run condition on second step
reorder steps so second step is first
run condition is no longer displayed but still in effect.

Source: https://secure.helpscout.net/conversation/331750973/13944/?folderId=845288

**Comment by ccamburn** [comment]
Related: #3096

**Comment by droyad** [comment]
Fixed when #3096 was implemented
