### ISSUE TITLE
Open Redirection attack error in IE 11

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3299]
When attempting to login using GoogleApps, Azure AD or the AD integrated security user receives the following

![image](https://cloud.githubusercontent.com/assets/4229735/23978429/aaad9f9e-0a3f-11e7-9c40-c3ee3fef9fe9.png)

Error only occurs when using IE11.  Chrome and Edge both work as expected.

Also doesn't seem to happen in current dev code, when using :8065.  If you run `npm run build` and rebuild the server then the issue appears.

Maybe related, server console also shows

```Unhandled exception from web server processing GET to http://localhost:8065/{{ '~/images/microsoft_signin_buttons/microsoft-logo.svg' | resolveLink }}: An operation was attempted on a nonexistent network connection```

when the page is loading, indicating the Js isn't working as expected.

We have had reports of this error from customers.
https://secure.helpscout.net/conversation/330142862/13853?folderId=557082

**Comment by zentron** [comment]
Didnt notice referenced exception, but IE11 appears to return paths from anchor elements different from other browsers (including edge). Fix ensure that `/` prefix exists for relative paths.

**Comment by zentron** [comment]
Release Note: Fixed redirect path on IE11 causing authentication login errors
