### ISSUE TITLE
Server fails to start due to missing SQL permissions when using Active Directory auth

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#3317]
**Repro steps during installation process:**
1. Choose a Domain Service account for the Octo service (e.g. `octo\octoservice`)
2. Choose integrated auth for SQL Server the connection, and choose a “New” database
  - a prompt will come up asking for permission to add the database
  - Note: no prompt to add permissions to the service account

**Outcome:**
After the rest of the install, Octopus stops running because the user doesn’t exist or have permissions.
An investigation of SQL Server shows that the service account doesn't exist as a user at all, when it should exist and have db_owner permissions.

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Server fails to start due to missing SQL permissions when using Active Directory auth](https://trello.com/c/JwYYEBTV/735-server-fails-to-start-due-to-missing-sql-permissions-when-using-active-directory-auth)

**Comment by michaelnoonan** [comment]
Fixed as a byproduct of https://github.com/OctopusDeploy/OctopusDeploy/pull/1760

**Comment by michaelnoonan** [comment]
Release Note: When installing Octopus Server and using a Custom Windows Account to run the service, the installation wizard will configure SQL Server correctly so the Custom Windows Account can access the database
