### ISSUE TITLE
Dashboard not always showing latest release version in environment

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3325]
Project overview: 
![image](https://cloud.githubusercontent.com/assets/1035315/24180231/82eafabe-0eff-11e7-956f-ef8719de4232.png)

Dashboard:
![image](https://cloud.githubusercontent.com/assets/1035315/24180242/8f0838c0-0eff-11e7-96cd-5b0c5936fa43.png)

Expected result on dashboard is that release `6.0.10` is shown in the `Production On Cloud` environment

Investigating the issue led me to this code in [release_matrix.js](https://github.com/OctopusDeploy/OctopusDeploy/blob/master/portal/app/areas/dashboard/directives/release_matrix.js#L149)
```
    var getItemToShowOnDashboard = function (deployments) {
        if (!deployments || !deployments[0]) {
            return deployments;
        }
        var sortedDeployments = _.sortBy(deployments, 'ReleaseVersion').reverse(); // sorting strings in JS is fraught with dangers! as we've found multiple times in the past
        var index = _.findIndex(sortedDeployments, function (item) {
            return item.State === 'Executing' || 
                item.State === 'Failed' || 
                (item.State === 'Success' && item.HasWarningsOrErrors);
        });
        if (index > -1) {
            return sortedDeployments[index];
        }
        return sortedDeployments[0];
    };
```
Sources (private threads): 
https://secure.helpscout.net/conversation/336702248?folderId=571729
http://help.octopusdeploy.com/discussions/problems/51353
http://help.octopusdeploy.com/discussions/problems/53220
http://help.octopusdeploy.com/discussions/problems/53126

**Comment by pawelpabich** [comment]
Release Note: Correct versions are now displayed on the main dashboard
