### ISSUE TITLE
Ability to exclude tenants when creating multiple tenanted deployments

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3336]
The tenant filters in Octopus currently allow you to create powerful queries as explained here: https://octopus.com/docs/key-concepts/tenants/tenant-tags#TenantTags-Tag-basedfilters

Sometimes customers want to exclude a specific tenant, or perhaps all tenants with a certain tag. We have been introducing support for exclusionary logic when choosing specific targets to deploy to, or when to run certain steps. Perhaps we should allow people to specify two entire filters?

1. Include tenants matching this filter
2. Exclude tenants matching this filter

Some interesting ideas are posed here to do with action conditions and tenants: https://github.com/OctopusDeploy/Issues/issues/3337

Source: http://help.octopusdeploy.com/discussions/questions/11198

# Some questions to answer

1. How would we tame the complexity of the UI around this?
2. Same for all the existing command-line and API parameters?
3. Should it be either include, or exclude, or should we allow a combination of the two and let the result be the "left outer join"?

**Comment by droyad** [comment]
Closing this for now as specific Exclude functionality would complicate everything
