### ISSUE TITLE
Octopus.Action.Package.InstallationDirectoryPath exists but its not discoverable

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3340]
The variable `Octopus.Action.Package.InstallationDirectoryPath` exists per #2300 and can be used in steps and scripts, but it doesn't show up in the Task Logs or the Variables Menu next to the fields making it a bit hard to discover for other users.

**Comment by NickJosevski** [comment]
Release Note: Octopus.Action.Package.InstallationDirectoryPath is now available in the variable menu
