### ISSUE TITLE
Process menu item covers part of the code window in full screen mode

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3381]
http://help.octopusdeploy.com/discussions/problems/53145

**Comment by pawelpabich** [comment]
Release Note: 'Process' menu item doesn't cover the code editor when editor is in full screen mode

**Comment by matt-richardson** [comment]
"interesting" reason why it does the `z-index` in the first place - https://github.com/twbs/bootstrap/blob/ab77282004a6534ed050d78b9699c84068de547a/scss/_list-group.scss#L74
