### ISSUE TITLE
PreservePaths not working correctly for Azure Web Apps

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3384]
Our documentation list an example about [Preserving Paths](https://octopus.com/docs/guides/azure-deployments/web-apps/web-app-concepts#WebAppConcepts-PreserveSpecificPathsWhenDeployingAzureWebApp) during deployment of an Azure Web App.

The scenario described in the documentation no longer works.  If the components are in a common folder and that folder is listed in the Octopus variable then all folders below it are preserved, regardless of any other expressions you add.  If you don't list the common folder then it and all of it's children are always removed, even if they are list explicitly to preserve in the expression.

Source http://help.octopusdeploy.com/discussions/problems/53130

**Comment by slewis74** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PreservePaths not working correctly for Azure Web Apps](https://trello.com/c/rKbX9o32/170-preservepaths-not-working-correctly-for-azure-web-apps)

**Comment by LukaszPrzybysz** [comment]
Hi,
As you've already closed the discussion (http://help.octopusdeploy.com/discussions/problems/53130-preservepaths-doesnt-work-as-expected), can I expect it to be fixed?

Thanks,
Lukasz

**Comment by slewis74** [comment]
We've talked about this among the team and it seems that the updated behavior in the newer version of WebDeploy actually removes the need to use the expression this way. It was documented as a way of stopping ComponentA from removing the files for ComponentB during deployment. The updated WebDeploy only acts on the files under ComponentA's folder now anyway, so you should just have to list the `//component` folder on your root level project deployment to stop it removing any of the components.
