### ISSUE TITLE
Action editor sometimes doesn't display properties

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3392]
There is a race condition in `project_process_step_edit_controller.js` re how `action` and `actionTemplate` are retrieved.

Started by: https://secure.helpscout.net/conversation/345980696

**Comment by pawelpabich** [comment]
Release Note: Action editor now always display properties correctly

**Comment by danielfischeroctopus** [comment]
Another source: https://secure.helpscout.net/conversation/347810233/14749/?folderId=845288
