### ISSUE TITLE
Be more explicit on the test permissions page

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3402]
We could be a bit more explicit on the test permissions page. Currently the following is displayed:

The user has the following Permissions:
Permission | Project Groups | Projects | Environments

Perhaps a change to be more explicit here could be something like 

John's permissions are restricted to:
Permission | Project Groups | Projects | Environments

A small change to the heading could solve a bit of confusion.

Source: http://help.octopusdeploy.com/discussions/problems/53303

**Comment by pawelpabich** [comment]
Release Note: Improved description of the permissions table on the permission test page
