### ISSUE TITLE
Subscription to machine events don't get logged when scoped to environments

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3405]
When you have a subscription to a machine event scoped to an environment, nothing is logged, and no notifications are sent when this event occurs. The query doesn't find anything. This is a limitation with machine events - in the events table, machine events don't refer to their environment or project in their respective columns. That's because machines can belong to multiple, so this information isn't logged.

This limitation should be made more obvious in the subscription settings, as it leads to confusion when events don't get logged, and subscriptions don't send notifications because of this. A suggestion would be to add to this information in the event filters section of the subscription.

![machine_event_scoped_to_environment](https://cloud.githubusercontent.com/assets/20388190/24941908/11450ba0-1f91-11e7-9fd0-cd25541df197.png)

The workaround is to not use any environment or project filters in your subscription if subscribed to machine events.

Source: http://help.octopusdeploy.com/discussions/problems/52729

**Comment by thebigmoosey** [comment]
We have added hints in the UI to explain why this occurs and why you can't join events and environment filters like this. This was released in version `3.12.5`
