### ISSUE TITLE
User scoped only to empty project groups can't add projects

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3423]
When a user has permissions only for project groups that are empty, the `Add project` button is missing. There's also no `Show empty groups` option.

To reproduce, give a new user permissions to create projects, and scope them only to empty project groups.

![empty_project_group_1](https://cloud.githubusercontent.com/assets/20388190/25209580/6ef526ac-25bf-11e7-9bdb-746c153706a4.png)

When the user logs in, the Projects page shows:

![empty_project_group_2](https://cloud.githubusercontent.com/assets/20388190/25209584/74f24166-25bf-11e7-8eea-c1c6baee5420.png)

Workarounds:
- Have another user add a project in the group. That allows the original user to then see the group, and can then create new projects, or edit the existing one.

![empty_project_group_workaround](https://cloud.githubusercontent.com/assets/20388190/25209558/449ed6dc-25bf-11e7-85f6-65575372c14f.png)

- If the user has permissions to multiple groups, only one group has to have a project in it for the original user to see all their groups in the _Projects_ page, and selecting _Show empty groups_. They can then add projects to either.

![empty_project_group_workaround_2](https://cloud.githubusercontent.com/assets/20388190/25209552/3dea84f8-25bf-11e7-86d7-7a7997175c72.png)

Source: http://help.octopusdeploy.com/discussions/problems/53736

**Comment by droyad** [comment]
Release Note: Users can now create projects if they are only members of empty project groups
