### ISSUE TITLE
SelectedPackage.StepName should be ActionName

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3424]
Report (private) https://secure.helpscout.net/conversation/351649166/14920/?folderId=845296

`SelectedPackage.StepName` should be named `ActionName` as it refers to the name of the `DeploymentAction`, not the  `StepName` (since child steps were introduced). For steps that don't have child steps, the step name and the action name are the same.

**Option A**
For compatibility we should still `StepName` and also return both `ActionName` and `StepName` in our responses. Consider also changing changing the DB entity `PackageStepVersion`

**Option B**
Detect that the user has used the step name instead of a child name and return a descriptive error

**Comment by droyad** [comment]
Whichever solution, the documentation at https://github.com/OctopusDeploy/OctopusDeploy-Api/wiki/Releases should be updated

**Comment by droyad** [comment]
v4.0?

**Comment by alfhenrik** [comment]
Release notes: `StepName` property in `Release.SelectedPackages` have been deprecated in favor of the new `ActionName` property
