### ISSUE TITLE
GetOctopusCertificate no longer exists on CertificateRepository

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3427]
The `CertificateConfiguration` API has been remove, breaking compatibility with existing scripts, Clients and OctoPosh.

**Comment by michaelnoonan** [comment]
Private conversation about this here: https://octopusdeploy.slack.com/archives/C27FNL3QW/p1492728613735819

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GetOctopusCertificate no longer exists on CertificateRepository](https://trello.com/c/ZXELW9vw/340-getoctopuscertificate-no-longer-exists-on-certificaterepository)

**Comment by MJRichardson** [comment]
The `GetOctopusCertificate()` method was added back to the `CertificateRepository` in Octopus.Client version 4.13.15.
