### ISSUE TITLE
Make it easier to cascade delete Tenant Tags which are still being used

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3436]
# Problem

Deleting a tenant tag requires you to manually remove all uses of that tenant tag in:

- Tenants tagged with the tag
- Both current and snapshotted Deployment Processes where actions are scoped to the tag
- Both current and snapshotted Variable Sets where variables are scoped to the tag
- Machines which are allocated to Tenants by the tag
- Dashboard configuration

Generally we don't expect tags to change very often, so we took a pessimistic approach to deleting tags: veto the delete unless all references have been removed and it's totally safe to delete.

In most cases this is OK, until you consider Deployment Process and Variable Set snapshots: these live, hidden and locked in the database, until all the releases referring to those snapshots are deleted.

In [the case described here](http://help.octopusdeploy.com/discussions/questions/11350), it makes sense to use a Library Variable Set, shared amongst several projects: but that might render certain tags as "undeletable" according to Octopus, even though the customer is 100% certain they want to delete the tag and are aware of the consequences of doing so.

# Proposed Solution

We should detect usage of the tag to be deleted and prompt the user to confirm they are happy with Octopus to go ahead and cascade delete all references to the tag.

## Safely cascade deleting a tag

We have to be very careful to minimise the side-effects when cascade deleting tags since in most cases this will affect Deployment Action and Variable Scopes. We should consider logic similar to when we cascade delete an Environment from scopes:

1. If deleting the tag would result in a narrowing of scope, just remove the tag
2. If deleting the tag would result in a widening of scope, we need to decide whether the best course of action is to delete the entire Action/Variable so it doesn't unintentionally leak, or to veto the operation???

Source: http://help.octopusdeploy.com/discussions/questions/11350

**Comment by matt-richardson** [comment]
Another report: http://help.octopusdeploy.com/discussions/problems/54395

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it easier to cascade delete Tenant Tags which are still being used](https://trello.com/c/oqEeBepO/701-make-it-easier-to-cascade-delete-tenant-tags-which-are-still-being-used)

**Comment by pawelpabich** [comment]
Another report: https://help.octopusdeploy.com/discussions/problems/59919

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it easier to cascade delete Tenant Tags which are still being used](https://trello.com/c/jSNwVR1b/734-make-it-easier-to-cascade-delete-tenant-tags-which-are-still-being-used)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it easier to deploy to all tenants in an environment](https://trello.com/c/QkHGk5cV/744-make-it-easier-to-deploy-to-all-tenants-in-an-environment)

**Comment by patnolan** [comment]
Hi,

I have a tenant Tag which I am unable to delete. I have deleted all Variable Sets, Releases, Tenants and Projects so there is absolutely nothing left for it to be associated with and I still cannot delete.

I'm looking forward to testing the solution produced as part of this issue.

**Comment by bhardister** [comment]
I had a similar problem: https://help.octopusdeploy.com/discussions/problems/63241-cannot-delete-tenant-tag-set

**Comment by danielfischeroctopus** [comment]
Another Source. https://secure.helpscout.net/conversation/482470015/21898?folderId=845288 (Internal Link)

**Comment by spuder** [comment]
I am also unable to delete a tenant tag set. I've removed all variable sets, releases, deployments. There is nothing left to remove, yet I'm still getting error `A tag you have attempted to remove is in use in: Variable sets.`

**Comment by OctopusBob** [comment]
Another report: https://secure.helpscout.net/conversation/730224154/36707?folderId=557077

**Comment by dgard1981** [comment]
I wonder if this issue will be tackled any time soon? I've only been using tenant tags for a few days and having run in to this issue I'm not sure I would recommend them as it's a poor user experience. IMHO it shouldn't take a support ticket to be able to delete a resource that you created.

Please tackle this issue, it would make users happier :)

**Comment by octokhor** [comment]
Based on tenants research, we have identified this as something to tackle next year (e.g. we will make it easier to surface tenant tags so that it's easier to delete). For now, this issue will be closed and a new ticket will be issued when we are ready to tackle this particular bit of tenancy.

**Comment by dgard1981** [comment]
@octokhor, is closing this issue the right thing to do? In my experience, when an issue is closed so that a new one can be created in the future, it inevitably gets forgotten about.

**Comment by octokhor** [comment]
Hi @dgard1981 - thanks for your message and hope you're having a good one so far! The above issue has been captured internally in another doc and we will be working on solving this problem the next year! In the meantime, the issue is closed as it's not something we'll work on over the next few months. 

Don't worry, we won't be forgetting it anytime soon and we hope to get started on some of these issues in the near future. If this is something you'd still like to be kept open or to hear more about our plans, please feel free to reach out to me on Community Slack as well. Thanks!
