### ISSUE TITLE
Case sensitive database collation will consider package ids with the same name but different casing to be different packages

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3437]
Packages ids are considered case insensitive.  We lookup packages from SQL based on the package id.  If SQL collation is case sensitive we will exactly match the case of the package id we are searching for, which will not return results that have a different case.

eg: For packages with ids `test` and `Test`, a search for `test` will only return packages with the id `test`. It should return both `test` and `Test`.

**Comment by droyad** [comment]
Should we check for case sensitive collation at startup instead?

**Comment by tothegills** [comment]
Replaced by https://github.com/OctopusDeploy/Issues/issues/3623
