### ISSUE TITLE
OCTOPUS - Reset password for non-admin user using scripts

### ISSUE THREAD

**Issue by SANTHIYAM** [OctopusDeploy/Issues#3439]
hi,
 I want to change password for a non-admin user using scripts.Can you please help me to resolve this.Or Is there any way to do it?

**Comment by vanessalove** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
