### ISSUE TITLE
OctoPack does not find namespaced GitVersion

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3443]
OctoPack will not use GitVersion if if it namespaced in `AssemblyInfo.cs`:

```
namespace GitVersionNamespace
{
    static class GitVersionInformation
    {
        public static string NuGetVersion = "1.4.0";
    }
}
```

See http://help.octopusdeploy.com/discussions/problems/53931-bug-in-assemblyextensions-cannot-gettypegitversioninformation

**Comment by droyad** [comment]
Fixed by https://github.com/OctopusDeploy/OctoPack/commit/d5d025f643e3efe249d1fba22118f930dfe6c733
