### ISSUE TITLE
Add Subscription event for Auto Release Creation failures/errors

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#3446]
If Auto Release Creation (ARC) fails to create a release, it would be very handy to be able to receive a notification via a subscription.  To achieve this, we need to add a new event type. Make sure auto deploy is handled in the same way.

Source:
http://help.octopusdeploy.com/discussions/questions/11463

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Subscription for "No release created"?](https://trello.com/c/zOMxVWA6/511-subscription-for-no-release-created)

**Comment by pawelpabich** [comment]
This should not go out in a patch release.

**Comment by droyad** [comment]
Should also cover scheduled triggers.
Perhaps also add an event and subscription when release promotion fails?

**Comment by zentron** [comment]
Closing ticket unless raised again by customer
