### ISSUE TITLE
"Move into..." is breaking the rules around supported child step types

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3449]
You can now move whatever step you want into a rolling deployment step with the new "Move into..." editing dropdown (including unsupported child step types).

### Deployment name calculations
After discussing within the team (see internal Slack _help-me_ chat ~ April 27: 11:20am), there is a valid use case for having Azure steps as child steps, HOWEVER this is currently broken because you end up with the same "Deployment name" if you have multiple Azure steps in the same rolling deployment, when you would expect these to be unique. For an example, see [this customer's support issue](https://secure.helpscout.net/conversation/354902378?folderId=801354).

### UI validation inconsistencies
If Azure step types can be child steps (seems like it should be valid), we should allow those steps to be added as child steps. Currently the only way to get this working is to use the "Move into..." dropdown.

### Documentation inconsistencies
Our [documentation on rolling deployments](https://octopus.com/docs/patterns/rolling-deployments) states that only certain steps are allowed to be child steps. If we choose to support Azure steps as children, they should be mentioned here also.

### Server side validation
Whatever solution we decide on, we should have server-side validation in place to stop unsupported child steps from being saved in the deployment process (when things slip through the UI validation). If Azure steps are allowed, then they should be let through both in the client-side validation and have server-side validation to check that they're allowed.

Source: https://secure.helpscout.net/conversation/354902378?folderId=801354

**Comment by robpearson** [comment]
Release note: Only child steps can be moved into rolling deployments.  Azure Resource Group steps can now be child steps as well.
