### ISSUE TITLE
Physical Path is hidden in IIS Step after upgrade

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3460]
To reproduce, setup a IIS deployment step with `3.12.3` or earlier and set the Physical Path. Upgrade the server to `3.12.4` or later. The UI indicates that a physical path is not used, but the path is revealed when the second radio is selected. At deployment time the physical path is used.

![physical path](https://cloud.githubusercontent.com/assets/1687639/25599535/35579c80-2f20-11e7-9b50-d764080ed701.gif)

Result of the #3253 change

**Comment by robpearson** [comment]
Release Note: IIS Website Step no longer hides Physical Path after upgrading
