### ISSUE TITLE
Run on Failure steps do not show in overview

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3461]
Create a deployment with the following:
1) A script that exits with an error code
2) A script that runs if the previous failed.

Create a release and deploy. When the deployment has completed, the summary tab only shows the first step. However the second step ran, and is in the Task log.

**Comment by MichaelJCompton** [comment]
This could be related.

With a deployment that has:

1) A failing step
2) A step (with child steps) that only runs if step 1 failed

Then (as well as step 2 not showing in the summary) the task log in the UI doesn't update until all child steps are complete.  See also (private) https://help.octopusdeploy.com/discussions/questions/13695

**Comment by alfhenrik** [comment]
Release notes: `Run on Failure` steps now show on the task summary tab if it is executed
