### ISSUE TITLE
Add ability to select severity level for specific log messages

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3462]
Originally from https://github.com/OctopusDeploy/Issues/issues/2380

The problem:
We used to have yellow icons when a deployment was successful but had warnings.
When it was changed to the green icon with the warning, we had a decrease in support requests. The reason being that customers were more interested in how to suppress warnings and have a green dashboard than actually getting rid of warnings or they had warnings they couldn't get rid of. But now we also agree that if you don't usually have warnings you want to know right away.

The solution:
Provide the ability to reduce the severity of specific warnings in logs.  For example: if the warning "This is a suppressed warning" shows up in the log we can choose that any occurrences of that warning will not cause 
a yellow warning icon for the deployment.

**Comment by droyad** [comment]
While this would be nice to have, we are not hearing a great demand for it recently. The implementation would also be tricky to cover all possible messages, so we are closing this for now. Comment below if you feel we really should do it.
