### ISSUE TITLE
No record in ActionVersionTemplate for community steps

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#3463]
We aren't adding a record to the ActionVersionTemplate table for community steps which breaks the UI around updating when the community step updates.

First reported: http://help.octopusdeploy.com/discussions/problems/54151 (private discussion)

To reproduce the UI issue shown in the ticket above, add the File System - Grant Permissions community step and fill out the four values. Then in the DeploymentProcess.Json field in the DB change the Items field to Item and Octopus.Action.Template.Version to 3.

**Comment by pawelpabich** [comment]
Release Note: Existing action data is displayed correctly and community step updates are versioned now.
