### ISSUE TITLE
Use a more recent version of NuGet for OCTONUGET

### ISSUE THREAD

**Issue by jez9999** [OctopusDeploy/Issues#3472]
I have a version string for my NuGet packages I want to use which is longer than 20 characters.  NuGet recently removed the annoying 20 character restriction in NuGet:

https://github.com/NuGet/Home/issues/2735

Could someone advise me what version of NuGet OCTONUGET is currently using, and could it be upgraded to use the most recent version to lift this restriction?

**Comment by droyad** [comment]
I successfully created a package with a pre-release string of 40 characters with `octo.exe` and deployed it using the built in feed. If there is a limitation on OctoPack, we don't plan on fixing it as that is no longer used with .NET Core.
