### ISSUE TITLE
Calamari Azure duplicate deployment names

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3473]
There is a bug in Calamari that is causing duplicate random strings for Azure deployment names. Eg. If you trigger two deployments at ~ the same time, the `AesEncryption.RandomString` method can return the same deployment name for both deployments.

Example of what deployment name this is referring to. If you run an ARM deployment, see the logs here:
```
10:49:22   Info     |       Deploying Resource Group markse-as1 in subscription 95bf77d2-64b1-4ed2-9de1-b5451e3881f5.
10:49:22   Info     |       Deployment name: arm-test-x4ep96
10:49:22   Info     |       Deployment mode: Incremental

```

NOTE: We had this same bug in Octopus and `RandomStringGenerator` late last year, so presumably the same fix (locking) will need to be applied here.

To work around this issue, customers are adding delays between deployments to try and ensure they get unique deployments names (see source issue below).

Source: https://secure.helpscout.net/conversation/354902378/15173/?folderId=801354

Related to https://github.com/OctopusDeploy/Issues/issues/3449 (and possibly the fix for this may help fix some of the problems mentioned here)

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Move into..." is breaking the rules around supported child step types](https://trello.com/c/O7YSNIQA/528-move-into-is-breaking-the-rules-around-supported-child-step-types)

**Comment by robpearson** [comment]
Release Note: Azure Resource Group deployments now generate unique deployment names
