### ISSUE TITLE
Audit screen document type filtering

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3488]
There is no way to filter the audit screen if I just want to see events for a given document type.

Eg. If I change either my library variable sets or some project variables and I just want to search the audit screen for "Variable" related changes, I want to be able to easily filter and see these events:

![variable-events](https://cloud.githubusercontent.com/assets/819605/25930369/2ed87e6c-3649-11e7-853f-16bb6f6bc74a.png)

This same scenario could be applied to any of our document types though.

These events are currently captured with our generic `Created` / `Modified` events, so they show up on our audit screen, but you can't filter by them.

## Potential Solution
Our `Event` table includes a `RelatedDocumentIds` column that we could potentially search on without having to add a new column to the event table (to be avoided if possible).

We could add another filter dropdown to the event filter dialog that lets you search by _any_ of our document types. ie. As we add more document types in the future, they should automatically be included in the list of potential types, so this would involve several changes:

- a new endpoint `/api/events/documentTypes`on the events API to return document types (similar to how `/api/events/eventCategories` works) ... where it returns a list of classes that conform to `IDocument` in our `Octopus.Core.Model` namespace (see our `DocumentMapIdColumnsFixture` for an example of something similar)
- call that endpoint from the client and populate a filter dropdown with the available document types
- modify the `ListEventsResponder` to accept a `relatedDocumentType` parameter and filter event result from that \*

\* Be careful in the `ListEventsResponder.QueryEventsAndApplyFilters` method as this is used in several places (by auto-deploy and subscriptions). Any changes here will need to be matched in the OctopusClient library @ `IEventRepository` also so people can use this new argument using the OctopusClient (there are .

Source: http://help.octopusdeploy.com/discussions/questions/11636

**Comment by matt-richardson** [comment]
I was thinking about this a few weeks ago, and I'd come to the solution of stopping using the generic `DocumentCreated` type events, and use entity specific events (eg `VariableSetCreated`) instead.

It would be hefty migration script to modify the existing events table, and definitely not backwards compatible, so would be minor release at least, potentially even major release.

We'd also have to consider what happens with subscriptions that refer to the `Document*` event types.

comment from @thebigmoosey:
> not sure how far-reaching the consequences are for replacing the current generic `Created` / `Modified` and `Deleted` categories, eg. if they’re used for other purposes … but worth a few hours of investigation to see if it’d be an easy transition

**Comment by thebigmoosey** [comment]
This was mostly a duplicate of OctopusDeploy/Issues#1090, closing now

**Comment by dijitali** [comment]
@thebigmoosey - are you sure this is a duplicate of #1090?

That seems to be quite a different topic relating to running bash scripts, whereas this issue relates to seeing variable changes in the audit log?

**Comment by thebigmoosey** [comment]
@dijitali Sorry, this meant to reference OctopusDeploy/Issues#1098, updating original comment now.

**Comment by dijitali** [comment]
Sorry to be a pain, but did you definitely mean #1098?  I think that one's about an error with the reset machine connection feature.

**Comment by thebigmoosey** [comment]
@dijitali Ahh sorry. I got my pull request and issue numbers mixed up :( I meant OctopusDeploy/Issues#3401 (which had a PR number of 1098)
