### ISSUE TITLE
Adding cleanup parameters to Octopack

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3489]
Source: http://help.octopusdeploy.com/discussions/questions/11593

When Octopack creates a package, it drops it into 3 locations:

A) `\obj\octopacked` which is the working directory before it gets copied to ⬇️ .
B) `\bin\debug-release`.
C) The feed/folder where it was pushed.

While its not hard to script the package cleanup, It'll be better if Octopack provided a way of doing this out of the box for (A) and (B). Since there's probably more than a few users relying on the packages in those paths, this would have to be introduced as an opt-in MSBuild parameter that, by default, doesn't delete any packages.

`/p:CleanOctopackWorkingDir` or `/p:CleanLocalPackageAfterPush` sound good to me.

**Comment by slewis74** [comment]
Closing as we have no plans to make any further changes to OctoPack.
