### ISSUE TITLE
TFS plugin - CORS error loading octopus

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3491]
Source: https://secure.helpscout.net/conversation/361239768?folderId=969747

The [OctoTFS](https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks) allows you to click through to the specific deployment shown. It uses `target="blank"` to open in a new window.

Unfortunately, this triggers CORS protection, as `origin` is `null` when `target="_blank"` is used.

See https://webmasters.stackexchange.com/questions/85793/xsrf-error-when-link-is-opened-via-an-a-tag-with-target-attribute-set-to-bla.

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TFS 2017 Widget](https://trello.com/c/vmwoYoLF/411-tfs-2017-widget)
