### ISSUE TITLE
Improve "Deploy an IIS Web Site" description

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3496]
The description of the step doesn't indicate that the step supports Virtual Directories and Web Applications. Because of that our users use IIS Community Step Templates which is unnecessary friction as there is already a builtin step that does what they need. 

Should we change the name and the description?
Should we change only the description?

**Current Name**: "Deploy an IIS Web Site"
**Current description**: "Deploy the contents of a package and configure an IIS Website"

**Make sure the name change doesn't break anything and update docs**

**Comment by alfhenrik** [comment]
:+1: for updating the description

**Comment by Dalmirog** [comment]
👍 for changing both.

**New Name**: "Deploy to IIS" or "IIS Deployment"
**New subject**: Deploy the contents of a package to an IIS Website, Web App or Virtual Directory"

**Comment by davidkeaveny** [comment]
@Dalmirog 's suggestion works for me.

**Comment by pawelpabich** [comment]
Release Note: We now explicitly mentioned that IIS step support Websites, Web Applications and Virtual Directories
