### ISSUE TITLE
Support non-classic storage accounts to Azure Cloud Service step

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#3503]
We load classic storage accounts in the Azure Cloud Service step, but Azure recently added support for non-classic storage accounts as well. Update the step so we can handle them.

Raised: https://secure.helpscout.net/conversation/366485441?folderId=557077 (internal link)

**Comment by robpearson** [comment]
Small update:  We're waiting for more information from Microsoft's Azure team as this may not be possible.  Will update here when we learn more.

**Comment by jlaari** [comment]
Any update?

**Comment by droyad** [comment]
Closing as it seems not to be possible outside of the portal
