### ISSUE TITLE
Deployed releases not showing as deployed after release is deleted

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3510]
After you delete the most recent release that has been deployed, that release version isn't being displayed as the most recent. Since deleting the release doesn't delete what was deployed, it's incorrect to display the first release as what's deployed to the environment.

After deploying two releases:
![deployed_releases_1](https://cloud.githubusercontent.com/assets/20388190/26232946/18a81562-3c9d-11e7-8065-3d06eddd0460.png)

After deleting second release (1.1.0):
![deployed_releases_2](https://cloud.githubusercontent.com/assets/20388190/26232949/1cb35b4e-3c9d-11e7-9927-98f1d0a681f4.png)

Steps to reproduce
1) Create first release and deploy it
2) Create second release and deploy it
3) Delete the second release

Source: http://help.octopusdeploy.com/discussions/questions/11733

**Comment by pawelpabich** [comment]
Mention dashboard in the error message when a release is deleted.

**Comment by pawelpabich** [comment]
This is by design but we will try to communicate it better to the end user

**Comment by pawelpabich** [comment]
Release Note: We now explicitly tell the user that release deletion will remove deployments from all dashboards

**Comment by justmara** [comment]
How will this change that fact, that dashboard shows incorrect information after release deletion?
Dashboard`s main purpose is to show environment`s current state. And after release deletion dashboard is in 'broken' state, because it shows incorrect information.

**Comment by pawelpabich** [comment]
Hi @justmara,

I understand that this behaviour is not what you expected. That being said this is how Octopus works internally. When something is deleted permanently, and this is why we warn users twice about it, it disappears entirely.  If you believe we should adjust this behaviour then please submit a [UV suggestion](https://octopusdeploy.uservoice.com/).
