### ISSUE TITLE
IIS Features does not validate that there is at least one binding

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3512]
The UI/API allows a step with the IIS Feature to be saved even if no IIS Bindings are specified. This then causes the following error at deployment time ([report](https://secure.helpscout.net/conversation/367940567?folderId=845296):

```
foreach-object : You cannot call a method on a null-valued expression.
```

A website can't be created in IIS without any bindings. However since we create it with a temporary binding and then replace it with the correct ones, we could use `Clear-ItemProperty` ([reference](https://technet.microsoft.com/en-us/library/ee909471(v=ws.10).aspx)) to set none. However I think we shouldn't support that scenario, as missing bindings are usually a mistake.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IIS Features does not validate that there is at least one binding](https://trello.com/c/xONfKSLz/668-iis-features-does-not-validate-that-there-is-at-least-one-binding)

**Comment by NickJosevski** [comment]
The value was `[]` so it did exist

![image](https://user-images.githubusercontent.com/119096/28348755-fdfb3c66-6c81-11e7-8be7-8594d3eaa689.png)

**Comment by NickJosevski** [comment]
now it will show this client side after the save

![image](https://user-images.githubusercontent.com/119096/28348780-314c4006-6c82-11e7-852d-646ee2b7734f.png)

**Comment by NickJosevski** [comment]
Release Note: validation checks for at least 1 binding on IIS related features on deployments

**Comment by NickJosevski** [comment]
Release Note: validation on required bindings for IIS related deployment steps
