### ISSUE TITLE
Start-Service is treating [ as a special character and unable to start service

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#3515]
On the start service line, it'll error in Octopus, because it fails to start, see [this ticket raised by customer](http://help.octopusdeploy.com/discussions/problems/54595-special-chars-in-service-name)

```
Write-Host "Starting the $serviceName service"
Start-Service $ServiceName
```
https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Scripts/Octopus.Features.WindowsService_BeforePostDeploy.ps1#L163

Here are raw log output of it failing to start service `[T3]asdfasdfasdf` - [ServerTasks-4491.log.txt](https://github.com/OctopusDeploy/Issues/files/1017623/ServerTasks-4491.log.txt)

Trying to make use of `[Regex]::Escape($ServiceName)` doesn't help, it injects backslashes and it produces 

```
[Regex]::Escape("[T3]asdfasdfasdf")
\[T3]asdfasdfasdf
```

In PowerShell by hand the only success I had starting the service was using the back tick:

     Start-Service '`[T3]asdfasdfasdf' 

I couldn't find consistent info/answers for how to properly escape and what, but see [this](http://stackoverflow.com/questions/527772/how-to-ignore-escape-sequences-stored-in-powershell-string-variable) and more info on `regex::escape` [here](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.escape%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) lists the following: `\, *, +, ?, |, {, [, (,), ^, $,., #, and white space`

**Comment by NickJosevski** [comment]
Here's a nuget package that contains a service call echosvc.exe (had to zip it to upload here)
[service.2017.5.22.121522.nupkg.zip](https://github.com/OctopusDeploy/Issues/files/1017636/service.2017.5.22.121522.nupkg.zip)

**Comment by johnsimons** [comment]
Release Note: Start-Service is treating [ as a special character and unable to start service
