### ISSUE TITLE
Disable user fields that will be overwritten by AD data

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#3518]
When a customer is using AD we overwrite most user fields with data from AD, however we still allow users to change their Display Name etc.

We should disable these fields and display a note on the screen that the data is drawn from AD.

Reported here: http://help.octopusdeploy.com/discussions/problems/54683-display-name-in-profile-changes-back-after-logout

**Comment by pawelpabich** [comment]
Fix in OD v4 as part of ODCM. Idea: multiple identities per user.

**Comment by droyad** [comment]
@slewis74 should I mark this as done in `3.17.2`?

**Comment by slewis74** [comment]
Yes, each Login now has it's own Display Name that gets updated independently of the user's Display Name.
