### ISSUE TITLE
Variable scoping error on project import

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#3521]
When a user saves a project variables, we check that the list of possible environment scopes provided in the save call's JSON blob, contains all environments that variables are currently (before the save) scoped to. This seems to be a check around a user having their permissions changed between loading the the data and saving it?

When Octo.exe does a project import, the variable update only supplies environments that are used as scopes in the updated values (not all possible environments). This means if the update doesn't use every environment for a scope that was previously used, it fails the above check.

Options: do we even need that env check? Need to investigate what it is trying to achieve. If it is needed, we need to make Octo.exe send back the list of environments that was loaded when doing the update, the same way the UI works.

Reported here: http://help.octopusdeploy.com/discussions/problems/54706 (private link)

**Comment by matt-richardson** [comment]
I _think_ that the intent was to handle the situation where a variable was scoped to environment `X`, `Y` & `Z`, but the user only has permission to view `X` & `Y`. We were silently dropping `Z` from the scoping when they were editing it.
