### ISSUE TITLE
Improve logging around retention policies for releases using #{} variables for packages

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3525]
If a project ever had a release using a `#{}` variable for a package ID, as long as that release exists (no matter how old), retention policies for that project wont work and the following will be printed in the logs:

```
[PackageID].[PackageVersion] was published on 20/03/2017 13:40:15 +00:00. It will be kept because the project [ProjectName] uses #{...} references in the package ID field and has deployed a package with this id before.
```

Currently we ask users to run the below query to figure out which releases are blocking the retention policies and then manually delete them:

```sql
SELECT [Project_Name], [Release_Version], [Release_Assembled], [Release_ProjectId]
  FROM [OctopusDeploy-master].[dbo].[Release_WithDeploymentProcess]
  WHERE DEploymentProcess_JSON LIKE '%PackageId":"#{%';
```

Instead of making them run this query, we could improve the log message for the retention policy to print which release number in that project is causing this. i.e:
```
[PackageID].[PackageVersion] was published on 20/03/2017 13:40:15 +00:00. It will be kept because the release [ReleaseNumber] of the project [ProjectName] uses #{...} references in the package ID field and has deployed a package with this id before.
```

This way It'll be much easier to point users to the release that must be deleted to correct this situation.

Sources:
- http://help.octopusdeploy.com/discussions/questions/11236
- http://help.octopusdeploy.com/discussions/problems/54698

**Comment by Dalmirog** [comment]
Discussed this with @tothegills before submitting the issue

**Comment by droyad** [comment]
We have since improved the logging in this area
