### ISSUE TITLE
Deploy Azure Cloud Services via ARM

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3526]
At the moment our cloud service step will deploy via the classic deployment model.  It looks like Microsoft now supports cloud services via the ARM model: https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-how-to-create-deploy-portal

Refer to: http://help.octopusdeploy.com/discussions/problems/54750

**Comment by slewis74** [comment]
See also, https://github.com/OctopusDeploy/Issues/issues/3503

**Comment by tothegills** [comment]
@robpearson has graciously volunteered to complete both related tickets

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support non-classic storage accounts to Azure Cloud Service step](https://trello.com/c/bPoLI7wu/582-support-non-classic-storage-accounts-to-azure-cloud-service-step)

**Comment by robpearson** [comment]
Small update:  We're waiting for more information from Microsoft's Azure team as this may not be possible outside of the portal.  Will update here when we learn more.

**Comment by droyad** [comment]
Closing as it seems not to be possible outside of the portal
