### ISSUE TITLE
Ensure new-certificate can work without a profile, or document how to load profiles

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#353]
Issue:

http://help.octopusdeploy.com/discussions/problems/13114-tentacle-new-certificate-throwing-unauthorisedaccessexception

Can we try and reproduce this, and then:

 1) Look at fixing our certificate generation so that the whole thing _just works_, or
 2) At least document how to force the profile to be loaded so that it can work

**Comment by mwrock** [comment]
I just ran into this trying to provision a tentacle via chef. We perform the initial provisioning run over winrm which has all the same restrictions as powershell remoting. @erichexter's approach is unfortunately the only approach likely to work here. I had success installing via boxstarter.org which basically does just that. It would be great if there was another way of generating the cert without needing the local user token. Scheduled tasks are such a pain. Funny, I just wrote a blog last week on this exact topic: http://www.hurryupandwait.io/blog/safely-running-windows-automation-operations-that-typically-fail-over-winrm-or-powershell-remoting

**Comment by erichexter** [comment]
I agree this approach sucks. But it has been reliable, we have scripted
200+ installs in azure and it works.

On Tuesday, January 27, 2015, Matt Wrock <notifications@github.com> wrote:

> I just ran into this trying to provision a tentacle via chef. We perform
> the initial provisioning run over winrm which has all the same restrictions
> as powershell remoting. @erichexter <https://github.com/erichexter>'s
> approach is unfortunately the only approach likely to work here. I had
> success installing via boxstarter.org which basically does just that. It
> would be great if there was another way of generating the cert without
> needing the local user token. Scheduled tasks are such a pain. Funny, I
> just wrote a blog last week on this exact topic:
> http://www.hurryupandwait.io/blog/safely-running-windows-automation-operations-that-typically-fail-over-winrm-or-powershell-remoting
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OctopusDeploy/Issues/issues/353#issuecomment-71721846>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by Tazer** [comment]
Has there been any updates to this ? Or the only solution is to run the install as a scheduled task ? @PaulStovell @erichexter

**Comment by erichexter** [comment]
There is a new export and import commands on the tentacle exe

On Saturday, September 26, 2015, Patrik <notifications@github.com> wrote:

> Has there been any updates to this ? Or the only solution is to run the
> install as a scheduled task ? @PaulStovell
> <https://github.com/PaulStovell> @erichexter
> <https://github.com/erichexter>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OctopusDeploy/Issues/issues/353#issuecomment-143467896>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by Tazer** [comment]
Thanks, that lead me to : http://docs.octopusdeploy.com/display/OD/Export+and+import+Tentacle+certificates+without+a+profile

**Comment by erichexter** [comment]
@mwrock  do you have a  confirmed way to configure via chef ?

**Comment by mwrock** [comment]
Unfortunately I don't have access to those recipes anymore @erichexter . I do remember we had to have the recipe create a scheduled task which ran a script that did the install. We then polled the tentacle endpoint waiting or it to come online.

**Comment by DevOpsFu** [comment]
I wrote a [blog post](http://www.devopsfu.com/2017/07/16/terraform-destroy-provisioners-and-pre-staging-octopus-deploy-tentacle-certificates/) on how we got around this using OpenSSL to pre-stage certificates for importing.
