### ISSUE TITLE
Hamburger menu for Azure Service Fabric steps in a deployment process is broken

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#3537]
If you access the 🍔  menu for a Azure Service Fabric step, it goes into a loop of errors.

Steps to repro.
* Add a project
* Add a service fabric step w/ any data
* Click the 🍔  menu and the console log will flood the console w/ errors and prevent further user interaction

**Comment by robpearson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Azure Service Fabric step Hamburger Menu is broken](https://trello.com/c/aelOduQg/607-azure-service-fabric-step-hamburger-menu-is-broken)

**Comment by michaelnoonan** [comment]
Release Note: Fixed a JavaScript problem with the Azure Service Fabric step's hamburger menu
