### ISSUE TITLE
Tooltip wording is incorrect when describing time before task will be processed #1136

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#3541]
The wording here of "The Octopus Server will process this task a few seconds ago." is confusing in that it references something that **will** take place **a few seconds ago**.

The issue was originally raised in [HelpScout](https://secure.helpscout.net/conversation/373884242?folderId=557082).

![theoctopusserver-message](https://cloud.githubusercontent.com/assets/160104/26705645/c123ea9e-477a-11e7-8108-1587af8ee5d1.png)

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tooltip wording is incorrect when describing time before task will be processed](https://trello.com/c/zJI951aY/618-tooltip-wording-is-incorrect-when-describing-time-before-task-will-be-processed)

**Comment by pawelpabich** [comment]
The only way this can happen is when the client and server times are out of sync. Because all of our UI is done on the the client side there is no way we can work around this problem.
