### ISSUE TITLE
Service Fabric should automatically import the certificate

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3544]
For Service Fabric steps, the selected certificate is not automatically imported on the server when executing, and unless you read the documentation very carefully, it is not clear that you need to do this and is causing confusion to customers.

We already have the code in place to do this in other areas of Octopus. Eg. If you use an Octopus-managed cert in a IIS HTTPS binding, we automatically install it. So Service Fabric steps should follow this same pattern and automatically install the certificate to the `LocalMachine` store it expects.

Source: http://help.octopusdeploy.com/discussions/problems/54905

**Comment by HighwayofLife** [comment]
We're running into this issue as well, and we need to be able to manage the certificates through automation, but the current process doesn't seem to allow that. Any status on being able to use the certificate import on the octopus server? Currently it requires a target.

**Comment by tudorsibiu90** [comment]
I have also run into this issue. We badly need this to be solved. The Service Fabric Deploy step gives the impression that this should already be automated. :(

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service Fabric should automatically import the certificate](https://trello.com/c/tKgQrVnD/41-service-fabric-should-automatically-import-the-certificate)

**Comment by thebigmoosey** [comment]
Release Note: Automatically importing the Service Fabric certificate (for both steps and targets)
