### ISSUE TITLE
Tenant variable values screen should perform better with hundreds of projects

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3547]
# Problem

A customer with a tenant connected to ~140 projects is reporting this screen taking 2-3 minutes to load, and it is crashing/erroring sometimes. We load tested this with 50 projects each having 10 variables each - but now we have a real-life scenario we should cater for it much better than we do today.

# Suggested solution

I think we could change the UX so it does something like:

1. The screen only loads the project names, enough to populate a selector/filter/combo
2. Choose the project you are interested in and we load everything required at that point

This original ticket has good details for an investigation.

#Source 

Source: https://secure.helpscout.net/conversation/374591997?folderId=557080

**Comment by zentron** [comment]
Added a change so that rather than doing any fancy filter\pre search, we can just avoid loading project resource altogether. This works by including the only 1 other piece of information we really needed from the project, the logo link, and returning this in the tenant variables resource.

**Comment by zentron** [comment]
Release Note: Avoid requirement to load project information on tenant project variables screen
