### ISSUE TITLE
Put Tentacle on a separate release cadence to Server

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3548]
Urgent:
- [x] Update ReleaseBot to deploy Tentacle
- [x] Update ReleaseBot not to deploy Tentacle with Octopus
- [x] Migrate Deploy to Deploy3
- [x] Modify Octopus Server deploy so it doesnt deploy Tentacle
- [x] Update Tentacle Army so release verifications use latest Tentacle instead of specific version
- [ ] Create a release notes page in Octofront for Tentacle
- [x] Update Permanent Octopus so it uses an appropriate Tentacle
- [x] Dev Octopus setup scripts
- [x] Modify Octofront to give Tentacle its own version

Less urgent:
- [x] Fix the circular dependency between Tentacle and Server
- [ ] Provide a way to automatically update Tentacles when a new version is released

**Comment by tothegills** [comment]
Breaking the dependency:

- Splitting E2E tests into their own repo
- Splitting Octopus.Shared into its own repo
- Octopus depends on Tentacle (similar to how SSH works now)

**Comment by tothegills** [comment]
Check the Hydra build, it is expecting some outputted parameters.

**Comment by tothegills** [comment]
A new issue for automatic Tentacle updates: https://github.com/OctopusDeploy/Issues/issues/3774

**Comment by matt-richardson** [comment]
New issue for how octofront treats Tentacle as a child of Server - https://github.com/OctopusDeploy/Octofront/issues/278
