### ISSUE TITLE
JsonReaderException "Input string '' is not a valid number." when parsing task log in deployment

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3550]
The exception doesn't seem to be a fatal one, as the deployment succeeds.

Source: http://help.octopusdeploy.com/discussions/problems/55031

**Comment by droyad** [comment]
[Test Log Parsing.zip](https://github.com/OctopusDeploy/Issues/files/1126441/Test.Log.Parsing.zip)

Tried reproducing the issue with the attached script running in two processes, but no luck. Reviewed the log file and no idea why it would think that part of the file should be parsed as a number, even with a partial line write.

**Comment by droyad** [comment]
Version `3.17.3` includes some diagnostics code for this issue. When it is encountered, the log file with the problem is written to `Issue3550Log.txt` in the Server Log folder. 

If you encounter this, please send both that file and the log file as described in the error message via our support forums.

**Comment by thashepherd** [comment]
[servertasks-39122_v9j6z653db.txt](https://github.com/OctopusDeploy/Issues/files/1989163/servertasks-39122_v9j6z653db.txt)
[Issue3550Log.txt](https://github.com/OctopusDeploy/Issues/files/1989164/Issue3550Log.txt)

Hit this while running `2018.3.8`; there are 3 instances of this error in `Issue3550.Log` that happened on 02APR, 12APR, and 09MAY. 

I don't know that this prevented any deployments from going out - just flashed an error message for a few seconds.

**Comment by droyad** [comment]
@thashepherd Thanks for the report. It would not affect the deployment, just the display of the log.

Do you have Octopus setup in High Availability (HA, multiple Octopus Server servers)? Where are the task log files stored (Local disk, SAN, NAS, etc)?

**Comment by droyad** [comment]
No further reports. This seems to be a problem with the SAN or NAS.

**Comment by tothegills** [comment]
Related: https://secure.helpscout.net/conversation/670425808?folderId=557077

**Comment by OctopusBob** [comment]
Additional information from a customer using HA.  

They had a task where this failed.  The task was trying to grab this file:

"ActivityLogs": [
   {
     "Id": "ServerTasks-74877_NDDTQP5ZEZ"
   }
]

Make note of that token, which is "NDDTQP5ZEZ."  However, when we went to the file share where the logs were stored it couldn't find that file.  Instead, it found the file ServerTasks-74877_DCEMM6MP6Y.  

![image](https://user-images.githubusercontent.com/38642825/46696760-95b76a00-cbd8-11e8-95d1-7f575bf19e25.png)
