### ISSUE TITLE
Connect to tentacles/server via an HTTP proxy

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#357]
Because we use HTTPS for Octopus/Tentacle communication, we should in theory be able to get network access using an HTTP proxy.

There are a few bits to this:
1. We need to make requests using the HTTP/1.0 or 1.1 protocols instead of our OCTO/1.0 marker protocol
2. We need to configure Pipefish's SecureTcpClient with the proxy name/port
3. Instead of directly starting an SSL handshake, we need to send in the clear

```
CONNECT host:port HTTP/1.0


```

(Two newlines in there).
1. (4.) we need to read the response from the proxy before continuing with the connection (this bit needs some more investigation).

**Comment by gbrackley** [comment]
It the version 3.x tentacle still using this non-http protocol? I'm trying to get a polling tentacle in through a firewall (nginx reverse proxy). I have the certificates setup, but the protocol seems to barffing the 'MX' verbs.

**Comment by matt-richardson** [comment]
Hi @gbrackley, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
