### ISSUE TITLE
Unscoped variables deleted when user doesn't have VariableViewUnscoped permission

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3570]
When a user has the `VariableEditUnscoped` permission but not the `VariableViewUnscoped` permission, all unscoped variables get deleted when this user creates a new unscoped variable. (With the exception of the variable they just created.) Steps to reproduce -

1. Give a project an unscoped variable(s).

![unscopedvariables_1](https://user-images.githubusercontent.com/20388190/27269575-6b413a9e-54fb-11e7-9f08-00c228a151dd.png)

2. My new user adds an unscoped variable, without having the `VariableViewUnscoped` permission. Variable disappears after creating it as expected without `View` perm.

![unscopedvariables_2](https://user-images.githubusercontent.com/20388190/27269579-6e9c2aa0-54fb-11e7-9e7f-6e9383385b03.png)

3. Log back in with admin user. View variables in project to see them all (except for the new one) deleted.

![unscopedvariables_3](https://user-images.githubusercontent.com/20388190/27269584-72eb30b0-54fb-11e7-9ab4-6d3dc6edf220.png)

Giving this user's role the `VariableViewUnscoped` permission allows it to work properly.

Source: http://help.octopusdeploy.com/discussions/problems/55181

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unscoped variables deleted when user doesn't have VariableViewUnscoped permission](https://trello.com/c/XezDXHEe/645-unscoped-variables-deleted-when-user-doesnt-have-variableviewunscoped-permission)
