### ISSUE TITLE
Make it possible to run Octopus Server with lower database privileges

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3571]
At the moment people need to run Octopus Server and connect to the SQL Server database as a user who is at least a member of the `db_owner` role for that database. Now we've made it possible to run SQL Database schema upgrades from the command-line (and during installation) we can lower the requirements for running Octopus Server. :)

A nice goal would be to make Octopus Server only require `db_reader` and `db_writer` to reduce the potential of attack via a public Octopus Server.

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it possible to run Octopus Server with lower database privileges](https://trello.com/c/V2cvHW8x/513-make-it-possible-to-run-octopus-server-with-lower-database-privileges)

**Comment by distantcam** [comment]
It looks like the server needs ALTER and EXECUTE permissions as well as `db_reader` and `db_writer`. I'll make a script to add a db role that users can include to provide those permissions.

**Comment by droyad** [comment]
We are closing this for now as it seems to be more effort than it's worth. We haven't seen many customers asking for it. Comment below if you do want this done.
