### ISSUE TITLE
Library variable scope : Project ?

### ISSUE THREAD

**Issue by doubret** [OctopusDeploy/Issues#3573]
Hi,
I just looked to the api and found that i can add a library variable scope specification for projects.
But it looks like i can't find the same feature from the user interface.

Is this expected behaviour ? What's the recommandation about using library variables scoped to projects ?
Dy you discourage using this extensively ?

Thanks

**Comment by doubret** [comment]
Bump

**Comment by alfhenrik** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
