### ISSUE TITLE
Error selecting packages with duplicate case-insensitive step names

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3581]
- Octopus `3.14.1`.
- If the fix ends up being that we'll prevent steps from being named identical except for the casing, please rephrase the ticket's title
- Totally didn't discover this by absolute accident.

![createreleaseerror](https://user-images.githubusercontent.com/6180562/27400738-6ef290e6-5697-11e7-8e0f-fa5684eccb66.jpg)
.

**Comment by pawelpabich** [comment]
Fixed in #3713
