### ISSUE TITLE
OctopusUseGuidedFailure variable unable to be set at project level

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3588]
Enabling the guided failure variable in a project does not enable guided failure during deployments.

![guided_failure](https://user-images.githubusercontent.com/20388190/27468877-dbd64d26-582f-11e7-93f2-53f01b4d13f1.png)

Guided failure works when setting it on the environment. This might or might not use `OctopusUseGuidedFailure ` variable.

Source: https://secure.helpscout.net/conversation/385067261/16611/?folderId=954335 (private link)

Expected behaviour:
Guided failure should be enabled/disabled via `OctopusUseGuidedFailure`. Assuming this can be done and it make sense from code perspective.

**Comment by jdkang** [comment]
This is a slight pain point for us as this is a regression from previous versions. 

We have many environments and many projects, and setting the GF mode environment-wide makes "auto deploys" a bit more painful in certain cases -- as we'd prefer those to simply fail/rollback or simply fail.

**Comment by droyad** [comment]
This option was removed in `3.0`

**Comment by markryd** [comment]
I've created an issue to have this added as an explicit setting in Project Settings rather than a variable https://github.com/OctopusDeploy/OctopusDeploy/issues/1565 and I'm closing this up.
