### ISSUE TITLE
EnvironmentView permission dictates which environment-scoped variables in a set that a user can access

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3591]
When a team has the `EnvironmentView` permission scoped to multiple environments, they are able to view and edit variables in a variable set which are scoped to environments that `VariableView` and `VariableEdit` should allow for. Variable permissions scoped to a single environment should limit access to variables within a set to only those scoped to that single environment.

Scenario:
A user has the following permissions.

![variable_set_permissions](https://user-images.githubusercontent.com/20388190/27566227-263e26dc-5b27-11e7-9f8e-3037e8881e22.png)

The user can view and edit variables scoped to environments as determined by their `EnvironmentView` permissions. `VariableEdit` permission is only for Development environment, and they should only be able to edit variables within a set that are scoped to Development. Here's the result from the permissions.

![variable_set_environment_scope](https://user-images.githubusercontent.com/20388190/27566191-da65c558-5b26-11e7-842f-2e8a226fab73.png)

Sources:
http://help.octopusdeploy.com/discussions/problems/55279
http://help.octopusdeploy.com/discussions/questions/12074

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EnvironmentView permission dictates which environment-scoped variables in a set that a user can access](https://trello.com/c/W8d5PdVt/662-environmentview-permission-dictates-which-environment-scoped-variables-in-a-set-that-a-user-can-access)

**Comment by NickJosevski** [comment]
Release Note: fix for permission combination that allowed viewing of variables that user did not have access to

**Comment by KennethBates** [comment]
Reports of issue re-emerging. Related to the fix to the following issue: https://github.com/OctopusDeploy/Issues/issues/3840

Tested and confirmed issue is present in 4.1.9, so reopening this issue.

**Comment by artfulq3** [comment]
Hi NickJosevski,

We have the same issue in our Octopus. Now, All people can edit/view variables of PROD/PRE, This is a big problem of security that it should be fix asap.

Please, when do you expect to have the solution?

Regards, 
Hugo Hidalgo

**Comment by NickJosevski** [comment]
Hi @artfulq3 I responded on the support ticket.

Summary for here, it's *not supported* we have this issue, but it's really a missing / confusing feature, that many customers do want: https://octopusdeploy.uservoice.com/forums/170787/suggestions/6986441

We're working towards supporting this, but don't have a solid time line to share yet.

**Comment by Benny1007** [comment]
@NickJosevski they never used to be treated differently, a variable scoped to an Environment in both a project variable set and a Library Variable set were both inaccessible for a user that didn't have variableview for that environment. Something changed between 3.5.2 and 3.17.8. We defined an access model for Octopus and had it signed off by our internal auditors, now this needs to be redesigned?

**Comment by Benny1007** [comment]
@NickJosevski any update on this?

**Comment by gw2kbust** [comment]
@NickJosevski  Any update on this feature?  We need the ability to lock down these permissions at a library level.  Let us know.
