### ISSUE TITLE
Investigate tasks becoming stuck when Tentacle crashes/disappears

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3592]
There are several reports of tasks not cancelling when a Tentacle crashes or is restarted mid-task.

See:
http://help.octopusdeploy.com/discussions/problems/55476
http://help.octopusdeploy.com/discussions/problems/54507
http://help.octopusdeploy.com/discussions/problems/54400
http://help.octopusdeploy.com/discussions/problems/55545-deployment-stops-on-target-with-no-output
https://secure.helpscout.net/conversation/378599669/16263/?folderId=557082
https://secure.helpscout.net/conversation/391911353?folderId=571723

Reports that it only happens for health checks in HA.
Reports that the Tentacle VM has crashed/needs to be restarted.

**Comment by fenneh** [comment]
Just to add to this - I've been affected by this a lot. Primarily when upgrading tentacles. Recently upgraded from 3.7.x to 3.10.x and over the hundreds of tentacles which were upgraded I'd say a good percentage, 20/30% of them caused issues -- meaning, when there was an issue upgrading an environment (Up to 100 tentacles) it'd sit there mid way through the upgrade. Octopus would need restarting and then trying again. 

A mix of 2008 R2 and 2012 R2 servers. This is causing knock on effects for deployments _from_ the Octopus Server, Health checks, Tentacle upgrades. 

I may be touching on one of the causes for the issue, which in itself may be a separate problem. Let me know if I can forward any logs to you guys. I experienced it a couple of times whilst registering tentacles yesterday.

**Comment by tothegills** [comment]
From a crash dump of a stuck health check:

![image](https://user-images.githubusercontent.com/171197/27779018-5dde55fe-6003-11e7-866e-f479e865877a.png)


From a crash dump of a stuck deployment:

![image](https://user-images.githubusercontent.com/171197/27779145-3244e8d0-6004-11e7-958d-570df3fa40af.png)

**Comment by tothegills** [comment]
I think we get here in `Task.cs` which might be a good clue:

```
if (!flag2)
{
    Debugger.NotifyOfCrossThreadDependency();
    flag2 = millisecondsTimeout == -1 && !cancellationToken.CanBeCanceled && (this.WrappedTryRunInline() && this.IsCompleted) || this.SpinThenBlockingWait(millisecondsTimeout, cancellationToken);
}
```

**Comment by tothegills** [comment]
Things I've tried:

- Connect to a raw socket: fails immediately
- Attempt to connect to no socket: fails immediately
- Set `TcpClientConnectTimeout` to 1ms on the Octopus Server: fails with timeout
- Turn random Tentacles on and off during deployments and health checks: fails as expected
- Kill the Tentacle process during deployments and health checks: fails as expected
- Health check 2.5k machines on one node while deploying on another node

**Comment by alfhenrik** [comment]
Over the past week I've attempted to replicate this issue as well, here's the things I've tried:
- Spun up an environment with 2 Octopus servers and 2500 Tentacles (spread over 50 VMs), kicked off 2 deployments to 2 environments at the same time and also health checks
  - I actually managed to get this environment into a locked state, but couldn't track down another cause than the one above
- Spun up an environment with 1 Octopus server running `3.7.18` and 120 Tentacles (spread over 12 VMs), upgraded the Octopus server to `3.13.10` and kicked off the upgrade of all Tentacles and they upgraded successfully
- Spun up an environment with 1 Octopus server and 200 Tentacles (spread over 2 VMs) and tried running simultaneous deployments and health checks but was not able to get it into a locked state either.

**Comment by distantcam** [comment]
@tothegills picture of the thread stacks looks like a threadpool starvation issue.

https://gennadny.wordpress.com/2015/08/09/running-to-stand-still-adventures-in-net-parallelism/

It looks like the code `.GetAwaiter().GetResult()` releases the thread, but then queues the work back onto the original thread. Then multiples are getting blocked because they all want the same thread back. `.ConfigureAwait(false).GetAwaiter().GetResult()` has no effect.

Here's a LINQPad script demonstrating the issue.

```
void Main()
{
	ThreadPool.SetMaxThreads(10, 10);
		
	Parallel.For(0, 100, DoTheThing);
}

ConcurrentDictionary<int, int> seenThreads = new ConcurrentDictionary<int, int>();

void DoTheThing(int i)
{
	seenThreads.AddOrUpdate(Thread.CurrentThread.ManagedThreadId,
		k => { Console.WriteLine($"Seen new thread {k} - Total {seenThreads.Count}"); return 1; },
		(k, v) => { Console.WriteLine($"Adding to thread {k} - Total {seenThreads.Count}"); return v++; });
	Task.Delay(1).GetAwaiter().GetResult();
}
```

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate tasks becoming stuck when Tentacle crashes/disappears #3592](https://trello.com/c/zaWtIMeD/607-investigate-tasks-becoming-stuck-when-tentacle-crashes-disappears-3592)

**Comment by michaelnoonan** [comment]
Hi All,

We've recently shipped #3702 and #3701 which should help alleviate pressure on your Octopus Server, and give us a clearer understanding of what else could be going wrong.

Please upgrade to Octopus Server `3.16.1` or newer and let us know if this change helps.

At this point we aren't able to reproduce the problem in our lab, so we are going to wait and see if this surgical change improves the situation before investigating further.

**Comment by EtharAlali** [comment]
Still an issue in 3.17.2. Cancelled tentacle upgrade caused it this time. Though a re-index did the same thing yesterday (the date on the tasks show the issue) and hung the server. The UAT tentacles are operating on a different environment to the dev one (at the top) is set to deploy to. So two things:

1. Without access to the DB, can we cancel out the task? We don't have access to the prod DB's to run queries on.

2. Can there be an enhancement so we can choose to operate the environment deployments on different threads, allowing us to get past such an issue? As it holds up deployments unnecessarily. 

![bugoct](https://user-images.githubusercontent.com/2097628/30875018-02a89c42-a2ea-11e7-92da-238326256031.png)

**Comment by fenneh** [comment]
@EtharAlali - The way I've managed to handle this without update the DB is to restart the Octopus Server service itself (And pausing build queues etc)

**Comment by tothegills** [comment]
More reports on 3.17x:
https://help.octopusdeploy.com/discussions/problems/59514
https://secure.helpscout.net/conversation/437729711?folderId=557082

**Comment by droyad** [comment]
Please see#3238 for some diagnostics information we would like to connect in relation to this issue
