### ISSUE TITLE
Cannot delete deployment if team is scoped to specific environments

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3603]
Unless the team is scoped to all environments, the API returns 

```
"You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: DeploymentDelete"
```

The expected behavior is that if the team is only scoped to `Dev`, that user should be able to delete deployments to `Dev` from the API.

Octopus: `3.14.1`
Source: http://help.octopusdeploy.com/discussions/problems/55494

**Comment by NickJosevski** [comment]
Closing as cannot reproduce using customers permissions and setup. It appears to work
