### ISSUE TITLE
Project Variable Templates not imported onto cloned project

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3613]
When you clone a Tenanted project and add it to a tenant, the Project Variable Templates section has not been cloned.

Steps-to-reproduce:

Created Tenanted project
Create Project Variable Template
Clone project
Add cloned project to Tenant
Project Variable Template is not carried over.

Source: http://help.octopusdeploy.com/discussions/problems/55579

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Variable Templates not imported onto cloned project](https://trello.com/c/ec6437ps/666-project-variable-templates-not-imported-onto-cloned-project)

**Comment by NickJosevski** [comment]
Release Note: Project Variable Templates are now also cloned along with the other project properties and data
