### ISSUE TITLE
Fix inconsistencies between UI and API surrounding Library Variable Set scoping.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3615]
You can currently edit the following scopes in library set variables via the UI: Environment, Roles, Targets, Tags. If you use the API, you can technically scope to everything Project, Action, etc...

We should add checks to prevent this from happening.

Our API documentation under scoping for variable sets is as follows:
https://github.com/OctopusDeploy/OctopusDeploy-Api/wiki/VariableScopeValues
The API wiki will need updating to reflect this change also.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix inconsistencies between UI and API surrounding Library Variable Set scoping](https://trello.com/c/Fmn0EQDn/667-fix-inconsistencies-between-ui-and-api-surrounding-library-variable-set-scoping)

**Comment by pawelpabich** [comment]
Release Note:  Both API and UI for Library Variable Set enforce now the same scoping rules
