### ISSUE TITLE
CSRF token not sticking after disabling HSTS

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3616]
1. deploy a permanent instance (which sets up SSL, ForceSSL & HSTS)
2. request site in chrome and login (which means browser gets and acts on HSTS header)
3. open up the HTTP port on AWS
4. set `forceSSL` to false
5. set `hstsmaxage` to 10 (so that we can get the browsers HSTS record to expire)
6. restart server (to get server to pickup changes)
7. request site in chrome 
8. set `hstsenabled` to false (so it stops sending header)
9. restart server
10. request http version of site in chrome and try to login
=> chrome refuses to accept the cookie, and therefore fails to login

**Comment by michaelnoonan** [comment]
The most likely candidate for this is the browser is rejecting the cookie and not persisting it. It would be nice to test and see what the browser says about the rejection reason... Either way I'm not sure what we'll be able to do about this except for add some notes to our troubleshooting. Unless we get lucky and we are holding something wrong on the server-side.

**Comment by michaelnoonan** [comment]
We haven't been able to reproduce this to my knowledge. We also haven't seen a customer report of this same symptom. I'm closing this issue. Please feel free to comment if you see this behaviour, or contact our support team if the issue is locked.
