### ISSUE TITLE
The 3.15.0 Web UI does not load in IE11

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3631]
Source http://help.octopusdeploy.com/discussions/problems/55699

I've confirmed this running against demo.

![image](https://user-images.githubusercontent.com/1687639/27855041-4b428f00-61ac-11e7-8836-9c8b7d06e8a0.png)

**Comment by droyad** [comment]
Confirmed it does work in Edge and Chrome

**Comment by zentron** [comment]
Release Note: Fix JS bug introduced in `3.15.0` causing portal loading issues in IE11
