### ISSUE TITLE
Recurring scheduled deployments

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3633]
> It would be great to have an ability to create a recurring scheduled deployment, such as each Monday at 9:30 pm promote from QA to Staging

https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6599104-recurring-scheduled-deployments

**Comment by droyad** [comment]
UV https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6599104-recurring-scheduled-deployments

**Comment by baannee** [comment]
When can we expect this to be implemented?

**Comment by droyad** [comment]
@baannee We are almost feature complete, but still need to to internal review and testing. We expect to ship this in `2018.3.0` (Start of March)

**Comment by alfhenrik** [comment]
Unfortunately this feature missed the cut-off date for `2018.3.0` and will now be shipped in `2018.4`.

**Comment by tw17** [comment]
Release Note: Added new scheduled project trigger that allows setting up of recurring scheduled deployments.
