### ISSUE TITLE
Octopack for the new project system

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3634]
Octopack currently relies on a build task being added to the project file on install. With the new project system, this no longer occurs. 

Change Octopack to run in the new world, and also make any adjustments required for ASP.NET MVC Core.

**Comment by valeriob** [comment]
+1

**Comment by alexgurman** [comment]
come on guys, we need this.

**Comment by valeriob** [comment]
you can :
- add octo.exe to your source repository
- create a teamcity command line step that runs 
pack --id ProjectName --version %system.build.number% --basePath  \PublishOutput\ --outFolder build/packages

**Comment by slewis74** [comment]
We are not planning to implement this. The recommended approach is to use our build server plugins and/or octo.exe. See https://octopus.com/blog/octopus-and-netcore
