### ISSUE TITLE
Removing custom installation directory in custom package step template does not save change

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3638]
Octopus 3.15.8

Create a custom package step template with `Custom Installation Directory` section defined. Save the step template. Remove the `Custom Installation Directory` section from the step. Save the change, and update the steps. Export the custom step template, and see `Custom Installation Directory` in JSON still defined with the value initially set. The value should be removed when removing the section of the step template.

Screenshot of message when deselecting this feature.

![de-selecting_option](https://user-images.githubusercontent.com/20388190/27892979-0db7077a-6246-11e7-8bab-ad54eb2dce79.png)

Screenshot of JSON export after saving/updating the change.

![value_in_export](https://user-images.githubusercontent.com/20388190/27892984-117ac518-6246-11e7-8e1b-40128fe06490.png)

Workaround: Remove the custom installation directory value from the field, save the step, disable the feature and save again. This completely removes it from the JSON.

Source: https://secure.helpscout.net/conversation/392403619/16955/?folderId=954335

**Comment by pawelpabich** [comment]
This problem applies to any feature

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Removing custom installation directory in custom package step template does not save change](https://trello.com/c/UU7a0Eed/673-removing-custom-installation-directory-in-custom-package-step-template-does-not-save-change)

**Comment by NickJosevski** [comment]
Release Note: data on extra step features will be cleared when feature is disabled
