### ISSUE TITLE
Unreleased packages in "Package Repository Retention" needs more explanation

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#3648]
![image](https://user-images.githubusercontent.com/122651/27999091-014d7834-655c-11e7-86a6-9dcd52ea2718.png)

It would be nice to include a more comprehensive definition of "Unreleased packages".
Should make it clearer that it also includes packages that now have deleted releases and were deployed but are no longer required.

**Comment by droyad** [comment]
Release Note: Clarified how the package retention settings work on the dialog
