### ISSUE TITLE
Health check for ReleaseBot is failing

### ISSUE THREAD

**Issue by deanmalone** [OctopusDeploy/Issues#3649]
On deploy3.octopushq.com the health check for the ReleaseBot target for both Staging and Production environments is failing with the following error:

Check deployment target: ReleaseBot
July 10th 2017 04:33:56 Fatal
Could not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by droyad** [comment]
Example: https://deploy3.octopushq.com/app#/tasks/ServerTasks-127280

**Comment by distantcam** [comment]
Release Note: Added missing `Microsoft.Threading.Tasks` assembly.
