### ISSUE TITLE
Variable Templates dropping sensitive value

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3651]
Our Variable Templates are dropping values marked as sensitive when you add&save another template.

Steps I used to reproduce:
```
Create a Variable Set.
Create a Variable Template, set `Control Type` to `Sensitive/Password Box`.
Set default value & Apply.
Save & confirm value is there.
Create any other Variable Template in the same Variable Set.
Once you save, the default value for first sensitive variable is no longer there.
```

Source including screenshots: http://help.octopusdeploy.com/discussions/problems/55835

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable Templates dropping sensitive value](https://trello.com/c/hslnPg61/681-variable-templates-dropping-sensitive-value)

**Comment by pawelpabich** [comment]
Any update to the library variable set will cause this behaviour.

**Comment by pawelpabich** [comment]
Release Note: Default value of sensitive variable templates is now preserved between updates
