### ISSUE TITLE
Incorrect content in Preview section in deploy release page when deploying a release of an untenanted project to tenanted deployment targets

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#3655]
When try to deploy a release for a untenanted project to tenanted targets, the UI crossed out the targets, this is caused by the incorrect client side calculation.

Steps to reproduce:

1. Enable Multi-Tenant Deployments feature from Configuration page
2. Setup an untenanted project
3. Add a new tenant
4. Link the tenant to the deployment target
5. Create a release and try to deploy it to an environment
6. Click on the Advanced link button in the deployment page to show the advance settings

You should be able to see the target name get crossed out in the Preview section

We are planning to fix this issue by 
1. Show the machine preview where we can be certain it’s correct (the deployment is for exactly one scenario)
2. Hide the machine preview where there is more than one scenario (multiple tenants)

Source including screenshots: http://help.octopusdeploy.com/discussions/problems/55867

**Comment by matt-richardson** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorrect content in Preview section in deploy release page when deploying a release of an untenanted project to tenanted deployment targets](https://trello.com/c/4SKMpXtu/663-incorrect-content-in-preview-section-in-deploy-release-page-when-deploying-a-release-of-an-untenanted-project-to-tenanted-deploy)

**Comment by droyad** [comment]
@mayuanyang Will this be included in 4.0?

**Comment by mayuanyang** [comment]
Yes,  it will

**Comment by droyad** [comment]
Release Note: The target machines for a deployment are now shown per tenant and environment
