### ISSUE TITLE
Cancelling a task should only require the TaskCancel permission

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3656]
If you saw a deployment task running which shouldn’t have been running, would your expectation be:

> It’s OK, I can cancel that task because I know I have permissions to cancel tasks for ProjectX, EnvironmentY, TenantZ

The actual behaviour is:

> You can’t cancel that deployment because you don’t have the `DeploymentCreate` permission.

I feel like the ability to cancel a task should only assert the `TaskCancel` permission. Cancelling a task shouldn’t assert that I could have created the task in the first place.

Re-queuing a task on the other hand should assert you have the permissions to create the task in the first place. _This works as expected already._

# Proposal

Remove any extended assertions when checking permissions of someone attempting to cancel a task. We will only check for an appropriately scoped `TaskCancel` permission.

# Source

This issue came from a support ticket: http://help.octopusdeploy.com/discussions/problems/55661

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cancelling a task should only require the TaskCancel permission](https://trello.com/c/oCvagMjt/573-cancelling-a-task-should-only-require-the-taskcancel-permission)

**Comment by simon-alexander** [comment]
Hi Michael - A slight addition to your statement, even if you **DO** have the `DeploymentCreate` permission you can't cancel the task, even if you **DID** create the task.
