### ISSUE TITLE
Project Variable Template is dropping sensitive values when saving new template.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3671]
Regarding: https://github.com/OctopusDeploy/Issues/issues/3651

Project Variable templates are dropping sensitive values when saving a new template.

`Library -> Variable Sets -> Variable Template` section was fixed in the linked issue, the problem remains when editing sensitive value templates in `Project -> Variables -> Project Variable Templates`.

Source: http://help.octopusdeploy.com/discussions/problems/56013

**Comment by pawelpabich** [comment]
Release Note: Default value of sensitive project variable templates is now preserved between updates

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Variable Template is dropping sensitive values when saving new template](https://trello.com/c/jkLv1SuU/687-project-variable-template-is-dropping-sensitive-values-when-saving-new-template)
