### ISSUE TITLE
"item with the same key has already been added" when deploying to all tenants from Octo.exe

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3674]
Sources: http://help.octopusdeploy.com/discussions/problems/56026 & http://help.octopusdeploy.com/discussions/problems/56042

- Both users are running `3.15.6`

- In both cases, their `GET` call to tenants have duplicate ID filter like `/api/tenants?ids=Tenants-1?ids=Tenants-1`.

- I was able to reproduce this with Octopus `3.15.6` and Octo.exe `4.21.0`. In my case though I didn't get the duplicate ID filter in que URL (mine was `/api/tenants?ids=Tenants-1`), but I did get the same `An item with the same key has already been added.`

- To reproduce this I had to pass `--tenant=*` to `OCto.exe`. Passing a specific tenant didn't trigger the error. One of the users that reported this issue was passing `*` as well. The other user didn't show the full command call.

- Before upgrading to `3.15.6`, I was running `3.15.3` and I wasn't able to reproduce this error there. Even browsing `/api/tenants?ids=Tenants-1?ids=Tenants-1` didn't return an error, but an empty tenant list. So it has to be a very recent change.

**Comment by Dalmirog** [comment]
More sources

- http://help.octopusdeploy.com/discussions/problems/56038

**Comment by thebigmoosey** [comment]
Release Note: Fix for ids filtering in projects, tenants and library-variable-sets API
