### ISSUE TITLE
Lifecycle link in Library page not displaying with LifecycleView permission

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3675]
Octopus 3.15.6

If a user has `LifecycleView` permission, but not `LifecycleEdit` permission, they cannot see the link to the lifecycle page in the Library page as they should.

![library_ui](https://user-images.githubusercontent.com/20388190/28344682-9a8896c4-6c68-11e7-9688-a1cbd68475d0.png)

Though, if they go to the Lifecycle URL directly, they can view the lifecycles.

![library_lifecycle_ui](https://user-images.githubusercontent.com/20388190/28344722-cea7c6e6-6c68-11e7-9f75-e49cb416b5c5.png)

They still cannot edit the lifecycles as they're missing the `Edit` permission.

To see this link in the Library page, they need `LifecyleEdit` permission.

Source: http://help.octopusdeploy.com/discussions/questions/12333

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lifecycle link in Library page not displaying with LifecycleView permission](https://trello.com/c/ztwzQrJm/689-lifecycle-link-in-library-page-not-displaying-with-lifecycleview-permission)

**Comment by NickJosevski** [comment]
Release Note: Life Cycle listing in the Library will now be available to those with just permission `LifecycleView`
