### ISSUE TITLE
Step Template export API endpoint

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#3679]
Currently when you got to a step template, and hit the export button it uses JavaScript to manipulate the data it already fetched about the step template to change it's shape suitable for export/import.

It would be helpful for customers wanting to mass export to be able to hit an endpoint and get the right JSON as the result.

Proposed route: `api/actiontemplates/{id}/export`

![image](https://user-images.githubusercontent.com/119096/28395781-e54188ca-6d39-11e7-8e14-0808a27d3b13.png)

Left: API currently
Right: The JSON from the Export UI button
![image](https://user-images.githubusercontent.com/119096/28395826-34a43a02-6d3a-11e7-84d9-2aba1709fb50.png)

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Step Template export API endpoint](https://trello.com/c/yw9fgJYX/690-step-template-export-api-endpoint)

**Comment by stagor** [comment]
Would it be possible to do this via UI as well? I want to be able to export all steps at a time (probably, even tick a checkbox next to the step) and save a zip file with all json files.

**Comment by NickJosevski** [comment]
@stagor would you mind elaborating as to why and how often you would do the export.

**Comment by stagor** [comment]
I am working on step template improvements all the time. Because there is no possibility to save configuration (step templates, variable sets, project etc.) in Git (i like such feature in TeamCity), I am saving them one by one manually. For today I have more than 20 template steps.

@NickJosevski Probably my case is a unique one and better to ask other users as well. Thanks.

**Comment by pawelpabich** [comment]
We talked about this and decided that our regular API should be enough to read/write ActionTemplates from/to Octopus.
