### ISSUE TITLE
Add a "What's New" link on the new version notification

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#3683]
The "download now" link in the new version available notification section of the Octopus dashboard links to the version comparison page rather than the download page or initiating a download. This is unexpected behaviour based on the name of the link.

Current suggestion post slack discussion is to add a "What's New" link that points to the version comparison page. Download now link will then need to be validated against support, if in support show button which will trigger download, if out of support hide download now button.

**Comment by pawelpabich** [comment]
@droyad, correct me if I'm wrong but this has not been done?

**Comment by mwoffenden** [comment]
To be clear, the download link used to lead to a page which, quite helpfully, displayed only the **changes between my current version and the latest version**.

Would love to see this capability put back.

**Comment by droyad** [comment]
The link now goes to https://g.octopushq.com/ProductDownloadPage

**Comment by droyad** [comment]
Current notification
![image](https://user-images.githubusercontent.com/1687639/57279096-7c818800-70eb-11e9-90b3-9916d92135a3.png)
