### ISSUE TITLE
No indication when certificate is invalid

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#3690]
Create a new empty file. Give it a name as if it were a certificate, like `my-certificate.pem`.

In Octopus, go to Library -> Certificates and Add a new Certificate. Select the file you have just created. 

What should happen is that the file appears as uploaded/attached to the form, and then the user is given an error when they try to save the certificate. 

What actually happens is that the file is not even uploaded/attached at all, so there is no change to the form after the user selects the certificate file. If they hit save, it behaves as if the user did not select a file at all.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No indication when certificate is invalid](https://trello.com/c/BKiCaOwf/1231-no-indication-when-certificate-is-invalid)

**Comment by pawelpabich** [comment]
Release Note: We warn user now when they select a cert file that is empty
