### ISSUE TITLE
Tenant variable's project template value editor has some issues.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3700]
The Tenant variable's project template screen has a couple of issues that could be improved.

Bug:
>Can not save sensitive value with "Enter" if there are more than one variable in `Tenant -> Variables -> Project Variables`.

When setting a sensitive value for a variable template value on the Tenant variable screen, you are not able to confirm your selection with enter if there are multiple values there.

Steps to reproduce:
Create a sensitive variable template in your project, attach your project to a tenant.
When editing sensitive value, you can confirm your new value with enter.
Adding another environment or variable here disables the enter key from working to set value.

Extra thoughts here:

>No button to confirm selection of new sensitive value aside from `Save` in the corner.

Should we have a button inline with the editing box to set the value?

>You can not preview the sensitive values you enter here.

The only way to absolutely confirm that the correct value is set in the box is to deploy and see. Should be able to preview your value after saving to ensure that it has been set correctly?

Source: http://help.octopusdeploy.com/discussions/problems/56185

**Comment by droyad** [comment]
Release Note: The editing of tenant sensitive variables has been improved
