### ISSUE TITLE
octo.exe cannot export environments

### ISSUE THREAD

**Issue by jez9999** [OctopusDeploy/Issues#3706]
I think octo.exe should be able to export/import environments as well as projects.  Sometimes environments are quite complex and having to set them up by hand before importing a project is quite a nuisance - they should be able to be exported/imported to/from JSON.

**Comment by vanessalove** [comment]
Hi @jez9999 , thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
