### ISSUE TITLE
Renaming a Service name on a 'Deploy Windows Service' step checks for an existing service with the new name

### ISSUE THREAD

**Issue by ThomasBouman** [OctopusDeploy/Issues#3710]
Like the title states: when you rename the Service name (either through variables or directly), on the next deploy it will check if there is a service running with that new name. 

This probably stems from the fact there is no change in the actual step, so it will do what it always does. It is however confusing, ideally it will check for the previous service name and stop/delete that one. Less than ideal it will give you a warning that you need to manually stop and delete the old service.

**Comment by droyad** [comment]
Feature suggestions should go to https://octopusdeploy.uservoice.com/. While I can understand this is annoying, we have no plans to support this at this stage. We also don't do this sort of thing for IIS Websites, App pools or cloud services. The deployments know very little about the previous deployment, and guessing at the user intention may lead to deletion of a service that is to be kept (eg in a Multi-tenanted setup).

What we may do is have an uninstall script that may allow you to do this.
