### ISSUE TITLE
Expose Octopus variables as Environment variables

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#3712]
When people write PowerShell, Bash or other scripts with Octopus, they have to rely on the fancy way that Octopus exposes our variables to them - by magically assuming a variable will be set in PowerShell, or by using `get_octopusvariable` in Bash. There's no nice way to write a single script that runs both inside Octopus and outside of Octopus without resorting to tricks. 

It would be better if we could expose project variables in Octopus as environment variables - perhaps with a checkbox on each variable - so that Bash, PowerShell and other scripts can just pull them out of environments. This would allow you to write a single script like:

```
curl $Website
...
```

This script would run exactly the same:

 - Via Octopus (`Website` is exposed as an environment variable)
 - Via TeamCity (using TeamCity `env.` parameters)
 - Via command line (calling `export Website=Foo` before invoking the script)

Having it as a setting on project variables also means they are ambiently passed down through steps and into things inside of steps - it would work with step templates, as well as with scripts called from the context of a package. All scripting languages provide facilities to not only read environment variables, but also iterate over them, which isn't currently possible with `get_octopusvariable` in our Bash scripts today.

**Comment by zentron** [comment]
It would need to be obvious that If i run a .net core app that uses values from the environment, that these will not by default persist between process restarts or reboots.  The variables are largely the domain of *the Octopus step itself* unless some other mechanism (e.g. PM2) ensures that they are captured and managed within the relevant deployed context boundary.

**Comment by alastairtree** [comment]
Shame this got closed @PaulStovell as was a nice idea. Does this mean it's not an OD priority?
