### ISSUE TITLE
Environment deletion times out

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3714]
It looks like the environment deletion can timeout when there is a lot of data to delete. Can this be optimised?

Source:
https://secure.helpscout.net/conversation/406209250?folderId=909879

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Environment deletion times out](https://trello.com/c/gxVqyxCx/717-environment-deletion-times-out)

**Comment by michaelnoonan** [comment]
I'm changing this to a bug, we want to investigate it further. We can't be confident the database was left in a consistent state after the error was thrown.

**Comment by pawelpabich** [comment]
Should we delete it in the same way we delete releases? I believe it happens as a task.

**Comment by droyad** [comment]
This will be covered by #4319
