### ISSUE TITLE
Machine set to be included in both tenanted and untenated deployments not showing in deployment preview of un-tenanted deployment

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3715]
To reproduce:

1. Create a project (Project A) with _Multi-tenant Deployments_ set to _Allow deployments with or without a tenant_
1. Create a tenant (Tenant A) linked to the project for an environment (Environment A)
1. Create a machine (Machine A) with _Tenanted Deployments_ set to _Include in both tenanted and untenanted deployments.  Set the tenant filter to include Tenant A.
1. Create a deployment of Project A to Environment A (no tenants)

*Expected*
Deployment preview shows Machine as _included_

*Actual*
Deployment preview shows Machine as _excluded_

Reported by https://secure.helpscout.net/conversation/396569580?folderId=571733 (private link)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Machine set to be included in both tenanted and untenated deployments not showing in deployment preview of un-tenanted deployment](https://trello.com/c/4hOaT995/621-machine-set-to-be-included-in-both-tenanted-and-untenated-deployments-not-showing-in-deployment-preview-of-un-tenanted-deploymen)

**Comment by michaelnoonan** [comment]
Let's verify this works as expected in 4.0 before it ships.

**Comment by MJRichardson** [comment]
Verified in 4.0

**Comment by michaelnoonan** [comment]
Release Note: We fixed several bugs with the Deployment preview and which deployment targets will be included in the deployment
