### ISSUE TITLE
Can't access latest and specific versions of packages when using a custom expression for the package feed

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#3721]
If you have multiple nuget feeds configured and you use a custom expression to determine which nuget feed to use when deploying a package, then you are unable to select the latest version of a package when creating a new release, nor are you able to search for a specific version of a package.

So if I have the following variable configuration to specify my feeds:
![image](https://user-images.githubusercontent.com/1892715/29011061-5a6f130a-7b73-11e7-851d-7b3d64cf960a.png)

And I specify a custom expression for the package feed:
![image](https://user-images.githubusercontent.com/1892715/29011097-b009339a-7b73-11e7-9e57-15e6ee7d76c4.png)

Then when I try to create a new release, the "Latest" column is empty, because Octopus does not know which feed to use.
![image](https://user-images.githubusercontent.com/1892715/29011070-76294872-7b73-11e7-839f-5fa5b7f7c8f3.png)

Similarly, if I try to search for a Specific package, the dialog is disabled:

![image](https://user-images.githubusercontent.com/1892715/29011140-1093dd96-7b74-11e7-8538-1337084d7ab4.png)

This is a little frustrating because in this scenario the feed is known ahead of time.

**Comment by droyad** [comment]
@TomPeters It's a bit unclear to me, from the example, how Octopus should know which feed to use at release creation time.

**Comment by thashepherd** [comment]
In the situation where I'd like to use this feature (I have the same issues as @TomPeters) the channel and lifecycle do result in one specific environment that could be used to bind the right feed. 

Unfortunately, as our release names are derived from NuGet package IDs, dynamically bound feeds aren't workable in our workflow right now.

**Comment by danielfischeroctopus** [comment]
Another source: https://help.octopusdeploy.com/discussions/questions/13993

**Comment by droyad** [comment]
I could not reproduce this in the latest version, and I suspect this was fixed as part of #5412
