### ISSUE TITLE
Hide advanced deployment options that are misleading

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3726]
Relates to https://github.com/OctopusDeploy/Issues/issues/3715

We have a lot of customers (probably 20) now who have become confused through small UI bugs with the advanced deployment options when deploying to multiple tenants or multiple environments. Sometimes the step previews are correct, sometimes they are not. Sometimes the machine previews are correct, sometimes they are not.

# Short term fix

Rather than showing information that may be incorrect and create fear-uncertainty-doubt, we should hide the information when people are deploying to multiple environments or multiple tenants.

## Will my deployments work properly

Yes. This is just a UI bug, and we have a lot of automated tests to ensure the server-side logic works according to our rules. If you find a deployment targets the wrong machines please double check your configuration. Otherwise feel free to get in touch with us at https://octopus.com/support

# Future redesign

The features of Octopus have outgrown this screen and it really needs to be re-imagined.

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide advanced deployment options that are misleading](https://trello.com/c/paCSWInA/631-hide-advanced-deployment-options-that-are-misleading)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide advanced deployment options that are misleading](https://trello.com/c/I332nUBE/716-hide-advanced-deployment-options-that-are-misleading)

**Comment by MJRichardson** [comment]
We are not going to make this change before v4 is released.
