### ISSUE TITLE
Scoping team to a single empty project group gives members access to all projects.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3728]
When a user is a member of a project group which has no projects associated with it, if the user has the other relevant permissions, they can view/modify all projects.

Steps to repro:
Create project group with no projects.
Create new user.
Create new Team with project permissions. I used Project lead & Project deployer.
Scope team to project group with no projects.
Add new user.

As there are no projects in the group, the user is able to perform actions against any project.
https://secure.helpscout.net/conversation/410528375/18137/?folderId=845288

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scoping team to a single empty project group gives members access to all projects.](https://trello.com/c/Fj5hCorV/714-scoping-team-to-a-single-empty-project-group-gives-members-access-to-all-projects)

**Comment by TomPeters** [comment]
https://github.com/OctopusDeploy/Issues/issues/3423

**Comment by pawelpabich** [comment]
Release Note: Teams scoped to empty project groups have access to no projects now
