### ISSUE TITLE
Adding OpenAPI Support

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#3729]
Adding support for generating and using an OpenAPI specification for the Octopus Server API.

- [ ] Auto-generate OpenAPI file from the Nancy system.
- [ ] Generate the client code from the OpenAPI spec.

Some other ideas for usage.

- Auto-generate documentation
- Anything else?

**Comment by droyad** [comment]
This was started with Swagger, no plans to do anything further at this stage (other than improving Swagger documentation)
