### ISSUE TITLE
Failed or canceled tenanted deployment stops you from promoting other successful tenants in the release.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3732]
There is a bug when promoting releases to tenants where one deployment fails or is canceled

Simple example that can be easily replicated.

Create a project that is connected to two tenants, where you would deploy for them simultaneously. My Lifecycle was Dev -> Test -> Prod.

Deploy to Tenant-A & Tenant-B in the Dev environment. During the deployment, cancel one of the tenanted deployments.

Assuming Tenant-A was canceled, Tenant-B should be able to be promoted to Test, however the option to promote the successful tenant is not available. Successfully retrying or manually setting Tenant-A to successful will fix the issue, redeploying Tenant-B to its already successful environment will also allow you to promote.

Source: http://help.octopusdeploy.com/discussions/questions/12554
GIF recording of this behavior on my VM: http://recordit.co/Xkp7oJy0s4

**Comment by zentron** [comment]
Release appears deployable in latest build. Discussed with @danielfischeroctopus and it also looks fine now on his side. Am putting down to "accidently fixed" unless it pops up again
![image](https://user-images.githubusercontent.com/1830666/31805221-7fc1df48-b5a2-11e7-80a1-414ce13021f3.png)
