### ISSUE TITLE
Provide helpful error message if package file with length of 0 is pushed

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3735]
Uploading an empty package file results in package indexing failing with an obscure error message similar to:

```
System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.
```

For example: https://secure.helpscout.net/conversation/411937596?folderId=571733 (private link)

When the file is pushed, if the stream length == 0 then we are in a good position to provide a helpful message.

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scoping team to a single empty project group gives members access to all projects.](https://trello.com/c/Fj5hCorV/714-scoping-team-to-a-single-empty-project-group-gives-members-access-to-all-projects)
