### ISSUE TITLE
Pull logic from Octo.exe into Octopus.Clients.dll to allow reuse

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3745]
At the moment there is currently a whole heap of logic in `Octo.exe` that could come in handy in the `Octopus.Clients.dll` directly. 
This logic should be moved up into `octopus.clients` leaving `Octo.exe` as a thin shell around it to parse and process console IO.
In addition, this would allow us to build a [dotnet core tooling](https://github.com/OctopusDeploy/OctoPack/pull/96) with feature parity without code duplication.

**Comment by droyad** [comment]
We will cover this as part of our normal engineering process.
