### ISSUE TITLE
If a variable does not exist, get_octopusvariable returns a message instead of empty

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3747]
When `get_octopusvariable` is used in a SSH script, and the specified variable does not exist, `Unrecognized variable "Foo"` is returned instead.

It should be echoing `Unrecognized variable "Foo"` to the console output and then returning null.

Original report: https://secure.helpscout.net/conversation/418002996/18564/?folderId=557077

It hits the default case here:
https://github.com/OctopusDeploy/Calamari/blob/7323157e3a2cf9d69d7da6edaef3c1d16818b9bf/source/Calamari/Integration/Scripting/Bash/Bootstrap.sh#L51

**Comment by RobSeder** [comment]
Thank you for addressing this!!

**Comment by droyad** [comment]
As some customers may be relying on the existing behaviour, we've decided to delay this until 4.0 (late 2017). In the meantime, I recommend checking to see if the value is `Unrecognized variable "Foo"` or an empty string.

**Comment by StephenShamakian** [comment]
@droyad Understood. But how do we check for an empty string? That's what we were asking for if the variable doesn't exist to just return null or empty.

**Comment by RobSeder** [comment]
@droyad I may have misspoke. This is for when the Parameter exists, but the user left the value empty. In that case,  "Unrecognized variable" is returned. What should be returned is an empty string.

It makes sense that "Unrecognized variable" would be returned for a Parameter that didn't exist in the Step Template definition. But we're talking about when the parameter does exist, but it simply doesn't have a value in it.

**Comment by droyad** [comment]
@StephenShamakian What I meant what that you should check for both for now so that you don't have to rewrite the script when 4.0 comes out.

**Comment by droyad** [comment]
@RobSeder Octopus does not differentiate between a parameter that does not exist and one that is not set. Both are omitted from the step's variables at deployment creation time (Have a look at what is posted when you edit a step). So at execution time we can't tell. The convention everywhere except bash scripts is to treat missing as empty string (or default value). This change would bring bash inline with that convention.

**Comment by droyad** [comment]
`Unrecognized variable "Foo"` will not be echoed out as everything written in a bash function is returned to the caller.

**Comment by RobSeder** [comment]
We'll look for this when 4.0 comes out - thanks very much!

**Comment by droyad** [comment]
Release Note: **Breaking Change** The `get_octopusvariable` bash function now returns an empty string if the variable does not exist
