### ISSUE TITLE
Some steps do not appear in the list when filtering or refreshing

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3750]
Stay with me on this one,

1) Navigate to a project -> Process -> Add Step
2) Note the presence of the `Run a Docker Container` step
3) `F5`
4) Where is my Docker?

![missing steps](https://user-images.githubusercontent.com/1687639/29608253-ff11aa10-8836-11e7-8203-32bbbfaf3f56.gif)

**Comment by droyad** [comment]
Original report https://secure.helpscout.net/conversation/418753861/18621/?folderId=557077

**Comment by droyad** [comment]
Since at least `3.15.8` as the above screenshot is from Demo

**Comment by NickJosevski** [comment]
Looks like a race condition on the `canShow` in the pluginRegistry. 

The 3 missing docker steps, all have this: `canShow: function() { return octopusFeatures.isEnabled('IsDockerEnabled'); },`

When you arrive via normal navigation octopusFeatures is populated, but when you re-load that page via F5 like the customer had it results them getting false for IsDockerEnabled.

**Comment by droyad** [comment]
It's probably time to remove that flag?

**Comment by NickJosevski** [comment]
## Outcome

Removing the Docker feature toggle is the ideal solution, that change will be in Version 4 (or later). 

## Work around 
Current work around is to navigate in app elsewhere, and return to the step page.

**Comment by droyad** [comment]
Release Note: The docker steps no longer disappear from the step list when the page is refreshed
