### ISSUE TITLE
Saving IIS related steps created by previous version of Octopus fails

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#3753]
### Issue

If the bindings are stored as a pipe delimited set when you add to the set or remove from it, save fails with a console error on `bindingsToString`.

Old style binding: `http:#{httpPort}://#{UseStandardHttpBinding}/false` when parsed host is undefined.

![image](https://user-images.githubusercontent.com/119096/29698698-d5543dae-899a-11e7-97c9-64cabae15b82.png)

### Solution

A new migration `Script0092MigrateIisBindingsToJson` that reads entire `DeploymentProcess` table, looking in `Steps -> Actions -> Properties -> Octopus.Action.IISWebSite.Bindings`, it ignores any that are new style, already have the indicator of starting as a JSON array is empty `[]` or start of populated set `[{`.

A new BindingEntry is built up from the split up of the pipe delimited string, following how [Calamari does it in this conditional branch of code](https://github.com/OctopusDeploy/Calamari/blob/51343ad74b29b3fb9a3fbdefe2eece85667053e7/source/Calamari/Scripts/Octopus.Features.IISWebSite_BeforePostDeploy.ps1#L496).

### Test cases
In test function: `CleanupBindingsCheck_Script0092MigrateIisBindingsToJson`

  - Unit tests with crafted steps containing old style
    - 2 taken from customers reporting issue
	- 1 hand crafted

 - Compared Database pre migration with post migration (Script0092MigrateIisBindingsToJson)

During testing, reviewed changes to the entire document, only changes were by design.

![image](https://user-images.githubusercontent.com/119096/29855264-e0149634-8d8d-11e7-9a61-1e65bc292b9a.png)

**Comment by NickJosevski** [comment]
This related to https://github.com/OctopusDeploy/Issues/issues/3752

The plan is to write a data migration script so the v1 parser and anything else can go away, and stop biting us.

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migration script for bindings old storage format](https://trello.com/c/PXIPODUt/719-migration-script-for-bindings-old-storage-format)

**Comment by pawelpabich** [comment]
@NickJosevski, I think we can close this one off ?

**Comment by NickJosevski** [comment]
yes it will be fixed for customers when they install v4 and `Script0093MigrateIisBindingsToJson` runs, same goes if they run the migrator and go to v4.

**Comment by NickJosevski** [comment]
@pawelpabich yes it will be fixed for customers when they install v4 and `Script0093MigrateIisBindingsToJson` runs, same goes if they run the migrator and go to v4.

**Comment by NickJosevski** [comment]
Release Note: Fixed error that occurs when saving IIS related project steps that were created by earlier versions of Octopus
