### ISSUE TITLE
Links in UI not displaying with their 'View' permissions

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3763]
Octopus 3.16.7

1) In the `Environment` tab in the web portal, the link to `Proxies` isn't displayed when user has only ProxyView permission.
Currently ProxyEdit is required to see the link.
Workaround: Enter the URL `OctopusServer/app#/environments/proxies`

2) In the `Configuration` tab, the link to `Users` isn't displayed when user has only UserView permission.
I can't find which permissions are required to view the Users link in the UI.
Workaround: Enter the URL `OctopusServer/app#/configuration/users`

Similar behavior in closed issue regarding LifecycleView permission not showing Lifecycle link: https://github.com/OctopusDeploy/Issues/issues/3675

Source: https://secure.helpscout.net/conversation/425074624/18951/?folderId=954335 (private link)

**Comment by KennethBates** [comment]
This same behavior happens with the Environments > Accounts link. In the Environment page, you can't see the link to Accounts with only AccountView permission. AccountEdit is required, but users only with the view permission can navigate to the URL at OctopusServer/#app/accounts.

**Comment by droyad** [comment]
Release Notes: The links to Accounts, Users and Proxies now show when you only have the relevant view permissions
