### ISSUE TITLE
Provide automatic Tentacle updates when a new version of Tentacle is released

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3774]
Because Tentacle and Server are on a separate release cadence it now makes sense to allow automatic updates of Tentacle when a new version of Tentacle is available.  At the moment the Octopus portal will prompt to update Tentacle when the Server is bundled with a new version of Tentacle.  It should prompt to update Tentacle whenever a new version of a compatible Tentacle is released.

**Comment by matt-richardson** [comment]
Related - https://github.com/OctopusDeploy/Octofront/issues/278

**Comment by droyad** [comment]
Calamari as well?

**Comment by droyad** [comment]
We are closing this as the demand for this has been reduced now that we are no longer shipping Tentacle as often. It would be great to see this.

We will re-consider this when we implement feeds for various tools as then this will be much easier to implement seeing the update package delivery infrastructure will be in place.
