### ISSUE TITLE
Project group dropdown list deselecting group

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3775]
Octopus 3.16.7

When you have over 50 project groups, the dashboard page displays the groups in a dropdown list. When you have a group selected, and hover over a different project group, the highlighting reverts back to the project group that's currently selected.

Steps to reproduce:
1) Have over 50 populated project groups to create the dropdown
2) Select a group
3) Hover over a different group in the dropdown

Gif showing this behavior:

![project_group_dropdown](https://user-images.githubusercontent.com/20388190/30142433-141eb14e-93c4-11e7-8a04-e26281e5f2b6.gif)

Source: https://secure.helpscout.net/conversation/427184886/19084/?folderId=954335

**Comment by pawelpabich** [comment]
This is fixed now in Octopus 4.
