### ISSUE TITLE
Step name is incorrect when the second last action moves out of a parent step

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3778]
Steps to reproduce:

1. Create parent step
2. Add a few child steps
3. Enable rolling deployments and set the window size to 2
4. Move out child steps one by one
5. Open re-order popup. 
6. The list of steps in the deployment process does not match the list of steps in the re-order dialog but it should.

Screenshot:

![image](https://user-images.githubusercontent.com/347637/30150963-eaa2c09e-93f0-11e7-8524-0981291b28bf.png)

Export of the deployment process:

[DeploymentProcess.zip](https://github.com/OctopusDeploy/Issues/files/1283724/DeploymentProcess.zip)

Started by: https://secure.helpscout.net/conversation/426786762?folderId=557077

**Comment by droyad** [comment]
What it looks like is that the process screen is displaying the `Action` name, while the reorder dialog is showing the `Step` name. Usually these are the same, but not when you remove the 2nd last child (leaving one and it collapses).

I think when there is only one action left, the step name should change to be the action name (discarding the step name).

**Comment by droyad** [comment]
This problem exists in both v3 and v4

**Comment by droyad** [comment]
Release Note: The step names now appear correctly in Reorder Steps after removing the all steps from a parent step
