### ISSUE TITLE
Support registering a tentacle allowing both tenanted and untenanted deployments via command line

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#3782]
Currently is not possible to register a Tentacle with both tenanted and untenanted deployments via the CLI.
https://octopus.com/docs/api-and-integration/tentacle.exe-command-line/register-with

**Comment by dopsy** [comment]
Hi,

any update when this could be implemented?

**Comment by danielfischeroctopus** [comment]
Source: https://help.octopus.com/t/register-tentacle-as-tenanted-deployments/18937

**Comment by spuder** [comment]
We really need this feature. Automating 1000 web servers with Tentacle.exe + Chef. 
All of them will be tenanted deploys. 

By default tentacles come up as excluded from tenanted deploys

![image](https://user-images.githubusercontent.com/242382/36917273-a63bbf70-1e13-11e8-89b9-e346e491adba.png)

**Comment by matt-richardson** [comment]
This has been released in Tentacle version `3.19.0`.

**Comment by spuder** [comment]
Thank you for implementing this so quickly.  I'm looking at the source but can't quite figure out what the syntax will be. Guessing something like this? 

    Tentacle.exe register-with --TenantedDeploymentParticipation=Tenanted

**Comment by matt-richardson** [comment]
It'll be
```
Tentacle.exe register-with --tenanted-deployment-participation=Tenanted
```

Running `Tentacle.exe register-with --help` will list the options.
