### ISSUE TITLE
Cannot edit variable template value of sensitive variable

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3784]
Octopus 3.16.7

Sensitive variable template values cannot be edited for tenants

Steps I took to reproduce
1) Add variable template to a project, control type: sensitive/password box
2) Bind the default value to a variable
3) Connect a tenant to this project
4) To edit the variable value, reset custom expression, and select `Set`

Result: When cursor is in the text box for the variable value, you are unable to type or paste anything into it. The following gif includes attempts to type and paste into the text box.

![sensitive_variable_template_edit_failure](https://user-images.githubusercontent.com/20388190/30254908-cd0f6048-96e1-11e7-9227-a61556315e57.gif)

May be related to the fix of this issue: https://github.com/OctopusDeploy/Issues/issues/3651
Reported here: https://secure.helpscout.net/conversation/427990728/19142/?folderId=954335

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot edit variable template value of sensitive variable](https://trello.com/c/z6ZRxJPJ/728-cannot-edit-variable-template-value-of-sensitive-variable)

**Comment by pawelpabich** [comment]
Release Note: Sensitive tenant variables that use variable expression can now be changed to set custom value
