### ISSUE TITLE
Clarify how wildcards work for purge custom directory

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#3786]
In:
![image](https://user-images.githubusercontent.com/122651/30300650-2ef2484a-9799-11e7-8d96-5728e1fa89f2.png)

the help text:
```
A newline-separated list of file or directory names, relative to the installation directory, to leave 
when it is purged. Extended wildcard syntax is supported. 
E.g., appsettings.config, Config\*.config, **\*.config
```

could be more clear on when to use wildcards

Raised by customer in https://help.octopusdeploy.com/discussions/questions/12996-exclude-from-purge-iis-templateperformance-hit

**Comment by droyad** [comment]
@johnsimons @larssb  How does this sound? (Bold added to show the added text)

A newline-separated list of file or directory names, relative to the installation directory, to leave 
when it is purged. **To exclude a whole directory, specify it by name without a wildcard.** Extended wildcard syntax is supported. E.g., appsettings.config, Config\\*.config, **Config**, **\\*.config

**Comment by droyad** [comment]
![image](https://user-images.githubusercontent.com/1687639/31753650-49880c68-b4d5-11e7-9157-e9cdd96e8d5f.png)

**Comment by droyad** [comment]
Release Note: Clarified how to exclude directories when purging a custom installation directory

**Comment by larssb** [comment]
Sounds good to me :-)
