### ISSUE TITLE
Project variable filter hides some variables

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3795]
Octopus 3.17.0

When using the filter in the project variables and changing the scope of variables, the filter incorrectly stops displaying them. The steps I took to reproduce this:

1) Create an unscoped variable
2) Filter by environment scope (the variable is displayed)
3) Scope the same variable to that environment
4) Remove the environment scope (to be unscoped)
5) Remove the scope filter
6) Filter by environment scope again

Result: The variable which had the scope changed stops displaying. Since the filter shows unscoped variables initially, this behavior is unexpected and implies the variable has been deleted.

![project_variable_filter](https://user-images.githubusercontent.com/20388190/30406199-b07ae066-9933-11e7-969d-ff211a13346b.gif)

Source: https://help.octopusdeploy.com/discussions/problems/58221

**Comment by droyad** [comment]
Release Note: The variable editor no longer hides unscoped variables when a variable with the same name is scoped to the filter condition
