### ISSUE TITLE
Issue setting external ids in OKTA

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3797]
In order to for OKTA to pass the required claims to Octopus, you need to set the OpenID Connect ID Token's `Group claim filter` to `roles` and filter by regex with `.*`

Source: https://help.octopusdeploy.com/discussions/questions/13072

**Comment by danielfischeroctopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue setting external ids in OKTA](https://trello.com/c/HQA61BzA/616-issue-setting-external-ids-in-okta)

**Comment by sbotman** [comment]
@danielfischeroctopus I'm trying to setup the same configuration, did the suggested here above, but still don't see any roles from okta in my json web token. Do you have any update on this or can you give me some tips on how to make this work?

**Comment by devanjain** [comment]
@danielfischeroctopus We have added Okta groups as external role in Octo, but group member still has their individual privileges, not the one provided to the external role in the team. We have followed the approach mentioned above, but it still doesn't work. Any document or advice to make it work.

**Comment by slewis74** [comment]
We have done some other fixes in this area since this was raised and believe the issues with the groups have been resolved. If you still experience issues please comment and we can reopen.
