### ISSUE TITLE
Change assembled date to be overwritable

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3800]
Octo.exe imports releases, but uses `now` as the assembled time and ignores the time from the origin server (which is included in the JSON).

Changing this property to be able to be overwritten means releases imported for Octo.exe (and in future for release promotions)  will have the date it was created on the origin server and not the imported date.

Source (private link):  https://help.octopusdeploy.com/discussions/problems/58305

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change assembled date to be overwritable](https://trello.com/c/zgEvDriG/710-change-assembled-date-to-be-overwritable)

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change assembled date to be overwritable](https://trello.com/c/zgEvDriG/710-change-assembled-date-to-be-overwritable)

**Comment by MJRichardson** [comment]
Release note: When creating a Release, if Assembled date supplied then use it
