### ISSUE TITLE
Remove fields marked as `Obsolete`

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3805]
See https://github.com/OctopusDeploy/OctopusDeploy/search?utf8=%E2%9C%93&q=ObsoleteEx&type=

Also see https://github.com/OctopusDeploy/OctopusDeploy/search?utf8=%E2%9C%93&q=deprecated&type=

(there's some that I did mark as remove in 4.3, but there's been no issues around them, so they should go in 4.0 instead)

**Comment by droyad** [comment]
Separate issues have been raised for this
