### ISSUE TITLE
Document Variable Run Condition

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3820]
There is no documentation for Variable Run Conditions. We should specifically call out that machine level variables are not supported (see #3206)

https://octopus.com/docs/key-concepts/projects/deployment-processes would be a good place to add it.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document Variable Run Condition](https://trello.com/c/FHsoh1K8/1233-document-variable-run-condition)

**Comment by pawelpabich** [comment]
Updated here: https://github.com/OctopusDeploy/docs/commit/abb1f57d63ef7993cb39711d2b21a3b74ee91d5b
