### ISSUE TITLE
Cloud Service should never allow a Service Principal account

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3821]
Through the Octopus UI you can only select a Management Certificate account in the Cloud Service step. This is by design, as it is the only option supported by the Azure cmdlets.

The API doesn't seem to enforce this and if you use a variable binding then it is also possible to bypass it. The step execution in Calamari should detect this and show a very clear error message indicating that Service Principals are not supported.

**Comment by thebigmoosey** [comment]
Release Note: Restricting Cloud Services to Management Certificate accounts at the API
