### ISSUE TITLE
OctoPack doesn't support new 2017 .csproj format

### ISSUE THREAD

**Issue by msnelling** [OctopusDeploy/Issues#3822]
OctoPack doesn't support the new `.csproj` file format in Visual Studio 2017

**Comment by benPearce1** [comment]
Hi,

We have this support on our radar, but don't have an ETA at this stage. 
In the meantime, you could try running ```dotnet publish``` and then run ```octo.exe pack``` against the publish output folder. 

I hope this helps.

Regards
Ben
