### ISSUE TITLE
TeamCity plugin needs to provide Pack option

### ISSUE THREAD

**Issue by msnelling** [OctopusDeploy/Issues#3823]
The TeamCity plugin needs to support the `pack` option for `octo.exe`. Without this we are unable to use TeamCity to pack and publish our builds to our OctopusDeploy server. as we are using Visual Studio 2017 (see issue https://github.com/OctopusDeploy/Issues/issues/3822).

**Comment by benPearce1** [comment]
Hi,

Thanks for getting in contact.
The pack option is not a separate step in the TeamCity plugin but is part of the Push step. If you add an expression to the "Package paths" ```published-webapp/**/* => MyApp.%build.number%.zip``` this will create a zip file from the source path and the step will push it to the Octopus server.

Regards
Ben

**Comment by valeriob** [comment]
Hi,
i think you really should separate pack from publish, i have the same issue : 
I have a mixed build with some dotnet core projects. For old projects i can just checkbox "Run OctoPack" on the build step, but for dotnet core project i followed this guide : 
https://octopus.com/docs/guides/deploying-asp.net-core-web-applications that suggest to do it yoursellf and call "octo.exe pack" but this is not possible in teamcity.
Pls provide this workflow.
Thanks
