### ISSUE TITLE
Evaluate channel name for packages on release creation to assist with package retention polciies

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3829]
you can have a package name that is dynamic based off channel name. As releases have a static channel, the package name could be evaluated and stored on the release instead of being stored with the variable name. this would allow for retention of those packages, even though they use a variable.

It would have to be using Octopus.Channel.Name variable.

Source: https://help.octopusdeploy.com/discussions/questions/12890
Spoke to Henrik about this one .....

**Comment by droyad** [comment]
This has worked since `3.3.2`  (https://github.com/OctopusDeploy/OctopusDeploy/commit/b8c12c2ea033ef02f6ad4863c1bcb87bad421ed7). The variable is `Octopus.Release.Channel.Name`
