### ISSUE TITLE
Remove deprecated configure command options

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3831]
Remove:
`Octopus.Server.exe configure --masterKey`
`Octopus.Server.exe configure --storageConnectionString`
`Octopus.Server.exe configure --webAuthenticationMode`

The first two have been replaced wtih `Octopus.Server.exe database` commands. The last one with individual configuration of providers.

These options were deprecated in June https://github.com/OctopusDeploy/OctopusDeploy/pull/1144

**Comment by droyad** [comment]
Release Note: Removed previously deprecated `Octopus.Server.exe configure`  options `--masterKey`, `--storageConnectionString` and `--webAuthenticationMode`.

**Comment by cjuroz** [comment]
Just to let you know docs don't reflect these changes: https://octopus.com/docs/v/4.0/api-and-integration/octopus.server.exe-command-line/database

**Comment by slewis74** [comment]
Docs have just been updated for the changes to `configure` and `database`

**Comment by rickjuryxero** [comment]
you still have the removed param webAuthenticationMode  in the example script on this page https://legacydocs.octopus.com/docs/v/4.0/installation/automating-installation/ and the link above is broken to OctopusDeploy/OctopusDeploy#1144
