### ISSUE TITLE
Tenant scoped steps are returned from the deployment preview api

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#3847]
Tenant scoped steps are returned from the release deployment preview api when doing environment only deployment. These steps should not be included in the return result.
This api is mainly being used by the portal, but customers might use it as well

Steps to reproduce
* Add a deployment step to a project and scoped to a tenant tag
* Check the result by calling the api, http://[yourserver]/api/releases/[ReleasesId]/deployments/preview/[EnvironmentId]

**Comment by droyad** [comment]
@mayuanyang This sounds more like a bug (API is returning incorrect results) than a breaking-change (we change expected behaviour)

**Comment by mayuanyang** [comment]
This is fixed in frontend-refactor branch

**Comment by michaelnoonan** [comment]
Release Note: Fixed a bug with the `/api/releases/[ReleasesId]/deployments/preview/[EnvironmentId]` API which resulted in steps that are scoped to tenants to be returned for un-tenanted deployments
