### ISSUE TITLE
Extract packaging logic to standalone library

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3849]
Some time ago [Octopus forked NuGet](https://github.com/OctopusDeploy/NuGet.Client) due to a design decision on NuGet's side to drop trailing zeros in version numbers. This can cause issues in CI pipelines when a specific version is expected. 
Furthermore NuGet seems to now have a bug causing [invalid timestamps](https://github.com/NuGet/Home/issues/5240) to be stored when packaging which appears to have been present at the time of forking.
In addition to these NuGet issues we currently have packaging logic duplicated and spread out across multiple projects (Octo.exe, Calamari, Server) and so bug fixes in one area often do not spread to the others.
To simplify all this, it's proposed that we extract all packaging logic that we use to a standard `Octopus.Packaging` library and include an internal implementation of the NuGet packaging protocol to remove the hard dependency on them. (NuGet packages are effectively zips with some differences around file names and additional metadata)

**Comment by droyad** [comment]
This issue has merit, but customers won't see any changes. Closing this as it will be handled as part of internal engineering process.
