### ISSUE TITLE
Octopus.Tools Zip file is showing up a false positive in Defender

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3857]
On some machines the Octopus Tools Zip file downloaded from the web site is showing up in Windows Defender as containing a Trojan.

We've tested on different machines with the same definition versions in Defender and received correct and false positive results.

We've tested against versions of the file but locally and they show up as clean on all machines. Versions built by our build server are exhibiting the issue when downloaded directly from the build artifacts, so it doesn't look like the public website causing anything.

Investigations are ongoing.

**Comment by benPearce1** [comment]
I scanned the last few version of the Octopus Tools with Norton Security, virus definitions update to 13/10/2017, and there were not reported viruses.

**Comment by dieterv** [comment]
Got the same for https://download.octopusdeploy.com/octopus-tools/4.24.1/OctopusTools.4.24.1.zip with current windows defender definitions just this morning.

![image](https://user-images.githubusercontent.com/220082/31600429-b31eb018-b256-11e7-83f4-c0c8fd28ab5b.png)
![image](https://user-images.githubusercontent.com/220082/31600438-bc569d6c-b256-11e7-978c-73c6bf631ad4.png)

**Comment by dieterv** [comment]
I reported the file yesterday (via the "home customer" button) on https://www.microsoft.com/en-us/wdsi/filesubmission, got a clean scan result mail back this morning for definition version 1.253.851.0 and can confirm that everything is working as it should on both my computers previously exhibiting the false positive detection after updating defender definitions.

**Comment by benPearce1** [comment]
Confirmed locally that this is no longer reporting an issue in Defender. Also confirmed with release 4.24.2
