### ISSUE TITLE
Advanced deployment options incorrectly reads available machines

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3858]
Octopus 3.17.5

If you have multiple machines with one role and try to deploy a release to those machines, the deployment is done to each expected machine, but the advanced deployment options reads which machines are available incorrectly. This prevents users from being able to include/exclude some machines from the deployment. Steps I took to reproduce:

2 machines with the `web` role.

![1_machines](https://user-images.githubusercontent.com/20388190/31562587-6aff0188-b09f-11e7-8fde-a2113f9b0618.png)

Deployment step scoped to the `web` role.

![2_step](https://user-images.githubusercontent.com/20388190/31562593-6de2fef4-b09f-11e7-96c9-efbc4f286971.png)

Deployment is successful to both machines.

![3_successful_deployment](https://user-images.githubusercontent.com/20388190/31562598-70fd5468-b09f-11e7-95c3-81cd72ae7f5a.png)

In the advanced deployment options, `Tentacle 2` is crossed out, and is then unable to be selected in the include or exclude deployment targets section.

![4_advanced_options](https://user-images.githubusercontent.com/20388190/31562612-7363c9e4-b09f-11e7-9832-4d95813c8fc1.png)

Workaround is to manually change the roles for a specific deployment.

Source (private link): https://secure.helpscout.net/conversation/448615796/20102/

**Comment by pawelpabich** [comment]
@KennethBates can you confirm that this is still a problem in v4?

**Comment by KennethBates** [comment]
Testing in v4 with same repro steps and same project/configuration, and the behavior seems to have been fixed in the new UI.

![advanced_deployment_options_v4](https://user-images.githubusercontent.com/20388190/33160337-41b9a084-d067-11e7-9604-b5dbfc732db1.png)

Closing this ticket.
