### ISSUE TITLE
Update Azure PowerShell Modules

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3860]
The Azure PS Modules that we bundle with Calamari are out of date (I think the last time we updated them was circa Octopus v3.5?) ... 

Instead of just ad-hoc updates, we need a way of staying on top of these new releases so customers always have the latest version. Discuss with team-cloud about how to get something like this into our release pipeline.

The workaround for the time being is to install the latest version of the Azure PowerShell modules on your server and simply tell Octopus to use them instead (see [this documentation](https://octopus.com/docs/guides/azure-deployments/running-azure-powershell/configuring-the-version-of-the-azure-powershell-modules) for more details).

Source: https://help.octopusdeploy.com/discussions/problems/55689

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Azure PowerShell modules](https://trello.com/c/WKTH0Y8I/368-update-azure-powershell-modules)

**Comment by timpoth** [comment]
Bump on this

**Comment by thebigmoosey** [comment]
Release Note: Updating Calamari to include latest Azure PowerShell cmdlets

**Comment by thebigmoosey** [comment]
Hmm, I'm re-opening this to investigate. The `Octopus.Dependencies.AzureCmdlets` dependency is still unpacking version 3.4.0, even though we've updated the package reference to 5.1.1. Needs some investigation before next release.

**Comment by thebigmoosey** [comment]
Updated the dependency reference in Server as well, this should pull down the right package now. Will go out in next minor release.

**Comment by thebigmoosey** [comment]
After going through our testing today, there's still some more problems here between the Azure powershell modules and the Azure SDK. It seems we'll have to update the both of these things together, since Azure has moved some namespaces around / removed some powershell methods. We'll look at rolling this out with both SDK updates and some other changes we're planning for Azure accounts.

**Comment by thebigmoosey** [comment]
Release Note: Updating Azure PowerShell modules to 5.7.0
