### ISSUE TITLE
XML doesn't render in manual intervention instructions

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3862]
To reproduce:

- Create a manual intervention step
- Set the "instructions" to XML
 ![image](https://user-images.githubusercontent.com/171197/31639317-7425d13c-b31b-11e7-8824-148466aaeb19.png)
- Run the deployment
 ![image](https://user-images.githubusercontent.com/171197/31639335-868deb70-b31b-11e7-98de-5e6e1f4caa2f.png)

**Comment by tothegills** [comment]
See https://help.octopusdeploy.com/discussions/questions/14035

**Comment by droyad** [comment]
Instructions are Markdown. The new UI makes this clearer. So this is working as designed.
