### ISSUE TITLE
Viable release plan calculation incorrect for some projects

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3867]
The ReleasePlan's `ChannelIsMissingSteps` isn't taking into account non-package steps. I.e. if there are only non-package steps (all script steps) then the plan isn't considered viable, which isn't correct.

It may not be correctly accounting for disabled steps either, i.e it may consider the plan viable if there is a single disabled step.

Relates to #3618 

Source https://help.octopusdeploy.com/discussions/problems/60372

**Comment by slewis74** [comment]
Another report of this https://secure.helpscout.net/conversation/450644182?folderId=557077

**Comment by benPearce1** [comment]
This issue has been resolved in Octo.exe 4.24.2
