### ISSUE TITLE
Script modules written with incorrect encoding

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3873]
The change in https://github.com/OctopusDeploy/Calamari/commit/0c1e431d533f83bc288122b5fae6655556903cd1 causes particular characters (i.e. `“`) to be written incorrectly to file. Using the `CalamariFileSystem.OverwriteFile(string, string, Encoding)` overload to use `Encoding.UTF8` fixes the problem.

Source: https://help.octopusdeploy.com/discussions/problems/60747-upgrade-from-3175-to-3176-changed-content-in-script-module

**Comment by tothegills** [comment]
Release note: Fix an exception loading script modules containing certain characters
