### ISSUE TITLE
Detection of database in CreateDatabase command needs improving

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3877]
Source: https://secure.helpscout.net/conversation/443189290?folderId=969747 (private link)

At the moment, the create database command handles the "database doesn't exist, create it" and "database already exists" scenarios quite well.

However, if the database is exists, but is in single user mode / is in the process of being restored etc, or even if there are transient network issues, it will assume the database doesn't exist and try to create it.

We should make the "database exists" check smarter than the existing "did we get an exception when we tried to connect" to handle these situations better.

In a docker scenario (and as requested by a customer in the above ticket), it would be useful to have a flag to say "yes, the database definitely exists, but the container may not be up yet, please retry until you can connect (with a timeout)".

We potentially should:
* try connecting to master and check the `sys.databases` table to see if the database exists
* add better logging of the error faced
* add new flags `--retry-attempts 10` (and potentially a flag to control the delay between checks?)
* update the docker launch scripts to allow customers to opt into this behaviour

**Comment by droyad** [comment]
We don't think this issue will bubble to the top because it is fairly niche. If you disagree, comment below.
