### ISSUE TITLE
ReOpen #830: Make NoneInteractive Optional

### ISSUE THREAD

**Issue by nns-bizbrains** [OctopusDeploy/Issues#3878]
I am opening this issue https://github.com/OctopusDeploy/Issues/issues/830 again due to the fact that it does not seem to work or I can't figure out how to make it work.
I have looked a the closed milestone but the issue is not in it as stated in the issue.

**Comment by droyad** [comment]
@nns-bizbrains We do not provide support through this repo and do not actively monitor it. Please contact us via our [support issues](https://octopus.com/support)
