### ISSUE TITLE
Scoping of variables for step Run Conditions is not clear

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#3882]
When deploying, you have the option of deciding whether to run a step using [Run Conditions](https://octopus.com/docs/key-concepts/projects/deployment-processes#DeploymentProcesses-Conditions). 

This run condition can be bound to a variable expression. In this case, the variable expression will be evaluated with a particular scope. It is not clear what this scope will be, nor is it mentioned in the docs.

For example, imagine you have a step which deploys to multiple deployment targets using roles. In this case, you might want to disable the step for some machines but not for others. You might expect that the Run Condition variable expression for this step is evaluated multiple times, once for each deployment target scope. This is not the case, it is only evaluated once for the entire step, and therefore the scope that it is evaluated with does not include a specific deployment target.

So we should make it clearer what scope is used here, and how this run condition is evaluated. This might involve updating docs. Perhaps a dry-run feature might be sufficient, because there are other places in the app that might have the same issue.

**Comment by btrepp** [comment]
This got me,

I have an application that needs to go in the 'worker' role, but is different from the other workers projects we run as it isn't 12 factor-y, it has to have only one instance running.

I tried to use this to restrict the deployment to a specific machine name, but it always gets evaluated as false.

I've seen before that not being able to restrict projects to machines seems to really destroy the point of roles in larger octopus projects. You end up with roles

app1-worker
app2-worker
app3-worker
....

etc and may have 20+ roles on machines, which makes the UI hard to read.

**Comment by pawelpabich** [comment]
Feature request is tracked here: https://github.com/OctopusDeploy/Issues/issues/3206
Docs updated as part of: https://github.com/OctopusDeploy/Issues/issues/3820
