### ISSUE TITLE
Provide complete team list for users

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3889]
The Octopus API currently doesn't return any Team information for users. It would be useful to surface this information.

Behind the scenes Octopus knows which groups the authentication provider (e.g. AD or Azure AD) has returned for each user and it also knows which external groups have been assigned to teams, along with which users have been explicitly added to the teams. It uses all this knowledge to determine a "complete" list if teams the user is considered part of when determining permissions, but doesn't expose that list through any current APIs.

This information would be useful at times in the UI to help troubleshooting issues and some customers would like access to it via `Octopus.Client` too.

Source https://help.octopusdeploy.com/discussions/problems/61453

**Comment by slewis74** [comment]
One option under consideration is a new API to read the projected "complete" team list.

An extension of this may be new APIs to add/remove a single user to/from a team. This would allow the user UI to provide explicit team add/remove as well as viewing the list of non-explicit teams derived from external provider data.

**Comment by slewis74** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide complete team list for users](https://trello.com/c/LeTSCgjs/391-provide-complete-team-list-for-users)

**Comment by shaunmarx** [comment]
Release Notes: Test permissions now includes teams based on external group membership
