### ISSUE TITLE
Unable to create certyficate for custom template.

### ISSUE THREAD

**Issue by mmpyro** [OctopusDeploy/Issues#3891]
When new Step Template for service fabric deployment was created and I tried use existing certificate it wasn't present. When I tried create a new one. I was redirected to the new window and below message was showed.
The resource '{{vm.project.Slug}}' was not found.

For service fabric step inside project it work fine without problems. Choosing certificate doesn't work only for step template.
Environment:
OS Type: Windows 10
Web browser: Firefox
Instalation type: Single node with ms sql server 2014 on local machine

**Comment by matt-richardson** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: https://octopus.com/support.

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
