### ISSUE TITLE
Task cap shouldn't include tasks awaiting manual intervention

### ISSUE THREAD

**Issue by MichaelJCompton** [OctopusDeploy/Issues#3893]
Tasks awaiting human intervention aren't taking up resources and so shouldn't count against task cap.

See also (https://help.octopusdeploy.com/discussions/problems/61963)

**Comment by droyad** [comment]
Deployments awaiting Manual Intervention are in a `Queued` state, therefor already do not contribute to the task cap. When the intervention is resolved, the task will wait for an available slot.

Guided failure tasks however are still running, as it is possible only one part of deployment is waiting for human input, while other machines (or steps) are still actively deploying. Also once the human input is obtained, the task continues immediately without considering the task cap.

**Comment by BlythMeister** [comment]
For me, this was more a graphical issue whereby a human interaction would show other running tasks which confused users.

Not sure if this still shows in v4 as I've not upgraded yet.

**Comment by droyad** [comment]
@BlythMeister Is Issue #3827 what you were seeing?

**Comment by BlythMeister** [comment]
Oh yea, it's that one.  Sorry my mistake
