### ISSUE TITLE
Executing Tentacle.exe register-with via a Windows Service fails on Tentacle 3.15.8 or newer

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#3897]
**ISSUE**

If you have a machine with Tentacle installed and an instance configured, if you then try to perform a "register-with" action on Tentacle.exe via a windows service on Tentacle 3.15.8 or later the service fails to start.

NOTE: Running the commands directly (and not as a service) works correctly, this issue only occurs when attempting to run Tentacle.exe from a service.

**Replication**
Configure a 3.15.8 or newer Tentacle with an instance. Create a windows service with the following Powershell:
```
New-Service -Name "ODTentacleAnnouncer" -BinaryPathName """C:\Program Files\Octopus Deploy\Tentacle\tentacle.exe"" register-with --force --server=$OctopusServerUrl --apikey=$ApiKey --policy=$MachinePolicy --environment=$Environments --role=$Roles --publichostname=$GetLocalIPAddress --name=$LocalMachineName" -StartupType Auto -Description "Re-register the Octopus Tentacle upon machine restart."
```

When the service attempts to run it will fail and the following error will be written to your Tentacle logs:
```
2017-11-01 11:32:42.9883   1524      1 ERROR  ===============================================================================
2017-11-01 11:32:43.0350   1524      1 FATAL  The handle is invalid.

System.IO.IOException
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_Title(String value)
   at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown)
   at Octopus.Shared.Startup.OctopusProgram.Run()
2017-11-01 11:32:43.0663   1524      1 FATAL  -------------------------------------------------------------------------------
Terminating process with exit code 100
Full error details are available in the log files at:
C:\Octopus\Logs
C:\Windows\system32\config\systemprofile\AppData\Local\Octopus\Logs
If you need help, please send these log files to https://octopus.com/support
-------------------------------------------------------------------------------
```

Note: Creating this service against 3.15.2 or earlier Tentacle works correctly.

Original report: https://help.octopusdeploy.com/discussions/problems/59474-tentacle-auto-registration-issue-the-handle-is-invalid

**Comment by michaelnoonan** [comment]
I think this is a bug, and it was probably introduced when I made some changes to our command-line interface in Octopus 3.15.x.

**Comment by michaelnoonan** [comment]
I would highly recommend against configuring a Windows Service like this to configure a Tentacle on startup. It would be better to use a Windows Scheduled Task or another approach.

**Comment by tw17** [comment]
Release Note: Added a check to Tentacle to only set the window title when the process is run interactively.
