### ISSUE TITLE
Tenant Filter Issue in Project Overview Screen

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#3898]
**Octopus Deploy Version:**

3.17.11

**Issue:**

Within the Project Overview screen when applying a filter to tenant tags prior to filtering by release version you are presented with an error message, if you filter by release version first and then tenant tags second, this works as expected

**Replication Steps:**

1. Create a Project

![image](https://user-images.githubusercontent.com/33012349/32305879-c1186928-bfc3-11e7-81b9-74bb7feb2a17.png)

2. Connect Tenant to the Project

![image](https://user-images.githubusercontent.com/33012349/32305888-d18e54ca-bfc3-11e7-8e71-acc188baedc8.png)

3. Apply Filter to Tenants

![image](https://user-images.githubusercontent.com/33012349/32305891-d91d29e6-bfc3-11e7-82b1-28f9244c895f.png)

4. Apply the Filter for the Release

![image](https://user-images.githubusercontent.com/33012349/32305896-e632debe-bfc3-11e7-978f-5755b5c7e42b.png)

5. The Overview is replaced with the below error message

![image](https://user-images.githubusercontent.com/33012349/32305922-ff21b878-bfc3-11e7-9b0a-df3baa5e5ff0.png)

**Workaround:**

As a workaround, if you apply the release filter prior to filtering down to the Tenants/Tags this will work as expected.

**Sources:**

https://help.octopusdeploy.com/discussions/problems/62103

**Comment by NickJosevski** [comment]
Release Note: Fixed tenant tag filtering on project overview screen
