### ISSUE TITLE
Scope is removed from snapshotted variable value when environment is deleted

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#3901]
**Issue**

When you have a snapshotted variable as part of a release that has been scoped to an environment, when that environment is removed the variable remains in the snapshot however the _scoping_ is removed making the value global/un-scoped

**Replication**

Testing performing in 3.17.6

1. Create a testing environment [and add machines], project and lifecycle.
2. Create a variable that is scoped to the environment.
3. Create and deploy a release (which snapshots the variable).
4. Remove the environment (follow any prompts to delete the environment).
5. Note that the variable is correctly removed from the Project Variables, but it remains in the release snapshot, and the scoping of the variable has been removed. This makes the variable value "global scope" for that project, and it will be misinterpreted on any further deployments.

**BEFORE**

![image](https://user-images.githubusercontent.com/1627582/32359577-ba1a8c1e-c09a-11e7-9e58-175ae9e68d28.png)

**AFTER**

![image](https://user-images.githubusercontent.com/1627582/32359468-0a912c26-c09a-11e7-8070-89e82d112a2f.png)

![image](https://user-images.githubusercontent.com/1627582/32359453-f900ff86-c099-11e7-983a-e0bbeab75921.png)

**Comment by NickJosevski** [comment]
Not detrimental to re-deployments.

The UI is misleading, because the environment no longer exists it cannot display what it *was scoped to*.

But the snapshot data still points to the `Environment Id`, so when it does run it is it still scoped as it was and *not unscoped*.

**Comment by NickJosevski** [comment]
Release Note: Snapshot variables referencing deleted resourced will clearly state it's missing from the scope, instead of just not showing it
