### ISSUE TITLE
Migrator performance issues

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#3912]
We've had numerous support cases where a customer with a large 2.6 instance (1Gb+) was having trouble using the migrator to upgrade to 3.x.

The major complaint surrounding the migrator is that it is memory hungry. Often the memory profile would be 10x the size of the database, or more.

Memory isn't the only problem however. The migrator is also slow once all the memory is loaded.

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrator performance fixes](https://trello.com/c/RedTidmc/805-migrator-performance-fixes)

**Comment by distantcam** [comment]
Release Note: Major improvements to migrator memory and speed performance

**Comment by EvilTony** [comment]
Thank you for this one.  One of my teams wasn't upgrading because of this problem.  Keep up the good work guys.
