### ISSUE TITLE
Powershell bootstrap file runs out of variables

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#3913]
There's a default limit to the number of variables in a powershell session of 4096. This limit can be reached easily if there are a lot of certificates in the deployment process.

The bootstrapper script is the place where the variables are added to the session. It should detect if the limit is not enough and increase the limit by setting the `MaximumVariableCount` variable within powershell.

**Comment by MichaelJCompton** [comment]
Release Note: Increases number of possible PowerShell variables in scripts to maximum available.
