### ISSUE TITLE
v4 Release and Deploy button permission issues

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3928]
The Deploy and Create Release buttons are not taking into consideration finer-grain permissions where project or teams may be scoped to your role. The attached support issue shows how to reproduce, and I've confirmed by reproducing. Copying here:

> ## Unable to deploy a release if DeploymentCreate is scoped to a project
> 1. I've got a team set up with "Project Viewer" and "Release Manager" roles. The "Release Manager" role has the "DeploymentCreate" permission, giving ability to deploy an already-created relase
> 2. If I don't add a project to the team, I can navigate to my project's release page and see the "Deploy To..." button at the top right (projects/test-project/releases/0.0.1)
> 3. When I add a project to the team, I no longer see this button at the top right. 
> 
> ### Unable to view/create release if team with Project Viewer role is scoped to a tenant
> 1. I've got a team set up same as before ("Project Viewer" and "Release Manager") roles. 
> 2. I've got the team scoped to a single project
> 3. When I go to the project, I see the "Releases" link on the left. I see the "Create Release" button under the Project name on the left. Both of these things are expected
> 4. I then add a tenant to the team
> 5. When I go back to the project, I now see that I'm missing both the "Create Release" button and the "Releases" link.

There is also an issue where ReleaseEdit permissions are currently required to create a release.

And further issues reported (see other comments in the source thread below) regarding `ProcessView ` permissions causing problems in areas that (presumably) should not require ProcessView, need to investigate.
 
Source: https://help.octopusdeploy.com/discussions/problems/63498

**Comment by NickJosevski** [comment]
Release Note: Viewing releases and creating deploys for Tenanted projects will now factor in permissions correctly
