### ISSUE TITLE
Deployment to Offline drop target failed due to project name has file system unfriendly char

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#3929]
## Steps to replicate
1. Create a project with name includes any file system unfriendly char e.g. `/`
2. Add some variables
3. Add 1 step
4. Create a release and deploy

## Error message
The step failed: Activity script on Offline drop failed with error 'Could not find a part of the path 'c:\temp\Development\hhhh\0.0.1\Variables\Offline drop.hhhh\.script.variables.json'.'. 

A folder with the sanitized project name(`/` removed) is created, looks like different logic is being used for variable files

**Comment by droyad** [comment]
Release Note: Offline drops now removed invalid characters from the project and target names used for filenames
