### ISSUE TITLE
ProcessView permission missing from Project viewer role

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3932]
The `ProcessView` permission is missing from the built-in "Project viewer" role.

Many project-related screens require doing a lookup of the deployment process to confirm if there are any steps (else we show onboarding, or do other custom logic based on number of steps) …and if people assign external contractors as project viewers, a lot of things are hidden or explode in the UI due to that missing ProcessView permission

In the past (in support) we’ve told people “oh you need to add `ProcessView`“, and they add it and it's all sorted, but it feels like that should just be part of the built-in “Project viewer” role so we need to add this.

We will _not_ provide an upgrade script in case existing customers are expecting the process to be hidden for "Project viewers", but new installations moving forward will get this out-of-the-box. Which means, any existing customers facing this problem will need to manually edit their "Project viewer" role and add the "ProcessView" permission.

Source: https://help.octopusdeploy.com/discussions/problems/63498-402-permission-problems (see Paul comment).

**Comment by michaelnoonan** [comment]
Release Note: For all new installations of Octopus Server, the `ProjectViewer` user role will be granted the `ProcessView` permission by default

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ProcessView permission missing from Project viewer role](https://trello.com/c/YDsY5ZjR/816-processview-permission-missing-from-project-viewer-role)
