### ISSUE TITLE
Security Issue: User Role Permission 'VariableEdit' allows editing of 'UnscopedVariables' when User Role Permission of 'VariableEditUnscoped' is not selected

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#3933]

**Comment by johnsimons** [comment]
This appears to be by design and looks like a misunderstanding around permissions, rather than an issue.
We will update our documentation to clarify the use of  `UnscopedVariables` permission in combination with `VariableEdit`.
