### ISSUE TITLE
Pause estimated deployment time during guided failure.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3936]
During a guided failure interrupt on a deployment the time elapsed for the deployment continues to calculate, leading to incorrect estimate on the next release for the same project.

Referring to the following text on an active deployment.
>This task started a few seconds ago and should finish in 30 seconds

The same notification seems to be paused during a manual intervention step.
Let me know if you would like some more info or a demo.

Source: https://help.octopusdeploy.com/discussions/problems/63534

**Comment by droyad** [comment]
The estimated time is a guide only. We also don't keep track of time in manual intervention, so this would required some effort to implement. Closing this we are not likely to get to it.
