### ISSUE TITLE
/api/useronboarding is slow when there are lots of deployments in the system

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#3939]
The `/api/useronboarding` call pulls in all the `DeploymentProcess` objects to check if any step required a package. This is causing memory issues once the system has a lot of deployments, or the deployments are large memory objects (lots of embedded scripts, lots of steps).

# Root cause

Every time the Octopus Web UI loads in the browser it makes an initial call to the `/api/useronboarding` endpoint. If you have a very large installation of Octopus this can be a very expensive call. Then scale that out across potentially hundreds of users coming in to work in the morning and loading Octopus.

# Suggested solution

Once you have completed a step of the user onboarding, like creating a project, we can assume you don't need our help to do that step again. We are planning to remember as soon as you check off each step in the onboarding process. This means we will only run the (potentially) expensive queries for the pieces of onboarding you haven't completed by that point in time.

This means when people start the Octopus UI, it will still make a GET request to `/api/useronboarding` - but the resulting query will be very cheap, instead of blindly loading every deployment process in existence. :)

**Comment by michaelnoonan** [comment]
Please also change the query for `DeploymentProcess` to include `WHERE Frozen = false` so it's ignoring any snapshotted processes.

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Useronboarding has performance issues](https://trello.com/c/crQRvzAb/819-useronboarding-has-performance-issues)

**Comment by michaelnoonan** [comment]
Release Note: Fixed a performance problem with very large installations related to the on boarding features we shipped in Octopus 3.12, which would cause high memory use and higher load on the Octopus database
