### ISSUE TITLE
V4 Variable editor not showing new lines like in V3

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#3948]
V3
![image](https://user-images.githubusercontent.com/119096/33109235-21bccf6c-cf8c-11e7-9ced-d22d610e9ddf.png)

![image](https://user-images.githubusercontent.com/119096/33109295-800d740e-cf8c-11e7-9843-eecb39ae72c7.png)

Reported here (private link): https://secure.helpscout.net/conversation/472455720?folderId=557082

V4
![image](https://user-images.githubusercontent.com/119096/33109269-5d17ff8c-cf8c-11e7-8273-ac6d95182026.png)

It is there via the edit modal:
![image](https://user-images.githubusercontent.com/119096/33109281-6d6c84c0-cf8c-11e7-9208-cff0b583905d.png)

**Comment by pawelpabich** [comment]
Let's wait for more user reports

**Comment by NickJosevski** [comment]
This hasn't come up as a problem for anyone. 

Closing as won't fix, if it gets reported by a customer can re-open and fix.
