### ISSUE TITLE
Cannot bind SSL thumbprint field to variable in IIS bindings dialog

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3957]
The UI is currently stripping characters.  So, for example, when `#{Acme.Https.Certificate}` is entered, it is being modified to `AcmeHttpsCertificate`.  

This obviously prevents the successful deployment of the website.

As reported in: https://help.octopusdeploy.com/discussions/problems/63976

**Comment by pawelpabich** [comment]
Release Note: Now we don't strip invalid characters when SSL thumbprint in IIS Step is bound to a variable
