### ISSUE TITLE
Process to update Octopus to use SHA256 certificates is difficult

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/Issues#3967]
# Issue
Currently the process to upgrade the Server and Tentacle certificates to use SHA256 cipher suite (instead of the old SHA1) is difficult to run through in an existing environment. At this point, you need to coordinate an upgrade across every machine that Octopus knows about at the same time - see [docs](https://octopus.com/docs/how-to/how-to-use-custom-certificates-with-octopus-server-and-tentacle) - but this is super painful when you have more than a handful of machines.

While we [don't believe](https://octopus.com/blog/shattered) that using SHA1 is a security concern, we are aware that many security scanning tools flag this up as a concern, and some audits / security teams flag this as a PCI issue.

While it _appears_ that PCI does not put a blanket ban on SHA-1, [this sysnetgs.com article](https://sysnetgs.com/2016/09/sha-1-the-pci-councils-views-revealed/) says:
> The PCI Council’s FAQ also notes that uses of SHA-1 in certain cases may result in ASV Scan failures.  The reality is that businesses will need to migrate away from using SHA-1 signed digital certificates or risk failing their quarterly ASV scans after 1st January 2017.  If a business cannot yet move away from using SHA-1 signed certificates they will need to go through a formal process with their ASV to ensure that the affected system is not susceptible to the particular vulnerabilities or that compensating controls are in place to reduce or eliminate the risk of the SHA-1 vulnerability.

(That [article](https://sysnetgs.com/2016/09/sha-1-the-pci-councils-views-revealed/) has some good links to the NIST guidance which appears pretty comprehensive).

Finally, in our [blog post on shattered](https://octopus.com/blog/shattered), we promised a fix and that we'd try and have it done with 90 days of the vulnerability being announced in Feb 2017.

# Customer requests
Multiple customers have asked for help on this: 
https://help.octopusdeploy.com/discussions/problems/57302
https://secure.helpscout.net/conversation/418596232/18615?folderId=557082 (Internal Link Only)
https://secure.helpscout.net/conversation/387381001/16731?folderId=557082 (Internal Link Only)
https://secure.helpscout.net/conversation/474103745/21334?folderId=557080 (Internal Link Only)

# The difficulties
As the communication channel from Server to Tentacle is using this certificate, its difficult to change this on the fly, especially as the communication channel has to be restarted with the new certificate. 
Another question is how would this functionality be surfaced in the UI? It doesn't feel like it has an obvious home.

# Proposed Solution
The code for Polling Tentacles currently has support for multiple certificates, but for Listening Tentacles, it does not. We should add multiple certificate support for Listening Tentacles in Halibut, and also a way to modify the certificate and to allow the certificate to be changed without tearing down the connection. Then, we'd run one of two tasks to update the certificates:

## Server certificate:
1. generate a new certificate
1. save it on the server as a "secondary" certificate 
1. run a task on all tentacles to trust the new cert thumbprint
1. run some kind of validation that they can all communicate with the new certificate
1. run a task on all tentacles to remove the old thumbprint
1. remove the old cert from the server

## Tentacle certificate
1. get the Tentacle to generate a new certificate
1. save it on the Tentacle as a "secondary" certificate
1. pass the thumbprint to the server, and get the server to trust the "secondary" thumbprint for that Tentacle
1. run some kind of validation task to ensure the communication works with the new certificate
1. get the Tentacle to remove the old certificate
1. get the server to remove the old thumbprint

**Comment by michaelnoonan** [comment]
At this point in time we have decided to close this issue. We get very few questions about it, and the effort to implement a built-in feature to achieve this turned out to be a lot more effort, especially when compared to the real-life value it offered.

If you find this issue, and absolutely must change to use `SHA256` certificates, please follow the steps in the issue description under `Proposed Solution`.

If you have any problems with that, or want to talk about it, we are more than happy for you to get in touch! https://octopus.com/support
