### ISSUE TITLE
Kaspersky detects Calamari 4.0.x as trojan

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3968]
3 customers with this issue:
https://help.octopusdeploy.com/discussions/problems/63521
https://help.octopusdeploy.com/discussions/problems/64241

Kaspersky detects Calamari `4.0.2` and `4.0.3` as `Trojan.MSIL.Miner.vvk`

Nothing big has changed in the source code.

**Comment by droyad** [comment]
**Workaround**

To work around this issue, download `Calamari` and `Calamari.Azure` packages from the links below (I've included the last two versions before `4.0.2`.

Then follow [these](https://github.com/OctopusDeploy/Calamari/blob/master/README.md#usage) instructions to use those versions with the latest version of Octopus.

Please remember to run the commands to revert to the bundled package when you upgrade Octopus Server, otherwise it will continue to use the set package.

**4.0.0**
https://octopus.myget.org/F/octopus-dependencies/api/v2/package/Calamari.Azure/4.0.0
https://octopus.myget.org/F/octopus-dependencies/api/v2/package/Calamari/4.0.0

*3.7.116*
https://octopus.myget.org/F/octopus-dependencies/api/v2/package/Calamari.Azure/3.7.116
https://octopus.myget.org/F/octopus-dependencies/api/v2/package/Calamari/3.7.116

**Comment by droyad** [comment]
Both `Calamari.exe` `4.0.2` and `4.0.3` scan as safe via the https://virusdesk.kaspersky.com website, perhaps they have already updated their definitions. Please comment below if you come across this problem with up to date definitions.

![image](https://user-images.githubusercontent.com/1687639/33191259-356bf4f2-d103-11e7-9141-b7415cd031e9.png)

![image](https://user-images.githubusercontent.com/1687639/33191278-6f3e1688-d103-11e7-979e-ef22c7359106.png)

**Comment by droyad** [comment]
Two more reports: https://help.octopusdeploy.com/discussions/problems/64387-kaspersky-antivirus-is-detecting-calamariexe-v-403-as-unwanted-software-trojanmsilminervvk-on-some-servers

I ran `Calamari.exe` `4.0.3` through their online scanner again and it came back as safe. I can't find any other way to submit the file to them.

**Comment by Know1** [comment]
Just upgraded to 4.04 and it is being flagged as well.
![image](https://user-images.githubusercontent.com/7904452/33360050-0ea38d2c-d526-11e7-8402-35e3aa95d311.png)
Reports as a virus on Kaspersky at least reported to them that it's not, but something has raised alarms

Weirdly virustotal says it's OK
https://www.virustotal.com/#/file/02ffec628b1c2af88708272a764b5a6bb9a6c06f6bb75045c525f0e001ce3e38/details

**Comment by droyad** [comment]
I tried out `4.0.4` on VirusDesk and it also came up as infected. I've also submitted it, hopefully they will get back to me soon. `4.0.3` still comes up as clean.

**Comment by droyad** [comment]
We have finally heard back from Kaspersky, they say it's a false positive and will fix it.
