### ISSUE TITLE
V4.0.6 Tenant checkbox variables aren't showing correct value unless bind button clicked to set it to false

### ISSUE THREAD

**Issue by ilyansolo** [OctopusDeploy/Issues#3970]
Hi, just upgraded Octopus 3 to 4.0.6 and i found that my Tenant Variables template is now doesn't work properly on existing or new tenants.

Steps to reproduce:
Create a new tenant variables template with ckeckbox and default value = false
Create a new project and link the variables template from above
Create a new tenant and link it to the project from above
Open Tenant->Variables->Common Variables->linked variable template
Click checkbox to set it to true->save
unforld linked variable template, checkbox expected to be CHECKED
UNCHECK variable->save
unforld linked variable template, checkbox expected to be CHECKED despite being set to false in previous steps

**Comment by pawelpabich** [comment]
Hi,

Thanks for getting in touch! I've reproduced your problem and it looks like a UI problem. The correct data seems to be sent to the server. We will have a look at it.

That being said, we have discovered this issue by accident as we don't actively monitor GitHub issues.  Next time, please [contact support](http://octopusdeploy.com/support) directly.

Regards

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checkobx parameter input doesn't reflect underlying value](https://trello.com/c/hhGFqN0Q/909-checkobx-parameter-input-doesnt-reflect-underlying-value)

**Comment by pawelpabich** [comment]
Release Note:  Checkbox can now be unchecked in Action Template Parameters
