### ISSUE TITLE
Form accessibility - increasing contrast of form elements and other components

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#3990]
It's been commented internally and externally that the forms are to light and need more contrast.  

We want to address the accessibility issue for the following components:
- All form elements
- Removable lists
- Disabled form elements
- Disabled state buttons
- Expanded and section divider

**Ideas**
- Increasing the font weight of labels
- Override the default material underline color with our darker grey
- Introducing a darker grey for notes
- Change default button to be our darker grey background with white text. Because the action buttons are strong they should still be enough contrast to tell it is disabled.
- Darken the diving line between sections, lists, and tables
- Change the default color for disabled form element to the darker grey _(this works on radio buttons and checkboxes but needs to be investigated more for disabled text and select fields)

<img width="1148" alt="screen shot 2017-11-28 at 4 11 12 pm" src="https://user-images.githubusercontent.com/17240784/33304945-72a15b58-d457-11e7-8971-3bfca6364308.png">
<img width="1149" alt="screen shot 2017-11-28 at 4 17 05 pm" src="https://user-images.githubusercontent.com/17240784/33304988-a8ec2a94-d457-11e7-93af-fdad2545f493.png">

Live demo: https://formaccessibility.octopushq.com

**Comment by pawelpabich** [comment]
Can you show examples of primary button that are enabled and disabled?

**Comment by jess-ross** [comment]
Example of save button going from disabled state to active state.
![nov 29 2017 9_26 am - edited](https://user-images.githubusercontent.com/17240784/33349945-297d5cf6-d4e8-11e7-9dd4-1b9c5c7ecc69.gif)

**Comment by jess-ross** [comment]
List titles, side menu active item, and first column text could be a heavier weight font to show better visual hierarchy and contrast. Especially when most titles are links in the blue color and the following text is a dark grey, when viewed in grayscale the emphasis on the title is lost. A heavier font weight will help.

Source (private): https://secure.helpscout.net/conversation/478045634?folderId=557082

### Ideas for improving text hierarchy shown in rgb and rgb-blind(Grayscale):
**List titles**
![process](https://user-images.githubusercontent.com/17240784/33467173-4c60edc0-d69e-11e7-9128-daca2ac31bb9.jpg)
**Side menu active item**
![side menu](https://user-images.githubusercontent.com/17240784/33467180-5a696f3c-d69e-11e7-984d-54f061ac0dbf.jpg)
**First table column**
![table](https://user-images.githubusercontent.com/17240784/33467192-6fc0341a-d69e-11e7-8197-acd363c46d57.jpg)

**Comment by jess-ross** [comment]
These changes can be viewed in our permanent instance 
**[https://formaccessibility.octopushq.com](https://formaccessibility.octopushq.com)**

**Comment by maarten-kieft** [comment]
Hi Jess,

Thanks for your response in the blog post. First let me point out that octopus is a great product and I truly believe that you guys are doing your best to make it even better. I noticed your demo / test environment.  My point is that if you are using octopus with a little more content it becomes to heavy. So instead of adding more contrast, I would like to suggest to reduce it a little. This is for example a small dashboard I'm currently using:

![image](https://user-images.githubusercontent.com/23722841/33835432-bdafebc6-de86-11e7-9594-0e0ea85e5f5f.png)

I have a hard time to really read what it says. Just to much screaming for my taste.

**Comment by jess-ross** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI accessibility - focus on contrast and hierarchy of elements](https://trello.com/c/VLTxrENr/959-ui-accessibility-focus-on-contrast-and-hierarchy-of-elements)

**Comment by jess-ross** [comment]
Release note: Increased contrast of form elements and content hierarchy
