### ISSUE TITLE
Octopus Deploy application from the Azure Marketplace does not install successfully

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/Issues#3997]
Using the azure marketplace to install a VM running the Octopus Deploy server does not successfully complete the installation. 

## Support discussions relating to this issue:
https://help.octopusdeploy.com/discussions/problems/64253
https://secure.helpscout.net/conversation/476696185/21490?folderId=567283 (Private Link)

## Underlying issue:
The Install-OctopusDeploy.ps1 script was updated to support the installation of Octopus V4 however the Azure Marketplace is in the process of updating in the Azure gallery.

## Temporary Workarounds
1. Install [Azure Powershell](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-5.0.0 ) prerequisites.
2. Clone this [azure-marketplace](https://github.com/OctopusDeploy/azure-marketplace) repository to your local system drive then browse to the directory containing the `mainTemplate.json` file.
3. Using Azure PowerShell, authenticate to Azure and select your desired subscription if applicable.
4. Create an empty resource group
5. Deploy the `mainTemplate.json` ARM Template to the empty resource group you created in step 4.

The script below will perform steps 3 to 5 from above:
Please change the values as necessary to suit your environment, especially the passwords.
```
$ResourceGroupName = "Octopus-marketplace-rg1"
$TemplateFile = ".\mainTemplate.json"

$octopusAdminPassword = ConvertTo-SecureString -String "P@ssword!pleasechangeme" -AsPlainText -Force
$sqlAdminPassword = ConvertTo-SecureString -String "P@ssword!pleasechangeme" -AsPlainText -Force
$vmAdminPassword = ConvertTo-SecureString -String "P@ssword!pleasechangeme" -AsPlainText -Force

$ParameterObject = @{
    "octopusDnsName" = '<your desired dns prefix>'
    "licenseFullName" = '<your name>'
    "licenseOrganisationName" = '<your organisation>'
    "licenseEmailAddress" = '<your email address>'
}

Login-AzureRmAccount

Select-AzureRmSubscription -subscriptionId '<SUBSCRIPTION_ID>'

New-AzureRmResourceGroup -Name $ResourceGroupName -Location "australiasoutheast"

New-AzureRmResourceGroupDeployment -Name "octopusdeploy" `
                                   -ResourceGroupName $ResourceGroupName `
                                   -TemplateFile $TemplateFile `
                                   -TemplateParameterObject $ParameterObject `
                                   -octopusAdminPassword $octopusAdminPassword `
                                   -sqlAdminPassword $sqlAdminPassword `
                                   -vmAdminPassword $vmAdminPassword
```

You may now browse to your new Octopus instance, either via public IP address or the dns hostname you specified in the script (For example: `<your desired dns prefix>.australiasoutheast.cloudapp.azure.com`) The default administrator username is `admin`

**Comment by lawrencewilson** [comment]
The Azure Marketplace offering of Octopus has been updated and is functioning properly.

**Comment by JudedeDude** [comment]
For security reasons my company will not use a static IP address associated to the VM. NSG rules still allow the vm to reach the www however its not determined what the NATed external IP address would be until you login to the server.

We are deploying to North Europe
Without adding the complete IP subnet Range to the firewall rules for SQL server, how else can this be achieve?
