### ISSUE TITLE
Getting started guide can crash 

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4010]
## Summary
Impacts all versions of v4, exists in v3, but lower impact. 

If you make < 5 projects create a release on one of them, and keep going you won't hit this issue on a clean install.

We load only 5, because that's what we chose ages ago, `this.projects = projectsData.Items.slice(0, 5);`

In a separate API call we load releases then try to match them, if the first is on a project not in that initial 5 then 💥 .

![image](https://user-images.githubusercontent.com/119096/33415801-da0702e6-d5e4-11e7-9e2f-4f41090ffd7a.png)

## Workaround

Create a release on one of your earlier projects, using the API.

Open the developer tools and attempt to issue the `dismiss()` on the getting started guide.

**Comment by johnsimons** [comment]
Release Note: Getting started no longer crashes Octopus if the first release is not on one of the first 5 created projects
