### ISSUE TITLE
Update OctoPack with latest version of NuGet

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#4013]
NuGet 4.6 has some fixes for things like preserving timestamps (https://help.octopusdeploy.com/discussions/problems/64682/r?go=aHR0cHM6Ly9naXRodWIuY29tL051R2V0L0hvbWUvaXNzdWVzLzUyNDA=). To incorporate these changes into OctoPack we will need create a custom build of NuGet that supports the custom version strings used by Octopus.

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update NuGet in OctoPack](https://trello.com/c/Y5tmQGPH/473-update-nuget-in-octopack)

**Comment by zentron** [comment]
Linked Issue: https://github.com/OctopusDeploy/Issues/issues/4013

**Comment by droyad** [comment]
We recommend using zip files if you are affected by this problem
