### ISSUE TITLE
v4 Project Overview permission scoping problems

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4016]
Due to a recent permissions change, EnvironmentView permissions that are scoped to a given environment now cause the Project Overview to be blocked by permissions warning.

The EnvironmentView permissions required here should have `wildcard:true`.

Cause of regression was from this PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/1590/files (my bad, I reviewed this PR, sorry 😊 )

Source: https://help.octopusdeploy.com/discussions/problems/64691

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [v4 Project Overview permission scoping problems](https://trello.com/c/XquiBu1j/981-v4-project-overview-permission-scoping-problems)

**Comment by thebigmoosey** [comment]
Release Note: Updating project overview to include wildcard for finer-scoped EnvironmentView permissions

**Comment by NickJosevski** [comment]
Damn I missed the `wildcard` sorry about that, even after doing and reviewing so many still making these mistakes :(

**Comment by thebigmoosey** [comment]
@NickJosevski I missed it in review too, it was just one of those weeks :)
