### ISSUE TITLE
Force deployment of packages option is missing from create release

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#4024]
In the v3 Portal, if the project settings option `Package re-deployment` was `Skip any package step that is already installed`, on the deployment preview screen an option `Force deployment of packages that are already installed` would appear:

![image](https://user-images.githubusercontent.com/1687639/33533365-5ae85680-d8ec-11e7-9d89-b1c601c49527.png)

v3 portal code: https://github.com/OctopusDeploy/OctopusDeploy/blob/master/portal/app/areas/projects/deployment-create/options.html#L27

This is no longer the case in v4.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Force deployment of packages option is missing from create release #4024](https://trello.com/c/daXWviBU/996-force-deployment-of-packages-option-is-missing-from-create-release-4024)

**Comment by pawelpabich** [comment]
Release Note:  Added missing option to re-deploy already installed packages
