### ISSUE TITLE
Variable Details UI lets you save a Certificate variable without linking it to a valid certificate in the library

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4025]
## Summary

You can have entered a value in the plain text variable, switch it to type certificate, and **not select** a certificate, it will treat the text value as an Id and fail when it tries to load, due to a related bug in showing the error when it can't find a certificate this was difficult to track down.

The entered data is stored against the state for the `value` and isn't being cleared, and we don't check if you made a selection of a certificate, allowing this invalid state.

In V3 you could not achieve this via the UI.

## Example

![bad cert with error](https://user-images.githubusercontent.com/119096/33535924-7b9101c4-d8fc-11e7-8ee8-2fd6f8b470fc.gif)

**Comment by TomPeters** [comment]
Just to clarify, this isn't actually invalid state right? There are other ways you can get to this state, eg by setting the value to something invalid through the api. Or by deleting the certificate that a variable references. Might be nice to improve that nasty exception message during deployment as well :) (maybe a separate fix)

**Comment by TomPeters** [comment]
I can also still set the id manually like this:

![2017-12-05_08-34-20](https://user-images.githubusercontent.com/1892715/33579952-2dcc4d0e-d997-11e7-9b16-b00219af991d.gif)

**Comment by NickJosevski** [comment]
The new behavior looks like this now:

![change to cert launches modal](https://user-images.githubusercontent.com/119096/33750814-2fecae02-dc22-11e7-9621-f82759f9546b.gif)

**Comment by NickJosevski** [comment]
Release Note: Better experience when changing variable type to certificate.
