### ISSUE TITLE
Make it even easier to perform the right tenanted deployments

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#4029]
In Octopus 4.x we've reworked the entire "Deploy Release" screen to make it scale better when deploying a release across multiple "scenarios" all at once. We've still got room to improve this experience.

Relates to https://github.com/OctopusDeploy/Issues/issues/3950
Relates to https://github.com/OctopusDeploy/Issues/issues/3951

# Examples

Here are some examples we want to make much easier, because they are very common.

I will provide some screen mockups tomorrow. :)

## Example 1: Deploy a brand new release 1.2.5 to the Production environment for all Tenants

1. Choose release 1.2.5
2. Click Deploy to Production
3. Click Deploy

_No tenants have 1.2.5 yet - it's not even on the dashboard_

## Example 2: Deploy 1.2.5 to the Production environment for all Tenants where 1.2.5 is not the current release on the dashboard (already deployed 1.2.5 to some Tenants)

1. Choose release 1.2.5
2. Click Deploy to Production
3. Click Deploy

_Octopus would already know where 1.2.5 is the current release and only create deployments for the Tenants where 1.2.5 is not the current release on the dashboard_

## Example 3: Deploy 2.0.0-beta.1 to the Beta environment for all Tenants who have opted in for the beta program (via channels)

1. Choose release 2.0.0-beta.1
2. Click Deploy to Beta
3. Click Deploy

_Octopus already knows which Tenants have opted in for the beta program, because the Channel has been associated with certain Tenants_

## Example 4: Re-deploy 1.2.5 to the Production environment for all Tenants, regardless of their current version on the dashboard

1. Choose release 1.2.5
2. Click Deploy to Production
3. Select "deploy to all selected tenants" or similar
4. Click Deploy

_Octopus would ignore the current state of the dashboard, and create a deployment for the Production environment for all tenants, effectively redeploying 1.2.5_

## Example 5: Deploy 1.2.5 to the Production environment for Tenant-A and Tenant-B

1. Choose release 1.2.5
2. Click Deploy to Production
3. Select Tenant-A and Tenant-B
4. Click Deploy

_Octopus would consider the fact that you've specifically selected Tenant-A and Tenant-B as fact: you want to deploy release 1.2.5 regardless of the state of the dashboard_

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it even easier to perform the right tenanted deployments](https://trello.com/c/gw8tcKri/847-make-it-even-easier-to-perform-the-right-tenanted-deployments)

**Comment by matt-richardson** [comment]
One that I'd love to see easier is "Deploy the latest to Tenant-A". One thing that annoys me is having to select the version I want deployed before hitting deploy.

**Comment by MJRichardson** [comment]
Superceded by https://github.com/OctopusDeploy/Issues/issues/4112
