### ISSUE TITLE
Apply included\excluded deployment targets to deployments for all tenants

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#4038]
## Problem
On the deploy release page, when deploying to many tenants, if you want to include\exclude the same deployment target\s for all deployments this currently involves expanding each deployment individually and modifying the Deployment Targets settings.

This is rather laborious when deploying to a large number of tenants.

## Proposed Solution

We could add a _Apply to all deployments_ button in the Deployment Targets section which would copy the included\excluded targets to each pending deployment.

For example: 

![apply-to-all-deployments](https://user-images.githubusercontent.com/113759/33606925-e3be5648-da0a-11e7-9ca9-09288bef087a.png)

The button could be displayed only if the selected machines were available for all deployments.

Requested by: https://help.octopusdeploy.com/discussions/problems/64420 (private link)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apply included\excluded deployment targets to deployments for all tenants](https://trello.com/c/TCw3NsYp/853-apply-included-excluded-deployment-targets-to-deployments-for-all-tenants)

**Comment by zentron** [comment]
Closing ticket unless issue raised by customer
