### ISSUE TITLE
Migration will fail if two projects with different name but the same Slug

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#4042]
## Issue
2 projects from 2 different servers with different name can resolve to the same `Slug` e,g `ES_DB_Backup` and `ES DB Backup` both resolve to `es-db-backup`, during migration, Slug is not regenerated and will fail on the unique index constraint check and cause the migration stopped

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migration will fail if two projects with different name but the same Slug](https://trello.com/c/wYVZ7utu/26-migration-will-fail-if-two-projects-with-different-name-but-the-same-slug)

**Comment by MJRichardson** [comment]
There have been no recent reports of this issue, and we have added a more informative error message.
And the data can be manually manipulated if necessary.
Closing for now.
