### ISSUE TITLE
v4 Task interruptions are not visible by anyone who does not have InterruptionViewSubmitResponsible permissions

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4044]
For users who do not have `InterruptionViewSubmitResponsible` permissions, interruptions to do get shown, so they end up looking at a deployment task that just appears paused with no way to action anything.

We should still show the intervention for all users with `InterruptionView` permissions, but only show the action/submission buttons to users with `InterruptionViewSubmitResponsible` permission, so all users with view permissions are _aware_ that there's an interruption waiting to be actioned, but only people with Submit permissions can action them.

### Potential Solution
We could change the `InterruptionViewSubmitResponsible` permission from the `interruptionsPromise` in Task.tsx to `InterruptionView` (so all users with view permission can still see the interruption), and move this `InterruptionViewSubmitResponsible` into the `Interruption` component itself (around its action buttons).

Source: https://help.octopusdeploy.com/discussions/beta-testing-feedback/664

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [v4 Task interruptions are not visible by anyone who does not have InterruptionViewSubmitResponsible permissions](https://trello.com/c/S00kU2W5/890-v4-task-interruptions-are-not-visible-by-anyone-who-does-not-have-interruptionviewsubmitresponsible-permissions)

**Comment by NickJosevski** [comment]
We have changed the `Project Viewer` to have the `InterruptionView`, back before 2019.1 this wouldn't have solved the problem.

The problems raised by this issue are addressed 2019.1 and polished off in a fix in:  https://github.com/OctopusDeploy/Issues/issues/5289

Closing this issue as the changes in 2019.1.x make this area better in line with making it more consistent.
