### ISSUE TITLE
Tentacle upgrade task does not wait for any deployments running on a machine before executing

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#4054]
This can cause deployments to fail due to the Tentacle restarting mid-deployment.

Source (private): https://secure.helpscout.net/conversation/482212886?folderId=557077

**Comment by droyad** [comment]
Duplicate of #4088?

**Comment by alfhenrik** [comment]
Hmm...looks like it, will close this one as I referenced the #4088 in the support ticket
