### ISSUE TITLE
'User invite' side menu link not showing and flashing when other menu items are clicked

### ISSUE THREAD

**Issue by jess-ross** [OctopusDeploy/Issues#4055]
In the Configuration side menu, User Invites isn't appearing. When a side menu item is clicked the User Invite menu item flashes at the bottom of the list.

Citrix and tested on latest browser versions of Chrome, Edge, IE11
Permissions: admin

Alex and I couldn't recreate the issue on macs and on VM 

![ezgif com-crop](https://user-images.githubusercontent.com/17240784/33750479-f34adb1a-dc1f-11e7-89e5-5b688bcc75c1.gif)

**Comment by pawelpabich** [comment]
Duplicate: https://github.com/OctopusDeploy/Issues/issues/4061
