### ISSUE TITLE
Configuration "User Invites" option flickers during navigation

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#4061]
To repro, you must have no authentication providers configured that support password management. I.e. `document.AnyAuthenticationProvidersSupportPasswordManagement` is `false`

![image](https://user-images.githubusercontent.com/1892715/33812913-57e1cb76-de6c-11e7-894a-a19348305d63.png)

This is because we reload this data everytime we navigate, instead of just loading it once. (`ConfigurationLayout`)

**Comment by pawelpabich** [comment]
Another report: https://github.com/OctopusDeploy/Issues/issues/4061

**Comment by NickJosevski** [comment]
Was fixed by: https://github.com/OctopusDeploy/Issues/issues/4055
