### ISSUE TITLE
Allow the built-in worker to run as a specific user account

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#4070]
When Octopus runs a script on the Octopus Server (for Azure Steps, or Cloud Regions, etc) it executes `calamari.exe` using the same user account the Octopus Server is running as. Out of the box this is highly privileged `LocalSystem` account. We recommend people use a different account specifically designed for Octopus Server, but again, people can run custom scripts on the Octopus Server as that user.

Until we make it possible to offload this work onto another server, an interim step we can take is to let people configure a user account on the Octopus Server specifically designed for running `calamari.exe` on that server.

# Proposed solution

We are referring to the thing that runs tasks on the Octopus Server as the "built-in worker". So let's make an `Octopus.Server.exe` command for configuring a custom user account, like:

`Octopus.Server.exe builtin-worker --username="username" --password="password"`

- [x] Change the `SilentProcessRunner` so it can launch processes as another user
- [x] Allow each Octopus Server node to configure the user credentials to use when running `calamari.exe` on that machine
- [x] Make sure it works as advertised on the box

# Long-term plan: workers

Please see this related issue which will supersede some of this in a future release: https://github.com/OctopusDeploy/Issues/issues/4158

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Run Calamari.exe as a different user account on the Octopus Server](https://trello.com/c/k63rOSlX/872-run-calamariexe-as-a-different-user-account-on-the-octopus-server)

**Comment by droyad** [comment]
UserVoice: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/20157787-make-run-on-octopus-server-a-separate-permission

**Comment by michaelnoonan** [comment]
Release Note: The built-in worker, which executes deployment steps and scripts on the Octopus Server, can now be configured to run using a different, lower-privileged user account

**Comment by droyad** [comment]
I am expecting the option for an external worker (#4201) to ship this week, followed using a bundled dedicated worker the week after (#4215).
