### ISSUE TITLE
"Only this channel" filter doesn't work when selecting packages for a release

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#4076]
Try to create a release for a channel that has package version rules. When you open up the package search dialog to select a specific version for a package, it will show you all of the packages from the feed that match the package version rules for your selected channel.

There is a checkbox at the top of the dialog that says "Only this channel". When you deselect this checkbox, and click refresh, you are expecting to see all of the versions of your package from the feed, not just those that have been filtered by your package version rules. Instead, the results don't change, so you still see only the filtered set of package versions.

"Pre-Release packages" also doesn't work

Old portal:

![image](https://user-images.githubusercontent.com/1892715/33966311-d52c037c-e0aa-11e7-9811-11b11c42113b.png)

New portal:

![image](https://user-images.githubusercontent.com/1892715/33966325-ea7bca96-e0aa-11e7-9d03-a53436c90bf9.png)

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Only this channel" filter doesn't work when selecting packages for a release](https://trello.com/c/j0uGzNO0/894-only-this-channel-filter-doesnt-work-when-selecting-packages-for-a-release)

**Comment by zentron** [comment]
Should be fixed as part of changes required for https://github.com/OctopusDeploy/Issues/issues/4114
