### ISSUE TITLE
Confirmation of PackageID within Deploy Package Step not committing in Internet Explorer 11

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4092]
**Octopus Version:**

4.1.1

**Issue:**

Using Internet Explorer 11 to access the Octopus web portal, within a Deploy Package step, selecting a Package ID from the 'Package ID' field via the down menu causes the selection to complete but the package is not committed.

Entering text as well as clicking the drop-down icon packages are populated but neither mouse or keyboard selection confirms the selection.

**Cause:**

This issue is present within Internet Explorer 11 as the web browser, this behavior is not consistent with Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) from the testing performed.

**Replication Steps:**

_Included a gif containing evidence of the below issue replication steps._
![package_dropdown](https://user-images.githubusercontent.com/33012349/34021535-31d7d8cc-e186-11e7-9d9e-a041cb31e858.gif)

1) Login to the Octopus web portal via Internet Explorer 11 as the nominated web-browser

2) Create a Deploy Package Step within an existing project.

![image](https://user-images.githubusercontent.com/33012349/34020642-12b2e784-e181-11e7-996e-3e1d1b16f714.png)

3) Select the 'Package ID' field.

![image](https://user-images.githubusercontent.com/33012349/34020722-819a3166-e181-11e7-84fa-af7b62817b5a.png)

4) Attempt to an existing package via the drop-down menu or begin typing to prompt the auto-suggestion.

![image](https://user-images.githubusercontent.com/33012349/34020763-b71e270c-e181-11e7-99c9-fb7756d6a8a4.png)

5) Confirm your selection of the nominated package.

6) Upon 'Package ID' selection the field will remain blank as the selection has not been committed.

**Source:**

https://help.octopusdeploy.com/discussions/problems/65726

**Comment by pawelpabich** [comment]
Release Note: Fixed package selection in IE 11
