### ISSUE TITLE
Tenant api missing validation of environment and project associations

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4095]
The "create tenant" api does not validate whether the environment and project ids are valid when it saves the tenant:

```
var endpoint = new OctopusServerEndpoint("https://octopus.example.com", "API-1234567890123456789");
var client = OctopusAsyncClient.Create(endpoint).Result;
var repository = new OctopusAsyncRepository(client);

var tenant = repository.Tenants.Create(new TenantResource
{
    Name = "matt",
    ProjectEnvironments = { { "project-spaghetti", new ReferenceCollection {"environment-bob"} }, }
}).Result;
```

Given that `project-spaghetti` and `environment-bob` are not valid id's, this should fail. However, it creates the tenant successfully.

![image](https://user-images.githubusercontent.com/373389/34025111-36d48b9c-e1a2-11e7-83d9-2dc93de4dc18.png)

In the UI, it appears as a permissions error:

![image](https://user-images.githubusercontent.com/373389/34025122-46efab7e-e1a2-11e7-8894-689d7239b276.png)

As the TenantEditor used in most of our [examples](https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/Octopus.Client/PowerShell/Tenants/CreateTenant.ps1) takes `EnvironmentResource` and `ProjectResource` objects in the `ConnectToProjectAndEnvironments`, this should not be a common issue.

One thing to ponder with this is whether this should be added to the data integrity check to pick up existing data issues. If it is, how would users resolve the issue?

**Comment by TomPeters** [comment]
Duplicate https://github.com/OctopusDeploy/Issues/issues/4032
