### ISSUE TITLE
v4 "Reordering" components have regressed on keyboard support

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4107]
In oldportal, if you had a LOT of things to reorder, you could click-and-hold then use the PageUp/Down/Home/End keys to quickly navigate up and down the reorder list.

In v4, you no longer have that ability.

### Steps to reproduce
- Create 200 environments (this example uses environments, but it applies to any resource that has a reordering component in the Octopus UI)
- Make your browser's window-size relatively small so you'd be forced to see a scrollbar in the reordering dialog
- Click and hold one environment from the top of the list, and try to use the PageUp/Down/Home/End keys, notice they do not work

^ In v3, if you try that same behaviour, those keys would let you quickly navigate up and down, so this is a regression.

Source: https://help.octopusdeploy.com/discussions/problems/65756

**Comment by matt-richardson** [comment]
This is unlikely to be actioned. We understand this is not ideal, but it's much harder to do than it sounds.
If this is a frequent problem, I'd suggest looking at using the api to re-order items.
