### ISSUE TITLE
Octopus V4 markdown functionality not working in Release Notes area

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4118]
**Version:**

Tested and replicated in;

Octopus 4.1.4

Google Chrome, Version 63.0.3239.84 (Official Build) (64-bit)

Firefox Quantum, Version 57.0.2 (64-bit)

**Issue:**

Within the release notes area of Octopus V4, markdown text does not appear correctly when compared to the original functionality exhibited in Octopus V3.

**Replication Steps:**

1) Within Octopus V4, create a Release and enter the following text in the '**Release notes**' area.

+ Header
  + Subtitle

![image](https://user-images.githubusercontent.com/33012349/34235727-53176fee-e63f-11e7-9a44-54048f0252d7.png)

2) Upon Release creation, the notes appear in V4 as displayed below;

![image](https://user-images.githubusercontent.com/33012349/34235773-9b343672-e63f-11e7-95c6-83fa9e78c26c.png)

3) Switch over to the V3 UI, opening the same release will show the release notes supporting markdown format.

![image](https://user-images.githubusercontent.com/33012349/34235800-c86a15f8-e63f-11e7-9a07-1a002826f5fc.png)

**Source:**

https://help.octopusdeploy.com/discussions/problems/66123

**Comment by johnsimons** [comment]
We can support 2 spaces by enabling https://github.com/showdownjs/showdown/wiki/Showdown-Options#disableforced4spacesindentedsublists

**Comment by pawelpabich** [comment]
Make it work as v3

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Octopus V4 markdown functionality not working in Release Notes area](https://trello.com/c/h03CBFAD/1236-octopus-v4-markdown-functionality-not-working-in-release-notes-area)

**Comment by pawelpabich** [comment]
Release Note:  Switched from 4 to 2 spaces for list indentation in markdown
