### ISSUE TITLE
Add another variable option in var set doesn't work

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4120]
Octopus 4.1.5 (also reproduced in Master)

When trying to add multiple variables in a set in one go using the `Add another variable` option, you get the error as shown in the following screenshot.

![add_another_variable](https://user-images.githubusercontent.com/20388190/34238211-43bda7d6-e64c-11e7-98cc-0f38b11cd526.png)

Steps to reproduce:

1) Create a variable in a set
2) Open Editor within the scope
3) Select `Add another variable` option
4) Define values for the next variable and save

Gif of repro steps.

![add_another_variable_in_set](https://user-images.githubusercontent.com/20388190/34238227-502f56fe-e64c-11e7-8da7-638873770098.gif)

Workaround: Create variables in the set individually avoiding the `Add another variable` option.

Source: https://help.octopusdeploy.com/discussions/problems/66145

**Comment by pawelpabich** [comment]
Covered by: Covered by: https://github.com/OctopusDeploy/Issues/issues/4120
