### ISSUE TITLE
Retry doesn't preserve settings

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#4132]
`Retry` does not preserve the list of excluded steps. It also does not also preserve the package transfer option.

**Comment by KennethBates** [comment]
Another source: https://secure.helpscout.net/conversation/520629381/23743/?folderId=954335 (Private link)

**Comment by KennethBates** [comment]
Steps to reproduce:

1) At deployment time, exclude a step

![exclude_step](https://user-images.githubusercontent.com/20388190/36133711-bd344a9e-10cb-11e8-9d94-399dd1f0bbbd.png)

2) Chance the state to cancelled, and redeploy

When redeploying, the step is still showing that it'll be skipped, however this step is *not* skipped when redeploying as shown in attached gif.

![redeploy_skipped_steps](https://user-images.githubusercontent.com/20388190/36133699-ada66756-10cb-11e8-8068-c2990b7bbe8d.gif)

**Comment by KennethBates** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redeploy doesn't preserve settings](https://trello.com/c/JWK44VDZ/1070-redeploy-doesnt-preserve-settings)

**Comment by pawelpabich** [comment]
Tried to reproduce on the latest version and couldn't.

![retry](https://user-images.githubusercontent.com/347637/36136481-72e43a2e-10dc-11e8-8c3c-86c52eef54d2.gif)

**Comment by pawelpabich** [comment]
Release Note: Excluded steps are now preserved between retries
