### ISSUE TITLE
Manage Tags popup shows first item selected

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#4135]
We don't actually select the first time here but it renders in a way that it looks like it is selected.
We have a few options here:

- Do what Variable Editor does and do not open the list
- Fix rendering so the first item looks like it is on the list of available options, instead looking like a selected option.

![image](https://user-images.githubusercontent.com/347637/34506966-5b691cb8-f07d-11e7-8f7d-97efbc524ac1.png)

Source: https://help.octopusdeploy.com/discussions/beta-testing-feedback/706

**Comment by matt-richardson** [comment]
This has been fixed. Retested in 2019.5.1.
