### ISSUE TITLE
Option for "Add Template" missing from Project Templates for environment scoped users

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4142]
**Octopus Version:**

Tested and replicated on Octopus Version: 4.1.6

**Issue:**

The option for "Add Template" is not visible via Variables > Project Templates when logged in as a User that belongs to a Team which is scoped to environments.

_From testing performed this issue does not occur when using the Octopus V3 UI._

![image](https://user-images.githubusercontent.com/33012349/34551350-c0450c5e-f164-11e7-878d-d902f0a01830.png)

![image](https://user-images.githubusercontent.com/33012349/34551368-f80d0e34-f164-11e7-875b-bb838ba7d26d.png)

**Replication Steps:**

1. Login to Octopus as a user who belongs to a team that does not have any environments scoped as shown below;

![image](https://user-images.githubusercontent.com/33012349/34551998-4473d780-f16a-11e7-9f70-b8ddd2287752.png)

2. Navigate to "Project Templates" via Variables within a Project, the option for 'Add Template' is viewable, as shown below;

![image](https://user-images.githubusercontent.com/33012349/34552136-78077330-f16b-11e7-88d9-11e25e1b66ac.png)

3. Apply environment scoping to the Team (in this example using the same user as before) as shown below, (Note: The issue occurs when specifying single or multiple environments)

![image](https://user-images.githubusercontent.com/33012349/34552022-8b87fb1a-f16a-11e7-8ba2-7a4fc03710ae.png)

4. Navigate back to "Project Templates" via Variables within a Project, the option for 'Add Template' is now missing, as shown below.

![image](https://user-images.githubusercontent.com/33012349/34552095-2e6f81e0-f16b-11e7-8b17-8e51b8119d11.png)

**Source:**

https://help.octopusdeploy.com/discussions/problems/67554

**Comment by sakopov** [comment]
What's the status on this?

**Comment by pawelpabich** [comment]
Release Note: Fixed a problem where teams scoped to an environment couldn't add project variable templates
