### ISSUE TITLE
Autocomplete/selects require two mouse clicks in Firefox

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#4145]
Steps:

1. Add  a new step to a deployment process
1. Go to environments sections and try to exclude one
1. First click does nothing

Possibly related to: https://github.com/OctopusDeploy/OctopusDeploy/blob/09c45c28e466a729410b696a0ce46d3f471b2691/newportal/app/components/MultiSelect/MultiSelect.tsx#L147

Source:
https://help.octopusdeploy.com/discussions/beta-testing-feedback/706

**Comment by pawelpabich** [comment]
![firefoxselects](https://user-images.githubusercontent.com/347637/34588393-7561aece-f1f8-11e7-8aa5-6b7014f62785.gif)

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Autocomplete/selects require two mouse clicks in Firefox](https://trello.com/c/RQU3nhWj/957-autocomplete-selects-require-two-mouse-clicks-in-firefox)

**Comment by reecewalsh** [comment]
Another reported instance of this issue can be found here;

https://help.octopusdeploy.com/discussions/problems/67673

**Comment by pawelpabich** [comment]
Release Note: Fix problem in Firefox where selects required two clicks
