### ISSUE TITLE
Allow reordering parameters in step templates

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4147]
Currently parameters in step templates aren't able to be reordered. It would be great if you could do this in the same way you can currently reorder deployment steps or environments, for example.

Workaround is a pain: Export the template, modify the parameter order, change the name, import it as a new template and connect it to project(s).

Source: https://help.octopusdeploy.com/discussions/questions/16129

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow reordering parameters in step templates](https://trello.com/c/KtNHTplq/1237-allow-reordering-parameters-in-step-templates)

**Comment by pawelpabich** [comment]
Release Note: Lists with parameters can now be manually ordered
