### ISSUE TITLE
Octopus Deploy Support for SSIS Package 

### ISSUE THREAD

**Issue by iamsaanvi** [OctopusDeploy/Issues#4153]
Hi 
Is there  any way or plan to support SSIS packages?

I am happy to create a custom library step for powershell to perform the installation and [deployment ](https://mindmajix.com/octopus-deploy-training)process if required.

**Comment by matt-richardson** [comment]
Hi @iamsaanvi - we dont normally monitor this repo for new issues. Your best bet for this kind of question is to go via our [support channels](https://octopus.com/support).

That said, we dont have any native support for SSIS, nor any specific plans around them. There is already a [library step that can deploy SSIS ISPAC projects](https://library.octopusdeploy.com/step-templates/bf005449-60c2-4746-8e07-8ba857f93605/actiontemplate-deploy-ispac-ssis-project-from-a-package) though -. If this isn't quite what you're looking for, we'd more than happily accept a PR for a new step.
