### ISSUE TITLE
Creating a release with more than 1 dash or plus fails as not valid

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4155]
When creating a release, if a version includes more than one dash or a plus, it is no longer detected as [SemVer](https://semver.org/), see full details in the customer report: https://help.octopusdeploy.com/discussions/problems/67775

Summary from the customers report:

> c.c.i-tag works
> c.c.i-tag-tag or c.c.i-tag+metadata throw an error

![image](https://user-images.githubusercontent.com/119096/34805740-659c9116-f6cb-11e7-9135-b861ff9436c3.png)

 - Create a new release with c.c.i : ✓
 - Create a new release with c.c.i-Tag+Metadata : ❌ 'The release number 'c.c.i-Tag+Metadata' does not appear ...
 - Create a new release with 1.0.0-Tag+Metadata : ✓
 - Create a new release with c.c.i : ✓ but the release is marked as 0.0.1

**Comment by mayuanyang** [comment]
Release Note: Fix a bug where metadata component in release version is not working with SemVer 2.0 template
