### ISSUE TITLE
Run on N targets in role

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#4159]
At the moment a step runs on all targets in a role. If a user wants to run a step only once, they either: 
- Choose one of the targets and assign a special role, which causes problems if that target is unhealthy
- Run the script on the server, which may not be optimal, e.g. as it could be in the wrong network segment

We should allow the user to specify the maximum number of targets to run the step on.

**UI Changes**

The `Execution Plan` section currently looks like this:

![image](https://user-images.githubusercontent.com/1687639/34923052-cd1cb2ba-f9e3-11e7-861a-2b77f63498b5.png)

We should re-work this into something like:

![image](https://user-images.githubusercontent.com/1687639/34923320-8435c30e-f9e6-11e7-96f8-3c5d52d299bc.png)

Once Workers #4158  is a thing `Octopus Server` would be replaced by `In Pool ...`

**Comment by droyad** [comment]
**UserVoice**

- https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/3721946-ability-to-run-a-powershell-script-once-before
- https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6316906-support-run-on-any-tentacle-model-for-deployment

**Comment by droyad** [comment]
@martynakaminska What is the scenario where you would find this feature useful? We have implemented workers (#4158), and that covers a lot of what is discussed above.

**Comment by martynakaminska** [comment]
What we see as problem that we are using Deploy Package step to deploy AWS Lambda functions. Unfortunately you can't run this step against workers

**Comment by droyad** [comment]
@martynakaminska Does this all happen in one step, or do you need to chain multiple steps together?

If it is one step, the "Run Script From Package" step might do what you need, particularly with the [latest changes](https://github.com/OctopusDeploy/Issues/issues/4842)

**Comment by martynakaminska** [comment]
Thanks. It would help but this step doesn't have Feature to perform transform of variables in files. However we found out that "Run an AWS CLI Script" step has this functionality, can run from package and can be run on Worker. This solves our issue.

**Comment by droyad** [comment]
Awesome you got it going. The Substitution options for normal script steps were added in 2018.8.0 if I remember correctly.

**Comment by droyad** [comment]
Closing this as we do not plan on implementing this in light of #4842
