### ISSUE TITLE
Tenant Variables Improvements

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4160]
## Summary
There Tenant managements screens would benefit from some more attention, they were mostly ported from v3 to v4 one-to-one.

## Aspects
 - Leveraging the new variable editor in more places
 - Filtering improvements
 - There's more white space now, not consistent with other parts
 - Variable template improvements

## Details / Discussion
 - Unified Variable System (Internal link): https://docs.google.com/document/d/1uenDKcRDhRm6pGAwN-W_fCC4ZZOh-tufT6k3zrShoz8/edit#heading=h.9ewmmkmoqyqi

Customers mentioning it:
 - https://secure.helpscout.net/conversation/504424506?folderId=557077 (internal link)
 - https://secure.helpscout.net/conversation/583371898/27191/?folderId=801354

**Comment by thebigmoosey** [comment]
fyi another customer frustrated with variable editing and tenants: https://secure.helpscout.net/conversation/583371898/27191/?folderId=801354

**Comment by patricknolan** [comment]
Hey Nick just thought I would see how this is going?

We have quite a complex multi-tenanted solution with many variables so I many suggestions in this space which would really help real-world users.

Would you consider a call so I can provide a walk-through of our implementation and the issues\challenges we have with Tenant Variables as they're currently implemented?

**Comment by NickJosevski** [comment]
@patricknolan thanks for the offer, we would like to take you up on the chat when we're ready to work on this.

At the moment I don't have a solid timeline on this improvement, it had to come after some major permission work we're in the middle of at the moment. It's good we've got your comment here, we can ping you when the time is right to get your input.

**Comment by TomPeters** [comment]
Improving tenant variables is one of the main goals of the Variable Unification project, so we are closing this issue and rolling up the changes into https://github.com/OctopusDeploy/Issues/issues/4390
