### ISSUE TITLE
Review the impact of pre-filling tenant tags

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4166]
Recent changes in on the release screen mean tenant tags are pre-filled, but there are 2 camps of users, those who *do want*, and those that *do not want*.

The pre-filled tenant tags, results in a selection of tenants that will be deployed to, and if the tag selection area is expanded, the tenants that will be deployed to will likely be off screen (requires scrolling).

The most recent change to this went out in 4.1.8 and is documented here: https://github.com/OctopusDeploy/Issues/issues/4112

We'll need a solution that caters for both, and doesn't result in the users who were used to not pre-filling deploying to an unexpected number of tenants.

## Ideas
Use explicit action `Include all applicable Tenants`. This will allow us to start with an empty list which makes Camp 1 happy, but also allows to pre-fill data with just one click which should be acceptable for Camp 2 happy. Pre-filling is magic as uses don't know the rules so it would be good if we can avoid it.

## Customers
 - Against pre-filling: https://help.octopusdeploy.com/discussions/problems/67898 with further comment from there here: https://github.com/OctopusDeploy/Issues/issues/4112#issuecomment-357830174

## Prior discussions
 - https://github.com/OctopusDeploy/Issues/issues/3336 - Ability to exclude tenants when creating multiple tenanted deployments

**Comment by pawelpabich** [comment]
> Include all applicable Tenants.
We already have that. @NickJosevski does this means this can be closed?

**Comment by NickJosevski** [comment]
I think I raised this issue because it was my support week, I don't speak with authority on it, would need to check with @mayuanyang

**Comment by mayuanyang** [comment]
No body else raises the similar issue, i think should be fine to close @NickJosevski

**Comment by pawelpabich** [comment]
Fixed in `4.1.8` https://github.com/OctopusDeploy/Issues/issues/3951
