### ISSUE TITLE
Simplify multi-selects by splitting new vs existing logic

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4172]
## Problem
Currently our multi-selects allow you to select from existing, or specify new, but handling this ability to specify a new value adds complexity and doesn't add much value, because that feature is only used by the Deployment Targets screen when specifying roles (where you can select from existing roles or type a new one).

This has become a problem because multi-selects **should stay open** while you make selections, rather than force you to click and re-open it every time :)

## Proposed Solution
Suggest we simplify our multi-select component to ONLY be a select component, and have the role selection in Deployment Targets be two separate components:

```
Add new role   [this is an input box]
Select existing role   [this is a multi-select]
```

This will allow us more flexibility to improve the multi-selects in other ways, where hopefully we can make them behave more like the MaterialUI multi-select component, which is what I’d expect if something allowed multiple selections @ http://www.material-ui.com/#/components/select-field

Notice in the above example from MaterialUI, the select popover stays open and shows selections, rather than dismissing on selection (which ours does atm to cater for the "specify new" selection).

Related: https://github.com/OctopusDeploy/Issues/issues/4086

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simplify multi-selects by splitting new vs existing logic](https://trello.com/c/blMvypyp/19-simplify-multi-selects-by-splitting-new-vs-existing-logic)

**Comment by droyad** [comment]
Do as part of #4313
