### ISSUE TITLE
Project description header lines are squished and overlapping

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#4175]
Here is the markdown I used for the top portion of that screenshot:
```
# Blah blah blah and more blah so it wraps

---

## More Blah

---

#### For high load: 
* Octopus url: https://foo.bar 
* Goto Projects->Blah

```

![image](https://user-images.githubusercontent.com/122651/35073103-2cdc583a-fc33-11e7-84bf-07428ccd048c.png)

Reported in https://help.octopusdeploy.com/discussions/beta-testing-feedback/737-new-ui#comment_44530457

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project description header lines are squished and overlapping](https://trello.com/c/4vKLjI95/1239-project-description-header-lines-are-squished-and-overlapping)

**Comment by NickJosevski** [comment]
Release Notes: Fixed display issue on project descriptions that have markdown
