### ISSUE TITLE
Unable to bind variable to manual intervention instructions

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4182]
Octopus 4.1.9

Tested in Chrome & Firefox

In the manual intervention step, you can't select a variable from the binding `insert a variable` dropdown.

![manual_intervention_variable](https://user-images.githubusercontent.com/20388190/35126738-81f504d0-fcfa-11e7-867a-cf72bbcaa9cf.gif)

Additionally, manually binding a variable (i.e. `#{Variable}`) to the field doesn't evaluate. You have to input a direct string into the instructions for any direction to display.

Source: https://help.octopusdeploy.com/discussions/problems/68015

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to bind variable to manual intervention instructions](https://trello.com/c/6y9aQAyl/1005-unable-to-bind-variable-to-manual-intervention-instructions)

**Comment by KennethBates** [comment]
Reproduced in master
