### ISSUE TITLE
New-OctopusArtifact is attempting to take out read only share when reading the artifact file

### ISSUE THREAD

**Issue by tw17** [OctopusDeploy/Issues#4184]
New-OctopusArtifact is attempting to take out a read only share when reading the artifact file. 
If if the artifact file is being written to by another process, i.e a log file, Octopus fails to acquire the file lock and throws a `System.IO.IOException: The process cannot access the file ` exception.

**Comment by droyad** [comment]
Fixed in Tentacle `3.17.0`

**Comment by tw17** [comment]
ReleaseNote: When collecting an artifact using New-OctopusArtifact, we now allow other processes to access the file.
