### ISSUE TITLE
SSH Targets not part of the Windows Platform FIPS validated cryptographic algorithms

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/Issues#4197]
Reproduced in Octopus Server 4.1.4

Connecting to an SSH Target while your Octopus server's Operating System has [FIPS enabled](https://octopus.com/docs/administration/security/fips-and-octopus-deploy) may cause the following error upon performing a target health check:

```
Could not connect to SSH endpoint: Exception has been thrown by the target of an invocation.
                    |     Octopus.Worker.Ssh.SshEndpointConnectionException: Could not connect to SSH endpoint: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
                    |     at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
                    |     --- End of inner exception stack trace ---
                    |     at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
                    |     at Renci.SshNet.Session.Connect()
                    |     at Renci.SshNet.BaseClient.Connect()
                    |     at Octopus.Worker.Ssh.Connectivity.SshClientFactory.EstablishConnection[TClient](Func`2 clientConstrutor)
                    |     --- End of inner exception stack trace ---
                    |     at Octopus.Worker.Ssh.Connectivity.SshClientFactory.EstablishConnection[TClient](Func`2 clientConstrutor)
                    |     at Octopus.Worker.Ssh.Connectivity.SshClientFactory.EstablshSshConnection()
                    |     at Octopus.Worker.Ssh.Connectivity.ConnectionScope.get_SshClient()
                    |     at Octopus.Worker.Ssh.SshRemoteEndpointFacade.EnsureDirectoryExists(String path, StringBuilder error)
                    |     at Octopus.Worker.Ssh.SshRemoteEndpointFacade.UploadFile(String remotePath, DataStream upload)
                    |     at System.Collections.Generic.List`1.ForEach(Action`1 action)
                    |     at Octopus.Worker.Ssh.SshRemoteEndpointFacade.UploadExecuteDownload(StartScriptCommand command)
                    |     at Octopus.Worker.Common.ExecuteCommandService.ExecuteCommand(Func`1 initialExecution, IEnumerable`1 preconditionChecks, Int32 count)
                    |     at Octopus.Worker.Ssh.SshWorker.ExecuteCommand(StartScriptCommand command, IEnumerable`1 preconditions)
                    |     at Octopus.Worker.Ssh.SshWorker.CheckHealth()
                    |     at Octopus.Server.Orchestration.Health.HealthCheckService.PerformHealthCheck(Machine machine, ExceptionHandling exceptionHandling, Action`2 customAction)
                    |     Octopus.Server version 4.1.4 (4.1.4+Branch.master.Sha.8582c6610adebd0404ec12b1e2ec662d1dfa4cee)
```

Related Support Tickets (Internal Link): https://secure.helpscout.net/conversation/508066347/23030?folderId=1380307

**Comment by sbebrys** [comment]
Hi, when You will fix this problem?

**Comment by sbebrys** [comment]
Hi, I repeat my question. It's so confuse for our company, because we must block updating version of OctopusServer.

**Comment by matt-richardson** [comment]
Thanks for your question @sbebrys. The best way to get in touch is via one of our [support channels](https://octopus.com/support), as we dont actively monitor these issues as per our [contribution guide](https://github.com/OctopusDeploy/Issues/blob/master/.github/CONTRIBUTING.md).

**Comment by droyad** [comment]
It is due to this issue https://github.com/sshnet/SSH.NET/issues/276#issuecomment-322877786

**Comment by sbebrys** [comment]
Hi, so I understand that You changed ssh component in version 4.1.4? ssh.net has a FIPS problem for 6 months. In 4.1.3 ssh worked correct.

**Comment by droyad** [comment]
@sbebrys Yes we upgraded to fix another issue and didn't see the above issue would apply to us (it isn't marked as a bug, the title is misleading and there are a lot of issues). We are currently looking into this, it looks like we won't need to patch SSH.NET

**Comment by droyad** [comment]
The library was upgraded in 4.1.2 as part of #2448

**Comment by sbebrys** [comment]
Thanks for explanation, nice to hear that You work on it 👍

**Comment by markryd** [comment]
Release Note: Update our SSH library so that it works on Octopus servers with FIPS enabled

**Comment by sbebrys** [comment]
Unfortunately when I test this version I have another error with ssh (only when FIPS is on): 

```
07:35:16   Verbose  |     Performing health check on machine
07:35:16   Verbose  |     Requesting upload...
07:35:16   Verbose  |     Establishing SSH connection...
07:35:16   Fatal    |     Could not connect to SSH endpoint: Client encryption algorithm not found
                    |     Client encryption algorithm not found
07:35:16   Verbose  |     Could not connect to SSH endpoint: Client encryption algorithm not found
                    |     Client encryption algorithm not found
                    |     Could not connect to SSH endpoint: Client encryption algorithm not found
                    |     Octopus.Server.Orchestration.Targets.Ssh.SshEndpointConnectionException: Could not connect to SSH endpoint: Client encryption algorithm not found ---> Renci.SshNet.Common.SshConnectionException: Client encryption algorithm not found
                    |     w Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
                    |     w Renci.SshNet.Session.Connect()
                    |     w Renci.SshNet.BaseClient.Connect()
                    |     w Octopus.Server.Orchestration.Targets.Ssh.Connectivity.SshClientFactory.EstablishConnection[TClient](Func`2 clientConstrutor)
                    |     w Octopus.Server.Orchestration.Targets.Ssh.Connectivity.SshClientFactory.EstablishConnection[TClient](Func`2 clientConstrutor)
                    |     w Octopus.Server.Orchestration.Targets.Ssh.Connectivity.SshClientFactory.EstablshSshConnection()
                    |     w Octopus.Server.Orchestration.Targets.Ssh.Connectivity.ConnectionScope.get_SshClient()
                    |     w Octopus.Server.Orchestration.Targets.Ssh.SshRemoteEndpointFacade.EnsureDirectoryExists(String path, StringBuilder error)
                    |     w Octopus.Server.Orchestration.Targets.Ssh.SshRemoteEndpointFacade.UploadFile(String remotePath, DataStream upload)
                    |     w System.Collections.Generic.List`1.ForEach(Action`1 action)
                    |     w Octopus.Server.Orchestration.Targets.Ssh.SshRemoteEndpointFacade.UploadExecuteDownload(StartScriptCommand command)
                    |     w Octopus.Core.Orchestration.Targets.Common.ExecuteCommandService.ExecuteCommand(Func`1 initialExecution, IEnumerable`1 preconditionChecks, Int32 count)
                    |     w Octopus.Server.Orchestration.Targets.Ssh.SshTarget.ExecuteCommand(StartScriptCommand command, IEnumerable`1 preconditions)
                    |     w Octopus.Server.Orchestration.Targets.Ssh.SshTarget.CheckHealth()
                    |     w Octopus.Server.Orchestration.ServerTasks.HealthCheck.HealthCheckService.PerformHealthCheck(Machine machine, ExceptionHandling exceptionHandling, Action`2 customAction)
                    |     Octopus.Server version 2018.2.7
```

**Comment by markryd** [comment]
@sbebrys when you have FIPS on we now restrict the possible encryption algorithms to aes256-cbc, aes192-cbc, aes128-cbc or 3des-cbc. We also limit HMAC algorithms, Host Key algorithms and Key exchange algorithms, you can see the lists [here](https://github.com/OctopusDeploy/SSH.NET/blob/octopus/src/Renci.SshNet/ConnectionInfo.cs#L450). Do you have the valid algorithms restricted in your sshd_config on the machines you are connecting to? You'd be looking for a `Ciphers` entry in the sshd_config?

If that's not it, or you need more help can you create an issue over at https://help.octopus.com/ or email us at support@octopus.com? We don't always see comments on closed GitHub issues.

**Comment by sbebrys** [comment]
Hi, our security policy exclude ciphers cbc as too weak, can You extend the list by aes256-gcm and aes256-ctr?

**Comment by markryd** [comment]
@sbebrys I can add aes256-ctr to the supported ciphers, but the library we're using for SSH does not currently support the others. You can see the full list of supported algorithms further up in the file I previously linked to starting [here](https://github.com/OctopusDeploy/SSH.NET/blob/octopus/src/Renci.SshNet/ConnectionInfo.cs#L295).

**Comment by sbebrys** [comment]
@markryd Great, aes256-ctr for now will fix my problem

**Comment by dparker61** [comment]
I am getting this error during connection to a Tectia ssh server running on a mainframe. The exception gets thrown from this piece of code in IgnoreMessage.cs

        '/// </summary>
        protected override void LoadData()
        {
            var dataLength = ReadUInt32();
            if (dataLength > int.MaxValue)
            {
                throw new NotSupportedException(string.Format(CultureInfo.CurrentCulture, "Data longer than {0} is not supported.", int.MaxValue));
            }'

I downloaded a zip of master, so think I am running the most recent. I don't know if it is a FIPS support issue, or something weird like the mainframe is not ints in network order....

I would appreciate any clues, or a pointer to the latest branch that has a fix.

Thank you!
