### ISSUE TITLE
Double scrollbars in release picker

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#4202]
![image](https://user-images.githubusercontent.com/122651/35310038-2b72ff2c-00fb-11e8-95f9-4f326852337e.png)

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enable strictnullcheck in TypeScript](https://trello.com/c/NphrfaIr/987-enable-strictnullcheck-in-typescript)

**Comment by pawelpabich** [comment]
Release Note: Package selector and Release selector are not showing double scrollbars any more.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Double scrollbars in release picker](https://trello.com/c/kEJWXqu3/1001-double-scrollbars-in-release-picker)
