### ISSUE TITLE
User created tasks require Admin privileges

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#4208]
There are a number of user creatable tasks that are blocked by needing the AdministerSystem permission.

- Upgrade Tentacles
- Run retention policies
- Send a test email
- Run an adhoc script
- Test Azure accounts
- System Integrity Check
- Synchronise community templates
- Synchronise built in package repository
- Synchronise external security groups
- Configure Lets Encrypt

This is a problem as Manager accounts (without AdministerSystem) will still need to perform these tasks.

**Comment by matt-richardson** [comment]
`Configure Lets Encrypt` feels like it should remain requiring `AdministerSystem`...

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Server tasks still need AdministerSystem permission](https://trello.com/c/T4LRtwsc/418-server-tasks-still-need-administersystem-permission)

**Comment by distantcam** [comment]
@NickJosevski Not sure. Need to speak to a UI person

**Comment by NickJosevski** [comment]
I watched it do the network call earlier to see what was happening, but didn't put it together it is.

It creates a task called `SynchronizeBuiltInPackageRepositoryIndex`.

If you open the network tab you too can be a UI Person ;)

**Comment by distantcam** [comment]
If it's in this list the PR will fix it.

https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Core/Resources/BuiltInTasks.cs#L9-L14

> Health.Name, Retention.Name, Upgrade.Name,
> TestEmail.Name, AdHocScript.Name, UpdateCalamari.Name, TestAzureAccount.Name,
> SystemIntegrityCheck.Name, SyncCommunityActionTemplates.Name,
> SynchronizeBuiltInPackageRepositoryIndex.Name,
> SynchronizeExternalSecurityGroupsForUsers.Name,
> ConfigureLetsEncrypt.Name

LONG LIVE WPF!

**Comment by NickJosevski** [comment]
👍 except the bit about WPF
