### ISSUE TITLE
Option to Update Variable Snapshot not viewable within V4 UI 'no snapshot exists'

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4209]
**Octopus Version:**

Tested and replicated on Octopus version 4.1.8

**Issue:**

Within the Octopus V4 UI, it's not currently possible to update a Variable snapshot within a release where no variables currently exist, the option to update variables is replaced by 'no snapshot exists'

This behavior is different from the V3 UI.

I have included a Gif of this behavior below;

![update variable snapshot](https://user-images.githubusercontent.com/33012349/35369191-96421108-01d2-11e8-9f55-40a6fa9e4fb4.gif)

**Source:**

https://help.octopusdeploy.com/discussions/problems/68191-clicking-include-library-variable-sets-while-screen-is-loading-unchecks-all-variable-sets

**Comment by flin-8** [comment]
Release Note: Show "Update variables" button on a release even if it doesn't have existing variables
