### ISSUE TITLE
Step template checkbox type parameter doesn't display correctly

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4210]
Tested on Octopus 4.1.10

Step to reproduce:
Define a parameter in a step template with control type `Checkbox` and default value of `False`

![01_parameter](https://user-images.githubusercontent.com/20388190/35372048-77276b4a-01e3-11e8-980f-f89b9974733f.png)

When adding to a project, the parameter displays as `True`. 

![02_parameter_in_step](https://user-images.githubusercontent.com/20388190/35372049-7752d1f4-01e3-11e8-9203-50af98c8c87c.png)

Expanding the field shows the checkbox correctly not selected.

![03_parameter_in_step_expanded](https://user-images.githubusercontent.com/20388190/35372052-7c6cb7f4-01e3-11e8-814d-e9b8ca8af36a.png)

On deployment, parameter is evaluated correctly, so it's a UI bug.

Source: https://help.octopusdeploy.com/discussions/problems/68100-step-template-check-box-parameters-are-always-evaluated-as-true-even-though-the-parameters-are-set-to-false

**Comment by reecewalsh** [comment]
Another instance of this issue;

https://help.octopusdeploy.com/discussions/questions/14705-dacpac-deployment

**Comment by KennethBates** [comment]
Another report: https://help.octopusdeploy.com/discussions/problems/68222

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Step template checkbox type parameter doesn't display correctly](https://trello.com/c/SzTRj4NI/1051-step-template-checkbox-type-parameter-doesnt-display-correctly)

**Comment by pawelpabich** [comment]
@KennethBates @reecewalsh can you try to reproduce it? I've tried with the latest version of Octopus and it works as expected.

![image](https://user-images.githubusercontent.com/347637/36192352-e2f7120c-11ac-11e8-99c8-1abf91a60d6e.png)

![image](https://user-images.githubusercontent.com/347637/36192364-ea842f78-11ac-11e8-8ece-b24f6e1c48cb.png)

**Comment by KennethBates** [comment]
Works as it should in local instance 2018.2.3
