### ISSUE TITLE
Modify the cache naming format to allow for new feed formats

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#4211]
Package file names in Octopus often need to convey information about its content. 
### Before Zips
Originally when Octopus just supported zips, the Nuget package name format was the only standard. This took the format of  `<PackageId>.<Version>.<Extension>` , with the caveat that the nuget package metadata would be extracted out and take precedence over the file name.  Although the cache busting GUID was appended before the extension on the server (`<PackageId>.<Version>_<GUID>.<extension>`) and after the extension on the Tentacle  (`<PackageId>.<Version>.<extension>-<GUID>`) this was _generally ok_ since there was so much duplicated code anyway across both sides it kinda _just worked out_.

### Before Maven
When zips were first introduced the naming style was carried on from how Nuget package names work. So  `<PackageId>.<Version>.<Extension>` continued to work however without the need/step to extract and confirm internal metadata.

### After Maven
With the addition of maven there were several problems that needed to be solved. First was the concern that packageIds could have invalid filesystem characters (e.g. `:` to separate package archive sections). To solve this the package Id would have a `<PackageId>.Replace(':', '#')` performed to ensure it could be saved. Since a packageId could be _anything_ or even contain just `.<Number>` it was also less reliable to try and determine where the package ended and vesion started. For this reason a `#` character was used to demarcate instead of the `.` in other package types (although both were used concurrently). Additionally the version format was different (Maven versioning) and so for both reasons an additional mechanism was needed to let calamari know to parse the filenames differently. To facilitate this a `Maven#` prefix was added to the packageId which the tentacle would `try... parse... catch` to try and extract the relevant package details. Since calamari sometimes deals with files and other times with package details directly (e.g. `DownloadPackage` command) the various parameters would also be sometimes encoded and sometimes not, depending on what command was being invoked. 

### The Next Feed
With work on the next feed type starting, the limitations of the way in which Octopus deals with packages has been hit. The new packaging format needed a _different_ escape character to be protected against. Furthermore the previous approach of determining the feed type based on metadata appended to the PackageId felt like it was not going to scale well as we add new package formats. The previous in extracting some of the package naming logic into its own library, while a good start, didn't go far enough in consolidation which in some ways made things more complicated since there needed to be multiple different pathways depending on if the parsing was happening on the server or tentacle. This made reasoning about\maintaining this library on its own harder to do.

## The Solution
A complete overhaul of the package naming system was required going forward to make the process easier to understand, more scale able and ultimately safer. Changes to Octopus Server and Calamari have been made as part of this work.
1. PackageId and Version information are to be escaped when used in filenames. This will ensure that no package or version characters, which in their own feed context may be completely valid can still be stored on the filesystem.
2. To deal with properly demarcating between version and package a `@` symbol is used as the separator. This character will be encoded if it is contained within the PackageId or Version as per step 1 above.
3. To parse version format correctly the version component will be prefixed with a character to signify versioning format. e.g. `S<Version>` for semver and `M<Version>` for maven. This will allow us to better handle future versioning formats without being tied via assumptions to feeds or file types.
4. Both the server and tentacle will store cached packages with the cache busting guid _before_ the extension; `<PackageId>@<Version>@<Guid>.<Extension>`. This will allow us to properly consolidate the way in which packages are stored and read.
5. In code, we should deal with `IVersion` data type as much as possible rather than parsing back and forth between strings. The version type should be passed along with the version string during transmission/storage to ensure proper rehydration.
6. When invoking calamari commands if a `--packageVersion` parameter is required then a corresponding `--packageVersionFormat` parameter will also be provided to pass through the version format rather  than overloading other parameters. Similarly a `--feedType` parameter will be included on the `DownloadPackage` command to ensure the correct downloader is used.
7. Wherever relevant, **missing information will default to NuGet or semver** for feeds and versions for backwards compatibility
8. The current decision at this point in time is to **no longer support the old cache package format**. This means that any existing packages stored on the server or tentacle will be ignored during future deployments. They will however continue to be cleaned up if required during standard package retention (since their information is stored in the deployment journal).

**Comment by matt-richardson** [comment]
> 3. To parse version format correctly the version component will be prefixed with a character to signify versioning format. e.g. S<Version> for semver and M<Version> for maven. This will allow us to better handle future versioning formats without being tied via assumptions to feeds or file types.

A single character doesn't feel like it will scale well (max 26 version formats), and isn't as clear as it could be. Maybe use a word here instead of a character?

**Comment by zentron** [comment]
im certainly hoping we don't hit 26 version formats :)
Unless we have good reason not to, we should always err on the side of semver
 trying to keep the file name as small as possible to avoid file length issues.
