### ISSUE TITLE
Audit Log document type filter doesn't work

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4218]
**Problem**

Octopus 2018.1.1

In *Configuration > Audit*, use the `document type` filter. Any document type selected gives error `Error while executing SQL command in transaction...`.

![audit_filter_document_type](https://user-images.githubusercontent.com/20388190/35547539-559c4bae-05c5-11e8-8f18-19b4f128484c.png)

Source: https://secure.helpscout.net/conversation/512394892/23254?folderId=954335 (private link)

**Solution**

UPDATE:  2018.3 will have a migration that will correct the corrupted data automatically 

There was a bug in Octopus that was fixed a year or so ago and as a result of it some customers might have corrupted data.  The fact that we haven't heard about this problem for so long indicates that the number of affected customers is very small.

Ideally we would have a migration that can fix this problem but there are two challenges that this approach presents.

1. The migration is not simple (still doable) as the correct data needs to be extracted from a text message.
1. Some customers have large Events tables and the upgrade can take a very long time.

Taking all of this into account we propose the following manual solution for now:

1.  **Backup** your database
2. Run this script to get a list of events that will be deleted.  Make sure you are happy for those events to be deleted.
```
Select * from dbo.Event 
Where Category = 'Modified' AND Id IN (Select er.EventId from EventRelatedDocument er where CHARINDEX('-', er.RelatedDocumentId) = 0)
```
3. Run this script to actually delete the events. 
```
Delete from dbo.Event
Where Category = 'Modified' AND Id IN (Select er.EventId from EventRelatedDocument er where CHARINDEX('-', er.RelatedDocumentId) = 0)
```

**Comment by matt-richardson** [comment]
Bit concerning we are showing the sql command as well - we shouldn't be leaking that information.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit Log document type filter doesn't work](https://trello.com/c/rB3ypGyv/1052-audit-log-document-type-filter-doesnt-work)

**Comment by pawelpabich** [comment]
@KennethBates can you try to reproduce it with the latest Octopus. It does work for me on master and I remember that it used to fail there.

**Comment by KennethBates** [comment]
Issue still present in local instance version 2018.2.3
However, it's fixed in master

**Comment by pawelpabich** [comment]
Release Note: Audit log filtering would error in some cases and this is fixed now
