### ISSUE TITLE
Show what project variables will evaluate to for different deployment contexts

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#4221]
A tool to effectively evaluate project variables for a given deployment context (environment/tenant/etc)

![image](https://user-images.githubusercontent.com/1830666/35600446-a5fa100e-0679-11e8-8a80-96c803260fbf.png)

Helps work towards https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6169634--dry-run-deployment

Note that since this will not include things like environment variables or output variables these values _may not precisely_ resolve into the _real_ values available at runtime.

**Comment by droyad** [comment]
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6668436-allow-an-api-call-to-return-resolved-variables

**Comment by markryd** [comment]
Implemented in 2018.3.0

**Comment by rohmcd** [comment]
This is a great feature! We were excited to try it out after we upgraded to 2018.3.3.

But it looks like it does not take into account any applied common variable sets? We use these heavily. :(

**Comment by matt-richardson** [comment]
Hi @rohmcd - we don't often monitor these issues for comments or feedback. Your best bet is to get in touch via one of our [support channels](https://octopus.com/support), and we'll be able to look into this for you.

**Comment by alfhenrik** [comment]
RE: changing channels and environments not updating to reflect the change, we have this issue https://github.com/OctopusDeploy/Issues/issues/4373 to fix that

**Comment by rohmcd** [comment]
Thanks i have added a new topic on the help.octopus forum.

**Comment by danielfischeroctopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable preview does not reflect changes in available environments when channel is changed](https://trello.com/c/TNijrCr2/242-variable-preview-does-not-reflect-changes-in-available-environments-when-channel-is-changed)
