### ISSUE TITLE
Improve availability of the details of a health check warning.

### ISSUE THREAD

**Issue by Flamage82** [OctopusDeploy/Issues#4230]
If a target is unhealthy, it is shown in the infrastructure screen as "healthy with warnings".  Drilling down to find the actual cause of the warning is lengthy and not obvious.

![healthcheck](https://user-images.githubusercontent.com/5789282/35662816-e8bd617e-0765-11e8-89d8-b5ed2f6828b0.gif)

One suggestion is that we add `SHOW DETAILS` links on the targets themselves in the infrastructure screen.

![healthcheck](https://user-images.githubusercontent.com/5789282/35662907-857dc382-0766-11e8-8909-9bc7694d3300.png)

**Comment by Flamage82** [comment]
Original reporting issue: https://secure.helpscout.net/conversation/514113317/23328/?folderId=557082 (private link)

**Comment by droyad** [comment]
This will be covered when we revisit how we do health checks.
