### ISSUE TITLE
Cannot add environment to lifecycle phase without EnvironmentCreate permission

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4231]
Octopus 2018.1.2

Steps to reproduce:
1) Create a custom role with every permission *except* `EnvironmentCreate` assigned
2) Add role to team with a user

This user doesn't see the `Add environment` button when in the lifecycle phase configuration. This user should be able to add environments when having `LifecycleEdit` permission.

![lifecycle_phase_add_environment_button_missing](https://user-images.githubusercontent.com/20388190/35663858-29c819f2-076b-11e8-88da-cf221e2bff86.png)

Workaround: Add the environment via the old portal at `OctoURL/oldportal`

Source: https://help.octopusdeploy.com/discussions/problems/68421

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot add environment to lifecycle phase without EnvironmentCreate permission](https://trello.com/c/MIIFRY9A/1053-cannot-add-environment-to-lifecycle-phase-without-environmentcreate-permission)

**Comment by pawelpabich** [comment]
Release Note: Now you can add an environment to a lifecycle phase without having EnvironmentCreate permission
