### ISSUE TITLE
TypeError: Cannot read property 'Version' of undefined - Applying Release Filter to Project Overview

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4234]
**Octopus Version:**

Tested and replicated on Octopus version 2018.1.2

Google Chrome, Version 63.0.3239.84 (Official Build) (64-bit)

Firefox Quantum, Version 57.0.2 (64-bit)

**Issue:**

An unhandled JavaScript error is encountered on the project overview screen when applying a filter to a specific release version. This only affects releases that exist prior to the last 29 releases that appear in the drop-down by default.

**Replication Steps:**

1) Create a New Project

2) Create 30+ concurrent releases for the newly created project.

3) Apply a Release filter to the Project Overview, selecting the 1st release created as it should not exist on the drop-down.

4) This is when the error is encountered.

I've included a gif of the behavior below;

![typeerror version](https://user-images.githubusercontent.com/33012349/35716601-b0f63f2a-0825-11e8-815d-e5673e20cc1e.gif)

**Full Exception:**

Attached is the full error log;
[Overview Error.txt](https://github.com/OctopusDeploy/Issues/files/1688014/Overview.Error.txt)

**Workaround:**

This issue is not experienced within the V3 UI and is currently specific to the V4 React UI, using the V3 UI is recommended as a workaround to retain this specific functionality.

**Source:**
https://help.octopusdeploy.com/discussions/problems/68447

https://help.octopusdeploy.com/discussions/problems/68039-exception-when-trying-to-select-version-in-overview

**Comment by johnsimons** [comment]
Release Note: Ensuring we can render old releases in project overview
