### ISSUE TITLE
Drain node with only one node does nothing

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4235]
Draining a node when there is only one node:
* appears to do nothing
* logs a javascript error
* gets an error response:
![image](https://user-images.githubusercontent.com/373389/35763124-52ed20c2-08f9-11e8-84fa-56d4aedbfe24.png)

It would be useful to be able to drain a single node to be able to do an automated upgrade.

**Comment by droyad** [comment]
Release Note: All nodes can now be drained at the same time
