### ISSUE TITLE
2018.2 Bug Bash Feeback: Template source code window is too small

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#4247]
From the 2018.2 bug bash by John Simons.

The code editing window is too small. Even with the `wideDialog` option it is not large enough.

Also https://twitter.com/spacattac/status/959459588033601536.

![7dd55d9f-f1b8-4bb2-971f-4549329aee3d](https://user-images.githubusercontent.com/160104/35893347-61e28240-0bf9-11e8-9fbb-f8e21efa9ce7.png)

**Comment by NickJosevski** [comment]
Raised here by a customer: https://help.octopus.com/t/arm-template-edit-box-size/18927/2

**Comment by NickJosevski** [comment]
Fixed at some point. No other issue was found, probably a broader change about these input windows.
