### ISSUE TITLE
2018.2 Bug Bash Feeback: Streamline the ability to add an account from steps that select an account variable

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#4249]
From the 2018.2 bug bash by Rob Wagner.

> I was confused why I went to the variables page instead of the accounts page when I clicked Add Account. Once I got there, I didn't know what to do. Could we perhaps show some help text when we redirect? Or automatically pop the add variable UI and autoselect the right variable type?

![image](https://user-images.githubusercontent.com/160104/35893515-29ad5fde-0bfa-11e8-8834-8cff9b0f1088.png)

**Comment by droyad** [comment]
Not a priority
