### ISSUE TITLE
2018.2 Bug Bash Feeback: Account header buttons flow to next line with long account name

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#4252]
From the 2018.2 bug bash by Tom Peters.

> This might be an existing issue, and it might not just be on this page

![image](https://user-images.githubusercontent.com/160104/35893675-e7ec4870-0bfa-11e8-8743-66ca7d375675.png)

**Comment by TomPeters** [comment]
No customers have reported this (presumably their account names aren't actually this long!) so we don't plan to spend any time fixing this right now.
