### ISSUE TITLE
Enabling and defining custom installation directory feature displays purge when its disabled

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4254]
Octopus 2018.1.4

Steps to repro

1) Create a package step and enable custom installation directory
2) Define the directory for CID and leave the purge option disabled
3) Save the step

When re-entering the step, it displays the following.

![01_purge_incorrect](https://user-images.githubusercontent.com/20388190/35895033-60b8f874-0c01-11e8-8396-e53117b359bb.png)

When the CID section is expanded, it correctly shows the purge option as disabled:

![02_purge_unselected](https://user-images.githubusercontent.com/20388190/35895038-654e1b26-0c01-11e8-9eae-7b4a25a96852.png)

When you deploy, the directory is *not* purged, so it's only a display issue.

Workaround: Enable purging, save the step, disable purging and re-save.

Source: https://secure.helpscout.net/conversation/515556239/23440?folderId=954335 (private link)

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enabling and defining custom installation directory feature displays purge when its disabled](https://trello.com/c/aE2CtQ7t/1055-enabling-and-defining-custom-installation-directory-feature-displays-purge-when-its-disabled)

**Comment by pawelpabich** [comment]
Release Note: Custom Install Directory feature shows now correctly whether files will be purged or not
