### ISSUE TITLE
Allow filtering by release in projects not using multi-tenancy

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4256]
Tested in 2018.1.4

If a project has tenanted deployments, you're able to filter by release in *[Project] > Overview*.

![01_multi_tenancy](https://user-images.githubusercontent.com/20388190/35952864-c702e6f4-0ccd-11e8-83d8-b4920fd93aa5.png)

When a project doesn't use multi-tenancy, the release filter doesn't exist. Users are only able to group by channel.

![02_no_multi_tenancy](https://user-images.githubusercontent.com/20388190/35952868-c8db9fc0-0ccd-11e8-9dbc-34d69bafd4f0.png)

Ideally, it would be great to be able to filter by release in Project > Releases page as well.

Source: https://help.octopusdeploy.com/discussions/questions/16741

**Comment by johnsimons** [comment]
So I had a go at implementing this feature as part of https://github.com/OctopusDeploy/OctopusDeploy/pull/1916 and I came to the conclusion that currently with the current API we have available is not possible to enable filtering by release

**Comment by TomPeters** [comment]
Will fix as part of https://github.com/OctopusDeploy/Issues/issues/3419
