### ISSUE TITLE
No external IP Address allowed on VM used for OD deploy to connect to PaaS SQL

### ISSUE THREAD

**Issue by JudedeDude** [OctopusDeploy/Issues#4258]
Thanks for taking the time to log an issue.

However, we want our backlog to reflect things we've committed to doing in the near future.

If you've found a bug or something isn't working, please [contact support](http://octopusdeploy.com/support) instead. We don't read new GitHub issues regularly, so if you post here it will likely not get a reply. But if you contact support we can probably help to find a workaround or make sure the issue gets prioritized properly.

If you have an idea or a feature request, please post it to [our UserVoice site](http://octopusdeploy.uservoice.com) so others can vote for it.

**Comment by JudedeDude** [comment]
For security reasons my company will not use a static IP address associated to the VM. NSG rules still allow the vm to reach the www however its not determined what the NATed external IP address would be until you login to the server.

We are deploying to North Europe
Without adding the complete IP subnet Range to the firewall rules for SQL server, how else can this be achieved?

I can login to the new VM, in i.e go to whois, get my external IP address for the vm and install Octopus succesfully using SQL PaaS, as per script

**Comment by droyad** [comment]
Hi @JudedeDude, as outlined in the IssueTemplate, we don't monitor this repo for new customer issues, as we receive 100's every week. Please use our support channels (https://octopus.com/support) instead for a timely response.
