### ISSUE TITLE
Better handling of health checked machines during auto-deploy

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#4265]
## The problem
If you have a health check step set to "Include new deployment targets" and have an auto-deployment trigger, when the trigger runs for a new machine, all of the existing machines which already have the deployment get sucked in and have the release re-deployed.

In most cases you can just exclude the health check, as it is generally performing the role that auto-deploy covers, however there are valid use-cases where you want both. For example you might have a deployment where in step 1 you build some infrastructure, then have a health check to include it in the current deployment. But also want to use auto-deploy.

## Solution
The current thinking is that the Health Check step should have a third option to only include new machines if they don't have the deployment in the current release deployed. This seems to cover all of the customer uses. Another option would just be to never include machines when running inside an autodeploy. But that seems like more of a hack.

**Comment by droyad** [comment]
This does not seem have come up again. We'll reopen if it does. Comment below if you are affected by this.
