### ISSUE TITLE
Investigate potential leaking sockets in Halibut

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#4266]
We have a report of a server that is acting as if it is running out of sockets or something similar.

Investigation shows we might be leaking the TcpClient in some cases, although not in the case that seems to match the customer's logs. Fix the issues we've found and investigate further.

Reported https://secure.helpscout.net/conversation/519642056?folderId=557082 (internal link)

**Comment by distantcam** [comment]
The client code for Halibut is never sending an `END` message. This leaves the server in a state where it's reading the stream, expecting another message. When the socket finally closes the server throws this error.

**Comment by nikitha789** [comment]
I would like to know when this bug would be released? We are having major trouble with this bug.

**Comment by distantcam** [comment]
Release Note: Fixed Halibut issue where connections were kept open by the server

**Comment by nikitha789** [comment]
I don't believe the issue is fixed, I am still facing issue with the package upload.

**Comment by distantcam** [comment]
Unfortunately due to an error this patch never made it out as part of the 2018.8.3 release. I'm redoing it now so it should be out this week.

**Comment by nikitha789** [comment]
I am still experiencing this issue after the upgrade to 2018.5 version, are there logs I can upload to debug this further!

**Comment by distantcam** [comment]
Hi @nikitha789, could you please contact support at https://octopus.com/support where we can help you further. Thanks
