### ISSUE TITLE
Project Variable Templates shows VariableName twice instead of Label value within Octopus V4 UI

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4283]
## Octopus Version:

Tested and replicated in Octopus version 2018.2.1

## Issue:

The Project Variable Templates visible via Variables > Project Templates within a Project now show the VariableName twice masking the previously specified Label value used, this behavior is inconsistent with the results exhibited when using the V3 UI.

## Replication Steps:

1) Login to Octopus with a version using the V4 UI

2) Create a New Project

3) Navigate to Variables > Project Templates

![image](https://user-images.githubusercontent.com/33012349/36237649-e20b9fc4-1248-11e8-9a6b-9f9eebd6576b.png)

4) Select 'Add Template'

![image](https://user-images.githubusercontent.com/33012349/36237677-1b1234c2-1249-11e8-80bc-6015b29db5df.png)

5) Enter a value for 'VariableName', 'Label' & 'Default Value' and select 'Add'

![image](https://user-images.githubusercontent.com/33012349/36237616-9fa50ce2-1248-11e8-85d8-1f52027ec758.png)

6) Within the V4 UI you will now see the VariableName exists as the Header for the VariableTemplate, in addition, to directly showing the same VariableName below. (In this example; Database Password is the VariableName)

![image](https://user-images.githubusercontent.com/33012349/36237591-62ee7d7e-1248-11e8-9c95-6e847d71773e.png)

7) To check this behavior comparatively, replace app# with oldportal# in the Octopus URL to load Octopus using the V3 UI

8) Navigating to the same area, Variables > Project Templates, you will see that the header name shown is populated by the value of the 'Label' field.

![image](https://user-images.githubusercontent.com/33012349/36237756-a794f754-1249-11e8-9500-b203a84c8777.png)

![image](https://user-images.githubusercontent.com/33012349/36237732-751e16e8-1249-11e8-9adc-5f0495b2929f.png)

## Source:

https://help.octopusdeploy.com/discussions/problems/69813

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Option for "Add Template" missing from Project Templates for environment scoped users](https://trello.com/c/YhpmGoKZ/1078-option-for-add-template-missing-from-project-templates-for-environment-scoped-users)

**Comment by pawelpabich** [comment]
Release Note: Variable Template heading displays now Label instead of Name when Label is avaialble
