### ISSUE TITLE
Missing Permission: "TaskView" when performing Deployment Target Health Check

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4287]
## Octopus Version:

Tested and replicated in Octopus version 2018.2.4-ci0008 (Master)

Tested and replicated in Octopus v3 & v4 UI

## Issue:

Performing the health check function, via the connectivity tab of a deployment target, results in a permissions related error that indicates insufficient permissions exist when an environment or project scoping is applied to the user's team.

## Replication Steps:

**I've included an example of the below steps within Master;**

**Please let me know when you require Login details as I've already created a User, Team & Role for this, performing a health check to an available Deployment Target will reproduce the error.**

1) Login to Octopus

2) Navigate to Configuration > Users, then create a New Octopus User

3) Navigate to Configuration > User Roles and create a User Role using the attached permissions.

_(Note: This issue is also apparent on built-in roles that have TaskView & TaskCreate i.e. ProjectContributor & EnvironmentViewer, however, they receive a 'MachineView' error before reaching this point due to insufficient permissions)_

3) Navigate to Configuration > Teams and create a new Team that is governed by the newly created User Role permissions

4) Scope this Team to any particular environment that contains Deployment Targets.

_(Note: This issue is also experienced if you provide scoping solely to a project, and also occurs when both are scoped.)_

5) Specify the originally created Octopus User to belong as a member of this Team.

![image](https://user-images.githubusercontent.com/33012349/36242310-d7d1669c-1266-11e8-9646-4a085b338fb6.png)

6) Login to Octopus using the newly created User.

7) Navigate to a Deployment Target that exists within the previously scoped Environment.

![image](https://user-images.githubusercontent.com/33012349/36242350-26cbc7ce-1267-11e8-9eaa-4dbe3f893a08.png)

8) Select 'Connectivity' and then subsequently proceed to select the 'Check Health' function, you will then be presented with the following error message;

![image](https://user-images.githubusercontent.com/33012349/36242400-92013d4e-1267-11e8-95e2-c79cc27f50a5.png)

## Workaround:

It's possible to include a health check task as a deployment step within the projects deployment process to perform the health check via this method.

## Source:

https://help.octopusdeploy.com/discussions/problems/69658

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/OctopusDeploy/Issues/issues/4287](https://trello.com/c/BDppuK5T/1097-https-githubcom-octopusdeploy-issues-issues-4287)

**Comment by NickJosevski** [comment]
Confirmed on Octopus 3.16

![image](https://user-images.githubusercontent.com/119096/36669715-940011f0-1b41-11e8-8c63-f4aba3362d61.png)

**Comment by NickJosevski** [comment]
A change to a more accurate testing for TaskView has resolved this issue in the 2018.x branch.
