### ISSUE TITLE
Script console: The multi-select component will auto-run a blank script when you hit enter

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4292]
You can cause unintended form submissions using our multi-select controls atm if you press enter. This is especially a problem on the task's script console screen.

For example, you select some targets using the multi-select, hit enter and the form will submit and run, even if you haven't added any script.

Our multi-selects should not cause form submissions when you press enter (because you can use enter to select items in the list, and it's therefore easy to hit enter again unintentionally).

For this screen specifically though, because it triggers a run action on a bunch of (potentially) production machines, I'd argue keyboard "hitting enter" support should be disabled, so users have to specifically tab or mouse to the "Run" button.

Source: https://secure.helpscout.net/conversation/526176249?folderId=801354

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Script console: The multi-select component will auto-run a blank script when you hit enter](https://trello.com/c/KESpHr3M/39-script-console-the-multi-select-component-will-auto-run-a-blank-script-when-you-hit-enter)

**Comment by thebigmoosey** [comment]
Release Note: Disabling keyboard form submissions on Script Console / AdHoc script

**Comment by nicwise** [comment]
follow :)

**Comment by thebigmoosey** [comment]
Hi @nicwise, fyi we pushed this change out with version `2018.2.5` yesterday, so you have to click the Run button (no keyboard "enter" will trigger this accidentally on the script console now).
