### ISSUE TITLE
Built-in support for SNI

### ISSUE THREAD

**Issue by robdmoore** [OctopusDeploy/Issues#430]
Obviously, I could do this using the PreDeploy/Deploy.ps1 script, but there are a few IIS settings that I think it would be really handy to allow tweaking when you ask Octopus to configure IIS, namely:
- `AppPool.ProcessModel.IdleTimeout` - I like to set this to `0` so the app pool doesn't timeout during the day if the site isn't under load (thus causing the next visitor to have a huge delay for the app pool to start up)
- `AppPool.Recycling.PeriodicRestart` - Would be cool to specify a specific schedule for the app pool to recycle at a time when you know the app isn't being used e.g. `2am` in your primary users' timezone - note there are multiple properties that can be set under this such as `Time` and `Schedule` - I like to set `Time` to `0` and clear `Schedule` before setting up a time like `2am`
- `AppPool.StartMode` - I like to set this to `AlwaysRunning` to turn on the web initialisation model (which is then further configured from `web.config`)

The other thing that would be handy is to allow the `preloadEnabled` flag to be set on the website. Unfortunately, it's not that trivial to set it (might be different in IIS8 though), but I've used the following PowerShell code in the past:

``` powershell
function Set-SiteToPreInitialiseAndWarmup($name) {
    [System.Reflection.Assembly]::LoadFrom("C:\windows\system32\inetsrv\Microsoft.Web.Administration.dll")
    $serverManager = (New-Object Microsoft.Web.Administration.ServerManager)
    $serverManager.Sites["$name"].Applications["/"].SetAttributeValue("preloadEnabled", $true)
    $serverManager.CommitChanges()
}
```

This in combination with the AppPool StartMode allow a site to make use of the application initialisation module. More info here: http://bartwullems.blogspot.com.au/2012/11/iis-80-application-initialization-module.html

If it helps - this is the code I've used to set up an AppPool in the past:

``` powershell
function Create-IISAppPool($name, $username, $password) {
    try {
        Get-WebAppPoolState -Name $name | Out-Null
        Write-Output "AppPool $name exists."
    } catch {
        Write-Output "Creating AppPool $name."
        New-WebAppPool -Name $name
    }

    Write-Output "Updating AppPool $name."
    $NewPool = Get-Item IIS:\AppPools\"$name"
    $NewPool.ProcessModel.Username = $username
    $NewPool.ProcessModel.Password = $password
    $NewPool.ProcessModel.IdentityType = 3 # Integrated authentication
    $NewPool.ProcessModel.IdleTimeout = [TimeSpan]::FromMinutes(0) # Remove idle timeout so the site doesn't randomly slow down
    $NewPool.Recycling.PeriodicRestart.Time = [TimeSpan]::FromMinutes(0) # Remove the default 29 hourly recycle
    $NewPool.ManagedRuntimeVersion = "v4.0" # .NET 4.X
    $NewPool.ManagedPipelineMode = "Integrated" # Integrated pipeline
    $NewPool.StartMode = "AlwaysRunning" # Worker is always running - requires application initialization module to be installed
    $NewPool | Set-Item
    Clear-ItemProperty IIS:\AppPools\"$name" -Name Recycling.periodicRestart.schedule # Clear any existing schedules
    Set-ItemProperty IIS:\AppPools\"$name" -Name Recycling.periodicRestart.schedule -Value @{value="02:00:00"} # Add a recycle schedule for 2am when there aren't many users online
    $NewPool.Start();
}
```

Lastly, for those scenarios where a role supports it (e.g. Server 2012 R2 with .NET 4.5.1), it might be cool to allow someone to specify the new App Suspend feature: http://blogs.msdn.com/b/webdev/archive/2013/10/09/enable-and-monitor-asp-net-app-suspend-on-windows-server-2012-r2.aspx. This is only really useful for people that have large web farms with lots of sites running on them so would probably be a lower priority than the rest I would say.

**Comment by dealproc** [comment]
:+1: Thanks @PaulStovell , etc!  Nice work!
