### ISSUE TITLE
Subscriptions permission bug with Machine events

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4307]
We have a bug in our permission system when querying the [Event] table for machines, when your team has restricted scope permissions to one or many environments and/or tenants.

Because machines can be scoped to one or many environments (and/or tenants), you can end up with `NULL` entries in the [EnvironmentId] and [TenantId] column for the [Event] table's machine entries, and instead these multiple values are entered into the [RelatedDocumentIds] column (and corresponding [EventRelatedDocument] table), which is correct from a data modelling point-of-view.

The problem comes when our `ScopedPermissionRequiredRule` tries to apply permissions, it assumes there's a single [EnvironmentId] and [TenantId] column, so when the query executes, it finds no events and returns an empty collection.

E.g. see the following machine events in the [Event] table:

![event-permission-problems-with-machines](https://user-images.githubusercontent.com/819605/36464571-535eda7e-171c-11e8-91e2-8e2c0ed6f484.png)

Our `ScopedPermissionRequiredRule` is being applied by our subscriptions code (and various other places possibly?) as follows:

```
var rule = new ScopedPermissionRequiredRule(typeof(Event), Permission.EventView);
var userEventsQuery = rule.Customize(eventsQuery, userContext);
``` 
https://github.com/OctopusDeploy/OctopusDeploy/blob/66e21a7ab26d8bdd37d2c26521587ad011128813/source/Octopus.Server/Schedules/EventNotifications/NotificationCreator.cs#L162

which will end up adding query conditions based on the user's teams, so you end up with query conditions like this:

```
((([EnvironmentId] = 'Environments-21' OR [EnvironmentId] = 'Environments-2') AND ([TenantId] = 'Tenants-21')))
```

which don't match any machine-related events in the [Event] table (because this data is instead in the [EventRelatedDocument] table), so the user receives no subscription email and/or webhook = 💥 :)

## Proposed Solution

We add a new `ScopedPermissionRequiredRule` specifically for dealing with the [Event] table's corresponding [EventRelatedDocument] table, which will contain ALL the possible environment and/or tenant ids related to the machine event.

Source: https://secure.helpscout.net/conversation/527641163?folderId=801354
and we also have a private Slack thread from the community Slack from the user who reported this, with additional screenshots. 

## Related Follow-up Issue

From the customer:
> I have noticed another permission related issue. When I added myself to the tenant restricted team, check health of a server returns no result even though I'm still on the admin team. As soon as I removed myself from that restricted team, health check returns with proper result again. Might be related? Or it's a different issue.

This sounds like the same permission problem is occurring during health checks. Could we investigate this while we're here, OR if this sounds like a completely separate issue, we can create a related issue.

**Comment by thebigmoosey** [comment]
@NickJosevski Please see the related follow-up note at the end of this issue's description. Wasn't sure whether to create a new issue, as this seemed related to the permissions problem around finely scoped machines/teams.

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Subscriptions permission bug with Machine events - https://github.com/OctopusDeploy/Issues/issues/4307](https://trello.com/c/guIEyJN6/1091-subscriptions-permission-bug-with-machine-events-https-githubcom-octopusdeploy-issues-issues-4307)

**Comment by NickJosevski** [comment]
The health check one I believe is covered by this: https://github.com/OctopusDeploy/Issues/issues/4287

After investigation it's the same class of problem EnvironmentId/TenantId not being on the model in an expected way.

**Comment by NickJosevski** [comment]
Release Note: Fixed subscriptions and web hooks that were not firing for users who had scoped permissions.
