### ISSUE TITLE
Cannot access certificate if tenant tag it's scoped to is deleted

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4388]
Octopus 2018.3.4

Deleting a tenant tag that a certificate is scoped to breaks the ability to view the certificate configuration.

Steps to reproduce.

1) Scope a certificate to a tenant tag
2) Delete the tenant tag

When you try to access the certificate details, you're greeted with the following TypeError:

![certificate_error](https://user-images.githubusercontent.com/20388190/37497908-d2a09092-2906-11e8-84a3-cac3cd340cff.png)

Related to cascade delete issue: https://github.com/OctopusDeploy/Issues/issues/4319

Workaround: Using the oldportal (*OctoURL/oldportal*) you can view the certificate. In its settings, select *Exclude from tenanted deployments*, save, and you can then re-enable tenanted deployments and save.

Source: https://help.octopus.com/t/can-no-longer-open-certificates-from-library-after-update-to-2018-3-1/19170/6

**Comment by KennethBates** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot access certificate if tenant tag it's scoped to is deleted](https://trello.com/c/O7XofieH/1176-cannot-access-certificate-if-tenant-tag-its-scoped-to-is-deleted)

**Comment by NickJosevski** [comment]
Release Notes: Fixed orphaned Tenant Tags impacting Certificates
