### ISSUE TITLE
Variable Preview window is truncating values.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#4392]
The values from a projects Variable Preview are being truncated.

These values should span the size of the window.

Example
![truncate](https://user-images.githubusercontent.com/18252832/37500321-92569640-2914-11e8-91b8-3c497c3aa3e0.JPG)

Source: https://secure.helpscout.net/conversation/540167990/24819?folderId=845288

**Comment by matt-richardson** [comment]
Release note: Fixed the variable preview grid to expand columns to all available space.
