### ISSUE TITLE
Filter in Include Library Variable Set popup is case sensitive

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4398]
Octopus 2018.3.4

When including a variable set into your project, the filter is case sensitive.

![include_variable_set](https://user-images.githubusercontent.com/20388190/37573029-24e6efb8-2b5f-11e8-8134-509a9b210fab.gif)

This is inconsistent, as the variable name filter in project variables is case insensitive, and you cannot add a library variable set with the same name but different casing.

Source: https://help.octopus.com/t/search-box-on-include-library-variable-sets-is-case-sensitive/19230

**Comment by TomPeters** [comment]
Release Note: Library variable set filter when including a library variable set in a project is now case insensitive
