### ISSUE TITLE
Dotnet CLI tool available on all supported platforms

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4403]
The Octo.exe tool should be available as a dotnet CLI tool (`dotnet octo`) and be built and supported on all currently supported platforms (Windows, MacOS, Ubuntu, Redhat, Fedora, OpenSUSE, Debian, Mint)

This issue does not relate to platform support for Octo.exe, which already supports all the above platforms.

**Comment by slewis74** [comment]
This has been implemented, see https://octopus.com/blog/octopus-and-netcore
