### ISSUE TITLE
Pulling data from GitHub Repository Feeds is very slow

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4405]
Octopus is querying the repository history each time a script is required for each individual script. This causes the performance of a release process which uses a GitHub repository to be poor for editing and executing.
This is made significantly worse when a single process uses multiple scripts from GitHub feeds.

**Comment by zentron** [comment]
Release Note:  Release creation page combines requests for the same package + channel filter combination.
