### ISSUE TITLE
Lifecycle phases don't display environments correctly if using the same environments of another lifecycle

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4406]
Octopus 2018.3.5

To reproduce, create a duplicate lifecycle, where each phase has environments defined which are exactly the same as another lifecycle

When viewing *Library > Lifecycles*, some of the environments aren't being displayed underneath the phase name.

![lifecycle_display_environments_in_phases](https://user-images.githubusercontent.com/20388190/37636991-1dd30a7a-2c51-11e8-94be-0fd1c494fe50.gif)

Source: https://help.octopus.com/t/lifecycle-not-showing-environments/19044/7 (private link)

**Comment by droyad** [comment]
This is by design as there is one environment and it matches the phase name.
