### ISSUE TITLE
Edit tags dialog opens the list of tags by default

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#4412]
When editing the tags associated with a tenant, the dialog automatically expands the list of tags for the first set.

I think this has to do with the autofocus on the first form element.

@robpearson 
> the default edit state forces me to select a tag or click away. If I do select a tag, it doesn’t do anything. It goes to the natural edit state where i could click and make changes.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit tags dialog opens the list of tags by default](https://trello.com/c/Pm0NsoLs/1208-edit-tags-dialog-opens-the-list-of-tags-by-default)

**Comment by matt-richardson** [comment]
Retested in 2019.5.1 - cannot reproduce. I've got a recollection of it being fixed, but I cant find a reference to it.
