### ISSUE TITLE
Support Output Variables for Offline Drop

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#4423]
A [highly voted UserVoice request](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/9196032-output-variables-for-offline-drops) (324 votes) is to provide the same support for output variables for offline drops as exists for standard deployments.

Although the execution environment is somewhat different one approach has been suggested that sounds viable.
1. Intercept the output stream from each calamari step
2. Look for any output variable services messages
3. Decode the values and put them into an in-memory hashtable
4. When the _next_ calamari step runs, take this hashtable and pass the variables in.  This can be done with a _new_ variables parameter that just takes a raw base64 encoded JSON representation that is combined inside calamari with the variables obtained through the standard variable files.

**Comment by zentron** [comment]
Resolved By: https://github.com/OctopusDeploy/OctopusDeploy/commit/1802cb20b2ff2065b143d49534e03eacca0de854

**Comment by warrenrumak** [comment]
Yeah!  This makes me super happy.  I'll try it out.

**Comment by zentron** [comment]
One limitation is that given how variables are replaced at the time they are written the `#{}` template format  will not work, you will currently need to use the ` $OctopusParameters[]` format to ensure that they pick up the required values

**Comment by warrenrumak** [comment]
So I tried it.  So far so good.... but is there a specific reason why the Receive-Output function calls `Write-Host $_` instead of just passing through the input, i.e. `$_` ?

**Comment by zentron** [comment]
Was there a reason? Does oversight count? A fix will be provided in the next release to use `Write-Output` instead
https://github.com/OctopusDeploy/Issues/issues/4490
