### ISSUE TITLE
Cannot manually type output variable in script step variable search

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4424]
Reproduced in Octopus 2018.3.7 & Master

To reproduce:

1) Select `Insert a variable` in `Script Content` section
2) Type an output variable

Result: the `[` character causes the page to break, displaying this error: "SyntaxError: unterminated character class" as shown in the gif below.

![script_step_variable](https://user-images.githubusercontent.com/20388190/37940763-c8fc9612-31ad-11e8-853f-0e2a729c3315.gif)

Workaround: Type the `]` character before the `[`.

Source: https://secure.helpscout.net/conversation/548845990/25312?folderId=954335 (private link)

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/OctopusDeploy/Issues/issues/4424](https://trello.com/c/b9kpp1B4/1222-https-githubcom-octopusdeploy-issues-issues-4424)

**Comment by pawelpabich** [comment]
Release Note: Insert variable doesn't throw an error when filter contains regex characters
