### ISSUE TITLE
Move Addons into More menu

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#4434]
Before you have created any tenants, there is an "Addons" menu in the main navbar which allows you to add a new tenant. The Tenants section lives under this Addons menu so that it is still accessible, but hidden from the main navbar to prevent users from seeing tenants until they start using them.

The name of this new menu item "Addons" does not accurately represent its contents and is a little confusing for some people. We are proposing to merge this menu with the "More" menu that appears when you have a constrained browser width, such as in a mobile view.

![image](https://user-images.githubusercontent.com/1892715/38065693-eb516d78-3347-11e8-9ed4-30355734a51c.png)

**Comment by PaulStovell** [comment]
Release note: Removed Addons menu and replaced with Tenants link.
