### ISSUE TITLE
Always generating Sensitive variables 

### ISSUE THREAD

**Issue by ismail-majid** [OctopusDeploy/Issues#4438]
Thanks for taking the time to log an issue.

However, we want our backlog to reflect things we've committed to doing in the near future.

If you've found a bug or something isn't working, please [contact support](http://octopusdeploy.com/support) instead. We don't read new GitHub issues regularly, so if you post here it will likely not get a reply. But if you contact support we can probably help to find a workaround or make sure the issue gets prioritized properly.

If you have an idea or a feature request, please post it to [our UserVoice site](http://octopusdeploy.uservoice.com) so others can vote for it. 

Hi,
      I am using Octopus **2018.2.7**. I am trying to generate an offline package and it always generates sensitive variable files in the variables folder. I don't have any sensitive variable, so I am not sure how to address this. I have to deploy something to the customer now but stuck on this issue?

I hope to receive a quick reply, as its very critical
Thank  You

Best Regards,
Majid

**Comment by pawelpabich** [comment]
Customer contacted support.

**Comment by ismail-majid** [comment]
I have fixed the issue by removing the password set in the offline drop package settings :)

Best Regards,

Majid
