### ISSUE TITLE
Retry doesn't preserve excluded machines settings

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4446]
Octopus 2018.3.8

Steps to reproduce:

1) Create a deployment and exclude a machine
2) Cancel the deployment

When you retry, the default option `Include all applicable deployment targets` is enabled as shown in the below gif.

![exclude_machine_retry](https://user-images.githubusercontent.com/20388190/38232382-17d93fcc-375a-11e8-8668-5755a508d649.gif)

Similar to excluded steps not being preserved on retry issue here: https://github.com/OctopusDeploy/Issues/issues/4132

Source: https://secure.helpscout.net/conversation/550874473/25440?folderId=954335 (private link)

**Comment by KennethBates** [comment]
Closing this issue as it's a duplicate of https://github.com/OctopusDeploy/Issues/issues/4383

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jump list broken, e.g. project switcher - Project switcher item highlighting is on the whole container](https://trello.com/c/cywO80Fi/1248-jump-list-broken-eg-project-switcher-project-switcher-item-highlighting-is-on-the-whole-container)
