### ISSUE TITLE
Prompted sensitive variable uses OD user's password if password is saved in browser

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4450]
Octopus 2018.3.9

Steps to reproduce:

1) Create a sensitive variable and save
2) Change it to a prompted variable
3) Create a release

Chrome: Nothing filled in by default, but the OD password can be used.

![chrome](https://user-images.githubusercontent.com/20388190/38345685-c04d95de-38d3-11e8-8e8a-9cb03fce564b.png)

Firefox: OD password automatically filled

![firefox](https://user-images.githubusercontent.com/20388190/38345688-c50f4036-38d3-11e8-8a9d-32ed07680682.png)

When editing the sensitive variable, the user password is prompted to set as the value:

![editing](https://user-images.githubusercontent.com/20388190/38345693-ca6365f8-38d3-11e8-9a6b-4c45082e2d62.png)

Source: https://secure.helpscout.net/conversation/553510772/25533?folderId=557077 (private link)

**Comment by NickJosevski** [comment]
Closing. This has low impact. Chrome doesn't obey the `autocomplete="off"` decorator there's discussions of alternatives [here](https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7) but we don't want to be battling this.

### Workarounds:
 - Disable your browser or other extensions from auto filling in fields/passwords
