### ISSUE TITLE
Variable set page takes a long time to load (and kills IE)

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4451]
Viewing the variable set page for a variable set that contains a lot of variable scoping takes a long time to render in Chrome and can cause Internet Explorer and Edge to crash.

I am using 30 variables, each with a value for 100 environments:

```
$varSet = $repository.LibraryVariableSets.CreateOrModify("Performance")

$environmentIds = New-Object Octopus.Client.Model.ReferenceCollection
0 .. 100 | % {
    $environment = $repository.Environments.CreateOrModify("SG - Env $_").Instance
    $environmentIds.Add($environment.Id)
}

0 .. 30 | % {
    $variableName = "Variable $_"
    foreach ($environment in $environmentIds)
    {
        $scopeValue = New-Object Octopus.Client.Model.ScopeValue $environment
        $scope = New-Object Octopus.Client.Model.ScopeSpecification
        $scope.Add([Octopus.Client.Model.ScopeField]::Environment,  $scopeValue)
        $varSet.Variables.AddOrUpdateVariableValue($variableName, "Test", $scope)
    }
}

$varSet.Save()
```

Here is the network trace in Chrome (I also have a HAR):
![image](https://user-images.githubusercontent.com/171197/38349659-749ec8ac-38eb-11e8-9403-9b0f398d0e76.png)

I think most of the time is spent rendering.  3 seconds for the API call, 15 seconds total.

I tried loading the page in IE and it took minutes before giving up, Edge crashed.

Reported here: https://help.octopus.com/t/performance-in-iexplorer/19528

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable set page takes a long time to load (and kills IE)](https://trello.com/c/Erd4Pzx1/1252-variable-set-page-takes-a-long-time-to-load-and-kills-ie)

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable set page takes a long time to load (and kills IE)](https://trello.com/c/Erd4Pzx1/1252-variable-set-page-takes-a-long-time-to-load-and-kills-ie)

**Comment by pawelpabich** [comment]
Release Note: Fixed a performance problem in Variable Editor where rendering of variables with a lot of values was slow
