### ISSUE TITLE
Project variable crashes when there are more than 2100 machines available 

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#4453]
1. Use a large data set with over 2100 machines.
2. Navigate to project variables page with enough permissions so all machines are used for the available scope.

![image](https://user-images.githubusercontent.com/347637/38399597-a2ce820a-398e-11e8-81b1-219ed72dbe91.png)

**Comment by droyad** [comment]
This was fixed with the Machine performance improvements around `2018.7`/`2018.11`
