### ISSUE TITLE
Duplicated step name prevent DeploymentProcess from being saved

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#4459]
### Details
Previously `DeploymentProcess` can have duplicated step names, we then added `MustHaveUniqueNamesIgnoreCase` rule without migrating the old data. Once people upgraded to the newer version, they cannot save the `DeploymentProcess` from our UI, the work around is to use the API

### Viable Workaround
 - Use the API to fetch the project, find the problem step, rename it and then post back the change via the API. 
 - Note the steps are case-insensitive

### Contact Support
 - If you are struggling with this issue contact support@octopus.com and we can help you.

**Comment by NickJosevski** [comment]
Current work around: use the API to fetch the project, find the problem step, rename it and then post back the change via the API.

**Comment by NickJosevski** [comment]
Closing: 
 - There's been no reports listed here
 - It could be problematic if we attempted to rename steps in a migration script on behalf of customers.
 - Safest approach is to handle on a per customer request.
