### ISSUE TITLE
PEM Certificate Chains

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#4461]
### Summary ###
Add support for uploading and exporting certificate chains in the PEM format.

We current  support uploading and exporting chains in the PFX format, but not PEM. 

### Reason ###

In the non-Microsoft world PEM format is much more common than PFX.  For example, uploading certificates to AWS requires them to be PEM formatted.

Not being able to access the chain-certificates in PEM format makes these scenarios much more difficult than they should be.

[UserVoice suggestion](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/19168123-allow-uploading-pem-file-containing-certificate-ch)

### Implementation ###

When exporting a certificate in PEM format the user will have the option to control the included certificates (and whether the private-key is included).

![image](https://user-images.githubusercontent.com/113759/38911630-fdbb3800-4313-11e8-808e-bcc7f0dc68f2.png)

We will also add a new variable to the [expanded variables for a certificate](https://octopus.com/docs/deployment-process/variables/certificate-variables#expanded-properties): `ChainPem`.  e.g.
 ```
$OctopusParameters["MyCertificate.ChainPem"]
```

**Comment by michaelnoonan** [comment]
Overall I like the strategy. :+1:

Will you only get the `MyCertificate.ChainPem` if the original cert format was PEM? Certificates can be expensive when it comes to variables already. :)

**Comment by MJRichardson** [comment]
No, it will always be there.  

I think it's nice that you don't need to know what the original format of the certificate was, you can always access the various variables.

But yeah, this does add more bloat to the variables collection.  I'm not sure how to address that?

**Comment by thebigmoosey** [comment]
Release Note: Adding support for uploading and exporting certificate chains in the PEM format
