### ISSUE TITLE
S3 Upload upload behavior and FIPS

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4470]
The S3 step currently checks the ETag provided by AWS against the MD5 content hash to determine whether it should upload a file. It also falls back to skipping these checks when FIPS mode is enabled resulting in files to be uploaded whether the file content has changed or not.

It is suggested that we make this behaviour a bit more flexible by providing the following options on the step:

(o) Only upload files if they have changed
( )  Always upload files

In order to make this behaviour to work with FIPS, we should also fallback to a FIPS supported algorithm such as SHA1 and use object metadata to set this value.

**Comment by johnsimons** [comment]
Given [MS recommendation on FIPS](https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/) and also we haven't received much feedback from customers on this feature, I am closing this issue for now.
If we decide to go ahead, we will reopen it.
