### ISSUE TITLE
Improve UX on show/hide empty groups on Project screen

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4472]
We've had to fix the show hide button a few times, as code changes / it breaks unnoticed.

Idea: move the show/hide toggle from right hand side to be a checkbox next to the 2 filters on the left.

Introduce some tests to ensure it doesn't continue to regress.

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make the show/hide groups better, so the code doesn't regress and the UX is better](https://trello.com/c/0KnQUFXj/1275-make-the-show-hide-groups-better-so-the-code-doesnt-regress-and-the-ux-is-better)

**Comment by droyad** [comment]
We won't realistically get to this any time soon and have decided to close for now.
