### ISSUE TITLE
Execution plan doesn't represent where things are running properly

### ISSUE THREAD

**Issue by MichaelJCompton** [OctopusDeploy/Issues#4478]
![image 1](https://user-images.githubusercontent.com/13693742/38718029-f161d21a-3f2d-11e8-964a-b4b45bbf88a9.png)

*Edit by @matt-richardson*: Specific part that led to this bug being raised was the `step will run on in role` phrasing

**Comment by droyad** [comment]
This UI has changed in the last few months, resolving this issue
