### ISSUE TITLE
New offline drop with output variables not compatible with Powershell 2.0

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#4505]
The new output variables implementation for offline drops uses the `ConvertTo-Json` cmdlet which is not available in Powershell 2.0.

Source (internal link): https://secure.helpscout.net/conversation/564352982?folderId=557077

**Comment by zentron** [comment]
Release Note:  Compatibility fix for Offline Drop output variables on PowerShell 2
