### ISSUE TITLE
Retention policy doesn't allow for channels

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#4511]
**Issue**
When you are using the `channels` feature and have individual lifecycles assigned to each channel, the retention policies will interfere with each other and remove packages from the other channel(s).

Testing is performed with 2018.3.13, issue was reported on 2018.2.6

**Replication**
1. Create a lifecycle which retains releases for 1 day/1 release
![screen shot 2018-04-23 at 3 57 59 pm](https://user-images.githubusercontent.com/29847178/39109188-24dfc24e-470f-11e8-9305-72f82b69a948.png)

2. Create a second lifecycle which retains releases for 3 days/3 releases
![screen shot 2018-04-23 at 3 58 32 pm](https://user-images.githubusercontent.com/29847178/39109202-310b7a36-470f-11e8-9604-a8c2932bc2e8.png)

3. Create a project and add two Channels, `Channel 1` and `Channel 2` and assign a lifecycle per channel
![screen shot 2018-04-23 at 3 58 56 pm](https://user-images.githubusercontent.com/29847178/39109253-642c92e2-470f-11e8-9ec2-f5a0a29bc426.png)

4. Create enough releases with `Channel 2` so that it triggers a release cleanup as part of a retention policy
![screen shot 2018-04-23 at 4 01 36 pm](https://user-images.githubusercontent.com/29847178/39109294-9fb14b3c-470f-11e8-9304-488f00a9f051.png)

5. Perform _one_ release with `Channel 1`
![screen shot 2018-04-23 at 4 02 31 pm](https://user-images.githubusercontent.com/29847178/39109317-c0eec1b2-470f-11e8-90fb-8e46dda26156.png)

6. You will see that releases performed with `Channel 2` where removed by the `Channel 1` releases retention policy
![screen shot 2018-04-23 at 4 03 36 pm](https://user-images.githubusercontent.com/29847178/39109358-e72b8356-470f-11e8-88c6-43c8e9ee8cb9.png)

This is not expected behaviour. This appears to be due to the `DeploymentJournal` not containing any information about the `channel` that has been used
`<Deployment WasSuccessful="True" CustomInstallationDirectory="C:\Octopus\Applications\Test\LifePro\0.0.6" RetentionPolicySet="Environments-1/Projects-1/Step-Deploy a package/Machines-21/<default>" ExtractedTo="C:\Octopus\Applications\Test\LifePro\0.0.6" ExtractedFrom="C:\Octopus\Files\LifePro@S0.0.6@F84AA2C231D28F429220046580986DE6.zip" InstalledOn="2018-04-23 03:11:56" PackageVersion="0.0.6" PackageId="LifePro" ProjectId="Projects-1" TenantId="" EnvironmentId="Environments-1" Id="e3a4da86-3d0e-4834-9a0b-330881afb72c"/>`

**Reported**
[Ticket 1](https://secure.helpscout.net/conversation/564718047/26152?folderId=1465198)

**Comment by thashepherd** [comment]
_Great_ catch - working channel-specific retention policies will really help us out.

**Comment by BrianKrohn** [comment]
Is there any update on this item? I am working around this issue now by deploying to a custom directory. These need to be cleaned up manually, as it appears retention policies don't apply to custom directories.

**Comment by michaelnoonan** [comment]
Is this related? https://octopus.com/docs/administration/retention-policies/retention-policy-tentacle-cleanup-and-troubleshooting#retention-policies-with-channels

**Comment by alexrolleyoctopus** [comment]
As it turns out a resolution to this issue already exists as per our documentation [here](https://octopus.com/docs/administration/retention-policies/retention-policy-tentacle-cleanup-and-troubleshooting#retention-policies-with-channels)

We wil work to make this option more discoverable and/or potentially flip the default for the retention policy in relation to channels.

**Comment by BrianKrohn** [comment]
I do not have that link on the right side of the Project > Process page (v2018.2.6).  Did it get moved somewhere else?

**Comment by zentron** [comment]
This feature is currently available under project settings as per the [link](https://octopus.com/docs/administration/retention-policies/retention-policy-tentacle-cleanup-and-troubleshooting#retention-policies-with-channels) provided by @alexrolleyoctopus above.
Approaches for surfacing this feature better will be taken up internally.
