### ISSUE TITLE
Add an end time to some scheduled project triggers

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4521]
There is confusion over "Start time" selection for scheduled triggers than run hourly or per minute:

![image](https://user-images.githubusercontent.com/171197/39339766-d3d23b78-4a0d-11e8-9fc8-c7c6b9bdae24.png)

When does the trigger actually start and when does it end? I think by adding an "end time" and changing the language so the trigger will "run between" it will be clearer. For example, you could then create a trigger that "Runs every hour between 9am and 5pm".

The existing interface makes sense for other types of triggers, for example "Run every monday starting at 9am".

**Comment by droyad** [comment]
As per #4925, setting the start time to `9:30` means that it only runs between 30 and 59 minutes past

**Comment by droyad** [comment]
Closing as this would be covered in a fix of #4925
