### ISSUE TITLE
Allow password to be passed as parameter to offline-drop scripts

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#4528]
Currently offline-drop deployment scripts prompt for a password to decrypt sensitive-variables.  This is currently implemented using the PowerShell `Read-Host` cmdlet.  

The problem is, if one wishes to write a meta-script to coordinate the execution of multiple project's offline-drop scripts, there is no way to supply the passwords.

We should allow the password to be supplied via a parameter, and prompt only if it isn't supplied.

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow password to be passed as parameter to offline-drop scripts](https://trello.com/c/nir9UJuS/24-allow-password-to-be-passed-as-parameter-to-offline-drop-scripts)

**Comment by zentron** [comment]
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/commit/a7b7e24c49ac022e2bce82b9f753f189d7d79a85

**Comment by zentron** [comment]
Allows users to invoke the offline drop orchestration scripts that typically would prompt for a password if manually run.

Given the generated script of
MyTarget.MyProject.Deployments-12.ps1
If there are no sensitive variables then the script can be programatically invoked, no problem. If there is are sensitive variables however that require a password, the user would be forced to provide the password by typing it in.

This PR allows the user to call the script as
MyTarget.MyProject.Deployments-12.ps1 -Password P@55w0rd!
