### ISSUE TITLE
Changing the name of an in use tenant tag causes temporary error

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#4539]
Using 2018.4.11, I found this issue while working with tenants.

**Steps to reproduce**
- Add a tenant tag set
- Add one of the tags to a tenant
- Rename the tag that was added to the tenant
- Navigate back to the tenant page
- Receive error message _"Cannot read property 'Description' of undefined"_

**Work around**

Complete reload of the page resolves the error.

**Screenshot**

![image](https://user-images.githubusercontent.com/1571799/39611724-54515e66-4f9d-11e8-8efc-a547522ef556.png)

**Comment by matt-richardson** [comment]
Cannot reproduce on 2019.5.1. @ryanrousseau - can you try and see if you can reproduce? If not, can you close?

**Comment by ryanrousseau** [comment]
Sure thing, Matt. I'll check and get back to you.

**Comment by ryanrousseau** [comment]
I can't reproduce in the latest either.
