### ISSUE TITLE
Import Certificates step in offline drop script escapes sensitive vars file wrong

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#4548]
When using the import certificates step in an offline drop deployment the sensitive variables file is escaped with the wrong characters.

```
& "Calamari\Calamari.exe" import-certificate -sensitiveVariables '\"Variables\Example.secret\"' -base64Variables ...
```

The path should be `'Variables\Example.secret'`

Reported here - https://secure.helpscout.net/conversation/574204268?folderId=557077

**Comment by janiekbuysrogge** [comment]
Hi,

Do you have any ETA on this?

We have a manual workaround, but it is kind of a hassle and sometimes it is forgotten and we lose time during deployment.

Thanks,
Janiek Buysrogge
