### ISSUE TITLE
Azure deployments broken with management certificates: "The underlying connection was closed"

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4549]
Various customers have suddenly started experiencing blocking errors when deploying to Azure App Services with Management Certificate accounts, receiving the following error:

> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

## Azure Retiring Support For Management Certificates
Azure recently [announced](https://blogs.msdn.microsoft.com/appserviceteam/2018/03/12/deprecating-service-management-apis-support-for-azure-app-services/) that from June 30th 2018 they are retiring support for Service Management API _(NOTE: Management Certificates use Service Management API)_. This affects deployments to Azure App Services.

If you’re suddenly experiencing issues deploying to your Azure App Service and you’re using a  Management Certificate account (which uses the Service Management API), we advise you [create a new Service Principal account](https://octopus.com/docs/infrastructure/azure/creating-an-azure-account/creating-an-azure-service-principal-account) moving forward and see if that fixes the issues you are seeing. Our guess at this stage is that Azure have started trialling this migration in selected regions earlier than their announcement date :(

Unfortunately we do not allow changing the type of Azure account in Octopus, so you will need to update all places the old Mgt Cert account was used and replace it manually with your new SP account.

We have been trying to reproduce this issue without any luck so far. We’re continuing to try various combinations of Azure regions, O/S and .NET framework to see what triggers this.

Sorry we don’t have better news. We'll keep you posted on our progress.

## Sources
- https://secure.helpscout.net/conversation/576633994?folderId=557077
- https://secure.helpscout.net/conversation/576823502?folderId=557077
- https://secure.helpscout.net/conversation/576844784?folderId=557077
- https://secure.helpscout.net/conversation/576896685?folderId=557077
- https://help.octopus.com/t/an-existing-connection-was-forcibly-closed-by-the-remote-host/19981
- https://secure.helpscout.net/conversation/576448658/26754/?folderId=801354

## Related Issues
We have had reports of a different (but possibly related) issue when deploying to Azure App Services with Management Certificates failing suddenly with 403 errors.
- https://secure.helpscout.net/conversation/576134179

**Comment by thebigmoosey** [comment]
One customer has found a workaround on Twitter [here](https://twitter.com/corneliu/status/994022375493533696), but as we have been unable to reproduce the problem, we are unable to recommend any solutions at this point in time.

**Comment by thebigmoosey** [comment]
A customer has reported that this started randomly working again for them today (using Management Certificate accounts), so our guess is that Azure is periodically doing A/B testing of various regions leading up to the June 30th cutoff date.

Our recommendation at this stage is to convert to [Service Principal accounts](https://octopus.com/docs/infrastructure/azure/creating-an-azure-account/creating-an-azure-service-principal-account) asap :)

**Comment by johnsimons** [comment]
We haven't received any more reports of this issue for a while and since then we also fixed quite a few related issues in the code base, therefore I am closing this issue for now.
If we receive any feedback regarding it, we will consider opening it again.
