### ISSUE TITLE
Parallel Interventions cause unhandled exception

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/Issues#4550]
We have received reports that running a project which uses `Deploy a Release` step targeting a release containing a project with `Manual Intervention` Steps running in parallel will get blocked.

I was able to reproduce the same behaviour as the ticket suggests.

Relating Support tickets: https://help.octopus.com/t/parallel-interventions-cause-unhandled-exception/19954

Octopus Server Version: 2018.4.7 

Steps to reproduce:

- Create a project (Intervention Hangup)
- Add several Manual Intervention steps to “Intervention Hangup” that execute in parallel
- Create a project (Parent)
- Add a deploy release step to “Parent” with “Intervention Hangup” as the target project
- Create a release of “Intervention Hangup”
- Create a release of “Parent”
- Deploy “Intervention Hangup” by itself
- Observe that both interventions can be executed (Proceed or Abort doesn’t matter)
- Deploy “Parent”

*Observation:*
Upon executing one intervention, other interventions can’t be executed.
The UI jumps to the top of the task bar
Selecting “cancel” on the “Intervention Hangup” temporarily displays the dialog:
```Octopus v2018.4.7 The interruption is not pending input System.InvalidOperationException at Octopus.Core.Model.ServerTasks.Interruption.CheckPending() at Octopus.Server.Web.Api.Actions.SubmitInterruptionResponder.UpdateLinkedInterruptions(Interruption interruption, IQueryExecutor queryExecutor) at Octopus.Server.Web.Api.Actions.TaskCancelResponder.CancelLinkedInterruptions(String taskId, IRelationalTransaction transaction) at Octopus.Server.Web.Api.Actions.TaskCancelResponder.ExecuteRegistered(String id) at Octopus.Server.Web.Infrastructure.Api.Responder1.Respond(TDescriptor options, NancyContext context) at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2) at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x) at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)```
“Intervention Hangup” can neither proceed or be cancelled

**Comment by alfhenrik** [comment]
Another report (private link): https://secure.helpscout.net/conversation/605610086/28329/

**Comment by alfhenrik** [comment]
Release Note: Multiple simultaneous interruptions no longer block a deployment from proceeding
