### ISSUE TITLE
Infrastructure > Overview Tenant Tag & Tenant machine count inconsistent with Infrastructure > Deployment Targets machine count

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4551]
## Octopus Version:

Tested and replicated in Octopus version 2018.4.9

## Issue:

The `Tenant Tag` machine count found via `Infrastructure > Overview` is inconsistent with the machine count found via `Infrastructure > Deployment Targets` when filtering to the desired Tag, this occurs in situations where a Deployment Target exists that has scoping applied to a specific Tenant that has this tag.

### Tenant: Gold Octopus / TagSet: Solar & Lunar / Tag: Sun & Moon

![image](https://user-images.githubusercontent.com/33012349/39794771-69519178-538f-11e8-8a6f-8362d52a1872.png)

### Tenant: Purple Octopus / TagSet: Solar & Lunar / Tag: Sun & Moon

![image](https://user-images.githubusercontent.com/33012349/39795133-6edf7ebe-5391-11e8-9e0d-d4e124482685.png)

### Gold Octopus scoped to `Testing` Deployment Target via `Sun` Tag

![image](https://user-images.githubusercontent.com/33012349/39794459-ce739e2c-538d-11e8-8785-195353e2963e.png)

### Purple Octopus scoped to `UAT` Deployment Target via `Moon` Tag

![image](https://user-images.githubusercontent.com/33012349/39794512-0f10ba00-538e-11e8-8a92-ebd5c5c1afe1.png)

### Overview Tenant Tag Count

![image](https://user-images.githubusercontent.com/33012349/39794794-874947e8-538f-11e8-8374-4efbead04604.png)

### Deployment Targets Filtered (Sun & Moon)

![image](https://user-images.githubusercontent.com/33012349/39796396-97e088be-5399-11e8-9e54-0e22912599a4.png)

### Including `Purple Octopus Tenant` scoping to `Production` target

![image](https://user-images.githubusercontent.com/33012349/39796662-41b5f76a-539b-11e8-879e-38e219787731.png)

### Tenant Tag Sets now show `3` targets

![image](https://user-images.githubusercontent.com/33012349/39796697-6eeec978-539b-11e8-9c8e-df0cffc4b678.png)

### Deployment Targets filtered to `Sun` tag  only shows 2 targets

![image](https://user-images.githubusercontent.com/33012349/39796883-91125848-539c-11e8-87bb-4bf9c941e10a.png)

### Tenants count showing `3` targets

![image](https://user-images.githubusercontent.com/33012349/39796945-dcd1b940-539c-11e8-95ba-0058f263c0e2.png)

### Deployment Targets filtered to `Gold Octopus` Tenant showing `2` targets

![image](https://user-images.githubusercontent.com/33012349/39796896-a1fdbac6-539c-11e8-8469-9502af112395.png)

## Source:

https://help.octopus.com/t/octopus-does-not-know-how-to-count/19903/9

https://secure.helpscout.net/conversation/573019044/26568?folderId=1661945

**Comment by droyad** [comment]
Above PR seems to have fixed it
