### ISSUE TITLE
Scheduled Trigger for project with Deploy a Release step fails deployment

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4553]
Octopus 2018.4.12

Steps to reproduce:

1) Configure a Deploy a Release step in process
2) Create a scheduled trigger on the parent project to create a release and deploy

When the scheduled trigger kicks in, the deployment of the parent project fails with error `The step failed: Activity Step 5 on the Octopus Server failed with error ‘The resource ‘users-system’ was not found.’`

Workaround: Manually deploy the release.

Source: https://help.octopus.com/t/deploy-a-release-step-missing-user-error/20031

**Comment by calewis02** [comment]
I am hitting the same issue.

**Comment by calewis02** [comment]
It seems to be using 'users-system' as the 'DeployedById'...I first noticed it when inserting into the Deployment table:

.
.
.
  "DeployedById": "users-system",
.
.
.

**Comment by wgv-srsedate** [comment]
As updated in the original post, the issue also seems to occur in the "Deploy a Package" step as well.

**Comment by KennethBates** [comment]
Another source: https://help.octopus.com/t/deploy-a-release-step-failure/20269

**Comment by praniga** [comment]
Hi

Any update on when a fix will be available.

Thanks
