### ISSUE TITLE
Ability to specify the Web App Slot per channel

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4561]
The new Azure Web App target model, allows you to specify a slot per target which supports varying the app and slot per environment but doesn't allow it to vary per channel.

Octopus needs to provide the ability to set the slot on the step to be able to vary the slot by channel and be able to bind the slot name to a scoped variable, overriding any slot on the target, if set.

**Comment by slewis74** [comment]
Another use case, https://secure.helpscout.net/conversation/589545568?folderId=909887

**Comment by benPearce1** [comment]
Release Note: Added support for specifying slots on Azure Web App targets and steps
