### ISSUE TITLE
ARC doesn't create release when package step name is changed

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4567]
Octopus 2018.5.1

Steps to reproduce:

1) Set up Automatic Release Creation for a package step
2) Change the step name
3) Push a package for this step to the built-in repository

Result: When looking at ARC settings, it shows the changed step name correctly, but no release is created when the package is pushed.

Reconfiguring ARC from scratch for the changed step name doesn't work.

Workaround: Revert the step name back to the original value.

Source: https://help.octopus.com/t/auto-release-creation-stop-working-after-updating-step-name/20118

**Comment by droyad** [comment]
Release Note: Automatic Release Creation now creates releases after a step rename
