### ISSUE TITLE
Deploy Azure Web App fails on external worker with custom deployment scripts

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4572]
Enabling custom deployment scripts when deploying an Azure Web App fails with an error message such as the following when using external workers:

![image](https://user-images.githubusercontent.com/6700195/40227680-83dd4344-5ad2-11e8-8bf7-a6a32747a951.png)

**Steps to Reproduce**

1. Ensure Octopus Server is using and external worker
2. Setup a project with a `Deploy an Azure Web App` step
3. Enable the `Custom deployment scripts` feature
4. Add a body such as `Write-Host "Hello World"` for any of the Pre-deployment, Deployment or Post-deployment scripts

**Comment by droyad** [comment]
Release Note: Steps now correctly load PowerShell modules when running on the external worker
