### ISSUE TITLE
Azure script steps failing to load Azure Modules when using external worker

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4573]
Azure script steps are currently failing with the following error message when using external workers:

![image](https://user-images.githubusercontent.com/6700195/40229166-cb851bdc-5ad6-11e8-8acf-9b9a5c60ba5e.png)

Related to #4572

**Comment by droyad** [comment]
The root cause of this is that the PowerShell variables in the Octopus Variables were not being evaluated due to a changed in the `2018.4.x` timeframe (encryption of all variables at rest).

**Comment by droyad** [comment]
Same problem as #4572
