### ISSUE TITLE
Update Azure modules to latest

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4574]
We should consider upgrading our bundled Azure modules to 6.0.1 or later as there is [a bug](https://github.com/Azure/azure-powershell/issues/6017) which has been fixed which some of our customers have been experiencing.

The `Get-AzureRmEnvironment` is returning an empty result which gives us an error similar to what we are currently experiencing with [external workers and Azure scripts](https://github.com/OctopusDeploy/Issues/issues/4573).

Original source: https://secure.helpscout.net/conversation/582987260?folderId=1576787

**Comment by shaunmarx** [comment]
Please note that configuring to use an external version of the modules does not seem to work in this instance as per our [documentation](https://octopus.com/docs/deploying-applications/azure-deployments/running-azure-powershell/configuring-the-version-of-the-azure-powershell-modules).

A short term workaround in this instance would be to update the modules in place. These would usually exist after first deployment in `C:\Octopus\OctopusServer\Tools\Octopus.Dependencies.AzureCmdlets`.

**Comment by guyvdn** [comment]
We forced Octopus to use the external version of the modules by renaming the Powershell folder inside Octopus.Dependencies.AzureCmdlets\5.7.0. This fixed the issue I reported [here](https://help.octopus.com/t/no-azure-environment-could-be-matched-given-the-name-azurecloud/20194)

**Comment by shaunmarx** [comment]
Please note that the external version of the Azure powershell modules can be configured using the `OctopusUseBundledAzureModules` variable from `2018.5.5` or newer as indicated in our [documentation](https://octopus.com/docs/deployment-examples/azure-deployments/running-azure-powershell/configuring-the-version-of-the-azure-powershell-modules). Updating the azure powershell modules inline should not be required. 

This was renamed from `Octopus.Action.Azure.UseBundledAzurePowerShellModules`, however, from `2018.6.15` the old version of the variable [will be honoured](https://github.com/OctopusDeploy/Issues/issues/4647).

You can revert any in-place module changes made as suggested before by deleting the `C:\Octopus\OctopusServer\Tools\Octopus.Dependencies.AzureCmdlets` folder. This will revert the tool to the bundled `5.7.0` version of the Azure powershell modules.

**Comment by benPearce1** [comment]
Release note: Updated Azure PS to `6.8.1`
