### ISSUE TITLE
LibraryVariableSetView doesn't grant access to view variables in a set

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4582]
Octopus 2018.5.1

Steps to reproduce:

Give a user only `CertificateView`, `LibraryVariableSetView`, `VariableView` and `VariableViewUnscoped` permissions.

This user is then unable to view variables within a set as they should. They're shown the message `LibraryVariableSetEdit Permission Required`.

![variable_set_view](https://user-images.githubusercontent.com/20388190/40343987-03e35d20-5dd6-11e8-8c7e-b704eef2d8f4.png)

If you give them this permission, the message disappears but they still cannot view the variables in the set.

![variable_set_edit](https://user-images.githubusercontent.com/20388190/40343995-104fad66-5dd6-11e8-889b-55416e244a18.png)

Source: https://secure.helpscout.net/conversation/585150934/27262?folderId=954335 (private link)

**Comment by NickJosevski** [comment]
Release Note: Viewing of Library Variable Sets will now check for VariableViewUnscoped instead of incorrectly checking for VariableEditUnscoped
