### ISSUE TITLE
New Dynamic Infrastructure environment flag causing issues

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4587]
After upgrading to 2018.5, a project with the setting to allow deployments without active targets will error at deployment creation time when deploying to an environment where the _Dynamic Infrastructure_ flag has not been switched on.
Error message that is currently showing is `There are no deployment targets in Dev and the environment is not configured to allow dynamic targets to be created.`

The purpose of the check was to give an early warning to the user. If no error was provided the user wouldn't find out until after the deployment has completed with an error.

Possible fix: Add warning to deployment screen to cover this scenario rather than a hard failure.

**Comment by droyad** [comment]
It's also a bit confusing as why do I need to switch the dynamic target flag on if I'm not using dynamic targets.
