### ISSUE TITLE
Certificate variable value not supplied when using `Insert a Variable` function

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4595]
## Octopus Version:

Tested and replicated in Octopus version 2018.5.4

## Issue:

When binding a Certificate variable in the `Import a Certificate` built-in process step, the variable value is not resolved during deployment although the variable name is wrapped in the #{} variable substitution syntax. This leads to an error during deployment indicating that no value was supplied.

Replacing this value by entering the variable name without #{} allows the deployment to successfully proceed.

## UI Deployment Error:

![image](https://user-images.githubusercontent.com/33012349/40594710-201a93ee-6274-11e8-8883-557914be8555.png)

## Replication Steps:

1) Add a new Certificate via `Library > Certificates`

![image](https://user-images.githubusercontent.com/33012349/40594597-7ffcac76-6273-11e8-83a9-01f37732ecbd.png)

2) Create a New Project

3) Add the Certificate Variable into the Project

![image](https://user-images.githubusercontent.com/33012349/40594634-a3c59546-6273-11e8-93c8-069e42df2ca4.png)

4) Add the `Import Certificate` release step

5) Within the `Certificate Variable` use the `Insert a Variable` function to specify the previously created variable.

![image](https://user-images.githubusercontent.com/33012349/40594723-30dbfe20-6274-11e8-8238-049b137cfa9b.png)

6) Create a Release and deploy a release, an error indicating that no certificate value was supplied will occur.

## V3 Behaviour Comparison:

When using the Octopus V3 UI, you are only able to select an existing CertificateType variable via the drop-down menu and the value itself is not wrapped in the #{} variable substitution syntax.

![image](https://user-images.githubusercontent.com/33012349/40594766-7ba3f944-6274-11e8-953d-db91f3d46371.png)

## Deployment Log:

[Deployment Log.txt](https://github.com/OctopusDeploy/Issues/files/2043379/Deployment.Log.txt)

## Workaround:

Instead of using the `Insert a Variable` function, you can specify the variable name in the Certificate Variable field or instead use this to enter the name and then subsequently remove the variable substitution syntax wrapping.

## Source:

https://secure.helpscout.net/conversation/588006052/27438?folderId=1661945

**Comment by MJRichardson** [comment]
We have removed the ability to bind the certificate variable selection to a variable expression.
This was almost impossible to hold correctly, as it was a double indirection, and was almost never what was actually wanted.
