### ISSUE TITLE
Refactor migration.exe into server

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4601]
Migrator.exe can be moved directly into Server now, and have its commands (`import`, `partial-export` etc) happen directly on Server, because we now use these commands in the migration API.

That will provide a side-benefit of us not calling out to an external process (Migrator.exe) during migration api tasks.

While we're here, we should also consider encrypting the contents of an export when migrations are triggered via the API. We encrypt the final zip package, but the contents of the migration just happen as per a usual migrator.exe command.

The plan is to provide an optional `encrypt-export` flag on the migration commands, so that any file system interaction is done with encryption also.

**Comment by droyad** [comment]
This will change with the planned migration/export revamp. Also this is mostly an engineering concern and not user facing.
