### ISSUE TITLE
Status icon continues spinning when changing from In Progress to Success on Dashboard/Tasks page

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#4602]
## Description

Found in 2018.5.4 using IE 11.

![image](https://user-images.githubusercontent.com/1571799/40689579-664e964a-6368-11e8-8e97-f63217580641.png)

It looks like when a task changes from In Progress to Success while viewing the Tasks page, the icon continues to spin.

![spinning-success](https://user-images.githubusercontent.com/1571799/40672549-bfc41544-6334-11e8-86e3-fbdd9f9c69d2.gif)

## How to reproduce

1. Start a deployment
2. Navigate to tasks page
3. Wait for task to change from In Progress to Success

**Comment by droyad** [comment]
We could not reproduce this, comment below if you are still affected
