### ISSUE TITLE
Powershell files with en-dash and other non-ASCII characters fail after upgrade

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#4613]
We have had two reports of scripts that contain en-dashes (`–`) used for PowerShell script parameters failing after upgrading to `2018.5.6`

example:
```
$dnsServerIp = ( Get-DnsClientServerAddress | Select-Object –ExpandProperty ServerAddresses | Select -First 1 )
```

There is also one in the Calamari bootstrapper https://github.com/OctopusDeploy/Calamari/blob/26e8aca40000a1a84c7f38ed66e1ba731e97ee92/source/Calamari.Shared/Integration/Scripting/WindowsPowerShell/Bootstrap.ps1#L457

Report: https://secure.helpscout.net/conversation/591488926/27610?folderId=557077

**Comment by zentron** [comment]
Bugfix - Properly encode non-ASCII characters in scripts

**Comment by droyad** [comment]
This was caused by no BOM being written to the file
