### ISSUE TITLE
Too many system tasks on task list crowd out deployments

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4621]
Now that we have a lot more system tasks (connectivity tests, recurring scheduled deployments, etc), it can be hard to see actual deployments:

![image](https://user-images.githubusercontent.com/373389/41072777-402f8c8a-6a43-11e8-85c6-4ecca45a8ed2.png)

It might be nice to have an option to hide system tasks or even hide system tasks by default (or something else...?)

**Comment by droyad** [comment]
While this is a real problem, and has some strong support, on balance we decided to not make changes here in the near future and see if it continues to come up. We should revisit this once we do Ops Processes.
