### ISSUE TITLE
Account usage and delete SQL can timeout

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#4622]
The queries Octopus server is using to check usage of accounts can cause a SQL timeout. The usage check is also run during a delete, to ensure the account isn't in use.

Sources
https://help.octopus.com/t/timeout-during-account-deletion/18980/4
https://secure.helpscout.net/conversation/590839822?folderId=557082

Related to general performance issue #4681

**Comment by tothegills** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timeouts when using LIKE queries](https://trello.com/c/79d8myPd/31-timeouts-when-using-like-queries)

**Comment by slewis74** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timeouts when using LIKE queries](https://trello.com/c/79d8myPd/31-timeouts-when-using-like-queries)

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/OctopusDeploy/OctopusDeploy/pull/2488](https://trello.com/c/059c5JSQ/102-https-githubcom-octopusdeploy-octopusdeploy-pull-2488)

**Comment by droyad** [comment]
Release Notes: Increased the speed of the Account Usage query
