### ISSUE TITLE
Variable binding expression not appearing in Tenant Common Variables using `Variable Template` - Sensitive Control Type

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4623]
## Octopus Version:

Tested and replicated in Octopus version 2018.5.6

## Issue:

When a variable is bound to the `Variable Template` using the `Sensitive/password box` control type, newly created Tenant files do not show the variable expression, however, this does work as expected during deployment time indicating this appears to be a display issue only.

This behavior is inconsistent when using the control type, `Single-line text box`

## Replication Steps:

1) Create a Variable Template using the two below values (as an example);

![image](https://user-images.githubusercontent.com/33012349/41078531-bc82ae12-6a60-11e8-92c0-e885b49f8fb1.png)

2) The configuration of these is listed below;

![image](https://user-images.githubusercontent.com/33012349/41078552-de8df566-6a60-11e8-971c-641c0775b4ce.png)

![image](https://user-images.githubusercontent.com/33012349/41078575-f85fe6b6-6a60-11e8-8546-f11426be7198.png)

3) When associated with the Tenant that default values appear as the following;

![image](https://user-images.githubusercontent.com/33012349/41080715-0ebd3134-6a6b-11e8-8490-b6d5c080db83.png)

4) During deployment time, however, the variable is resolved as expected so this appears to be a display issue.

## Source:

https://secure.helpscout.net/conversation/594388485/27724/

**Comment by MJRichardson** [comment]
This behavior has changed.  The problem no longer exists.
