### ISSUE TITLE
Keyboard Shortcut in Project Switcher menuitem not working correctly

### ISSUE THREAD

**Issue by poohbear80** [OctopusDeploy/Issues#4630]
When trying to switch to a new project using keyboard arrows and then pressing Enter, I get navigated to the wrong project. It seems that it's only an issue when I first filter with some text.

Steps to reproduce:
* Make sure you have multiple projects available with your logged in user
* Click on Project Switcher, and notice the name of the first element in the list
* Start typing to filter to another project, and that project is the only element in the list
* Use keyboard shortcuts to choose that project with typing down-arrow and then Enter keyboard buttons
* See that you will be navigated to the project which was the first item in the list initially

**Comment by NickJosevski** [comment]
Hi @poohbear80 thanks for the bug report.

I'll close this but link to the other earlier report: https://github.com/OctopusDeploy/Issues/issues/4547
