### ISSUE TITLE
DeploymentLabel character limit validation and error handling

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4635]
We currently allow any arbitrary length value to be specified for the `Octopus.Action.Azure.DeploymentLabel` variable which ends up with some pretty convoluted errors at deployment time if it exceeds the 100 character limit. We can also end up in a similar situation when `Octopus.Action.Azure.DeploymentLabel` is omitted and the `{Action Name}` plus the `{Release Number}` happen to exceed the 100 character limit.

The resulting error would be something like the following:
```
Set-AzureDeployment : Specified argument was out of the range of valid values. 
Parameter name: parameters.Label 
At E:\Octopus\Work\20180611163020-601394-70449\staging\DeployToAzure.ps1:42 char:5 
+     Set-AzureDeployment -Upgrade -ServiceName $OctopusAzureServiceNam ... 
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
    + CategoryInfo          : CloseError: (:) [Set-AzureDeployment], ArgumentOutOfRangeException 
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.HostedServices.SetAzureDeploymentComma  
   nd
```

We should consider adding better error handling so that things fail with a meaningful error message which won't result in unnecessary support tickets and or wasting customers time to track things down.

We should also try and provide some validation around the `Octopus.Action.Azure.DeploymentLabel` variable as well so that we can try and prevent this from happening at deployment time or at the very least fail early.

**Comment by susanpann** [comment]
This issue relates to Cloud Services through the Azure Service Management API, which was [deprecated back in 2018](https://azure.microsoft.com/en-gb/updates/deprecating-service-management-apis-support-for-azure-app-service/) . We've closed the issue as it is no longer being actively supported. See [here](https://www.octopus.com/docs/deployments/azure/cloud-services) for more details.
