### ISSUE TITLE
TypeError: Object doesn’t support property or method ‘fill’ navigating to `Infrastructure > Accounts` using Internet Explorer

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4642]
## Version:

Tested and replicated in Octopus version 2018.6.1

Tested and replicated in Internet Explorer versions;

```
11.0.9600.17146

11.112.17134.0
```

## Issue:

When using Interner Explorer as the specified web-browser, upon navigating to the `Accounts` area found via the `Infrastructure` tab, an unhandled exception occurs that prevents the user from viewing/editing the Account resources in this area.

This issue appears to be browser-specific as the same behavior is not experienced using Google Chrome or Mozilla Firefox.

## Replication Steps:

1) Login to Octopus using Internet Explorer as the designated web-browser

2) Navigate to the `Infrastructure` tab and select `Accounts`

### Internet Explorer:

![typeerror internet explorer](https://user-images.githubusercontent.com/33012349/41444837-e97228d4-7088-11e8-836e-44b4a2072709.gif)

### Google Chrome:

![typeerror google chrome](https://user-images.githubusercontent.com/33012349/41444840-eef92442-7088-11e8-9d59-4dcef353d868.gif)

## Exception:

```
Octopus v2018.6.1

TypeError: Object doesn't support property or method 'fill'

renderContent (/app/areas/infrastructure/components/AccountsLayout/AccountsLayout.tsx:119:8)
render (/app/areas/infrastructure/components/AccountsLayout/AccountsLayout.tsx:135:8)
Lf (/node_modules/react-dom/cjs/react-dom.production.min.js:147:337)
sf:a:{e=b.type;c=b.pendingProps;d=b.memoizedProps;if(nf())null===c&& (/node_modules/react-dom/cjs/react-dom.production.min.js:150:232)
e (/node_modules/react-dom/cjs/react-dom.production.min.js:182:349)
g (/node_modules/react-dom/cjs/react-dom.production.min.js:183:347)
p (/node_modules/react-dom/cjs/react-dom.production.min.js:184:366)
0;null!==a&&c;){c=!1;if(a.pendingWorkPriority===T||a.pendingWorkPriority>b)c=!0,a.pendingWorkPriority=b;null!==a.alternate&&(a.alternate.pendingWorkPriority===T||a.alternate.pendingWorkPriority>b)&&(c=!0,a.alternate.pendingWorkPriority=b);if(null===a["return"])if (/node_modules/react-dom/cjs/react-dom.production.min.js:188:389)
S (/node_modules/react-dom/cjs/react-dom.production.min.js:187:415)
enqueueSetState (/node_modules/react-dom/cjs/react-dom.production.min.js:140:181)
```

## Workaround:

At this stage, the workaround solution is to use an alternative web-browser when attempting to access this area of Octopus.
## Source:

https://help.octopus.com/t/account-maintenance-error/20493

**Comment by Flamage82** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error in IE with Array.prototype.fill()](https://trello.com/c/RxgBUKl8/1454-error-in-ie-with-arrayprototypefill)

**Comment by Flamage82** [comment]
Release note: Fixed an error in the accounts overview in Internet Explorer.
