### ISSUE TITLE
It's possible to not have a default machine policy

### ISSUE THREAD

**Issue by MichaelJCompton** [OctopusDeploy/Issues#4644]
There's nothing in the API to stop the default policy being deleted or switched to not default.

We should add a DefaultMachinePolicyInitializer like we have for the default project group to detect if it’s missing and always make sure one exists.

UI add deployment target breaks if there is no default (source: https://secure.helpscout.net/conversation/599005917?folderId=557077).  Not sure what would happen if you added a machine through the API without a default - it does try to add the default policy if non is given.

**Comment by matt-richardson** [comment]
An initializer like that would only run at startup, though, wouldn't it? I would've thought a rule was the right place for this?

**Comment by tothegills** [comment]
Rules already exist to [prevent the default machine policy from being deleted](https://github.com/OctopusDeploy/OctopusDeploy/blob/e652b33db0293f2ca742eba1a3fbe5c95a1fd84a/source/Octopus.Server/Web/Api/Actions/DeleteMachinePolicyAction.cs#L40) and ensure that [the default can't be toggled off](https://github.com/OctopusDeploy/OctopusDeploy/blob/e652b33db0293f2ca742eba1a3fbe5c95a1fd84a/source/Octopus.Server/Web/Api/Rules/ADefaultMachinePolicyMustExist.cs).
