### ISSUE TITLE
`Missing Resource` in Tenant > Overview > Project Environments

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4645]
## Version:

Tested and replicated in Octopus version 2018.6.1.

## Issue:

When navigating to the `Tenants` area of Octopus it is possible to see associated `Projects` and their respective `Environments` via `Overview > Edit`.

When a Project is connected you can specify the associated environments based on the Projects current lifecycle, however, if the lifecycle is later changed to exclude an environment that was previously specified, you will see `Missing Resource` in the `Environment` scoping and will be unable to remove this connection.

## Replication Steps:

1) Create a new Project using a simple lifecycle (i.e. Test, UAT, Prod)

![image](https://user-images.githubusercontent.com/33012349/41446868-52e34ada-7095-11e8-8f7e-0f82c897511f.png)

2) Connect this Project to a Tenant via `Tenants > Connect Project` and specify these three environments.

![image](https://user-images.githubusercontent.com/33012349/41446883-791cc4c4-7095-11e8-9dc9-c118cfa06616.png)

3) Navigate back to the Project and update the Lifecycle to a Lifecycle that is missing one of these three environments (i.e. Production)

![image](https://user-images.githubusercontent.com/33012349/41446901-a209c1c0-7095-11e8-9dac-7648d07b0e7c.png)

4) When navigating back to the Tenant area, the UAT environment is still visible from the Overview, however, when selecting `Edit` the resource appears as `Missing Resource`

![missing resource](https://user-images.githubusercontent.com/33012349/41447058-a71cc4d6-7096-11e8-94fe-58fd90c1a805.gif)

![image](https://user-images.githubusercontent.com/33012349/41447042-94574b14-7096-11e8-92d1-92696bffcede.png)

## Workaround:

The current workaround to this issue is as follows;

1) Navigate back to the associated Project and change the Lifecycle of the Project to include the missing environment and then subsequently navigate back to the Tenants area to update the connection.

## Source:

https://help.octopus.com/t/your-post-in-unable-to-associate-environment-to-tentant/20190

**Comment by NickJosevski** [comment]
Closing this as it's covered by: https://github.com/OctopusDeploy/Issues/issues/2989
