### ISSUE TITLE
Setting AuditView permission on a custom role doesn't allow users to view events in the audit log

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#4660]
Issue originally raised by @ryanrousseau

The [documentation](https://octopus.com/docs/administration/auditing#viewing-audit-logs) appears to indicate that the AuditView permission allows a user to view the Audit page in the Configuration menu, while this is true, it doesn't provide meaningful output until combined with the EventView permission.  

Is this a documentation issue or a bug?

I think this could be simply addressed with some documentation around setting up a custom Auditors role, but, in case this is a bug...

### Steps to repo:

1. Create a custom user role called 'AuditViewers' and apply the 'AuditView' permission.
2. Create a new team called 'Auditors' and add only the 'AuditViewers' role to it.
3. Create a user called 'Auditor' and add them to the 'Auditors' team
4. browse to https://[your-instance]/app#/configuration/audit and observe an empty list

![image](https://user-images.githubusercontent.com/579657/41688746-7ed9df28-752c-11e8-88d2-2f261e0527f6.png)

### Workaround:
Apply AuditView, EventView, ProjectView and EnvironmentView to the AuditViewers role to take full advantage of the Audit page.

**Comment by NickJosevski** [comment]
`AuditView` is no longer a concept as of 2019.1.

Docs have been updated to reflect this.
