### ISSUE TITLE
Browser tab crashing in chrome only

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#4661]
### Browser specifics
Spotted on Chrome Version 67.0.3396.87 64bit
OK in Firefox and Edge
Not tested on Safari

### Steps to repro:

1. Head to the Audit log
2. Set a date filer
3. Change the 'to' parameter on the query string to a number. E.g: 1 and navigate to that

### Observations
![browser-tab-crash](https://user-images.githubusercontent.com/579657/41688934-4befcc48-752d-11e8-817a-b68d2940193b.gif)

The query string seems to iterate through all possible dates times from 0000-12-31, sending a great many GET requests off api/events

I didn't dig too far but it may be related to momentjs date string parsing

**Comment by NickJosevski** [comment]
### Closing
 - No customer has reported
 - In the current version 2019.2 it kicks off an error about repeated setState class (does about 10 API calls)

### Work around
 - Don't do this.
 - Use the date picker if you put in an invalid date in the URL params such as this you'll see this error:
![image](https://user-images.githubusercontent.com/119096/54731995-899ef200-4be5-11e9-9f71-b2b941faeb2c.png)
