### ISSUE TITLE
VSTS Extension - Widget Service Endpoint Access

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4673]
In order for the VSTS widgets to work the user must be added to the service endpoint `Users` group. We should investigate whether we can allow an admin user to configure the widget to use a separate access token as an alternative in order to use those endpoints alleviating the need to add all users to the given service endpoint group.

Original Source: https://help.octopus.com/t/web-deploy-gives-a-powershell-error-after-upgrade-to-latest-version/20128/47

**Comment by droyad** [comment]
There has not been much demand for this and is unlikely to reach the top of our TODO list. If you would like to see this feature, comment below.
