### ISSUE TITLE
Update Release Variables orphans variable sets

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#4676]
1. Create a library variable set
1. Create a project
1. Add a variable to that project
1. Add the library variable set to the project
1. Create a release
1. Remove the variable and library variable set from the project
1. Click `Update Variables` on release detail page

The project variable snapshot is now orphaned as it's no longer referenced by any releases. It should be deleted if no longer used (snapshots get deleted if the last released referencing them is deleted). This snapshot hanging around prevents accounts and other things being deleted and the user can't do anything about it

Query to find orphans:
```
SELECT * FROM VariableSet 
WHERE id not in (SELECT ProjectVariableSetSnapshotId from Release) 
    AND OwnerId like 'projects%' 
    AND IsFrozen = 1
```

Also the library variable snapshot is now no longer in use and should be deleted (again if the release was actually deleted, it would have been removed). This prevents the library variable set from being deleted, as well as accounts, etc.

Query:

```
SELECT * FROM VariableSet 
WHERE not exists (SELECT * from Release WHERE json like '%' + VariableSet.Id + '%') 
    AND OwnerId like 'Library%' 
    AND IsFrozen = 1

```

Found this in testing another feature, but here is a User Report: https://secure.helpscout.net/conversation/605541234/28327/?folderId=557082
https://help.octopus.com/t/cannot-delete-variableset/20413/8

**Comment by pawelpabich** [comment]
More than likely the fix will need to be accompanied by a migration that gets rid of orphan data

**Comment by droyad** [comment]
If #4622 is released beforehand, don't forget to cleanup the `RelatedDocument` table as well if writing pure SQL.

**Comment by michaelnoonan** [comment]
Release Note: Fixed a data integrity issue where library variable sets could be orphaned when manually updating the variable snapshot for a release
