### ISSUE TITLE
Octopus Dashboard - Project Scrollbar hiding Projects when failed Release exists

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4679]
## Octopus Version:

Tested and replicated in Octopus version 2018.6.5

## Issue:

When navigating to the Dashboard, Projects are being condensed into a scrollbar window that hides the Projects and associated release versions when filtered to `Project Groups`  in scenarios where a deployment is either currently in progress and navigation back to the dashboard occurs, or in scenarios where a project exists with a failed release

### Working Dashboard;

![image](https://user-images.githubusercontent.com/33012349/41951718-ad8c58d6-7a0f-11e8-8520-7e01ea8ebd6f.png)

### Scrollbar Dashboard;

![image](https://user-images.githubusercontent.com/33012349/41952521-ab7bc640-7a13-11e8-86e2-8771bd4c0d4d.png)

## Replication Steps:

1) Create two Projects within the Octopus portal (i.e. Project A, Project B)

2) Create a Project Group and assign these newly created Projects to this group (i.e Project Group Test)

3) Navigate back to the Dashboard and filter the Projects to this Group, you'll notice that both Projects appear on top of each other and any release version for the environments will appear (if any)

4) Create a Release for one of the Projects and set this up to fail, then deploy this release

5) When navigating back to the Dashboard, the Projects will appear on top of each other concealing the secondary Project. 

## Workaround:

At this stage, it appears that refreshing the browser resolves the issue.

## Source:

https://help.octopus.com/t/2018-6-2-vertical-scrollbar-when-filtering-from-dashboard/20554

**Comment by NickJosevski** [comment]
Closing.

Viable workarounds:
 - Refreshing the browser.
 - Reorganizing dashboard to not have as many projects via filters or making use of Spaces.
