### ISSUE TITLE
New server version notification not working

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4685]
The “server has been updated - you should refresh your browser” notification is not working in 2018.6.x. Found during an upgrade from `2018.6.8` to `2018.6.9`, but its been a long time (ever?) since I've seen a notification telling me to refresh due to a server upgrade.

I updated from `2018.6.8` to `2018.6.9` and I still saw the “you have a notification” icon, but when I click on it, it does nothing,

I got this in the console:

```
react-dom.production.min.js:185 Uncaught TypeError: Cannot read property 'length' of undefined
    at r (index.js:91)
    at Function.i [as compile] (index.js:111)
    at o (resolvePathWithSpaceId.tsx:21)
    at Object.r [as resolvePathWithSpaceId] (resolvePathWithSpaceId.tsx:8)
    at u (InternalLink.tsx:50)
    at beginWork (react-dom.production.min.js:149)
    at i (react-dom.production.min.js:182)
    at u (react-dom.production.min.js:183)
    at c (react-dom.production.min.js:184)
    at m (react-dom.production.min.js:188)
```

which appears to be because in `resolvePathWithSpaceId.tsx:8`
```
export function resolvePathWithSpaceId(to: LocationDescriptor, spaceId: string | undefined): LocationDescriptor  {
    if (typeof to !== "string") {
        return {...to, pathname: resolveStringPathWithSpaceId(to.pathname, spaceId)};
    }

    return resolveStringPathWithSpaceId(to, spaceId);
}
```
both `to` and `spaceid` are `undefined`

**Comment by michaelnoonan** [comment]
+1 I just had the same experience with 2018.6.14-2018.6.15.

**Comment by matt-richardson** [comment]
Release note: Fixed issue where the "new server version" notification was not appearing
