### ISSUE TITLE
Output if/what step template is used in raw log

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#4687]
We should output what step template if any was used in the raw logs for each step. This could take some of the guess work out of support when identifying what a particular step is doing and if it is from a built-in template.

Example:
Currently you can add a built-in step template "Deploy to IIS" and rename it "Deploy XYZ" It would be great to be able to see in the logs that the step being run is a built in "Deploy to IIS" step.

**Comment by droyad** [comment]
The templateID would probably suffice to save querying for the template name.

**Comment by danielfischeroctopus** [comment]
Looks like this is implemented, not sure which version but a like like the following can be found in the raw logs when deploying a step based off a template:
`Executing test (type Deploy to IIS) on Machine-A`
Tested in 2019.1.5
