### ISSUE TITLE
Azure Web App should not include Custom Installation Directory feature

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4694]
Our Azure Web App step includes the option for a custom installation directory, which doesn't actually get used. This is confusing customers, as they are (rightfully) thinking this is where we install relative to their web root.

Azure Web Apps have a "Physical Path" variable for this, so we need to remove the Custom Install Directory feature to avoid confusion. We checked and this feature does not appear to be used, and is not mentioned in the docs as something that should be available: https://octopus.com/docs/deployment-examples/azure-deployments/deploying-a-package-to-an-azure-web-app#DeployingapackagetoanAzureWebApp-DeploymentfeaturesavailabletoAzureWebAppsteps

While we're here, we should double check other cloud-related steps to make sure only valid features are available.

Source: https://help.octopus.com/t/custom-install-directory-not-used-with-new-azure-target/20674

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Azure Web App should not include Custom Installation Directory feature](https://trello.com/c/AfMcZicW/832-azure-web-app-should-not-include-custom-installation-directory-feature)

**Comment by benPearce1** [comment]
Fixed in 2018.7
