### ISSUE TITLE
Deploy release doesn't tell you why you can't deploy to some tenants

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#4709]
Repro  steps

Setup:
- Create a multi-tenanted project
- Ensure that it has a multi-stage lifecycle with required phases (eg DEV -> TEST -> PROD)
- Connect a tenant to all of these stages
- Create a release (don't deploy it anywhere yet)

Now on that release, select `Deploy To` and pick an environment from later in the lifecycle (like PROD).

The tenant selection will now be filtered down to the tenants that can currently be deployed to that environment. The tenant you have created will not be available in that selection because you have not yet deployed to the earlier lifecycle phases for this tenant (DEV and TEST).

*The problem here is that there is no indication why some tenants might appear in this list and why others might not appear there.*

The logic for determining whether you can deploy to a tenant is not simple, as it depends on
- the lifecycle (channels could add another dimension here)
- what environments that tenant is connected to
- what releases have been deployed *for that tenant* in the environments belonging to earlier lifecycle phases
- what releases have been deployed *for other tenants* in the environments belong to earlier lifecycle phases

For users with complex tenant setups, this can be difficult to reason about, and this page provides little assistance when a user might expect a tenant to appear there and it does not. Documentation might help but it feels like we could improve the app too.

The same argument could also be made for the environment selection, although the problem is probably not as significant in that case as it is much simpler to reason about.

For example, Tenant C is missing from the available tenants in this list, but why?: https://master.octopushq.com/app#/projects/tomp-tenants-4707/releases/0.0.1/deployments/create/to/Environments-22

![image](https://user-images.githubusercontent.com/1892715/42502441-60cada62-8479-11e8-8ee9-520e2ffec1c4.png)

The answer is that I have not yet deployed to Test for Tenant C yet, which is an environment that Tenant C is connected to.

Support ticket: https://help.octopus.com/t/tenant-not-appearing-as-a-deployment-target/20730

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy release doesn't tell you why you can't deploy to some tenants](https://trello.com/c/OZCSNFGV/136-deploy-release-doesnt-tell-you-why-you-cant-deploy-to-some-tenants)

**Comment by zentron** [comment]
Closing issue unless it is raised again by customer
