### ISSUE TITLE
Can't deploy to a newly created tentacle

### ISSUE THREAD

**Issue by siberianguy** [OctopusDeploy/Issues#4717]
I'm using a cloud version of Octopus and just added a new Tentacle, specified Role and Environment (casing is correct) as usual but my project is not available for deploy to this tentacle:
<img width="900" alt="screenshot 2018-07-13 00 22 57" src="https://user-images.githubusercontent.com/1661681/42646274-fd47087e-8632-11e8-82f0-4d57f96e7b1f.png">
When I go to Process page, the new tentacle doesn't seem to be visible in Default Lifecycle (though tentacle is healthy and is listed in environments):
<img width="261" alt="screenshot 2018-07-13 00 26 04" src="https://user-images.githubusercontent.com/1661681/42646372-5b9902f6-8633-11e8-8b10-76d60bcbc31c.png">
Could you please hint me what to do?

**Comment by droyad** [comment]
@siberianguy Please contact us via our [support page](https://octopus.com/support), you will get an answer quicker that way.
