### ISSUE TITLE
Step status code variable evaluates to succeeded when step isn't run on any machines

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4723]
Octopus 2018.6.15

Steps to reproduce:
1) Create a step targeting a role that will prevent the step from being run
2) On a subsequent step, write the output variable `Octopus.Step[S].Status.Code`

Result:

![skipped_succeeded_status](https://user-images.githubusercontent.com/20388190/42740539-3b9557be-88ec-11e8-95bf-324d116a61d0.png)

This step should populate the status code variable to something other than `skipped`, perhaps `NoOp`. This will allow you to easily write run conditions based on this value.

**Comment by zentron** [comment]
This status code is by design. The previous step ran for all machines for that role. This ticket will be closed unless user feedback indicates it is causing an issue
