### ISSUE TITLE
Package acquisition will not see targets created during the process

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4731]
When using Dynamic Infrastructure PowerShell cmdlet's to create a new deployment target, if a subsequent step deploys a package from an external worker, the deployment will fail. 
Scenarios where this may occur:
 - deploy the same package before and after the step creating the deployment target, the later package deployment will fail
 - creating infrastructure in the pre-deploy script on the package deployment step 
- running an Azure Resource Group template and an Azure Web App deployment where the Web App and ARM template are in the same package

Workaround: Adding a **Health Check** step, configured for a **full health check**, between the script step and the package deployment step which will allow the deployment plan to acquire the necessary packages to the worker.

**Comment by johnsimons** [comment]
Tested this one against v2019.1.3 and it seems to be fixed.
If not we can reopen it.
