### ISSUE TITLE
Service Fabric script steps to use new SF targets

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4751]
### Problem
Due to time constraints, we made the decision to not convert the SF script step to use the new targets, so this step works the same way it always has, where you have to specify the SF connection endpoint and security mode on the step itself.

However in hindsight there's no reason this SF script step can't also take advantage of the new SF targets now (so you don't need to duplicate all the details on the step).

### Solution
We need to investigate making the SF script step take advantage of the new SF targets (and provide backwards compatibility like we do for the SF package step).

Source: https://help.octopus.com/t/service-fabric-powershell-with-target-roles/20878

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SF Script Steps to use new SF Targets](https://trello.com/c/REGzqr6x/862-sf-script-steps-to-use-new-sf-targets)

**Comment by johnsimons** [comment]
Release Note: Service Fabric Script steps now use the new Service Fabric targets

**Comment by prebenh** [comment]
Is this a breaking change?
Will our steps keep working if we haven't defined Service Fabric Targets?

**Comment by thebigmoosey** [comment]
Hi @prebenh, no breaking change. Your existing steps will continue working the way they currently do. This change only effects steps you create moving forward (or if you modify your existing steps by removing the SF connection endpoint field - which is a trigger for the step to realise it should be using targets instead).
