### ISSUE TITLE
Wrong ScriptWrappers selected when run on behalf of roles

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#4756]
Issue with Calamari combined script engine logic...

If you run an Azure Powershell Script step *on behalf of roles* where the role maps to a target that contributes an account (I.e. a k8s or SSH target), the `Octopus.Account.AccountType` property from the step (Azure) gets overwritten with the account from the target (not Azure) and then we fall into the wrong `IScriptWrapper` in Calamari (see the `CombinedScriptEngine`), and the Azure Powershell cmdlets don't execute properly.

We've been able to reproduce this with both a Kubernetes target and and SSH target, which leads to a lot of confusion depending on what you're trying to execute in your scripts.

Source: https://help.octopus.com/t/azure-account-credentials-shadowed-by-ssh-target-account/20887

**Comment by droyad** [comment]
No recent reports, assuming fixed.
