### ISSUE TITLE
Large sets of output variables for offline deployments causes the call to Calamari to fail due to exceeding command-line string limitation

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#4764]
# The bug

When an offline deployment includes many output variables the following error might manifest itself `Program ‘Calamari.exe’ failed to run: The filename or extension is too long`. 

The reason that we're getting this error is that we're exceeding the [command-line string limitation](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation) in Windows _(the knowledge base mentions limits of 2047 and 8191 characters but these were from Windows XP and earlier. In more recent versions, I tested on Windows Server 2008 R2, this limit seems to have been increased to 32766 characters)_ as we Base64 encode the output variables before passing them to the next call to `Calamari`.

## What I expected to happen

I expect the call to `Calamari` to succeed and all my output variables be available to the step.

## Steps to reproduce

1. Add an offline drop target with a role of `Offline`
2. Create a new project
3. Add a script step scoped to the `Offline` role with the following script:
```
foreach($x in 1..200) {
    Set-OctopusVariable -name "VariableName$x" -value "VariableValue$x"
}
```
4. Add another script step scoped to the `Offline` role with the following script:
```
$VariableValue = $OctopusParameters["Octopus.Action[NameOfStepAbove].Output.VariableName143"]
Write-Host "Value: $VariableValue"
```
5. Create and deploy a new release
6. Run the `.cmd` file in the offline drop location
7. After the first step has completed and `Calamari` is called to execute the second step the error `Program ‘Calamari.exe’ failed to run: The filename or extension is too long` should be thrown.

### Log exerpt

```
Program 'Calamari.exe' failed to run: The filename or extension is too longAt D:\temp\offline\Dev\Offline drop
test\0.0.3\Offline drop.Offline drop test.Deployments-3.ps1:36 char:5
+     & "Calamari\Calamari.exe" run-script -variables 'Variables\Offlin ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At D:\temp\offline\Dev\Offline drop test\0.0.3\Offline drop.Offline drop test.Deployments-3.ps1:36 char:5
+     & "Calamari\Calamari.exe" run-script -variables 'Variables\Offlin ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

## Affected versions

**Octopus Server: 2018.3.8 and newer** 

## Workarounds

Limit the number of output variables you create in your deployment, this isn't always possible though if you have a large number of package steps in your deployment as we, by default, create a number of output variables as part of the `Deploy package` step.

## Links

Source ticket: https://help.octopus.com/t/offline-drop-output-variables-brakes-all-offline-deploy/20901

**Comment by VitaliyFedorov** [comment]
Guys, any updates? This bug brake all offline deploys!

**Comment by alfhenrik** [comment]
Release note: Encrypt and write output variables to a file instead of passing them as a base64 encoded string for offline drop targets
