### ISSUE TITLE
Environment Filter missing from Tasks > Filters for User's associated with Environment-scoped Team

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4776]
## Octopus Version:

Tested and replicated in Octopus version 2018.7.7

## Issue:

When navigating to the `Tasks` area of Octopus, the option to provide Environment filtering is missing from the UI when logged in as User who belongs to a Team that has Environment specific scoping.

The option is present, however, for Administrator users who have no scoping in their associated Team, for example.

### Administrator User (No-Scoping) - Environment Filter Present

![image](https://user-images.githubusercontent.com/33012349/43623279-c0bd9de4-9723-11e8-9ab1-d4bc4083890a.png)

### Standard User (Scoping) - Environment Filter Missing

![image](https://user-images.githubusercontent.com/33012349/43623473-b82bfdd2-9724-11e8-972c-22207d418d57.png)

### Administrator User (Team Settings)

![image](https://user-images.githubusercontent.com/33012349/43623620-7e2d9fe0-9725-11e8-8be0-d6fcfb21e70d.png)

### Standard User (Team Settings)

![image](https://user-images.githubusercontent.com/33012349/43623519-01c23650-9725-11e8-99f5-70db3161bc87.png)

## Source:

https://help.octopus.com/t/tasks-hide-advanced-filter/20936/3

**Comment by NickJosevski** [comment]
Release Notes: Fix for showing environment selection for users with scoped environment view permission
