### ISSUE TITLE
AWS CloudFormation links and errors

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4778]
We currently do not provide any means to easily navigate to a given stack or change set to easily review things. Similarly, there are a number of error codes which we link off to in our log messages which needs to be reviewed, cleaned up and changed so that we generate links in the logs in order to make things a bit more seamless.

Links to associated stack and change sets could for example be included in the deployment overview:
![image](https://user-images.githubusercontent.com/6700195/43693927-20e5b416-9974-11e8-81e5-bf3cd4a156a8.png?v=4&s=200)

**Challenges**
- There doesn't seem to be a supported way to get a deep link to the AWS console for a given stack / change set (that we know of)
- Templating is interesting since some endpoints such as the [China endpoints](http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorth_region) are slightly different and of course things may change over time
- Potentially using octopurls - we may need to clearly communicate that we resolve these templates/urls externally if we go down this route

This issue arose after a recent discussion internally [here](https://octopusdeploy.slack.com/archives/C3M85NMHU/p1533509925000071?thread_ts=1533275630.000035&cid=C3M85NMHU)

**Comment by droyad** [comment]
Closing this as it's not clear how this would be done, and the effort required means this would not rise to the top of the pile.
