### ISSUE TITLE
The deployment page should show the options used to created the deployment

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#4782]
Improvement:

When a release has been created and needs review it is currently not possible to return to the `Deploy a Release` screen (e.g to confirm that the required machines have been selected). 

<img width="1251" alt="screen shot 2018-08-07 at 11 37 48 am" src="https://user-images.githubusercontent.com/29847178/43749872-319159a8-9a39-11e8-8c6c-b77274cfacc9.png">

It would be greatly useful if this was possible for any release (either past or future).

**Comment by droyad** [comment]
I think it would make more sense to add the options to the deployment on the deployment details page

**Comment by matt-richardson** [comment]
It'd also be good to show the values supplied to the deployment for prompted variables

**Comment by droyad** [comment]
Related to #4278

**Comment by droyad** [comment]
We have decided to close this as the information is not currently stored long term and will likely come up again as we revamp the deployment page.
