### ISSUE TITLE
Improve capability of variable `Octopus.Date`

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4787]
This came up when a [customer reported](https://help.octopus.com/t/octopus-date-vs-octopus-version-last/20983) the mismatch of leading zeroes in a version number when compared to `Octopus.Date`

It would be nice to have a function that takes the standard C# formatting options to spit out an `Octopus.FormattedDate`.

**Comment by droyad** [comment]
You could use `#{ | NowDate "yyyy.MM.dd"}` or `#{Octopus.Date.Month | Replace "0([0-9]) $1 }`
