### ISSUE TITLE
Azure App Service PaaS target health checks fail

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#4791]
Azure health checks fail when they are scoped to more than one account.  Health check error:

```
The azureserviceprincipal-octofront-service-principal account does not belong to this environment and this project cannot be deployed. Either add the account to the environment or resolve a different account.
```

This was encountered on the internal Octopus instance. Check the following health check logs for more information.
`https:// ... /app#/tasks/ServerTasks-296873`
`https:// ... /app#/tasks/ServerTasks-296880`

Steps to repro:
1. Create an account and scope it to two environments.
2. Added a single PaaS deployment target in one of the environments mentioned above. 
3. Perform a health check => 💥

**Comment by johnsimons** [comment]
@robpearson tried to reproduce this but it seems to work now, can you check it when you have time?

**Comment by robpearson** [comment]
@johnsimons If you followed the repro steps and it worked then I'm happy to close.

**Comment by mbotting** [comment]
@danielfischeroctopus care to weigh on this one? I initially reported the issue as it is occuring on my Octopus instance. I believe you were able to replicate it from my support ticket. Has it been fixed in a recent build?
