### ISSUE TITLE
Cannot create releases when the project's Release Versioning is set to a disabled step.

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#4792]
As per the title, you cannot create a release when a project's `Release versioning` setting is set to use the Version number from a package step that is disabled. It would be great to surface a nice warning/error message here as soon as you save.

Steps to repro:
- Create a project
- Add a package step and configure it
- Update the project `Release versioning` setting to use that package step for releases. 
- Add another package step and configure it. 
- Disable the original step.
- Try to create a release => 💥 

This was found when we updated Octofront to use the new Azure PaaS steps w/ new steps and then disabled the old ones. Then TeamCity failed to create a release.

**Comment by OctopusBob** [comment]
Another sequence of events to disable a release versioning.

1) Add a deploy a package step
2) Add other steps
3) Disable deploy a package step
4) Go to project settings and set the release versioning to the disabled deploy a package step (it works)
5) Attempt to disable other steps => error message

**Comment by matt-richardson** [comment]
Can you still repro this, @robpearson?

I get this:
![image](https://user-images.githubusercontent.com/373389/55035683-ac5d5a80-506c-11e9-9a05-6456da572955.png)

**Comment by robpearson** [comment]
@matt-richardson I believe the original but I reported has been fixed (probably realated to another chunk of work) as it now prevents you from disabling the step. 

@OctopusBob report is a different path and it appears to still be valid. It still has some strange behaviour. 

Strictly speaking. The bug I reported is fixed.

**Comment by matt-richardson** [comment]
Closing in favour of a more specific issue - https://github.com/OctopusDeploy/Issues/issues/5431
