### ISSUE TITLE
Support retaining folder structure when uploading to S3

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#4793]
The built in S3 step currently flattens the package content into a single folder when uploading to S3, if you using the option to unpack and upload vs just uploading the package as is.

There are a number of use cases where content is being hosted using an S3 bucket where retaining the source folder structure is essential and we should update the step to include this as an option.

Source https://secure.helpscout.net/conversation/634319413?folderId=557077

**Comment by slewis74** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Retain folder structure in S3 step](https://trello.com/c/61zYDp5F/879-retain-folder-structure-in-s3-step)

**Comment by shaunmarx** [comment]
Release Note: Fix an issue where s3 multiple file selections would not retain folder structures
