### ISSUE TITLE
Audit - tenant variable document type filter doesn't show events

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4806]
Octopus 2018.7.8

Steps to reproduce:

1) Make a change to a tenant's variables
2) Filter audit page by the `Tenant Variable` document type

Result: These events aren't included in the filtered audit as shown in the following gif.

![tenant_variable_audit_filter](https://user-images.githubusercontent.com/20388190/44008536-2b17e390-9ee8-11e8-9c3e-468d34340ce8.gif)

Source: https://secure.helpscout.net/conversation/638677633/30971?folderId=954335 (private link)

**Comment by TomPeters** [comment]
Release Note: Fixed a bug where tenant variable events were not associated with tenant variable documents

**Comment by TomPeters** [comment]
This fix will not allow you to view tenant variable related events from earlier versions, but any tenant variable related events that are created after this fix has been applied will not work with that filter
