### ISSUE TITLE
Can't reset tenant variable value for sensitive variables

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#4808]
Repro steps:
1. Create a project with a sensitive project variable template. Give the template a default value.
2. Link a tenant to that project.
3. Add a value for the sensitive variable template for that tenant and save
4. Attempt to reset this value back to the default by removing the sensitive value from the tenant. Hit save.

You'll find that when you return to the tenant's variables, it still appears as if you have overridden the variable value, and indeed the act of removing the sensitive value was ignored by the server. If you try to deploy and use this variable now, it won't use the default, but will instead use the value you specified in step 3.

![2018-08-14_15-23-59](https://user-images.githubusercontent.com/1892715/44073950-02b63ff8-9fda-11e8-9b4b-eb50055344d0.gif)

Source: https://secure.helpscout.net/conversation/640463137?folderId=557077 (private link)

**Comment by jburger** [comment]
This change does seem to fix the underlying issue of the wrong values being used after the delete button is used.

There are some other issues with the visuals but I'll check to make sure we don't have an issue raised for that

**Comment by TomPeters** [comment]
Release Note: Fixed a bug where removing the sensitive value from a tenant variable would not update the value
