### ISSUE TITLE
add an "are you sure" when adding first worker to the default pool

### ISSUE THREAD

**Issue by MichaelJCompton** [OctopusDeploy/Issues#4818]
Adding the first worker to the default pool is system changing moment.  It means that steps that used to run on the Octopus Server will now be transported elsewhere.  It's a moment that's probably worth stopping to confirm.

So when adding the first worker to the default pool the UI should popup a confirmation that has some explanation of what's about to happen and asks to confirm.

**Comment by thashepherd** [comment]
Thank you! (This is @malioto from the Octopus user group on Slack)

**Comment by droyad** [comment]
Instead of a dialog, can we add explanatory text at the top of the add page? We should run this past the #ux team

**Comment by MichaelJCompton** [comment]
Release Note: Added a warning when the first Worker is added to the default pool.
