### ISSUE TITLE
Move lifecycle auto deploy from automatic release creation to scheduler

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4820]
Package push can cause lifecycle automatic deployment to trigger by setting up automatic release creation and setting the first phase of a lifecycle to auto deploy. When this happen, the lifecycle automatic deployment is evaluated by the package push API call. We want to move this evaluation so it lives with the rest of the automatic deployment evaluation code in the scheduler.

A point of friction towards achieving this is the difficulty determining when a release has been created from the `Event` table. We could create a new event category specifically for release created events (as machine triggers have done for machines) or extend the `Event` table.  After discussion we decided to explore creating a new event stream specifically for automatic deployment events.

With the creation of auto-deploy we introduce some jankiness into the `Event` table trying to adapt it to auto deploy. We started adding short-lived events for machine health statuses that aren't really audit-related events. We double up on some events, for example `MachineAdded`, to cater for auto deploy. We struggle to adapt the data for its dual purposes: auditing and triggering automatic deployments.

As a part of this issue let's explore decoupling audit events and auto deploy events. There will be some doubling up of event generation, certain events will go into both the audit and auto deploy event streams. The `Event` table will only contain events relevant to auditing and we can go back to guaranteeing that nothing is ever removed from that table (currently there is retention on some events). The auto deploy event stream will contain only events relevant to auto deploy, and we can run retention on those events as required. The auto deploy event model can be tailored to contain exactly what we need to process auto deployments.

**Comment by tothegills** [comment]
See https://octopusdeploy.slack.com/archives/C033W4273/p1534462841000100

**Comment by droyad** [comment]
Should consider this for machine triggers as well

**Comment by droyad** [comment]
Closing as this is an internal engineering concern and will be addressed there.
