### ISSUE TITLE
Halibut Memory Leak

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#4824]
A customer investigated their servers memory usage and discovered that Halibut was the main culprit.

The memory profile suggest that there's a lot of `RequestMessage` being held onto by many `InMemoryConnectionLog`

**Comment by distantcam** [comment]
It looks like there's an unbounded object pool for `InMemoryConnectionLog` so while the internal `RequestMessage` is limited, there can be an unlimited amount of `InMemoryConnectionLog`.

**Comment by droyad** [comment]
Could be the same as, or related to #4227

**Comment by distantcam** [comment]
Release Note: Fixed memory issue in Halibut
