### ISSUE TITLE
Possible to get through the tentacle install process without having connectivity.

### ISSUE THREAD

**Issue by samrueby** [OctopusDeploy/Issues#4832]
We ran into a situation where we got through the tentacle install process using a Polling Tentacle and in the end, the Octopus Server could not communicate with the Tentacle. 

This can happen if the Polling Tentacle is on a domain where all connections are intercepted. The domain prohibits clients from connecting to sites with invalid TLS certificates. The Polling Tentacle connects to the Octopus Deploy server that serves a self-signed certificate on port 10943. We understand that the way this is operating is secure and legitimate. 

Expected behavior: users should be warned of this type of connectivity problem prior to finishing Polling Tentacle installation. It was confusing to get through the process successfully, but then see that an endpoint was unhealthy because Octopus Server could not communicate with the tentacle.

**Comment by droyad** [comment]
@samrueby Thank you for reporting this problem, however please contact us via our support channels https://octopus.com/support in the future as we don't monitor this repository regularly. 

It's unclear to my what is preventing the connection.. Is it an intermediary proxy? Why did the problem not occur when registering? During registration we connect to make sure the polling port is accessible.

**Comment by samrueby** [comment]
I'm no looking for help to solve the connectivity issue and didn't mind if I don't get an immediate response, so this location seemed appropriate.

I am not positive if it is an HTTP proxy that is automatically configured or if all outbound connections are being monitored through the gateway. It's an enterprise network, that isn't ours.

I can't really explain when the problem didn't occur during registering- I just know that it didn't. I'm guessing how Octopus works, but perhaps when you first give the Polling Tentacle the address it connects to the server through the API. We have a valid certificate configured for the web UI/API. The Polling Tentacle connects via 10943 where the server is expecting a client certificate. In this case, Octopus Server's certificate is not one signed by an authority, and this is where the connection is being interrupted by the network's gateway.

**Comment by droyad** [comment]
During registration we do check on port 10943 as we need to get the server certificate thumbprint. We connect on the port and make sure we get a  Could it be that the user doing the registration bypassed the gateway rule while the account that the Tentacle runs as doesn't?

**Comment by samrueby** [comment]
I don't think so- even if we try to connect to 10943 over https as a more-privileged user, we're presented with a message that appears to come from the gateway that the connection is not allowed because the certificate is invalid.

**Comment by droyad** [comment]
Interesting. Could you grab me a screen shot or export of the request from the browser's network tab showing that request and response. I wonder whether the gateway is returning a 200 result.

**Comment by samrueby** [comment]
![tentacle connect](https://user-images.githubusercontent.com/4096958/44658244-18d88400-a9ce-11e8-82e6-7ac7bfa0a8af.png)

Yes, the gateway is returning 200.

**Comment by droyad** [comment]
Thanks for confirming that. I don't think this is something we will handle. It's the first time we've come across this and I'm not even sure how we would confirm definitively it's a server as the server would reject any further communication due to the thumbprint not being trusted.

**Comment by samrueby** [comment]
Isn't it true that if the tentacle verified some sort of payload instead of just checking for code 200, the installation process could have noticed a problem with connectivity?
