### ISSUE TITLE
User can create step template task but not view it

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#4834]
Unable to retrieve ServerTasks with a user with TaskView permissions

### Steps to reproduce 

Using the C# client, with an API Key for a user with TaskCreate & TaskView permission, 
scoped to some environments, some tenants and a project (with appropriate permissions to create tasks based on a step template)

1. Create a task from a given step template, targeting a machineId that exists in one of the environments the team is scoped for.
2. Using the same client, attempt to retrieve the TaskResource (using `FindOne(t => t.Id == taskId)`  -- `Get(taskId)` seems to be fine)

#### Expected result
This should bring back the TaskResource
#### Actual result
No TaskResource is returned
#### Workaround
Setup the team such that it is unscoped for environments. Not suitable in most cases because team are usually scoped to environments for security reasons.

**Comment by jburger** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User can create step template task but not view it](https://trello.com/c/k0QEOQ5V/1682-user-can-create-step-template-task-but-not-view-it)

**Comment by NickJosevski** [comment]
Fixed in 2019.1.0.
