### ISSUE TITLE
TypeError on Scheduled Triggers if user doesn't have access to all environments for project

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4836]
Octopus 2018.7.13 & Master

Steps to reproduce:

1) Scope a user's team to a certain environment(s)
2) On the project, assign a lifecycle to it that includes more environments than the user has permissions for
3) Try to enter a scheduled trigger

Result:

![typeerror_trigger_permissions](https://user-images.githubusercontent.com/20388190/44559778-7cc13980-a78f-11e8-8beb-f11f6d5f7084.gif)

Source: https://help.octopus.com/t/ui-error-when-creating-scheduled-trigger-if-user-account-is-restricted-by-what-environments-it-can-access/21125

**Comment by flin-8** [comment]
Release Note: Fix TypeError on Scheduled Triggers if user doesn't have access to all environments for project
