### ISSUE TITLE
Service Fabric targets with Certificates fails on cloud-hosted instances

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4841]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using a cloud-hosted instance of Octopus, if you try to use Service Fabric targets with the Certificates as the security mode, exceptions are occurring.

**PLEASE NOTE** - I was not able to reproduce the same exception the customer has reported, but I received a different exception. When working through this issue, please investigate that the fix will solve the original issue reported by the customer as well.

## Steps to reproduce

1. Create a cloud instance
2. Create an SF cluster on Azure, using certificates and a key vault, wait until the cluster is "Ready"
3. Create an SF target in your cloud instance, setup to use the certificate available on Azure
4. See error during health check (see attached log)

### Screen capture
<img width="1527" alt="screen shot 2018-08-27 at 12 38 43 pm" src="https://user-images.githubusercontent.com/819605/44637712-299cf000-a9f6-11e8-8af7-df93f54fe5fd.png">

### Log exerpt

[ServerTasks-29.log.txt](https://github.com/OctopusDeploy/Issues/files/2322227/ServerTasks-29.log.txt)

## Affected versions

Occurs in latest version of Octopus `2018.7.11` from a cloud-hosted instance.

## Workarounds

Overrride the default certificate store location as part of the step:
![image](https://user-images.githubusercontent.com/122651/52610588-879e9080-2ecd-11e9-800d-8e3ddeba2466.png)

## Source

https://help.octopus.com/t/unable-to-create-azure-service-fabric-target/21133

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service Fabric targets with Certificates fails on cloud-hosted instances](https://trello.com/c/QplWHrZj/914-service-fabric-targets-with-certificates-fails-on-cloud-hosted-instances)

**Comment by johnsimons** [comment]
We allow the users to override the certificate store location for this exact reason.
Hence I am closing this issue.
