### ISSUE TITLE
Reference Packages from Script Steps

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#4842]
### Why
Historically, Script Steps (Run a Script, Run an Azure PowerShell Script, Run an AWS CLI Script) have allowed optionally sourcing the script from within a package. This is certainly useful, but does not support (or does not nicely support) the following scenarios:

**Packages which do not contain the source script**
You may wish to write a script which uses a tool contained in a package. A good example of this is nuget.exe. This required creating a "wrapper package" which would bundle both the tool and the source script.

**Un-extracted packages**
The package containing the script is currently always extracted. Working with an un-extracted package again required creating a wrapper package.

**Container images**
Because Octopus has not had support for executing a script from within a container image, there has been no way to reference container images from script steps. The work-arounds for this have involved either creating a dummy package to mimic the container image, or using variables to represent the container image.

### What
To address the issues above, we have added support for referencing packages from script steps.
These referenced packages do not contain the script-source (that can still be obtained from a package).
The referenced packages are given a name, and can optionally be extracted (depending on the feed-type).

![nuget-add-package](https://user-images.githubusercontent.com/113759/44705176-38140600-aae1-11e8-9d3d-6a5736b75f53.png)

![script-step-package-references](https://user-images.githubusercontent.com/113759/44705220-57ab2e80-aae1-11e8-8e98-85c81e48bcea.png)

Indexed variables are supplied to the custom script. e.g. a package-reference named `acme` would contribute the following variables:

```
Octopus.Action.Package[acme].PackageId
Octopus.Action.Package[acme].PackageVersion
Octopus.Action.Package[acme].FeedId
Octopus.Action.Package[acme].ExtractedPath
```

For packages which are acquired, the package file/s will be added the working directory.
If the package is extracted, it will be extracted under the working directory named the same as the package-reference. e.g. `./acme`
If the package is not extracted, the package file will be dropped in the working directory, again named as the package-reference. e.g. `./acme.zip`

### Related UserVoice Issues
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/16824922-script-files-inside-a-package-run-multiple-scripts
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/19280662-allow-scripts-to-reference-nuget-packages
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/18158758-add-custom-deployment-script-feature-to-transfe
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/5235333-deploy-nuget-package-to-nuget-feed

**Comment by thashepherd** [comment]
![image](https://user-images.githubusercontent.com/711467/45311320-bbc4ee00-b4f6-11e8-95f5-b3aa295b639a.png)
Is there a way to unify the package version selected across multiple steps?
