### ISSUE TITLE
VariableSet API is slow when there are lots of tenants

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#4845]
/api/variables/variableset-XXX api requests have very long duration 20-24 seconds.

Source: https://help.octopus.com/t/suggest-to-change-tenantproject-view/21156/3

This is due to the `TenantProject` view performing string splitting on ` Tenant.ProjectIds`. This should be replaced with the `RelatedDocuments` table or a dedicated table.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VariableSet API is slow when there are lots of tenants #4845](https://trello.com/c/pmmq8QlZ/153-variableset-api-is-slow-when-there-are-lots-of-tenants-4845)

**Comment by flin-8** [comment]
I'm not sure if it's the view... 

On a DB with 68 projects x 2600 tenants resulting in 14K rows in `TenantProject` , the query takes 1-2s to return in SSMS

**Comment by droyad** [comment]
The usage of `TenantProject` view was removed in https://github.com/OctopusDeploy/OctopusDeploy/pull/2702
