### ISSUE TITLE
HTTPS_PROXY not set for AWS CLI

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4860]
# The bug

The AWS CLI uses the HTTPS_PROXY environment variable for proxy details and we don't set this environment variable when the tentacle web proxy has been configured.

## What I expected to happen

The HTTPS_PROXY environment variable should be set when the tentacle web proxy environment variable has been specified. In addition to this, the Tentacle configured proxy should not override the HTTPS_PROXY environment variable.

## Steps to reproduce

1. Configure a proxy
2. Configure a tentacle to use the proxy
3. Run an AWS Cli command such as `aws sts get-caller-identity`
4. Notice the error

## Affected versions

**Octopus Server: 2018.2.0 - 2018.8.1** 

## Workarounds

Set the HTTPS_PROXY environment variable in addition to the tentacle web proxy details for the associated worker machine.

## Links

https://secure.helpscout.net/conversation/651800838?folderId=557080

**Comment by benPearce1** [comment]
Resolved in https://github.com/OctopusDeploy/Calamari/pull/320

**Comment by benPearce1** [comment]
Release Note: Support for proxies in AWS CLI in AWS CLI script steps
