### ISSUE TITLE
Octopus Cloud instances are showing renewal warnings

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4869]
Customers who are on a month-by-month Octopus Cloud plan are seeing warnings about license expiration and that they need to renew.

![image](https://user-images.githubusercontent.com/373389/45128074-55bb2c80-b1bf-11e8-973f-3f6f64736baf.png)

As renewals are automatically processed, we should suppress this warning in this scenario.

source: https://secure.helpscout.net/conversation/655929734?folderId=557077 (private link)

**Comment by michaelnoonan** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/2837

**Comment by michaelnoonan** [comment]
Release Note: Octopus Cloud instances no longer show license expiry notifications since those are tailored towards self-hosted licenses.
