### ISSUE TITLE
Azure CLI will fail to login if password contains special characters

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4873]
# Prerequisites

- [ x] I have verified the problem exists in the latest version
- [x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ x] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [x ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When executing an Azure PowerShell step where the password contains a special character (`%, (, "`), the `az login` line in `AzureContext.ps1` may fail with an error:
```Error: % was unexpected at this time.```

## What I expected to happen

Login should have occurred correctly

## Steps to reproduce

Using an Azure Service Principal account, where the password is valid and contains one of the characters listed above, execute an Azure PowerShell script step.

### Log exerpt

```
Verbose: Azure CLI: Authenticating with Service Principal
Verbose: C:\Octopus\Work\20180903123948-22063-30> “C:\Octopus\OctopusServer\Tools\Octopus.Dependencies.AzureCLI\2.0.42\AzureCLI\wbin\…\python.exe” -IBm azure.cli login --service-principal -u XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -p ******** --tenant ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ
Error: %( was unexpected at this time.
Verbose: Azure CLI: Setting active subscription to YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY
Error: ERROR: The subscription of ‘YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY’ doesn’t exist in cloud ‘AzureCloud’.
Verbose: Successfully authenticated with the Azure CLI
```

## Affected versions

**Octopus Server:** 2018.7.4+

## Workarounds

In project variables, set `OctopusDisableAzureCLI` to `True`. This will disable the Azure CLI login. (Only available in 2018.8+)

Modify the password to not include special characters.

## Links

[source](https://help.octopus.com/t/azure-powershell-works-octopus-fails/21211)

**Comment by jburger** [comment]
Similar issue here [Internal support link] https://secure.helpscout.net/conversation/699118531 `|` characters appear to be an issue too.

**Comment by shaunmarx** [comment]
Release Note: Fix an escaping issue causing Authentication issues with Azure CLI, when using new Azure App registrations preview blade.
