### ISSUE TITLE
Audit log contains sensitive variables

### ISSUE THREAD

**Issue by sbebrys** [OctopusDeploy/Issues#4874]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Audit log contains sensitive variables

## What I expected to happen

I think we couldn't have access to sensitive variables in all UI.

## Steps to reproduce

1. Go to 'Audit'
2. Select 'Variable set' in document type filter
3. Show diff from variables
4. There are sensitive variables

### Screen capture

![2018-09-07_16h25_58](https://user-images.githubusercontent.com/22738365/45225032-cd6e8180-b2bb-11e8-8af0-3f171d53081d.png)

## Affected versions

It is in version 2018.7.3 and 2018.8.2

**Comment by droyad** [comment]
@sbebrys 

This is a hash of the secret. Eg here is the entry for `abcd`:
![image](https://user-images.githubusercontent.com/1687639/45269888-e6a04980-b4d8-11e8-81cc-09d8001b961a.png)


Also, please contact us via our [support](https://octopus.com/support) channels to ensure your question gets triaged and responded to quickly.
