### ISSUE TITLE
Bitbucket pipelines using Octo.exe docker image does not support project names with spaces

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#4878]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using the `octopusdeploy/octo` (specifically `octopusdeploy/octo:4.37.0-alpine`) Docker image in Bitbucket Pipelines and you call `octo deploy-release --project "Test Website 2018"` `octo.exe` throws the following error `Unrecognized command arguments: Website, 2018`

**NB** Running the same Docker image locally (on both Windows and MacOS) does not exhibit the same issue.

## What I expected to happen

The call to `octo.exe deploy-release` to succeed.

## Steps to reproduce

Follow the instructions [here](https://octopus.com/docs/api-and-integration/bitbucket-pipelines) but instead of running `octo pack/push` call `octo create-release` for a project that has spaces in its name.

### Screen capture

![image](https://user-images.githubusercontent.com/1035315/45281223-829e7500-b51a-11e8-9808-20db9f6f7934.png)

## Affected versions

**Octopus Server:** N/A

## Workarounds

I have been unable to find any combination of escaping that makes the call to `octo.exe` succeed.

The following permutations have been tested in the `bitbucket-pipelines.yml` file:
- *octo create-release --project "Project With Spaces" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project \"Project With Spaces\" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project 'Project With Spaces' --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project ""Project With Spaces"" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project \"Project\ With\ Spaces\" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project \\"Project\\ With\\ Spaces\\" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project ''Project With Spaces'' --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project "Project\ With\ Spaces" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project="Project With Spaces" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project="""Project With Spaces""" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project `"Project With Spaces`" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project `Project With Spaces` --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project `'Project With Spaces`' --version `'$VERSION`' --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *octo create-release --project='Project With Spaces' --version='$VERSION' --server=$OCTOPUS_SERVER --apiKey=$OCTOPUS_APIKEY*
- *octo create-release --project=\\"Project\\ With\\ Spaces\\" --version=$VERSION --server=$OCTOPUS_SERVER --apiKey=$OCTOPUS_APIKEY*
- *'octo create-release --project="Project With Spaces" --version=$VERSION --server=$OCTOPUS_SERVER --apiKey=$OCTOPUS_APIKEY'*
- *'octo create-release --project=\"Project With Spaces\" --version=$VERSION --server=$OCTOPUS_SERVER --apiKey=$OCTOPUS_APIKEY'*
- *'octo create-release --project=''Project With Spaces'' --version=$VERSION --server=$OCTOPUS_SERVER --apiKey=$OCTOPUS_APIKEY'*
- *"octo create-release --project=\"Project With Spaces\" --version=$VERSION --server=$OCTOPUS_SERVER --apiKey=$OCTOPUS_APIKEY"*
- *"octo create-release --project \"Project With Spaces\" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY"*
- *"octo create-release --project '''Project With Spaces''' --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY"*
- *'octo create-release --project ''Project With Spaces'' --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY'*
- *octo create-release --project $OCTOPUS_PROJECT --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY*
- *"octo create-release --project \"$OCTOPUS_PROJECT\" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY"*
- *"octo create-release --project '$OCTOPUS_PROJECT' --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY"*
- *"octo create-release --project \"'$OCTOPUS_PROJECT'\" --version $VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY"*

Environment variable `$OCTOPUS_PROJECT` tested with the following values:
- `Project With Spaces`
- `'Project With Spaces'`
- `"Project With Spaces"`
- `\"Project With Spaces\"`
- `\'Project With Spaces\'`
- `''Project With Spaces''`
- `""Project With Spaces""`

## Links

https://help.octopus.com/t/octo-exe-project-name-with-spaces/21242

**Comment by adam-resdiary** [comment]
For the record, I've just run into this problem as well. I also tried using `%20` and replacing the space with a dash (`-`) since that's what's in the URL in Octopus, but with no joy. For now I think we're going to have to rename our projects if we want to be able to use the docker image.

**Comment by hnrkndrssn** [comment]
Fix for this issue has shipped in the `octopusdeploy/octo:4.46.2-alpine` docker image now available
