### ISSUE TITLE
Ideas / Feedback for migrating resources between Spaces.

### ISSUE THREAD

**Issue by Flamage82** [OctopusDeploy/Issues#4883]
Note: This discussion assumes the initial version of Spaces has been released.

# Problem
One major drawback in the initial release of Spaces is that we can't move resources between spaces.  This will limit the appeal of Spaces to those customers who would want to migrate existing projects, etc, into different spaces as the only way to do this now is to re-create them in a new space.

# Solution
In Spaces vNext after the initial release, we want to add the ability to move / migrate resources between Spaces to improve the usability of the feature for new customers.  This Issue is to track feedback on that migration feature.

**Comment by MJRichardson** [comment]
Replaced by https://github.com/OctopusDeploy/Issues/issues/5451
