### ISSUE TITLE
When dynamically creating cloud infrastructure only 1 target gets deployed to

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#4887]
When creating cloud targets for multiple cloud regions, as illustrated in our blog example [here](https://octopus.com/blog/dynamic-infrastructure#azure-resource-manager-templates-and-cloud-regions) only 1 of the targets now gets deployed to.

This was working at the time `2018.5` was released but has regressed in a recent version.

We have been able to reproduce this, and the issue seems to relate to the fact that the health checks for the targets run in parallel on the server (which relates to Cloud Region handling). It appears the multiple threads are both reading separate copies of the same machine list then adding their own entry and writing the list back. Last list wins as to which machine actually gets deployed too.

Initial investigation indicates that the introduction of the FullTableCache for the machine loader may have caused or at least contributed to this and we'll have to change the health check handling code to account for it.

Source https://secure.helpscout.net/conversation/638728115/30980/

**Comment by benPearce1** [comment]
Until this has been resolved, a workaround is to add a **Health Check** step into the process between the step responsible for creating the target and the step responsible for deploying the package.

**Comment by dgard1981** [comment]
I can confirm that the workaround suggested by Ben seems to work.

However, don’t just use the default settings for the Health Check step; change the **New Deployment Targets** option to **Include new deployment targets in the deployment**.

**Comment by johnsimons** [comment]
@benPearce1 and I tested this with v2019.1 and it seems to work.

@dgard1981, when you have the time, please try this again with v2019.1.

**Comment by dgard1981** [comment]
@johnsimons I'm not sure when we next plan to update, but I will try and remember to comment on this thread after we do.
