### ISSUE TITLE
Features for multiple packages not available in Azure script steps

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#4896]
The "Run an Azure Powershell Script" and "Run a Service Fabric SDK Powershell Script" steps have multiple packages but do not have the variable replacement features enabled like the regular script step.

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable-substitution features not enabled for Azure and AWS script steps](https://trello.com/c/oSEnD2ud/49-variable-substitution-features-not-enabled-for-azure-and-aws-script-steps)

**Comment by MJRichardson** [comment]
Release note: Variable-substitution and config-transform features enabled for Azure PowerShell script steps and Azure Service Fabric script steps.
