### ISSUE TITLE
Tenant variable template select control initially bound when options contain spaces

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4897]
# The bug

When you provide a select with whitespaces as part of the value, the select option presents itself as bound even though it should not be. Unbinding does present the dropdown items, however, regardless of changing the option and saving, the value will always present itself as bound on reload.

## What I expected to happen

When choosing an option from the dropdown list i.e. not being bound should remain unbound regardless of whitespace in my chosen values.

## Steps to reproduce

1. Add a variable template and choose a control type of select
2. Add options such as the following:
```
True | True
False | False
```
3. Add a default value of `False`
4. Ensure you have a tenant connected to a project where the above variable template will come into play
5. Navigate to the tenant variables page
6. Notice the value is *bound*

### Screen capture

![tenant-variable bug](https://user-images.githubusercontent.com/6700195/45542867-6ec67c00-b856-11e8-8188-6605aaa35e17.gif)

## Affected versions
Reported working in 2018.1.1 and not working since 2018.7.14. Confirmed not working with 2018.8.4

**Octopus Server:** 

## Workarounds
Ensure select options do not contain any whitespaces inbetween i.e.
```
Value1|Display
Value2|Display
```
## Links
Original [source](https://secure.helpscout.net/conversation/662126641/32120?folderId=1576787)

**Comment by matt-richardson** [comment]
Release note: Add validation for drop down options for variable templates of type "select"
