### ISSUE TITLE
Script console execution fails for all subsequent targets when failing to connect to Tentacle

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#4902]
# Prerequisites

- [x ] I have verified the problem exists in the latest version
- [x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x ] I have written a descriptive issue title
- [x ] I have linked the original source of this report
- [x ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If the Tentacle service is unavailable during script console execution, the execution fails and does not attempt to run against the other available targets.

More information on replication from steps below.

## What I expected to happen

For any targets the script console fails running against, we should note it and continue, not fail on all subsequent targets. 

## Steps to reproduce

1. Add at least three Tentacles (individual services) to Octopus. (Health check successful)
2. Stop two of the Tentacle services, restart the Octopus server service. (Restart is needed to replicate for Polling not sure about Listening)
3. Create a Script Console task `Write-Host "Hello world"
4. Execute it for multiple targets starting with the disabled Tentacles. (This is governed by alphabetical precedence so name the Tentacles so they will be executed first)
5. The initial two Tentacles which are disabled will fail as expected, however, the remaining targets will never run as a result and the execution is regarded as `Failed`. 

Have seen this happen with a Polling Tentacle timeout and the following on a Listening Tentacle:
```
An error occurred when sending a request to 'https://localhost:10933/', before the request could begin: No connection could be made because the target machine actively refused it [::ffff:127.0.0.1]:10933
```

## Affected versions

Tested on 2018.8.5

## Workarounds

None known currently

## Links

Source: https://help.octopus.com/t/script-not-running-on-all-machines/21331/8

**Comment by droyad** [comment]
Closing this as the planned Maintenance Processes will resolve this

**Comment by ayseff** [comment]
What is "planned Maintenance Processes"?  Thanks,

**Comment by ayseff** [comment]
?
