### ISSUE TITLE
Deployment fails to start when specific certificate scoping is used

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4908]
# The bug

There are two certificates scoped to their namesake environments: Dev, Production. A project references those certificates via a variable that is unscoped for Dev and scoped for Production. Attempting to deploy a release to Prod yield the following error:

```
There was a problem with your request.
Certificate 'Dev' is not scoped to environment 'Production'. It is currently referenced by variable 'Cert'. Either scope the certificate to the environment or change the value of the variable.
 Once you have corrected these problems you can try again.
 If the problem is related to a variable you will need to update the variables for this release or recreate the release for the changes to take effect.
 If the problem is related to the deployment process you will need to create a new release for the changes to take effect.
```

## What I expected to happen

The deployment should recognise that there is a certificate explicitly scoped to Production and prefer that certificate to the unscoped Dev certificate.

## Steps to reproduce

1. Create a certificate called Dev that is scoped to the Dev environment
2. Create a certificate called Production that is scoped to the Production environment
3. Create a project with whatever deployment process you want
4. Create a variable that point to the Dev and Production certificates.  Leave Dev unscoped and explicity scope the Production certificate to Production.
5. Create a release and attempt to deploy it to Production

### Screen capture

Two certificates, note the scope:
![image](https://user-images.githubusercontent.com/171197/45789382-c20b5500-bcc2-11e8-8368-7cd0dd239417.png)

Variable with unscoped and scoped values:
![image](https://user-images.githubusercontent.com/171197/45789411-dd766000-bcc2-11e8-8917-c65100fc4696.png)

## Workarounds

Explicitly scope the unscoped variable.

## Links

https://secure.helpscout.net/conversation/661007332?folderId=557080

**Comment by tothegills** [comment]
Unscoped variables pointing to restricted certificates just doesn't work.

At the start of a deployment we gather up all of the variables for the deployment. We collect every variable that matches the deployment even if there is no possible way for that variable to be used in the deployment. An example to illustrate would be a variable scoped to an environment and another scoped to a machine in that environment. When a deployment happens to only that machine, the environment scoped variable and machine scoped variable are both included in the deployment because they match the parameters of the deployment. It is only at runtime that scope specificity is used to determine which of those variables will be used.

When a variable is unscoped it means "use this variable in every deployment". In this issue the unscoped variable will always be included in every deployment, regardless of whether there is another scoped variable that will always take precedence. When the variable is expanded and we attempt to find the certificate that the variable is pointing to it results in the described error because of the environment restrictions on that certificate.

The simple solution is to explicitly scope certificate variables to the same environments that they are restricted to. We could provide a better UI around this to match the scope of the variable to the scope of the certificate, in the meantime it should be done manually.

**Comment by jburger** [comment]
duplicate of https://github.com/OctopusDeploy/Issues/issues/3333
