### ISSUE TITLE
Reword 'Helm Update' command as 'Helm Upgrade'

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#4916]
The command that we run against helm is actuall `helm upgrade`, not `update` as is indicated by the current step name
![image](https://user-images.githubusercontent.com/1830666/45991898-4a766500-c0ca-11e8-9065-b93f2b179772.png)

**Comment by MJRichardson** [comment]
It seems this was never merged.  Re-opening.

**Comment by MJRichardson** [comment]
Release note: Renamed 'Run a Helm Update' step to 'Upgrade Helm Chart'
