### ISSUE TITLE
First-class step support for Azure Functions

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4930]
## Azure Function step

We currently can deploy to Azure Functions via our Azure Web App step (purely by coincidence) and this has been the approach we recommend [in our recent blog article](https://octopus.com/blog/azure-functions).

However this is not intuitive (you would search for "Azure Function" when trying to deploy to Azure Functions, and there's always the risk this approach will stop working, as appears to be the case for some customers at the moment.

## Proposal
We want to add first-class support for Azure Functions with a step dedicated to this, including tests to ensure this feature is always guaranteed to work with the latest version of Octopus.

## Links
- https://secure.helpscout.net/conversation/673450843?folderId=557077

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [First-class step support for Azure Functions](https://trello.com/c/3ggi8gVh/995-first-class-step-support-for-azure-functions)

**Comment by droyad** [comment]
Closing this as this issue would not prompt us to implement this feature, it'll make it's way up the list by itself.
