### ISSUE TITLE
No release packages displayed for Deploy a Release steps in 2018.8

### ISSUE THREAD

**Issue by tw17** [OctopusDeploy/Issues#4933]
# The bug

When you have a project that has a 'Deploy a Release' step, the child project that gets deployed as part of this step no longer shows in the "Packages" section of the release.

## What I expected to happen

Any projects that are deployed as part of a 'Deploy a Release' step should be shown in the "Packages" section of the release with the corresponding versions.

## Steps to reproduce

1. Create a Project that has one or more `Deploy a Release` steps set to deploy other projects
2. Click on 'Create Release'
3. Enter details for the release and click 'Save'
4. See on the release page there is no packages listed in the 'Packages' section that correspond to the 'Deploy a Release' steps.

### Screen capture

![image003](https://user-images.githubusercontent.com/2016079/46323810-75653980-c633-11e8-8a12-4e6d2d469af2.png)

## Affected versions

all versions from 2018.8 onwards

## Links

Reported issue [here](https://secure.helpscout.net/conversation/673604186?folderId=557077)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No release packages displayed for Deploy a Release steps in 2018.8](https://trello.com/c/6pSoNJOG/69-no-release-packages-displayed-for-deploy-a-release-steps-in-20188)
