### ISSUE TITLE
The Bash (and python) script option should always appear

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#4956]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Bash scripting is not immediately available as an option for existing script steps when an SSH worker is added to the default pool.

## What I expected to happen

As soon as an SSH target is available in Octopus the Bash script option should become available.

## Steps to reproduce

1. Without any workers defined, create a "Run a Script" step that runs on the server. At this point the script options are "Powershell", "C#" and "F#".
2. Add a SSH worker
3. Go back to the "Run a Script Step"
4. The step will now run from a worker in the "Default Worker Pool". My worker is a SSH worker, but I do not have the option to select a Bash script. The screenshot below shows the step after adding a worker.

![image](https://user-images.githubusercontent.com/29847178/46592613-ea3ee480-cb07-11e8-9e47-de06388b0799.png)

5. The workaround is to select "Run on each deployment target" and then "Run once on a worker" again. After swapping these setting the Bash option is available.

<img width="1268" alt="screen shot 2018-10-08 at 2 40 31 pm" src="https://user-images.githubusercontent.com/29847178/46592654-25411800-cb08-11e8-8b9f-3e2cae9cf2b1.png">

## Affected versions

**Octopus Server:**  2018.7.x and newer

## Workarounds

This issue only occurs for existing script steps that we created priory to an SSH worker being available. Selecting `Run on Deployment Target` then immediately switching back to `Run on Worker` resolves issue.

## Links

[Initial report](https://secure.helpscout.net/conversation/678359549/33147?folderId=1465198)

**Comment by MichaelJCompton** [comment]
see also https://github.com/OctopusDeploy/Issues/issues/4890.  Both of these are linked in with it not being possible to leave the pool selection empty.

You should be able to leave the pool selection empty - selecting one overrides all defaults (solves https://github.com/OctopusDeploy/Issues/issues/4890)

Then (this ticket) the logic around if a step is going to run on the server (BuiltIn Worker) needs touching up.

**Comment by droyad** [comment]
This seems to have been fixed
