### ISSUE TITLE
Allow the license key to be force updated even if it would cause the server to become non compliant

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#4966]
# The enhancement

There have been cases where customers needed to update their license key, but were prevented by our validation: updating the license key would cause the server to be non-compliant. The only way to work around this was to edit the database directly.

We should add a command-line option to skip the compliance check and force the update of the license key.

## Workarounds

Update the database directly.

**Comment by matt-richardson** [comment]
Overlaps with https://github.com/OctopusDeploy/Issues/issues/4703?

**Comment by michaelnoonan** [comment]
Yep, it's part of that issue, and I figure good enough to be a duplicate.
