### ISSUE TITLE
Known upgrade path bugs and restrictions

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4979]
This issue contains special instructions for Octopus Server upgrade paths that have been broken.

## < 3.4 to 2018.4.0-2018.5.4
Due to #4509 Octopus Server should be upgraded in the following order:
- Upgrade to [3.4.15](https://octopus.com/downloads/3.4.15)
- Upgrade to [3.17.14](https://octopus.com/downloads/3.17.14)
- Upgrade to the desired version between 2018.4.0 and 2018.5.4

## 2.6 to 2018.8.0-2018.8.11
Due to #4958 Octopus Server should be upgraded in the following order:
- Upgrade to [2018.7.14](https://octopus.com/downloads/2018.7.14)
- Upgrade to latest

**Comment by droyad** [comment]
This is now in the documentation
