### ISSUE TITLE
'Latest' package version works differently for packages and release versions (Deploy a Release step)

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5010]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When creating a release, the `Latest` field behavior is inconsistent between standard package versions and release versions for `Deploy a Release` steps.

## What I expected to happen

Since release versions of child projects are treated like packages, I expected the behavior to be the same between both.

## Steps to reproduce

1. Create a package, versioning it later, i.e. 2.0.0
2. Create an earlier package version, i.e. 1.0.0
3. Create a release of a child project, versioning it later, i.e. 2.0.0
4. Create an earlier release version of a child project, i.e. 1.0.0
5. Create a release of the parent project

### Screen capture

Result: The package step correctly chooses version 2.0.0 of the package, but the `Deploy a Release` step incorrectly selects version 1.0.0 of the child project.

![package_version_release_version](https://user-images.githubusercontent.com/20388190/47276722-8a166b00-d5fc-11e8-8e8c-ce0caed52f37.png)

## Affected versions

Tested in 2018.8.7 & 2018.8.12
## Workarounds

Manually select the true latest release version of the child project when creating a release of the parent project.

## Links

Source: https://help.octopus.com/t/channel-rules-not-working-correctly-for-deploying-releases/21563

**Comment by MJRichardson** [comment]
This was an intentional decision.  
We figured it was more likely to be creating a parent release for the most recent release of a child project, rather than the latest according to the version.
This assumption won't always be true of course.
