### ISSUE TITLE
Support Azure WebApps on Linux 

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#5012]
The current Octopus implementation for deploying Azure Web Apps uses WebDeploy, and relies on SCM. To deploy to an app service on Linux some adjustments are required, per https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq

Longer term we will likely be looking at Zip and container deployments, this change will focus just on fixing the WebDeploy deployments.

## Links

https://help.octopus.com/t/failed-deploy-to-azure-web-app-for-linux/21558

**Comment by CashmereBob** [comment]
Any eta on this?

**Comment by shaunmarx** [comment]
Hi @CashmereBob, we are looking into this at the moment and hope to have a fix available soon.

**Comment by shaunmarx** [comment]
Release Note: Updated Web App deployments to use XML publish endpoint enabling deployments for Linux based Web Apps using web deploy
