### ISSUE TITLE
Should consider type when validating existence of related documents

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#5049]
# The bug

When setting ids of related documents, we validate that these ids exist in the database. We don't actually validate whether the id that exists in the database is of the correct type of document. For example, if you add a member to a Team, you set the `MemberUserIds` property, and the expectation is that this only contains user ids. However, the system will consider it valid to set any existing id in this property, eg Accounts, Teams, Projects, etc.

## Steps to reproduce

```
using Octopus.Client;

namespace OctopusDeployApiManagement
{
   class Program
   {
      private const string ApiKey          = "API-MySuperSecretApiKey";
      private const string OctopusServer   = "http://localhost/OctopusDeploy";
      private static readonly OctopusRepository _octopus = new OctopusRepository(new OctopusServerEndpoint(OctopusServer, ApiKey));

      static void Main()
      {
         //Create a new Octopus Deploy User
         var newUser = _octopus.Users.CreateServiceAccount("Test", "Test");
         
         //Generate a new API Key for new user
         var key = _octopus.Users.CreateApiKey(newUser, "Test");

         //Find the team I want to modify.
         var team = _octopus.Teams.FindOne(resource => resource.Name == "Test Team");

         //ISSUE:
         //Incorrectly passed in the Team's Id string itself instead of the users Id.
         team.MemberUserIds.Add(team.Id);

         //Save the Team
         _octopus.Teams.Modify(team);
      }
   }
}
```

See `IdExistenceChecker.cs` and the database view `IdsInUse`.

## Links

Source: https://github.com/OctopusDeploy/OctopusClients/issues/337

**Comment by droyad** [comment]
Will be covered as part of dependency graph work.
