### ISSUE TITLE
Licensing prevents creating a new user even though the user should not contribute to license usage

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#5052]
Octopus will prevent you from creating a new user account when that user would otherwise cause your server to become non compliant with the current license. Ever since https://github.com/OctopusDeploy/Issues/issues/5023 certain types of users should be excluded from this check.

## What I expected to happen

When a particular type of user account should be excluded from license limits, I should be able to create that user account without being prevented by license validation.

## Steps to reproduce

1. Create a license to exclude users with an email address from the `mydomain.com` domain.
2. Create enough licensed users to get the server to its limits, preventing you from adding any additional normal users.
3. Try to create a user from the `mydomain.com` domain. It should succeed without changing the license usage, but instead it will fail.
 
## Affected versions

**Octopus Server:** 2018.9.1 until fixed

## Workarounds

1. Disable a licensed user temporarily
2. Create the new user
3. Enable the licensed user again

**Comment by pawelpabich** [comment]
Release Note: Now users with emails in domains specified in the licence will be skipped during the calculation of licence usage
