### ISSUE TITLE
Tooltip for manual intervention task icon

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#5062]
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

Use tooltip to show more information about the intervention, e.g. step name, approver etc
This can be useful if a deployment process has more than 1 manual intervention, user can see what cause it without going into the task page itself
## Links
https://secure.helpscout.net/conversation/693029819/33998?folderId=557077

**Comment by droyad** [comment]
We are closing this as it seems unlikely we will get to it in the near future
