### ISSUE TITLE
Multi file selection S3 with glob tries to include relative path in bucket key

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#5066]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When specifying a multi file selection to upload to S3 such as the default provided i.e. `**/*` something strange starts to happen where relative file paths make an appearance in the bucket key for example `../file.json`

## What I expected to happen

Absolute paths should be provided which would represent the bucket key prefix for the file as relative file paths just don't make sense and consequently cause uploads to fail as the characters are illegal.

## Steps to reproduce

1. Ensure you have a package with multiple folders and files (GitHub feed will also work)
2. Create a new S3 step
3. Choose to upload files within the package
4. Configure the required account, bucket and region
5. Add a standard multi-file selection such as **/*

### Log exerpt

```
10:36:32   Info     |       Glob pattern '**/*' matched 9 files.
10:36:32   Info     |       Attempting to upload C:\Octopus\worker-local\Work\20181108003628-14234-28\staging\bucket-noparamfile.json to some-amazing-bucket with key ../bucket-noparamfile.json.
10:36:32   Error    |       Calamari.Aws.Exceptions.UnknownException: An unrecognised Forbidden error was thrown while uploading to some-amazing-bucket
10:36:32   Error    |       at Calamari.Aws.Deployment.Conventions.UploadAwsS3Convention.Install(RunningDeployment deployment)
10:36:32   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
10:36:32   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
10:36:32   Error    |       Running rollback conventions...
10:36:32   Error    |       An unrecognised Forbidden error was thrown while uploading to bucket test-shaun-awesome-bucket
10:36:32   Error    |       Calamari.Aws.Exceptions.UnknownException
10:36:32   Error    |       at Calamari.Aws.Deployment.Conventions.UploadAwsS3Convention.Install(RunningDeployment deployment)
10:36:32   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
10:36:32   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
10:36:32   Error    |       at Calamari.Aws.Commands.UploadAwsS3Command.Execute(String[] commandLineArguments)
10:36:32   Error    |       at Calamari.Program.Execute(String[] args)
```

## Affected versions

**Octopus Server: 2018.8.0 - 2018.9.7** 

## Links
[Original report](https://help.octopus.com/t/upload-to-s3-issue/21706)

**Comment by BoMoro** [comment]
Could you please say my when this issue will publish to production?

**Comment by BoMoro** [comment]
Could you please say me when Octopus cloud version will update?

**Comment by shaunmarx** [comment]
@BoMoro I believe the hosted instances would be updated during your nominated outage window. We can do this for you sooner if you send a request through to support@octopus.com with the instance information.

**Comment by liatmayo** [comment]
Can you please clarify - if I have a nightly outage window, it is expected to be updated tonight?

**Comment by shaunmarx** [comment]
@liatmayo it would seem that our hosted instances are currently configured to use `2018.9.5`, which means that your instance will not be upgraded to `2018.9.8` or newer unless you send a request through to support@octopus.com asking for your instance to be upgraded to this version.
