### ISSUE TITLE
Support for Service Fabric WindowsCredentials / AD

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#5073]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

Service Fabric targets and/or steps could use the `WindowsCredential` parameter from [here](https://docs.microsoft.com/en-us/powershell/module/servicefabric/connect-servicefabriccluster?view=azureservicefabricps), but our UI does not currently allow you to set this security mode. We need to investigate what's required for AD support and SF.

If we also want to support "group-managed service-accounts", we'll also need to consider the `ClusterSpn` parameter.

## Related
We should knock [this related issue](https://github.com/OctopusDeploy/Issues/issues/4827) over while we're here to enhance the flexibility if possible.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for Service Fabric WindowsCredentials / AD](https://trello.com/c/UrJ7E7k0/1074-support-for-service-fabric-windowscredentials-ad)

**Comment by pregress** [comment]
This would be great to have for teams running Service Fabric on Prem. 
Our case:
The octopus server/tentacles/workers all run under the same AD account, so we don't need to pass in extra credentials. 

Although it would be usefull for other people to pass in the specific AD account that you want to use.

**Comment by slewis74** [comment]
We're closing this as any further work on Service Fabric has currently been de-prioritized.
