### ISSUE TITLE
Retention policies should not delete in-use releases

### ISSUE THREAD

**Issue by tw17** [OctopusDeploy/Issues#5074]
# The bug

When using “Deploy a Release” step and retention policies. the retention policy deletes release that are in-use:

- “Project A” has a deploy a release step to deploy “Project B”, both with release number “1.2.3”
- Project B has a different retention policy, and has release 1.2.3 deleted
- Project A now has a release that cannot be deployed, as it references a non-existent release of Project B.

## What I expected to happen

We don't delete packages that are in use, the same should go for releases. the retention policy should exclude any releases that are referenced in “Deploy a Release” steps.

**Comment by ccamburn** [comment]
Any chance of an update on this? We are currently experiencing lots of issues with releases being deleted despite being in use. The only workaround I've found is to greatly increase the retention policy on the Project B. Worse than the release being deleted tho is that this eventually deletes the _packages_ used by this release from the built-in repository, which in some cases doesn't give us a way to restore the release.
