### ISSUE TITLE
Enabled configuration transform feature for Upload to S3 step

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#5075]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

The enhancement would be to enable configuration transforms for the S3 step in order to provide better support for deploying .net core apps to AWS

## Links

https://octopususergroup.slack.com/archives/CCRM18TPV/p1541171906001900

**Comment by droyad** [comment]
This will be covered by the "Replace variables in package" feature
