### ISSUE TITLE
Octopus steps should include platform compatibility

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#5088]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/feature)

# The feature

## What it actually enables people to do

As pointed out by a [customer](https://help.octopus.com/t/terraform-on-linux-ssh-worker/21740/3), currently Octopus allows users to execute steps that will fail on certain platforms, in this case the user is trying to execute Terraform on a linux ssh target.

The proposal here is to somehow tag the individual steps as compatible with target, so we do not run them against incompatible targets

## What pain relievers or gain generators are we solving for people?

This would ensure customers cannot deploy to an incompatible target that will fail, and quite possible reduce support cases.

## Who will care about it?

Customers that want to use Octopus in non MS environments

## Elevator pitch for this feature

Less time wasted for both customers and us in support

## How much noise should we make about this?

Not sure!

# Links

https://help.octopus.com/t/terraform-on-linux-ssh-worker/21740/3

**Comment by MJRichardson** [comment]
We may well do something like this, but we would raise a more specific issue.
