### ISSUE TITLE
C# scripts broken on mono 5.16

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#5092]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Running a C# script on an SSH target running `mono` version `5.16.0` fails with the following error message: 
```
(305,39): error CS0584: Internal compiler error: The method or operation is not implemented. 
(1,2): error CS0103: The name `Octopus' does not exist in the current context 
(1,16): error CS0103: The name `Octopus' does not exist in the current context 
(1,35): error CS0103: The name `someVar' does not exist in the current context 
The remote script failed with exit code 255 
```

Root cause is that `mono` version `5.16.0` introduces [System.IO.Path.GetFileName](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.IO/Path.cs#L956) method overload taken from the .NET `corefx` code base.

## What I expected to happen

I expect the C# script to run successfully

## Steps to reproduce

1. Go to 'Infrastructure->Deployment Targets'
2. Click on 'Add Deployment Target'
3. Add a new SSH Connection
4. Enter the details for your Linux server that has `mono` version `5.16.0` installed
5. Create a new project
6. Add a script step to run on the role of your SSH target
7. Enter the following F# script in the script body
```
var machineName = Octopus.Parameters["Octopus.Machine.Name"];
Console.WriteLine("Machine name is: " + machineName);
```
8. Create a new release and deploy that to your SSH target
9. See error.

### Log excerpt

```
Executing '/home/octopus/.octopus/master/Work/20181113235710-7330-61/Script.csx' 
(305,39): error CS0584: Internal compiler error: The method or operation is not implemented. 
(1,2): error CS0103: The name `Octopus' does not exist in the current context 
(1,16): error CS0103: The name `Octopus' does not exist in the current context 
(1,35): error CS0103: The name `someVar' does not exist in the current context 
```

## Affected versions

**Octopus Server: Since C# support was introduced** 

## Workarounds

Downgrade `mono` to version `5.14.0` or lower.

## Links

Related issue for F# scripts: https://github.com/OctopusDeploy/Issues/issues/5091
Support ticket: https://help.octopus.com/t/c-on-linux-ssh-target-strange-error/21689

**Comment by Justin-Walsh** [comment]
Additional report: https://help.octopus.com/t/issues-with-mono-6-x/28654

**Comment by zentron** [comment]
[Mono is now slated for deprecation](https://github.com/OctopusDeploy/Issues/issues/8146) and so this item is likely to remain unresolved.
