### ISSUE TITLE
IIS deployment fails when there are multiple SSL certificates and they are in different stores

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#5096]
The deployment fails with:

```
Could not find certificate with thumbprint '<redacted>' in store
```

See https://help.octopus.com/t/could-not-find-certificate-with-thumbprint-in-store/21678 for a detailed explanation of the problem.

**Comment by hnrkndrssn** [comment]
Another report: https://help.octopus.com/t/error-when-importing-multiple-certificates-on-the-deploy-to-iis-step/21861

**Comment by kiyoichikawa** [comment]
Is there any update to when this will be resolved?

**Comment by bryanroth** [comment]
Any updates?

**Comment by ajohnstone-ks** [comment]
I think I'm hitting this issue; has it really not been fixed in five years?

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13190 |
| 2023.4 | _tbc_ |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13190 |
| 2023.4 | 2023.4.8101 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13190 |
| 2023.4 | 2023.4.8101 |
| 2024.1 | 2024.1.2374 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13190 |
| 2023.4 | 2023.4.8101 |
| 2024.1 | 2024.1.2374 |
| 2024.2+ | _all releases_ |
