### ISSUE TITLE
Migrator removes variables scoped to tenant tags during import

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#5101]
Imagine you have some project variable values scoped to some tenant tags like `Region/US` or `Region/EU`. Now imagine you export that project and import it into another Octopus Server instance.

The first time you do this, the variable values are migrated successfully. If you do it again, the variable values are stripped out of the project variable set and a message like this is logged: `WARN  Variable 'SqlDatabasePassword' dropped, as it was previously scoped to 'TenantTag = (TagSets-121/Tags-151)', but these scopes are not available`. This seems very strange since the equivalent tenant tags exist on both the source and destination.

While investigating I discovered a difference between the first and second imports:

First attempt:
```
Converting TagSet TagSets-121
Created TagSet "Customer.Region" (TagSets-121 -> TagSets-1)
```

Second attempt:
```
Converting TagSet TagSets-121
Skipping TagSet "Customer.Region" (TagSets-121) because no overwrites selected
Could not import TagSet "Customer.Region" (TagSets-121)
...
'SqlDatabasePassword' dropped, as it was previously scoped to 'TenantTag = (TagSets-121/Tags-151)
```

## What I expected to happen

It shouldn't matter whether it's the first or subsequent times I'm importing... these particular variables should have been retained. Instead they were removed from the Variable Set.

## Affected versions

**Octopus Server:** 3.4 until fixed.

## Workarounds

When importing you can add the `--overwrite` argument - this will cause the Tenant Tag Sets to be reimported, and the variable values will no longer be dropped - but it may also have the unintended side-effect of overwriting things you didn't intend.

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrator removes variables scoped to tenant tags during import](https://trello.com/c/BSQTHjnY/25-migrator-removes-variables-scoped-to-tenant-tags-during-import)

**Comment by MJRichardson** [comment]
Release note: Migrator now correctly remaps tenant tag references when the tag-set exists on the destination
