### ISSUE TITLE
External links not evaluating correctly for IE11

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#5130]
# Prerequisites

- [x ] I have verified the problem exists in the latest version
- [x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x ] I have written a descriptive issue title
- [x ] I have linked the original source of this report
- [x ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Links in the Octopus portal drop down are resolving locally in IE11.

Where clicking `Documentation` should direct you to `https://g.octopushq.com/DocumentationHome`.
Users are being directed locally to something like: `https://OctopusServer.local/DocumentationHome`

## Steps to reproduce

1. Using IE11
2. Load Octopus web portal
3. Select drop down button on top right

## Affected versions

2018.9.10

## Links

Source: https://secure.helpscout.net/conversation/717956737/35765?folderId=845288

**Comment by danielfischeroctopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [External doc links in IE11 are borked](https://trello.com/c/4aHNvdPt/328-external-doc-links-in-ie11-are-borked)

**Comment by thebigmoosey** [comment]
Release Note: Fixed external doc links not redirecting properly in IE11
