### ISSUE TITLE
bug: Helm upgrade step does not support using additional values file from chart package as advertised

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#5146]
## Issue
The `Template Values` option to use `Files in Chart Package` does not appear to provide the appropriate values when the apply step is being called.
![image](https://user-images.githubusercontent.com/1830666/49551819-92243300-f93c-11e8-8d16-594755cd1c01.png)

Due to the way in which package variables are provided to a deployment, the "default" package does not include the additional `ValuesFilePath` that is provided when the additional package option is used.

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Helm chart additional variables are not provided](https://trello.com/c/rGEO7qL8/181-helm-chart-additional-variables-are-not-provided)

**Comment by scardetto** [comment]
I'm also seeing this behavior.  On a related note, the editor prompt says that you should enter a newline separated list of files/patterns, but the input doesn't accept new lines.

**Comment by thelious1974** [comment]
I'm also seeing this behaviour.

I'm setting some explicit values (which contain octotash variables), and then I'm attempting to use an explicit file within the Chart package for the rest of the configuration.

**Comment by zentron** [comment]
Release Note: Bugfix: Support additional values file sourced from helm chart package
