### ISSUE TITLE
Add shortcut menu to subscription list

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#5157]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

The subscriptions list does not currently have a shortcut menu - it would be useful to add `Edit`, `Disable`/`Enable` and `Delete` quick actions to this list.

## Mockup

![image](https://user-images.githubusercontent.com/373389/49767982-bca43080-fd2e-11e8-995f-0917bfd150d2.png)

## Workarounds

All actions are already available - they just require a few more clicks.

## Links

source: internally raised

**Comment by droyad** [comment]
A lot of lists could do this, so closing this as it'll be covered by a larger program of work.
