### ISSUE TITLE
UI bug where variable editor popovers are being cut off

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#5190]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The variable popovers are cut off (by the paper layout's overflow:hidden css) and you cannot see or access these popover menus as a result.

### Screen capture

![image](https://user-images.githubusercontent.com/819605/50582111-d529e580-0eab-11e9-857e-1401935e5887.png)

## Affected versions

**Introduced in Octopus Server: 2018.9.17**

**Comment by thebigmoosey** [comment]
A one-line fix committed directly to master to fix this: https://github.com/OctopusDeploy/OctopusDeploy/commit/5378d1e4a651568c2fa068fe672eec21c4b8be10

**Comment by thebigmoosey** [comment]
Release Note: UI fix for variable editor popover menus being visually cut off

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI bug where variable editor popovers are being cut off](https://trello.com/c/5YBPNQZy/372-ui-bug-where-variable-editor-popovers-are-being-cut-off)

**Comment by amc-bbeard** [comment]
Will this fix be applied to the LTS 2018.10 release? This bug is rather annoying and I'm not sure I want to wait three months for the next LTS release.

**Comment by amc-bbeard** [comment]
Great! That's good to hear.
