### ISSUE TITLE
Poor performance when calculating certificate usage

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#5198]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Loading the certificate usage on a server with a large number of tenants can take several seconds to complete. A user with 800 tenants reporting the request taking 30 seconds.

I was able to create a call that took 6 seconds with 1000 tenants on a cloud hosted instance.

After discussing with the performance team, we have a N+1 query problem with pulling back the tenants and some lookups on IDs that will break at around 2100 tenants.

## What I expected to happen

Loading the certificate usage should not take 30 seconds to load.

## Steps to reproduce

1. Create a server with ~50 projects and ~1000 tenants.
2. Create a certificate and attach it to a tenant or tenant tag set.
3. Open dev tools and view the network activity
4. View the certificate details page.
5. Find the usage request and see that it is taking multiple seconds.

## Affected versions

**Octopus Server:** At least 2018.7 to current

**Comment by benPearce1** [comment]
Release Note: Improved performance of certificate usages
