### ISSUE TITLE
Add `aws-iam-authenticator` to the AWS tools Octopus ships out of the box

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#5214]
# Prerequisites

## What pain relievers or gain generators are we solving for people?

At the moment customers need to create their own worker with [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator)  installed.

## Who will care about it?

Customers deploying to Amazon EKS service.

# Links

https://secure.helpscout.net/conversation/750683321

**Comment by nblumhardt** [comment]
Just to chime in (👋 ) .. this pretty much left our Octopus Cloud -> Kubernetes configuration dead in the water. Octopus Cloud doesn't seem like a great value proposition for deploying to Kubernetes if the first thing we need to do is provision a VM so that we can run a health check on the cluster 😄

**Comment by pawelpabich** [comment]
Hey,

We will add this tool the Cloud image. That being said I will leave this issue open so we can decide whether to include it in the AWS package that we ship with Octopus Server.

**Comment by johnsimons** [comment]
Our direction regarding shipping tools out of the box has changed.
We do not want to ship any additional tools out of the box, as this adds to the size of the package and complexity of keeping these tools up to date.
