### ISSUE TITLE
Support precompiled websites with Octopack

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#524]
Via support. The reporter is using a custom MSBuild step post-build with TeamCity to generate compiled binaries. These need to be packed for deployment.

**Comment by dazinator** [comment]
Does this [user voice issue](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6042239-precompile-asp-net-website-as-part-of-build) qualify for revisiting this topic?

Some general guidance documentation / example for using OctoPack, with pre-compilation of ASP.net websites (during build) would be really useful - even if it's just explaining that it's done via a custom nuspec file
