### ISSUE TITLE
Migrator Import results in Project.VariableSetId and Project.DeploymentProcessId with $sourceId

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#5259]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# The bug

Using `Octopus.Migrator.exe` to export a series of projects and then import them into a brand new destination server can end up with broken links between a Project and its Deployment Process and Variable Set.

Inspecting the Project you can see the IDs have `$` appended to the front!

![image](https://user-images.githubusercontent.com/1627582/52030080-cf362b80-2561-11e9-82b2-f4245dba5469.png)

This should never happen but it does... and results in the project being totally broken.

## Analysis

Project logos are stored as attachments, and are written to files with names like `Projects-2`. In `ImportController.IdentifyAttachments` we add these to the `IdentityMap` with a source and destination ID of `Projects-2`…

The conditions needed to cause this are:
- Project A with a logo (the logo attachment will be named e.g. `Projects-2`)
- Project B which gets allocated a destination ID equal to Project A’s Source ID (e.g. `Projects-2`)

## What I expected to happen

The Project should have correct links to its Deployment Process and Variable Set. These IDs should have been successfully translated.

## Steps to reproduce

The linked conversation with a customer has the exported data and we can reproduce the result by importing using Octopus `2018.11.1`.

### Log exerpt

Omitted due to privacy. The original conversation thread provides access.

## Affected versions

**Octopus Server:** 3.0 until fixed.

## Workarounds

Nothing good.

## Links

Private conversation: https://octopususergroup.slack.com/archives/GDSQG34Q4/p1547224452004900
Investigation: https://octopusdeploy.slack.com/archives/CBLPZ0N59/p1548890123028800

**Comment by MJRichardson** [comment]
Release note: Resolved migrator issue where attachments were causing '$' to be left in IDs
