### ISSUE TITLE
Unable to create a release for a project linked to multiple Tenants when users permissions are restricted to a subset of those Tenants

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5284]
# The bug
Unable to create a release for a project linked to multiple Tenants when users permissions are restricted to a subset of those Tenants

## What I expected to happen
The deployment should be allowed to be created.

## Steps to reproduce

1. Create 2 Tenants
2. Link a project to both
3. Restrict a user to `DeploymentCreate` on 1 of those tenants only
4. Attempt to create a release
5. You will get an error with missing `DeploymentCreate`

## Affected versions

**Octopus Server:** 2019.1.0 - 2019.1.5

## Workarounds

Perform these actions with a user who does not have the permissions scoped on the Tenant dimension

## Links

https://secure.helpscout.net/conversation/766749079 (internal link)

**Comment by TomPeters** [comment]
Release Note: Fixed various issues around permissions that allows access to projects through connected tenants
