### ISSUE TITLE
Deploy A Windows Service step is missing options under Start Mode

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#5286]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using the Deploy A Windows Service step, the Start Mode option box seems to have some issues.

Unchanged: I would expect this option, if updating an existing service, to identify the current Start Mode used before the upgrade and use that. Leaving the services start mode Unchanged after the upgrade.

Disabled: Currently Unchanged is leaving the service stopped after installation. We should have an extra option for leaving the service disabled after service installation.

## What I expected to happen

Start Mode options which are user friendly and easy to interpret.

### Screen capture

![servicestart](https://user-images.githubusercontent.com/18252832/52679891-4a480a80-2f82-11e9-97c0-9666ab82c9a7.JPG)

## Affected versions

**Octopus Server:** 
2019.1.5

## Workarounds

To deploy the same service to multiple targets with different states of Start Mode, you will need to script this behaviour, or use a scoped variable bound to the Start Mode field.

## Links

https://secure.helpscout.net/conversation/774437888/39148?folderId=845288

**Comment by mcasperson** [comment]
This was fixed in 2019.1.11

**Comment by matt-richardson** [comment]
Release Note: Windows service state can now be specifically defined
