### ISSUE TITLE
Variable page (and various other pages) reloading when filtering

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#5316]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you filter on the project variables page, the whole screen refreshes and can blow away your filter. This was an unintended side-effect of some front-end refactoring to our routing system (to accommodate page identifiers for some up-coming work).

## Affected versions

**Octopus Server: 2018.1.7+** 

## Links

Raised in community slack: https://octopususergroup.slack.com/archives/C6UEBB7R9/p1550569757089200

**Comment by thebigmoosey** [comment]
Release Note: UI fixing route issues that were causing pages to re-render when filtering

**Comment by verzada** [comment]
It's not restricted to project pages.
In 2019.1.8 the following pages are affected with a reload
The DashBoard (https://<octopus-url>/app#/Spaces-1/) - reloads the page but the filter focus persists
Deployment targets (https://<octopus-url>/app#/Spaces-1/infrastructure) - reloads the page but the filter focus persist
Variable sets (and variables in projects) (https://<octopus-url>/app#/Spaces-1/library/variables) - reloads page and looses focus
