### ISSUE TITLE
Make octo.exe do some validation against API for deployment related values when called with `create-release`

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5329]
## Details 
When [create-release](https://octopus.com/docs/api-and-integration/octo.exe-command-line/create-release) is called on octo.exe you can supply some deployment related arguments, and it will proceed to create a deployment also.

Currently if you supply some invalid arguments relating to the deployment it will create the release as they do not apply at that stage.

But will then fail to create the deployment, making it more difficult for customers who are setting up automation around this.

## Objective
 Some clear validation output, and to block the creation of the release if the whole command isn't valid.

## Primary fields to consider validation
 - `--tenant=VALUE `
 - `--tenanttag=VALUE`
 - `--deployto=VALUE`

## Additional fields to consider for validation
 -  `--specificmachines=VALUE`
 - `--excludemachines=VALUE`

### Examples
 - Supplying invalid tags, results in:
    - Canonical Tag Name expected in the format of `TagSetName/TagName`

## Links
 - https://help.octopus.com/t/bug-octo-exe-create-release-should-fail-fast-due-to-validation-issues-when-providing-an-invalid-tag-name-currently-it-doesnt-complain-in-time/22388

**Comment by mcasperson** [comment]
This is available in version 5.2.7 of the CLI tools.
