### ISSUE TITLE
Make building secure 3rd party UIs for Octopus easy

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#5331]
# Prerequisites

- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/feature)

# The feature

## What it actually enables people to do

There are customers that want to either build a custom UI for Octopus or expose a subset of Octopus data and actions in their own UI. Today there is no easy way to do it, especially if the customer wants to delegate authentication to Octopus.

### Mockup

This feature requires a bit more investigation but early conversations suggest that we should use bearer tokens.  Ability to consume TypeScript client as a packge would also help here.

## What pain relievers or gain generators are we solving for people?

At the moment our customers have 2 possible options but none of them provides a complete solution.

1. The integration with Octopus can be done at the backend, e.g using our C# client, but this requires our customers to use Octopus API keys. Either one key per instance or one key per user (preferred way).  That being said API keys don't expire and need to be stored somewhere by the application that integrates with Octopus.

2. The integration with Octopus can be done at the frontend. This approach doesn't require API keys but our customers would have to reverse engineer our TypeScript client to mimic its behaviour in their code. What is more, this integration is not officially supported and might suffer from breaking changes in the future.

## Who will care about it?

Customers who build dashboards showing data and exposing actions from multiple different systems.

## How much noise should we make about this?

We don't hear often about this feature so let's track the interest here for now. This will help us make the right decision in the future.

# Links

https://help.octopus.com/t/using-the-login-with-windows-feature-through-api/22401/2

**Comment by MJRichardson** [comment]
There isn't enough demand for this to justify right now.
