### ISSUE TITLE
Add callout when editing a space that's not the current one

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#5370]
# The enhancement

When I create my first new space, it's too easy to just start adding data thinking that I'm in the context of that space (before I've even switched to it).

Right now, I create a space then my focus is taken by the blue info callout (talking about Space Managers), that I forget that I need to switch to this space.

The space edit screen could benefit from a callout that tells you that you are editing a space that's different from the one you are currently on.

### **Before** (regardless if you are in that space or not)
![image](https://user-images.githubusercontent.com/6180562/53985660-ff419300-40fa-11e9-877e-64eef3438e9d.png)

### **After** (when not in the space)
![image](https://user-images.githubusercontent.com/6180562/53985633-eb962c80-40fa-11e9-94b1-9486b86e8862.png)

### **After** (when in that space))
![image](https://user-images.githubusercontent.com/6180562/53985764-40d23e00-40fb-11e9-83e3-62bbe28dc46a.png)

**Comment by matt-richardson** [comment]
I'd like to discuss this as a team... I've got a spidey tingle that we should solve this at a higher level...

**Comment by Dalmirog** [comment]
Release note: Cleaned up callouts in `Space Edit` screen to improve UX
