### ISSUE TITLE
User's permissions scoped to project group and a project outside of that group can't view project

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5379]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a user is a member of a team that's scoped to both a project group and a project that doesn't belong in that group, that user is unable to view/access that project.

## What I expected to happen

The user should still be able to access that individual project. The wording in the team's page in the UI suggests that they should (e.g. `Team has permissions for [group] project groups and [project] projects...`)

## Steps to reproduce

1. Create a team with a user role that includes ProjectView
2. Scope that team to a specific project, and to a project group that project doesn't belong to
3. Add user to that team and login with them

### Screen capture

Permissions setup:

![project_and_group_permissions](https://user-images.githubusercontent.com/20388190/54106025-9f135f80-4420-11e9-8a44-85c1519c266c.png)

Projects page not displaying project:

![projects_page](https://user-images.githubusercontent.com/20388190/54106040-aa668b00-4420-11e9-9e9b-f5f3e5ba9888.png)

## Workarounds

Add this project into the project group this user's permissions is scoped to, or
Scope the team to the project group this project is in.

## Links

Source: https://secure.helpscout.net/conversation/796127556/40604/ (private link)

**Comment by jburger** [comment]
Release note: fixes scoping for projects when a different project group is scoped on the user role.
