### ISSUE TITLE
Allow Username authentication to login with email address

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#5380]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

The `UsernamePassword` authentication provider currently only queries the store by username, since the email address is unique, this could also allow the users email address to be provided as the username. This would also reduce some of the confusion around the login to `Octopus.com` using the email address.

## Mockup

![image](https://user-images.githubusercontent.com/5336529/54176456-9ed79a80-44da-11e9-9c7a-d07010cb1c25.png)

## Workarounds

None.

**Comment by michaelnoonan** [comment]
This actually feels like a bug - the label says "Username or email" but only accepts "Username" :)

**Comment by benPearce1** [comment]
@michaelnoonan this is for an enhancement to add email address as a valid login username

**Comment by michaelnoonan** [comment]
Oh, that's a mockup! 🤦‍♂️ 😄

**Comment by benPearce1** [comment]
Release Note: UsernamePassword authentication now accepts email address
