### ISSUE TITLE
CS Scripts that use Env.ScriptArgs not working correctly

### ISSUE THREAD

**Issue by hatcherj** [OctopusDeploy/Issues#5382]
Octopus Version v2018.9.14

Your variable documentation taken from this website
https://octopus.com/docs/deployment-examples/custom-scripts

--------------------------------------
Passing Parameters to C# Scripts
You can pass parameters to C# scripts as described here for the ScriptCS engine. ScriptCS only supports positional parameters.

Script Parameters in Octopus

-- "#{Octopus.Environment.Name}" "#{MyApplication.Storage.Path}"
Usage in C# script

var environment = Env.ScriptArgs[0]
var storagePath = Env.ScriptArgs[1]
Console.WriteLine("{0} storage path: {1}", environment, storagePath);

----------------------------------------

Steps to reproduce
1) Create a new Custom Step Template
  Click Library-> Step Template -> Add
2) Choose "Run a Script"
3) Give it a name
4) On the "Step tab, select "Inline source code" and "C#"
populate with following code

Console.WriteLine(Env.ScriptArgs[0]);

5) On the Parameter tab, add a Parameter with the following information
Variable Name: VarName
6) Click "Save"
7) Run the step Template and enter a value into the Parameter such as "Today"
8) The output is a weird string of data.  The expected results is the word "Today"

**Comment by droyad** [comment]
The string you saw is part of our setup for the script. The way to reference parameters is documented [here](https://octopus.com/docs/deployment-examples/custom-scripts/using-variables-in-scripts)
