### ISSUE TITLE
Refresh feed button crashes with "TypeError: e is not a function"

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#5383]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Same as #5255 for every step using the below line

```
this.setState({ feeds: await repository.Feeds.all() }, () => callback(this.state.feeds));
```

## Steps to reproduce

1. Go to any step with the `Refresh Feed` button
2. Click on the `Refresh feeds`button
3. See error

## Affected versions

2019.2.2

## Workarounds

Just reload the entire step page. Doing that will refresh the feeds (along with the entire page content).

**Comment by Dalmirog** [comment]
Release note: Fixed feed refresh button crashes in several built-in steps.

**Comment by eXpl0it3r** [comment]
I am still encountering this issue with 2019.5.4 and the "Docker Add" step.

`An unexpected error occurred in Octopus v2019.5.4: "TypeError: e is not a function"`

**Comment by matt-richardson** [comment]
Hi @eXpl0it3r - can you send through as much details as you can to support@octopus.com?
I've just retested locally, and I cant reproduce.

**Comment by Justin-Walsh** [comment]
More details added at https://secure.helpscout.net/conversation/860567943/45100?folderId=557077 (Internal link)
