### ISSUE TITLE
Support for Az PowerShell Modules

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#5384]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

Support for the new [Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.5.0&viewFallbackFrom=azps-1.4.0) either within the existing Azure PowerShell step, or as a seperate step.

## Workarounds

Install the new module on the worker or Octopus Server (where ever the step will execute), run the `Enable-AzureRmAlias` command to allow the existing login in the step bootstrapper to work, and turn off the [bundled Azure PowerShell module](https://octopus.com/docs/deployment-examples/azure-deployments/running-azure-powershell/configuring-the-version-of-the-azure-powershell-modules)   

## Links

[Source](https://secure.helpscout.net/conversation/797005833/40657?folderId=1465198)

**Comment by dgard1981** [comment]
Is there any news on this? Microsoft seem to be adding new some features that we need to `Az` PowerShell, but not to `AzureRm` PowerShell.

`Az` PowerShell is not that new, and Octopus needs to catch up so that we can use the latest tools.

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploying helm chart to Azure Kubernetes](https://trello.com/c/ubg36bp3/1696-deploying-helm-chart-to-azure-kubernetes)

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploying helm chart to Azure Kubernetes](https://trello.com/c/ubg36bp3/1696-deploying-helm-chart-to-azure-kubernetes)

**Comment by davidpeden3** [comment]
Is there a plan to officially support the Az module beyond the documented workaround?

**Comment by dvdgutzmann** [comment]
In the meantime Microsoft announced a sunset date for AzureRm (29 February 2024) and clearly states: 

> All versions of the AzureRM PowerShell module are **outdated**.  

https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-5.5.0

Please consider adding out-of-the-box support for the Az Module now.

**Comment by droyad** [comment]
We shipped #6330 as the solution to this.
