### ISSUE TITLE
Scoping a User Role to a project group causes buggy permissions behaviour.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#5387]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

There seems to be some buggy behaviour when scoping a user role to project groups.

One example I reproduced was not being able to delete a project I have access to when the user role providing the permissions was scoped to a project group. Even if you scope the user role to the project group & specific project in the group. The presence of the project group scope seems to break things here.

## What I expected to happen

Having project group scoping should be the same as individual project scoping for each project in the group. It should not break any permissions. 

## Steps to reproduce

1. Create two projects inside a project group.
2. Create a custom user role with enough permissions to view, edit, and delete projects.
3. Add this custom user role to a team and scope it to the above project group.

The user will be able to edit the project just fine but can not delete it.

4. Add one of the projects in the group alongside the project group to the user role.

The user can still not delete this project.

5. Remove the project group scoping.

User can now delete the project. 

This above behaviour also seemed a bit temperamental while testing. Though these steps should help to reproduce the behaviour. 

## Affected versions

Tested on 2019.1.5

## Links

Probably related: https://github.com/OctopusDeploy/Issues/issues/5379

**Comment by jburger** [comment]
Release note: fixes project scoping for user roles when scoped to the projects' group
