### ISSUE TITLE
A Mix of ProjectGroup and Project scoping of permissions breaks access to projects in a group user doesn't have access to view

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5391]
# The bug

For a user scoped to a project group AND a different individual project (in a different group) the project screens will fail to load.

## What I expected to happen

It should not error when loading a project user has access to, but lacks access to the project group.

## Steps to reproduce

1. For a user who has project related permissions
2. Restrict them to 1 group, and an `other project` not in that group.
3. Via the dashboard navigate to that `other project` 
4. 💥 Bread crumbs break

### Screen capture

![image](https://user-images.githubusercontent.com/119096/54322970-57245080-464b-11e9-8bba-3aeca15890bf.png)

### Log exerpt

```
An unexpected error occurred in Octopus v0.0.0-local: "TypeError: Cannot read property 'Name' of undefined"


TypeError: Cannot read property 'Name' of undefined

areaTitle (/app/areas/projects/components/ProjectLayout/ProjectLayout.tsx:157:151)
render (/app/areas/projects/components/ProjectLayout/ProjectLayout.tsx:104:22)
xg (/node_modules/react-dom/cjs/react-dom.production.min.js:163:128)
wg (/node_modules/react-dom/cjs/react-dom.production.min.js:162:274)
16:e=b.elementType;null!==a&&(a.alternate=null,b.alternate=null,b.effectTag|=2);f=b.pendingProps;a=Nf(e);b.type=a;e=b.tag=Ze(a);f=P (/node_modules/react-dom/cjs/react-dom.production.min.js:169:426)
lh (/node_modules/react-dom/cjs/react-dom.production.min.js:204:15)
mh (/node_modules/react-dom/cjs/react-dom.production.min.js:205:270)
Ph (/node_modules/react-dom/cjs/react-dom.production.min.js:220:232)
Qh (/node_modules/react-dom/cjs/react-dom.production.min.js:219:142)
sh (/node_modules/react-dom/cjs/react-dom.production.min.js:216:195)
```

## Affected versions

**Octopus Server:** 2018.11.x onwards

## Workarounds

 - Grant the user access to that project group, they will just need `ProjectGroupView`

## Links

- Discovered as part of testing https://github.com/OctopusDeploy/Issues/issues/5379

**Comment by jburger** [comment]
Release note: fixes dashboard bug when accessing projects in a group the user doesn't have access to.
