### ISSUE TITLE
Kubernetes step doesn't support Let's Encrypt

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#5394]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

The current Kubernetes step only supports using a certificate in Octopus as the TLS certificate for Ingress. Some customers are wanting to use Let's Encrypt, as per this documentation https://docs.microsoft.com/en-us/azure/aks/ingress-tls, and it is not possible.

The step should be updated to include support for external certificates, like Let's Encrypt.

## Workarounds

Ingress controllers like nginx can be configured with a default certificate (https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate), and the certificate in the `Configure TLS certificate` dialog can be left blank to use the default certificate.

The ingress resource can also be defined in a `Deploy raw Kubernetes YAML` step, and configured using Octostash templates.

## Links

https://help.octopus.com/t/using-letsencrypt-prod-as-tls-secret/22526

**Comment by GeertvanHorrik** [comment]
> The step should be updated to include support for external certificates, like Let's Encrypt.

Ideally I would just be able to put in *any* text (instead of a forced selector) and I would be happy.

**Comment by jcuzzi** [comment]
Agreed, having the option to enter the name of an existing tls secret as text would be great.

**Comment by zentron** [comment]
Release Note: K8S deploy step supports external secrets to be used for ingress TLS
