### ISSUE TITLE
Update bundled AWS Cli version

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#5395]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement
We should bump the AWS CLI version, since there are some capabilities which customers wish to leverage such as AWS CodeDeploy enabling blue/green scenarios.

## Workarounds

Use Run CLI script step targeting a Linux worker which has AWS CLI installed globally.

## Links
https://secure.helpscout.net/conversation/801151250/40862/

**Comment by KennethBates** [comment]
Another request: https://help.octopus.com/t/aws-cli-version/23212/3

**Comment by matt-richardson** [comment]
Release note: Update bundled AWS CLI to `1.16.178`
