### ISSUE TITLE
Cloning a project does not clone its logo

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#5399]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Cloned project does not include the logo from the original project.

## What I expected to happen

Project logo should be cloned along with the project, just like the variables and deployment process.

## Steps to reproduce

1. Create a project with a logo
2. Clone the project

## Links

https://help.octopus.com/t/cloning-project-does-not-clone-icon/22535

**Comment by slewis74** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cloning a project doesn't include logo](https://trello.com/c/8IzjhjFX/381-cloning-a-project-doesnt-include-logo)

**Comment by NickJosevski** [comment]
Fixed by: https://github.com/OctopusDeploy/OctopusDeploy/pull/3560

**Comment by NickJosevski** [comment]
Release Notes: Project logo will be included in the project cloning process.
