### ISSUE TITLE
Migrator is slow when importing into a target database with a large VariableSet table

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#5406]
# The bug

When the migrator is used to import data into a target database with a large variable set table (~10k rows @ ~2GB) the import can be excessively slow with some customers experiencing exports of over 15 minutes. This happens even when importing a small data set from a partial export.

The secret appears to be when we are building the Identity Map. This process was originally built to migrate an entire Octopus 2.6.5 database to Octopus 3.0, and the Identity Map process was "the simplest thing that could possibly work": it performs a `SELECT * FROM VariableSet` on the target database to fill the Identity Map.

## What I expected to happen

The import process for a small project should take a reasonable amount of time based on the size of the project being imported.

In code we should change the Identity Mapping process to be more efficient when importing data from a `partial-export`.

## Steps to reproduce

1. Fill the target database with lots of large variable sets
2. Export a single small project from somewhere
3. Try to import the single small project into the target database with lots of large variable sets
4. The import process will be slow, especially when the Octopus.Migrator.exe process is accessing a SQL Server database across a normal network.

### Log excerpt

The following log excerpt shows an example of the 15 minute export symptom
```
09:10:53   Info     |       Reader took 2751ms (0ms until the first record) in transaction '<unknown>': SELECT *
09:10:53   Info     |       FROM dbo.[Release]
09:10:53   Info     |       ORDER BY [Id]
09:26:00   Info     |       Reader took **908382ms** (24ms until the first record) in transaction '<unknown>': SELECT *
09:26:00   Info     |       FROM dbo.[VariableSet]
09:26:00   Info     |       ORDER BY [Id]
```

## Affected versions

**Octopus Server:** since 3.0. Reported in 2019.1.6 

## Workarounds

If you are experiencing this issue, the following things can be tried to improve performance:
- minimizing the amount of data in the target VariableSet table is required to store by avoiding the storage of large configuration files. Instead consider shipping these files as part of your deployment package and injecting smaller snippets of configuration
- Minimizing the number of unused projects and releases in your target database
- Inspect the indexes of the target VariableSet table and ensure the index on ID isn't fragmented and in need of a rebuild 

## Links
[internal support ticket](https://secure.helpscout.net/conversation/800019264/40788?folderId=2118197)

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

**Comment by MJRichardson** [comment]
Release note: Migrator import command won't load variable sets associated with deployments
