### ISSUE TITLE
Certificate with private-key being displayed as not having private-key

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5426]
Certificates which include a private-key when uploaded are being displayed as not having a private-key:

![image](https://user-images.githubusercontent.com/113759/55127424-c9248b80-515b-11e9-80a6-88a23ce0ba58.png)

This also impacts downloading the certificate, as no password is able to be set when downloading as PFX.

Introduced in 2019.2.2 (https://github.com/OctopusDeploy/OctopusDeploy/pull/3544)

Reported by https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1553694680337300 (Octopus Community Slack)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Certificate with private-key being displayed as not having private-key](https://trello.com/c/XOg45Kim/482-certificate-with-private-key-being-displayed-as-not-having-private-key)

**Comment by verzada** [comment]
Is there any progression on this issue?

**Comment by matt-richardson** [comment]
Not as yet. It's near the top of our list, and we're hoping to tackle shortly.

**Comment by verzada** [comment]
Is the bug fixed in 2019.4.0? could not see it mentioned in the comparison view for 2019.4.0
https://octopus.com/downloads/compare?from=2019.4.0&to=2019.4.0

**Comment by zentron** [comment]
This fix did not make it into `2019.4.0` and instead will shortly go out in `2019.4.1`
