### ISSUE TITLE
Target detail page issues excessive number of requests for TagSets

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#5430]
Reproduced in `2018.10.5` (Current LTS). This makes IE unresponsive, Chrome very sluggish

For repro steps see:
https://help.octopus.com/t/unavailable-targets-create-continuous-flow-of-requests-in-web-interface/22614

The work around is to expand the `Associated Tenant` section. This will stop the request storm.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Target detail page issues excessive number of requests for TagSets #5430](https://trello.com/c/ToJ25Gqe/525-target-detail-page-issues-excessive-number-of-requests-for-tagsets-5430)

**Comment by droyad** [comment]
The problem exists on all machine pages. It looks like the page is being continually rebuilt due to the server version change notification being dismissed and Redux seeing that as a state change.

**Comment by shaunmarx** [comment]
Release Note: Fixed an issue where an excessive amount of requests were being made for tenant tag sets when on the deployment target settings page
