### ISSUE TITLE
Move projects between spaces

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5451]
This would allow moving existing projects, which were placed in the default space, to be moved to another space. 

All the associated data (lifecycles, tenants, accounts, certificates, etc) would also need to be moved.

**Comment by JChatmasOctopus** [comment]
I have a customer that asked about the status of this on a call today.

**Comment by whereisaaron** [comment]
This customer asked about it too 😄 
https://help.octopus.com/t/how-do-i-transfer-or-clone-a-project-to-a-different-space-in-octopus-cloud/23333

I am not sure you can move the associated data if it is shared by multiple projects in the source space? If you could duplicate those associated resources into the target space (if they don't exist there with the same name) that would be fabulous.

**Comment by rboddy** [comment]
This is the only thing holding my team back from spaces right now. We have a distributed system with over 80 Microservices/APIs and moving our deployments for each one to a new space would be very time consuming. We've discussed writing against the API to pull all our deployment processes/projects from the default space and create them in a new space and just use new lifecycles, but a migration tool would be easier.

**Comment by kharatsunil** [comment]
Hi,

We are using a process to migrate projects into a different space, can't take responsibility if something breaks :) so please test it yourself before you use it.
1. Create a space in the Octopus instance where you wish to migrate the project, take note of the Project space id (let's say Space-22)
2. Use Octopus partial export to get all the data you need for that project.
_Octopus.Migrator.exe partial-export --instance "OctopusServer" --projectGroup="project-group name" --directory "D:\octoexport" --password "xxxxxx"  --ignore-machines --ignore-tenants_
3. In the directory where all the export has been copied lots of files will have reference to Space the project was copied from. Replace that with the new Space id:
_Get-ChildItem -Filter “*Spaces-1*” -Recurse | Rename-Item -NewName {$_.name -replace ‘Spaces-1’,’Spaces-22’ }_
4. Open the Folder containing the project files as a workspace in Notepad++
- Replace default Space ID with the new Space ID
- Get the Feed ID for that space from Octopus Database & replace all the occurrences of default Feed-ID with the new Feed ID for new Space (Eg. feeds-builtin with Feeds-1021)
5. Then use Octopus import command to import the project. It then shows up in the new space.

Cheers,
Sunil

**Comment by emilwester** [comment]
Is there any progress on this one? Can i upvote this feature somehow?

**Comment by albernazf** [comment]
still nothing?

**Comment by tonythebest** [comment]
I developed a python client tool to migrate the whole space to another space. This tool can also migrate the space to another space on different server. I will share the tool if company allows.

**Comment by tonythebest** [comment]
I developed a python tool to move/clone the projects and other types from space to space and from octopus server to octopus server
https://github.com/tableau/octopus-python-client/wiki#migrationclone-data-across-spacesservers

**Comment by tonythebest** [comment]
https://github.com/tableau/octopus-python-client/ has some other features. Let me know if you see any issues.

**Comment by james-a-morgan** [comment]
Is there somewhere we can upvote to get this functionality added sooner rather than later?  I have 30 projects in the Default space and would like to isolate the teams.  Any information is appreciated.

**Comment by GillesBer** [comment]
I followed the manual steps from @kharatsunil.
Could you elaborate on 

`Get the Feed ID for that space from Octopus Database & replace all the occurrences of default Feed-ID with the new Feed ID for new Space (Eg. feeds-builtin with Feeds-1021)`

I also identified that you have to manually update the teams, in order to include 'user role' in the new space.

**Comment by tonythebest** [comment]
https://github.com/tableau/octopus-python-client/ has a new GUI to do clone now.

**Comment by donkeybrains** [comment]
Not being able to clone or move projects between project groups is a pain in the neck. I must be missing something here. Is this correct?

**Comment by tonythebest** [comment]
@donkeybrains 

Assume you are using https://github.com/tableau/octopus-python-client/. You have project A in project group B and you want to clone project A to project group C as A_clone

- clone project A to project A_clone (it would not change project group)

![image](https://user-images.githubusercontent.com/3278731/119532893-26b3c300-bd3a-11eb-9991-3f976ba7de61.png)


- go to the settings of project A_clone and change the project group from B to C

![image](https://user-images.githubusercontent.com/3278731/119533026-4d71f980-bd3a-11eb-8d4c-4929738b580a.png)

- you are done

run octopus_python_client_gui to start the GUI. Let me know if you have more questions.

**Comment by donkeybrains** [comment]
Clang my fault. Didint set the project group to move to. It does work and its in the other group now. Many thanks.

**Comment by benPearce1** [comment]
This functionality was implemented in 2021.1 via the [Import/Export](https://octopus.com/docs/projects/export-import) feature.

**Comment by inemerovsky** [comment]
Hello! Is it possible to move Octopus projects between Octopus Dashboards?
