### ISSUE TITLE
Variables not correctly being passed from parent to child projects with Deploy A Release steps

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#5467]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When passing variables from a parent project to a child project using the Deploy a Release step it is possible that the variables aren't replaced as planned. What we state in our documentation is that _Variables passed in will override existing variables in the child project if the names collide_ however we pass the variables in without any scoping applied. 

This means that variables with any scoping applied (as per our [scope specificity rules](https://octopus.com/docs/deployment-process/variables#Scopingvariables-Scopespecificity)) will maintain its value instead of being overwritten as expected.

## What I expected to happen

Variables being passed from a parent project to a child project should be considered `most specific` as stated and should override these variables.

## Steps to reproduce

1. Create a child project with two variables, one scoped and one unscoped
2. Create a simple script step to write out the variable values
3. Create and deploy a release
4. Create parent project with Deploy a release step
5. Input the same variables with different values
6. Create and deploy a release of the parent project
7. Note that the un-scoped variable value changes, however the scoped value does not

### Screen capture

Initial deployment of child project, note both variables are set to `Child`
![Screen Shot 2019-04-09 at 1 27 45 pm](https://user-images.githubusercontent.com/29847178/55771503-a97e5300-5acb-11e9-8c54-0e7f5b06795a.png)

Deployment from parent project, I would expect both scoped and unscoped variables to be the same (`Parent`) however the scoped variable has retained the original scoped value.
![Screen Shot 2019-04-09 at 1 26 38 pm](https://user-images.githubusercontent.com/29847178/55771534-d5013d80-5acb-11e9-800d-4a10a3a07841.png)

## Affected versions

All versions of Octopus with `deploy a release` step.

## Workarounds

Remove scoping from child projects, however this may provide unintended consequences.

## Links

[Original Report](https://secure.helpscout.net/conversation/818983878/41851?folderId=1465198)

**Comment by alexrolleyoctopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variables not correctly being passed from parent to child projects with Deploy Relelase steps #5467](https://trello.com/c/L9enzGhl/617-variables-not-correctly-being-passed-from-parent-to-child-projects-with-deploy-relelase-steps-5467)

**Comment by NickJosevski** [comment]
Release Notes: Variables supplied from parent to child projects with Deploy Release steps will correctly have a higher specificity score now allowing them to always overwrite child variables
