### ISSUE TITLE
High browser CPU usage after viewing deployment task page

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5476]
Viewing a deployment task log gradually increases the browser CPU usage.  This continues even after navigating away from the page.

Replicated in 2019.4.2

Reported by https://secure.helpscout.net/conversation/822504576/42014?folderId=571733 (private link)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High browser CPU usage after viewing deployment task page](https://trello.com/c/6E6fFqB0/657-high-browser-cpu-usage-after-viewing-deployment-task-page)

**Comment by droyad** [comment]
I think this is due to `Sticky.tsx` stuck in a loop:
![image](https://user-images.githubusercontent.com/1687639/56935736-7103ef00-6b36-11e9-9c59-cd8dda4cd305.png)

One way to reproduce, go to the `Tasks` tab and queue a lot of tasks. Replicated on `2019.3.1` as well.

**Comment by shaunmarx** [comment]
Release Note: Fixed high CPU usage on deployment task page
