### ISSUE TITLE
Bug: Unable to pull docker image on some ssh targets

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#5481]
A bug appears to have been introduced for some platforms when the Docker Acquisition step runs.

An example of the messages that appear in the logs
>Feed type provided `Docker` using DockerImagePackageDownloader
>bash: Calamari/Temp/5f251161-9c57-4807-9220-aacde2746244/Bootstrap.d41-4bd3-b222-d6a6c4343caa.Octopus.DockerPull.sh: No such file or directory
> Failed to download package mongo v4.1.10 from feed: 'https://index.docker.io'
> Unable to pull Docker image

Is appears as though the script is having some problems writing to the temp directory on some ssh targets.

**Comment by zentron** [comment]
New version of Calamari in `2019.4.3` writes temporary files into current working directory rather than filesystem temp location. Preliminary test with one customer's instance indicates this resolves the problem.

**Comment by joelhays** [comment]
@zentron any thoughts on how to fix this on 2019.3.0 LTS when upgrading is not an option?
