### ISSUE TITLE
Space creation may fail if unexpected data exists defining Feeds

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5504]
# The bug

Creating a new Space fails for some customers.

## What I expected to happen

Space creation should be 

## Steps to reproduce

Create a new space, if your database is in an unexpected state it may fail.

### Screen capture

![image](https://user-images.githubusercontent.com/119096/56579444-81d2d300-6613-11e9-9f0e-0be01634fba6.png)

### Log exerpt

```
Error while executing SQL command in transaction ‘<unknown>’: Violation of PRIMARY KEY constraint ‘PK_Feed_Id’. Cannot insert duplicate key in object ‘dbo.Feed’. The duplicate key value is (Feeds-1). The statement has been terminated. 
```

## Affected versions

**Octopus Server:**  2019.x

## Workarounds

- None yet, please contact us support@octopus.com while we still investigate

## Links

 - https://secure.helpscout.net/conversation/834018031/43730?folderId=845288 (internal link)
 - https://help.octopus.com/t/error-while-adding-a-new-spaces/22763/7 (internal link)
 - https://secure.helpscout.net/conversation/818034600/41767?folderId=845288  (internal link)
- https://secure.helpscout.net/conversation/884556749/46250/ (internal link)

**Comment by hnrkndrssn** [comment]
Release Note: Fixed issue where historical feed data in database caused primary key violation when creating a new space
