### ISSUE TITLE
Cannot step into script module function while debugging 

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#5508]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When performing a remote debugging session with Powershell it will error with "Unable to open ‘Library_Common_somerandomstuff.psm1’: File not found if any script modules are used. 

## What I expected to happen

You should be able to step through script modules when debugging. This is related to [this issue](https://github.com/OctopusDeploy/Issues/issues/3895) where we clean up script modules as soon as the script is run and loaded in memory.

## Affected versions

**Octopus Server:** 3.17.12 and later

## Workarounds

N/A

## Links

[Initial Report](https://help.octopus.com/t/cannot-step-into-script-module-function-while-debugging/22751)

**Comment by alexrolleyoctopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot step into script module function while debugging #5508](https://trello.com/c/41xqByCi/716-cannot-step-into-script-module-function-while-debugging-5508)

**Comment by matt-richardson** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/commit/637bb41c9b219109bb088b98b8e27677c92b4435

**Comment by matt-richardson** [comment]
Release Note: Can now step into script modules while debugging PowerShell script steps.
