### ISSUE TITLE
Test permissions page in UI breaks for some users

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5510]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

For some users, testing their permissions breaks the page in the UI with`"TypeError: Cannot read property 'indexOf' of null"`

## Steps to reproduce

1. Go to *Configuration > Test Permissions > Select a user (tested with user `Kenny` in master)

### Screen capture

![test_permissions](https://user-images.githubusercontent.com/20388190/56777342-50752580-6814-11e9-883d-441782db17bb.png)

### Log exerpt

```
TypeError: Cannot read property 'indexOf' of null

supportsRestriction (/app/areas/configuration/components/TestPermissions/PermissionTable.tsx:40:139)
supportsRestriction (/app/areas/configuration/components/TestPermissions/PermissionTable.tsx:93:29)
map (/app/areas/configuration/components/TestPermissions/PermissionTable.tsx:87:50)
map (/app/areas/configuration/components/TestPermissions/PermissionTable.tsx:86:41)
og (/node_modules/react-dom/cjs/react-dom.production.min.js:145:95)
b.elementType;null!==a&& (/node_modules/react-dom/cjs/react-dom.production.min.js:174:122)
hi (/node_modules/react-dom/cjs/react-dom.production.min.js:221:15)
ii (/node_modules/react-dom/cjs/react-dom.production.min.js:222:280)
```

## Affected versions

Reproduced in master and reported in 2019.4.4

**Octopus Server:** 

## Workarounds

Hit the API endpoint directly to export the user's permissions to CSV (`/api/users/users-205/permissions/export{?spaces,includeSystem}`)

## Links

Source: https://secure.helpscout.net/conversation/836734295/43858?folderId=954335 (private link)

**Comment by KennethBates** [comment]
Another report: https://help.octopus.com/t/v2019-4-4-test-permission-throws-error/22818

**Comment by tmbam** [comment]
One More report: https://help.octopus.com/t/error-when-testing-permissions-an-unexpected-error-occurred-in-octopus-v2019-3-4-typeerror-cannot-read-property-indexof-of-null/23245

**Comment by dhoeglund** [comment]
I'd like to add that we are seeing the same issue as well.

**Comment by anandbaboo10** [comment]
Hi... we are using octopus version 2019.3.4 and we are able to see same exception been thrown when trying to view the permission for a particular user.

**Comment by tmbam** [comment]
Another report of issue found in 2019.3.1.  https://secure.helpscout.net/conversation/1012407262/53509?folderId=2845830

**Comment by paraicoceallaigh** [comment]
Another occurrence: https://octopus.zendesk.com/agent/tickets/76790. 2019.6.0

**Comment by zentron** [comment]
This issue is no longer reproduceable in the latest build (`2022.2.191`).
Will reopen for investigation of additional incidents arise
