### ISSUE TITLE
Terraform steps support for Azure accounts

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#5518]
# The feature

## What it actually enables people to do

Terraform steps have been updated to include support for Azure accounts, so we now support both AWS and Azure accounts.
As part of this change, we have also added an extra output variable for the `Plan` step that includes[ the detailed exit code](https://www.terraform.io/docs/commands/plan.html#detailed-exitcode), the output variable is named `TerraformPlanDetailedExitCode`.
The last change is Linux support, so we now support running Terraform steps in ssh targets (you do need the Terraform CLI installed on these targets).

### Mockup

![Mockup](https://www.useronboard.com/imgs/posts/mario-water.png)

## What pain relievers or gain generators are we solving for people?

The biggest pain relief is the support for Azure provider out of the box.

## Who will care about it?

Customers that want to use Terraform to administer Azure resources.
Customers that want to use ssh Linux targets to run Terraform steps.

## Elevator pitch for this feature

Octopus Terraform ❤️ Azure

## How much noise should we make about this?

# Links

**Comment by johnsimons** [comment]
Release Note: Added support for Azure accounts in Terraform steps

**Comment by mud5150** [comment]
Oh man, thanks so much. Been waiting for this for a while.
