### ISSUE TITLE
Space calculation for standard unlimited licenses after upgrade from enterprise is limiting users to 1 space.

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#5548]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Customers who upgraded from Enterprise (unlimited users/projects/machines/1 node) to Standard Unlimited are being limited to one space.  This is because the date of the 

![image](https://user-images.githubusercontent.com/38642825/57320677-108c2900-70c5-11e9-9709-a49a09ba591f.png)

This is because the customer purchased the license back in 2015 and that license was upgraded.  It looks like the algorithm to determine spaces can't differeniate between enterprise and standard unlimited.  It is going off of the valid from date.

```
<License Signature="Invalid Sig">
  <LicensedTo>Demo Company</LicensedTo>
  <LicenseKey>Key</LicenseKey>
  <Version>2.0<!-- License Schema Version --></Version>
  <ValidFrom>2015-08-15</ValidFrom>
  <MaintenanceExpires>2020-01-14</MaintenanceExpires>
  <ProjectLimit>Unlimited</ProjectLimit>
  <MachineLimit>Unlimited</MachineLimit>
  <UserLimit>Unlimited</UserLimit>
</License>
```

## What I expected to happen

Customers with standard unlimited get at least three spaces.

## Affected versions

**Octopus Server:** 2019.x.x

## Workarounds

We have been giving customers trial licenses to give them the three spaces.

## Links

https://secure.helpscout.net/conversation/846950732/44356/

**Comment by michaelnoonan** [comment]
The policy for Spaces looks right: https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Core/Features/Licensing/Schemes/Policies/SelfHostedSpaceLimitPolicy.cs#L74

As you've suggested it must be related to `ValidFrom` https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Core/Features/Licensing/LicenseKeys/LicenseKey.cs#L335

Progressing with this is not straightforward. The reason it's not straightforward: their license looks all the world to be an "old" `Enterprise` license. `Standard Unlimited` looks exactly the same except for the `ValidFrom` date (as per the logic in `LicenseKey.IsSelfHostedEnterprise()` and `LicenseKey.IsSelfHostedStandardUnlimited()`).

The bit I'm missing here is how they transitioned from `Enterprise` to `Standard Unlimited`. I didn't realise this was something customers could do, or would do.

Another reason this is not straightforward: the only logical logic change I can think of to fix this customer with their old license key would result in giving every `Enterprise` customer `3 Spaces`.

The most straightforward approach may be to add `<Spaces>3</Spaces>` to their license.

**Comment by michaelnoonan** [comment]
We are going to modify Octofront so we can add `<Spaces>3</Spaces>` to licenses which fall into logic gaps here.
