### ISSUE TITLE
Terraform steps have lost the ability to assume an AWS Service Role

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#5556]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The Octopus Terraform steps changed in `2019.4.7` and the ability to assume an AWS service role. The AWS account only lets you select an AWS account specifically

![image](https://user-images.githubusercontent.com/4229735/57503958-e1302300-7335-11e9-9280-804e67bb6678.png)

## What I expected to happen

The step used to look like this

![image](https://user-images.githubusercontent.com/4229735/57503915-aa5a0d00-7335-11e9-8b52-ce18b8c946c6.png)

It should still support the service role and additional role settings.

## Affected versions

**Octopus Server:** 
2019.4.7

## Workarounds

None

## Links

https://secure.helpscout.net/conversation/849306263/44463/

**Comment by shaunmarx** [comment]
Release Note: Fix terraform steps unable to asume AWS service roles

**Comment by gurkarangulati** [comment]
This issue has re-opened/been re-introduced in the 2019.5.5 release.

**Comment by matt-richardson** [comment]
@gurkarangulati - We had an issue with our build pipeline with 2019.5.5 where the UI wasn't bundled correctly. We pulled that version and release 2019.5.6, which contains the correct UI. Sorry for the hassle.
