### ISSUE TITLE
Variable editing and tenant tag scoping is not intuitive

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#5574]
# The enhancement

Currently, editing variables scoped to tenant tags is painful, as it takes you out of the flow of the in-line variable editing process and forces you into the variable editor dialog (switching between the variable value and scoping pages).

This makes variable scoping for tenant tags hard-to-discoverable for the most part, and generally not intuitive.

We want to investigate an in-line tenant tags dropdown filter to be made available with the other quick scope filters (like environments, roles, targets etc.), grouped by tag set (using [optgroups](https://www.w3schools.com/tags/tag_optgroup.asp)) so you can select tags directly from a single filter dropdown.

Failing that, at a minimum we should include a tag sets dropdown in this filter that opens the variable editor scoping page, to make this more discoverable (doing the same job as the "Open editor" link essentially).

### Related issue

- the “Open editor” link from the scoping selector works differently when editing an existing variable (it opens the scoping popover), but differently when defining a new one (it opens the variable editor popover, so you still have to make another click to get to the scoping popover). If you click "Open editor" from the scoping selector, it should ALWAYS take you to the scoping page.

## Workarounds

- A quick-jump to the scoping details so you can edit tags. is the "Open editor" link at the bottom of the scoping popover. This goes straight to the scoping page of the variable editor dialog, so you can easily select your tags without having to switch to the "define scope" page first.

## Links

Source: https://help.octopus.com/t/scope-variables-by-tenant-tag-unintuitive-gui/23119

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable editing and tenant tag scoping is not intuitive](https://trello.com/c/w2W2vQmj/621-variable-editing-and-tenant-tag-scoping-is-not-intuitive)

**Comment by jjanuszkiewicz** [comment]
I'd like to add that the proposed workaround doesn't work in some cases - the “Open editor” link works differently when editing an existing variable (it opens the scoping popover), but differently when defining a new one (it opens the variable editor popover, so you still have to make another click to get to the scoping popover). Is this a separate bug?

**Comment by octokhor** [comment]
This ticket is 3 years old and better placed in a pitch doc than in the FnM backlog. Closing this for now.
