### ISSUE TITLE
TypeError on certificate search

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5575]
# Prerequisites

- [ ] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using the search filter in the Certificates page, the following TypeError displays: `TypeError: Cannot read property ‘toLowerCase’ of null`. Probably some issue with having an invalid certificate, and the user reporting it noticed the subject common name on the certificate was Null.

## Links

Source: https://help.octopus.com/t/an-unexpected-error-occurred-in-octopus-v2019-3-2-typeerror-cannot-read-property-tolowercase-of-null/23117/4

**Comment by KennethBates** [comment]
Report of similar TypeError ("TypeError: t.Thumbprint is null") when searching certificates: https://help.octopus.com/t/an-unexpected-error-occurred-in-octopus-v2019-3-3-typeerror-t-thumbprint-is-null/23218

**Comment by NickJosevski** [comment]
Release Note: Fix for TypeError on certificate search, when certificate data was in an unexpected state
