### ISSUE TITLE
Display which projects and releases a specific package is used in

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5622]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

Add a way within the UI to search which projects and releases a package is used in.

## Mockup

Potentially the way to approach this could be to add a search option in the *Library > External Feeds* page. For packages in the built-in repository, it could be included in the package's page in the UI, in the same way to how there's a list of projects that use a lifecycle shown below:

![projects_used_by_lifecycle](https://user-images.githubusercontent.com/20388190/59398632-41eac980-8dd4-11e9-93bf-0562d41c3a40.png)

## Workarounds

Currently you have to go digging around deployment processes or task logs to find this information.

## Links

Requested here (private link) https://secure.helpscout.net/conversation/877773199/45910/

**Comment by MJRichardson** [comment]
This is a neat idea, but it's non-trivial to implement, and realistically won't make it to the top of the priority list in the immediate future.
