### ISSUE TITLE
Unable to browse AWS Docker repo's when image count is >200

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#5624]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When you have ~200 or more images in your Docker feed when searching for an image the search errors with `A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.`

## What I expected to happen

We should be able to search docker feeds regardless of item count

### Log excerpt

```
2019-04-19 19:44:47.7760   5628     44 ERROR  Unhandled error on request: http://octopus/api/Spaces-1/feeds/Feeds-4/packages/versions?packageId=package%2Fui-api&take=20&includePreRelease=true&includeReleaseNotes=false <GUID> by admin : A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.
System.UriFormatException: A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Octopus.Core.Packages.Docker.DockerRegistryOAuthClient.<>c__DisplayClass8_0.<GetNextPageUrl>b__1(String x)
   at Octopus.CoreUtilities.MaybeExtentions.Select[T,R](Maybe`1 maybe, Func`2 selector)
   at Octopus.Core.Packages.Docker.DockerRegistryOAuthClient.GetNextPageUrl(HttpResponseMessage response)
   at Octopus.Core.Packages.Docker.DockerRegistryOAuthClient.<GetAllPages>d__4.MoveNext()
```

## Affected versions

**Octopus Server:** ??? > Latest 

## Workarounds

N/A

## Links

[Initial Report](https://secure.helpscout.net/conversation/832533934/)

**Comment by zentron** [comment]
Initial investigation using AWS ECR with > 200 *tags* for a given image indicates that it is able to search through more than one page of results
![image](https://user-images.githubusercontent.com/1830666/59416199-46c97080-8e08-11e9-87ee-4db99f114e04.png)
![image](https://user-images.githubusercontent.com/1830666/59416216-4d57e800-8e08-11e9-8a36-2b35625c5b17.png)
Some further testing may be required to reproduce this issue. Maybe ill try with more?
In addition, adding > 200 repositories (different images) also worked
![image](https://user-images.githubusercontent.com/1830666/59416383-9ad45500-8e08-11e9-9b01-56ce04cf9fa7.png)

**Comment by zentron** [comment]
Although I was unable to reproduce the exact error even with 600 images, The error message points pretty clearly to what is _probably_ going on. So have updated the parsing of the pagination links to allow the header to send the next page as a relative or absolute url (previously it expected relative)

**Comment by zentron** [comment]
Release Note: Bugfix paging through docker registry results
