### ISSUE TITLE
Extracting step template from deploy a package and removing the package ID results in a "The given key was not present in the dictionary" error

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#5628]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [ ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
Extracting a step template from a "Deploy a package" step, then removing the package ID from the template will result in a "The given key was not present in the dictionary" error.

## What I expected to happen

Action would be blocked.

## Steps to reproduce
1) Add the "Deploy a Package" step to the process
2) Give it a name, any role and specify a Package ID
3) Save it
4) On Project settings select this step as "Release Versioning"
5) Go back to that step, enter to the details page and "Extract Step Template"
6) Go to that step template and remove the Package ID setting and save the changes
7) Go to "Usage" and update the step in the process
8) Now try to access the project, the step in the project process or the project overview and you will see the error on every page

### Screen capture

https://www.dropbox.com/s/36ukmdync0iz1vl/Bug-20190614.gif

## Affected versions

**Octopus Server: x -> 2019.5.10+** 

## Workarounds

Don't do this :)

## Links
Source ticket: https://secure.helpscout.net/conversation/879223799/46002?folderId=557082 (internal link)

**Comment by MJRichardson** [comment]
This was a specific instance of the more general https://github.com/OctopusDeploy/Issues/issues/5689
