### ISSUE TITLE
Install helm chart specific version

### ISSUE THREAD

**Issue by ekjuanrejon** [OctopusDeploy/Issues#5629]
Hello

how can i specify the chart version i want to install when running a helm install step?

**Comment by mcasperson** [comment]
Hi @ekjuanrejon , you can use channels to define a specific version of any package used by Octopus, including those used by Helm. https://octopus.com/docs/deployment-process/channels has more details on how to use channels.

**Comment by ekjuanrejon** [comment]
@mcasperson I would want to agree with you but that is the octopus way of doing it. Helm install has a --version which is being ignored by the helm step in octopus

https://helm.sh/docs/helm/#helm-install

**Comment by ekjuanrejon** [comment]
--version string           Specify the exact chart version to install. If this is not specified, the latest version is installed

**Comment by mcasperson** [comment]
Ho @ekjuanrejon, please feel free to raise this question with the support team. You can contact them using the links from https://octopus.com/support.
