### ISSUE TITLE
Generic template-based file transformation

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#563]
Octopus has had built-in config file transformation for some time, but uses an XML-driven approach rather than the `#{Substitution}` approach that we use elsewhere (e.g. for email templates and so-on).

Since 2.0 has a more powerful template syntax, let's create a feature that is configured by listing target files, e.g.:

```
Octopus.Feature.TemplateSubstitution.FilesToTransform = "MyFile.txt; MyFile.config; MyFile.ps1"
```

And at deployment time:
- Loads each file
- Parses the file as a template
- Executes the template
- Writes the output back to the file

Example of a template for a HOSTS file might be:

```
foo.com  123.456.678.789
#{each host in ExtraHostBindings}
# Server for #{host}
#{host.Hostname}  #{host.IP}
#{/each}
```

The corresponding variables would look like:

| Name | Value |
| --- | --- |
| ExtraHostBindings[DB].Hostname | db-qa.mycompany.com |
| ExtraHostBindings[DB].IP | 345.678.789.67 |
| ExtraHostBindings[Apps].Hostname | apps-qa.mycompany.com |
| ExtraHostBindings[Apps].IP | 234.567.67.6 |

And the output like:

```
foo.com  123.456.678.789
# Server for DB
db-qa.mycompany.com   345.678.789.67
# Server for Apps
apps-qa.mycompany.com  234.567.67.6
```

**Comment by johnkors** [comment]
Hi @nblumhardt , is the input list of files comma separated or newline separated? Using Octopus 2.3.X. Couldn't find it in the docs.

**Comment by nblumhardt** [comment]
Hi @johnkors - I'm struggling to remember; the screenshot above uses commas but there was some standardisation around how these are specified, later on. Have you had trouble with one or the other? Cheers!
