### ISSUE TITLE
Account usage does not show releases where the project currently does not reference the account

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#5644]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The UI does not show anything if a account is in a variable set belonging to a release but has since been removed from the project

1. Add a variable to a project's variable set
1. Create a release
1. Remove the variable from the variable set

The Usages API now returns:
```
{
  "Targets": [],
  "DeploymentProcesses": [],
  "Releases": [],
  "ProjectVariableSets": [
    {
      "ProjectSlug": "azure",
      "ProjectName": "Azure",
      "ProjectId": "Projects-21",
      "Releases": [
        {
          "ReleaseId": "Releases-141",
          "ReleaseVersion": "0.0.10"
        }
      ],
      "IsCurrentlyBeingUsedInProject": false
    }
  ],
  "LibraryVariableSets": [],
  "Links": {}
}
```

The `IsCurrentlyBeingUsedInProject` causes the entry to be ignored by the UI in the "project" section. 

## What I expected to happen

The account usage should show the old release.

## Workarounds

Nothing good, unfortunately

## Links

Pulled out of https://github.com/OctopusDeploy/Issues/issues/4675.

**Comment by droyad** [comment]
It looks like https://github.com/OctopusDeploy/OctopusDeploy/pull/2881 actually fixed this

**Comment by matt-richardson** [comment]
We determined that the original issue had already been fixed as @droyad mentioned, so this can be closed.
