### ISSUE TITLE
Spaces missing from Azure VM Extension

### ISSUE THREAD

**Issue by DevOpsDerek** [OctopusDeploy/Issues#5655]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

## Steps to reproduce

1. Go to 'Virtual Machine in Azure Portal.'
2. Follow on '.https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-the-azure-portal'
3. Notice that Spaces is not listed

### Screen capture

![image](https://user-images.githubusercontent.com/42529489/60452156-d3a46480-9c25-11e9-9c00-642a713f62cb.png)

### Log exerpt

```
Insert your log exerpt here.
```

## Affected versions

**Octopus Server:All** 

## Workarounds

* Automate the tentacle installation as per https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/automating-tentacle-installation
* Automate installation of Listening Tentacle with Chocolatey ````Choco Install OctopusDeploy.Tentacle```` and then configure as per https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/automating-tentacle-installation#AutomatingTentacleinstallation-Example:ListeningTentacle
* Automate installation of Polling Tentacle with Chocolatey ````Choco Install OctopusDeploy.Tentacle```` and then configure as per https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/automating-tentacle-installation#AutomatingTentacleinstallation-Example:PollingTentacle

## Links

* https://secure.helpscout.net/conversation/1138867661/62868?folderId=1514841 (Private Link)

**Comment by chrischu** [comment]
Is there any ETA when this might be implemented?

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customer using Azure VM extension can only create new targets in the Default space](https://trello.com/c/JFd0HCP0/3164-customer-using-azure-vm-extension-can-only-create-new-targets-in-the-default-space)

**Comment by chrischu** [comment]
> 
> 
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Customer using Azure VM extension can only create new targets in the Default space](https://trello.com/c/JFd0HCP0/3164-customer-using-azure-vm-extension-can-only-create-new-targets-in-the-default-space)

Am I supposed to be able to see something when clicking on this link (I only get an error that the card is not found since it is on a private board) or is this just for other contributors?

**Comment by DevOpsDerek** [comment]
The link is for internal tracking purposes only @chrischu

**Comment by mcasperson** [comment]
@chrischu The recommended solution to support spaces is to use DSC. We have documentation for this process at https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-an-arm-template-with-dsc.

**Comment by mcasperson** [comment]
We have made the decision to deprecate the Azure VM extension, and so no new features will be added to it. The docs at https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines have more details.

**Comment by chrischu** [comment]
Wait a second. The reason you state for not supporting the extension any longer is that "Microsoft no longer supports third party extensions", but the discussion linked to in your documentation only states that third party Azure VM extensions publishing through the marketplace is no longer supported. That does not really seem to add up from my point of view.

Do you have any other evidence that Microsoft no longer supports third party VM extensions? I not only ask regarding the deprecation of the Octopus VM extension, but also since my team is thinking about publishing an Azure VM extension of our own and that being no longer supported is news to us.

**Comment by mcasperson** [comment]
We've attempted to reach out to Microsoft to get support for issues publishing the last round of updates to the extension, and could not find anyone who could help. That, combined with the statements that publishing extensions is no longer supported, was a factor in us deciding to no longer pursue development of the extension.
