### ISSUE TITLE
Tenant variable dropdown doesn't display certificates/accounts

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5664]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Tenant variable dropdowns for certificate and account variable types display variable names instead of the certificates and accounts themselves. This should instead be populated by the cert/accounts that are scoped to the tenant/environment.

## Steps to reproduce

1. Create a tenant-scoped certificate
2. Create a project variable template with a different name from the certificate
3. View the dropdown list of the tenant's variables

Result: You see the project variable template name instead of the certificate.

### Log exerpt

If you create a project variable that points to the cert and point the tenant to it and deploy, you're greeted with the following message

`Could not find certificate with ID ‘xxx’, which is the value of variable…`

## Affected versions

Reproduced in 2019.5.12.

## Links

Source: https://help.octopus.com/t/certificate-picker-broken/23409/4

**Comment by shaunmarx** [comment]
Release Note: Fix an issue where it was not possible to select a certificate or account when using tenant variables
