### ISSUE TITLE
Deployments blocked by other deployments awaiting manual intervention

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5666]
## Background
Octopus has always taken the approach:
_One deployment per-project per-environment can run at a time (or per-tenant for tenanted projects)_

Except there was a loophole to this: _if a deployment was awaiting manual intervention, we allowed another deployment to start._   

This was a pretty significant caveat.  And one that we didn’t document anywhere.  Some customers complained, arguing this was a bug.  It was easy to sympathize with this; if your deployment is not idempotent, starting another while one was mid-way through could easily cause problems.  

So we implemented a [change](https://github.com/OctopusDeploy/Issues/issues/4564) in 2019.5.8

## The Problem
The change prevents some customers’ deployments from starting.

The scenarios reported (thus far) all come down to variations on the same theme:
_Using manual interventions steps to indicate which releases are eligible to be promoted._

We’ll use an example scenario because it will help us validate the approach:

```
Deployment Process:
Deploy Package and run scripts
Manual Intervention
Send notification

Lifecycle:
QA
Prod

Deployments happen automatically to the QA environment.  Once the QA team has tested the release, they either approve/reject Step 2.
Releases can sit pending approval for days/weeks, or never be approved/rejected.

The team responsible for deploying Prod then can come in and know that any successful (green) deployments to the QA environment are eligible for promotion (or it may happen automatically).
```

So these teams may have 1000’s of releases sitting pending.  Once they have upgraded, no new releases are being deployed.

And just to be clear about the previous behavior, _Step 1 never ran concurrently_.  So it was safe to do things like update load-balancer config, etc.  _Step 3 was implicitly safe to be run concurrently_, as it would potentially run at the same time as the process started concurrently.  

## Proposal
We add a checkbox to the Manual Intervention step, something like `Allow concurrent deployment to start while awaiting intervention`.
If this is set, we revert to the previous behavior.  And we default this to `true`.

### Other options considered
We could implement this as a project setting.  E.g. `Allow concurrent deployments`.
There is a significant problem with this:  _it would not restore the previous behavior_.  The previous behavior was single-threaded until the manual intervention step, then concurrent thereafter.

**Comment by jenseralmeida** [comment]
Is there any ETA for this?

**Comment by MJRichardson** [comment]
@jenseralmeida we have a fix ready.  This will ship as a patch on Monday.
We do apologize.

**Comment by MJRichardson** [comment]
Release note: Deployments awaiting manual intervention will no longer block other deployments the environment by default.  This behavior can now be controlled by a switch on the manual intervention step.
