### ISSUE TITLE
Tenant-scoped permissions breaks ability to select environment on deployment page

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5669]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a user has adequate permissions to deploy a project, but their permissions are scoped to any tenants, they're unable to select an environment in the dropdown on the deploy release page.

## What I expected to happen

The environments the user is allowed to deploy to should still be displayed here, and then only the tenants they're scoped to should display in the tenants dropdown.

## Steps to reproduce

1. Create a user with deployment permission and scope them to a tenant
2. Try to deploy a release with this user
3. See no environments listed in the dropdown

### Screen capture

![no_results_found_environments](https://user-images.githubusercontent.com/20388190/60637144-98d84180-9e5c-11e9-8a99-540fc1aa9578.png)

## Affected versions

Replicated in 2019.5.10 & 2019.5.12

**Octopus Server:** 

## Workarounds

This user whose permissions are currently scoped to tenants can still trigger a deployment via Octo.exe with their API key.
`octo.exe deploy-release --project VALUE --version VALUE --deployto EnvName --tenant TenantName --server OctoURL --apikey API-XXX`

## Links

Sources: https://secure.helpscout.net/conversation/892324387/46586?folderId=954335 (private link)
https://help.octopus.com/t/teams-with-tenanted-user-roles-cannot-deploy-to-the-associated-environment/23445

**Comment by KennethBates** [comment]
Also reported in 2019.6.0 LTS

**Comment by TomPeters** [comment]
Release Note: Fixed an issue where the UI would prevent you from selecting an environment to deploy to if your `DeploymentCreate` permissions were scoped to tenants.
