### ISSUE TITLE
Run Azure Powershell script account error

### ISSUE THREAD

**Issue by hullscotty1986** [OctopusDeploy/Issues#5672]
When creating a step based on a azure powershell step template you get the following error:
"There was a problem with your request.
Couldn't find an account with the Id AzureAccount. Perhaps the account has been deleted? Either select another account, or create a new account and select it.
 Once you have corrected these problems you can try again.
 If the problem is related to a variable you will need to update the variables for this release or recreate the release for the changes to take effect.
 If the problem is related to the deployment process you will need to create a new release for the changes to take effect."

To reproduce:

Create an azure powershell step template. 
Create a paramater with control type Azure Account
Bind the Account in the "Step" tab to the paramater
Create a Azure Account variable in a variable set and assign it an azure account
Go to a project and include the variable set
In the process add a step of the template created earlier
Set the paramamter to the account selected in the variable set
Create a release
Try deploy the release - you will get the error above

Tried on version: 2019.5.7

**Comment by droyad** [comment]
Hi @hullscotty1986 ,

Please contact our [support team](https://octopus.com/support) directly as they will be able to diagnose and work through the problem with you. Please include screenshots, a [raw deployment log](https://octopus.com/docs/support/get-the-raw-output-from-a-task) with [debug variables](https://octopus.com/docs/support/debug-problems-with-octopus-variables#DebugproblemswithOctopusvariables-Writethevariablestothedeploymentlog) and if possible and export of the minimum deployment process (from the overflow menu) required to reproduce the problem.

**Comment by hullscotty1986** [comment]
Hi Robert,

I reported it on the forums: https://help.octopus.com/t/run-azure-powershell-script-account/23381
but have gotten no response for a week.

Scott
