### ISSUE TITLE
All the queued server tasks are displayed when deploying for a project with a pending manual intervention task. 

### ISSUE THREAD

**Issue by mudra-octopus** [OctopusDeploy/Issues#5677]
Related to: https://github.com/OctopusDeploy/OctopusDeploy/pull/4038

When there are pending tasks, it is not very clear to figure out which tasks to address in order to proceed with the current deployment. When there are any queued deployments for a project, it displays a list of all the queued tasks on the server rather than pointing pending tasks for that project. 

Clicking on the task links do not take to a page where we can cancel/proceed to pending tasks.

There is information about existing pending tasks while changing the values of the `Blocks deployment` checkbox. 

## Steps to reproduce

- Have a few projects with pending manual intervention steps. 
- Create a new project with a manual intervention step and select `Prevent other deployments while awaiting intervention`
- Deploy a release. Let it wait for manual intervention. 
- Now edit the step and set *Block Deployments* to `Allow another deployment to begin while awaiting intervention`. 
- Create another release & deploy.
- At this point, all the queued tasks from all the projects are displayed. 

![image](https://user-images.githubusercontent.com/48192575/60780309-457a3200-a181-11e9-879e-842d4137dd40.png)

# Issue 1:

1. When we deploy 0.0.2, it is queued behind 0.0.1 ONLY, but we are still showing the previous information - all tasks waiting in the queue.
![image](https://user-images.githubusercontent.com/48192575/60782981-f5549d00-a18b-11e9-85fe-9421615df234.png)

# Issue 2: 
On clicking the waiting tasks, it navigates to task summary page. It just says the task has not started yet. There is nothing that can be done to trigger this task. 

![2019-07-08_11-43-00 (1)](https://user-images.githubusercontent.com/48192575/60780400-a30e7e80-a181-11e9-9422-22b0938f169a.gif)

There is nothing that can be done here to trigger these tasks again. 

## Suggestion:
Instead of navigating to the task summary page, maybe navigate to its actionable page like 
![image](https://user-images.githubusercontent.com/48192575/60780778-211f5500-a183-11e9-8b56-d285bfa5a89d.png)

# Issue 3: 
There is no information while changing the toggle value that there are any pending tasks for this (project-environment-tenant)

![image](https://user-images.githubusercontent.com/48192575/60780927-b1f63080-a183-11e9-81a2-c499add72570.png)

It will be helpful to have a link/dialog box that will navigate to pending tasks before changing the value for *block deployments*.

**Comment by droyad** [comment]
I would like to delay this until the planned task queue revamp

**Comment by veochen-octopus** [comment]
Closing this one. 

We've updated this page to show accurate information. At the time of writing, this change is still rolling out. But issues 1 & 2 should already be resolved. Issue 3 should be less of an issue now that the page is accurate. Feel free to create a separate ticket if it's still a problem.
