### ISSUE TITLE
Upgrade to 2019.7.0 breaking PS Version lookup. 

### ISSUE THREAD

**Issue by DerekCampbellOctopus** [OctopusDeploy/Issues#5683]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x]  I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x]  I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

After upgrading tp 2019.7.0 from a 2019.5.12, the server fails to start with the below error. Only tested on Server 2016. 

![image](https://user-images.githubusercontent.com/42529489/60882759-740b1200-a240-11e9-88aa-57dd9b33d556.png)

## What I expected to happen

I would expect it to continue with the upgrade. 

## Steps to reproduce

1. Download 2019.7.0 from website. 
2. Run upgrade
3. When about to start upgrade it fails with the error message. 
4. Check PS version and can see it's installed. 

### Screen capture

![image](https://user-images.githubusercontent.com/42529489/60882878-aae12800-a240-11e9-9dce-c52b78678093.png)

### Log exerpt

```
Insert your log exerpt here.
```

## Affected versions

**Octopus Server:2019.7.0

## Workarounds

- Install the 4.7.2 .Net Framework - https://dotnet.microsoft.com/download/dotnet-framework/net472
- Install the KB4041085, KB4049017, or KB4499408 hotfixes from Microsoft.

## Links

https://secure.helpscout.net/conversation/898699238/46975?folderId=557077

**Comment by whereisaaron** [comment]
Ref: https://help.octopus.com/t/octopus-manager-wont-start-after-2019-7-0-octopus-upgrade/23472

**Comment by droyad** [comment]
This was fixed by #5684 by requiring 4.7.2 to be installed
