### ISSUE TITLE
Worker pool selection reset to default when changing execution location

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5691]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The non-default worker pool selected on a step is reset to the default worker pool when switching the `Execution Location`.

## What I expected to happen

The non-default worker pool selected should be retained when switching the `Execution Location` option.

## Steps to reproduce

1. Set `Execution Location` on a step to either `Run once on a worker` or `Run on a worker on behalf of each deployment target`
2. Change worker pool selection to a non-default pool
3. Change `Execution Location` to the other option

Result: Worker pool selection resets to the default worker pool

### Screen capture

![worker_pool_reset](https://user-images.githubusercontent.com/20388190/61015669-f2e28500-a3cf-11e9-9160-fd7b1e05315c.gif)

## Affected versions

Reproduced in 2019.6.3

**Octopus Server:** 

## Links

Source: https://help.octopus.com/t/worker-pool-config-glitch/23496

**Comment by shaunmarx** [comment]
Release Note: Fixed an issue where worker pool selection reset to default when changing execution location
