### ISSUE TITLE
Certificate API is slow

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#5693]
# The bug

The periodic certificate expiry check is slower than it needs to be, it decrypts the certificate only to get the expiry time. For an instance with 1000 certificates, it takes ~18s to validate the certificates. We should not have to decrypt the certificate to do this, we could also validate the certificates in parallel.

Trace:
![image](https://user-images.githubusercontent.com/2888279/61033396-c26a0d80-a406-11e9-9db0-1531e3ff1460.png)

## Affected versions

All current versions

**Comment by droyad** [comment]
We'd have to be very careful if we did parallel, many bits of our request pipeline are not threadsafe

**Comment by KennethBates** [comment]
Another report (private link) https://secure.helpscout.net/conversation/934768744/49010/

**Comment by droyad** [comment]
This performance problem also exists on the API. [This](https://github.com/OctopusDeploy/OctopusDeploy/blob/688f5f33c9975c2bb6984b39483201eaaf552abb/source/Octopus.Server/Web/Mapping/ResourceMappings.cs#L596) is called for every certificate and takes about 6ms per certificate (which is a lot when there are 7000+ certs).

![image](https://user-images.githubusercontent.com/1687639/109092923-9205ed00-776b-11eb-8b23-9decc837af84.png)

**Comment by droyad** [comment]
We should consider putting all those properties onto the document so we don't need to call `CertificateEmbeddedData()`

**Comment by YuKitsune** [comment]
Release Note: Improved performance of Certificate endpoints

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4974 |
| 2021.1 | 2021.1.7089 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4974 |
| 2021.1 | 2021.1.7089 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | -all releases- |
