### ISSUE TITLE
Healthchecks on Linux targets require bash shell

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#5695]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

We should try to be shell agnostic at the early stages of machine healthchecks.
Currently we do require `/bin/bash`
And the error the users get is quite difficult to diagnose, "Ambiguous output redirect."

## What I expected to happen

To be POSIX compliant

## Steps to reproduce

Create a Linux target that uses an account that does not have `/bin/bash` shell
Run a health check 

### Log exerpt

```
15:36:09 Verbose | Performing health check on machine
15:36:09 Verbose | Establishing SSH connection…
15:36:09 Verbose | SSH connection established
15:36:09 Error | Ambiguous output redirect.
15:36:09 Verbose | SSH connection disposed.
15:36:09 Verbose | Exit code: 1
15:36:09 Fatal | The remote script failed with exit code 1
15:36:09 Verbose | The remote script failed with exit code 1
| Octopus.Server.Orchestration.Targets.Tasks.ActionHandlerFailedException: The remote script failed with exit code 1
| at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.SuccessArbitrator.ThrowIfNotSuccessfull(IActionHandlerResult result)
| at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.AdHocActionDispatcher.Dispatch(Machine machine, ActionHandlerInvocation actionHandler, VariableCollection variables)
| at Octopus.Server.Orchestration.ServerTasks.HealthCheck.Controllers.SshMachineHealthController.CheckMachineHealth(Machine machine)
```

## Affected versions

**Octopus Server:**  2019.6.3

## Workarounds

Ensure ssh account has `/bin/bash` shell

## Links

https://help.octopus.com/t/ambiguous-output-redirect/23502
https://github.com/OctopusDeploy/OctopusDeploy/blob/2d82a78926e2fb8c01732c6c85e7e54bd32c7c94/source/Octopus.Server/Orchestration/ServerTasks/HealthCheck/Controllers/SshMachineHealthController.cs#L72

**Comment by zentron** [comment]
The SSH health checks did operate as "raw" commands originally, but appear to have been introduced as "script" commands (which then requires getting invoked by bash). The fix may be as simple as changing the command type to raw, or it may be more involved.

**Comment by droyad** [comment]
It looks like it was fixed in July 2019 and this issues shoud have been closed. 
However a [customer](https://octopus.zendesk.com/agent/tickets/80929) reports that they have run into it on `2021.2.7462` after upgrading from 3.14. We'll look into whether we regressed. No other reports at the moment.

**Comment by droyad** [comment]
> It looks like it was fixed in July 2019 and this issues shoud have been closed.
Upon looking into this further, the solution is to use connection only health checks. This is still the supported resolution to this problem.

I looked back at `3.16.1` and health checks did work if the default shell wasn't bash, but bash had to be available.
Sometime between `2019.1.11` and `2020.1.22` this stopped working. Seeing this has been this way for 2 years, and the connectivity only health check is an acceptable work around, I'm closing this.
