### ISSUE TITLE
Show discrete channel releases on main dashboard

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5721]
## Problem 

When the `Discrete Channel Releases` option is selected on a project, releases are shown per channel on the project dashboard:

![image](https://user-images.githubusercontent.com/113759/61675706-c23e0c00-ad3c-11e9-9fee-6c97ba605991.png)

========

![image](https://user-images.githubusercontent.com/113759/61675771-003b3000-ad3d-11e9-854f-ae74c36702f7.png)

But on the global dashboard, these are collapsed down to a single release per environment:

![image](https://user-images.githubusercontent.com/113759/61675863-485a5280-ad3d-11e9-9768-580efcbb7cfc.png)

## Solution

For projects with `Discrete Channel Releases` enabled, display a row per channel on the main dashboard.  This will display the latest release in each environment _per channel_.

**Comment by zentron** [comment]
Item referenced on larger dashboard ticket to be reviewed as part of that work
