### ISSUE TITLE
Release_LatestByProjectChannel view is slow (especially in Azure SQL)

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#5722]
# The bug

Octopus calls the **Release_LatestByProjectChannel** view to get the latest release for each project/channel combination. This query isn't using the right index and ends up doing a table scan. In Azure SQL the performance impact is _very_ noticeable.

The slow/current query:
exec sp_executesql N’SELECT * FROM dbo.[Release_LatestByProjectChannel] WHERE ([ProjectId] = @projectid) ORDER BY [Id]’,N’@projectid nvarchar(12)’,@projectid=N’Projects-1’

Adding OPTION (RECOMPILE) in SQL server:
exec sp_executesql N’SELECT * FROM dbo.[Release_LatestByProjectChannel] WHERE ([ProjectId] = @projectid) ORDER BY [Id] **OPTION (RECOMPILE)** ‘,N’@projectid nvarchar(12)’,@projectid=N’Projects-1’

![image](https://user-images.githubusercontent.com/2888279/61681944-f290a500-ad52-11e9-8749-a110cd8bd13b.png)

## What I expected to happen

We should see if there's a way to make SQL server use the right index without having to manually specify the RECOMPILE hint.

## Workaround

Create a plan guide which adds the `OPTION (RECOMPILE)` query hint for this query. For more information on how to configure this, see https://docs.microsoft.com/en-us/sql/relational-databases/performance/plan-guides?view=sql-server-2017#sql-plan-guide

## Links

https://help.octopus.com/t/slow-performance-with-release-latestbyprojectchannel/23543

**Comment by flin-8** [comment]
Another option is to change the query we run so we filter on **ProjectId** earlier, this will involve a new stored procedure or running SQL from Octopus Server

**Comment by NickJosevski** [comment]
Release Notes: Fix for slow performing release and deployment queries
