### ISSUE TITLE
IIS step with IP address bindings failing to find SITE object with identifier

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#5745]
# The bug

With the `Deploy to IIS` step, if you have an IP address specified in your IIS binding, the deployment fails with the error below. If you update the binding to use the 'All Unassigned' option, the deployment succeeds. 

## What I expected to happen

Our step should work when you have IP address bindings.

### Screen capture

![image001](https://user-images.githubusercontent.com/819605/62104066-cb514f00-b2e1-11e9-98e4-29795098975a.png)

### Log exerpt

```
15:04:22   Info     |       ERROR ( message:Cannot find SITE object with identifier "https://MY_IIS_SITE". )
```

## Affected versions

**Octopus Server:** 

2018.10.5 +

## Workarounds

Set your site bindings to `All Unassigned` if possible.

## Links

https://secure.helpscout.net/conversation/888243003/46396

**Comment by matt-richardson** [comment]
Closing - turns out this issue was inside the customers script module.
