### ISSUE TITLE
NullReferenceException in AutomaticReleaseCreationReleaseCreator.CollectCreationDataIfProjectMatchesThePackage(Project project)

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#5748]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [ ] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

While investigating an issue for a [support case](https://secure.helpscout.net/conversation/882811030/46146/) I noticed the following exception in the logs:
```
2019-07-29 04:42:15.6220   8116    475 ERROR  Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Octopus.Server.Communications.Packages.AutomaticReleaseCreationReleaseCreator.<>c__DisplayClass13_1.<CollectCreationDataIfProjectMatchesThePackage>b__0(DeploymentAction a)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Communications.Packages.AutomaticReleaseCreationReleaseCreator.CollectCreationDataIfProjectMatchesThePackage(Project project)
```

## What I expected to happen

I looked at the [code](https://github.com/OctopusDeploy/OctopusDeploy/blob/a63bc5ce99148373594071780af4345772b2b092/source/Octopus.Server/Communications/Packages/AutomaticReleaseCreationReleaseCreator.cs#L99) and it is possible we have a null check missing, but then I saw the catch block in https://github.com/OctopusDeploy/OctopusDeploy/blob/a63bc5ce99148373594071780af4345772b2b092/source/Octopus.Server/Communications/Packages/AutomaticReleaseCreationReleaseCreator.cs#L129-L135, I honestly not sure why we adding the projectid to the exception data?

## Affected versions

**Octopus Server:** v2019.5.12

## Workarounds

None

## Links

https://secure.helpscout.net/conversation/882811030/46146/

**Comment by droyad** [comment]
The extra data is not being printed in the exception, we should fix this as well

**Comment by tmbam** [comment]
Another Customer reported seeing this error in their diagnostic logs. https://secure.helpscout.net/conversation/1107778935/58775?folderId=2845830

**Comment by droyad** [comment]
This has not come up again recently
