### ISSUE TITLE
Tenant Tag scoping is broken for Azure Subscription

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#5757]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When scoping an Azure account to both Tenant and Tenant Tag, creating a deployment to Tenants under the tag, or the tag itself will fail with the following error:

![error](https://user-images.githubusercontent.com/18252832/62431107-f7e4eb00-b767-11e9-939a-4336bf9bee23.PNG)

## What I expected to happen

If you scope an account to a Tenant + Tenant Tag, you should be able to deploy via either the Tenant, Tenant Tag, or Tenants under the Tenant Tag.

## Steps to reproduce

1. Create `Tenant-A` & `Tenant-B`
2. Provide a `Tenant Tag` for `Tenant-B`
3. Scope an Azure account to `Tenant-A` & `Tenant Tag` used for `Tenant-B`
4. Create a Project Variable Template for an Azure Account
5. Set the value in the Tenant to the above Tenant scoped account.
6. Create Release and deploy to the `Tenant Tag` or `Tenant-B` which is available due to the tag.
7. See error.

## Affected versions

Tested on `2019.7.4`

## Workarounds

A workaround would be to avoid using Tenant tags for the scoping of the Azure account. Until this is resolved, directly provide the Tenant under scoping if you need to scope this account.

## Links

https://help.octopus.com/t/account-linking-to-tenant-fails/23604/5
https://secure.helpscout.net/conversation/917500292/47974?folderId=557080

**Comment by octokhor** [comment]
Issue from 3 years ago and no further reports
