### ISSUE TITLE
Proxy configuration log noise during tentacle upgrades

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#5784]
# The bug

When automatically upgrading tentacles, `information` level logs concerned with setting proxy values can be repeated in the UI which is noisy. The repetition is caused when subsequent upgrade retries occur.

## What I expected to happen

These kinds of logs should be written at `verbose` level (or removed) to keep them out of the standard task log UX.

### Screen capture
![image](https://user-images.githubusercontent.com/579657/63247457-3f10c700-c2a4-11e9-8296-a88a14a734f7.png)

## Affected versions
**Calamari: 4.1.8+** 

## Workarounds

These logs are safe to ignore, and should only be visible if either the default or system proxy is being used.

## Links

[Internal issue](https://secure.helpscout.net/conversation/930938286/48796?folderId=1422805)

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

**Comment by flin-8** [comment]
The log message have been demoted to VERBOSE level

**Comment by flin-8** [comment]
Release Note: Demote logging level for "Setting Proxy Environment Variables" to VERBOSE
