### ISSUE TITLE
Cannot delete projects and spaces that have multiple consecutive spaces

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#5788]
When deleting spaces and projects, the user needs to enter the name of the project/space. We render the name, but consecutive spaces are suppressed because HTML is HTML.

## Projects:

given this project name:
![image](https://user-images.githubusercontent.com/373389/63404866-23362e00-c428-11e9-8c25-1ebb29c7ec44.png)

![image](https://user-images.githubusercontent.com/373389/63404817-06015f80-c428-11e9-8a59-a91375174350.png)

typing in what appears to be the correct project name doesn't work - the button doesn't enable unless the exact spaces are entered:

![image](https://user-images.githubusercontent.com/373389/63404838-0f8ac780-c428-11e9-8232-87fb90d46bdc.png)

## Spaces:

![image](https://user-images.githubusercontent.com/373389/63405191-4b725c80-c429-11e9-80fc-594ba13df910.png)

typing what it looks like you should type, button doesn't enable:

![image](https://user-images.githubusercontent.com/373389/63405201-5200d400-c429-11e9-9d42-ba62997ca559.png)

**Comment by matt-richardson** [comment]
Release Notes: Consecutive spaces in Projects and Spaces are now ignored during the "type the name to confirm" delete validation
