### ISSUE TITLE
Projects list does not initially populate in v4 of ADO extension

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/Issues#5794]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

For the Create Release Task in Azure DevOps, the Projects list does not populate after selecting the Octopus Deploy connection.  The Spaces list populates correctly, however, it looks like the population of the Projects list is triggered off a Change event on the Space list, projects appear once the value has been changed.

When adding the step to the Pipeline, I noted that the initial value of Space is Default instead of blank like the other fields, even before the Octopus Deploy connection is selected.

## What I expected to happen

The initial value of the Space field should be blank.  After selecting the Octopus Deploy connection, the Space list should populate with the available spaces that API Key has access to and the Project list should populate with a list of projects that the API Key has access to that is in the first Space in the list.

## Steps to reproduce

1. Add a Create Release step to an ADO pipeline
2. Note the Space field has an initial value of Default even before Octopus Server value has been selected
3. Select a value from the Octopus Server drop-down
4. Click on Project drop-down, should see No results found

Workaround
1. Add a Create Release step to an ADO pipeline
2. Note the Space field has an initial value of Default even before Octopus Server value has been selected
3. Select a value from the Octopus Server drop-down
4. Click on the Space drop-down, choose another space
5. Click on Project drop-down, projects listed

### Screen capture

![image](https://user-images.githubusercontent.com/5552453/63472669-b28f1180-c427-11e9-9093-f466ebc67d46.png)

After workaround

![image](https://user-images.githubusercontent.com/5552453/63472713-d4889400-c427-11e9-9fb7-060a40ec38e4.png)

## Affected versions

Version 4 of the ADO extension

**Octopus Server:** 

## Workarounds

If you change the selected value of Space, the Project drop-down is populated with the list of projects of the space.  If you change the Space back to Default, the Project drop-down will be populated with projects from the Default space.

This workaround only works if you have multiple Spaces to choose from.  Selecting the Default space when clicking on the drop-down does not trigger the event and the Projects are not loaded.

**Comment by thedewi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Projects list does not initially populate in v4 of ADO extension](https://trello.com/c/hjA1dQ6Z/1344-projects-list-does-not-initially-populate-in-v4-of-ado-extension)

**Comment by twerthi** [comment]
Issue resolved, thank you :)
