### ISSUE TITLE
UI add a side-by-side step-editing experience and filters

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#5804]
# Background

## Side-by-side step-editing
We want to refactor the deployment process list and editing screens so customers can see and interact with their deployment process list while editing/adding new steps. The v4 re-design project always intended to include a side-by-side step-editing experience, but due to time constraints this design was never actioned.

## Introducing Process Filtering (and Advanced Filtering)
This issue takes the opportunity to add simple and advanced filters to the process list (and sidebar) so customers can find what they're looking for quickly, with filters persisted while in the given project for ease-of-use. The aim being to improve the quality of life for users only interested in a given channel or environment.

# Results

![screencapture-localhost-5000-octopus-html-2019-07-16-17_01_37](https://user-images.githubusercontent.com/819605/61272868-78f53600-a7eb-11e9-83fd-f284e65e5923.png)

![screencapture-localhost-5000-octopus-html-2019-07-16-17_01_53](https://user-images.githubusercontent.com/819605/61272856-75fa4580-a7eb-11e9-9502-c74de2da8a94.png)

# Known limitations

## User experience

- You can still only edit one step at a time. While this may seem frustrating, this approach does have its own set of benefits and avoids a heap of edge cases that we're not ready to approach at this point in time. This could be considered for a phase 2.
- You cannot use the sidebar overflow menu for a step you are currently viewing/editing (we chose this approach to avoid a myriad of potential edge-cases in this first phase (such as things getting out of sync between the sidebar and the step you're viewing/part-way-through-editing).  We do intend to try and address this in the future, but that is very much a phase 2 concern).
- Advanced filters do not update the query string (the complexity of maintaining your advanced filters while clicking between various steps and various menus to get back to your main deployment process made this complicated, so we chose to avoid it for now).

**Comment by thebigmoosey** [comment]
Release Note: UI adding a side-by-side step-editing experience and filters

**Comment by zapr-16** [comment]
After 2019.9.1 LTS I see that the side by side is working but I get a pretty ugly overlapping of the step names onto the right side view, is this expected? 

![image](https://user-images.githubusercontent.com/16386389/66701918-fb50a180-ecd7-11e9-949a-585ef178f860.png)
