### ISSUE TITLE
Support ARC on Deploy a Release steps

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#5807]
I have a project that deploys three other projects using Deploy a Release.

![image](https://user-images.githubusercontent.com/1571799/63699640-dca95080-c7e6-11e9-884f-cd602131fb1e.png)

I would like Octopus to automatically create a release of my parent project when a release is created in a referenced project.

**Comment by octokhor** [comment]
This is better placed in a pitch or ideas doc. Also this is 3 years ago - closing this now.
