### ISSUE TITLE
Octo.exe not parsing --package=StepName:PackageName:Version command correctly

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#5821]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Octo.exe supports a --package switch which lets you specify an exact package and version by step. Currently when supplying all three options (Step Name, PackageName and Version) it ignores the version supplied and selects latest

## What I expected to happen

It should respect all three provided options and select the version sepecified

## Steps to reproduce

1. Create a project in Octopus "OctoReleaseTest"
2. Create a script step (`Import_Common_Scripts`) with an attached package (`lpf.Octopus.Scripts.AWS` in this case)
3. Run the following:
```c:\OctopusTools>octo create-release --project="OctoCreateRelease" --releaseNumber="0.0.1-b00032" --channel="" --server=http://octopus.local/ --apiKey=API-[API-KEY] --enableServiceMessages --deployTo="test" --progress=False --package=Import_common_scripts:lpf.Octopus.Scripts.Aws:1.0.0```
4. Note that it ignores the package version and chooses "latest"
```
The package version for some steps was not specified. Going to try and resolve those automatically...
Finding latest package for step: Import_common_scripts
Selected 'lpf.Octopus.Scripts.Aws' version '1.0.1' for 'Import_common_scripts'
```

### Screen capture

<img width="662" alt="Annotation 2019-08-30 130059" src="https://user-images.githubusercontent.com/29847178/63990145-43e83d00-cb26-11e9-8fdc-f770d879626b.png">
## Affected versions

**Octopus Server:** 

## Workarounds

Specifying either only two of the three options works correctly (i.e. StepName:Version or PackageName:Version).

For example:
```octo create-release --project=“OctoCreateRelease” --releaseNumber=“0.0.1-b00033" --channel=“” --server=http://octopus.local/ --apiKey=API-[API-KEY] --enableServiceMessages --deployTo=“test” --progress=False --package=lpf.Octopus.Scripts.Aws:1.0.0```

Produces the correct result:

<img width="661" alt="Annotation 2019-08-30 130514" src="https://user-images.githubusercontent.com/29847178/63990301-d4268200-cb26-11e9-9f53-1e3955877827.png">

**Comment by slewis74** [comment]
Another report, https://help.octopus.com/t/octo-create-release-fails-to-find-package-version-for-a-script-step/23926

We've done some further investigation and understand now why this is happening. The code is doing something that is technically correct, according to the way we designed the pattern matching to work. But this isn't necessarily what you would imply about how it would work from reading our documentation, and leads to a poor/confusing user experience.

The crux at the moment is that when you specify only step or package name the code isn't sure which package reference name you mean for the version, and so assumes blank for backward compatibility. To the code a blank also means "Default package", not all packages, so when there is a package reference name on the step it doesn't line them up. 

We're looking at what we can do to make this more intuitive. Changing it to assume all packages (i.e. wildcard) has it's pitfalls too. If you say `--package Step1:1.0.0` and then also say `--package Step1:PackageA:1.0.1` what should we do? Expectation would probably be that "PackageA is 1.0.1 and all other packages on Step1 are 1.0.0", but we don't have support for that at the moment either.
