### ISSUE TITLE
Create Release Button missing on Overview Page for Non-Admins

### ISSUE THREAD

**Issue by tmbam** [OctopusDeploy/Issues#5823]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Non-Admins, with "Create Release" permissions, do not see the "Create Release" button on the "Overview Page", but do see the "Release Button" on the "Releases" screen. 

## What I expected to happen
Users with "Create Release" permissions should see the "Release Button" on the overview page

Release button should be visable on Overview page.
## Steps to reproduce

1. Setup user with Create Release permissions
2. Access project Overiew page. Should be no release button.
3. Go to Rleases.  Should see Release button. 
4. Should see Release button. 

### Screen capture

![64042592-062fe800-cb17-11e9-9567-38f9071f0cb7](https://user-images.githubusercontent.com/28936678/64045546-70985680-cb1e-11e9-975b-22832f0051d0.png)
![64044881-c8ce5900-cb1c-11e9-942c-debc18a82ee3](https://user-images.githubusercontent.com/28936678/64045769-fe744180-cb1e-11e9-9454-4f5b0e35c5a5.png)

## Affected versions

v2019.7.13

## Workarounds
Create Release from "Releases" page.

## Links

https://secure.helpscout.net/conversation/939803513/49194?folderId=2845830

**Comment by tmbam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Release Button Missing](https://trello.com/c/R3Eo87l2/1383-create-release-button-missing)

**Comment by tmbam** [comment]
We have another report https://help.octopus.com/t/missing-create-release-button-on-project-dashboard/23887

**Comment by droyad** [comment]
This was fixed as a side effect of http://github.com/OctopusDeploy/OctopusDeploy/pull/4384

**Comment by droyad** [comment]
This only affected users who were scoped to a project or project group
