### ISSUE TITLE
UI add ability to clone the step you're currently viewing from the sidebar's overflow menu

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#5829]
# The enhancement

Add the ability to clone the step you're currently viewing using the side-by-side step-editor's overflow menu.

### Background
When we shipped [this feature](https://github.com/OctopusDeploy/Issues/issues/5804) we listed a bunch of known limitations, but someone on the [community slack](https://octopususergroup.slack.com/archives/CC393GZFB/p1567512865003600) correctly pointed out that the ability to clone a step using this side menu would be super useful and make you more productive when editing.

We considered this, and it's a good point, because cloning wouldn't impact the current step you're viewing/editing, so it should be safe to add that as the only side-menu overflow item for the step you're currently viewing.

## Links

https://octopususergroup.slack.com/archives/CC393GZFB/p1567512865003600

**Comment by kengel100** [comment]
This enhancement has since been implemented and is working in the latest versions of Octopus server.
