### ISSUE TITLE
Wrong step is deleted in deployment process

### ISSUE THREAD

**Issue by ankithkonda** [OctopusDeploy/Issues#5840]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [ ] ~~I have linked the original source of this report~~
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When you try to delete a parent step from the detailed view, the action deletes the next unrelated step in the process.

## What I expected to happen

When I delete a parent step, if the child steps can be deleted (not assigned to versioning strategy) then the parent and children should be deleted and i should be redirected to the edit page of the next unrelated step in the process 

## Steps to reproduce

1. Create a project
2. Add a step, and add a child step (to create a parent-child process)
3. click on the parent to go into the edit page
4. delete the parent step

### Screen capture

![2019-09-06_11-35-53 (1)](https://user-images.githubusercontent.com/1918487/64518021-bf22cd80-d334-11e9-975a-9415a063124e.gif)

### Log exerpt

N/A

## Affected versions

**Octopus Server:** 2018.8.3

## Workarounds

delete all child steps until you are left with only 1 child, this will remove the parent step, now you can delete the last child

## Links

N/A

**Comment by ThirtyThirds** [comment]
Hello, this bug was not present in the previous version we had 2019.6.5 LTS but since we updated to 2019.9.10 LTS (latest) this bug appeared for us. 
This is veeeeery annoying for very large project cloning/sorting. 
Did you plan to fix this in a short time? Should we open a case to support for a 4 month old bug?

**Comment by TomPeters** [comment]
Release Note: Fixed a bug where deleting a parent step might delete the wrong step
