### ISSUE TITLE
Dashboard is showing more projects than set in configuration

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#5861]
# The bug

When limiting the amount of projects from `/dashboard/configure`, the dashboard ended up showing a lot more projects than expected.

Similar to https://github.com/OctopusDeploy/Issues/issues/5698 but not identical

## What I expected to happen

The dashboard only shows the amount of projects set in `/dashboard/configure` + any projects with failed deployments.

## Steps to reproduce

1. Create 2 project groups.
2. Create 3 projects in each group.
3. Set the project limit in `/dashboard/configure` to `2`
4. Go back to the dashboard. It will show 2 projects of the first Project Group and the 3 projects of the 2nd Project Group.
5. The message next to the project filter also displays the ground amount of groups.

### Screen capture

(amount of projects doesn't match steps to repro but its good enough to get the idea :) )

9 projects in total
![image](https://user-images.githubusercontent.com/6180562/65187130-9213a080-da41-11e9-9936-2d4032e09d63.png)

Max amount of projects = 3

![image](https://user-images.githubusercontent.com/6180562/65187175-a8b9f780-da41-11e9-9ab7-bb9f2c04f8a2.png)

The dashboard shows 3 projects from the first project group + all the projects from the other groups
![image](https://user-images.githubusercontent.com/6180562/65187287-f0408380-da41-11e9-9c4d-4a34f10a63d7.png)

Also the text next to the filter says `8` projects instead of the `9` that exist
![image](https://user-images.githubusercontent.com/6180562/65187661-c471cd80-da42-11e9-8e43-3aeb2fbabb3c.png)

## Affected versions

2019.8.5 and below.

## Workarounds

None

## Links

https://help.octopus.com/t/dashboard-filtering-doesnt-work-as-expected/23048/23

**Comment by ziaulislamOctopus** [comment]
https://help.octopus.com/t/dashboard-filtering-doesn-t-work-as-expected/24150

Another customer with the issue

**Comment by jjanuszkiewicz** [comment]
@ziaulislamOctopus Hi, this is actually the same customer, you just keep closing our support threads :-(
https://help.octopus.com/t/dashboard-project-filter/22601 - closed
https://help.octopus.com/t/dashboard-filtering-doesnt-work-as-expected/23048 - closed
https://help.octopus.com/t/dashboard-filtering-doesn-t-work-as-expected - the current one

**Comment by slewis74** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard is showing more projects than set in configuration](https://trello.com/c/bRGRI7Kt/1649-dashboard-is-showing-more-projects-than-set-in-configuration)

**Comment by gupta-kartik** [comment]
Release Note: Filtering Dashboard by Max Limit does not add errors or warnings
