### ISSUE TITLE
Tasks report the wrong Calamari architecture

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#5864]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

This task in the image was run from a Windows Server on a Windows hosted worker, but it is reporting a Linux Calamari. Looking at the Calamari files unpacked it appears to be the Windows version.

## What I expected to happen

It should be reporting the correct version for the Worker OS.

### Screen capture

![image](https://user-images.githubusercontent.com/5336529/65371435-f08d8880-dca6-11e9-8460-e2462bc3bf86.png)

## Affected versions

**Octopus Server:** 2019.8.4
**Calamari:** 7.1.7

**Comment by droyad** [comment]
I think this has been fixed as we now pre-detect the OS
