### ISSUE TITLE
Symlinks are not preserved when extracting a TAR

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#5871]
Symlinks were likely not supported until SharpCompress `0.23.0` (https://github.com/adamhathcock/sharpcompress/pull/423). We use `0.15.2` in Calamari and `0.22.0` on the server.

We have been bitten in the past when we changed or updated the compression lib. The PR above also talks about a delegate that needs implementing.

To reproduce deploy [octopus-sample.1.0.0.tar.gz](https://github.com/OctopusDeploy/Issues/files/3649609/octopus-sample.1.0.0.tar.gz) to a linux machine and inspect the extraction directory

Customer Issue: https://secure.helpscout.net/conversation/961621762/50521?folderId=3074962

**Comment by twerthi** [comment]
Customer is asking about status on this issue, has it been placed in the queue?

**Comment by droyad** [comment]
Yes ([internal link](https://trello.com/c/6OLxw6Kz/1523-symlinks-are-not-preserved-when-extracting-a-tar))

**Comment by tw17** [comment]
This Issue has been put back on hold. The update to SharpCompress only provides a delegate for when a symlink is encountered. There currently does not seem to be a straight forward cross platform approach for creating symlinks in netcore
It looks like this is being worked on in netcore and is scheduled for 5.0
https://github.com/dotnet/corefx/issues/29978
