### ISSUE TITLE
Resizing browser window clears form input

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5875]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you're currently filling in some details (for example the create release page), and you resize the browser window small enough and maximize the window again, the page reloads and clears your input.

## Steps to reproduce

1. Make some changes on a form in the web portal without saving
2. Resize the browser window (tested in Chrome and Firefox)
3. Maximize the browser window
4. See the page reload

### Screen capture

![browser_window_resize](https://user-images.githubusercontent.com/20388190/65735075-1e485680-e119-11e9-8da0-969e68237dc5.gif)

## Affected versions

Reproduced in 2019.8.5. Still exists in 2020.2.5.

**Octopus Server:** 

## Links

- https://help.octopus.com/t/resizing-browser-window-refreshes-the-page-entered-data-is-lost/23972
- https://secure.helpscout.net/conversation/1164653052/64569

**Comment by Waldo000000** [comment]
Another report: https://secure.helpscout.net/conversation/1164653052/64569

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resizing browser window clears form input](https://trello.com/c/CbvP9K5e/3281-resizing-browser-window-clears-form-input)

**Comment by mcasperson** [comment]
This bug has been included in a pitch to clean up the process editor at https://docs.google.com/document/d/12HVJLOgKX5VJNEYjDhGbovOxxJAsfQLQcylgF7uG014/edit#.

**Comment by peter-dolkens** [comment]
While you're looking at usability - my team has also raised that hitting `esc` immediately closes the modal windows.

A confirmation of discarded changes would be appreciated here.
