### ISSUE TITLE
Project group & project name boxes in dashboard misaligned in Firefox

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5876]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

In Firefox, the project group and project name fields are misaligned on the dashboard page.

### Screen capture

![image](https://user-images.githubusercontent.com/20388190/65734799-03291700-e118-11e9-816c-c05fc7898726.png)

## Affected versions

Reproduced in 2019.8.5

**Octopus Server:** 

## Links

Source: https://help.octopus.com/t/misaligned-filters-on-dashboard/23974

**Comment by kengel100** [comment]
Confirmed that this has been fixed, using the latest build of Octopus with Firefox.
