### ISSUE TITLE
Allow virtual directory mappings in the IIS feature

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#588]

**Comment by bill-sorensen** [comment]
I agree with @waynebrantley - this is a critical feature that needs to be standard.

**Comment by drusellers** [comment]
Can't this just be a customization of an existing powershell template in the library?

**Comment by memark** [comment]
I agree, this is a very common scenario. The step templates are nice, but it needs to be a core feature.

**Comment by drusellers** [comment]
There are 'detailed' step templates in the octo library that I found to do this that are super easy to use. But I consider the octo library as a core feature and others may not. :(
