### ISSUE TITLE
Run PowerShell Core deployment scripts on all platforms

### ISSUE THREAD

**Issue by gupta-kartik** [OctopusDeploy/Issues#5881]
# The feature

Octopus Deploy will be able to execute scripts using PowerShell Core on both Windows and non-Windows platforms.

## What it actually enables people to do

Currently, some users have to maintain two versions of the same script i.e. usually a `bash` version of their `ps1` scripts for for non-windows targets. This feature enables support for PowerShell across both platforms allows the users to use existing `.ps1` scripts and packages to run across both Windows and non-Windows targets.

Anyone using PowerShell scripts in their deployments can take advantage of enhancements and bug fixes that have been included in PowerShell Core, but not in Windows PowerShell.

## Choosing Windows PowerShell or PowerShell Core on Windows

**Using Configure Features** 
![2019-09-30_16-40-34 (1)](https://user-images.githubusercontent.com/4622084/65855116-af316300-e3a1-11e9-91ec-90bd09a4e8ae.gif)

## What this feature isn't

This feature isn't a deprecation of Windows PowerShell. We will continue to support both editions of PowerShell for Windows. 

## Breaking Changes
Prior to this change, any deployments that include powershell scripts (for example, `Deploy.ps1` files within deployment packages) and were deploying to non-windows targets would have silently been ignoring the `.ps1` files. 

After this change, Octopus will attempt to execute those `.ps1` files on those targets. If PowerShell Core is installed on those targets, then this will may change the behaviour of your deployments. If PowerShell Core is not installed on those targets, then the deployment will fail.

## Details

If Calamari is running on non-Windows environments, PowerShell Scripts (`.ps1` files) can now be executed. They will be run through `pwsh`, which is assumed to be available in the `$PATH` variable for the user running Calamari.

On Windows environments, PowerShell scripts will still be run through Windows Powershell (the desktop, full .NET framework edition of powershell), unless Calamari has been explicitly configured to run the script on PowerShell Core. This is to preserve backwards compatibility.

To configure the edition that Calamari will use on Windows environments, there is a new optional feature that can be included in steps. This allows you to pick the Desktop edition of PowerShell (i.e. "Windows PowerShell") or the Core edition of PowerShell (i.e. PowerShell Core).

All existing Windows PowerShell features are fully supported on PowerShell Core on both Windows and non-Windows targets, with a few exceptions and caveats listed below.

### Proxy
For version 6 of PowerShell Core, it does not appear possible to configure all http traffic to go through the configured proxy server. In particular, using the [HttpClient class](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8) directly requires some manual set up in the powershell scripts in order for its web requests to use the proxy.

To make this set up more convenient, a new `$OctopusProxy` variable has been made available for scripts to use. For consistency, this variable has been made available in all versions and editions of PowerShell, across all platforms.

This extra manual configuration is not required from PowerShell Core version 7 and beyond.

### Multiple versions
**Windows**
Multiple versions of PowerShell Core can be installed side-by-side on Windows. If multiple versions are detected, the latest installed version will be used, even if that version is a pre-release version. By providing the `Octopus.Action.PowerShell.CustomPowerShellVersion` variable, you can customize the version that is used if multiple versions are installed.

**Non-windows**
While multiple versions of PowerShell core can be installed side-by-side on many non-Windows targets this may be difficult to do depending on what OS you are using, and what method you have used to install PowerShell Core. For example, if you have installed PowerShell Core through your OS's package manager, it may only be possible to installed one version at a time.

Due to the large variance in install locations, methods, and versioning schemes, the `Octopus.Action.PowerShell.CustomPowerShellVersion` variable is not supported for non-Windows targets and instead the pwsh executable must be available in the `$PATH` variable for the user running Calamari.

**Comment by TomPeters** [comment]
Release Note: Adds support for PowerShell Core deployment scripts on all platforms
