### ISSUE TITLE
Lack of LibraryVariableSetView blocking project overview screen

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5889]
# The bug

Project Overview on Tenanted projects attempts to determine missing variables for Tenants, the check asserts user must have `LibraryVariableSetView`

## What I expected to happen

It should not be required to view this screen.

## Steps to reproduce

1. Set up a Project with Tenanted deployments
2. With a user lacking `LibraryVariableSetView`
3. Load the project and 💥 

### Screen capture

![image](https://user-images.githubusercontent.com/119096/66182556-ea40d880-e6b8-11e9-98db-4b301d8a331e.png)

### Log exerpt

```
You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: LibraryVariableSetView
```

## Affected versions

**Octopus Server:** 2019.*

## Workarounds

Grant the user `LibraryVariableSetView`

## Links

https://octopususergroup.slack.com/archives/C6UEBB7R9/p1570069092136700

**Comment by NickJosevski** [comment]
Release Note: Project overview screen is no longer dependant on LibraryVariableSetView permission for Tenanted projects.

**Comment by Jorgelig** [comment]
i have 2019.9.8 version

![image](https://user-images.githubusercontent.com/581672/68900283-207e6880-06f9-11ea-922a-9ce0f856c4d7.png)

**Comment by matt-richardson** [comment]
Hi @Jorgelig. Can you please get in touch with our [support team](https://octopus.com/support) with a detailed report? That way this will get to the right people quicker.

**Comment by whereisaaron** [comment]
I already reported to and discussed it in the help forum some time ago. I'll find The reference. This was confirmed as a bug/regression, but this is the only issue I know if for it. I was told it was too be fixed in an upcoming release.
