### ISSUE TITLE
Manual intervention step in child project marks parent project's Deploy a Release step as failed

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5898]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a child project (deployed via a Deploy a Release step in a parent project) has a manual intervention step, it incorrectly marks the parent project's step as a failure.

## What I expected to happen

Step should be considered successful if approving the child deployment.

## Steps to reproduce

1. Add a Manual Intervention step to a child project
2. Add a Deploy a Release step to a parent project to deploy the child
3. Deploy the parent project
4. Approve the intervention in the child

### Screen capture

![manual_intervention_child](https://user-images.githubusercontent.com/20388190/66629935-7d908580-ec46-11e9-9e43-b58d1a893bad.png)

## Affected versions

**Octopus Server:** 2019.8.6

Probably only this version as it seems likely it's a result of this issue: https://github.com/OctopusDeploy/Issues/issues/5797

**EDIT** Still occurring in 2019.13.7

## Workaround

Configuring the parent project for Guided Failure mode in the Project Settings will stop this from returning an error. 

## Links

Source: https://secure.helpscout.net/conversation/978015806/51394?folderId=557077 (private link)
[Private Source](https://secure.helpscout.net/conversation/1014967981/53622?folderId=845288)

**Comment by JscNZ** [comment]
We have the same issue occurring.

**Comment by KennethBates** [comment]
Another source: https://secure.helpscout.net/conversation/1060841400/56030?folderId=954335 (private link)

**Comment by KennethBates** [comment]
When using the workaround to use guided failure on the parent project, approving the manual intervention step in the child project still throws a warning in the parent project, saying `Deployment of release 1.0.0 of project 'Child Project' is paused for manual intervention`.

**Comment by calverp** [comment]
Another report of this issue, still occurring in 2019.12.8. I tested it in 2019.13.7 and it still exists there too.
https://secure.helpscout.net/conversation/1127315762/61297?folderId=557082
(private link)

**Comment by KennethBates** [comment]
Another instance of this popping up: https://secure.helpscout.net/conversation/1143471815/63435/
They're also noticing some strange behavior around the manual intervention box in the parent project - the show/hide details button doesn't do anything.

![show-hide_details](https://user-images.githubusercontent.com/20388190/79932833-bcbf4f00-8491-11ea-907c-c0bbe7be362e.gif)

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Manual intervention step in child project marks parent project's Deploy a Release step as failed](https://trello.com/c/SYYzLNi8/3184-manual-intervention-step-in-child-project-marks-parent-projects-deploy-a-release-step-as-failed)

**Comment by andrewabest** [comment]
Release Note: Fixes an issue with Deploy a Release step where deployment would fail if release contained a Manual Intervention step.
