### ISSUE TITLE
On the project process view, the step list overlaps if the step name has long words

### ISSUE THREAD

**Issue by zapr-16** [OctopusDeploy/Issues#5899]
Related to #5804 

After 2019.9.1 LTS I see that the side by side is working but I get a pretty ugly overlapping of the step names onto the right side view, is this expected?

This is happening on the latest version of Chrome and Firefox

![image](https://user-images.githubusercontent.com/16386389/66701991-ec1e2380-ecd8-11e9-9e73-147ff564d5b7.png)

**Comment by droyad** [comment]
Thanks @zapr-16, I've been able to reproduce it. FYI we usually discourage raising of issues here as we don't monitor this list closely. Best course is to contact us through our support channels.

**Comment by zapr-16** [comment]
ok @droyad sorry about that, should I still contact Octopus support? Is there a way to track the issue after that? (to decide when to upgrade again)

**Comment by droyad** [comment]
@zapr-16 No worries, we've fixed it and will ship it soon
