### ISSUE TITLE
Configuration Variable feature always escapes ampersand

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#5907]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using the Configuration Variable feature and a variable containing an ampersand `&`, Octopus will always escape it. You can not explicitly define `&amp;` to workaround this.

## What I expected to happen

If you can not directly use & in the Configuration Variable, you should at least be able to use `&amp;` currently you can have neither.

## Steps to reproduce

1. create package with an xml config file with appSettings section. (Something we automatically substitute with the feature)
2. create a variable to evaluate against the config file and use an ampersand in the value.
3. Octopus will escape the ampersand.

## Affected versions

Tested on Octopus Server `2019.9.3`

## Workarounds

Use the Substute Variables in Files feature and configure a variable in the configuration file using the Octopus variable syntax. `#{SomeVariable}`

## Links

https://secure.helpscout.net/conversation/976748284/51299?folderId=845288

**Comment by Justin-Walsh** [comment]
This issue is no longer valid. Modern versions of Octopus will all substitute the values as expected. This was likely fixed as part of the Structured Variable Configuration changes in 2020.4

**Comment by twerthi** [comment]
It looks like this may have popped up again in 2022.2.6971 as it's happening for a .NET Configuration Variable setting.

**Comment by mjhilton** [comment]
I've reviewed [the official XML Specification](https://www.w3.org/TR/2008/REC-xml-20081126/), and found the following, in section 2.4:

> The ampersand character (&) and the left angle bracket (<) **must not** appear in their literal form, except when used as markup delimiters, or within a [comment](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-comment), a [processing instruction](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-pi), or a [CDATA section](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-cdsection). If they are needed elsewhere, they *must* be [escaped](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-escape) using either [numeric character references](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-charref) or the strings " &amp; " and " &lt; " respectively.

So when performing an XML replacement on a text node or an attribute, this is correct behaviour. If we directly placed an unescaped ampersand into one of these, we would create an XML document which is not well-formed. It's the responsibility of any reader of the XML file to successfully un-escape the characters in such text nodes.

[Our documentation of the Structured Configuration Variables feature](https://octopus.com/docs/projects/steps/configuration-features/structured-configuration-variables-feature#replacing-content) supports this, though it doesn't explicitly mention the ampersand character - it might be good for us to add that in.

In elements where it's valid to have an unescaped ampersand, such as `CDATA`, Octopus will substitute the value un-escaped as per the spec. I've done up an example with the various different types of elements we can replace, which shows what I believe is correct behaviour across all of them:

Source XML file with various replaceable elements:
<img width="677" alt="Source XML file with various replaceable elements" src="https://user-images.githubusercontent.com/730704/178677185-4874cb92-69e7-408b-a100-9279c321184e.png">

Project Variables to replace various elements of the XML document:
<img width="1226" alt="Project Variables to replace various elements of the XML document" src="https://user-images.githubusercontent.com/730704/178677362-4b7680dd-3e3d-4b14-8e23-bbcfcad94fb2.png">

Resulting replacements:
<img width="1168" alt="Resulting replacements" src="https://user-images.githubusercontent.com/730704/178677428-98c00f86-870e-4dc4-9e81-0a1892e78429.png">

**Comment by mjhilton** [comment]
I've [updated our docs](https://octopus.com/docs/projects/steps/configuration-features/structured-configuration-variables-feature#replacing-content) to be explicit about ampersand replacement, and that it's intended when replacing an XML text element
