### ISSUE TITLE
Kubernetes deployments logs warning for missing kubectl-octo.yml file

### ISSUE THREAD

**Issue by tw17** [OctopusDeploy/Issues#5910]
# The bug

When performing K8s deployments, we always set the `KUBECONFIG` env variable to the path of the kubectl-octo.yml file, however we don't always write this file out, it looks like its only used for K8s deployments that use a Amazon Web Services Account.

The problem is that the latest version of Kubectl checks the `KUBECONFIG` env variable and if the file doesn't exist it logs a warning.

We should only be setting that variable when we actually write the file out

**Comment by PashCracken** [comment]
Any ETA on a fix?

**Comment by matt-richardson** [comment]
This was fixed by https://github.com/OctopusDeploy/Issues/issues/6050, which got shipped with `2019.10.12`.
