### ISSUE TITLE
A variable used in a templated step that evaluates to the name of a variable causes the server to crash

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#5924]
Affected versions: `2019.8.6` and later

Introduced in https://github.com/OctopusDeploy/Issues/issues/5835

###Steps to reproduce:
- Create a step template with a parameter
- Add the template to a project and use `#{MyVar}` as the value
- Add a project variable called `MyVar` with value `MyVar`
- Go to the variable preview

The variable loop does not have to be direct

Cause:
For each of the variables used in a step template, it evaluates that variable (the result) and keeps doing so until it can't find a variable with that result in the variable collection.

e.g. In the above example, it finds the step template parameter, and resolves `#{MyVar}` to `MyVar`. It Then looks in the dictionary to see if a variable with the name `MyVar` exists, if so it will evaluates `#{MyVar}`

The problem occurs here: https://github.com/OctopusDeploy/OctopusDeploy/blob/3b0ea2f4eb5e9bc02bb8422f40fe84e2414d0d6a/source/Octopus.Server/Orchestration/ServerTasks/Deploy/Manifest/DeploymentManifestFactory.cs#L638

### Workaround:
Ensure that variables do not have a value or a value that evaluates to the name of another variable. The easiest way to do that is to download your deployment process as JSON (in the overflow menu of the process page). Open it and look for the `Properties` item under each `Action`. Look for any variable expressions. Then use the `Variables` -> `All` page to figure out whether that variable will resolve to the name of another variable.

Example JSON:
![image](https://user-images.githubusercontent.com/1687639/67256650-9d883a80-f4cb-11e9-94db-7a6b77de798b.png)

And variables:
![image](https://user-images.githubusercontent.com/1687639/67256669-b395fb00-f4cb-11e9-9848-602e7ba4545a.png)

### Reports 
(Private links)
https://secure.helpscout.net/conversation/985522604/51818/
https://secure.helpscout.net/conversation/985706886/51843/
https://secure.helpscout.net/conversation/981437308/51582?folderId=557082 (Rolledback)
https://secure.helpscout.net/conversation/982091660/51619/ (Rolledback)
https://secure.helpscout.net/conversation/985820999/51855?folderId=845288 (diagnostics attached)

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Octopus Server crashing on deploy](https://trello.com/c/79QVKfw0/1621-octopus-server-crashing-on-deploy)

**Comment by droyad** [comment]
Release Note: Fix for StackOverflowException causing Octopus Server to crash

**Comment by droyad** [comment]
@verzada We are planning a feature that will allow us to push notifications to the Web UI. We can use that to notify users of bugs like this.

**Comment by verzada** [comment]
@droyad I updated the https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/13832598-custom-message-alert-for-maintenance-mode with more examples of what I'm looking for.
