### ISSUE TITLE
The create deployment page reports that a recursive loop is detected when there isn't one

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#5927]
This problem occurs if:
- one or more of the deployment processes steps that are based on a library template
- that step uses a variable in the template parameter field 
- There is no variable with that name that is unscoped or only has tenant, environment or step scoping

On the create deployment page, the following error is shown
```
An attempt to parse the variable symbol "MyVar" appears to have resulted in a self referencing loop (MyVar-> MyVar). Ensure that recursive loops do not exist in the variable values.
```

### To Reproduce:
- Create a step template with parameter named `MyParam`
- Add that step to the process
- Fill `#{MyVar}` as the value of the step template
- Add a variable `#{MyVar}` scoped to a `role`

This is perfectly valid and would work during the deployment as it would be resolved via the target's role. However during preview and deployment creation, only a limited scope resolution exists and this variable is undefined.

The variable preview page is blank.

This is related to #5924

### Work Around
Define a default value for the variable without any scope

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Octopus Server crashing on deploy](https://trello.com/c/79QVKfw0/1621-octopus-server-crashing-on-deploy)

**Comment by tw17** [comment]
Release Note: Fix for recursive variable loop when there isn't one
