### ISSUE TITLE
Invalid version in BuildInformation can break deployments

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#5939]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Prior to 2019.10, the `BuildInformation` api (previously known as `PackageMetadata`) would allow a `string` value for the version. This meant that a bad provider could push an invalid semver version. When it came time to deploy, the deployment would read the metadata version, try to parse it as semver, and then fail to deploy.

In 2019.10 a change was made so the version is now stored as an `IVersion`, which means it's no longer possible to push an invalid version through our API. However existing databases will still have this bad data in them.

## What I expected to happen

When creating a release with invalid metadata, the metadata should be ignored, and the release should be created.

## Steps to reproduce

1. Create a project that deploys a package.
2. In the database, create a `BuildInformation` record with the right package name, and an invalid version string.
3. Try to create a release for the project.

## Links

https://help.octopus.com/t/error-message-not-a-valid-version-string-refers-to-strange-version/24136
https://help.octopus.com/t/release-creation-fails-after-upgrade-to-2019-10-1-with-invalid-version-string/24130/4

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release creation fails after upgrade to 2019.10.1 with invalid version string](https://trello.com/c/dtOUa5oU/1628-release-creation-fails-after-upgrade-to-2019101-with-invalid-version-string)

**Comment by distantcam** [comment]
Release Note: Fixed bad data for release versions in package metadata

**Comment by ptrukhman** [comment]
@distantcam any ideas of how to fix it in Octopus Cloud?

**Comment by distantcam** [comment]
@ptrukhman Octopus Cloud is regularly updated with the latest version, so this patch will eventually make it there.

If you need more immediate help I recommend reaching out to our support.
https://octopus.com/support

**Comment by ptrukhman** [comment]
@distantcam already asked on the last week, but still have no a solution. And also i still see v.2019.10.1 in my Octopus Cloud.
