### ISSUE TITLE
Changes to license checks cause high CPU usage

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#5944]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Recent changes to the license checking cause it to load and deserialize the JSON content for all machines in the Machine table. This is happening at startup but also in most API calls, so as soon as the API call rate goes up the CPU usage goes through the roof if there are lots of machines.

Looks to have been introduced as part of the fix for OctopusDeploy/Issues#5704

## What I expected to happen

License check should not be an expensive call.

### Screen capture

![image](https://user-images.githubusercontent.com/4229735/67817902-08082e80-fafb-11e9-9038-ef2859e4e76c.png)

Output of a dotTrace log sent by a customer
![image](https://user-images.githubusercontent.com/4229735/67817914-10606980-fafb-11e9-9619-b6c250d8375e.png)

## Affected versions

**Octopus Server:** 
`2019.7.3`

## Workarounds

None known.

## Links

Internal slack thread https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1572304065116600

**Comment by distantcam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wayfair perf issues](https://trello.com/c/x0PElHDD/1640-wayfair-perf-issues)

**Comment by distantcam** [comment]
Release Note: Changed machine license check to sql column for better performance.
