### ISSUE TITLE
Sensitive project variables cause any matching words to be obscured in variable preview and logs

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#5966]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If the value entered for a sensitive variable matches any part of a non-sensitive variable, this will cause it to become obscured in the variable preview page.
The same will occur in deployment logs if the sensitive variable matches any word in the logs.

## What I expected to happen

Only sensitive variables should be obscured.

## Steps to reproduce

1. Create and save a project variable of type 'Sensitive' with the value 'process'
2. Create and save a project variable of type 'Text' with a value of 'processtest'
3. View variable preview page and and check the text variable, it will display '*******test'
4. Add a script process step with a script of `Write-Output 'process'`
5. Create a release and deploy
6. Check the deployment logs, the output will be obscurred wherever the word 'process' should appear

### Screen capture
![image](https://user-images.githubusercontent.com/20085569/68120033-35d6e400-fefc-11e9-82df-82ff3a8d94fb.png)

![image](https://user-images.githubusercontent.com/20085569/68119989-18a21580-fefc-11e9-97fa-44204cc6487e.png)

## Affected versions

**Octopus Server:** 2019.10.1

## Links

[Issue Reported](https://help.octopus.com/t/censoring-password-in-variables-goes-wrong/24191/3)

**Comment by droyad** [comment]
This is [by design](https://octopus.com/docs/deployment-process/variables/sensitive-variables#Sensitivevariables-LoggingLogging)
