### ISSUE TITLE
Choose file box in Replace Certificate UI does not work

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#5974]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Replacing a certificate in the library is impossible to complete due to the choose file button failing to open the expected dialogue box.

## What I expected to happen

A dialogue box would open allowing me to input the filepath to the new certificate.

## Steps to reproduce

1. Add a certificate to the library
2. Select the certificate
3. Select Replace
4. Click on the Choose File button

## Affected versions

**Octopus Server:** 2019.10.4

## Workarounds

Main workaround would be to use the API to carry out this action.
[Sample Script](https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/Octopus.Client/PowerShell/Certificates/ReplaceCertificate.ps1)

## Links

[Internal Link](https://secure.helpscout.net/conversation/998489195/52711?folderId=3252735)

**Comment by bryanroth** [comment]
Any update on when this might get fixed/merged?

**Comment by andrew-moore-octo** [comment]
Release Note: Fix bug where the file chooser doesn't open when replacing certificates.

**Comment by andrew-moore-octo** [comment]
:wave: @bryanroth This will be fixed in the 2019.10.7 release.
