### ISSUE TITLE
Long list of changes for deployments makes the deployment page unresponsive

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#6013]
# The bug

When a deployment contains a long list of changes, the rendering of this causes the page to become slow or unresponsive.

## What I expected to happen

When there are a lot of changes in a deployment, the page should load and render quickly and initially be responsive. This means that the full changes should not be initially rendered. There should be a mechanism for the user to opt-in to rendering the full list of changes (e.g.  Show More button, or a separate tab).

## Steps to reproduce

Navigate to a deployment that deploys a large number of changes.

### Screen capture

This affects deployments with a large number of deployment notes, which are rendered in the sidebar on this screen:
![image](https://user-images.githubusercontent.com/1892715/69022054-a9e9af80-0a05-11ea-9503-05b980205e99.png)

We previously had this problem on the Create Release page, but have solved this problem there with a Show More button:
![image](https://user-images.githubusercontent.com/1892715/69022069-bb32bc00-0a05-11ea-88d0-522d581d0668.png)

## Affected versions

**Octopus Server:** Up to the version in which this bug has been fixed.

## Workarounds

- Have shorter release notes and changes.
- Deploy frequently to environments in order to reduce the quantity of changes within each deployment
- Do not track changes within octopus

## Links

https://help.octopus.com/t/poor-performance-on-deployments-page-with-a-lot-of-release-deployment-notes/24266

**Comment by andrew-moore-octo** [comment]
Release Note: Show a preview of the release notes on the deployment page with a button to show more.
