### ISSUE TITLE
Json variable replacement doesn't work if the variable starts with "Octopus"

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#6029]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a Json config file contains a structure like the following

```
{
    "octopus": {
        "apikey": "API-????"
    }
}
```
And you have a variable with the name `octopus:apikey` in the project and the Json variable substitution feature enabled, the value doesn't get replaced in the file.

## What I expected to happen

The variable should get replaced.

Investigation has lead us to https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari.Shared/Integration/JsonVariables/JsonConfigurationVariableReplacer.cs#L185
The check there is trying to screen out the Octopus system variables, as they aren't expected to be used as properties in the Json file, but it is being over eager in this case.

## Steps to reproduce

1. Create a package with a json config, say test.config that has the content shown above
2. Create a project with a script step that uses the package and has it marked to extract
3. Set the inline script to something like `Get-Content -Path .\packageId\test.config` to get it to output the content easily into the task log
4. Enable the Json substitution and set the glob to `**/test.config`
5. Add a project variable named `octopus:apikey` and set a value for it
6. Do a release and deployment and check the value for the apikey that gets output in the task log

## Affected versions

**Octopus Server:** 
up to and including `2019.10`

## Workarounds

None.

## Links

https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1574312822340400
There have been other customer questions about this but I haven't been able to track them down as yet.

**Comment by droyad** [comment]
This is intentional, see https://github.com/OctopusDeploy/Calamari/pull/69

**Comment by distantcam** [comment]
Release Note: Fixed json configs not replacing variables that start with "octopus"
