### ISSUE TITLE
Tenanted project shows wrong message when there is a release but no tenants connected to the project

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#6040]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you have a tenanted project with a release but no connected tenants, the overview shows a message that you have no releases.

## What I expected to happen

The message should reflect that you don't have any tenants connected to the project.

## Steps to reproduce

1. Create a tenanted project.
2. Do not connect any tenants.
3. Create a release for the project.
4. Go to the overview.
5. See the message 'There are no releases for this project yet.'

### Screen capture

![image](https://user-images.githubusercontent.com/1571799/69654132-e8045600-1039-11ea-858b-76f47a23aff0.png)

![image](https://user-images.githubusercontent.com/1571799/69654148-edfa3700-1039-11ea-9797-565fc73c79da.png)

## Affected versions

**Octopus Server:** 2019.10.8

## Workarounds

Connect a tenant for the message to go disappear and the normal overview to appear.

## Links

Reported internally

**Comment by octokhor** [comment]
Old issue and 3 years ago. Closing this for now.
