### ISSUE TITLE
Support Helm 3

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6048]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Currently Octopus doesn't support Helm 3.

The `helm init` command is no longer required with helm 3, so we should detect the helm version and not run `helm init` if it’s helm 3.

## Steps to reproduce

1) Put helm3 binary to the path variable or reference to it in the Helm Chart Step
2) Create a Kubernetes Target
3) Create a project with a Helm Deploy Step
4) Prepare a Helm Repo as External Reference in Octopus
5) Deploy a helm chart

`Error: unknown flag: --skip-refresh` during package acquisition

## Affected versions

Reported in **Octopus Server** 2019.10.1 and 2019.10.10

## Links

Sources:
https://secure.helpscout.net/conversation/1018885849/53863?folderId=954335 (private)
https://help.octopus.com/t/helm-3/24225/3
https://secure.helpscout.net/conversation/1055504048/55691?folderId=3209064

**Comment by fsettele** [comment]
Any chance to get that fixed in the near future?

**Comment by PashCracken** [comment]
We are also waiting on a fix for this. We are on Octopus v2019.9.10 LTS
Currently Octopus is the only thing in our tool chain that are blocking us from migrating to Helm 3

**Comment by PashCracken** [comment]
What is the planned version for a fix? Will it be in the next LTS version? Or a fix for existing LTS? Anyone from Octopus reading this? :-)

**Comment by MJRichardson** [comment]
We are working right now on modifying the Helm feed and step to support Helm v3.

We will ship this in early January, including as a patch for the 2019.9 LTS release.

We do apologize for the inconvenience.

**Comment by ilyalukyanov** [comment]
Sorry for bugging this ticket, but it's already early January :) Can you guys please give any heads up on ETA for that release? That would help us to decide whether to build a workaround or just wait.

**Comment by ilyalukyanov** [comment]
For those who want to start using Helm 3 with Octopus now, I've hacked together some embarrassing code that is now serving us well on our Octopus server.

Check this out if you're as impatient as I was https://gist.github.com/ilyalukyanov/c2c37d7a0fae85c177e8da6999de89e3 :)

**Comment by flin-8** [comment]
Thanks for your patience everyone and sorry for the delay. We now anticipate to ship this around mid February.

**Comment by flin-8** [comment]
Release Note: Support Helm V3

**Comment by PashCracken** [comment]
I assume there will be a patch to latest LTS also so we don’t have to wait for next LTS?

**Comment by flin-8** [comment]
> I assume there will be a patch to latest LTS also so we don’t have to wait for next LTS?

Yes, the corresponding issue for `2019.12 LTS` is https://github.com/OctopusDeploy/Issues/issues/6144.

**Comment by flin-8** [comment]
Hi everyone,

You can now download either **2019.13.5** or **2019.12.2 LTS** from our [downloads](https://octopus.com/downloads) page.

Please note that you will need to specify the Helm version on the step:
![image](https://user-images.githubusercontent.com/2888279/74210350-1b6c8d80-4cd7-11ea-9f7e-b4c85c73cad3.png)

**Comment by michaelpearce-gain** [comment]
Hi can we get our octopus cloud upgraded, so we have this? currently still at 2019.13.4

**Comment by benPearce1** [comment]
@michaelpearce-gain can you send a message to support@octopus.com and we can upgrade in your next maintenance window

**Comment by benPearce1** [comment]
@michaelpearce-gain I found the instance, but your maintenance window is not u tul 23:00 GMT, let me know if you want the upgrade earlier

**Comment by michaelpearce-gain** [comment]
@benPearce1 , have sent email to support, but yes if it can be done today, we dont have to wait for maintenance window, i can be done immediately.
