### ISSUE TITLE
If the network interface is interrupted the server stops accepting HTTP requests - LTS 2019.6

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#6077]
This is the backport of #5795

**Comment by gupta-kartik** [comment]
Closed by https://github.com/OctopusDeploy/OctopusDeploy/pull/4993

**Comment by gupta-kartik** [comment]
Release Note: Backport Fix - The WebUI HTTP listener now retries if there is a network error that causes it to terminate
