### ISSUE TITLE
Sensitive variable templates incorrectly detecting default values

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6080]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

A sensitive template variable with a default value will incorrectly state that it is using the default value even after being changed.

## What I expected to happen

It should detect that the value is different and provide a 'Reset to default' option

## Steps to reproduce

1. Create a library variable set and link to a project and tenant
2. Add a template variable of type Sensitive and set a default value
3. Navigate to the Tenant Variables and change the value to something new

## Affected versions

**Octopus Server:** 2019.11.0

## Links

[Internal Link](https://secure.helpscout.net/conversation/1037709780/54764?folderId=3252735)

**Comment by KennethBates** [comment]
Another source: https://secure.helpscout.net/conversation/1062420794/56156?folderId=954335 (private link)

**Comment by alialmaktoum** [comment]
Discussion on how to fix this issue: (private link)
https://octopusdeploy.slack.com/archives/C033W4273/p1583974878176600

**Comment by alialmaktoum** [comment]
The fix looked like it would just add more confusion so it was decided to leave it at the investigation of a potential solution.

**Comment by alexrolleyoctopus** [comment]
This issue will be closed as "won't fix".

As @alialmaktoum mentioned, in researching a potential solution to this issue we couldn't arrive at a solution that resolved the problem without either introducing a security flaw and/or having an even more confusing user experience.

While this is less than ideal, considering the amount of effort involved and the small number of users affected we have decided that this is the best path.

**Comment by paulegradie** [comment]
We've had some more discussion on how to handle this, and we've decided to implement a fix that will at least prevent users from being mislead about which password is being used, so I've reopened this issue for the moment while we put the fix in place.

To any users experiencing this: I've tested to ensure that the intended behavior is actually executing (passwords _are_ being changed, despite what the message says). We will remove this message for now.

**Comment by paulegradie** [comment]
After discussion, we've gone ahead with the decision to remove this Note altogether from UI. 
@andyinaus @andrewabest 

For reference, previous discussion was held on this issue here: https://github.com/OctopusDeploy/OctopusDeploy/pull/5459

We can consider a more explicit UI for this feature if the current fix proves to be suboptimal.

**Comment by paulegradie** [comment]
Release Notes: Removes an incorrect note when setting sensitive fields in tenant variables
