### ISSUE TITLE
System variable Octopus.Action.Status not working

### ISSUE THREAD

**Issue by Tom-Dunstan** [OctopusDeploy/Issues#6114]
I'm trying to include the list of actions in a notification email for a release. I'm iterating through the actions with `#{each action in Octopus.Actions}` and I'm trying to get `action.Status.Code` and `action.Status.Error`
The problem is that `action.Status` does not seem to exist.

**Comment by tothegills** [comment]
Here is the syntax I got working in a PowerShell script:

```
#{each action in Octopus.Action}
	echo '#{action.Name} - #{action.Status.Code}'
#{/each}
```

Not that the currently executing action does not have a status code.
