### ISSUE TITLE
Octopus.Action variable is sorted alphabetically instead of by Number property 

### ISSUE THREAD

**Issue by Tom-Dunstan** [OctopusDeploy/Issues#6115]
I'm currently using `#{each action in Octopus.Action}` to interstate through the list of actions. The array that is returned by **Octopus.Action** is ordered alphabetically. In most cases I would expect it to be ordered by its Number property. Ideally the ability to sort with using #{each} using a pipe operator would fix this eg: `#{each action in Octopus.Action | orderby Number}`

**Comment by MarkSiedle** [comment]
Hi Tom,

Thanks for getting in touch.

Our issues repository is for issues that have been triaged by our support team. As mentioned in our issues template, please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately.

In terms of this feature, this is not something we'll be prioritising at this time. However, you could consider adding this as a [uservoice suggestion](https://octopusdeploy.uservoice.com/) if you feel strongly about it. If your suggestion gets enough community support/votes, we will consider adding it as a feature in a future version of Octopus.

Mark
