### ISSUE TITLE
Tentacle Configuration Options: Tenant option missing if no tenant found

### ISSUE THREAD

**Issue by andyinaus** [OctopusDeploy/Issues#6122]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives

It gives a better understanding of what configuration options/restrictions we have for tentacles to users who are not familiar with Octopus Deploy. Otherwise, users are not even aware of that deployment targets can be configured to support different types of tenanted deployment.
## Proposed solution

It may be better off if the restriction "Tenanted Deployments" is still visible to users during or after creation but marked with the default value (if there is no tenants) and a "how to enable" instruction link. 

## Mockup

Tentacle with no tenants
![image](https://user-images.githubusercontent.com/12688884/73044953-b67ffd80-3eb7-11ea-8b3e-43476e4c69f4.png)

Tentacle with tenant(s)
![image](https://user-images.githubusercontent.com/12688884/73045031-fe9f2000-3eb7-11ea-806c-f1b95422b03e.png)

**Comment by zentron** [comment]
This is by design. We deliberately hide parts of the system that talk about Tenants if no tenants are available since in a large number of customer instances they never have\know about tenants and this results in clutter that they then log issues about.
