### ISSUE TITLE
Disabling features from library package step template aren't removed

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6148]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Removing features (tested with `custom installation directory`, `substitute variables in files` and `configuration variables` features) from a custom package step template in the library don't fully remove these features.

## Steps to reproduce

1. Create a custom package step template in the library and enable the `substitute variables in files` feature targeting a file
2. Add it to a project
3. Disable the `substitute variables in files` feature in the step template and update the step in the project
4. Deploy the project

### Screen capture

Audit log showing the template version and features removed from the `enabled features`, but their respective properties aren't removed:

![step_template_updated](https://user-images.githubusercontent.com/20388190/73708232-8b17d100-4749-11ea-87ac-17a6faffae9a.png)

Task log from the deployment of the project using the updated template version:

![updated_step_template_deployed](https://user-images.githubusercontent.com/20388190/73708243-90751b80-4749-11ea-8062-3399c86d43bd.png)

## Affected versions

Reproduced in Octopus Server 2019.13.2

## Workarounds

1. Re-enable the features in the step template
2. Remove any input on the features (for example, anything in the `Target files` field in `Substitute variables in files` feature)
3. Save the step template
4. Remove the features and save again.

## Links

Source: https://secure.helpscout.net/conversation/1070224685/56614?folderId=954335 (private link)

**Comment by Waldo000000** [comment]
Note: This issue seems to also affect simple scenarios adding/removing configuration features on a regular run a script/deploy a package step.

**Comment by danefalvo** [comment]
Release Note: Fixes an issue where configuration features weren't able to be disabled from Library Package Step Templates.
