### ISSUE TITLE
Retention policy deleting package referenced by published Runbook

### ISSUE THREAD

**Issue by octocrock** [OctopusDeploy/Issues#6150]
- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

A package referenced by a Runbook is deleted when the package is not referenced by a deployment process.

## What I expected to happen

Package should not be deleted if referenced by a published Runbook.

## Steps to reproduce

1. Create a Runbook that references a package in the Octopus package repository.  Do not reference that package in any deployment process. 
2. Publish the Runbook.
3. When retention policy runs that would otherwise clear down a package, because it "is not referenced anywhere" it will delete it, even though the package is used in.

## Affected versions

**Octopus Server:** 2019.11+

## Workarounds

Reference the package from within a Project Deployment and create a release. 

## Links

https://help.octopus.com/t/retention-of-packages-not-in-any-release-but-referenced-by-a-runbook/24605

**Comment by NickJosevski** [comment]
Release Note: A package referenced by a Runbook is not deleted by retention policy.

**Comment by NickJosevski** [comment]
Release Note: A package referenced by a Runbook is not deleted by retention policy.
