### ISSUE TITLE
API Key Copy to Clipboard action not working

### ISSUE THREAD

**Issue by ankithkonda** [OctopusDeploy/Issues#6157]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Copy to clipboard action for API key doesn't work even though action indicates the value was copied

## What I expected to happen

When I click on the copy button, I expect to be notified that the value is copied and I can paste the value elsewhere.

## Steps to reproduce

1. Go to Users
2. Select a user to generate an API key
3. Click on the copy icon
4. Paste the copied value 

## Affected versions

**Octopus Server:** 2019.13

## Workarounds

Copy manually using OS copy paste functionality

## Links
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1581363558088400

Previous issue - https://github.com/OctopusDeploy/Issues/issues/5579

**Comment by emilol** [comment]
Release Note: fix icon alignment so that copy button works on mac
