### ISSUE TITLE
Slow package upload

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#6161]
# The bug

When you push a package to Octopus, there's permission checks to confirm that you have permission to push to the built-in feed, and an additional permission check to find any projects that are referencing this package in their deployment process, to check if the user is authorized to push the package for the given project.

When operating at scale (with large numbers of deployment processes), the package upload endpoint becomes progressively slower, due to these permission checks that scan the `DeploymentProcess` table with a `LIKE` query.

For example, when pushing a package, this query was found in the SQL profiler:

```
exec sp_executesql N'SELECT *
FROM dbo.[DeploymentProcess]
WHERE ((([SpaceId] = ''Spaces-1'')))
AND ([IsFrozen] = @isfrozen_0)
AND ([JSON] like @packageid)
ORDER BY [Id]',N'@isfrozen_0 bit,@packageid nvarchar(13)',@isfrozen_0=0,@packageid=N'%MyPackageName%'
```

That `LIKE` query can become very slow over time.

## What I expected to happen

We should add `PackageIds` to the `RelatedDocuments` table and establish a relationship between `DeploymentProcess` and `Packages` so we can query for this information efficiently and not resort to these horrible LIKE queries.

### Screen capture

![2020-02-12 13_43_12-SQL Server Profiler -  Untitled - 1 ( )](https://user-images.githubusercontent.com/819605/74301091-a44dfc80-4d9d-11ea-92e0-040fdb76b1e2.png)

## Workarounds

There are no workarounds at this time.

## Internal Links

E.g. https://github.com/OctopusDeploy/OctopusDeploy/blob/80da6cae6ddeb139613a270b834e70f2e442013d/source/Octopus.Core/BuiltInFeed/BuiltInPackageRepository.cs#L246

calls through to this document restriction:
https://github.com/OctopusDeploy/OctopusDeploy/blob/80da6cae6ddeb139613a270b834e70f2e442013d/source/Octopus.Server/Web/Api/ModelRestrictionMap/IndexedPackageRestrictionDefinition.cs#L50

which calls this permission check:
https://github.com/OctopusDeploy/OctopusDeploy/blob/80da6cae6ddeb139613a270b834e70f2e442013d/source/Octopus.Server/Web/Api/ModelRestrictionMap/IndexedPackageRestrictionDefinition.cs#L65

which scans deployment processes for usages of that package:
https://github.com/OctopusDeploy/OctopusDeploy/blob/80da6cae6ddeb139613a270b834e70f2e442013d/source/Octopus.Server/Web/Api/ModelRestrictionMap/PackageUsages.cs#L15

which highlights their performance issue (that `LIKE` query on the `JSON` column)

## Links

https://secure.helpscout.net/conversation/1075238708/56846?folderId=3074962

**Comment by flin-8** [comment]
There's also a bug where it's not checking runbooks

**Comment by fourpastmidnight** [comment]
Hope you guys are still working on this. It's been almost a year!

**Comment by mcasperson** [comment]
@fourpastmidnight This issue is still in our backlog, although unfortunately I couldn't provide a time frame as to when it will resolved at this point. 

We'll post any updates on the progress here in this issue.

**Comment by adrianhowchin** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by fourpastmidnight** [comment]
That's a very poor response for a critical bug impacting your  customers. Instead of new features, how about prioritizing this critical bug? Asking customers to increase their build time--in my organization's case, to over 100 minutes--frankly, is ridiculous. We pay for this product. We pay for support. But you're basically saying you won't support us.

**Comment by Silcoish** [comment]
Release Note: Uploading a package with a user that has unscoped built in feed push permission will skip the need to check permission to upload against all projects. Improved query time by changing the query to make use of json queries.
