### ISSUE TITLE
Auto-deploy logs added to improve diagnosing experience

### ISSUE THREAD

**Issue by alialmaktoum** [OctopusDeploy/Issues#6163]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives
User has difficulty determining why an Auto-deploy trigger did not execute
## Proposed solution
Adding auto-deploy logs stating what machines were considered and what projects were considered for Auto-deploy

## Mockup

![image](https://user-images.githubusercontent.com/5039628/74215396-ae63f280-4cec-11ea-8d91-267afeeefcb7.png)

**Comment by tothegills** [comment]
I think this was done but we forgot to reference it
