### ISSUE TITLE
Deploy Kubernetes Container Step doesn't allow Variables for Volume Name 

### ISSUE THREAD

**Issue by tinabamford** [OctopusDeploy/Issues#6182]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Deploy Kubernetes Container Step doesn't allow Variables for Volume Name.  The Variable link is avalible and it will allow you to choose a variable, but attempting to saving throws the following error: 
![image](https://user-images.githubusercontent.com/49412137/74783979-bcb98d80-525b-11ea-9267-9ca7b5461685.png)

## Affected versions
Found in: v2019.13.4
Tested in: v2019.12.0

**Octopus Server:** 

## Workarounds
None

## Links
https://help.octopus.com/t/cant-use-variable-name-for-volume-mount/24701
https://octopus.zendesk.com/agent/tickets/61485

**Comment by aadje** [comment]
We are hitting the same bug. Any updates on this?

**Comment by mcasperson** [comment]
This issue was fixed in 2020.3.1. Unfortunately this issue was not updated at the time, but all LTS versions of Octopus have the fix.

**Comment by danefalvo** [comment]
Release Note: Fixed an issue where the Kubernetes Container Step wasn't allowing Variables for the "Volume Name"
