### ISSUE TITLE
Downloading package from built-in library does not provide size

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#6189]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
When downloading from the built-in library, you get no indication of how large a file may be and therefore you get no indicator from browsers etc. as to how long or big a download happens to be.

## What I expected to happen
We should be returning the content length so that browsers can show the appropriate details.

## Steps to reproduce

1. Go to the built-in library
2. Download a sizeable package
3. Notice there is no file size indication when downloading

### Screen capture
![image](https://user-images.githubusercontent.com/6700195/74889332-61f37380-53cc-11ea-9de5-3305ae8b4d6d.png)

## Affected versions
**Octopus Server: < 2019.13.7

**Comment by NickJosevski** [comment]
Release notes: Downloading package from built-in library will now have content length headers set
