### ISSUE TITLE
Octopus.Server configure--xFrameOptionAllowFrom=SAMEORIGIN pre-pends Allow-from during change

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#6196]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When customer changes X-Frame-Options from the default `Deny` we pre-pend `Allow-from` to the command. For example, if you change X-Frame-Options to `SAMEORIGIN` via Octopus.Server cmd or in the UI the change is overwritten to `Allow-from SAMEORIGIN`. 

While this is as specified in our documentation this isn't expected behaviour, and `Allow-From` has been marked as [obsolete](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) 

Only available options are now `DENY` or `SAMEORIGIN`

## What I expected to happen

We should set X-Frame-Option exactly as specified.

## Steps to reproduce

1. Browse to Octopus.Server location in admin CMD window
2. Run Octopus.Server configure --xFrameOptionAllowFrom=SAMEORIGIN
3. Check headers and you will see that it has been set to `Allow-from SAMEORIGIN`

## Affected versions

**Octopus Server:** 3.2.23 > Latest 

## Workarounds

NA

## Links
[Customer report](https://secure.helpscout.net/conversation/1090105947/57654?folderId=1465198) - Private link

**Comment by alialmaktoum** [comment]
Release Note: New XFrameOptions setting added to set x-frame-options header to sameorigin, deny or none
