### ISSUE TITLE
Slow tenant missing variables endpoint

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#6197]
# The bug

Various performance issues are presenting themselves in regards to tenants in the Octopus UI, due to the addition of permission restrictions running poorly-performing `LIKE` queries on related documents, such as `LibraryVariableSets`.

The problems are occurring on critical path areas of the UI, such as the tenants and project overview screens (anywhere the `/api/tenants/variables-missing` endpoint is used).

This is semi-related to a slow package upload issue, which also came down to permission restrictions - see [related issue here](https://github.com/OctopusDeploy/Issues/issues/6161)

## Internal Notes

Tenants are primarily suffering due to the `TenantVariablesMissingAction` API action, E.g. `/api/tenants/variables-missing`, which runs a permission check on `TenantVariableRestriction` and the `LIKE` queries contained in [CreateLibraryOwnerFilter](https://github.com/OctopusDeploy/OctopusDeploy/blob/b923764c6563e50944f2a2f328bb8731934162b9/source/Octopus.Server/Web/Api/ModelRestrictionMap/TenantVariableRestrictionDefinition.cs#L156-L166). We should be creating an `OwnerType` column to save joining to other tables.

This is the query execution plan sent by a customer, ​I'm guessing we've hit another case of SQL parameter sniffing (https://github.com/OctopusDeploy/Issues/issues/5722). 
​
​You can see the execution plan has triggered a "Table Spool" that is storing the full join of LibraryVariableSet+Project (1360 rows) x Tenants (179 rows) = 243440 rows, only to discard most of the rows immediately after.

![image](https://user-images.githubusercontent.com/2888279/75932243-ae59ab80-5ec2-11ea-9324-036791a43563.png)

### Reproduction and Investigation

There is also a script provided by the customer (see links below) to highlight the differences in queries (between sp_executesql vs raw) that we need to review as part of this issue. Table stats are also provided to help create a reproduction.

## What I expected to happen

RelatedDocuments should be used to ensure we are not running poorly-performing `LIKE` queries on the `JSON` column.

## Affected versions

**Octopus Server:** 2019.8.2 +

## Workarounds

No known workarounds.

## Links

https://secure.helpscout.net/conversation/1092158332/57731/

**Comment by droyad** [comment]
Related to #4845

**Comment by flin-8** [comment]
This merged to `master` in 7dec2550eba87d211f9fd01914dde98fd0e2918e

**Comment by flin-8** [comment]
Release Note: Fix bug where it can sometimes be slow to retrieve tenant variables
