### ISSUE TITLE
Deployment fails when running Helm from a `.tar.gz` package

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#6199]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Deployment fails with `Unsupported file extension '.gz'` when you try to upgrade a Helm chart using the Helm tool from a Helm archive that has the `.tar.gz` extension, for example: `helm-v2.9.1-windows-amd64.tar.gz`

This is because tar archives with a two-part extension aren't being parsed correctly when a package name includes release tags and/or build metadata.

## What I expected to happen

It should work!

## Steps to reproduce

1. Upload `https://get.helm.sh/helm-v2.9.1-windows-amd64.tar.gz` to the Octopus build-in feed
2. Create a Helm step and use the Helm tool from the package from **1.**
![image](https://user-images.githubusercontent.com/2888279/75228148-59030780-57fb-11ea-9359-61e5edd69253.png)
3. Try to deploy

### Screen capture

![image](https://user-images.githubusercontent.com/2888279/75227763-869b8100-57fa-11ea-8934-26ec894c4b7d.png)

## Affected versions

Verified on **Octopus Server 2019.13.7** 

## Workarounds

Use a `.zip` archive instead.

**Comment by emilol** [comment]
Release note: Handle two-part extensions like "tar.gz" when parsing file names
