### ISSUE TITLE
Switching Between Project Steps Calls ActionTemplate/Search Unnecessarily

### ISSUE THREAD

**Issue by BobJWalker** [OctopusDeploy/Issues#6211]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

On the new project process screen, each time I switch between steps I am seeing calls to the ActionTemplate/Search endpoint (/api/[Space-ID]/actiontemplates/search).  

![image](https://user-images.githubusercontent.com/38642825/75565314-55e26400-5a13-11ea-8965-d63f2dfcd4eb.png)

In an of itself, that isn't a big deal.  However, the responder (source/Octopus.Server/Web/Api/Actions/ActionTemplatesSearchResponder.cs) for that endpoint is doing the following:

- Pulls back all the built-in steps as the ActionTemplate class (source/Octopus.Core/Model/Projects/ActionTemplate.cs)
- Pulls back all the community steps as the CommunityActionTemplate class (source/Octopus.Core/Model/Projects/CommunityActionTemplate.cs)
- Calculates which community template has an update
- Returns a subset of all the data returned (source/Octopus.Core/Resources/ActionTemplateSearchResource.cs)

A lot of extra data is being returned from the database (step properties, packages, scripts, etc) which is then disgarded.  For users with any sort of latency between the server and their database, the API will take a while return data.  Which, in turn, causes the step screen to take a long time to render.

## Affected versions

**Octopus Server:** 2019.8.x and newer

## Workarounds

Work on eliminating latency between the database and the Octopus Server.  Though in some cases that is not possible.  

## Links

Reported from customer: https://secure.helpscout.net/conversation/1071297953/56665/

> Update: the above issue can be viewed on ZenDesk via this link: https://octopus.zendesk.com/agent/tickets/4686

**Comment by shaunmarx** [comment]
This will require a bit of thought as to how we approach this particular problem. We need to move the calls up to the highest possible level where it makes sense, however there are currently some hurdles preventing us from doing so. We have a few options we are considering, however will take some time to solve properly.

**Comment by YihaoOct** [comment]
Closing this issue since it has already been fixed since [2020.3.0](https://github.com/OctopusDeploy/OctopusDeploy/tree/2020.3.0).
