### ISSUE TITLE
S3 Uploads Are Failing when on the call to DoesS3BucketExistV2Aync

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#6224]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When I am running 2019.13.6 or 2020.1.x all my uploads to S3 are failing.  I am trying to upload files from a package to a new folder created in this bucket: octopus-demo/bob-demo/linux/

![image](https://user-images.githubusercontent.com/38642825/75824657-83a80f80-5d69-11ea-9f8a-2e9fff2c134c.png)

See attached error log.
[ServerTasks-23775.log.txt](https://github.com/OctopusDeploy/Issues/files/4283867/ServerTasks-23775.log.txt)

I am using the "BobDemo" IAM user I created.  This was the same user I used in December in that bucket without issue.  

## What I expected to happen 

S3 Uploads to work.

## Steps to reproduce

1. Create a support user for our samples instance (https://samples.octopus.app)
2. Navigate to this space https://samples.octopus.app/app#/Spaces-102
3. Look at the lone project and the single step
4. Run the deployment and boom.

## Affected versions

**Octopus Server:** 2019.13.0`

## Workarounds

N/A

## Links

Self Reported.

**Comment by droyad** [comment]
Reproduced. Caused by #6092 via https://github.com/OctopusDeploy/Calamari/pull/465/files#diff-0750ca9c27e8fe869bb63ae317ea6e9bR44

**Comment by flin-8** [comment]
The bucket name field should not have a path, just the bucket name.

The bucket key prefix should be used to specify the path:
![image](https://user-images.githubusercontent.com/2888279/75845405-b531e100-5e24-11ea-890c-55f49d1036f6.png)
