### ISSUE TITLE
Octopus.Server configure--xFrameOptionAllowFrom=SAMEORIGIN pre-pends Allow-from during change

### ISSUE THREAD

**Issue by alialmaktoum** [OctopusDeploy/Issues#6233]
#6196 also affected `2019.12 LTS`. The fix has been shipped in the LTS patch indicated by the milestone. If you are using `2019.12 LTS` we highly recommend applying this patch.

Learn about the [Octopus Server LTS program](https://g.octopushq.com/longtermsupport).

**Comment by alialmaktoum** [comment]
Release Note: New XFrameOptions setting added to set x-frame-options header to sameorigin, deny

**Comment by alialmaktoum** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [X-Frame-Options](https://trello.com/c/qMkihfxa/2944-x-frame-options)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.3 |
| 2020.2+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.1 | 2020.1.3 |
| 2020.2+ | -all releases- |
