### ISSUE TITLE
Changing the lifecycle for a project does not update the UI

### ISSUE THREAD

**Issue by JChatmasOctopus** [OctopusDeploy/Issues#6246]
- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When the customer changes the lifecycle for a deployment process, and clicks `Save`, the UI does not reflect the change that was made until the page is refreshed. The change is not reflected on the right side of the `Process` page or on the `Channels` page for the lifecycle under the default channel. Additionally, when cloning the project afer changing the lifecycle, the change is not reflected in the clone window.

## What I expected to happen

When the lifecycle is changed for a deployment process, I expect the UI to reflect the change after clicking `Save`.

## Steps to reproduce

1. Navigate to a project and click on `Process`
2. In the right column under `Lifecycle` click on `Change`
3. Select a different lifecycle and click `Save`
4. See that the lifecycle has not updated on the deployment process page
5. Click on `Channels`
6. See that the lifecycle has not updated for the `Default` channel
7. Click on `Settings`
8. Click on the ellipse in the upper right and click `Clone`
9. See that the lifecycle selected has not updated with the change

## Affected versions

**Octopus Server:** 2019.12.1
**Octopus Server:** 2020.1.2

## Workarounds

If the deployment process page is refreshed, or if the customer goes to another screen and comes back to the deployment process, the lifecycle reflects the correct change.

**Comment by JChatmasOctopus** [comment]
Video demonstration of the defect [here](https://www.dropbox.com/work/Team%20Shared/Teams/Customer%20Success/Chatmas/Aetna?preview=LifecycleDefect-6246.mp4).

**Comment by kengel100** [comment]
Closing this issue as it is not reproducible in the latest version of Octopus. It was likely fixed when the new Project switcher was implemented.
