### ISSUE TITLE
Performance of tenant variables page when multiple Certificate variables

### ISSUE THREAD

**Issue by alialmaktoum** [OctopusDeploy/Issues#6250]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you have multiple certificate variables in Tenant Variables page, there will be an API call for each Certificate Variable to retrieve all certificates. 

## What I expected to happen
We expect one call for the entire page for retrieving all certificates or a call per certificate to only retrieve that one certificate. See the screenshot below for the network trace in Chrome.

## Steps to reproduce

1. Select a project
2. Go to Variables -> Project Variable Templates
3. Add multiple Templates of Control Type "Certificate"
4. Go to Tenants -> Select a tenant -> Variables -> Expand project with certificate variables.
5. Check fiddler to see multiple requests to get certificates

### Screen capture
![12552571](https://user-images.githubusercontent.com/5039628/76480019-44f51200-6459-11ea-897b-1641e819b9ac.gif)

## Links
https://secure.helpscout.net/conversation/1105652183/58619/

**Comment by johnsimons** [comment]
Release Note: Improved performance of tenant variables page when multiple Certificate variables are displayed
