### ISSUE TITLE
Auto deploy trigger doesn't deploy to environment if it's not in the default channel's lifecycle

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6257]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you have a deployment target trigger configured to deploy to an environment that does not exist in the lifecycle the project's default channel uses, the release in that channel will not be deployed to the newly created target.

## What I expected to happen

The auto deploy trigger would pick up the release in the non-default channel and deploy to the environment.

## Steps to reproduce

1. Create a non-default channel in a project
2. Configure the channel to use a lifecycle that has an environment that isn't specified in the default
3. Create a release in that channel
4. Create a deployment target trigger in the project, and configure it to deploy to the environment not listed in the default channel's lifecycle
6. Create a deployment target in that same environment

Result: The auto deploy doesn't pick it up and the release isn't deployed to the new machine.

### Screen capture

Lifecycle configuration:

![auto_deploy_second_lifecycle](https://user-images.githubusercontent.com/20388190/76722478-71799880-678f-11ea-9ab9-9870cc3734f3.png)

Channel configuration:

![auto_deploy_second_channel](https://user-images.githubusercontent.com/20388190/76722482-76d6e300-678f-11ea-8e4c-27e1786ec5d8.png)

Trigger configuration:

![auto_deploy_second_trigger](https://user-images.githubusercontent.com/20388190/76722484-7a6a6a00-678f-11ea-8cb0-b6e45a35a310.png)

## Additional Notes

Further reports of this issue have narrowed this down to an issue specifically around environments in the **project's** default lifecycle, and not the default **channel's** lifecycle. In the case outlined in the original report, the default channel's lifecycle would have been configured to `Inherit from parent`, so this certainly can be, and has been, misleading.

Auto-deploy triggers do not fire when the target environment for the trigger is not contained in the overall Project Lifecycle. The Overall Project Lifecycle is the one configured within the "Process" tab of the project. Once the target environment is added to the selected lifecycle, auto-deploy triggers work as expected.

![Lifecycle highlight](https://user-images.githubusercontent.com/5361797/92043932-745d5980-edc0-11ea-8bae-8f5e6f4a2a76.png)

## Affected versions

Reproduced and reported in 2019.13.7

## Workarounds

Only option is to add the environment to the default lifecycle.

## Links

Source: https://help.octopus.com/t/tentacle-registration-not-auto-triggering-deployment/24818

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto deploy trigger doesn't deploy to environment if it's not in the default channel's lifecycle](https://trello.com/c/pQTeIlMk/3083-auto-deploy-trigger-doesnt-deploy-to-environment-if-its-not-in-the-default-channels-lifecycle)

**Comment by KennethBates** [comment]
Works as intended in 2019.11.3 (latest fast lane release before 2019.13.0) and 2019.12.8 LTS. Might be a regression introduced in #5911

**Comment by KennethBates** [comment]
Another source: https://secure.helpscout.net/conversation/1101914104 (private)

**Comment by KennethBates** [comment]
Another source: https://secure.helpscout.net/conversation/1209333414/66847?folderId=954335 (private link)

**Comment by danefalvo** [comment]
Another Source: https://secure.helpscout.net/conversation/1259168297/69284?folderId=557082

**Comment by Justin-Walsh** [comment]
Another source: https://octopus.zendesk.com/agent/tickets/67250 (private link)

**Comment by KennethBates** [comment]
Another report: https://octopus.zendesk.com/agent/tickets/74924 (private)

**Comment by paraicoceallaigh** [comment]
Another instance: https://octopus.zendesk.com/agent/tickets/80188

**Comment by N-lson** [comment]
Release Note: Auto-deploy triggers now consider environments from all lifecycles included in a project

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12021 |
| 2022.1 | _tbc_ |

**Comment by jvincent-siplay** [comment]
Hi, where can I find those releases? ☝️  The latest version I see available for download is 2021.3.8275.  It doesn't seem to be listed as a nightly either, the last release I see is from 2 months ago.  Thanks.
https://octopus.com/downloads/previous

**Comment by N-lson** [comment]
Hey @jvincent-siplay, we've had an unusual delay in releases for 2021.3 due to a couple of issues picked up during internal testing and the end-of-year period. We should have a steady stream of releases for 2021.3 rolling out once again within a week or two which will be >=2021.3.12021 🙏 Apologies for the inconvenience. The 2022.1 release stream will only be available for self-hosted customers from around March.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12021 |
| 2022.1 | 2022.1.359 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12021 |
| 2022.1 | 2022.1.359 |
| 2022.2+ | _all releases_ |
