### ISSUE TITLE
Tentacle upgrade not available on Octopus Cloud instances

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#6260]
# The bug

We forgot to include the Tentacle.nupkg as part of the Octopus Linux image, this causes the Tentacle upgrade button to not be available

## What I expected to happen

The upgrade button to be available when Tentacles are not up to date.

## Affected versions

**Octopus Server:** 
2020.1.0 - 2020.1.4

## Workarounds

None

**Comment by johnsimons** [comment]
Release Note: Tentacle upgrade button is displayed again

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The "Upgrade Tentacle" button is missing on Cloud instances](https://trello.com/c/eFJgmRbM/3093-the-upgrade-tentacle-button-is-missing-on-cloud-instances)
