### ISSUE TITLE
Can't log in via "Sign in with a domain account" button after upgrade to 2020.1.4

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#6265]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

After upgrading to `2020.1.4`, logging in via the "Sign in with a domain account" button stops working in some cases. _This can happens in single or multiple domain scenarios_

## What I expected to happen

A user from any domain should be able to log in using the integrated sign-in button.

## Steps to reproduce

1. Try to log in using the "Sign in with a domain account" button from a browser that is signed in to a  domain
![image](https://user-images.githubusercontent.com/2888279/77129252-04237b80-6a9f-11ea-9a39-7a59aecb5e8e.png)

2. The browser redirects back to the sign-in form
![image](https://user-images.githubusercontent.com/4229735/77508374-47725580-6eb6-11ea-9684-a922f29ec9c2.png)

## Root cause
This issue was caused by a change in the `WWW-Authenticate` header behavior when the `IntegratedWindowsAuthentication` setting is chosen for Active Directory Authentication.

As part of an upgrade from `.Net Full Framework` to `.Net Core 3.1` we started using `HTTP.sys` for this plugin, which doesn't support user mode authentication.

Since we look at the [`HttpContext.User.Identity.Name` property](https://github.com/OctopusDeploy/DirectoryServicesAuthenticationProvider/blob/db50fc4b4c9c0d7ce4dd3a3d6ec9c559d0d1a51f/source/Server/IntegratedAuthentication/IntegratedAuthenticationHost.cs#L96
) to identify the user that is trying to log on when performing integrated sign-in, in scenarios that rely on kerberos, the [domain] service account being used to run octopus server, isn't able to make this determination.

This property is not set on the first request, so the server returns a `401` to start the authentication challenge. We expect the `HttpContext.User.Identity.Name` property to be populated on the next request from the browser. For a user that is not on the same domain as the Octopus Server service account, this property is never set, blocking the user from signing in using the integrated sign-in.

As a result of raising this [issue](https://github.com/dotnet/aspnetcore/issues/20091) with Microsoft and our investigation we determined that it is possible to address this issue by setting a HTTP service class SPN as described [here](https://octopus.com/docs/administration/authentication/active-directory-authentication#ActiveDirectoryAuthentication-UsingNegotiate).

## Affected versions

**Octopus Server: 2020.1.0 and later** 

## Workarounds

In cases where NTLM is OK, using `Negotiate` or `NTLM` instead of `IntegratedWindowsAuthentication` should be sufficient to address this problem. If Kerberos is required, use `Negotiate` and make sure you've set an SPN as described [here](https://octopus.com/docs/administration/authentication/active-directory-authentication#ActiveDirectoryAuthentication-UsingNegotiate)

Alternatively you can use forms authentication. Type in the credentials manually and use the "SIGN IN" button instead. The [app](https://github.com/OctopusDeploy/Issues/issues/6272) will prompt the user to do that.

## Links

https://secure.helpscout.net/conversation/1114426224/59230?folderId=2845821
https://secure.helpscout.net/conversation/1114705621/59246?folderId=557077
https://help.octopus.com/t/sign-in-with-domain-account-not-working-after-2020-1-8-update/24972

**Comment by ryanrousseau** [comment]
Additional report: https://secure.helpscout.net/conversation/1148700480/63710?folderId=557077

**Comment by jburger** [comment]
Release note: fixes integrated authentication headers when using active directory integration
