### ISSUE TITLE
Listening tentacles become unable to communicate with Octopus Server following 2020.1.4 upgrade

### ISSUE THREAD

**Issue by Waldo000000** [OctopusDeploy/Issues#6266]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Following the cloud rollout of 2020.1.4, we've seen a small number of cases where listening tentacles fail to authenticate to the Octopus Server, with a `System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception` error.

## How do I know if I'll be affected?

You may be affected by this bug if you use Octopus Cloud, and you use a listening tentacle. This seems to only affect some such instances, and we're currently working on further clarifying the affected scenarios.

## Steps to reproduce

TBD

## Related bugs

We saw a similar issue affecting _polling_ tentacles in the same release, but with slightly different symptoms: https://github.com/OctopusDeploy/Issues/issues/6262

#### Tentacle log
```
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The token supplied to the function is invalid
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Halibut.Transport.SecureListener.<ExecuteRequest>d__24.MoveNext()
```

#### Server log
```
|     Halibut.HalibutClientException: An error occurred when sending a request to 'https://x.x.x.x:10933/', before the request could begin: Authentication failed because the remote party has closed the transport stream.
|     ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
|     at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
|     at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
|     at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
|     at Halibut.Transport.TcpConnectionFactory.EstablishNewConnection(ServiceEndPoint serviceEndpoint, ILog log, CancellationToken cancellationToken)
|     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
|     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
|     at System.Lazy`1.CreateValue()
|     at Halibut.Transport.ConnectionManager.<>c__DisplayClass9_0.<CreateNewConnection>b__1()
|     at Halibut.Transport.ConnectionManager.AcquireConnection(IConnectionFactory connectionFactory, ServiceEndPoint serviceEndpoint, ILog log, CancellationToken cancellationToken)
|     at Halibut.Transport.SecureListeningClient.ExecuteTransaction(Action`1 protocolHandler, CancellationToken cancellationToken)
```

## Affected versions

**Octopus Server: 2020.1.2 -> (Suspected)** 

## Workarounds

We suggest you first ensure that the servers running your tentacles are updated with the latest cumulative patches for your operating system (`Workaround 3` below). Then try following the troubleshooting steps [in our documentation](https://octopus.com/docs/administration/security/octopus-tentacle-communication/troubleshooting-schannel-and-tls#TroubleshootingSchannelandTLS-Solution:IncreaseRdaKeyLength), i.e. `Workaround 2` below. If those workarounds don't work, try deleting and recreating the tentacle, i.e. `Workaround 1` below.

### Workaround 1 (recreate tentacle)
1. Log into the Octopus server and note the target name, environments, and target roles.
2. Open tentacle manager on the impacted machine.
3. Take note of the "Home Directory" setting for your instance (C:\Octopus by default)
4. Delete the Tentacle instance via the Tentacle Manager:
![image](https://user-images.githubusercontent.com/49404281/76994464-cbf82d80-6924-11ea-97e4-954c20ad3aea.png)
5. Ensure that the `Tentacle.config` file has been removed from the home directory noted in step 2.
7. Recreate the tentacle instance with the previously noted name, environments, and target roles. Click the "Overwrite existing" checkbox on the registration page to prevent duplicate targets being created.

### Workaround 2 (new certificate)
1. Run `tentacle new-certificate` on the target (https://octopus.com/docs/octopus-rest-api/tentacle.exe-command-line/new-certificate 1)
2. Update the thumbprint for the target accordingly on the Server as shown:
![image](https://user-images.githubusercontent.com/1407488/77127331-c66f2480-6a97-11ea-84d5-1ecb557514c2.png)

### Workaround 3 (patch server)
1. Ensure that your servers running Tentacle are updated with the Windows Cumulative updates for March 2020
2. Reboot the servers running Tentacle

#### Blocked
- https://secure.helpscout.net/conversation/1115527764/59371 (listening tentacle)

#### Unblocked
- https://secure.helpscout.net/conversation/1113750397/59136 (patched listening tentacle server)
- https://help.octopus.com/t/24833 (recreated listening tentacle)
- https://secure.helpscout.net/conversation/1113867332/59149 (new cert for listening tentacle)

### Internal Slack discussion
- https://octopusdeploy.slack.com/archives/CUCG4LAF8/p1584465465243200
- https://octopusdeploy.slack.com/archives/C0100CCBR25/p1584943720174600?thread_ts=1584935880.171400&cid=C0100CCBR25

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [multiple [tentacles] offline](https://trello.com/c/AencIwIB/3097-multiple-tentacles-offline)

**Comment by johnsimons** [comment]
Release Note: Fix connectivity issue with Listening Tentacles when the Octopus Server is using an RSA1 certificate
