### ISSUE TITLE
Connection only test in health check doesn't write Tentacle version

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6268]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When checking the health of a Tentacle that uses a machine policy configured with the setting `Only perform connection test` as the `Health Check Type`, the resulting health check doesn't write the Tentacle version to the log.

## What I expected to happen

The version of Tentacle should be written to the end of the last line in the log `[Tentacle Listening](~/app#/Spaces-1/infrastructure/machines/Machines-1/settings) at https://xxx:10933/, running version`

## Steps to reproduce

1. Ensure a machine policy uses the setting `Only perform connection test` as the `Health Check Type`

![machine_policy_connection_test](https://user-images.githubusercontent.com/20388190/77397529-87bbd000-6df1-11ea-8e64-d3952517648a.png)

2. Perform a health check on a Tentacle that uses this machine policy

![health_check_running_version](https://user-images.githubusercontent.com/20388190/77397684-c9e51180-6df1-11ea-96e9-d7425091fdc8.png)

3. See log

## Affected versions

Reported in Server 2019.12.1 and reproduced in 2019.13.7

## Links

Source: https://help.octopus.com/t/tentacle-versions-not-reporting/24859

**Comment by droyad** [comment]
This is by design as the Tentacle does not report it's version via it's API and we have to run a script to get it: https://github.com/OctopusDeploy/OctopusDeploy/blob/175f01829d6d3c7063dceeb98d7a5af8795abef1/source/Octopus.Server/Orchestration/ServerTasks/HealthCheck/Controllers/Scripts/HealthCheck.ps1#L60

The connection only health check by definition does not run scripts

**Comment by kengel100** [comment]
This is working as designed, please see the comment above. Health checks do not run scripts, therefore we can't get the Tentacle version number.
