### ISSUE TITLE
Project switcher caches search text

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6282]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using the project switcher, if you search by typing text to find a project, and exit the switcher, that text is cached and automatically populates when dropping down the switcher next time. This is inconvenient when jumping to other projects that do not include that previously typed text in the search.

## What I expected to happen

The search would be reset to blank on second use of the project switcher.

## Steps to reproduce

1. Type in some text in the project switcher
2. Close the switcher (either clicking off the dropdown or going into a project)
3. Reopen the project switcher
4. See the search term is still in the search

### Screen capture

![project_switcher_caching](https://user-images.githubusercontent.com/20388190/77973275-fc819380-7336-11ea-9200-cd3d99b56447.gif)

## Affected versions

Reproduced in server 2020.1.6 & reported in 2019.13.7

## Workarounds

Remove the search term when needed for a new search.

## Links

Source: https://help.octopus.com/t/project-switcher-caching-issue/24889

**Comment by kengel100** [comment]
This issue has since been resolved and is working correctly in the latest versions of Octopus. It was likely addressed when the Project switcher design was updated.
