### ISSUE TITLE
Linux tentacle upgrades from tarball install can not be upgraded

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#6283]
#6212 also affected `2020.1 LTS`. The fix has been shipped in the LTS patch indicated by the milestone. If you are using `2020.1 LTS` we highly recommend applying this patch.

Learn about the [Octopus Server LTS program](https://g.octopushq.com/longtermsupport).

**Comment by adam-mccoy** [comment]
Release Note: Fix bug with auto-upgrade of tarball Linux tentacles
