### ISSUE TITLE
Running a Runbook against a tenant and then deleting the tenant causes 'TypeError'

### ISSUE THREAD

**Issue by JChatmasOctopus** [OctopusDeploy/Issues#6291]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

~**Note: This issue does not exist in 2020.1.6**~
**This exists in 2020.1.6**

If I run a Runbook against a tenant and then subsequently delete that tenant, I see the error "TypeError: Cannot read property 'Name' of undefined" when returning to the Runbook overview page.

## What I expected to happen

I expect that after I delete a tenant after running a Runbook against it, there will be no error.

## Steps to reproduce

1. Create and publish a Runbook
2. Run the Runbook against a tenant
3. Delete that tenant
4. Navigate to the Runbook overview page
5. See error

### Screen capture

![image](https://user-images.githubusercontent.com/50506513/78596178-4e378b80-7819-11ea-9f5d-ea4617621154.png)

## Affected versions

**Octopus Server:** 2019.12.4, 2019.13.7, 2020.1.6

~**Not affected:** 2020.1.6~

## Workarounds

It is possible to access the other Runbook pages by manually replacing `/overview` in the address bar with the route for the desired page:
- `/runslist` for the list of runs
- `/steps/all` for the runbook steps
- `/settings` for the runbook settings

Creating new runs is not blocked by this issue.

## Links

https://secure.helpscout.net/conversation/1129933739/61607?folderId=2981202

**Comment by adam-mccoy** [comment]
Release Note: Clean up a tenants runbook runs when they are deleted
