### ISSUE TITLE
Step run condition fails when binding to process-scoped variable

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6292]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

A run condition based on a variable expression doesn't work when the variable is scoped to a process (runbook or deployment).

## What I expected to happen

The step would correctly run or not run based on the value of the process-scoped variable.

## Steps to reproduce

1. Create a project variable with a value of `True`
2. Scope the variable to a process (scoped to a runbook in my example)

![runbook_scoped_variable](https://user-images.githubusercontent.com/20388190/78732968-6fb68580-7987-11ea-9323-5c703a55498c.png)

3. Configure a step to run based on a variable expression, using this variable

![runbook_variable_expression_condition](https://user-images.githubusercontent.com/20388190/78732986-7cd37480-7987-11ea-9741-3144de907948.png)

4. See result on run

![step_skipped](https://user-images.githubusercontent.com/20388190/78733006-878e0980-7987-11ea-8f6b-f7d4efc96ff0.png)

## Affected versions

Reproduced in 2020.1.6 and reported in 2019.13.7

## Workarounds

The below report outlines their workaround involving exporting the process-scoped variable, setting an output variable and binding that to the run condition.

## Links

Source: https://help.octopus.com/t/issue-with-prompted-variables-used-in-runbook-step-run-condition/24926

**Comment by KennethBates** [comment]
Also reproduced using a deployment process scoped variable in master under project Kenny Feed Variable Test

**Comment by flin-8** [comment]
The evaluated variable in step 1 is true, so it's probably an edge case somewhere

![image](https://user-images.githubusercontent.com/2888279/78736671-14899080-7991-11ea-93ef-22ae80cb4912.png)

**Comment by andrewabest** [comment]
Release Note: Fixes an issue where a run condition based on a variable expression doesn't work when the variable is scoped to a process
