### ISSUE TITLE
Tenant scoped account doesn't automatically populate in tenant's common variable dropdown

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6321]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When trying to set a value to an account variable in a tenant's common variables, the accounts connected don't automatically populate in the dropdown.

## Steps to reproduce

This example uses an Azure account.
1. Scope the Azure account to a tenant.

![scope_azure_account_to_tenant](https://user-images.githubusercontent.com/20388190/79926261-ca6bd900-847f-11ea-8fca-0a4140c67e49.png)

2. Create a common variable template of type Azure Account.

![common_template_azure_account](https://user-images.githubusercontent.com/20388190/79926271-ce97f680-847f-11ea-8a80-65e1293aa946.png)

3. Include the variable set in a project the same tenant is connected to.
4. Open the tenant's common variables tab and click the dropdown.

Result is the Azure Account isn't automatically populated.

![tenant_dropdown](https://user-images.githubusercontent.com/20388190/79926281-d2c41400-847f-11ea-88e9-d9b09d2cbc08.png)

Very confusing as it implies something isn't configured correctly in one of those places. To get it to populate, you have to click the Refresh icon next to the dropdown.

![refresh_account_variables](https://user-images.githubusercontent.com/20388190/79926291-d8215e80-847f-11ea-8ad6-404abaceb50d.png)

## Affected versions

Reported in 2019.12.2 LTS and reproduced in master under tenant `Kenny`.

## Workarounds

Click the refresh icon next to the field.

## Links

Reported here: https://secure.helpscout.net/conversation/1131152029/61853?folderId=954335 (private link)

**Comment by tothegills** [comment]
Release note: Accounts can now be selected without refreshing on the tenant common variables screen
