### ISSUE TITLE
Execution containers for workers

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6330]
# The feature

## Problem

Deployments (and runbooks) have dependencies.

In this case, “dependencies” are things like Azure and AWS command-lines, NodeJS, Python, kubectl, Terraform client, Helm, .NET, Java, etc, etc, etcetera.

Octopus currently takes an inconsistent approach to these.  Some are bundled with the Octopus server and pushed to execution targets.  Examples of these are the Azure PowerShell modules, AWS CLI, and Terraform.  In other cases we just assume the dependency is pre-installed on the target, e.g. kubectl, Helm, Java.  

The bundled dependencies are a constant thorn in our side.  They are always out of date.  They are platform-specific.  Users currently can’t pin the version of the bundled dependencies, so when breaking changes are introduced to the dependency, we find ourselves in a damned-if-we-do, damned-if-we-don’t scenario (e.g. Terraform).  

## Proposed solution

We will add a new field that will be exposed whenever an action is configured to run on a worker pool.  

![image](https://user-images.githubusercontent.com/171197/80436792-4d3ed900-8943-11ea-89db-06ae0d289865.png)

The new field will allow specifying whether the action executes directly on the deployment target, or inside a container created from a specified image.

If executing inside a container, the image (including the tag) will be specified.

We will publish Octopus images for both Windows and Linux, which contain all the dependencies required by any built-in steps (Azure CLI, AWS CLI, Terraform, Kubernetes, Java, .NET, PowerShell, etc).  We will update these with each release, but users are free to build their own images.  

Note that the tag is set in the step itself, not chosen at release creation time.  It is up to the step author to decide when to bump the tag, not the person creating releases.  When we ship new versions of the Octopus images, existing steps will not be automatically updated.  This allows us to safely ship new versions.  

At run-time, Calamari (and any required scripts, packages, and variable files) will be mounted into a container created from the specified image, and docker exec will be used to execute the Calamari command.

This effectively means the only prerequisite on workers is docker.  The action can fail immediately at runtime if docker is not installed.

# Links

[Pitch document](https://docs.google.com/document/d/1X43jGGDmhLh5Hq2JJ7eb0-FKBYcKz94IqpyG2-KY0d0/edit#) (Private)

**Comment by tothegills** [comment]
Release note: Execution Containers for Workers - Steps that run on a worker can specify a container to execute the step in

**Comment by NotIlya4** [comment]
Is it possible to set feed through variable? We want to use different feeds based on regions. Currently looks like it isnt(
