### ISSUE TITLE
Azure CLI Tool Extensions use Octopus Supplied directory when using Pre-Installed Tools

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6336]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using Pre-Installed Azure CLI tools in an Azure step, the installed extensions will not be usable as Octopus is overwriting the extensions location with its own in the work directory.

## What I expected to happen

It should use the system default extension directory

## Steps to reproduce

1. Install an extension in PowerShell (`az extension add --name eventgrid`).
2. Go to a deployment/runbook and create an Azure Step, and run `az --version`.
3. Examine the table in the log, compare it to running `az --version` inside of PowerShell.
4. Examine the task log to see the extension directory is still being set to inside of the work directory, rather than the system directory.

![image](https://user-images.githubusercontent.com/2888279/80761030-28ce4100-8b7d-11ea-905b-95d7b440b786.png)

### Log exerpt

**From Azure Step inside Octopus**
```
10:24:03   Verbose  |       Invoking target script C:\Octopus\Work\20200428142352-681-19\Script.ps1 with  parameters
10:24:05   Info     |       azure-cli                          2.4.0 *
10:24:05   Info     |       command-modules-nspkg              2.0.3
10:24:05   Info     |       core                               2.4.0 *
10:24:05   Info     |       nspkg                              3.0.4
10:24:05   Info     |       telemetry                          1.0.4
10:24:05   Info     |       Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
10:24:05   Info     |       Extensions directory 'C:\Octopus\Work\20200428142352-681-19\azure-cli\cliextensions'
```
**From PowerShell**
```
PS C:\Windows\system32> az --version
azure-cli                          2.4.0 *
command-modules-nspkg              2.0.3
core                               2.4.0 *
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
eventgrid                          0.4.8
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\username\.azure\cliextensions'
```

## Affected versions

**Octopus Server: Reproduced in 2019.10.12 and 2020.1.15** 

## Workarounds

Install the extension inside of a **Run a Script** step rather than using the **Run an Azure Script** step. Run all required az commands inside of a **Run a Script** step. You will be required to include any login commands to connect to Azure at the beginning of the script. The Azure account can be passed as a variable to these steps to facilitate the use of the pre-configured Azure account. 

## Links

(Internal Link) https://secure.helpscout.net/conversation/1146274152/63606?folderId=3767306

**Comment by gupta-kartik** [comment]
We'll be able to use a variable, `Octopus.Action.Azure.ExtensionsDirectory` to set a non default Azure extensions folder. It will be shipped as part of the release indicated by the milestone.
