### ISSUE TITLE
Unable to start Octopus Manager (intermittent)

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#6353]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Sometimes Octopus Manager may fail to start with a message that looks like:
```
Description: A .NET Core application failed.
Application: Octopus.Manager.Server.exe
Path: C:\Program Files\Octopus Deploy\Octopus\Octopus.Manager.Server.exe
Message: The application to execute does not exist: 'C:\Users\<username>\AppData\Local\Temp\.net\Octopus.Manager.Server\j43ftxkj.mmw\Octopus.Manager.Server.dll'.
```

This is a [dotnet core issue](https://github.com/dotnet/runtime/issues/3778) that affects all single-file executables. When running the executable, the contents are extracted to a temporary directory and executes from there. The unfortunate thing is that temporary files sometimes get cleaned up by scheduled tasks and other processes, which breaks things. Microsoft has recently [fixed ](https://github.com/dotnet/core-setup/pull/9013) this issue so we will be able to fix this permanently once they releases the new version of NetCore 3.1.

## What I expected to happen

Octopus Manager should work even when some of the files have been cleaned up.

## Affected versions

**Octopus Server: 2020.1+** 

## Workarounds

The [.net documentation here](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md#extraction-location)​ explains how the extraction location is determined. You can override this in the meantime by setting the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable to somewhere else.

## Links

https://help.octopus.com/t/unable-to-start-octopus-server-manager/25047

**Comment by matt-richardson** [comment]
Release note: Fixed intermittent startup issue in Octopus Manager due to extracted files missing
