### ISSUE TITLE
Typing a character into the variable name or value of a Deploy a Release step loses focus

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#6356]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you type a character into the variable name or value of a Deploy a Release step, the field loses focus.

## What I expected to happen

The field to keep focus so I can type the full name.

## Steps to reproduce

1. Go to a project.
2. Add a Deploy a Release step.
3. Expand the Variables section.
4. Click Add Variable.
5. Click into the Variable name field and start typing.
6. See that only the first character is entered and the field no longer has focus.

## Affected versions

**Octopus Server:** 2020.2.4

## Workarounds

Type the name and value somewhere else and copy/paste it into the field.

## Links

Raised internally.

**Comment by kengel100** [comment]
This issue has since been resolved, as verified on Chrome, Firefox and Safari using the latest build.
