### ISSUE TITLE
Docker login on windows fails due to docker cli writing to stderr.

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#6360]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When attempting to deploy to a windows target using the `Run a docker container` step template, and pulling the container from a registry that requires authentication, the deployment will fail due to the windows docker cli writing a warning to stderr on Docker versions >= 17.7.

We use stream redirection on the linux shell script version of this calamari script, but the windows version does not.

## What I expected to happen
Docker deployments on windows hosts work without error.

## Steps to reproduce
1. Configure an authenticated docker feed.
2. Create a process with a `Run a docker container` step template.
3. Deploy to a windows target.
4. See error.

### Screen capture
Windows:
![image](https://user-images.githubusercontent.com/49404281/81570928-3b136080-936f-11ea-91f5-1aa856577a10.png)

Linux:
![image](https://user-images.githubusercontent.com/49404281/81570951-45cdf580-936f-11ea-9b77-637eb21570e8.png)

### Log exerpt
```
09:35:55   Verbose  |         Docker version 19.03.5, build 2ee0c57608
09:35:55   Error    |         docker : WARNING! Your password will be stored unencrypted in octo-docker-configs\config.json.
09:35:55   Error    |         At C:\Octopus\Work\20200428073502-1040257-3\Octopus.DockerPull.ps1:14 char:32
09:35:55   Error    |         + ... rPassword | docker login --username $dockerUsername --password-stdin  ...
09:35:55   Error    |         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
09:35:55   Error    |         + CategoryInfo          : NotSpecified: (WARNING! Your p...gs\config.json.:String) [], RemoteException
09:35:55   Error    |         + FullyQualifiedErrorId : NativeCommandError
09:35:55   Error    |         Failed to download package etc/ico-scu-id4 v1.0.1 from feed: 'https://dockerregistry.implico.com/'
09:35:55   Error    |         Unable to pull Docker image
09:35:55   Verbose  |         Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20200428073502-1040257-3 exited with code 1
09:35:55   Verbose  |         Exit code: 1
```

## Affected versions

**Octopus Server:** 

## Workarounds
1. Use anonymous access/IP whitelists to access the docker registry without authentication (if possible/appropriate).
2. Use a custom version of Calamari (https://github.com/OctopusDeploy/Calamari) with modifications to https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari.Shared/Integration/Packages/Download/Scripts/DockerPull.ps1 
3. Deploy to linux docker hosts (if possible/appropriate).

## Links
(Internal Link) https://secure.helpscout.net/conversation/1148570556/63695?folderId=557082
https://help.octopus.com/t/docker-steps-are-failing-with-newer-powershell/23213/3

**Comment by mcasperson** [comment]
Ensuring `docker-credential-wincred.exe` is on the system path (download from https://docs.docker.com/engine/reference/commandline/login/#credentials-store) may resolve this issue.

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docker steps on Windows fail due to login warning](https://trello.com/c/7BIJmbOh/3258-docker-steps-on-windows-fail-due-to-login-warning)

**Comment by Waldo000000** [comment]
Release Note: Prevent Docker login warning from causing deployments to fail on Windows
