### ISSUE TITLE
Support object parameter defaults in ARM templates entered as JSON

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6386]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The Deploy an Azure Resource Manager template step cannot be saved when the template JSON contains object parameters with default values.

## Steps to reproduce

1. Create a Deploy an Azure Resource Manager template step
2. For the Template Source, select Source code, then Add source code
3. In the template, add a parameter of type object and provide some value for defaultValue, e.g.:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "VNetSettings": {
      "type": "object",
      "defaultValue": {}
    }
  },
  "resources": []
}
```

4. Click save

### Screen capture

![image](https://user-images.githubusercontent.com/20388190/82849871-43f25d80-9f3d-11ea-8ff2-6fa34b9b03d8.png)

## Affected versions

Reported and reproduced in **Octopus Server:** 2020.2.7

## Workarounds

1. Remove default values from any object parameters.

2. Store the source code as a file in a package and call that instead of using inline source code.

## Links

Source: https://secure.helpscout.net/conversation/1174306709/65093/ (private link)

**Comment by KennethBates** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React error when rendering summary for ARM template object parameter](https://trello.com/c/R1Rsw5uP/3301-react-error-when-rendering-summary-for-arm-template-object-parameter)

**Comment by Waldo000000** [comment]
Release note: Fix to support object parameter default values in ARM templates entered as JSON

**Comment by Waldo000000** [comment]
Fixed in https://github.com/OctopusDeploy/OctopusDeploy/commit/4d8535371700d3a5555ddb6a0dcee5390f689c90
