### ISSUE TITLE
Can't edit unscoped variables in a set with VariableEditUnscoped if LibraryVariableSetEdit is scoped to environment

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6393]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a user has unscoped VariableEditUnscoped permission, where their LibraryVariableSetEdit permission is scoped to an environment, they're unable to edit unscoped variables within a set. 

## What I expected to happen

The user should be able to edit the unscoped variables in the set. The VariableEditUnscoped permission's description in the UI says "Edit non-environment scoped variables belonging to a project or library variable set" indicating this setup should work.

## Steps to reproduce

1. Grant a user VariableEditUnscoped permission, as well as an environment-scoped LibraryVariableSetEdit permission
2. As this user, view a variable set that has an unscoped variable defined within it
3. The user is unable to edit the unscoped variable.

### Screen capture

Setup of user's permissions with scoped LibraryVariableSetEdit:

![LibraryVariableSetEdit_scoped_to_env](https://user-images.githubusercontent.com/20388190/83206241-c83e1e00-a193-11ea-8a2c-96c865c8aa21.png)

This results in the user being unable to edit unscoped variable in the set:

![uneditable_unscoped_var](https://user-images.githubusercontent.com/20388190/83206252-cf652c00-a193-11ea-9dda-67c2342fd2b3.png)

Removing the environment scoping of LibraryVariableSetEdit:

![LibraryVariableSetEdit_unscoped](https://user-images.githubusercontent.com/20388190/83206268-da1fc100-a193-11ea-97bb-fed408bd582b.png)

Results in the user being able to edit the unscoped var in the set:

![Editable_unscoped_var](https://user-images.githubusercontent.com/20388190/83206282-e1df6580-a193-11ea-96e0-5d8f2d562424.png)

## Affected versions

Reported in **Octopus Server:** 2020.1.15 and reproduced in 2020.2.9.

Unable to reproduce this in 2019.13.7 (unscoped variables are editable with these permissions) so it seems to be a regression as part of the breaking changes made to variable set permissions in 2020.1.2 detailed in this blog post.

https://octopus.com/blog/libraryvariableset-permission-changes

## Workarounds

The only workaround I can see is to remove the environment scoping of the LibraryVariableSetEdit permission, but that's likely not ideal.

## Links

Source: https://help.octopus.com/t/user-cannot-edit-unscoped-variable-even-when-he-has-the-permission/25147/3

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can't edit unscoped variables in a set with VariableEditUnscoped if LibraryVariableSetEdit is scoped to environment](https://trello.com/c/mZArt167/3315-cant-edit-unscoped-variables-in-a-set-with-variableeditunscoped-if-libraryvariablesetedit-is-scoped-to-environment)

**Comment by KennethBates** [comment]
This behavior is in fact as designed. Previously, users who had LibraryVariableSetEdit permission scoped to only a specific environment (e.g. UAT) were able to edit unscoped library variables and thereby potentially affect production deployments (because unscoped variables can apply to all environments).

As a way forward in this kind of case, the more secure way to model these variables is to duplicate the unscoped variables values in the library set, scoping one to the environment(s) that these users should have access to (e.g. UAT) and the other to the environment(s) that they should not be allowed to affect (e.g. Production).

**Comment by loyke0** [comment]
While I understand the concern for security, it feels to me that something is not right there.
If a user has the "VariableEditUnscoped" permission, it feels like he should actually have the right to do so. If not, this permission seems useless at best, confusing/misleading at worst.
