### ISSUE TITLE
Unable to use FindName overload on projecttriggers in API

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6399]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If any scheduled triggers exist any project then attempting to use FindName() or FindAll will fail.

## What I expected to happen

Triggers that match the name or all triggers should be returned

## Steps to reproduce

1. Create a deployment target trigger in a project
2. Run a script to retrieve all triggers e.g.
```
$endpoint = New-Object Octopus.Client.OctopusServerEndpoint $octopusURI,$apikey 
$repository = New-Object Octopus.Client.OctopusRepository $endpoint

$triggers = $repository.ProjectTriggers.FindAll()
```
3. Add a scheduled trigger to a project
4. Re-run the same script

### Log exerpt
```
Exception calling "FindAll" with "0" argument(s): "Unable to process response from server: Requested value 'OnceDailySchedule' was not found.. Response content: {
  "ItemType": "ProjectTrigger",
  "TotalResults": 5,
  "ItemsPerPage": 30,
  "NumberOfPages": "
At line:4 char:1
+ $triggers = $repository.ProjectTriggers.FindAll()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : OctopusDeserializationException
```

## Affected versions

**Octopus Server:** 2020.2.10

## Workarounds

None found so far

## Links

[Internal Link](https://secure.helpscout.net/conversation/1182359656/65550?folderId=3252735)

**Comment by TomPeters** [comment]
This occurs if the version of `Octopus.Client` you are using is anything before version `8.0.0`. Closing this as this is not reproducible using more recent versions of `Octopus.Client`.
