### ISSUE TITLE
Frame downloads blocked in Chrome 83 and newer

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#6401]
Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When attempting to download Process JSON (and potentially other areas on Octopus) in Google Chrome 83.0.4103.61 (and newer) you will see the following error in Dev Tools, with the download failing to start:

_Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag 'allow-downloads' is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details._

## What I expected to happen

The download should run as expected

## Steps to reproduce

1. Go to a project
2. View the deployment process
3. Select `Download as JSON` from the overflow menu
4. See error in Chrome Console

_or_

1. Go to Configuration > Audit 
2. Click on `Export` button 
3. See error in Chrome Console

![image](https://user-images.githubusercontent.com/29847178/83590137-65d08d80-a598-11ea-8353-d42c389a183d.png)

## Affected versions

**Octopus Server:** 4.0 > Latest 

## Workarounds

1. Use Firefox (76.0.1 was not affected when I checked)
2. Right click -> Open in new tab (verified for the Variables -> Download as JSON case reported by this customer)

## Links
Intial Report: [Internal link](https://secure.helpscout.net/conversation/1183475490/65624?folderId=557077)
Internal link: https://secure.helpscout.net/conversation/1184938465/65706?folderId=557082

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Downloads via the Portal fail (e.g. Artifacts/packages/variables/project JSON), unless via a new tab/right click](https://trello.com/c/ROWl7jvQ/3303-downloads-via-the-portal-fail-eg-artifacts-packages-variables-project-json-unless-via-a-new-tab-right-click)

**Comment by thedewi** [comment]
Additional context: this affects downloads without the presence of frames, because we use `Content-Security-Policy: sandbox`, which:
```
enables a sandbox for the requested resource similar to the <iframe> sandbox attribute
```

**Comment by thedewi** [comment]
Release Note: Adjusted security to allow downloads in Chrome 83
