### ISSUE TITLE
Paging on audit view does not respect the "By spaces" field

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#6403]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Using the page selector on the audit screen does not include the "By spaces" filter.

## What I expected to happen

The next page of results to be filtered by my current space.

## Steps to reproduce

1. Go to Configuration > Audit.
2. Ensure a space is selected in the By Spaces filter.
2. Open network inspector.
3. Click on the second page of results.
4. Find the request to /api/events and see that Spaces is missing from the url.

## Affected versions

**Octopus Server:** 

2020.3.0

## Links

Raised internally

**Comment by N-lson** [comment]
Duplicate of https://github.com/OctopusDeploy/Issues/issues/7334
