### ISSUE TITLE
Docker Volume Bind Mount

### ISSUE THREAD

**Issue by ziaulislamOctopus** [OctopusDeploy/Issues#6419]
# Prerequisites

- [ ] I have verified the problem exists in the latest version
- [ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ ] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [ ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
While trying to add a Run Docker Container step. If you try to add volume binding, you will not be able to click onto the okay button to proceed with the rest of the process. 

## What I expected to happen

I expect it to allow you to enter the information and click onto the okay button.

## Steps to reproduce

1. Go to ' Run Docker Container step.'
2. Click on 'Add Volume binding'
3. Enter information.

### Screen capture

![ProcessNotLoading](https://user-images.githubusercontent.com/55085140/84140291-45e21380-aa49-11ea-95c3-55f2ed62e4ad.gif)

## Affected versions

2020.2.9
2020.2.11
**Octopus Server:** 

## Links

https://secure.helpscout.net/conversation/1183724191/65642?folderId=557082

**Comment by Silcoish** [comment]
Release Note: Fixed Run a Docker Container step volume mounts never allowing adding of volumes due to validation never passing
