### ISSUE TITLE
Clearing out a parameter with a default value incorrectly shows that it is using the default value

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#6423]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

I have a step template with a default value.  
![image](https://user-images.githubusercontent.com/38642825/84306785-90cf5a00-ab21-11ea-9b44-32021dfbb216.png)

If I don't change the default value the collapsed UI looks like this:
![image](https://user-images.githubusercontent.com/38642825/84306775-8d3bd300-ab21-11ea-85bf-5420ce27e758.png)

I delete value in the text box and hit the `Save` button.
![image](https://user-images.githubusercontent.com/38642825/84306821-a17fd000-ab21-11ea-9cdc-0b36bbde12cf.png)

The UI states to provide a value for that field:
![image](https://user-images.githubusercontent.com/38642825/84306871-b0ff1900-ab21-11ea-8cc5-cde7f05ded12.png)

However, when I expand it, the default value is there, even though I did not try to reset the value to its default value.
![image](https://user-images.githubusercontent.com/38642825/84306909-c4aa7f80-ab21-11ea-9b30-e22484e8b33d.png)

If you try to execute this process, the value of this variable will be missing and the step will likely fail, even though it appears that it has a value.

## What I expected to happen

The parameter value should not display the default value, but instead display an empty or missing value. From here, the user can either enter a value, or click the link to reset its value to the default value.

## Affected versions

**Octopus Server:** 2020.2.x+

## Workarounds

This is more confusing than anything.  It doesn't appear to have any negative side affects.

## Links

Reported on community slack via a private channel.

**Comment by TomPeters** [comment]
Release note: Fixed confusing UX when the value for a parameter is empty
