### ISSUE TITLE
All tenants matching channel scoping are selected by default when deploying release

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6429]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When a channel is scoped to a tenant tag(s), all of the matching tenants are populated by default when deploying a release in that channel. This is risky as it can lead to unintended deployments.

## What I expected to happen

The deploy release page for this release should leave the target tenants empty but only populate the dropdown selections with the matching tenants based on the channel's scoping.

## Steps to reproduce

1. Scope a channel to a tenant tag
2. Create a release in that channel
3. Go to deploy the release
4. See all tenant tags populated by default

### Screen capture

(Showing the default population of the dropdowns)

![tenant_channel_deploy_release](https://user-images.githubusercontent.com/20388190/84720522-96b1b900-afc1-11ea-8b30-33c48d2f6ef7.png)

## Affected versions

Reproduced in **Octopus Server** 2020.2.13

## Workarounds

Make sure to manually update the tenant selection to match where you want to deploy to.

## Links

Source: https://secure.helpscout.net/conversation/1194834012/66130?folderId=557077 (private link)

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.
