### ISSUE TITLE
Legacy Upgrade Helm Chart step templates defaults to v3 

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6433]
The ability to select the Helm version was added to Upgrade Helm Chart steps in 2019.12.2

Upgrade Helm Chart steps created prior to 2019.12.2 did not have the option to select the Helm version.  They assumed it was Helm v2.  

When the Octopus instance is upgraded to >= 2019.12.2 these existing steps should default to Helm V2, as this was the previous behavior.  Instead they are defaulting to V3 and indicating the step has changes even when no changes have been explicitly made.

Reported by https://secure.helpscout.net/conversation/1098551343/58201?folderId=571733 (private link)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Legacy Upgrade Helm Chart steps defaults to v3](https://trello.com/c/MqJAKidg/3359-legacy-upgrade-helm-chart-steps-defaults-to-v3)

**Comment by flin-8** [comment]
The upgrade script for this is [here](https://github.com/OctopusDeploy/OctopusDeploy/blob/eb02b97fe6b41356469b5539076e56e87915db27/source/Octopus.Core/UpgradeScripts/Script0236P5SetHelmVersionOnStep.cs)

It would be worth checking if it's the UI that's playing up.

**Comment by TomPeters** [comment]
This issue only affects step templates - normal Upgrade Helm Chart steps that are not based on step templates should not have been affected by this bug.

**Comment by TomPeters** [comment]
Release Note: Fixed a bug where Upgrade a Helm Chart Step templates created before 2019.12.2 may be using the wrong helm client version
