### ISSUE TITLE
Unable to clear the project logo

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6439]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [ * ] I have verified the problem exists in the latest version
- [ * ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ * ] I have written a descriptive issue title
- [ * ] I have linked the original source of this report
- [ * ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When a logo has been uploaded to a project, users are unable to clear it due to the "Use Default" button acting like a file upload for the project too. 

## What I expected to happen

The logo should be cleared.

### Screen capture

![image](https://user-images.githubusercontent.com/160104/85241278-a6784400-b47e-11ea-993c-fedfbbdcfc9e.png)

![image](https://user-images.githubusercontent.com/160104/85241293-abd58e80-b47e-11ea-9337-36eea352cb6c.png)

## Affected versions

Confirmed happening in 2020.2.13 and 2020.1.13 with chrome and firefox.
Works in 2020.1.13 with internet explorer.

## Workarounds

1. Edit the HTML using Chrome tools, and delete the input box element, choose the "default logo" button on the far right, and hit Save

2. Use the below snippet of API code:
```
$spaceId="ENTER-SPACE-ID"
$projectId="ENTER-PROJECT-ID"
$header = @{ "X-Octopus-ApiKey" = $octopusAPIKey }
$url = "$OctopusURL/api/$spaceId/projects/$projectid/logo"
Write-Host $url
$result = (Invoke-RestMethod "$OctopusURL/api/$spaceId/projects/$projectid/logo" -Method POST -Headers $header)
```

## Links
Internal link: https://trello.com/c/DGZPb96B/3349-unable-to-clear-a-project-logo
Workaround: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1591975378195500?thread_ts=1591975307.195400&cid=CNHBHV2BX

**Comment by mjhilton** [comment]
This was fixed by @YihaoOct in OctopusDeploy/OctopusDeploy#11297

**Comment by YihaoOct** [comment]
Closed by https://github.com/OctopusDeploy/OctopusDeploy/pull/11297

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.1252 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.1252 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.1252 |
| 2022.2+ | _all releases_ |
