### ISSUE TITLE
Deployment step with a target which doesn't have a matching role skips the deployment

### ISSUE THREAD

**Issue by harrisonmeister** [OctopusDeploy/Issues#6444]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

A deployment with a project setting set to **Deployments with no targets are not allowed** and with a deployment process which includes a step that has a role with no matching deployment target skips the step.

## What I expected to happen

I'd expect the step with no matching deployment target to fail the deployment rather than skip the step.

## Steps to reproduce

1. Add a step in the deployment process with a role which has **at least one** matching deployment target.

![image](https://user-images.githubusercontent.com/1418993/85407519-37bce880-b55b-11ea-83e4-e0baa4bc9a9a.png)

2. Add another step in the deployment process with a different role which has **no matching** deployment targets

![image](https://user-images.githubusercontent.com/1418993/85407644-5b802e80-b55b-11ea-87f5-4a00c4f0326c.png)

3. Ensure the project setting of **Deployment Targets** is set to **Deployments with no targets are not allowed**

![image](https://user-images.githubusercontent.com/1418993/85407671-63d86980-b55b-11ea-87d7-a6a23192b612.png)

4. Create a release and deploy, then the deployment of the step with the role with no matching deployment target skips the step.

![image](https://user-images.githubusercontent.com/1418993/85408057-f11bbe00-b55b-11ea-990e-a0925a1ddc4e.png)

user expected this to fail despite there being a warning shown on the deployment page at the bottom)

## Affected versions

**Octopus Server:** 2020.2.X

## Workarounds

Add a script step at the start of the deployment process to validate the roles you expect to be present and fail if any roles have no matching deployment targets:

```powershell
$ApiKey = "API-KEY" # Create a sensitive variable for your ApiKey
$octopusUrl = "http://your-octopus-server-url" # Create a variable for your Octopus URL or use `Octopus.Web.BaseUrl` or `Octopus.Web.ServerUri`

$spaceId = $OctopusParameters["Octopus.Space.Id"]
$projectId = $OctopusParameters["Octopus.Project.Id"]
$releaseVersion = $OctopusParameters["Octopus.Release.Number"]
$header = @{ "X-Octopus-ApiKey" = $ApiKey }

$release = Invoke-RestMethod "$octopusUrl/api/$spaceId/projects/$projectId/releases/$releaseVersion" -Headers $header
$deploymentProcessUrl = $OctopusUrl + $release.Links.ProjectDeploymentProcessSnapshot
$projectDeploymentProcess = Invoke-RestMethod $deploymentProcessUrl -Headers $header

$roles = @()

foreach ($step in $projectDeploymentProcess.Steps)
{        
    $stepTargetRoles = $step.Properties.'Octopus.Action.TargetRoles'
    if( -not ([string]::IsNullOrEmpty($stepTargetRoles))) 
    {
        $stepRoles = $stepTargetRoles.Split(",")

        foreach($stepRole in $stepRoles)
        {
            if (-not ($roles -contains $stepRole)) {
                $roles += $stepRole
            }
        }
    }
} 

foreach($role in $roles)
{
    Write-Host "Looking for machines in $role"
    $machinesInRole = $OctopusParameters["Octopus.Environment.MachinesInRole[$role]"]
    Write-Host "Machines found in role $role : $machinesInRole"
    if( [string]::IsNullOrEmpty($machinesInRole)) {
        Write-Error "Expected at least one machine in role: $role!"
    }
}

```
## Links
Report: https://secure.helpscout.net/conversation/1194985173/66139 (private link)

**Comment by droyad** [comment]
I think this is by design. That setting was intended for situations where there are no steps at all in the process that have targets (or are run on server). It was added so that targets could be dynamically added during deployment.

**Comment by mcasperson** [comment]
The PR at https://github.com/OctopusDeploy/docs/pull/796 explains the options in more details given this is the intended behaviour.

**Comment by droyad** [comment]
The option was introduced here: https://github.com/OctopusDeploy/Issues/issues/2732
