### ISSUE TITLE
Renaming tag set breaks deployment/runbook process overview pages

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#6468]
# The bug

Tenant Tag sets stored in a deployment/runbook process can now be stored as either names / ids as we start getting things ready for git integration. We [fixed a small](https://github.com/OctopusDeploy/Issues/issues/6461) part of this but did not take into account that we can end up with unknown references in our actions when renaming a tag set.

## What I expected to happen

The process overview should still work. It may make sense to show `unknown` chips similar to missing resources for things we don't understand. At the very least we shouldn't error the entire overview page.

## Steps to reproduce

1. Go to a deployment process
2. Scope a step to a tenant tag
3. Save the process
4. Rename the tag set
5. Try and view the process overview and notice the error.

### Screen capture

![image](https://user-images.githubusercontent.com/6700195/86561730-aad74d80-bfa4-11ea-850a-9e97a138fce6.png)

## Affected versions
**Octopus Server: 2020.3.2+**

## Workarounds

The workaround for this is to rename the tag set back to the original name. In order to do this, it may be necessary to look at the response that comes back when viewing the deployment process to determine what the tag set name the process is looking for.

## Links
Reported [internally](https://octopusdeploy.slack.com/archives/CLQNM80U9/p1594014124315600) 
https://trello.com/c/2b5NG0e7/3436-renaming-tenant-tag-set-breaks-process-overview

**Comment by zentron** [comment]
Workaround exists. Name or Id will dissapear soon
