### ISSUE TITLE
Immediate retry in Halibut may cause TCP socket exhaustion in some cases

### ISSUE THREAD

**Issue by uglybugger** [OctopusDeploy/Issues#6482]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

It appears that there is a bug in Halibut that can cause an immediate retry attempt on some forms of TCP connection failure.

Under certain circumstances involving large numbers of polling tentacles, this can cause a large number of reconnection attempts against the Octopus Server in a short period of time, which can lead to socket exhaustion and/or thread starvation in the server.

Triggers for this issue appear to include (but are not necessarily limited to):
- Certificate rotation/thumbprint changes on either Tentacle or Server
- TCP socket resets caused by intermediate firewalls
- Thread starvation on the Octopus Server under already-heavy load.

## Steps to reproduce

1. Deploy an Octopus Server instance with a large number of polling Tentacle instances (1000+).
1. Change the certificate on the Octopus server.
1. Observe the tentacles' CPU usage and the Octopus Server's response times to TCP connections both spike.

## Affected versions

It appears that the affected versions are `2020.1`, `2020.2`, and `2020.3`, but this may be misleading as the behaviour in Halibut has been in existence for years before. Suspicions include potentially that there are no older versions of Octopus being used with sufficiently numbers of polling tentacles to provoke this issue.

## Workarounds

Unknown at present.

## Links

[Issue 1](https://secure.helpscout.net/conversation/1203338483/66583/) (Internal link)
[Issue 2](https://secure.helpscout.net/conversation/1223659603/67455/) (Internal link)
[Slack thread](https://app.slack.com/client/T02G7QA31/CLQNM80U9/thread/CNHBHV2BX-1594681419.107000) (Internal link)

**Comment by flin-8** [comment]
Release Note: Fix issue where a large number of polling Tentacles can significantly slow down Octopus Server
