### ISSUE TITLE
404 when trying to push release to octopus

### ISSUE THREAD

**Issue by Dragas** [OctopusDeploy/Issues#6488]
I've recently started using octopus deploy plugin for jenkins (https://octopus.com/docs/packaging-applications/build-servers/jenkins/pipeline#pack) and CLI tool v. 7.4.1. My octopus server is at version: 2019.3.1; API version: 3.0.0

 I'm trying to deploy releases using the following configuration:

```groovy
                    octopusPushPackage(
                            serverId: 'octopus-internal-server',
                            toolId: 'Default',
                            spaceId: 'Default',
                            verboseLogging: true,
                            overwriteMode: 'FailIfExists',
                            packagePaths: env.newName
                    )
                    octopusCreateRelease(
                            serverId: 'octopus-internal-server',
                            toolId: 'Default',
                            spaceId: 'Default',
                            verboseLogging: true,
                            project: env.projectName,
                            releaseVersion: env.versionString
                    )
```
The plugin does indeed upload and create releases for specific projects, but unlike direct CLI counterpart it throws the following additional message:

```
[2020-07-22T10:33:32.861Z] Creating release...
[2020-07-22T10:33:32.950Z] POST http://octopus.host/api/Spaces-1/releases?ignoreChannelRules=False
[2020-07-22T10:33:33.670Z] GET http://octopus.host/api/Spaces-1/releases/Releases-43984
[2020-07-22T10:33:33.698Z] Release 1.21.0-SNAPSHOT-JENKINS-12 created successfully!
[2020-07-22T10:33:33.731Z] INFO: Octopus CLI exit code: 0
[2020-07-22T10:33:33.796Z] FATAL: Failed to create release: Code 404 - 
```

How come? What is it trying to do? Why doesn't the plugin show all the URLs it tries to query?

**Comment by droyad** [comment]
Hi @realrubberduckdev, as per our [issue template](https://github.com/OctopusDeploy/Issues/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) please contact [our support team](https://octopus.com/support) so that they can triage the issue. You will get a much quicker response as the inbox is monitored and we have staff in UK, US and AU.
