### ISSUE TITLE
Unable to publish runbook from process page

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6490]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

In a Runbook's process page, the `Publish` option (like shown in the following image) isn't available like it should be.

![image](https://user-images.githubusercontent.com/20388190/88243260-2b02f000-ccd3-11ea-887c-6b8aecbb7abd.png)

## Screenshot

![missing_publish](https://user-images.githubusercontent.com/20388190/88243464-d01dc880-ccd3-11ea-847f-9ff868610430.png)

## Affected versions

Reproduced in **Octopus Server** 2020.3.1 & master

## Workarounds

Go to a previous run to publish from there.

## Links

Source: https://help.octopus.com/t/cannot-publish-runbooks/25450

**Comment by MarkSiedle** [comment]
Release Note: UI fixes to get publishing buttons showing in the primary Runbook layouts

**Comment by benjimac93** [comment]
<3
