### ISSUE TITLE
Case sensitivity issue when deploying a Certificate Secret for Kubernetes step

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#6498]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

For Kubernetes steps, [Octopus is populating the Certificate secret values](
https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Kubernetes/Resources/Secret.cs#L131) with a `certificateId` variable. This always contains a capital letter, e.g.

`octopus-certificate-Certificates-1`

As per the [Kubernetes requirements for object names/IDs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/):
```
Most resource types require a name that can be used as a DNS subdomain name as defined in RFC 1123. This means the name must:

contain no more than 253 characters
contain only lowercase alphanumeric characters, '-' or '.'
start with an alphanumeric character
end with an alphanumeric character
```

## What I expected to happen

Octopus should be able to provide a certificateId that matches the Kubernetes requirements.

## Steps to reproduce

1. Create a Kubernetes step
2. Provide a TLS Certificate variable through Octopus Library
3. When deploying, Octopus will create a resource name for the TLS cert such as `octopus-certificate-Certificates-1`

## Affected versions

**Octopus Server:**

2020.3

## Workarounds

No workaround, currently Octopus will always populate the cert ID with a capital.

## Links

Source: https://help.octopus.com/t/kubernetes-ingress-ssl-issue/25465

**Comment by mcasperson** [comment]
This has been fixed in 2020.4.0.
