### ISSUE TITLE
Default variable values do not display on tenant variable screens

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6500]
# The bug
For variable templates that have default values: the value is not shown on the tenant variable screen when a variable value has not been set.

This is an issue with the UI displaying default values, the response from the API is as expected.

## What I expected to happen
The default variable value should be displayed on the tenant variable screen when a value has not been set.

## Steps to reproduce

1. Create a variable template with a default value (either via project variables or library variable sets) and a label
2. Create a tenant and connect the tenant to a project that uses the above variable template
3. Visit the appropriate Tenant > Variables screen (common or project depending on what kind of template you made) and observe that the variable value is empty, or displays the variable label (depending on the variable type)

### Screen capture
Now:
![image](https://user-images.githubusercontent.com/171197/88739245-7444bb00-d17d-11ea-828e-0fb35f2b4af6.png)
Before:
![image](https://user-images.githubusercontent.com/171197/88743829-07cfb900-d189-11ea-99c5-b83afbd96ad6.png)

## Affected versions

**Octopus Server:** Introduced in 2020.3.0-rc.1

## Workarounds

Tenant variables will continue to use the default value during a deployment, this is only a UI behaviour.

## Links

Introduced in https://github.com/OctopusDeploy/OctopusDeploy/pull/6277
Reported in [internal support ticket](https://secure.helpscout.net/conversation/1231723643/67819?folderId=557082), [internal support ticket](https://secure.helpscout.net/conversation/1232134797/67839?folderId=557080), [internal support ticket](https://secure.helpscout.net/conversation/1226543656/67603?folderId=2845830)

**Comment by tothegills** [comment]
Release Note: Default variables are displayed again on tenant variable selection screens

**Comment by hardKOrr** [comment]
I just upgraded to 2020.3.3 from 2020.3.2, existing default variable template values are not being displayed.  New project connections are also not displaying default values for their templates.  Project Template variables without a default value show as being of default value.

**Comment by tothegills** [comment]
@hardKOrr could you please get in touch with support@octopus.com providing screenshots of what you are seeing?

**Comment by hardKOrr** [comment]
@tothegills Thanks, I got in touch with support.  I apparently just needed a cache flush, which I had tried incognito mode in chrome to attempt to not have cache/data conflicts... ctrl + f5 will be my new friend.
Thanks again everyone

**Comment by tothegills** [comment]
@hardKOrr Glad it's working! Had a minor heart attack. :)
