### ISSUE TITLE
Valid Master Key Does Not Work with a New Installation of Octopus Using an Existing SQL DB

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#6507]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

"Please enter a valid master key for the existing database" error when attempting to use a valid Master Key to connect a new installation of Octopus to an existing SQL DB. This happens in 2020.3.1 -> 2020.3.1, 2020.3.2 -> 2020.3.2, but not in 2020.2.16 -> 2020.2.16.

## What I expected to happen

The installer accepts the valid Master Key without error

## Steps to reproduce

Take an existing 2020.2.16 instance, upgrade to 2020.3.1
Backed up and restore the db to a new VM
Make a fresh install of 2020.3.1 on the new VM
Input Master Key when prompted after connecting the restored db.

### Screen capture

![image](https://user-images.githubusercontent.com/63249187/89069996-38a71e00-d342-11ea-91e5-a2f0bfd90f14.png)

## Affected versions

Confirmed on 2020.3.1 and 3030.3.2

**Octopus Server:**

## Workarounds

Use 2020.2.16 or older when moving your Octopus Server to a new machine/VM

## Links

https://trello.com/c/7h9Xa5Lq/3554-master-key-issues

**Comment by alialmaktoum** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Master key issues](https://trello.com/c/7h9Xa5Lq/3554-master-key-issues)

**Comment by MarkSiedle** [comment]
Release Note: Fix regression in Octopus Server Manager to allow using an existing database if the master-key is known
