### ISSUE TITLE
Deployment steps preview missing information in the UI (such as step number, name, and the icon for the type)

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#6520]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

On the "Deploy release" page, the "Deployment steps preview" does not populate all of the step information. See screenshots below.

## What I expected to happen

The "Deployment steps preview" should show the icon for type, step number, and step name with the tentacles nested underneath.

## Steps to reproduce

1. Open Octopus 2020.3.X
2. Project -> Releases -> click on a release -> Deploy To -> make sure an environment is selected

### Screen capture
What it should look like:
![image](https://user-images.githubusercontent.com/63249187/90682377-dd769600-e232-11ea-8935-53bde570fc83.png)

What it looks like with the bug:
![image](https://user-images.githubusercontent.com/63249187/90682454-f67f4700-e232-11ea-8c2e-1604d01d0480.png)

## Affected versions
Likely an issue on all current 2020.3.X+ version. Tested and confirmed on 2020.3.2 and 2020.4.0-ci0428. 

Confirmed this is working as intended on 2020.2.13

## Workarounds

None

## Links

Customers with the issue (internal only)
https://secure.helpscout.net/conversation/1258558024/69245,
https://secure.helpscout.net/conversation/1233275246/67905,
https://secure.helpscout.net/conversation/1262650855/69445,
https://secure.helpscout.net/conversation/1248402219/68734

**Comment by MarkSiedle** [comment]
Release Note: UI fix to show step information in deployment preview
