### ISSUE TITLE
SSH Targets do not respect the configured retry amount for health checks. Fail after one.

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6524]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

SSH Targets dont respect the machine policy retry amount specified. They always fail after one attempt.

## What I expected to happen

I expect the SSH targets to retry the specified amount of times like a normal listening tentacle would.

## Steps to reproduce

1. Create an SSH target
2. Verify connection retries is over 1
3. Take SSH target offline
4. Check health on SSH target and see that it fails after 1 attempt and doesn't retry.

### Screen capture

N/A

### Log exerpt

```
                    |   == Failed: Check deployment target: Linux ==
19:54:34   Verbose  |     Performing health check on machine
19:54:34   Verbose  |     Establishing SSH connection...
19:55:34   Fatal    |     Could not connect to SSH endpoint: Connection failed to establish within 60000 milliseconds.
                    |     Connection failed to establish within 60000 milliseconds.
19:55:34   Verbose  |     Could not connect to SSH endpoint: Connection failed to establish within 60000 milliseconds.
                    |     Connection failed to establish within 60000 milliseconds.
                    |     Could not connect to SSH endpoint: Connection failed to establish within 60000 milliseconds.
                    |     Octopus.Server.Orchestration.Targets.Ssh.SshEndpointConnectionException: Could not connect to SSH endpoint: Connection failed to establish within 60000 milliseconds.
```

## Affected versions

**Octopus Server:** Exists on latest(2020.3.3). I have not attempted any previous versions.

## Workarounds

None.

## Links

Ticket source: https://help.octopus.com/t/details-on-ssh-health-checks/25533/2

**Comment by adrianhowchin** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by adam-mccoy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SSH Targets do not respect the configured retry amount for health checks](https://trello.com/c/gNV3TlJi/3748-ssh-targets-do-not-respect-the-configured-retry-amount-for-health-checks)

**Comment by johnsimons** [comment]
We've got to the bottom of this issue and the confusion is that the machine policy UI needs to be more explicit on what settings apply to what targets.
So in summary not all settings apply to all targets.
Here is how it works:
![image](https://user-images.githubusercontent.com/122651/94104180-c3efec00-fe79-11ea-84c2-56285754086b.png)

We will be working on a fix to this screen to ensure it is clear what target each setting applies to.

**Comment by johnsimons** [comment]
I have raised a new issue for enhancing this screen, https://github.com/OctopusDeploy/Issues/issues/6597

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.
