### ISSUE TITLE
Updating library step template in process requires browser refresh to show changes

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6533]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you make a change to a library step template and update the step in the project's process, the UI will then not display any of the step template information.

## What I expected to happen

All the details would be displayed after an update.

## Steps to reproduce

1. Change a step template and save a new version
2. Navigate to a step that uses the step template
3. Click on Update (depending on what type of change you made, you may need to enter variable info and click Confirm… if the change was only to a parameter name or something then only clicking Update causes this issue).
4. The entire "step template" portion of the UI disappears from the step editor page being displayed.
5. Navigate to another step and then back to the step in question.
6. The step template section will be back, but it will appear to be back in its original state, along with it again showing the warning that "This step is out of date" with the Update button.
7. This can be repeated multiple times and it'll appear that the page is never updating.

### Screen capture

After updating the step:

![step_template_update_missing_section](https://user-images.githubusercontent.com/20388190/90994146-26e03000-e5fb-11ea-83a6-deffbcc7bf47.png)

After refreshing the page in the browser: 

![step_template_updated_after_refresh](https://user-images.githubusercontent.com/20388190/90994151-2a73b700-e5fb-11ea-8c3a-a501b107ae50.png)

## Affected versions

Replicated in **Octopus Server** 2020.3.3

## Workarounds

Manually refresh the page in the browser.

## Links

Source: https://secure.helpscout.net/conversation/1260809584/69394?folderId=557077 (private link)

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.
