### ISSUE TITLE
Tenant Variables page not retaining collapsed state

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6537]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When opening the tenant variables for a project, all linked environments will expand by default. If the collapse all option is used as soon as the project is expanded, all environments immediately expand again too instead of remaining collapsed. This is causing significant slowness on servers that have a large number of environments and tenant variables.

These sections remained collapsed in previous versions.

## What I expected to happen

When clicking collapse all, all options should remain collapsed until manually expanded.
Preferably, everything would default to being collapsed when the page is initially loaded.

## Steps to reproduce

1. Create a tenant and link a few variables and environments to it
2. Navigate to Tenant Variables > Project Variables
3. See all variables expanded
4. Select Collapse All
5. Expand a single project
6. See all environments linked to that project automatically expand

### Screen capture

Previous versions would keep the environments collapsed:
![image](https://user-images.githubusercontent.com/20085569/91281949-94699900-e780-11ea-9263-12942a6aa592.png)

## Affected versions

**Octopus Server:** 2020.3.2

## Workarounds

No permanent workaround, users have to manually collapse each environment.

## Links

[Internal Link](https://secure.helpscout.net/conversation/1263498022/69504?folderId=3252735)

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by FinnianDempsey** [comment]
Currently when expanding a Tenant's Project Variable for a Project, all the Environment variables get expanded by default. 

See screenshot of current default when expanding a project:
<img width="1306" alt="Screen Shot 2021-07-05 at 13 06 49" src="https://user-images.githubusercontent.com/78527975/124412524-0f80e000-dd92-11eb-838e-342b5cc4bbd8.png">

How I would expect it to behave is that the Environment variables are collapsed by default:
<img width="1325" alt="Screen Shot 2021-07-05 at 13 06 56" src="https://user-images.githubusercontent.com/78527975/124412568-27f0fa80-dd92-11eb-9ad1-4f3e6d285232.png">

**Comment by octokhor** [comment]
Issue from 2 years ago - no other reports since. Closing this for now.
