### ISSUE TITLE
TypeError when deleting machine policy

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6553]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When deleting a machine policy via the web portal, the user is not redirected back to the list of machine policies, but instead keeps you on the deleted machine policy's `details` tab which fails with the following TypeError.

## What I expected to happen

The user would be sent to the Machine Policies tab in the UI after deleting a machine policy.

## Steps to reproduce

1. Delete a machine policy
2. See error

### Screen capture

![typeerror_delete_machine_policy](https://user-images.githubusercontent.com/20388190/92338056-f5825c80-f0f0-11ea-910f-74c0c520506a.png)

### Log exerpt

```
An unexpected error occurred in Octopus v2020.4.0-rc0004: "TypeError: Cannot read property 'Id' of null"
in MachinePolicyLayoutInner
in DataBaseComponent
in n
in MachinePolicyLayout
in Page
in p
in RenderWithPage
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in InfrastructureRoutes
in r
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in t
in RootRoutes
in withRouter(RootRoutes)
in SpaceLoader
in WithPersistedSpace
in p
in withRouter(Connect(WithPersistedSpace))
in div
in StandardLayoutInternal
in p
in t
in ErrorBoundaryInternal
in ReloadableRoute
in SecureRoute
in t
in t
in t
in DevToolsContextProvider
in ClientConnector
in App
in Unknown
in t
in Theme
in f
in ErrorBoundaryInternal
in AppContext
```

## Affected versions

Reported in Octopus server 2020.3.4 and reproduced in 2020.4.0

## Workarounds

Ignore the error message, as the deletion is successful.

## Links

Reported here: https://help.octopus.com/t/machine-policy-page-bugs/25623

**Comment by andrewabest** [comment]
Release note: Fixes error displayed when deleting machine policies
