### ISSUE TITLE
configure-tentacle.sh script doesn't accept spaces in some values

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6574]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When working through the script certain fields like Spaces and Name allow you to enter a value with a space included but will truncate the value when generating the register-with command. Enclosing the value in "" or '' doesn't make a difference.

## What I expected to happen

The register-with command can accept these values with spaces in, so the script should not truncate them.

## Steps to reproduce

1. Run configure-tentacle.sh
2. For the fields Spaces and Name enter values with spaces e.g. New Space and New Machine
3. Check the register-with line generated at the end of the script, the values will have been truncated to "New"

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/92894574-9edb9200-f412-11ea-8f8c-a0fca3da182e.png)

## Affected versions

**Octopus Server:** All

## Workarounds

When the script reaches the end, it outputs the commands that it is going to run. If you copy these commands and amend the truncated value to the correct one. You can then manually run the commands successfully.

**Comment by andrewabest** [comment]
Release Note: fixes issue where tentacle and space names would be truncated when running `configure-tentacle.sh`
