### ISSUE TITLE
Rolling Deploy a Release steps don't continue to next targets if any manual intervention or failure guidance is required

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6576]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When a Deploy a Release step is configured in a rolling deployment, the child deployments target each machine individually. If one of those machines requires a manual intervention or guided failure assistance, any subsequent child deployment will not be executed, instead the result of the initial intervention will be carried forward to all subsequent child deployments.

## What I expected to happen

The next machine in the rolling deploy would still trigger the child deployment for that machine.

## Steps to reproduce

1. Create a Deploy a Release step in a rolling deployment (to deploy to 2+ machines)
2. In the child project, enable guided failure and ensure the deployment will fail
3. Deploy the parent project
4. Click `Ignore` on the guided failure prompt in the child project
5. See the next machines in line don't have the child deployment attempted

### Screen capture

![deploying_release_rolling](https://user-images.githubusercontent.com/20388190/93155498-97392780-f749-11ea-9741-decea001b88f.png)

(It should include the line `Deploying release 0.0.15 of project 'Child A'. View deployment` to indicate the deployment started)

## Affected versions

Reproduced in **Octopus Server** 2020.4.0

## Workarounds

Define the window size in the parent project to match the number of machines. This lets the deployment task to be created and queued which will be picked up after ignoring the guided failure on the first machine.

Additional note: If you select `Exclude machine from deployment` in guided failure on the rolling child deployment, the parent deployment task log reports `Object reference not set to an instance of an object.` Since the deployment is only targeting one machine, this option shouldn't be available.

## Links

Reported here: https://help.octopus.com/t/deploy-a-release-is-skipping-targets-after-manual-intervention/25668

**Comment by andrewabest** [comment]
Release Note: Fixes issue in which child deployment interventions in rolling deployments would short-circuit subsequent child deployments
