### ISSUE TITLE
Linux tentacle doesn't show current version in connectivity tab

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6580]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When checking a Linux Tentacle target Connectivity page the version is displayed as 0.0.0

## What I expected to happen

The correct version should be displayed

## Steps to reproduce

1. Configure a Linux Tentacle
2. Select the Tentacle within Infrastructure and browse to Connectivity page
3. Version will display as 0.0.0

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/93326695-21988e80-f811-11ea-8f71-5b7c6f4e10ef.png)

## Affected versions

**Octopus Server:** 2020.3.0+

## Workarounds

This is purely a UI issue, the tentacle is still working fine.

## Links

https://help.octopus.com/t/linux-listening-tentacles-reporting-version-0-0-0/25676

**Comment by calverp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Linux tentacle doesn't show current version in connectivity tab](https://trello.com/c/8Dc98Uko/3591-linux-tentacle-doesnt-show-current-version-in-connectivity-tab)

**Comment by droyad** [comment]
Could you confirm that the Tentacle's machine policy isn't set to "Connectivity Only"? Also if you could attach the health check log that would be helpful.

**Comment by calverp** [comment]
> Could you confirm that the Tentacle's machine policy isn't set to "Connectivity Only"? Also if you could attach the health check log that would be helpful.
> 
> Which version of Tentacle is it? Is it dockerised?

It was running the Default health check.
Health check log attached.
Tentacle version 5.0.9.
The tentacle was running on an Ubuntu VM, no docker.
[ServerTasks-634.log.txt](https://github.com/OctopusDeploy/Issues/files/5237064/ServerTasks-634.log.txt)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6800 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6800 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6800 |
| 2022.1+ | _all releases_ |
