### ISSUE TITLE
The Start Trigger and Package Requirement options don't appear at the right times

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6584]
# The bug

[Example](https://master.octopushq.com/app#/Spaces-1002/projects/package-requirement/deployments/process/steps?actionId=d7c557b9-a71c-497e-99cb-3c56dacfef60) and showing the previous behaviour [example](https://robw.tentaclearmy.com:8085/app#/Spaces-1/projects/test/process/step/1bd40ef1-76f1-4ae0-be19-72c3d628d5ae)

From my understanding the `Start Trigger` should show up for all except the first step.
Currently the `Start Trigger` shows on the first step.

The `Package Requirement` option should show up for all non-package steps that come before the first step with a package. There might be a little more subtly than that.

Currently it looks like the `Package Requirement` section is only showing up for rolling steps that have a package ([Example](https://master.octopushq.com/app#/Spaces-1002/projects/test/deployments/process/steps?actionId=7e1fdf10-8ac9-48df-9421-86fcbf4b72f8))

From memory the `Package Requirement` feature was added after we moved package acquisition to later in the process. This option then gave the user to force acquisition before a step. This would be used to help reduce down time as you don't want acquisition to run after you take your website offline.

 I'm not 100% sure how `AfterPackageAcquisition` fits into it. @tothegills or @michaelnoonan might remember.

## Steps to reproduce

1. Create a new project
2. Add a script step with no package

### Screen capture

![image](https://user-images.githubusercontent.com/1687639/93537844-f8ead300-f98f-11ea-9235-c88647c394ee.png)

### Expected
`2019.5.12`
![image](https://user-images.githubusercontent.com/1687639/93537967-423b2280-f990-11ea-8e55-a13b161cdf82.png)

## Affected versions

**Octopus Server:** Likely `2020.2` onwards

## Workarounds

Set properties via the API. Add a fake step that requires a package as the first step.

## Links

[PR that added Package Requirement](https://github.com/OctopusDeploy/OctopusDeploy/pull/1636)

**Comment by michaelnoonan** [comment]
> I'm not 100% sure how AfterPackageAcquisition fits into it. @tothegills or @michaelnoonan might remember.

Sorry, I really don't have any recollection of that change.
