### ISSUE TITLE
Deploy to IIS step cannot create virtual directory with leading period e.g. \.well-known\

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#6586]
# The bug

When using the Deploy to IIS step and configuring a virtual path, Octopus fails to create the directory if it has a leading period. 

## Steps to reproduce

Configure and deploy IIS website where Octopus is expected to create a virtual directory containing leading `.` such as `\.well-known\`

### Screen capture

![image](https://user-images.githubusercontent.com/18252832/93728351-edeba900-fc02-11ea-90ec-d469bc59e0db.png)

### Log exerpt

```
11:35:09   Info     |       Making sure a Virtual Directory "\.well-known\" is configured as a child of "ParentSite" at "C:\Octopus\Applications\Dev\json\1.0.1_3"...
11:35:09   Verbose  |       Acquired mutex Global\Octopus-IIS-Metabase-Mutex
11:35:09   Verbose  |       Looking for the parent Site "ParentSite" at "IIS:\Sites\ParentSite"...
11:35:09   Info     |       "\.well-known\" does not exist. Creating Virtual Directory pointing to IIS:\Sites\ParentSite\.well-known ...
11:35:09   Verbose  |       Acquired mutex Global\Octopus-IIS-Metabase-Mutex
11:35:09   Info     |       Attempt 1 of 5 failed: Parent node has no children of type VirtualDirectory.
11:35:09   Info     |       Parameter name: path
11:35:09   Info     |       Waiting for 2 seconds before retrying...
11:35:11   Info     |       Retrying...
11:35:11   Info     |       Attempt 2 of 5 failed: Parent node has no children of type VirtualDirectory.
11:35:11   Info     |       Parameter name: path
11:35:11   Info     |       Waiting for 2 seconds before retrying...
11:35:13   Info     |       Retrying...
11:35:13   Info     |       Attempt 3 of 5 failed: Parent node has no children of type VirtualDirectory.
11:35:13   Info     |       Parameter name: path
11:35:13   Info     |       Waiting for 2 seconds before retrying...
11:35:15   Info     |       Retrying...
11:35:15   Info     |       Attempt 4 of 5 failed: Parent node has no children of type VirtualDirectory.
11:35:15   Info     |       Parameter name: path
11:35:15   Info     |       Waiting for 2 seconds before retrying...
11:35:17   Info     |       Retrying...
11:35:17   Error    |       InvalidArgument: Parent node has no children of type VirtualDirectory.
11:35:17   Error    |       Parameter name: path
11:35:17   Error    |       At C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1:304 char:4
11:35:17   Error    |       +             New-Item $fullPathToLastVirtualPathSegment -type VirtualD ...
11:35:17   Error    |       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:35:17   Error    |       at <ScriptBlock>, C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1: line 304
11:35:17   Error    |       at Core-Execute-WithRetry, C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1: line 125
11:35:17   Error    |       at Execute-WithRetry, C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1: line 147
11:35:17   Error    |       at <ScriptBlock>, C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1: line 303
11:35:17   Error    |       at <ScriptBlock>, C:\Octopus\Applications\Dev\json\1.0.1_3\Bootstrap.Octopus.Features.IISWebSite_BeforePostDeploy.ps1: line 1694
11:35:17   Error    |       at <ScriptBlock>, <No file>: line 1
11:35:17   Error    |       at <ScriptBlock>, <No file>: line 1
11:35:17   Verbose  |       Deleting 'C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1'
11:35:17   Verbose  |       Calamari.Commands.Support.CommandException: Script 'C:\Octopus\Applications\Dev\json\1.0.1_3\Octopus.Features.IISWebSite_BeforePostDeploy.ps1' returned non-zero exit code: 1
11:35:17   Verbose  |       at Calamari.Deployment.Conventions.FeatureConventionBase.ExecuteFeatureScripts(RunningDeployment deployment, String feature, HashSet`1 embeddedResourceNames)
11:35:17   Verbose  |       at Calamari.Deployment.Conventions.FeatureConventionBase.Run(RunningDeployment deployment)
11:35:17   Verbose  |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
11:35:17   Verbose  |       at Calamari.Deployment.ConventionProcessor.RunConventions()
11:35:17   Error    |       Running rollback conventions...
```

## Affected versions

**Octopus Server:**

Reproduced on 2020.3.3

## Workarounds

Manually create virtual directory via script before the Deploy to IIS step and Octopus will recognise that it exists and not fail.

## Links

Private Source: https://secure.helpscout.net/conversation/1286469094/70757?folderId=557077

**Comment by adam-mccoy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Calamari can't create IIS virtual directories which start with a dot](https://trello.com/c/pa94iPq3/3746-calamari-cant-create-iis-virtual-directories-which-start-with-a-dot)

**Comment by paulegradie** [comment]
Calamari executes virtual directory creation during IIS deployments using Powershell. We recreated the issue, however it seems that Powershell doesn't support the creation of virtual directories in the website root when the name begins with a dot.  We explored both `New-Item` and `New-WebVirtualDirectory` cmdlets, however we failed to identify any way of overcoming this apparent limitation.

@danielfischeroctopus - could share the script you used with the workaround you found?

 I'm going to close this issue for now since there is a workaround.

**Comment by paulegradie** [comment]
Update: 

Creating virtual directories with a name that leads with a dot is a known limitation of Powershell. The workaround for this limitation is to create a physical directory with the same name, e.g. `.well-known`, prior to attempting to create the virtual directory. 

You can achieve this by using a preceding script step, or potentially a predeployment script, to create this physical directory. For example, the deployment script step might contain an inline script with the following content:

```
cd #{CustomInstallationDirectory}
mkdir .well-known
```
where `#{CustomInstallationDirectory}` is an Octopus octostache-style variable that contains the path to the physical directory where your site or application will be installed to. This variable would be set under [project variables](https://octopus.com/docs/projects/variables).

In the IIS Deployment step, you can then configure the IIS Web Site and Application Pool section similar to to following image, as you would normally do:

![image](https://user-images.githubusercontent.com/30226456/96517084-ff80a900-12b3-11eb-8105-42db4e385ca4.png)

If anyone attempts this solution and runs into issues, please don't hesitate to reach out to us on our support channels. For more general information about deploying to IIS, you can [visit our support documentation](https://octopus.com/docs/deployment-examples/iis-websites-and-application-pools).

Happy Deployments!
