### ISSUE TITLE
Allow scheduled triggers to use tenant tags

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6594]
Scheduled triggers for deployments and runbooks can be configured to run against tenants, but the each tenant must be configured specifically:

![image](https://user-images.githubusercontent.com/113759/94142038-fcf78300-feb0-11ea-8d9b-2384fc1b3cb6.png)

This is painful to manage.
 It would be a powerful use of tenant-tags to be able to configure the trigger to use tags. 

Reported by: https://help.octopus.com/t/scheduled-runbook-trigger-missing-full-featured-tenant-selector/24709

**Comment by droyad** [comment]
This feature presents a bit of a security conundrum. 

Scenario:
- A user has access to `Tenant A` 
- The user does not have permissions to edit, depoy (or even see) `Project 1`
- `Project 1` is setup with a scheduled trigger that deploys to all tenants with `Tag Z`.

That user can add `Tag Z` to `Tenant A`. `Project 1` will now start deploying to `Tenant A`.

In other words, if a trigger is setup to run based on tags, any user with edit access to a tenant can cause that trigger to fire for that tenant even if they couldn't edit that trigger themselves.

A few possible solutions to this:
1. Accept as a known limitation of our security model, the user setting up the trigger will need to be aware of this
2. Don't allow the addition of a tag to a tenant unless the user had deploy privileges for all projects that use that tag as a trigger
3. Add permissions to tags

**Comment by MJRichardson** [comment]
I support option 1. 

I don't see any contradiction/limitation.  The argument could be made, what's the point of tags if we don't allow using them to treat tenants as a group?

**Comment by dvdgutzmann** [comment]
> I support option 1.
+1

Tags are a means to shoot oneself in the foot, agreed. With great power comes great responsibility.  That said, option 1 represents the current status quo in terms of tags. 

Suppose a tag controls whether a deployment step in `Project 1` is executed or not. The user who only has the right to add tags to `Tenant A`, but does not even see `Project 1`, can still add `Tag Z` to `Tenant A` today without any permissions check regarding the actions in the deployment step. And we are all totally fine with that  :)

**Comment by droyad** [comment]
> tag controls whether a deployment step

The difference I see in that scenario is that someone with `deploy` permission is choosing to deploy to that tenant. They should (theoretically) verifying that the process is right for that tenant.

> treat tenants as a group
If you use tags it would make scoping permissions (other than `Tenant*`) to a particular tenant ineffective.

Thinking further about this, if I don't have `deploy` permission for a given `Tenant`, I can't go and manually deploy a release to that tenant. I also (currently) can't create a trigger for that `Tenant`. With this change you can get around these restrictions if the Tenant has a tag.

**Comment by zentron** [comment]
Unlikely to be actioned given priorities. Ticket can be reopened if\when we action

**Comment by EliaSaSe** [comment]
I would like the feature too. For those who also want to upvote, I found the relevant user voice here: 

https://octopusdeploy.uservoice.com/forums/170787-product-feedback/suggestions/42607861-add-tenant-tag-support-to-runbook-scheduling

**Comment by ryanrousseau** [comment]
Recently raised as a request in community slack.

**Comment by twerthi** [comment]
Feature requested by customer 2/24.
