### ISSUE TITLE
Disabled child step isn't greyed out on process overview

### ISSUE THREAD

**Issue by charles-hague-octopus** [OctopusDeploy/Issues#6615]
# Prerequisites

- [ x ] I have verified the problem exists in the latest version
- [ x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ x ] I have written a descriptive issue title
- [ x ] I have linked the original source of this report
- [ x ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Disabled steps aren't greyed out in the "Process" view if they're part of a rolling deployment. Disabled steps that aren't part of a rolling deployment are greyed out correctly. Both types of disabled steps are greyed out correctly in the process editor itself.

## What I expected to happen

Disabled child steps should be greyed out like normal disabled steps.

## Steps to reproduce

1. Create 2 child steps and disable one of them.
2. The child step appears disabled when you are editing a step
3. Go back to the process overview - see that the step isn't greyed out

### Screen capture

Editing:

<img width="285" alt="Screenshot 2020-10-08 at 09 50 59" src="https://user-images.githubusercontent.com/71703850/95439639-cd845400-094f-11eb-94d4-5df4d6f08618.png">

Overview:

<img width="553" alt="Screenshot 2020-10-08 at 09 49 35" src="https://user-images.githubusercontent.com/71703850/95439651-d2490800-094f-11eb-9bc6-2d9afe4fef30.png">

### Log exerpt

Not applicable.

## Affected versions

**Octopus Server:** 2020.3 onwards (confirmed on 2020.4.2)

## Workarounds

Use the edit mode to find disabled steps.

## Links

https://secure.helpscout.net/conversation/1304004503/71623?folderId=4115243

**Comment by charles-hague-octopus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disable child step isn't grayed out on process overview](https://trello.com/c/bYJ20LW9/3784-disable-child-step-isnt-grayed-out-on-process-overview)

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by AndyWardUST** [comment]
Is there any update on when this bug may be addressed? We have currently taken the decision that we will not be rolling the upgrade into production as managing the comms for 1k+ deployments would be too awkward for a simple ui bug that may confuse the users

**Comment by ankithkonda** [comment]
Release note: Disabled child steps are greyed out on both the process editor and overview pages

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.0-rc.3 |
| 2021.1 | 2021.1.6091 |
| 2021.2+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.0-rc.3 |
| 2021.1 | 2021.1.6091 |
| 2021.2+ | -all releases- |
