### ISSUE TITLE
When using an Azure or Terraform step and you use a script named deploy.* predeploy.* or postdeploy.*, it will cause the deployment to fail.

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6621]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
 
When you are using an Azure or Terraform step, and you name your script deploy.* , predeploy.* , or postdeploy.*, the deployment will fail.

## What I expected to happen

I would expect the deployment to not fail.

## Steps to reproduce

1. Bundle a script called deploy.ps1 in a package
2. Run this script in an azure/terraform script step

### Screen capture

![image](https://user-images.githubusercontent.com/63259411/95597923-469dad00-0a1d-11eb-943a-05c632ecee5b.png)

![image](https://user-images.githubusercontent.com/63259411/95597791-1524e180-0a1d-11eb-9076-f14900782c7a.png)

### Log exerpt

Logs in the screen capture above

## Affected versions

**Octopus Server:** 2020.4.2 is confirmed

## Workarounds

Rename the script to something that isn't deploy, predeploy, or postdeploy.

## Links

Ticket: https://help.octopus.com/t/script-parameters-missing-at-deploy-time/25789/3

**Comment by benPearce1** [comment]
Release note: Fixed issue with executing Azure script step from package when script it named `(pre|post)deploy.ps1`

**Comment by iernie** [comment]
We still experience this issue in 2020.4.5

**Comment by benPearce1** [comment]
Hi @iernie,

You are right, this did not get correctly resolved in 2020.4.5. Apologies for the inconvenience.
We should have a fix out shortly.

Ben
