### ISSUE TITLE
Browser console error when loading dashboard

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6625]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When loading the dashboard it seems to be trying to resolve https://<serverURL>/outdated-browser.js and receiving a 404.
This isn't actually causing any problems.

## What I expected to happen

https://<serverURL>/outdated-browser.js should resolve correctly.

## Steps to reproduce

1. Open browser dev tools (F12) to the console tab
2. Refresh the Octopus dashboard
3. Check the error presented

## Affected versions

**Octopus Server:** 2020.4+

## Workarounds

None required.

## Links

[Internal Link](https://octopus.zendesk.com/agent/tickets/1511)

**Comment by calverp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Browser console error when loading dashboard](https://trello.com/c/Ms4toaim/3786-browser-console-error-when-loading-dashboard)

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by MarkSiedle** [comment]
Fixed during sharpening. This will be rolled out in the next releases for 2020.4 and 2020.5 etc.
