### ISSUE TITLE
IIS settings revert to default when cloning the step

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6648]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When cloning an IIS deploy step the settings for Application Pool, Bindings and IIS Authentication settings can revert to their defaults in the original step.

## What I expected to happen

The settings should be retained

## Steps to reproduce

- In an IIS step, set the IIS Auth to Anonymous only and Save. Can also configure bindings and amend App Pool settings.
- Clone the step into the same project
- Select the new step
- Select the original step
- The IIS Auth, Bindings and App Pool settings will have reverted to default

## Affected versions

**Octopus Server:** 2020.4.0+

## Workarounds

Save the process after creating the clone, but before selecting the clone.
e.g.

- In an IIS step, set the IIS Auth to Anonymous only and Save
- Clone the step into the same project
- Select Save whilst the original step is still selected
- Can select either the new or old step now and the settings will not revert

## Links

[Internal Link](https://octopus.zendesk.com/agent/tickets/21905)

**Comment by andrew-moore-octo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cloning Deploy to IIS step modifies original step](https://trello.com/c/uHDRDzvz/3871-cloning-deploy-to-iis-step-modifies-original-step)

**Comment by matt-richardson** [comment]
Release Note: Fixed steps reverting to default values when changing steps without saving
