### ISSUE TITLE
Custom script steps do not evaluate release notes or build information when using dynamic packages

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#6652]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you create a Custom Script Step based on "Deploy a Package" and set the templates PackageName to a variable (e.g #{PackageName} ) which is also set within the "Parameters" section - although the package deploys as expected the release notes evaluate to empty. 

## What I expected to happen

Using the above setup - I expect the release notes and build information to appear as usual.

## Steps to reproduce

1. Create a Custom Script template based off of "Deploy a Package"

2. Set the Step Package details to a variable. For example #{SomePackageVariable}

3. Set a Parameter with a name reflecting the variable entered in step 2. 

4. Create a project and attach the new Custom Script Template

5. Fill the Package Value in with a valid Package available from the BuiltIn feed and whatever other minimum details are required.

6. Click on Create Release and set the "Release Notes" template to use the default release notes template.

7. Click "Save" - The release notes and Build information will not appear - however deploying the package will still work fine.

### Screen capture

Screenshots in order of reproduction
**Step 2**
![ScriptTemplate1](https://user-images.githubusercontent.com/5361797/97531605-3ff0cd00-1a00-11eb-9fce-9108d7db6e89.png)

**Step 3**
![StepTemplate2](https://user-images.githubusercontent.com/5361797/97531661-5b5bd800-1a00-11eb-9aa6-26040cd24c31.png)

**Step 5**
![Process1](https://user-images.githubusercontent.com/5361797/97531751-93631b00-1a00-11eb-821e-76dd2f4ff71d.png)

**Result**
![ReleaseNotes](https://user-images.githubusercontent.com/5361797/97531849-cd342180-1a00-11eb-8339-c864389e67a6.png)

**Same Package with a static Package Name Provided**
![hardcode](https://user-images.githubusercontent.com/5361797/97532159-7418bd80-1a01-11eb-9442-c3522cb9b395.png)

## Affected versions

2020.1.6+

## Workarounds

Setting the Variable #{SomePackageVariable} with a valid PackageName in the Project Variables in addition to the above reproduction steps results in the Release Notes and Build Information appearing as expected.

**Comment by amjadkhoja** [comment]
How do i know if this is issue is being worked upon for a patch?

**Comment by amjadkhoja** [comment]
Please can you. let us know the status for permanent fix.

**Comment by mcasperson** [comment]
Hi @amjadkhoja - This issue is on our backlog, but unfortunately we are not able to provide guideance on when it is likely to be resolved.

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Custom script steps do not evaluate release notes or build information when using dynamic packages](https://trello.com/c/nVkI4zJd/3888-custom-script-steps-do-not-evaluate-release-notes-or-build-information-when-using-dynamic-packages)

**Comment by amjadkhoja** [comment]
Thanks Matt,

Kind of waiting to enable this feature from September. Hoping you will take
up this soon to resolve the issue.

Regards
Amjad

**Comment by amjadkhoja** [comment]
I have message this issue is being worked upon for 2020.6 release. Please confirm if it will be available in 2020.6   octopus release

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4786 |
| 2021.1 | 2021.1.6916 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4786 |
| 2021.1 | 2021.1.6916 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | -all releases- |
