### ISSUE TITLE
Allow Docker registry secrets to not be created when deploying Kubernetes containers

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6653]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [ ✔️  ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [ ✔️ ] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [ ✔️ ] I have written a descriptive issue title
- [ ✔️ ] I have linked the original source of this feature request
- [ ✔️ ] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives

Cloud hosted K8s clusters often allow access to a Docker registry through IAM roles, removing the need for the K8s cluster to maintain credentials to access Docker images.

Today, any feed with credentials has an associated registry secret created to allow images to be downloaded.

This can be unnecessary, and there are situations where it leads to problems.

## Proposed solution

The solution is to provide an option to create or not create the registry secret.

## Mockup

![image](https://user-images.githubusercontent.com/160104/97649062-16887d80-1aa2-11eb-97b6-33a542f48539.png)

## Workarounds

Using the Deploy Raw YAML step provides control over what additional resources are created.

## Links

https://octopus.zendesk.com/agent/tickets/38537

**Comment by mac2000** [comment]
Got an opposite request :) 

The only possible way to deploy cronjob at moment is to use raw yaml deployment and there is no option to pass docker registry credentials, as a results - cronjob deployments can not pull image and do not work

**Comment by mcasperson** [comment]
@mac2000 We have had a few requests to include the ability to create a cronjob with the opinionated step. However, it has not made it onto our backlog, so there is no date I could give as to when it would be available, but it is on our radar to add this functionality.
