### ISSUE TITLE
Migrator import doesn't import runbook snapshots

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6659]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Runbook snapshots look to be exported correctly via migrator `export` or `partial-export`, but migrator `import` command does not import the runbook snapshots.

## What I expected to happen

Runbook snapshots would be imported.

## Steps to reproduce

1. Create a runbook snapshot
2. Export (either via migrator `export` or `partial-export`
3. Import into another instance

### Screen capture

![runbooksnapshots-84_not_found](https://user-images.githubusercontent.com/20388190/98197748-2527d680-1f73-11eb-951d-0beacbc5554b.png)

## Affected versions

Reproduced in **Octopus Server** 2020.4.11

## Workarounds

Unknown

## Links

Similar to #6210 
Report: https://octopus.zendesk.com/agent/tickets/60398 (private)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5027 |
| 2021.1 | 2021.1.7159 |
| 2021.2 | 2021.2.3652 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5027 |
| 2021.1 | 2021.1.7159 |
| 2021.2 | 2021.2.3652 |
| 2021.3+ | -all releases- |
