### ISSUE TITLE
Azure Devops Issue Tracker / How to fix "The server returned a sign-in page" error

### ISSUE THREAD

**Issue by melih154** [OctopusDeploy/Issues#6668]
Sorry as it might sound like an issue with Azure DevOps and not Octopus. Hope you can help.

Working on enabling "Azure Devops Issue Tracker" feature on On-Premise Octopus, version 2020.1.10. Connectivity Test succeed on initial setup. Azure DevOps organization has single sign-on enabled with corporate Azure AD.

Getting below error message on ADO build with "Push Package Build Information to Octopus" task  and a commit with releated work item.

`Error while fetching work item references from Azure DevOps: The server returned a sign-in page. Please confirm the Personal Access Token is configured correctly in Azure DevOps Issue Tracker settings, and is authorized to read scopes 'Build' and 'Work items'.`

Running the same source code, that retrieves build work item links, on OctopusDeploy / AzureDevOpsIssueTracker repo and succeed on my corporate desktop, to confirm that it is not a PAT token issue.

[this](https://github.com/OctopusDeploy/AzureDevOpsIssueTracker/blob/9e58dab581a4e06116bed0ff56a4fbbb7ba3af15/source/Server/AdoClients/HttpJsonClient.cs#L98) line of code generates this error message but still not sure what needs to be done on Azure AD or VM that Octopus is installed to remediate this issue.

**Comment by Justin-Walsh** [comment]
HI @melih154 - 

Thanks for reaching out, and sorry that you are having issues with your build information. We use this repository for conveying triaged and reproduced bugs to our users. If you could drop an email to support@octopus.com with this issue, our team would love to help get to the bottom of this for you.
