### ISSUE TITLE
Octopus HA using Docker Container

### ISSUE THREAD

**Issue by pogosoftware** [OctopusDeploy/Issues#6671]
Is it possible to setup Octopus Deploy Server in HA using Docker Containers? I found only instructions how to do this using windows server.

**Comment by KennethBates** [comment]
Hi @pogosoftware,

Thanks for getting in touch! The following blog post provides detailed information to hopefully help get you going.
https://octopus.com/blog/introducing-linux-docker-image#running-octopus-in-kubernetes

We don't actively monitor Github for support inquiries, so if you have any further questions or concerns, please don't hesitate to reach out to our support team via email at support@octopus.com or on our public forum at help.octopus.com for quicker response times. :)

Best regards,
