### ISSUE TITLE
run-runbook not accepting --variable flag

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/Issues#6675]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [ ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The octo.exe run-runbook command is not accepting values for passed variables.  

![image](https://user-images.githubusercontent.com/5552453/100157058-cc0ade80-2e5e-11eb-9b75-a4a262f00421.png)

If the prompted variable is required, this will fail the run-runbook command.

## What I expected to happen

Similar to the deploy-release or create-release (with the deployTo switch), the variable should be populated with the passed value

![image](https://user-images.githubusercontent.com/5552453/100157087-d88f3700-2e5e-11eb-99af-92fd64b569fc.png)

## Steps to reproduce

1. Create a prompted variable within a project
2. Create a run runbook that uses the prompted variable and make it required
Write-Host "The value passed was $($OctopusParameters['promptedTest'])"
3. Using the octo.exe, use the run-runbook switch and pass a variable
octo run-runbook --runbook="TestRunBook" --project="VariableTest" --environment="Development" --progress --waitForRun --server="https://shawnsesna.octopusdemos.app" --apiKey="API-XXXXXXXXXXXXXXXXXX" --variable="promptedTest:Sesna"

### Screen capture

![image](https://user-images.githubusercontent.com/5552453/100157547-94506680-2e5f-11eb-8f8c-8282f1aac48a.png)

### Log exerpt

```
Insert your log exerpt here.
```

## Affected versions

**Octopus Server:**
2020.5.0

**Comment by twerthi** [comment]
Duplicate of https://github.com/OctopusDeploy/OctopusCLI/issues/96

**Comment by matt-richardson** [comment]
Release Note: Fixed handling of required prompted variables for runbooks
