### ISSUE TITLE
Importing a step template can overwrite the templates configuration with default settings

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#6680]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
Importing a step template based on one of our built-in steps, like `Deploy a windows service` can cause the configured settings to be overwritten with the default settings. This is an error in the web UI where the step is imported, then the step "feature" is enabled, causing the default settings to clobber the inherited ones from the step template. 

As the step template is snapshotted at import time, existing projects that utilize this functionality should continue to work. Only steps added after the bug was introduced will exhibit this issue.

## What I expected to happen
Settings are successfully merged, keeping the inherited ones from the step template.

## Steps to reproduce
1. Create a custom step template based on the "Deploy a windows service" built-in step. Customising the service credentials or startup type.
2. Create a step from the step template, save
3. Inspect JSON and see the clobbered settings.

## Affected versions
**Octopus Server: 2020.4**
**Note:** First noted after the 2020.5 cloud rollout, but the consensus was that it could have happened earlier.

## Workarounds
As this issue only occurs on the initial import of the step template, you can force this to work as intended by making a change to the step template (adding or deleting a line, adding a comment, etc.), saving, then updating the impacted projects through the Usage pane for the template.

## Links
(Internal link) Initial report: https://octopus.zendesk.com/agent/tickets/61340

**Comment by calverp** [comment]
Another report of this issue: https://octopus.zendesk.com/agent/tickets/61636

**Comment by OctoStu** [comment]
Another report of this issue: https://octopus.zendesk.com/agent/tickets/62089

**Comment by mcasperson** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by paulegradie** [comment]
We've picked this issue up and are now looking into it 👍

**Comment by paulegradie** [comment]
Release Note: Fixes issue where step template settings were not applied
