### ISSUE TITLE
Structured configuration should detect XML file even if extension not xml

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6683]
From the [structured configuration docs](https://octopus.com/docs/deployment-process/configuration-features/structured-configuration-variables-feature#how-the-file-type-for-target-files-is-determined):

> Structured Configuration Variables allows for replacement in JSON, YAML, XML, and Properties files. To determine what file type is being used, Octopus will first try and parse the file as JSON, and if it succeeds, it will treat the file as JSON. This is to ensure backwards compatibility, because this feature previously only supported JSON files.

> If the file doesn't parse as JSON, Octopus refers to its file extension. If it is yaml or yml, the file will be parsed as YAML, if the extension is xml, the file will be parsed as XML, and finally if the extension is properties the file will be parsed as a Java Properties format.

This means that an XML file which doesn't have an extension of `.xml` cannot be targeted by the structured configuration feature.

There should be no reason we can't try to detect via file-extension first, and then attempt to parse the file.  Especially for XML.

Reported by: https://octopususergroup.slack.com/archives/CBS54TR9S/p1606920773038800 (octopus community slack)

**Comment by donnybell** [comment]
Additional inquiries: https://help.octopus.com/t/manually-specify-file-type-for-structured-configuration-variables-feature/25958

**Comment by TomPeters** [comment]
Release Note: Structured Configuration variables now tries all parsers for files that don't match well-known file extensions

**Comment by DanielSundberg** [comment]
> 
> 
> Release Note: Structured Configuration variables now tries all parsers for files that don't match well-known file extensions

Perhaps you could document those well known extensions? I've just spent a few hours trying to understand why octopus wouldn't modify the nlog.config file..

**Comment by TomPeters** [comment]
> > Release Note: Structured Configuration variables now tries all parsers for files that don't match well-known file extensions
> 
> Perhaps you could document those well known extensions? I also had a problem with the nlog.config file.

The extensions are documented here: https://octopus.com/docs/deployment-process/configuration-features/structured-configuration-variables-feature#how-the-file-type-for-target-files-is-determined

>If the file doesn't parse as JSON, Octopus refers to its file extension. If it is yaml or yml, the file will be parsed as YAML, if the extension is xml, the file will be parsed as XML, and finally if the extension is properties the file will be parsed as a Java Properties format.

So the supported well-known extensions are `.xml`, `.yaml`, `.yml` and `.properties`. In the case of `.config` files, these will begin working when the fix for this issue has been released, because the new algorithm will attempt all of the parsers (json, xml, yaml, properties) until it finds a matching parser (xml in the case of nlog.config). 

As per https://github.com/OctopusDeploy/Issues/issues/6709, this scenario will be supported from 2020.5.3, which we are preparing for release now.

**Comment by DanielSundberg** [comment]
> > > Release Note: Structured Configuration variables now tries all parsers for files that don't match well-known file extensions
> > 
> > 
> > Perhaps you could document those well known extensions? I also had a problem with the nlog.config file.
> 
> The extensions are documented here: https://octopus.com/docs/deployment-process/configuration-features/structured-configuration-variables-feature#how-the-file-type-for-target-files-is-determined
> 
> > If the file doesn't parse as JSON, Octopus refers to its file extension. If it is yaml or yml, the file will be parsed as YAML, if the extension is xml, the file will be parsed as XML, and finally if the extension is properties the file will be parsed as a Java Properties format.
> 
> So the supported well-known extensions are `.xml`, `.yaml`, `.yml` and `.properties`. In the case of `.config` files, these will begin working when the fix for this issue has been released, because the new algorithm will attempt all of the parsers (json, xml, yaml, properties) until it finds a matching parser (xml in the case of nlog.config).
> 
> As per #6709, this scenario will be supported from 2020.5.3, which we are preparing for release now.

Thanks, great work!

**Comment by tomchidlaw** [comment]
Hello Octopus

We were really excited to see this feature released, but I'm afraid it still doesn't appear to be working as documented. 

At my company, we are trying to use the feature to transform values in a custom XML config file named "acorn.config". In the project where we intended to use the feature, we found that Octopus would try to parse the file as JSON, and then fail.

I have just reproduced the issue in a very basic deployment project with a single "Deploy an Azure Web App" step. The error output shows that Octopus attempts to parse the file as JSON, then retries as YAML, and then errors:

```
The file at F:\Octopus\Work\20210209160647-113372-19780\staging\acorn.config does not match any known filename patterns. The file will be tried as multiple formats and will be treated as the first format that can be successfully parsed. 
February 9th 2021 16:06:49Verbose
Attempting structured variable replacement on file F:\Octopus\Work\20210209160647-113372-19780\staging\acorn.config with format Json 
February 9th 2021 16:06:49Verbose
The file at F:\Octopus\Work\20210209160647-113372-19780\staging\acorn.config couldn't be parsed as Json: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. 
February 9th 2021 16:06:49Verbose
Attempting structured variable replacement on file F:\Octopus\Work\20210209160647-113372-19780\staging\acorn.config with format Yaml 
February 9th 2021 16:06:49Error
Running rollback behaviours... 
February 9th 2021 16:06:49Error
Structured variable replacement failed on file F:\Octopus\Work\20210209160647-113372-19780\staging\acorn.config. The file could not be parsed as Yaml: (Line: 14, Col: 5, Idx: 467) - (Line: 14, Col: 5, Idx: 467): Did not find expected <document start>. See verbose logs for more details. 
February 9th 2021 16:06:49Error
System.Exception 
February 9th 2021 16:06:49Error
   at Calamari.Common.Features.StructuredVariables.StructuredConfigVariablesService.DoReplacement(String filePath, IVariables variables, IFileFormatVariableReplacer[] replacersToTry) 
February 9th 2021 16:06:49Error
   at Calamari.Common.Features.StructuredVariables.StructuredConfigVariablesService.ReplaceVariables(RunningDeployment deployment) 
February 9th 2021 16:06:49Error
   at Calamari.Common.Features.Behaviours.StructuredConfigurationVariablesBehaviour.Execute(RunningDeployment context) 
February 9th 2021 16:06:49Error
   at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<ExecuteBehaviour>d__16.MoveNext() 
February 9th 2021 16:06:49Error
--- End of stack trace from previous location where exception was thrown --- 
February 9th 2021 16:06:49Error
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
February 9th 2021 16:06:49Error
   at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<Execute>d__13.MoveNext() 
February 9th 2021 16:06:49Error
--- End of stack trace from previous location where exception was thrown --- 
February 9th 2021 16:06:49Error
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
February 9th 2021 16:06:49Error
   at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<Execute>d__13.MoveNext() 
February 9th 2021 16:06:49Error
--- End of stack trace from previous location where exception was thrown --- 
February 9th 2021 16:06:49Error
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
February 9th 2021 16:06:49Error
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
February 9th 2021 16:06:49Error
   at Calamari.Common.CalamariFlavourProgramAsync.<Run>d__4.MoveNext() 
February 9th 2021 16:06:49Verbose
Process C:\windows\system32\WindowsPowershell\v1.0\PowerShell.exe in f:\Octopus\Work\20210209160647-113372-19780 exited with code 100 
February 9th 2021 16:06:49Verbose
Updating manifest with output variables 
February 9th 2021 16:06:49Verbose
Updating manifest with action evaluated variables 
February 9th 2021 16:06:49Fatal
The remote script failed with exit code 100 
February 9th 2021 16:06:49Fatal
The action Deploy an Azure Web App on the Octopus Server failed 
```

It's our understanding that Octopus should also attempt to parse the file as XML.

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Structured variable replacement breaking service fabric.](https://trello.com/c/bcOqVQoB/19-structured-variable-replacement-breaking-service-fabric)

**Comment by mcasperson** [comment]
Ho @tomchidlaw - If you reach out to support@octopus.com we should be able to resolve this issue for you.

**Comment by palmerandy** [comment]
Hi Team,

> 
> 
> Ho tomchidlaw - If you reach out to [support@octopus.com](mailto:support@octopus.com) we should be able to resolve this issue for you.

We have just updated to Octopus v2020.6.4688 and like tomchidlaw we were expecting web.config files to be supported as per the [documentation](https://octopus.com/docs/projects/steps/configuration-features/structured-configuration-variables-feature#how-the-file-type-for-target-files-is-determined):

> How the file type for target files is determined
Structured Configuration Variables allows for replacement in JSON, YAML, XML, and Properties files. To determine what file type is being used, Octopus will first try and parse the file as JSON, and if it succeeds, it will treat the file as JSON. This is to ensure backwards compatibility, because this feature previously only supported JSON files.
> 
> If the file doesn't parse as JSON, Octopus refers to its file extension. If it is yaml or yml, the file will be parsed as YAML, if the extension is xml, the file will be parsed as XML, and finally if the extension is properties the file will be parsed as a Java Properties format.
> 
> **If the file extension is not recognized (for example, a file with a config file extension), Octopus will try to parse the files using each of the supported formats until a matching format is found.**

Instead we are getting a similar error:
```
09:56:42   Verbose  |       The file at D:\OctopusHome\Work\20210314235635-163401-450\staging\web.config does not match any known filename patterns. The file will be tried as multiple formats and will be treated as the first format that can be successfully parsed.
09:56:42   Verbose  |       Attempting structured variable replacement on file D:\OctopusHome\Work\20210314235635-163401-450\staging\web.config with format Json
09:56:42   Verbose  |       The file at D:\OctopusHome\Work\20210314235635-163401-450\staging\web.config couldn't be parsed as Json: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
09:56:42   Verbose  |       Attempting structured variable replacement on file D:\OctopusHome\Work\20210314235635-163401-450\staging\web.config with format Yaml
09:56:42   Error    |       Running rollback behaviours...
09:56:42   Error    |       Structured variable replacement failed on file D:\OctopusHome\Work\20210314235635-163401-450\staging\web.config. The file could not be parsed as Yaml: (Line: 12, Col: 16, Idx: 517) - (Line: 12, Col: 16, Idx: 517): While scanning a multiline plain scalar, found invalid mapping. See verbose logs for more details.
09:56:42   Error    |       System.Exception
09:56:42   Error    |       at Calamari.Common.Features.StructuredVariables.StructuredConfigVariablesService.DoReplacement(String filePath, IVariables variables, IFileFormatVariableReplacer[] replacersToTry)
09:56:42   Error    |       at Calamari.Common.Features.StructuredVariables.StructuredConfigVariablesService.ReplaceVariables(RunningDeployment deployment)
09:56:42   Error    |       at Calamari.Common.Features.Behaviours.StructuredConfigurationVariablesBehaviour.Execute(RunningDeployment context)
09:56:42   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<ExecuteBehaviour>d__16.MoveNext()
09:56:42   Error    |       --- End of stack trace from previous location where exception was thrown ---
09:56:42   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
09:56:42   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<Execute>d__13.MoveNext()
09:56:42   Error    |       --- End of stack trace from previous location where exception was thrown ---
09:56:42   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
09:56:42   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<Execute>d__13.MoveNext()
09:56:42   Error    |       --- End of stack trace from previous location where exception was thrown ---
09:56:42   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
09:56:42   Error    |       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:56:42   Error    |       at Calamari.Common.CalamariFlavourProgramAsync.<Run>d__4.MoveNext()
09:56:42   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in D:\OctopusHome\Work\20210314235635-163401-450 exited with code 100
09:56:42   Verbose  |       Updating manifest with output variables
09:56:42   Verbose  |       Updating manifest with action evaluated variables
09:56:42   Fatal    |       The remote script failed with exit code 100
09:56:42   Fatal    |       The action Deploy to App Service on the Octopus Server failed
```

Any update on this -  or should I also be contacting support@octopus.com?

**Comment by mcasperson** [comment]
Ho @palmerandy, yes, if you could reach out to the support team they should be able to provide a resolution for the issue.

**Comment by palmerandy** [comment]
For anyone experiencing similar issues, the outcome of my contact with support is the following bug report:
https://github.com/OctopusDeploy/Issues/issues/6794
