### ISSUE TITLE
Upgrading causes FeedId in Deployment Process JSON to be incorrectly set

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6685]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When upgrading from 3.x to 2020.5.x. The legacy deployment process JSON is incorrectly formatting the FeedId field.
It gets set to:
```
"FeedId": {
               "Value": "feeds-builtin"
             },
```

## What I expected to happen

When it should be:
`"FeedId": "feeds-builtin",`

## Steps to reproduce

1. Create Octopus 3.x instance
2. Create a Deploy Package step within a project
3. Upgrade to 2020.5.0
4. Attempt to view Projects

## Affected versions

**Octopus Server:** 2020.5.0

## Workarounds

Upgrading to an earlier version of 2020.x and then upgrading to 2020.5.0 should prevent this issue from occurring.

## Links

[Internal Link](https://octopus.zendesk.com/agent/tickets/61674)

**Comment by calverp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrading to 2020.5 causes FeedId in Deployment Process JSON to be incorrectly set](https://trello.com/c/OlJGmtZA/4025-upgrading-to-20205-causes-feedid-in-deployment-process-json-to-be-incorrectly-set)

**Comment by TomPeters** [comment]
Release Note: Fixed an issue where upgrading from an older version of Octopus Server resulted in corrupt FeedId values stored in the database
