### ISSUE TITLE
Channels now required the `ProjectView` permission

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6690]
Prior to this release performing operations on Channels required the `ProcessView` and `ProcessEdit` permissions. As of this release the `ProjectView` permission is also required. Any users or service accounts that perform operations on Channels should be granted the `ProjectView`, `ProcessView` and `ProcessEdit` permissions.

**Comment by tothegills** [comment]
Release note: **Breaking change** Channels now require the `ProjectView` permission

**Comment by dhmodh** [comment]
Does **Channels now require the ProjectView permission** have been solved in the higher version of Octopus like **_2022.1_**? Or else is there any solution for this ?
