### ISSUE TITLE
Changes on Microsoft's side are causing Azure WebApp deployments to fail when using slots on Octopus Server builds older than 2018.10.x

### ISSUE THREAD

**Issue by OctoStu** [OctopusDeploy/Issues#6692]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Deployments that use scripts to create/swap/delete slots to deploy Azure WebApps are failing. Deployment slots for Azure Web Apps are not appearing within Octopus dropdown boxes. Appears to be affecting previously successful deployments as of December 4th due to a change in Azure.

## What I expected to happen

Successful deployment using slots

## Steps to reproduce

1. Create a project with the following steps:

- Run an Azure Script: `New-AzureRMWebAppSlot -Name "AppName" -Slot slot2 -ResourceGroupName "ResourceGroupName"`

- Deploy an Azure WebApp to slot 2

- Run an Azure Script: Run an Azure Script: `Switch-AzureRmWebAppSlot -ResourceGroupName "ResourceGroupName" -Name "AppName" -SourceSlotName slot2 -DestinationSlotName slot3`
- Run an Azure Script: `Remove-AzureRmWebAppSlot -ResourceGroupName "ResourceGroupName" -Name "AppName" -Slot "slot2" -Force`
2. Deploy project
3. See error

Cloud reproduction of a working project with the above steps for internal use [here](https://octopus-operations.octopus.app/app#/Spaces-102/projects/azure-test/deployments/process)

### Screen capture

Snapshot of error:
![image](https://user-images.githubusercontent.com/71699621/101792015-1dbc9580-3afc-11eb-9277-2ee6bf477757.png)

### Log exerpt

``` 
15:01:53   Info     |       Deploying package:    C:\Octopus\Packages\index\index.0.0.1.zip
15:01:53   Verbose  |       Extracting package to: C:\Octopus\Work\20201209150151-11-4\staging
15:01:53   Verbose  |       Extracted 1 files
15:01:53   Info     |       Deploying to Azure WebApp 'StuartMcilveenApp' in Resource Group StuartMcilveen, using subscription-id 'xxxxxxxxxxxxxxxxxxxxx'
15:01:53   Verbose  |       Authentication Context: https://login.windows.net/xxxxxxxxxxxxxxxxxxxxx
15:01:54   Error    |       Could not find Azure WebSite 'StuartMcilveenApp' in subscription 'xxxxxxxxxxxxxxxxxxxxx'
15:01:54   Error    |       Running rollback conventions...
15:01:54   Error    |       Could not find Azure WebSite 'StuartMcilveenApp' in subscription 'xxxxxxxxxxxxxxxxxxxxx'
15:01:54   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20201209150151-11-4 exited with code 1
15:01:54   Verbose  |       Updating manifest with output variables
15:01:54   Verbose  |       Updating manifest with action evaluated variables
15:01:55   Fatal    |       The remote script failed with exit code 1
15:01:55   Fatal    |       The action app on the Octopus Server failed
```

## Affected versions

**Octopus Server:** Pre 2018.10.1 

## Workarounds

Upgrade to 2018.10.1 or newer

If upgrading isn't possible, we've had a user report success by removing the staging slot from the deployment and pushing it straight to the production app instead

## Links

Internal links:

QRF thread https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1607491746245200

https://octopus.zendesk.com/agent/tickets/62043
https://octopus.zendesk.com/agent/tickets/61823
https://octopus.zendesk.com/agent/tickets/61907
https://octopus.zendesk.com/agent/tickets/61972
https://octopus.zendesk.com/agent/tickets/62027

**Comment by droyad** [comment]
Fixed in newer versions
