### ISSUE TITLE
Filtering by Multiple Tags within Advanced Filters inside of tenants returns incorrect results. 

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#6694]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When you have multiple tenants with tags against each tenant, attempting to filter by more than one Tag, results in all Tenants being displayed including tenants with none of the tags that have been filtered.

## What I expected to happen

Either: 

a: If I filter by more than one tag, a reductive function should be used to include only the tenants that match both tags.
b: Alternatively, If I filter by more than one tag, a addition function should be used to include the tenants that match either tag.

## Steps to reproduce

Create any Project (and environment)
Create 3 Tenants - Tenant A, Tenant B, Tenant C
Create 3 Tenant Tag Sets - Tag Set 1, Tag Set 2 and Tag Set 3
Create a tag in each Tag Set - TS1 Tag 1, TS2 Tag 1, TS3 Tag 1 respectively. 
Connect a project to Tenant A and apply TS1 Tag 1
Connect a project to Tenant B and apply TS2 Tag 1
Connect a project to Tenant C and apply TS3 Tag 1
Open the Tenants Tab, click on "Show Advanced Filters"
Select TS1 Tag 1 and TS2 Tag 1.

You will see 3 Tenants Match and "Tenant C" will appear in the filtered list.

### Screen capture

![Tagset Error](https://user-images.githubusercontent.com/5361797/101865005-dc41ee00-3bc0-11eb-9f3d-de58a9db4902.png)

# More Info

I initially considered that the issue was "When 'no tenants match' it displayed ALL tenants." This is not the case. I added one other Tenant with all the tags. This tenant should appear with any combination of Tenant Tag Filtering - however when I chose two tenant tags to filter by, all tenants appeared.

In this circumstance - if the Tenant tag filters were reductive (Logical AND) - then only Tenant D should appear otherwise if they were Additive (Logical OR) then Tenant A, Tenant B and Tenant D should appear, while Tenant C will remain unmatched.
![TenantTahwithD](https://user-images.githubusercontent.com/5361797/101867042-05b14880-3bc6-11eb-9b61-17761119b451.png)

## Affected versions

Reproduced in Octopus Server: 2020.4.11

## Workarounds

No workarounds except checking manually.

## Links

https://help.octopus.com/t/when-using-the-advanced-filters-area-in-tenants-if-filtering-by-two-different-tag-sets-where-the-filter-results-will-be-zero-it-shows-all-tenants-instead-of-none/26058

**Comment by adrianhowchin** [comment]
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by auziel** [comment]
+1

**Comment by octokhor** [comment]
Old issue with no other reports. Closing this for now.
