### ISSUE TITLE
Custom expression on NuGet Package ID field in process step doesn't get replaced when creating a release

### ISSUE THREAD

**Issue by bcornett** [OctopusDeploy/Issues#671]
I have a package named "CompanyName.ProjectName.Web" in my built-in octopus NuGet feed. My project name is "CompanyName.ProjectName". When using the custom expression "#{Octopus.Project.Name}.Web" for the NuGet Package ID field in a process step and creating a new release, the project name does not get replaced, and the NuGet package matching "CompanyName.ProjectName.Web" is not found. Because of this, I am not allowed to continue my release and have to hard-code the project name into the NuGet Package ID field.

**Adding a process step with a custom expression for the Package ID:**
![packageid_variable](https://f.cloud.github.com/assets/4959971/2215560/6e9f648c-99f5-11e3-95bb-daf0ded887db.PNG)

**Creating a new release with a custom expression for the Package ID:**
![release_nopackage](https://f.cloud.github.com/assets/4959971/2215568/af8d2d58-99f5-11e3-878f-f4d25d1811b1.PNG)

**Adding a process step with a constant name for the Package ID:**
![packageid_static](https://f.cloud.github.com/assets/4959971/2215569/be598200-99f5-11e3-9875-33ad8ef9c633.PNG)

**Creating a new release with a constant name for the Package ID:**
![release_package](https://f.cloud.github.com/assets/4959971/2215574/cc28d80e-99f5-11e3-95b5-c263e3ef0502.PNG)

**Comment by rokeno** [comment]
I am at this point, too.

Read all posts here, but something eludes me: If the package ID is dynamic and has several values, how can Octopus distinguish one name (or at least allow to select it) from the other on the Release Creation page?

I need to be able to add the value myself in there (i might have 3-4 packages with different name for that variable)

Thanks.

**Comment by ricksecretin** [comment]
I have the same problem in version 3.16.

This is my packageId
![afbeelding](https://user-images.githubusercontent.com/10882683/28968353-e472700c-791f-11e7-9502-e82b8990ea8d.png)

And this is my custom variable
![afbeelding](https://user-images.githubusercontent.com/10882683/28968377-f747ab7a-791f-11e7-8d3c-5afacbbdafae.png)

When I create a release it does not evaluate the package id and thus cannot find my package in the nuget feed of teamcity.
![afbeelding](https://user-images.githubusercontent.com/10882683/28968404-181c01fc-7920-11e7-9115-88413dc9bc91.png)

Thanks in advance.
