### ISSUE TITLE
#{Octopus.Release.CurrentForEnvironment.Number} variable does not get substituted in step parameter in certain projects

### ISSUE THREAD

**Issue by tudorsibiu90** [OctopusDeploy/Issues#6724]
We have octopus deploy 2020.1.17

# Prerequisites

- [ yes] I have verified the problem exists in the 2020.1.17 version
- [yes ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

I have a powershell step that compares 2 versions of a release. I use #{Octopus.Release.CurrentForEnvironment.Number} as a parameter to get one of the version numbers. In one project it works fine. I get the last successfully deployed release number. In another project it does not get substituted. In powershell I get the value "#{Octopus.Release.CurrentForEnvironment.Number}" instead of the number i got in the working project. The steps in the 2 projects are identical. I have triple checked everything. The odd part is it works with Octopus.Release.Number or Octopus.Release.PreviousForEnvironment.Number but that does not help me.
## What I expected to happen

I expect the system variable to be usable in all projects

### Log excerpt

This is what I get for the non-working project (this is copy pasted from the tasklog)
"Url: https://api.github.com/repos/Visma-AO-Solutions-AdvisoryTools/Recon/compare/#{Octopus.Release.CurrentForEnvironment.Number}...20210106.031518 "

This is the task log from the working project
"Url: https://api.github.com/repos/Visma-AO-Solutions-AdvisoryTools/Core/compare/20201218.041242...20210104.041747"

## Affected versions

Octopus Server 2020.1.17

## Workarounds

none

**Comment by droyad** [comment]
@tudorsibiu90 Please contact our [Support Team](https://octopus.com/support), they will be able to give you timely support.

**Comment by tudorsibiu90** [comment]
it actually worked in Production environment. It does not work for the Internal Test environment. Very strange...
