### ISSUE TITLE
Upload to S3 bucket step not getting read from deployment_process.ocl correctly

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#6732]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

This bug was discovered internally.  

The deployment process is defined in this file: https://github.com/OctopusDeploy/octopus-design-system/blob/main/.octopus/deployment_process.ocl

However, when I navigate to that process (https://deploy.octopus.app/app#/Spaces-1/projects/octopus-design/branches/main/deployments/process/steps?actionId=upload-to-s3) several key values are not populated.

- Account variable not selected
- Region not populated
- Bucket not populated
- Target is set entire package file, but it should be set to `specific file(s) within a package`
- Missing file selector

![image](https://user-images.githubusercontent.com/38642825/104463087-f0d62500-5576-11eb-8afa-a6e45f50c2c2.png)  

On top of that, when I attempt to fill in those values I get an error stating `Please provide the S3 file(s) package`.  

![image](https://user-images.githubusercontent.com/38642825/104463348-46aacd00-5577-11eb-928c-6e43785f023e.png)

The package is getting pushed up as part of the request.

![image](https://user-images.githubusercontent.com/38642825/104462842-ab195c80-5576-11eb-9b8a-00e44cdc9e51.png)

Looking at the code, it expects exactly one package (which the request body is providing): https://github.com/OctopusDeploy/Sashimi.AwsS3/blob/b7e461f747fcee00c2877e9d61e57ce45cc69ba1/source/Sashimi/Validation/AwsUploadS3DeploymentValidator.cs#L40

## What I expected to happen

It appears the parser is not working properly on both the POST/PUT and GET commands.  

## Steps to reproduce

All of the above links are to our internal build system, you can use that to repro.

## Affected versions

**Octopus Server:** 2021.1.0-ci0029

## Workarounds

None

**Comment by droyad** [comment]
I failed to modify the OCL properly when we did the last update. I've fixed it up now.
