### ISSUE TITLE
Promote To and Try Again should remember previous skipped steps

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#674]
When using the "Promote To" or "Try Again" buttons on a deployment, the deployment creation page should automatically set the same skip steps and other settings as were used on the previous deployment. 

E.g., if I skipped the database step when I deployed to UAT, and then I click "Promote To" to go to production, I should see the database step skipped too (by default). 

http://octopus-deploy.tenderapp.com/discussions/problems/16178-promote-to-doesnt-remember-release-settings

**Comment by justinmcunn** [comment]
This doesn't seem to be in 2.6.  I tried to promote a release that had a step disabled and the promote tried to execute all steps.

**Comment by esetyanto** [comment]
Would it be possible to reopen this? as justinmcunn mentioned, this is no longer working in the latest version.
