### ISSUE TITLE
Octopus no longer loads if there are two slashes after domain

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#6744]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Accessing Octopus with two trailing slashes after the domain name no longer works. Instead, it now displays an error

https://demo.octopus.app//app#/Spaces-1 

```
{"title":"Not found","message":"The resource you requested was not found.","details":{"ErrorMessage":"The resource you requested was not found."}}
```

In 2020.3.4, the same URL would take you to the expected page.

This could be widespread in an instance where URLs are constructed with variables like `#{Octopus.Web.ServerUri}/#{Octopus.Web.DeploymentLink}`.

## What I expected to happen

The expected page will load.

## Steps to reproduce

1. Go to https://demo.octopus.app//app#/Spaces-1
2. See the error

## Affected versions

**Octopus Server:** 2020.5.5

## Workarounds

- Remove the extra slash from the URL in the browser
- Remove the source of the extra slash

## Links

Reported directly by a customer email.

**Comment by richev-o** [comment]
Fixed in 2020.5.266

https://octopus.com/downloads/2020.5.266

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.266 |
| 2020.6 | 2020.6.4688 |
| 2021.1 | 2021.1.6739 |
| 2021.2 | 2021.2.99 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.266 |
| 2020.6 | 2020.6.4688 |
| 2021.1 | 2021.1.6739 |
| 2021.2 | 2021.2.99 |
| 2021.3+ | -all releases- |
