### ISSUE TITLE
Importing a step template can overwrite the templates configuration with default settings

### ISSUE THREAD

**Issue by paulegradie** [OctopusDeploy/Issues#6747]
https://github.com/OctopusDeploy/Issues/issues/6680

Also affected `<2020.5.6`. The fix has been shipped in the patch indicated by the milestone. If you are using `2020.5.5` we highly recommend applying this patch.

Learn about [Releases of Octopus Deploy Server](https://g.octopushq.com/longtermsupport).

**Comment by paulegradie** [comment]
Release Note: Fixes issue where step template settings were not applied

**Comment by matt-richardson** [comment]
This landed in 2020.5.6, and landed in 2020.6.0-rc2 (and therefore is in all public 2020.6 releases)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.0-rc.2 |
| 2021.1 | 2021.1.6091 |
| 2021.2+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.0-rc.2 |
| 2021.1 | 2021.1.6091 |
| 2021.2+ | -all releases- |
