### ISSUE TITLE
Package download options not available for package parameter in step template

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6751]
When configuring a package in a step template to `Let the project select the package`, package acquisition options can not be configured. 

![image](https://user-images.githubusercontent.com/113759/106234356-6cf18d80-6244-11eb-878b-f77ff68a82be.png)

This prevents configuring the package to be acquired on the target, or not acquired at all.  i.e.

![image](https://user-images.githubusercontent.com/113759/106234560-cbb70700-6244-11eb-9ba6-d41a87b3a35b.png)

The reason for this is because these options were driven by the type of the package feed (NuGet, Docker, etc), which in this case is not known. 

To resolve, we will show all available options on the step template.  This will result in being able to configure invalid combinations (like acquiring docker images on the server), but this is preferable to _not_ being able to configure the desired behaviour.

**Comment by tothegills** [comment]
Release note: Package download options are now shown for deferred package selection
