### ISSUE TITLE
Expose machine architecture to either a system variable or API call.

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6754]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this feature request
- [X] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives
It would allow people to implement logic based on the architecture of a machine so that they can dynamically work with multiple types of infrastructure within the same process without a lot of workaround overhead.

## Proposed solution
Expose machine architecture to a system variable preferably, or potentially an API call.

## Workarounds
There are many ways you could work around this. The one we recommend is below

A two-fold strategy:
1) Run a scheduled runbook daily to check the architecture of each machine and update it's role/environment with the current architecture so that you can reference that.
2) Run a trigger on machine event "becomes healthy" to do the same as the above so that the architecture gets added as soon as a machine is spun up.

## Links

Source ticket; https://help.octopus.com/t/best-method-of-deploying-architecture-specific-packages/26224
Slack Discussions (Internal):
https://octopusdeploy.slack.com/archives/CC44LTNF5/p1611936239054000
https://octopusdeploy.slack.com/archives/C033W4273/p1611940710046100

**Comment by MissedTheMark** [comment]
Release Note: Added `Architecture` to the response whenever machine is referenced in an API call

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.6626 |
| 2021.2+ | <all releases> |
