### ISSUE TITLE
Recursive volume mounts break windows 2016-based execution containers

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#6755]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
When executing an execution container based off of a Windows Server 2016 base layer, the operation will fail due to how we're calling docker to run the image.

We run a recursive volume mount, mounting both the Work directory (Default: C:\Octopus\Work\<folder>) as well as the tentacle home directory (Default: C:\Octopus\). Because of the way docker creates these volume mounts, this will error when attempting the second volume mount because it's an operation on a symlink. This only errors on 2016-based hosts and images, and 2019-based images work as intended.

Owing to the fact that we get the Work directory as part of the tentacle home directory volume mount, we should just have to remove the volume mount for the Work directory.

## Steps to reproduce

1. Create a step that uses an execution container on a Windows 2016 worker that has docker installed (not cloud dynamic workers, as they don't have docker).
2. Use a Server 2016 base image such as `mcr.microsoft.com/windows/servercore:ltsc2016`
3. Create release and deploy

### Log excerpt
```
09:28:00   Verbose  |       Docker version 19.03.11, build 0da829ac52
09:28:00   Verbose  |       docker run --rm
09:28:00   Verbose  |       --env TentacleHome= C:\Octopus
09:28:00   Verbose  |       -w C:\Octopus\Work\20210128142759-30999-10
09:28:00   Verbose  |       -v C:\Octopus\Work\20210128142759-30999-10:C:\Octopus\Work\20210128142759-30999-10
09:28:00   Verbose  |       -v C:\Octopus:C:\Octopus
09:28:00   Verbose  |       mcr.microsoft.com/windows/servercore:ltsc2016

09:28:02   Error    |       C:\Program Files\Docker\docker.exe: Error response from daemon: hcsshim::CreateComputeSystem db163bd81bc6798a7850663226ce3f5bea0f0719c533fa14e9f151efab193937: This application does not support the current operation on symbolic links.

09:28:02   Error    |       (extra info: {"SystemType":"Container","Name":"db163bd81bc6798a7850663226ce3f5bea0f0719c533fa14e9f151efab193937","Owner":"docker","VolumePath":"\\\\?\\Volume{bb08d182-5c64-11eb-a2f8-cf65a595c49b}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\db163bd81bc6798a7850663226ce3f5bea0f0719c533fa14e9f151efab193937","Layers":[{"ID":"66a529c7-64d9-5407-bd43-f75da91abfb5","Path":"C:\\ProgramData\\docker\\windowsfilter\\7812a7867c128111d8cdb77d64648c8fc64c930495dd027cb7ab7874e5ddf20a"},{"ID":"9c6bc41b-9b26-58dd-b90b-41c8feb748e4","Path":"C:\\ProgramData\\docker\\windowsfilter\\514a6d97d593171725dc4ae0d22ddb6530c8bcaed1228646e53597b4d9205d6a"},{"ID":"548a2c75-e217-5b34-9fed-6f2686d2cce4","Path":"C:\\ProgramData\\docker\\windowsfilter\\e299078147b21cb5888c1b97dd137a3fbc4835004c8af22fce9986fadaeb69af"},{"ID":"9ac1efc9-f83c-57af-95dd-9926a228f8e1","Path":"C:\\ProgramData\\docker\\windowsfilter\\bc5d5d19614ad291740411f09b45823741a3a7f888120de968e1ac919cf8fb16"},{"ID":"de3f9b90-1d5c-50a5-b800-236e4f1400f4","Path":"C:\\ProgramData\\docker\\windowsfilter\\23fcd8d97062a883af7a54bfa220aec1a2de3bc609b0c425c0e08664b14efb45"},{"ID":"5e952edb-6e6d-5440-9060-a9f53da03d97","Path":"C:\\ProgramData\\docker\\windowsfilter\\8abffc9447a3414c1b795427c48e5587466807c85b4af8adf4340748dfd8fad3"},{"ID":"d886af94-094c-5b78-8dc5-16283597b826","Path":"C:\\ProgramData\\docker\\windowsfilter\\35d42e4ab6b26f923af972b631c512f01390f6256704616c33d455cda4642bf8"},{"ID":"02d7e46a-eead-5fbc-ac1c-ff059e2d0f45","Path":"C:\\ProgramData\\docker\\windowsfilter\\c720755e3e71ab21c052027f3ae5bb8799e6d04f361bc10663380d9f43709249"},{"ID":"923b76fa-f72f-5bc0-87d7-81fb3fc9a479","Path":"C:\\ProgramData\\docker\\windowsfilter\\c55460fdc686ed8cf735424ab729e09531eeb0d38caec27e66031d9685c59c46"},{"ID":"4afeba9d-c7e6-5ace-b487-6c498669413e","Path":"C:\\ProgramData\\docker\\windowsfilter\\98e631e2584822d5e1f0c099adad0285dd42c4f1a2b92bc78fe0a80fe39beb06"},{"ID":"cc0757c0-7fba-5365-883d-4624af26e096","Path":"C:\\ProgramData\\docker\\windowsfilter\\594ff024114a1ef888c2746a9ea8493a44a0a89c70e2debe7381e4f9a7e2790e"},{"ID":"7a305ead-b589-5c90-a441-9b5372a9f802","Path":"C:\\ProgramData\\docker\\windowsfilter\\175488eeb38fd695e05ab683899e470ac87f64f46e851c3f668f33bdaf5463e4"},{"ID":"675f7f43-bef2-5712-9b9d-e5dc034de067","Path":"C:\\ProgramData\\docker\\windowsfilter\\015684f6addd6fc1a25d438a288aec08e2cf39813f961405da2c8f045e4fb11e"},{"ID":"0e22fa4a-8fa1-55e2-804d-0760c7c18682","Path":"C:\\ProgramData\\docker\\windowsfilter\\bb1b96bdb5bde3f385dc46433785b8b46dd359e3f01d6397bb5e6c3088d0ff0b"}],"HostName":"db163bd81bc6","MappedDirectories":[{"HostPath":"c:\\octopus","ContainerPath":"c:\\octopus","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\octopus\\work\\20210128142759-30999-10","ContainerPath":"c:\\octopus\\work\\20210128142759-30999-10","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["ee0d5ab2-21e0-4579-b45c-9406181528eb"],"AllowUnqualifiedDNSQuery":true}).
```

## Affected versions
**Octopus Server: 2020.2 -> **

## Workarounds
* If using Windows 2019 workers, rebase your docker container to use a 2019 base layer.
* Call run docker manually in a script step and pass the correct parameters, and execute your scripts as part of the call.

## Links
(Ticket with initial report): https://octopus.zendesk.com/agent/tickets/64191
(Internal Link): Repro environment: https://octopus-operations.octopus.app/app#/Spaces-82/projects/repro-executioncontainersredundantvolumes/deployments/process 
(Internal Link): Working 2019 deployment: https://octopus-operations.octopus.app/app#/Spaces-82/tasks/ServerTasks-58877/raw

**Comment by N-lson** [comment]
We currently won't be fixing this; we've updated our docs to reflect which versions of Windows base images we support - https://octopus.com/docs/projects/steps/execution-containers-for-workers
