### ISSUE TITLE
On Create Release the version settings from the previous release are used

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6756]
At [this point](https://github.com/OctopusDeploy/OctopusDeploy/blob/0790e369ff847e5b172f1230a7cd2d46028b4643/source/Octopus.Server/Web/Controllers/DeploymentProcesses/ReleaseTemplateCreator.cs#L44) in the code (private link) the `DeploymentSettings` used are the ones from the previous release instead of the ones configured on the project.

## Steps to reproduce:
1. Create a release
1. Change the release versioning template in the deployment settings
1. Got to the create release screen and note the changes to the template are not reflected in the generated version

*Expected*: It uses the current settings

## Notes
**Octopus Server Version Affected**: `2020.6.0-rc.1`
PR that introduced this bug: https://github.com/OctopusDeploy/OctopusDeploy/pull/7698

**Comment by droyad** [comment]
I also see there is a transaction without a name there

**Comment by emilol** [comment]
Release note: Fixes an issue where an incorrect version template is used when generating a release version during release creation
