### ISSUE TITLE
After upgrade Octopus Server may fail to start due to invalid mimetype in project images

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6759]
After upgrade to `2020.5.0` or later the Octopus Server may fail to start with an error that contains:
```
Exception has been thrown by the target of an invocation.. Compiled reader expression
```
and
```
A valid image mimetype in the format image/{format} must be supplied
```

# Cause
We previously did not validate the mimetype of uploaded project images. This allowed non-images to be uploaded. We subsequently added validation at the API level to ensure the mimetype was an image. This only causes an error when updating an image.

In `2020.5` that validation was also applied when loading from the database. This cause projects not to load at all, which is required by permissions and in turn the login process. ([PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/7681))

# Workaround
Run the following on the database:
```
UPDATE Project 
SET JSON = JSON_MODIFY(JSON_MODIFY(JSON, '$.LogoAttachmentMimeType', null), '$.LogoAttachmentKey', null)
WHERE JSON_VALUE(Json, '$.LogoAttachmentMimeType') = 'application/octet-stream'
```

This will remove the logo from the project.

**Comment by matt-richardson** [comment]
This was fixed in:
* 2020.5.256
* 2020.6.4671
