### ISSUE TITLE
Release versions with regex characters break the dashboard

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6771]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [ ✔️  ] I have verified the problem exists in the latest version
- [ ✔️ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ ✔️ ] I have written a descriptive issue title
- [ ✔️ ] I have linked the original source of this report
- [ ✔️ ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you create a release with a version like `20210221.7.$(Rev:rr)`, the dashboard will break with an error like `An unexpected error occurred in Octopus v2020.6.0-rc0001: "TypeError: Expected "0" to be defined"`.

## What I expected to happen

The version should be displayed as it was entered.

## Steps to reproduce

1. Create a new release in a project with the version `20210221.7.$(Rev:rr)`
2. Open the project overview
3. See error

### Screen capture

![image](https://user-images.githubusercontent.com/160104/108647018-549f2680-7503-11eb-9ba9-9c76759572e8.png)

### Log excerpt

```
An unexpected error occurred in Octopus v2020.6.0-rc0001: "TypeError: Expected "0" to be defined"

    in InternalLink
    in withRouter(InternalLink)
    in n
    in TaskStatusDetails
    in div
    in DashboardCell
    in div
    in t
    in div
    in div
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in TransitionAnimation
    in div
    in div
    in PaperLayout
    in DashboardGrid
    in ProjectDashboard
    in div
    in section
    in Section
    in div
    in TransitionAnimation
    in div
    in div
    in PaperLayout
    in DashboardDataSourceInternal
    in p
    in main
    in div
    in div
    in MediaQuery
    in DrawerWrapperLayoutInternal
    in p
    in main
    in DashboardOverview
    in Page
    in p
    in DatabaseComponentContextProvider
    in FieldErrorContextProvider
    in ErrorContextProvider
    in Unknown
    in RenderWithPage
    in t
    in ErrorBoundaryInternal
    in ReloadableRoute
    in t
    in t
    in RootRoutes
    in withRouter(RootRoutes)
    in SpaceLoader
    in WithPersistedSpace
    in p
    in withRouter(Connect(WithPersistedSpace))
    in div
    in StandardLayoutInternal
    in p
    in t
    in ErrorBoundaryInternal
    in ReloadableRoute
    in SecureRoute
    in t
    in Unknown
    in t
    in t
    in Unknown
    in DevToolsContextProvider
    in ClientConnector
    in W
    in t
    in Theme
    in p
    in DatabaseComponentContextProvider
    in FieldErrorContextProvider
    in ErrorContextProvider
    in ErrorBoundaryInternal
    in App
```

## Affected versions

**Octopus Server: 2020.6.0**

## Workarounds

Using the Octopus cli, you can list the releases with the command:

```
octo list-releases --project=Loggd --apiKey API-xxxxxxxxxxxxxxxxxxxxx--server=https://myinstance.octopus.app
```

You can then delete the offending release versions with the command:

```
octo delete-releases --project=Loggd --minVersion '20210221.7.$(Rev:rr)' --maxVersion '20210221.7.$(Rev:rr)' --apiKey API-xxxxxxxxxxxxxxxxxxxxxxxxxxxx--server=https://myinstalce.octopus.app
```

## Links

Internal link: https://octopus.zendesk.com/agent/tickets/65237

**Comment by mcasperson** [comment]
This is fixed in 2020.6.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4615 |
| 2021.1 | 2021.1.6252 |
| 2021.2+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4615 |
| 2021.1 | 2021.1.6252 |
| 2021.2+ | -all releases- |
