### ISSUE TITLE
Library Variables Usage can time out

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6772]
Library Variable Set Usage can time out if there are a lot of snapshots and a lot of release. We do a `like` search through the `Release` `JSON` column for each library variable set snapshot we are interested in. This results in 100's of `like` where clauses.

Fixes #6775 as well

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.266 |
| 2020.6 | 2020.6.4694 |
| 2021.1 | 2021.1.6827 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.266 |
| 2020.6 | 2020.6.4694 |
| 2021.1 | 2021.1.6827 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | -all releases- |
