### ISSUE TITLE
Helm external feed - query sends incorrect Accept header

### ISSUE THREAD

**Issue by protonyx** [OctopusDeploy/Issues#6773]
# Background

We are hosting Helm charts as static files on a server hosted by IIS. The IIS StaticFilesModule contains content negotiation logic that will prevent serving files if the MIME type is not known, or is not represented in the incoming request Accept header. 

# The bug

OctopusDeploy-Server sends requests to the Helm repository index.yaml file with headers: 

Accept: application/x-yaml, application/yaml 
Accept-Encoding: gzip, deflate 
Host: tdwebtest.micron.com 
User-Agent: OctopusDeploy-Server/2020.2.16+Branch.tags-2020.2.16.Sha.768f1ab39d3a63d1a7356cd18487d8cb14d27fdc

## What I expected to happen

The Accept header should be "text/yaml, text/x-yaml" according to the Helm chart repository [documentation](https://helm.sh/docs/topics/chart_repository/) under the section "Ordinary web servers"

## Steps to reproduce

1. Build a repository index with 'helm repo index' with a folder containing charts
2. Copy the folder to an IIS 10.0 server with Static Content enabled
3. Ensure the .yaml MIME type is registered as 'text/yaml'
4. Add the URL to Octopus as an external registry

### Screen capture

![image](https://user-images.githubusercontent.com/8594948/109072016-b2717100-76b1-11eb-8668-3a9d4d7588cd.png)

## Affected versions

**Octopus Server:** 2020.2.16

## Workarounds

Override the MIME type in the web.config to 'application/yaml':

```
<configuration>
  <system.webServer>
    <staticContent>
      <remove fileExtension=".yaml" />
      <mimeMap fileExtension=".yaml" mimeType="application/yaml" />
    </staticContent>
  </system.webServer>
</configuration>
```

## Reference

https://helm.sh/docs/topics/chart_repository/

**Comment by droyad** [comment]
@protonyx Thank you for the report. In order to get your request looked into and triaged in a timely manner please contact [support](https://octopus.com/support). They will look into this and try and reproduce the problem and triage it appropriately (which could include re-opening this issue).
