### ISSUE TITLE
Script Module Usage is slow

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6775]
The API can take a long time and time out or overload the server.
Same problem as #6772

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.266 |
| 2020.6 | 2020.6.4694 |
| 2021.1 | 2021.1.6827 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.266 |
| 2020.6 | 2020.6.4694 |
| 2021.1 | 2021.1.6827 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | -all releases- |
