### ISSUE TITLE
Some Calamari binaries do not support long file names when running on Net451

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#6778]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

This is a regression from https://github.com/OctopusDeploy/Issues/issues/4204

The following Calamari binaries are affected:
- Calamari.AzureServiceFabric
- Calamari.AzureWebApp
- Calamari.AzureResourceGroup
- Calamari.AzureCloudService
- Calamari.AzureScripting
- Calamari.Terraform

## Affected versions

**Octopus Server:** 2020.5 and above

## Workarounds

You have to replace the Calamari binaries

## Links

https://octopus.zendesk.com/agent/tickets/62944

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.249 |
| 2020.6 | 2020.6.4668 |
| 2021.1 | 2021.1.6739 |
| 2021.2 | 2021.2.99 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.249 |
| 2020.6 | 2020.6.4668 |
| 2021.1 | 2021.1.6739 |
| 2021.2 | 2021.2.99 |
| 2021.3+ | -all releases- |
