### ISSUE TITLE
After upgrade Octopus Server may fail to start due to invalid mimetype in project images

### ISSUE THREAD

**Issue by andrewabest** [OctopusDeploy/Issues#6779]
#6759 also affected `2020.6`. The fix has been shipped in the patch indicated by the milestone. If you are using `2020.6` we highly recommend applying this patch.

Learn about [Releases of Octopus Deploy Server](https://g.octopushq.com/longtermsupport).

**Comment by matt-richardson** [comment]
This was fixed in:
* 2020.5.256
* 2020.6.4671
