### ISSUE TITLE
After upgrade Octopus Server may fail to start due to invalid mimetype in project images

### ISSUE THREAD

**Issue by andrewabest** [OctopusDeploy/Issues#6780]
#6759 also affected `2020.5`. The fix has been shipped in the patch indicated by the milestone. If you are using `2020.5` we highly recommend applying this patch.

Learn about [Releases of Octopus Deploy Server](https://g.octopushq.com/longtermsupport).

**Comment by droyad** [comment]
@andrewabest removing the milestone

**Comment by matt-richardson** [comment]
This was fixed in:
* 2020.5.256
* 2020.6.4671

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.251 |
| 2020.6 | 2020.6.4668 |
| 2021.1 | 2021.1.6739 |
| 2021.2 | 2021.2.99 |
| 2021.3+ | -all releases- |
