### ISSUE TITLE
Release screen omits commit build information if VcsType is unknown

### ISSUE THREAD

**Issue by harrisonmeister** [OctopusDeploy/Issues#6784]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When you have build information that has a VcsType of `Unknown`, commit information which is available and stored in the database is not shown on the release page. It is present on both the linked package and the Build information screens.

Further, it looks like it's due to the commits not being present in the **BuildInformation** object returned by the releases API endpoint. (example: `https://your.octopus.app/api/Spaces-1/projects/Projects-ID/releases/RELEASE.NUMBER`)

## What I expected to happen

The build information section would include all of the stored build information, including commits

## Steps to reproduce

1. Upload build information with an Unknown VcsType e.g.:

```json
{
  "PackageId": "my-package",
  "Version": "2021.03.05.01",
  "BuildEnvironment": "Bamboo",
  "BuildNumber": "8",
  "BuildUrl": "https://vcs.example.com/browse/",
  "Branch": "Develop",
  "VcsType": "Unknown",
  "VcsRoot": "ssh://git@vcs.example.com/notreal",
  "VcsCommitNumber": "123456",
  "VcsCommitUrl": null,
  "IssueTrackerName": null,
  "WorkItems": [],
  "Commits": [
    {
      "Id": "12345678910",
      "LinkUrl": null,
      "Comment": "Merge pull request #1"
    },
    {
      "Id": "78910111213",
      "LinkUrl": null,
      "Comment": "Implemented some things"
    }
  ]
}
```
2. Upload a package with Id: `my-package` and version `2021.03.05.01`
3. Create a deployment process with one step which references the package: `my-package`
4. Create a release and see that the build information section of the release doesn't include the commits.

### Screen capture

![Screenshot](https://user-images.githubusercontent.com/1418993/110139675-353dae80-7dcb-11eb-88be-7ad181430b59.png)

## Affected versions

**Octopus Server: 2020.6.4634** (but likely affecting earlier versions)

## Workarounds

Write a script to call the package API endpoint to return the data you want in a script step and use the information in a deployment to either send details to be Emailed, Slack notification or create an Artifact.

## Links

- [Internal link](https://octopus.zendesk.com/agent/tickets/65886) (private)

**Comment by YuKitsune** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The release screen (API Endpoint) omits commit build information if VcsType is unknown](https://trello.com/c/EaClujJs/4263-the-release-screen-api-endpoint-omits-commit-build-information-if-vcstype-is-unknown)

**Comment by YuKitsune** [comment]
Release note: Fixes an issue where commits were omitted from the release screen when the VCS type is unknown.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4772 |
| 2021.1 | 2021.1.6916 |
| 2021.2 | 2021.2.994 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4772 |
| 2021.1 | 2021.1.6916 |
| 2021.2 | 2021.2.994 |
| 2021.3+ | -all releases- |
