### ISSUE TITLE
RunbookView permission required to view projects

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6787]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a user does not have the `RunbookView` permission granted to them, they're unable to access projects.

## What I expected to happen

A user without `RunbookView` should still be allowed to access a project. They should only be restricted from the *Operations* tab in a project.

## Steps to reproduce

1. Grant access to projects for a user, but revoke `RunbookView`
2. Attempt to enter a project as the user
3. See error

### Screen capture

![image](https://user-images.githubusercontent.com/20388190/110262118-5fc37d80-7ffe-11eb-9d46-d94452683740.png)

### Log excerpt

```
You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: RunbookView
This action requires permission to view runbooks. None of your teams have this permission.
```

## Affected versions

Reproduced in 2021.1.6691. Reported in 2020.5.5, though this issue wasn't present prior to upgrading from 2019.13.7.

## Workarounds

Grant RunbookView to the user.

## Links

Report: https://octopus.zendesk.com/agent/tickets/65911 (private)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4709 |
| 2021.1 | 2021.1.6829 |
| 2021.2 | 2021.2.592 |
| 2021.3+ | _all releases_ |
