### ISSUE TITLE
Allow third party Docker images with ENTRYPOINTs to be used as container images

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6788]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [ ] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [ ] I have written a descriptive issue title
- [ ] I have linked the original source of this feature request
- [ ] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives
Docker images that define an ENTRYPOINT can not be used as a container image, as Octopus only overrides the CMD. This leads the container image running its original executable and passing the calamari commands as arguments, which will never work as expected.

## Proposed solution
Override the ENTRYPOINT of a image when it is used as a container image. This allows calamari to run as expected.

## Workarounds

Building a custom docker image from the third party image and setting

```
ENTRYPOINT []
```

will clear the entrypoint of the base image.

**Comment by mcasperson** [comment]
This is fixed in 2021.2.0.

**Comment by matt-richardson** [comment]
Release Note: Third party docker images can be now be used as container images

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.124 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.124 |
| 2021.3+ | -all releases- |
