### ISSUE TITLE
Pagination is applied as if all runbooks were visible instead of only filtered runbooks

### ISSUE THREAD

**Issue by charles-hague-octopus** [OctopusDeploy/Issues#6789]
# Prerequisites

- [ x ] I have verified the problem exists in the latest version
- [ x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ x ] I have written a descriptive issue title
- [ x ] I have linked the original source of this report
- [ x ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Pagination is applied as if all runbooks were visible instead of only filtered runbooks.

## What I expected to happen

The pagination should be applied to the filtered runbooks instead of all runbooks.

## Steps to reproduce

1. Create at least 31 runbooks in order to exceed the pagination threshold
2. Note that runbooks after the pagination threshold are correctly only shown after clicking "Load More"
3. Apply a filter which would return results from both the first and second 'pages'
4. Note that only runbooks from the first 'page' are shown regardless of how many results there are
5. Click on "Load More"
6. Note that the rest of the runbooks are displayed

### Screen capture

<img width="394" alt="Resized Screenshot 2021-03-09 at 12 51 18 " src="https://user-images.githubusercontent.com/71703850/110473213-324a0300-80d6-11eb-99d4-b607f89bba4e.png">

<img width="388" alt="Resized Screenshot 2021-03-09 at 12 51 27 " src="https://user-images.githubusercontent.com/71703850/110473220-34ac5d00-80d6-11eb-89d1-0e59f33fd16c.png">

### Log excerpt

N/A

## Affected versions

Octopus Server: 2020.5.5+, 2021.1.0+

## Workarounds

All runbooks can be reached by clicking the "Load More" button until the required runbook is displayed.

## Links

https://octopus.zendesk.com/agent/tickets/66000 (Internal)
https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1615282173004600 (Community Slack)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.1901 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.1901 |
| 2021.3+ | -all releases- |
