### ISSUE TITLE
Ability to make variable an environment variable in step

### ISSUE THREAD

**Issue by DarrenV79** [OctopusDeploy/Issues#6790]
A feature https://github.com/OctopusDeploy/Issues/issues/3712 like this has been asked before.  

What I want to be able to do is promote a variable to an environment variable.  I can use it in scripts or in the template replacement but this is extremely clunky and doesn't work for everything.  Take deploying a terraform script.  Locally I have keys defined in environment variables. On Octopus I need to fill my scripts with conditionals to replace with variables.  It makes a huge mess in the code or the scripts I want to run and is extremely hard to test.  

If I could tick a box on the variable so that the worker sets it as an environment variable it would be much similar.  It would also make life much easier for enabling accounts for providers you don't support such as digital ocean.  Currently, we are just avoiding Octopus and going via Teamcity because the script maintenance is extremely cumbersome.

**Comment by calverp** [comment]
Hi Darren, thanks for the detailed feature request.
Unfortunately, this isn't the best place to raise this. We have a User Voice site (https://octopusdeploy.uservoice.com) that can be used for requesting new features that our Product Team reviews regularly.
I couldn't see a similar request raised there yet, so, it would be a good idea to add this.
Regards,
