### ISSUE TITLE
Can't save changes to process when release versioning setting is tied to a package step

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6795]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Setting a project's release versioning setting to `Use the version number from an included package` breaks the ability to save changes to the deployment process.

## What I expected to happen

Changes to the deployment process would be saved.

## Steps to reproduce

1. Add a package step to the deployment process
2. Set `Release Versioning` to `Use the version number from an included package`

![image](https://user-images.githubusercontent.com/20388190/111416048-d105dd80-872e-11eb-8877-ca542006d7ed.png)

3. Attempt to save a change to the process
4. Save button does nothing

### Log excerpt

Network response in browser reports:

```
"ErrorMessage": "The given key '' was not present in the dictionary."
```

## Affected versions

Reproduced in 2021.1.6691
Works correctly in 2020.6.4688

## Workarounds

Toggle the Release Versioning setting to `Generate version numbers using a template` temporarily. Switch it back once the changes are saved as needed.

## Links

Report (private): https://octopus.zendesk.com/agent/tickets/66282

**Comment by NickJosevski** [comment]
That work around worked for me! 🎩

**Comment by KennethBates** [comment]
Another report: https://octopus.zendesk.com/agent/tickets/66733 (private)

**Comment by YuKitsune** [comment]
Release note: Fixes an issue where changes to the deployment process could not be saved when the versioning strategy is set to "Use the version number from an included package"

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.6879 |
| 2021.2 | 2021.2.994 |
| 2021.3+ | -all releases- |
