### ISSUE TITLE
CommunityActionTemplates folder missing when exporting a runbook using Octopus.Migrator.exe

### ISSUE THREAD

**Issue by OctoStu** [OctopusDeploy/Issues#6799]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
When using Octopus.Migrator.exe to export a runbook that includes a step with a community step template, the CommunityActionTemplates folder isn't exported resulting in the runbook not being able to use that step after import.

## What I expected to happen

Runbook steps that use a community step template in the process should be able to export/import successfully 

## Steps to reproduce

1. Create a runbook that uses a community step template in one of the steps
2. Use octopus.Migrator.exe to export it `Octopus.Migrator.exe partial-export --directory="C:\runbook" --ignore-deployments --ignore-machines --ignore-tenants --project="runbook" --password="password" --clean`
3. Import it to another instance `Octopus.Migrator.exe import --directory="C:\runbook" --password="password"`
4. Browse to the steps in the runbook, the affected step will not load and the blue progress bar at the top will not stop moving:
![image](https://user-images.githubusercontent.com/71699621/111796415-0f7ed200-88c0-11eb-83ca-81ff7a460807.png)
5. Attempting to delete the step will give the following error:
![image](https://user-images.githubusercontent.com/71699621/111796737-608ec600-88c0-11eb-82e8-7c29597d24ce.png)

### Screen capture
Left: Runbook export, Right: Deployment process export 
![image](https://user-images.githubusercontent.com/71699621/111798763-49e96e80-88c2-11eb-8bee-a0791c144fbc.png)

### Log excerpt

```
N/A
```

## Affected versions

**Octopus Server:** Reproduced in 2020.5.5, also attempted an export on 2021.1.0-ci0972 and the folder wasn't included there either

## Workarounds

Two possible workarounds:
1: Delete the step and add it again
2: Delete the affected step before exporting and manually add it after importing
## Links
Internal link - https://octopus.zendesk.com/agent/tickets/65831

**Comment by vladpRiM** [comment]
This is still an issue - will it be fixed?

**Comment by droyad** [comment]
@vladpRiM This is included in `2020.6.5026`

**Comment by droyad** [comment]
Release Note: Included the community action templates when exporting a runbook

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5026 |
| 2021.1 | 2021.1.7159 |
| 2021.2 | 2021.2.3652 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5026 |
| 2021.1 | 2021.1.7159 |
| 2021.2 | 2021.2.3652 |
| 2021.3+ | -all releases- |
