### ISSUE TITLE
IDs and name slugs in URLs and API Calls have case sensitivity when they shouldn't

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6801]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

URLs and API calls will fail based on the case sensitivity of IDs and name slugs.

Examples:
192.168.139.160/app#/Spaces-1/projects/api-call-examples/variables  (**works**)
192.168.139.160/app#/Spaces-1/projects/Api-call-examples/variables  (**Does not work**, capitalized name slug)
192.168.139.160/app#/spaces-1/projects/api-call-examples/variables  (**Does not work**, s in spaces is not capitalized)

192.168.139.160/api/Spaces-1/projects/projects-81/ (**does not work**, P not capitalized in Projects-81)
192.168.139.160/api/spaces-1/projects/Projects-81/ (**does not work**, S not capitalized in spaces-1)

These are just some examples I've found by spot-checking.

## What I expected to happen

I expect them to work regardless of case.

## Steps to reproduce

1. Attempt URLs like the above examples and see them fail

## Affected versions

**Octopus Server:** Latest at time of writing (2020.6.4688)

## Workarounds

Use the correct case for each scenario

## Links

Ticket(INTERNAL): https://octopus.zendesk.com/agent/tickets/66461
Slack Convo (INTERNAL): https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1616099884043600

**Comment by droyad** [comment]
This was introduced in `2020.6.0-rc.1` (https://github.com/OctopusDeploy/OctopusDeploy/pull/7698). [This line](https://github.com/OctopusDeploy/OctopusDeploy/commit/49b544113f2683c7cc48895031257c595c1cc274#diff-4809639251bd9cfba039cb763e088a5632123ede8e8c11c9b8765e276481123cR32) does a case sensitive comparison.

**Comment by zentron** [comment]
A fix for this has been added to the `2020.6` release

**Comment by zentron** [comment]
Release Note: Project API calls are case insensitive matching the project slug

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4772 |
| 2021.1 | 2021.1.6916 |
| 2021.2 | 2021.2.994 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4772 |
| 2021.1 | 2021.1.6916 |
| 2021.2 | 2021.2.994 |
| 2021.3+ | -all releases- |
