### ISSUE TITLE
The latest docker tag should not be sorted as the latest version.

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6807]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives

When a Docker image has been tagged with latest, that tag is shown as the latest version, meaning it is selected by default when selecting a new docker image from a package feed during release creation.

## Proposed solution

The proposed solution is to not sort the latest tag in a special way.

## Mockup

Latest isn't shown as the highest version:
![image](https://user-images.githubusercontent.com/160104/112428310-b19e2e80-8d86-11eb-8793-c61dd5504977.png)

But you can find it if you search:
![image](https://user-images.githubusercontent.com/160104/112428334-bc58c380-8d86-11eb-8d5b-d9db78e83073.png)

## Workarounds

Using channel rules to remove docker tags called `latest` means it will not be selected during deployment.

## Links

Internal link: https://octopus.zendesk.com/agent/tickets/66642

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4786 |
| 2021.1 | 2021.1.6918 |
| 2021.2 | 2021.2.1224 |
| 2021.3+ | -all releases- |
