### ISSUE TITLE
Runbooks with process-scoped prompted variables fail to run due to missing variable values from other scopes

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#6813]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
When utilizing process-scoped variables, with prompted variables scoped to different processes (deployment processes, as well as other runbooks), Octopus will fail to run the runbook, citing that the prompted variables scoped to other processes do not have values. This does not happen from the web portal, only via API calls (in this case, from OctopusCLI)

## What I expected to happen
Octopus should only look at prompted variables scoped to that process.

## Steps to reproduce
1. Create a new project
2. Create a deployment process to do something
3. Create a runbook to do something
4. Create prompted variable(s) process-scoped to the runbook process
5. Create prompted variable(s) process-scoped to the deployment process
6. Run/Publish runbook
7. Attempt to run the runbook with `octo run-runbook`
8. 💥 

### Screen capture
Variable screen:
<img width="539" alt="variables" src="https://user-images.githubusercontent.com/49404281/113059543-94e66a00-917d-11eb-933a-b8bbe7cddb21.png">

### Log excerpt
Octopus CLI output
```
octo run-runbook --server=https://octopus --apikey=x --space=Justin --Project=ProjectName --runbook=Runbooks-162 --environment=Dev --variable=1:1 --variable=3:3

Detected automation environment: "NoneOrUnknown"
Found space: Justin (Spaces-82)
Space name specified, process is now running in the context of space: Justin
Handshaking with Octopus Server: https://octopus
Handshake successful. Octopus version: 2021.1.6460; API version: 3.0.0
Authenticated as: Justin Walsh <justin.walsh@octopus.com>
Found project: ProjectName (Projects-443)
Found runbook: Runbook (Runbooks-162)
Found environment: Dev (Environments-181)
There was a problem with your request.

 - The following required variables were not provided: 4 , 2

Once you have corrected these problems you can try again.
If the problem is related to a variable you will need to update the variables for this snapshot or recreate the snapshot for the changes to take effect.
If the problem is related to the runbook process you will need to create a new snapshot for the changes to take effect.

Error from Octopus Server (HTTP 400 BadRequest)
```

## Affected versions
**Octopus Server: 2020.6+**
Higher requirement is due to https://github.com/OctopusDeploy/Issues/issues/6777 only being fixed in 2020.6.

## Workarounds
* Run the runbook from the Octopus web UI
* Split the runbooks up into distinct projects with their own variables

## Links (Internal)
Repro (Runbook): https://octopus-operations.octopus.app/app#/Spaces-82/projects/runbookvarscoping/operations/runbooks/Runbooks-162/overview
Repro (Variables): https://octopus-operations.octopus.app/app#/Spaces-82/projects/runbookvarscoping/variables
Initial report: https://octopus.zendesk.com/agent/tickets/66948

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5131 |
| 2021.1 | 2021.1.7311 |
| 2021.2 | 2021.2.5105 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5131 |
| 2021.1 | 2021.1.7311 |
| 2021.2 | 2021.2.5105 |
| 2021.3+ | -all releases- |
