### ISSUE TITLE
Some Valid Versioning usage in External Feeds (GitHub Nuget) will result in Package Not Found in Feed

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6817]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Using a GitHub Nuget external feed, some versioning will result in **The package was not found in the feed**. An example of this is `#.#.#-AAA-####-AAAAA-AAAAA.###`. This versioning is valid semver, but Octopus fails to pull in the details of the package on the release page. However, the package still deploys correctly. I would expect this behavior is not limited to GitHub Nuget feeds, but that is what I discovered and tested it on.

## What I expected to happen

I would expect the release page to be able to find the package and get the information.

## Steps to reproduce

1. Create an external Nuget GH feed
2. Push a package with versioning like the above example or below screenshot.
3. Add the package to a step and create a release
4. See the error

### Screen capture

![image](https://user-images.githubusercontent.com/63259411/113875041-5dcb1680-9784-11eb-997c-9790d0ff31bc.png)

## Affected versions

**Octopus Server:** Latest at time of writing (2021.1.6460)

## Workarounds

Change the versioning schema of your package or ignore the error, as the package will still deploy correctly.

## Links

Source Ticket: https://help.octopus.com/t/the-package-was-not-found-in-the-feed/26423/3
Internal Slack Convo: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1616089126042000
Internal Cloud Repro: https://octopus-operations.octopus.app/app#/Spaces-83/projects/github-nuget-feed-tests/deployments/releases/0.0.1

Additional Ticket: https://octopus.zendesk.com/agent/tickets/71812

**Comment by N-lson** [comment]
This looks like it was fixed in https://github.com/OctopusDeploy/Issues/issues/6949 - the earliest version this fix was added in was `2021.1.7599`
Rerun of the internal cloud repro is now successful on build `7638`: https://octopus-operations.octopus.app/app#/Spaces-83/projects/github-nuget-feed-tests/deployments/releases/0.0.2
