### ISSUE TITLE
Helm timeout values fails when entering a time unit value for Helm V3

### ISSUE THREAD

**Issue by tmbam** [OctopusDeploy/Issues#6820]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
The syntax changed in Helm 3 to require a time unit at the end, but setting a unit in Octopus under the timeout option causes errors because the timeout value is not a valid integer.

## Steps to reproduce

Configure step to use Helm v3 and set timeout flag for 1500s.  Our template only accepts an integer value for timeout and fails if you specify the duration designation with the following error:

invalid argument "1500" for "--timeout" flag: time: missing unit in duration 1500
Using Release Name upgradeahelmchart-development Running rollback conventions... Timeout period is not a valid integer: 1500s The remote script failed with exit code 1 

## Affected versions
Found in 2020.2.1, 2020.3.4 and confirmed in latest. 

**Octopus Server:**

## Workarounds

The workaround here is to remove the timeout value and use the "Additional Arguments" option to pass the timeout flag.

## Links

https://octopus.zendesk.com/agent/tickets/1571
https://octopus.zendesk.com/agent/tickets/67293

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Helm 3 timeout value no longer validates](https://trello.com/c/CBJq4YPe/40-helm-3-timeout-value-no-longer-validates)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3387 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3387 |
| 2021.3+ | -all releases- |
