### ISSUE TITLE
Clone Project UI no longer offers users to redefine project group and lifecycle.

### ISSUE THREAD

**Issue by pstephenson02** [OctopusDeploy/Issues#6830]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report (This issue was reported on a customer call and in a subsequent email)
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When cloning a project, the Octopus UI used to allow users to redefine the project's group and lifecycle on the same modal where they entered the new project name and description. In the latest versions, the clone project modal only allows users to edit the name. See screenshots for difference.

![image](https://user-images.githubusercontent.com/6306934/114940022-108b1c80-9df6-11eb-8a4a-bfc0a9b7282d.png)
![image](https://user-images.githubusercontent.com/6306934/114940038-15e86700-9df6-11eb-86e2-c949efdbef9e.png)

## What I expected to happen

I would expect these options to remain. The customer that reported this liked having those settings all on one page and didn't need to go back after the fact to change them.

## Steps to reproduce

Just try to clone any project and notice the UI from the screenshot above.

## Affected versions

2020.6.x

## Workarounds

The workaround is to edit these settings after the project has been cloned.

## Links

[Internal discussion](https://octopusdeploy.slack.com/archives/C80H394RK/p1618429416035200)

**Comment by droyad** [comment]
This change was done deliberately and at this stage we don't plan on changing this.
