### ISSUE TITLE
Terraform Issue with Channel creation for Process Step of type Script which References Package

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#6831]
# The bug

When using the Terraform Octopus Deploy Plugin, a channel is able to be created without issue for Process Steps of type "Deploy a Package" however currently unable to create a channel where the Process Step is of type "Run a Script" which references a package. Previously created channels are able to be imported without issue. 

This was tested and confirmed with @jbristowe 

## What I expected to happen

Terraform Plugin to be able to create channels with actions of type Process Step "Run a Script" which references a package. 

## Steps to reproduce

Requires a Package to be configured previously.

1. Create a terraform configuration whose action will reference a Process Step of type "Run a Script":
```
resource "octopusdeploy_channel" "channel" {
  name = "test"
  project_id = "Projects-1"
  rule {
    actions = [
    "Run a Script/MyPackage"
    ]
    version_range = "1.0.0"
  }
}
```

### Log excerpt

```
 Error: Octopus API error: Unable to find package reference  on deployment action Run a Script in project Projects-1 []
```

## Affected versions

Lastest OctopusDeploy Terraform Plugin = 0.7.22

**Comment by jbristowe** [comment]
The `octopusdeploy_channel` resource is missing an `action_packages` attribute. This will be added to the next release of the Terraform Provider for Octopus Deploy.

**Comment by jbristowe** [comment]
This has been fixed. Closing issue.
