### ISSUE TITLE
Invalid day names can be used in cron expressions resulting in the "Triggers" overview becoming inaccessible

### ISSUE THREAD

**Issue by charles-hague-octopus** [OctopusDeploy/Issues#6833]
# Prerequisites

- [ x ] I have verified the problem exists in the latest version
- [ x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ x ] I have written a descriptive issue title
- [ x ] I have linked the original source of this report
- [ x ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Cron expressions are evaluated during creation and an error is normally displayed if the cron expression is invalid. This validation doesn't appear to work correctly if an incorrect day name is entered allowing an invalid cron expression to be saved. Upon saving the "Triggers" overview page becomes inaccessible.

## What I expected to happen

The invalid day name should be detected and an error displayed preventing it from being saved.

## Steps to reproduce

1. Create a Runbook
2. Create a Scheduled Trigger
3. Enter `0 1 2 3` as an example of an invalid cron expression
4. Attempt to save and note that an error prevents you from doing so* 
5. Enter `0 0 6 * * Thurs` as the invalid cron expression
6. Attempt to save and note that "Invalid cron expression" is shown but the update still saves
7. Browse to the "Triggers" overview page and note the error

\* It's worth saving the address of the edit page at this point so you can get back to it

### Screen capture

An invalid cron expression correctly showing an error:

<img width="452" alt="Resized Screenshot 2021-04-16 at 16 29 25 " src="https://user-images.githubusercontent.com/71703850/115048056-13a70b00-9ed1-11eb-945c-49e17739079a.png">

An invalid cron expression incorrectly showing no error:

<img width="378" alt="Resized Screenshot 2021-04-16 at 16 29 57 " src="https://user-images.githubusercontent.com/71703850/115048064-17d32880-9ed1-11eb-9e14-b4a51518ca9c.png">

The "Triggers" overview page after saving an invalid cron expression:

<img width="445" alt="Resized Screenshot 2021-04-16 at 16 30 15 " src="https://user-images.githubusercontent.com/71703850/115048078-1ace1900-9ed1-11eb-94e9-d71e57fbf386.png">

### Log excerpt

N/A

## Affected versions

**Octopus Server:** 2021.1.6460

## Workarounds

The issue can be fixed by finding the direct edit address of the Trigger and correcting the cron expression.

## Links

https://octopus.zendesk.com/agent/tickets/67682 (internal)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7244 |
| 2021.2 | 2021.2.4367 |
| 2021.3+ | <all releases> |
