### ISSUE TITLE
Terraform init parameters used by "Apply a Terraform Template" is no longer usable with Terraform version 0.15.x

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#6835]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The Step "Apply Terraform Template" uses the init argument 
`terraform.exe init -no-color -get-plugins=true`

The argument '-get-plugins=true' _should not be used_  in 0.13+ and has been completely removed from terraform 0.15.

_Note: Since Terraform 0.13, this option has been superseded by the provider_installation and plugin_cache_dir settings. It should not be used in Terraform versions 0.13+, and this option was removed in Terraform 0.15._
https://www.terraform.io/docs/cli/commands/init.html#plugin-installation

Although everything works nicely on our dynamic workers (bundled with 0.11.8), we are currently shipping our worker_tools with Terraform 0.13.4 on Windows server 2019 ltsc and 0.13.5 on the ubuntu 18.04 image.

## What I expected to happen

"Apply a Terraform Template" checks which version of Terraform is running and uses the correct Terraform init argument.

## Steps to reproduce

1. Create a project with a single step "Apply a Terraform Template"
2. You can use source code as simple as:

```
terraform {
  required_providers {
    octopusdeploy = {
      source = "OctopusDeployLabs/octopusdeploy"
      version = "0.7.26"
    }
  }
}
```

3. Deploy it via a worker with Terraform latest.

### Log excerpt

```


Terraform v0.15.0 
April 19th 2021 13:50:46Info
on windows_amd64 
April 19th 2021 13:50:46Info
"terraform.exe" init -no-color -get-plugins=true  

<REDACTED>

Running rollback behaviours... 
April 19th 2021 13:50:46Error
The following command: "terraform.exe" init -no-color -get-plugins=true  
April 19th 2021 13:50:46Error
With the working directory of: C:\Octopus\Work\20210419035043-27512-9 
April 19th 2021 13:50:46Error
Failed with exit code: 1 


```

## Affected versions

Terraform v0.15 (Latest)
Octopus 2021.1.6593 (Latest)

## Workarounds
Use an earlier version of Terraform
Use a script instead of the built in step.

## Links

https://help.octopus.com/t/modify-terraform-default-init-command/26538

**Comment by wjrogers** [comment]
Please consider adding a special variable that _overwrites_ the default options -- instead of adding to them -- as an "escape hatch" against this kind of problem happening again in the future. Octopus Deploy limiting the version of Terraform we can use is a bummer.

**Comment by egorpavlikhin** [comment]
Support for the latest version of Terraform will be added to versions `2020.1` and up in a few days.

@wjrogers this is a great idea, we will certainly discuss it. There is an option to add additional parameters to the `init` command, however at present it is not possible to overwrite the parameters sent by Calamari.

![image](https://user-images.githubusercontent.com/1160707/115507723-d15e3f00-a2bf-11eb-82e3-c84ead17ea68.png)

**Comment by egorpavlikhin** [comment]
Fixed in `2020.5` and up.

**Comment by egorpavlikhin** [comment]
Release Note: Added support for Terraform CLI v0.15.0

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.353 |
| 2020.6 | 2020.6.4919 |
| 2021.1 | 2021.1.7089 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.5 | 2020.5.353 |
| 2020.6 | 2020.6.4919 |
| 2021.1 | 2021.1.7089 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | -all releases- |
