### ISSUE TITLE
Users in a Team with User Roles scoped to Environments may not be able to add values to a project variable unless the top value in the list is editable

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#6837]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Users in a Team with User Roles scoped to Environments may not be able to add values to a project variable unless the top value in the list is editable.

## What I expected to happen

The order in which the variable values are displayed should not affect the option to add a value if the user has such permission.

## Steps to reproduce

1. Create a test user
2. Add user to a Team with "VariableEdit" permissions scoped to Environments "Dev" and "Test"
3. Add an additional Role to the Team that includes "VariableView" permissions with no scope
4. Create a Project
5. Create a Project Variable with multiple values and differing Environmental scopes.

Example:
![image](https://user-images.githubusercontent.com/63249187/115293407-434e5100-a125-11eb-9430-6177af0a57ba.png)

What the test user sees when the top value is scoped to an Environment not included in #2 above:
![image](https://user-images.githubusercontent.com/63249187/115293555-78f33a00-a125-11eb-830e-f6ff90cefa2b.png)

What the test user sees when reversed:
![image](https://user-images.githubusercontent.com/63249187/115293577-801a4800-a125-11eb-8517-ce254647c223.png)

## Affected versions

Test in 2020.6.4855 and 2021.1.6930

**Octopus Server:**

## Workarounds

None

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8102 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
