### ISSUE TITLE
Running Linux Octopus docker with read only root file system

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6838]
# The enhancement
Run Linx Octopus Docker with read only root file system.

## What is the problem this solves or benefit it gives
We have a requirement to run all our docker containers with the read only root file system. And there is no exception for the Octopus Deploy.

To be able to do so, I had to build a custom image with a modified /Octopus/install.sh file. 

The modification I made is to move ./configured to /home/octopus/configured. 

## Proposed solution
![image](https://user-images.githubusercontent.com/171197/115324748-c3c88c80-a1cd-11eb-9231-23f1e677d358.png)

## Links

https://octopus.zendesk.com/agent/tickets/67683
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1618785820036300

**Comment by hazzik** [comment]
Hi there

I ended up doing this in my custom docker image:

```shell
RUN \
    #Replace ./configured with $HOME/configured because working directory (.) should remain read-only
    sed 's/\.\/configured/$HOME\/configured/g' -i install.sh && \ 
    # Replace /home/octopus with $HOME to use the home directory of a user that runs container
    sed 's/\/home\/octopus/$HOME/g' -i install.sh
```

**Comment by N-lson** [comment]
Hey @hazzik thanks for that. Would you be able to provide us with the configuration used to run your docker containers with a read-only root filesystem? We're looking into this but finding that using the `--read-only` option causes this error
```
Failed to create CoreCLR, HRESULT: 0x80004005
```
which seems to be caused by [this known issue](https://github.com/dotnet/runtime/issues/9336) on dotnet images

**Comment by hazzik** [comment]
> We're looking into this but finding that using the --read-only option causes this error ...

We usually mount `/tmp` as readable fs (`emptyDir` in k8s terms) in our set up to avoid this issue as opposite to `ENV COMPlus_EnableDiagnostics=0`. In some of our images we use `/tmp` as a drop folder for liveness/readiness probes so we decided to use the same approach for octopus. 

The following folders need to be writable to be able to run in readonly:

- `/tmp`, partially for the problem you're facing (maybe `ENV COMPlus_EnableDiagnostics=0` is enough instead)
- `/root` (this is `$HOME`), if running as non root, it should be a different folder.
- `/cache`
- `/etc/octopus/` (AFAIR Octopus looks/updates default `.config` and `machineKey` files here for reconfigure)
- `/Octopus/Octopus/Logs` (Logs for default configuration)

```bash
root@octopus-0:/Octopus# find /etc/octopus/
/etc/octopus/
/etc/octopus/OctopusServer
/etc/octopus/OctopusServer/Instances
/etc/octopus/OctopusServer/Instances/octopusserver.config
/etc/octopus/machinekey
root@octopus-0:/Octopus# cat /etc/octopus/OctopusServer/Instances/octopusserver.config
{
  "Name": "OctopusServer",
  "ConfigurationFilePath": "/root/.octopus/OctopusServer/Server/Server.linux.config"
}
```

**Comment by N-lson** [comment]
Thanks @hazzik that's very helpful. With a writable `/tmp` we're no longer running into the above error, however the container hangs on `./Octopus.Server create-instance`. We've also made `/root`, `/cache` and `/etc` writeable. Is this familiar to you?

**Comment by hazzik** [comment]
It hangs on trying to write logs to `/Octopus/Octopus/Logs` (you can verify it with ps)

**Comment by N-lson** [comment]
Ah that was the one! We're still looking into this issue, thanks for the extra info.

**Comment by N-lson** [comment]
Release Note: Added an environment variable `OCTOPUS_SERVER_CONFIGURATION_DIRECTORY` which refers to the directory where the docker image stores configuration files. Defaults to `/home/octopus/.octopus`

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8358 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
