### ISSUE TITLE
Octopus CLI / OctopusClient is uploading packages twice when delta compression is enabled

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#6840]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Octopus Client is uploading files twice when delta compression is enabled - it first successfully uploads the delta file, then thinks it has failed, and uploads the full file.

## What I expected to happen

It should only upload once.

## Steps to reproduce

1. Create a large nupkg file.
1. Use `octo push` to upload it
1. Use `octo push` to upload it with the ` --overwrite-mode IgnoreIfExists` option
-> note it uploads fully twice.

### Log excerpt

```
Pushing package: C:\temp\packages\Zip.1.0.0.zip...
Requesting signature for delta compression from the server for upload of a package with id 'Zip' and version '1.0.0'
Calculating delta
The delta file (40,980,320 bytes) is more than 95% the size of the original file (40,980,269 bytes)
Falling back to pushing the complete package to the server
```

## Affected versions

**Octopus Server:** At least `2019.1`

## Workarounds

This only causes extra data transfer/slowness - it still works.

## Initial investigation

From debugging through the code, OctopusCLI is definitely uploading twice.
[This line](https://github.com/OctopusDeploy/OctopusDeploy/blob/cf5aa361945abc1304169ffab8074db0785dde51/source/Octopus.Server/Web/Api/NuGet/PackagePushActionBase.cs#L124) of code returns just a plain old 200 OK response, but [OctopusClient is seeing](https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs#L65) that as a null response, so assumes things have failed.

## Links

Discovered internally. See [slack thread.](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1614223950089000)

**Comment by droyad** [comment]
Release Note: The API now returns a response body when a package already exists in the internal feed, which fixes the double uploading from the .NET `Octopus.Client` library

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4974 |
| 2021.1 | 2021.1.7089 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4974 |
| 2021.1 | 2021.1.7089 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | -all releases- |
