### ISSUE TITLE
Sort order for lists in Octopus are not following an alphabetical convention

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6846]
# The bug

It can be difficult to find items in drop-downs or list when there are many of them, because the sorting of those items.

## What I expected to happen

It should be easy to find items in Octopus.

### Screen capture

Example: connecting a tenant to a project

![image](https://user-images.githubusercontent.com/171197/115637979-cbff0400-a354-11eb-97c5-457061568bee.png)

Example: variables listed when an environment is expanded:

![image](https://user-images.githubusercontent.com/171197/115638024-e46f1e80-a354-11eb-800f-2616dd6ad443.png)

## Links

(internal) https://octopus.zendesk.com/agent/tickets/67973

**Comment by peter-dolkens** [comment]
Hiya, I think I raised the original feature request on this.

Instead of alphabetical, I think it would make sense to use the order set in the environments page.

The environments page already has "reorder" functionality, so there is definite intentional order of the environments supported by the product, it makes sense to persist this across all areas of the product.

**Comment by peter-dolkens** [comment]
For reference:

### Variables > Project Template

![image](https://user-images.githubusercontent.com/469666/116479313-5248a800-a877-11eb-8c28-d364d93f17ae.png)

### Infrastructure > Environments

![image](https://user-images.githubusercontent.com/469666/116479440-8d4adb80-a877-11eb-89a0-ecbc8952d310.png)
![image](https://user-images.githubusercontent.com/469666/116479472-976cda00-a877-11eb-82b1-88f2141ddc46.png)

### Tenants > Variables

![image](https://user-images.githubusercontent.com/469666/116479771-1a8e3000-a878-11eb-80ca-e5c78c30101b.png)

**Comment by droyad** [comment]
@peter-dolkens Thanks for that clarifying, we are fixing this as well as the Dropdowns. the latter is related to another request.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.4974 |
| 2021.1 | 2021.1.7093 |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | <all releases> |
