### ISSUE TITLE
Subscription "name" help text is incorrect

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6852]
# The bug
The "Name" field when configuring a subscription displays "Apply filters to this subscription."

**Comment by tothegills** [comment]
Release note: The subscription "Name" field now displays appropriate help text

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.2828 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.2828 |
| 2021.3+ | -all releases- |
