### ISSUE TITLE
Split Project and Deployment Settings into their own tabs in the UI. Remove Package Redeployment Option.

### ISSUE THREAD

**Issue by gupta-kartik** [OctopusDeploy/Issues#6855]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

## What is the problem this solves or benefit it gives
As part of config-as-code, we need to split project settings:
* Deployment settings - These are version-controlled are live under the Deployments menu
* Project settings - These are not version-controlled, and live where they do today.

We are also removing the package redeployment setting (screenshot below) as it did not make sense as a project-level setting. If you think this will break your workflow there is a workaround. This change is being made in Octopus Server `v2020.6`

![image](https://user-images.githubusercontent.com/4622084/116644259-3bf53600-a9b6-11eb-8f2a-e18560a449b7.png)

## Proposed solution

Add a new Settings tab under Deployments section in the UI for Deployment Settings.

![image](https://user-images.githubusercontent.com/4622084/116511040-31309780-a909-11eb-8bbf-ee7c66bd8b60.png)

## Workaround for Package Redeployment Option

We have a System level variable ([docs](https://octopus.com/docs/projects/variables/system-variables#Systemvariables-Action)) for Actions: `Octopus.Action.Package.SkipIfAlreadyInstalled`  which is `False` by default i.e. Octopus will always reinstall every included package even if the version of the package being deployed is already present on the machine.

To skip redeploying packages that are already installed:
* Navigate to the project you wish to disable package redeployment for
* Click on Variables on the sidebar
* Add a new variable to the list `Octopus.Action.Package.SkipIfAlreadyInstalled`
* Set the value to `True` (Reminder, it is `False` by default)
* Save the Variables
* Create a new Release to update the latest variables snapshot
* Deploy the release
* You will see the Octopus skip packages that are already installed (if the same version already exists on the machine)

![image](https://user-images.githubusercontent.com/4622084/116644173-094b3d80-a9b6-11eb-9024-56e32696f9e1.png)

## Links

[Internal Link](https://octopus.zendesk.com/agent/tickets/68298)

**Comment by kengel100** [comment]
[Internal link](https://octopus.zendesk.com/agent/tickets/68298)

**Comment by gupta-kartik** [comment]
Release Note: Split Project & Deployment Settings into their own tabs in the UI. Remove Package Redeployment project setting.
