### ISSUE TITLE
Structured Configuration Variables break Yaml with comments

### ISSUE THREAD

**Issue by sergey-tihon** [OctopusDeploy/Issues#6859]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [ x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Structured Configuration feature break yaml structure when comment written at the beginning of the list
 
YAML file:
```yaml
db: # comment
    prefix: 'Content_'
```

after transformation looks like this

```yaml
db # comment
:
    prefix: 'Content_'
```

It introduce new line with `:` and remove it before comment

## What I expected to happen

After transformation Octopus should generate valid YAML file with same semantic

```yaml
db: # comment
    prefix: 'Content_'
```

## Steps to reproduce

1. Create new Process step that use `Structured Configuration Variables`
2. Add yaml file with comment after `:`
3. Run this step

## Affected versions

**Octopus Server:** v2020.6 (Build 4855)

## Workarounds

Do you write comments ?)

**Comment by KennethBates** [comment]
Hi Sergey,

I appreciate you bringing this issue to our attention. However, would you mind instead emailing us at support@octopus.com with this report? That will allow us to triage your report internally, reproduce the issue, get the appropriate details raised and addressed, etc.

**Comment by sergey-tihon** [comment]
What wrong with reporting issues here?
