### ISSUE TITLE
Variables scoped to a step have "undefined" appended to the name of the step after upgrading

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6861]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Variables scoped to a step have "undefined" appended to the name of the step after upgrading. I followed the path of 2020.6.4855->2021.1.7006 and it caused variables scoped to a step to have the visual bug. This appears to only be a visual bug in my testing. See in the screenshots below that the scoped variable is output not the unscoped variable.

## What I expected to happen

I would expect the name to have been preserved through the upgrade.

## Steps to reproduce

1. Spin up 2020.6.4855 and create a project with variables scoped to steps.
2. Upgrade to 2021.1.7006 and look at the variables and see the scope names have changed.

### Screen capture

![image](https://user-images.githubusercontent.com/63259411/116931688-5128c980-ac2f-11eb-902a-301970d3c1a0.png)

![image](https://user-images.githubusercontent.com/63259411/116931722-600f7c00-ac2f-11eb-90a0-0fb82a641f83.png)

![image](https://user-images.githubusercontent.com/63259411/116931750-67cf2080-ac2f-11eb-8be3-495d2cd0be0a.png)

## Affected versions

**Octopus Server:** Latest at the time of writing (2021.1.7006)

## Workarounds

No workaround necessary, it appears to be a visual bug.

## Links
Source Ticket(INTERNAL) : https://octopus.zendesk.com/agent/tickets/68352

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7123 |
| 2021.2 | 2021.2.3140 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7123 |
| 2021.2 | 2021.2.3140 |
| 2021.3+ | -all releases- |
