### ISSUE TITLE
Azure App Service step

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6871]
We've added a new step to deploy to Azure App Services.  

This step deploys to Azure Web App deployment targets.  It essentially supersedes the existing `Deploy an Azure Web App` step, bringing the following improvements:

- It can deploy to Linux App Service plans (without any magic app settings)
- It can deploy container images
- It can execute on either Windows or Linux workers
- It no longer relies on WebDeploy (which had some idiosyncracies) 
- It can set AppSettings and ConnectionStrings on the app service

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7123 |
| 2021.2 | 2021.2.3140 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7123 |
| 2021.2 | 2021.2.3140 |
| 2021.3+ | -all releases- |
