### ISSUE TITLE
Azure login fails if password contains certain special characters

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#6874]
# The bug

If the Service Principal App Password contains certain special characters i.e. '-' '~'  '_'. then the following error is received: 
az login: error: argument –password/-p: expected one argument

## What I expected to happen

You should be able to use any special characters in passwords.

## Steps to reproduce

1. Create a Service Account Password which contains a special character like '-', '~' or '_'.
2. Try to login to the Azure account through Octopus.
3. See error

### Log excerpt
az login: error: argument –password/-p: expected one argument

## Affected versions

Latest: 2020.6+

## Workarounds

Create a Service Account Password that doesn't contain the special characters '-', '~' or '_'.

## Links
[Internal](https://octopus.zendesk.com/agent/tickets/67578)
[Internal](https://trello.com/c/OWYpuNGw/62-azure-k8s-login-fails-when-password-starts-with-a-dash)

**Comment by geofflamrock** [comment]
Release Note: Azure passwords with leading dash or other special characters now work as expected

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3684 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3684 |
| 2021.3+ | -all releases- |
