### ISSUE TITLE
Tenant Preview under a step displays tenant preview incorrectly

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#6876]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When there is no tenant filter applied on a step, the tenant preview dialog doesn't show/indicate all tenants are selected by default.

## What I expected to happen

All tenants are shown under 'preview tenants' if there are no filters selected, as the default is all tenants selected.

## Steps to reproduce

1. Create a project
2. Create a few tenants and connect your project to these tenants
2. Go back to your project and create a new step. In the process editor, scroll down to conditions > tenants and open tenant preview dialog.
3. See that there are 0 matching tenants selected

### Screen capture
![tenant-preview-bug1](https://user-images.githubusercontent.com/82346985/117918897-57a1fa00-b32f-11eb-9b14-6019f8c890a9.png)

![tenant-preview-bug2](https://user-images.githubusercontent.com/82346985/117918900-596bbd80-b32f-11eb-81b0-a4c41d39b980.png)

## Affected versions

master

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3854 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3854 |
| 2021.3+ | -all releases- |
