### ISSUE TITLE
Modifying a 'Copy of' template fails on save

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/Issues#6886]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
After making a copy of an existing Community Step Template, Octopus will fail to save any modifications stating that there are duplicate variables within the template.  

## What I expected to happen

Octopus should save changes to the template after modifications have been made.

## Steps to reproduce

1. Go to Library -> Step Templates
2. Select an existing Community Step Template from the Library and click **SAVE AS COPY**
3. Make a change to the copied template and click Save

### Screen capture

![image](https://user-images.githubusercontent.com/5552453/118674198-74668380-b7ae-11eb-8dca-0b1af4801bf5.png)

### Log excerpt

```
Insert your log excerpt here.
```

## Affected versions

**Octopus Server:** 2020.5+

## Workarounds

Two workarounds exist

1. Remove all Parameters from the template, then re-add
2. Choose Export from the ellipses menu, copy the JSON, delete the template, import the JSON

**Comment by iryan2** [comment]
The fix for this issue is now in `master`

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5094 |
| 2021.1 | 2021.1.7255 |
| 2021.2 | 2021.2.4478 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5094 |
| 2021.1 | 2021.1.7255 |
| 2021.2 | 2021.2.4478 |
| 2021.3+ | -all releases- |
