### ISSUE TITLE
CaC transaction connection leaks via DocumentStores

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#6898]
# The bug

Release `2021.1` has a known issue of *SQL transaction connection leaks* for Health Checks and Deployment/Runbooks tasks (that use `OctoParallel` to run code in parallel).

Leading up to this error:
```
There are a high number of transactions active. The below information may help the Octopus team diagnose the problem:
Now: 2021-05-27T01:51:17
Transaction '<unknown>' Open with 0 commands started at 2021-05-27T01:51:13 (3.91 seconds ago)
```

Or when the instance has run out of connections:
```
Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
```

## Affected versions

**Octopus Server:**
`2021.1` release stream
(fixed separately in `2021.2`)

## Workaround

Restart your Octopus instance to free up connections.

## Currently Under Investigation

The workaround above is not ideal. We're actively working on a fix for `2021.1`.

## Technical Details (Devs)

Our `OctoParallel` code correctly creates a new transaction per thread, but the problem comes from the usage of DocumentStores in these code paths. DocumentStores are a new abstraction layer we've been slowly introducing to switch between persistence layers for DB or Git (for the up-coming config-as-code feature). These DocumentStore instances are created _per lifetime scope_ and are created at a higher level, before the `OctoParallel` begins thread work. So for DB queries, we end up trying to access a transaction (that's created per thread) via a shared instance of a DocumentStore. This instance of the DocumentStore is being used by multiple threads and they're getting confused over which transaction they should be using, so we end up with MARS (multiple active result sets) issues, where multiple queries from different threads are executing on the same transaction and :boom:. We get a MARS error when the transaction is attempting to dispose, and this is causing connection leaks.

E.g.
```
The connection does not support MultipleActiveResultSets. System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Rollback()
   at Microsoft.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at Nevermore.Advanced.ReadTransaction.Dispose()
```

This issue does not occur on `2021.2` (current `master`) as we identified this issue during the subsequent fixes around the [message contracts PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/8569) and [subsequent message contracts cleanup PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/8947), where we introduced a `UnitOfWorkExecutor` and resolved our DocumentStores from within that executor's scope (inside the `OctoParallel` thread path). So now we get a DocumentStore per thread and this issue is resolved.

## Links

Internal [trello card](https://trello.com/c/exyGOohk/193-warranty-connection-leak-document-stores-are-being-shared-between-transactions)

**Comment by MarkSiedle** [comment]
Release Note: Fixing a transaction connection from our document stores

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7292 |
| 2021.2 | 2021.2.4545 |
| 2021.3+ | -all releases- |
