### ISSUE TITLE
In Infrastructure -> Deployment Targets, filtering by Tenant name with more than one Tenant yields no results

### ISSUE THREAD

**Issue by garrettdass** [OctopusDeploy/Issues#6907]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Filtering by two or more Tenants will remove all results as the filter is using 'and' instead of 'or'. 

## What I expected to happen

All matching Tenants should display when using filtering.

## Steps to reproduce

1. Go to Infrastructure > Deployment Targets 
2. Show Advanced Filters
3. Select two Tenants in the same filter

### Screen capture
No Filters
![image](https://user-images.githubusercontent.com/84342666/120857696-85492000-c536-11eb-8372-9f5a5b256889.png)

One Filter
![image](https://user-images.githubusercontent.com/84342666/120859216-bfb3bc80-c538-11eb-8b85-b8d02d23d187.png)

Two Tenants remove all results
![image](https://user-images.githubusercontent.com/84342666/120857747-985bf000-c536-11eb-8a2b-586b8d3c3c41.png)

## Affected versions

**Octopus Server:**
2021.1
## Workarounds

None

## Links
[Internal Link](https://octopus.zendesk.com/agent/tickets/70102)

**Comment by zentron** [comment]
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/pull/9303

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7396 |
| 2021.2 | 2021.2.6009 |
| 2021.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7396 |
| 2021.2 | 2021.2.6009 |
| 2021.3+ | _all releases_ |
