### ISSUE TITLE
If a phase does not override the retention policy, a previous phase's policy is used

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6917]
**Replication steps:**
* Create lifecycle with 2 phases
* Change the first phase to only retain 10 releases of tentacle files
* Don't override the retention policy for the second phase.
* Perform a deployment for the second phase environment and check the retention task. It will state that it is keeping 10 releases instead of all

The [logic here](https://github.com/OctopusDeploy/OctopusDeploy/blame/c89ce2626b0ffc206b6d7f8941b67fefda214b54/source/Octopus.Server/Orchestration/ServerTasks/Deploy/DeploymentFactory.cs#L467) is incorrect

**Affected versions**: `3.0.21` and later (believe it or not)

**Comment by N-lson** [comment]
Release Note: Fixed an isssue where the Tentacle retention policy of an earlier phase of a lifecycle was being used for a later phase if the later phase policy was left as default

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5272 |
| 2021.1 | 2021.1.7584 |
| 2021.2 | 2021.2.6482 |
| 2021.3 | 2021.3.438 |
