### ISSUE TITLE
Runbooks that run via scheduled triggers default to environment-level guided failure settings

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#6919]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Runbooks that run via scheduled triggers default to environment-level guided failure settings

## What I expected to happen

The runbook-level setting for guided failure should take precedence when run by a scheduled trigger.

## Steps to reproduce

1. Create a runbook - in settings, set the default guided failure mode to not use guided failure.
2. Create a process within this Runbook to run on a test environment, with the environment set to use guided failure by default.
3. Create a scheduled trigger for this runbook.
4. Allow runbook to run via the scheduled trigger.
5. Check dbo.RunbookRun to verify that "UseGuidedFailure" within the JSON is set to True.

### Screen capture

![image](https://user-images.githubusercontent.com/23742700/122195559-616ad000-ce8e-11eb-89e6-26aac42fb691.png)

## Affected versions

**Octopus Server:** 
Tested on: 2021.1.7316, 2021.1.7149
Customer reported on: 2020.6.4788

## Links

Internal Link to Customer Issue: https://octopus.zendesk.com/agent/tickets/70597

**Comment by kcamp** [comment]
Upvote for addressing this one please 👍  Is this on the roadmap for a release sooner than later?  This one has been problematic for a while.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5329 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | -tbc- |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5329 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5329 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | 2021.3.1254 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5329 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | 2021.3.1254 |
| 2022.1+ | _all releases_ |
