### ISSUE TITLE
Targets cannot download package straight from GitHub feed with credentials

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6922]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When using a GitHub package feed with credentials, the Octopus Server can successfully download the packages from the feed. But when setting a step to have the target download straight from the feed, the acquire packages step fails.

## What I expected to happen

Target should be able to download the package directly from the feed correctly.

## Steps to reproduce

1. Configure a GitHub feed in Octopus with credentials
2. Set up a step to deploy a package from this feed
3. Change the default on the step to `The package will be downloaded directly from the feed on the execution target`
4. Attempt to deploy
5. See error

![image](https://user-images.githubusercontent.com/20388190/122486978-79bd2500-d01d-11eb-84d6-7e69b51f3dd1.png)

### Log excerpt

```
Failed to download package xxx/xxx v1.0.0 from feed: 'https://api.github.com'
00:04:24   Error    |         The remote server returned an error: (404) Not Found.
00:04:24   Error    |         System.Net.WebException
00:04:24   Error    |         at System.Net.HttpWebRequest.GetResponse()
00:04:24   Error    |         at System.Net.WebClient.GetWebResponse(WebRequest request)
00:04:24   Error    |         at System.Net.WebClient.OpenRead(Uri address)
00:04:24   Error    |         at System.Net.WebClient.OpenRead(String address)
00:04:24   Error    |         at Calamari.Integration.Packages.Download.GitHubPackageDownloader.PerformRequest(ICredentials feedCredentials, String uri) in C:\buildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Integration\Packages\Download\GitHubPackageDownloader.cs:line 220
00:04:24   Error    |         at Calamari.Integration.Packages.Download.GitHubPackageDownloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String cacheDirectory, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff) in C:\buildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Integration\Packages\Download\GitHubPackageDownloader.cs:line 134
00:04:24   Error    |         at Calamari.Integration.Packages.Download.GitHubPackageDownloader.DownloadPackage(String packageId, IVersion version, String feedId, Uri feedUri, ICredentials feedCredentials, Boolean forcePackageDownload, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff) in C:\buildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Integration\Packages\Download\GitHubPackageDownloader.cs:line 63
00:04:24   Error    |         at Calamari.Integration.Packages.Download.PackageDownloaderStrategy.DownloadPackage(String packageId, IVersion version, String feedId, Uri feedUri, FeedType feedType, ICredentials feedCredentials, Boolean forcePackageDownload, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff) in C:\buildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Integration\Packages\Download\PackageDownloaderStrategy.cs:line 78
00:04:24   Error    |         at Calamari.Commands.DownloadPackageCommand.Execute(String[] commandLineArguments) in C:\buildAgent\work\e0cefbed4ad11812\source\Calamari\Commands\DownloadPackageCommand.cs:line 111
```

## Affected versions

Reported in 2021.1.7316 and reproduced in 2021.1.7322

Internal repro can be referenced here: 

[Release 1.0.0 succeeds](https://octopus-operations.octopus.app/app#/Spaces-142/projects/github-feed-testing/deployments/releases/1.0.0/deployments/Deployments-2127?activeTab=taskLog) as it's downloading to Octo server then uploading to target.
[Release 1.0.1 fails](https://octopus-operations.octopus.app/app#/Spaces-142/projects/github-feed-testing/deployments/releases/1.0.1/deployments/Deployments-2128?activeTab=taskLog) as the target is downloading straight from the GH feed.

## Workarounds

Change the selection back to the default, Octopus Server will download the package, then securely upload it to the Tentacles.

## Links

Reported here: https://octopus.zendesk.com/agent/tickets/70679 (private link)

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Targets cannot download package straight from GitHub feed with credentials](https://trello.com/c/j9JSvgex/99-targets-cannot-download-package-straight-from-github-feed-with-credentials)

**Comment by harrisonmeister** [comment]
Another report of this: https://octopus.zendesk.com/agent/tickets/71302 (private link)
