### ISSUE TITLE
Running 50-80+ deployments fails due to performance regression

### ISSUE THREAD

**Issue by kengel100** [OctopusDeploy/Issues#6929]
## The bug 
We have 2 reports of this issue so far. More details will be added as they become available. 
This is a performance regression in Release 2021.1.

We have been unable to reproduce this issue internally using the latest 2021.1 builds - investigations are continuing. 

## Affected versions

**Octopus Server:**
2021.1 - all builds (until a fix is available)

## Links
INTERNAL: https://octopus.zendesk.com/agent/tickets/71129
INTERNAL: https://octopusdeploy.slack.com/archives/C026R6Z2DC0/p1624581504024600

**Comment by droyad** [comment]
We have not been able to reproduce this specifically, however it's highly likely that some of the other performance issues outside of deployments caused heavy enough load on the server that the deployments started failing.
