### ISSUE TITLE
Usage not displayed for Accounts set to a variable in a variable set that is part of a release which blocks Account deletion

### ISSUE THREAD

**Issue by garrettdass** [OctopusDeploy/Issues#6932]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

After removing an Account variable from a variable set you are unable to delete the Account if any Releases have snapshotted the Account variable. Attempting to delete produces the error: `This account cannot be deleted as it is currently referenced by a variable. Please refer to account usage for more detail.` The Usage tab does not show any usage on where the variable is linked.

Similar to: https://github.com/OctopusDeploy/Issues/issues/6734

## What I expected to happen

The Usage tab should display where the Account variable is referenced.

## Steps to reproduce

1) Add an account variable to a variable set
2) Attach the variable set to a project
3) Create a release of the project
4) Delete the account variable from the variable set

### Screen capture

![image](https://user-images.githubusercontent.com/84342666/124168935-8c425000-da5a-11eb-8d36-73fbd30cae6e.png)

![image](https://user-images.githubusercontent.com/84342666/124168826-7a60ad00-da5a-11eb-89aa-951d7a881bcf.png)

### Log excerpt

No log available.

## Affected versions

**Octopus Server:**

v2021.1 (7236)

## Links

[Internal link](https://octopus.zendesk.com/agent/tickets/71517)
[Internal link](https://octopus.zendesk.com/agent/tickets/71238)

**Comment by droyad** [comment]
Thank you, I can see this can be quite annoying.

Fire and Motion team has added this to their backlog. We will look at the issue but not as a priority since it doesn't appear to block the deployment workflow and there are workarounds (manually find the releases and delete them).

**Comment by donnybell** [comment]
Here [another report](https://octopus.zendesk.com/agent/tickets/71573) of a customer affected by this issue.

**Comment by zentron** [comment]
Potentially related to https://github.com/OctopusDeploy/Issues/issues/7049

**Comment by KennethBates** [comment]
[Another report](https://octopus.zendesk.com/agent/tickets/84530)

**Comment by KennethBates** [comment]
[Another report](https://octopus.zendesk.com/agent/tickets/84599) of references in runbook snapshots (not releases)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4634 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4634 |
| 2023.2+ | _all releases_ |
