### ISSUE TITLE
Can't import a Bento package if the project doesn't reference a Library Variable Set but its Release still does

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#6933]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When exporting a project via Bento, we automatically include required referenced documents.

The problem here is that we're only including Library Variable Sets that are currently included by a Project, we're not following the link from a Release that still references Library Variable Sets that are no longer included by a Project.

## What I expected to happen

The Library Variable Sets that are only referenced by a Release should still be exported.

## Steps to reproduce

1. Create a Project that references a Library Variable Set
2. Create a Release
3. Remove the Library Variable Set from Project
4. Export the Project
5. Import the Project into a new Space

### Log excerpt

```
18:55:58   Verbose  |   The LibraryVariableSet 'LibraryVariableSets-530-D4C63A85E7894C5D8C20D9297FEA1A43' couldn't be found in the export set.
                    |   Reference path: Project 'Precis PTA' => Release '5.1.51.0'
                    |   Octopus.ImportExport.DocumentSources.BreadcrumbedException: The LibraryVariableSet 'LibraryVariableSets-530-D4C63A85E7894C5D8C20D9297FEA1A43' couldn't be found in the export set.
                    |   Reference path: Project 'Precis PTA' => Release '5.1.51.0'
                    |   ---> Octopus.ImportExport.Import.ImportDocumentNotFoundException: The LibraryVariableSet 'LibraryVariableSets-530-D4C63A85E7894C5D8C20D9297FEA1A43' couldn't be found in the export set
                    |   at Octopus.ImportExport.Import.ImportDocumentProvider.GetRequired[T](String id) in /opt/buildagent/work/c42ca9d2b8233f1c/source/Octopus.ImportExport/Import/ImportDocumentProvider.cs:line 33
                    |   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
                    |   at Octopus.ImportExport.DocumentSources.ImportedDocumentProcessor.Process[TModel](IReadOnlyCollection`1 originalIds, Func`2 matchAndSaveDocument) in /opt/buildagent/work/c42ca9d2b8233f1c/source/Octopus.ImportExport/DocumentSources/ImportedDocumentProcessor.cs:line 35
                    |   at Octopus.ImportExport.DocumentSources.LibraryVariableSetDocumentSource.<>c__DisplayClass3_0.<ImportDocuments>b__0(ILogWithContext taskLog) in /opt/buildagent/work/c42ca9d2b8233f1c/source/Octopus.ImportExport/DocumentSources/LibraryVariableSetDocumentSource.cs:line 46
                    |   at Octopus.ImportExport.DocumentSources.ImportExportContext.WithinLogContext[TReturn](CorrelationId correlationId, Func`2 logCallback) in /opt/buildagent/work/c42ca9d2b8233f1c/source/Octopus.ImportExport/DocumentSources/ImportExportContext.cs:line 56
                    |   at Octopus.ImportExport.DocumentSources.LibraryVariableSetsSnapshotDocumentSource.ImportDocuments(ImportContext context, ImportDocument`1 importedParent, Release targetRelease, ImportExportBreadcrumb importBreadcrumb)
                    |   at Octopus.ImportExport.DocumentSources.ProjectReleaseDocumentSource.<>c__DisplayClass11_2.<ImportDocuments>b__4(ImportExportBreadcrumb`1 breadcrumb) in /opt/buildagent/work/c42ca9d2b8233f1c/source/Octopus.ImportExport/DocumentSources/ProjectReleaseDocumentSource.cs:line 118

```

## Affected versions

**Octopus Server: 2021.1**

## Workarounds
- Delete the problematic release before exporting.
- Include the missing Library Variable Set in the Project again.

## Links
https://octopus.zendesk.com/agent/tickets/70804

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7496 |
| 2021.2 | 2021.2.6316 |
| 2021.3 | 2021.3.71 |
| 2022.1+ | _all releases_ |
