### ISSUE TITLE
Deleting replacement certificate causes error when accessing certificates replaced.

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#6938]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Using the 'Replace' feature on a Certificate then archiving and deleting the replacement causes all certificates that were replaced to throw an error on loading their UI page. 
This is likely due to the page trying to display the message 'This certificate was replaced by: THUMBPRINT' and cannot locate the thumbprint of the, now deleted, replaced certificate.

## What I expected to happen

A user should not be able to archive and delete linked certificates, a reason why should be provided or the option to cascade the deletion along to linked certs.

## Steps to reproduce

1. Create a new certificate in Octopus, Cert X.
2. Replace the certificate with a new one, Cert Y.
3. Archive and Delete Cert Y.
4. Try to load the page for Cert X.

### Screen capture

https://user-images.githubusercontent.com/23742700/124725462-ca30ef80-df04-11eb-97b6-33951faba8e2.mp4

### Log excerpt

`'No certificate was found with ID or thumbprint 'Certificates-Id'`

## Affected versions

Tested in **Octopus Server: 2020.6** and **Octopus Server: 2021.1**

## Workarounds

The workaround for this issue requires the database to be manipulated. Due to this - please reach out to Octopus Support should you run into this error.

## Links

Internal Link to Customer Ticket: https://octopus.zendesk.com/agent/tickets/71683

**Comment by N-lson** [comment]
Release Note: Existing certificates which point to a non-existent replacement certificate will no longer have an invalid reference. References to replacement certificates will be cleaned if the replacement certificate is deleted.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1724 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1724 |
| 2022.1+ | _all releases_ |
