### ISSUE TITLE
AWS SDK bundled with Calamari is unable to recognise/deploy to AF-South-1

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#6939]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When using "Deploy and AWS CloudFormation" or any other AWS step that uses the AWS SDK and attempting to target  the region "AF-South-1", the step fails with:

```
System.Net.Http.HttpRequestException: No such host is known. 
 ---> System.Net.Sockets.SocketException (11001): No such host is known. 

```

It seems that references to AF-South-1 weren't included in the AWS SDK until version 3.3.802.0. This means that the library will default to "<service>.<region>.amazonaws.com", e.g. s3.af-south-1.amazonaws.com which is a non-existent URL

## What I expected to happen

The step should succeed deploying to all Regions, including AF-South-1

## Steps to reproduce

1. Create a project with a single step: "Deploy an AWS Cloudformation Template"
2. Create a simple XML/YAML file to a deploy such as:
`Resources:
  BucketOfIssues:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead`
3. Set the target region to "AF-South-1"
4. Deploy

### Log excerpt

```
System.Net.Http.HttpRequestException: No such host is known. 
 ---> System.Net.Sockets.SocketException (11001): No such host is known. 
```

## Affected versions

Calamari 18.1.12

## Workarounds

Drop the latest AWS SDK DLL into Calamari.

## Links

https://octopus.zendesk.com/agent/tickets/71548

**Comment by mjhilton** [comment]
This was fixed in `2021.1` from version `2021.1.7595`, and the fix has since been rolled forward to all supported versions.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7571 |
| 2021.2 | 2021.2.6482 |
| 2021.3 | 2021.3.438 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7571 |
| 2021.2 | 2021.2.6482 |
| 2021.3 | 2021.3.438 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7571 |
| 2021.2 | 2021.2.6482 |
| 2021.3 | 2021.3.438 |
| 2022.1+ | _all releases_ |
