### ISSUE TITLE
React Error when creating API Key without setting Expiry Date - Firefox Only

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#6940]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When creating an API key for a User using the Firefox browser, if the dropdown for Set Expiry Date is expanded but an option not selected, an error will occur if the user clicks outside of the expanded dropdown. 

## What I expected to happen

I would expect Firefox to behave like other browsers, expanding the dropdown and not selecting an option without error.

## Steps to reproduce

1. Navigate to an Octopus Server using the Firefox Browser
2. Go to Configuration
2. Click on a User
3. Create a new API key for that user. 
4. Expand the dropdown for "Set Expiry Date"
5. Click anywhere outside of the expanded dropdown.
6. See Error

### Screen capture

<img width="924" alt="Screen Shot 2021-07-08 at 10 35 37" src="https://user-images.githubusercontent.com/78527975/124844655-3deffc80-dfd8-11eb-924a-a6b7d59a2df5.png">
<img width="908" alt="Screen Shot 2021-07-08 at 10 35 53" src="https://user-images.githubusercontent.com/78527975/124844671-46e0ce00-dfd8-11eb-8888-766ed689cdf9.png">

### Log excerpt

```
An unexpected error occurred in Octopus v2021.1.7469: "Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in TextInternal
    in r
    in div
    in div
    in CustomDialogContent
    in div
    in div
    in FrameWrapper
    in MediumDialogFrame
    in SmallDialogFrame
    in CustomSaveDialogLayout
    in AddApiKeyDialogLayout
    in div
    in t
    in ForwardRef
    in div
    in t
    in div
    in t
    in t
    in div
    in ModalRoot
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in DatabaseComponentContextProvider
    in FieldErrorContextProvider
    in ErrorContextProvider
    in CustomDialog
    in div
    in DialogTrigger
    in p
    in WithDialogIdentifier
    in OpenDialogButton
    in div
    in ActionList
    in div
    in div
    in RemoveItemsList
    in div
    in section
    in Section
    in UserApiKeysList
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in div
    in t
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ExpandableFormSectionInternal
    in ExpandableInternal
    in p
    in ContextualExpandableContainer
    in div
    in TransitionAnimation
    in div
    in div
    in TransitionAnimation
    in div
    in div
    in PaperLayout
    in div
    in KeyboardHandler
    in div
    in FormComponent
    in Unknown
    in FormPaperLayout
    in withRouter(FormPaperLayout)
    in UserEdit
    in ErrorBoundaryInternal
    in RouteAwareErrorBoundary
    in div
    in div
    in Unknown
    in main
    in div
    in div
    in MediaQuery
    in DrawerWrapperLayoutInternal
    in p
    in MediaQuery
    in div
    in NavigationSidebarLayout
    in withRouter(NavigationSidebarLayout)
    in main
    in ConfigurationLayout
    in RenderWithLayout
    in Unknown
    in Page
    in p
    in DatabaseComponentContextProvider
    in FieldErrorContextProvider
    in ErrorContextProvider
    in Unknown
    in RenderWithPage
    in t
    in ErrorBoundaryInternal
    in ReloadableRoute
    in t
    in t
    in ErrorBoundaryInternal
    in ReloadableRoute
    in t
    in ConfigurationRoutes
    in r
    in t
    in ErrorBoundaryInternal
    in ReloadableRoute
    in t
    in t
    in RootRoutes
    in withRouter(RootRoutes)
    in SpaceLoader
    in WithPersistedSpace
    in p
    in withRouter(Connect(WithPersistedSpace))
    in div
    in StandardLayoutInternal
    in p
    in t
    in ErrorBoundaryInternal
    in ReloadableRoute
    in SecureRoute
    in t
    in Unknown
    in Unknown
    in t
    in t
    in Unknown
    in DevToolsContextProvider
    in ClientConnector
    in W
    in t
    in Theme
    in p
    in DatabaseComponentContextProvider
    in FieldErrorContextProvider
    in ErrorContextProvider
    in ErrorBoundaryInternal
    in c
    in App
```

## Affected versions

Confirmed in the Latest version. Both Octopus Server and Hosted Cloud instances. 
FireFox browser only.

## Workarounds

Use another browser or make sure to select an option when using the Set Expiry Date dropdown.

## Links

[Internal Link - Zendesk](https://octopus.zendesk.com/agent/tickets/71842)

**Comment by droyad** [comment]
This is very obscure and we don't think many people will run into it. We are closing this in favour of higher value fixes.
