### ISSUE TITLE
Lifecycle page does not load Usage data opened directly via a URL

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6945]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When you're on a usage tab in the UI, refreshing the page in the browser often does not reload the usage information.

## What I expected to happen

The page you were looking at would repopulate with the correct usage data when you refresh the page in your browser.

## Steps to reproduce

1. Go to Library > Lifecycle > [Your Lifecycle] > Usage tab and see the list of projects using that lifecycle
2. Refresh this page in your browser
3. See the usage list previously displayed does not get repopulated with the projects

### Screen capture

Lifecycle usage:

![image](https://user-images.githubusercontent.com/20388190/125018896-4ec46f00-e0b9-11eb-8c46-834ecfd0807b.png)

After refresh:

![image](https://user-images.githubusercontent.com/20388190/125018909-54ba5000-e0b9-11eb-8ea7-0b7a9a8054dc.png)

Similar issues exist in other usages. E.g. in step template usages, a refresh just does not load the usage form at all. This results in: 

![image](https://user-images.githubusercontent.com/20388190/125018959-656ac600-e0b9-11eb-8f19-6ab05f07b911.png)

Whereas in account usage, a refresh when you're on usage tab will reload in the details tab, so this whole issue is avoided there.

## Affected versions

Reproduced in 2021.1.7500 in Chrome and Firefox

## Workarounds

Click the Details tab, then back on the Usage tab. This will repopulate the data correctly.

## Links

Reported here: https://octopus.zendesk.com/agent/tickets/71910 (private link)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1318 |

**Comment by desruc** [comment]
Release Note: Fetch Lifecycle usage data when accessing page directly

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1318 |
| 2022.1+ | _all releases_ |
