### ISSUE TITLE
Invalid step name can be provided for Release Versioning

### ISSUE THREAD

**Issue by charles-hague-octopus** [OctopusDeploy/Issues#6947]
# Prerequisites

- [ x ] I have verified the problem exists in the latest version
- [ x ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ x ] I have written a descriptive issue title
- [ x ] I have linked the original source of this report
- [ x ] I have labelled the value stream (area/core, area/steps, ...)
- [ x ] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

An invalid step name can be provided for Release Versioning. This results in the project becoming inaccessible.

## What I expected to happen

The invalid step name should be rejected.

## Steps to reproduce

1. Create a new project
2. Add a "Deploy a Package" step and call it "Initial Step Name"
3. In a new tab, go to the "Deployment Settings" page
4. View the list of steps available for "Release Versioning" and confirm that "Initial Step Name" is there
5. Leave that tab exactly as it is and go back to the first tab
6. In the first tab, rename the step to "Modified Step Name" and hit "Save"
7. Return to the other tab, select "Initial Step Name" from the list that is already loaded and hit "Save"
8. Observe the error message stating `The resource "Initial Step Name" was not found`
9. Observe that the same error appears on all pages under the project

### Screen capture

N/A

### Log excerpt

N/A

## Affected versions

**Octopus Server:** 2021.1

## Workarounds

Query the Octopus SQL db to find the affected record in `dbo.DeploymentSettings` (replace STEP NAME with the one from the error):
```
SELECT * FROM dbo.deploymentsettings
WHERE JSON like '%STEP NAME%'
```
Use a follow-up query to set the affected record in `dbo.DeploymentSettings` to default (replace STEP NAME with the one from the error):
```
UPDATE dbo.deploymentsettings
SET JSON = '{"VersioningStrategy":{"DonorPackage":null,"Template":"#{Octopus.Version.LastMajor}.#{Octopus.Version.LastMinor}.#{Octopus.Version.NextPatch}"},"ReleaseNotesTemplate":null,"DefaultToSkipIfAlreadyInstalled":false,"ConnectivityPolicy":{"SkipMachineBehavior":"None","TargetRoles":[],"AllowDeploymentsToNoTargets":false,"ExcludeUnhealthyTargets":false},"DeploymentChangesTemplate":null,"DefaultGuidedFailureMode":"EnvironmentDefault"}'
WHERE JSON like '%STEP NAME%'
```

## Links

https://octopus.zendesk.com/agent/tickets/71925 (internal)
https://octopus.zendesk.com/agent/tickets/71610 (internal)

**Comment by donnybell** [comment]
Here is another customer with the same issue: https://octopus.zendesk.com/agent/tickets/72223

**Comment by N-lson** [comment]
Release Note: Fixed an issue where a non-existent package action could be selected for Release Versioning

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7599 |
| 2021.2 | 2021.2.6580 |
| 2021.3 | 2021.3.519 |

**Comment by donnybell** [comment]
Another affected customer: https://help.octopus.com/t/unable-to-remove-tenant-tag/27179

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7599 |
| 2021.2 | 2021.2.6580 |
| 2021.3 | 2021.3.519 |
| 2022.1+ | _all releases_ |
