### ISSUE TITLE
Fetching channels for projects was slow/timing out due to resource mapping issues

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#6953]
# The bug

For the `/api/projects/{id}/channels` endpoint, our channel resource mappings were unnecessarily loading the project. This caused an N+1 performance issue (the more channels your project had, the more lookups occurred).

This became especially noticeable with large amounts of data, reaching the point where transactions were exhausted and causing the endpoint to time out.

## Affected versions

**Octopus Server:**
- 2021.1

## Workarounds

We recommend using the latest build of 2021.1 to avoid this issue

**Comment by MarkSiedle** [comment]
Release Note: Performance improvements to the project channels endpoint

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7548 |
| 2021.2 | 2021.2.6423 |
| 2021.3 | 2021.3.309 |
