### ISSUE TITLE
Package publish datetime in UI inconsistent between Release and Library pages

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6954]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

The package's publish date/time is displayed differently when viewing the package in a release, versus viewing the package in the built-in repo. The release page displays the time in UTC +x to account for timezone, where the package itself in the Library displays it in the browser timezone.

## What I expected to happen

Both places would display times in the browser timezone.

## Steps to reproduce

1. Push a package to the built-in repo
2. Create a release of a project that uses the package
3. View the package in the release page
4. Compare it to the package in the Library > Packages page

### Screen capture

Release:

![image](https://user-images.githubusercontent.com/20388190/126114785-369aa225-015a-483a-9a12-26cecb23e40f.png)

Package:

![image](https://user-images.githubusercontent.com/20388190/126114792-2ffca103-d4d2-426b-8ac8-7c93140f14ab.png)

## Affected versions

Reproduced in2021.1.7508

## Links

Report: https://octopus.zendesk.com/agent/tickets/72330 (private)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.931 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.931 |
| 2022.4+ | _all releases_ |
