### ISSUE TITLE
Can't create custom package step template with feed bound to a variable

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6956]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When creating a *new* custom step template based on any step that deploys a package (or container, etc.) the step cannot be saved if you have defined the feed to be bound to a variable.

Note: this seems to only apply to creating new templates. Updating existing ones to bind the feed to a variable works.

## What I expected to happen

The step should be successfully saved when binding a var to the feed.

## Steps to reproduce

1. Configure a new step template in Library > Step Templates
2. Bind the package feed field to a variable
3. Attempt to save

### Screen capture

![image](https://user-images.githubusercontent.com/20388190/126411407-6cf8ab7f-5051-4fcd-a8fa-9e432e861ba6.png)

## Affected versions

Reproduced in 2021.1.7508

## Workarounds

Unbind the feed and select any feed from the dropdown and save the template. Then attempt to re-bind it to a variable and the save is successful.

## Additional info

This also prevents extracting a step configured in a project's deployment process. Similar workaround to above is to unbind the feed, select a static feed, extract into step template, and then change both back.

In this case of extracting a step into a template, it is unsuccessful, and no error is surfaced to indicate why. Only when looking at the network response via browser dev tools are you shown the error.

## Links

Reported here: https://help.octopus.com/t/step-template-cant-be-created-for-k8s-step-when-the-image-registry-is-a-bound-variable/26926/3

**Comment by mjhilton** [comment]
Unable to reproduce on the latest version (`2022.4.3166`).
