### ISSUE TITLE
Octopus.Tentacle.Agent.ApplicationDirectoryPath variable does not truncate trailing slashes which may cause inconsistencies

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#6957]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Octopus.Tentacle.Agent.ApplicationDirectoryPath variable does not truncate trailing slashes which may cause inconsistencies when using this variable. This is set via the `Tentacle.Deployment.ApplicationDirectory` key in Tentacle.config.

For example:
Tentacle 1 `Octopus.Tentacle.Agent.ApplicationDirectoryPath` = C:\Applications
Tentacle 2 `Octopus.Tentacle.Agent.ApplicationDirectoryPath` = C:\Applications\

## What I expected to happen

Octopus.Tentacle.Agent.ApplicationDirectoryPath should account for this possible difference and maintain consistency by either truncating trailing slashes or adding it when they are not present.

## Steps to reproduce

1. write-host #{Octopus.Tentacle.Agent.ApplicationDirectoryPath}
2. Deploy against a Target
3. Change the `Tentacle.Deployment.ApplicationDirectory` key in Tentacle.config
4. Stop/Start the Tentacle service
5. Re-Deploy against the same Target

### Screen capture

![image](https://user-images.githubusercontent.com/63249187/126507878-a6daae19-c126-4160-a35b-56f71e8a9b97.png)

## Affected versions

Tested on 2021.1.7469, likely affects all versions with Octopus.Tentacle.Agent.ApplicationDirectoryPath.

## Workarounds

Use Regex Replace as a workaround:
`#{Octopus.Tentacle.Agent.ApplicationDirectoryPath | Replace "\\$" "" }`

## Links

[Internal Link](https://help.octopus.com/t/how-to-remove-trailing-directory-separators-after-variable-substitution/26919/7)

**Comment by droyad** [comment]
No further requests for this, so we are closing this for now.
