### ISSUE TITLE
Automatic release creation no longer occurs synchronously on package upload

### ISSUE THREAD

**Issue by uglybugger** [OctopusDeploy/Issues#6959]
# Background

As part of improving the performance of Octopus Server, some actions taken by the system have been moved to background tasks. One of these actions is automatic release creation.

## Before

Previously, an HTTP request to upload a package would only return once any relevant releases had been created. This meant that _every single package upload_ would check through all projects containing ARC rules to decide whether to create a release, and it would not return to the caller until that check had been completed.

## After

Now, an HTTP request to upload a package will return immediately once that package has been added to the internal Octopus package repository. This gives better response times for the overwhelmingly-common case of "I just want to upload a package".

The ARC release creation check is queued immediately upon package upload and will still commence within milliseconds of that package upload's completion, but the caller will not have to wait for the ARC check to complete.

# Implications

For most use cases, automatic release creation is a "fire and forget" concern, i.e. the reason to use ARC is that _all the caller wants to do is upload a package_. If this is the case in any of your code or scripts then no action should be required.

If you have code or a script which expects a release to exist immediately upon the uploading of a package, you will need to consider whether to poll for the creation of a release with the expected package number.

**Comment by uglybugger** [comment]
Release Note: Automatic release creation no longer occurs synchronously on package upload

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.3118 |
| 2021.3+ | -all releases- |
