### ISSUE TITLE
Extra slash after hostname during api request returns 405 error (unless using partialName)

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#6964]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labeled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When querying the API for **specific** data, including an extra slash after the server hostname returns a 405 error.

## What I expected to happen

The request should be resolved successfully.

## Steps to reproduce

1. Make a request to the API of an Octopus Server for a specific resource:
'https://octopus-server/api/Spaces-1/projects/Project-1'

2. Add an extra slash after the hostname of the server:
'https://octopus-server//api/Spaces-1/projects/Project-1'

### Screen capture

![image](https://user-images.githubusercontent.com/23742700/127532230-7e57e964-5781-4f67-b0ce-7924512e7865.png)

## Affected versions

**Octopus Server: 2021.1.7595**
_Issue was not present in 2021.1.7500_

## Workarounds

If the name of the resource is known, you can use partialName=NAME to have the request succeed however this may cause different issues.

## Links

Internal User Issue with investigation: https://octopus.zendesk.com/agent/tickets/72854

**Comment by tothegills** [comment]
Original fix: https://github.com/OctopusDeploy/OctopusDeploy/pull/8338

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7660 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | -tbc- |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7660 |
| 2021.2 | 2021.2.7154 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7660 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | 2021.3.1254 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7660 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | 2021.3.1254 |
| 2022.1+ | _all releases_ |
