### ISSUE TITLE
Terraform step will not parse template with "{{

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6966]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

A template like `a = "{{abc}}"` is not recognised by Octopus as valid HCL.

## What I expected to happen

The tample should save correctly.

## Steps to reproduce

1. Add a `Apply a Terraform template` step
2. Add an inline template of `a = "{{abc}}"`
3. Click the `Done` button
4. The error `The Terraform template parser failed for the supplied input. Ensure the template code is well formed.` is displayed.

## Affected versions

All versions of Octopus Server until 2021.3

## Workarounds

Applying the template from a file bypasses the HCL parsing in Octopus.

## Links

Internal Link: https://octopus.zendesk.com/agent/tickets/72890

**Comment by mcasperson** [comment]
This is fixed in HCL parser 1.1.3 - see this [PR](https://github.com/OctopusDeploy/Issues/issues/6966).

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.727 |
| 2022.1+ | _all releases_ |
