### ISSUE TITLE
Masks like `1.0.0-i` are not recognised

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6967]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When using a release version mask like `1.0.0-i`, the string is not detected as a mask and the release field is not incremented.

## What I expected to happen

A version string like `1.0.0-i` should be detected as a mask.

## Steps to reproduce

1. Create a new release version
2. Set the version string to `1.0.0-i`
3. Create the release
4. The version string was not used as a mask

## Affected versions

**Octopus Server: 2020.6 - 2021.2**

## Workarounds

Manually creating the correct version works as expected. Also versions like `1.0.0-something.i` work as expected.

## Links

Internal link: https://octopus.zendesk.com/agent/tickets/71996
PR in the versioning library: https://github.com/OctopusDeploy/Versioning/pull/22

**Comment by mcasperson** [comment]
This PR returns 2020.6 and above to the same functionality as 2020.5 (which was the latest version before any changes to the masking logic).

In Octopus 2020.5, using a mask like `0.0.3-i` resulted in that actual string being used for the release version:

![image](https://user-images.githubusercontent.com/160104/127801750-7071632f-9b9f-4585-9961-977bda312b1e.png)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5321 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | -tbc- |
| 2021.3 | -tbc- |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5321 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | -tbc- |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5321 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5321 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | 2021.3.1254 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5321 |
| 2021.1 | 2021.1.7646 |
| 2021.2 | 2021.2.7154 |
| 2021.3 | 2021.3.1254 |
| 2022.1+ | _all releases_ |
