### ISSUE TITLE
Lifecycle is now recorded directly on the release rather than resolved on demand via the channel

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#6968]
# Background
As parts of the Octopus information architecture are prepared to be version controlled, some of the assumptions that could previously be relied upon to be valid are no longer possible. One such relationship is how lifecycles and releases relate to one another.

## Before
In Octopus projects previous to this change, the lifecycle is defined in the channel, and it is by selecting a channel on a release that transitively defines which lifecycles that release can be deployed to. When the relevant lifecycle (and therefore environments) was required for a given release, Octopus would first load the given channel and read the lifecycle listed on it. This worked fine more as a convenient relationship rather than necessarily an explicit design decision.

## After
With the introduction of version controlled projects, the channel (and therefore its relationship to a given lifecycle) can be stored in the external data store that is git. This means that when a release is created, its progression and environmental rules would require loading data from an external system that Octopus has no control over. In keeping in like with deployment processes and variables, it makes sense to "snapshot" the lifecycle that was set on the channel at the time that the release was created. This change provides some additional safety, in that the environments that were contributed to variables scopes at the time of creation, should be reconsidered if the lifecycles used by that release are also updated.

## Implications
If the lifecycle on a channel is modified _after_ a release is created that uses that channel, that release will _not_ automatically have it's lifecycle and progression rules updated. Once the release is created and its package rules and lifecycle have contributed to the structure of the release, the channel relationship will primarily affect behavior through any relevant step conditions. Updating a lifecycle for an existing release will require modifying and re-saving that release, thereby updating the lifecycle based on the channel provided.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.5105 |
| 2021.3+ | _all releases_ |

**Comment by zentron** [comment]
This change has been reversed in `2021.3.2638`  https://github.com/OctopusDeploy/Issues/issues/7073
