### ISSUE TITLE
Variables with invalid type do not show up correctly on the UI

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#6970]
# The bug

Variables can be added from the API with different casings and unhandled types eg. `string` rather than `String`, or `nonexistenttype` which doesn't exist. These variables don't show up correctly on the UI.

## Steps to reproduce

1. Create a project
2. Get the variable set ID of the project eg. `variableset-Projects-1`
3. Follow [these steps](https://octopus.com/docs/octopus-rest-api/examples/variables/add-update-project-variable) to add a variable, using an unexpected type eg. `string`
4. Open the Variables for the project and note the input for the variable does not show up correctly.

### Screen capture

![image](https://user-images.githubusercontent.com/11970672/128125140-e5d2c962-dd36-456a-b00d-0bbfc2e7cbb2.png)

## Affected versions

**Octopus Server:** 2020.6+

## Workarounds

Modify the variable to have a `Type` with the correct casing eg. `String`

## Links

https://octopus.zendesk.com/agent/tickets/70609 (internal)

**Comment by N-lson** [comment]
Release Note: Validate variable types and correctly deserialize types to allow case-insensitive input

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.861 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.861 |
| 2022.1+ | _all releases_ |
