### ISSUE TITLE
Helm, Terraform, ARM Template, and CloudFormation steps referencing Docker images

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6973]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

A common use case when deploying cloud resources is to reference a Docker image. For example, deploying ECS task definition through cloud formation, an Azure Container Instance through ARM templates, doing either of those with Terraform, and specifying a Docker image as a Helm variable.

By adding Docker image references to these steps, they can declare a dependency on an image whose version is selected at release creation time.

## Proposed solution

Allow Docker images to be selected as package references, much like we do with the K8s YAML deployment step.

## Mockup

![image](https://user-images.githubusercontent.com/160104/128654447-51831d05-6106-48aa-b750-53e852939503.png)

## Workarounds

Defining package references in a script step and consuming the variables in a subsequent step can be used as a workaround.

## Links

Community Slack: https://octopususergroup.slack.com/archives/CBQ3FPQAH/p1627673870011200
Support request: https://help.octopus.com/t/deploy-with-helm-but-select-the-version-from-a-feed/26422/9

**Comment by mcasperson** [comment]
The ability to reference Docker images is now available in the Terraform, Helm, CloudFormation and ARM Template steps.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1001 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1001 |
| 2022.1+ | _all releases_ |
