### ISSUE TITLE
Server Manager fails to start in 2021.2 and newer.

### ISSUE THREAD

**Issue by MissedTheMark** [OctopusDeploy/Issues#6974]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Server manager fails to open in version 2021.2 and above, and shows an error message.

## What I expected to happen

Server manager should load the main screen.

## Steps to reproduce

1. Install Octopus Deploy 2021.2 and above
2. Open server manager

### Screen capture

![image](https://user-images.githubusercontent.com/46470837/128648240-8fda3bb8-ed19-4136-b6c5-bd039313685c.png)

## Affected versions

**Octopus Server: 2021.2+**

## Workarounds

None.

**Comment by MissedTheMark** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/9723

**Comment by MissedTheMark** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/9723

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7145 |
| 2021.3 | -tbc- |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7145 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7145 |
| 2021.3 | 2021.3.1254 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7145 |
| 2021.3 | 2021.3.1254 |
| 2022.1+ | _all releases_ |
