### ISSUE TITLE
Certificates that have been replaced cannot be deleted if the replacement certificate is deleted first

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#6976]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Attempting to delete a certificate which has been replaced by another fails due to the certificate being inaccessible. This is caused by the replacement certificate being deleted prior to trying to delete the replaced certificate. This leads to being unable to delete environments which these certificates are scoped to.

## What I expected to happen

Either:

- I should be warned on deleting the replacement certificate that other certificates need to be deleted first
- All certificates which reference the given certificate should be deleted at the same time the replacement certificate is deleted

## Steps to reproduce

1. Go to `Library -> Certificates`
2. Create a new Certificate
3. Edit the newly created Certificate, from the dropdown select `Replace` and replace the Certificate with another
4. Archive and delete the replacement Certificate
5. Click `View Archive` and try to open the replaced certificate

### Screen capture

![image](https://user-images.githubusercontent.com/11970672/129820196-eb543a35-16c8-4e44-9842-1ba68495447f.png)

## Affected versions

**Octopus Server:** 2020.6+ (most likely)

## Workarounds

// TODO: Add detection + fix script

## Links

https://octopus.zendesk.com/agent/tickets/67090 (Internal)

**Comment by AdamHollow49** [comment]
Is this the same behaviour as this issue [here](https://github.com/OctopusDeploy/Issues/issues/6938)?

**Comment by N-lson** [comment]
@AdamHollow49 Ah yeah that's right. I'll move the PR to point to that issue instead
