### ISSUE TITLE
403 from https://apt.octopus.com/public.key

### ISSUE THREAD

**Issue by chathsuom** [OctopusDeploy/Issues#6977]
Trying to get `https://apt.octopus.com/public.key`, but returning 403

```AccessDeniedAccess DeniedB90JM9FF34FHBGSGtuuQPY/Sjw0+trTyF2RnjfsqqPkd0wcWYogKQD+cBFG09H1/VwzOUnwb2YdaBL8tonkaM6MYjdg=````

**Comment by cailyoung** [comment]
Hi @chathsuom - sorry about that. We believe we've resolved this now. Please see the incident report [here.](https://status.octopus.com/incidents/s493zvbn5gmg)

If you have any further issue the best place to get attention is support@octopus.com
