### ISSUE TITLE
EventRelatedDocument insert failing with too many parameters

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6985]
# The bug

Requests that include a lot of related documents will fail when the `EventRelatedDocument` table is populated because the number of SQL parameters exceeds the SQL limit of 2100.

## Steps to reproduce

```
    public class RelatedDocumentStoreFixture : IntegrationTest
    {
        public RelatedDocumentStoreFixture(ITestOutputHelper testOutputHelper, RunningOctopusCluster cluster) : base(testOutputHelper, cluster)
        {
        }
        
        public async Task SupportsLotsOfParameters()
        {
            var spaceContext = await this.SpaceContextBuilder().Build(CancellationToken);
            var projects = Enumerable.Range(0, 500).Select(_ => spaceContext.ProjectBuilder().Build(CancellationToken).AsSync()).ToArray();
            await spaceContext.ScopedUserRoleBuilder().WithProjects(projects).Build(CancellationToken);
        }
    }
```

### Log excerpt

```
The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
The command being executed was:
INSERT INTO [dbo].[EventRelatedDocument]  ([EventId], [RelatedDocumentId], [RelatedDocumentIdPrefix]) VALUES 
(@0__EventId, @0__RelatedDocumentId, @0__RelatedDocumentIdPrefix)
....
```

## Affected versions

**Octopus Server:** 2021.1

## Links

https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1629496416150700

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7710 |
| 2021.2 | 2021.2.7358 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7710 |
| 2021.2 | 2021.2.7358 |
| 2021.3 | 2021.3.1762 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7710 |
| 2021.2 | 2021.2.7358 |
| 2021.3 | 2021.3.1762 |
| 2022.1+ | _all releases_ |
