### ISSUE TITLE
Allow CloudFormation templates to be deployed via S3

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6993]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

CloudFormation templates must be placed in S3 to support larger templates or use nested templates. This enhancement will allow the existing `Deploy an AWS CloudFormation template` step to deploy templates from S3.

## Proposed solution

Add fields that allow the template and parameters file to be selected from S3.

This is complemented by the [ability to process S3 file uploads with structured configuration variables](https://github.com/OctopusDeploy/Issues/issues/6997).

## Mockup

![image](https://user-images.githubusercontent.com/160104/131077421-2e2ce262-de8b-443a-88bd-063045bc3291.png)

## Workarounds

Running the `aws` cli directly allows CF templates to be deployed from S3.

## Links

Internal link: https://trello.com/c/VyZDkegD/36-enhance-cloudformation-deployments

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1848 |
| 2022.1+ | _all releases_ |
