### ISSUE TITLE
Deploy a Release step in a runbook doesn't allow selection of the same project

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#6994]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Currently the project dropdown on a Deploy a Release step in a runbook doesn't populate the current project the runbook resides in.

## What I expected to happen

The project the runbook is in would be in the dropdown list for selection.

## Steps to reproduce

1. Create a runbook
2. Create a Deploy a Release step in the runbook
3. In the project dropdown, see the project you're currently in is not populated

## Affected versions

Reproduced in **Octopus Server:** 2020.2.13 & 2021.2.7293

## Workarounds

- Set up the runbook in a different project.
- Use the community step Chain Deployment, which would also give you the benefit of not having to hardcode the release version in the runbook snapshot.

## Links

Reports: https://help.octopus.com/t/re-no-package-version-was-specified-for-the-step-x/25294 (private)
https://octopus.zendesk.com/agent/tickets/74579 (private)
Old discussion here: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1592446462239500
Mentioned here in the comment to this loosely related issue: https://github.com/OctopusDeploy/Issues/issues/6435#issuecomment-646390123

Discussions about this issue: https://octopusdeploy.slack.com/archives/C01GYCD6VUH/p1642651174067800

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.820 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.819 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.819 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.819 |
| 2022.2+ | _all releases_ |
