### ISSUE TITLE
Tentacle Installation Issue - Harden_Install_Directory.ps1 - Error 1603

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#6996]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When installing the latest version of Tentacle, the installation will fail with an error 1603 for some users. 

## What I expected to happen

I would expect the installation of Tentacle to run without error for anybody.

## Steps to reproduce

Unable to reproduce

### Log excerpt

```
Action start 11:49:18: HardenInstallationDirectory.
WixQuietExec:  Removing write permissions on C:\Program Files\Octopus Deploy\Tentacle for BUILTIN\Users
WixQuietExec:  Error 0x80070001: Command line returned an error.
WixQuietExec:  Error 0x80070001: QuietExec Failed
WixQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction HardenInstallationDirectory returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (AC:30) [11:49:19:870]: Note: 1: 2265 2:  3: -2147287035
```

## Affected versions

**Octopus Tentacle:**
Latest - 6.0.736

## Workarounds

Install a version of Tentacle that doesn't contain the Harden_Install_Directory.ps1 script 

## Links

[Discourse](https://help.octopus.com/t/unable-to-uninstall-or-install-octopus-tentacle/27043)

**Comment by N-lson** [comment]
Should've been fixed by https://github.com/OctopusDeploy/OctopusTentacle/pull/351
