### ISSUE TITLE
Add support for structured variable replacements in S3 uploads

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6997]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

When uploading files to S3 we allow variable replacements to be performed. This should be enhanced to allow structured variables to be injected into files as well.

## Proposed solution

The S3 step will be expanded to allow individual files to be processed with structured configuration variables, and when uploading multiple files a file pattern can be defined.

## Mockup

![image](https://user-images.githubusercontent.com/160104/131047416-ebd87d57-5836-45aa-9590-551e52d3bd5f.png)

## Workarounds

Using the AWS Script step and manually uploading files allows them to be processed with structured configuration variables.

## Links

Internal link: https://trello.com/c/p9DMlsVK/93-s3-structured-variable-replacements

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1855 |
| 2022.1+ | _all releases_ |
