### ISSUE TITLE
Export Terraform plan output in JSON

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6998]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

Terraform 0.12 introduced the ability to output plan results as JSON. This allows the details of the plan to be parsed, extracted, and used in customized reports. 

## Proposed solution

The Terraform plan steps in Octopus will be updated to allow plan steps to generate JSON output, and capture the results in output variables.

## Mockup

![image](https://user-images.githubusercontent.com/160104/131058550-cfebc993-da71-4141-85a1-61b746e846af.png)

## Workarounds

Running Terraform from a script step allows the `--json` option to be defined and output variables to be captured.

## Links

Internal link: https://trello.com/c/feAKRfR1/109-show-terraform-plan-step-output-as-structured-json-instead-of-a-single-string-variable

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1846 |
| 2022.1+ | _all releases_ |
