### ISSUE TITLE
Octopus Bundled AWS CLI tools warning message shows on existing process steps when running tools on containers

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#6999]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

'Run an AWS CLI script' steps which use the AWS tools on a worker created before upgrading to 2021.2 do not contain the flag `'OctopusUseBundledTooling = "false"'` as a result, even when using worker tools, the warning message `Using the AWS tools bundled with Octopus is not recommended. Learn more about AWS Tools at https://g.octopushq.com/AWSTools.` shows up as a false positive.

## What I expected to happen

The check to display the warning message would look specifically for `OctopusUseBundledTooling = 'True'` rather than the lack of a flag.
This would mean that steps created even before the change wouldn't show this warning message.

## Steps to reproduce

Reproducing this warning without running 2021.1 and upgrading requires some API manipulation as creating the issue organically is impossible due to newly created steps having the 'False' flag.

1. Create a project with a 'Run an AWS CLI script' step.
2. Configure it to use the AWS tools running on a worker.
3. Open the API to show the process steps for this project.
4. Copy the API process steps and remove the 'OctopusUseBundledTooling' flag.
5. PUT these new process settings to the project via the API
6. Run the project and observe the warning message. 

### Screen capture

![image](https://user-images.githubusercontent.com/23742700/131135581-7cfefb24-7562-4941-bca3-94234f7b1eb4.png)

### Log excerpt

```
Using the AWS tools bundled with Octopus is not recommended. Learn more about AWS Tools at https://g.octopushq.com/AWSTools. 
```

## Affected versions

**Octopus Server:2021.2.X**

## Workarounds

You can remove the warning by opening the process step and de-selecting 'Run inside a container', then swapping the setting for the tooling to use those on a worker, then saving the project. After, you would then re-select 'Run inside a container' and configure the container as appropriate.
Alternatively, you can add the `OctopusUseBundledTooling = 'False'` flag via API.

## Links

Cloud repro: https://octopus-operations.octopus.app/app#/Spaces-262/projects/aws-cli-warning-repro/deployments

**Comment by mcasperson** [comment]
Some investigation notes.

The `awsRunScriptAction.tsx` file was modified to set `OctopusUseBundledTooling` to a default value of `False`.

The logic to display the option to use bundled tools is exposed in `BundledToolsEditBase.tsx`. It will only be displayed if `!runOn.runningInContainer`.

Meanwhile in the server code base, the decision to use the bundled tools in `AwsActionHandlerExtensionMethods` will default to true if `OctopusUseBundledTooling` is undefined.

So when upgrading from an old release where an execution container has been defined, the options to not use bundled tools are hidden because `BundledToolsEditBase.tsx` detects the use of an execution container, `OctopusUseBundledTooling` remains undefined because `awsRunScriptAction.tsx` never set the default value, and Octopus treats the absence of  `OctopusUseBundledTooling` as an indication that the bundled tools will be used.

**Comment by mcasperson** [comment]
The PR to address this issue makes a potentially breaking change by setting the `OctopusUseBundledTooling` variable for any steps upgraded from old versions. The migration script will set `OctopusUseBundledTooling` to false for steps that use an execution container, and true to steps that don't.

For those edge cases where using bundled tools inside an execution container is required, the `OctopusUseBundledTooling` variable can be set at the project level, and optionally scoped to individual steps. By setting `OctopusUseBundledTooling` to true at the project level, the step variable is overridden, and the legacy behavior is maintained.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7454 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7454 |
| 2021.3 | 2021.3.2040 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7454 |
| 2021.3 | 2021.3.2040 |
| 2022.1+ | _all releases_ |
