### ISSUE TITLE
Validate the JSON entered into the Azure Web Service step

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#7000]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

The Azure Web Service deployment step can have two JSON fields defined. These should be validated where possible to ensure only JSON has been entered.

## Proposed solution

The JSON fields will be presented as code dialog boxes with the content validated when the dialog is closed.

## Mockup

![image](https://user-images.githubusercontent.com/160104/131269121-487a9c3a-a745-45dd-9fbf-9d415ab33f64.png)

## Workarounds

The JSON could be validated outside of Octopus if needed using one of the many JSON linting services on the web.

## Links

Internal Link: https://trello.com/c/69OPoxmm/120-validate-the-new-azure-step-application-settings-json

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validate the new Azure step Application settings JSON.](https://trello.com/c/69OPoxmm/120-validate-the-new-azure-step-application-settings-json)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1901 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1901 |
| 2022.1+ | _all releases_ |
