### ISSUE TITLE
Creating a self-signed Certificate with tenanted deployments does not save as tenanted

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7003]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

If you try to create a Certificate and select `Include only in tenanted deployments` along with a chosen tenant/tenant tag, after saving the Certificate it will say `Only available for untenanted deployments`. The database record shows that the Certificate is saved as Untenanted with no tenants connected.

## What I expected to happen

The Certificate should be saved as tenanted with the selected tenant/tenant tag listed as an association.

## Steps to reproduce

1. Create a Project/Tenant if none exist
2. Go to `Library` -> `Certificates`
2. Click `Add Certificate` and fill in name, certificate data (select 'Create Self Signed')
3. Under `Tenanted Deployments` select `Include only in tenanted deployments` and under `Associated Tenants` select the tenant
4. Save the Certificate

### Screen capture

![image](https://user-images.githubusercontent.com/11970672/131438478-f63b09ef-ad06-4010-86e7-575d76038f9e.png)

## Affected versions
**Octopus Server:** 2020.6+

## Workarounds

After saving the certificate re-enter the tenanted deployment details and re-save. The tenanted settings will be updated correctly.

**Comment by N-lson** [comment]
Release Note: Self-signed Certificates are now correctly saved as tenanted if the option is selected

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9531 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9531 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9531 |
| 2022.1+ | _all releases_ |
