### ISSUE TITLE
Automatic Release Creation shows Package Step: Not Found

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#7004]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When configuring the Automatic Release Creation trigger it will display Package Step: Not Found after saving the settings. The trigger will function as normal though, this seems to be a UI problem only.

## What I expected to happen

The package step selected should be displayed.

## Steps to reproduce

1. Go to Triggers within a Project
2. Ensure project has a deploy package step 
3. Click Setup on the Automatic Release Creation
4. Select the package step and Save
5. Check the Package Step text for "Not Found"

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/131474646-138bf6af-469f-47ca-8492-a4d2b60049e2.png)

## Affected versions

**Octopus Server:** 2021.2

## Workarounds

None required, the trigger will work normally.

## Links

[Internal Link](https://octopus.zendesk.com/agent/tickets/74833)

**Comment by garrettdass** [comment]
It looks like this bug is causing issues with the Usage tab under Lifecycles as well. ARC turned on will cause all projects to disappear from the usage like so: 
![image](https://user-images.githubusercontent.com/84342666/134592665-17b68f84-daa5-4c0a-bb2f-799663498fdb.png)
Disabling ARC on all projects that use this lifecycle will cause the usage to reappear:
![image](https://user-images.githubusercontent.com/84342666/134592978-20d3ecb4-e27e-418a-b0f3-b8b36765219e.png)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7693 |
| 2021.3 | 2021.3.6643 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7693 |
| 2021.3 | 2021.3.6643 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7693 |
| 2021.3 | 2021.3.6643 |
| 2022.1+ | _all releases_ |
