### ISSUE TITLE
Release Versioning package step not displayed

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#7005]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When a package step is selected to control release versioning. Opening the setting up will not display the selected step in the drop-down. This is only a UI issue though, the functionality does work as normal.

## What I expected to happen

The step should be displayed.

## Steps to reproduce

1. Select a project with a deploy package step
2. Go to Project > Deployment Settings
3. Edit Release Versioning to use a version from a package
4. Select a package step and save
5. Expand the setting again and the package step drop down will be blank

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/131522693-53845fc3-392e-4c1e-8b62-7896c5bbad61.png)

## Affected versions

**Octopus Server:** 2021.2

## Workarounds

None required, the functionality works as normal.

## Links

https://help.octopus.com/t/versioning-package-step-is-not-retained/27088

Might be related to: https://help.octopus.com/t/package-step-not-found-after-selecting-trigger/27086/3

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7693 |
| 2021.3 | 2021.3.6643 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7693 |
| 2021.3 | 2021.3.6643 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7693 |
| 2021.3 | 2021.3.6643 |
| 2022.1+ | _all releases_ |
