### ISSUE TITLE
sudo checks on Server/Tentacle do not recognise root shell without sudo.

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#7006]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug
Command arguments that have an elevated access check, we run a `sudo -vn` to verify that the user has access to use `sudo`. This works in most situations, but we do not check to see if the user is root. In situations where root does not have sudo access (it does by default in most scenarios), this check will fail. We should additionally be checking to see if the user is root or has sudo access.

Note: This requires additional environmental configuration, by default this will work, as root has full `sudo` access on almost all distributions.

## What I expected to happen
Access checks should check to see if the current user is root, or has sudo access. We could add an additional `id -u` command to check if the user is root. Command will return 0 if the user is root.

## Steps to reproduce
1. Remove sudo access from the `root` user in `/etc/sudoers` by deleting the line that looks like `root		ALL = (ALL) ALL`
2. Obtain a root bash shell (`su`/`sudo` or direct login if enabled)
3. Attempt to run a command that requires the elevated permissions, `Tentacle service --stop` etc.
4. See error.

### Log excerpt

```
[root@server ~]# sudo -vn
sudo: a password is required
[root@server ~]# echo $?
1
[root@server ~]# /opt/octopus/tentacle/Tentacle service --stop
Requires elevated privileges. Please run command as sudo.
```

## Affected versions

**Octopus Server: 2019.8 ->**

## Workarounds
* Run command as a user with sudo access.
* If root requires password authentication, pre-authenticate so that you have a valid recent sudo, and the `sudo -vn` works.

## Links

* (Internal link) Initial report: https://octopus.zendesk.com/agent/tickets/74877
* (Internal link) Slack discussion: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1630444665080000
* (Internal link) Code in question: https://github.com/OctopusDeploy/OctopusShared/blob/master/source/Octopus.Shared/Startup/LinuxServiceConfigurator.cs#L204-L231

**Comment by octokhor** [comment]
Won't fix as it's been hanging around for awhile with no additional customer complaints. Closing now unless more need is necessary in the future.
