### ISSUE TITLE
Swagger generated URL for api-key deletion is incorrect.

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#7007]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When using Swagger to generate a request URL to delete an API Key, an invalid URL is generated.

Swagger created URL: `https://OctopusURL/api/users/Users-IDkeys/apikeys-ID`
How the URL should look: `https://OctopusURL/api/users/Users-ID/apikeys/apikeys-ID​`

## What I expected to happen

The URL is created correctly. (It appears that '/api' is removed from the middle of the URL, perhaps some sort of string manipulation is removing this.)

## Steps to reproduce

1. Go to https://octopusurl/swaggerui
2. Scroll to the API key section.
3. Select 'Delete' and click the 'Try it out' button on the top right.
4. Enter a Users-ID and apikeys-ID.
5. Click 'Execute' and observe the incorrect URLs

### Screen capture

![image](https://user-images.githubusercontent.com/23742700/131689060-87be759c-bdc2-4884-bd60-4b55db6516ad.png)

### Log excerpt

404 | Error: Response body{   "ErrorMessage": "The resource you requested was not found." }

## Affected versions

**Octopus Server: 2021.2.X** perhaps also earlier.

## Workarounds

Manually add the '/api' to the URL created by swagger and perform the request using PowerShell or Postman.

## Links

Internal User ticket: https://octopus.zendesk.com/agent/tickets/74925

**Comment by N-lson** [comment]
Release Note: Fix Swagger documentation for `DELETE apikeys`

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2124 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2124 |
| 2022.1+ | _all releases_ |
