### ISSUE TITLE
Add Google Cloud support to New-OctopusKubernetesTarget cmdlet

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/Issues#7008]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this feature request
- [ ] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have added the kind/enhancement label

# The enhancement
Octopus introduced support for Google Cloud in 2021.2, however, the New-OctopusKubernetesTarget cmdlet doesn't currently have parameters needed for adding a GKE cluster.  I'm proposing that we add the necessary parameters to the cmdlet so it is supported like AKS and EKS.

## What is the problem this solves or benefit it gives
With the added support of Google Cloud, a customer may expect existing functionality is extended to the new cloud provider.  Adding the necessary parameters to the New-OctopusKubernetesTarget cmdlet would show that Google is supported like the other cloud providers.

## Proposed solution
Some of the necessary functionality already exists such as specifying which Account to use.  I recommend the following parameters:
ProjectId: The Google Cloud project Id
Region: The Google Cloud region code
Zones: An array of zone IDs for Google cloud.

## Workarounds
The API can be used to add a GKE cluster as a deployment target.  The cmdlet would make this a nice, one-line operation

```
# Get the variables
$clusterName = $OctopusParameters['Google.Kubernetes.Cluster.Name']
$gkeUrl = $OctopusParameters['Octopus.Action[Create GKE Cluster].Output.GKEURL']
$octopusUrl = $OctopusParameters['Global.Base.Url']
$apiKey = $OctopusParameters['Global.Api.Key']
$spaceId = $OctopusParameters['Octopus.Space.Id']
$headers = @{ "X-Octopus-ApiKey" = $apiKey }

# Add new Kubernetes cluster target
#New-OctopusKubernetesTarget -Name "Samples-#{Octopus.Space.Name | Replace " "}-GKE" -clusterName $clusterName -octopusRoles "test1" -octopusAccountIdOrName "#{Google.Account.Name}" -namespace "default" -skipTlsVerification $true -octopusDefaultWorkerPoolIdOrName "Hosted Ubuntu" -healthCheckContainerImageFeedIdOrName "Docker Hub" -healthCheckContainerImage "octopusdeploy/worker-tools:3.0.0-ubuntu.18.04"


$newMachine = @{
	Name = "$clusterName-GKE"
    Endpoint = @{
    	CommunicationStyle = "Kubernetes"
        Authentication = @{
        	AuthenticationType = "KubernetesGoogleCloud"
            AccountId = $OctopusParameters['Google.Account.Name']
            UseVmServiceAccount = $false
            ImpersonateServiceAccount = $false
            Project = $OctopusParameters['Google.Project.Name']
            Region = $OctopusParameters['Google.Region.Name']
            ClusterName = $clusterName
        }
        AccountType = "GoogleCloudAccount"
        DefaultWorkerPoolId = "WorkerPools-1143"
        Container = @{
        	FeedId = "Feeds-2124"
            Image = "octopusdeploy/worker-tools:3.0.0-ubuntu.18.04"
        }
    }
    Roles = @("PetClinic")
    EnvironmentIds = @($OctopusParameters['Octopus.Environment.Id'])
}

# Call API to register cluster
Invoke-RestMethod -Method Post -Uri "$octopusUrl/api/$spaceId/machines" -Body ($newMachine | ConvertTo-JSON -Depth 10) -Headers $headers
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2806 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2806 |
| 2022.1+ | _all releases_ |
