### ISSUE TITLE
Audit log not showing some changes for document modified entries in portal

### ISSUE THREAD

**Issue by patrick-smergut-octopus** [OctopusDeploy/Issues#7009]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

The audit log isn't showing some of the changes (red/green highlights and associated modified records) for document modified events. This seems to be fairly widespread in the octopus-operations instance, and isn't limited to a specific document type.

## What I expected to happen

When a document is modified (e.g. a user is added or removed from a team in the hosted environment), it should be shown in the audit log. The below steps show when a user was added to a team, and then removed.

## Steps to reproduce

Example for modifying a team (there are other existing examples in the octopus-operations instance you can view in the audit log):

1. Go to https://octopus-operations.octopus.app
2. Click on Configuration > Teams
3. Add or remove a user from a team (e.g. add/remove a user from team Service Account Limited Privs)
4. Go to the audit log in Configuration > Audit
5. Expand the relevant document modified event and check for changes

The below screenshot shows the audit log for when a user was removed, and then the next event when the user was added to the team.

### Screen capture
![image](https://user-images.githubusercontent.com/83607909/132074509-dbd096bd-8609-4aa6-81f2-9a24ac757fed.png)

## Affected versions

**Octopus Cloud: 2021.2.7428**

## Workarounds

No known workarounds.

## Links

[Internal] https://octopus-operations.octopus.app/app#/Spaces-1/configuration/audit?includeSystem=true&spaces=Spaces-1
Not yet identified externally.

**Comment by MarkSiedle** [comment]
Release Note: Fixed auditing diffs for document modified entries

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7650 |
| 2021.3 | 2021.3.4658 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7650 |
| 2021.3 | 2021.3.4658 |
| 2022.1+ | _all releases_ |
