### ISSUE TITLE
Subscription payload has changed

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7013]
### Team

- [X] I've assigned a team label to this issue

### Severity

Breaks automations that depend on the subscription payload format

### Version

2021.2

### Latest Version

I could reproduce the problem in the latest version

### What happened?

I have a user who noticed there's a new subtype of 'Value' beneath SpaceId in a JSON payload returned from a subscription. They have an azure function that handles deployment target subscription events and it is throwing exceptions:
Exception while executing function: MachineAdded Unexpected character encountered while parsing value: {. Path 'Payload.Subscription.SpaceId', line 1, position 1272.
They've provided the JSON payload from a subscription (in :thread:), and it does show SpaceId with a subtype Value beneath it.

### Reproduction

Create a subscription and observer the payload:

```
"Payload": {

    "ServerUri": https://drbsystems.octopus.app,

    "ServerAuditUri": https://drbsystems.octopus.app/app#/Spaces-3/configuration/audit?environments=Environments-261&eventCategories=MachineAdded&from=2021-09-03T20%3a01%3a49.%2b00%3a00&to=2021-09-03T20%3a02%3a19.%2b00%3a00,

    "BatchProcessingDate": "2021-09-03T20:02:19.2174415+00:00",

    "Subscription": {

      "Id": "Subscriptions-161",

      "Name": "MachineAdded-OEFunc-Test",

      "Type": 0,

      "IsDisabled": false,

      "EventNotificationSubscription": {

        …..removed

      },

      "SpaceId": {

        "Value": "Spaces-3"

      },
  ```

**Comment by N-lson** [comment]
Release Note: Remove `Value` under `SpaceId` and convert enums to strings in the subscription payload

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7536 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7536 |
| 2021.3 | 2021.3.2185 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7536 |
| 2021.3 | 2021.3.2185 |
| 2022.1+ | _all releases_ |
