### ISSUE TITLE
Main menu UI bug with safari MacOS

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#7014]
### Team

- [X] I've assigned a team label to this issue

### Version

cloud version: v2021.1 (Build 7322)

### Latest Version
master

### What happened?
After a page loads, the main menu bar is in the wrong position when you scroll down, then back up.

https://user-images.githubusercontent.com/82346985/132273571-b86bfd49-32e9-4fa5-99cc-507d881456c6.mp4

https://user-images.githubusercontent.com/82346985/132273654-f9ae303c-f39e-4a85-86fe-2e8143bd8486.mp4

### Reproduction
1. Open Octopus Deploy portal in safari
2. Create a project & navigate to deployments > process > add step
3. Expand all form sections & play around with scrolling down/up the page. The bug appears randomly (for me, anyway)

### More Information

Original bug report:
Safari: Version 14.1.1 (16611.2.7.1.4)) & 14.0.3 on macOS Big Sur v11.2.3 (m1 chip)

### Workaround

Use chromium or firefox browser

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7777 |
| 2021.2 | 2021.2.7555 |
| 2021.3 | 2021.3.2264 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7777 |
| 2021.2 | 2021.2.7555 |
| 2021.3 | 2021.3.2264 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7777 |
| 2021.2 | 2021.2.7555 |
| 2021.3 | 2021.3.2264 |
| 2022.1+ | _all releases_ |
