### ISSUE TITLE
Environment and project filters against deployments API endpoint don't work when used in conjunction with the TaskState filter

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#7016]
### Team

- [X] I've assigned a team label to this issue

### Severity

One report with a workaround

### Version

2021.2.7428

### Latest Version

Not applicable

### What happened?

SQL error 8003 can occur when querying Deployments API endpoint with a TaskState filter. If you were to use the env or project filters in the GET, I would expect only the tasks matching all filter criteria would be returned (e.g. only successful tasks associated with project X in env X). Instead, it looks like we run a SQL query against every task matching only the state filter, which can be many, many more than expected. This can lead to the below error.

### Reproduction

See source report

### Error and Stacktrace

```shell
SQL Error 8003 - The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
```
```


### More Information

Report: https://octopus.zendesk.com/agent/tickets/75093

### Workaround

- Remove the TaskState filter
- Tighten retention so as to cut down the total number of tasks that will be queried

**Comment by jnus** [comment]
Any update on this issue? We recently upgraded and hit this issue, currently blocking a number of deployment pipelines.

**Comment by droyad** [comment]
example `https://company.com/api/deployments?take=1&environments=Environments-6&projects=MyProject&taskState=success`

**Comment by droyad** [comment]
Introduced in `2021.2.3944`

**Comment by droyad** [comment]
Workaround: Drop the `taskState` parameter

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8102 |

**Comment by droyad** [comment]
Release Note: Fixed `too many parameters` error when using the `deployments` api

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7803 |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
