### ISSUE TITLE
`Download custom version` menu item should go to the Tentacle download page

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7019]
Remove the "Download custom version" from the dropdown button and make it an external link because t doesn't download anything and change the name to something like `Need a different version`

![image (1)](https://user-images.githubusercontent.com/82346985/132620039-d972e1f4-83b4-41e8-9e53-baec524f0e3b.png)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2298 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2298 |
| 2022.1+ | _all releases_ |
