### ISSUE TITLE
Parallel package push may fail

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7022]
### Team

- [X] I've assigned a team label to this issue

### Severity

Failed build but re-run works

### Version

At least 2021.1

### What happened?

We experienced an intermittent issue when trying to push a package to octopus server during [this build](https://build.octopushq.com/buildConfiguration/OctopusDeploy_OctopusCLI_ReleaseDeployOctopusClients/1688401?logFilter=debug) of OctoCLI. See the [logs](https://build.octopushq.com/buildConfiguration/OctopusDeploy_OctopusCLI_ReleaseDeployOctopusClients/1688401?showLog=1688401_509_477.478.514&logFilter=debug).

[Seq log event](https://seq.octopushq.com/#/events/?filter=@Id%20%3D%20%27event-2fd562ef765a08d81238efca00000000%27&showExpanded&permalinkId=permalink-8107)

Looking back through the last page of build results, this is the only occurrence. 

We ran into this issue on deploy.octopus.app: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1603864882480400

This happened in [this build](https://build.octopushq.com/buildConfiguration/OctopusDeploy_OctopusServer_PublishPushPackagesAndCreateRelease/1704209?buildTab=log&focusLine=3&linesState=55.56).

Seq Logs from this build
- [Failure](https://seq.octopushq.com/#/events/?filter=@Id%20%3D%20%27event-989de3267b0608d8c37564cd00000000%27&showExpanded&permalinkId=permalink-8108)
- [Related failure?](https://seq.octopushq.com/#/events?from=2020-10-28T05:00:00.000Z&to=2020-10-28T06:00:00.000Z&filter=Octopus.Installers)

We asked for more context in QRF channel: https://octopusdeploy.slack.com/archives/CLQNM80U9/p1603695426403500

Escalating this issue: https://octopusdeploy.slack.com/archives/CLQNM80U9/p1603866645018200

A case we found for a real customer by searching through Seq: https://seq.octopushq.com/#/events/?filter=@Id%20%3D%20%27event-e14819e67f0008d84fe76ccf00000000%27&showExpanded&permalinkId=permalink-8111 You can search seq by searching for "Could not find a part of the path"

### Reproduction

See description

**Comment by octokhor** [comment]
Looks like only we faced this internally. Closing this down for now.
