### ISSUE TITLE
Kubernetes deployments on a Linux worker always wait for the deployment

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#7023]
### Team

- [X] I've assigned a team label to this issue

### Severity

This was reported internally and is not blocking any customers

### Version

All versions of Octopus supporting Kubernetes deployments are affected

### Latest Version

I could reproduce the problem in the latest version

### What happened?

When deploying a Kubernetes deployment on a Linux worker, and setting the `Do not wait for the deployment to succeed` option, Octopus will still wait for the deployment to succeed.

The expected result is that the deployment is started and the step finishes without waiting.

### Reproduction

1. Created a `Deploy Kubernetes Containers` step
2. Select the `Do not wait for the deployment to succeed` option
3. Set the step to run on a Linux worker
4. Notice that the step does wait for the deployment to succeed.

### Workaround

A windows worker can be used to solve the issue.

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [K8s deployment on Linux worker does not respect the UI option to not wait for deployment to succeed.](https://trello.com/c/bCp4aJsc/147-k8s-deployment-on-linux-worker-does-not-respect-the-ui-option-to-not-wait-for-deployment-to-succeed)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2104 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2104 |
| 2022.1+ | _all releases_ |
