### ISSUE TITLE
Deployment Time Calculations are off

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7026]
### Team

- [X] I've assigned a team label to this issue

### Version

Unknown

### Latest Version

Not applicable

### What happened?

From @peterlanoie (https://octopusdeploy.slack.com/archives/C80H394RK/p1621869179009300)

I've noticed a few minute errors with the deployment running time calculations. In my short test (I tested several times to double check):
running time update is ahead by 1 minute and about 3 seconds (I've noticed this 1+ minute error before)
overall time elapsed is reporting short by about 6 seconds

### Reproduction

See screenvid

### More Information

![timemath](https://user-images.githubusercontent.com/1687639/132603916-da02a8cd-cd3e-43f1-bfca-9b5a7f1d8e36.gif)

**Comment by zentron** [comment]
Closing unless this is raised again by a user
