### ISSUE TITLE
Project trigger validation message is cryptic

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7027]
### Team

- [X] I've assigned a team label to this issue

### Version

All

### Latest Version

I could reproduce the problem in the latest version

### What happened?

When attempting to save a project trigger, a message about cron expressions is returned:

![image](https://user-images.githubusercontent.com/171197/132609842-f8414ba8-b55e-428b-9979-1d42ae64a2a8.png)

### Reproduction

Create a scheduled project trigger but omit some of the fields.

**Comment by droyad** [comment]
A link to the doco and a bit of explanation in the message is likely all that is required.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2413 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2413 |
| 2022.1+ | _all releases_ |
