### ISSUE TITLE
Kubernetes YAML view does not remove unrecognised elements when saving and opening again

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#7033]
### Team

- [X] I've assigned a team label to this issue

### Severity

This doesn't block anyone

### Version

All versions of Octopus since 2018

### Latest Version

I could reproduce the problem in the latest version

### What happened?

When editing the Kubernetes yaml from the dialog presented when clicking the `EDIT YAML` button, any unrecognised YAML properties are still visible once the `SAVE` button is clicked and `EDIT YAML` is clicked again. This gives the impression these fields are persistent, but they are not.

### Reproduction

1. Add a `Deploy Kubernetes Containers` step
2. Fill out the step with valid options
3. Click the `EDIT YAML` button
4. Add a value not regcognised by the form
5. Click the `SAVE` button
6. Click the EDIT YAML` button again
7. The unrecognised property still exists

https://user-images.githubusercontent.com/160104/132802818-daebad7c-357a-4f2e-afa0-09a2717cf510.mp4

### Workaround

Simply ignore the unrecognised values. They will not be shown when the step is reloaded.

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent unrecognised values from persisting in the K8s EDIT YAML dialog](https://trello.com/c/Triw3PXf/150-prevent-unrecognised-values-from-persisting-in-the-k8s-edit-yaml-dialog)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2193 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2193 |
| 2022.1+ | _all releases_ |
