### ISSUE TITLE
New release package selection panel shows wrong "Last" version when collapsed

### ISSUE THREAD

**Issue by peterlanoie** [OctopusDeploy/Issues#7036]
### Team

- [X] I've assigned a team label to this issue

### Severity

minor, UI only issue

### Version

Found in Server 2021.2.7462, repro in Cloud 2.7428

### Latest Version

I could reproduce the problem in the latest version

### What happened?

In the create release page, under `Packages`, after selecting the "Last" option and collapsing the `Packages` panel, the panel summary text shows the `Latest` version instead of the `Last` version. Selecting `Latest` shows as expected and selecting a `Specific` version shows as expected.

I expect the panel summary to show the correct version.

**This does not affect actual release functionality. The correct package version is captured as expected.**

![PackageVersionSelectDisplay](https://user-images.githubusercontent.com/2675796/132908336-d5d1cc59-a277-4ae6-8e6f-d9ca8eba60f4.gif)

### Reproduction

Start with a project that references a package that has at least 1 deployed release to ensure you have a `Last` deployed version for a package.
1. `CREATE RELEASE`
2. Expand `Packages`
3. Select the `Last` radio button.
4. Collapse `Packages`
5. Confirm the collapsed panel summary displays a different version.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1337 |

**Comment by veochen-octopus** [comment]
Release Note: Package version now displays correctly on the release details page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1337 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
