### ISSUE TITLE
Add Telemetry Section in the UI

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7038]
- [ ] Contains content about our telemetry approach and transparency, linking the docs page - @ryangribble to supply content
- [x] Has the setting for opt-out of all telemetry
- [x] Displays the current health/status of the telemetry jobs, enabling any communications issues (for example corporate firewall policies) to be surfaced, so they are known and can be rectified
- [x] Shows the history of telemetry jobs so users can see when they ran, how long they took, what they sent
- [x] Allows the user to view the actual telemetry files through the web UI rather than needing to locate them on disk.  This should include “what would be sent” even when telemetry is turned off, so the screen can encourage admins to review their actual data 
- [x] Provides a function to collect/send telemetry on demand (this could be useful even for customers who have opted out, to be able to send us a quick one off “snapshot” of usage if they were having a particular support engagement where it would be useful.  Some support tickets have been observed where this does happen already, but the customers are asked to manually locate and upload the json files but even then they can't be viewed easily
- [ ] ~Include the Feature and performance telemetry in system report~

A lot of this would already be supported by a ServerTask see https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/24 (internal task)

The system report and the "What would be sent" functionality imply we should be able to generate the data outside of the task (i.e a service).

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8392 |

**Comment by ankithkonda** [comment]
Release Note: Decouple telemetry from checking for upgrades and introduce dedicated telemetry screen

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
