### ISSUE TITLE
Notification on Upgrade

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7039]
[Doc for notification (internal)](https://docs.google.com/document/d/1yKb1EsOuiBIxdAz-DDCob1BGWAM1zN5Hz_K4vm2Uvtw/edit)
[Overall Telemetry changes (internal)](https://docs.google.com/document/d/17oTRuRvnJec0YavAcXQ22pYwCgQ7xC7gPF03D8b3ByA/edit#heading=h.wijsmqwruedm)

- [ ] Notification API
- [ ] Notification UI
- [ ] `OctopusServerInstallationHistory` raises a domain event on version upgrade. 
- [ ] Handle event -> If minor or major version changes and telemetry is opted out, add a message asking to enable telemetry
- [ ] Notification of new features after first installation of this change -> consider getting this from a Octopus URL -> Talk to the marketing team

**Comment by zentron** [comment]
Closed unless it gets picked back up as a roadmap item
