### ISSUE TITLE
Octo create-release packageprerelease parameter does not match on the entire string and can result in the wrong package being chosen

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#7048]
### Team

- [X] I've assigned a team label to this issue

### Severity

1 company has reported it and is blocked

### Version

Latest tried was 2021.2.7428

### Latest Version

I could reproduce the problem in the latest version

### What happened?

Using octo CLI along with the parameter for     --packagePrerelease=VALUE, if you have 2 pre-release tags that have the same starting substring (for example -hello and -helloworld), if you choose the value "hello", and "helloworld" has a higher version, it will use that package instead of the lower version of "hello".

Documentation for the parameter says : [Optional] Pre-release for latest version of all packages to use for this release.

Detailed example.

Package library for PackageA
1.0.1-helloworld
1.0.0-hello

Run an octo create-release with parameter --packagePrerelease=hello and it will choose 1.0.1-helloworld, not 1.0.0-hello.

I would expect it to match the exact pre-release tag given.

### Reproduction

Upload packages with versions:
1.0.1-helloworld
1.0.0-hello

Run an octo create-release with parameter --packagePrerelease=hello and it will choose 1.0.1-helloworld, not 1.0.0-hello.

### More Information

First report: https://help.octopus.com/t/cli-package-prerelease-selecting-wrong-packages/27152/3

**Comment by johnsimons** [comment]
I didn't know about this myself, but the argument `--packagePrerelease=VALUE` supports regex patterns.
In this case, the solution for this is to pass `--packagePrerelease=hello$`. `$` means the end of the text and therefore does not include `helloworld`.
