### ISSUE TITLE
Deployment card overflows release line in overview page

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#7053]
### Team

- [X] I've assigned a team label to this issue

### Severity

Very low/visual

### Version

2021.3 (Build 2156)

### What happened?

Observed in Overview page

Long release names with Config As Code EAP enabled have resulted in the deployment box overflowing the Release row

![image](https://user-images.githubusercontent.com/332730/133556577-3ca93df4-d585-4311-a7f6-52e68d003d78.png)
![image](https://user-images.githubusercontent.com/332730/133556620-f11f4902-b17b-4153-996e-b632f0be7ea0.png)

It's not consistent though, some release rows do not exhibit the behaviour
![image](https://user-images.githubusercontent.com/332730/133556710-82a11501-b45a-4f71-a62b-c9d637dabbae.png)

### Reproduction

Observed on Octofront overview page

https://deploy.octopus.app/app#/Spaces-443/projects/octofront/deployments

**Comment by TomPeters** [comment]
As discussed [here](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1631789432265500), this feels like it belongs with the fire and motion team.

**Comment by cstrzadala** [comment]
Closing as looking at this as part of https://github.com/OctopusDeploy/Issues/issues/3419
