### ISSUE TITLE
Kubernetes Job resources do not include images

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#7059]
### Team

- [X] I've assigned a team label to this issue

### Severity

This is not a blocking issue

### Version

2021.3

### Latest Version

I could reproduce the problem in the latest 2021.3 build

### What happened?

When deploying a Job via the `Deploy Kubernetes containers` step, the image field is not populated, resulting in a failed deployment.

### Reproduction

1. Create a new `Deploy Kubernetes containers` step
2. Set the resource type to job
3. Add a container to the resource
4. Deploy the job, and notice the error `* spec.template.spec.containers[0].image: Required value `

### Error and Stacktrace

```shell
The Job "test" is invalid:  
* spec.template.spec.containers[0].image: Required value
```

### Workaround

Deploying the Job resource with the `Deploy Raw Kubernetes YAML` step will work as expected.

**Comment by mcasperson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [K8s job resource type missing image field.](https://trello.com/c/0g2LApPX/164-k8s-job-resource-type-missing-image-field)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2832 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.2832 |
| 2022.1+ | _all releases_ |
