### ISSUE TITLE
Polling Tentacles are unable to bypass IE Proxy on registration

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#7065]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking issue for enterprise customers

### Version

Tested on Tentacle 6.1.670 and 6.1.961

### Latest Version

I could reproduce the problem in the latest build

### What happened?

It appears that new Polling Tentacles may not be looking at the tentacle.config file for proxy settings when sending the web request to register the Polling Tentacle. Setting `Tentacle.exe proxy --proxyEnable "False"` prior to running `Tentacle.exe register-with` does not prevent the web request from using IE proxy settings. 

The Polling Tentacle wizard in Tentacle Manager reflects this behavior as well as there is no "Web Proxy" option until the Polling Tentacle is successfully created.

![image](https://user-images.githubusercontent.com/63249187/135099812-724af8de-6bb2-4dfb-b7df-0b283e63a1a5.png)

![image](https://user-images.githubusercontent.com/63249187/135100024-9afe82d9-d9a2-434f-b7fd-b225d67032dc.png)

### Reproduction

1.) Use broken proxy settings in IE
2.) Attempt to register a new Polling Tentacle to an Octopus Server with a DNS binding

### Workaround

Temporarily disable IE proxy settings

**Comment by donnybell** [comment]
Affected Customer Ticket: [Internal Link](https://octopus.zendesk.com/agent/tickets/76389)

**Comment by tothegills** [comment]
I think this is because of how we deal with the `null` proxy in OctopusClient.

**Comment by tothegills** [comment]
Internal discussion: https://octopusdeploy.slack.com/archives/C02A2SJ1ZFA/p1632887093098900
