### ISSUE TITLE
Auditing screen filters/sidebar show missing resources for deployment settings

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#7066]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low

### Version

I tried on 2021.3.4218

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Clicking on the "audit trail" link on a projects deployment settings page
![image](https://user-images.githubusercontent.com/373389/135181144-acdb65f8-db11-4994-8ba9-7cfc3ce5f832.png)

Takes you to the audit page, but  shows errors for both document types and projects

![image](https://user-images.githubusercontent.com/373389/135181207-7e99f522-01df-475c-b9dc-c47135aa4864.png)

### Reproduction

This can be seen on [this project](https://deploy.octopus.app/app#/Spaces-842/projects/releasebot/deployments/settings) which takes you to [this audit log](https://deploy.octopus.app/app#/Spaces-842/configuration/audit?projects=deploymentsettings-Projects-5150&documentTypes=deploymentsettings&from=2021-08-29T00%3A00%3A00.%2B10%3A00&to=2021-09-28T23%3A59%3A59.%2B10%3A00&includeSystem=false).

### More Information

This may be related to https://github.com/OctopusDeploy/Issues/issues/7057.

Note the modified events don't show the actual changes - I think this is covered by https://github.com/OctopusDeploy/Issues/issues/7009

### Workaround

This appears to be just UI related - the filtering works as expected.

**Comment by dylanlerch** [comment]
## Where is it broken
### 2021.1
All looks good, both of those filters are showing correctly.

### 2021.2
Half broken, error showing the specific settings resource token, but no issues showing the category.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/4549037/135209552-d1312b09-f03f-4609-bdb1-0736917e27dc.png">

### 2021.3 (master)
As you have in the screenshot above, both broken.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7648 |
| 2021.3 | 2021.3.4658 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7648 |
| 2021.3 | 2021.3.4658 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7648 |
| 2021.3 | 2021.3.4658 |
| 2022.1+ | _all releases_ |
