### ISSUE TITLE
Subscription payload properties changed from int to string

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7069]
Some properties of the subscription web hook payload have changed from their integer representation of the property value to the string representation.

For example, the `Type` property is now a string:
```
{
  "Timestamp": "<DATETIME>",
  "EventType": "SubscriptionPayload",
  "Payload": {
    "Subscription": {
      "Id": "Id",
      "Name": "Name",
      "Type": "Event"
      }
  }
}
```

**Comment by tothegills** [comment]
Release note: **Breaking change** Some subscription payload properties are now strings instead of integers

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7536 |
| 2021.3 | 2021.3.2185 |

**Comment by HgIain** [comment]
Is there a list anywhere of all the changed variables?

**Comment by HgIain** [comment]
This page still has Type as an int: https://octopus.com/docs/administration/managing-infrastructure/subscriptions/webhook-slack

**Comment by HgIain** [comment]
AFAICT the only other one to change is EmailPriority

**Comment by N-lson** [comment]
@HgIain thanks for letting us know about the outdated docs. We'll update those to reflect this change. Looks like you're correct - only those two properties have changed. We've gone ahead and updated the description of the issue along with the release notes to make it more clear what's been changed.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7536 |
| 2021.3 | 2021.3.2185 |
| 2022.1+ | _all releases_ |
