### ISSUE TITLE
"Missing Permission" UI and log warnings for CertificateView and AccountView when viewing Project Variables and Library Variable Sets

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#7076]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking

### Version

Test in 2021.1.7665 and 2021.2.2750

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a User does not have CertificateView and/or AccountView permissions, navigating to Project Variables or a Library Variable Set will generate an error message at the top of the page and warnings in the Server Logs. This should be handled more elegantly, especially in scenarios that are not specifically utilizing certificates or accounts.

Possibly related to: https://github.com/OctopusDeploy/Issues/issues/4372

Library Variable Set error message:
![image](https://user-images.githubusercontent.com/63249187/136049108-99510ee6-2ac8-4496-bf3e-cf33a3285c02.png)

Corresponding Octopus Server logs warnings:
![image](https://user-images.githubusercontent.com/63249187/136049257-0b5ac59d-b8d5-478a-af29-96f6fabc5ca6.png)

### Reproduction

1.) Create a User with the following permissions:
![image](https://user-images.githubusercontent.com/63249187/136049547-187bb20d-a117-4887-ae48-c917413a7063.png)

2.) Navigate to Project Variables or a Library Variable Set

### Workaround

The errors on screen and the warnings in the logs are safe to ignore, but could potentially generate quite a bit of noise in the logs depending on the usage scenario.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5525 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5525 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5525 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5525 |
| 2022.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5525 |
| 2022.3+ | _all releases_ |
