### ISSUE TITLE
Indexes are dissapearing

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7077]
### Team

- [X] I've assigned a team label to this issue

### Severity

Results in unusable instance

### Version

2021.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Some indexes are missing. This appears in the schema check:
```
 |     Missing item: IDX dbo.IX_EventRelatedDocument_EventId_RelatedDocumentIdPrefix NONCLUSTERED 0
                    |     Missing item: IDX dbo.IX_EventRelatedDocument_EventId_RelatedDocumentIdPrefix RelatedDocumentId
                    |     Missing item: IDX dbo.IX_EventRelatedDocument_EventId_RelatedDocumentIdPrefix RelatedDocumentIdPrefix
                    |     Missing item: IDX dbo.IX_EventRelatedDocument_RelatedDocumentIdPrefix EventId
                    |     Missing item: IDX dbo.IX_EventRelatedDocument_RelatedDocumentIdPrefix NONCLUSTERED 0
                    |     Missing item: IDX dbo.IX_EventRelatedDocument_RelatedDocumentIdPrefix RelatedDocumentId
                    |     Missing item: IDX dbo.IX_EventRelatedDocument_RelatedDocumentIdPrefix RelatedDocumentIdPrefix
```

### Reproduction

Can not reliably reproduce

### More Information

Support request: https://octopus.zendesk.com/agent/tickets/76208

**Comment by tothegills** [comment]
Adding another upgrade script as a stop-gap that will attempt to re-create the missing indexes.

**Comment by akirayamamoto** [comment]
Another customer affected: https://octopus.zendesk.com/agent/tickets/86610

> This can happen if, after upgrading the first node in the HA pair, if the second node restarted before it was upgraded, it could potentially have seen that there were additional indexes and removed them.

**Comment by benPearce1** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/10380

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7660 |
| 2021.3 | 2021.3.6093 |
| 2022.1 | 2022.1.2739 |
| 2022.2 | 2022.2.6436 |
| 2022.3 | 2022.3.1142 |
| 2022.4+ | _all releases_ |
