### ISSUE TITLE
`DeploymentHistory` duration can be incorrect

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7090]
### Team

- [X] I've assigned a team label to this issue

### Version

All

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The `DurationSeconds` column of the `DeploymentHistory` table can contain an incorrect duration. If a deployment is re-run, for example by auto-deploy, the duration will be negative.

### Reproduction

This is a guess:

- Create a deployment
- Cause the deployment to be automatically deployed
- Check the `DurationSeconds` in the `DeploymentHistory` table

### More Information

See https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1633640236036200

`ServerTask` duration is what we want. The `UpdateDeploymentHistory` does it's own calculations for duration which is incorrect.

**Comment by octokhor** [comment]
No other complaints and this has been open for awhile. Closing this now unless there is more reason to re-open this.
