### ISSUE TITLE
Converting machineroles/all from Nancy to MVC

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7096]
# The enhancement

## What is the problem this solves or benefit it gives

The `/api/machineroles/all` endpoint needs to be converted from Nancy to the new MVC pipeline to take advantage of the new mediator pattern and async entry point.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6339 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6339 |
| 2022.1+ | _all releases_ |
