### ISSUE TITLE
Server Tasks being created with QueueTime of DateTimeOffset.MinValue

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7098]
### Team

- [X] I've assigned a team label to this issue

### Severity

Cord pulled - https://octofront.com/software-products/OctopusServer/problems/SoftwareReleaseProblems-1761

### Version

2021.3.4985

### What happened?

When executing a deployment target health check from the connectivity screen, the task that is created cannot be found. Initial health check after adding a new deployment target can be found ok, just not subsequent ones executed from screen.

### Reproduction

Create a target and run a health check, then wait on the task screen for 30 seconds or so until the error message appears.

### Error and Stacktrace

```shell
Results in a task screen error message of `The resource ServerTasks-1234 was not found`
```

### More Information

[Internal slack report](https://octopusdeploy.slack.com/archives/C01HZFJRYSH/p1633933277243100?thread_ts=1633929652.242600&cid=C01HZFJRYSH)

**Comment by MarkSiedle** [comment]
Release Note: Fix for server tasks being created with QueueTime of DateTimeOffset.MinValue

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6084 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6084 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6084 |
| 2022.1+ | _all releases_ |
