### ISSUE TITLE
Blob storage warnings - The maximum key length for a clustered index is 900 bytes

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7099]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low, warning only

### Version

2021.3.2638

### Latest Version

The problem does not exist in the latest build

### What happened?

When [introducing blog storage](https://github.com/OctopusDeploy/OctopusDeploy/pull/10168), the indexes we introduced could cause an issue because the columns in the clustered index were larger than the SQL supported index size.

### Reproduction

Create a blob with large values for keys.

### Error and Stacktrace

```shell
Executing .NET Database Server script 'Script0297CreateBlobTable'
Warning! The maximum key length for a clustered index is 900 bytes. The index 'IX_Blob_BlobId' has maximum length of 1040 bytes. For some combination of large values, the insert/update operation will fail.
```
```


### More Information

_No response_

### Workaround

_No response_

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5805 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5805 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5805 |
| 2022.1+ | _all releases_ |
