### ISSUE TITLE
Revert "Tune GC settings to be more friendly to shared hosting" for performance

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7100]
# The enhancement

## What is the problem this solves or benefit it gives

There were [good reasons](https://github.com/OctopusDeploy/OctopusDeploy/pull/9934) to make this change originally; the reduced RAM usage on start up has been measurable _however_ this has also had a [measurable impact on performance](https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/43)

This leaves us stuck between a rock and a hard place. What we know is we're going to need to pay for better perf somewhere, either by allocating resources at start up, or by enabling the Workstation GC mode.

**Comment by MarkSiedle** [comment]
Release Note: Revert "Tune GC settings to be more friendly to shared hosting" for performance reasons

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4289 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4289 |
| 2022.1+ | _all releases_ |
