### ISSUE TITLE
Add stop-loss convention test for MVC controller parameters

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7102]
# The enhancement

## What is the problem this solves or benefit it gives

MVC controllers are only one of several ingress points into our API surface. This means that they **should not define their own contracts**.

Every action method should take either a command or request payload DTO so that those same command/request DTOs can be reused via non-HTTP transports. And validated. And versioned.

We want to introduce a stop-loss convention test to require that new MVC controller action methods take either a request or command DTO as the request payload.

**Comment by MarkSiedle** [comment]
Release Note: Add stop-loss convention test for MVC controller parameters

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4480 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4480 |
| 2022.1+ | _all releases_ |
