### ISSUE TITLE
Add simple performance test for creating releases and deployments, logged to TeamCity build statistics

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7103]
# The enhancement

## What is the problem this solves or benefit it gives

We made a first attempt at bolting on some performance testing ages ago in #9579 but found it genuinely prohibitive given the overall performance of Server and what we were trying to test (querying a modest-sized `Events` table).

We're continually being bitten by performance degradation which we only notice when either 1) someone manually runs a script, 2) something times out and goes 💥 or 3) a customer (rightfully) complains.

While we're desperately trying to put some stop-loss mechanisms in place for other regressions, we can't afford to let either performance or stability drop.

We want to add:

* a small `PerformanceTest` base class which acts as a simple load-testing harness for common operations.
* Some tests to cover common operations. The operations modelled by the tests are as per [this issue](https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/43) as a starting point.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5760 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5760 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5760 |
| 2022.1+ | _all releases_ |
