### ISSUE TITLE
Cherry-pick performance changes to entity tracker

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7104]
# The enhancement

## What is the problem this solves or benefit it gives

Our entity tracker had some performance changes lost in a merge forward from 2021.2 to master.

The `EntityTracker` needs to use a dictionary keyed on the document ID rather than just a list.

These performance changes were re-make on our long-running business processes branch, so we need to cherry pick them from there in order to gain an immediate performance benefit without waiting for that branch to be stabilised and merged.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4323 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4323 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.4323 |
| 2022.1+ | _all releases_ |
