### ISSUE TITLE
Visually Differentiate Teams mapped to Groups via LDAP vs AD

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#7106]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives
Groups linked to Octopus teams via AD mapping and Groups linked to Octopus Teams via LDAP mapping visually look identical.
![Team Groups](https://user-images.githubusercontent.com/5361797/137480053-5c2c8f3e-fe05-4416-8e58-b2ef2eb95594.png)

## Proposed solution
Either by modifying the icon or adding some differentiating text after the group name to differentiate the way it was mapped

## Mockup
![Team Groups 2 Flat](https://user-images.githubusercontent.com/5361797/137480187-6ec39620-fe91-4b7f-9d71-c9aae256c80a.png)

## Workarounds
There is no way to differentiate these unless you delete then re-add the group.

**Comment by octokhor** [comment]
Doesn't look like something too massive, in terms of being an issue. Closing it for now unless we have a reason to open this in the future.
