### ISSUE TITLE
Portal locks up with various SQL Server errors

### ISSUE THREAD

**Issue by adam-mccoy** [OctopusDeploy/Issues#7108]
### Team

- [X] I've assigned a team label to this issue

### Severity

Inconveniencing a couple of Cloud customers. Can be addressed with restart

### Version

2021.3.5416 and greater

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The issue identified in #7105 has the additional effect of seemingly corruption connections in the pool. With repeated requests the corruption of the pooled connections means that unrelated requests begin to fail with various SQL Server errors.

### Reproduction

See the reproduction steps in #7105. This error is encountered by repeatedly creating new releases in the child and parent projects, and viewing the release of the parent project in the portal.

### Error and Stacktrace

```shell
Several errors may occur, depending on the operating being performed. The SQL Server errors encountered include:
- The server failed to resume the transaction.
- The transaction active in this session has been committed or aborted by another session.
- The transaction operation cannot be performed because there are pending requests working on this transaction.
```

### More Information

This is caused by the same issue in #7105, and will be addressed when that issue is closed.

### Workaround

Only seen on Cloud instances. Restarting the instance addresses the problem.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6515 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6515 |
| 2022.1+ | _all releases_ |
