### ISSUE TITLE
Version rules are deleted from other channels when a channel is deleted

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7110]
### Team

- [X] I've assigned a team label to this issue

### Severity

Data loss, possible wrong deployments

### Version

2021.3.6515

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The channel rules for Octopus Server project were deleted.

See https://deploy.octopus.app/app#/Spaces-622/configuration/audit?from=2021-09-18T00%3A00%3A00.%2B10%3A00&to=2021-10-18T23%3A59%3A59.%2B10%3A00&includeSystem=false at 18 Oct 4:28pm (BNE time)

### Reproduction

1. Create 3 channels, add version rules
2. Define a deployment process with a package and scoped to those channels
3. Delete a channel
4. The channel rules are gone

The version rule may have to target an additional package.

I could reproduce this on main. [This audit log](https://main.testoctopus.app/app#/Spaces-203/configuration/audit?projects=Projects-1543&from=2021-09-18T00%3A00%3A00.%2B10%3A00&to=2021-10-18T23%3A59%3A59.%2B10%3A00&includeSystem=true&spaces=Spaces-203) is easier to read clearer.

### More Information

![image](https://user-images.githubusercontent.com/1687639/137720125-81af39bc-f41f-4a54-8a7d-fd6a3c34b69e.png)

![image](https://user-images.githubusercontent.com/1687639/137720044-4d23d293-d2de-4b91-9d9d-a49b876010d4.png)

![image](https://user-images.githubusercontent.com/1687639/137720073-92aafd00-c4e1-45fe-8674-c8f514eeb8e9.png)

**Comment by dylanlerch** [comment]
This was an issue with how we reference the action with the package reference. We now reference them by either the action name or the id, but in the cleanup job we were only looking up by the id. The version rule was being incorrectly cleaned up because the action with the package reference couldn't be found. Fixed the lookup, and this is looking good.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7705 |
| 2021.3 | 2021.3.6874 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7705 |
| 2021.3 | 2021.3.6874 |
| 2022.1+ | _all releases_ |
