### ISSUE TITLE
Unable to parse SSH service messages 

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7115]
### Team

- [X] I've assigned a team label to this issue

### Severity

Causing deployments to fail for one customer

### Version

2021.1

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Service messages from SSH targets are being split across lines, which prevents Octopus from parsing them.

### Reproduction

Difficult to reproduce. Create a lot of huge service messages.

### Error and Stacktrace

```shell
Will result in a warning like:
`Could not parse '##octopus[...`
```

### More Information

Related to: https://github.com/OctopusDeploy/Issues/issues/6731

**Comment by tothegills** [comment]
Release note: Mutli-line service message are now parsed correctly

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7856 |
| 2021.2 | 2021.2.7792 |
| 2021.3 | 2021.3.8102 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7856 |
| 2021.2 | 2021.2.7792 |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7856 |
| 2021.2 | 2021.2.7792 |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7856 |
| 2021.2 | 2021.2.7792 |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
