### ISSUE TITLE
Tentacle demands admin rights for non-admin commands

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#7117]
# The enhancement

## What is the problem this solves or benefit it gives

On Windows, we currently use an [application manifest](https://docs.microsoft.com/en-gb/windows/win32/sbscs/application-manifests?redirectedfrom=MSDN) to demand admin rights to run the `tentacle.exe` application. 
This is too broad, actively encouraging bad behavior at runtime for customers (violating the principal of least privilege) and also at dev time (running IDEs as admin etc).
This forces you to run an admin shell to even run `tentacle.exe --help`!
This also blocks potential future functionality like command line auto-complete.

![image](https://user-images.githubusercontent.com/373389/137856846-8341d24c-a192-4792-8071-58682046f45e.png)
(well, this is an unsigned binary... users would see a slightly different one because its signed)

This issue was resolved for Octopus Server under https://github.com/OctopusDeploy/Issues/issues/6721.

## Proposed solution

Instead of relying on a manifest to ask for admin rights, we should just show a message when the user is trying to do something that requires admin but doesn't have admin rights.

The commands this will impact are:
* `checkservices` (windows only)
* `service`
* `watchdog`  (windows only)

All others should work without admin rights.

## Workarounds

None, unfortunately. The application must run with admin rights.

## Links

Actual fix implemented in https://github.com/OctopusDeploy/OctopusTentacle/issues/330.
This issue is to flag where we pull it into server.

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6720 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.6720 |
| 2022.1+ | _all releases_ |
