### ISSUE TITLE
"load all" displayed unformatted in release screen

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#7121]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking, just a cosmetic issue

### Version

v2021.3 (Build 6770)

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you go to https://deploy.octopus.app/app#/Spaces-62/projects/octopus-cli/deployments/releases/3451.0.3458 you will see the following:
![image](https://user-images.githubusercontent.com/122651/138219355-f0f56984-ebb1-4ea9-b342-00cd4a350249.png)

### Reproduction

Go to https://deploy.octopus.app/app#/Spaces-62/projects/octopus-cli/deployments/releases/3451.0.3458

**Comment by TomPeters** [comment]
Duplicate: https://github.com/OctopusDeploy/Issues/issues/7474
