### ISSUE TITLE
Starting Octopus Server after 2021.2 upgrade fails with access to path denied error

### ISSUE THREAD

**Issue by andrewabest** [OctopusDeploy/Issues#7129]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking customers after upgrading to newer versions of 2021.2.*

### Version

2021.2.6114 onwards

### Latest Version

The problem does not exist in the latest build

### What happened?

When attempting to upgrade from a version of `2021.2` to a version greater than `2021.2.6114`, users may encounter the following error when Server is starting:

```
Access to the path 'C:\Program Files\Octopus Deploy\Octopus\steps\processed' is denied.
```

This should not occur.

### Reproduction

https://octopusdeploy.slack.com/archives/C27FNL3QW/p1634913262027100

### Error and Stacktrace

```shell
Access to the path 'C:\Program Files\Octopus Deploy\Octopus\steps\processed' is denied.
```

### Workaround

Increase permissions on the Octopus Server install folder for the Octopus service user, or manually create the `steps\processed` folder structure underneath the Octopus Server install folder.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7727 |
| 2021.3 | 2021.3.7091 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7727 |
| 2021.3 | 2021.3.7091 |
| 2022.1+ | _all releases_ |
