### ISSUE TITLE
Migrating api/accounts from Nancy to MVC

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7131]
The /api/accounts endpoint needs to be converted from Nancy to the new MVC pipeline to take advantage of the new mediator pattern and async entry point.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
