### ISSUE TITLE
Invalid collation pre-condition does not tell what is invalid

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7132]
### Team

- [X] I've assigned a team label to this issue

### Version

all

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the database collation pre-condition fails it just displays:
```
One or more columns in the database are not using the default collation
```
This makes it difficult to determine what failed.

### Reproduction

Change the collation for a column in the database to something other than the default.

### More Information

https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1635203934047100

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.7108 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.7108 |
| 2022.1+ | _all releases_ |
