### ISSUE TITLE
Tentacle update fails on ~30 machines out of 4500. Manual update also fails.

### ISSUE THREAD

**Issue by SergeiDubovsky** [OctopusDeploy/Issues#7135]
### Team

- [X] I've assigned a team label to this issue

### Severity

Workaround is available

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Customer have recurring trouble with Tentacle updates. Some machines fail the installation via tentcle.exe. We tried to install the MSI manually, and it failed with the following errors:

DEBUG: Error 2755:  Server returned unexpected error 1632 attempting to install package C:\temp\Octopus.Tentacle.6.1.1068-x64.msi.
DEBUG: Error 2851:  The data for the icon WixUI_Ico_Info is not valid

1632 is %temp% not accessible. We tried to add Everyone with Full access. It didn't help. 2851 is something is wrong with the icon. 

[tentacle.install2.log](https://github.com/OctopusDeploy/Issues/files/7421580/tentacle.install2.log)

AV is disabled. The server is 2012R2. A workaround is to uninstall tentacle. After the uninstall, it works with no issues.

### Reproduction

Intermittent. No exact steps to reproduce. It affects less than 1% of the customer's VM fleet.

### Error and Stacktrace

```shell
MSI (s) (F4:20) [23:46:54:869]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (F4:20) [23:46:54:869]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (F4:20) [23:46:54:869]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (F4:20) [23:46:54:869]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (54:A8) [23:46:54:869]: Note: 1: 2755 2: 1632 3: C:\temp\Octopus.Tentacle.6.1.1068-x64.msi 
DEBUG: Error 2755:  Server returned unexpected error 1632 attempting to install package C:\temp\Octopus.Tentacle.6.1.1068-x64.msi.
DEBUG: Error 2851:  The data for the icon WixUI_Ico_Info is not valid
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2851. The arguments are: WixUI_Ico_Info, ,
```

### More Information

https://octopus.zendesk.com/agent/tickets/78191

### Workaround

Uninstall the Tentacle. Install a new MSI manually.

**Comment by N-lson** [comment]
Closing as no other customers have reported this issue.
