### ISSUE TITLE
ServerTask query returns all rows in the table

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7139]
### Team

- [X] I've assigned a team label to this issue

### Version

Latest in cloud

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Looking at [Seq](https://seq.octopushq.com/#/events?filter=InstanceId%20%3D%20'i009472'%20and%20Reef%20%3D%20'hwestus2p00105'), it appears that the query here is taking 10 seconds to complete:
```
SELECT * FROM [dbo].[ServerTask] WHERE (((([SpaceId] is null OR [SpaceId] in ('Spaces-1', 'Spaces-102', 'Spaces-122', 'Spaces-142', 'Spaces-162', 'Spaces-182', 'Spaces-202', 'Spaces-22', 'Spaces-222', 'Spaces-242', 'Spaces-3', 'Spaces-42', 'Spaces-62'))))) AND ([BusinessProcessState] <> @businessprocessstate) ORDER BY [LastModified]
```

I upgraded my local instance and all ServerTasks have the state of `InProgress` so it will be pulling back the whole table every 10 seconds (100,000+ rows).

### Reproduction

See slack thread for details on the customer's cloud instance

### More Information

https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1635501176085300

**Comment by droyad** [comment]
[This](https://github.com/OctopusDeploy/OctopusDeploy/blob/ef7bf1080236fca38551e0c6477720b2d6fe519d/source/Octopus.Core/Infrastructure/BusinessProcesses/BusinessProcessAnimator.cs#L40) is the culprit query

**Comment by uglybugger** [comment]
Sigh. The `BusinessProcessAnimator` has a query which looks like this:

```
var entity = await documentStore.Query()
    .Where(x => x.BusinessProcessState != BusinessProcessState.Completed)
    .OrderBy(x => x.LastModified)
    .FirstOrDefaultAsync(cancellationToken);
```

That's entirely reasonable - until we discover that the `.FirstOrDefaultAsync(...)` method is a facade which materialises the entire recordset. I've changed the facade in 3cfcc3da3a1f41528432a514dec186d3ef8cb7ed to use a method which Nevermore actually supports and will map to a `SELECT TOP n` SQL expression.

**Comment by droyad** [comment]
I saw a long running query with `Unknown` coming up in the Crow's Nest data. From the number of invocations I thought it was number of queries, but probably not:

![image](https://user-images.githubusercontent.com/1687639/139631038-2d984ae4-2f40-407e-8c66-1a02057acddf.png)

If we name it we get an earlier warning in the data.

**Comment by emilol** [comment]
Fixed in https://github.com/OctopusDeploy/OctopusDeploy/pull/10581

**Comment by emilol** [comment]
Release Note: Fixed a performance issue where querying a large number of ServerTasks was taking a long time.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.7616 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
