### ISSUE TITLE
Adjustable session timeouts and invalidation

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#7142]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this ~in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future~ with several key product team members and with Principal Engineers
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

At the moment session timeouts in Octopus Deploy Server are fixed and do not give our customers security teams the ability to adjust them according to their own internal security policies. This is a problem because we're effectively assuming their threat model on their behalf, rather than allowing them to express their threat model in our configuration settings.

Additionally, security teams cannot easily invalidate sessions a user currently has access to, ensuring that a given user cannot interact with the system at all, particularly for the following scenarios:

- Employee reports suspected malicious activity on their account
- Known malicious activity is identified
- Employee offboard/role change

## Proposed solution

- Session information/tokens to be checked server side such that near-immediate session invalidation is possible by an Administrator of the system. Ideally several users could have their sessions invalidated at once.
- Any relevant session timeouts be configurable to enforce a re-authentication to occur, and this should be configurable by an Administrator for all users in an instance. Typically these timeouts would allow configuration in terms of minutes, hours or days.

## Workarounds

At the moment customers can remove a user from the Users list, or change their permissions within the application to restrict what data the API can interact with.

## Internal Links
[One of several issues raised by customers here](https://octopusdeploy.slack.com/archives/CB2QY9CTD/p1622208721008100)

**Comment by geeeyetee** [comment]
> Release Note: Active Directory integrated authentication cookie timeout has been increased from 20min to 20days
> _Originally posted by @octoreleasebot in https://github.com/OctopusDeploy/Issues/issues/3987#issuecomment-347406646_

I am dumbfounded to learn this. Please make configurable ASAP. I see Octopus took note of customers requesting this more than 6.5 years and 5.5 _thousand_ issues ago: https://github.com/OctopusDeploy/Issues/issues/1526

**Comment by ankithkonda** [comment]
Configurable session timeouts and session invalidation features work has been completed. please see the following issues for release notes and versions.

Configurable user session timeouts #7305
Ability to invalidate user sessions #7306
