### ISSUE TITLE
Deployment Targets not upgrading when tasks are running in queue (high volume) after SQL timeout

### ISSUE THREAD

**Issue by laurencagneyoctopus** [OctopusDeploy/Issues#7146]
### Team

- [X] I've assigned a team label to this issue

### Severity

Affecting 1 customer

### Version

Upgraded to 2021.2.7650

### Latest Version

I could not reproduce the problem

### What happened?

When attempting to upgrade deployment targets after a recommended upgrade prompt ("Upgrade Tentacle on X Deployment Targets" ellipse in Environments) the on-prem server returned the following error and did not upgrade the selected targets:
 
'Error while executing SQL command in transaction 'UpgradeTaskController|ServerTasks-GUID|T1000': Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 
The SQL command being executed can be viewed in [internal ticket](https://octopus.zendesk.com/agent/tickets/78203).

Workers were unaffected by this and have upgraded successfully. 

The customer has since been able to perform successful rolling upgrades of the deployment targets however only when there are no tasks running on the server.
 
Actual execution plan has been captured and attached to the above internal ticket. Results show a missing index - a request to create the index has been offered to the customer.

### Reproduction

Customer is running HA setup with multiple nodes and highly volume of tentacles. Unable to repro.

### Error and Stacktrace

```shell
Activity failed with error 'Error while executing SQL command in transaction 'UpgradeTaskController|ServerTasks-INSERTGUID|T1000': Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding
```

### More Information

[Internal discussion](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1635731096106400)
[Internal ticket](https://octopus.zendesk.com/agent/tickets/78203)

**Comment by octokhor** [comment]
Closing this ticket - looks like it was affecting only one customer. We are also rolling out some Tentacle upgrade improvements that will hopefully help with the timeouts by slimming down the Tentacle package size and allowing users to increase the number of parallel tentacle upgrades they can run at the same time.

If this problem persists, happy to reopen it again in the future. Thanks
