### ISSUE TITLE
Can't add/edit Azure account variables

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/Issues#7152]
### Team

- [X] I've assigned a team label to this issue

### Severity

Many customers: blocks adding/editing  Azure account variables

### Version

Seen on 2021.3.7919

### What happened?

When adding a new variable of type `AzureAccount`, the dropdown list of Azure accounts in the space isn't shown

![image](https://user-images.githubusercontent.com/2888279/140680585-45b3fbcd-f24c-41a1-aa93-5f35d68f82a3.png)

Similar thing for editing existing variables

### Reproduction

Open the editor for the `AzureAccount` variable
https://deploy.octopus.app/app#/Spaces-142/library/variables/LibraryVariableSets-1082

AWS account seems to be working still - `AwsAccount` variable here:
https://deploy.octopus.app/app#/Spaces-622/projects/octopus-server/variables

**Comment by mjhilton** [comment]
This looks to be a problem with the way the Account Editor is trying to retrieve the Azure Accounts from Server. It makes a request of this format:

`/api/Spaces-1/accounts?accountType=AzureServicePrincipal,AzureSubscription`

This doesn't line up with the way Server is expecting multiple values to be passed in that `accountType` parameter.

Instead, the correct request would need to be:
`/api/Spaces-1/accounts?accountType=AzureSubscription&accountType=AzureServicePrincipal`

Digging in to see what's changed lately in this space... Can't see anything obvious in the front-end, so perhaps it's something to do with the API Controller changes (Nancy -> ASP.NET) going on at the moment.

**Comment by mjhilton** [comment]
This seems to have been accidentally caused in https://github.com/OctopusDeploy/OctopusDeploy/pull/10559 when we migrated from Nancy to ASP.NET for the AccountsController.

It seems that the way you pass multiple values to a querystring parameter has changed. Azure is the only account type which has multiple underlying types (`AzureServicePrincipal` vs `AzureSubscription`), which is why the others still work.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8030 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
