### ISSUE TITLE
A Crontab containing Fri can't be parsed in the `tr-TR` locale

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7155]
### Team

- [X] I've assigned a team label to this issue

### Severity

Workaround available

### Version

All that have crontab

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a crontab contains `Fri`, the [NCrontab.Advanced](https://github.com/jcoutch/NCrontab-Advanced) library calls `ToUpperCase()` on it. This results in `FRİ` ([more info](http://haacked.com/archive/2012/07/05/turkish-i-problem-and-why-you-should-care.aspx/))

### Reproduction

Done using a unit test

### Workaround

Use `FRI` or the digit number of the week.

**Comment by droyad** [comment]
Problem code is [here](https://github.com/jcoutch/NCrontab-Advanced/blob/master/NCrontab.Advanced/CrontabSchedule.cs#L285)

**Comment by droyad** [comment]
Raised a PR https://github.com/jcoutch/NCrontab-Advanced/pull/26

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8925 |

**Comment by droyad** [comment]
Release Note: Crontabs can now be correctly parsed in the `tr-TR` locale

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8925 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8925 |
| 2022.1+ | _all releases_ |
