### ISSUE TITLE
disallow updating to point at empty repo, with an informative message

### ISSUE THREAD

**Issue by LeeMeyer** [OctopusDeploy/Issues#7160]
Currently if we have already converted a project to version control we get the error `A document must have an identifier before it can be tracked. (Parameter 'Id')` 

It's quite unclear to anyone outside of the config is code team what this actually means, but it boils down to that if a repository is empty and we try to point a config as code project at it, we will expect valid OCL and error out if we do not find it. It's legitimate to point at a repository that contains OCL, but if it's empty the likely fix is that we display a human-readable error message that explains we couldn't find valid OCL in the provided repository, and to either update the repository with valid OCL or point at a repository that contains valid OCL.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9150 |

**Comment by StephenHeise** [comment]
Release Note: Improve the error message when the deployment settings file can not be found in the Git repo.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9150 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9150 |
| 2022.1+ | _all releases_ |
