### ISSUE TITLE
Variable preview page does not show all options scoped to role.

### ISSUE THREAD

**Issue by brentkinney** [OctopusDeploy/Issues#7165]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.2.7727

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When viewing the variable preview page, only one value appears for a variable entry even though there are multiple items scoped for that step/environment.

Variable Preview page showing one value for IIS Port:
![image](https://user-images.githubusercontent.com/48770271/141582605-72ce342e-3a7d-40f9-b61e-8a542b88b66d.png)

Variable page showing that two values are scoped for that variable:
![image](https://user-images.githubusercontent.com/48770271/141583412-3e9eef70-3cfa-429b-b695-dcc2bd20cf09.png)

### Reproduction

Create a variable and scope a value, then create a new value and set the same scope.  View the preview page and see only one of the scoped values even though there are two.

**Comment by matt-richardson** [comment]
This is by design, @brentkinney. There can [only be one value for a given variable scope](https://octopus.com/docs/projects/variables#Scopingvariables-Scopespecificity):

> If two variables are scoped equally, Octopus will choose project-defined variables ahead of library-defined ones. If this still does not resolve the conflict the result is non-deterministic and you should not depend on a specific value being used. Instead, you should take care when scoping variables so that they are unlikely to conflict.

**Comment by brentkinney** [comment]
Hey @matt-richardson, Thanks for the clarification!
