### ISSUE TITLE
IDs Query Parameter Ignored for Worker Pools API Endpoint

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/Issues#7166]
### Team

- [X] I've assigned a team label to this issue

### Severity

Breaking Expectations for Integration Queries

### Version

Earliest tried was 2021.3.8117

### What happened?

The endpoint, `/api/workerpools` allows you to specify an `ids` query parameter to filter worker pools based on their ID value.

Currently, the endpoint does not honour the `ids` query as part of the response (result set) if specified in the request.

For example, if you make an HTTP request to `/api/workerpools?ids=WorkerPools-321`, you would expect a response with all worker pools that have an ID value equal to the value, `WorkerPools-321`. That's not what happens. Instead, the response includes *all* worker pools, effectively ignoring this query parameter.

### Reproduction

1. Create two distinct worker pools in Octopus Deploy. Make a note of each worker pool's ID (i.e. WorkerPools-123 and WorkerPools-321).
2. Execute a query to the endpoint, `/api/workerpools?ids=WorkerPools-123`.
3. Notice that the response does not filter out any worker pools.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9687 |

**Comment by tothegills** [comment]
Release note: The `/api/workerpools` filters by the specified `ids` query parameter once more

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9687 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9687 |
| 2022.1+ | _all releases_ |
