### ISSUE TITLE
Typeahead fields remove leading and trailing spaces

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7176]
### Team

- [X] I've assigned a team label to this issue

### Severity

Annoyance

### Version

2021.2.7808

### Latest Version

Not applicable

### What happened?

When selecting an environment via a variable set, if I type ‘AWS – ‘ it auto removes the last space when searching for the environment.

### Reproduction

![2021-11-17_15-50-16 (1)](https://user-images.githubusercontent.com/1687639/143987079-13230640-04e8-4099-a27e-578abaa87258.gif)

**Comment by droyad** [comment]
This affects all type ahead combos. The type ahead 

[This is the line](https://github.com/OctopusDeploy/OctopusDeploy/blob/4bbf69120b3fba336f09548a443323146a8721fc/newportal/app/components/MultiSelect/MultiSelect.tsx#L341) that removes the spaces I think. I'm not 100% sure why it doesn't do it if you type slowly, likely because it doesn't consider whitespace to be a change in of itself.

The typeahead also does not take leading/trailing spaces into account when filtering:
![image](https://user-images.githubusercontent.com/1687639/143989058-b96d86ac-6d48-4ac0-a87a-a523aae5e74e.png)

**Comment by TomPeters** [comment]
Release Note: Fixed a bug where whitespace input characters could be trimmed when typing into a MultiSelect

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.11006 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.11006 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.11006 |
| 2022.1+ | _all releases_ |
