### ISSUE TITLE
Octopus Client not working with Server

### ISSUE THREAD

**Issue by desruc** [OctopusDeploy/Issues#7190]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3

### Latest Version

I could not reproduce the problem

### What happened?

A new permission - `TelemetryView` - was added to both Octopus Server and Octopus Client as part of the recent telemetry work done by Team Fire and Motion.

The permission was added to Server in `2021.3.7491` and added to Client in `11.3.3453`.

This is a breaking change as both Server and Client need the permission to work with each other.

### Reproduction

N/A

### Error and Stacktrace

```shell
Error converting value "TelemetryView" to type 'Octopus.Client.Model.Permission'
```

### Workaround

Octopus Server `2021.3.7491` and above must use Octopus Client `11.3.3453` (or above)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.7491 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by OscarChavarriam** [comment]
2021.3.7491

**Comment by OscarChavarriam** [comment]
2021.3.7491- Apache Community Facebook page
https://www.facebook.com/ApacheSoftwareFoundation

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
