### ISSUE TITLE
Loading variablesets takes a long time

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7195]
We have a user reporting a performance issue after upgrading from 2021.1.x to 2021.2.7650 and they seem to have narrowed it down to their `/api/Spaces-1/variables/variableset-Projects-XXXXX` endpoint. They say it's most noticeable when they're trying to load the Variables page and saving changes to variables for a project. They've included a screenshot of their browser network tab (looks like it's taking up to 43s in one test), and there's a dotTrace referenced in the ticket here. Any ideas on what might be causing this or what we can have them try?

## Links
Support ticket: https://octopus.zendesk.com/agent/tickets/78873
Trace: https://aetna.box.com/s/rzvvx6lbosgju386r4n8wgai5jsbux9h
Thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1636491536232800

**Comment by MarkSiedle** [comment]
Release Note: Speeding up variables API fetching

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7840 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7840 |
| 2021.3 | 2021.3.8815 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7840 |
| 2021.3 | 2021.3.8815 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7840 |
| 2021.3 | 2021.3.8815 |
| 2022.1+ | _all releases_ |
