### ISSUE TITLE
`No git resource` when last selected branch was deleted

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7196]
### Team

- [X] I've assigned a team label to this issue

### Version

Earliest tried was 2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the last selected branch is deleted, some project pages show the following error:
![Screen Shot 2021-11-24 at 5 06 10 pm](https://user-images.githubusercontent.com/25342760/143190953-726a9254-66d8-4d1e-a273-0dcab5f1301f.png)

### Reproduction

1. Create a version controlled project
2. Create a new branch, and select that branch in the Octopus UI (via the Deployment Process or Deployment Settings page)
3. Delete the newly created branch
4. May need to wait for the git cache to invalidate (~30 seconds)
5. Switch to a page that doesn't have a branch selector (E.g: Channels, Triggers)

### Workaround

Switching to the Deployment Process or Deployment Settings pages should reset the selected branch to the default branch.

**Comment by YuKitsune** [comment]
Release note: Fixed an issue where some Project pages without a branch selector would show a "No git resource" error if the last selected branch was deleted.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9351 |
| 2022.1+ | _all releases_ |
