### ISSUE TITLE
SumoLogic log sink causes performance degredation in high-use scenarios

### ISSUE THREAD

**Issue by skermajo** [OctopusDeploy/Issues#7199]
Customers found that, when under load, performance degraded when piping logs to SumoLogic. By default, the SumoLogic log sink does not buffer.

Buffering the SumoLogic output removes the performance penalty.

**Comment by skermajo** [comment]
Release note: SumoLogic Serilog sink now buffers to improve performance.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8740 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8740 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8740 |
| 2022.1+ | _all releases_ |
