### ISSUE TITLE
Auto-created space manager team for given space was not found

### ISSUE THREAD

**Issue by paulegradie** [OctopusDeploy/Issues#7202]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking external and internal customers. Several internal reports of builds failing and at least 1 or 2 external customers blocked from server upgrades.

### Version

2021.2.7462

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When creating a new space, if one attempts to retrieve the space details shortly after creating the space, then the server returns a 404 not found error. I expect that when I create a space, I should be able to immediately retrieve that space without a 404 no found on entities that are related to that space (in the case the space manager team).

### Reproduction

Reproducing this can be tricky depending on your system (slower systems reproduce it more easily in situ). 

To achieve a repro, you must make a call to retrieve all spaces (or the space that is in progress of being created...) while the space is still being create. This can be done programmatically by smashing server with parallel requests to both create spaces and retrieve all spaces.

### Workaround

There current workaround for this issue to delay calls to fetch all spaces after creating a new space (by a few seconds typically). If these calls are made programmatically (e.g. via the octopus cli), then it may appear random without a suitable workaround.

**Comment by paulegradie** [comment]
Release Note: Fix issue with auto-created space manager team not found when creating / retrieving space

**Comment by paulegradie** [comment]
Release Note: Fix issue with auto-created space manager team not found when creating / retrieving space

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7855 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7855 |
| 2021.3 | 2021.3.8899 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7855 |
| 2021.3 | 2021.3.8899 |
| 2022.1+ | _all releases_ |

**Comment by psychonic** [comment]
We are still seeing this issue on 2021.2.7924

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7855 |
| 2021.3 | 2021.3.8899 |
| 2022.1+ | _all releases_ |
