### ISSUE TITLE
Loading Projects can be Slow

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7204]
### Team

- [X] I've assigned a team label to this issue

### Severity

At least one customer is affected by this issue

### Version

2021.2.7462

### Latest Version

I could reproduce the problem in the latest build

### What happened?

For databases with a large number of projects (thousands), hitting project endpoints such as "api/Spaces-1/projects?take=10" would take far too long (> 10 seconds).

### Reproduction

With a database with thousands of projects, hit the "api/Spaces-1/projects?take=10" endpoint

**Comment by sburmanoctopus** [comment]
Release Note: Speeding up project fetching when requesting an individual project, or taking a set number.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7897 |
| 2021.3 | 2021.3.9302 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7897 |
| 2021.3 | 2021.3.9302 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7897 |
| 2021.3 | 2021.3.9302 |
| 2022.1+ | _all releases_ |
