### ISSUE TITLE
Message bus pruning of stale events is too slow

### ISSUE THREAD

**Issue by uglybugger** [OctopusDeploy/Issues#7207]
### Team

- [X] I've assigned a team label to this issue

### Severity

This is causing a customer instance's database to grow unreasonably large and quite rapidly. Other customers may soon be affected.

### Version

2021.3+

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The background task which is responsible for removing stale events from the `MessageBusEvents` table was initially not scheduled correctly. This led to the task's only being run infrequently, with the result being that stale events would not be pruned from the table. While this causes no logical errors, it does chew up (sometimes significant) database storage space.

In the case where customers have a large number of transient nodes and thus create many orphaned cursors, the events would potentially stick around for up to a week. If a customer were to have either high throughput or events with larger payload sizes, this would result in unreasonable expansion of database disk space usage.

### Reproduction

1. Run Octopus Server.  (This will create a set of message bus cursors.)
2. Stop Octopus Server. (This will leave those cursors in the database to be cleaned up asynchronously.)
3. Run Octopus server again using a different hostname or machine name. (This will create additional message bus cursors.)

 Observe that Octopus does not clean up the messages until all of the stale cursors are gone, and it does not properly clean up all of the stale cursors unless restarted again.

### Workaround

Run the below queries. They are the normal queries that the background task will execute, and are safe to run repeatedly to delete stale cursors and messages in batches.

```sql
DELETE
FROM MessageBusCursor
WHERE LastModified < DATEADD(hour, -1, GETDATE())

DELETE TOP (100)
FROM MessageBusEvent
WHERE SequenceNumber < (SELECT MIN(SequenceNumber) FROM MessageBusCursor);
```

**Comment by MarkSiedle** [comment]
Release Note: Fix issue with message bus events not being deleted, leading to slow queries

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8805 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8805 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8805 |
| 2022.1+ | _all releases_ |
