### ISSUE TITLE
Cannot select channel grouping filter

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#7221]
### Team

- [X] I've assigned a team label to this issue

### Version

v2021.3 (Build 8929)

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When you go to https://deploy.octopus.app/app#/Spaces-142/projects/dw-infrastructure/deployments
I cannot select this filter on this screen
![image](https://user-images.githubusercontent.com/122651/144143963-bb05fbcf-346e-47f1-8d27-5e879c6fd8dd.png)

### Reproduction

go to https://deploy.octopus.app/app#/Spaces-142/projects/dw-infrastructure/deployments

### More Information

I am using Safari Version 15.1 (17612.2.9.1.20)

**Comment by N-lson** [comment]
Reproduction:

1. Create a channel in a project (so that there are 2 including the default)
2. Create a release in the default channel
3. Create a release in the new channel
4. Try to change the grouping options

![ChannelGroupBug](https://user-images.githubusercontent.com/11970672/144536585-5431e71b-154d-4779-96d2-36b9905c91d0.gif)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10526 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10526 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10526 |
| 2022.1+ | _all releases_ |
