### ISSUE TITLE
Updating step template usage fails if the usage is part of a channel's version rules

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7224]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking a customer

### Version

Earliest tested on 2021.2.7808

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you try to update the usage of a step template to the latest version the result should be a successful update or a popup which highlights any breaking changes caused by the update. However this error is shown instead:
![image](https://user-images.githubusercontent.com/11970672/144169288-68c42f85-7283-4d5d-95a5-d7dbc73a2534.png)

### Reproduction

1. Add a package to the built-in feed
2. Create a custom step template `Library -> Step Templates` based off the `Deploy a Package` step and select the package from step 1
3. Create a project
4. Add the custom step to the deployment process
5. In `Channels` select the default channel and add a version rule. Select the custom step and set the version range to `(0,1)`
6. Go back to the custom step template and edit the name
7. Go to `Usage` and try to update the newly added usage. The error should occur.

### Error and Stacktrace

```shell
Value cannot be null. (Parameter 'key')
```

### Workaround

Remove the step from the channel version rules and re-add the step after updating the usage.

**Comment by tothegills** [comment]
Doesn't appear that the channel rule check causing the issue is doing anything - the packages are removed from the channel rule rather than the update vetoed.

**Comment by N-lson** [comment]
Release Note: Updating a step template usage which is used in a channel's versioning rules will no longer result in an error

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7870 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7870 |
| 2021.3 | 2021.3.9124 |

**Comment by FelixBrunet** [comment]
> 2021.3.9124

When this release will be available?

**Comment by N-lson** [comment]
Hi @FelixBrunet, thanks for the question. Unfortunately we can't predict when a release with this change will be available. We've picked up several other issues during internal testing of releases >=2021.3.9124, and as such we've had to delay a new release to general availability. As a rough estimate, a release including this change should be available sometime by late January/February.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7870 |
| 2021.3 | 2021.3.9124 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7870 |
| 2021.3 | 2021.3.9124 |
| 2022.1+ | _all releases_ |
