### ISSUE TITLE
Dashboard Does Not Display Correct Releases

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7227]
### Team

- [X] I've assigned a team label to this issue

### Severity

Releases that shouldn't get deleted might get deleted

### Version

2021.2.7808

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The dashboard does not display the latest release for certain environments. This makes sense when "Discrete Channel Releases" is not turned on in the project settings, however when it is turned on every channel should show it's latest release regardless of how many releases have been deployed in another channel.

The release `0.0.3` should be displayed in the dashboard for the `Testing` environment, however it doesn't show up.

![image](https://user-images.githubusercontent.com/11970672/144328092-63470a58-b6ed-4cd8-b2ef-c3a684117006.png)

![image](https://user-images.githubusercontent.com/11970672/144328132-39215623-c4bd-4e30-993f-73dfaf67bbc4.png)

### Reproduction

https://octopus-operations.octopus.app/app#/Spaces-142/projects/channel-phase-deletion-test/deployments

1. Create 3 environments (will refer to these as Dev, Test, Prod)
2. Create a project with a lifecycle which retains all releases and includes all 3 environments
3. Add a simple run a script step
4. Add a channel `Ch2` so that there are 2 channels in the project
5. Create release `0.0.1` in `Ch2` -> Deploy this to all 3 environments going from Dev then Test then Prod
6. Create release `0.0.2` in `Ch2` -> Deploy this to Dev then Test
7. Create release `0.0.3`, `0.0.4`, `0.0.5` in `Ch2` -> Deploy this to Dev
8. Create release `0.0.6`, `0.0.7` in `Default` -> Deploy this to Dev and Test
9. 🪄 `0.0.2` is gone from the dashboard

Simpler reproduction can also be done by skipping step 5 - the release in step 6 will still be removed from the dashboard.

Even simpler reproduction:

1. Create release 0.0.1, 0.0.2, 0.0.3, 0.0.4 in Ch1
2. Create release 0.0.5, 0.0.6 in Ch2
3. Deploy 0.0.1, 0.0.5, 0.0.6
4. Look at the dashboard - 0.0.1 won't be there

### More Information

https://octopus.zendesk.com/agent/tickets/80068
https://github.com/OctopusDeploy/Issues/issues/6950
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1638330077004400

**Comment by N-lson** [comment]
Release Note: Display correct latest release for each channel when "Discrete channel releases" is enabled

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10322 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10322 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10322 |
| 2022.1+ | _all releases_ |
