### ISSUE TITLE
Teams/All endpoint can be slow

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7231]
### Team

- [X] I've assigned a team label to this issue

### Severity

At least one customer is finding this painful

### Version

2021.2

### Latest Version

Not applicable

### What happened?

Loading teams when editing the 'manual intervention' step caused the teams/all endpoint to be hit. This was taking too long to return.

### Reproduction

- Have lots of teams in the database
- Edit a manual intervention step
- Notice the endpoint take a long time to finish loading

**Comment by sburmanoctopus** [comment]
Release Note: Speeding up teams API fetching

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7879 |
| 2021.3 | 2021.3.9302 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7879 |
| 2021.3 | 2021.3.9302 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7879 |
| 2021.3 | 2021.3.9302 |
| 2022.1+ | _all releases_ |
