### ISSUE TITLE
Manual Interventions time out after 30 minutes on Azure

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7235]
### Team

- [X] I've assigned a team label to this issue

### Severity

At least one customer is affected by this

### Version

2021.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Azure would kill the inactive transaction after 30 minutes. But this would cause finishing the manual intervention to fail

### Reproduction

- Create script to run on worker
- Create child step of a manual intervention
- Create a release and deploy
- Wait 30 minutes (or manually kill the transaction)
- Try to finish the manual intervention

**Comment by sburmanoctopus** [comment]
Release Note: Fixing timeout from manual interventions after 30 minutes on Azure

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7897 |
| 2021.3 | 2021.3.9302 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7897 |
| 2021.3 | 2021.3.9302 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7897 |
| 2021.3 | 2021.3.9302 |
| 2022.1+ | _all releases_ |
