### ISSUE TITLE
Teams show up as 'Missing Resource' when loading all teams in manual intervention step

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7236]
### Team

- [X] I've assigned a team label to this issue

### Severity

Looks weird

### Version

2021.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

In a manual intervention step all teams are loaded. If there are a lot of teams in the space then the chips which should display each team's name will display 'Missing Resource':
![image](https://user-images.githubusercontent.com/11970672/144785121-2a52458a-a46d-4adb-8554-e02bde2c3c93.png)

This is because the step is loaded but the API call to retrieve all the teams is still being processed. During this time there is no team data to match the deployment process' data against, so it displays as missing until the data is loaded.

### Reproduction

1. Add a manual intervention step with a team to a project
2. Either have lots of teams or set a breakpoint in server `GetAllTeamsController`
3. Reload the step

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | 2021.3.9411 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | 2021.3.9411 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | 2021.3.9411 |
| 2022.1+ | _all releases_ |
