### ISSUE TITLE
Progression endpoint is slow

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7237]
### Team

- [X] I've assigned a team label to this issue

### Severity

Affects at least one customer

### Version

2021.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The progression endpoint is about 2-3 seconds slow for large databases. This makes the project overview loading slow.

### Reproduction

Load the project overview with a large database

**Comment by sburmanoctopus** [comment]
Release Note: Speeding up progression endpoint

**Comment by sburmanoctopus** [comment]
https://github.com/OctopusDeploy/OctopusDeploy/pull/10880

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | 2021.3.9411 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | 2021.3.9411 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7899 |
| 2021.3 | 2021.3.9411 |
| 2022.1+ | _all releases_ |
