### ISSUE TITLE
Revert disable of default branch in Config as Code settings.

### ISSUE THREAD

**Issue by StephenHeise** [OctopusDeploy/Issues#7240]
# Background

Changing the default branch was removed due to it causing issues. Those issues have been resolved, so default branch changing can be re-enabled. See ticket for further details.

# Known Issues

- Changing to a branch without config will cause an error.

**Comment by StephenHeise** [comment]
Release Notes: Enables changing the default branch in Config as Code settings.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
