### ISSUE TITLE
Service Message Parsing (This time for sure)

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7244]
The issue described in https://github.com/OctopusDeploy/Issues/issues/7115 is still happening.

**Comment by zentron** [comment]
https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/82

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7911 |
| 2021.3 | 2021.3.9485 |
| 2022.1+ | _all releases_ |
