### ISSUE TITLE
Cloning steps can take a long time when there are many projects

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7246]
### Team

- [X] I've assigned a team label to this issue

### Severity

Annoying for large customers

### Version

Forever

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A customer has reported that cloning deployment process steps takes a long time. They have thousands of projects.

### Reproduction

Create thousands of projects
Try to clone a step in a deployment process

### More Information

The reason cloning a step is so slow is because it has to load all the projects using the projects/all endpoint.
That customer has > 6700 projects, and that endpoint loads everything for that project (deployment processes etc. etc.).
It looks like it only needs the list of project names (and maybe ids) for a droplist. So most of this data is fetched for no reason.
Would it be possible to use the much much quicker "projects/experimental/summaries" endpoint instead?
We also noticed that "projects/experimental/summaries" has a set of links. We can make it even faster if we don't need those. Do we need them?

Internal support ticket: https://octopus.zendesk.com/agent/tickets/78873
Slack discussion: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1638843701074900

**Comment by tothegills** [comment]
Let's review everywhere we use projects/all

**Comment by N-lson** [comment]
Release Note: Speed up cloning a step, filtering tenants and testing permissions by retrieving project summaries instead of full details

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8001 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8001 |
| 2021.3 | 2021.3.10845 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8001 |
| 2021.3 | 2021.3.10845 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8001 |
| 2021.3 | 2021.3.10845 |
| 2022.1+ | _all releases_ |
