### ISSUE TITLE
Expand Octopus Tentacle Docker Image to Include Tenant options

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7251]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not Blocking

### Version

Latest Tentacle Docker Image

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The Tentacle Docker Image doesn't allow for configuring a Tentacle with the Tenant/TenantTags options available via the register-with command. 

https://hub.docker.com/r/octopusdeploy/tentacle 

### Reproduction

N/A

### Error and Stacktrace

```shell
N/A
```

### More Information

Current Image Environment Vars:
https://octopus.com/docs/installation/octopus-tentacle-container#environment-variables 

register-with command:
https://octopus.com/docs/octopus-rest-api/tentacle.exe-command-line/register-with

### Workaround

Use the CLI to add tentacles with Tenant/Tenant Tags via the register-with command

**Comment by N-lson** [comment]
Release Note: Add Tenant environment variable options for running Tentacle in a Docker container
