### ISSUE TITLE
The resource '#{Deployment.PackageFeed}' was not found error appears when editing a projects variables when cloning a project with Automatic Release Creation Enabled.

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7252]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking a handful of users from deploying cloned projects where ARC was enabled on the original project.

### Version

2019.8.6 - 2019.12.1 LTS

### Latest Version

Cant Reproduce in version 2021.2.7808

### What happened?

When cloning a project with Automatic Release Creation enabled which has variables attached to the project the user is unable to edit the project variables and is faced with the error message 'The resource '#{Deployment.PackageFeed}' was not found' when trying to save the edited variable. 

### Reproduction

- Clone a project with ARC enabled which has project variables attached to the project.
- Try and edit the cloned projects variables. 
- When saving the project variables Octopus throws an error `'The resource '#{Deployment.PackageFeed}' was not found'`.

When looking inside the Octopus Instance UI it shows Automatic Release creation is not enabled, however when looking at the project json AutoCreateRelease is set to 'true' - 

![image](https://user-images.githubusercontent.com/92790462/145377591-a4e704d5-7bc4-4585-a610-620b30b1cffa.png)

### More Information

Tickets - 

https://octopus.zendesk.com/agent/tickets/79705
https://octopus.zendesk.com/agent/tickets/4516

### Workaround

- Set up a temporary package step within the affected project, using a package from a built-in package repository.
- Go back into 'Triggers' for the project and it should then give you the option to disable ARC.
- Test editing your variables and the error should not appear again. 
- You can then delete the temporary package step.

**Comment by geofflamrock** [comment]
Thanks for reporting this @Clare-Octopus, we're going to redirect over to Team Fire and Motion, as it falls within their area of ownership.

**Comment by N-lson** [comment]
Closing this one as it's outside of our supported versions (>=2021.1)
