### ISSUE TITLE
Parent block in task log marked as done when child is still executing

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7254]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not a blocker but looks weird

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

In certain cases a parent log block may show as done on the UI even though a child log block shows as executing still:

![image](https://user-images.githubusercontent.com/11970672/145492258-fd7ae7cf-8237-4d85-8adf-8a67fdd84343.png)

The cause _may_ be that the "FIN" (finish) log of the parent is occurring before the child's, which is something that shouldn't be happening.

### Reproduction

1. Create an Offline Package Drop target with destination set to Artifact
2. Add a 'Deploy a package' step to the deployment process which deploys to the role of the newly created target
3. Create and deploy a new release
4. When the deployment starts, the target block is marked as successful even though the 'Creating Artifacts' block is in progress
![image](https://user-images.githubusercontent.com/11970672/148003567-322b5fc4-9719-4510-b1be-af917926e06d.png)

### More Information

Internal slack thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1639000600122400

### Workaround

If you refresh the page the log should show correctly.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1086 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1086 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1086 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
