### ISSUE TITLE
Pruning old message bus events can fail due to timeouts.

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7256]
### Team

- [X] I've assigned a team label to this issue

### Severity

This is causing a customer instance's database to grow unreasonably large and quite rapidly. Other customers may soon be affected.

### Version

2021.3.8815

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The background task that deletes old message bus events for some of our cloud customers was failing.

### Reproduction

This was found by some of our cloud customers

**Comment by sburmanoctopus** [comment]
Release Notes: Message bus event deletion now dynamically reduces the number of events dropped if a timeout occurs

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9551 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9551 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9551 |
| 2022.1+ | _all releases_ |
