### ISSUE TITLE
Variable preview endpoint does not scope on role if provided

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7261]
### Team

- [X] I've assigned a team label to this issue

### Severity

Regression on variable preview endpoint

### Version

2021.3.1198

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Previously the variable preview endpoint would scope variables to roles based on the `role` param. The variable preview UI was changed to remove the Role input https://github.com/OctopusDeploy/Issues/issues/6944. This means that when a target is specified, the variables are scoped to the target's role instead. However, scoping based on the `role` param was removed unintentionally as part of this change.

### Reproduction

1. Make a request to the `variables/preview` endpoint with the `role` set to the name of a role
2. Variables will not be scoped based on the role

### More Information

Internal ticket: https://octopus.zendesk.com/agent/tickets/80652
Internal slack thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1639401648193100

**Comment by N-lson** [comment]
Release Note: `role` parameter now functions correctly on the `GET /variables/preview` endpoint

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10181 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10181 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10181 |
| 2022.1+ | _all releases_ |
