### ISSUE TITLE
apt-key is deprecated warning when installing octopus cli

### ISSUE THREAD

**Issue by andriijas** [OctopusDeploy/Issues#7276]
### Severity

-

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Following the installation guide for octopus cli, i get apt-key is deprecated warnings.

### Reproduction

Easy to reproduce just follow the install guide on https://octopus.com/downloads/octopuscli#linux

### Error and Stacktrace

```shell
You get an message that apt-key is deprecated
```

### More Information

Investigate if you can provide a format of the key that can be used directly without converting to keyring with gpg --import and gpg --export 

### Workaround

Update installation guide for octopus cli to use the new recommended ways in debian work with keys,

sudo sh -c "echo deb [signed-by /path/to/keyring] https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list"

**Comment by ncipollina** [comment]
I see this was closed, but with no resolution?

**Comment by andriijas** [comment]
Dunno have not used octopusdeploy in over a year
