### ISSUE TITLE
Duplicate queries generated per transaction

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7279]
A [regression](https://github.com/OctopusDeploy/Nevermore/issues/173) in Octopus' ORM (what we use to query SQL) resulted in duplicate queries being run. This may cause performance regressions from unnecessary query-pressure on SQL.

## Workarounds

No workarounds.

**Comment by MarkSiedle** [comment]
Release Note: Fix for duplicate SQL queries being generated per transaction

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9863 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9863 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.9863 |
| 2022.1+ | _all releases_ |
