### ISSUE TITLE
Release Versioning is forced based on the first Package from step with multiple package references

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#7283]
### Team

- [X] I've assigned a team label to this issue

### Severity

Packages referenced with other packages in the same step cannot be selected for release versioning

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If multiple packages are referenced within a process step, you are forced to use the first package referenced for release versioning.

All packages referenced within the step are visible, however, when clicking anything other than the first package the selection is ignored and the first package is selected.

### Reproduction

1. Create a Project
2. Add a "Run a Script" step.
3. In the Referenced Packages field, add multiple packages.
4. Go to Deployment Settings and select Release Versioning.
5. Try to select any of the packages other than the first package within that step.

### Workaround

You can force the package to be used via API call by changing the DonorPackage.PackageReference.

When running this script, be sure to read and fully understand it before doing so.
Incorrect modifications to package references within versioning strategies can cause `Resource Not Found` errors.

Before running this script, select the first package available in the step where the package you want resides.
As this script does not change step names referenced, only package names referenced, not doing so will result in Octopus not being able to find the package in the step.

projectName can be entered as seen in the UI as it's converted into a slug by PowerShell.
packageName is the name as it appears in the drop-down box for versioning strategy, without the step name:

Example:
In Versioning Strategy Selection: "Script Step\Package Name"
In script: $packageName = "Package Name"

```
# Create Script Variables
$octopusUrl = "https://octopusURL"
$octopusAPIKey = "API-XXXXXXXXXXXXXXXXXXXXXXXX"
$header = @{ "X-Octopus-ApiKey" = $octopusAPIKey }
$spaceId = "Spaces-ID"
$projectName = "project name"
$packageName = "package name"

# Obtain Project data
$projectData = Invoke-RestMethod -Method Get "$($octopusUrl)/api/$($spaceId)/projects/$($projectName.Replace(" ", "-").ToLower())" -Headers $header

# Obtain Deployment Settings
$depSettings = Invoke-RestMethod -Method Get "$($octopusUrl)/$($projectData.Links.DeploymentSettings)" -Headers $header

# Set New Package Reference
$depSettings.VersioningStrategy.DonorPackage.PackageReference = $packageName

# API PUT New Settings
Invoke-RestMethod -Method Put "$($octopusUrl)/$($projectData.Links.DeploymentSettings)" -Body ($depSettings | ConvertTo-JSON -Depth 10) -Headers $header
```

**Comment by AdamHollow49** [comment]
Discourse thread where this was reported: https://help.octopus.com/t/cant-select-the-right-package-for-release-versioning/27518/4

**Comment by N-lson** [comment]
_Pretty_ sure it was introduced in https://github.com/OctopusDeploy/OctopusDeploy/pull/9400

**Comment by donnybell** [comment]
Related bug: https://github.com/OctopusDeploy/Issues/issues/7359

**Comment by N-lson** [comment]
Release Note: Release versioning selection for steps with multiple package references now works as expected

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12217 |
| 2022.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12217 |
| 2022.1 | 2022.1.1597 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12217 |
| 2022.1 | 2022.1.1597 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12217 |
| 2022.1 | 2022.1.1597 |
| 2022.2+ | _all releases_ |
