### ISSUE TITLE
Deployment proceeds to next step when "Deploy a package" to an offline package drop target is still running

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7286]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking

### Version

2021.3.X

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Given:
1. An offline package drop target with destination set to "Artifact"
2. A deployment process with:
  a. A "Deploy a package" step with role matching the above target
  b. A simple script step with run condition set to "only run when previous steps succeed"

When a deployment is run, the script step runs before the first step is finished:
![image](https://user-images.githubusercontent.com/11970672/148011101-e03b6802-49a8-4ff4-9c45-cb6fda10ae19.png)

This also looks to be related to https://github.com/OctopusDeploy/Issues/issues/7254 as the parent step block displays as successful even though the child activity is running.

This doesn't happen with Tentacle targets - the log displays correctly and the script step waits for the deploy a package step to complete before starting.

### Reproduction

1. Create an offline package drop target with destination set to "Artifact"
2. Create a deployment process with:
  a. A "Deploy a package" step with role matching the above target
  b. A simple script step with run condition set to "only run when previous steps succeed"
3. Create a release and deploy it
4. Observe the log

**Comment by zentron** [comment]
Closing as no reported customer impact as of yet
