### ISSUE TITLE
LDAP library error 

### ISSUE THREAD

**Issue by piyush94** [OctopusDeploy/Issues#7291]
### Team

- [X] I've assigned a team label to this issue

### Severity

High

### Version

2021.2.7964

### Latest Version

The problem does not exist in the latest build

### What happened?

```
Could not load file or assembly 'Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f'. The system cannot find the file specified.
```

### Reproduction

Configure LDAP and try to add LDAP group to a team

### Error and Stacktrace

```shell
Could not load file or assembly 'Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f'. The system cannot find the file specified.
```
```


### More Information

<img width="443" alt="image" src="https://user-images.githubusercontent.com/11614204/148198565-a41bda18-33d7-487f-bbe9-5e7f01da8340.png">


### Workaround

_No response_

**Comment by droyad** [comment]
@piyush94 Thank you for making a report, but please contact our [support ](https://octopus.com/support) team so we can triage your issue, and we can make sure it's handled appropriately.
