### ISSUE TITLE
Sample paths in Git File Storage Location UI don't appear to be correct

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#7300]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.10028

### What happened?

The sample paths for the Git File Storage Location refer to `./octopus` and `./octopus/acme` and they probably should be `.octopus/` and `.octopus/acme`

![image](https://user-images.githubusercontent.com/332730/148719771-edc05cdb-77b7-4414-9213-30b2ab770f10.png)

### Reproduction

- Go to version control settings for a new project

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.184 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.184 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.184 |
| 2022.2+ | _all releases_ |
