### ISSUE TITLE
Open redirect vulnerability in Octopus Server

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7301]
## Description

Octopus can redirect requests to arbitrary urls.

## Affected versions

**Octopus Server:** 2021.2

I suspect this was introduced in the Nancy -> ASP.NET core conversion, possibly 2020.x.

## Links
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1641568179037700
https://octopusdeploy.slack.com/archives/C01KX2Z32HE/p1641218773142300

**Comment by tothegills** [comment]
Url rewriter replaces the host when there is one in the rewrite result: https://github.com/aspnet/BasicMiddleware/blob/master/src/Microsoft.AspNetCore.Rewrite/Internal/RewriteRule.cs#L63

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8011 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8011 |
| 2021.3 | 2021.3.11057 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8011 |
| 2021.3 | 2021.3.11057 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8011 |
| 2021.3 | 2021.3.11057 |
| 2022.1+ | _all releases_ |
