### ISSUE TITLE
Valid CRT certificates are returning an "Unable to parse certificate 'cert name' (id: some-id)" on upload.

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#7302]
### Team

- [X] I've assigned a team label to this issue

### Severity

Some Users inconvenienced - Effective Workaround available

### Version

2021.3.10607

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A CRT file that is valid when tested with Certificate validity checkers, returns the following error:
![image](https://user-images.githubusercontent.com/5361797/148909097-f3d6136e-4547-48db-ba70-a5dfeac7487f.png)

Converting the CRT file to a CER file using the method outlined in the workaround shows that the certificate is in fact valid and works correctly.

### Reproduction

Grab the Certificate file from here: https://octopus.zendesk.com/agent/tickets/81869

Attempt to upload it to Library -> Certificates.

### Workaround

Double-click on the file labeled .crt to open it into the certificate display.
Select the Details tab, and then click Copy to File.
Click the Next option in the certificate wizard.
Choose Base-64 encoded X.509 (.cer), and then click on Next.
Now, browse to store your file and type in the filename that you want to keep
Finally, save the file.

**Comment by N-lson** [comment]
Release Note: Correctly parse valid certificates which have varying amounts of whitespace

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.11057 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.11057 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.11057 |
| 2022.1+ | _all releases_ |
