### ISSUE TITLE
Session invalidation UI for users

### ISSUE THREAD

**Issue by ankithkonda** [OctopusDeploy/Issues#7308]
# The enhancement

This issue will be used to track part of the overall work proposed by https://github.com/OctopusDeploy/Issues/issues/7142

## Proposed solution

- ~~New tab Sessions in the user's page that lists all sessions, reach out to UX team~~ (out of scope)
- ~~Sessions should show details such as IP, the device it was issued to, last time it was used~~ (out of scope)
- Revoke all sessions button in the tab
  - revoke individual session **(nice to have)**

## Links

Internal link (summary of discussion of #7142) - https://octopusdeploy.slack.com/archives/C01J6U3MHJ4/p1641879591030900

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1023 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1023 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
