### ISSUE TITLE
Tenant Variables Endpoints are Slow

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#7310]
### Team

- [X] I've assigned a team label to this issue

### Severity

At least one customer is affected by this

### Version

2021.2.7952

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Variable editing for customers with tenants was too slow. This could even stop them being able to use the product.

Affected endpoints:
- api/Spaces-1/tenants/variables-missing?projectId=PROJECTID&includeDetails=false
- api/Spaces-1/tenantvariables/all?projectId=PROJECTID
- api/Spaces-1/tenants/TENANTID/variables
- api/Spaces-1/certificates/all

### Reproduction

When the instance had many tenants, projects, and environments, with tenant variables all linked up, trying to load the variables page of a project (especially the 'all' variables) was unusable.

**Comment by sburmanoctopus** [comment]
Release Notes: Increased performance on tenant variable endpoints

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8012 |
| 2021.3 | 2021.3.11057 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8012 |
| 2021.3 | 2021.3.11057 |
| 2022.1+ | _all releases_ |
