### ISSUE TITLE
If a phase does not override the retention policy, a previous phase's policy is used

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7319]
### Team

- [X] I've assigned a team label to this issue

### Severity

Feature does not work as expected for everyone

### Version

3.xx

### Latest Version

I could reproduce the problem in the latest build

### What happened?

For release retention: if a lifecycle phase overwrites the default retention policy, all subsequent phases will use that retention rather than the default.

### Reproduction

- We have a lifecycle whose retention policy is set to keep releases for 600 days.
- Our first phase overrides that to keep just the last one
- All subsequent phases inherit from the lifecycle

![image](https://user-images.githubusercontent.com/171197/150032012-edbf106e-15f5-4cd2-b332-d63ad764d5c3.png)

### More Information

Support ticket: https://octopus.zendesk.com/agent/tickets/82235
Request thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1642526756209700

**Comment by N-lson** [comment]
After reviewing our [docs](https://octopus.com/docs/administration/retention-policies#set-release-retention-policies), the behavior described in the issue is intentional.

> Each phase will inherit the retention policy from the above phase, but this is something you can change by expanding the Retention Policy panel.

The UI was unintentionally changed from `2018.6.15` to show the lifecycle policy as the default for any phase with no custom policy. This previously showed the policy of the latest phase with a custom policy:
![image](https://user-images.githubusercontent.com/11970672/151483005-9da83e3e-2a69-4610-b569-03990081f5ee.png)

We've created a [new issue](https://github.com/OctopusDeploy/Issues/issues/7338) to update the UI and rollback the Tentacle retention policy changes made [here](https://github.com/OctopusDeploy/Issues/issues/6917).

**Comment by ImMattAsh** [comment]
While this will accurately reflect how Octopus works, it is counterintuitive to how a typical override/default situation works. Intuitively one would expect to have to override the lifecycle default, not the previous phases's lifecycle choice. It's kind of a "make sure you read the fine print" solution, IMO. Glad it will reflect the actual behavior accurately, but I think some thought should be given to whether this behavior makes the most sense for the typical user's expectations. I could see this being unintentionally missed by users very easily.

**Comment by N-lson** [comment]
Hey @ImMattAsh - we've had some internal discussion about this and do agree that this could go either way. Paul has provided a reason as to why we want to keep it the way it is:
> We did this because phases tend to get more "serious" over time, and the more serious they get, the more the retention policy matters. They usually want to keep "more" things as a release progresses, not less.
Usually a customer would do something like:
    Lifecycle: keep 3 releases
    Phase 1 (dev): inherit = 3
    Phase 2 (test): inherit = 3
    Phase 3 (staging): keep 5 releases
    Phase 4 (production): inherit = 5
Effectively they might want to say "if a release ever gets to staging or production, keep it forever, but if it was only ever deployed to dev, just keep a few".
The final phases are most likely to be production and therefore you want to keep the most of them. So it makes sense to base it on the previous phase more than the lifecycle default.

We do want to make this a bit clearer for others as well, so we'll be [updating our docs on retention policies](https://github.com/OctopusDeploy/docs/pull/1450) to add an explanation.
