### ISSUE TITLE
`/api/spaces` used to support `ids` query params

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#7321]
### Team

- [X] I've assigned a team label to this issue

### Severity

Possible a large number

### Version

2021.2.1666

### Latest Version

I could reproduce the problem in the latest build

### What happened?

`/api/spaces` used to support `ids` query params

After doing some research it seems this has been broken since v2021.2.1666.
The PR that broke it is https://github.com/OctopusDeploy/OctopusDeploy/pull/8556 which updated quite a few endpoints

### Reproduction

You can use curl to issue a request to the mentioned endpoint passing `ids`

### More Information

See [internal conversation in slack](https://octopusdeploy.slack.com/archives/C01HZFJRYSH/p1642550495125400)

### Workaround

None

**Comment by akirayamamoto** [comment]
@paulegradie do you think we can close this issue after you merged the PR above?

**Comment by paulegradie** [comment]
👍 This should have auto closed I would have thought. Thanks 🙏

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | 2021.3.12042 |
| 2022.1 | 2022.1.359 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | 2021.3.12042 |
| 2022.1 | 2022.1.359 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | 2021.3.12042 |
| 2022.1 | 2022.1.359 |
| 2022.2+ | _all releases_ |
