### ISSUE TITLE
validation errors and create branch

### ISSUE THREAD

**Issue by LeeMeyer** [OctopusDeploy/Issues#7322]
Currently when you create a new branch with the commit dialog and an error happens (on the process screen), the branch is created but you stay on the old one, the dialog closes and you see the error. This is possibly confusing for users who wouldn't necessarily realize they have created a new branch but are still on the old branch, even though the UI does tell them if they are looking for it. Maybe we need to better call our what happened or better define what the flow should be here if we are not happy with it.

https://octopusdeploy.slack.com/archives/CMJ4TPLKH/p1642568643069100

**Comment by cstrzadala** [comment]
Won't fix, wait for user feedback
