### ISSUE TITLE
Updating a Certificate from Tenanted to Untenanted deployment mode without removing associated tenants doesn't save

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7324]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not a big deal

### Version

2021.3.X

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you have a Certificate which is set to tenanted or both untenanted/tenanted and update the deployment mode to untenanted without first removing any associated tenants, the Certificate won't save the change even though it shows no error on the UI.
![CertTenanted](https://user-images.githubusercontent.com/11970672/150280242-fcf68313-3707-4427-b18c-f69eaed4b6b8.gif)

### Reproduction

1. Create a Certificate and set the deployment mode to tenanted + attach a Tenant to it
2. Update the Certificate to untenanted
3. Nothing happens

### Workaround

Remove any associated tenants first

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12205 |
| 2022.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12205 |
| 2022.1 | 2022.1.1392 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12205 |
| 2022.1 | 2022.1.1392 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12205 |
| 2022.1 | 2022.1.1392 |
| 2022.2+ | _all releases_ |
