### ISSUE TITLE
Recreating a Version Controlled Project pointing to an existing repo fails

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#7330]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.10803

### What happened?

Cannot link project to an existing repo

### Reproduction

1. Create a project and convert to version controlled
2. Delete Project
3. Create a new project and configure with the same repository+path as previously configured

**What Happens**
500 Error
![image](https://user-images.githubusercontent.com/1830666/150711736-482e963a-343c-4534-83fc-1ae06a4d2d03.png)

**What Should Happen**
The project should be updated to point at that repo.

**Comment by kengel100** [comment]
Searchable error message text: Branch has already been initialized

**Comment by YuKitsune** [comment]
Release notes: Fixed an issue where projects could not be configured with existing config-as-code files.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12091 |
| 2022.1 | 2022.1.630 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12091 |
| 2022.1 | 2022.1.630 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12091 |
| 2022.1 | 2022.1.630 |
| 2022.2+ | _all releases_ |
