### ISSUE TITLE
Lifecycle phase with no custom retention policy displays the incorrect inherited policy on the UI

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7338]
### Team

- [X] I've assigned a team label to this issue

### Severity

UI is misleading

### Version

2018.6.15 to current

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you have a lifecycle with some retention policy, and 2 or more phases in that lifecycle, if the first phase has a custom retention policy then the later phases will inherit this custom policy instead of the lifecycle's policy. However, the UI shows the phase inheriting from the lifecycle's policy. The backend processes the policies correctly.

The Tentacle retention policy now also behaves incorrectly after [closing this issue](https://github.com/OctopusDeploy/Issues/issues/6917) - both retention policies should function the same so we'd want to revert this fix.

### Reproduction

1. Have a lifecycle with release retention policy set to 5 days
2. Add a phase and set the release retention policy to 1 release
3. Add another phase with no custom retention policy
4. Note the second phase says 5 days instead of 1 release

### More Information

This was previously https://github.com/OctopusDeploy/Issues/issues/7319

**Comment by N-lson** [comment]
Release Note: Tentacle retention policy will inherit from previous phase instead of lifecycle. Phase UI now shows the correct inherited retention policies

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12132 |
| 2022.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12132 |
| 2022.1 | 2022.1.1062 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12132 |
| 2022.1 | 2022.1.1062 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12132 |
| 2022.1 | 2022.1.1062 |
| 2022.2+ | _all releases_ |
