### ISSUE TITLE
Viewing a Deployment Process creates a `Document modified` audit entry

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7344]
### Team

- [X] I've assigned a team label to this issue

### Version

Earliest tried was 2021.3. 11085

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When viewing a Deployment Process for a config as code enabled project via the portal, an audit entry is created saying "Document Modified".

![Screen Shot 2022-02-01 at 2 46 52 pm](https://user-images.githubusercontent.com/25342760/151914182-2e563a23-d472-423b-818d-390fc088de44.png)

### Reproduction

1. Create a version controlled project
2. Configure a deployment process
3. View the deployment process via the portal
4. Audit log will show a "Document modified" event

**Comment by YuKitsune** [comment]
Release note: Resolved an issue where viewing a deployment process for a version controlled project can create an audit entry

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12355 |
| 2022.1 | 2022.1.1908 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12355 |
| 2022.1 | 2022.1.1908 |
| 2022.2 | 2022.2.604 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.604 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12355 |
| 2022.1 | 2022.1.1908 |
| 2022.2 | 2022.2.604 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12355 |
| 2022.1 | 2022.1.1908 |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12355 |
| 2022.1 | 2022.1.1908 |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
