### ISSUE TITLE
Clicking on the edit release option does not load the edit screen. 

### ISSUE THREAD

**Issue by dan-close** [OctopusDeploy/Issues#7345]
### Team

- [X] I've assigned a team label to this issue

### Severity

1

### Version

2021.3.10327

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When selecting the Edit option from a release, the screen to edit the release does not launch. 

### Reproduction

Click into a release and select Edit from the ellipsis menu.

**Comment by N-lson** [comment]
Fixed in https://github.com/OctopusDeploy/Issues/issues/7285
