### ISSUE TITLE
Screen reader does not announce environments as they are focused

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#7346]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking

### Version

Known to exist in 2022.1. Probably has existed for a long time before that.

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Multi-Selects don't use the `option` role for their options, which makes them difficult to interact with via the accessibility tree. This means that screen readers don't announce options as they are focused.

### Reproduction

- Navigate to a multi select (for example, the environments multi select on the Deployment Target configuration page)
![image](https://user-images.githubusercontent.com/1892715/152058821-088ef052-61e7-4526-9091-ec3ab9ccca27.png)
- Try to interact with the options using a keyboard
- Observe that the screen reader doesn't announce the options as they are focused

### More Information

Our multi-select's options should be using the `option` role, but they are not. They were designed without accessibility in mind, so don't have any role. Somewhere up the component hierarchy, we use the grid roles as a side effect of some component we have selected for styling reasons, and this makes the options appear like a grid in the accessibility tree

#### Internal links

[Support ticket](https://octopus.zendesk.com/agent/tickets/82967)

**Comment by dyantako** [comment]
Release Note: Improved the accessibility of multiselect inputs

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.9015 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.9013 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.9013 |
| 2022.4+ | _all releases_ |
