### ISSUE TITLE
Spaces endpoint doesn't honour the `name` query parameter

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#7347]
### Team

- [X] I've assigned a team label to this issue

### Severity

None blocking, has shown up in things like the Terraform provider where engineers have assumed this is a valid query parameter

### Version

2021.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The root document exposes the following template for the Spaces endpoint

```
/api/spaces{/id}{?name,skip,ids,take,partialName}
```
However the name parameter is not applied. Providing a value for it results in all spaces being returned.

Given the parameter list, the expected behaviour would be for it to be doing an exact name match with that parameter. This filtering not working was a root cause of [this issue](OctopusDeployLabs/terraform-provider-octopusdeploy#259) in the Terraform provider. 

### Reproduction

Create 2 spaces with unique names. 
Using a browser or Postman or tool of choice hit `/api/spaces?name=oneOfYourNames` and the json will contain the data for both spaces.

### Workaround

Use `partialName` and check the result set yourself for the exact match you need.

**Comment by johnsimons** [comment]
Possible related to https://github.com/OctopusDeploy/Issues/issues/7321

**Comment by paulegradie** [comment]
I've reviewed the original Index responder / descriptor and it appears that the exact name filter was never implemented for these endpoint types. Furthermore, the old spec (whcih I think probably comes from the SpaceRoute.cs Template) doesn't match what the actual Index route provides (only partialName is available):

```
        public string Template => Route("spaces{/id}{?name,skip,ids,take,partialName}");
        public string Index => Route("spaces{?skip,take,ids,partialName}");
```
That is what will have probably led to the incorrect links collections being returned as well as the old swagger (which I think was incorrect).


This isn't related to #7321 (that was an actual bug I introduced 😓 ).

@slewis74 Filtering on the name is new functionality - so we can consider closing this issue. If we need exact name filtering, we can certainly add that to the API - its a pretty small bit of work 👍

**Comment by slewis74** [comment]
Sorry, I don't think we actually need exact name filtering, we just need to remove name from the template so aren't misrepresenting what the API supports.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.1062 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.1062 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.1062 |
| 2022.2+ | _all releases_ |
