### ISSUE TITLE
Trace level lock logs are showing up in task logs when target is "Run on server"

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7349]
### Team

- [X] I've assigned a team label to this issue

### Severity

Annoyance, and confusion

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Mutex logs are still appearing in the Task log when the target is set to "Run on server". These should be going to the system log (or at least they always used to).

### Reproduction

1. Run a script with target set to "Run on server" (this can be done through `Tasks -> Script Console -> Run the script on the Octopus Server`)

### Error and Stacktrace

```
[ServerTasks-124] [RunningScript] [Read Lock] [no locks] Trying to acquire lock
```

### More Information

https://github.com/OctopusDeploy/Issues/issues/7270

**Comment by veochen-octopus** [comment]
Release Note: script isolation mutex logging redirected from task log to system log

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1476 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1476 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
