### ISSUE TITLE
Worker Pool properties not displaying correctly when using Action Templates on Config as Code projects

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7351]
### Team

- [X] I've assigned a team label to this issue

### Version

Earliest tried 2022.1.552

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using an Action Template with a Config as Code project, the Worker Pool properties can sometimes display incorrectly in the portal:

![Screen Shot 2022-02-03 at 11 18 54 am](https://user-images.githubusercontent.com/25342760/152265204-50d163a0-45ce-45fa-88b5-801c9a85fa47.png)

### Reproduction

1. Create a Config as Code project
2. Add a step based on an Action Template (I've found the `Slack - Detailed Notification` to be a good example)
3. Set the execution location for that step to a Worker Pool
4. Commit
5. Refreshing the page should reset the execution location field to `Run on each deployment target`

**Comment by YuKitsune** [comment]
Release notes: Fixed worker pool properties not displaying correctly when using Action Templates on config-as-code projects.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12191 |
| 2022.1 | 2022.1.1301 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12191 |
| 2022.1 | 2022.1.1301 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12191 |
| 2022.1 | 2022.1.1301 |
| 2022.2+ | _all releases_ |
