### ISSUE TITLE
Unexpected error when manually creating release

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#7353]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.1.890

### What happened?

I manually created a release in the Octofront project and when I was taking to the release page, I was presented with this error screen.

![image](https://user-images.githubusercontent.com/332730/152457822-2dc86b31-ef64-401e-87d9-78420b3ea9ec.png)

Navigating away to Overview and then back to the release detail page did _not_ show the error

### Reproduction

I was unable to reproduce it when creating a new release 🤷 

The steps were
- create new release in Octofront Full channel
- Hit save/create
- Boom

**Comment by tothegills** [comment]
Unable to reproduce
