### ISSUE TITLE
Deploy an Azure Resource Manager Template variable Bind for the Account Resource Group doesn't work

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#7364]
### Team

- [X] I've assigned a team label to this issue

### Severity

No customers I'm aware of

### Version

2021.3.11085

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the Azure Resource Manager Step; Clicking on the bind option, doesn't provide any options for binding variables.
Also, typing in a variable manually doesn't allow you to save the entry
![Deploy an ARM Manager Template](https://user-images.githubusercontent.com/5361797/153197536-dd470f88-ab42-4e0f-9e36-278cec36bd8b.png)
.

### Reproduction

1. Add a "Deploy an Azure Resource Manager Template" step to your project.
2. Attempt to bind a variable to the Account Resource Group
![ARMBind](https://user-images.githubusercontent.com/5361797/153197465-667e6b13-de0e-4f2e-a034-c18899a80006.gif)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1679 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1679 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
