### ISSUE TITLE
Jira integration stops octo create-release comment if Jira has a "badrequest" response code

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#7369]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking 1+ customers, workaround is to disable Jira integration

### Version

Reported in 2021.3.8275

### What happened?

The `octo create-release` command will not work if Jira is returning `badrequest` response codes.

### Reproduction

See [Internal Discussion](https://octopusdeploy.slack.com/archives/C02A2SJ1ZFA/p1644425862420289)

### Error and Stacktrace

```shell
Jira: Failed to retrieve Jira issues 'issue-1, issue-2, issue-3' from https://web.site.website. Response Code: BadRequest (Reason: Bad Request)
```

### More Information

Affected Customer | [Internal Link](https://octopus.zendesk.com/agent/tickets/82646)
[Internal Discussion](https://octopusdeploy.slack.com/archives/C02A2SJ1ZFA/p1644425862420289)

### Workaround

Disable Jira in Octopus, create release, then re-enable Jira in Octopus

**Comment by donnybell** [comment]
Another affected customer: https://help.octopus.com/t/error-with-jira-integration-with-latest-release-2021-3-12205/27636

**Comment by Clare-Octopus** [comment]
https://octopus.zendesk.com/agent/tickets/83079 - Another affected customer 

I have managed to reproduce this - 2021.3.8275 works with JIRA and doesn't throw out any errors, if I then upgrade to 2021.3.12217 and refresh the browser (not push a new release out JUST refresh the browser) I get the error.

This is shown in the word doc I have attached to this comment.

The engineers and I have used my test instance and found the fix so this will get implemented into a build and make it through the pipeline. For any customers affected please use the workaround shown in this GitHub issue for now and subscribe to this issue so you can see when the fix is applied and in what version.
[JIRA Issue.docx](https://github.com/OctopusDeploy/Issues/files/8080144/JIRA.Issue.docx)

**Comment by jbristowe** [comment]
This behaviour can be attributed to the JSON payload that is sent to the route, `/rest/2/search` hosted by on-premise instances of Jira. This route is used to search for work items by ID values in Jira. The [Jira REST client sends a payload with the property/value pair, `validateQuery = "none"`](https://github.com/OctopusDeploy/JiraIntegration/blob/ba3737e77397dc8267c1788f42faf6ef13456e77/source/Server/Integration/JiraRestClient.cs#L96). This is by-design. The purpose of this property is to control how the API responds to search queries where no work items are found. Setting this property/value pair results in a `HTTP 200 OK` response from Jira hosted in the Cloud. Unfortunately, on-premise instances of Jira do not support this value; they only support the (deprecated) Boolean values of `"true"` or `"false"`. During investigation of this issue, it was discovered that setting this property to `"false"` resolved this unexpected behaviour.

**Comment by donnybell** [comment]
Another affected customer: https://octopus.zendesk.com/agent/tickets/83868

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | 2022.1.1825 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | 2022.1.1825 |
| 2022.2 | 2022.2.272 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | _tbc_ |
| 2022.2 | 2022.2.272 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | 2022.1.1825 |
| 2022.2 | 2022.2.272 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | 2022.1.1843 |
| 2022.2 | 2022.2.272 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.272 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | 2022.1.1843 |
| 2022.2 | 2022.2.272 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12294 |
| 2022.1 | 2022.1.1843 |
| 2022.2 | 2022.2.272 |
| 2022.3+ | _all releases_ |
