### ISSUE TITLE
Harden-InstallationDirectory.ps1 isn't signed

### ISSUE THREAD

**Issue by ankithkonda** [OctopusDeploy/Issues#7377]
### Team

- [X] I've assigned a team label to this issue

### Severity

Script is there, just need to sign it

### Version

script was added in 2021.1.6091

### Latest Version

I could not reproduce the problem

### What happened?

We sign the tentacle script https://github.com/OctopusDeploy/OctopusTentacle/issues/357 but not this one in server

### Reproduction

N/A

### More Information

Slack (internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1645036736504369

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.59 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.59 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.59 |
| 2022.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.59 |
| 2022.3 | 2022.3.10790 |
| 2022.4 | 2022.4.8167 |
| 2023.1 | 2023.1.1476 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.59 |
| 2022.3 | 2022.3.10790 |
| 2022.4 | 2022.4.8167 |
| 2023.1 | 2023.1.1476 |
| 2023.2+ | _all releases_ |
