### ISSUE TITLE
Improve performance of polling tentacle connection SQL query

### ISSUE THREAD

**Issue by ankithkonda** [OctopusDeploy/Issues#7378]
### Team

- [X] I've assigned a team label to this issue

### Severity

performance improvement 

### Version

2021.1.6160 and above

### Latest Version

Not applicable

### What happened?

we tend to call` SELECT * FROM [dbo].[Machine] ` when using polling tentacles. This causes performance issues for the db. We used to run a more efficient query by filtering on what we need. However there was a changed to pull everything. So when you have 1000s of polling tentacles this becomes as issue 

### Reproduction

N/A

### More Information

Initial report (internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1645047502449569
zendesk (internal) - https://octopus.zendesk.com/agent/tickets/82749

**Comment by cstrzadala** [comment]
For assignee, see https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1645063348399629?thread_ts=1645047502.449569&cid=CNHBHV2BX which details

>[#team-core-platform](https://octopusdeploy.slack.com/archives/C0276V91ZAA) have recently provided support for querying JSON. It might be worth seeing if we can leverage that directly through the `IQueryable` rather than falling back to raw sql as that has a bunch of drawbacks

**Comment by tothegills** [comment]
May be fixed by https://github.com/OctopusDeploy/OctopusDeploy/commit/21c7bd5a3b31f440ce2af798977d8c66dcdf4443

**Comment by tothegills** [comment]
Reopen if it continues to happen.
