### ISSUE TITLE
HCL parser version

### ISSUE THREAD

**Issue by imre-turi-cko** [OctopusDeploy/Issues#7383]
Hey,

I'm looking for some guidance regarding the HCLParser package(s).

2 different packages are available:
- https://github.com/OctopusDeploy/HCLParser
<img width="233" alt="image" src="https://user-images.githubusercontent.com/71646017/154586303-82f09308-15f1-4906-aaa6-0814c079f623.png">
Seems like the actual parser is not included by mistake?

- https://www.nuget.org/packages/Octopus.Core.Parsers.Hcl/
Contains the parsers, but and old version, not supporting HCL v2.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/71646017/154586540-ae357b03-3b29-48ab-a41b-ec968522f193.png">

Could you please advice where is the latest HCL parser package available?

**Comment by imre-turi-cko** [comment]
Summoning @andrewabest

**Comment by danefalvo** [comment]
Hi @imre-turi-cko , 
This repository is usually left for Octopus Team members to raise issue. Unfortunately your issue probably hasn't been seen as it has not triggered one of our workflows.

Please reach out to the support team using the email address support@octopus.com

Someone will definitely be able to point you in the right direction and help you solve your problem.

**Comment by cveld** [comment]
I am also confused
https://www.nuget.org/packages/Octopus.Core.Parsers.Hcl/ -> seems deprecated. Last update 2018
https://www.nuget.org/packages/Octopus.CoreParsers.Hcl -> most recent versie 1.1.599 end of year 2022.

What is the source code governing this?
It seems https://github.com/OctopusDeploy/HCLParser is related to the package with the dot Octopus.Core.Parsers.Hcl, i.e. the "deprecated" one
