### ISSUE TITLE
Execution Location not displaying correctly in the frontend

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7392]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.12191 onwards

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If no worker pool or target roles are set on a deployment step in a version controlled project, but the `Octopus.Action.RunOnServer` property is set to `true` in the OCL (Which should indicate that the default worker pool should be used), the frontend would incorrectly display the Execution Location:

![Screen Shot 2022-02-23 at 12 22 16 pm](https://user-images.githubusercontent.com/25342760/155251809-20b4ee39-7f9d-4fd7-bd18-80752f7691b3.png)

The `Octopus.Action.RunOnServer` property would also be set to `false` in API responses.

### Reproduction

1. Create a version controlled project
2. Add a step, which should execute on a worker pool
3. In the OCL, remove the worker pool related properties, and set `Octopus.Action.RunOnServer = "true"`
4. Return to the portal

### Workaround

Explicitly setting the `worker_pool` property on the action can resolve this issue.

**Comment by YuKitsune** [comment]
Release note: Fixed an issue with the Execution Location on version controlled actions occasionally displaying incorrectly

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12372 |
| 2022.1 | 2022.1.1942 |
| 2022.2 | 2022.2.694 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12372 |
| 2022.1 | 2022.1.1942 |
| 2022.2 | 2022.2.693 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.693 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12372 |
| 2022.1 | 2022.1.1942 |
| 2022.2 | 2022.2.693 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12372 |
| 2022.1 | 2022.1.1942 |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12372 |
| 2022.1 | 2022.1.1942 |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
