### ISSUE TITLE
Config as code - Feed 'feed-name' could not be found

### ISSUE THREAD

**Issue by realrubberduckdev** [OctopusDeploy/Issues#7398]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.8275

### What happened?

Trying out Octopus Deploy config as code EAP as we are considering moving towards config as code.

### Reproduction

Steps
- Use config as code EAP
- Use a step template that uses a script in nuget package from a feed "feed-name"
- Commit changes to git
- See error 
```
Feed 'feed-name' could not be found
```

### Workaround

Detach step template to be a step in deployment and the error seems to go away.

**Comment by benjimac93** [comment]
@realrubberduckdev this has been fixed in a later release ( I just can't for the life of me find the Issue to reference which versions it's fixed in ). 

I would recommend reaching out to support@octopus.com as the team do not actively monitor GitHub Issues as far as I'm aware

**Comment by N-lson** [comment]
https://github.com/OctopusDeploy/Issues/issues/7480#issuecomment-1097316667
