### ISSUE TITLE
Renaming the default Git Branch for a Git Project may result in Project being unable to load

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#7404]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.8275

### What happened?

Users renamed their default branch (`master`) from within GitHub itself to be `main`. When they went to Octopus to update their settings they were presented with the following error when trying to save
<img width="993" alt="image" src="https://user-images.githubusercontent.com/1830666/156298610-9ecc8d21-dfa3-4543-a828-8f4692c057fd.png">

### Reproduction

1. Create Git Project
2. In GitHub rename the default branch for this repository to something else
3. Go to Version Control Settings and try to update the default branch to the new name.
4. Read Error message. e.g 
> Remote repository returned an error: cannot delete branch 'refs/heads/master' as it is the current HEAD of the repository.

### Workaround

If the user clears their cache (`Configuration` --> `Git` --> `Clear Local Cache`) then goes straight to the project settings and updates the default branch the correct branch will then be used.

**Comment by StephenHeise** [comment]
I have not been able to repro on the latest version of master (can't get 2021.3.8275 to compile). This code seems to handle the branch being missing fine `~\Octopus.Core\Git\Repositories\RepositoryRoot.cs:396`:
``` c#
/// <summary>
/// We attempt to remove both the local worktree and branch. If we try and remove the branch without first removing the
/// worktree, bad things happen. E.g. "Cannot delete branch 'refs/heads/whatever' as it is the current HEAD of a linked repository."
/// </summary>
void RemoveLocalWorktreeAndBranch(Repository repository, string friendlyName, string canonicalName)
{
    var worktreeName = GitRepository.ConvertToWorktreeName(friendlyName.ToGitBranch());
    var worktree = repository.Worktrees[worktreeName];
    if (worktree != null)
    {
        systemLog.Info($"Removing the local worktree and branch for '{friendlyName}'.");
        repository.Worktrees.Prune(worktree);
        repository.Branches.Remove(canonicalName);
    }
    else
    {
        systemLog.Info($"Removing the local branch for '{friendlyName}'.");
        repository.Branches.Remove(canonicalName);
    }
}
```

**Comment by cstrzadala** [comment]
Closing as can't repro on `2022.2`
