### ISSUE TITLE
UI is making requests to incorrect routes after converting a project to Git

### ISSUE THREAD

**Issue by dylanlerch** [OctopusDeploy/Issues#7410]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.1

### What happened?

After converting a project to version control, other instances of the UI (in separate tabs or on other machines) are not passing the branch when making requests. The UI is holding on to the old project state (when the configuration was still stored in the database).

### Reproduction

- Open a project in 2 separate browsers or browser tabs.
- Convert the project in one of these browser instances.
- Without refreshing the browser, view the deployment process in the other instance of the UI (that was loaded before the project was converted).

### Error and Stacktrace

```shell
We received a request for a version-controlled resource on a non-version control route. Please use projects/{projectId}/{gitRef}/deploymentprocesses
```

### More Information

Not yet ruling out that it _could_ happening in the same UI instance that ran the project conversion, but haven't been able to reproduce it this way.

### Workaround

Refresh the browser. This will force a fetch of the new project state and you'll be good to go from there.

**Comment by StephenHeise** [comment]
I'm not sure it makes sense to fix this. The second tab doesn't know that the project has been converted to CaC. To fix this, we would need to change the Deployment Process page to always send a query to determine if the project has been converted to CaC before it get the deployment process data. Seems like a lot of mucking around for a very rare situation with a easy fix.
You can also _delete_ the project on one tab and try to go to the deployment process page on another tab (`Exception of type 'Octopus.Core.Model.Exceptions.EntityNotFoundException' was thrown.`). Don't really think that is worth fixing either.

**Comment by cstrzadala** [comment]
Closing as there is a valid work around for this issue and there isn't a high chance of having multiple tab instances of Octopus Server open and handling this issue.
