### ISSUE TITLE
Creating release in Git project when package does not exist shows The Version field is required error

### ISSUE THREAD

**Issue by dylanlerch** [OctopusDeploy/Issues#7412]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.1

### What happened?

When creating a release, if the any of the steps reference packages that do not exist, you will see a `The Version field is required` error.

![image](https://user-images.githubusercontent.com/4549037/156669768-37747c72-d478-44dd-9c66-f34e659c17c1.png)

You should only be able to get into this state by editing the `package_id` directly in the OCL. This should not be possible if the process is persisted in the database.

### Reproduction

Starting with this initial state:
- A project persisted in Git
- Deployment process with a step that references a package

Modify the OCL directly to set the `package_id` to a package that doesn't exist.

From this
```hcl
packages {
    ...
    package_id = "Package"
    ...
}
```

To this
``` hcl
packages {
    ...
    package_id = "PackageWithAnIdThatDoesNotExist"
    ...
}
```

### More Information

We will work on better handling of this case with a more helpful error message, for now follow the workaround below.

### Workaround

Ensure that all of the packages listed in your steps exist in the specified feed.

**Comment by YuKitsune** [comment]
Release note: The Create or Edit release page will now show a warning icon next to packages which could not be resolved from their feed.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2386 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2386 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2386 |
| 2022.2 | 2022.2.3181 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2386 |
| 2022.2 | 2022.2.3181 |
| 2022.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2386 |
| 2022.2 | 2022.2.3181 |
| 2022.3+ | _all releases_ |
