### ISSUE TITLE
AWS EKS Targets - IAM Authenticator v0.5.4+ no longer supports v1alpha1 endpoint 

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7413]
### Team

- [X] I've assigned a team label to this issue

### Severity

Workaround Exists

### Version

Effects Latest Version

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When adding a Kubernetes Deployment Target that uses an AWS Account for authentication, the health check fails due to the wrong endpoint, if the version of [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) is above 0.5.3.

(Unsure if this only affects health-checks, or if it impacts the deployment step as well)

### Reproduction

1. Add Kubernetes Deployment Target in Octopus
2. On the Worker Performing the Health Check, install aws-iam-authenticator version 0.5.4+
3. Perform Health Check - See Error

### Error and Stacktrace

```shell
Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1
```

### More Information
* [Dynamic Workers are built using the latest version rather than a pinned version](https://github.com/OctopusDeploy/DynamicWorkerVmImages/blob/master/Win2019/scripts/install-aws-iam-authenticator.ps1).
* [This pull request is responsible for the change](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/386)
* [🔒 Slack Thread](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1646356964735849) (internal)

### Workaround

**Option 1**
Where you control the execution environment for the affected step or health-check, install 0.5.3 of [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator)
`choco install -y aws-iam-authenticator --version 0.5.3`

**Option 2**
If you're encountering this problem when executing on a Windows Dynamic Worker (the current production version has `0.5.5` of the tool installed), you could change to running the step/health check in an execution container. The both the [Windows](https://github.com/OctopusDeploy/WorkerTools/blob/master/windows.ltsc2019/Dockerfile#L7) and [Linux](https://github.com/OctopusDeploy/WorkerTools/blob/master/ubuntu.18.04/Dockerfile#L4) versions of the Octopus Worker Tools image are built using version `0.5.3` of the `aws-iam-authenticator` tool.

**Comment by Clare-Octopus** [comment]
Any update on moving forward with using a different authentication package for Linux? We have a customer who was having issues getting 0.5.3 to work on an Ubuntu worker (discussion [here](https://help.octopus.com/t/client-authentication-k8s-io-v1alpha1-error-exec-plugin-invalid-apiversion/28034) and [here](https://help.octopus.com/t/client-authentication-k8s-io-v1alpha1-error-exec-plugin-invalid-apiversion/28426))

It seems like the aws-iam-authenticator package on an Ubuntu worker running in Kubernetes will error out if using 0.5.3 (see this specific post [here](https://help.octopus.com/t/client-authentication-k8s-io-v1alpha1-error-exec-plugin-invalid-apiversion/28034/13)). There were discussions [here](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1646356964735849) (internal link) about moving to Azure CLI for authentication.

Have any of our customers managed to get 0.5.3 working with Ubuntu in Kubernetes and would be willing to share how they accomplished it?

**Comment by patrick-smergut-octopus** [comment]
Another report with having issues getting this to work in Linux [internal]: https://octopus.zendesk.com/agent/tickets/99532

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10711 |
| 2022.4 | 2022.4.7439 |
| 2023.1+ | _all releases_ |
