### ISSUE TITLE
Artifact collection fails when running in a script in bash

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#7424]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.2.1122

### Latest Version

I could reproduce the problem in the latest build

### What happened?

In a script when we use `new_octopusartifact` the artifact fails to be collected with a warning
> Artifact foo.txt not found at path 'foo.txt'. This can happen if the file is deleted before the task completes. 

### Reproduction

https://main.testoctopus.app/app#/Spaces-25/projects/container/deployments/releases/0.0.1/deployments/Deployments-8962?tasklineid=0%2FServerTasks-843072_66EFUU6SFH%2F4f3d05218a5b4de9aa3b05fb9e4ef137%2F859406dad88a4d378c5d336036d11e15&activeTab=taskLog

### More Information

[Internal discussion](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1646895819512439)

**Comment by tothegills** [comment]
I think this is being caused by the temporary work folder being cleaned up before the artifact is retrieved from the server. A workaround would be to use a different folder (ie not ./) to create the artifact in.

**Comment by johnsimons** [comment]
Tried a different folder like @tothegills mentions above, still same issue 😢

**Comment by johnsimons** [comment]
So it seems @tothegills works if running directly on a worker, but if running in a container, it still fails.
![image](https://user-images.githubusercontent.com/122651/157774443-17c0a709-b565-4b81-a2af-7096a213f919.png)

**Comment by tothegills** [comment]
The deployment target home directory is mapped in the container. The file needs to be saved and collected from the mapped directory.

For example:

```
echo "Hello" > /home/Octopus/foo.txt
new_octopusartifact /home/Octopus/foo.txt
```
