### ISSUE TITLE
Run deployment as a different user

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#745]
A new "Feature" that can be enabled on deployment steps, and allows you to specify the username and password of a user to execute the current step as. 

The feature applies to PowerShell script steps as well as all of the package step types. 

The username and password fields can be bound, and they could even be bound to our new prompted variables. 

Some issues to consider:
http://blogs.msdn.com/b/shawnfa/archive/2005/03/22/400749.aspx

We'll also need to test whether the impersonated context automatically applies to child processes, and whether we run with profiles or not. 

As an alternative to impersonation within a thread, we could spawn a worker process, but we'd need to then find a nice way to communicate back to the parent process. 

This feature came from UserVoice: 

https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/4032707-run-steps-as-a-different-user

**Comment by ffMathy** [comment]
We also need this.
