### ISSUE TITLE
Consider not showing duration for future/queued tasks

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7460]
### Team

- [X] I've assigned a team label to this issue

### Severity

Nothing major. Only a little confusing.

### Version

any

### Latest Version

I could reproduce the problem in the latest build

### What happened?

On the release page, a duration text of "less than a second" always shows for queued/scheduled deployments. As they haven't started yet, it might be better to not show the duration for those tasks.

### Reproduction

Schedule a deployment to run in the future. Go the release page, and look at the `when` column.

![image](https://user-images.githubusercontent.com/101071188/161475253-9a541658-db39-4223-ac26-fae3222b5796.png)

**Comment by octokhor** [comment]
Closing this one. Understand the annoyance on this but not a priority.
