### ISSUE TITLE
Step using Nuget feed no longer functions correctly after conversion to version controlled project

### ISSUE THREAD

**Issue by acodrington** [OctopusDeploy/Issues#7462]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking on-prem customer, no workaround, unsure if they are 'testing' config-as-code or if this in a production project

### Version

Reported in 2021.3.12132, fixed in 2022.2.1086

### Latest Version

The problem does not exist in the latest build

### What happened?

After converting an existing project to config-as-code, Octopus shows an error in the process editor if the selected step is based on a template which accesses a package from a feed, as the feed cannot be found.

![Error shown on Step page](https://user-images.githubusercontent.com/277700/161645988-1a8f0b2e-1684-48fe-b1ec-067603f506e2.png)

### Prequisites:
Non-VCS project with a step that...
1. Based on a template
2. Template references a package from a feed

### Reproduction steps:
1. Convert project to git
2. Navigate to Process Editor
3. Select relevant step
4. See error related for missing feed

### More Information

This has been fixed in 2022.2, but is still an issue in 2022.1.

More info on existing internal issues:
https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/302
https://github.com/OctopusDeploy/OctopusDeploy/pull/11442

### Workaround

There is no workaround :(

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |
| 2022.3+ | _all releases_ |
