### ISSUE TITLE
Failed deployments with windows worker & windows execution container combination

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#7465]
### Team

- [X] I've assigned a team label to this issue

### Version

Customer saw error in 2021.3.8275 and 2022.1.2133

### What happened?

Error occurs when deploying a package (zipped with bash) to azure using a windows worker and windows worker tools execution container.

Have tried replicating the error using linux worker + linux worker tools and seem to work fine.

### Reproduction

See slack thread for cmds to produce zip

### Error and Stacktrace

```shell
Included in slack thread
```

### More Information

Original Ticket: https://help.octopus.com/t/failed-deployments-with-execution-containers/27776/6
Internal slack: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1648578450736009

**Comment by octokhor** [comment]
This has actually been resolved: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1648578450736009. Closing this now.
