### ISSUE TITLE
Viewing Step Templates in Library produces an error

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/Issues#7466]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking Samples, will affect all customers on this version.

### Version

v2022.2.2208

### What happened?

When attempting to view a step template from the Library -> Step Templates tab, the user is presented with the following error

![image](https://user-images.githubusercontent.com/5552453/162021342-3f0d08bc-88f6-4183-a108-57d126a442b5.png)

### Reproduction

Using the Samples instance (https://samples.octopus.app), navigate to the Step Template Library

- Click on Library
- Click on Step Templates
- Click on any template listed in either Custom Step Templates or Installed Community Step Templates

Direct link to quickly view issue - https://samples.octopus.app/app#/Spaces-106/library/steptemplates/ActionTemplates-384

### Error and Stacktrace

```shell
An unexpected error occurred in Octopus v2022.2.2208: "Error: The "RefreshProcessAccountsContext" context has not been initialized. Please ensure the provider exists above the current consumer in the component hierarchy to address this."
in Unknown
in ControlledTabsContainer
in UrlNavigationTabsContainer
in div
in Unknown
in div
in div
in TransitionAnimation
in div
in div
in PaperLayout
in div
in KeyboardHandler
in div
in FormComponent
in Unknown
in FormPaperLayout
in withRouter(FormPaperLayout)
in ActionTemplateInternal
in Unknown
in ErrorBoundaryInternal
in RouteAwareErrorBoundary
in div
in div
in Unknown
in t
in Unknown
in MediaQuery
in div
in NavigationSidebarLayout
in withRouter(NavigationSidebarLayout)
in main
in y
in ActionTemplateLayoutInternal
in p
in withRouter(Connect(ActionTemplateLayoutInternal))
in RenderWithLayout
in Unknown
in Page
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in Unknown
in RenderWithPage
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in ActionTemplateRoutes
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in LibraryRoutes
in n
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in t
in RootRoutes
in withRouter(RootRoutes)
in SpaceLoader
in WithPersistedSpace
in p
in withRouter(Connect(WithPersistedSpace))
in div
in StandardLayoutInternal
in p
in t
in ErrorBoundaryInternal
in ReloadableRoute
in SecureRoute
in t
in Unknown
in Unknown
in t
in t
in Unknown
in DevToolsContextProvider
in ClientConnector
in W
in t
in Unknown
in h
in Unknown
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in ErrorBoundaryInternal
in c
in App
```

### Workaround

No known workaround.  Adding steps to processes still seems to work fine, just viewing them seems to be the issue.

**Comment by payable-nick-godsland** [comment]
Has this been fixed? I created a step and then converted into a step template and now I can no longer view it. I'm using v2022.1 build 2184.

**Comment by tekerson** [comment]
Hi @payable-nick-godsland,
Yes, this issue should be fixed but unfortunately it looks like you're on one of the effected builds. Any build >= 2022.1.2226 should work for you.

**Comment by payable-nick-godsland** [comment]
Thanks @tekerson I've updated to the latest build and it fixed the issue.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2226 |
| 2022.2 | 2022.2.2328 |
| 2022.3+ | _all releases_ |
