### ISSUE TITLE
Deployment task page shows incorrect "ran for" time for process with Manual Intervention step

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#7468]
### Team

- [X] I've assigned a team label to this issue

### Severity

UI bug

### Version

Earliest tried was 2022.2 (Build 387-hotfix.903)

### Latest Version

2022.2.2754 

### What happened?

I noticed that the deployment task log shows two different values for how long the deployment ran for when deploying a release with manual intervention step. See screenshot below. The deployment ran for a few minutes but the first set of text says it ran for 1 second.

![image](https://user-images.githubusercontent.com/1571799/162069044-2ee9c38a-1457-44fa-a967-778fcfd09061.png)

It looks like this is relatively new. Deployments from yesterday seem to be fine.

### Reproduction

- Create a deployment process with a manual intervention step and a script step with a sleep of 15seconds
- Create a release
- Deploy the release
- Approve the intervention
- Observe the task log screen shows deployment ran for 1 second whereas the deployment took much longer

### More Information

When the manual intervention step is reached while deploying the release, the `TaskState` gets set to "Queued" and `Completed` field gets populated. `Duration` is calculated as `Completed-StartTime`. The completed field should change after manual intervention is received and deployment resumes.
 
![image](https://user-images.githubusercontent.com/4622084/162595813-b77d59d8-3e9d-4790-91e2-d78020dd6f06.png)

 

### Workaround

No workaround as the deployment itself succeeds, just the duration reported is incorrect.

**Comment by mik-ky** [comment]
Hey @ryanrousseau,

I've tried replicating on my cloud instance but was unable to reproduce the issue:
![image](https://user-images.githubusercontent.com/97423717/162081931-7d94c816-b5b1-4c3e-858d-4a51e0b844d9.png)

Is this a recurring issue?

**Comment by ryanrousseau** [comment]
Hey @mik-ky - after double-checking, it seems it only impacts projects with a manual intervention step, potentially as the first step. 

![image](https://user-images.githubusercontent.com/1571799/162208775-8daf7660-bbed-4572-9743-bf548db402cd.png)

Given that new info, I'm not sure how long it's been happening since it only affects that subset of deployments.

**Comment by mik-ky** [comment]
Thanks @ryanrousseau.

By adding a manual intervention step, I was able to reproduce this behaviour of server task details returning a fixed duration (e.g. 2 seconds) each interval. From testing, it looks like the duration stops incrementing and stays stopped until the whole process is finished.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/97423717/162334244-33d420ab-360c-4789-81bf-5f25f10740fc.png">

**Comment by donnybell** [comment]
Another affected customer [[Internal Link]](https://octopus.zendesk.com/agent/tickets/152125)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.1679 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.1679 |
| 2024.2+ | _all releases_ |
