### ISSUE TITLE
Audit login succeeded and failed events for authentication providers

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#7471]
# The enhancement

We have several requests from customers to audit login events (such as success and failure). There is also mounting evidence that this will help us prepare for ISO compliance audits in the near future.

Administrators should be able to see a history of login events for their users, showing username and IP address. E.g.

<img width="979" alt="2022-04-07 17_11_25-Audit - Octopus Deploy - Brave" src="https://user-images.githubusercontent.com/819605/162141030-6baf19b3-4720-4a48-bbf2-7b74f501b48a.png">

This needs to work for all supported authentication providers.

## Links

- [Internal support](https://octopusdeploy.slack.com/archives/C0K9DNQG5/p1634076148248400)

**Comment by MarkSiedle** [comment]
Release Note: Audit login succeeded and failed events for authentication providers

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |

**Comment by benjimac93** [comment]
@MarkSiedle Noticed this when in our audit logs tonight. So went looking for the release notes on it.

Seems to be a cloud issue that stops the IP coming though - gotta love nginx (v2022.2.4955)

![image](https://user-images.githubusercontent.com/33694220/168814150-93849bae-dc63-4e74-b917-5aa3e8b40b58.png)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |
| 2022.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2321 |
| 2022.2 | 2022.2.2937 |
| 2022.3+ | _all releases_ |
