### ISSUE TITLE
Library variable sets form not responding to clicking away

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7479]
### Team

- [X] I've assigned a team label to this issue

### Severity

Minor inconvenience - non blocking

### Version

Current

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When editing the library variable sets, the fields expand once clicked on or brought in focus. This expanded form doesn't respond to any clicking away _below the form_ and stays open. Weirdly, clicking anywhere above the lower edge of the form does work.

The screenshot shows `Scope` as an example as that is usually the last field to be edited. But same thing happens with `Name` and `Value`.

![image](https://user-images.githubusercontent.com/101071188/162886705-f709e233-b547-4637-a9f2-88eeb82dca32.png)

_Note_: Project variables work as expected. Only library variable sets seem to have this issue.

### Reproduction

1. Go to `Library -> Variable Sets`
2. Add or edit a variable set.
3. Click on any empty and existing field.
4. Try clicking away on any empty space at the bottom of the page - the field stays open.

**Comment by octokhor** [comment]
Closing this one.
