### ISSUE TITLE
Feature Request - Allow for Tenant Project Variables to be scoped to more than environment 

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7484]
# Prerequisites

- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future - Raised in F&M 
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this feature request
- [X] I have labelled the correct team - F&M
- [X] I have added the kind/enhancement label

# The enhancement
Currently, variables supplied by a tenant via a template, can only be scoped to an Environment. This could be improved by allowing for the variables to be scoped to 'Tenant Tags' for example. 

## What is the problem this solves or benefit it gives
It was discovered that [a recent issue with Tenant Variable scoping](https://github.com/OctopusDeploy/Issues/issues/6666) is by design and the solution is to use Variable Templates, however this only allows for scoping to Environments. 

## Proposed solution
Allow for Variable Templates to be scoped to tenant tags for example also. 

## Links
[Slack - Internal](https://octopusdeploy.slack.com/archives/C01J6U3MHJ4/p1649805126533109)

**Comment by octokhor** [comment]
There's some multi-tenancy work happening that will hopefully alleviate some of the scale issues this feature request is meant to solve (e.g. scoping to multiple tenants via tenant tags). Closing this to see if the multi-tenancy initiative helps instead.
