### ISSUE TITLE
"Corrupt repository" when deleting and recreating branch

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7485]
### Team

- [X] I've assigned a team label to this issue

### Severity

Affecting a handful of customers.

### Version

Earliest tried 2022.2.2964, have observed in past releases

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a branch has been deleted, and recreated, Octopus will throw an error saying `Corrupt repository. The 'HEAD' reference is missing.`

![image](https://user-images.githubusercontent.com/25342760/163107737-f710d4c9-8c19-44de-8234-5fafb5f8e47c.png)

### Reproduction

1. Create a branch
2. Checkout the branch in Octopus
3. Delete the branch
4. Create a new branch with the same name as the deleted branch
5. 💥

### Workaround

Clicking on `Clear Local Cache` in `Configuration > Git` can fix the issue.

**Comment by acodrington** [comment]
I've spent some time looking to this issue whilst on QRF duty, and the good news is that I think I've figured it out. The bad news is that I didn't have time to implement the actual fix during QRF, so here are the details for someone in the future (possibly myself) to pick up and complete.

## Reproduction
1. Create `zombie` branch at same commit as `main`, and set as active branch in Octopus Deploy on Process page
2. Delete `zombie` via GitHub
3. Navigate to Process Settings page:
![image](https://user-images.githubusercontent.com/277700/177094568-c11e0a64-0eb8-475a-9e2f-0b9f3898bef2.png)
4. Re-create `zombie` in GitHub
5. Navigate to Process page:    
![image](https://user-images.githubusercontent.com/277700/177094646-83a37cd9-e1e2-4caa-964f-6e72383e174d.png)

## Findings
When navigating to any page that uses version-controlled data, the handlers for the corresponding API requests will almost always depend on getting a `GitDocumentStore`, which in turn depends on `GitTransaction` which calls the `GitTransactionFactory.BeginOrAdoptExisting` method, which eventually calls `GitRepository`.[PrepareWorkTree](https://github.com/OctopusDeploy/OctopusDeploy/blob/d98ddf41cecf6b15324c66286e154a4786841421/source/Octopus.Core/Git/Repositories/GitRepository.cs#L126) method:

```
public async Task<(IRepositoryRoot rootRepository, IRepositoryWorktree workTreeRepository)> PrepareWorkTree(GitRef gitRef, CancellationToken cancellationToken)
{
    await repositoryRoot.EnsureRepositoryIsCurrent(cancellationToken);
    <snip>
}
```

The above call to `RepositoryRoot`.[EnsureRepositoryIsCurrent](https://github.com/OctopusDeploy/OctopusDeploy/blob/d98ddf41cecf6b15324c66286e154a4786841421/source/Octopus.Core/Git/Repositories/RepositoryRoot.cs#L266) does a whole bunch of things (too many?), but most importantly for this ticket, it calls [EnsureLocalBranchesAreCurrent](https://github.com/OctopusDeploy/OctopusDeploy/blob/d98ddf41cecf6b15324c66286e154a4786841421/source/Octopus.Core/Git/Repositories/RepositoryRoot.cs#L349) which will remove and cleanup any local worktrees that no longer have a remote branch:
```
// Delete the local working trees for any local branches that no longer have a
// remote branch to track (branch was deleted from the remote)
var extraneousLocalBranches = localBranches
    .Where(lb => branchRefSpecs.None(rb => rb == lb.UpstreamBranchCanonicalName))
    .ToArray();

foreach (var extraneousLocalBranch in extraneousLocalBranches)
{
    RemoveLocalWorktreeAndBranch(repository, extraneousLocalBranch.FriendlyName, extraneousLocalBranch.CanonicalName);
}
```
This will delete the worktree directory from the Octopus Server's local filesystem (via the libgit2sharp library), but unfortunately, the `GitRepository` instance does not know anything about this and therefore holds on to an instance of `IRepositoryWorktree` which *still references the filesystem directory that has just been deleted*.

All of this means that when the user recreates the deleted branch (Step 4) and navigates to another page with version-controlled data (Step 5), there is an invalid instance of `IRepositoryWorktree` which references a deleted directory, and the first attempt to do anything with the worktree fails. In this case, the failure occurs when [RepositoryWorktree](https://github.com/OctopusDeploy/OctopusDeploy/blob/d98ddf41cecf6b15324c66286e154a4786841421/source/Octopus.Core/Git/Repositories/RepositoryWorktree.cs#L113) tries to get the HEAD of the worktree via libgit2sharp.

## Solutions
While there are some potential quick 'n' dirty fixes that will fix the symptoms of this problem, a proper fix will require some refactoring of the repository classes (`GitRepository`, `RootRepository`, `WorktreeRepository`).

It would probably best to have `GitRepository` have more control over what is currently done in the `RootRepository.EnsureRepositoryIsCurrent` call. At the moment, `GitRepository` maintains a dictionary of `IWorktreeRepository` instances, yet has no idea the `RootRepository` will be (indirectly) deleting filesystem directories that are referenced by these instances.

**Comment by acodrington** [comment]
Moving ticket back to Backlog to be completed at a later date.

**Comment by cstrzadala** [comment]
Closing as no longer an issue
