### ISSUE TITLE
Git ref validation fails when branch contains a `/` character

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7486]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.12655

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a branch name contains a `/` character, the following message appears:

![](https://user-images.githubusercontent.com/25342760/163122213-3e1e4fe7-f94e-4f47-a6ae-e5485a38d870.png)

### Reproduction

1. Create a branch with a `/` character in the name
2. Try to switch to that branch in the Octopus portal
3. 💥

**Comment by YuKitsune** [comment]
Release note: Fixed an issue where switching to a branch with a `/` character in the name would cause the portal to redirect the user to the default branch.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2364 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2364 |
| 2022.2 | 2022.2.3086 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12692 |
| 2022.1 | 2022.1.2364 |
| 2022.2 | 2022.2.3086 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12692 |
| 2022.1 | 2022.1.2364 |
| 2022.2 | 2022.2.3086 |
| 2022.3+ | _all releases_ |
