### ISSUE TITLE
Swagger UI missing the body for POST'ing to the /users/ endpoints.

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#7489]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking

### Version

Earliest replication tested was 2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

SwaggerUI no longer includes the option to modify/send the body for POST'ing to /users endpoint - should show the body text box when you click "Try it out".

Looks like other endpoints (/users/login, /users/register etc.) exhibit the same behavior.

### Reproduction

1. Load SwaggerUI
2. Navigate to the Users section
3. Click on the POST to /users/ section
4. Click "Try it out"
5. Observe no body field presented.

### Workaround

Create users through the Web UI or via an external REST call to the /user/ endpoint.

**Comment by matt-richardson** [comment]
This looks to be solved now, @Justin-Walsh 

![image](https://user-images.githubusercontent.com/373389/215367455-a80a9010-13f8-43dc-a96c-e252629263ff.png)

**Comment by matt-richardson** [comment]
I think this was fixed in https://github.com/OctopusDeploy/OctopusDeploy/pull/15754, which means it'll be in `2023.1.4050`.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4050 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4050 |
| 2023.2+ | _all releases_ |
