### ISSUE TITLE
Steps generated by cloning a child step with a variable run condition to a different project may have inaccessible, nested properties

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#7498]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking

### Version

Tested in 2022.1.2232 (likely in all current versions with this functionality)

### What happened?

Steps generated by cloning a child step with a variable run condition to a different project may have inaccessible, nested properties. Octopus sees this as a child step with no parent, but there's no indication anything is wrong in the UI which can cause confusion when deploying.

It looks like the child properties may need to be mapped a level higher when the step is cloned (or cleared):
![image](https://user-images.githubusercontent.com/63249187/164062726-5021acad-b26b-4a5a-a2c9-996b29493dda.png)

### Reproduction

1. Create a project with a child step
2. Set a variable run condition for the child step
3. Clone the child step to a different project
4. Confirm via the Project JSON of the destination project

### Workaround

1. Delete and re-create the Step in the destination Project.

2. Set the original Child Step's run condition to `Success: runs when the previous child steps succeed (or is the first step)` then clone again.

3. Alternatively, you could edit the Process JSON via Swagger:

First, navigate to `http://YOUR_OCTOPUS_URL/swaggerui/index.html`. Then find the `GET` for `/projects/{projectId}/deploymentprocesses` under the **DeploymentProcesses** heading.

Input the Project ID of the project containing the broken step(s) and `Execute`:
![image](https://user-images.githubusercontent.com/63249187/164064666-b71b5b00-a04e-4bbf-b171-c095e2d923cd.png)

Copy the Response Body into your favorite text editor. Then delete the two properties as shown in the image below. Please note that the `KEEP` and `DELETE` designations are for demonstration purposes. You only need to delete the lines indicated, highlighted in red.
![image](https://user-images.githubusercontent.com/63249187/164066458-4e3e3a82-28ef-425f-83c6-78b604837ed3.png)

Once edited, copy your full Process JSON from your text editor. In Swagger, navigate to the `PUT` for `/projects/{projectId}/deploymentprocesses`, then paste into the text box. Be sure to input the Project ID, then `Execute`. (If you get an authorization error, make sure you use the Authorize button in Swagger by scrolling to the very top of the page; the button is on the far right of the screen.)

![image](https://user-images.githubusercontent.com/63249187/164067051-cd909b12-499c-4649-a85e-cb0e8343f076.png)

**Comment by donnybell** [comment]
Another affected customer [[Internal Link](https://octopus.zendesk.com/agent/tickets/154460)]

**Comment by hnrkndrssn** [comment]
Release note: Use run condition of child step when cloning to a different project

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.13363 |
| 2023.3 | 2023.3.13094 |
| 2023.4 | 2023.4.5965 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.13363 |
| 2023.3 | 2023.3.13094 |
| 2023.4 | 2023.4.5965 |
| 2024.1+ | _all releases_ |

**Comment by cmuesing** [comment]
I am another affected customer and am happy to see that it is fixed in the next releases. We are running 2023.2.13151. Just missed the fix last time we upgraded.
