### ISSUE TITLE
Prevent optional lifecycle phases from having automatic environments

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7505]
Prerequisites

- [ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [ ] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [ ] I have written a descriptive issue title
- [ ] I have linked the original source of this feature request
- [ ] I have labelled the value stream (area/core, area/steps, ...)
- [ ] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives
At the moment you can add automatic environments to an optional lifecycle phase. The problem is that these don't actually do anything, and basically behave like manual environments. This isn't really a valid state, and so we should consider preventing this from occurring in the first place.

## Proposed solution
- Add some kind of prevention on the UI (eg. greying out the optional phase option if an automatic environment is added)
- Add validation on the API to check if there are any automatic environments if the phase is optional
- An upgrade script to convert any automatic environments in existing optional phases to a manual environment

## Workarounds

Don't add environments as automatic to an optional phase.

## Links

Extending upon https://github.com/OctopusDeploy/Issues/issues/7446

**Comment by octokhor** [comment]
Low hanging fruit with minimal impact. Closing this unless more issues crop up
