### ISSUE TITLE
Git Project Access IssueGit Project Access Issue

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#7516]
### Team

- [X] I've assigned a team label to this issue

### Version

n/a

### What happened?

n/a

### Reproduction

n/a

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12725 |
| 2022.1 | 2022.1.2466 |
| 2022.2 | 2022.2.3712 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12725 |
| 2022.1 | 2022.1.2466 |
| 2022.2 | 2022.2.3712 |
| 2022.3+ | _all releases_ |
