### ISSUE TITLE
ArgumentNullException when dynamic extension configuration is null

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7519]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocks an instance

### Version

2022.1.2386

### What happened?

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Infrastructure.Headers.ContentSecurityPolicy.<GetHeaders>g__BuildDomainList|2_0(IReadOnlyCollection`1 domains) in ./source/Octopus.Server/Web/Infrastructure/Headers/ContentSecurityPolicy.cs:line 16
```

### Reproduction

Hard to reproduce

### More Information

Internal discussion: https://octopusdeploy.slack.com/archives/C06FUR5HN/p1651019424559229

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2495 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2495 |
| 2022.2 | 2022.2.3990 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.2495 |
| 2022.2 | 2022.2.3990 |
| 2022.3+ | _all releases_ |
