### ISSUE TITLE
Missing tenant variables again?

### ISSUE THREAD

**Issue by dario-l** [OctopusDeploy/Issues#7528]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.1.2495

### Latest Version

Not applicable

### What happened?

Tenanted project overview (at the tenant list also) shows triangle warning icon at each tenant with message `Some of the required variable values have not been set`. In fact all variables are set and all deployments works.

### Reproduction

Upgrade from previous version to the latest (2022.1.2495).

**Comment by danefalvo** [comment]
Hi Dario, Can you please contact support@octopus.com with your issue (and perhaps a screenshot).

Issues in this area are only raised by Octopus staff. 
![image](https://user-images.githubusercontent.com/5361797/166894662-431e8302-92a6-4b7c-842e-66ca4e439aeb.png)

Closing this issue.
