### ISSUE TITLE
Inconsistent padding in library tenant tag set onboarding page

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7531]
### Team

- [X] I've assigned a team label to this issue

### Severity

UI issue only

### Version

Effects Latest Version

### What happened?

When viewing the Tenant Tag page, the margin around the Documentation link is excessive:
<img width="1775" alt="Screen Shot 2022-05-04 at 17 14 04" src="https://user-images.githubusercontent.com/78527975/167041840-6bbf6549-11cf-4817-8402-695a390648e3.png">

### Reproduction

Navigate to the the TenantTag page which doesn't have any tag sets.

<a href="https://g.octopushq.com/MultiTenantTags" target="_blank" rel="noopener noreferrer">documentation<em class="fa fa-external-link" aria-hidden="true" style="margin-left: 0.25rem;"></em></a>  

### Error and Stacktrace

```shell
N/A
```

### More Information

[Internal - Slack](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1651728077899139)

### Workaround

N/A - very minor UI issue only

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5608 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5608 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5608 |

**Comment by rosslovas** [comment]
Release note: Fixed inconsistent padding in tenant tag set onboarding page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5608 |
| 2022.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.5608 |
| 2022.3+ | _all releases_ |
