### ISSUE TITLE
Can not create releases on CaC projects that use step templates without action template view permission

### ISSUE THREAD

**Issue by dylanlerch** [OctopusDeploy/Issues#7560]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking release creation for some users of some CaC projects 

### Version

2022.2.5531 onward

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Creating a release that uses a step template incorrectly requires `ActionTemplateView` permission. 

### Reproduction

- Create a Git project
- Add a step template to the process
- Attempt to create a release with a user that only has `ReleaseCreate`, `ProjectView`, and `ProcessView` permissions.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.6247 |
| 2022.3 | 2022.3.320 |
