### ISSUE TITLE
Improve `EventRelatedDocument` population

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7571]
# The enhancement

## What is the problem this solves or benefit it gives
Documents related to an event are added to the `EventRelatedDocument` table, by removing everything for this `event` and reinserting everything for this `event`, several times. This could lead to several consecutive deletes and inserts, creating unnecessary db load. It could also potentially lead to deadlocks.

## Proposed solution
- Is there ever a need to delete event related documents? If not let's get rid of the delete.
- If we do need to delete, can we apply the same treatment as in https://github.com/OctopusDeploy/OctopusDeploy/pull/12162 to minimize deletes and inserts.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7499 |
| 2022.3 | 2022.3.6341 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7499 |
| 2022.3 | 2022.3.6341 |
| 2022.4+ | _all releases_ |
