### ISSUE TITLE
Unable to push to git when `Block command line pushes that expose my email` is enabled

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7572]
### Team

- [X] I've assigned a team label to this issue

### Version

Earliest tried was 2022.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the `Block command line pushes that expose my email` option is enabled in GitHub, Octopus cannot push any changes to the repository. The following error is shown:

![Screen Shot 2022-05-31 at 8 45 27 am](https://user-images.githubusercontent.com/25342760/171065665-5f661914-04fb-4659-b001-5faafaac2bd6.png)

### Reproduction

1. Go to GitHub > Settings > Email > enable `Block command line pushes that expose my email`
2. Create a repository (or use an existing one)
3. Create a project in Octopus
4. Using a repository from GitHub, convert the project to version controlled
5. 💥

### Workaround

The only real workaround is to disable the option in the GitHub settings.

**Comment by cstrzadala** [comment]
Closing as no customers have raised this issue. May re-open if needed.
