### ISSUE TITLE
Performance issues tenant deployment when logs of user has lots of permissions

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#7577]
### What happened?

User has `ProjectView` permissions scoped to almost 3000 projects. Trying to create deployment to a tenanted project results in a SQL error

### Error and Stacktrace

Error Message Shows
> Error while executing SQL command in transaction ... 
> This is a rare event and only expected for extremely complex queries or queries that reference a vary large number of tables or partitions.

![image](https://user-images.githubusercontent.com/1830666/171517048-2e89cf5a-c4be-40c6-b131-1a0a8496eb1c.png)

### Workaround
An user with _unscoped_ project view permissions (i.e. can see all projects by default) can perform the required action as it bypasses this complex query.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12920 |
| 2022.1 | 2022.1.2744 |
| 2022.2 | _tbc_ |
| 2022.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12920 |
| 2022.1 | 2022.1.2744 |
| 2022.2 | _tbc_ |
| 2022.3 | 2022.3.1142 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12920 |
| 2022.1 | 2022.1.2744 |
| 2022.2 | 2022.2.6436 |
| 2022.3 | 2022.3.1142 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12920 |
| 2022.1 | 2022.1.2744 |
| 2022.2 | 2022.2.6436 |
| 2022.3 | 2022.3.1142 |
| 2022.4+ | _all releases_ |
