### ISSUE TITLE
Applying retention policies fails with more than 2100 projects

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7578]
### Team

- [X] I've assigned a team label to this issue

### Severity

Retention doesn't run, pretty bad

### Version

2021.3.12755

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you have more than 2100 projects or releases, release retention won't be able to run due to a query parameter limit

### Reproduction

1. Have more than 2100 projects
2. Run retention

### Error and Stacktrace

```shell
Error while executing SQL command in transaction 'ApplyRetentionPoliciesTaskController|ServerTasks-931589-e963dad7-b37f-43c5-a58e-e593176a9d8b|T498': The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
```

### More Information

Due to https://github.com/OctopusDeploy/Issues/issues/7518

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12928 |
| 2022.1 | 2022.1.2756 |
| 2022.2 | 2022.2.6444 |
| 2022.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12928 |
| 2022.1 | 2022.1.2756 |
| 2022.2 | 2022.2.6444 |
| 2022.3 | 2022.3.1214 |
| 2022.4+ | _all releases_ |
