### ISSUE TITLE
Add warnings when the SQL connection max pool size is less than triple the task limit/cap

### ISSUE THREAD

**Issue by rosslovas** [OctopusDeploy/Issues#7592]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives

Octopus Server instances with high limits on the number of concurrently running tasks can't properly take advantage without raising their SQL connection _Max Pool Size_ (which can be specified in the SQL connection string), as each task takes one or more SQL connection(s) from the pool during its lifetime.

## Proposed solution

In order to help get the max pool size increased when it may need to be, the proposed solution is to add warnings when the SQL connection max pool size is less than 3 times the task limit in two places:
* A log message during startup, when the task limit is determined by the license
* Configuration -> Nodes, when the task limit is determined by the user

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.1901 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.1901 |
| 2022.4+ | _all releases_ |
