### ISSUE TITLE
Some customers receiving a 401 error on all “Jira Status Update” steps in their deployments

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7596]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking customers from using JIRA

### Version

All versions where customers have the JIRA Connect App installed.

### Latest Version

I could reproduce the problem in the latest build

### What happened?

There is a current issue with the Octopus Jira Integration affecting a small number of users. Customers that are affected are receiving a 401 error on all “Jira Status Update” steps in their deployments with the error message:

![image](https://user-images.githubusercontent.com/92790462/172569254-5288a9eb-57fe-40aa-b86a-d629182ceb87.png)

If you test the JIRA App connection in Octopus customers see this:

![image](https://user-images.githubusercontent.com/92790462/172568095-c6a92e2e-c925-479f-96b3-78166a9603fa.png)

 In Jira, customers are unable to access the Octopus Deploy App and receive the following error:

![image](https://user-images.githubusercontent.com/92790462/172569004-d21356b0-cd45-492b-b9a3-b18808c2895b.png)

 We do not know why this happens, we have a theory that sometimes the JIRA Connect App can become out of sync to JIRA Cloud and needs its client secret between Jira and the ConnectApp resynced.

Historically when this has happened customers have re-installed the app and this fixes the issue. **However, due to the recent Atlassian issue with JIRA data being completely wiped when users reinstall the JIRA Connect app** (detailed in this [GitHub issue](https://github.com/OctopusDeploy/JiraIntegration/issues/100)) we now cannot use the reinstall option to get this to work again for customers.

### Reproduction

We have not managed to re-create this, seems like it happens randomly, doesn't seem to be a specific JIRA App version or Octopus version where this happens or the length of time the app has been installed. Customers have not reported doing anything specific when this happens. Sometimes if a customer upgrades the JIRA App this can happen but we have seen tickets in where it has just happened randomly.

### Error and Stacktrace

```shell
Customers are receiving a 401 error on all “Jira Status Update” steps in their deployments with the error message:

`Unable to publish data to Jira. Response code: Unauthorized, Message: Jira Cloud returned an authorization failure.`

 In Jira, customers are unable to access the Octopus Deploy App and receive the following error:


 Looks like something went wrong!

Unable to decode JWT token: Invalid signature. Expected: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=; Received: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=

We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try configuring your Octopus instance in Jira again.
```

### More Information

Tickets in so far (all internal):

https://octopus.zendesk.com/agent/tickets/87525
https://octopus.zendesk.com/agent/tickets/90045
https://octopus.zendesk.com/agent/tickets/86382
https://octopus.zendesk.com/agent/tickets/68214
https://octopus.zendesk.com/agent/tickets/70734
https://octopus.zendesk.com/agent/tickets/65888
https://octopus.zendesk.com/agent/tickets/2221 
https://octopus.zendesk.com/agent/tickets/85247

### Workaround

There is no workaround at present. **Please do NOT uninstall the app.**

Unfortunately, the only thing we can do at the moment is to advise customers to turn off JIRA Integration within Octopus itself so you are still able to deploy and keep old JIRA Data.

![image](https://user-images.githubusercontent.com/92790462/172570085-b3be6d67-39a8-4992-9e13-80115371a0ab.png)

**Comment by ann-mwangi** [comment]
The issue that was causing 401 error has been fixed. Now, customers are able to rotate the secret between JIRA and our ConnectApp, without the need to re-install the app.

Please note: The case where the historical deployment data was lost, has been flagged as expected behaviour from JIRA.

**Comment by slewis74** [comment]
Release note: Jira ConnectApp was updated to correctly handle secret rotations
