### ISSUE TITLE
Runbook multi-tenancy and deployment target status resets to default when cloning a project with runbooks

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#7602]
### Team

- [X] I've assigned a team label to this issue

### Version

Reported on 2022.3.349-hotfix.1272

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When cloning a project with runbooks, some of the runbook settings don't carry over to the clone - the `MultiTenancy` and `Deployment Target Status` values return to default.

### Reproduction

1. Create a project and change the settings to `Allow deployments with or without a tenant'
2. Create a runbook and change the settings to `Allow deployments with or without a tenant'
3. Clone the project
4. In the cloned project, you will see that the project's settings have been correctly cloned but some of the runbook settings have changed back to the default value.

### More Information

Internal link: https://octopus.zendesk.com/agent/tickets/89491

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.3878 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.3878 |
| 2022.4+ | _all releases_ |
