### ISSUE TITLE
Update Amazon ECS Service Step Template Targets Wrong Cluster

### ISSUE THREAD

**Issue by briggs-octo** [OctopusDeploy/Issues#7618]
### Team

- [X] I've assigned a team label to this issue

### Severity

1 customer currently

### Version

2022.3.349-hotfix.1272

### Latest Version

I could reproduce the problem in the latest build

### What happened?

I have two similarly-named ECS clusters set up in my AWS account (`wrong-cluster` and `cluster`), and when attempting to update `cluster` via the [Octopus Deploy step template](https://octopus.com/docs/deployments/aws/ecs-update-service) `wrong-cluster` was incorrectly selected during the deployment process (appears to match on the similar word "cluster" in `wrong-cluster` before hitting `cluster`).

### Reproduction

1. Set up two clusters in AWS ECS, `wrong-cluster` and `cluster`, in the same AWS region.
2. Ensure these clusters have two differently-named services configured (can use the same task definition).
3. Configure a new deployment target in Octopus Deploy, targeting the `cluster` ECS cluster.
4. Configure a deployment process that leverages the "Update Amazon ECS Service" step template, using the deployment target configured in step 3.
5. Create a release and perform a deployment.

### Error and Stacktrace

```shell
The deployment task log shows that the step properly lists out all clusters for the selected AWS region:

20:49:02   Verbose  |         "clientName": "ECSClient",
20:49:02   Verbose  |         "commandName": "ListClustersCommand",
20:49:02   Verbose  |         "input": {},
20:49:02   Verbose  |         "output": {
20:49:02   Verbose  |         "clusterArns": [
20:49:02   Verbose  |         "arn:aws:ecs:us-west-1:xxx:cluster/wrong-cluster",
20:49:02   Verbose  |         "arn:aws:ecs:us-west-1:xxx:cluster/cluster"
20:49:02   Verbose  |         ]
20:49:02   Verbose  |         }

Then, despite the deployment target being configured to target "cluster", "wrong-cluster" is targeted and a missing service error is thrown ("service-b" is associated with "cluster"):

20:49:08   Verbose  |       "clientName": "ECSClient",
20:49:08   Verbose  |       "commandName": "DescribeServicesCommand",
20:49:08   Verbose  |       "input": {
20:49:08   Verbose  |       "cluster": "arn:aws:ecs:us-west-1:xxx:cluster/wrong-cluster",
20:49:08   Verbose  |       "services": [
20:49:08   Verbose  |       "service-b"
20:49:08   Verbose  |       ],
20:49:08   Verbose  |       "include": [
20:49:08   Verbose  |       "TAGS"
20:49:08   Verbose  |       ]
20:49:08   Verbose  |       },
20:49:08   Verbose  |       "output": {
20:49:08   Verbose  |       "failures": [
20:49:08   Verbose  |       {
20:49:08   Verbose  |       "arn": "arn:aws:ecs:us-west-1:xxx:service/service-b",
20:49:08   Verbose  |       "reason": "MISSING"
20:49:08   Verbose  |       }
20:49:08   Verbose  |       ]
```

### More Information

Zendesk :ticket:: https://octopus.zendesk.com/agent/tickets/91308

### Workaround

Use non-similar names for AWS ECS clusters in the same region when using the "Update Amazon ECS Service" step template, where no cluster name matches the substring of another cluster name (i.e. `cluster` and `wrong-cluster`).

**Comment by geofflamrock** [comment]
🎉  The fix for this issue has been released in the following versions of ECS step templates:

<table>
<tr>
	<th>Step Template
	<th>Version
<tr>
	<td>Deploy Amazon ECS Service
	<td>1.3.1
<tr>
	<td>Update Amazon ECS Service
	<td>1.3.1
</table>

New versions of step templates are automatically updated by Octopus Server versions `2022.1`+ if **Step Template Updates** are enabled. To check whether step template updates are enabled go to **Configuration** -> **Features** -> **Step Template Updates**.
