### ISSUE TITLE
Support deployment to "air gap" machines

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#762]
In Octopus 1.6, you could use the following command to manually deploy a package using Tentacle:

```
Tentacle.exe deploy-package someFile.nupkg -v variable1=ABC
```

Unfortunately the number of variables required to be passed in meant that  `deploy-package` never really worked, so recently we removed it. 

Let's bring this back and make it usable.

**Comment by kpitt** [comment]
With this solution, will we be allowed to redistribute the Tentacle.exe application to a customer for running the install, or will the customer still need to purchase their own Octopus license?

**Comment by vanessalove** [comment]
@kpitt Sorry for the delay in response. The endpoint (customer) will  not require their own license. It will be counted as part of your own license machine count.

**Comment by jchannon** [comment]
Are there any docs for installing apps for customers that are offline?

Thanks

**Comment by alfhenrik** [comment]
[Calamari](https://github.com/OctopusDeploy/Calamari) is the tool that will be used for executing the "offline" deployment, so you can take a look there. 

But currently there is nothing within Octopus to create the variables file or commands required to be executed. (It's coming though in 3.0 as it was just merged today) :)

**Comment by jchannon** [comment]
ETA on 3.0 release I assume that will support proper offline deployments?

**Comment by alfhenrik** [comment]
Yes, 3.0 will have proper offline deployment support, fully self-contained and runnable on machines that does not have a Tentacle installed on it. 

No finalised date just yet, but pre-release is coming "soon", we're currently putting some finishing touches on it before getting it out there.
