### ISSUE TITLE
Scheduled Trigger Creation - Deploy New Release - TypeError: (reading AutomaticDeploymentTargets) When No Environments Exist

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7622]
### Team

- [X] I've assigned a team label to this issue

### Severity

Error Message Not Very Helpful - Workaround Exists

### Version

2022.3.2387

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When configuring a Scheduled Deploy Trigger which creates a new release, a Type Error is received if no environment has been configured. 

### Reproduction

1. Create new space and project (without creating an Environment)
2. Begin configuring a Scheduled Trigger and select "Deploy new Release"
3. See TypeError regarding AutomaticDeploymentTargets

### Error and Stacktrace

```shell
An unexpected error occurred in Octopus v2022.3.2387: "TypeError: Cannot read properties of undefined (reading 'AutomaticDeploymentTargets')"
```

### More Information

<img width="1198" alt="Screen Shot 2022-06-22 at 12 09 28" src="https://user-images.githubusercontent.com/78527975/174933552-9db6fc6c-ae72-40da-9e4c-b36c8dbb1d5f.png">

### Workaround

Create an Environment in the Space before configuring a trigger to 'Deploy new release'

**Comment by N-lson** [comment]
Unable to reproduce from 2023.1
