### ISSUE TITLE
Scheduled Tasks Logs are intermittently missing from the UI but appear in the shared `.\TaskLogs` folder

### ISSUE THREAD

**Issue by emilol** [OctopusDeploy/Issues#7624]
### Team

- [X] I've assigned a team label to this issue

### Severity

Non-blocking, known workaround

### Version

2022.2.3990 - 2022.2.6895
2022.3.earliest - 2022.3.3156

### What happened?

Scheduled task logs are getting suffixed with server node names that are no longer running. Eventually after the logs roll over, they reappear in the UI, but older logs appear to be missing.

### Reproduction

- Run Octopus Server one node1
- Run a scheduled task
- Shutdown node1, Run Octopus Server on node2
- Observe that logs are missing for the scheduled task

### Workaround

Exporting logs directly, rather than viewing through the UI will include the missing log files.

**Comment by emilol** [comment]
Relates to https://github.com/OctopusDeploy/Issues/issues/7611

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.6895 |
| 2022.3 | 2022.3.3156 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.6895 |
| 2022.3 | 2022.3.3156 |
| 2022.4+ | _all releases_ |
