### ISSUE TITLE
Creating a release in the UI is blocked if using a Docker feed that fails to search (eg. GitHub Container Registry)

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7626]
### Team

- [X] I've assigned a team label to this issue

### Severity

Can't create or view releases which use this feed

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you try to create a release that uses a Docker feed which doesn't support HTTP API eg. GitHub Container Registry, GitLab Container Registry, then the release fails to load with the error message listed at the top:
![image](https://user-images.githubusercontent.com/11970672/175203357-e5cc8d00-d555-47f5-a04b-213da0b4ffc6.png)

### Reproduction

1. Connect a GHCR external Docker feed to Octopus
2. Create a step that references a package from this feed
3. Create a release

### More Information

Internal discussions/customer reports:
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1655902488547239
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1655912877500419

### Workaround

Create a release via the API

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.3277 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.3316 |

**Comment by Clare-Octopus** [comment]
A side note to customers who are having issues creating releases via the API:

One of our customer's was unable to complete a manual release via the API, they were getting the 500 error and nothing else. To get it to work they had to edit the process via the UI, clone the "Run a docker container" step and then click save. They could then create a release.

It seems they have to do this each time they need to make a release, hopefully we can get the patch out to our Cloud customers soon. Most customers can create a release via the API with no issues but if you cant please try the workaround of cloning the project step above.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.3316 |
| 2022.4+ | _all releases_ |
