### ISSUE TITLE
Semantic Version Masks are not evaluated correctly for automatically created versions if it's the first release of that version number

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7627]
### Team

- [X] I've assigned a team label to this issue

### Severity

Triggered releases still don't get correct masked versions

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Pretty much this https://github.com/OctopusDeploy/Issues/issues/6774 but only when it's a new version. For example if you use `#{Octopus.Date.Year}.#{Octopus.Date.Month}.#{Octopus.Date.Day}.i`, if the triggered release is the first release created on the new day then you'll get an `i` in the evaluated release number.

If a release with a bad version exists eg. `2022.6.23.i` then attempting to manually create a release will result in this error:
```
Input string was not in a correct format.
```
![image](https://user-images.githubusercontent.com/11970672/175224130-2f097312-1865-41c6-8e5f-c24b614bbaa9.png)

Deleting the release with the bad version will allow you to create a release manually.

### Reproduction

1. Create a trigger
2. Use `#{Octopus.Date.Year}.#{Octopus.Date.Month}.#{Octopus.Date.Day}.i` as the version template

### More Information

Internal discussion: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1655949985161859

### Workaround

Manually correct the version on the first created Release.

**Comment by flin-8** [comment]
Release Note: Fix issue where the version mask isn't evaluated correctly for the first Release created via a trigger

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.3996 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.3996 |
| 2025.2+ | _all releases_ |
