### ISSUE TITLE
Docker images are reported as not found when creating a release

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7637]
### Team

- [X] I've assigned a team label to this issue

### Severity

Confusing

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Searching docker images doesn't work when searching for exact image ids. This is presumably due to the forward slash separating the owner and image name. A recent change was made to show when packages aren't found when creating a release https://github.com/OctopusDeploy/Issues/issues/7412. This leads to docker images showing up as not found even though they exist.

![image](https://user-images.githubusercontent.com/11970672/176357111-a9536141-bfe5-47e2-bc1d-0f2f87c68b52.png)
![image](https://user-images.githubusercontent.com/11970672/176357118-187707db-900d-402d-9ce9-767649fb7371.png)
![image](https://user-images.githubusercontent.com/11970672/176357124-1946098a-b9e5-4bec-9580-3ec4d4eab528.png)

### Reproduction

1. Have a docker feed
2. Add a deploy a package step referencing a package from the feed
3. Create a release

**Comment by michelle-luana** [comment]
@N-lson was this only happening for Docker Hub or other registries too?

**Comment by michelle-luana** [comment]
Closing this as it has been resolved for DockerHub
