### ISSUE TITLE
Bug in Kubernetes Secret resource Step when adding Duplicate Key Values

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7639]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking anything, UI needs updating so it shows an error rather than deletes a variable.

### Version

2022.1.2744

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A secondary Secret Item of the same name will wipe out the value of the first secret item of that name:

If you put a secret item in the `Deploy Kubernetes secret resource `step with the key of 'Test' and then a value it saves it fine. 
If you add another secret with a key of say 'Lest' it allows you to save it with a value alongside the previous Test secret.
If you then add another secret with the same key of 'Test' it wipes out the previous test key's value.

Please see video for a reproduction:

https://user-images.githubusercontent.com/92790462/176475662-05a18b42-5120-4dff-9f68-33680d02d240.mp4

### Reproduction

- Go into any project and add a `Deploy Kubernetes secret resource `step.
- Only fill out the Secret Items field:
  - Put a Key in called 'Test' with a value of '1234' and save the step.
  - Create another secret item with the key of 'Lest' and value of '1234', save the step.
  - Create one more key with the name of 'Test' - Watch at that box disappears and the value of the first 'test' key also disappears:

(See video above for example)

### Error and Stacktrace

```shell
No error in HAR file when running through the reproduction.
```

### More Information

Ideally what should happen here is you should be able to create a duplicate key without the previous key value disappearing, the UI should produce an error on save of the step saying something along the lines of 'You cannot have two secret items under the same key value.'

If the value of the previous secret item is deleted the customer might not know what it is to fill it back in!

Internal Ticket where this was reported - https://octopus.zendesk.com/agent/tickets/92057 

### Workaround

None, most users will not have the same value for secret items, _however,_ if you want a key for 'Test' you cannot put another key as 'Test 1' because the bug will appear as soon as you write out 'Test'.

**Comment by veochen-octopus** [comment]
Same issue with terraform steps and other steps with a similar setting.

**Comment by michelle-luana** [comment]
The Octopus engineering team has reviewed this issue.  
After careful consideration, we’ve classed this low priority. This means we won’t work on it in the near future. 
We prioritize issues based on the number of people affected, the impact type, and available workarounds. 
If you’ve encountered this issue and haven’t informed our support team, please email [support@octopus.com](mailto:support@octopus.com). Knowing how many people this issue affects helps us determine its priority.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.4740 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.4740 |
| 2025.2+ | _all releases_ |
