### ISSUE TITLE
Improving how shared resources are referenced from OCL

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7645]
# Summary

When config as code launched, git projects would reference shared resources using their name. This also meant that API responses from git projects would include names instead of IDs.

Instead of using names, we're introducing slugs into OCL, and bringing IDs back to the API for git projects.

With this change, git projects can reference shared resources from OCL using their unique slug instead of their name.
Octopus Server will convert these slugs to the resources IDs when returning results via the API, allowing (most) scripts to be re-used between database and git projects, without the need to account for names and IDs.

#### OCL

```ocl
step "hello-world-using-bash" {
    name = "Hello world (using Bash)"

    action {
        action_type = "Octopus.Script"
        channels = ["default"]
        environments = ["uat"]
        is_required = true
        properties = {
            Octopus.Action.RunOnServer = "true"
            Octopus.Action.Script.ScriptBody = "echo \"Hello Slugs!\""
            Octopus.Action.Script.ScriptSource = "Inline"
            Octopus.Action.Script.Syntax = "Bash"
            Octopus.Action.Email.ToTeamIds = "space-managers,global/everyone"
        }

        packages "Acme.Service" {
            acquisition_location = "Server"
            feed = "octopus-server-built-in"
            package_id = "Acme.Service"
            properties = {
                Extract = "True"
                Purpose = ""
                SelectionMode = "immediate"
            }
        }
    }
}
```

#### API

```json
{
  "Id": "hello-world-using-bash",
  "Slug": "hello-world-using-bash",
  "Name": "Hello world (using Bash)",
  "Actions": [
    {
      "Id": "hello-world-using-bash",
      "Name": "Hello world (using Bash)",
      "Slug": "hello-world-using-bash",
      "ActionType": "Octopus.Script",
      "Environments": ["Environments-2"],
      "Channels": ["Channels-1"],
      "Packages": [
        {
          "Name": "Acme.Service",
          "Id": "acme-service",
          "PackageId": "Acme.Service",
          "FeedId": "feeds-builtin",
        }
      ],
      "Condition": "Success",
      "Properties": {
        "Octopus.Action.RunOnServer": "true",
        "Octopus.Action.Script.ScriptBody": "echo \"Hello Slugs!\"",
        "Octopus.Action.Script.ScriptSource": "Inline",
        "Octopus.Action.Script.Syntax": "Bash",
        "Octopus.Action.Email.ToTeamIds": "teams-spacemanagers-Spaces-1,teams-everyone"
      },
    }
  ]
}
```

**Comment by YuKitsune** [comment]
Release note: Update OCL to reference shared resources via slugs instead of names. Update API responses for version-controlled documents to reference shared resources via IDs instead of names.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.4517 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.4517 |
| 2022.4+ | _all releases_ |
