### ISSUE TITLE
Unresolved manual intervention holding transaction open forever

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7647]
### Team

- [X] I've assigned a team label to this issue

### Severity

kinda non-blocking

### Version

Reported on 2021.2.7650

### What happened?

Unattended manual interventions after some time cause db (replicated) to time out. The tempdb version stores grow too large. We believe there's a transaction somewhere being kept open while waiting for the interruption to resolve.

### Reproduction

Below is a best guess

- Create a project with a simple deployment process that would error
- Use guided failure
- Deploy, which should result in a manual intervention
- Wait for a long time and watch the tempdb version stores grow in size

### More Information

Internal slack discussion - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1656639072790969
More discussion - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1660868210247089
Customer report - https://octopus.zendesk.com/agent/tickets/92111

### Workaround

Customer suggests restarting the mssql services resolves the issue at the cost of losing the intervention task, so is not a full workaround.

**Comment by donnybell** [comment]
Another affected customer: https://octopus.zendesk.com/agent/tickets/92598

**Comment by akirayamamoto** [comment]
Another customer is facing this error: `SQL Error 1222 - Lock request time out period exceeded`
Their issue could be related to this manual intervention problem: [internal] [ticket](https://octopus.zendesk.com/agent/tickets/94755).

**Comment by evolutionise** [comment]
Fixed in:
2023.1.9794
2022.4.8583
2022.3.11320

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.11320 |
| 2022.4 | 2022.4.8583 |
| 2023.1 | 2023.1.9794 |
| 2023.2 | 2023.2.5159 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.11320 |
| 2022.4 | 2022.4.8583 |
| 2023.1 | 2023.1.9794 |
| 2023.2 | 2023.2.5159 |
| 2023.3+ | _all releases_ |
