### ISSUE TITLE
Tenant selection UI slightly confusing

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7651]
### Team

- [X] I've assigned a team label to this issue

### Severity

minor UI/wording issue, non blocking

### Version

any

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Tenant selection provides both the ability to include tenants by names and by tenant tags. Some customers find it unclear whether the end result is a logical `AND` or `OR` on the 2 selections. The visual layout is also slightly different between tenant selection and the preview popup, potentially further indicating that they work differently. See screenshots below. This might just need a wording/visual update.

### Reproduction

- Create some tenants
- Create some tenant tags and randomly assign
- Create a deployment target
- Go to settings for this deployment target
- See `Associated Tenants`
- Click `Tenant Preview` and see the popup

### More Information

![image](https://user-images.githubusercontent.com/101071188/177423284-21237764-05b8-49ae-9a17-50f6b5dcd539.png)
![image](https://user-images.githubusercontent.com/101071188/177423291-eb5dd85f-752f-45d1-bd2c-508a1af4dc4b.png)

**Comment by brentkinney** [comment]
To add to this, we had a customer report the following behavior and I was able to confirm in 2022.3.2617-hotfix.4278

Observed:
When filtering Tenants by a tag that has not been assigned to any Tenant, Octopus returns ALL Tenants.

Also, if filtering by multiple tags from different tag sets, if you include a tag that has not been assigned to any Tenant, Octopus returns ALL Tenants.

Expected:
If you filter Tenants by a tag that hasn’t been applied, Octopus should return no Tenants.

**Comment by octokhor** [comment]
I'm closing this for now as we will focus on tenants as a larger piece of work next year.
