### ISSUE TITLE
Slow deployment process requests when using many action templates

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7652]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking one customer

### Version

Earliest tried was 2022.2.7131

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a version controlled deployment process references a large number of action templates, the performance of the `/deploymentprocess` route (and any other routes which may need to query the process) is degraded.
The performance is worsened as more templates are referenced.

### Reproduction

1. Create a project with a large number of actions (90+)
2. Have each step reference a unique template
3. Convert the project to version controlled
4. Try accessing the deployment process via the API or portal
5. 🐌

**Comment by YuKitsune** [comment]
Release note: Address a performance issue when using step templates in a version controlled deployment process.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7151 |
| 2022.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7151 |
| 2022.3 | 2022.3.4732 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7151 |
| 2022.3 | 2022.3.4732 |
| 2022.4+ | _all releases_ |
