### ISSUE TITLE
Extreme Slowness when accessing Artifacts from Octopus UI or API

### ISSUE THREAD

**Issue by brentkinney** [OctopusDeploy/Issues#7666]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.1.2875, 2022.2.6895, 2022.2.6971

### Latest Version

I could not reproduce the problem

### What happened?

After upgrading, several customers have noted degraded performance on the Artifacts endpoint.  It takes some customers 10-15 minutes to load a 10kb artifact.  With one customer, we discovered 65k orphaned artifact rows in their artifact table and provided an API script to clean out the orphaned rows.  The script ran for 24 hours and only got through 65 records.

This FM Thread will have more info - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1656899562070059

### Reproduction

Several attempts were made to reproduce the behavior, but we did not see any performance degradation.

### Error and Stacktrace

```shell
Affected Customers Are here:
https://octopus.zendesk.com/agent/tickets/92168
https://octopus.zendesk.com/agent/tickets/92623
https://octopus.zendesk.com/agent/tickets/92886
https://help.octopus.com/t/i-can-not-download-artifacts-after-upgrade/28120
```

**Comment by brentkinney** [comment]
Affected customers again for links:
https://octopus.zendesk.com/agent/tickets/92168
https://octopus.zendesk.com/agent/tickets/92623
https://octopus.zendesk.com/agent/tickets/92886
https://help.octopus.com/t/i-can-not-download-artifacts-after-upgrade/28120

**Comment by N-lson** [comment]
Release Note: Improved performance of retrieving and deleting artifacts

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3010 |
| 2022.2 | 2022.2.7301 |
| 2022.3 | 2022.3.5213 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3010 |
| 2022.2 | 2022.2.7301 |
| 2022.3 | 2022.3.5213 |
| 2022.4+ | _all releases_ |
