### ISSUE TITLE
Unable to remove client secret using the command line

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7684]
### Team

- [X] I've assigned a team label to this issue

### Severity

Nice to have. Workaround exists.

### Version

any

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The `configure` command accepts a client secret for an open id connection. Once it's set there's no way to remove it using the same command. Would be nice to be able to unset it by omitting the option or passing in an empty value. Currently this encrypts the empty string and uses that as the client secret.

### Reproduction

Run `configure` without `azureADClientSecret` or with `azureADClientSecret=""`. See the client secret in db become an encrypted empty string.

### More Information

Line in question: https://github.com/OctopusDeploy/OpenIDConnectAuthenticationProviders/blob/main/source/Server.OpenIDConnect.Common/Configuration/OpenIDConnectConfigureCommands.cs#L67

### Workaround

It's possible to do this via the UI under `Configuration -> Settings`

**Comment by octokhor** [comment]
Let's close this for now. Based on conversations around secrets, lots of folks are using the UI anyway to edit, manage and remove secrets so not a big priority in my mind. Will reopen if more cases pop up.
