### ISSUE TITLE
UI Bug on Worker Pools page when user is missing Permissions

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#7692]
### Team

- [X] I've assigned a team label to this issue

### Severity

not blocking

### Version

could repro on 2022.1

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a user is missing `WorkerEdit` permissions, the overflow menu for the Worker Pool shows an empty menu. 

### Reproduction

1. Add a new user
2. Add user to a new custom team with `Project Lead` user role
3. Add `WorkerView` space permission to the `Project Lead` user role
4. Create a new worker pool with worker
5. Sign in to new user and view Worker Pool page
6. Expand new worker pool section, click overflow menu and see bug

### Error and Stacktrace
<img width="1058" alt="Screen Shot 2022-07-28 at 3 50 31 pm" src="https://user-images.githubusercontent.com/82346985/181430365-9487dc80-a273-4824-983b-2ac838124cc5.png">

**Comment by octokhor** [comment]
Let's close this for now. Understand that this is a bug but it isn't a security problem and is doing the correct thing (i.e. not giving the user access to the overflow menu when not provided the right permissions.
