### ISSUE TITLE
ECS Step - Removing Entrypoint and Command from a Container Definition leaves empty ""

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7694]
### Team

- [X] I've assigned a team label to this issue

### Severity

Workaround Exists

### Version

Confirmed in 2022.3.4954-hotfix.6005

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When defining a container definition in the ECS step, if you add an Entrypoint and Command to your Container Definition and later remove it, there are leftover "". 

Pre-defining Entrypoint and Command:
<img width="529" alt="Screen Shot 2022-08-01 at 13 55 57" src="https://user-images.githubusercontent.com/78527975/182069390-222ae22c-4b76-417e-b04f-79c1f3cd55ac.png">

With Entrypoint & Command:
<img width="513" alt="Screen Shot 2022-08-01 at 13 56 43" src="https://user-images.githubusercontent.com/78527975/182069436-c686f673-9342-4f86-b7e0-4d743acc68a8.png">

Once Entrypoint & Command are removed:
<img width="520" alt="Screen Shot 2022-08-01 at 13 56 25" src="https://user-images.githubusercontent.com/78527975/182069475-2fefe94e-be5d-411e-aabb-f973cb556bf7.png">

### Reproduction

1. Configure ECS step to deploy container with Entrypoint and Command
2. Deploy and see Entrypoint and Command in ContainerDefinition
3. Remove Entrypoint and Command from the ECS Step's Container Definition
4. See leftover "" when deploying new release

### Error and Stacktrace

```shell
container_linux.go:380: starting container process caused: exec: “”: executable file not found in
$PATH
```

### More Information

[Customer Report](https://help.octopus.com/t/the-step-to-deploy-to-aws-ecs-is-formatting-wrong-the-task-definition/28176)

### Workaround

Delete the Container Definition in the ECS Step and reconfigure it

**Comment by tothegills** [comment]
Another report: https://octopus.zendesk.com/agent/tickets/126688
