### ISSUE TITLE
Too many redirects or authentication replays error when Git credentials are expired for Config as Code projects

### ISSUE THREAD

**Issue by dylanlerch** [OctopusDeploy/Issues#7695]
### Team

- [X] I've assigned a team label to this issue

### Severity

Unclear error message, not blocking.

### Version

2022.3.4368 onward

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the configured Git credentials are invalid or expired, a misleading error message is returned.

### Reproduction

- Create a new project and convert to Git with using a GitHub PAT for auth
- Wait for the PAT to expire
- Error is returned

I've only tested this with an _expired_ GitHub PAT. Have not confirmed if it's just limited to this specific scenario or all invalid or expired credentials.

### Error and Stacktrace

```shell
There was an error accessing version control.
- too many redirects or authentication replays
```

### Workaround

You should only see this error if your Git credentials are expired or invalid. Update the credentials on the Version Control settings page and the project will start working again.

**Comment by cruikshj** [comment]
This may have gotten worse in the latest release of Octopus (2022.3.10470).

The UI and API seem unable to set new credentials if the existing credentials are bad.  Here is the error.

> There was a problem with your request.
Remote repository returned an error: unexpected http status code: 403
There was an error accessing version control.
Unable to establish a connection to git.
Please check the URL, default branch name, and authentication details.
unexpected http status code: 403

This is blocking the use of the project and there seems to be no way to recover.

**Comment by YuKitsune** [comment]
Hi @cruikshj 
It looks like the issue you've describe is related to OctopusDeploy/Issues#7807.

**Comment by YuKitsune** [comment]
Release note: Improved error message when git credentials are invalid or expired.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10591 |
| 2022.4 | 2022.4.3438 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10591 |
| 2022.4 | 2022.4.3438 |
| 2023.1+ | _all releases_ |
