### ISSUE TITLE
DatePicker can show incorrect date when selected date differs from current DST

### ISSUE THREAD

**Issue by dyantako** [OctopusDeploy/Issues#7708]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.3.7461

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When selecting dates in the date picker, it can sometimes result in the previous date being selected rather than the chosen date.

### Reproduction

1. Open Octopus on a machine that has a timezone affected by daylight savings, on a day where daylight savings has not started.
2. Navigate to a date picker (e.g. Runbooks > Run > When > Later)
3. Open the date picker and select a date in the future where daylight savings will have started so the utc offset has increased. For example if the current day is 8 August 2022, my current utc offset is +12. I select 10 February 2023 which has a +13 offset.
4. Observe that 9 February 2023 is selected.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.7969 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.7969 |
| 2022.4+ | _all releases_ |
