### ISSUE TITLE
Lifecycle usage tab initially shows zero projects before loading

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#7709]
### Team

- [X] I've assigned a team label to this issue

### Severity

Can mislead users into taking certain actions

### Version

2022.3.5513-hotfix.7091

### What happened?

When opening the a lifecycle that has projects using it, the usage tab takes an amount of time proportionate to the amount of projects to change from 0 projects to the correct amount.

It would be expected to show a loading icon or some sort of text stating that data is still being collected before displaying a number.

### Reproduction

Attach a lifecycle to any amount of projects greater than 10.

Open the Library -> Lifecycle tab, then select the lifecycle and click "Usage".
Observe how the tab says zero projects are connected for a brief period of time.

Reported by user here: https://octopus.zendesk.com/agent/tickets/94138

**Comment by octokhor** [comment]
It looks like it still loads at the end of it. I'm closing this ticket now as it's super low priority but if more customers complain it as being an issue, we can reopen.
