### ISSUE TITLE
CaC externally delete branch create release fails

### ISSUE THREAD

**Issue by domrichardson** [OctopusDeploy/Issues#7717]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking

### Version

2022.3.4954-hotfix.6005

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If a project uses a version-control and you manually delete a branch externally for example through Github. when going to the create release page it fails with `No branch with the name 'refs/heads/test' exists in the repository`

This blocks the customer from creating releases both through the UI and other integrations e.g. OctoCLI.

[Internal Ticket](https://octopus.zendesk.com/agent/tickets/94495)

### Reproduction

1. Start with a project with config as code enabled.
2. Create a branch (`branchA`), and manually edit the process on this branch using the UI. Commit the changes and ensure that your process is valid.
3. Outside of OD, delete `branchA`. Do not return to the OD UI until later on.
4. Outside of OD, create a new release with a process git ref from another branch (`branchB`). We did this via an Azure DevOps pipeline, but I assume any other tooling would work so long as it's not the UI. Do not deploy the release automatically.
5. Back in the OD UI, go to the Overview page for your project, and find the release that was just created. Verify that the git ref associated to this release is correct (`branchB`).
6. Click the blue Deploy button to deploy this release into an environment.
7. The 'Deploy release' page will fail. Expected: the deploy release loads as expected, with the process from `branchB`. Actual: deploy release page fails to load, and instead displays a message in red along the lines of 'No git ref branchA', as if the UI is trying to load from the last branch that you were using in the UI.

### Workaround

Navigate to the projects Process tab and select a different branch.

**Comment by StephenHeise** [comment]
Internal issue: [565](https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/565)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.233 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.233 |
| 2023.1+ | _all releases_ |
