### ISSUE TITLE
Instances with large number of users face several issues due to Private Spaces being created for each user

### ISSUE THREAD

**Issue by egorpavlikhin** [OctopusDeploy/Issues#7718]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.1.1495

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Having a very large number (thousands) of spaces in an instance creates multiple issues:
1) Some queries face a limit of 2100 SQL parameters. This is true for queries that implicitly append a check for every existing space. The endpoints with such queries fail with 500 error.
2) Large number of spaces also degrades the performance due to the way space boundaries are checked in SQL queries.
3) Health check and other tasks that are launched periodically by every space create a very large queue of tasks, blocking other tasks from executing.

### Reproduction

1) Create a new Octopus instance.
2) Enable PrivateSpaces feature toggled.
3) Create 3000 users via the API.
4) Try to create a new Project via the user interface.

New Project dialog will take more than a minute to load even when running on a powerful local machine.

### More Information

Zenddesk ticket: https://octopus.zendesk.com/agent/tickets/94139

### Workaround

The task queue can be disabled for private spaces which will prevent further checks from triggering. This requires manual query execution on the database:

```
UPDATE [dbo].[Space] SET TaskQueueStopped = 1 WHERE IsPrivate = 1
```

**Comment by egorpavlikhin** [comment]
Release Note: Private spaces are decommissioned and will no longer be available. Existing private spaces will be deleted in the background over time.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3133 |
| 2022.2 | _tbc_ |
| 2022.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3133 |
| 2022.2 | 2022.2.7860 |
| 2022.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3133 |
| 2022.2 | 2022.2.7860 |
| 2022.3 | 2022.3.9395 |

**Comment by StephenShamakian** [comment]
@egorpavlikhin 

Important Note: This may help others that have the same problem. If the above SQL workaround is in place. This automatic delete feature does not trigger! The Private Spaces bust have a TaskQueueStopped value of 0 for this automatic feature to work.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3133 |
| 2022.2 | 2022.2.7860 |
| 2022.3 | 2022.3.9395 |
| 2022.4+ | _all releases_ |
