### ISSUE TITLE
When importing projects that have a library variable set attached you might get a duplicate entry for some variables

### ISSUE THREAD

**Issue by akirayamamoto** [OctopusDeploy/Issues#7720]
### Team

- [X] I've assigned a team label to this issue

### Severity

Non-blocking

### Version

2021.3.7082

### What happened?

When importing multiple projects with import/export ([bento](https://octopus.com/docs/projects/export-import)) that have a library variable set attached to them that have duplicate scoped values, you will get an extra duplicate entry for each import after the first.

If you attempt to delete these variables you get an error:
![image](https://user-images.githubusercontent.com/63259411/140796085-fb9f1ad3-6c83-4751-8b86-bfc99251770d.png)

An item with the same key has already been added. Key: 080c13ed-f995-ea0a-c1dc-11d16d75670b

This problem is very similar to this [other one](https://github.com/OctopusDeploy/Issues/issues/7154). However, this one does not affect variables with duplicate scoped values because that bug was fixed. We noticed this problem happening when one variable had a role and another did not but they ended up with the same ID.

### Reproduction
1. Create project with Library variable set
2. Scope library variables to something (Dev)
3. Export this project
4. Create project2, use the same Library variable set 
5. Add another scope to the variables (prod)
6. Import both projects into another space

### Workaround

Manually delete the variable in the variable set by running a update SQL command.

**Comment by nathanwoctopusdeploy** [comment]
## Internal Workaround

Using the Cloud Portal Run SQL Task run `SELECT [json] FROM dbo.[VariableSet] WHERE Id = 'variableset-LibraryVariableSets-TBC'` replacing the variable set id as appropriate.

Copy the `State` json from the Run SQL Task and save it to a file.

Run the following code to de-duplicate the variable set, merge scopes and warn about differences in variable values that were merged. It produces a SQL statement that can be run using the Cloud Portal Run SQL Task to update the variable set.

This relies on internal schemas for both the Cloud Portal and Octopus Server so may break if these change.

### LINQPad Query

```
<Query Kind="Program">
  <NuGetReference>Newtonsoft.Json</NuGetReference>
  <Namespace>Newtonsoft.Json</Namespace>
  <Namespace>Newtonsoft.Json.Bson</Namespace>
  <Namespace>Newtonsoft.Json.Converters</Namespace>
  <Namespace>Newtonsoft.Json.Linq</Namespace>
  <Namespace>Newtonsoft.Json.Schema</Namespace>
  <Namespace>Newtonsoft.Json.Serialization</Namespace>
</Query>

void Main()
{
	var filePrefix = "variableset-25";
	var originalJsonFilePath = @$"C:\temp\{filePrefix}-error.json";
	var originalJsonFilePathFormatted = @$"C:\temp\{filePrefix}-error-formatted.json";
	var fixedJsonFilePath = @$"C:\temp\{filePrefix}-fixed.sql";
	var fixedJsonFilePathFormatted = @$"C:\temp\{filePrefix}-fixed-formatted.json";

	var originalJsonString = File.ReadAllText(originalJsonFilePath);

	var wrapperJson = JsonConvert.DeserializeObject(originalJsonString) as JObject;
	var result = ((wrapperJson.SelectToken("Result") as JArray)[0] as JArray)[0] as JToken;
	var json = JsonConvert.DeserializeObject(result.Value<string>()) as JObject;
	
	Order(json);
	
	File.WriteAllText(originalJsonFilePathFormatted, JsonConvert.SerializeObject(json, Newtonsoft.Json.Formatting.Indented));
	
	Fixup(json as JObject);

	File.WriteAllText(fixedJsonFilePath, $"UPDATE dbo.[VariableSet] SET JSON = '{JsonConvert.SerializeObject(json).Replace("'", "''")}' WHERE Id = 'variableset-LibraryVariableSets-TBC'");
		
	File.WriteAllText(fixedJsonFilePathFormatted, JsonConvert.SerializeObject(json, Newtonsoft.Json.Formatting.Indented));

	var pi = new ProcessStartInfo
	{
		UseShellExecute = true,
		FileName = "code",
		Arguments = $"--diff {originalJsonFilePathFormatted} {fixedJsonFilePathFormatted}"
	};

	Process.Start(pi);
}

void Order(JObject json)
{
	var variables = json.SelectToken("Variables") as JArray;
	var ordered = variables.OrderBy(x => x.SelectToken("Id")).ToList();
	
	variables.RemoveAll();
	
	foreach (var item in ordered)
	{
		variables.Add(item);
	}
}

readonly JsonMergeSettings mergeSettings = new JsonMergeSettings
{
	MergeArrayHandling = MergeArrayHandling.Union
};

void Fixup(JObject json)
{
	var log = new StringBuilder();
	
	var variables = json.SelectToken("Variables") as JArray;
	var grouped = variables.GroupBy(x => x.SelectToken("Id")).ToList();
	var duplicates = grouped.Where(x => x.Count() > 1).ToList();

	foreach (var duplicate in duplicates)
	{
		var keep = duplicate.Take(1).Single();
		var KeepScope = keep.SelectToken("Scope") as JObject;
		var remove = duplicate.Skip(1).ToList();

		foreach (var item in remove)
		{
			if (keep.SelectToken("Value").Value<string>() != item.SelectToken("Value").Value<string>())
			{
				Console.WriteLine($"VALUES DIFFER for {keep.SelectToken("Id")} - '{keep.SelectToken("Value")}' vs '{item.SelectToken("Value")}'");
			}

			var itemScope = item.SelectToken("Scope") as JObject;

			KeepScope.Merge(itemScope, mergeSettings);

			variables.Remove(item);
		}
	}
}
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.7088 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10981 |
| 2022.4 | _tbc_ |
| 2023.1 | 2023.1.7088 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10981 |
| 2022.4 | 2022.4.8362 |
| 2023.1 | 2023.1.7088 |

**Comment by garrettdass** [comment]
Additional SQL query to find duplicate variables:
```
SELECT` DISTINCT vs.Id, vs.JSON
FROM dbo.[VariableSet] vs
CROSS APPLY OPENJSON (vs.JSON, '$.Variables')
  WITH (
    Id VARCHAR(300) '$.Id'
  ) AS vsj
WHERE vs.IsFrozen = 0
GROUP BY vs.Id, vsj.Id, vs.JSON
HAVING COUNT(*) > 1
ORDER BY vs.Id
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10981 |
| 2022.4 | 2022.4.8362 |
| 2023.1 | 2023.1.7088 |
| 2023.2+ | _all releases_ |
