### ISSUE TITLE
Tentacle update-trust command provides incorrect value for Polling Tentacle name

### ISSUE THREAD

**Issue by danefalvo** [OctopusDeploy/Issues#7730]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not Blocking

### Version

6.2.59

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the command "update-trust" when there is a thumbprint that doesn't match the thumbprint you want to change, you receive an error message that shows the target server, as opposed to the instance name. 

I believe the result should actually be the instance name.

Current Results:
```
Tentacle update-trust --oldThumbroot@dafubu22:/home/dane# /opt/octopus/tentacle/Tentacle update-trust --oldThumbprint="OLDTHUMBPRINTABC123" --newThumbprint="NEWTHUMBPRINTABC123"
Updating Octopus servers thumbprint from OLDTHUMBPRINTABC123 to NEWTHUMBPRINTABC123

Finding existing Octopus Server registrations trusting the thumbprint OLDTHUMBPRINTABC123
 and updating them to trust the thumbprint NEWTHUMBPRINTABC123:
Ignoring polling tentacle https://octopusserverurl.octopus.app:10943/ ADIFFERENTTHUMBPRINTABC123 - does not match old thumbprint
```

I believe it should be:

```
Ignoring polling tentacle DeploymentTargetName (https://octopusserverurl.octopus.app:10943) ADIFFERENTTHUMBPRINTABC123 - does not match old thumbprint
```

### Reproduction

1. Install a polling tentacle.
2. Use the command:
Tentacle update-trust --oldThumbprint="CE4CB70FXXXXXXXXXFA384D39F6B" --newThumbprint="03B95D6CC4E2D3828XXXXXXXXXXEFCCB012C4D"

The incorrect old Thumbprint in the above example, should result in the incorrect message being displayed.

**Comment by veochen-octopus** [comment]
Looks like this command works on a single tentacle instance at a time and goes through all the known server endpoints. The output does indeed reflect this process. However it's not very well explained by the command description. Closing this as it's a non issue. But will look at making the messages more consistent.
