### ISSUE TITLE
Cloning steps causes duplicate slugs

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7735]
### Team

- [X] I've assigned a team label to this issue

### Severity

Only report so far

### Version

Reported in `2022.3.7275-horfix.8764`

### What happened?

When cloning a step, then converting the project to git, the cloned step may have the same slug as the original step, causing odd behaviour in the UI:

![image](https://user-images.githubusercontent.com/25342760/186782369-0d3a0d1c-40fc-4789-998e-343ae86f7c85.png)

### Reproduction

1. Create a project
2. Add a step
3. Clone the step and save
4. Convert the project to version controlled
5. 💥

**Comment by YuKitsune** [comment]
Release note: Fixed an issue where duplicate slugs were allowed in deployment and runbook processed.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.899 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.899 |
| 2023.1+ | _all releases_ |
