### ISSUE TITLE
Project triggers are frequently modified without user input

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7740]
### Team

- [X] I've assigned a team label to this issue

### Severity

Affects all customers, annoying

### Version

latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The audit log contains an event for "Project trigger modified" after every run of a project trigger.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/171197/187566247-12b06681-acf7-498e-a676-6eba4d7c74aa.png">

### Reproduction

Run a project trigger.

**Comment by mjhilton** [comment]
This got closed as a result of a merge-forward from `2022.3` -> `master`. I'm unsure if it's complete or not, so I'm reopening and assigning to @tothegills for verification and any ReleaseBot actions

**Comment by tothegills** [comment]
Release note: Project triggers no longer generate modified audit events without user input

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3204 |
| 2022.2 | 2022.2.8132 |
| 2022.3 | 2022.3.10345 |
| 2022.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3204 |
| 2022.2 | 2022.2.8132 |
| 2022.3 | 2022.3.10345 |
| 2022.4 | 2022.4.982 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.3204 |
| 2022.2 | 2022.2.8132 |
| 2022.3 | 2022.3.10345 |
| 2022.4 | 2022.4.982 |
| 2023.1+ | _all releases_ |
