### ISSUE TITLE
Creating branches via the branch selector prefixes `refs/heads/` in the branch name

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7742]
### Team

- [X] I've assigned a team label to this issue

### Severity

No reports, only internal.

### Version

Earliest tried was 2022.3.9953

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When creating a new branch from the git ref selector, a commit is checked out instead, and a branch with `refs/heads/` prefixed in the name is pushed to the repository.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25342760/187595884-16cbbf57-794b-43d4-a308-71c04518ed8b.gif)

![Screen Shot 2022-08-31 at 2 58 00 pm](https://user-images.githubusercontent.com/25342760/187595934-7b104a05-1ccd-4e5d-81c8-65de3d3e5aad.png)

### Reproduction

1. Create a new branch from the branch selector
2. 💥

### Workaround

This seems to be isolated to the branch selector. Creating new branches via the API, or via the commit dialog works fine.

**Comment by YuKitsune** [comment]
Release note: Fix an issue where branches created via the branch selector would end up prefixed with `refs/heads/`

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10263 |
| 2022.4 | 2022.4.495 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10263 |
| 2022.4 | 2022.4.495 |
| 2023.1+ | _all releases_ |
