### ISSUE TITLE
Rolling deployments to targets can happen out of order

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7743]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking but potentially disruptive

### Version

Found on 2022.2.7897

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A rolling deployment to a list of targets is supposed to go down the target list ordered by name. Sometimes it happens out of order and can seem random.

### Reproduction

- Create a rolling deployment with at least 2 targets
- Create a release and run enough deployments
- See that occasionally the targets are deployed to randomly

### More Information

Internal discussion: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1661212516450579

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.8068 |
| 2022.3 | 2022.3.10300 |
| 2022.4 | 2022.4.627 |

**Comment by veochen-octopus** [comment]
Release Note: Ensure rolling deployments happen in correct order based on targets.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.8068 |
| 2022.3 | 2022.3.10300 |
| 2022.4 | 2022.4.627 |
| 2023.1+ | _all releases_ |
