### ISSUE TITLE
Worker is unable to expire stale package locks after running worker retention

### ISSUE THREAD

**Issue by brentkinney** [OctopusDeploy/Issues#7744]
### Team

- [X] I've assigned a team label to this issue

### Severity

affecting 2 known customers but deployments are not affected

### Version

2022.2.7934

### What happened?

When running deployments on Linux workers, the following errors are displayed:

`Releasing package lock for XCAMCIAW1P-Worker.

August 31st 2022 14:33:29

Info

Unable to expire stale package locks.

August 31st 2022 14:33:29

Info

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

August 31st 2022 14:33:29

Info

at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

August 31st 2022 14:33:29

Info

at System.Linq.Enumerable.WhereListIterator`1.MoveNext()

August 31st 2022 14:33:29

Info

at Calamari.Deployment.PackageRetention.Model.PackageJournal.ExpireStaleLocks(TimeSpan timeBeforeExpiration) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Deployment\PackageRetention\Model\PackageJournal.cs:line 120

August 31st 2022 14:33:33

Info

The deployment completed successfully.`

![image](https://user-images.githubusercontent.com/48770271/187801762-b327c928-00ca-4ba2-bdff-a5fc50951ae2.png)

### Reproduction

I was unable to reproduce the behavior on my local setup but it appears to occur with deployments running on linux workers that have package steps and that have this change - https://github.com/OctopusDeploy/Issues/issues/6664

### More Information

Possibly related to this change https://github.com/OctopusDeploy/Issues/issues/6664
Affected customers - https://octopus.zendesk.com/agent/tickets/95419 & https://octopus.zendesk.com/agent/tickets/94875

**Comment by SeanStanway-Octopus** [comment]
FYI another customer who seems to have encountered this: https://octopus.zendesk.com/agent/tickets/95757 (internal link)

**Comment by brentkinney** [comment]
Another Report of this https://octopus.zendesk.com/agent/tickets/96638 (internal link)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.8476 |
| 2022.3 | 2022.3.10655 |
| 2022.4 | 2022.4.5165 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.8476 |
| 2022.3 | 2022.3.10655 |
| 2022.4 | 2022.4.5165 |
| 2023.1+ | _all releases_ |
