### ISSUE TITLE
API deployments/create/untenanted/v1 fails to deploy release in a version controlled project

### ISSUE THREAD

**Issue by borland** [OctopusDeploy/Issues#7746]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Attempting to deploy a release using the new API's added in 2022.3

```
POST http://<server>/api/Spaces-1/deployments/create/untenanted/v1
POST http://<server>/api/Spaces-1/deployments/create/tenanted/v1
```

For database-backed projects, the operation succeeds.

For version controlled projects, the operation fails; The Octopus Server returns an HTTP 404 response with the following response payload

```json
{
  "ErrorMessage": "The resource 'deploymentprocess-Projects-423' was not found."
}
```

Where `Projects-423` is the ID of your project.

Both tenanted and untenanted deployments are affected

### Reproduction

1. Configure a version-controlled project in octopus deploy
2. Create a release within that project (let's say release 0.0.1)
3. Attempt to deploy the release using the API:

Specifically: 
```json
POST http://<server>/api/Spaces-1/deployments/create/untenanted/v1

{
  "spaceId": "Spaces-1",
  "spaceIdOrName": "Spaces-1",
  "projectName": "Your Project Name",
  "releaseVersion": "0.0.1",
  "environmentNames": ["Your Environment Name"],
}
```

The server fails to deploy with the error message as above `The resource 'deploymentprocess-Projects-423' was not found.`

Performing the same request on a database-backed project succeeds and creates the deployment tasks.

### More Information

Debugging:

The new API attempts to get the deployment template to validate it.

It does this by performing `Mediator.Request(new GetTemplateRequest(untenantedCommandV1.ProjectName.Value.ToProjectIdOrName(), releaseVersion), cancellationToken)` within the server.

This hits code in `GetTemplateForRelease` in GetTemplateRequestHandler which does this:

`var projectProcess = deploymentProcessDocumentStore.AsUserWithAllPermissions().GetByProject(project);`

This line throws an exception. In a version controlled project we need a Git Reference to resolve the project deployment process, however none is available during deploy-time. A Git Reference shouldn't be needed here; deployment should only reference the process snapshot associated with the release, which is not dependent upon git.

Root cause is that this particular `GetTemplate` method was intended for use by release creation (which has a Git Reference available). Release creation compares the snapshot process against the project process and shows a warning if they differ, which is why it wants to load the project process.

Release deployment doesn't need to do any of that; This method should not have been re-used by release deployment.

### Workaround

This only affects releases created using this specific HTTP API (which is, at time of writing, only the early-development new Go CLI)

Neither the Octopus Web Portal, nor the .NET OctopusCLI use this API, and they are unaffected.

**Comment by borland** [comment]
Discussion with @slewis74 -- the code is loading the project template so it can compute a property `IsDeploymentProcessModified` on the returned `DeploymentTemplateResource` -- however searching through all our Octopus code, other than a unit test (which always expects `false`) no code ever appears to read the property.

Solution: Remove the code which looks up the project process and just have `IsDeploymentProcessModified` return false all the time (removing the property would be an API break)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10271 |
| 2022.4 | 2022.4.495 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10271 |
| 2022.4 | 2022.4.495 |
| 2023.1+ | _all releases_ |
