### ISSUE TITLE
Add Slug to Space

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#7750]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives
A number of our domain models have recently had Slugs added. Space is not currently one of them.

This means:
- we have no option but to continue bleeding DB Ids out through the API
- Users of integrations, or those scripting against the API, are forced to use IDs for everything, rather than names or slugs that are human readable

## Proposed solution

The proposed solution is to add Slug to Space, support setting it through the API, and support using it instead of SpaceID in the API/UI routes.

## Workarounds

None.

**Comment by slewis74** [comment]
Release note: Added slugs to Spaces, and added support for using them in the API routes

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.1915 |
| 2023.1+ | _all releases_ |
