### ISSUE TITLE
Tenant tag filter not working properly if there's no match

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7756]
### Team

- [X] I've assigned a team label to this issue

### Severity

Makes tenants page less searchable

### Version

Can repro on 2022.3. Probably earlier versions too.

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Filtering by tenant tags on the Tenants page only works if the tag matches at least one tenant. If there is no match, it doesn't do _any_ filtering making it look like everything is a match. I'd expect there to be no results.

### Reproduction

- Create a tenant tag and a few tenants
- Go to the Tenants page and select the tag
- See that the page shows all tenants

### More Information

Seems to only happen if the `/tenants/tag-test` call returns all tenants as mismatches. There's probably a condition that short circuits any update in the UI when this happens.

**Comment by N-lson** [comment]
The tenants overview page has been updated, this should be fixed.
