### ISSUE TITLE
Can't connect a version controlled project to a forked pre-v5 schema repo

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#7758]
### Team

- [X] I've assigned a team label to this issue

### Severity

One report with a workaround

### Version

2022.3.9164-hotfix.10176

### What happened?

When configuring a project to point to a forked repo which uses a schema version pre-v5, the version in schema_version.ocl is updated to v5, however it looks like the migration itself isn't applied. This causes a `Sequence contains no matching element` error in the project's process.

### Reproduction

1. Fork a pre-v5 schema version repo
2. Connect an Octopus project to this new forked repo
3. See version in ocl updated, however project's process page fails to load with `Sequence contains no matching element`

### More Information

[Private report.](https://octopus.zendesk.com/agent/tickets/95595)

### Workaround

The user who initially reported this issue has worked around this by manually editing the schema_version.ocl back to the original version (v3 in their case).

**Comment by YuKitsune** [comment]
Release note: Fixed an issue where git migrations may incorrectly get skipped.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.1282 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.1282 |
| 2023.1+ | _all releases_ |
