### ISSUE TITLE
Deployments containing ManualInterventions fail if Jira WorkItems 

### ISSUE THREAD

**Issue by rain-on** [OctopusDeploy/Issues#7763]
It has been identified that a deployment will fail with an autofac "circular deployment" error if:
* Jira Integration is enabled
* The deployed release relates to Jira Work Items
* The deployment contains a Manual Intervention

All other deployments are unaffected.

**Comment by rain-on** [comment]
This issue can be hotfixed by modifying the MapServerTaskToTaskResource to not calculate/populate the UnmetPreconditions, this will break the circular dependency.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10405 |
| 2022.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10405 |
| 2022.4 | 2022.4.1327 |
| 2023.1+ | _all releases_ |
