### ISSUE TITLE
Releases created by scheduled triggers are not considered for Insights Lead Time and are missing from the detail tables

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7780]
### Team

- [X] I've assigned a team label to this issue

### Severity

Incorrect reports

### Version

at least 2021.3, likely or earlier

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a release is created by a scheduled trigger, no Release History is kept. Therefore Insights can't:
- Calculate a LeadTime
- Show it in the CSV or detail tables as the Version of the release is not found.

### Reproduction

Create a scheduled trigger that creates a release and deploys it
Wait
Check Insights charts and tables. The frequency chart shows it occurred, but it is missing form Lead Time chart and any detail tables (including CSV)

**Comment by MissedTheMark** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/14203, released in 2022.3.10566

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10566 |
| 2022.4 | 2022.4.3022-master-online-index-rebuild |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10566 |
| 2022.4 | 2022.4.3034 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10566 |
| 2022.4 | 2022.4.3034 |
| 2023.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10566 |
| 2022.4 | 2022.4.3022-master-online-index-rebuild |
| 2023.1+ | _all releases_ |
