### ISSUE TITLE
Error accessing some Git repositories on 2022.3

### ISSUE THREAD

**Issue by dylanlerch** [OctopusDeploy/Issues#7784]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When accessing Git repositories (from Git projects) from in some Git providers, an authentication error is returned. So far we have only been able to reproduce this on Azure DevOps Server 2020 Update 1.2

### Reproduction

Attempt to connect a project to a Git repository hosted in Azure DevOps Server 2020 Update 1.2

### Error and Stacktrace

```shell
There was an error accessing version control. Unable to establish a connection to git. Please check the URL, default branch name, and authentication details. too many redirects or authentication replays
```

**Comment by YuKitsune** [comment]
Release note: Fixed an issue where Octopus couldn't authenticate with git repositories hosted by Azure DevOps Server 2020.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10591 |
| 2022.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10591 |
| 2022.4 | 2022.4.3438 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10591 |
| 2022.4 | 2022.4.3438 |
| 2023.1+ | _all releases_ |
