### ISSUE TITLE
Cannot view git resources without `GitCredentialView` permission

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7796]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking customers, discovered internally

### Version

Introduced in 2022.4.2098

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When attempting to view git resources from the UI, the `git/validate` endpoint returns the following error if the user does not have the `GitCredentialView` permission:

![Screen Shot 2022-09-26 at 10 09 00 am](https://user-images.githubusercontent.com/25342760/192171971-2a0b70ec-8652-4c57-a009-0a700d5843fb.png)

### Reproduction

1. Create a git project using shared credentials
2. Create a new user with access to the project, but without the `GitCredentialView` permission
3. Have the new user attempt to access a version controlled page (E.g: Deployment Process)
4. 💥

**Comment by YuKitsune** [comment]
Release notes: Fixed an issue where the `GitCredentialView` permission was required to invoke the `/git/validate` endpoint.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.3289 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.3289 |
| 2023.1+ | _all releases_ |
