### ISSUE TITLE
Target Roles auto-fill only surfaces roles against deployment targets, not roles on deployment processes

### ISSUE THREAD

**Issue by mjhilton** [OctopusDeploy/Issues#7797]
## Enhancement
When defining a deployment process which runs against Targets in a Role, you may not yet have the targets available. The Process Editor allows you to perform an "add new" action to define a Role in the process.

However, the suggestion box for the Target Role fields only ever surfaces roles that are defined against Targets, it doesn't show up roles that only exist on Processes.

So if you do:

* Create Deployment Target
  * Add new role "abc"
* Create Deployment Process
  * Run on Server for Targets in role

When you start typing in the Roles text box in the process editor, the role "abc" is suggested.

If you do this in reverse:

* Create Deployment Process
  * Run on Server for Targets in role
  * Add new role "abc"
* Create Deployment Target

When you start typing in the Roles text box in the Add Deployment Target page, the role "abc" created on the deployment process is not suggested. If you type the exact same role for your target then it will all line up and work, but it feels like a bug that the role you "created" in the process is not suggested.

This enhancement is to update "Role" suggestion drop-downs to source its suggestions from both Processes _and_ Targets in the current permissions scope, not just Targets.

## Links
Requested internally ([🔒 Slack thread](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1663942175973879))

**Comment by mjhilton** [comment]
After some discussion internally, it seems that this is not a problem with the Process Editor, but with the underlying API which retrieves Roles to populate into the auto-suggest dialog, and some historical/architectural reasons.

In short, to do this under the current way roles are architected would cause some pretty severe performance implications for customers with large numbers of deployment processes. This challenge is the same underlying reason for [not being able to rename Roles](https://octopusdeploy.uservoice.com/forums/170787-product-feedback/suggestions/3271170-renaming-roles), which has been a long-standing feature request.

**Comment by veochen-octopus** [comment]
Thanks @mjhilton for the detailed investigation into this. Unfortunately we don't have the capacity for this work anytime soon. I'm closing this for now. Let's revisit in the future.
