### ISSUE TITLE
Unable to save issue tracking settings

### ISSUE THREAD

**Issue by BobJWalker** [OctopusDeploy/Issues#7803]
### Team

- [X] I've assigned a team label to this issue

### Severity

Potentially anyone on 2022.4 cannot save issue tracking settings

### Version

2022.4.2848

### Latest Version

I could reproduce the problem in the latest build

### What happened?

It was reproduced in 2022.4.2910 as well.

When attempting to save Jira Issue Tracking or GitHub Issue Tracking, I get the following error:

Error Message:
![image](https://user-images.githubusercontent.com/38642825/192632671-130f2f43-d17d-419d-bd06-6ec42469355c.png)

Browser Log:
![image](https://user-images.githubusercontent.com/38642825/192633380-ff34e570-91c8-47c8-a5b1-a24b19cf29ad.png)

This appeared to happen in the UX layer, as no network traffic was seen.

### Reproduction

On an instance without Jira or GitHub issue tracking is enabled.

- Go to configuration -> settings
- Open up either Jira Issue Tracking or GitHub Issue Tracking
- Change "Is Enabled" from false to true (or change any setting)
- Click save.

### Error and Stacktrace

```shell
See what happened
```

### Workaround

Write an API script to save Issue Tracking settings.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.3438 |
| 2023.1+ | _all releases_ |
