### ISSUE TITLE
Invalid OCL causes branch switcher to be disabled

### ISSUE THREAD

**Issue by acodrington** [OctopusDeploy/Issues#7809]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking customers, workaround is possible (but clunky)

### Version

2022.4.1372-hotfix.1656

### Latest Version

I could reproduce the problem in the latest build

### What happened?

An error is displayed in the UI when the currently selected branch/git ref has invalid OCL. However, this error also disables the branch switcher.

Disabling the branch switcher when processing invalid OCL means that the user cannot switch to another branch which has valid OCL.

I would expect that the branch switcher remains enabled with invalid OCL errors, and is only disabled upon _connection_ errors to the git repo.

![image (3)](https://user-images.githubusercontent.com/277700/192728552-148b8c2e-8319-4ed6-81ff-d4be1b6a76e2.png)

### Reproduction

1. Create a CaC project
2. Create a non-default Channel
3. Add a step/action (anything will do) on the default branch
4. Create and switch to a new branch
5. Add/edit a step and set **Conditions** -> **Channels** to the Channel created in (2)
6. Delete the Channel created in (2)
7. Navigate to the deployment process page
8. 💥 

### More Information

An internal ticket was created when this bug was initially reported internally, and can be found [here](https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/599).

### Workaround

Fixing the OCL manually (i.e. Editing OCL and pushing new version to git repo)

**Comment by acodrington** [comment]
Fixed in this [pull request](https://github.com/OctopusDeploy/OctopusDeploy/pull/13990).

**Comment by YuKitsune** [comment]
Release note: Fixed git ref selector disabling with invalid OCL.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.3455 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.3455 |
| 2023.1+ | _all releases_ |
