### ISSUE TITLE
Make `PUT /dashboardconfiguration` restore default settings when called with no request payload

### ISSUE THREAD

**Issue by long-sean** [OctopusDeploy/Issues#7833]
# Prerequisites

- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this feature request
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have added the kind/enhancement label

# The enhancement

Change the `PUT /dashboardconfiguration` response contract by not returning an error message for requests without a payload/body

## What is the problem this solves or benefit it gives

 - More consistent endpoint behaviour
 - Default settings can be restored by a request with an empty request body

## Proposed solution

The current validation which returns a "No request body" error message will not be ported over to ASP when this endpoint is converted during **project-nancyfx-migration**

**Comment by long-sean** [comment]
Release Note: Make `PUT /dashboardconfiguration` restore default settings when called with no request payload instead of returning a "*No request body*" error message

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.4586 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.4586 |
| 2023.1+ | _all releases_ |
