### ISSUE TITLE
In progress task icons don't spin when a system has reduced animations

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#7842]
### Severity

Cosmetic

### Version

2022.3

### What happened?

Users that have [configured their system to minimize the amount of non-essential motion it uses](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences) don't see animations for in progress task icons.

### Reproduction

- Disable non-essential motion in an appropriate way for your system and browser (see https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences)
- View an in progress task

You'll see that the task icon does not animate, while it did animate in 2022.2.

### More Information

We believe this resulted from an upgrade to our embedded font-awesome library, which now [respects](https://fontawesome.com/docs/web/style/animate#accessibility) the [`prefers-reduced-motion` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences).

### Workaround

Configure your system so that it [does not prefer reduce motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences).

**Comment by TomPeters** [comment]
We are investigating our next steps here. For example:
- Should we prevent animation of this icon for users that have reduced animations configured? Or does it still make sense to animation this icon?
- Is there enough information without the animation to determine if the task is in progress?
- Are there alternative ways we can indicate that the task is in progress without animation?
- More generally: What is our approach to dealing with animations and accessibility?

If this was an unexpected change for you (for example, if you have the reduced animation option configured for your system but were expecting to see task icon animations; or if you didn't know you had the reduced animation option configured), then we would like to hear from you! Please comment on this issue with your experience.

**Comment by TomPeters** [comment]
[unconfirmed] I _think_ that reduced animations are enabled by default on Windows Server 2019. Anyone that install octopus server on Windows Server 2019, then tries to verify or use the installation from the same machine might unexpectedly see no animations.

**Comment by Clare-Octopus** [comment]
Initial ticket - https://help.octopus.com/t/fontawesome-spinners-dont-spin-in-2022-3/28394/10

**Comment by Katy-Octopus** [comment]
The design team is currently working on a fallback state for when reduce motion is turned on which will be part of a wider icon update that is coming in the future.

**Comment by Katy-Octopus** [comment]
The design team is currently working on a fallback state for when reduce motion is turned on which will be part of a wider icon update that is coming in the future.
