### ISSUE TITLE
117 instances in the West US 2 region experienced an 80-second outage

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#7843]
### Team

- [X] I've assigned a team label to this issue

### Severity

117 Octopus Cloud customer instances experienced a brief <2min outage without prior warning

### Version

2022.4

### What happened?

During a Placement and Load Balancing (PLB) event at Azure, a large number of Octopus Cloud instances can experience a brief outage. This can occur outside of maintenance windows, and without warning, potentially resulting in failed deployments.
The issue was first described here on our Status page - https://status.octopus.com/incidents/qstr2cfjvckq
We're currently:
- monitoring this scenario, so that we can advise customers of recurrences (if any) via [[status.octopus.com](http://status.octopus.com/)](https://status.octopus.com/)
- following up with Microsoft for details on why this 80-second outage occurred, and whether it's like to reoccur
- improving our cloud platform's resilience to brief, unexpected Azure outages

### Reproduction

[Slack thread](https://octopusdeploy.slack.com/archives/C044KDNAACS/p1665443188262949)

**Comment by alxmitch** [comment]
We have improved Octopus Cloud monitoring of brief unexpected outages due to such Azure events. We have also improved Octopus Cloud instances' recovery time, minimizing the impact of these events.
