### ISSUE TITLE
Update variable snapshot does not provide any success indicator

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7845]
# The enhancement

## What is the problem this solves or benefit it gives
When you update the variable snapshot of a release/runbook run there is no indicator that the action succeeded or failed.

## Proposed solution
A simple solution would be to add a toaster popup.

## Links

Internal discussion: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1665612941188019

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.5661 |

**Comment by samdanae-octopus** [comment]
Release Note: The Deployment History section will now be refreshed when the variables are updated for a Release

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.5661 |
| 2023.2+ | _all releases_ |
