### ISSUE TITLE
Add support for container name variables in "Deploy Kubernetes containers" step template

### ISSUE THREAD

**Issue by mik-ky** [OctopusDeploy/Issues#7850]
In our "Deploy Kubernetes containers" step, the container name field does not support variable substitution.

Upon saving after modifying the resource YAML directly to attempt a variable substitution, the following error is produced.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/97423717/196300707-5cbbf409-aef5-45ac-8307-823c52127556.png">

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have added the kind/enhancement label

# The enhancement

## What is the problem this solves or benefit it gives
Users can easily identify containers for debugging purposes. At the moment, they all have the same name and a random guid attached to it, making it difficult to pin point and search for logs. The use of variables would allow users to easily manage this.

## Proposed solution
Support variable substitution for container names.

## Workarounds
Workaround is to use Deploy raw Kubernetes YAML over Deploy Kubernetes containers step.

## Links

Detail in more threads: [here](https://help.octopus.com/t/custom-names-for-containers-deployed-to-kubernetes/27960), [here](https://help.octopus.com/t/support-for-variables-in-kubernetes-container-names/28440/4) and, [uservoice](https://octopusdeploy.uservoice.com/forums/170787-product-feedback/suggestions/44891890-container-image-name-variables)

**Comment by NickJosevski** [comment]
See improvements in Kubernetes deployments made in 2024: https://octopus.com/docs/kubernetes

Closing this issue as no longer relevant.
