### ISSUE TITLE
Tentacle Upgrades failing with FileNotFoundException

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7857]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.3.10640

### What happened?

Tentacle upgrade is failing

### Reproduction

Upgrade a Tentacle

### More Information

Internal: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1666100384773889

**Comment by N-lson** [comment]
Release Note: Disable new Tentacle upgrade flow

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10674 |
| 2022.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10674 |
| 2022.4 | 2022.4.5988 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10674 |
| 2022.4 | 2022.4.5988 |
| 2023.1+ | _all releases_ |
