### ISSUE TITLE
Runbook publish status not reflected immediately after publish

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7862]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

See repro for more details.

### Reproduction

For a runbook:
1. Make changes
2. Click PUBLISH text
3. Click green PUBLISH button >> while loading page, this button changes to Publishing...
4. Under “Run history” you see [Runbook Name] (Snapshot [#]) in [Project Name] was published >> however the GUI doesn’t show the green published tag, and the text PUBLISH remains next to the RUN button
5. If you refresh the page, then the green Published tag appears, and the text PUBLISH is no longer visible next to the RUN button

### More Information

See https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1666294858590099 (internal)

**Comment by samdanae-octopus** [comment]
Fixed with https://github.com/OctopusDeploy/OctopusDeploy/pull/15145

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.744 |
| 2023.2+ | _all releases_ |
