### ISSUE TITLE
Task incorrectly reporting earlier versions of package on tentacle

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7881]
### Team

- [X] I've assigned a team label to this issue

### Severity

Confusing logs

### Version

any

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a package is required by a task, the logs may report the package already exists, e.g.
> Found 1 earlier version of My.Package on this Tentacle

which could then be followed by 
>Found no locally cached versions of My.Package so we can't perform a delta upload, entire package will be uploaded.

Looks like Calamari takes an argument of [exactMatch=](https://github.com/octopusdeploy/calamari/blob/master/source/Calamari/Commands/FindPackageCommand.cs#L41) but Server invokes it with [exactMatchOnly](https://github.com/OctopusDeploy/OctopusDeploy/blob/86fabd9eb6e0445939cda936af1549342213c866/source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/PackageAcquisitionExecutionHandlers.cs#L62).

### Reproduction

Speculative: 
- Make sure the package exists on tentacle.
- Run a task that references the same package.
- Depending on whether the package cache has been cleaned up, it may lead to the confusing log messages

### More Information

[sc-29599](https://app.shortcut.com/octopusdeploy/story/29599/calamari-invoked-with-wrong-argument-exactmatchonly-instead-of-exactmatch)

[slack](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1666872316221829)

**Comment by DavidDeSloovere** [comment]
It's been a few month since I reported this issue. I understand this is not your highest priority, but we and other customer would benefit a lot from a fix for this.

**Comment by DavidDeSloovere** [comment]
It's been a few month since I reported this issue. I understand this is not your highest priority, but we and other customers would benefit a lot from a fix for this.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.9410 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.9410 |
| 2023.2+ | _all releases_ |
