### ISSUE TITLE
Clicking "Run" after modifying a Runbook process without saving and then accepting the changes makes the "Run" button vanish.

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#7894]
### Team

- [X] I've assigned a team label to this issue

### Severity

UI Bug

### Version

2022.3.10723

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When editing a Runbook process and wishing to immediately run the new process, clicking on the "run" button prompts you to either save or discard the changes you've made.
Once accepting to save those changes, the "run" button vanishes from the User Interface until a refresh is done.

### Reproduction

1. Create a runbook
2. Add a process step the runbook and save the process.
3. Make an adjustment to the process and click "Run" without saving.
4. Answer the prompt by saving the new process.
5. Observe the "Run" button is no longer visible.

### Workaround

The run button re-appears once the page has refreshed.

**Comment by IsaacCalligeros95** [comment]
Closed in https://github.com/OctopusDeploy/OctopusDeploy/pull/15117.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10750 |
| 2022.4 | 2022.4.8113 |
| 2023.1 | 2023.1.685 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10750 |
| 2022.4 | 2022.4.8113 |
| 2023.1 | 2023.1.685 |
| 2023.2+ | _all releases_ |
