### ISSUE TITLE
ServerTaskStartedDomainEvent not published for deployment tasks.

### ISSUE THREAD

**Issue by gb-8** [OctopusDeploy/Issues#7897]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking customers.

### Version

master

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The ServerTaskStartedDomainEvent is not published for deployment tasks.

The new dynamic environments overview (not shipped to the public yet) relies on this event to update the dashboard, and so currently deployments go straight from queued to complete.

I think the problem is that TaskQueue is using a raw relational store to create a transaction, and committing directly, rather than using UnitOfWork which would handle the publishing of domain events.

### Reproduction

Repro case:
 
Set breakpoints on these lines:
 - https://github.com/OctopusDeploy/OctopusDeploy/blob/fd979669dd79141cd75f2becd200192a79ec8be5/source/Octopus.Core/Model/ServerTasks/ServerTask.cs#L271
 - https://github.com/OctopusDeploy/OctopusDeploy/blob/fd979669dd79141cd75f2becd200192a79ec8be5/source/Octopus.Core/Model/ServerTasks/ServerTaskStateDomainEventMapper.cs#L46
2. Start a deployment.
3. Observe that the first breakpoint is hit, but the second is not.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4069 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4069 |
| 2023.2+ | _all releases_ |
