### ISSUE TITLE
Cancelled Tasks (e.g. a deployment) completes but the Task is never marked as completed and stays in the cancelling state with SQL Error 1222.

### ISSUE THREAD

**Issue by LukeButters** [OctopusDeploy/Issues#7921]
### Team

- [X] I've assigned a team label to this issue

### Version

2022.3

### What happened?

Cancelled tasks appear to stay in state `cancelling` forever despite running all steps (likely caused by  https://github.com/OctopusDeploy/Issues/issues/7920) or running all steps it will ever run because the `cancel` stopped further steps from being executed. 

### Reproduction

unkown.

### Error and Stacktrace

```shell
The ServerTask log contains a message like `SQL Error 1222 - Lock request time out period exceeded.`
```

### Workaround

Restart the octopus server running the task.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10827 |
| 2022.4 | 2022.4.8196 |
| 2023.1 | 2023.1.2211 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10827 |
| 2022.4 | 2022.4.8196 |
| 2023.1 | 2023.1.2211 |
| 2023.2+ | _all releases_ |
