### ISSUE TITLE
Hanging SFTP file operations prevent a user successfully canceling a task

### ISSUE THREAD

**Issue by matthew-james-octopus** [OctopusDeploy/Issues#7931]
### Team

- [X] I've assigned a team label to this issue

### Severity

This has been reported internally only.

### Version

Octopus Server, at least 2019.9.10 onwards

### Latest Version

I could reproduce the problem in the latest build

### What happened?

* I have an SSH tentacle worker that will block / hang on file operations
* I have a process with a step that will run a bash script on a Linux SSH worker
* I run the process
* The bash script step's task hangs when trying to upload a file to the Linux SSH worker in an SFTP operation (see related issue #6445)
* I attempt to 'cancel' the hanging task
* Canceling then hangs indefinitely, preventing me from canceling the task successfully

I expected the task to cancel successfully within an acceptable period of time, for example ~5 seconds.

### Reproduction

I'm able to reproduce this locally when following the steps in the bug's description when using a TCP 'port forwarder' between Octopus Server and an SSH tentacle. The custom 'port forwarder' sits behind a load balancer and, when enough bytes have been sent from Server to the tentacle to detect a file transfer, tentacle to Server messages are blocked.

### Workaround

If the SFTP sessions on the SSH tentacle are killed, then the task will fail, exiting the hanging state.

**Comment by matthew-james-octopus** [comment]
I've confirmed that a 'file download' SFTP operation has the same issue. If a script artifact has started downloading and the operation hangs, the same behavior described in the bug occurs. Since this happens for the same reason, the fix for this will cover canceling a task that's hanging during either upload or download operations.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10847 |
| 2022.4 | _tbc_ |
| 2023.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10847 |
| 2022.4 | _tbc_ |
| 2023.1 | 2023.1.3502 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10847 |
| 2022.4 | 2022.4.8228 |
| 2023.1 | 2023.1.3502 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.10847 |
| 2022.4 | 2022.4.8228 |
| 2023.1 | 2023.1.3502 |
| 2023.2+ | _all releases_ |
