### ISSUE TITLE
AWS S3 Bucket Feed doesn't show in feed selection dropdown in Deploy a Package steps

### ISSUE THREAD

**Issue by dan-close** [OctopusDeploy/Issues#7943]
### Team

- [X] I've assigned a team label to this issue

### Severity

2 customers reported

### Version

2022.4.8167

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The AWS S3 Bucket Feed type does not show in the Package Feed selection dropdown in Deploy a Package steps.

### Reproduction

- Create an AWS S3 Bucket Feed in External Feeds.
- Add a Deploy a Package step to a project.
- Select the Package Feed dropdown in Package Details and note the S3 feed isn't shown as an option.

### More Information

[Internal Ticket](https://octopus.zendesk.com/agent/tickets/99073)
[Internal Discussion](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1668458342719489)

### Workaround

Manually bind the Feed ID of the S3 Bucket Feed in the Package Feed selection.

![image](https://user-images.githubusercontent.com/97460762/205077585-82fc87d6-1751-4adc-b371-2e883c28565e.png)
![image](https://user-images.githubusercontent.com/97460762/205077726-db22c472-bea4-45e5-9424-63f3d28cbac6.png)

**Comment by Clare-Octopus** [comment]
Another user having this issue (internal link) - https://octopus.zendesk.com/agent/tickets/104599

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.8805 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.8802 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.8802 |
| 2023.2+ | _all releases_ |
