### ISSUE TITLE
Calamari - Structured Variable Replacement - Allow For Replacing Each Item In Array

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7945]
# The enhancement
When using the Structured Variable Replacement feature to replace array values, a single value or the entire array is able to be replaced, however it is not possible to replace all values in an array of an unknown length. 

## What is the problem this solves or benefit it gives
This allows for users to define more complex variable replacements with less manual scripting. Currently users are unable to easily replace values for arrays of unknown length.

## Proposed solution
Allow for the `*` syntax to be used which will allow for looping over all values in an array

E.g.
`
foo:bar:*:url
`

## Workarounds
Requires manually parsing the file to confirm the length of the array to create variables for each index. 

## Links
[Discourse](https://help.octopus.com/t/json-configuration-variables/28588)
[Slack](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1670207338912779)
[Calamari - JsonUpdateMap](https://github.com/OctopusDeploy/Calamari/blob/1e9d53ba7dfc49e0828c6722133715bf1d440231/source/Calamari.Common/Features/StructuredVariables/JsonUpdateMap.cs)

**Comment by rdavisunr** [comment]
Specifically, I would like to be able to process JSON such as this:

```json
{
    "Name": "DeploymentServers",
    "Servers": [{
            "Name": "Server-One",
            "CpuCount": 2,
            "Image": ""
        }, {
            "Name": "Server-Two",
            "CpuCount": 4,
            "Image": ""
        }
    ]
}
```

In this case, I'd like to be able to update a value in **all** the objects in the Servers collection that have an Image key.

As shown above, a syntax like `Server:*:Image` seems natural.

**Comment by NickJosevski** [comment]
~2 years in backlogs, marking as [closed/wontfix]
