### ISSUE TITLE
Unable to configure Repository Access Tokens on a Config As Code project to authenticate with a BitBucket Cloud Repository

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7949]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking any customer wanting to use Repository Access Tokens with BitBucket Cloud

### Version

2022.4.8211, 2022.3.10807

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A customer [here](https://octopus.zendesk.com/agent/tickets/102870) (internal link) wants to use a [Repository Access Token](https://support.atlassian.com/bitbucket-cloud/docs/using-access-tokens/) (RAT) to setup a BitBucket Cloud repository link for use with their Config as Code project. Due to company policy, they cannot use a PAT or username/password as they are not allowed to use shared or service accounts for their repositories.

When trying to input the RAT into Octopus I get this error:

![image](https://user-images.githubusercontent.com/92790462/205921694-b52cf22d-b698-4b60-9586-2de58d6b6337.png)

### Reproduction

1. Access a BitBucketCloud repository and create a new repository.
2. [Create a RAT ](https://support.atlassian.com/bitbucket-cloud/docs/create-a-repository-access-token/)for that repository and give it Full Control (for testing) 
3. Go into Octopus and create a new project and convert it to Config As Code.
4. Enter the BitBucket Cloud details and enter the RAT into the 'Password or Personal Access Token' field.
5. Save and test the connection.
6. See error message for incorrect login credentials.

Example screenshot of BitBucket Cloud account settings:

![image](https://user-images.githubusercontent.com/92790462/205923103-70663d95-f672-442c-b331-921520bb1a76.png)

### Error and Stacktrace

```shell
We were unable to connect to your remote repository (Login failed due to incorrect login credentials or method. If you are unsure of which login details or login method to use, visit: https://support.atlassian.com/bitbucket-cloud/docs/log-into-or-connect-to-bitbucket-cloud/ ). Please check the URL, default branch name and authentication details.
```

### More Information

[Slack channel](https://octopusdeploy.slack.com/archives/C01AJE4K3T2/p1670260983217499 ) for this (internal) 

### Workaround

None at the moment, customers will need to use username/password or PAT.

**Comment by dylanlerch** [comment]
This should work in recent version of Octopus, however you will need to set the username to `x-token-auth` when configuring the username and password authentication details.

## BitBucket Token settings
When configuring the token, ensure that it is configured Read and Write permissions for the repository.

![Screenshot of BitBucket Create Repository Access Token modal with Read and Write checkboxes under the Repositories header selected and all other checkboxes unselected](https://user-images.githubusercontent.com/4549037/213579697-6be99ff7-67f2-4f70-ae05-217c3294dad2.png)

## Octopus settings
When configuring the token, ensure that the username is set to `x-token-auth`. From my testing, if the username is set to anything other than this value, authentication will fail.

<img width="1301" alt="Screenshot of Octopus Version Control Settings page with Authentication section expanded. Username/password auth method is selected, the Username input field is highlighted with a bold red box, and contains the value x-token-auth" src="https://user-images.githubusercontent.com/4549037/213579895-c8151509-bbd4-404b-9d38-4b97e9884849.png">

**Comment by chounry** [comment]
hi, @dylanlerch. After doing that there's a different error. Here's a screenshot:
![Screen Shot 2023-03-03 at 4 54 31 PM](https://user-images.githubusercontent.com/29001338/222689825-b2e944f4-fd5b-4fcc-bd6b-72f3a9d87f86.png)
