### ISSUE TITLE
Deleted deployments show a blank page instead of an error

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#7960]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low

### Version

Looks to have been around for a good while

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Looks like clicking on a deployment that has been deleted (most likely by the retention policy)  shows a blank page.

![image](https://user-images.githubusercontent.com/373389/208344429-315fc4e1-19cc-477d-a934-6a65b9c2c8fd.png)

### Reproduction

Click on a link like https://example.octopus.app/app#/Spaces-126/deployments/Deployments-265726, and it shows a blank page.

It should show an error message.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4818 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.4818 |
| 2023.2+ | _all releases_ |
