### ISSUE TITLE
Minor UI - Deploy CloudFormation Step Template - Configuring S3 Source Gives "Template Source Not Specified"

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7970]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not Blocking - Minor UI

### Version

2022.4.8241

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When configuring a Deploy CloudFormation Step Template to source from an S3 bucket, the UI indicates wrongly that no source has been configured

### Reproduction

Configure CloudFormation Step Template to source from an S3 bucket
Collapse Template Source Object
See UI Indicate "Template Source Not Specified"

### More Information

<img width="725" alt="Screenshot 2023-01-05 at 13 57 04" src="https://user-images.githubusercontent.com/78527975/210708076-51d3fafc-8d71-4f9b-9e50-07f1e02fe6a9.png">
<img width="602" alt="Screenshot 2023-01-05 at 15 27 32" src="https://user-images.githubusercontent.com/78527975/210708083-0f279f50-7d0c-4fd6-85f3-4d8f6401f550.png">

### Workaround

N/A - Minor UI issue only, source is configured correctly

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.8845 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.8845 |
| 2023.2+ | _all releases_ |
