### ISSUE TITLE
Octopus does not deploy to old versions of Tentacle

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8002]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocks customers on older versions of Tentacle

### Version

2022.4

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When attempting to deploy:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/171197/214173287-61741971-f745-4723-87bb-8484ea44a829.png">

```
One or more machines in the selected environment are running outdated versions of the Tentacle agent, and they must be upgraded before deployment can proceed. The following machines need to be upgraded: EC2AMAZ-8EM8NJC-1 Once you have corrected these problems you can try again. If the problem is related to a variable you will need to update the variables for this release or recreate the release for the changes to take effect. If the problem is related to the deployment process you will need to create a new release for the changes to take effect.
```

### Reproduction

Attempt to deploy a release to a Tentacle that is a major version behind the current Tentacle version.

### More Information

Introduced in https://github.com/OctopusDeploy/OctopusDeploy/pull/13557

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.7558 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8373 |
| 2023.1 | 2023.1.7558 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8373 |
| 2023.1 | 2023.1.7558 |
| 2023.2+ | _all releases_ |

**Comment by veochen-octopus** [comment]
This was fixed again in
- `2023.1.9879`+
- `2023.2.9032`+
- and all subsequent versions

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8373 |
| 2023.1 | 2023.1.9879 |
| 2023.2 | 2023.2.9032 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8373 |
| 2023.1 | 2023.1.9879 |
| 2023.2 | 2023.2.9032 |
| 2023.3+ | _all releases_ |
