### ISSUE TITLE
Octopus.com keeps throwing a 404 on oauth2 connected logins

### ISSUE THREAD

**Issue by buvinghausen** [OctopusDeploy/Issues#8007]
https://octopus.com/oauth2/authorize?client_id=redacted&scope=openid%20profile%20email&response_type=code+id_token&redirect_uri=https://redacted.octopus.app/api/users/authenticatedToken/OctopusID&state=%7b%22RedirectAfterLoginTo%22%3a%22%2fapp%23%2f%22%2c%22UsingSecureConnection%22%3atrue%7d&nonce=duTY2bxPZiJzUP1rQuy9A

When it does come online I usually get an error message

{
  "ErrorMessage": "There was a problem with your request.",
  "Errors": [
    "User login failed: Missing State Hash Cookie. As a security precaution, Octopus ensures the state object returned from the external identity provider matches what it expected. In this case the Cookie containing the SHA256 hash of the state object is missing from the request."
  ],
  "ParsedHelpLinks": [],
  "Details": {}
}

This is making getting code deployed a real nightmare all day today.

**Comment by patrick-smergut-octopus** [comment]
Unfortunately, we are currently experiencing an outage with Octopus.com and our engineers are working to resolve the underlying issue. You can follow the status of the outage at [status.octopus.com](http://status.octopus.com/) and we will continue to post updates there. We apologize for the inconvenience.

**Comment by buvinghausen** [comment]
Thanks for the update @patrick-smergut-octopus it does seem to be working today.
