### ISSUE TITLE
Deploy an Azure Web App (Web Deploy) step fails when run in the Worker Tools image

### ISSUE THREAD

**Issue by mjhilton** [OctopusDeploy/Issues#8012]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking deployments, no workaround

### Version

Calamari 24.2.0 or  25.3.0 (in Server 2022.3.10978 to 2022.3.11011; 2022.4.8361 to 2022.4.8377; and 2023.1.7463 to 2023.1.7626)

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the Deploy an Azure Web App (Web Deploy) step is run inside the `octopusdeploy/worker-tools:windows.ltsc2019` worker tools image, the step fails with an error code but no description of the problem

### Reproduction

1. Install a version of Octopus Server that ships with an affected Calamari version
2. Create a deployment process with an Azure Web App target using the Deploy an Azure Web App (Web Deploy) step (note, not the newer Deploy an Azure App Service step)
3. Run the deployment

**Expected**: Deployment succeeds
**Actual**: Deployment fails

### Error and Stacktrace

```shell
22:07:53   Verbose  |       docker run --entrypoint='' --rm
22:07:53   Verbose  |       --env TentacleHome= C:\Octopus\Tentacle
22:07:53   Verbose  |       -w C:\Octopus\Tentacle\Work\20230126220752-4887247-1573
22:07:53   Verbose  |       -v C:\Octopus\Tentacle\Work\20230126220752-4887247-1573:C:\Octopus\Tentacle\Work\20230126220752-4887247-1573
22:07:53   Verbose  |       -v C:\Octopus\Tentacle:C:\Octopus\Tentacle
22:07:53   Verbose  |       index.docker.io/octopusdeploy/worker-tools:windows.ltsc2019
22:07:57   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Tentacle\Work\20230126220752-4887247-1573 exited with code -2146232576
22:07:57   Verbose  |       Updating manifest with output variables
22:07:57   Verbose  |       Updating manifest with action evaluated variables
22:07:57   Fatal    |       The remote script failed with exit code -2146232576
```

### More Information

The affected Calamari versions contained an upgrade of .NET Framework from 4.5.2 to 4.8. 

The Worker Tools must be missing something that the updated .NET Framework requires to run. 

The step runs fine when executed directly on the worker using the bundled tools.

**Comment by mjhilton** [comment]
Release Note: Fixed an issue where running the Deploy an Azure Web App (Web Deploy) step would fail when running in the Worker Tools

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.11011 |
| 2022.4 | _tbc_ |
| 2023.1 | 2023.1.7772 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.11011 |
| 2022.4 | 2022.4.8394 |
| 2023.1 | 2023.1.7772 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.11011 |
| 2022.4 | 2022.4.8394 |
| 2023.1 | 2023.1.7772 |
| 2023.2+ | _all releases_ |
