### ISSUE TITLE
Error when using microsoft AD login

### ISSUE THREAD

**Issue by shakamus** [OctopusDeploy/Issues#8028]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low

### Version

2022.4.8397

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Recently i configured my octopus instance to authenticate against Azure AD with the next authentication setup:

![image](https://user-images.githubusercontent.com/1176404/217522920-48e8699b-cc3b-4a4e-9bd5-fecf84d8b252.png)

After that i tried to login with Microsoft:

![image](https://user-images.githubusercontent.com/1176404/217523126-7baccf1b-41a3-47a4-8f1a-621bf547464c.png)

When i click the button i see this requests in the developer toolbar:

![image](https://user-images.githubusercontent.com/1176404/217523510-a711bd92-09b5-4ee7-a9db-0b816d1ac423.png)

Here is the request to adfs:

> https://xxxxxxx.my-company.com/adfs/oauth2/authorize/?client_id=9xxxxxxxxxxxxxxxxxxxxxxxx9&scope=openid%20profile%20email&response_type=code&redirect_uri=https://octopus.my-company.com/api/users/authenticatedToken/AzureAD&state=%7b%22RequestId%22%3a%22eea22e66-e780-421c-866d-a5c0431262bb%22%2c%22RedirectAfterLoginTo%22%3a%22%2fapp%23%2f%22%2c%22UsingSecureConnection%22%3atrue%7d&code_challenge=I2UtzmNXuKON5A1Jj5tcpqINYyW-uNBZIv_iQpTkanM&code_challenge_method=S256

![image](https://user-images.githubusercontent.com/1176404/217524402-6a48eb37-2fe1-490a-b861-95da93dddbc8.png)

Then, the adfs server answer me with this request to my octopus instance:

> https://octopus.my-company.com/api/users/authenticatedToken/AzureAD?code=the-adfs-code&state=%7B%22RequestId%22:%22eea22e66-e780-421c-866d-a5c0431262bb%22,%22RedirectAfterLoginTo%22:%22/app&client-request-id=d7f7470e-33de-43f4-d42b-0080030c00b7

Then, octopus responds with a 500 status code and the next error message:

```
{
  "ErrorMessage": "Unterminated string. Expected delimiter: \". Path 'RedirectAfterLoginTo', line 1, position 80."
}
```

It seem than the "RedirectAfterLoginTo" containing a "#" is breaking the adfs response.

In a second test i tried to replay the response from adfs modifying the url like that (adding the missing quote and the curly bracket symbol): 

> https://octopus.my-company.com/api/users/authenticatedToken/AzureAD?code=the-adfs-code&state=%7B%22RequestId%22:%22eea22e66-e780-421c-866d-a5c0431262bb%22,%22RedirectAfterLoginTo%22:%22/app"}&client-request-id=d7f7470e-33de-43f4-d42b-0080030c00b7

After that it seems that internally is trying to get the autorization code but octopus is responging with the next error:

> Failed to authenticate user: MSIS9609: The 'redirect_uri' parameter is invalid. No redirect uri with the specified value is registered for the received 'client_id'. 
> The response from the external identity provider contained an error: MSIS9609: The 'redirect_uri' parameter is invalid. No redirect uri with the specified value is registered for the received 'client_id'. 

My octopus instance is running in a docker container with this image: octopusdeploy/octopusdeploy:2022.4

As a proxy/loadbalancer a traefik proxy 2.9 is used to serve the app under the domain "https://octopus.my-company.com/"

How can i solve this problem?

Regards.

### Reproduction

See previous info.

**Comment by SeanStanway-Octopus** [comment]
Hi @shakamus 

Would you be able to email these details to our support desk at support@octopus.com so we can triage this please? This issue board is for Octopus Staff usage only in terms of posting issues. We can investigate this thoroughly via support and then if this is an issue we'll get this raised up to our engineering team who can get this resolved as quickly as possible.

Thanks!
Sean
