### ISSUE TITLE
Environment page times out in the Octopus portal

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8042]
### Team

- [X] I've assigned a team label to this issue

### Version

Lots

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The environment page times out. The API call that times out is `api/Spaces-1/environments/Environments-1/singlyScopedVariableDetails`.

### Reproduction

Create a lot of variables scoped to a single environment. Attempt to view that environment in the portal.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8471 |
| 2023.1 | _tbc_ |
| 2023.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8471 |
| 2023.1 | 2023.1.9605 |
| 2023.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8471 |
| 2023.1 | 2023.1.9605 |
| 2023.2 | 2023.2.1307 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8471 |
| 2023.1 | 2023.1.9605 |
| 2023.2 | 2023.2.1307 |
| 2023.3+ | _all releases_ |
