### ISSUE TITLE
Unique name constraint error when cloning a project

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#8052]
### Severity

Blocking some customers, but simple workaround available

### Version

2023.2.958, 2023.1.*.hotfix

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Unique channel name error when cloning a project.

### Reproduction

Source project with a channel named `Default` but no channels are marked as the default channel.
Clone project.
Will error with `A channel with this name already exists for this project. Please choose a different name.`

### Error and Stacktrace

```shell
A channel with this name already exists for this project. Please choose a different name.
```

### Workaround

The error will not occur if there is a channel in the source project marked as the default channel, or there is no channel called `Default`

[sc-40959]

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.1308 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10235 |
| 2023.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10235 |
| 2023.2 | 2023.2.1308 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10235 |
| 2023.2 | 2023.2.1308 |
| 2023.3+ | _all releases_ |
