### ISSUE TITLE
Creating tenants now requires ProjectEnvironments and TenantTags to be set

### ISSUE THREAD

**Issue by andrewabest** [OctopusDeploy/Issues#8057]
### Severity

Blocking customers, workaround available

### Version

Present from 2023.1.8475

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When creating a tenant via the Octopus API (or via an API consumer like Terraform), you are now forced to specify ProjectEnvironments and TenantTags, whereas previously you were not.

The collections can be empty, but they must be supplied now, whereas before they could be completely omitted.

### Reproduction

POST to `/api/tenants` with the payload `{ "Name": "TestTenant" }`

### Error and Stacktrace

```shell
{
  "ErrorMessage": "There was a problem with your request.",
  "Errors": [
    "The TenantTags field is required.",
    "The ProjectEnvironments field is required."
  ],
  "Details": {
    "TenantTags": "The TenantTags field is required.",
    "ProjectEnvironments": "The ProjectEnvironments field is required."
  }
}
```

### Workaround

Add empty collections for TenantTags and ProjectEnvironments when creating tenants via the API or Terraform.

i.e. `{ "Name": "TestTenant", "TenantTags": [], "ProjectEnvironments": [] }`

**Comment by andrewabest** [comment]
Related to https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/487

**Comment by michaelongso** [comment]
Release Note: Fixed an issue with Tenant creation where ProjectEnvironments and TenantTags are set as required instead of optional
