### ISSUE TITLE
Build Information duplicates data

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#8067]
We currently store build information (commits and changesets) for every package. If a build produces many packages we duplicate the same build information for every package in that build. When creating releases that use those packages a large amount of duplication occurs, exploding the size of the data. This is exacerbated when there are many releases between deployments and/or there are many Tenants.

Instead we should store the build information against the build and link the packages to that.

This is a significant change and will require reworking our integrations and documentation.

**Comment by droyad** [comment]
Related to #8051

**Comment by patrick-smergut-octopus** [comment]
Another occurrence here [internal]: https://octopus.zendesk.com/agent/tickets/173611

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.7747 |
| 2024.3+ | _all releases_ |

**Comment by shaun-od** [comment]
ReleaseNote: Fixed Build Information duplication in a deployment caused by multiple releases containing the same package but not the other duplication scenarios.
