### ISSUE TITLE
Tentacle upgraded to .NET Framework 4.8

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8074]
The Tentacle bundled with the Octopus Server has been upgraded to .NET Framework 4.8.

See the [blog post](https://octopus.com/blog/tentacle-dotnet-version-change) for more details.

**Comment by tothegills** [comment]
Release note: Tentacle on Windows now requires .NET Framework 4.8

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.5560 |
| 2023.2+ | _all releases_ |

**Comment by McAndersDK** [comment]
This is a major issue.
Microsoft have multiply product that are very much tied to one specific version of .net, and they do not work with higher versions of .net.
This update require alle tentacles to be update with .net right?
Why have the windows tentacle not been migrated to .net core/5+ ?
