### ISSUE TITLE
Packages with chained file extensions (.tar.gz) are not being cleaned up from the Package Cache

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8075]
### Severity

Low

### Version

2022.1.*

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The package cache is not cleaning files that have chained extension types i.e. .tar.gz, .tar.z etc. We use the `IFileInfo.Extension.EndsWith()` method which returns .gz or .z in these cases. This is compared to a set of expected file types and as .tar.gz != .gz we don't clear the file from cache.

### Reproduction

Create a package that uses a .tar.gz file type extension and configure Octopus to clear the package cache on subsequent releases. This file will not be cleared.

### Error and Stacktrace

```shell
NA
```

### Workaround

Manually delete these extension types.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8541 |
| 2023.1 | 2023.1.9727 |
| 2023.2 | 2023.2.3289 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8541 |
| 2023.1 | 2023.1.9727 |
| 2023.2 | 2023.2.3289 |
| 2023.3+ | _all releases_ |
