### ISSUE TITLE
Users with the required permissions to clone a project scoped to a specific project group receive a permission warning when cloning a project

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8080]
### Severity

Low

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A user in a team with the required permissions to clone a project scoped to a specific project group shows a warning when trying to clone a project. The project is cloned, however the UI warning and lack of redirect makes it hard to tell the clone has completed. 
![Permission denied warning](https://user-images.githubusercontent.com/101079287/223878746-8abdc0dd-8690-472e-94a9-13ee95c36704.png)

This error throws from the `IAccessChecker`, `AssertCanView` method with "This action requires permission to view the details of projects. At least one of your teams has this permission in a limited scope, but this doesn't cover the project or environment in question." with the reason "Missing permission: ProjectView". 

[sc-42256]

### Reproduction

Create a new user in a team with the following two user roles, scope these to a specific project group. Sign in as the user and try clone a project from that project group, the ProjectView permission warning message should show. The project will still be cloned.
![image (14)](https://user-images.githubusercontent.com/101079287/223878851-08ea8c40-e474-48fc-8a8e-5cf37f64a730.png)
![image (13)](https://user-images.githubusercontent.com/101079287/223878867-0ada5f60-42c5-49aa-a1bd-8570ed4c0a3c.png)

### Error and Stacktrace

```shell
NA
```

### Workaround

Assign the ProjectGroupView permission to the Projects Edit user role. Since this is scoped to the Project Group the user will still only see the that project group.

**Comment by AdamHollow49** [comment]
To add more to this, there are more details specific to this issue that the workaround above doesn't solve.

I was in the middle of creating an issue and noticed this one, so thought best to add to it.

### Description:
```
When restricting permissions scoped by Project Group, if a project that was previously cloned into a different group retains a deployment process, an error is thrown requiring ProjectView permissions.

Removing the ProjectGroup scoping from the permissions allows cloning as expected.
Removing the projects deployment process also allows cloning as expected.
```


### Reproduction:
```
Create two project groups.

Project Group A and Project Group B

Create a project in project Group A titled: Initial Project.
Add a deployment process to this project, a simple deploy a package step is fine.

Clone this project _twice_ to a new project in Group A titled: "Cloned Project A" and a new project in Group B titled: "Cloned Project B".

Create a user role with permissions required to clone a project:

ProjectView
ProjectGroupView
ProjectCreate
ProjectEdit
etc

Create a team and apply this user role to the team, scoping it to Project Group A.

Anyone with _just_ this role will be unable to clone "Cloned Project A" due to "ProjectView" permissions, despite explicit project view permissions.

Once you remove the Project Group scoping from the User Role, the user is able to clone the project.
Deleting the process from the project that you are cloning also allows the project to be cloned.
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10950 |
| 2023.2 | _tbc_ |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10950 |
| 2023.2 | 2023.2.11991 |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10950 |
| 2023.2 | 2023.2.11991 |
| 2023.3 | 2023.3.2151 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10950 |
| 2023.2 | 2023.2.11991 |
| 2023.3 | 2023.3.2151 |
| 2023.4+ | _all releases_ |
