### ISSUE TITLE
Deployment Target Health Check for a Kubernetes Cluster shows warnings due to --short flag deprecation

### ISSUE THREAD

**Issue by mik-ky** [OctopusDeploy/Issues#8082]
### Version

-

### Latest Version

None

### What happened?

From Kubernetes version 1.24+, the `--short` flag is being deprecated, as it will become the default.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#uncategorized-1

### Reproduction

[Internal slack](https://octopusdeploy.slack.com/archives/C04F5HY8JPJ/p1678341252595609)

![image](https://user-images.githubusercontent.com/97423717/224177616-cc11979b-04e8-4b67-bc4f-cd606378ab8c.png)

### More Information

There are scripts within Octopus Server that tries to run version --short, as well as in Calamari.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.3099 |
| 2023.4+ | _all releases_ |

**Comment by johnsimons** [comment]
Release Note: Removed the usage of `--short` flag from kubectl since it has been deprecated

**Comment by tothegills** [comment]
The fix for this issue has been backported to 2023.2.13238
