### ISSUE TITLE
Tenant filtering regression in `2023.1`

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#8088]
### Severity

Non-blocking, queries can return additional data. There is no impact on deployments or runbooks.

### Version

2023.1

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Filtering of tenants across tag sets is not functioning correctly.

The `/tenants` and `/tenants/all` APIs regressed to doing an OR across the provided tenant tags. The correct behavior for the filtering is to do an OR within each tag set and then AND across the tag sets themselves. In other words, a tenant matches if they have 1 or more tag matches within each tagset in the filter.

### Reproduction

Sample data used to reproduce the issue:

**Tags**
Continent/Australia
Continent/NorthAmerica
Ring/Alpha
Ring/Beta

**Tenants**
Tenant A
- Continent/Australia
- Ring/Alpha
- Ring/Main

Tenant B
- Continent/Australia
- Ring/Beta

Tenant C
- Continent/Europe
- Ring/Alpha

**Query filter => should result in tenant(s)**
`/tenants?tags=Continent%2FAustralia,Ring%2FBeta` => B
`/tenants?tags=Continent%2FAustralia,Ring%2FAlpha,Ring%2FBeta` => A, B
`/tenants?tags=Continent%2FAustralia,Ring%2FMain,Ring%2FBeta` => A, B
`/tenants?tags=Continent%2FEurope` => C
`/tenants?tags=Continent%2FEurope,Ring%2FBeta` =>

In testing on `2023.1+` the first of these returns A, B instead of just B

### Workaround

None

**Comment by michaelongso** [comment]
Release Note: Fixed regression on Tenant tags filtering for the endpoints.

**Comment by michaelongso** [comment]
The fix didn't filter tenants with no tags. This scenario is also failing:
`/tenants?tags=Continent%2FEurope => C` (due to multiple tag-sets on tenant-c)

**Comment by SeanStanway-Octopus** [comment]
Hey all, got a customer here ([Internal link](https://octopus.zendesk.com/agent/tickets/113533)) who is experiencing this. Is there a timeline when this will be implemented on cloud instnaces? Thanks.
