### ISSUE TITLE
Modifying a project variable template in a project removes any existing sensitive default values from others

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#8108]
### Severity

One report

### Version

2023.2.3930

### Latest Version

None

### What happened?

If you have a default value set for a sensitive project variable template, any update to another variable template will remove the default sensitive values.

### Reproduction

1. Configure at least 2 project variable templates, one being sensitive with a default value

![image](https://user-images.githubusercontent.com/20388190/229002479-811d6a5c-c73c-4010-96b2-eafe5fc214b4.png)

2. Save a change to the other (change value, add description, etc.) and see the sensitive default value erased

![image](https://user-images.githubusercontent.com/20388190/229002462-63150307-1f51-416e-9215-621057b9c076.png)

### More Information

Report (private): https://octopus.zendesk.com/agent/tickets/113472

**Comment by rickychongjl** [comment]
Hi thanks for lodging this. Can you also please check if the associated tenant variable value gets removed as a side effect of this bug?

**Comment by borland** [comment]
Update from R&D: Have investigated this and determined the bug was introduced in version 2023.2.2070
A fix has been implemented and is in-review. I will notify of the fixed version number when available.
