### ISSUE TITLE
Connectivity checks running indefinitely blocking execution on a deployment target

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8118]
### Severity

This is not blocking, the task can be cancelled but has to be done manually.

### Version

Latest

### Latest Version

I could not reproduce the problem

### What happened?

Customers with hundreds of polling tentacles have reported cases where one tentacle can get stuck on a health check indefinitely until manually cancelled. This has prevented deployment processes completing. This issue has been reported by multiple customers, one with ~500 polling tentacles which has occurred twice over a couple of months.

Internal thread - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1676257279255989

### Reproduction

This was not reproducible with tentacle simulator, running up to ~3000 tentacles, it seems the issue is uncommon and based on this number of tentacles is not likely to be thread exhaustion related. The closest simulation of the scenario is updating the MachineHealthController CheckConnectivity method script to include a sleep.

### Error and Stacktrace

```shell
No Error or stack trace, Tentacle ends in a state with a child PowerShell process which has it's own child conhost process. The .DMP files for this are available internally at https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1680519930435479?thread_ts=1676257279.255989&cid=CNHBHV2BX
```

### More Information

After a lot of investigation no root cause has been found. This fails on connectivity checks running a PowerShell script of "exit 0" (it shouldn't be timing out). These connectivity checks do not contain a scriptIsolationMutexTimeout like other healthchecks and there's also no default timeout on the cancellation token within server. A default timeout will at least cause long running processes to be cancelled, the impact of the scriptIsolationMutexTimeout is harder to determine.

A lot of the code around script execution and health checks has recently been converted to async/await, nothing stands out from these changes but it's possibly related.

### Workaround

These health checks can manually be cancelled.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.9995 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.9995 |
| 2023.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10765 |
| 2023.2 | _tbc_ |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10765 |
| 2023.2 | 2023.2.9995 |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10765 |
| 2023.2 | 2023.2.9995 |
| 2023.3 | 2023.3.1899 |

**Comment by bryanroth** [comment]
Still running into this on v2023.3.2586.

**Comment by ChrisPleasant** [comment]
Experiencing this problem on v2023.2.12868
We have only 116 deployment targets.  Two in particular seem to get stuck more often (the problem isn't random across targets)

**Comment by IsaacCalligeros95** [comment]
Hi @bryanroth and @ChrisPleasant, Sorry for the slow reply, I've been away on leave. Just to confirm for your issues, are these connectivity checks or Health checks? This original fix was specifically targeting connectivity checks, this has now been [ported over to Health Checks](https://github.com/OctopusDeploy/Issues/issues/8250). There's ongoing work to update the task execution pipeline which should resolve the underlying problem here. 

Thanks for raising this and your patience on this issue.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.10765 |
| 2023.2 | 2023.2.9995 |
| 2023.3 | 2023.3.1899 |
| 2023.4+ | _all releases_ |
