### ISSUE TITLE
Step retries

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8123]
# The enhancement

## The Need
Currently, if a deployment has commenced and one of the steps fails the user has to manually intervene to recommence the deployment.  This creates extra work for customers and is counterintuitive to automated and continuous deployment.

## Solution
The ideal outcome for this project would be to provide users with the option to automate the process of retrying steps, where it makes sense, with the goal of reducing the number of failed deployments and improving the confidence users have in Octopus Deploy.

**Comment by tothegills** [comment]
Release note: Steps can be configured to automatically retry when they fail

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.10862 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.10862 |
| 2023.3+ | _all releases_ |
