### ISSUE TITLE
Deprecating Mono support for deployments on SSH Targets

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8146]
# Background
* Mono has long been superseded by dotnetcore as the recommended mechanism for executing deployments on SSH Targets. 
* Support will shortly be removed from Octopus Server in favour of relying on .netcore.
* There are some minor adjustments that Mono users may need to make to their targets to continue using SSH targets after this switch.

[Related Blog Post](https://octopus.com/blog/deprecating-mono)

# Call to Action
Let us know in this thread if you have any questions or concerns about this change. Any and all feedback is welcome.

❓Will the removal of Mono support affect you? 
❓What is preventing you from updating your targets to use .netcore?

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.4160 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.4160 |
| 2024.2+ | _all releases_ |
