### ISSUE TITLE
Provide variables relating to the previous version

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#815]
On the server, when a deployment begins, find the previous successful deployment of this project to this environment, and make information such as:
- The deployment ID
- The release ID
- The release version number

Also do the same thing for the last release (whether it was successful or failed)

Available as variables in the deployment manifest. 

On the Tentacle, when installing a package, use the `DeploymentJournal.xml` file to find information about the previous installed package for that step/project/environment (the retention policy set info should give us enough to determine this). Make those values (such as the package file path, installation destination path, and release number) available. 

This would make it possible to handle scenarios like this:

http://octopus-deploy.tenderapp.com/discussions/questions/2073-new-version-and-rollback-of-previous-installation

Where he could use something like in PreDeploy.ps1:

```
$oldPath = $OctopusParmaters["Octopus.Tentacle.PreviousInstallation.InstalledTo"]
$oldScript = Join-Path $oldPath "Remove.ps1"
if ((test-path $oldScript) -eq $true) {
     . $oldScript
}
```

**Comment by patriklindstrom** [comment]
Did the metadata improve made it yet . I want to access the $OctopusParameters['Octopus.Release.Previous.Number'] for eg production environment. We are creating automated release/installation instructions documentation and have to give the last the rollback version to be used.  I have tried to use $OctopusParameters['Octopus.Deployment.PreviousSuccessful.Id'] but I cant find a way to translate to the version. Also tried $OctopusParameters['Octopus.Tentacle.PreviousInstallation.PackageVersion'] but that does not work either.

**Comment by patriklindstrom** [comment]
We used: $OctopusParameters['Octopus.Release.PreviousForEnvironment.Number'] and that seems to work for us.
