### ISSUE TITLE
Create Deployment page Deployment Preview loads slow when large amount of build information is present 

### ISSUE THREAD

**Issue by paulegradie** [OctopusDeploy/Issues#8151]
The Create Deployment page Deployment Preview loads very slowly when large amounts of build information is present due to large amounts of unnecessary data being returned from the API.

## The Need
Limiting these payload sizes could speed up page load times.

## Solution
A backend-for-frontend can be used to compute counts server-side instead of returning data to the UI for counting. This will speed up payload download time substatially and give a much better user experience.

**Comment by paulegradie** [comment]
Release Note: Introduced page-specific endpoint to improve Deployment Preview load time on Create Deployment page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.11412 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.11412 |
| 2023.3+ | _all releases_ |
