### ISSUE TITLE
CaC - Channel Package Version Rules Aren't Updated When Referenced Step Name Modified 

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#8162]
### Severity

Not Blocking, Workaround Exists

### Version

2021.3.9787

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When renaming a Deployment Step for a Project that has been converted to CaC, the corresponding Channel Version Rule is not updated.

This results in the Channel Package Version Rule no longer applying to that Step and can result the `Force Package Version` UI option to not appear and release creation can fail.

### Reproduction

1. Configure a config as code Project with a Deploy a Package Step
2. Create a Channel Package Version Rule
3. Modify the Deploy a Package Step name
4. See Channel Package Version Rule reference incorrect Step name

### Error and Stacktrace

```shell
The requested package versions for the following steps violate the channel version rules: STEPNAME. Please specify a different package version, channel or provide the `ignoreChannelRules` parameter to override this check.
```

### More Information

Step called UPPERCASE1:
<img width="867" alt="Screenshot 2023-05-26 at 14 15 27" src="https://github.com/OctopusDeploy/Issues/assets/78527975/df7d4885-3d13-4c30-9ede-aeea254799e1">

Channel Version Rule Created:
<img width="1289" alt="Screenshot 2023-05-26 at 14 15 40" src="https://github.com/OctopusDeploy/Issues/assets/78527975/1c5130b7-8008-43fb-a641-3490c6425803">

Step Renamed to lowercase1:
<img width="829" alt="Screenshot 2023-05-26 at 14 16 54" src="https://github.com/OctopusDeploy/Issues/assets/78527975/60e75ed5-5898-4b32-8b20-7d407de5c0eb">

Channel Version Rule isn't Updated but Create a Release has:
<img width="1284" alt="Screenshot 2023-05-26 at 14 17 42" src="https://github.com/OctopusDeploy/Issues/assets/78527975/b8bd59c1-d58a-4688-992d-b9f2d9eda3f8">

Renamed Step can be re-added to the Package Version Rule:
<img width="969" alt="Screenshot 2023-05-26 at 14 21 57" src="https://github.com/OctopusDeploy/Issues/assets/78527975/210ae158-8a43-4495-b8ce-b4350ff9d3df">

### Workaround

Change the Package Version Rule to reference the renamed step or use the CLI to create a release using the `--ignoreChannelRules` flag: [https://octopus.com/docs/octopus-rest-api/octopus-cli/create-release](https://octopus.com/docs/octopus-rest-api/octopus-cli/create-release)

**Comment by zentron** [comment]
This is by design. 
When using version controlled projects, there is no single source of truth in the same way we think about database backed projects.

A release could be created at any point for any branch, tag or commit and so the relationship between git-based resources and database-based resources becomes tenuous.

Even attempting to read and update every branch that could be referencing a step that has its name changed on a channel could, therefore, be pointless if the user creates a release from a previous commit. And we do not want to go making random commits on customer branches.
