### ISSUE TITLE
Upgrade a Helm Chart step - Helm feeds require a trailing slash in the URL if helm repo's index.yaml uses relative URLs

### ISSUE THREAD

**Issue by mik-ky** [OctopusDeploy/Issues#8168]
### Severity

Low

### Version

Earliest tried in v2023.1, but suspect this has been around for a long time.

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When adding a helm feed, if you omit a trailing slash as the feed URL and if the `urls` is relative in `index.yaml` for the helm repository, then the step will fail with a 403. This isn't a problem with feeds that have absolute URLs in their `index.yaml` like `https://charts.helm.sh/stable`.

This is due to how the URLs are being concatenated with helm feeds. Unlike other feeds, we don't do a special logic to deal with no trailing slashes, making it brittle.

### Reproduction

Steps to reproduce:
* Create a feed with url: `https://octopus-sales-public-helm-repo.s3.ap-southeast-2.amazonaws.com/charts`
* Save and test for package `octopub-products-mysql`
* Run a Upgrade a Helm Chart step with the newly created feed for the package `octopub-products-mysql`

### Workaround

Add a trailing slash for a helm feed URL.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.2173 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.2173 |
| 2023.4+ | _all releases_ |
