### ISSUE TITLE
WindowSize is not being respected when Octopus.Action.MaxParallelism set to a higher value

### ISSUE THREAD

**Issue by mik-ky** [OctopusDeploy/Issues#8170]
### Version

Earliest tried 2023.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When configuring a rolling deployment for a step, WindowSize is being ignored if there is a `Octopus.Action.MaxParallelism` set, and is configured to be higher than WindowSize. It should be reading off `MaxParallelism` that is _indexed by action_ from the manifest.

This goes against what is described in our docs: 

> If you include the variable Octopus.Action.MaxParallelism in your Project with a value higher than your Window size set in a rolling deployment, you will find the Octopus.Action.MaxParallelism value is no longer respected. This is expected behavior as Octopus also uses this variable to limit the number of deployment targets on which the rolling deployment step will run concurrently. A warning will also be printed in the Task Log.

### Reproduction

1. Configure a step with a rolling deployment
2. Configure 3 deployment targets
3. Set WindowSize to `1`
4. Set project variable `Octopus.Action.MaxParallelism` to `3`
5. Create a deployment

This will result in 3 deployments happening in parallel.

**Comment by tothegills** [comment]
Variable evaluation gives precedence to project variables over step variables.  To workaround, add values to the `Octopus.Action.MaxParallelism` reflecting the window size you would like, and scope the values to the rolling steps.
