### ISSUE TITLE
Python function get_octopusvariable should return an empty string if the variable does not exist

### ISSUE THREAD

**Issue by mik-ky** [OctopusDeploy/Issues#8175]
### Severity

Low

### Version

Tried in v2023.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Python's `get_octopusvariable` isn't returning an empty string if the variable doesn't exist. Instead, it errors, failing the script.
This is not consistent with the behaviour with `get_octopusvariable` in bash.

Related to https://github.com/OctopusDeploy/Issues/issues/3747

### Reproduction

1. Create a Run a Script step.
2. Select Python as the scripting language, and paste the following:
```
# python script
print("Color from pound-braces #{Color}")
print("Color from get_octopusvariable " + get_octopusvariable("Color"))
```

3. Run the script and verify step fails.

**Comment by mik-ky** [comment]
Release Note: Return empty string instead of failing when executing get_octopusvariable() in a python script

**Comment by mik-ky** [comment]
The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.1477 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.1477 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.1477 |
| 2023.4+ | _all releases_ |
