### ISSUE TITLE
View/delete packages from the built-in package repository

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#818]
Under _Library_, allow a suitably-priviliged user to list packages in the built-in repository, and delete them. Search + select-all should be a reasonable way to present this.

In future we may provide deeper drill-down into package details (e.g. projects using this package and so-on) but this ticket will keep to the basics required for freeing-up space.

**Comment by zuperm4n** [comment]
Would be great to offer some sort of control over the retention of packages too. For example, automatically prune packages marked with `alpha`, `beta` or `rc` after X days.
