### ISSUE TITLE
Looking up a project by slug is slow

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#8184]
[sc-48662]
### Severity

UI and API slowness

### Version

2022.1 onwards

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The API call /api/projects/foo (foo being the slug) takes much longer than the call /api/projects/Projects-1 .

This occurs when there are 1000's of projects.

### Reproduction

Create 5,000 projects
Select one by slug, takes about 500ms
Select one by id, takes about 50ms

### More Information

An instance of #8142

**Comment by tothegills** [comment]
Release note: Improved response time when requesting projects by slug

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11040 |
| 2023.2 | 2023.2.12206 |
| 2023.3 | 2023.3.3099 |
| 2023.4+ | _all releases_ |
