### ISSUE TITLE
Workers leases are not released when a task is cancelled

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8185]
### Version

2023.1.2047 to 2023.2.3196

### Latest Version

The problem does not exist in the latest build

### What happened?

Tasks involving workers can leave stale leases when the task is cancelled.

### Reproduction

- Create a deployment that runs a script on a worker inside a container.
- Run the deployment.
- After the worker has been leased, cancel the deployment.
- Observe that the worker is still leased.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11040 |
| 2023.2 | _tbc_ |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11040 |
| 2023.2 | 2023.2.3196 |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11040 |
| 2023.2 | 2023.2.3196 |
| 2023.3 | 2023.3.3099 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11040 |
| 2023.2 | 2023.2.3196 |
| 2023.3 | 2023.3.3099 |
| 2023.4+ | _all releases_ |
