### ISSUE TITLE
Updating clock icon colour for scheduled runbook triggers

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#8197]
# Background

We are in the process of [uplifting our navigation](https://octopus.com/blog/navigation-uplift) and as part of this process we are also updating our icons to be consistent with our design system. In this particular case, the clock icon colour will slightly change in light mode.

## Before
![image](https://github.com/OctopusDeploy/Issues/assets/6700195/63a56644-ab79-45d1-a5da-5150fa884094)

## After
![image](https://github.com/OctopusDeploy/Issues/assets/6700195/c9f1cd9b-0ca1-4519-8aa2-6642be587c59)

**Comment by shaunmarx** [comment]
Release Note: Changed clock icon colour for scheduled runbook triggers

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.3405 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.3405 |
| 2023.4+ | _all releases_ |
