### ISSUE TITLE
Kubernetes object status check not finishing while all objects are shown as successful

### ISSUE THREAD

**Issue by YihaoOct** [OctopusDeploy/Issues#8206]
### Severity

A few customers are affected, workarounds exist

### Version

This issue is to track the release of a fixed bug. It is fixed as of 2023.3.4068

### Latest Version

Not applicable

### What happened?

When I enable the Kubernetes Object Status Check feature on a "Deploy a Kubernetes Container" step, all the resources listed on the "OBJECT STATUS" tab are deployed successfully, but the status check keeps running rather than completing the deployment. If I also have an execution timeout defined for the step, the execution will timeout eventually.

<img width="1655" alt="Screenshot 2023-06-19 at 2 37 29 PM" src="https://github.com/OctopusDeploy/Issues/assets/97418140/79b232ff-47f5-4f6b-9d8a-7e7b91548668">

Note in this screenshot, all objects are deployed successfully, but the status check keeps running.

### Reproduction

Create a Deploy a Kubernetes Container step, enable the Kubernetes Object Status option (which is enabled by default).

__Make sure at least one of the ConfigMap or Secret section is left empty.__ This is the key of reproducing this issue.

<img width="1227" alt="Screenshot 2023-06-19 at 2 35 46 PM" src="https://github.com/OctopusDeploy/Issues/assets/97418140/45dbec34-8792-4f6c-ad8a-c46a05a8f543">

Create deployment, observe that the deployment does not complete despite all resources are deploy successfully.

### Error and Stacktrace

```shell
When this bug is encountered, we should see task log similar to this:


02:40:13   Verbose  |       Performing resource status checks on the following resources:
02:40:13   Verbose  |       - Secret/octopus-feedcred-feeds-1041 in namespace robe-namespace
02:40:13   Verbose  |       - Deployment/test in namespace robe-namespace
02:40:13   Verbose  |       - Secret/#{Octopus.Action.KubernetesContainers.SecretName}-deployments-463 in namespace robe-namespace
02:40:13   Verbose  |       - ConfigMap/#{Octopus.Action.KubernetesContainers.ConfigMapName}-deployments-463 in namespace robe-namespace
```

Note that there are `#{Octopus.Action.KubernetesContainers.SecretName}` and `#{Octopus.Action.KubernetesContainers.ConfigMapName}` unsubstituted.

### More Information

This bug has already been fixed in https://github.com/OctopusDeploy/Calamari/pull/1065.

It is on its way of being released. The fix should be available after release `2023.3.4068`.

### Workaround

If you are experiencing this bug, you can work around this by manually turn off the "ConfigMap" and "Secret" features that are not used.

On the process configuration page, go "CONFIGURE FEATURES", then unselected the unused "ConfigMap" and "Secret" features.

<img width="1410" alt="Screenshot 2023-06-19 at 2 37 51 PM" src="https://github.com/OctopusDeploy/Issues/assets/97418140/34cc4b75-f61c-4fdb-852e-5785efa6117e">

<img width="954" alt="Screenshot 2023-06-19 at 2 38 01 PM" src="https://github.com/OctopusDeploy/Issues/assets/97418140/fcc04b46-10af-4b6d-828e-2e05df7c7792">

Create another deployment, this time it should work.

<img width="1649" alt="Screenshot 2023-06-19 at 2 46 39 PM" src="https://github.com/OctopusDeploy/Issues/assets/97418140/e47bec44-7701-4896-aec0-6de893118db4">

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.3705 |
| 2023.4+ | _all releases_ |
