### ISSUE TITLE
URLs for Releases may exceed 4000 characters due to many Tenants / Deployments

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#8208]
### Version

2023.2.12209

### Latest Version

None

### What happened?

Users may run into an issue with URL length due to many ServerTasks for Releases from Tenanted deployments. This is affecting the URL length of "/app#/Spaces-1/projects/{projectname}/deployments/releases/{releasename}".

The URLs can exceed 4000 characters, which is may cause network configuration challenges for affected users.

Might be the same as: https://github.com/OctopusDeploy/Issues/issues/5161

### Reproduction

Deploy a Release many times or to many Tenants

1 Deployment x 275 Tenants should be enough.

### More Information

[[Internal Discussion](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1686738514637519)]

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.6811 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.6811 |
| 2024.4+ | _all releases_ |
