### ISSUE TITLE
Improve Tentacle Resiliency for Unreliable Networks (Retry RPC calls to Tentacle)

### ISSUE THREAD

**Issue by nathanwoctopusdeploy** [OctopusDeploy/Issues#8229]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

Deployments to tentacles on flaky networks are prone to failure, this enhancement aims to improve on that by allowing Octopus Server to retry failed communications to tentacle allowing the deployments on flaky networks to succeed.

## The Need

Deployments and Runbook Runs to Tentacles can fail if minor network issues occur while the task runs. This can be particularly problematic when deploying to Tentacles with poor internet connections. This can also be an issue when deploying to 1000s+ of tentacles on relatively stable connections, since chances are the network will fail during one of those deployments.

Currently when a network issue causes a failure, the entire step or deployment needs to be re-run. Rectifying these failed tasks can be time consuming since doing so is typically a manual task. This can become even more time consuming when deployments are not safe to re-run.

The goal is to make communications to Tentacles resilient to intermittent network issues, allowing Octopus Server to re-attempt network communications without re-running steps within a deployment. Since deployments steps are not repeated it should be safe to use this feature on most Deployments and RunBooks.

Intermittent network issues for this ticket are those that last for no more than 10 minutes, although the solution allows for recovering from longer network issues.

## Solution

The solution is to add _Transient Network Error Recovery_ to Octopus allowing it to retry failed communications with tentacle. Octopus Server will retry for the duration specified within the machine policy (under the yet to be released _Transient Network Error Recovery_ section).

When _Transient Network Error Recovery_ is enabled and a network issue occurs while communicating to tentacle, e.g. during a Deployment, Octopus Server will retry communications to Tentacle. Previously the network error would have failed the deployment, if the network is restored in time Octopus Server will be able to continue communications with tentacle to complete the deployment.

The _Transient Network Error Recovery_ feature does not cause Octopus Server to re-run steps within a deployment or re-run the entire deployment. Instead communications to tentacle have been made idempotent and those idempotent communications are retried.

### Impact on Deployment and Runbook Run duration

Retrying failed communications with Tentacle can result in the total deployment time taking longer when a network error occurs due to the extra time spent retrying failed communications. The Deployment/Runbook run duration will only increase if a network error occurs which would have previously failed the deployment. 

#### Interactions with Automatic Step Retries

The existing [Automatic Step Retries](https://octopus.com/blog/step-retries) feature, unlike Transient Network Error Recovery, will rerun the scripts generated by steps, including scenarios where the script itself failed but also scenarios where the script did not fail but the step failed as there was a communication issue between Server and Tentacle. 

If Action Retries and Transient Network Error Recovery are enabled, then it can result in longer deployments over flaky/down networks. Automatic retries for steps will rerun up to 3 times if they fail, while RPC retries will also retry failed communications between Server and Tentacle during the initial Step and Step retries.

For example, on a down network, when RPC retries are configured to retry for 2 minutes, and Automatic retries for steps are enabled, the RPC retries will timeout 3 times = 6mins.

## Getting access

The _Transient Network Error Recovery_ feature is soon to be rolled-out in the Octopus Cloud as an opt-in Early Access feature. If you are interested in trialling this feature sooner, please contact support so that it can be made available on your instance.

The feature is available on your instance if the _Transient Network Error Recovery_ feature is available with the machine policy page.

This feature is expected to be available for on premise customers by the end of this year.

## Enabling and configuration

The _Transient Network Error Recovery_ feature is enabled under the machine policy. This will only be visible on instances that have the feature available.

![image](https://github.com/OctopusDeploy/Issues/assets/7076477/93f518f7-a3a3-4c93-b087-8358046dd923)

**Comment by nathanwoctopusdeploy** [comment]
Release Note: Adds an opt-in feature, ‘Transient Network Error Recovery’, which allows Octopus Server to retry failed communications to Tentacle during Deployments/RunBook Runs for the duration specified in machine policy. This feature is currently only available in Octopus Cloud. OctopusDeploy/Issues/issues/8229

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.8103 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.8103 |
| 2023.4+ | _all releases_ |
