### ISSUE TITLE
Allow multiple tenants to be connected to a project in the same request

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#8244]
# The enhancement
[sc-53099]

## The Need
If you want to connect multiple tenants, you need to connect each one-by-one.

## Solution
Allow selecting multiple tenants in the same dialog.

## Screenshots and Mockups

![image](https://github.com/OctopusDeploy/Issues/assets/11970672/8ec20b59-9917-4a40-a242-ab4456d94960)

_**Note: This will be released as an alpha feature to begin with, and will not be enabled by default.**_

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.8647 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.8647 |
| 2023.4+ | _all releases_ |
