### ISSUE TITLE
Subscriptions not firing when using Event Groups / Categories and adding any Document Type

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#8246]
### Severity

Blocking any customer that wants to use a Subscription with Event Groups / Categories and any Document Type

### Version

2023.2.12868, 2022.3.10723.

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When setting up a subscription with Event Groups / Categories selected and adding any Document Type, the subscription will not run after the triggered event. It will silently queue (not shown in the tasks list) until you remove the Document Type selections in the subscription and save it. The subscription task will then run straight after the save of the subscription without you triggering another event.

Working Subscription filters:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/ede936bc-31e6-4902-92ef-258ede88d814)

Not Working Subscription filters:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/c40855e9-c660-40f5-8953-5724ce001831)

You should see the notification below in your subscription logs (these can be found at `Configuration > Diagnostics > Subscription Logs` in the Octopus UI):

`Notifications need to be sent for subscriptions. This work will now be added to the Octopus task queue to complete (upToEventAutoId:xxxxxx). `

### Reproduction

1. Setup a Subscription with either an Event Group or Event Categories (for this example, we will use the `Deployment Events` Group), set it to run every 1 minute. Save it and deploy a project to an environment. See the subscription is processed on the tasks page.

2. Add any Document Type filter to the subscription we created in Step 1. Save it and re-deploy the same deployment to another environment, see the subscription not be processed in the tasks menu, wait a few minutes and it still won't be processed.

3. Return to the subscription we created, take the Document Type filter off the subscription and save it.

4. Go back to the tasks page and see that subscription has been processed (without us actually deploying anything).

_This proves the subscription event task from Step 2 is silently queued until the Document Type is removed from the filter._

### Error and Stacktrace

```shell
Notifications need to be sent for subscriptions. This work will now be added to the Octopus task queue to complete (upToEventAutoId:xxxxxx).
```

### More Information

This may be related to this GitHub issue but that seems to be slightly different so I have created this new one to track this issue. 
#5463

Slack discussion (internal) with a video of the issue and logs - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1688572102692259

Customer ticket (internal) - https://octopus.zendesk.com/agent/tickets/138670

### Workaround

The only workaround at the moment would be to create two subscriptions, one for your Event Groups / Categories and then another, separate subscription for your Document Type filters.

**Comment by Clare-Octopus** [comment]
https://github.com/OctopusDeploy/Issues/issues/5463 - Potentially related - might be able to close both of them off once we fix this.

**Comment by YuKitsune** [comment]
Release note: Updated the wording of the "Event Filters" section on the Subscription page to better convey the behaviour of event filtering in subscriptions.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.9485 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.9485 |
| 2023.4+ | _all releases_ |
