### ISSUE TITLE
Log .NET Framework during windows healthcheck

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8248]
# Background
With upcoming target deprecations, some earlier systems may run into problems if they are running older versions of .NET Framework.  The data in this log message may help customers or us be aware of what is available on their target system.
It is deliberately verbose at the moment since it will be irrelevant for a majority of users but could provide additional information if required. We might raise its log level if\when we want to make further use of it.

# Results

![image](https://github.com/OctopusDeploy/OctopusDeploy/assets/1830666/cda050e2-5d64-4701-9341-20d9c0d9b592)

![image](https://github.com/OctopusDeploy/OctopusDeploy/assets/1830666/0835ef63-0b59-42dc-bd15-e536748320eb)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.6933 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.6933 |
| 2023.4+ | _all releases_ |
