### ISSUE TITLE
Health checks running indefinitely blocking execution on a deployment target

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#8250]
### Severity

This is not blocking, the task can be cancelled but has to be done manually.

### Version

2023.2.12868

### Latest Version

I could not reproduce the problem

### What happened?

Customers with hundreds of polling tentacles have reported cases where one tentacle can get stuck on a health check indefinitely until manually cancelled. This has prevented deployment processes completing. This issue has been reported by multiple customers.

### Reproduction

Have been unable to reproduce the issue.

### Workaround

These health checks can manually be cancelled.

**Comment by hnrkndrssn** [comment]
Release note: Added a default timeout for machine health checks

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11933 |
| 2023.2 | _tbc_ |
| 2023.3 | 2023.3.8740 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11933 |
| 2023.2 | 2023.2.13111 |
| 2023.3 | 2023.3.8740 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.11933 |
| 2023.2 | 2023.2.13111 |
| 2023.3 | 2023.3.8740 |
| 2023.4+ | _all releases_ |
