### ISSUE TITLE
Provide list of recent changes in an instance

### ISSUE THREAD

**Issue by rain-on** [OctopusDeploy/Issues#8261]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement
When in a cloud instance, the Version number link in the User Account opens a new tab showing a version comparison between my current version, and another version (which happens to be the last LTS version created, though isn't obvious).

It would be great if there was a way to show a list of changes recently introduced to OctopusDeploy, ideally tailored to the instances installation history.

## The Need
Cloud instances upgrade at a fairly regular cadence, and functionality (or the look-and-feel) may change across an upgrade - potentially leaving customers surprised, which is not usually a good thing.

## Solution
A "Release Notes" link is to be added to the Release-Notes menu, this link will open a new tab and show the changes incorporated in each of the last-N installs for this instance - similar to the compare-versions page, but more directed at things that have changed for this instance.

**Comment by rain-on** [comment]
Release Note: Added "Release Notes" item to User menu, which opens new tab showing recent installs and associated chagnes

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.9156 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.9156 |
| 2023.4+ | _all releases_ |
