### ISSUE TITLE
Deprecation warnings  added to health checks & tasks on Windows 2003 Targets & Workers

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8268]
## Windows Server 2003 Deprecation
With pending deprecations for Windows Server 2003, warnings have been added to Octopus Server that will be displayed when a Windows Server 2003 target is detected during a health check or execution task.

### Mitigation
Users wanting this error to go away should upgrade their target or worker to a more recent version of Windows. Further details are available in the related blog post which will be made available shortly.

### Screenshots
**Note The message in these screenshots refer to Windows Server 2008 is for illustrative purposes. The actual change introduced will only currently generate warnings for Windows Server 2008**
![image](https://github.com/OctopusDeploy/Issues/assets/1830666/56fed69a-c588-494a-b7e9-fb042077fc35)

![image](https://github.com/OctopusDeploy/Issues/assets/1830666/23119a05-8390-463b-8268-86a922046333)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.13151 |
| 2023.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.13151 |
| 2023.3 | 2023.3.9913 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.2 | 2023.2.13151 |
| 2023.3 | 2023.3.9913 |
| 2023.4+ | _all releases_ |
