### ISSUE TITLE
Improve performance of the Deployment Template endpoint for large scale tenanted scenarios

### ISSUE THREAD

**Issue by paulegradie** [OctopusDeploy/Issues#8280]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

Improving API response time

## The Need
API performance is a top level concern for Octopus Deploy as we endeaver to support the needs of larger and larger customers. In this issue, we focus on the response time of server when creating deployment templates, which is a critical step when creating deployments in general.

## Solution
This is a complex problem that we'll need to iterate on and approach from multiple angles. One opportunity we identified was to improve the computational efficiency of logic that computes tenant promotions.

## Benchmark improvments
We use internal benchmarks to guage how well we perfom at different scales. The following table demonstrates the performance improvement against our worst performing bechmark tests.

 | DisplayName                 | Median      | Mean          | StdDev       |
 | ---                         | ---         | ---           | ---          | 
 | `Before` TemplateEndpointTest.Get()  | 31_404.4637 ms | 31_761.6498 ms | 1_199.1411 ms | 
 | `After` TemplateEndpointTest.Get() | 5_010.834 ms | 5_158.90896 ms | 271.97866 ms |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.11120 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.11120 |
| 2023.4+ | _all releases_ |

**Comment by paulegradie** [comment]
Release notes: improve performance when compute tenant promotions
