### ISSUE TITLE
Add sourcing from Git Repos to Kubernetes Raw Yaml Step

### ISSUE THREAD

**Issue by scme0** [OctopusDeploy/Issues#8285]
Adding a new feature to allow users to source their yaml from a Git Repository rather than using Inline YAML or using Packages.

**Comment by scme0** [comment]
Release Note: Adding the ability to source YAML from a Git Repository for the Kubernetes Raw YAML Step.

**Comment by scme0** [comment]
Feature enabled by default in https://github.com/OctopusDeploy/OctopusDeploy/pull/19619

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.11207 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.11207 |
| 2023.4+ | _all releases_ |
