### ISSUE TITLE
Make NonInteractive optional

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#830]
When we invoke PowerShell, we set -NonInteractive. 

But sometimes PowerShell insists on prompting, no matter what we set `$ConfirmPreference` to. 

http://octopus-deploy.tenderapp.com/discussions/problems/17369-power-shell-scrips-doent-work-from-octopus

http://octopus-deploy.tenderapp.com/discussions/problems/16549-issue-with-execution-of-octopus-ps-script

Let's make a special variable that allows people to turn this off temporarily so that they can work out why PowerShell is prompting. Yes, it will cause the scripts to hang, but at least we should see the output from the prompt. 

(Tagging this as a bug because it's going to help to troubleshoot some bugs)

**Comment by BurkeyDaTurkey** [comment]
An old one that I'm going back to but I have Octopus 3.2.28 and this OctopusAllowInteractivePowerShell doesn't make any effect during an offline deployment.  Checking the Calamari code I cannot find this, I would expect it to exist in the SpecialVariables.cs in the same way as OctopusPrintVariables applies, for example.
Did this get added?

**Comment by tonyeung** [comment]
Kept on getting this error, for anyone else that runs into this, turns out I didn't set -Recurse on Remove-Item. Had it in my ISV but forgot when I typed it in the deploy step... Full code:

```
$jsFolderName="#{FrontEnd}\js" //#{FrontEnd} is a Octo Deploy variable
If (Test-Path $jsFolderName){
	Remove-Item $jsFolderName -Recurse -ErrorAction SilentlyContinue -Force
}
```

Otherwise, you might want to run your script in the ISV and eliminate any interactive prompts via switches like how I got rid or the recurse prompt by adding the recurse switch

**Comment by nns-bizbrains** [comment]
Where do I set this OctopusAllowInteractivePowerShell  variable? Is it in variables in Octopus? I have tried that but with no change.
