### ISSUE TITLE
Introduce Event Based Deployment History and Runbook Run History Process

### ISSUE THREAD

**Issue by shaun-od** [OctopusDeploy/Issues#8305]
# Prerequisites

- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] My team has started working on this issue
- [X] I have written a descriptive issue title

# The enhancement

## The Need
The current Deployment History and Runbook Run History processes in Octopus run on scheduled stored procedure. This store procedure updates the tables with new data regularly and then does a full update to the table multiple times a day. The full update is causing spikes in database usage when it is running.

## Solution

A new system event-based process is being introduced to allow the updating of the Deployment History and Runbook Run History tables. This will replace the stored procedure based process. 

This change is also adding a number of indexes to the Deployment History and Runbook Run history tables.

**Comment by shaun-od** [comment]
Release Note: Introducing new event-based deployment history and runbook run history processes to replace current stored procedure based processes.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.11948 |
| 2023.4+ | _all releases_ |
