### ISSUE TITLE
Show number of tenants that failed to connect on Project Tenant page.

### ISSUE THREAD

**Issue by shaun-od** [OctopusDeploy/Issues#8313]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need

Bulk connecting Tenants to a project is a background process. The UI shows the progress and the number of successful connections once the process is completed. The UI won't inform the user if any tenants fail to connect.

## Solution

Add a new callout to inform the user the number of failed connections (if any occur) and how to see the error messages. If no errors occurs the current successful callout is shown.

## Screenshots and Mockups

![Screenshot 2023-08-31 at 3 55 18 pm](https://github.com/OctopusDeploy/Issues/assets/88302625/7b732f45-d7cb-4605-84be-04bfbec91833)

**Comment by shaun-od** [comment]
Release Note: Introducing a new error callout to the Project Tenant page if any tenants fail to connect.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.1479 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.1479 |
| 2024.1+ | _all releases_ |
