### ISSUE TITLE
Help Sidebar - In-Product Links are Broken - HTTP 404

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#8324]
### Severity

Not Blocking - Minor UI

### Version

2023.3.12439

### Latest Version

I could not reproduce the problem

### What happened?

When clicking on the link provided in the new Help panel, the links lead to 404 errors.

It looks like the URL's now include the cloud instance url:
```
https://finnd-test.octopus.app/HelpGeneral 
vs
https://oc.to/HelpGeneral
```

### Reproduction

Disable the option `Toggle the Help Sidebar` under Configuration -> Features
Click link from Help Sidebar
See 404 error

### Error and Stacktrace

```shell
{"title":"Not found","message":"The resource you requested was not found.","details":{"ErrorMessage":"The resource you requested was not found."}}
```

### More Information

[Internal Slack](https://octopusdeploy.slack.com/archives/C02KJJD8D0X/p1694041906520499)

### Workaround

Change the URL to use oc.to instead of the Cloud instance url,  e.g. `https://oc.to/HelpGeneral`

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.1941 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.1941 |
| 2024.1+ | _all releases_ |
