### ISSUE TITLE
Update license period to match customer agreement

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8333]
Expired self-host licenses will no longer allow 60 days before restricting product usage.

**Comment by tothegills** [comment]
Release note: Updated license handling to match the customer agreement

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.12941 |
| 2023.4 | 2023.4.2492 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.12941 |
| 2023.4 | 2023.4.2492 |
| 2024.1+ | _all releases_ |
