### ISSUE TITLE
Option to delete XML config transforms after applying

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#834]
Via http://help.octopusdeploy.com/discussions/questions/243-deleting-config-transformation-files-after-deploy

Lingering .config files cause issues for some applications.

**Comment by donesbon** [comment]
I have very easily achieved this using this script:


Write-Host 'Preparing to delete config transformation files in $TargetPath:' $TargetPath

function DeleteIfConfigTransformFile($file)
{
    #Write-Host "Processing file:" $file
    
    try
    {
        $xdoc = New-Object System.Xml.XmlDocument
        $xdoc.Load($file)

        if($xdoc.configuration.xdt -eq "http://schemas.microsoft.com/XML-Document-Transform")
        {
            Write-Host "Deleting file:" $file
            Remove-Item $file
        }
        else
        {
            Write-Host "Not deleting config file (doesn't have the correct xdt xml namespace declaration):" $file
        }
    }
    catch
    {
        Write-Host "Could not xml parse file:" $file
    }
    
}

Get-ChildItem $TargetPath -Recurse | Where-Object { $_.Name -like "*.config" } | ForEach-Object { DeleteIfConfigTransformFile ($_.FullName) }



Script template JSON:

{
  "Id": "ActionTemplates-5",
  "Name": "Delete Config Transform Files",
  "Description": "Recursively deletes all files underneath #{TargetPath} which has the extension .config, is parsable xml and has the namespace xmlns:xdt=\"http://schemas.microsoft.com/XML-Document-Transform\" defined.",
  "ActionType": "Octopus.Script",
  "Version": 4,
  "Properties": {
    "Octopus.Action.Script.ScriptBody": "Write-Host 'Preparing to delete config transformation files in $TargetPath:' $TargetPath\r\n\r\nfunction DeleteIfConfigTransformFile($file)\r\n{\r\n    #Write-Host \"Processing file:\" $file\r\n    \r\n    try\r\n    {\r\n        $xdoc = New-Object System.Xml.XmlDocument\r\n        $xdoc.Load($file)\r\n\r\n        if($xdoc.configuration.xdt -eq \"http://schemas.microsoft.com/XML-Document-Transform\")\r\n        {\r\n            Write-Host \"Deleting file:\" $file\r\n            Remove-Item $file\r\n        }\r\n        else\r\n        {\r\n            Write-Host \"Not deleting config file (doesn't have the correct xdt xml namespace declaration):\" $file\r\n        }\r\n    }\r\n    catch\r\n    {\r\n        Write-Host \"Could not xml parse file:\" $file\r\n    }\r\n    \r\n}\r\n\r\nGet-ChildItem $TargetPath -Recurse | Where-Object { $_.Name -like \"*.config\" } | ForEach-Object { DeleteIfConfigTransformFile ($_.FullName) }"
  },
  "SensitiveProperties": {},
  "Parameters": [
    {
      "Name": "TargetPath",
      "Label": "Target path",
      "HelpText": "The path to clean.\n\nUsually you would set this to `Octopus.Action[StepName].Output.Package.InstallationDirectoryPath`.",
      "DefaultValue": null,
      "DisplaySettings": {
        "Octopus.ControlType": "SingleLineText"
      }
    }
  ],
  "LastModifiedOn": "2015-05-05T14:04:15.699+00:00",
  "LastModifiedBy": "epe@dis.dk",
  "$Meta": {
    "ExportedAt": "2015-05-05T14:11:21.100Z",
    "OctopusVersion": "2.6.5.1010",
    "Type": "ActionTemplate"
  }
}

**Comment by jo3stevens** [comment]
Thanks @donesbon. I'm using Sitecore which has many config files the other step template deleted, but yours did the job.

**Comment by donesbon** [comment]
@jo3stevens I used it wit Sitecore too. Glad it worked for you

**Comment by johndowns** [comment]
Is there a version of this that would work with an Azure web app deployment?

**Comment by donesbon** [comment]
Hi @johndowns I haven't worked with Octopus or deployment of any kind for a long long time (or Azure for that matter). I won't be of any help :(

**Comment by aocampocogworks** [comment]
Would be great to implement this as par of the deployment step for IIS websites and Azure webapps, I think this is something we all need. /cc @PaulStovell
