### ISSUE TITLE
Update to latest Tentacle

### ISSUE THREAD

**Issue by acodrington** [OctopusDeploy/Issues#8342]
There have been numerous improvements and fixes made in OctopusTentacle over the past few months. Updating Tentacle to the latest version allows Octopus Server to take advantage of these improvements.

Changes include:
* [Fixed:  PollingOverWebSockets can fail to close a WebSocket connection once it is finished with](https://github.com/OctopusDeploy/OctopusTentacle/issues/596)
* [Fixed: WebSocket bug where a SendAsync is not being awaited](https://github.com/OctopusDeploy/OctopusTentacle/issues/597)
* [Fixed: Some error messages are misleading](https://github.com/OctopusDeploy/OctopusTentacle/issues/598)
* [Fixed: Memory leak and inefficiencies](https://github.com/OctopusDeploy/OctopusTentacle/issues/599)
* [Fixed: Performance issue when instantiating logs](https://github.com/OctopusDeploy/OctopusTentacle/issues/601)

**Comment by acodrington** [comment]
Release Note: Update Tentacle to v7.0.219
Changes and improvements include:
* Fixed: PollingOverWebSockets can fail to close a WebSocket connection once it is finished with
* Fixed: WebSocket bug where a SendAsync is not being awaited
* Fixed: Some error messages are misleading
* Fixed: Memory leak and inefficiencies
* Fixed: Performance issue when instantiating logs

**Comment by acodrington** [comment]
[sc-57057]

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.1989 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.1989 |
| 2024.1+ | _all releases_ |
