### ISSUE TITLE
Allow the selection of packages in Terraform step to be deferred

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#8355]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
The package selection fields in the Terraform steps do not support deferred package selection, This means the package must be hard coded in a step template, or feeds and packages must be individual variables. 

## Solution

Update the Terraform steps to use deferred package selection.

## Screenshots and Mockups

![image](https://github.com/OctopusDeploy/Issues/assets/160104/6e53ad7d-4dbb-49eb-a010-58700b77e709)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.3691 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.3691 |
| 2024.1+ | _all releases_ |
