### ISSUE TITLE
Re implement support for ScriptCS to handle cases where net6.0 is not available and not possible to upgrade to.

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8359]
### Severity

Sev 2

### Version

2023.4.*

### Latest Version

None

### What happened?

As a part of our migration from ScriptCS to dotnet-script a number of customers did not receive deprecation notices in the lead-up to the switch over. This along with the requirement to have net6.0 available in the execution environment has led to a number of customers being blocked from upgrading. The intention here was to force a deadline transition from ScriptCS -> dotnet-script but considering the above issues we are adding support for ScriptCS back for the interim while people migrate over.

### Reproduction

Executing C# scripts in an environment without net6.0.

### Workaround

- Install .NET 6 on any affected targets (AND)
- Use the [workaround script detailed in our blog](https://octopus.com/blog/rfc-migrate-scriptcs-dotnet-script#workaround) Note the workaround uses a PowerShell Step.
OR
- Alternatively, you can update your scripts so the workaround isn’t required. Check out the dotnet-script NuGet Packages format detailed [here](https://github.com/dotnet-script/dotnet-script#nuget-packages-1).

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.3867 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.3867 |
| 2024.1+ | _all releases_ |
