### ISSUE TITLE
Using dotnet-scripts syntax to reference NuGet packages throws "The given path's format is not supported" error

### ISSUE THREAD

**Issue by SeanStanway-Octopus** [OctopusDeploy/Issues#8375]
### Severity

1 customer affected, though any using this syntax will be affected

### Version

2023.4.4265

### Latest Version

None

### What happened?

Attempting to use the dotnet-script syntax for referencing NuGet packages causes a `[NotSupportedException] The given path's format is not supported`.

### Reproduction

1. Create a CSX script file containing the following and upload this as a package to the Octopus instance: 
`#r "nuget: Newtonsoft.Json, 13.0.3"`
`using Newtonsoft.Json;`
`Console.WriteLine("Test");`

2. Setup a "Run a Script" step to use the above script file
3. Deploy this to a newer Tentacle version that has dotnet-script on it

### Error and Stacktrace

```shell
13:19:27   Info     |       ERROR: Error executing script 'D:\Octopus\Cloud\Work\ServerTasks-86519-b1bc26c3-7700-415e-92e7-5e19e58fe123\Bootstrap.863-41e9-85b7-bf9dec931f7c.Script.csx' [NotSupportedException] The given path's format is not supported.
```

### More Information

This syntax works directly when executed against dotnet-script on the Tentacle itself. Looks to be a problem when going through the generated code to execute the script.

### Workaround

Current workaround is to reference whatever library or package files that are necessary for the script directly on the targets file structure.

**Comment by IsaacCalligeros95** [comment]
Resolved in https://github.com/OctopusDeploy/Calamari/pull/1156
