### ISSUE TITLE
Calc variable substitution fails to handle 'Variable / integer"

### ISSUE THREAD

**Issue by rain-on** [OctopusDeploy/Issues#8382]
### Version

2023.1.1

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Assuming a variable "MyVar" exists with value "2".

A second Variable "CalcedVar" exists with value `{calc MyVar/2}`.

CalcedVar is not numerically calculated (eg evaluated to "1"),  instead is considered a string literal in places where it is used.

### Reproduction

See What happened.

### More Information

It appears the problem is that "/" has two purposes in Octopus variables:
1. As the divide operator
2. As a valid character in a variable name.

Currently:
* `#{calc 2 / MyVar}` works as expected, as the parser assumes the "/" is a divide operation (due to first operand being numeric.
* `#{calc MyVar/2}` assumes that 'MyVar/2' is an entire variable name, and thus, making the calc substitution meaningless - thus it renders as a string.
* `#{calc VarWith/Inside * 5}` works as expected (assuming a variable named "VarWith/Inside" exists)

There are a few available solutions:
1. Change the divide operator symbol (none immediately present as acceptable)
2. Variable identifiers must escape their "/", but only in Calc operations
3. Prevent usage of Variable-names containing "/" in the calc block (such that "/" _always_ implies divide).
4. Allow variables to be enclosed in  { ... }, such that everything within the braces is _also_ deemed to be an identifier, and not an operator, this in turn would allow for the following, without breaking existing behaviour:
* #{calc {My/Var} / 2}
* #{calc 2 / {My/Var}}
* #{calc 2 / My/Var}, and
* #{calc 2/ {My/Var}}

### Workaround

It should be possible to write #{calc 1/2 * MyVariable}

**Comment by rain-on** [comment]
Release note: 'Calc' variable substitution allows variable names to be enclosed in { } to overcome parsing issues

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.5214 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.5214 |
| 2024.1+ | _all releases_ |
