### ISSUE TITLE
Session timeouts under 20 minutes cause Auth cookies to refresh every on api request

### ISSUE THREAD

**Issue by tleed5** [OctopusDeploy/Issues#8392]
### Severity

Not blocking and work around not necessary

### Version

Any version post 2017-02-23 will have the affected code

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the Authentication setting "Session Timeout" is set to a value under 20 minutes it will cause the authentication token to refresh on every api request.

This also causes issues when trying to revoke all of your sessions as the api request to revoke all of the session will generate an new auth cookie that won't be affected by the revoke.

Video show casing issue - Session timeout of 2 minutes
https://github.com/OctopusDeploy/Issues/assets/3272176/be9efa35-a05d-4662-be1a-28410f77a028

### Reproduction

1. Go to configuration
2. Open Settings
3. Open Authentication
4. Set Session Timeout (seconds) to a value less than 1200 (20 minutes)

**Comment by tleed5** [comment]
Release Note: Session Timeouts with values less than the default timeout(20 minutes) will now no longer cause the authentication cookie to refresh on every API request and will refresh when necessary.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.6282 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.6282 |
| 2024.1+ | _all releases_ |
