### ISSUE TITLE
Unable to Distinguish Unique Projects with Long Names in the Projects Button Drop-Down Search 

### ISSUE THREAD

**Issue by briggs-octo** [OctopusDeploy/Issues#8402]
### Severity

Non-blocking

### Version

2023.4.4798

### Latest Version

None

### What happened?

When searching for projects via the Project button drop-down search (left side of the screen), you are not able to distinguish between similarly named projects when they have long names, as this content is truncated:

![image](https://github.com/OctopusDeploy/Issues/assets/104870596/937961cb-82cf-4293-8ea5-5d000de576a4)

This is different than the main search box (right side of the screen), where this content displays completely:

![image](https://github.com/OctopusDeploy/Issues/assets/104870596/4f391639-7cf9-4138-9fd1-86df03ccbf64)

### Reproduction

Create several similarly named projects with long names and attempt to search for them using the Project button search on the left side of the screen (via the drop-down arrow).

**Comment by MarkSiedle** [comment]
Release Note: Added tooltips to accommodate for long project names in the project-switcher

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.160 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.160 |
| 2024.2+ | _all releases_ |
