### ISSUE TITLE
"Run a Docker Container" Step No Longer Allows for Selecting a Feed

### ISSUE THREAD

**Issue by briggs-octo** [OctopusDeploy/Issues#8419]
### Severity

Blocking issue

### Version

2023.4.5740

### Latest Version

None

### What happened?

In using the "Run a Docker Container" step, you used to be able to select a feed for the step, but this is no longer the case and the step just defaults to the built-in package feed (with no options to modify this).

Old example:

![image](https://github.com/OctopusDeploy/Issues/assets/104870596/cca9dc77-7f72-4b3f-a2dd-be0a7bb772dd)

How things look now:

![image](https://github.com/OctopusDeploy/Issues/assets/104870596/e066d178-d963-4a85-bf02-41387b7f4868)

### Reproduction

Add the built-in step "Run a Docker Container" to your process and try to select a feed within the "Docker Image Details" section of the step.

### Error and Stacktrace

```shell
N/A
```

**Comment by IsaacCalligeros95** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/20790

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.6580 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.6580 |
| 2024.1+ | _all releases_ |
