### ISSUE TITLE
Recovering from Communication Errors with Tentacle on by Default

### ISSUE THREAD

**Issue by sburmanoctopus** [OctopusDeploy/Issues#8422]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement
Deployments to tentacles on flaky networks are prone to failure. Octopus Server has an [EAP feature](https://github.com/OctopusDeploy/Issues/issues/8229) to retry failed communications to tentacle allowing the deployments on flaky networks to succeed.

## The Need
The EAP feature has gone well, and should now be turned on by default.

## Solution
We will now update all machine policies to allow Octopus Server to re-attempt failed communications with Tentacle.

If you find that communication error recovery is not beneficial, then it can be disabled in the respective Machine Policy.

For more information regarding the communication error recovery, please refer to [Recover from communication errors with Tentacle](https://octopus.com/docs/infrastructure/deployment-targets/machine-policies#MachinePolicies-Recoverfromcommunicationerrorswithtentacle)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.6883 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.6883 |
| 2024.1+ | _all releases_ |
