### ISSUE TITLE
New welcome dialog for trial licenses

### ISSUE THREAD

**Issue by tleed5** [OctopusDeploy/Issues#8428]
# Prerequisites
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
A welcome dialog for new users will provide different ways to get started with Octopus. This will increase their engagement with Octopus as it will support them through various goals rather than us assuming their intent as we currently do. 

## Solution
New welcome dialog that appears on trial licenses that helps direct users to their first deployment faster

## Screenshots and Mockups

![Screenshot](https://www.fillmurray.com/620/300)

## Links
- Related issue: https://github.com/OctopusDeploy/Issues/issues/8427

**Comment by tleed5** [comment]
Release Note: Adds a new welcome dialog for trial licenses with prompts for creating a new project or a [sample project](https://github.com/OctopusDeploy/Issues/issues/8427).

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.4909 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.4909 |
| 2024.1+ | _all releases_ |
