### ISSUE TITLE
Thread Pool exhaustion events 

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#8429]
### Severity

Blocking some customers, workaround available

### Version

2023.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Under certain workloads, operations can be delayed or fail due to thread pool exhaustion.

The following error will be logged in the system logs:
`ThreadPool exhausted for approximately 4997ms current ThreadPool exhaustion events 1`

Other symptoms of potential thread pool exhaustion are the existence of the following log entries:

`"QueryExecutorProvider" created with "ServerTasks-3006-7c571afe-7a81-40b7-9854-163d581b3397" has been alive for "0:00:05:02.553775".` where the time is excessive.
`"Open Database Connection" attempt #1 faulted, retrying in 00:00:00.1000000: "Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached."`

### Reproduction

No simple reproduction available. Occurs under load.

### Workaround

For 2023.3 and later, set the following environment variables:

`OCTOPUS__ThreadPool__MinimumWorkerThreads` 
`OCTOPUS__ThreadPool__MinimumCompletionPortThreads`

The default value for these is `128` as of 2023.3. The recommendation would be to increase these gradually starting with 400.

If changing these values, consideration should also be given to increasing the maximum SQL connection pool. The default value for this is 100, this should also be increased gradually as each of these settings have other potential issues for memory and CPU contention.
To increase the sql connection pool max size, add `Max Pool Size=<pool size>` to the end of the sql connection string in the Octopus Server config.
`<set key="Octopus.Storage.ExternalDatabaseConnectionString">Server=localhost,1433;Database=OctopusDeploy-release;User Id=sa;Password=<password>;Max Pool Size=<pool size></set>`
The recommendation is to increase this in small increments of 50 or 100 at a time, bumping this number up too large can cause CPU increases on both the application server and the SQL server.

 Related to #8444

**Comment by droyad** [comment]
Release Note: Increased the default number of Thread Pool threads and Database Connections

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8059 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13181 |
| 2023.4 | 2023.4.8059 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13181 |
| 2023.4 | 2023.4.8059 |
| 2024.1 | 2024.1.1624 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13181 |
| 2023.4 | 2023.4.8059 |
| 2024.1 | 2024.1.1624 |
| 2024.2+ | _all releases_ |
