### ISSUE TITLE
Introduce Event Based Deployment History and RunbookRun History table syncing

### ISSUE THREAD

**Issue by paulegradie** [OctopusDeploy/Issues#8432]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

Octopus Server has historically used two stored procedures run at regular intervals (one at short intervals to perform updates, and the other at long intervals to perform a full table sync) to sync and update the deployment and runbook run data tables with their respective history tables. For customers with large amounts of data in these tables, this has led to regular spikes in database activity, which in some circumstances has led to performance degredation.

## The Need
The execution of the stored procedures at large scales can be unnecessarily expensive when there are a small number of additions or updates to make.

## Solution
We can leverage the internal eventing system to make updates and additions to these tables so that small, frequent sync operations are made instead of large infrequent operations.

**Comment by paulegradie** [comment]
Release Note: Greatly reduced the performance impact of calculating `DeploymentHistory` and `RunbookRunHistory` reporting tables for customers with many deployments and/or runbook runs. Improved overall system performance for customers with large instances and heavy Octopus usage.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.7781 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.7781 |
| 2024.1+ | _all releases_ |

**Comment by mjhilton** [comment]
This change made the new event-based approach the default for all customers, and switched off the scheduled stored procedure runs.
