### ISSUE TITLE
Help Sidebar Improvements

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#8438]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
The in-product Help Sidebar is useful but under-utilized. Our hypothesis is that bringing instructional videos and docs content to the help sidebar will increase adoption of new features for trial users, which will in turn increase the likelihood of them extracting value from Octopus. 

## Solution
Among other small improvements, we will be putting some useful support related links in a new, collapsable footer. The links from the old "Resources" tab will be moved under the main help content, beneath a heading of "Related Docs". The links to video content will be replaced by embedded videos, reducing the need to view them in a separate tab. We'll make the sidebar's width adjustable, so users will be able to set a comfortable width to consume the sidebar content, particularly videos. We're also allowing users to customise the label that appears for their internal support link, via the Configuration -> Features screen.

## Screenshots and Mockups
<img width="1092" alt="image" src="https://github.com/OctopusDeploy/Issues/assets/5858312/e20969dc-56ad-4470-8a77-5ca2f8906537">

**Comment by iryan2** [comment]
Release Note: The Help Sidebar has been overhauled. It now has adjustable width, embedded YouTube videos and a simplified layout, among other smaller improvements.

**Comment by thekatstevens** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/21498

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.3217 |
| 2024.2+ | _all releases_ |
