### ISSUE TITLE
Sourcing scripts from Git

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#8442]
# The enhancement

## The Need
Scripts are code, and we can hardly think of a better way to store and evolve code than Git.
That's why we are adding a new way to source scripts to our script steps. 
You'll be able to choose between sourcing a script from a Git repo, sending it as a package or writing it directly in the Octopus UI.

## Solution

We are adding git script sourcing to "nearly" all script steps.
The steps that will get this option are:
![image](https://github.com/OctopusDeploy/OctopusDeploy/assets/122651/421f808f-cfe9-4331-9d9c-7356fa8a177a)

## Screenshots and Mockups

The steps will have a 3rd option, where a user can configure the git source.
![image](https://github.com/OctopusDeploy/Issues/assets/122651/ed582d8c-15ff-47bf-94e5-1cd6f106fcd8)

## Links

https://roadmap.octopus.com/c/93-sourcing-scripts-from-git

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.8 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.7982 |
| 2024.1+ | _all releases_ |
