### ISSUE TITLE
Tentacle health checks keep a transaction open for every machine for the duration of the check

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#8444]
### Severity

Disruption for customers with many machines, viable workaround available

### Version

At least 2023.2 and later

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A transaction is opened and held for every machine currently being health checked. If that number reaches or exceeds the database connection pool size (default 100), the server can lock up until the health checks complete.

In most cases this is not a visible problem because:
- Large customers increase the connection pool size
- Each health check task only runs 30 at a time, so would only exceed the limit if 3 or more health checks with 30+ machines are run at the same time
     - Health checks are often configured not to run at the same time
- Health checks usually complete quickly, except when machines are offline or unreachable

### Reproduction

1. Create 10 machine policies
2. Create 300 polling tentacles, 30 on each machine policy
3. Queue a health check for all machine policies

### Workaround

- Stagger the machine policy health check times (available in the machine policy details
- [Increase the sql connection pool max size](https://octopus.com/docs/administration/managing-infrastructure/performance#connection-pool-timeout)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.6567 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.6567 |
| 2024.2+ | _all releases_ |
