### ISSUE TITLE
Add/Modify ProjectGroup returning 500 when it should return 409

### ISSUE THREAD

**Issue by emilol** [OctopusDeploy/Issues#8464]
### Version

2024.1.231-2024.1.854

### Latest Version

None

### What happened?

When two attempts to update the same project group are made at the same time, this should result in a 409 conflict status code. A recent regression saw this return a 500 instead.

### Reproduction

Update the same ProjectGroup multiple times in parallel.

**Comment by emilol** [comment]
Release note: Add/Modify ProjectGroup returning 500 when it should return 409

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.854 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.854 |
| 2024.2+ | _all releases_ |
