### ISSUE TITLE
Support Harbor OCI feeds with sub-paths

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8470]
OCI feeds with sub-paths were supported in https://github.com/OctopusDeploy/Issues/issues/8446. The implementation works with the docker self-hosted registry but does not work with Harbor. Harbor returns an exception when attempting to search the feed: "Unknown Authentication scheme for Uri..."

**Comment by tothegills** [comment]
Release note: Support OCI feed sub-paths in Harbor

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8059 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13181 |
| 2023.4 | 2023.4.8059 |
| 2024.1 | 2024.1.1624 |
| 2024.2+ | _all releases_ |
