### ISSUE TITLE
User session management improvements

### ISSUE THREAD

**Issue by tleed5** [OctopusDeploy/Issues#8480]
# Prerequisites
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
User Session management within Octopus needs updating to allow for better control over the lifecycle of the session and future improvements.

**Comment by tleed5** [comment]
Release note: Improvements made to user sessions to allow for better management these changes. With the roll out of these changes, it will unfortunately cause existing user sessions to be invalidated and users will be forced to log back in.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2270 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2270 |
| 2024.2+ | _all releases_ |
