### ISSUE TITLE
Targets and Workers running Windows Server 2012 R2 or earlier will generate warnings in health checks if not running  .NET 462 or later

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8483]
As part of the [deprecation plans](https://octopus.com/blog/deprecating-win2003) for Windows Server 2003, we intend to update the full framework build of the [Calamari task engine](https://octopus.com/docs/octopus-rest-api/calamari) to .NET462.

As described in the above blog post this is [not installed by default](https://octopus.com/blog/deprecating-win2003#after-2024.1-february-2024) on Windows Server 2012 R2 and below. 

To provide some advanced warning, health checks on these machines will now generate a warning so that users are aware that their deployments may fail without this upgrade.

![image](https://github.com/OctopusDeploy/Issues/assets/1830666/9eb0be89-378b-4c30-9e79-4c109ab4cad1)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2286 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2286 |
| 2024.2+ | _all releases_ |
