### ISSUE TITLE
Improving our Page Layouts

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#8487]
# The enhancement

## The Need

We have been working towards improving our user experience at Octopus Deploy. Specifically addressing feedback about our interface looking “messy” and “hard to navigate”.  Addressing these concerns requires a layout that presents information in an easy-to-read structure.

## Enabling the feature (all users)

The feature can be enabled for all users of an instance by setting the `OCTOPUS__FeatureToggles__PageHeaderUpliftEverywhereFeatureToggle` environment variable with a value of `true`

## Solution

We began by looking at our project page layouts. Here we identified a couple of key elements that needed improving. In the image below, the highlighted areas are where we placed our focus. These areas contained our page headings and breadcrumbs. Page headings and breadcrumbs are important for understanding your location in the app.

### Old Projects Layout
![old-layout](https://github.com/OctopusDeploy/Issues/assets/819605/007205a2-f6be-4764-9d1c-f70dcd7a7eff)

Once we arrived at a design that worked well for projects, we then took this design across the entire app. See below our new layout for projects.

### New Projects Layout
![new-layout](https://github.com/OctopusDeploy/Issues/assets/819605/67ee8d14-ccac-4fbe-9766-72530a911eb5)

## Benefits of this change
The benefits of this change provides an easier-to-understand Octopus Deploy UI. The headings now have an appropriate size and placement relative to the page content. The breadcrumbs now have appropriate visual treatment and their behaviour is applied consistently. Placing the Create Release button in the top-right corner near other page actions is a more intuitive location. Customers were having trouble remembering where this button was located.

A few other notable improvements:
- Simplified loading state animations
- Clearer menu interaction states
- Flattened project navigation by removing groups
- Updated headings and menu labels to match

**Comment by MarkSiedle** [comment]
Release Note: Improved our Page Layouts UX

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2326 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2326 |
| 2024.2+ | _all releases_ |
