### ISSUE TITLE
Enable TCP Keepalives between Octopus Server and Tentacle

### ISSUE THREAD

**Issue by nathanwoctopusdeploy** [OctopusDeploy/Issues#8495]
# The enhancement

## The Need

Octopus Server and Tentacle establish long-lived TCP connections to transfer Requests and Responses. The timeouts for Reads and Writes over the TCP connection can be up to 10 minutes by default.

If the TCP connection between Server and Tentacle fails and is not closed cleanly by both parties (FIN or RST packets are not sent and received), it can take up to 10 minutes for Server to detect the TCP connection has failed and to terminate a waiting Read or Write.

This leads to undesirable delays when processing Requests and Responses.

## Solution

Starting with Server version `2024.1.1801` it is possible to enable TCP Keepalives between Server and Tentacle. This will ensure the connection is active and fail after ~60 seconds if there is an issue with the connection between Server and Tentalce.

As of `2024.1.1801` this is an opt-in feature. A future update will enable this feature by default.

This has been enabled for all Octopus Cloud instances  `>=2024.1.1801`

## Links

- [Adding option to enable TCP keep alives in Server](https://github.com/OctopusDeploy/OctopusDeploy/pull/21270)
- [Enable TCP Keepalives between Tentacle and Octopus Server](https://github.com/OctopusDeploy/OctopusTentacle/issues/692)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.3382 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.3382 |
| 2024.2+ | _all releases_ |
