### ISSUE TITLE
Use local async lock when publishing to the message bus

### ISSUE THREAD

**Issue by desruc** [OctopusDeploy/Issues#8507]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
The current process for publishing messages to the message bus is causing scalability challenges, primarily due to the use of `TABLOCKX`. It results in a bottleneck that hinders our ability to efficiently scale deployments.

## Solution
We have implemented a semaphore slim around the affected transactions. This addition has proven effective in relieving load on the database, enabling us to concurrently deploy to a larger number of targets.

**Comment by LukeButters** [comment]
Release Note: Improved performance in publication of internal messages

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8125 |
| 2024.1 | 2024.1.3979 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8125 |
| 2024.1 | 2024.1.3979 |
| 2024.2+ | _all releases_ |
