### ISSUE TITLE
Minor visual and textual improvements of Kubernetes step expanders

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#8513]
# The enhancement

[sc-65887]
[sc-65892]
[sc-65934]

## The Need
There are several expanders that need updating.
1. The Authentication expander description is incorrect in Raw YAML step
![CleanShot 2023-11-28 at 13 18 50@2x](https://github.com/OctopusDeploy/Issues/assets/151479559/ffdb0ea9-093b-4caf-b2f5-883b18b8aae3)
2. The current expander description uses (s) multiple times, which makes it difficult to read
![CleanShot 2023-11-28 at 13 22 07@2x](https://github.com/OctopusDeploy/Issues/assets/151479559/d8d30409-65b5-49a7-839b-fb735a28e7cd)
3. The Kubernetes Object Status Check expander needs 3 changes:

  - Remove the 'NEW' chip since the feature is now 6 months old

  - Remove the bold text formatting on the radio button labels

  - Remove the callout asking for feedback on the step

![CleanShot 2023-11-28 at 16 16 15@2x](https://github.com/OctopusDeploy/Issues/assets/151479559/7f6b725d-26c8-4a6d-b042-2b10f93d0234)

## Screenshots and Mockups
<img width="797" alt="Screenshot 2023-12-05 at 8 20 26 am" src="https://github.com/OctopusDeploy/Issues/assets/151479559/efacea08-613b-422a-8688-74da9c4ca0c5">
<img width="738" alt="Screenshot 2023-12-05 at 8 20 36 am" src="https://github.com/OctopusDeploy/Issues/assets/151479559/8d1f04df-f32d-4c09-8dac-2875c40da8f6">

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.4054 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.4054 |
| 2024.2+ | _all releases_ |
