### ISSUE TITLE
An error is displayed when there are no archived audit logs

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8514]
Fresh Octopus instances do not create audit log archives. When managing archives audit logs, an error is displayed:

![image](https://github.com/OctopusDeploy/Issues/assets/171197/fc48a33c-219c-4f23-aa65-a00ceb279d1d)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5271 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5271 |
| 2024.2+ | _all releases_ |
