### ISSUE TITLE
Runbook Scheduled Trigger Fires/Queues Unexpectedly at the Top of the Hour Instead of Adhering to Specified Interval

### ISSUE THREAD

**Issue by RobMcCarther** [OctopusDeploy/Issues#8525]
### Severity

medium

### Version

2024.1.Build 3998-hotfix.4353

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The runbook trigger exhibits unexpected behavior by executing prematurely at the top of the hour, irrespective of the scheduled interval. This anomaly occurs regardless of the specific interval configuration (e.g., every 17 minutes or other intervals). When the trigger cycle initiates at a particular time (e.g., 13:15), it correctly fires/queues subsequent runs at 13:32, 13:59, and unexpectedly at the top of the hour (e.g., 14:00). This deviates from the intended behavior of respecting the specified interval and waiting until the scheduled time for the next execution (e.g., 14:16). I then picks back up the interval, deploying 17 minutes from the top of the hour

### Reproduction

- Set up a trigger with any configured interval. (that doesn't;t naturally hit the top of the hour)
- Observe the trigger cycle starting at a specific time (e.g., 13:15).
- Note the times at which subsequent trigger executions occur in the audit
- Identify the premature firing/queuing at the beginning of the next hour (e.g., 14:00 instead of the scheduled time).
- Also notice the scheduled interval get's picked back up

For ex:

- runbook setup to trigger every 17 minutes starting at 11:17am to 12:30pm
- Expected runs 11:17, 11:34, 11:51, 12:08, 12:25
- Actual runs 11:17, 11:34, 11:51, 12:00, 12:17

-  Fired off at 12pm EST when it should have been triggered next at 12:08pm
Edit: Did NOT fire off at 12:08pm as expected. Instead it ran again at 12:17pm (picking back up the interval after the top of the hour ) not 12:25pm (17 minutes after the last expected run 12:08pm)

https://octopus-operations.octopus.app/app#/Spaces-955/configuration/audit?eventCategories=RunbookRunStarted&from=2023-11-11T00%3A00%3A00.-05%3A00&to=2023-12-11T23%3A59%3A59.-05%3A00&includeSystem=true&spaces=Spaces-955

### Workaround

no current workaround

**Comment by RobMcCarther** [comment]
![Uploading Runbook trigger - top of hour.png…]()

**Comment by RobMcCarther** [comment]
Testing using CRON expression as well
*/17 14-16 11 12 1
Expected runs 2:18, 2:35, 2:52, 3:09
Actual runs 2:18, 2:35, 2:52, 3:01, 3:18
![CRON - top of hour](https://github.com/OctopusDeploy/Issues/assets/139906297/a070bdb3-8ed7-4030-927e-e36639d5efac)

**Comment by N-lson** [comment]
Closing this issue as it seems this behavior is intended. Minute intervals in CRON expressions start on the hour, regardless of whether it is part of a time period. [Putting the above CRON expression](https://crontab.guru/#*/17_14-16_11_12_1) returns this:
> At every 17th minute past every hour

The time period isn't continuous.


The minute interval selector in Octopus uses a CRON expression behind the scenes. It gets converted to a similar CRON expression to the one you provided in the repro e.g. `*/17 * * * MON` (assuming the user has only selected Monday).

We'll update our public docs to specify that all triggers are based on CRON expressions. I don't think our docs are very clear on that.

If you want to run a runbook or deployment at specific minutes over multiple hours, one approach would be to create multiple triggers - one for the first hour, and one for the second.
