### ISSUE TITLE
Variable Substitution Issue in Repository URL field with Git Repository as Script Source in Run a Script Step

### ISSUE THREAD

**Issue by RobMcCarther** [OctopusDeploy/Issues#8526]
### Severity

Low

### Version

2024.1 Build 3998-hotfix.4353

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Encountering a bug where variable substitution is not functioning as expected in the Repository URL field when using a Git repository as the script source in a Run a Script step. Despite attempting to substitute variables like #{Project.AdoRepositoryUrl}, the system generates an error insisting on a valid repository URL, hindering the intended flexibility in configuration.

_A valid repository URL must be specified when using a Git repository source, e.g. https://github.com/OctopusDeploy/OctopusClients.git_

The Script File Path accepts variable substitution without issue

![Repo URL error](https://github.com/OctopusDeploy/Issues/assets/139906297/77982d0a-aa8d-49b7-ac15-6c01042c2c68)
![sctipt file path var sub - no error](https://github.com/OctopusDeploy/Issues/assets/139906297/c8fb5d6d-2535-4e62-91dd-ff87aa653b90)
![Variable Repo URL definition](https://github.com/OctopusDeploy/Issues/assets/139906297/fbe0bcb8-51de-4a67-a2b7-7324d5a0d5ae)

### Reproduction

- Configure a Run a Script step using a Git repository as the script source.
- Define project variable for a valid git repo URL (https://github.com/OctopusDeploy/OctopusClients.git)
- Attempt to substitute variables like in the Repository URL field and save
- Encounter an error demanding a valid repository URL, despite the presence of the variable.

### Error and Stacktrace

```shell
_A valid repository URL must be specified when using a Git repository source, e.g. https://github.com/OctopusDeploy/OctopusClients.git_
```

### Workaround

To enter in the Repository URL manually

**Comment by rain-on** [comment]
Release Note: Fixed issue whereby when using git-sourced scripts, an Octopus variable was considered invalid content for the repository URL; Octopus Variables can now be used for git repository urls.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.6781 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.6781 |
| 2024.3+ | _all releases_ |
