### ISSUE TITLE
Step templates sourcing scripts from git fail at deploy time.

### ISSUE THREAD

**Issue by rain-on** [OctopusDeploy/Issues#8527]
### Version

2023.3.10825

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Deployments containing a step-template which customises "Script Step" by sourcing the script from a git-repo fails at execution time.

### Reproduction

Create a new "Step Template" in library which templates the "Run a Script" built-in step template.

In the new step-template, set the "Script Source" to "Git Repository" - and set all required fields, and save.

In your deployment process, add an instance of this custom-step-template to your process and fill in required fields, and save the step/process.

The process will fail when it is executed, indicating tha ta package could not be sourced.

### More Information

The built-in script-step works corrctly when using git-sourced scripts.

Appears to be a problem whereby the git-fields are not copied from the template into the step instance.

**Comment by rain-on** [comment]
Release Note: Deployments containing templated script-steps which source scripts from a git repository, successfully run to completion.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13273 |
| 2023.4 | _tbc_ |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13273 |
| 2023.4 | 2023.4.8231 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13273 |
| 2023.4 | 2023.4.8231 |
| 2024.1 | 2024.1.7889 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13273 |
| 2023.4 | 2023.4.8231 |
| 2024.1 | 2024.1.7889 |
| 2024.2+ | _all releases_ |
