### ISSUE TITLE
Links to documents in the Audit log showing a "Resource is not found" error

### ISSUE THREAD

**Issue by dyantako** [OctopusDeploy/Issues#8528]
### Version

2024.1.4041

### Latest Version

The problem does not exist in the latest build

### What happened?

Clicking a link to an environment from the Audit log results in a "Resource is not found" error.

![image](https://github.com/OctopusDeploy/Issues/assets/110360246/caa093ea-5575-4151-b128-c7b0355f6c75)

Links to proxies are similarly affected.

### Reproduction

1. Create an environment or proxy in a space.
2. Switch spaces
3. Navigate to the Audit log
4. Change filter to include the space that the resource was created
5. Click the resource in the Audit log

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.4914 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.4914 |
| 2024.2+ | _all releases_ |
