### ISSUE TITLE
Degraded performance of variable endpoints when upgrading from 2023.3 to 2023.4+

### ISSUE THREAD

**Issue by desruc** [OctopusDeploy/Issues#8529]
### Version

2023.4.8116

### Latest Version

I could reproduce the problem in the latest build

### What happened?

We have identified a significant performance degradation in the `GET variables/{variableId}` and `GET variables/preview` endpoints. Investigations revealed that this issue stems from a change in the caching mechanism.

This change inadvertently resulted in longer response times and higher resource consumption.

This issue is seemingly exclusive to users with large datasets.

### Reproduction

Attempt to fetch variables from either endpoint.

### More Information

We have a fix that will be rolling out shortly.

**Comment by desruc** [comment]
Release note: Resolved performance degradation in variable endpoints by restoring caching mechanism.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8166 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8166 |
| 2024.1 | 2024.1.5056 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8166 |
| 2024.1 | 2024.1.5056 |
| 2024.2+ | _all releases_ |
