### ISSUE TITLE
Requests to `lifecycles/{id}/projects` may never receive a response

### ISSUE THREAD

**Issue by rosslovas** [OctopusDeploy/Issues#8533]
### Severity

Currently 1 known affected customer

### Version

Earliest tried was 2023.4

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A request to `lifecycles/{id}/projects` may run indefinitely, never returning a response. 

### Reproduction

TBD

**Comment by rosslovas** [comment]
Release note: Fix API requests for projects associated with a lifecycle not responding

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8185 |
| 2024.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8185 |
| 2024.1 | 2024.1.5399 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8185 |
| 2024.1 | 2024.1.5399 |
| 2024.2+ | _all releases_ |
