### ISSUE TITLE
Help Sidebar content uplift

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#8534]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
The Help Sidebar is under-utilised. Over the coming months we'll be expanding the content, among other improvements.

## Solution
Many of the Help Sidebar articles will be updated with new content, embedded videos and helpful links

## Screenshots and Mockups

<img width="395" alt="image" src="https://github.com/OctopusDeploy/Issues/assets/5858312/4647bee7-263a-439a-a8bc-c7fdfcb65eaa">

**Comment by iryan2** [comment]
Release Note: The Help Sidebar has been updated to include embedded videos, refreshed content and relevant links.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5619 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5619 |
| 2024.2+ | _all releases_ |
