### ISSUE TITLE
Cancelling a deployment queued to a Polling Tentacle that has recently disconnected does not stop RPC retries

### ISSUE THREAD

**Issue by nathanwoctopusdeploy** [OctopusDeploy/Issues#8535]
### Version

2024.1.5531

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a deployment to a polling tentacle that has recently gone offline is cancelled, then RPC retries may continue to execute until the RPC retry time limit is reached.

### Reproduction

- Ensure RPC Retries is on
- Deploy successfully to a Polling Tentacle that is online
- Take Polling Tentacle offline
- Retry the deployment
- Wait for RPC retry message to start, then cancel

At this point, RPC retry messages will continue to stream in, even though we have cancelled.

### More Information

What appears to be happening is that the cancellation is happening correctly.

But since it has gotten past get capabilities, and has called 'start script', it doesn't know if the Tentacle actually received the message or not. So now it has to call Cancel on the Tentacle just in case.

But because the Tentacle is offline, the Cancel RPC call never gets through.

**Comment by nathanwoctopusdeploy** [comment]
Server is incorrectly trying to Cancel the Script running on Tentacle in this scenario. We know Tentacle has not started the script, so can cancel quickly cancel without trying to cancel the script on Tentacle

![image](https://github.com/OctopusDeploy/Issues/assets/86938706/99fa590e-142a-460f-b4af-b422b93302cf)

**Comment by nathanwoctopusdeploy** [comment]
[sc-67724]

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.6784 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.6784 |
| 2024.2+ | _all releases_ |
