### ISSUE TITLE
Tasks running on Windows 2008 machines will start logging warnings indicating pending drop of support

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8538]
In preparation for the [planned dropping of support](https://octopus.com/blog/2024-deprecated-features#windows-server-2008) for Windows 2008 based Targets and Workers in 2025, workloads that are detected as running on those machines will start logging a warning notice.

![image](https://github.com/OctopusDeploy/Issues/assets/1830666/99926015-d7a3-4b69-b1e5-c6b0b1d411e1)

Windows 2008 was flagged as [end-of-life in 2020](https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2).

These warnings can be safely ignored, however we would advise customers to upgrade to a more recent Operating System.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5681 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5681 |
| 2024.2+ | _all releases_ |
