### ISSUE TITLE
Support revoking JWT Auth Tokens through the existing user session revocation functionality

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8539]
Access Tokens generated via the [new OIDC Auth flows](https://octopus.com/docs/octopus-rest-api/openid-connect/github-actions) are should support the ability to be revoked after their creation.

We currently support the ability to revoke Username/Password sessions for specific users, this functionality should be extended to include tokens generated via OIDC flows.

![image](https://github.com/OctopusDeploy/Issues/assets/1830666/4cca6edd-98d8-4d91-b7a8-bec466f2286b)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5684 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5684 |
| 2024.2+ | _all releases_ |
