### ISSUE TITLE
Windows Server 2003 Targets no longer function and Windows Server 2012 and below now require NET462 to be installed.

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8548]
As noted in a [recent blog post](https://octopus.com/blog/deprecating-win2003#after-2024.1-february-2024) , a part of dropping support for running workloads on Windows 2003 servers is so that we can upgrade the tooling used for .NET Full Framework targets from the current net40 to net462.

This means that Octopus Targets and Workers running on Windows Server 2012 and below will require the presence of NET462 to operate.

Warnings have [already been added](https://github.com/OctopusDeploy/Issues/issues/8483) to healthchecks to provide advanced warning.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7704 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7704 |
| 2024.2+ | _all releases_ |
