### ISSUE TITLE
Execute using the AWS service role for an EC2 instance causes deployments to fail

### ISSUE THREAD

**Issue by dan-close** [OctopusDeploy/Issues#8551]
### Severity

Any instance on 2024.1.6245

### Version

2024.1.6245

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the 'Execute using the AWS service role for an EC2 instance' option in the AWS Account settings of an AWS step you receive a 'An account identifier was not found. This can occur when the role(s) of the step are scoped to deployment targets that are not compatible with the given step type' error in your deployment. 

### Reproduction

1. Create a new AWS CLI Script step.
2. Set the deployment to run directly on a Worker.
3. Under the AWS Account settings, set the 'Execute using the AWS service role for an EC2 instance' option to Yes.
4. Create and deploy a new release to observe the error. 
5. Switch the step to use an AWS Account variable instead and the error no longer occurs. 

### Error and Stacktrace

```shell
18:00:51   Verbose  |       An account identifier was not found. This can occur when the role(s) of the step are scoped to deployment targets that are not compatible with the given step type.
18:00:51   Fatal    |       The action Run an AWS CLI Script on a Worker failed
```

### Workaround

Use an AWS Account variable for authentication if at all possible.

**Comment by andrewabest** [comment]
Release note: Fixes a regression where steps relying on an EC2 instance role would cause deployments to fail

**Comment by andrewabest** [comment]
Fix is currently rolling out to cloud customers.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.6809 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.6809 |
| 2024.2+ | _all releases_ |
