### ISSUE TITLE
Block the creation of any new Azure Cloud resources in Octopus as part of the deprecation of Azure Cloud Services

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#8554]
**Are you a customer of Octopus Deploy? Please contact [our support team](https://octopus.com/support) if you have any questions regarding an upcoming deprecation.**

# Description

Azure Cloud Services is being [deprecated](https://octopus.com/blog/2024-deprecated-features#azure-cloud-services). There needs to be a way to raise user awareness and discourage further use of it, so that users can have the time to prepare for its end-of-life. 

This first phase of deprecation will add warning log messages whenever an Azure Cloud Service step is being executed in Octopus. Additionally, users will not be able to create any new Azure Cloud resources (i.e. AzureCloudService step and AzureCloudService deployment target).

# Process
- The functionality (executing Azure Cloud Service steps) will be marked as deprecated in code, causing any usages to be logged for monitoring purposes
- After the notification period of at least 6 months the functionality will be toggled off, resulting in an error when attempting to use it. Customers can toggle this back on if they still require it.
- After another 12 months the functionality will be completely removed

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7063 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7063 |
| 2024.2+ | _all releases_ |
