### ISSUE TITLE
Add a warning message about the upcoming deprecation of F# scripting

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#8555]
**Are you a customer of Octopus Deploy? Please contact [our support team](https://octopus.com/support) if you have any questions regarding an upcoming deprecation.**

# Description

As [noted in blog](https://octopus.com/blog/2024-deprecated-features#what-to-expect-3), FSharp scripts are being deprecated.
To provide some waning, any FSharp execution should result in a warning in logs.

# Process
- The functionality will be marked as deprecated in code, causing any usages to be logged for monitoring purposes
- After the notification period of at least 6 months the functionality will be toggled off, resulting in an error when attempting to use it. Customers can toggle this back on if they still require it.
- After another 12 months the functionality will be completely removed

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5631 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.5631 |
| 2024.2+ | _all releases_ |
