### ISSUE TITLE
Creating the Json serializers used for communications to Tentacles can consume lots of resources when deploying to many tentacles.

### ISSUE THREAD

**Issue by LukeButters** [OctopusDeploy/Issues#8556]
# The enhancement

## The Need

When deploying to many Tentacles concurrently the Json parser creation can become a bottle neck.

## Solution

See: https://github.com/OctopusDeploy/OctopusDeploy/pull/22120

## Links

https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/665

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7199 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7199 |
| 2024.2+ | _all releases_ |
