### ISSUE TITLE
Add support for Wildcards in OIDC subjects

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8557]
Currently the subject of an ID token is matched to an OIDC identity _exactly_ during token exchange. This is more secure but potentially means that users need to configure lots more identities, particularly for GitHub Actions if they are using direct branch builds (not PR builds).

We could add support for some sort of wildcard/pattern matching to the subject, allowing users to more easily configure identities.

**Comment by zentron** [comment]
Mainly back end changes. UI updated to reflect change
![image](https://github.com/OctopusDeploy/Issues/assets/1830666/6f02d494-e838-48cf-8aa2-25149d52e4f2)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7382 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.7382 |
| 2024.2+ | _all releases_ |
