### ISSUE TITLE
Git sourced resources can cause a deployment failure if Git commit hash is parsed incorrectly

### ISSUE THREAD

**Issue by tleed5** [OctopusDeploy/Issues#8567]
### Severity

Unknown if blocking any customers

### Version

Earliest 2023.3.1934 based on the original code was introduced

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When sourcing a resource from git, a script for example if the commit that gets packaged starts with 10 digits e.g. `3725016905b9508ca35edfe3636f05e0e557deff` the starting digits `3725016905` would get parsed as the major version of the package which would cause an integer overflow exception to be thrown by the versioning library.

### Reproduction

Get really unlucky with the value of a git commit hash

### Error and Stacktrace

```shell
System.Exception: Unexpected file format in 3876e269c1ddf6b0c757eb6c82605f3629107ddf@O8637286312c1084306c648fad49dce64cf2dffa0@da39a3ee5e6b4b0d3255bfef95601890afd80709.zip.
Expected Octopus cached file format: `<PackageId>@<Version>@<CacheBuster>.<Extension>` or `<PackageId>.<SemverVersion>.<Extension>`
```

### More Information

Issue was found due to a flaky test.

### Workaround

Create a new git commit and make your release reference the new commit that hopefully doesn't start with 10 digits larger than the maximum int value.

**Comment by tleed5** [comment]
Release Note: Updated the packaging process for git sourced resources to no longer use a version type that will attempt to parse the git commit hash into major/minor/patch versions.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.8172 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.8172 |
| 2024.2+ | _all releases_ |
