### ISSUE TITLE
Polling Response Timeout causes Tentacle to time out, when it doesn't need to.

### ISSUE THREAD

**Issue by LukeButters** [OctopusDeploy/Issues#8578]
## The bug

The **Polling Response Timeout** setting of a machine policy can cause communication to a polling Tentacle to time out.

This happens when the Tentacle has picked up the request from the queue, and is taking a while to start the work. If the **Polling Response Timeout** is reached, then Octopus Server will fail the task being run.

This is not dependant on how long the request takes to run, but rather, how long it takes to start.

But this can happen if a delay occurs while attempting to start the request. For example, if the request has a large file, and it takes a long time for that to be transferred.

## Workarounds

Increasing **Polling Response Timeout** to an appropriately long amount of time will fix the issue.

**Comment by LukeButters** [comment]
Release Note: Removes Polling Response Timeout in favour of depending on ordinary communication timeouts. Doing so allows for large packages to be sent between Octopus Server and Tentacle.

**Comment by LukeButters** [comment]
Available since: 2024.1.8781

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.8781 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.8781 |
| 2024.2+ | _all releases_ |
