### ISSUE TITLE
Unable to update Step Template usage when changing source from Inline Script to Git Repository

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#8585]
### Version

Confirmed in 2024.1.8619, reported in 2024.1.8396, working as expected in 2023.4.8245

### Latest Version

None

### What happened?

Unable to update Step Template usage when changing source from Inline Script to Git Repository

### Reproduction

1. Create a Step Template based on the "Run a Script" step with an "Inline script" source
2. Add the Step Template to a Runbook
3. Change the Step Template script source to "Git repository" with valid information and save
4. Attempt to update from the usage tab
5. Attempt to update from the Runbook step

### Error and Stacktrace

```shell
Git details must be provided when using a Git repository source.
GitDependencies: Only one Git dependency should be specified when using a Git repository source.
```

### More Information

Error from Usage tab:
![image](https://github.com/OctopusDeploy/Issues/assets/63249187/73364165-ea79-4b06-a377-cdd4b0f166b7)

Message in the Runbook step:
![image](https://github.com/OctopusDeploy/Issues/assets/63249187/6a643ebe-ce6d-44fb-8523-3ed2dc40085e)

The message below is what shows after click on `Update and Commit` in the picture above. Pressing `Confirm` loops the same message over and over:
![image](https://github.com/OctopusDeploy/Issues/assets/63249187/fa2f2b8e-1532-4745-b788-b92e4fd2eb7f)

### Workaround

Remove the affected step from the Runbook or database-backed (non-Git) Project process, then re-add the step template.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8432 |
| 2024.1 | _tbc_ |
| 2024.2 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8432 |
| 2024.1 | _tbc_ |
| 2024.2 | 2024.2.3713 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8432 |
| 2024.1 | 2024.1.12210 |
| 2024.2 | 2024.2.3713 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.4 | 2023.4.8432 |
| 2024.1 | 2024.1.12210 |
| 2024.2 | 2024.2.3713 |
| 2024.3+ | _all releases_ |
