### ISSUE TITLE
[Opt-in] Project tenant variables

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#8591]
# The enhancement

## The Need
Variables are not very intuitive in multi-tenancy. This page redesign aims to improve the clarity around how tenant variables work with projects.
[sc-69635]

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9391 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9391 |
| 2024.2+ | _all releases_ |
