### ISSUE TITLE
UI Dropdown menu with Support link issue

### ISSUE THREAD

**Issue by paraicoceallaigh** [OctopusDeploy/Issues#8593]
### Severity

Minor display issue

### Version

2024.1.x

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Based on this PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/20877 the Internal Support link is confusing customers. It mentions it in the sidebar config under Features in the UI but it displays on the drop down User menu instead. Also the wording is confusing as it defaults to Octopus support instead of being left blank if not configured.
<img width="1007" alt="Screenshot 2024-01-30 at 4 34 54 pm" src="https://github.com/OctopusDeploy/Issues/assets/83265184/03eb5bf5-1d2c-498a-9aa9-86d9a2f9f3e5">

### Reproduction

Any 2024.1.x cloud instance under Features--> Sidebar

### More Information

Zendesk ticket: [internal] https://octopus.zendesk.com/agent/tickets/170139

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9484 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9484 |
| 2024.2+ | _all releases_ |
