### ISSUE TITLE
Users struggle to choose the appropriate step

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#8595]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need
During usability sessions we often observe users having a hard time deciding which step is appropriate for the task they're trying to complete.

## Solution
One small part of solving this problem is adding a new "Featured" category, where a few of our most highly recommended steps are presented.

## Screenshots and Mockups
<img width="1361" alt="after-2" src="https://github.com/OctopusDeploy/Issues/assets/5858312/11420e27-b269-40ae-8020-a3b7f9658ad8">

**Comment by iryan2** [comment]
Release Note: A new "Featured" category has been added to the step selection screen, promoting a few "Recommended" steps.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9686 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9686 |
| 2024.2+ | _all releases_ |
