### ISSUE TITLE
Display installed community steps will now be visible in both the Library Step Templates and their original categories

### ISSUE THREAD

**Issue by tanyaastreika** [OctopusDeploy/Issues#8598]
# Prerequisites

- [ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [ ] My team has started working on this issue
- [ ] I have written a descriptive issue title

# The enhancement

## The Need
Currently, when a community step is installed, it is removed from the original category and only appears in the Library Step Templates category. This makes it challenging to locate the step.

## Solution
Installed community steps will now be visible in both the Library Step Templates and their original categories (e.g., Kubernetes, Azure, etc.) to improve visibility.

## Screenshots and Mockups
![image](https://github.com/OctopusDeploy/Issues/assets/149440183/ec673a42-196d-49cd-ad27-09e139a1aaa3)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9533 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9533 |
| 2024.2+ | _all releases_ |
