### ISSUE TITLE
Introduce new `Octopus.Project.Git.BasePath` system variable

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8604]
With the recent support for sourcing (config as code git resources in deployments)[https://octopus.com/blog/git-resources-in-deployments], we need a simple way to reference the directory of the CaC project files.

The `Octopus.Project.Git.BasePath` will be populated for version-controlled projects from the `Git File Storage Directory` project settings
![image](https://github.com/OctopusDeploy/Issues/assets/1830666/4970b9a7-a937-4a76-aad6-fabfcdd6fc1d)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9859 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.9859 |
| 2024.2+ | _all releases_ |
