### ISSUE TITLE
AWS ECS Deployment Target - AWS OIDC Accounts aren't able to be selected 

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#8612]
### Severity

new feature missing functionality, workaround exists

### Version

2024.1.8619

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When selecting the AWS Account for an ECS Deployment Target in Octopus, AWS OIDC accounts don't appear in the account dropdown list. 

### Reproduction

Configure an AWS OIDC Account
Create a new ECS Deployment Target
See AWS OIDC Account missing from dropdown list

### Error and Stacktrace

```shell
N/A
```

### More Information

[Internal Link - Slack](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1707280697252729) 
[Internal Link - Zendesk](https://octopus.zendesk.com/agent/tickets/171231) 

### Workaround

Configure a regular AWS Account for authentication instead

**Comment by byu621** [comment]
Thanks so much!
