### ISSUE TITLE
Project tenant variables - Adding share filters button

### ISSUE THREAD

**Issue by shaun-od** [OctopusDeploy/Issues#8625]
# The enhancement

## The Need

Add a button to enable sharing the currently configured filters for both the Project Templates and Common Templates tabs for the new project tenant variables page.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.10992 |
| 2024.2+ | _all releases_ |
