### ISSUE TITLE
Add new Kubernetes Agent deployment target for simplified deployments to Kubernetes

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#8628]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need

Deploying to Kubernetes is complex with Octopus. We want to simplify it by addressing four friction points.
1. Kubernetes target configuration, especially access to a cluster.
2. Network access. Currently, workers need access to a cluster, so customers might need to allow this on their firewalls.
3. Workers. Customers need workers for Kubernetes deployments. First of all, workers should be configured and managed. But also, they require extra configuration on each Kubernetes step.
4. Tooling. Customers must provide a suitable execution container for their targets (e.g., the correct kubectl version).

## Solution

We're adding a new Kubernetes deployment target — Kubernetes Agent.

- The agent will run on a cluster.
- It will require minimal configuration and will be installed with one Helm command.
- It will work in the poll mode, i.e., initiate a session with Octopus Server from within the cluster.
- The agent will execute deployments and choose the right tool for it — no need for workers or tool configuration.

## Links

https://portal.productboard.com/octopusdeploy/1-octopus-deploy-roadmap/c/84-octopus-agent-for-kubernetes?utm_medium=social&utm_source=portal_share

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.7658 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.7658 |
| 2024.3+ | _all releases_ |
