### ISSUE TITLE
Add support for configuring custom audience on an OpenID Connect (OIDC) Identity

### ISSUE THREAD

**Issue by geofflamrock** [OctopusDeploy/Issues#8648]
The Octopus API supports using OpenID Connect (OIDC) to to exchange an identity token from a OIDC provider (e.g. GitHub actions) for an access token, which can then be used to authenticate to the API for service accounts. Currently we require that the audience in the token being exchanged (the `aud` property) matches the id of the service account being used. 

There are some providers where this isn't possible. For example when using Azure as the provider of identity tokens to send to Octopus (e.g. a custom application running in Azure that wants to use OIDC to connect to Octopus), the audience of the identity token is set by Azure and can't be controlled by the requester, so the exchange fails.

An option to help with this would be to add support for setting a custom audience in the OIDC identity configuration and matching this to `aud` in the identity token during exchange, rather than requiring it to be the id of the service account. This would be an advanced option, the default would remain the id of the service account.

**Comment by cathalmchale** [comment]
Great to see this implemented. We see the Azure provider as particularly important, outside of CICD workflows. E.g. a SaaS app with 2-way integration with Octopus. From a corporate governance point-of-view, an Azure app reg that issues tokens is viewed as something that can be centrally managed, controlled and verified, whereas GitHub (outside of companies that use it as their enterprise solution) would just be a developer managed solution and wouldn't be deemed acceptable.

**Comment by geofflamrock** [comment]
Support for custom audiences for OIDC identities is starting to roll out to Octopus Cloud now and we expect will continue over the next couple of weeks. We'll reply back here with any updates.

**Comment by geofflamrock** [comment]
This was rolled out to Octopus Cloud and self-hosted customers in `2024.2`, unfortunately this issue wasn't closed at the time. I'll close it now, specific version numbers for the release will be added automatically.

**Comment by geofflamrock** [comment]
Release Note: Adds support for using a custom audience when authenticating to the Octopus API using OpenID Connect

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9426 |
| 2024.3 | 2024.3.12371 |
| 2024.4+ | _all releases_ |
