### ISSUE TITLE
AWS accounts with OIDC used on Terraform steps fails to login with error.

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8650]
### Severity

Sev 1

### Version

All

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Using AWS OIDC accounts for terraform throws with `AWS-LOGIN-ERROR-0006: Failed to login via external credentials assigned to the worker.`

### Reproduction

* Configure the Apply a Terraform template step with an AWS account -> 💣

### Error and Stacktrace

```shell
AWS-LOGIN-ERROR-0006: Failed to login via external credentials assigned to the worker.
```

### More Information

This is resolved in https://github.com/OctopusDeploy/Calamari/pull/1226.

### Workaround

NA

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.11671 |
| 2024.2 | 2024.2.156 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.11671 |
| 2024.2 | 2024.2.156 |
| 2024.3+ | _all releases_ |
