### ISSUE TITLE
Always keep "edit" button visible in Tenant Variables page

### ISSUE THREAD

**Issue by denys-octopus** [OctopusDeploy/Issues#8654]
# The enhancement

## The Need
At this moment in "Project"-"Tenant Variables" is really hard to find/see "edit" button for single variable when variable value is very long.
To get to the edit icon, user have to scroll to the bottom, then find the horizontal scroll bar and then find the edit button.

## Solution
Make "edit" button for Tenant Variables is always visible regardless of the length of the variable value by truncating variable value when it is too long

## Screenshots and Mockups
<img width="797" alt="image" src="https://github.com/OctopusDeploy/Issues/assets/102932057/7cc61c87-b762-4c58-b82f-0aa8014ff923">

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.427 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.427 |
| 2024.3+ | _all releases_ |
