### ISSUE TITLE
Guest users can't view CaC projects

### ISSUE THREAD

**Issue by tleed5** [OctopusDeploy/Issues#8664]
### Severity

Low

### Version

Latest 2024.2.534

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When logged in as a guest user attempting to view a CaC project fails with a 403 error, with the error message

"Sorry, but you are signed in as an anonymous guest account, so your changes cannot be persisted. Please contact your Octopus administrator to request a standard user account instead."

### Reproduction

Log in as a guest user and view a CaC project
or try and view this this project in the samples instance
https://samples.octopus.app/app#/Spaces-1/projects/aws-octosubscriber

### Error and Stacktrace

```shell
{
    "errorMessage": "Sorry, but you are signed in as an anonymous guest account, so your changes cannot be persisted. Please contact your Octopus administrator to request a standard user account instead.",
    "fullException": null,
    "errors": [],
    "parsedHelpLinks": null,
    "helpText": null,
    "helpLink": null,
    "details": null
}
```

**Comment by tleed5** [comment]
Release note: Guest users can view config as code projects again

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.1252 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.1252 |
| 2024.3+ | _all releases_ |
