### ISSUE TITLE
Add/edit source code in Terraform steps has a small textarea

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#8673]
### Severity

low

### Version

2024.2.1511

### Latest Version

None

### What happened?

Trying to add or edit inline Terraform code is difficult due to a small textarea.

### Reproduction

* Create a project
* Add a terraform step
* Click Add Source Code button
* See small text area

### More Information

![image](https://github.com/OctopusDeploy/Issues/assets/1571799/093632ce-b11a-48a5-a13f-12f475109bb1)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.2028 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.2028 |
| 2024.3+ | _all releases_ |
