### ISSUE TITLE
Routing to invalid space resolves showing dashboard of default space

### ISSUE THREAD

**Issue by yangguoif** [OctopusDeploy/Issues#8679]
### Severity

Not blocking

### Version

2024.2.1998

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When new routing infrastructure feature flag is enabled, given a user does not have permission to access a space, when the user uses that space ID, or uses an invalid space ID as route param to load the app, then the app presents the dashboard for the default space instead of Space Not Found page.

### Reproduction

1. Ensure the feature flag for new routing infrastructure is enabled
2. Load root page with an invalid space ID or the space ID that you do not have access to, such as `/app#/Spaces-999999`
3. The Dashboard for the default space shows instead of Space Not Found page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.2254 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.2254 |
| 2024.3+ | _all releases_ |
