### ISSUE TITLE
Selecting the appropriate step can be confusing

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#8686]
# The enhancement
The existing Step Selection UI will be overhauled and replaced by a new design.

## The Need
Based on a recent usability study, where users were required to deploy YAML from a forked git repo, we identified some critical problems that make it difficult for users to navigate and select appropriate Kubernetes steps.
- The order in which Kubernetes steps appear, their names, and their descriptions can be misleading.
   - Evidence: 4 of 6 users chose the ‘Deploy Kubernetes Container’ step (the correct choice was ‘Deploy raw Kubernetes YAML’). Users likely perceived it as the logical option because of its favoured placement (second, after Kustomize), name (Deploy Kubernetes Container), and description (Deploy containers to a Kubernetes cluster).
- On smaller screens (14”),  when users select a filter category, the filtered steps are hidden below the fold. Users are confused by the lack of visible change.

## Solution
We'll implement a design that features a familiar side-nav experience for selecting categories of steps. A new "Featured" category will be introduced, to bring attention to our most commonly used steps. Within categories, we'll add the ability to flag certain steps as "Recommended" via a chip in the corner of the card. The Library -> Step Templates screens will also be updated to use the new design. Finally, some buttons in the header of the Process Editor will be hidden until the point in time that they become relevant.

## Screenshots and Mockups

<img width="1617" alt="image" src="https://github.com/OctopusDeploy/Issues/assets/5858312/7fec8b4c-e118-4fbf-ba38-a04362aa3642">

**Comment by iryan2** [comment]
Release Note: Overhauled Step Selection screen to reduce confusion and make it easier for K8s users to choose the appropriate step.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.2873 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.2873 |
| 2024.3+ | _all releases_ |
