### ISSUE TITLE
Lifecycles - Phases Reorder function not working as expected when reorder newly added phases

### ISSUE THREAD

**Issue by HuyPhanNguyen** [OctopusDeploy/Issues#8691]
### Severity

Confuse user when they try to reorder phases.

### Version

2024.2

### Latest Version

I could reproduce the problem in the latest build.

### What happened?

The phases in "Reorder Phases" multiply itself.
![image](https://github.com/OctopusDeploy/Issues/assets/162080607/7b872adc-9ab0-4e90-bf88-93b5ca771548)

Got error screen if try to click "Reorder Phase" again.
![image](https://github.com/OctopusDeploy/Issues/assets/162080607/7bd2296b-c60a-4627-a7eb-a3f3744e8994)

### Reproduction

1. Create a lifecycle with 2 phases (Phase 1, Phase 2) and hit save.
2. Edit that lifecycle and add another 2 phases (Phase 3 or Phase 4) but don't click "Save" button but click "Reorder Phases".
3. Try drag the newly add Phases - Phase 4 over Phase 3 then drag Phase 4 over Phase 2.
4. Result in the "Phase 4" multiple itself.

### Error and Stacktrace

```shell
Error: Cannot have two MultiBackends at the same time.
    at E.setup (MultiBackendImpl.js:122:15)
    at handleRefCountChange (DragDropManagerImpl.js:21:25)
    at Object.d [as dispatch] (redux.js:296:32)
    at e.value (HandlerRegistryImpl.js:92:18)
    at o (registration.js:10:27)
    at O.value (decorateHandler.js:149:32)
    at O.value (decorateHandler.js:134:14)
    at O.value (decorateHandler.js:110:14)
    at cl (react-dom.production.min.js:212:132)
    at Ts (react-dom.production.min.js:255:229)
```

### Workaround
- Save the lifecycles before re-ordering

**Comment by LewisJohnsonOctopus** [comment]
We have tested this in other areas - Looks like the reordering is causing the same fault in runbooks, deployment processes and the reordering of environments.

During our testing we found that saving the runbooks/deployment process before reordering had no affect and the fault persisted. This also now seems to be the case for lifecycles post saving.

**Comment by LewisJohnsonOctopus** [comment]
Another customer experiencing this issue (internal) - https://octopus.zendesk.com/agent/tickets/176337

**Comment by shaunmarx** [comment]
Release Note: Fixed an issue where reordering list items in some situations would be duplicated and potentially crashing the ui

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4331 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4331 |
| 2024.3+ | _all releases_ |
