### ISSUE TITLE
Resizing browser window can reload and unsaved changes lost

### ISSUE THREAD

**Issue by michelle-luana** [OctopusDeploy/Issues#8697]
### Severity

Not blocking but has potential to impact all customers

### Version

2024.1

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Resizing the browser window in/out of the mobile breakpoint causes reload which means progress is lost.
This issue occurs on multiple pages including (but likely not limited to)
- Channels
- Project templates
- Configuration

### Reproduction

https://github.com/OctopusDeploy/Issues/assets/111258903/bd39f5a8-1b78-4b83-ba88-df0ffb1844e1

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.3657 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.3657 |
| 2024.3+ | _all releases_ |
