### ISSUE TITLE
Call to server tasks list bff results in tasks page loading indefinitely

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#8709]
### Severity

Sev-3-low

### Version

2024.1.11885

### Latest Version

None

### What happened?

Querying server tasks list endpoint results in a hanging query. In the front end, this manifests as the task page loading indefinitely. Endpoint: `/bff/tasks/list`

### Reproduction

-

### More Information

https://github.com/OctopusDeploy/OctopusDeploy/blob/df39785b39f97d9b1cdc538e445c553305b647b5/source/Octopus.Core/Features/ServerTasks/Bff/ListServerTasksBffRequestHandler.cs#L70

**Comment by mjhilton** [comment]
Skip: Closing as duplicate of #8549
