### ISSUE TITLE
Artifactory generic feeds cannot be selected on Deploy a Helm Chart step

### ISSUE THREAD

**Issue by geofflamrock** [OctopusDeploy/Issues#8713]
### Severity

Low

### Version

2024.1.5399

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Previously, Artifactory Generic feeds were able to be selected on the Deploy a Helm Chart step. There was a regression introduced when support for sourcing helm charts from git repositories was added where this was removed.

### Reproduction

- Create an Artifactory Generic feed
- Add a Deploy a Helm Chart step to a deployment process

You should be able to select the artifactory generic feed but cannot.

### Workaround

Create a project variable containing the id of feed and bind this to the feed in the deployment process. You can find the id of the feed in the details of the feed.

![image](https://github.com/OctopusDeploy/Issues/assets/2915931/e0fd5c1d-5536-4871-99ff-194ac7a20e4a)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4063 |
| 2024.3+ | _all releases_ |
