### ISSUE TITLE
Client Denied messages are creating noise in logs

### ISSUE THREAD

**Issue by rhysparry** [OctopusDeploy/Issues#8716]
Halibut logs attempts by unauthorized polling Tentacles to connect to the Octopus Server. These logs were mainly added as part of the reliable comms pod work in 2023, and while potentially still useful as a way to detect abandoned polling Tentacles, they are causing extra noise in logs.

This can be useful information, but it isn't usually actionable as the refused client may not be one managed by the owner of the logs.

**Comment by rhysparry** [comment]
Release Note: Log ClientDenied messages at Debug level

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4275 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4275 |
| 2024.3+ | _all releases_ |
