### ISSUE TITLE
"Target Roles" are now named "Target Tags"

### ISSUE THREAD

**Issue by egorpavlikhin** [OctopusDeploy/Issues#8740]
# The enhancement

## The Need
Connecting targets to a new project is essential in most cases, and there are many ways to make a mistake - many of which don’t appear until much later.  

Existing convention of finding targets by roles has lost its relevance over time and created some issues:
* The word “role” is unfamiliar in the context of deployment targets, and is often confused with a permissions setting. 
* It is not clear how roles relate to deployment targets, especially in the world of Kubernetes Clusters where one cluster represents many different things and does not have a particular "role" to serve.
* This comprehension barrier contributes to users sometimes leaving Target Roles blank, even though it's necessary for correct step execution.

Renaming "roles" to "tags" better conveys the meaning behind them and how they relate to deployment targets.

## Solution
We will be gradually renaming "target roles" to "target tags" first in Octopus Server interface and then in docs and other places where "target roles" are mentioned.

**Comment by david-wu-octopus** [comment]
Release Note: "Target Roles" are now named "Target Tags"
