### ISSUE TITLE
Small UI improvement to Server-Side Apply config options

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#8750]
1. We would like to change the casing of the expander title to be consistent with other mentions of Server-Side Apply such as our [docs](https://octopus.com/docs/deployments/kubernetes/server-side-apply) i.e. from "Server-side apply" -> "Server-Side Apply"

2. In addition we'd like to also swap the position of the _New_ feature chip so that the text can line flush on the left. This will be a change affecting all form section expanders going forward. i.e. {chip} {text} -> {text} {chip}

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.6290 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.6290 |
| 2024.3+ | _all releases_ |
