### ISSUE TITLE
latest docker octopusdeploy/tentacle fails on build

### ISSUE THREAD

**Issue by dmeagor** [OctopusDeploy/Issues#8752]
### Severity

no, rolled back to previous version

### Version

8.1.1462

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A few days ago our builds using the octopusdeploy/tentacle started failing.  We tried updaing a couple of times, but that hasn't fixed the issue.

We rolled back to this version octopusdeploy/tentacle:8.1.1435	 and everything is working again with that version.

The container is run in privileged mode

Error below. Seems to be something IP6 related which isn't something we've configured on the docker host (portainer.)  

### Reproduction

https://shout.octopus.app/app#/Spaces-1/projects/shout-angular/deployments/releases/55.0.425/deployments/Deployments-5390?element=0%2FServerTasks-48971_HUZPBEYEX4%2Fd9582d5a70394e1daee09077fc56bab7%2Fe7dbd470067e419faa916691e4b616b1&activeTab=taskLog&line=33

### Error and Stacktrace

```shell
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: failed to add interface veth16c1068 to sandbox: error setting interface "veth16c1068" IPv6 to <nil>: failed to configure ipv6: failed to disable IPv6 forwarding for container's interface eth0: open /proc/sys/net/ipv6/conf/eth0/disable_ipv6: read-only file system: unknown. 
`[33](https://shout.octopus.app/app#/Spaces-1/projects/shout-angular/deployments/releases/55.0.425/deployments/Deployments-5390?element=0%2FServerTasks-48971_HUZPBEYEX4%2Fd9582d5a70394e1daee09077fc56bab7%2Fe7dbd470067e419faa916691e4b616b1&activeTab=taskLog&line=33)
The remote script failed with exit code 125 
[34](https://shout.octopus.app/app#/Spaces-1/projects/shout-angular/deployments/releases/55.0.425/deployments/Deployments-5390?element=0%2FServerTasks-48971_HUZPBEYEX4%2Fd9582d5a70394e1daee09077fc56bab7%2Fe7dbd470067e419faa916691e4b616b1&activeTab=taskLog&line=34)
The action Deploy to CloudFlare worker on a Worker failed
```

### Workaround

rollback to 8.1.1435

**Comment by RobMcCarther** [comment]
Hi @dmeagor Thanks for submitting this issue! As a customer of Octopus Deploy, we'd like to encourage you to reach out to directly via [support@octopus.com](mailto:support@octopus.com) to ensure this gets addressed and investigated appropriately. We'll be closing this issue, but looking forward to assisting you further!
