### ISSUE TITLE
Configuration of OIDC Issuer URL is not reflected in /.well-known/openid-configuration

### ISSUE THREAD

**Issue by kengibous** [OctopusDeploy/Issues#8759]
### Severity

Blocking our teams from using OIDC with AWS

### Version

2024.1.12455

### Latest Version

None

### What happened?

The overridden OIDC Issuer Url should be present when viewing  `.well-known/openid-configuration`

### Reproduction

Set to Settings-> Authentication and specified `https://exp-octopus-oidc.zywave.com` as the OIDC Issuer Url

Navigating to `https://exp-octopus-oidc.zywave.com/.well-known/openid-configuration`

Shows the:
- issuer
- token_endpoint
- jwks_uri

as `exp-octopus.zywave.com` and **not** as `exp-octopus-oidc.zywave.com`

This prevents the ability to add Octopus as an identity provider in AWS.  AWS checks the response from  .well-known/openid-configuration and attempts to get the certificate thumbprint based on the `jwks_uri`  which will fail in this scenarion

### Error and Stacktrace

```shell
When configuring a OpenID Connect provider in AWS 

Provider URL = `https://exp-octopus-oidc.zywave.com/.well-known/openid-configuration`

Clicking `Get Thumbprint`

Results in

`Your request has a problem. Please see the following details.

Please check .well-known/openid-configuration of provider: https://exp-octopus-oidc.zywave.com/.well-known/openid-configuration is valid.
`
```

**Comment by IsaacCalligeros95** [comment]
This issue is resolved in `[2024.1.12719](https://github.com/OctopusDeploy/OctopusDeploy/releases/tag/2024.1.12719)` and [2024.2.7550](https://github.com/OctopusDeploy/OctopusDeploy/releases/tag/2024.2.7550). Thanks for raising it! Please let me know if there are any other issues/blockers you run into using this change.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.12719 |
| 2024.2 | 2024.2.7550 |

**Comment by kengibous** [comment]
this looks great, thank you @IsaacCalligeros95

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.12719 |
| 2024.2 | 2024.2.7550 |
| 2024.3+ | _all releases_ |
