### ISSUE TITLE
Certificate variables from step templates in CaC projects not being picked up within the project step

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#8766]
### Severity

Blocking customers from using certificate variables within their step templates if using Configuration as Code.

### Version

 2024.1.11997, 2024.2.6366

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If using a step template in a project which has certificate variable parameters, the step will pickup the project variables when attempting to select a certificate in the step, this is intended behaviour: 

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/227644cc-6a2c-4c81-ab47-566d50d92c79)

However, as soon as you convert the project to Configuration as Code (CaC) the step template will no longer find the project certificate variable value:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/27b142a0-2c5f-48a3-9391-4bc59d39c142)

If you also include an account variable parameter in the step template, when converting the project to CaC it does find the account variable and will let you select an option in the step, so we know the step is looking at the `variables.ocl` file for the variables. 

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/5dd3e07a-8eb1-4453-b2c8-96eb387de521)

My `variable.ocl` file values:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/103a49a8-44a5-403c-8b51-28b9409eac8c)

This looks to be related specifically to certificate variables via step templates in CaC projects.

If you create a normal `Run a Script` step in a CaC project and `write-host` the certificate variable in the script it will output the correct variable value so this does just seem to be related to step templates.

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/ed2a2d38-7595-41ae-952c-a46b128b9698)

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/3f19ea60-9b16-4767-b4d3-6e1f03ced85a)

### Reproduction

1. Create a step template based on a `Run a Script` step with a variable parameter and an account parameter:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/9a522617-7d9a-44c4-88d2-455fa2fb908b)

2. Create a project and add two project variables, one using an account type, the other a certificate type:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/8a9eef23-734a-4fbf-8773-316049e7c9fa)

3. Add the step template to the project and note you can select an account and certificate for the drop down options within the step.

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/27af2f5a-82c1-4231-9ebd-318301be3a11)

4. Convert that project to configuration as code. Note you can no longer select a variable value for the certificate but you can for an account. Also note in your CaC repo you will have a `variables.ocl` file which will contain the correct variables and values.

5. Now add a basic `Run a Script` step - have that write host the variable ie in my example it would be - 
`Write-Host "$CertTest"`.

6. Disable the previous step we created based on the step template and deploy the release to an environment. Note the correct certificate value will be printed in the deployment which proves Octopus is looking at the `variables.ocl` file for normal steps, just not when using step templates.

### Error and Stacktrace

```shell
N/A
```

### More Information

Initial user who raised the ticket (internal) - https://octopus.zendesk.com/agent/tickets/184239
Internal slack conversation - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1714729870926349

### Workaround

Do not use a step template if you want to reference a certificate variable in a CaC project. You can use the steps provided rather than a step template. Hopefully that will allow you to reference the project variables within your scripts which should be picked up during a deployment, based on my testing.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.12728 |
| 2024.2 | 2024.2.7747 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.12728 |
| 2024.2 | 2024.2.7747 |
| 2024.3+ | _all releases_ |
