### ISSUE TITLE
Convert tab keys to whitespace characters in the Code Editor

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#8773]
A lot of editors these days, such as VSCode, have built-in behaviour to convert tab presses into whitespace.
While just about every language allows whitespaces for indentation, not every allows tabs - the notable one being YAML.

Users of today's code editor in Octopus can't rely on pressing tab to indent their YAML code as it will not conform to the YAML syntax standard. Instead they have to either rely on other tools to convert those tabs to whitespaces (which detracts from the usefulness of having a code editor in Octopus), or they have to indent using the spacebar which is more tedious.

The code editor in Octopus should bind tab key presses to equivalent whitespace spacing instead. This will bring the experience of the code editor more in line with other popular editors.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.7852 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.7852 |
| 2024.3+ | _all releases_ |
