### ISSUE TITLE
Deployments using multiple workers in a single Worker Pool acquire different workers when packages overlap or subsequent steps do not use packages.

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8791]
### Severity

Low, Sev 3

### Version

All

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Our docs spell out how [Worker Selection works](https://octopus.com/blog/workers-explained#worker-selection-caveats). In reality it looks like there's quite a few discrepancies in the actual behaviour and some room for improvement. There's some comments in the RequiredPackageListBuilder that call this out 

            // We want to try to ensure actions which require the same package run on the same worker, to minimize package transfers.
            // This is currently pretty naive. It ignores:
            // - package versions
            // - some packages won't be acquired
            // - it is only using the first package which will be acquired in the case of actions with multiple packages
            // But this isn't functionality we advertise publicly, and it should cover the majority of cases.

The simplest case here is a deployment process with one worker pool, two steps (Run a Script), where the first uses a package and the other is an inline script. Since the packageId is a part of the Worker Lease Key, the second step will require a new worker. We should be able to fine tune this logic. 

These docs also call out Reference Packages and reference package ordering. The WorkerLeaseFactory GetOrLeasePackageWorker only takes a single PackageId, which is then used in the worker lease key. The key is just a concatenation of the WorkerPoolId and the PackageId. From this it appears that Reference packages are completely ignored in this process

Containers and Execution images are another area to look into.

### Reproduction

* Create a Worker Pool with 2 workers.
* Create two steps `Run a Script steps`, the first will use a package reference and the second will be an Inline Script.
* Depending on environment variables the project variables Octopus.Acquire.MaxParallelism and Octopus.Action.MaxParallelism may be required.
* Deploy -> Two workers will be selected
![image](https://github.com/OctopusDeploy/Issues/assets/101079287/9d017f83-87a6-4e7e-af80-7811b750b44d)

### Error and Stacktrace

```shell
NA
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.4888 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.4888 |
| 2024.4+ | _all releases_ |
