### ISSUE TITLE
Account type variable values will use account ID not account name if clicking on 'All Variables' or 'Variable Preview' page and then refreshing that page.

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#8795]
### Severity

Not blocking, a click on the 'Project Variable' page and back resets the account variable names

### Version

2024.2.8486 and 2024.1.12600

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you have project variables of the `Account` type they render fine on the `Project Variable` page with the account name being used for the value of the variable:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/377f73cf-8d61-4df2-8496-0560aa490b99)

However, if you go into another variable page like the `All Variables` page or the `Variable Preview` page and you hit refresh on any one of those two pages, the account names revert to using the Account IDs:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/3e6be8e9-4e3f-46ec-88be-7ae0854afb5c)

The only way you can get them to then revert back to using the account names is to go back to the `Project Variable` page, this then resets the variable values to use the account names again.

This bug is present in both Octopus Cloud 2024.2.8486 and Octopus server 2024.1.12600.

### Reproduction

1. Create a new project with two variables of the `Account` type and ensure you select an account to use for their values.
2. Save the Project Variables and refresh the page, note the variable values are using the account names, which is expected.
3. Click into the `Variable Preview` page, note account names are used, however, on a refresh of the page the account names change to using Account IDs. Refresh the page again and note Account IDs are still being used not names.
4. Click on the `Project variables` page, note the values reset to using account names, click back into the `Variable preview` page and note account names are being used not account ids, until a refresh resets the values to account ids.
5. Follow steps 3 and 4 again but this time with the `All Variables` page and note the same behaviour exists there too.

### Error and Stacktrace

```shell
N/A
```

### More Information

Initial ticket from our engineer who noticed this (internal) - https://octopus.zendesk.com/agent/tickets/186259
Slack conversation (internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1715846731604139

### Workaround

To reset the account variables values back to using Account names not account IDs you will need to click on the Project Variable page, this will then refresh the other variable pages back to using account names.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.295 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.295 |
| 2024.4+ | _all releases_ |
