### ISSUE TITLE
Octopus RestAPI create release unable to include / in package name

### ISSUE THREAD

**Issue by HuyPhanNguyen** [OctopusDeploy/Issues#8818]
### Version

2023.4

### Latest Version

I could reproduce the problem in the latest build

### What happened?

**Issue with Package Names Containing Slashes**
When using tools such as CLI, GitHub Action extensions, Azure DevOps extensions, etc., that rely on RestAPI to create releases, there is an issue with including slashes (/) in package names. For instance, when running the create release command via RestAPI, the package version cannot include a package name with a /.

### Reproduction

* Configure an Octopus Project to deploy a package that includes a / in its name (e.g., a Docker container).
* Run the create release command specifying the version for the package:
```
release create --project 'Project1' --channel 'Default' --package 'octopusdeploy/worker-tools:8.1.1594' --space spaces-1
release create --project 'Project1' --channel 'Default' --package 'Run a Script:octopusdeploy/worker-tools:8.1.1594' --space spaces-1
```

### Error and Stacktrace
The package the use to create release always the latest version not the version specific in the cli command

### Workaround

One workaround is to use the --packageVersion option to set the default package version. However, this approach is not suitable for deployments that reference multiple packages, as it requires manually including the version for each referenced package.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.1246 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.1246 |
| 2024.4+ | _all releases_ |

**Comment by 3guboff** [comment]
The issue is still there @HuyPhanNguyen, [details](https://github.com/OctopusDeploy/cli/issues/282)
