### ISSUE TITLE
Deprecation of Helm V2 support

### ISSUE THREAD

**Issue by MissedTheMark** [OctopusDeploy/Issues#8835]
# Prerequisites

- [X] I have updated the [public deprecation schedule](https://octopus.com/docs/deprecations)
- [X] I have written a descriptive issue title

# Description
Helm V2 support is being disabled in 2024.3.  Warning notifications were added in [2024.1 to inform customers of this](https://octopus.com/docs/deprecations). 

There is extremely low Helm V2 usage, and Helm V2 was deprecated more than 3 years ago.

Related issue: [Deprecation notification of Helm V2 support](https://github.com/OctopusDeploy/Issues/issues/8627).

# Process
- As the notification period of at six months has passed, the functionality has been toggled off, resulting in an error when attempting to use it. Customers can toggle this back on if they still require it.
- After another six months the functionality will be completely removed.

# Migration Guide
There is an official [Helm V2 to V3 Migration guide](https://oc.to/HelmV2ToV3Migration) that details the steps to follow. Once this has been performed, customers will need to update their Helm Upgrade deployment step to change to Helm V3.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.1684 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.1684 |
| 2024.4+ | _all releases_ |
