### ISSUE TITLE
Octopus.Release.CurrentForEnvironment.Number is blank on a deployment after a runbook snapshot/run.

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8858]
### Severity

Low

### Version

All

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When running a deployment after a Runbook Snapshot + run the `Octopus.Release.CurrentForEnvironment.Number` variable is empty.

### Reproduction

* Snapshot a runbook
* Run
* Create a Release
* Deploy
* Octopus.Release.CurrentForEnvironment.Number is empty

### Error and Stacktrace
![333448319-9b4f23ee-9b48-4534-85c2-f600dbab715b](https://github.com/OctopusDeploy/Issues/assets/101079287/6755b869-1a34-4945-be9f-d65d1ca769d1)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.12854 |
| 2024.2 | 2024.2.9206 |
| 2024.3 | 2024.3.3183 |
| 2024.4+ | _all releases_ |
