### ISSUE TITLE
Large Variables page with lots of scopes is slow to add new value 

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#8867]
### Severity

Blocking some customers, no workaround available

### Version

2024.3, possibley 2024.3.164

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When attempting to add a new variable value to an existing variable, in a variable set with hundreds of variables, it can take many seconds for the new variable value row to appear.

### Reproduction

In a variable set with multiple hundreds of variables, press the overflow on a row and select `Add Value`. The new row can take several seconds (or more) to appear and the overflow menu will stay visible during this time.

### Error and Stacktrace

```shell
N/A
```

### More Information

![image](https://github.com/OctopusDeploy/Issues/assets/5336529/de10e837-53ee-41aa-81d3-f457925d8003)

related to #8868

**Comment by benPearce1** [comment]
Export performance trace from Chrome

[Uploading Trace-20240613T172437.json.zip…]()

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9232 |
| 2024.3 | 2024.3.3815 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9232 |
| 2024.3 | 2024.3.3815 |
| 2024.4+ | _all releases_ |
