### ISSUE TITLE
Kubernetes Agent - Execution Containers In Private Repositories - Image Definition Changed 

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#8900]
### Severity

not blocking, workaround exists

### Version

2024.3.5388

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the Kubernetes Agent with Execution Containers that reside in private repositories e.g. not dockerhub, the execution container's image url isn't constructed from the External Feed URL and must be explicitly defined in the Deployment Process.

This requires a change in the deployment process in order to migrate to the Kubernetes Agent so previous releases won't be able to be redeployed successfully. 
 

### Reproduction

1. Configure a Docker External Feed in Octopus
2. Configure Kubernetes API Deployment Target
3. Deploy to Kubernetes API target using a execution container reference format: 
`octopusdeploy/worker-tools:ubuntu.22.04`
4. Migrate to Kubernetes Agent
5. See image pulled from `docker.io` instead of external feed URL - error is image isn't found

### Error and Stacktrace

```shell
PullError - Image not found error shown when image isn't also located in `docker.io`
```

### More Information

[Internal Link - Slack](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1720148688676889)

### Workaround

When using the Kubernetes Agent, use the following execution container reference format which includes the complete URL of the image to pull `docker.packages.octopushq.com/octopusdeploy/worker-tools:ubuntu.22.04`

**Comment by APErebus** [comment]
Release notes: Fixed an issue where execution containers images in custom registries were not being correctly retrieved when using the Kubernetes agent

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.6375 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9302 |
| 2024.3 | 2024.3.6375 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9302 |
| 2024.3 | 2024.3.6375 |
| 2024.4+ | _all releases_ |
