### ISSUE TITLE
Unable to bind variable to repo URL for git sourced scripts

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#8902]
### Severity

One report

### Version

reported in 2024.2.9253 and reproduced in 2024.3.5388

### Latest Version

None

### What happened?

Attempting to bind the repository URL to a variable in a git-sourced script step is unable to evaluate the variable value at release/snapshot creation.

### Reproduction

1. Create a variable holding the value of the URL to your git repo (e.g. `https://github.com/OctopusDeploy/OctopusClients.git`)
2. Configure a script step sourcing the script from a git repository
3. Bind the Repository URL field to the repo variable
4. Attempt to create a release

![image](https://github.com/OctopusDeploy/Issues/assets/20388190/20905bf5-0e8a-40eb-be48-1f44fbbc8f6c)

### Error and Stacktrace

```shell
Unable to retrieve commit details from the provided Git repository at '#{repo}', for branch 'main'. Ensure that the Uri and credentials are correct, and try again.
```

### Workaround

Specify the repo URL directly in the script step instead of binding to a variable holding that same value.

**Comment by SeanLively** [comment]
I've run into this same issue.

**Comment by patrick-smergut-octopus** [comment]
Unable to reproduce in `2024.3.12751` and `2024.4.2718`, but the deployment will fail due to https://github.com/OctopusDeploy/Issues/issues/9033
