### ISSUE TITLE
Auto select JSON or YAML syntax highlighting when editing variable values

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8922]
## Before

YAML
![image](https://github.com/user-attachments/assets/20006928-eeff-4b06-b635-78be4c8109da)

## After

JSON
![image](https://github.com/user-attachments/assets/e2ae63da-cfd8-4ce4-a424-d82af3b10aaf)

YAML
![image](https://github.com/user-attachments/assets/53d16764-7221-4a0b-91c9-418453b92719)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.7486 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.7486 |
| 2024.4+ | _all releases_ |
