### ISSUE TITLE
New projects dashboard rendering feels sluggish

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#8938]
### Severity

Non blocking, workaround available

### Version

2024.3.6174

### Latest Version

The problem does not exist in the latest build

### What happened?

We recently made some changes to our frontend to include some source maps for our emotion styles in the frontend, however, the source maps were base64 encoded and inlined into the styles resulting in slow rendering performance wherever emotion's `cx` function was used to combine classes. This is most obvious on the new projects dashboard shipped as part of the new vertical navigation.

### Reproduction

Navigate to the new projects dashboard with the new vertical navigation enabled. Ensure that a number of projects exist within the space with a number of deployments. Reload the page and notice the noticeable rendering delay. A performance trace will also highlight that a lot of time is being spent in emotion during the render phase.

### Workaround

Revert to old dashboard

**Comment by shaunmarx** [comment]
Release Note: Fixed an issue where the new projects dashboard rendering felt sluggish

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.8034 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.8034 |
| 2024.4+ | _all releases_ |
