### ISSUE TITLE
Inspect target execution context for custom Calamari environment variable

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#8969]
# Background
As part of the upcoming work to [deprecate support for Windows Server 2008](https://octopus.com/docs/deprecations#dropping-capability-for-windows-server-2008-workers-and-targets-in-20251), a short term workaround is being made available for customers relying on this platform to provide their own version of [Calamari](https://octopus.com/docs/octopus-rest-api/calamari).

# Changes
To support this, a new `CalamariDirectoryPath` environment variable will be inspected during task execution that, if present, will be used for the subsequent execution. This will prevent any download of the bundled Calamari in Octopus Server. Improved documentation around this will be made available closer to the capability being made generally available.

![image](https://github.com/user-attachments/assets/1b256dce-7ed0-45b3-af44-32f7bd1051e1)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.10501 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.10501 |
| 2024.4+ | _all releases_ |
