### ISSUE TITLE
Automatic upgrading of Kubernetes agent targets fails when agent has been configured with targetNamespaces

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#8985]
### Version

2024.2 onwards

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Kubernetes agents that have the `scriptPods.serverAccount.targetNamespaces` value set will fail to automatically upgrade due to the script pod not having enough permissions to perform the upgrade.

### Reproduction

1. Install a Kubernetes agent, setting the `scriptPods.serverAccount.targetNamespaces` value to something. Install the agent using a slightly older version (e.g. `1.10.0`)
2. Notice that the initial health-check triggers a upgrade
3. The upgrade fails

### Error and Stacktrace

```shell
Error: UPGRADE FAILED: query: failed to query with labels: secrets is forbidden: User "system:serviceaccount:octopus-agent-namespaced-deployment-target:octopus-agent-scripts" cannot list resource "secrets" in API group "" in the namespace "octopus-agent-namespaced-deployment-target"
```

### Workaround

The agent can be manually updated using a credential that has enough permissions.
The helm command is (in bash)

```base
helm upgrade \
--atomic \
--version "1.*.*" \
--namespace NAMESPACE \
RELEASE_NAME \
oci://registry-1.docker.io/octopusdeploy/kubernetes-agent
```

**Comment by APErebus** [comment]
With the `1.16.0` and `2.2.0` releases of the Kubernetes agent, we now have a `octopus-agent-auto-upgrader` service account that is used for Octopus Server to perform the upgrades.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.11946 |

**Comment by APErebus** [comment]
Release Note: Use well known service account when upgrading Kubernetes agents and workers

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.11946 |
| 2024.4+ | _all releases_ |
