### ISSUE TITLE
Add a reference to the user to successful login audit events

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#9000]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] My team has started working on this issue
- [X] I have written a descriptive issue title

# The enhancement

When a user successfully logs in, an audit event is created with that users username, but there is no reference or link to the user themselves.

Include a link to the user in the login succeeded audit event.

**Comment by YuKitsune** [comment]
Release note: Enhanced the "Login Succeeded" audit event by including a reference to the user.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12615 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12615 |
| 2024.4+ | _all releases_ |
