### ISSUE TITLE
New Vertical Navigation UI design

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#9002]
# The enhancement

## The Need
Our new navigation UI makes it easier to find what you're looking for in Octopus in a handful of different ways. It's also a faster experience for our scale customers. And for everyone, we've ensured modern dark and light themes that are more considerate of accessibility.

## Solution

* Vertical navigation exposes the features you use to manage deployment projects
* Favorited projects appear in the navigation, simply by clicking the star ⭐️
* We've positioned global search more centrally

## Screenshots and Mockups

<img width="666" alt="newui5" src="https://github.com/user-attachments/assets/079dedbf-ab19-4e1b-b6f5-99e756f23e7d">

## Links

[Read about what's new in our blog post](https://octopus.com/blog/whats-new-navigation-ui).

Also see our earlier post: [Redesigning the navigation in Octopus](https://octopus.com/blog/redesigning-octopus-navigation).

**Comment by MarkSiedle** [comment]
Release Note: Introducing the new Vertical Navigation UI

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.1592 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12728 |
| 2024.4 | 2024.4.1592 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12728 |
| 2024.4 | 2024.4.1592 |
| 2025.1+ | _all releases_ |
