### ISSUE TITLE
Step Templates sourced from Git can cause a deployment to fail when deploying in parallel

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#9009]
### Severity

Medium - No practical workaround

### Version

Confirmed in 2023.4.8245

### Latest Version

None

### What happened?

Step Templates sourced from Git can cause a deployment to fail when deploying to multiple targets. It appears that Octopus is unnecessarily attempting to create a package/artifact from Git multiplied by the number of targets, all using the exact same file path and name.

Octopus should only create one artifact since this will be the same for all targets of the same deployment.

### Reproduction

On a self-hosted installation of Octopus Server on Windows:

- Add a Step Template from Git to a Project process or Runbook process
- Deploy to multiple environments
- If the deployment doesn't fail, retry a few times

### Error and Stacktrace

```shell
The process cannot access the file 'C:\Octopus\Packages\git-resources\b56df92d813bf9ab7988d6f8e92d2dbe8481294a@O7e24c0b27f526b3e21cf0ee16b651d05145acc73@da39a3ee5e6b4b0d3255bfef95601890afd80709.zip' because it is being used by another process.
```

### More Information

Same issue as https://github.com/OctopusDeploy/Issues/issues/8573 but deploying multiple projects or to multiple environments at the same time.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.8548 |
| 2024.4+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9450 |
| 2024.3 | _tbc_ |
| 2024.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9450 |
| 2024.3 | 2024.3.8548 |
| 2024.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9450 |
| 2024.3 | 2024.3.8548 |
| 2024.4 | 2024.4.704 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9450 |
| 2024.3 | 2024.3.8548 |
| 2024.4 | 2024.4.704 |
| 2025.1+ | _all releases_ |
