### ISSUE TITLE
Runbook Publishing Error - Visual Only - The file '.octopus/runbooks/Runbooks-xx.ocl' on the 'main' branch does not exist in the Git repository

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#9036]
### Severity

not blocking, visual only

### Version

2024.4.1937

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When publishing a runbook in a project with CaC enabled, that sources it's script from Git an error is shown but the runbook is still able to be published ok

### Reproduction

Configure a CaC project
Add a Runbook using a Script Step that sources the script from Git
Publish Runbook
See Error

### Error and Stacktrace

```shell
The file '.octopus/runbooks/Runbooks-xx.ocl' on the 'main' branch does not exist in the Git repository
```

### More Information

![Screenshot 2024-09-24 at 14 24 31](https://github.com/user-attachments/assets/24b64400-cfb0-436c-be56-04adce7a72c7)

### Workaround

N/A - Error is only visual

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.3169 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.3169 |
| 2025.1+ | _all releases_ |
