### ISSUE TITLE
Allow New-OctopusArtifact cmdlet to upload file with different name

### ISSUE THREAD

**Issue by crossetj** [OctopusDeploy/Issues#904]
Instead of writing:

``` PowerShell
# Copy the hosts file and give the copy a machine-specific name
$machineName = [Environment]::MachineName
$copyHostsTo = ".\$machineName-hosts.txt"

Copy-Item "C:\Windows\System32\drivers\etc\hosts" $copyHostsTo

# Tell Octopus about the artifact
New-OctopusArtifact $copyHostsTo
```

It would be nice to say:

``` PowerShell
$machineName = [Environment]::MachineName
New-OctopusArtifact "C:\Windows\System32\drivers\etc\hosts" -ArtifactName "$machineName-hosts.txt"
```

**Comment by tugberkugurlu** [comment]
I am looking for a way to rename the `New-OctopusArtifact` output as mentioned by @crossetj. Is this released? if not, do we have a workaround for this?

**Comment by yannisgu** [comment]
@tugberkugurlu 
You  can use this function instead of New-OctopusArtifact:

    function New-OctopusArtifactEx([string]$path, [string]$Filename) {
        if(-not $Filename) {
            $Filename = [System.IO.Path]::GetFileName($path)
        }
        
        $Filename = Encode-ServiceMessageValue($Filename)
        $path = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($path)
        $path = [System.IO.Path]::GetFullPath($path)
        $path = Encode-ServiceMessageValue($path)
        Write-Output "##octopus[createArtifact path='$path' originalFilename='$Filename']"
    }
