### ISSUE TITLE
Add Support for running IIS and Windows Certificate steps using NetCore build of Calamari

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#9042]
As part of the shift towards the deprecation of Windows Server 2008 and running all Octopus Server workloads on .netcore, there are some capabilities that currently are only available in the full framework tooling. 

This change, while it should result in no impact to the end user, will result in these workloads using newer compiled tools.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.3558 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.3558 |
| 2025.1+ | _all releases_ |
