### ISSUE TITLE
Octopus UI makes requests to experiences.octopus.com when self hosting

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#9053]
### Severity

Non blocking

### Version

2024.3.12731

### Latest Version

Not applicable

### What happened?

When self hosting octopus server requests are sent to experiences.octopus.com which in most cases would be cross domain requests and may contain some sensitive information such as a user's email address. This functionality is in the process of being developed, but was inadvertently exposed to self hosted installations as well. 

The request being sent off to our experiences endpoint as currently implemented would never succeed and as such is not applicable to self hosted customers at this point in time. We will provide a mechanism to enable/disable this for self hosted customers, however, what we currently have should not be available anywhere other than cloud.

### Reproduction

Run a version of server after 2024.3.12731 inclusive, but before 2024.3.12820. Before logging into the server, open the network panel. After logging in, notice requests being sent off to `experiences.octopus.com` which fail. 

### Workaround

No workaround, requests will be sent but always fail authentication.

**Comment by shaunmarx** [comment]
Release Note: Removed in-app messaging capabilities that had been inadvertently released to self-hosted customers

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12820 |
| 2024.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12820 |
| 2024.4 | 2024.4.3890 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12820 |
| 2024.4 | 2024.4.3890 |
| 2025.1+ | _all releases_ |
