### ISSUE TITLE
Deleting Releases from retention tasks gets progressively slower

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#9061]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your feature request, making sure it's handled appropriately._**

# Prerequisites

- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [X] My team has started working on this issue
- [X] I have written a descriptive issue title

# Problem

When the retention task executes, the process of deleting a release has gotten noticeably slower, and progressively increases in duration as the retention task runs.

**Comment by YuKitsune** [comment]
Release note: Improve performance when deleting releases during the retention task.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12848 |
| 2024.4 | 2024.4.4265 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12848 |
| 2024.4 | 2024.4.4665 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12887 |
| 2024.4 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12887 |
| 2024.4 | 2024.4.5314 |
| 2025.1+ | _all releases_ |
