### ISSUE TITLE
Error exporting project due to unidentifiable PackageID/FeedID

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#9064]
### Severity

Sev 3 (Low)

### Version

All

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When attempting to export a project, some customers are met with an error message stating the Value cannot be null, similar to

### Reproduction

* Create a deployment process and add a step template step
* On the step template include a variable that will be provided by the project
* On the project set this variable to a Json value 

### Error and Stacktrace

```shell
Value cannot be null. (Parameter 'value') System.ArgumentNullException: Value cannot be null. (Parameter 'value') at XXXXXXs.Value[T,U](IEnumerable1 value)
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.4395 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.4395 |
| 2025.1+ | _all releases_ |
