### ISSUE TITLE
Azure Cloud Services has been officially retired by Microsoft

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#9066]
# Prerequisites

- [x] I have updated the [public deprecation schedule](https://octopus.com/docs/deprecations)
- [x] I have written a descriptive issue title

# Description

Azure has official retired [Azure Cloud Services (classic)](https://azure.microsoft.com/en-us/updates/cloud-services-retirement-announcement/) as of 31st August 2024. As a result, these deployment steps will no longer work.

# Migration Guide

The recommended migration path outlined by Azure is to make use of the separate [Azure Cloud Services (extended support)](https://learn.microsoft.com/en-us/azure/cloud-services-extended-support/overview) product. There are no plans to support this feature in Octopus.

**Comment by rain-on** [comment]
Release Notes: Azure Cloud Service has been retired by Microsoft. Executing an associated step will result in a failed deployment.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.4603 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.4603 |
| 2025.1+ | _all releases_ |
