### ISSUE TITLE
Guidance within Git credentials field is misleading

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#9076]
### Version

2024.4.5398

### Latest Version

I could reproduce the problem in the latest build

### What happened?

A Callout was recently added to the Git credentials field in the process editor, which warned users that they'd usually have to provide credentials even when referencing a public repo. The root cause of this surprising behaviour was a bug that has [since been fixed](https://github.com/OctopusDeploy/Issues/issues/9075), making the guidance misleading.

### Reproduction

- Add a "Deploy Kubernetes YAML" step
- Scroll to the "Authentication" field
- Click the "Anonymous" option
- See Callout with misleading message: "In most cases you'll need to provide credentials, even when the repository is public."

**Comment by iryan2** [comment]
Release notes: Remove misleading message telling users that anonymous authentication for public git repos probably won't work.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.5422 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.5422 |
| 2025.1+ | _all releases_ |
