### ISSUE TITLE
Markdown Not Rendering Correctly for 'Descriptions' in Library Sets included in Projects

### ISSUE THREAD

**Issue by RobMcCarther** [OctopusDeploy/Issues#9079]
### Severity

Low

### Version

2024.4.4834

### Latest Version

I could reproduce the problem in the latest build

### What happened?

 In both the **Tenant Variables > Common Templates** and **Variable Sets > Include Variable Sets** sections of a project, the markdown formatting for the 'Descriptions'  of Variable sets are not being rendered correctly.  Instead of displaying the formatted text, the markdown syntax is shown as plain text.
![image](https://github.com/user-attachments/assets/351edc15-a4a1-445b-ad91-570c2bd1b289)
![image](https://github.com/user-attachments/assets/73dec7cf-7eb7-4bb5-8462-2e4fd2e937ba)

### Reproduction

1. Create or Edit existing Variable Set
2. Add or edit a description using markdown formatting (e.g., bold, italics, bullet points).
3. Save the changes and view the description.
4. Open up a Project
5. Navigate to **Tenant Variables > Common Templates** or **Variable Sets > Include Variable Sets**.
6. Include the Variable Set that has markdown formatting
7. Note that the formatting is not rendered correctly

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6141 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6141 |
| 2025.1+ | _all releases_ |
