### ISSUE TITLE
Clicking "Environments" item in Project Status Bar should re-open project's Guided Setup dialog

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#9087]
## Before

https://github.com/user-attachments/assets/e4d38aab-143a-4298-9bd9-c784dd82f470

## After

https://github.com/user-attachments/assets/9f48fe50-c3d0-4381-b4ff-b47fdc9ed3e7

**Comment by iryan2** [comment]
Release Notes: Clicking "Environments" item in Project Status Bar will re-open project's Guided Setup dialog

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.5924 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.5924 |
| 2025.1+ | _all releases_ |
