### ISSUE TITLE
Project onboarding has poor support for Runbook-only projects

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#9089]
# Background

When a Runbook-only project is the only project in a given Space, the "Continue" project setup button is presented, even if the runbook has been successfully run.

# Results

A runbook run is treated the same as a deployment, and the "Continue" button will not be presented for Runbook-only projects where the runbook has been successfully run.

## Before
<img width="1284" alt="Screenshot 2024-10-24 at 2 54 38 PM" src="https://github.com/user-attachments/assets/cfba4f74-b973-4d8e-8e32-98a875b4d670">

It was pretty awful getting back to your Runbook in this scenario - when there were no other projects you'd have to navigate through several irrelevant screens:

https://github.com/user-attachments/assets/1848ed4b-9a8e-4b33-8775-c934c4cac68d

## After
<img width="1288" alt="Screenshot 2024-10-24 at 2 49 56 PM" src="https://github.com/user-attachments/assets/79bb1ce7-e665-4ace-a782-da51d3964cef">

**Comment by iryan2** [comment]
Release notes: Runbook-only projects with a successful Run will no longer show as semi-setup projects on the Projects Dashboard

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6044 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6044 |
| 2025.1+ | _all releases_ |
