### ISSUE TITLE
Wrong active item in Project Status bar when refreshing Process Editor

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#9090]
### Version

Earliest tried was 2024.4.4698

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a new project has yet to complete onboarding, and there's no environments in the space, the Guided Setup dialog will resume when the user refreshes the page on the Process Editor. When the dialog appears, the active item should be "Environments", with "Deployment Process" as the next item, but "Deployment Process" is the active item.

### Reproduction

- Create project in a Space that has no environments
- During guided setup, select k8s and yaml options
- Skip environment creation, land on the process editor
- Refresh the page, see guided setup dialog appear with incorrect status item

<img width="1380" alt="Screenshot 2024-10-30 at 3 52 57 PM" src="https://github.com/user-attachments/assets/749cd34d-446b-4544-aeb3-413df4799628">

**Comment by iryan2** [comment]
Release notes: Prevent wrong Project Status item being active after refreshing page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6220 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6220 |
| 2025.1+ | _all releases_ |
