### ISSUE TITLE
Reinstate sticky page headers

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#9105]
# The enhancement

## The Need
Page headers used to be sticky, which made it easy to save a deployment process when the page was long from having so many fields on screen, for example.

## Solution

Make page headers sticky again.

## Screenshots and Mockups
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/c5ca2621-1f28-44cb-85c9-bd959b97493b">

**Comment by iryan2** [comment]
Release notes: Page headers are now sticky, allowing users to perform actions (e.g. Save Process) without scrolling to the top of the page.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6545 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6545 |
| 2025.1+ | _all releases_ |
