### ISSUE TITLE
OpenTelemetry Provider for Audit Stream

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#9112]
An OpenTelemetry provider should be added to the [Audit Stream](https://octopus.com/docs/security/users-and-teams/auditing/audit-stream) feature.

This will allow customers to stream to many more destinations.

![image](https://github.com/user-attachments/assets/ef1dbe07-19b0-47e6-91b2-60b49759938b)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6705 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.6705 |
| 2025.1+ | _all releases_ |
