### ISSUE TITLE
Accented characters get removed from file names on deployment

### ISSUE THREAD

**Issue by SeanStanway-Octopus** [OctopusDeploy/Issues#9119]
### Severity

1 customer reported, no workaround at this time

### Version

2024.3.12899, not present in 2024.4.6143

### Latest Version

None

### What happened?

When deploying a package that has a file inside with an accented character in the name (é, á, ó, etc.) that character gets removed completely when that package is deployed, leaving gaps in the file names. 

Unable to recreate this in the current cloud instance version

### Reproduction

1. Create a zip package with a single file in it with an accented character (i.e. `fráncé.txt`). 
2. Upload the zip to the built-in package feed
3. Use this package in a "deploy a package" step to any target
4. After deployment, check the deployed files on the target, observe that the file name has spaces where the accented characters were (e.g. `fr nc .txt`)

### More Information

![image](https://github.com/user-attachments/assets/83873cd7-1a75-4c92-873f-17b11bfc668f)

### Workaround

No workaround known currently

**Comment by rain-on** [comment]
Release Note: Zip file extraction, on Windows 2008 assumes UTF-8 filenames within the archive - ensuring accent characters are supported.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12957 |
| 2024.4 | _tbc_ |
| 2025.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12957 |
| 2024.4 | _tbc_ |
| 2025.1 | 2025.1.1248 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12957 |
| 2024.4 | 2024.4.6939 |
| 2025.1 | 2025.1.1248 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12957 |
| 2024.4 | 2024.4.6939 |
| 2025.1 | 2025.1.1248 |
| 2025.2+ | _all releases_ |
