### ISSUE TITLE
Validation errors in Process Editor aren't visible until user scrolls to top of page

### ISSUE THREAD

**Issue by iryan2** [OctopusDeploy/Issues#9133]
### Version

2025.1.799

### Latest Version

None

### What happened?

Recently the page headers for the Process Editor were made sticky, which meant the user could click the "Save" button when they were scrolled far down the page. However, the validation errors appear at the top of the page, which means the users isn't alerted to problems with their deployment process until they either scroll to the top of the page or attempt to create a release.

### Reproduction

Add a Run a Script step to a deployment process. Scroll down, leave the inline script field blank and click save. There are now validation errors at the top of the page but no indication on screen that anything has gone wrong.

### Workaround

Scroll to top of page to see errors

**Comment by iryan2** [comment]
Release notes: Fixed bug where validation errors weren't visible because the Process Editor didn't scroll to top of page after clicking save.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.1548 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.1548 |
| 2025.2+ | _all releases_ |
