### ISSUE TITLE
Default to Hosted Ubuntu worker pool when Bash scripting language is selected

### ISSUE THREAD

**Issue by egorpavlikhin** [OctopusDeploy/Issues#9135]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] My team has started working on this issue
- [x] I have written a descriptive issue title

# The enhancement

## The Need

Bash scripts cannot run on Windows workers, yet they are presented as the default choice. We are changing the default selection such that when Bash is selected Ubuntu worker pool is selected automatically. Further, if Hosted Windows is selected manually a callout is presented warning the user that the selection might not work at deployment time.

## Screenshots and Mockups

![image](https://github.com/user-attachments/assets/f1ffc26a-d8fd-4840-a624-78984f5d4bad)

**Comment by egorpavlikhin** [comment]
Release note: Default to Hosted Ubuntu worker pool when Bash scripting language is selected in Run a Script step

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.912 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.912 |
| 2025.2+ | _all releases_ |
