### ISSUE TITLE
Deployment duration resets to 0 when it exceeds a day of run time

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#9136]
On the task log screen, when a deployment runs for over 24 hours, once the deployment hit 23:59:59 the duration ticks back over to 0.

**Comment by tothegills** [comment]
Release note: Durations on the task screen will show correctly when the duration exceeds 24 hours

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.1162 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.1162 |
| 2025.2+ | _all releases_ |
