### ISSUE TITLE
Upgrading from Octopus versions prior to v2018.3 to v2024.3 or newer causes Octopus Server not to start

### ISSUE THREAD

**Issue by andrewabest** [OctopusDeploy/Issues#9145]
### Severity

Blocking one customer so far on upgrade.

### Version

Exists on upgrade paths between v2018.3 and older, and v2024.3 and newer.

### Latest Version

None

### What happened?

When upgrading from v2018.3 to v2024.3, the upgrade completed successfully, however the Octopus Server would not start after upgrading.

### Reproduction

Upgrade from a version v2018.3 or older to v2024.3 or newer.

### Error and Stacktrace

```shell
2024-11-26 10:14:21.3565   8768      5 FATAL  An exception was thrown while activating Octopus.Server.OctopusServerEngine -> λ:Octopus.Core.Infrastructure.Hosting.IOctopusHostedService[] -> Octopus.Core.Features.Features.FeatureToggleHeartbeat -> Octopus.Core.Features.Features.HeartbeatFeatureToggle -> Octopus.Core.Infrastructure.FeatureToggles.OpenFeatureFeatureToggleSource -> Octopus.Core.WebPortal.WebConfigurationMemento.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Octopus.Server.OctopusServerEngine -> λ:Octopus.Core.Infrastructure.Hosting.IOctopusHostedService[] -> Octopus.Core.Features.Features.FeatureToggleHeartbeat -> Octopus.Core.Features.Features.HeartbeatFeatureToggle -> Octopus.Core.Infrastructure.FeatureToggles.OpenFeatureFeatureToggleSource -> Octopus.Core.WebPortal.WebConfigurationMemento.
```

### More Information

Internal link: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1732582696556129

Customer ticket: [private link]: https://octopus.zendesk.com/agent/tickets/214212

### Workaround

Upgrade to the latest LTS version once available, or contact support for a SQL script that will recover instances in this state.

**Comment by andrewabest** [comment]
Release note: Fixes issue where an upgraded Octopus instance could refuse to start if the origin version was 2018.3 or older, and the target version was 2024.3 or newer.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12972 |
| 2024.4 | _tbc_ |
| 2025.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12972 |
| 2024.4 | 2024.4.6945 |
| 2025.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12972 |
| 2024.4 | 2024.4.6945 |
| 2025.1 | 2025.1.1897 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.12972 |
| 2024.4 | 2024.4.6945 |
| 2025.1 | 2025.1.1897 |
| 2025.2+ | _all releases_ |
