### ISSUE TITLE
Performance regression when adding machines

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#9147]
### Version

Introduced in 2025.1.192

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The time to add machines has increased significantly. Adding many machines in bulk has increased from ~15 minutes to ~35 minutes.

### Reproduction

Add >10,000 machines to Octopus Server.

**Comment by YuKitsune** [comment]
Release note: Fixed a performance regression with various machine related endpoints.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.2033 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.2033 |
| 2025.2+ | _all releases_ |
