### ISSUE TITLE
The Octopus Helm step tries to retrieve the deployed manifest even when step verification is disabled

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#9160]
### Severity

Low Severity

### Version

Earliest in 2025.1.1579

### Latest Version

None

## Background
#9137 introduced support for Kubernetes Object Status to the Octopus Helm step. This feature is enabled by turning on the option for Step Verification
<img width="618" alt="Screenshot 2024-12-10 at 1 20 22 pm" src="https://github.com/user-attachments/assets/805634b0-2b88-4f11-8347-21e64c0e129a">

When this is enabled, the step will attempt to retrieve the manifest (via `helm get manifest`) after it has been applied to the cluster. If this process fails (e.g. manifest retrieval times out or is invalid), then the step will fail as expected.

## Problem
The issue is that the code currently attempts to retrieve the applied manifest even with the Step Verification option turned off. This should not happen as we do not want a step failing due to step verification if this option is not explicitly enabled.

### Reproduction

1. Create an Octopus Helm step and disable Step Verification.
2. Configure the step to deploy an 'empty' Helm chart. Empty as in a Helm chart that contains no YAML templates and hence would return an empty manifest when calling `helm get manifest`. The reason this works for reproducing the error is because empty Helm charts are currently **not considered** a valid Helm deployment.
3. Create a release and deploy with the step.

Check your cluster. The deployed Helm release should be there which means the deployment should be considered successful since Step Verification is disabled. However, the deployment fails because the retrieved manifest is invalid.

<img width="1229" alt="Screenshot 2024-12-10 at 1 35 39 pm" src="https://github.com/user-attachments/assets/816ccc82-6079-4614-9f6a-5416342be608">

### Error and Stacktrace

```shell
Failed to retrieve helm manifest in a timely manner
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.3480 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.3480 |
| 2025.2+ | _all releases_ |
