### ISSUE TITLE
Update System.IO.Packaging from 8.0.0 to 8.0.1

### ISSUE THREAD

**Issue by nick-roscarel-octo** [OctopusDeploy/Issues#9167]
# The enhancement

## The Need

Octopus Server currently depends on `System.IO.Packaging` v8.0.0.

## Solution

Upgrade the version of `System.IO.Packaging` Octopus Server depends on to v8.0.1.

## Links

https://github.com/dotnet/core/releases/tag/v8.0.1

**Comment by nick-roscarel-octo** [comment]
Release Note: Upgraded `System.IO.Packaging` from 8.0.0 to 8.0.1

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13001 |
| 2024.4 | _tbc_ |
| 2025.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13001 |
| 2024.4 | 2024.4.7017 |
| 2025.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13001 |
| 2024.4 | 2024.4.7017 |
| 2025.1 | 2025.1.5054 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13001 |
| 2024.4 | 2024.4.7017 |
| 2025.1 | 2025.1.5054 |
| 2025.2+ | _all releases_ |
