### ISSUE TITLE
Regression in Helm Upgrade step: Quoted Argument Handling

### ISSUE THREAD

**Issue by kevjt** [OctopusDeploy/Issues#9168]
### Severity

Breaking deployments for some customers

### Version

Earliest in 2025.1.1579

## Background
#9137 introduced support for Kubernetes Object Status (KOS) to the Octopus Helm step. This change also revised the way the Helm step was being executed in Calamari. Instead of [using a Bash](https://github.com/OctopusDeploy/Calamari/blob/main/source/Calamari/Kubernetes/Conventions/HelmUpgradeConvention.cs#L50) script to construct and run the Helm command, the Helm command is now being [invoked directly](https://github.com/OctopusDeploy/Calamari/blob/main/source/Calamari/Kubernetes/Conventions/Helm/HelmUpgradeExecutor.cs#L45) with the command arguments.

## Problem
Some customers are experiencing deployment failures when using the KOS for Helm feature due to the way Bash handles parameter expansion. When Bash parameters are used in Helm step arguments, Bash removes quotes around strings. However, with the KOS for Helm feature, arguments are passed directly to Helm as raw strings, requiring quotes to be preserved. This mismatch can lead to incorrect command execution and deployment failures.

### Reproduction

1. Create an Octopus Helm upgrade step and configure it to deploy a chart
2. Inside the "Additional Parameters" option, add a Helm upgrade option to set a value on the Helm release. 
Enclose the value in quotes e.g. `--set myhelmvalue='something'`
3. Deploy the Helm chart with the KOS for Helm feature disabled, and notice that the quotes are not there.
4. Deploy the Helm chart again with the KOS for Helm feature enabled. The quotes around the Helm value are now being preserved.

#### Immediate
Disable the KOS for Helm feature for the time being. 

#### Short-term
A feature-toggled workaround will be rolled out to allow affected customers to continue using Bash arguments with the new Helm command. 

### Long-term
The workaround will be deprecated in **Octopus version 2025.3** (6 months from now) as our long-term goal is to move towards direct Helm command execution, which offers enhanced security.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.3917 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.3917 |
| 2025.2+ | _all releases_ |
