### ISSUE TITLE
Document how to deploy ClickOnce applications

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#968]
http://help.octopusdeploy.com/discussions/questions/2434

**Comment by camp-007** [comment]
I'm still trying to find some clear documentation or recommendations for deploying ClickOnce apps.  Since this issue was closed a long time ago, is there something out there that I'm just not finding?  Can we add a link to this thread for the docs on ClickOnce?

**Comment by Stockholmsnovis** [comment]
I am with @camp-007 here. Currently looking into using my build server to create the package (msbuild => build project => Publish) and then use https://github.com/rasmus/CiPsLib Powershell scripts on the Octopus Tentacle to resign the package for each environment. Still a bit unclear how I would use variable substitution? Maybe rename myapplication.exe.config.deploy to .config, let OD do its magic and then in the end, rename and resign?
