### ISSUE TITLE
Windows Service: Startup Change password checkbox always unchecked

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#992]
I have a deployment step that installs a service and sets a user and password. When checking the "change password" checkbox it shows me the textbox where I can set the password. After saving the step and reopening the edit screen the checkbox is unchecked, but when checking it again it's actually readonly?

Source: http://help.octopusdeploy.com/discussions/problems/21701

**Comment by jdkang** [comment]
What was the rationale for WONTFIX? I'm still having this issue in 3.2.21

**Comment by michaelnoonan** [comment]
Hi @jdkang. We are doing some work to make these sensitive/password fields more robust across the board which we are hoping to ship as part of `Octopus 3.3.0`. I think the best steps you can take at this point would be to raise a [support request](https://octopus.com/support) - this way we can investigate the specific issue you're experiencing and make sure we address that as part of the same work.

Hope that helps!
